export default {
  'courses.courses': 'Курси',
  'courses.overview': 'Огляд курсів',
  'course.create': 'Створити новий курс',
  'course.reading.title': 'Назва завдання для читання',
  'course.question.add': 'Додати питання',
  'course.add.courseElement': 'Додати новий елемент курсу',
  'course.lessons.newMessage': 'Створюйте та організовуйте свої уроки для ефективного викладання',
  'course.reading.new': 'Завдання для читання',
  'course.reading.newMessage': 'Створюйте та організовуйте завдання з читання для своїх учнів',
  'course.writing.new': 'Завдання для написання',
  'course.writing.newMessage': 'Швидко налаштовуйте та розподіляйте завдання на написання текстів',
  'course.question.text': 'Ваше питання тут',
  'course.question.type': 'Будь ласка, оберіть тип запитання',
  'course.question.delete': 'Видалити питання',
  'course.type': 'Виберіть тип курсу',
  'course.visibility': 'Виберіть параметр видимості',
  'course.title': 'Заголовок',
  'course.description': 'Описання',
  'course.cover': 'Обкладинка',
  'course.start': 'Ваш курс починається о',
  'course.ends': 'Ваш курс закінчується о',
  'course.curriculum': 'Навчальний план',
  'course.members': 'Студенти та вчителі',
  'course.assignments': 'Завдання',
  'course.question.deleteWhole': 'Видалити увесь питання',
  'course.question.yes': 'Так',
  'course.question.no': 'Ні',
  'course.lesson.title': 'Назва уроку',
  'course.lesson.add.universe': 'Додати історію/Всесвіт',
  'course.lesson.add.link': 'Додати зовнішнє посилання',
  'course.status': 'Статус',
  'course.active': 'Діяльність',
  'course.active.message': 'Активний',
  'course.inactive': 'Неактивний',
  'course.module.edit': 'Редагувати назву модуля',
  'course.upload.resource': 'Завантажити файловий ресурс',
  'course.question.answer': 'Додати відповідь',
  'course.question.open': 'Відкрите питання',
  'course.question.close': 'Питання закрите.',
  'course.question.multiple': 'Питання з декількома варіантами відповідей',
  'course.about': 'Про цей курс',
  'course.lesson.new': 'Створіть новий урок',
  'course.lesson.type': 'Тип уроку',
  'course.lesson.inPerson': 'Особисто',
  'course.lesson.preRecorded': 'Попередній запис',
  'course.lesson.online': 'Онлайн',
  'course.lesson.text': 'Тільки текст',
  'course.lesson.content': 'Зміст уроку',
  'course.lesson.description': 'Публічний опис',
  'course.add.module': 'Додати новий модуль',
  'course.add.story': 'Додати історію',
  'course.remove.story': 'Видалити історію',
  'course.dateOfPublish': 'Дата публікації',
  'course.lesson.meetInPerson': 'Зустрітися особисто',
  'course.curriculum.edit': 'Редагувати навчальний план',
  'course.stories.own': 'Ваші власні історії',
  'course.stories.organization': 'Історії організацій',
  'course.stories.public': 'Публічні історії',
  'course.publish.at': 'Я хочу, щоб цей курс був опублікований на сайті:',
  'course.edit.curriculum': 'Редагувати навчальний план',
  'course.assignment': 'Завдання',
  'course.lesson.removeLink': 'Видалити посилання',
  'course.remove.user': 'Вилучити користувача',
  'course.add.user': 'Додати користувача',
  'course.edit.role': 'Роль редактора',
  'course.assignment.description': 'Опис завдання',
  'course.internal': 'Внутрішній',
  'course.free': 'Безкоштовно',
  'course.sale': 'Розпродаж',
};
