export default {
    'reader.storyEnd.heading': 'Кінець',
    'reader.storyEnd.description': 'Ви дійшли до кінця історії.',
    'reader.externalSale.heading': 'Ще в дорозі',
    'reader.externalSale.description': 'Ця історія недоступна на Літературному Всесвіті, але можливо, ви знайдете її у іншому місці.',
    'reader.storyTBC.heading': 'Далі буде...',
    'reader.storyTBC.description': 'Наразі це вся історія, але пригоди продовжаться в майбутньому, слідкуйте за новинами!',
    'chapter.translation.notYetDescription': 'Чекатимемо на вас!',
    'reader.externalShopping.heading': 'Придбати {storyName} у крамничках:',
    'chapter.next': 'Наступний розділ',
    'chapter.previous': 'Попередній розділ',
    'chapter.comment': 'Коментарі до цього розділу',
    'reader.language': 'Мова:',
    'reader.fullscreen.enter': 'Увімкнути повноекранний режим',
    'reader.fullscreen.exit': 'Вимкнути повноекранний режим',
    'reader.details.universe': 'Детальніше про цей всесвіт',
    'reader.details.story': 'Детальніше про цю історію',
    'reader.darkmode': 'Увімкнути темний режим',
    'reader.flowtext': 'Змінити розмір тексту',
    'reader.menu.optionsAria': 'Меню параметрів зчитувача',
    'reader.accessibility': 'Перемикання доступності',
    'chapter.translation.notYet': 'Цей розділ ще не перекладено.',
    'externalShopping.buyLink.amazon': 'Придбати на Amazon',
    'externalShopping.buyLink.other': 'Придбати на {storeName}',
    'externalShopping.buyLink.bookshop': 'Придбати на Bookshop.org',
    'reader.accessibility.aria': 'Налаштування доступності',
    'reader.accessibility.toggleDyslexic': 'Перемикання шрифту для людей з дислексією',
    'reader.accessibility.toggleParagraphStripes': 'Перемикання зміни фону абзаців',
    'reader.accessibility.toggleParagraphHighlight': 'Увімкнути підсвічування вибраних абзаців',
    'reader.accessibility.toggleRules': 'Перемикання допоміжної лінійки',
    'reader.nextRelease.scheduled': 'Наступний розділ вийде {nextReleaseAt, date} о {nextReleaseAt, time}!',
    'reader.storyContinues': 'Історія триває...',
    'reader.storyOnHiatus': 'Наразі автор(ка) бере перерву у роботі над цією історією. Повертайтеся через місяць-два.',
    'reader.storyCancelled': 'На жаль, це все. Роботу над цією історією припинено, тож навряд чи буде щось нове.',
    'reader.storyCancelled.heading': 'Припинено'
};