export default {
    'writer.menu.optionsAria': 'Меню параметрів редактора',
    'writer.menu.saveOptionsAria': 'Параметри збереження',
    'writer.undo': 'Скасувати',
    'writer.redo': 'Повторити',
    'writer.ul': 'Неупорядкований список',
    'writer.ol': 'Упорядкований список',
    'writer.blockquote': 'Цитата',
    'writer.link': 'Вставити посилання',
    'writer.image': 'Вставити зображення',
    'writer.bold': 'Зробити жирним виділене',
    'writer.underline': 'Підкреслити виділене',
    'writer.italic': 'Надати виділеному нахил',
    'writer.wordCount': '{characters, number} символів, {words, number} слів',
    'writer.characterCount': '{characters, number} символів',
    'finder.details': 'деталі',
    'finder.remove': 'Видалити з\'єднання',
    'finder.connect': 'Підключити виділене до статті в енциклопедії',
    'writer.aside.ariaLabel': 'Меню параметрів довідки',
    'writer.nothingToSave': 'Немає чого зберігати',
    'writer.link.placeholder': 'Введіть URL-адресу',
    'writer.link.error.empty': 'URL-адреса не може бути порожньою',
    'writer.link.error.invalid': 'Будь ласка, введіть дійсну URL-адресу',
    'writer.fontFamily': 'Сімейство шрифтів',
    'writer.fontFamily.select': 'Виберіть шрифт',
    'writer.publish.publishAria': 'Варіанти публікації',
    'writer.publish.scheduleExplained': 'Ви можете опублікувати відразу або запланувати розділ на пізніший час.',
    'writer.publish.schedule': 'Встановити дату та час публікації',
    'writer.publish.previousChapterPublished': 'Попередній розділ було опубліковано {publishDate, date, short} о {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'Попередній розділ заплановано для публікації {publishDate, date, short} о {publishDate, time}',
    'writer.publish.alreadyPublished': 'Цей розділ вже був опублікований {publishedAt, date, short}. Нові версії будуть опубліковані відразу.',
    'writer.publish.betaReader': 'Бета',
    'writer.publish.public': 'Опублікувати',
    'writer.publish.now': 'Опублікуйте зараз',
    'writer.publish.schedulePrevious': 'Вам потрібно опублікувати або запланувати публікацію попереднього розділу, перш ніж ви зможете опублікувати цей.',
    'writer.publish.earlyAccess.title': 'Ранній доступ для шанувальників',
    'writer.publish.earlyAccess.groupLine': '{days} на кілька днів раніше: {tiers} - вболівальники отримують доступ на {date, date, short} за адресою {date, time}'
};