export default {
    'writer.menu.optionsAria': 'Меню параметрів редактора',
    'writer.menu.saveOptionsAria': 'Параметри збереження',
    'writer.undo': 'Скасувати',
    'writer.redo': 'Повторити',
    'writer.ul': 'Неупорядкований список',
    'writer.ol': 'Упорядкований список',
    'writer.blockquote': 'Цитата',
    'writer.link': 'Вставити посилання',
    'writer.image': 'Вставити зображення',
    'writer.bold': 'Зробити жирним виділене',
    'writer.underline': 'Підкреслити виділене',
    'writer.italic': 'Надати виділеному нахил',
    'writer.wordcount': '{characters, number} символів, {words, number} слів',
    'finder.details': 'деталі',
    'finder.remove': 'видалити зв\'язок',
    'finder.connect': 'Підключити виділене до статті в енциклопедії',
    'writer.aside.ariaLabel': 'Меню параметрів довідки',
    'writer.nothingToSave': 'Немає чого зберігати',
    'writer.publish.publishAria': 'Варіанти публікації',
    'writer.publish.scheduleExplained': 'Ви можете опублікувати відразу або запланувати розділ на пізніший час.',
    'writer.publish.schedule': 'Встановити дату та час публікації',
    'writer.publish.previousChapterPublished': 'Попередній розділ було опубліковано {publishDate, date, short} о {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'Попередній розділ заплановано для публікації {publishDate, date, short} о {publishDate, time}',
    'writer.publish.alreadyPublished': 'Цей розділ вже був опублікований {publishedAt, date, short}. Нові версії будуть опубліковані відразу.',
    'writer.publish.betaReader': 'Бета',
    'writer.publish.public': 'Опублікувати'
};