export default {
    'sharing.title': 'Delen',
    'sharing.button': 'Delenknop',
    'sharing.share': 'Delen met...',
    'sharing.feedback': 'Missen we een plek waar je naar wilt delen? Laat het ons weten!',
    'sharing.copy': 'Kopiëren',
    'sharing.email': 'E-mail',
    'sharing.sms': 'SMS',
    'sharing.messenger': 'Facebook Messenger',
    'sharing.whatsapp': 'WhatsApp',
    'sharing.twitter': 'X/Twitter',
    'sharing.linkedin': 'LinkedIn',
    'sharing.telegram': 'Telegram',
    'sharing.facebook': 'Facebook',
    'sharing.line': 'LINE',
    'sharing.mastodonSocial': 'Mastodon Social',
    'sharing.mastodonJapan': 'Mastodon Japan',
    'sharing.gab': 'Gab',
    'sharing.pinterest': 'Pinterest',
    'sharing.gettr': 'Gettr',
    'sharing.minds': 'Minds.com',
    'sharing.instagram': 'Instagram'
};