export default {
    'stats.age.groups': 'Leeftijdsgroepen',
    'stats.age.range': 'Leeftijdsbereik',
    'stats.age.to12': 'Tot 12',
    'stats.age.12to17': '12 tot 17',
    'stats.age.18to20': '18 tot 20',
    'stats.age.21to29': '21 tot 29',
    'stats.age.30to39': '30 tot 39',
    'stats.age.40to49': '40 tot 49',
    'stats.age.50to64': '50 tot 64',
    'stats.age.65to84': '64 tot 84',
    'stats.age.above85': 'Boven 85',
    'stats.section.aggregate': 'Geaggregeerde statistieken',
    'stats.section.chapter': 'Statistieken per hoofdstuk',
    'stats.readers.title': 'Over uw lezers',
    'stats.gender.title': 'Geslacht',
    'stats.view.table': 'Tabelweergave',
    'stats.view.pie': 'Taartdiagramweergave',
    'stats.view.bar': 'Staafdiagramweergave',
    'stats.view.chart': 'Grafiekweergave',
    'stats.table.total': 'Totaal',
    'stats.timeline.title': 'Tijdlijn',
    'stats.timeline.dateStart': 'Statistieken beginnen op',
    'stats.timeline.dateEnd': 'Statistieken eindigen op',
    'stats.likeCount': 'Aantal likes',
    'stats.language.title': 'Gesproken taal',
    'stats.chapter.visitorsAndViews': 'Totaal aantal bezoekers en weergaven per hoofdstuk',
    'stats.chapter.wordCount': 'Aantal woorden per hoofdstuk',
    'stats.chapter.chartTooltipViews': 'Hoofdstuk {chapter, number}: {views, number} weergaven',
    'stats.chapter.chartTooltipVisitors': 'Hoofdstuk {chapter, number}: {visitors, number} unieke bezoekers',
    'stats.chapter.chartTooltipWordCount': 'Hoofdstuk {chapter, number}: {wordCount, number} woorden',
    'stats.totalHits': 'Totaal aantal weergaven',
    'stats.totalVisitors': 'Totaal aantal unieke bezoekers',
    'stats.totalWords': 'Totaal aantal woorden',
    'stats.totalEntries': 'Encyclopedie-artikelen',
    'stats.blogPage': 'Pagina',
    'stats.blog.typeSelectionAria': 'Type selectie',
    'stats.blog.pages': 'Pagina\'s',
    'stats.blog.posts': 'Berichten',
    'stats.unknown': 'Onbekend',
    'stats.noData': 'Geen gegevens beschikbaar op dit moment.',
    // Author overall statistics
    'workshop.theWay.overallStats.noData': 'Er zijn nog geen statistieken beschikbaar. Begin met het publiceren van uw werk om uw statistieken te zien!',
    'workshop.theWay.overallStats.content': 'Uw inhoud',
    'workshop.theWay.overallStats.stories': 'Verhalen',
    'workshop.theWay.overallStats.universes': 'Universums',
    'workshop.theWay.overallStats.chapters': 'Hoofdstukken',
    'workshop.theWay.overallStats.wordCount': 'Geschreven woorden',
    'workshop.theWay.overallStats.encyclopediaEntries': 'Encyclopedie Inzendingen',
    'workshop.theWay.overallStats.publishingStreak': 'Week publiceren',
    'workshop.theWay.overallStats.monthlyPublicationStreak': 'Maand Publicatiereeks',
    'workshop.theWay.overallStats.audience': 'Uw publiek',
    'workshop.theWay.overallStats.fans': 'Ventilatoren',
    'workshop.theWay.overallStats.followers': 'Volgers',
    'workshop.theWay.overallStats.uniqueReaders': 'Unieke lezers',
    'workshop.theWay.overallStats.storyViews': 'Verhaal Bekeken',
    'workshop.theWay.overallStats.universeViews': 'Universumgezichten',
    'workshop.theWay.overallStats.readingTime': 'Leestijd (min)',
    'workshop.theWay.overallStats.demographics': 'Lezersdemografie',
    'workshop.theWay.overallStats.topCountry': 'Top land',
    'workshop.theWay.overallStats.topAgeGroup': 'Top Leeftijdsgroep',
    'workshop.theWay.overallStats.genres': 'Uw genres'
};