export default {
    'writer.menu.optionsAria': 'Opties menu van de editor',
    'writer.menu.saveOptionsAria': 'Opslaan opties',
    'writer.undo': 'Ongedaan maken',
    'writer.redo': 'Opnieuw uitvoeren',
    'writer.ul': 'Ongeordende lijst',
    'writer.ol': 'Geordende lijst',
    'writer.blockquote': 'Citaat',
    'writer.link': 'Een link invoegen',
    'writer.image': 'Een afbeelding invoegen',
    'writer.bold': 'De selectie vetgedrukt maken',
    'writer.underline': 'De selectie onderstrepen',
    'writer.italic': 'De selectie benadrukken',
    'writer.wordCount': '{characters, number} tekens, {words, number} woorden',
    'writer.characterCount': '{characters, number} tekens',
    'finder.details': 'details',
    'finder.remove': 'Verwijder de verbinding',
    'finder.connect': 'Verbind selectie met encyclopedie-item',
    'writer.aside.ariaLabel': 'Help opties menu',
    'writer.nothingToSave': 'Niets om op te slaan',
    'writer.link.placeholder': 'Een URL invoeren',
    'writer.link.error.empty': 'URL kan niet leeg zijn',
    'writer.link.error.invalid': 'Voer een geldige URL in',
    'writer.fontFamily': 'Lettertype familie',
    'writer.fontFamily.select': 'Lettertype selecteren',
    'writer.publish.publishAria': 'Publicatieopties',
    'writer.publish.scheduleExplained': 'Je kunt het hoofdstuk direct publiceren of plannen om het op een later tijdstip beschikbaar te maken.',
    'writer.publish.schedule': 'Stel de publicatiedatum en -tijd in',
    'writer.publish.previousChapterPublished': 'Het vorige hoofdstuk is gepubliceerd op {publishDate, date, short} om {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'Het vorige hoofdstuk is gepland om gepubliceerd te worden op {publishDate, date, short} om {publishDate, time}',
    'writer.publish.alreadyPublished': 'Dit hoofdstuk is al gepubliceerd op {publishedAt, date, short}. Nieuwe versies worden direct gepubliceerd.',
    'writer.publish.betaReader': 'Bèta',
    'writer.publish.public': 'Publiceren',
    'writer.publish.now': 'Nu publiceren',
    'writer.publish.schedulePrevious': 'U moet het vorige hoofdstuk publiceren of de publicatie ervan plannen voordat u dit hoofdstuk kunt publiceren.'
};