/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'Literary Universe',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe is an all-in-one creative and publishing platform for grand story universes.',
    'site.keywords': 'creative writing, scifi, sci-fi, fantasy, writing, publishing, story, stories, universe, web novel, webnovel',
    'site.logoAlt': 'लिटररी यूनिवर्स लोगो',
    mobileMenu: 'मोबाइल मेनू',
    'common.signin': 'लॉगिन',
    'common.signup': 'रजिस्टर करा',
    'common.signout': 'लॉगआउट',
    'common.dashboard': 'डॅशबोर्ड',
    'common.discovery': 'शोध',
    'common.library': 'लायब्ररी',
    'common.library.own': 'तुमची लायब्ररी',
    'common.workshop': 'कार्यशाळा',
    'common.pm': 'संदेश',
    'common.settings': 'सेटिंग्ज',
    'common.options': 'पर्याय',
    'common.profile': 'प्रोफाइल',
    'common.blog': 'ब्लॉग',
    'common.blogs': 'ब्लॉग्स',
    'common.about': 'आमच्याविषयी',
    'common.accessdenied': 'प्रवेश नाकारला',
    'common.accessdenied.msg': 'तुम्हाला येथे जाण्याची परवानगी दिली नाही. जर तुम्हाला येथे प्रवेश असावा लागला तर कृपया मालकांशी संपर्क साधा आणि त्यांना सेटिंग्ज चाचण्यासाठी एकदा तपासावा.',
    'common.loading': 'लोड होत आहे...',
    'common.add': 'जोडा',
    'common.save': 'सेव्ह करा',
    'common.email': 'ई-मेल',
    'common.soon': 'शीघ्र येत आहे...',
    'common.search': 'शोधा',
    'common.search.do': 'शोधा',
    'common.searching': 'शोधत आहे...',
    'common.report': 'अहवाल',
    'common.user': 'वापरकर्ता',
    'common.users': 'वापरकर्ते',
    'common.showmore': 'अधिक पहा',
    'common.futurefeature.title': 'भविष्यातील सुविधा',
    'common.futurefeature.text': 'आपल्याला खूप दुखी आहे, पण ही सुविधा आता उपलब्ध नाही. आम्ही कडकपूरते ती लवकरच उपलब्ध करण्याच्या आठवणीत काम करीत आहोत.',
    'common.nothingfound': 'काहीही सापडलं नाही',
    'common.explore': 'अन्वेषण करा',
    'common.by': 'द्वारा {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'स्क्रॅचपॅड',
    'common.scratchpad.own': 'तुमचं स्क्रॅचपॅड',
    'common.news': 'बातम्या',
    'common.encyclopedia': 'विज्ञानकोश',
    'common.art': 'Art',
    'common.story': 'कथा',
    'common.stories': 'कथांचं संग्रह',
    'common.universe': 'ब्रह्मांड',
    'common.universes': 'ब्रह्मांडे',
    'common.collaborator': 'सहयोगी',
    'common.collaborators': 'सहयोगी',
    'common.translator': 'भाषांतरक',
    'common.translators': 'भाषांतरक',
    'common.betareader': 'बेटा वाचक',
    'common.betareaders': 'बेटा वाचक',
    'common.post': 'पोस्ट',
    'common.statistics': 'आकडेवारी',
    'common.lang.select': 'भाषा निवडा',
    'common.submit': 'सबमिट करा',
    'common.close': 'बंद करा',
    'common.comment': 'टिप्पणी',
    'common.comments': 'टिप्पण्या',
    404: 'पृष्ठ आढळलं नाही',
    'search.users': 'वापरकर्त्यांच्या शोधा',
    'search.user': 'वापरकर्ता शोधा',
    'common.help': 'मदत',
    'common.or': 'किंवा',
    'common.account.create': 'खाते तयार करा',
    'signup.username': 'वापरकर्तानाव',
    'signup.email': 'तुमचा ईमेल',
    'signup.password.label': 'तुमचा संकेतशब्द',
    'signup.password.repeat': 'तुमचा संकेतशब्द पुन्हा टाका',
    'common.password': 'संकेतशब्द',
    'signin.password.forgot': 'संकेतशब्द विसरलात का?',
    'dashboard.whatsnew': 'नविन आहे काय',
    'dashboard.blog': 'तुमचं ब्लॉग',
    'common.footer.tagline': 'कॉम्प्लेक्स यूनिव्हर्सेसला लिहाणे आणि वाचणे सोपे.',
    'common.footer.plans': 'योजना आणि मूल्यनिर्धारण',
    'common.legal.tos': 'सेवा शर्ती',
    'common.legal.community': 'समुदाय मार्गदर्शक',
    'common.legal.privacy': 'गोपनीयता धोरण',
    'common.legal.copyright': 'कॉपीराइट समजूती',
    'common.legal.versionDisplay': `{type, select,
    tos {Terms of Service}
    community {Community Guidelines}
    privacy {Privacy Policy}
    copyright {Copyright Agreement}
    publishingAgreement {Publishing Agreement}
    other {Agreement}
  } Version {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'A new version ({newVersion}) of this document will come into effect on {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} सर्व हक्क राखील, सर्व मजकूर त्यांच्या संबंधित लेखकांच्या मालकीची आहे.',
    'premium.only.title': 'प्राधान्य दर्जाची उंची कमी आहे',
    'premium.only.msg': 'माफ करा, आपला प्राधान्य दर्जा या सुविधेस जोडण्यासाठी किंवा प्रवेश करण्यासाठी पुरेसे उच्च नाही.',
    'premium.only.join': 'आम्ही सर्वांसाठी विविध योजना आणणार आहोत तात्पुरत्या वाचकांसाठी अधिक मिळवण्यासाठी वाचनसामग्रीचा उपयोग करा.',
    'premium.only.link': 'तपासा!',
    'universe.visit': 'यूनिव्हर्स पृष्ठ भेटा',
    'common.fanmanager': 'Fan manager',
    'common.fanarts': 'Fan arts',
    'common.fanfiction': 'Fan fiction',
    'common.fansettings': 'Fan settings',
    'story.chapter': 'अध्याय',
    'story.chapters': 'अध्याय',
    'story.genre': 'शैली',
    'story.genres': 'शैली',
    'story.read': 'वाचा',
    'story.lastUpdate': 'शेवटचे अद्यावत केले गेले आहे {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'शेवटचे अद्यावत केले गेले आहे {date, date, medium}.',
    'story.comments.for': '{story} {chapter}साठी टिप्पण्या.',
    'story.cover.alt': '{story}साठी कवर चित्र',
    'story.note.fanfiction': 'नोंद: ही कथा {universe} यूनिव्हर्सवरील एक फॅन फिक्शन आहे.',
    copyrights: 'कॉपीराइट',
    'common.challenges': 'साहसिक',
    // for beta only
    'beta.notice': 'लिटररी युनिवर्स बीटा मध्ये आपले स्वागत आहे. ही एक सार्वजनिक पूर्वावलोकन आहे आणि त्यामुळे अद्याप अॅपचा काम चालू आहे. हे म्हणजे की आपण अजिबात त्रुटी आणि अपूर्ण वैशिष्ट्ये अपेक्षा करू शकता. जर आपल्याला कोणतीही त्रुटी मिळाली किंवा काम करत नसल्यास तर कृपया आम्हाला सांगा आणि कृपया थोडं धीर धरा जेणेकरून आम्ही सर्व काही सुचवू शकणार आहोत.',
    'beta.thanks': 'आपल्या सहभागाबद्दल धन्यवाद!',
    'scratchpad.about': 'आपले नोट आणि विचार साइटवर कोठेही प्राप्त',
    'common.feedback': 'प्रतिसाद',
    'common.createdOn': 'Created on {date, date, long}',
    'common.createdOn.title': 'Created on',
    // account types
    admin: 'व्यवस्थापक',
    'common.saved': 'साठवले गेले!',
    'common.saving': 'साठवत आहे...',
    'common.friends': 'मित्र',
    'lang.orig': 'मूळ भाषा',
    'lang.orig.plus': 'मूळ भाषा - {language}',
    buy: 'खरेदी करा',
    confirm: 'पुष्टी करा',
    cancel: 'रद्द करा',
    processing: 'प्रोसेसिंग...',
    'common.noData': 'No data',
    'error.title': 'एक त्रुटी आली आहे. आपल्याला अस्वीकार करण्याबद्दल आपल्याला खेद आहे.',
    'common.offlineStatus': 'आपण वर्तमानपत्र ऑफलाइन आहात.',
    male: 'पुरुष',
    female: 'महिला',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: 'कृपया निवडा',
    'common.statusFailed': 'सर्व्हरला कनेक्ट करण्यात त्रुटी आली.',
    'common.statusConnecting': 'सर्व्हरला कनेक्ट करण्याचा प्रयत्न करीत आहे... ({count, number})',
    'slug.checking': 'तपासत आहे...',
    'slug.failed': 'हा पत्ता आधीच अस्तित्वात आहे.',
    'slug.success': 'हा पत्ता उपलब्ध आहे!',
    'notVerified.msg': `Your account {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    } is not verified.`,
    'notVerified.verify': `Please verify your {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    }.`,
    unknown: 'अज्ञात',
    'common.legal.guidelines': 'समुदाय मार्गदर्शक',
    'errorLoading.title': 'पृष्ठ लोड करताना त्रुटी',
    'errorLoading.explained': 'पृष्ठ लोड होत असताना एक त्रुटी आली आहे. आपल्याला असुविधेसाठी खेद आहे. कृपया पुन्हा पृष्ठाची पहा. जर समस्या सुरू असेल तर कृपया आपल्याला सापडलेली का जाणीव करा.',
    'errorLoading.retry': 'पुन्हा प्रयत्न करा!',
    'errorLoading.takingLong': 'हे वेळ लागत आहे...',
    'common.title': 'शीर्षक',
    'common.timelines': 'टाइमलाइन्स',
    'common.legal.gdpr': 'जीडीपीआर',
    'common.legal.gdpr.long': 'सामान्य डेटा संरक्षण प्राधान्य',
    'editor.placeholder.link': 'URL प्रविष्ट करा...',
    'editor.placeholder.connection': 'विज्ञानकोश प्रविष्टीसाठी शोधा...',
    'editor.saved.beta': 'बीटा वाचकांसाठी नवीन संशोधन तयार केला गेला आहे!',
    'editor.saved.public': 'नवीन संस्करण प्रकाशित!',
    goodbyeForever: 'आपल्याला जात बघून आनंद झालं. तो काहीतरी आम्ही केलं का? कृपया आपल्याला सांगा जर ते असा असेल. किंवा कायमचं आपल्या भविष्यातील प्रयत्नांमध्ये आम्ही आपल्याला सध्याच्या विचारात आहोत. दीर्घकालिक आणि आशीर्वाद द्या आणि विकास करा!',
    'goodbyeForever.feedback': 'आम्हाला काय चांगलं करू शकतं हे सांगा',
    'common.edit': 'संपादित करा',
    'common.publish': 'प्रकाशित करा',
    'common.publishAt': 'प्रकाशन तारीख आणि वेळ',
    'a11y.user.menu': 'युजर मेनू',
    'a11y.navigation': 'Navigation',
    'dashboard.profile': 'आपली प्रोफाइल',
    'profile.website': 'माझी वैयक्तिक वेबसाइट',
    'story.notes.concept': 'कॉन्सेप्ट',
    'story.notes.settings': 'कथा सेटिंग',
    'story.notes.theme': 'थीम',
    'story.notes.impact': 'आवश्यक प्रभाव',
    'story.notes.outcome': 'परिणाम',
    'story.notes.audience': 'लक्षित वाचकांसाठी',
    'story.notes.pitch': 'पिच',
    'story.notes.notes': 'टीका',
    'story.authorsNotes': 'Author\'s notes',
    'common.members': 'सदस्य',
    'common.language': 'भाषा',
    next: 'पुढे',
    previous: 'Previous',
    'common.legal.tos.short': 'अटी',
    'common.legal.privacy.short': 'गोपनीयता',
    'premium.increaseLimit': 'तुमची मर्यादा वाढवण्यासाठी अपग्रेड करा.',
    'common.sharing': 'सामायिक करणे',
    'story.isbn': 'ISBN',
    'common.name': 'नाव',
    'common.remove': 'काढा',
    'common.time.milliseconds': 'मिलीसेकंद',
    'common.time.seconds': 'सेकंद',
    'common.time.minutes': 'मिनिटे',
    'common.time.hours': 'तास',
    'common.time.days': 'दिवस',
    'common.time.weeks': 'आठवडे',
    'common.time.months': 'महिने',
    'common.time.years': 'वर्षे',
    'common.monetization': 'Monetization',
    'common.tab.monetizationOptions': 'Monetization options',
    'common.pagination': 'Pagination',
    'common.forum': 'Forum',
    'common.2faCode': '2FA code',
    'common.2faCodeIntro': 'Please enter your one time code generated by your authenticator application.',
    'common.2faCodeAria': '2FA code entry form',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Default language',
    'signin.web3.signMessage': 'Please confirm that you want to enter Literary Universe with your wallet as authentication method. Code: {code}',
    'common.web3.confirmationCode': 'Confirmation code: {code}',
    'common.roadmap': 'Roadmap',
    'common.luStatsIFrameOptOut': 'Literary Universe statistics opt-out',
    'common.image': 'Image',
    'common.home': 'Home',
    'common.administration': 'Administration',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'Groups',
    'common.upload': 'Upload',
    'common.backToDashboard': 'Back to dashboard',
    'common.accept': 'Accept',
    'common.reject': 'Reject',
    'common.events': 'Events',
    'common.event': 'Event',
    'common.all': 'All',
    'common.social': 'Social',
    'common.discordCommunity': 'Discord Community',
    'common.account': 'Account',
    'common.notifications': 'Notifications',
    'common.byDeclaration': 'By:',
    'common.done': 'Done',
    recommended: 'Recommended',
    'select.typeToCreate': 'Start typing to create an item',
    'select.noSearchResults': 'No results for “{search}”',
    'select.removeOption': 'Remove {option}',
    create: 'Create',
    'banner.support': 'Literary Universe is supported by users like you! Please consider subscribing to one of our subscription plans to stay independent and make Literary Universe event better!',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Don\'t have an account?',
    'common.haveAccountQuestion': 'Already have an account?',
    'common.socialLogin': 'Login with other services',
    'common.viewMore': 'View more',
    'common.overview': 'Overview',
    'common.loggingOut': 'Logging out',
    'common.thankYou': 'Thank you!',
    'common.seeYouAgain': 'See you again!',
    'email.hello': 'Hello {username},',
    'common.back': 'Back',
    'console.stop': 'रुका!',
    'console.explain': 'हा एक डेव्हलपर्ससाठी वापरण्यात येणारा ब्राउझर फिचर आहे. जर कोणी आपल्याला काहीतरी कॉपी-पेस्ट करता येते असा आपल्याला सांगितलं असेल की लिटररी युनिव्हर्सचे एक फिचर चालू करण्यासाठी किंवा कोणाच्या खात्याला "हॅक" करण्यासाठी असेल तर तो फसवणूक आहे आणि त्यांनी तुमच्या लिटररी युनिव्हर्सच्या खात्याकडे प्रवेश मिळवणार आहे.'
}    /* eslint-enable max-len */;