export default {
    'feedback.home': 'मदत केंद्र',
    'feedback.bugs': 'त्रुटी',
    'feedback.bugs.desc': 'Did you encounter an error or something else that is wrong or out of place? Let us know here!',
    'feedback.features': 'विचारे आणि प्रास्तावे',
    'feedback.features.desc': 'नवीन वैशिष्ट्यांचे विचार आहेत किंवा साइटला चांगले कसे करावे? आम्हाला सांगा!',
    'feedback.help': 'मदत आणि सूचना',
    'feedback.help.desc': 'तुम्हाला _____कसं करायचं आहे? उत्तरे येथे शोधण्यासाठी येथे जा.',
    'feedback.desc': 'आमच्या मदत आणि समाधान केंद्रात आपले स्वागत आहे!',
    'feedback.faq': 'अक्कलमार्गदर्शन',
    'feedback.faq.desc': 'वापरकर्त्यांनी अक्कलविषयक विचारांची अधिक प्रश्ने',
    'feedback.open': 'उघडा',
    'feedback.closed': 'बंद',
    'feedback.accepted': 'स्वीकृत',
    'feedback.inprogress': 'प्रगतीशील',
    'feedback.completed': 'पूर्ण',
    'feedback.fixed': 'ठरवलेले',
    'feedback.new.bugs': 'नवीन त्रुटी अहवाल करा',
    'feedback.new.features': 'नवीन वैशिष्ट्य सुचवा',
    'feedback.lang.nosupport': 'तुमची सध्याची भाषा अभिप्रायासाठी समर्थित नाही, कृपया इंग्रजीत लिहा. धन्यवाद!',
    'feedback.new.thanks': 'Thank you for the notice! We will look into it shortly.',
    'feedback.comment.title': 'टिप्पणी',
    'feedback.comment.desc': 'आमच्या अभिप्रायांना पाठवा',
    'feedback.comment.legend': 'तुमचा अभिप्राय - कोणतेही गोष्ट आम्हाला सांगा',
    'feedback.comment.success': 'तुमच्या अभिप्रायाबद्दल धन्यवाद!',
    'feedback.comment.label': 'तुमची टिप्पणी',
    'feedback.copyrightReport.title': 'कॉपीराइट उल्लंघन',
    'feedback.copyrightReport.desc': 'कॉपीराइट उल्लंघन अहवाल द्या',
    'feedback.report.noUser': 'अहवाल दाखल करण्यासाठी आपल्याला साइन इन केलेला असणे आवश्यक आहे.',
    'feedback.voting.totalVoters': 'वापरकर्ते मतपेढले आहेत: {voted, number}',
    'feedback.voting.upvote': 'अपवोट',
    'feedback.voting.downvote': 'डाउनवोट',
    'feedback.voting.score': 'एकूण गुण',
    'feedback.report.title': 'अहवालाची सामग्री',
    'feedback.report.typeSelect': 'येथे काय समस्या आहे?',
    'feedback.reportType.law': 'कायदेशीर उल्लंघन',
    'feedback.reportType.vulgar': 'अश्लील/अशिष्ट',
    'feedback.reportType.copyright': 'कॉपीराइट उल्लंघन',
    'feedback.reportType.storyRating': 'चुकीची वय मान्यता',
    'feedback.reportType.scam': 'धोखा',
    'feedback.report.submit': 'अहवाल',
    'feedback.report.submitting': 'तक्रार करीत आहे...',
    'feedback.report.violationDesc': 'तपशील',
    'feedback.report.reportSaved': 'तक्राराबद्दल धन्यवाद! आपल्याला तपशीलची तपासणी करण्यात येईल आणि आवश्यक असेल तर कारवाई करण्यात येईल.',
    'feedback.report.copyrightReportSaved': 'तक्राराबद्दल धन्यवाद! आपल्याला तपशीलची तपासणी करण्यात येईल आणि आमच्याशी संपर्क साधण्यात येईल.',
    'feedback.report.copyrightOwnershipDesc': 'स्वामित्वाची माहिती',
    'feedback.report.copyrightNotice': 'Please note that you need to be the rightful owner of the work to use this form. If you are not the owner, please inform the owner or use the other category to inform us. We take copyright violations extremely seriously, and the same applies to improper and abusive use of this form.',
    'feedback.report.copyrightInternalProperty': 'माझ्याकडे लिटररी युनिव्हर्सवर ही कामगिरी प्रकाशित केली आहे',
    'feedback.reportType.spam': 'स्पॅम किंवा फिशिंग',
    'feedback.reportType.soliciting': 'Soliciting',
    'feedback.reportType.aiUnmarked': 'Unmarked AI-generated content',
    'feedback.reportType.other': 'इतर',
    'feedback.report.copyrightType.propertySelectLabel': `कोणती विश्व {type, select,
    universe {कथा}
    story {कथा}
    other {कथा}
  } उल्लंघित केली जात आहे?`,
    'feedback.help.overview': 'Overview',
    'feedback.help.articles': 'Articles',
    'feedback.help.courses': 'Courses',
    'feedback.help.videoTutorials': 'Video tutorials',
    'feedback.help.featuredArticles': 'Featured Articles',
    'feedback.help.featuredCourses': 'Featured Courses',
    'feedback.help.featuredVideos': 'Featured Videos',
    'feedback.help.subCategories': 'Sub-categories',
    'feedback.resolution.title': 'Resolution center',
    'feedback.resolution.desc': 'Manage and resolve reported violations',
    'feedback.reportType.aiGenerated': 'AI-generated content',
    'feedback.resolution.aiGeneration': 'AI Generation Status',
    'feedback.resolution.aiGenerated': 'AI Generated',
    'feedback.resolution.notAiGenerated': 'Not AI Generated',
    'feedback.center.noReports': 'All clear! There are no reported violations.',
    // Added for Resolution Center lists
    'feedback.reportType.unknown': 'Unknown',
    'feedback.report.status.reported': 'Reported',
    'feedback.report.status.investigating': 'Investigating',
    'feedback.report.status.accepted': 'Accepted',
    'feedback.report.status.disputed': 'Disputed',
    'feedback.report.status.fixed': 'Fixed',
    'feedback.report.status.invalid': 'Invalid',
    'feedback.report.status.rejected': 'Rejected',
    'feedback.report.dateDetails': 'Created: {createdAt, date} | Updated: {updatedAt, date}',
    'feedback.report.quickResolution': 'Quick resolution',
    'feedback.report.actions.none': 'No quick action available',
    'feedback.report.actions.storySettings': 'Go to story settings',
    'feedback.report.actions.universeSettings': 'Go to universe settings',
    'feedback.report.description': 'Provided description',
    'feedback.report.copyrightReport': 'We have received copyright claim to this work. We will review the claim and make determination. If you want to provide any additional comment or context, please do so bellow.',
    // Slider component strings
    'feedback.help.selectFeaturedArticles': 'Select featured articles',
    'feedback.help.featuredArticlesDescription': 'These articles will be displayed in a slider on the category page. Articles should have a cover image for best appearance.',
    'feedback.help.addFeatured': 'Add to featured',
    'feedback.help.removeFeatured': 'Remove from featured',
    'feedback.help.noFeaturedArticles': 'No featured articles selected.',
    'feedback.help.noArticles': 'No articles in this category.',
    'feedback.help.noVideos': 'No videos',
    'feedback.help.noCourse': 'No courses',
    'feedback.help.videos': 'Help Videos',
    'feedback.help.noFeaturedVideos': 'No featured videos available yet.',
    'feedback.help.selectFeaturedVideos': 'Select featured videos',
    'feedback.help.featuredVideosDescription': 'These videos will be displayed in a slider on the category page. Videos should have a thumbnail for best appearance.',
    'feedback.help.backToCategory': 'Back to category',
    'feedback.help.watchVideo': 'Watch video'
};