export default {
    'groups.listing.title': 'युजर समूह',
    'groups.listing.organizationTitle': 'टीम्स',
    'groups.create.title': 'नवीन समूह तयार करा',
    'groups.type.label': 'प्रकार',
    'groups.type.open': 'उघडा',
    'groups.type.openDesc': 'उघडा - कोणताही व्यक्ती समूहात सामील होऊ शकतो.',
    'groups.type.closed': 'बंद',
    'groups.type.closedDesc': 'बंद - लोक तुमच्या समूहात सामील होण्यापूर्वी मंजूर केले पाहिजे.',
    'groups.type.hidden': 'लपविलेले',
    'groups.type.hiddenDesc': 'लपविलेले - फक्त तुम्ही आमंत्रित केलेले लोक समूहात सामील होऊ शकतात.',
    'groups.imageAlt': '{groupName} चित्र',
    'groups.members': 'सदस्य',
    'groups.members.total': `या समूहात {totalMembers, plural,
    zero {सदस्य आहेत}
    one {एक सदस्य आहे}
    other {# सदस्य आहेत}
  }`,
    'groups.leaveGroup': 'समूह त्यागा',
    'groups.leaveGroup.confirm': 'खात्री करण्यासाठी. तुम्ही खात्री आहात की तुम्ही नक्की समूहातून बाहेर पडायला जाता? {groupName}?',
    'group.settings': 'समूह सेटिंग्ज',
    'group.role.member': 'सदस्य',
    'group.role.moderator': 'मॉडरेटर',
    'group.role.admin': 'व्यवस्थापक',
    'groups.join.openGroup': 'समूहात सामील होण्यासाठी येथे क्लिक करा',
    'groups.join.closedGroup': 'समूहात सामील होण्यासाठी विनंती करा',
    'groups.join.questionToJoin': 'नवीन सदस्यांसाठी प्रश्न',
    'groups.join.closedAria': 'बंद समूहात सामील होण्यासाठी विनंती फॉर्म',
    'groups.join.questionDefault': 'तुम्हाला का समूहात सामील होण्याची परवानगी द्यायला पाहिजे?',
    'groups.join.pendingRequest': 'तुमची समूहातील सदस्यता विनंती समूहाच्या व्यवस्थापकांकडून मंजूरीकरणासाठी वाटते.',
    'groups.join.requesting': 'याची विनंती करणे',
    'groups.invite.btn': 'गटात आमंत्रण',
    'groups.invite.modalAria': 'गटात युजरचे आमंत्रण करा',
    'groups.invite.send': 'आमंत्रण पाठवा',
    'groups.invite.label': 'आमंत्रणासाठी युजर शोधा',
    'groups.invite.tileMsg': `तुम्हाला {count, plural,
    other {# गट आमंत्रणे आहेत}
  }`,
    'groups.invites.title': 'गट आमंत्रणे',
    'group.invite.accept': 'आमंत्रण स्वीकारा',
    'group.noticeBoard': 'नोटिस बोर्ड'
};