export default {
    'sharing.title': 'सामायिक करा',
    'sharing.button': 'Sharing Button',
    'sharing.share': 'Share with...',
    'sharing.feedback': 'Are we missing some place you would like to share to? Let us know about it!',
    'sharing.copy': 'नकल',
    'sharing.email': 'ई-मेल',
    'sharing.sms': 'SMS',
    'sharing.messenger': 'फेसबुक मेसेंजर',
    'sharing.whatsapp': 'WhatsApp',
    'sharing.twitter': 'X/Twitter',
    'sharing.linkedin': 'लिंक्डइन',
    'sharing.telegram': 'टेलिग्राम',
    'sharing.facebook': 'फेसबुक',
    'sharing.line': 'LINE',
    'sharing.mastodonSocial': 'Mastodon Social',
    'sharing.mastodonJapan': 'Mastodon Japan',
    'sharing.gab': 'Gab',
    'sharing.pinterest': 'Pinterest',
    'sharing.gettr': 'Gettr',
    'sharing.minds': 'Minds.com',
    'sharing.instagram': 'Instagram',
    'sharing.reddit': 'रेडिट',
    'sharing.bsky': 'BlueSky'
};