export default {
    'org.auditLog.title': 'অডিট লগ',
    'org.settings.title': 'সংগঠন সেটিংস',
    'org.settings.name': 'সংগঠনৰ নাম',
    'org.settings.membersPrivate': 'সদস্যবৃন্দক সর্বজনীনভাৱে প্ৰদৰ্শন কৰিব নহয়',
    'org.logo': 'সংগঠনৰ লগো',
    'org.logo.alt': '{organizationName} লোগো',
    'org.superAdmin': 'সুপাৰ এডমিন',
    'org.settings.language': 'প্ৰাথমিক ভাষা',
    'org.meta.desc': 'সাহিত্যিক বিশ্বত সংগঠন আৰু সৃজনশীল গোষ্ঠীসমূহ।',
    'org.luOrgs': 'সাহিত্যিক বিশ্বত সংগঠনসমূহ',
    'org.otherOrgs': 'Organizations',
    'org.aboutTitle': 'বিষয়বস্তু {orgName}',
    'org.membersTitle': 'সংগঠনের সদস্যবৃন্দ',
    'org.membersNone': 'সদস্যরা প্রকাশ্য নয়',
    'org.storiesTitle': '{orgName}থেকে গল্পসমূহ',
    'org.universesTitle': '{orgName}থেকে বিশ্বসমূহ',
    'org.userDashboardTitle': 'আপনার সংগঠনসমূহ',
    'org.settings.hideMembers.label': 'সদস্যদের প্রকাশ্য করুন না',
    'org.visit': '{organization} পৃষ্ঠায় যান',
    'org.authorOverride.legend': 'লেখক ওভাররাইড',
    'org.authorOverride.desc': 'সংগঠনের নামের পরিবর্তে এই পাঠ্যটি দেখায়।',
    'org.authorOverride.label': 'লেখকের নাম',
    'org.membersAdd.title': 'সংগঠনে সদস্যদের আমন্ত্রণ জানান',
    'org.flashnews.admin': 'ফ্ল্যাশনিউজ প্রশাসন',
    'org.settings.tabListAria': 'সংগঠনের জন্য বিভাগসমূহ সেট করুন',
    'org.forums.title': '{orgName} ফোরাম',
    'org.flashnews.internal': 'আন্তর্জাতিক খবর ফ্ল্যাশ',
    'org.flashnews.publicAll': 'সকল সম্পত্তির জন্য পাবলিক খবর ফ্ল্যাশ',
    'org.flashnews.createTitle': `সমস্ত সম্পত্তির জন্য সকল পাবলিক খবর ফ্ল্যাশের জন্য নতুন খবর ফ্ল্যাশ তৈরি করুন {type, select,
    internal {সংগঠন}
    allProperties {প্রদর্শন করা সকল সম্পত্তির জন্য}
    other {সংগঠন}
  }`,
    'org.members.invited': 'আমন্ত্রিত সদস্যবোৰ',
    'org.members.list': 'সংগঠনের সদস্যবৃন্দ',
    'org.invitesTileNotice': 'আপোনালৈ {count, number} {count, plural, one {সংগঠনত আমন্ত্ৰণ দিয়া হৈছে} other {সংগঠনত আমন্ত্ৰণ দিয়া হৈছে}}',
    'org.invitePage.title': 'সংগঠনসমূহত আমন্ত্ৰণ',
    'org.invitePage.invitedAt': 'আপুনি {invitedAt, date, short}ত আমন্ত্ৰণ দিয়া হৈছে।',
    'org.invitePage.ignoring': 'আপুনি বৰ্তমানে এই আমন্ত্ৰণটো অগ্ৰাহ্য কৰিছে, যিটো বুলি থাকিলে এটা এখনৰ পৰা সক্ৰিয় হব নাপাইব কিন্তু বিজ্ঞপ্তিত প্ৰবল নহয়।',
    'org.invitePage.expiresAt': 'এই আমন্ত্ৰণটো {expiresAt, date, short} {expiresAt, time}ত মেৰি হব।',
    'org.invitePage.accept': 'সংগঠনত যোগদান কৰক',
    'org.invitePage.reject': 'আমন্ত্ৰণ প্ৰত্যাখ্যান কৰক',
    'org.invitePage.ignore': 'এতিয়ালৈকে অগ্ৰাহ্য কৰক',
    'org.leaveOrg.title': 'সংগঠন ছেঁচাই দিয়ক',
    'org.leaveOrg.confirm': 'এইটো এটা ধ্বংসপ্ৰবণ ক্ৰিয়া। এটা ছেঁচাই দিলে আপুনি এই সংগঠনত সকলো প্ৰবেশ হারি যাব। আপুনি নিশ্চিত যে আপুনি সংগঠনটো ছেঁচাই দিব বিচাৰে নেকি?',
    'org.confirmRemove.aria': 'ব্যৱহাৰকাৰীৰ অপসারণ নিশ্চিত কৰক',
    'org.confirmRemove.confirm': 'আপুনি নিশ্চিত নেকি যে আপুনি {username} বুকটোৰ পৰা {organization}বুকটো আঁতৰাব বিচাৰে?',
    'org.confirmRemove.remove': 'ব্যৱহাৰকাৰী আঁতৰাওক',
    'org.mainBlog': 'মূখ্য ব্লগ',
    'org.teams': 'টীমসমূহ',
    'org.teams.total': 'মুঠ টীমসমূহ: {totalTeams, number}',
    'org.teams.create': 'নতুন টীম সৃষ্টি কৰক',
    'org.teams.settings': 'টীম সংস্কাৰ',
    'org.workshop.ownerUser': 'এটা একটা গিল্ড কাজ নয়',
    'org.workshop.caption': 'গিল্ড মালিকানা',
    'org.workshop.title': 'সংগঠনৰ কাৰ্যশালা',
    'org.title': 'সংগঠন',
    'org.hall.title': '{orgName} members hall',
    'org.member.leave': 'Leave organization',
    'org.member.leaveModalTitle': 'Leaving organization confirmation',
    'org.member.leaveModalHeading': 'Are you sure you want to leave {orgName}',
    'org.member.leaveModalExplain': 'Once you leave the organization you will loose access to all of the organization\'s associated resources and works. This action can\'t be undone.',
    // Role management strings
    'org.member.manageRoles': 'Manage Roles',
    'org.roles.error': 'Error: {error}',
    'org.roles.manageFor': 'Managing roles for {name}',
    'org.roles.selectRole': 'Select role',
    'org.roles.noRole': 'No role (permissions only)',
    'org.roles.admin': 'Admin',
    'org.roles.member': 'Member',
    'org.roles.author': 'Author',
    'org.roles.workshop': 'Workshop',
    'org.roles.teacher': 'Teacher',
    'org.permissions.title': 'Permissions',
    'org.permissions.includedInRole': '(included in role)',
    // Permission names
    'org.permissions.members.add': 'Add members',
    'org.permissions.members.remove': 'Remove members',
    'org.permissions.members.view': 'View members',
    'org.permissions.settings': 'Manage settings',
    'org.permissions.auditLog': 'View audit log',
    'org.permissions.flashnews': 'Manage flash news',
    'org.permissions.workshop.view': 'View workshop',
    'org.permissions.workshop.create': 'Create workshop items',
    'org.permissions.workshop.transfer': 'Transfer ownership',
    'org.permissions.workshop.viewAll': 'View all workshop items',
    'org.permissions.forum.manager': 'Manage forums',
    'org.permissions.blog.manage': 'Manage blog',
    'org.permissions.blog.post': 'Create blog posts'
};