export default {
    'feedback.home': 'Справочный центр',
    'feedback.bugs': 'Проблемы',
    'feedback.bugs.desc': 'Встретили ли вы ошибку или что-то ещё, что не так или не на своём месте. Сообщите нам об этом здесь!',
    'feedback.features': 'Идеи и предложения',
    'feedback.features.desc': 'Есть идеи о новых возможностях или о том, как сделать сайт лучше? Дайте нам знать!',
    'feedback.help': 'Помощь и руководства',
    'feedback.help.desc': 'Как сделать _____? Перейдите сюда, чтобы найти ответы.',
    'feedback.desc': 'Добро пожаловать в наш центр помощи и решений!',
    'feedback.faq': 'ЧаВО',
    'feedback.faq.desc': 'Часто задаваемые вопросы',
    'feedback.open': 'Открыто',
    'feedback.closed': 'Закрыто',
    'feedback.accepted': 'Принято',
    'feedback.inprogress': 'В разработке',
    'feedback.completed': 'Завершено',
    'feedback.fixed': 'Исправлено',
    'feedback.new.bugs': 'Сообщить о новой проблеме',
    'feedback.new.features': 'Предложить новую функцию',
    'feedback.lang.nosupport': 'Ваш текущий язык не поддерживается для обратной связи, пожалуйста, пишите на английском. Спасибо!',
    'feedback.new.thanks': 'Спасибо за сообщение! Мы рассмотрим его в ближайшее время.',
    'feedback.comment.title': 'Комментирий',
    'feedback.comment.desc': 'Оставить отзыв',
    'feedback.comment.legend': 'Ваш отзыв - дайте нам знать обо всём',
    'feedback.comment.success': 'Спасибо за ваш отзыв!',
    'feedback.comment.label': 'Ваш комментарий',
    'feedback.copyrightReport.title': 'Нарушение авторских прав',
    'feedback.copyrightReport.desc': 'Сообщить о нарушении авторских прав',
    'feedback.report.noUser': 'Вы должны войти, чтобы отправить жалобу.',
    'feedback.voting.totalVoters': 'Пользователей проголосовали: {voted, number}',
    'feedback.voting.upvote': 'Полож. голос',
    'feedback.voting.downvote': 'Отриц. голос',
    'feedback.voting.score': 'Всего голосов',
    'feedback.report.title': 'Пожаловаться',
    'feedback.report.typeSelect': 'В чём проблема?',
    'feedback.reportType.law': 'Нарушение закона',
    'feedback.reportType.vulgar': 'Вульгарность/непристойность',
    'feedback.reportType.copyright': 'Нарушение авторских прав',
    'feedback.reportType.storyRating': 'Неверный возрастной рейтинг',
    'feedback.reportType.scam': 'Мошенничество',
    'feedback.report.submit': 'Пожаловаться',
    'feedback.report.submitting': 'Отправление жалобы...',
    'feedback.report.violationDesc': 'Подробности',
    'feedback.report.reportSaved': 'Спасибо за сообщение! Мы проведём расследование и при необходимости примем меры.',
    'feedback.report.copyrightReportSaved': 'Спасибо за сообщение! Мы проведём расследование и свяжемся с вами.',
    'feedback.report.copyrightOwnershipDesc': 'Заявление о праве собственности',
    'feedback.report.copyrightNotice': 'Обратите внимание, что для использования этой формы вы должны быть законным владельцем произведения. Если вы не являетесь владельцем, пожалуйста, сообщите об этом владельцу или воспользуйтесь другой категорией, чтобы сообщить нам. Мы крайне серьёзно относимся к нарушениям авторских прав, и то же самое относится к ненадлежащему и неправомерному использованию этой формы.',
    'feedback.report.copyrightInternalProperty': 'Я опубликовал(-а) это произведение на сайте Literary Universe',
    'feedback.reportType.spam': 'Спам или фишинг',
    'feedback.reportType.other': 'Другое',
    'feedback.report.copyrightType.propertySelectLabel': `Какая {type, select,
    universe {вселенная}
    story {история}
    other {история}
  } нарушается?`,
    'faq.section.about': 'О нас',
    'faq.section.settings': 'Настройки',
    'faq.section.discovery': 'Исследовать',
    'faq.section.reader': 'Читатель',
    'faq.section.library': 'Библиотека',
    'faq.section.workshop': 'Мастерская',
    'faq.section.writer': 'Писатель',
    'faq.section.encyclopedia': 'Энциклопедия',
    'faq.section.groups': 'Группы',
    'faq.section.blogs': 'Блоги',
    // About us questions
    'faq.question.about.dataLocation': 'Где хранятся данные LU?',
    'faq.answer.about.dataLocation': 'Данные Literary Universe хранятся на серверах в Соединённых Штатах Америки, а именно в регионе AWS us-east-1.',
    'faq.question.about.incorporation': 'Где вы зарегистрированы?',
    'faq.answer.about.incorporation': 'Literary Universe зарегистрирована в Чешской Республике. Более подробную информацию вы можете найти на странице <a href="/about">о нас</a>.',
    'faq.question.about.roadmap': 'Каковы следующие шаги для Literary Universe?',
    'faq.answer.about.roadmap': 'Мы постоянно развиваемся. Ознакомьтесь с нашей <a href="/roadmap">картой разработки</a> для получения более подробной информации.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Как изменить внешний вид Literary Universe?',
    'faq.answer.settings.changeTheme': 'Зарегистрированные пользователи могут изменить тему в своих <a href="/user/settings/account">настройках учётной записи</a> в разделе «Темы сайта». У нас есть светлая и тёмная темы. Если вы не зарегистрированы, мы пытаемся определить, какую тему предложить вам на основе настроек вашего браузера и операционной системы.',
    'faq.question.settings.changeAvatar': 'Как изменить мой аватар?',
    'faq.answer.settings.changeAvatar': 'Вы можете изменить свой аватар в <a href="/user/settings/profile">настройках профиля</a>.',
    'faq.question.settings.changeLanguage': 'Как изменить язык?',
    'faq.answer.settings.changeLanguage': 'Вы можете изменить язык Literary Universe в <a href="/user/settings/account">настройках учётной записи</a>.',
    'faq.question.settings.translationMistake': 'Мной была замечена ошибка в тексте на сайте, где мне о ней сообщить?',
    'faq.answer.settings.translationMistake': 'Все наши языковые файлы доступны на GitHub. Вы можете <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">сообщить об этой проблеме там</a> или в разделе ошибок в обратной связи, или, если вам так хочется, вы можете исправить её самостоятельно на <a href="https://crowdin.com/project/literary-universe" target="_blank">нашей странице Crowdin</a>.'
};