export default {
    'org.auditLog.title': 'Журнал аудита',
    'org.settings.title': 'Настройки организации',
    'org.settings.name': 'Название организации',
    'org.settings.membersPrivate': 'НЕ отображать участников открыто',
    'org.logo': 'Логотип организации',
    'org.logo.alt': 'Логотип {organizationName}',
    'org.superAdmin': 'Суперадминистратор',
    'org.settings.language': 'Основной язык',
    'org.meta.desc': 'Организации и творческие коллективы на Literary Universe.',
    'org.luOrgs': 'Организации Literary Universe',
    'org.otherOrgs': 'Организации',
    'org.aboutTitle': 'О {orgName}',
    'org.membersTitle': 'Участники организации',
    'org.membersNone': 'Участники не являются публичными',
    'org.storiesTitle': 'Истории от {orgName}',
    'org.universesTitle': 'Вселенные от {orgName}',
    'org.userDashboardTitle': 'Ваши организации',
    'org.settings.hideMembers.label': 'Скрыть участников из публичных',
    'org.visit': 'Перейти на страницу {organization}',
    'org.authorOverride.legend': 'Переопределение автора',
    'org.authorOverride.desc': 'Отображает этот текст вместо названия организации.',
    'org.authorOverride.label': 'Имя автора',
    'org.membersAdd.title': 'Пригласить участников в организацию',
    'org.flashnews.admin': 'Управление новостями',
    'org.settings.tabListAria': 'Установка разделов для организации',
    'org.forums.title': 'Форумы {orgName}',
    'org.flashnews.internal': 'Внутренние новости',
    'org.flashnews.publicAll': 'Общедоступные новости для всех объектов',
    'org.flashnews.createTitle': `Создайте новую новостную ленту для {type, select,
    internal {организации}
    allProperties {общего показа на всех объектах}
    other {организации}
  }`,
    'org.members.invited': 'Приглашённые участники',
    'org.members.list': 'Участники организации',
    'org.invitesTileNotice': 'Вы были приглашены в {count, number} {count, plural, one {организацию} few {организации} many {организаций} other {организаций}}',
    'org.invitePage.title': 'Приглашения в организации',
    'org.invitePage.invitedAt': 'Вас пригласили {invitedAt, date, short}',
    'org.invitePage.ignoring': 'В настоящее время вы игнорируете это приглашение, что означает, что оно всё ещё действует, но не беспокоит вас уведомлениями.',
    'org.invitePage.expiresAt': 'Срок действия приглашения истекает {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Присоединиться к организации',
    'org.invitePage.reject': 'Отклонить приглашение',
    'org.invitePage.ignore': 'Пока игнорировать',
    'org.leaveOrg.title': 'Покинуть организацию',
    'org.leaveOrg.confirm': 'Это деструктивное действие. Как только вы покинете, вы потеряете всякий доступ к этой организации. Вы уверены, что хотите покинуть организацию?',
    'org.confirmRemove.aria': 'Подтверждение удаления пользователя',
    'org.confirmRemove.confirm': 'Вы уверены, что хотите удалить {username} из «{organization}»?',
    'org.confirmRemove.remove': 'Удалить пользователя',
    'org.mainBlog': 'Основной блог',
    'org.teams': 'Команды',
    'org.teams.total': 'Всего команд: {totalTeams, number}',
    'org.teams.create': 'Создать новую команду',
    'org.teams.settings': 'Настройки команды',
    'org.workshop.ownerUser': 'Не произведение гильдии',
    'org.workshop.caption': 'Владелец гильдии',
    'org.workshop.title': 'Мастерская организации',
    'org.title': 'Организация',
    'org.hall.title': 'Зал участников «{orgName}»',
    'org.member.leave': 'Покинуть организацию',
    'org.member.leaveModalTitle': 'Подтверждение выхода из организации',
    'org.member.leaveModalHeading': 'Вы уверены, что хотите покинуть «{orgName}»',
    'org.member.leaveModalExplain': 'Как только вы покинете организацию, вы потеряете доступ ко всем связанным с ней ресурсам и работам. Это действие необратимо.',
    // Role management strings
    'org.member.manageRoles': 'Управление ролями',
    'org.roles.error': 'Ошибка: {error}',
    'org.roles.manageFor': 'Управление ролями для {name}',
    'org.roles.selectRole': 'Выберите роль',
    'org.roles.noRole': 'Нет роли (только разрешения)',
    'org.roles.admin': 'Администратор',
    'org.roles.member': 'Член',
    'org.roles.author': 'Автор',
    'org.roles.workshop': 'Семинар',
    'org.roles.teacher': 'Преподаватель',
    'org.permissions.title': 'Разрешения',
    'org.permissions.includedInRole': '(входит в роль)',
    // Permission names
    'org.permissions.members.add': 'Добавить участников',
    'org.permissions.members.remove': 'Удалите членов',
    'org.permissions.members.view': 'Просмотр участников',
    'org.permissions.settings': 'Управление настройками',
    'org.permissions.auditLog': 'Просмотр журнала аудита',
    'org.permissions.flashnews': 'Управление флэш-новостями',
    'org.permissions.workshop.view': 'Посмотреть мастер-класс',
    'org.permissions.workshop.create': 'Создавайте предметы для мастер-классов',
    'org.permissions.workshop.transfer': 'Передача прав собственности',
    'org.permissions.workshop.viewAll': 'Посмотреть все товары для семинаров',
    'org.permissions.forum.manager': 'Управляйте форумами',
    'org.permissions.blog.manage': 'Управляйте блогом',
    'org.permissions.blog.post': 'Создавайте посты в блоге'
};