export default {
    'reader.storyEnd.heading': 'КОНЕЦ',
    'reader.storyEnd.description': 'Вы подошли к концу истории.',
    'reader.externalSale.heading': 'Пока нет',
    'reader.externalSale.description': 'Эта история недоступна на Literary Universe, но вы можете получить её в других местах.',
    'reader.storyTBC.heading': 'Продолжение следует...',
    'reader.storyTBC.description': 'Это пока всё, что у нас есть для этой истории, но приключения продолжатся в будущем, заглядывайте почаще!',
    'chapter.translation.notYetDescription': 'Загляните к нам ещё раз!',
    'reader.externalShopping.heading': 'Купить {storyName} в магазинах:',
    'chapter.next': 'Следующая глава',
    'chapter.previous': 'Предыдущая глава',
    'chapter.comment': 'Комментарии к этой главе',
    'reader.language': 'Язык:',
    'reader.fullscreen.enter': 'Войти в полноэкранный режим',
    'reader.fullscreen.exit': 'Выйти из полноэкранного режима',
    'reader.details.universe': 'Подробности вселенной',
    'reader.details.story': 'Подробности истории',
    'reader.darkmode': 'Тёмная тема',
    'reader.flowtext': 'Размер текста',
    'reader.menu.optionsAria': 'Меню настроек для чтения',
    'reader.accessibility': 'Специальные возможности',
    'chapter.translation.notYet': 'Эта глава ещё не была переведена.',
    'externalShopping.buyLink.amazon': 'Купить на Amazon',
    'externalShopping.buyLink.other': 'Купить в {storeName}',
    'externalShopping.buyLink.bookshop': 'Купить на Bookshop.org',
    'reader.accessibility.aria': 'Настройки специальных возможностей',
    'reader.accessibility.toggleDyslexic': 'Шрифт для дислексиков',
    'reader.accessibility.toggleParagraphStripes': 'Изменение фона абзацев',
    'reader.accessibility.toggleParagraphHighlight': 'Выделение выбранного абзаца',
    'reader.accessibility.toggleRules': 'Вспомогательная линейка',
    'reader.nextRelease.scheduled': 'Следующая глава выйдет {nextReleaseAt, date} в {nextReleaseAt, time}!',
    'reader.storyContinues': 'История продолжается...',
    'reader.storyOnHiatus': 'The author is currently taking a break from this story and this story is on hiatus for now. Check back in a month or two.',
    'reader.storyCancelled': 'Sadly this is it. The story has been cancelled so it is unlikely there is going to be anything new.',
    'reader.storyCancelled.heading': 'Cancelled'
};