export default {
    'writer.menu.optionsAria': 'Меню настроек редактора',
    'writer.menu.saveOptionsAria': 'Сохранить настройки',
    'writer.undo': 'Отменить',
    'writer.redo': 'Повторить',
    'writer.ul': 'Неупорядоченный список',
    'writer.ol': 'Упорядоченный список',
    'writer.blockquote': 'Цитата',
    'writer.link': 'Вставить ссылку',
    'writer.image': 'Вставить изображение',
    'writer.bold': 'Выделить жирным шрифтом выделенное',
    'writer.underline': 'Подчеркнуть выделенное',
    'writer.italic': 'Акцентировать выделенное',
    'writer.wordCount': '{characters, number} символа(-ов), {words, number} слов(-а)',
    'writer.characterCount': '{characters, number} символа(-ов)',
    'finder.details': 'подробности',
    'finder.remove': 'Удалить подключение',
    'finder.connect': 'Подключить выделенное к записи энциклопедии',
    'writer.aside.ariaLabel': 'Меню настроек справки',
    'writer.nothingToSave': 'Нет данных для сохранения',
    'writer.link.placeholder': 'Введите URL-адрес',
    'writer.link.error.empty': 'URL не может быть пустым',
    'writer.link.error.invalid': 'Пожалуйста, введите правильный URL',
    'writer.fontFamily': 'Семейство шрифтов',
    'writer.fontFamily.select': 'Выберите шрифт',
    'writer.publish.publishAria': 'Настройки публикации',
    'writer.publish.scheduleExplained': 'Вы можете опубликовать главу сразу или запланировать её появление на более поздний срок.',
    'writer.publish.schedule': 'Установить дату и время публикации',
    'writer.publish.previousChapterPublished': 'Предыдущая глава была опубликована {publishDate, date, short} в {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'Предыдущая глава должна быть опубликована в {publishDate, date, short} в {publishDate, time}',
    'writer.publish.alreadyPublished': 'Эта глава уже была опубликована {publishedAt, date, short}. Новые версии будут опубликованы немедленно.',
    'writer.publish.betaReader': 'Тестирование',
    'writer.publish.public': 'Опубликовать',
    'writer.publish.now': 'Опубликовать сейчас',
    'writer.publish.schedulePrevious': 'Вам необходимо опубликовать или запланировать публикацию предыдущей главы, прежде чем вы сможете опубликовать эту.'
};