export default {
  'courses.courses': 'Courses',
  'courses.overview': 'कोर्स का अवलोकन',
  'course.create': 'नया कोर्स बनाएं',
  'course.reading.title': 'Reading assignment title',
  'course.question.add': 'Add question',
  'course.add.courseElement': 'Add a new course element',
  'course.lessons.newMessage': 'Create and organize your lessons for effective teaching',
  'course.reading.new': 'Reading Assignment',
  'course.reading.newMessage': 'Create and organize reading assignments for your students',
  'course.writing.new': 'लेखन कार्य',
  'course.writing.newMessage': 'Quickly set up and distribute writing tasks',
  'course.question.text': 'आपका सवाल यहाँ दर्ज करें',
  'course.question.type': 'Please select a type of question',
  'course.question.delete': 'Remove question',
  'course.type': 'कोर्स के प्रकार का चयन करें',
  'course.visibility': 'दृश्यता विकल्प का चयन करें',
  'course.title': 'शीर्षक',
  'course.description': 'विवरण',
  'course.cover': 'कवर',
  'course.start': 'आपका कोर्स यहाँ से शुरू होता है',
  'course.ends': 'आपका कोर्स यहाँ समाप्त होता है',
  'course.curriculum': 'पाठ्यक्रम',
  'course.members': 'छात्र और शिक्षक',
  'course.assignments': 'Assignments',
  'course.question.deleteWhole': 'पूरा प्रश्न हटाएँ',
  'course.question.yes': 'हाँ',
  'course.question.no': 'नहीं',
  'course.lesson.title': 'पाठ का शीर्षक',
  'course.lesson.add.universe': 'कहानी/यूनिवर्स जोड़ें',
  'course.lesson.add.link': 'बाहरी लिंक जोड़ें',
  'course.status': 'Status',
  'course.active': 'Activity',
  'course.active.message': 'Active',
  'course.inactive': 'Inactive',
  'course.module.edit': 'Edit module name',
  'course.upload.resource': 'Upload a file resource',
  'course.question.answer': 'Add answer',
  'course.question.open': 'Open question',
  'course.question.close': 'Closed question',
  'course.question.multiple': 'Multiple-choice question',
  'course.about': 'About this course',
  'course.lesson.new': 'Create a new lesson',
  'course.lesson.type': 'Lesson type',
  'course.lesson.inPerson': 'In person',
  'course.lesson.preRecorded': 'Pre-recorded',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Text only',
  'course.lesson.content': 'Lesson content',
  'course.lesson.description': 'Public description',
  'course.add.module': 'Add new module',
  'course.add.story': 'Add story',
  'course.remove.story': 'Remove story',
  'course.dateOfPublish': 'Date of publishing',
  'course.lesson.meetInPerson': 'Meet in person',
  'course.curriculum.edit': 'Edit curriculum',
};
