export default {
    'feedback.home': 'सहायता केंद्र',
    'feedback.bugs': 'समस्याएँ',
    'feedback.bugs.desc': 'क्या आपने कोई त्रुटि या कुछ ऐसा देखा है जो गलत या अप्रासंगिक है। हमें यहाँ बताएं!',
    'feedback.features': 'विचार और प्रस्ताव',
    'feedback.features.desc': 'नई सुविधाओं के लिए विचार या साइट को और बेहतर कैसे बनाएं? हमें बताएं!',
    'feedback.help': 'सहायता और ट्यूटोरियल',
    'feedback.help.desc': 'आप _____कैसे करते हैं? यहाँ जाकर जवाब पाएं।',
    'feedback.desc': 'हमारे सहायता और समाधान केंद्र में आपका स्वागत है!',
    'feedback.faq': 'सामान्य प्रश्न',
    'feedback.faq.desc': 'अक्सर पूछे जाने वाले प्रश्न',
    'feedback.open': 'खुला',
    'feedback.closed': 'बंद',
    'feedback.accepted': 'स्वीकृत',
    'feedback.inprogress': 'प्रगति में',
    'feedback.completed': 'पूरा हुआ',
    'feedback.fixed': 'ठीक हुआ',
    'feedback.new.bugs': 'नई समस्या की रिपोर्ट करें',
    'feedback.new.features': 'नई सुविधा की सुझाव दें',
    'feedback.lang.nosupport': 'आपकी वर्तमान भाषा समर्थित नहीं है, कृपया अंग्रेजी में लिखें। धन्यवाद!',
    'feedback.new.thanks': 'सूचना के लिए धन्यवाद! हम जल्दी ही इस पर नज़र डालेंगे।',
    'feedback.comment.title': 'टिप्पणी',
    'feedback.comment.desc': 'हमें अपनी प्रतिक्रिया भेजें',
    'feedback.comment.legend': 'आपकी प्रतिक्रिया - हमें हर चीज़ के बारे में बताएं',
    'feedback.comment.success': 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    'feedback.comment.label': 'आपकी टिप्पणी',
    'feedback.copyrightReport.title': 'कॉपीराइट उल्लंघन',
    'feedback.copyrightReport.desc': 'कॉपीराइट उल्लंघन की रिपोर्ट करें',
    'feedback.report.noUser': 'रिपोर्ट दर्ज करने के लिए आपको साइन इन करने की आवश्यकता है।',
    'feedback.voting.totalVoters': 'उपयोगकर्ताओं ने मतदान किया: {voted, number}',
    'feedback.voting.upvote': 'उपवोट',
    'feedback.voting.downvote': 'नीचे मतदान करें',
    'feedback.voting.score': 'कुल स्कोर',
    'feedback.report.title': 'रिपोर्ट की सामग्री',
    'feedback.report.typeSelect': 'यहाँ क्या समस्या है?',
    'feedback.reportType.law': 'कानून का उल्लंघन',
    'feedback.reportType.vulgar': 'अश्लील/अशोभनीय',
    'feedback.reportType.copyright': 'कॉपीराइट का उल्लंघन',
    'feedback.reportType.storyRating': 'गलत आयु रेटिंग',
    'feedback.reportType.scam': 'धोखाधड़ी',
    'feedback.report.submit': 'रिपोर्ट',
    'feedback.report.submitting': 'रिपोर्ट कर रहा है...',
    'feedback.report.violationDesc': 'विवरण',
    'feedback.report.reportSaved': 'रिपोर्ट के लिए धन्यवाद! हम जांच करेंगे और यदि आवश्यक हो तो कार्रवाई करेंगे।',
    'feedback.report.copyrightReportSaved': 'रिपोर्ट के लिए धन्यवाद! हम जांच करेंगे और संपर्क में रहेंगे।',
    'feedback.report.copyrightOwnershipDesc': 'स्वामित्व का दावा',
    'feedback.report.copyrightNotice': 'कृपया ध्यान दें कि आपको इस फॉर्म का उपयोग करने के लिए कार्य का वास्तविक मालिक होना चाहिए। यदि आप मालिक नहीं हैं, तो कृपया मालिक को सूचित करें या हमें सूचित करने के लिए अन्य श्रेणी का उपयोग करें। हम कॉपीराइट उल्लंघन को अत्यंत गंभीरता से लेते हैं और इसी तरह इस फॉर्म के अनुचित और अपयश उपयोग पर भी यही लागू होता है।',
    'feedback.report.copyrightInternalProperty': 'मैंने इस कार्य को लिटररी यूनिवर्स पर प्रकाशित किया है',
    'feedback.reportType.spam': 'स्पैम या फिशिंग',
    'feedback.reportType.other': 'अन्य',
    'feedback.report.copyrightType.propertySelectLabel': `कौनसा {type, select,
    universe {यूनिवर्स}
    story {कहानी}
    other {कहानी}
  } का उल्लंघन किया जा रहा है?`
};