export default {
    'feedback.home': 'सहायता केंद्र',
    'feedback.bugs': 'समस्याएँ',
    'feedback.bugs.desc': 'क्या आपने कोई त्रुटि या कुछ ऐसा देखा है जो गलत या अप्रासंगिक है। हमें यहाँ बताएं!',
    'feedback.features': 'विचार और प्रस्ताव',
    'feedback.features.desc': 'नई सुविधाओं के लिए विचार या साइट को और बेहतर कैसे बनाएं? हमें बताएं!',
    'feedback.help': 'सहायता और ट्यूटोरियल',
    'feedback.help.desc': 'आप _____कैसे करते हैं? यहाँ जाकर जवाब पाएं।',
    'feedback.desc': 'हमारे सहायता और समाधान केंद्र में आपका स्वागत है!',
    'feedback.open': 'खुला',
    'feedback.closed': 'बंद',
    'feedback.accepted': 'स्वीकृत',
    'feedback.inprogress': 'प्रगति में',
    'feedback.completed': 'पूरा हुआ',
    'feedback.fixed': 'ठीक हुआ',
    'feedback.new.bugs': 'नई समस्या की रिपोर्ट करें',
    'feedback.new.features': 'नई सुविधा की सुझाव दें',
    'feedback.lang.nosupport': 'आपकी वर्तमान भाषा समर्थित नहीं है, कृपया अंग्रेजी में लिखें। धन्यवाद!',
    'feedback.new.thanks': 'सूचना के लिए धन्यवाद! हम जल्दी ही इस पर नज़र डालेंगे।',
    'feedback.comment.title': 'टिप्पणी',
    'feedback.comment.desc': 'हमें अपनी प्रतिक्रिया भेजें',
    'feedback.comment.legend': 'आपकी प्रतिक्रिया - हमें हर चीज़ के बारे में बताएं',
    'feedback.comment.success': 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    'feedback.comment.label': 'आपकी टिप्पणी',
    'feedback.copyrightReport.title': 'कॉपीराइट उल्लंघन',
    'feedback.copyrightReport.desc': 'कॉपीराइट उल्लंघन की रिपोर्ट करें',
    'feedback.report.noUser': 'रिपोर्ट दर्ज करने के लिए आपको साइन इन करने की आवश्यकता है।',
    'feedback.voting.totalVoters': 'उपयोगकर्ताओं ने मतदान किया: {voted, number}',
    'feedback.voting.upvote': 'उपवोट',
    'feedback.voting.downvote': 'नीचे मतदान करें',
    'feedback.voting.score': 'कुल स्कोर',
    'feedback.report.title': 'रिपोर्ट की सामग्री',
    'feedback.report.typeSelect': 'यहाँ क्या समस्या है?',
    'feedback.reportType.law': 'कानून का उल्लंघन',
    'feedback.reportType.vulgar': 'अश्लील/अशोभनीय',
    'feedback.reportType.copyright': 'कॉपीराइट का उल्लंघन',
    'feedback.reportType.storyRating': 'Incorrect age rating',
    'feedback.reportType.scam': 'Scam',
    'feedback.report.submit': 'Report',
    'feedback.report.submitting': 'Reporting...',
    'feedback.report.violationDesc': 'Details',
    'feedback.report.reportSaved': 'Thank you for the report! We will investigate and take action if needed.',
    'feedback.report.copyrightReportSaved': 'Thank you for the report! We will investigate and be in touch.',
    'feedback.report.copyrightOwnershipDesc': 'Ownership statement',
    'feedback.report.copyrightNotice': 'Please note that you need to be the rightful owner of the work to use this form. If you are not the owner, please inform the owner or use the other category to inform us. We take copyright violations extremely seriously and the same applies to improper and abusive use of this form.',
    'feedback.report.copyrightInternalProperty': 'I have published this work on Literary Universe',
    'feedback.reportType.spam': 'Spam or phishing',
    'feedback.reportType.other': 'Other',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`
};