export default {
    'org.auditLog.title': 'ऑडिट लॉग',
    'org.settings.title': 'संगठन सेटिंग्स',
    'org.settings.name': 'संगठन का नाम',
    'org.settings.membersPrivate': 'सदस्यों को सार्वजनिक रूप से प्रदर्शित न करें',
    'org.logo': 'संगठन लोगो',
    'org.logo.alt': '{organizationName} लोगो',
    'org.superAdmin': 'सुपर एडमिन',
    'org.settings.language': 'प्राथमिक भाषा',
    'org.meta.desc': 'लिटररी यूनिवर्स के संगठन और रचनात्मक समूह।',
    'org.luOrgs': 'लिटररी यूनिवर्स संगठन',
    'org.otherOrgs': 'Organizations',
    'org.aboutTitle': 'बारे में {orgName}',
    'org.membersTitle': 'संगठन के सदस्य',
    'org.membersNone': 'सदस्यों को सार्वजनिक नहीं बनाया जाता है',
    'org.storiesTitle': '{orgName}से कहानियाँ',
    'org.universesTitle': '{orgName}से विश्व',
    'org.userDashboardTitle': 'आपके संगठन',
    'org.settings.hideMembers.label': 'सदस्यों को सार्वजनिक से छिपाएँ',
    'org.visit': '{organization} पेज पर जाएँ',
    'org.authorOverride.legend': 'लेखक ओवरराइड',
    'org.authorOverride.desc': 'संगठन के नाम की बजाय यह पाठ दिखाता है।',
    'org.authorOverride.label': 'लेखक का नाम',
    'org.membersAdd.title': 'संगठन में सदस्यों को आमंत्रित करें',
    'org.flashnews.admin': 'फ़्लैशन्यूज़ प्रशासन',
    'org.settings.tabListAria': 'संगठन के लिए खंड सेट करें',
    'org.forums.title': '{orgName} मंच',
    'org.flashnews.internal': 'आंतरिक न्यूज़ फ्लैश',
    'org.flashnews.publicAll': 'सभी संपत्तियों के लिए सार्वजनिक न्यूज़ फ्लैश',
    'org.flashnews.createTitle': `{type, select,
    internal {संगठन}
    allProperties {के लिए एक नया न्यूज़ फ्लैश बनाएं, सभी संपत्तियों पर सार्वजनिक रूप से प्रदर्शित करें}
    other {संगठन}
  }`,
    'org.members.invited': 'आमंत्रित सदस्य',
    'org.members.list': 'संगठन के सदस्य',
    'org.invitesTileNotice': 'आपको आमंत्रित किया गया है {count, number} {count, plural, one {संगठन में} other {संगठनों में}}',
    'org.invitePage.title': 'संगठनों के लिए आमंत्रण',
    'org.invitePage.invitedAt': 'आपको आमंत्रित किया गया है {invitedAt, date, short}पर।',
    'org.invitePage.ignoring': 'आप वर्तमान में इस आमंत्रण को नजरअंदाज कर रहे हैं, जिसका मतलब है कि यह अभी भी सक्रिय है, लेकिन सूचनाओं के साथ परेशान नहीं करता।',
    'org.invitePage.expiresAt': 'यह आमंत्रण समाप्त होगा {expiresAt, date, short} {expiresAt, time}पर।',
    'org.invitePage.accept': 'संगठन में शामिल हों',
    'org.invitePage.reject': 'आमंत्रण अस्वीकार करें',
    'org.invitePage.ignore': 'अभी के लिए नजरअंदाज करें',
    'org.leaveOrg.title': 'संगठन छोड़ें',
    'org.leaveOrg.confirm': 'यह एक विनाशकारी कार्रवाई है। एक बार जब आप छोड़ देंगे तो आपको इस संगठन का पहुंच सब कुछ खो जाएगा। क्या आप वाकई संगठन छोड़ना चाहते हैं?',
    'org.confirmRemove.aria': 'उपयोगकर्ता हटाने की पुष्टि करें',
    'org.confirmRemove.confirm': 'क्या आप वाकई {username} को {organization}से हटाना चाहते हैं?',
    'org.confirmRemove.remove': 'उपयोगकर्ता हटाएं',
    'org.mainBlog': 'मुख्य ब्लॉग',
    'org.teams': 'टीमें',
    'org.teams.total': 'कुल टीमें: {totalTeams, number}',
    'org.teams.create': 'नई टीम बनाएं',
    'org.teams.settings': 'टीम सेटिंग्स',
    'org.workshop.ownerUser': 'एक गिल्ड का काम नहीं',
    'org.workshop.caption': 'गिल्ड स्वामित्व',
    'org.workshop.title': 'संगठन कार्यशाला',
    'org.title': 'संगठन',
    'org.hall.title': '{orgName} members hall',
    'org.member.leave': 'Leave organization',
    'org.member.leaveModalTitle': 'Leaving organization confirmation',
    'org.member.leaveModalHeading': 'Are you sure you want to leave {orgName}',
    'org.member.leaveModalExplain': 'Once you leave the organization you will loose access to all of the organization\'s associated resources and works. This action can\'t be undone.',
    // Role management strings
    'org.member.manageRoles': 'Manage Roles',
    'org.roles.error': 'Error: {error}',
    'org.roles.manageFor': 'Managing roles for {name}',
    'org.roles.selectRole': 'Select role',
    'org.roles.noRole': 'No role (permissions only)',
    'org.roles.admin': 'Admin',
    'org.roles.member': 'Member',
    'org.roles.author': 'Author',
    'org.roles.workshop': 'Workshop',
    'org.roles.teacher': 'Teacher',
    'org.permissions.title': 'Permissions',
    'org.permissions.includedInRole': '(included in role)',
    // Permission names
    'org.permissions.members.add': 'Add members',
    'org.permissions.members.remove': 'Remove members',
    'org.permissions.members.view': 'View members',
    'org.permissions.settings': 'Manage settings',
    'org.permissions.auditLog': 'View audit log',
    'org.permissions.flashnews': 'Manage flash news',
    'org.permissions.workshop.view': 'View workshop',
    'org.permissions.workshop.create': 'Create workshop items',
    'org.permissions.workshop.transfer': 'Transfer ownership',
    'org.permissions.workshop.viewAll': 'View all workshop items',
    'org.permissions.forum.manager': 'Manage forums',
    'org.permissions.blog.manage': 'Manage blog',
    'org.permissions.blog.post': 'Create blog posts'
};