export default {
    'homepage.welcome': 'Welcome to',
    'homepage.start': 'Start Your journey!',
    'homepage.iAm': 'I am a',
    'homepage.iAm.aria': 'Select between display of features for readers and writers',
    'homepage.reader': 'READER',
    'homepage.writer': 'WRITER',
    'homepage.reader.title': 'Reading has never been so interesting like this',
    'homepage.reader.registerCTA': 'Start reading now!',
    'homepage.reader.readingTitle': 'Unique reading experience',
    'homepage.reader.readingDesc': 'Delve deeper into your favorite fictional universe in Literary Universe. Stories in Literary Universe are connected within the same universe, giving you immediate access to the universe encyclopedia from the story reader.',
    'homepage.reader.favoriteTitle': 'Find out more about Your favorite stories and authors',
    'homepage.reader.favoriteDesc': 'Universe encyclopedia and author\'s blogs are just a few feature that will help you find out everything you need to know about your favorite stories, their settings and their creators!',
    'homepage.reader.communityTitle': 'Join the community',
    'homepage.reader.communityDesc': 'Meet people from across the globe on dedicated universe and author\'s forums, blogs and other community features where like-minded fans gather. All in one place.',
    'homepage.reader.readingFeatureTitle': 'Enjoy an immersive yet practical reading experience',
    'homepage.reader.readingFeatureDesc': 'From stories and universe, have the benefit of effortless reading with access to details without needing to switch between pages.',
    'homepage.reader.readingExploreTitle': 'Explore all the minutia in the universe',
    'homepage.reader.readingExploreDesc': 'Universe encyclopedia allows you to learn all the details about the universe and fully immerse yourself in the stories.',
    'homepage.reader.start': 'Start Reading',
    'homepage.writer.title': 'Showcase your universe and share your stories',
    'homepage.writer.writingTitle': 'Writing & creating made easy',
    'homepage.writer.writingDesc': 'Experience the new way of writing with Literary Universes Workshop. Create all the details of your universe in an encyclopedia to share with your readers and write amazing stories on that foundation.',
    'homepage.writer.collaborationTitle': 'Collaborative creation',
    'homepage.writer.collaborationDesc': 'Creative process often involves multiple people. No worries, we got you covered! You can easily add beta readers, co-authors and translators to your stories and universes.',
    'homepage.writer.communityTitle': 'Connect with Your readers',
    'homepage.writer.communityDesc': 'Go beyond writing and connect with your readers via blogs, forums and other community features connected to your universes or to you as a writer.',
    'homepage.writer.workshopFeatureTitle': 'One place for all your creative needs',
    'homepage.writer.workshopFeatureDesc': 'Our ever evolving workshop is the central place for your creative needs. From a simple idea create amazing universes, stories and everything else that is needed around it.',
    'homepage.writer.monetizationFeatureTitle': 'मोनेटाइजेशन',
    'homepage.writer.monetizationDesc': 'We strongly believe that people should be payed for their work and are constantly looking for new monetization opportunities for writers. Monetization feature allows you writers to be appreciated for what you do. Explore all the different options that allow your fans to show you their appreciation.',
    'homepage.writer.start': 'Setup Your workshop!',
    'homepage.featureSelection': 'Check out these popular universe!',
    'about.title': 'About Literary Universe',
    'about.desc': 'History, secrets and humans behind Literary Universe.',
    'about.text.1': 'लिटररी यूनिवर्स लेखकों और उत्साही पाठकों दोनों के लिए डिज़ाइन की गई है। लेखक डैशबोर्ड मेनू में "वर्कशॉप" बटन का चयन करके मूल रचनात्मक कार्य बना सकते हैं। यह मुख्य संपादक और संकलनिका के कार्यों का पहुंच प्रदान करता है, जो आपकी व्यक्तिगत कहानी यूनिवर्स के सभी पहलुओं को एक ही पेज पर व्यवस्थित करने पर केंद्रित है। सामाजिक सुविधाएँ लेखकों को अपना काम साझा करने, एक फॉलोइंग बनाने और अपने पाठकों के साथ अधिक सीधे रूप से बातचीत करने की अनुमति देती हैं, यदि वे चुनें।',
    'about.text.2': 'पाठक वेबसाइट का प्रमुख रूप से उपयोग नई रचनाओं की खोज करने और अपने पसंदीदा लेखकों का अनुसरण करने के लिए कर सकते हैं, लेकिन यदि लेखक द्वारा अनुमति दी जाती है तो वे प्री-प्रकाशित कहानियों का संपादन करने में भी मदद कर सकते हैं। Literary Universe पर एक पाठक होना एक पूरी नई पढ़ने की अनुभव प्रदान करता है— मुख्य कहानी के साथ ही सभी पृष्ठभूमि जानकारी तक पहुँच होने से लेखक के मन की सूचना प्राप्त होती है।',
    'about.text.3': 'Literary Universe के भविष्य में लेखक अपनी रचनाएँ बेच सकते हैं और लेखकों और पाठकों के बीच संचार को मजबूत करने के लिए समुदाय सुविधाएं जोड़ने की योजना है। हम समय के साथ अतिरिक्त लेखक के उपकरणों को पेश करने, जिनमें से अभी तक इकाइयां विकसित की जा रही हैं या योजित की गई हैं, जोड़ने की योजना बना रहे हैं। हमारा प्रमुख लक्ष्य इंटरनेट माध्यम का उपयोग करके लेखकों और पाठकों के अनुभव को योगदान करके बढ़ाना है।',
    'about.text.4': 'We hope that you join us as we explore what the internet medium can do for creative writing!',
    'about.team': 'The team',
    'about.history': 'History',
    'about.company': 'The company',
    'about.companyCountry.czechia': 'Czechia',
    'about.companyCountry.japan': 'Japan',
    'about.companyCity.prague': 'Prague',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Chief Executive Officer',
    'about.CTO': 'Chief Technology Officer',
    'about.jan': 'जैन साहित्यिक यूनिवर्स के संस्थापक, दृष्टिवान, और प्रौद्योगिकी की दिमागी शक्ति हैं। विस्तृत साहित्यिक यूनिवर्स के लेखक के रूप में, जैन को अक्षरशः टेक्निकल सटीकता के साथ पठनीयता को संतुलित ढंग से लिखने की समस्या होती थी, पाठक के अनुभव को प्रभावित किए बिना। इस चुनौती ने उन्हें वेब विकास में अध्ययन करने के लिए प्रेरित किया, जिसका लक्ष्य है बड़े संसार में कहानियां लिखने की प्रक्रिया को सरल बनाने वाला एक एप्लिकेशन बनाना।',
    'about.history.text': '2010 में, जैन ने वेब विकास के ज्ञान को गहराने के लिए रॉचेस्टर इंस्टीट्यूट ऑफ टेक्नोलॉजी में अपनी पढ़ाई शुरू की, जिसका उद्देश्य क्रिएटिव राइटिंग प्लेटफॉर्म बनाना था। यह विचार 2013 में अंतरिक्ष छापा गया था, जब प्राथमिकता का पहला सबूत इमेज़िन RIT में प्रस्तुत किया गया। जैन ने अपनी पढ़ाई जारी रखी, और 2016 में, एक नई संस्करण का ऐप उसके मास्टर्स कैपस्टोन परियोजना के रूप में बनाया गया। परियोजना 2016 के गिरफ़्त में और बढ़ते हुए इस समय देखने के लिए प्लेटफ़ॉर्म में विकसित हुआ।',
    'copyrights.desc': 'Information about Copyrights at Literary Universe.',
    'privacy.desc': 'Full legal text of Privacy Policy of Literary Universe.',
    'guidelines.desc': 'साहित्यिक यूनिवर्स के समुदाय दिशा-निर्देश।',
    'tos.desc': 'साहित्यिक यूनिवर्स के सेवा की नियमावली का पूरा कानूनी पाठ।',
    'homepage.intro': 'Let Your Creativity Run Wild Across the Literary Universe',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'Ever dreamt of developing a fictional world so detailed, even you get lost in it? At Literary Universe, we provide the tools to make this vision a reality. Every writer deserves access to top-notch resources and support. That\'s why we\'ve designed an all-inclusive space that bridges the gap between intricate storytelling and passionate reading. For writers, it\'s a dream workspace; for readers, an odyssey of exploration. Join us as we follow the literary rabbit hole to discover how far it leads us in the world of imagination.',
    'gdpr.title': 'जीडीपीआर संगठनात्मक अनुपालन',
    'gdpr.desc': 'साहित्यिक यूनिवर्स यूई जीडीपीआर निर्देशानुसार है।',
    'gdpr.compliant': 'साहित्यिक यूनिवर्स यूई जीडीपीआर नियमानुसार है।',
    'gdpr.compliant.text': 'साहित्यिक यूनिवर्स ने 25 मई 2018 को जीडीपीआर प्रशासन के लिए अपडेट और परिवर्तन किए हैं।',
    'common.legal.dmca': 'डीएमसीए',
    'common.legal.dmca.long': 'डिजिटल मिलेनियम कॉपीराइट एक्ट',
    'common.legal.changelog': 'इस संस्करण में परिवर्तन',
    'dmca.title': 'डिजिटल मिलेनियम कॉपीराइट एक्ट (डीएमसीए) नीति',
    'dmca.subtitle': 'कॉपीराइट विवाद नीति',
    'dmca.step1.title': 'कॉपीराइट उल्लंघन की रिपोर्ट करने की प्रक्रिया।',
    'dmca.step2.title': 'जब निर्दिष्ट प्रतिनिधि द्वारा उचित और विश्वसनीय उल्लंघन अधिसूचना प्राप्त की जाती है।',
    'dmca.step3.title': 'निर्दिष्ट प्रतिनिधि को काउंटर-नोटिस प्रदान करने की प्रक्रिया।',
    'dmca.desc': 'हम कॉपीराइट उल्लंघन को गंभीरता से लेते हैं।',
    'gdpr.access.title': 'पहुँच का अधिकार और डेटा पोर्टेबिलिटी का अधिकार',
    'gdpr.access.desc': 'उपयोगकर्ता सेटिंग में आप अपने सभी डेटा को निर्यात कर सकते हैं। यह डेटा मानक JSON प्रारूप में होगा।',
    'gdpr.forget.title': 'भूल जाने का अधिकार',
    'gdpr.forget.desc': 'उपयोगकर्ता सेटिंग के माध्यम से किसी भी खाता को हटा सकते हैं। कुछ डेटा संग्रहीत किए जा सकते हैं, विशेष रूप से अगर वे बिक्री और/या विवाद के विषय रहे हैं।',
    'gdpr.rectification.title': 'सुधार का अधिकार',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'प्रोसेसिंग की सीमा करने का अधिकार',
    'gdpr.processing.desc': 'लिटररी यूनिवर्स पूरी तरह से ब्राउज़र सेटिंग का सम्मान करता है, जैसे कि हमारे Matomo सांख्यिकी सर्वर को रिपोर्ट करने के लिए "ट्रैक न करें" अनुरोध।',
    'gdpr.object.title': 'आपत्ति का अधिकार',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'रिपोर्टिंग दो स्थितियों में विभाजित है। 1. आंतरिक संपत्ति (साइट पर मौजूद संपत्ति पर उल्लंघन)। 2. बाहरी संपत्ति (साइट पर मौजूद न होने वाली संपत्ति पर उल्लंघन)।',
    'dmca.step1.desc2': 'आंतरिक संपत्ति की रिपोर्टिंग संपत्ति पर रिपोर्ट बटन के माध्यम से की जा सकती है। बाहरी संपत्ति के उल्लंघन की रिपोर्टिंग सुझाव स्क्रीन के माध्यम से की जा सकती है। दोनों मामलों में आपसे व्यक्तिगत विवरण और अतिरिक्त विवरण पूछे जाएंगे जो हमें आपके स्वामित्व की जांच करने में सहायता करेंगे।',
    'dmca.step1.desc3': 'कृपया ध्यान दें कि झूठी दावा करने से आपकी भविष्य में दावे करने की असमर्थता होगी।',
    'dmca.step2.desc1': 'आपकी रिपोर्ट प्राप्त होने के बाद हम आपकी प्रमाणिकता और स्वामित्व दावे की पुष्टि करेंगे। यदि सब कुछ ठीक हो तो हम दावा की जांच करेंगे। यदि हम दावा को सत्य मानते हैं तो हम काउंटर-नोटिस के निर्धारण या 14 दिनों के बाद तक उस अधिकार वाली संपत्ति को अप्राप्य बना देंगे, जिसके बाद वह हटा दी जाएगी।',
    'dmca.step3.desc1': 'एक शिकायत प्राप्त होने के बाद निर्धारित संपत्ति के मालिक को 14 दिन का समय होगा काउंटर नोटिस दाखिल करने के लिए। निर्धारित एजेंट फिर विवाद की जांच करने के लिए आगे बढ़ेगा। इस चरण में निर्धारित एजेंट द्वारा लिया गया कोई भी निर्णय अंतिम होगा।',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'जन ड्वोराक',
    'about.attributions': 'श्रेय',
    'about.attributionsIntro': 'साहित्यिक यूनिवर्स बहुत सारे ओपन सोर्स प्रोजेक्ट्स और मुफ्त संसाधनों पर आधारित है। नीचे आपको उनकी सूची मिलेगी।',
    'about.attributionsMatomo': 'हमारा विश्लेषण स्व-होस्टेड Matomo उपयोग करता है जिसमें IP2Location LITE डेटा https://lite.ip2location.com से उपलब्ध होता है।',
    'team.name.pjakubec': 'पावेल जाकुबेक',
    'about.developer': 'डेवलपर',
    'about.seniorDeveloper': 'वरिष्ठ डेवलपर',
    'about.juniorDeveloper': 'जूनियर डेवलपर',
    'about.leadDesigner': 'Lead designer',
    'about.leadUX': 'Lead UX designer',
    'about.intern': 'इंटर्न',
    'about.advisor': 'सलाहकार',
    'about.headOfResearch': 'अनुसंधान के प्रमुख',
    'about.CFO': 'मुख्य वित्तीय अधिकारी',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry is a designer with more than 15 years experience. He\'s been working in agency since 2010, his client such as PERTAMINA, VOA, and Ministry tourism of Indonesia. Experienced in Branding, layout and also UI/UX he feels challenged to design Literary Universe.',
    'about.pavel': 'Web3, Metaverse, AI, और किसी भी उभरती हुई तकनीक— पावल इन सभी की जांच करते हैं और इसे लिटररी यूनिवर्स को कैसे बढ़ा सकता है, देखते हैं। एक सच्चे बहुविज्ञानिक शोधकर्ता के रूप में, पावल के पास कई क्षेत्रों में अंतर्दृष्टि है और प्लेटफ़ॉर्म में नए और रोचक सुविधाएँ जोड़ने पर काम करते हैं।',
    'copyrights.about': 'Literary Universe takes Copyright very seriously. All the content that is published by users is their own and available under the license that is specified. Beside the full set of Creative Commons licenses, Literary Universe also offers 2 commercial licenses, exclusive and non-exclusive.',
    'copyrights.nonExclusiveLicense': 'The Literary Universe Non-Exclusive License allows you to publish on Literary Universe without giving away any of your rights as the copyright holder. You are free to publish anywhere else. Literary Universe only reserves the right to use your IP for marketing purposes. If you decide to sell you IP on Literary Universe the platform will charge 30% platform fee.',
    'copyrights.exclusiveLicense': 'The Literary Universe Exclusive License allows you to publish on Literary Universe exclusively. That means you can\'t publish your IP on other online platforms or anything else outside of Literary Universe. If you want to publish a physical medium like a book you need to ask as for permission. If Literary Universe doesn\'t respond in 30 days then that is automatic consent. In the future we hope to offer you physical publishing and other services via our partners. Don\'t be afraid to contact us, we wish for your success and in most cases we are just looking out for fraudulent companies. Still this is restrictive, so as a thank you, the platform fee is only 10%.',
    'copyrights.licensesAreImportant': 'Choosing a license is extremely important and affects how your work will be accessed in the future. To make selection easier you can check out our license chooser bellow.'
};