export default {
    'workshop.title': 'आपका काम',
    'workshop.noneassigned': 'आपको अभी तक कोई काम नहीं दिया गया है।',
    'workshop.notavailable': 'यह सुविधा अभी तक उपलब्ध नहीं है।',
    'workshop.none': `आपके पास वर्तमान में कोई {type, select,
      universe {यूनिवर्स}
      story {कहानी}
      fanfiction {फैन फिक्शन}
      other {}
    }नहीं है। अब एक बनाएं!`,
    'workshop.collab': 'सहयोगी कार्य',
    'workshop.betareadings': 'बीटा पठन',
    'workshop.translations': 'अनुवाद',
    'workshop.createnew': 'नया बनाएँ...',
    'workshop.story.standalone': 'स्थानीय कहानी',
    'workshop.story.standalone.desc': 'यह एक स्थानीय कहानी है।',
    'workshop.controlpanel': '{name} नियंत्रण पट्टी',
    'workshop.universe.page': 'यूनिवर्स पेज',
    'workshop.fictionaltime': 'काल्पनिक समय',
    'workshop.dashboard.name': '{name} डैशबोर्ड',
    'workshop.stories.in': '{universe}कहानियाँ',
    'workshop.universe.nostories': 'इस यूनिवर्स में कोई कहानियाँ नहीं हैं।',
    'workshop.story.chapter.add': 'नया अध्याय',
    'workshop.universe.new': 'नया यूनिवर्स बनाएँ',
    'workshop.universe.publish': 'यूनिवर्स प्रकाशित करें',
    'workshop.universe.publishing.notice': 'यदि आप यूनिवर्स को प्रकाशित नहीं करते हैं, तो जब पहली कहानी जो यूनिवर्स से जुड़ी हो, प्रकाशित होगी तब यह स्वचालित रूप से प्रकाशित होगा।',
    'workshop.universe.settings': '{universe} यूनिवर्स सेटिंग्स',
    'workshop.universe.publishedOn': 'यह यूनिवर्स प्रकाशित किया गया है {date, date, long} {date, time, short}',
    'workshop.universe.description': 'यूनिवर्स विवरण',
    'workshop.settings.title': 'शीर्षक',
    'workshop.description': 'विवरण',
    'workshop.language.primary': 'प्राथमिक भाषा',
    'workshop.publication.options': 'प्रकाशन विकल्प',
    'workshop.rating': 'सामान्य रेटिंग',
    'workshop.universe.rating.desc': 'इस से ऊपर की कहानियाँ यूनिवर्स पेज सूची में छिपी रहेंगी जो गैर-पंजीकृत उपयोगकर्ताओं और उचित आयु वाले उपयोगकर्ताओं को दिखाई नहीं देंगी।',
    'workshop.universe.license': 'यूनिवर्स लाइसेंस',
    'workshop.universe.genre.pick': 'यूनिवर्स के लिए शैली का चयन करें',
    'workshop.story.genre.pick': 'कहानी के लिए शैलियों का चयन करें',
    'workshop.cover': 'कवर',
    'workshop.nothingtosee': 'यहाँ कुछ देखने लायक नहीं है...',
    'workshop.story.cannon': 'कैनन कहानी',
    'workshop.story.cannon.desc': 'यह कहानी {universe} यूनिवर्स में कैनन है।',
    'workshop.story.cannon.desc.create': 'यह कहानी {universe} यूनिवर्स में एक कैननिकल कहानी के रूप में बनाई जाएगी।',
    'workshop.story.fanfiction.search': 'यूनिवर्स का नाम टाइप करें (यह आपकी पुस्तकालय में होना चाहिए)। और फिर सुझाव से चुनें।',
    'workshop.story.error.nogenres': 'आपको कम से कम एक शैली का चयन करना होगा।',
    'workshop.story.error.toomanygenres': 'कहानी में केवल दो शैलियाँ अनुमति दी जाती हैं।',
    'workshop.story.error.fanfiction.selectuniverse': 'अपने फ़ैन फ़िक्शन के लिए मूल यूनिवर्स का चयन करना आवश्यक है!',
    'workshop.story.error.tags.toomany': 'प्रति कहानी में आपके पास केवल 10 टैग हो सकते हैं।',
    'workshop.story.new': 'एक नई कहानी बनाएँ',
    'workshop.story.publishing.notice': 'पहले अध्याय प्रकाशित करने पर कहानी स्वचालित रूप से प्रकाशित हो जाएगी।',
    'workshop.settings.edit': 'सेटिंग्स संपादित करें',
    'workshop.story.publishedOn': 'यह कहानी प्रकाशित की गई है {date, date, long} {date, time, short}',
    'workshop.story.settings': 'कहानी सेटिंग्स',
    'workshop.settings.basic': 'मूल सेटिंग्स',
    'workshop.settings.genres': 'शैलियाँ (अधिकतम 2)',
    'workshop.story.license': 'कहानी का लाइसेंस',
    'workshop.story.settings.universe': 'यूनिवर्स सेटिंग्स',
    'workshop.settings.tags': 'टैग',
    'workshop.revision': 'संशोधन',
    'workshop.revisions.title': '{story}: {chapter} संशोधन',
    'workshop.revisions.current': 'वर्तमान ड्राफ़्ट',
    'workshop.revisions.new.beta': 'ड्राफ़्ट से एक नई संशोधन बनाएँ।',
    'workshop.revisions.new.public': 'ड्राफ़्ट से एक नई सार्वजनिक संशोधन बनाएँ।',
    'workshop.revisions.toeditor': 'संपादक में जाएँ',
    'workshop.revisions.comments': 'संशोधन टिप्पणियाँ',
    'workshop.revisions.comments.title': '{story}: {chapter} - संशोधन {revision} - टिप्पणियाँ',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {बीटा पाठकों के लिए}
      readers {सार्वजनिक}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'आपको पहले संशोधन बनाना होगा।',
    'workshop.revisions.comments.select': 'चयन करें',
    'workshop.collaborators.noresults': 'कोई परिणाम नहीं',
    'workshop.collaborators.add.beta': 'बीटा पाठक जोड़ें',
    'workshop.collaborators.add.collaborator': 'सहयोगी जोड़ें',
    'workshop.collaborators.add.translator': 'अनुवादक जोड़ें',
    'workshop.collaborators.language.add': 'नया अनुवाद बनाएं',
    'workshop.translations.stories': 'अनुवाद - कहानियाँ',
    'workshop.translations.universes': 'अनुवाद - विश्व',
    'workshop.revisions.beta.none': 'इस समय कोई संशोधन नहीं हैं।',
    'reader.asidetoggle': 'अलावा जानकारी टॉगल करें',
    'workshop.translation.original': 'मूल:',
    'workshop.translation.original.title': 'मूल शीर्षक:',
    'workshop.translation.original.description': 'मूल विवरण:',
    'workshop.translation.original.cover': 'मूल कवर',
    'workshop.translation.original.tags': 'मूल टैग',
    'workshop.cover.alt': 'कवर छवि',
    'workshop.translation.updatedOrig': 'मूल की अंतिम अपडेट: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'अनुवाद की अंतिम अपडेट: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'मूल की अंतिम संशोधन {revision, number}, : {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'अनुवाद की अंतिम संशोधन {revision, number}, : {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `अधिक {type, select,
    collaborator {सहयोगी}
    beta {बीटा पाठक}
    translator {अनुवादक}
    other {}
  }जोड़ने के लिए, आपको अपने सदस्यता टियर को बढ़ाना होगा।`,
    'workshop.collaborators.requests.sent': 'भेजे गए अनुरोध',
    'workshop.collaborators.requests.invite': `आपको निम्नलिखित के लिए आमंत्रित किया गया है {role, select,
    beta {बीटा पाठक}
    translator {अनुवादक}
    collaborator {सहयोगी}
    other {}
  } बनने के लिए:`,
    'workshop.collaborators.requests.dashboard': `आपको आमंत्रित किया गया है कि आप सहयोग करें {count, plural,
    zero {कोई काम नहीं}
    one {एक साहित्यिक कार्य}
    other {# साहित्यिक कार्य}
  }.`,
    'workshop.collaborators.language.added': 'भाषा जोड़ी गई',
    'workshop.story.noChaptersFound': 'कोई अध्याय नहीं मिला।',
    'workshop.fanfic.needUniverseInLibrary': 'वहां बहुत सारे ब्रह्मांड हैं। कृपया पहले उन ब्रह्मांडों को अपनी पुस्तकालय में जोड़ें जिनमें आप लिखना चाहते हैं, ताकि हम उन्हें ढूंढ सकें।',
    'workshop.fanfic.findUniverse': 'एक अद्भुत ब्रह्मांड ढूंढ़ें!',
    'workshop.encSettings': 'विज्ञानकोश सेटिंग्स',
    'workshop.collaborators.removeUser': 'उपयोगकर्ता हटाएं',
    'workshop.collaborators.cancelInvite': 'आमंत्रण रद्द करें',
    'workshop.universe.createFirstStory': 'पहली कहानी बनाएं',
    'workshop.storylines': 'कहानी की रेखाएँ',
    'workshop.scenesManager': 'सीन मैनेजर',
    'workshop.collaborators.addRoleForLang': '{language}के लिए {role} जोड़ें',
    'workshop.beta.revisionInfo': 'यह संशोधन है {revision, number}, {createdAt, date, long}को बनाया गया।',
    'workshop.story.notes.title': '{storyTitle}के लिए आपके नोट्स',
    'workshop.story.notes.desc': 'कहानी के बारे में अवलोकन नोट्स।',
    'workshop.story.notes.tile': 'अवलोकन नोट्स',
    'workshop.hideOrgs': 'संगठनों से सामग्री छिपाएं',
    'workshop.translation.premium': 'अनुवाद जोड़ने के लिए, आपके पास कम से कम एक एक्सप्लोरर सदस्यता होनी चाहिए।',
    'workshop.story.finished': 'कहानी पूरी है',
    'workshop.story.publishing.externalSellingNotice': 'क्योंकि आप साहित्यिक ब्रह्मांड के बाहर बेच रहे हैं, इसलिए आप अब कहानी प्रकाशित कर सकते हैं। आपके स्टोर लिस्टिंग के लिंक कहानी पर या जो वर्तमान में आप यहां प्रकाशित कर रहे हैं, उसके अंत में दिखाए जाएंगे।',
    'workshop.sharing.publicURL': 'सार्वजनिक संस्करण',
    'workshop.fictionalTime.title': '{universeName}के लिए कालकारिता समय',
    'workshop.fictionalTime.none': 'आपके पास वर्तमान में कोई काल्पनिक समय सेट नहीं है।',
    'workshop.fictionalTime.createNow': 'अब एक बनाएँ!',
    'workshop.fictionalTime.createTitle': 'एक नया काल्पनिक समय बनाएँ',
    'workshop.fictionalTime.editTitle': 'संपादित करें {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'समय का नाम',
    'workshop.fictionalTime.basicInfo': 'मूलभूत जानकारी',
    'workshop.fictionalTime.timeSetup': 'समय सेटअप',
    'workshop.fictionalTime.linkedToET': 'क्या यह समय पृथ्वी की तारीख (ग्रीगोरियन कैलेंडर) पर शुरू होता है?',
    'workshop.fictionalTime.timeDeclaration': 'समय घोषणा',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'इकाईयों से पहले',
    'workshop.fictionalTime.declarationAfter': 'इकाईयों के बाद',
    'workshop.fictionalTime.declarationNone': 'कोई नहीं',
    'workshop.fictionalTime.units': 'इकाईयाँ',
    'workshop.fictionalTime.ETStart': 'इस समय की प्रारंभिक तारीख',
    'workshop.fictionalTime.unitsDescFirst': 'मिलीसेकंड से इस इकाई में कितनी इकाईयाँ हैं?',
    'workshop.fictionalTime.unitsDesc': 'पिछली इकाई से इस इकाई में कितनी इकाईयाँ हैं?',
    'workshop.fictionalTime.unitsName': 'इकाई का नाम',
    'workshop.fictionalTime.unitsSeparator': 'पिछली इकाई से विभाजक',
    'workshop.fictionalTime.unitAdd': 'इकाई जोड़ें',
    'workshop.fictionalTime.clocks': 'घड़ियाँ',
    'workshop.fictionalTime.unitTransfer': 'इकाइयों को स्थानांतरित करें',
    'fictionalTime.pageStartElapsedTime': 'इस पेज को खोलने के बाद से बिता हुआ समय',
    'fictionalTime.currentTime': 'वर्तमान समय',
    'workshop.shoppingExternal.options': 'बाहरी खरीदारी विकल्प',
    'workshop.shoppingExternal.explainer': 'यदि आपकी कहानी कहीं और बिक रही है तो आप यहां लिंक सेट कर सकते हैं। लिंक तो फिर आपके द्वारा चुने गए सामग्री की जगह दिखाई देंगे या सामग्री के अंत में दिखाई देंगे।',
    'workshop.shoppingExternal.amazonStore': 'अमेज़न स्टोर',
    'workshop.shoppingExternal.amazon': 'अमेज़न',
    'workshop.shoppingExternal.storeName': 'स्टोर का नाम',
    'workshop.shoppingExternal.itemUrl': 'आइटम URL',
    'workshop.shoppingExternal.storesOther': 'अन्य स्टोर',
    'fictionalTime.units.milliseconds': '{units, number} मिलीसेकंड',
    'fictionalTime.countdownToStart': 'शुरुआत के लिए उलटी गिनती',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 दिन }
      other {{days} दिन }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {सेकंड}
      other {सेकंड}
    }}
    minutes {{units, plural,
      one {मिनट}
      other {मिनट}
    }}
    hours {{units, plural,
      one {घंटा}
      other {घंटे}
    }}
    days {{units, plural,
      one {दिन}
      other {दिन}
    }}
    years {{units, plural,
      one {साल}
      other {साल}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'से',
    'fictionalTime.inputSelectTimeUnit': 'समय इकाई का चयन करें',
    'fictionalTime.inputSelectETUnit': 'पृथ्वी की समय इकाई का चयन करें',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'साइडबार टूलबॉक्स',
    'workshop.writerSidebar.description': 'अपनी कहानी में आपका स्वागत है! यह साइडबार आपको आपकी कहानी से संबंधित सभी संसाधनों तक आसानी से पहुंच देता है। नवीनतम टिप्पणियों, आपके नोट्स और बहुत कुछ देखने के लिए ऊपर दिए गए आइकन की जाँच करें!',
    'workshop.story.authorsNotesExplained': 'अपने नोट्स पाठकों के लिए जो अध्याय की शुरुआत में पढ़ने के लिए होंगे।',
    'workshop.story.chapterSortSwitch': 'अध्याय की क्रम बदलें',
    'workshop.universe.monetizationTitle': '{title} मोनेटाइज़ेशन',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} मोनेटाइज़ेशन',
    'workshop.universe.monetizationWebMonetization': 'वेब मोनेटाइजेशन',
    'workshop.webMonetization.explain': 'वेब मोनेटाइज़ेशन आपको यूजर के सामग्री पर बिताने के आधार पर भुगतान स्ट्रीम करेगा। आप अपने प्रोफ़ाइल मोनेटाइज़ेशन सेटिंग्स में अपना भुगतान पॉइंटर सेट कर सकते हैं। यहां आप वेब पेमेंट सक्षम करने वाले सहयोगियों के साथ अपने साथी विभाजन पर निर्णय ले सकते हैं। Literary Universe स्वचालित रूप से 10% ले लेता है।',
    'workshop.webMonetization.revShare': 'वेब मोनेटाइज़ेशन की सीमा के कारण, प्रायिकतात्मक राजस्व बाँटवारे का उपयोग किया जाता है। प्रायिकतात्मक राजस्व बाँटवारे कार्य इस प्रकार करता है कि हर बार जब एक वेब मोनेटाइज़ेशन योग्य आगंतुक आपके पेज को लोड करता है, तो पहले से निर्धारित भुगतान पॉइंटरों की सूची से यादृच्छिक रूप से चुनता है। आगंतुक चुने हुए पॉइंटर को पेज रीलोड या बंद होने तक भुगतान करता है।',
    'workshop.webMonetization.revShareMore': 'प्रायिकतात्मक राजस्व बाँटवारे के बारे में और अधिक जानें। हम उस पृष्ठ पर दिए गए कोड का ही उपयोग करते हैं।',
    'workshop.story.notEligible.licence': `कहानी का लाइसेंस मोनेटाइज़ेशन के लिए अनुमति नहीं देता है।`,
    'workshop.universe.notEligible.licence': `यूनिवर्स का लाइसेंस मोनेटाइज़ेशन के लिए अनुमति नहीं देता है।`,
    'workshop.story.notEligible.fanFiction': 'फ़ैन फ़िक्शन कहानियों को मोनेटाइज़ेशन के लिए योग्य नहीं माना जाता है।',
    'workshop.revShare.mustBe100': 'बाँटवारा 100% के बराबर होना चाहिए',
    'workshop.revShare.LUCut': 'लिटररी यूनिवर्स और भुगतान गेट',
    'workshop.revShare.unallocated': 'अप्रविष्टित बाँटवारा {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'अनिर्णय',
    'workshop.revShare.origLangCreators': 'मूल भाषा के निर्माता',
    'workshop.story.prolog': 'प्रोलॉग',
    'workshop.story.chapter': 'अध्याय {sequence, number}',
    'workshop.work.includesAds': 'क्या कार्य में कोई विज्ञापन या उत्पाद स्थानन प्रारूपण है?',
    'workshop.universe.forumSettings': 'आंतरिक ब्रह्मांड फोरम सेटिंग्स',
    'workshop.universe.forum': 'आंतरिक {universeName} फोरम',
    'workshop.ratingAdjusted': 'शिकायतों के कारण हमें आपकी रेटिंग को उस एक के साथ समायोजित करना पड़ा जो हमें उचित लगी। इस प्रकार रेटिंग बदलना अब अक्षम हो गया है।',
    'workshop.selectCollaborator': 'सहयोगी का चयन करें',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'ड्राफ़्ट',
    'workshop.chapterStatus.scheduled': 'निर्धारित',
    'workshop.chapterStatus.published': 'प्रकाशित',
    'workshop.story.continuedIn': 'कौन सी कहानियाँ इस कहानी को जारी रखती हैं?',
    'workshop.story.continuedPlaceholder': 'इस यूनिवर्स से कहानी का चयन करें',
    'workshop.universe.isAIGenerated': 'क्या यूनिवर्स की सामग्री AI द्वारा उत्पन्न की जाती है?',
    'workshop.universe.isAIGeneratedTooltip': 'कृपया हमें बताएं कि क्या यूनिवर्स की सामग्री में AI द्वारा या AI की सहायता से कुछ उत्पन्न किया गया है। हम इस जानकारी का उचित लेबलिंग के लिए उपयोग करते हैं और AI कार्यक्रमों के उत्पन्न होने के कारण कुछ सीमाएं और प्रतिबंध हो सकते हैं।',
    'workshop.story.isAIGenerated': 'क्या कहानी AI द्वारा उत्पन्न हुई है?',
    'workshop.story.isAIGeneratedTooltip': 'कृपया हमें बताएं कि क्या कहानी में AI द्वारा या AI की सहायता से कुछ उत्पन्न किया गया है। हम इस जानकारी का उचित लेबलिंग के लिए उपयोग करते हैं और AI कार्यक्रमों के उत्पन्न होने के कारण कुछ सीमाएं और प्रतिबंध हो सकते हैं।',
    'workshop.publicationAgreement.aria': 'कार्य के लिए प्रकाशन समझौता',
    'workshop.publicationAgreement.intro': 'हमें खुशी है कि आपने हमारे साथ अपने रचनात्मक काम का प्रकाशन चुना है। आगे बढ़ने से पहले हमें बस इस प्रकाशन समझौते पर नज़र डालने की आवश्यकता है, ताकि आपको कानूनी मामलों की दृष्टि से इसका क्या मतलब है समझ में आ सके।',
    'workshop.sortChapters': 'क्रमबद्ध करें:',
    'workshop.sortChapters.ascending': 'शुरुआत से',
    'workshop.sortChapters.descending': 'नवीनतम से',
    'workshop.sortChapters.aria': 'अध्याय सूची को किस तरह से क्रमबद्ध करना है, उसके लिए चुनें',
    'workshop.hiatus.btn': 'कहानी की स्थिति को रोकथाम पर बदलें',
    'workshop.cancelled.btn': 'कहानी की स्थिति को रद्द करें',
    'workshop.complete.btn': 'कहानी की स्थिति को पूर्ण करें',
    'workshop.statusChange.modalTop': 'क्या आप वाकई स्थिति को बदलना चाहते हैं',
    'workshop.statusName.hiatus': 'रोकथाम',
    'workshop.statusName.cancelled': 'रद्द किया गया',
    'workshop.statusName.completed': 'पूरा हुआ',
    'workshop.statusExplain.hiatus1': 'रोकथाम का मतलब है कि आप इस कहानी पर कुछ समय के लिए काम करना छोड़ रहे हैं किसी भी कारण से। यह आपके पाठकों को बताएगा कि वे आने वाले हफ्तों या कुछ महीनों तक किसी नई अद्यतन की उम्मीद न करें।',
    'workshop.statusExplain.hiatus2': 'यदि आप कोई अध्याय प्रकाशित करते हैं तो रोकथाम स्थिति स्वचालित रूप से हटा दी जाएगी। या आप इसे खुद बदल सकते हैं।',
    'workshop.statusExplain.hiatus3': 'यदि आप अपनी कहानी को छह महीने तक रोकथाम में रखते हैं, तो हम यह कहानी स्वचालित रूप से रद्द कर देंगे।',
    'workshop.statusExplain.cancelled1': 'हमें यह दुख है कि आप कहानी पर काम जारी नहीं रख सकते। दूसरी ओर हमें यह खुशी है कि आप अपने पाठकों को बताने के लिए तैयार हैं।',
    'workshop.statusExplain.cancelled2': 'कहानी को रद्द करने से आपके पाठकों को यह पता चलेगा कि वे किसी नई अद्यतन की उम्मीद न करें।',
    'workshop.statusExplain.cancelled3': 'आप हमेशा इसे प्रकाशित करके या स्थिति बदलकर इसे पुनः प्रारंभ कर सकते हैं।',
    'workshop.statusExplain.finished1': 'बधाई हो! सारी उच्च कठिनाईयों के बावजूद, आपने अंदरूनी यात्रा का अंत अंततः कर लिया है। हालांकि कहानी अब समाप्त हो सकती है, हमें आशा है कि भविष्य में कहानियाँ और भी होंगी, लेकिन अब आराम करें और अर्जित आराम का आनंद लें।',
    'workshop.statusExplain.finished2': 'कहानी को पूर्ण मानकर पाठकों को बताएगा कि कहानी समाप्त हो गई है। जबकि आपको कोई नया अध्याय जोड़ना नहीं चाहिए, हम आपको रोक नहीं देंगे और सभी पात्रों के लिए अतिरिक्त अध्याय जोड़ना एक बुरी विचार नहीं है, जैसे कि सभी पात्रों के लिए अतिरिक्त उपन्यास।',
    'workshop.statusExplain.finished3': 'इस स्थिति को रद्द करने के बावजूद आप हमें इसके खिलाफ सलाह देते हैं। यदि कहानी जारी रखनी है तो एक नई कहानी शुरू करना बेहतर हो सकता है।',
    'workshop.status.goActive': 'कहानी को फिर से सक्रिय करें',
    'workshop.statusChangeEmail.storyIntro': 'हम आपको सूचित करना चाहेंगे कि आपकी कहानी:',
    'workshop.statusChangeEmail.hiatusTitle': 'आपकी कहानी की स्थिति स्वचालित रूप से हायेटस पर सेट की गई है',
    'workshop.statusChangeEmail.hiatusIntro': 'निष्क्रियता के कारण आपकी कहानी की स्थिति स्वचालित रूप से हायेटस पर सेट की गई है।',
    'workshop.statusChangeEmail.hiatusWhy': '6 महीनों से अधिक समय तक कोई नया अध्याय प्रकाशित नहीं होने के कारण यह स्वचालित रूप से हायेटस पर रख दी गई है।',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'यदि आप एक नया अध्याय प्रकाशित करते हैं तो यह स्थिति स्वचालित रूप से समाप्त हो जाएगी। यदि आप अगले 6 महीनों में कोई नया अध्याय प्रकाशित नहीं करते हैं, तो हम स्वचालित रूप से कहानी को रद्द कर देंगे।',
    'workshop.statusChangeEmail.cancellationIntro': 'आपकी कहानी की स्थिति स्वचालित रूप से रद्द कर दी गई है।',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'यदि आप इस कहानी पर और काम नहीं करने का इरादा रखते हैं, तो आपको कुछ और करने की आवश्यकता नहीं है।',
    'workshop.startCreating': 'सृजन शुरू करें',
    'workshop.ownWork': 'अपना काम',
    'workshop.list.thumbs': 'थंबनेल सूची',
    'workshop.list.list': 'संक्षेप सूची',
    'workshop.fanfiction.new': 'एक नई फैन फिक्शन बनाएं',
    'workshop.videoTrailerLink': 'वीडियो ट्रेलर लिंक',
    'workshop.videoTrailerPlayerTitle': 'स्टोरी वीडियो ट्रेलर प्लेयर',
    'workshop.videoTrailer.supportedPlaftorms': 'हम Youtube, Vimeo और Odysee का समर्थन करते हैं',
    'workshop.videoTrailer.rumble': 'हम रंबल का समर्थन भी करते हैं, लेकिन याद रखें कि IFRAME URL की प्रतिलिपि करें।',
    'workshop.videoTrailer.suggestPlatforms': 'क्या आपके वीडियो प्लेटफ़ॉर्म में कोई कमी है, हमें हमारे <a>सुझाव</a> के माध्यम से बताएं!',
    'workshop.cover.edit': 'Change cover',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.'
};