export default {
    'writer.menu.optionsAria': 'एडिटर विकल्प मेनू',
    'writer.menu.saveOptionsAria': 'विकल्प सहेजें',
    'writer.undo': 'पूर्ववत करें',
    'writer.redo': 'पुनः करें',
    'writer.ul': 'अव्यवस्थित सूची',
    'writer.ol': 'क्रमित सूची',
    'writer.blockquote': 'उद्धरण',
    'writer.link': 'लिंक डालें',
    'writer.image': 'तस्वीर डालें',
    'writer.bold': 'चयन को बोल्ड करें',
    'writer.underline': 'चयन को अंडरलाइन करें',
    'writer.italic': 'चयन को महत्वपूर्ण बनाएं',
    'writer.align.left': 'Align left',
    'writer.align.center': 'Align center',
    'writer.align.right': 'Align right',
    'writer.align.justify': 'Justify',
    'writer.wordCount': '{characters, number} अक्षर, {words, number} शब्द',
    'writer.characterCount': '{characters, number} अक्षर',
    'finder.details': 'विवरण',
    'finder.remove': 'कनेक्शन हटाएं',
    'finder.connect': 'चयन को विज्ञानकोष प्रविष्टि से जोड़ें',
    'writer.aside.ariaLabel': 'मदद विकल्प मेनू',
    'writer.aside.todo': 'Todo & Tasks',
    'writer.aside.ai': 'AI Assistant',
    'writer.todo.title': 'Writing Progress & Goals',
    'writer.todo.description': 'Track your writing tasks and goals for this chapter.',
    'writer.todo.currentChapter': 'Current Chapter ({sequence})',
    'writer.todo.currentStatus': 'Current Status',
    'writer.todo.currentCount': 'Current chapter: {count, number} {unit}',
    'writer.todo.storyAverage': 'Your average chapter length: {count, number} {unit}',
    'writer.todo.recommendations': 'Recommended Chapter Lengths',
    'writer.todo.recommendation': '{label}: {count, number} {unit}',
    'writer.todo.recommendation.progress': 'Progress: {current, number} / {target, number} {unit} ({percent, number}%)',
    'writer.todo.dailyPublishing': 'Daily publishing',
    'writer.todo.dailyTooltip': 'For stories published every day. Shorter chapters help maintain daily engagement and work well for serialized content.',
    'writer.todo.biDailyPublishing': 'Bi-daily publishing',
    'writer.todo.biDailyTooltip': 'For stories published 3-4 times per week. Balanced length that allows for detailed storytelling while maintaining reader engagement.',
    'writer.todo.weeklyPublishing': 'Weekly publishing',
    'writer.todo.weeklyTooltip': 'For stories published once per week. Longer chapters allow for more complex plots and character development.',
    'writer.todo.monthlyPublishing': 'Monthly publishing',
    'writer.todo.monthlyTooltip': 'For stories published once per month. Much longer chapters suitable for in-depth storytelling and complex narratives.',
    'writer.nothingToSave': 'कोई बचाने के लिए कुछ नहीं है',
    'writer.link.placeholder': 'Enter a URL',
    'writer.link.error.empty': 'URL cannot be empty',
    'writer.link.error.invalid': 'Please enter a valid URL',
    'writer.fontFamily': 'Font Family',
    'writer.fontFamily.select': 'Select font',
    'writer.image.upload': 'Upload Image',
    'writer.image.uploading': 'Uploading image...',
    'writer.image.error.type': 'Only JPEG, PNG, and WebP images are supported',
    'writer.image.error.size': 'Image must be less than 5MB',
    'writer.image.error.upload': 'Failed to upload image. Please try again.',
    'writer.publish.publishAria': 'प्रकाशन विकल्प',
    'writer.publish.scheduleExplained': 'आप या तो तुरंत प्रकाशित कर सकते हैं या चैप्टर को एक बाद में उपलब्ध करने के लिए शेड्यूल कर सकते हैं।',
    'writer.publish.schedule': 'प्रकाशन तिथि समय सेट करें',
    'writer.publish.previousChapterPublished': 'पिछला चैप्टर प्रकाशित किया गया था {publishDate, date, short} पर {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'पिछला चैप्टर शेड्यूल किया गया है {publishDate, date, short} पर {publishDate, time}',
    'writer.publish.alreadyPublished': 'यह चैप्टर पहले से ही {publishedAt, date, short}पर प्रकाशित किया गया था। नई संस्करण तुरंत प्रकाशित किए जाएंगे।',
    'writer.publish.betaReader': 'बीटा',
    'writer.publish.betaReader.original': 'Beta (Original)',
    'writer.publish.public': 'प्रकाशित करें',
    'writer.publish.publish': 'Publish',
    'writer.publish.publish.original': 'Publish (Original)',
    'writer.publish.now': 'Publish now',
    'writer.publish.moreOptions': 'More save options',
    'writer.publish.schedulePrevious': 'You need to publish or schedule publication of previous chapter before you can publish this one.',
    'writer.publish.earlyAccess.title': 'Early access for fans',
    'writer.publish.earlyAccess.groupLine': '{days} days early: {tiers} — fans get access on {date, date, short} at {date, time}',
    'writer.initialLetter': 'Initial Paragraph Letter'
};