export default {
    'writer.menu.optionsAria': 'एडिटर विकल्प मेनू',
    'writer.menu.saveOptionsAria': 'विकल्प सहेजें',
    'writer.undo': 'पूर्ववत करें',
    'writer.redo': 'पुनः करें',
    'writer.ul': 'अव्यवस्थित सूची',
    'writer.ol': 'क्रमित सूची',
    'writer.blockquote': 'उद्धरण',
    'writer.link': 'लिंक डालें',
    'writer.image': 'तस्वीर डालें',
    'writer.bold': 'चयन को बोल्ड करें',
    'writer.underline': 'चयन को अंडरलाइन करें',
    'writer.italic': 'चयन को महत्वपूर्ण बनाएं',
    'writer.wordCount': '{characters, number} अक्षर, {words, number} शब्द',
    'writer.characterCount': '{characters, number} अक्षर',
    'finder.details': 'विवरण',
    'finder.remove': 'कनेक्शन हटाएं',
    'finder.connect': 'चयन को विज्ञानकोष प्रविष्टि से जोड़ें',
    'writer.aside.ariaLabel': 'मदद विकल्प मेनू',
    'writer.nothingToSave': 'कोई बचाने के लिए कुछ नहीं है',
    'writer.link.placeholder': 'Enter a URL',
    'writer.link.error.empty': 'URL cannot be empty',
    'writer.link.error.invalid': 'Please enter a valid URL',
    'writer.publish.publishAria': 'प्रकाशन विकल्प',
    'writer.publish.scheduleExplained': 'आप या तो तुरंत प्रकाशित कर सकते हैं या चैप्टर को एक बाद में उपलब्ध करने के लिए शेड्यूल कर सकते हैं।',
    'writer.publish.schedule': 'प्रकाशन तिथि समय सेट करें',
    'writer.publish.previousChapterPublished': 'पिछला चैप्टर प्रकाशित किया गया था {publishDate, date, short} पर {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'पिछला चैप्टर शेड्यूल किया गया है {publishDate, date, short} पर {publishDate, time}',
    'writer.publish.alreadyPublished': 'यह चैप्टर पहले से ही {publishedAt, date, short}पर प्रकाशित किया गया था। नई संस्करण तुरंत प्रकाशित किए जाएंगे।',
    'writer.publish.betaReader': 'बीटा',
    'writer.publish.public': 'प्रकाशित करें',
    'writer.publish.now': 'Publish now',
    'writer.publish.schedulePrevious': 'You need to publish or schedule publication of previous chapter before you can publish this one.'
};