export default {
    'feedback.home': 'உதவி மையம்',
    'feedback.bugs': 'பிழைகள்',
    'feedback.bugs.desc': 'பிழை அல்லது மற்ற தவறு என்னை சந்திக்கின்றதா? இங்கே தெரிவிக்கவும்!',
    'feedback.features': 'கருத்துகளும் முன்னுரிமைகளும்',
    'feedback.features.desc': 'புதிய அம்சங்களுக்கான கருத்துகள் அல்லது இணையத்தை மேம்படுத்த எவ்வாறு என்னை செய்ய முடியும்? தெரிவிக்கவும்!',
    'feedback.help': 'உதவி மற்றும் பயிற்சிகள்',
    'feedback.help.desc': 'நீங்கள் எப்படி _____செய்வது? பதில்களைக் கண்டுபிடிக்க இங்கே செல்லவும்.',
    'feedback.desc': 'எங்கள் உதவி மற்றும் தீர்வு மையத்திற்கு வரவேற்கிறோம்!',
    'feedback.faq': 'கேள்விகள் மற்றும் பதில்கள்',
    'feedback.faq.desc': 'அடிப்படைப் பொது கேள்விகள்',
    'feedback.open': 'திறக்கப்பட்டது',
    'feedback.closed': 'மூடப்பட்டது',
    'feedback.accepted': 'ஏற்கப்பட்டது',
    'feedback.inprogress': 'செயல்படுகின்றது',
    'feedback.completed': 'முடிந்தது',
    'feedback.fixed': 'சரிசெய்யப்பட்டது',
    'feedback.new.bugs': 'புதிய பிழையைப் புகாரளிக்கவும்',
    'feedback.new.features': 'புதிய அம்சத்தை பரிந்துரைக்கவும்',
    'feedback.lang.nosupport': 'உங்கள் தற்போதைய மொழி பின்னர் பின்னர் உதவிக்கு ஆதரவாகவில்லை, தயவுகூர்ந்து ஆங்கிலத்தில் எழுதுங்கள். நன்றி!',
    'feedback.new.thanks': 'அறிவிப்புக்கு நன்றி! நாம் மிகவும் விரைவில் அதைப் பார்க்கும்.',
    'feedback.comment.title': 'கருத்து',
    'feedback.comment.desc': 'உங்கள் அறிவிப்பை எங்களுக்கு அனுப்புங்கள்',
    'feedback.comment.legend': 'உங்கள் அறிவிப்பு - எந்த பொருளையும் எங்களுக்கு தெரிவிக்கவும்',
    'feedback.comment.success': 'உங்கள் அறிவிப்புக்கு நன்றி!',
    'feedback.comment.label': 'உங்கள் கருத்து',
    'feedback.copyrightReport.title': 'பதிப்பாக்கல் மீறல்',
    'feedback.copyrightReport.desc': 'பதிப்பாக்கல் மீறலை புகாரளிக்கவும்',
    'feedback.report.noUser': 'அறிவிப்பை பதிவு செய்ய நீங்கள் உள்நுழைய வேண்டும்.',
    'feedback.voting.totalVoters': 'பயனர்கள் வாக்களித்தனர்: {voted, number}',
    'feedback.voting.upvote': 'மேலே வாக்கு',
    'feedback.voting.downvote': 'கீழே வாக்கு',
    'feedback.voting.score': 'மொத்த மதிப்பு',
    'feedback.report.title': 'அறிக்கையை பதிவு செய்யுங்கள்',
    'feedback.report.typeSelect': 'இங்கே ஏதாவது பிரச்சனை உள்ளதா?',
    'feedback.reportType.law': 'சட்டம் மீறல்',
    'feedback.reportType.vulgar': 'அழகான/அரசியலாளர் மொழிபெயர்ப்பு',
    'feedback.reportType.copyright': 'பதிப்புரிமை மீறல்',
    'feedback.reportType.storyRating': 'தவறான வயது மதிப்பு',
    'feedback.reportType.scam': 'பாத்திரம்',
    'feedback.report.submit': 'அறிக்கை',
    'feedback.report.submitting': 'அறிக்கை செய்கிறது...',
    'feedback.report.violationDesc': 'விவரங்கள்',
    'feedback.report.reportSaved': 'அறிவிப்புக்கு நன்றி! நாங்கள் சந்தேகம் செய்யும் மற்றும் தீர்வு எடுக்கப்பட்டால் நடவடிக்கை எடுக்கும்.',
    'feedback.report.copyrightReportSaved': 'அறிவிப்புக்கு நன்றி! நாங்கள் சந்தேகம் செய்யும் மற்றும் தொடர்பு கொள்வோம்.',
    'feedback.report.copyrightOwnershipDesc': 'உரிமை அறிப்பு',
    'feedback.report.copyrightNotice': 'தயவுசெய்து இந்த படிவத்தைப் பயன்படுத்துவதற்கு நீங்கள் தமிழ் உலாவியில் உள்ள உரிமையாளர் ஆக வேண்டும். நீங்கள் உரிமையாளர் அல்லது உரிமையாளராக இல்லையானால், தயவுசெய்து உரிமையாளருக்கு அறிவிக்க அல்லது மற்ற வகையில் எங்களுக்கு அறிவிக்க பயன்படுத்துகின்றோம். நாங்கள் பதிலளிக்கும் முடிவுகளை மிகுந்த முடிவுகளாக எடுக்கின்றோம்.',
    'feedback.report.copyrightInternalProperty': 'நான் இந்த பணியத்தை இலக்கணக்கல் உலாவியில் வெளியிட்டுள்ளேன்',
    'feedback.reportType.spam': 'அஞ்சல் அல்லது பிஷிங்',
    'feedback.reportType.other': 'மற்றவை',
    'feedback.report.copyrightType.propertySelectLabel': `எந்த {type, select,
    universe {உலகம்}
    story {கதை}
    other {கதை}
  } மீட்டப்படுகிறது?`,
    'faq.section.about': 'எங்களை பற்றி',
    'faq.section.settings': 'அமைப்புகள்',
    'faq.section.discovery': 'விளக்கம்',
    'faq.section.reader': 'வாசிப்போர்',
    'faq.section.library': 'நூலகம்',
    'faq.section.workshop': 'பயிற்சி மனைவர்',
    'faq.section.writer': 'எழுதுபவர்',
    'faq.section.encyclopedia': 'அறிவியல் அமைப்பு',
    'faq.section.groups': 'குழுக்கள்',
    'faq.section.blogs': 'வலைப்பதிவுகள்',
    // About us questions
    'faq.question.about.dataLocation': 'LU தரவு எங்கே சேமிக்கப்படுகிறது?',
    'faq.answer.about.dataLocation': 'இலக்கண உலகம் தரவு ஐகான்சர்கள் அமெரிக்கத்தின் ஐபிஎஸ்-கிழக்கு 1 பகுதியில் உள்ள சேவையகங்களில் சேமிக்கப்படுகின்றன.',
    'faq.question.about.incorporation': 'நீங்கள் எங்களிடம் சேர்க்கப்பட்டுள்ளீர்களா?',
    'faq.answer.about.incorporation': 'இலக்கண உலகம் செசுகிய மாடலானது. எங்களைப் பற்றி மேலும் விவரங்களைப் பெற நீங்கள் இங்கே பார்க்க முடியும் <a href="/about">பக்கத்தில்</a>.',
    'faq.question.about.roadmap': 'இலக்கண உலகம் அடுத்த படி என்ன தொடர்புகள் உள்ளன?',
    'faq.answer.about.roadmap': 'இது தொடர்புகளின் மூலமாக செயல்படுகின்றது. மேலும் விவரங்களுக்கு எங்கள் <a href="/roadmap">தொடர்புகள் பக்கத்தை சோதிக்கவும்</a>.',
    // Settings questions
    'faq.question.settings.changeTheme': 'இலக்கண உலகம் பார்வையை எப்படி மாற்றுவது?',
    'faq.answer.settings.changeTheme': 'Registered users can change their theme in the <a href="/user/settings/account">account settings</a> under "site theming" section. We have a light and a dark theme available. If you are not registered, then we try to determine which theme to serve you based on your browser and operating system settings.',
    'faq.question.settings.changeAvatar': 'என்ன வடிவமைப்பை மாற்ற வேண்டும்?',
    'faq.answer.settings.changeAvatar': 'நீங்கள் உங்களுடைய வடிவமைப்பை மாற்றலாம் <a href="/user/settings/profile">சுயவிவர அமைப்புகள்</a>.',
    'faq.question.settings.changeLanguage': 'மொழியை எப்படி மாற்ற வேண்டும்?',
    'faq.answer.settings.changeLanguage': 'இலக்கண உலகத்தின் மொழியை நீங்கள் மாற்றலாம் <a href="/user/settings/account">சுயவிவர அமைப்புகள்</a>.',
    'faq.question.settings.translationMistake': 'வல்லுநரிடம் உள்ள உரையில் ஒரு தவறைக் கண்டுபிடித்தேன், அதை நான் எப்படி அறிவிக்க வேண்டும்?',
    'faq.answer.settings.translationMistake': 'எங்கள் மொழி கோப்புகள் அனைத்தும் GitHub இல் கிடைக்கின்றன. நீங்கள் <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">அங்கே ஒரு பிரச்சனையை சமர்ப்பிக்க முடியும்</a> அல்லது பின்னர் விளக்கப்படும் பிரச்சனையையும் அல்லது நீங்கள் விரும்பினால், நீங்கள் தனிப்பட்டவராகவும் உட்பட்ட மூலத்தையும் மூடிவிடலாம் <a href="https://crowdin.com/project/literary-universe" target="_blank">எங்கள் கிரவூடின் பக்கம்</a>.'
};