/**
 * Licenses for creative works
 * https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
 */
export default {
    'licenses.about': 'About licenses',
    'licenses.more': 'More information',
    'licenses.legal': 'Legal document',
    'licenses.name.cc-by': 'Creative Commons Attribution 4.0',
    'licenses.cc-by': 'This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.',
    'licenses.name.cc-by-sa': 'Creative Commons Attribution-ShareAlike 4.0',
    'licenses.cc-by-sa': 'This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms. This license is often compared to "copyleft" free and open source software licenses. All new works based on yours will carry the same license, so any derivatives will also allow commercial use. This is the license used by Wikipedia, and is recommended for materials that would benefit from incorporating content from Wikipedia and similarly licensed projects.',
    'licenses.name.cc-by-nd': 'Creative Commons Attribution-NoDerivs 4.0',
    'licenses.cc-by-nd': 'This license allows for redistribution, commercial and non-commercial, as long as it is passed along unchanged and in whole, with credit to you.',
    'licenses.name.cc-by-nc': 'Creative Commons Attribution-NonCommercial 4.0',
    'licenses.cc-by-nc': 'This license lets others remix, tweak, and build upon your work non-commercially, and although their new works must also acknowledge you and be non-commercial, they don\'t have to license their derivative works on the same terms.',
    'licenses.name.cc-by-nc-sa': 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0',
    'licenses.cc-by-nc-sa': 'This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms.',
    'licenses.name.cc-by-nc-nd': 'Creative Commons Attribution-NonCommercial-NoDerivs 4.0',
    'licenses.cc-by-nc-nd': 'This license is the most restrictive of our six main licenses, only allowing others to download your works and share them with others as long as they credit you, but they can\'t change them in any way or use them commercially.',
    'licenses.name.lu-c': 'Literary Universe Copyrights',
    'licenses.lu-c': 'நீங்கள் உங்கள் வேலையை விரும்பும்போது விரும்புவதன் மூலம் உங்கள் உரிமைகளை பாதுகாக்குகின்ற ஒரு நியாய உரிமை அனுமதி. இந்த உரிமை உங்களைக் கதைகளை விற்றுக்கொள்ள மற்றும் இலக்கு உரிமையை பெற வழிவகுக்கின்றது.',
    'licenses.name.lu-e': 'Literary Universe Exclusive',
    'licenses.lu-e': 'This license grants Literary Universe exclusive rights to publish and distribute your work online. You will retain the copyright, but Literary Universe will have the sole right to publish and distribute your work online.',
    'licenses.name.lu-ne': 'Literary Universe Non-Exclusive',
    'licenses.lu-ne': 'This license grants Literary Universe non-exclusive rights to publish and distribute your work online. You will retain the copyright and the right to publish and distribute your work through other channels.',
    'licenses.name.cc0': 'எந்த உரிமையுமில்லை - CC0 1.0',
    'licenses.cc0': 'Put your work into public domain. In contrast to CC\'s licenses that allow copyright holders to choose from a range of permissions while retaining their copyright, CC0 empowers yet another choice altogether – the choice to opt out of copyright and database protection, and the exclusive rights automatically granted to creators – the "no rights reserved" alternative to our licenses.',
    // License Chooser Modal
    'licenses.chooser.title': 'License Chooser',
    'licenses.chooser.button': 'Help me choose a license',
    'licenses.chooser.ariaLabel': 'Choose a license for your work',
    'licenses.chooser.introduction': 'This tool will help you choose the most appropriate license for your work. The license determines how others can use your work and affects your ability to monetize it on Literary Universe.',
    // License Chooser Wizard Steps
    'licenses.chooser.step.contentType.title': 'What type of content are you licensing?',
    'licenses.chooser.step.contentType.description': 'The type of content affects which licenses are available to you.',
    'licenses.chooser.step.contentType.original': 'Original Work',
    'licenses.chooser.step.contentType.fanfiction': 'Fan Fiction',
    'licenses.chooser.step.contentType.fanfictionNote': 'Fan fiction works on Literary Universe are automatically assigned the Creative Commons Attribution-NonCommercial license (CC BY-NC). This is because fan fiction is based on copyrighted works owned by others, and commercial use would potentially infringe on those rights.',
    'licenses.chooser.step.commercial.title': 'Do you want to monetize your work?',
    'licenses.chooser.step.commercial.description': 'Choosing to monetize your work affects which license is most appropriate.',
    'licenses.chooser.step.commercial.yes': 'Yes, I want to monetize my work',
    'licenses.chooser.step.commercial.no': 'No, I don\'t want to monetize my work',
    'licenses.chooser.step.commercial.monetizeNote': 'To monetize your work on Literary Universe, you\'ll need to use one of our commercial licenses. These licenses allow you to sell your work while maintaining your copyright protection.',
    'licenses.chooser.step.exclusivity.title': 'Do you want to publish exclusively on Literary Universe?',
    'licenses.chooser.step.exclusivity.description': 'Choosing exclusivity affects the platform fee and publishing options.',
    'licenses.chooser.step.exclusivity.yes': 'Yes, exclusively on Literary Universe',
    'licenses.chooser.step.exclusivity.no': 'No, I want to publish elsewhere too',
    'licenses.chooser.step.exclusivity.exclusiveNote': 'With exclusive publishing on Literary Universe, you\'ll benefit from a lower platform fee of 10%. This means you keep 90% of your earnings.',
    'licenses.chooser.step.exclusivity.nonExclusiveNote': 'With non-exclusive publishing, you can publish your work on other platforms as well. The platform fee is 30%, which means you keep 70% of your earnings on Literary Universe. In the future, we\'ll provide tools to help you publish to other platforms directly from Literary Universe.',
    'licenses.chooser.step.derivatives.title': 'Do you want to allow others to create derivative works?',
    'licenses.chooser.step.derivatives.description': 'Derivative works include adaptations, remixes, or transformations of your original work.',
    'licenses.chooser.step.derivatives.yes': 'Yes, allow derivative works',
    'licenses.chooser.step.derivatives.no': 'No, don\'t allow derivative works',
    'licenses.chooser.step.derivatives.allowNote': 'Allowing derivative works means others can adapt, remix, or transform your work. This can lead to wider distribution and creative reuse of your content.',
    'licenses.chooser.step.derivatives.disallowNote': 'Not allowing derivative works means your work must be passed along unchanged and in whole, though it can still be shared with proper attribution.',
    'licenses.chooser.step.attribution.title': 'Do you want to require attribution?',
    'licenses.chooser.step.attribution.description': 'Attribution means others must give you credit when they use your work.',
    'licenses.chooser.step.attribution.yes': 'Yes, require attribution',
    'licenses.chooser.step.attribution.no': 'No, place in public domain (CC0)',
    'licenses.chooser.step.attribution.requireNote': 'Requiring attribution means anyone who uses your work must give you credit in the way you request.',
    'licenses.chooser.step.attribution.publicDomainNote': 'Placing your work in the public domain (CC0) means you waive all copyright and related rights. Others can freely use your work for any purpose without attribution.',
    // License Result
    'licenses.chooser.result.commercialTitle': 'Commercial Information',
    'licenses.chooser.result.exclusiveInfo': 'With the Literary Universe Exclusive license, you\'ll benefit from a lower platform fee of 10%. This means you keep 90% of your earnings, but you can only publish this work on Literary Universe.',
    'licenses.chooser.result.nonExclusiveInfo': 'With the Literary Universe Non-Exclusive license, you can publish your work on other platforms as well. The platform fee is 30%, which means you keep 70% of your earnings on Literary Universe. In the future, we\'ll provide tools to help you publish to other platforms directly from Literary Universe.',
    'licenses.chooser.result.fanfictionNote': 'This license is automatically applied to fan fiction works because they are based on copyrighted material owned by others. Commercial use would potentially infringe on those rights.',
    'licenses.chooser.result.selectLicense': 'Select This License'
};