export default {
    'homepage.welcome': 'Welcome to',
    'homepage.start': 'Start Your journey!',
    'homepage.iAm': 'I am a',
    'homepage.iAm.aria': 'Select between display of features for readers and writers',
    'homepage.reader': 'READER',
    'homepage.writer': 'WRITER',
    'homepage.reader.title': 'Reading has never been so interesting like this',
    'homepage.reader.readingTitle': 'Unique reading experience',
    'homepage.reader.readingDesc': 'Delve deeper into your favorite fictional universe in Literary Universe. Stories in Literary Universe are connected within the same universe, giving you immediate access to the universe encyclopedia from the story reader.',
    'homepage.reader.favoriteTitle': 'Find out more about Your favorite stories and authors',
    'homepage.reader.favoriteDesc': 'Universe encyclopedia and author\'s blogs are just a few feature that will help you find out everything you need to know about your favorite stories, their settings and their creators!',
    'homepage.reader.communityTitle': 'Join the community',
    'homepage.reader.communityDesc': 'Meet people from across the globe on dedicated universe and author\'s forums, blogs and other community features where like-minded fans gather. All in one place.',
    'homepage.reader.readingFeatureTitle': 'Enjoy an immersive yet practical reading experience',
    'homepage.reader.readingFeatureDesc': 'From stories and universe, have the benefit of effortless reading with access to details without needing to switch between pages.',
    'homepage.reader.readingExploreTitle': 'Explore all the minutia in the universe',
    'homepage.reader.readingExploreDesc': 'Universe encyclopedia allows you to learn all the details about the universe and fully immerse yourself in the stories.',
    'homepage.reader.start': 'Start Reading',
    'homepage.writer.title': 'Showcase your universe and share your stories',
    'homepage.writer.writingTitle': 'Writing & creating made easy',
    'homepage.writer.writingDesc': 'Experience the new way of writing with Literary Universes Workshop. Create all the details of your universe in an encyclopedia to share with your readers and write amazing stories on that foundation.',
    'homepage.writer.collaborationTitle': 'Collaborative creation',
    'homepage.writer.collaborationDesc': 'Creative process often involves multiple people. No worries, we got you covered! You can easily add beta readers, co-authors and translators to your stories and universes.',
    'homepage.writer.communityTitle': 'Connect with Your readers',
    'homepage.writer.communityDesc': 'Go beyond writing and connect with your readers via blogs, forums and other community features connected to your universes or to you as a writer.',
    'homepage.writer.workshopFeatureTitle': 'One place for all your creative needs',
    'homepage.writer.workshopFeatureDesc': 'Our ever evolving workshop is the central place for your creative needs. From a simple idea create amazing universes, stories and everything else that is needed around it.',
    'homepage.writer.monetizationFeatureTitle': 'செலுத்துதல் முறைகள்',
    'homepage.writer.monetizationDesc': 'We strongly believe that people should be payed for their work and are constantly looking for new monetization opportunities for writers. Monetization feature allows you writers to be appreciated for what you do. Explore all the different options that allow your fans to show you their appreciation.',
    'homepage.writer.start': 'Setup Your workshop!',
    'homepage.featureSelection': 'Check out these popular universe!',
    'about.title': 'About Literary Universe',
    'about.desc': 'History, secrets and humans behind Literary Universe.',
    'about.text.1': 'Literary Universe is designed both for writers and for the avid reader. Writers can use the site to write original works through the workshop button in the dashboard menu. This will give you access to the main editor and encyclopedia functions which primarily focus on organizing all aspects of your personal story universe into one page. The social aspects allow authors to broadcast their work and develop a following, as well as to interact more directly if they chose with their readers.',
    'about.text.2': 'Readers can use the site primarily to read new works and follow authors but also to help edit pre-published stories if given permission by the writer. Being a reader on Literary Universe is a whole new reading experience, having access to all the background information on the same page as the main story gives you insight into the mind of the author like never before.',
    'about.text.3': 'The future for Literary Universe involves creating a marketplace for authors to sell their work and adding community features to enhance author and reader communication through blogs and forums. Writer’s tools will be added over time, with over a dozen currently either in development or on the board. Our ultimate goal is to enhance the experiences of writers and readers through providing more innovative use of the internet medium.',
    'about.text.4': 'We hope that you join us as we explore what the internet medium can do for creative writing!',
    'about.team': 'The team',
    'about.history': 'History',
    'about.company': 'The company',
    'about.companyCountry.czechia': 'Czechia',
    'about.companyCountry.japan': 'Japan',
    'about.companyCity.prague': 'Prague',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Chief Executive Officer',
    'about.CTO': 'Chief Technology Officer',
    'about.jan': 'Jan is the founder, visionary and technological brain behind Literary Universe. As a writer of large literary universes, Jan had always found it difficult to write stories from a technical and readability point of view that would not compromise the reading experience. As such, Jan decided to pursue his studies in web development to create an application that would make it easy to write stories in large universes.',
    'about.history.text': 'In 2010 Jan started at Rochester Institute of Technology to learn more about web development in order to be able to build a creative writing site. This materialized in 2013 when the first proof of concept was presented at Imagine RIT. Jan continued his studies and in 2016 a new version of the app was created as a Master\'s Capstone Project. The project continued in fall 2016 and further developed into what you see today.',
    'copyrights.desc': 'The full text of Literary Universe Copyrights Agreement.',
    'privacy.desc': 'Full legal text of Privacy Policy of Literary Universe.',
    'guidelines.desc': 'Community Guidelines of Literary Universe.',
    'tos.desc': 'Full legal text of Terms of Service of Literary Universe.',
    'homepage.intro': 'Let Your Creativity Run Wild Across the Literary Universe',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'நேர்மறையான உலகம் எப்போதும் உங்களுக்கும் தொடர்பான உலகமாக மாற்ற விரும்புகின்றீர்களா? இலக்கண உலகத்தின் படிப்பில், இதை உருவாக்க முடியும் கருவிகளை நாங்கள் வழங்குகின்றோம். ஒவ்வொரு எழுத்தாளருக்கும் மிகுந்த வளர்ச்சி மற்றும் ஆதரவுகளை அவர்கள் அரசாளுமாறு கட்டணமாக வழங்குகின்றோம். எழுத்தாளர்களுக்கும், படிக்கும் மக்களுக்கும் இது ஒரு கனவு பணியிடம்; படித்தவர்களுக்கும், கலாச்சாரத்தின் உலகில் எவ்வளவு மேல் செல்கிறது என்பதை ஆராய்ந்து கண்டுபிடிக்கும் புதிய வழியில் எங்களுடன் சேர்க்கவும்.',
    'gdpr.title': 'GDPR Compliance',
    'gdpr.desc': 'Literary Universe is compliant with the EU GDPR directives.',
    'gdpr.compliant': 'Literary Universe is GDPR Compliant',
    'gdpr.compliant.text': 'Literary Universe has implemented various updates and changes to its codebase in preparation for GDPR enforcement on May 25th 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'இந்த பதிப்பில் மாற்றங்கள்',
    'dmca.title': 'Digital Millennium Copyright Act (DMCA) Policy',
    'dmca.subtitle': 'Copyright Dispute Policy',
    'dmca.step1.title': 'Procedure for Reporting Copyright Infringements.',
    'dmca.step2.title': 'Once Proper Bona Fide Infringement Notification is Received by the Designated Agent.',
    'dmca.step3.title': 'Procedure to Supply a Counter-Notice to the Designated Agent.',
    'dmca.desc': 'நாங்கள் பதிப்பிப்பதில் பாதிக்கப்பட்ட உரைச்சொற்களை மிக்கவாறு எடுக்கின்றோம்.',
    'gdpr.access.title': 'Right of Access and Right of Data Portability',
    'gdpr.access.desc': 'In user settings you can export all your data. This data will be in standard JSON format.',
    'gdpr.forget.title': 'Right to be forgotten',
    'gdpr.forget.desc': 'Any account can be deleted via user settings. Some data might be preserved, especially if they have been subject to sale and/or disputes.',
    'gdpr.rectification.title': 'சரிபார்த்தல் உரிமை',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'செயலாக்கத்தின் வரம்பை வரம்புச் செய்தல் உரிமை',
    'gdpr.processing.desc': 'இலக்கண உலகம் முழுமையாக உலாவியில் "கண்காணிப்பு செய்ய வேண்டாம்" கேட்டாலும், எங்களால் அறிவிப்புகளை அறிவிப்பு பயன்பாட்டு சேவையகத்திற்கு அறிவிக்கும் மாற்றங்களை முழுமையாக மாற்றுகின்றது.',
    'gdpr.object.title': 'எதிர்க்கோள் உரிமை',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'Reporting is split into two scenarios. 1. Internal property (infringement on site of property existing on site). 2. External property (infringement on site of property not existing on site).',
    'dmca.step1.desc2': 'Reporting internal property can be done via report button on the property. Reporting external property infringement can be done via feedback screen. In both cases you will be asked to provide personal details and additional details that will allow us to check your ownership.',
    'dmca.step1.desc3': 'Please note that making a false claims will result in your inability to file claims in the future.',
    'dmca.step2.desc1': 'உங்கள் அறிக்கையைப் பெறும் போது, உங்கள் அங்கீகாரத்தையும் உரிமையையும் சரிபார்க்கும். அனைத்தும் சரியானதாக இருக்கின்றதால், நாங்கள் கேள்வியை சரிபார்க்கும். கேள்வி மொழியாக்கம் உண்டாக முடியும்போது, மேற்கோள்வி மூலம் பிழையான சொல்லை அழிக்கும் வரை தடைக்கப்படும் பொருத்தமில்லாமல் அனைத்தும் நீக்கப்படும்.',
    'dmca.step3.desc1': 'புகைப்படக் குழுவின் உரிமையாளர் எந்தவொரு புகைப்படத்தின் பின்னர் எத்தனை நாட்களுக்குப் பின்வரும் முதலியன எதிர்பார்ப்பு அறிவிப்பு பதிவை செய்ய வேண்டும். அங்கீகாரத்தைச் செய்வதன் பின்னர், பொருத்தமான விவாதத்தை ஆராய்ந்து பார்க்கும் புகைப்படக் குழுவின் முக்கிய முடிவு ஆகும்.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'ஜான் ட்வோராக்',
    'about.attributions': 'பண்பாட்டுகள்',
    'about.attributionsIntro': 'இலக்கிய உலகம் பல திறன்களுடன் திறன் மூலங்களின் மீது அமைக்கப்பட்டுள்ளது. கீழே அவற்றின் பட்டியல் உள்ளது.',
    'about.attributionsMatomo': 'எங்கள் பயன்பாட்டின் பகுதியில் தன்னை வைப்புள்ள பொதுநிலையான மாற்றங்கள் பயன்படுத்துகின்றன.',
    'team.name.pjakubec': 'பாவேல் ஜகுபெக்',
    'team.name.asebesta': 'ஆடம் ஷெபெஸ்டா',
    'about.developer': 'மென்பொருள் மேம்பாட்டாளர்',
    'about.seniorDeveloper': 'மேல் மென்பொருள் மேம்பாட்டாளர்',
    'about.juniorDeveloper': 'குறிப்பிட்ட மென்பொருள் மேம்பாட்டாளர்',
    'about.leadDesigner': 'Lead designer',
    'about.leadUX': 'Lead UX designer',
    'about.intern': 'மனித வளமாக்கல் மாணவர்',
    'about.advisor': 'ஆலோசனையாளர்',
    'about.headOfResearch': 'ஆராய்ச்சி முதலாளி',
    'about.CFO': 'முதல் நிதி அலுவலர்',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry is a designer with more than 15 years experience. He\'s been working in agency since 2010, his client such as PERTAMINA, VOA, and Ministry tourism of Indonesia. Experienced in Branding, layout and also UI/UX he feels challenged to design Literary Universe.',
    'about.pavel': 'Web3, Metaverse, AI, all that and anything new is what Pavel looks into and how it can be added to improve Literary Universe. A true multidisciplinary researcher Pavel holds insight into many areas and works on adding new interesting features to Literary Universe',
    'about.seba': 'Once a gamer, Adam is now studying to become a fully fledged developer.'
};