export default {
    'workshop.title': 'உங்கள் வேலை',
    'workshop.noneassigned': 'இன்னும் நீங்கள் எந்தப் பணியையும் பதிவு செய்யப்படவில்லை.',
    'workshop.notavailable': 'இந்த அம்சம் இன்னும் கிடைக்கவில்லை.',
    'workshop.none': `நீங்கள் தற்போது இல்லை {type, select,
      universe {உலகம்}
      story {கதை}
      fanfiction {பாராட்டுக்குரிய கதைகள்}
      other {}
    }. இப்போது ஒருவர் உருவாக்குக!`,
    'workshop.collab': 'கூட்டுறவு பணிகள்',
    'workshop.betareadings': 'பீட்டா வாசனைகள்',
    'workshop.translations': 'மொழிபெயர்ப்புகள்',
    'workshop.createnew': 'புதியதை உருவாக்கு...',
    'workshop.story.standalone': 'தனிப்பட்ட கதை',
    'workshop.story.standalone.desc': 'இது தனிப்பட்ட கதையாகும்.',
    'workshop.controlpanel': '{name} கட்டுப்பாட்டு மேலாளர் தாள்',
    'workshop.universe.page': 'பரலோகப் பக்கம்',
    'workshop.fictionaltime': 'Fictional time',
    'workshop.dashboard.name': '{name} டாஷ்போர்டு',
    'workshop.stories.in': 'கதைகள் {universe}இல்',
    'workshop.universe.nostories': 'இந்த பரலோகத்தில் எந்த கதையும் இல்லை.',
    'workshop.story.chapter.add': 'புதிய அத்தியாயம்',
    'workshop.universe.new': 'புதிய பரலோகத்தை உருவாக்கு',
    'workshop.universe.publish': 'பரலோகத்தை வெளியிடு',
    'workshop.universe.publishing.notice': 'பரலோகத்துடன் இணைக்கப்பட்ட முதன்முதல் கதை வெளியிடப்படும்படி இல்லாமல் இருக்கும் போது பரலோகத்தை வெளியிடுவது தானாகவே நடைமுறைபடும்.',
    'workshop.universe.settings': '{universe} பரலோக அமைப்புகள்',
    'workshop.universe.publishedOn': 'இந்த உலகம் வெளியிடப்பட்டது {date, date, long} {date, time, short}',
    'workshop.universe.description': 'பரலோக விளக்கம்',
    'workshop.settings.title': 'Title',
    'workshop.description': 'விளக்கம்',
    'workshop.language.primary': 'முதன்மை மொழி',
    'workshop.publication.options': 'வெளியீட்டு விருப்பங்கள்',
    'workshop.rating': 'பொது மதிப்பீடு',
    'workshop.universe.rating.desc': 'இந்த மதிப்பீட்டில் மேலும் உருவாக்கப்படும் கதைகள் மற்றும் பிராம்பன கதைகள் பரலோக பக்கத்தில் மறைக்கப்படும். அறியாத பயனர்களும் மற்றும் பொது வயது குறிப்பிட்ட பயனர்களும் இந்த மதிப்பீட்டில் மேலும் உருவாக்கப்படும் கதைகளை மறைக்கப்படுத்தும்.',
    'workshop.universe.license': 'பரலோக உரிமை',
    'workshop.universe.genre.pick': 'பரலோகத்திற்கு வகை தேர்வு செய்யவும்',
    'workshop.story.genre.pick': 'கதைக்கு வகைகளை தேர்வு செய்யவும்',
    'workshop.cover': 'கவர்',
    'workshop.nothingtosee': 'இங்கே எதுவும் இல்லை...',
    'workshop.story.cannon': 'கேனன் கதை',
    'workshop.story.cannon.desc': 'This story is canonical in {universe} universe.',
    'workshop.story.cannon.desc.create': 'இந்த கதை ஒரு முக்கிய கதையாக உருவாக்கப்படும் {universe} உலகத்தில்.',
    'workshop.story.fanfiction.search': 'உங்கள் நூலகத்தில் உள்ள உலகத்தின் பெயரை தட்டச்சு செய்யவும். அப்புறம் பரிந்துரைகளிலிருந்து ஒன்றைத் தேர்ந்தெடுக்கவும்.',
    'workshop.story.error.nogenres': 'நீங்கள் குறைந்தது ஒரு வகையைத் தேர்ந்தெடுக்க வேண்டும்.',
    'workshop.story.error.toomanygenres': 'ஒரு கதையில் மட்டும் இரண்டு வகைகள் மட்டுமே அனுமதிக்கப்படுகின்றன.',
    'workshop.story.error.fanfiction.selectuniverse': 'உங்கள் புகழ்பெயர்க்கு ஒரு அசல் உலகத்தைத் தேர்வு செய்ய வேண்டும்!',
    'workshop.story.error.tags.toomany': 'ஒரு கதையில் மட்டும் 10 குறிச்சொல்லுக்கள் மட்டுமே உள்ளன.',
    'workshop.story.new': 'ஒரு புதிய கதை உருவாக்கப்படும்',
    'workshop.story.publishing.notice': 'முதன்முதலில் அதிகாரப்பூர்வமாக பதிவை வெளியிடப்படும் போது இந்த கதையின் மேல் வெளியேற்றம் செய்யப்படும்.',
    'workshop.settings.edit': 'அமைப்புகளைத் திருத்து',
    'workshop.story.publishedOn': 'இந்த கதை வெளியிடப்பட்டது {date, date, long} {date, time, short}',
    'workshop.story.settings': 'கதை அமைப்புகள்',
    'workshop.settings.basic': 'அடிப்படை அமைப்புகள்',
    'workshop.settings.genres': 'வகைகள் (அதிகபட்சம் 2)',
    'workshop.story.license': 'கதை உரிமை',
    'workshop.story.settings.universe': 'உலகத்தின் அமைப்புகள்',
    'workshop.settings.tags': 'குறிச்சொல்லுக்கள்',
    'workshop.revision': 'மருத்துவம்',
    'workshop.revisions.title': '{story}: {chapter} மருத்துவங்கள்',
    'workshop.revisions.current': 'தற்போதைய வரைவு',
    'workshop.revisions.new.beta': 'மருத்துவத்திலிருந்து புதிய மருத்துவத்தை உருவாக்கவும்.',
    'workshop.revisions.new.public': 'மருத்துவத்திலிருந்து புதிய பொது மருத்துவத்தை உருவாக்கவும்.',
    'workshop.revisions.toeditor': 'எடிட்டருக்குச் செல்க',
    'workshop.revisions.comments': 'மருத்துவ கருத்துகள்',
    'workshop.revisions.comments.title': '{story}: {chapter} - மருத்துவம் {revision} - கருத்துகள்',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {for Beta readers}
      readers {Public}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'முதலில் நீங்கள் ஒரு மருத்துவத்தை உருவாக்க வேண்டும்.',
    'workshop.revisions.comments.select': 'மாற்றத்தைத் தேர்ந்தெடுக்கவும்',
    'workshop.collaborators.noresults': 'முடிவுகள் இல்லை',
    'workshop.collaborators.add.beta': 'பீட்டா வாசிப்பாளரைச் சேர்க்கவும்',
    'workshop.collaborators.add.collaborator': 'ஒப்பந்தாளரைச் சேர்க்கவும்',
    'workshop.collaborators.add.translator': 'மொழிபெயர்ப்பாளரைச் சேர்க்கவும்',
    'workshop.collaborators.language.add': 'புதிய மொழிபெயர்ப்பை உருவாக்கவும்',
    'workshop.translations.stories': 'மொழிபெயர்ப்புகள் - கதைகள்',
    'workshop.translations.universes': 'மொழிபெயர்ப்புகள் - உலகம்',
    'workshop.revisions.beta.none': 'இந்த நேரத்தில் மாற்றங்கள் இல்லை.',
    'reader.asidetoggle': 'தகவலை அடுக்கு மாற்றவும்',
    'workshop.translation.original': 'மூலம்:',
    'workshop.translation.original.title': 'மூல தலைப்பு:',
    'workshop.translation.original.description': 'மூல விளக்கம்:',
    'workshop.translation.original.cover': 'மூல கவர்',
    'workshop.translation.original.tags': 'மூல குறிச்சொல்லுக்கள்',
    'workshop.cover.alt': 'கவர் படம்',
    'workshop.translation.updatedOrig': 'மூலத்தின் கடைசி புதுப்பிப்பு: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'மொழிபெயர்ப்பின் கடைசி புதுப்பிப்பு: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'கடைசி மாற்றம் {revision, number}, மூலத்தின்: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'கடைசி மாற்றம் {revision, number}, மொழிபெயர்ப்பின்: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `மேலும் {type, select,
    collaborator {ஒப்பந்தப் பகிர்வாளர்கள்}
    beta {பீட்டா வாசிப்பவர்கள்}
    translator {மொழிபெயர்ப்பாளர்கள்}
    other {}
  }சேர்க்க உங்கள் உறுப்பினர் அணுகலை அதிகரிக்க வேண்டும்.`,
    'workshop.collaborators.requests.sent': 'அனுப்பிய கோரிக்கைகள்',
    'workshop.collaborators.requests.invite': `நீங்கள் பின்வரும் பற்றியதற்காக {role, select,
    beta {பீட்டா வாசிப்பவர்}
    translator {மொழிபெயர்ப்பாளர்}
    collaborator {ஒப்பந்தப் பகிர்வாளர்}
    other {}
  } ஆக அழைக்கப்பட்டுள்ளீர்கள்:`,
    'workshop.collaborators.requests.dashboard': `நீங்கள் ஒரு இலக்கிய பணிக்கு ஒரு ஆழ்ந்த ஆழ்ந்த பணிக்களத்தில் சேர்க்கப்பட்டுள்ளீர்கள் {count, plural,
    zero {ஒரு ஆழ்ந்த பணிக்களம்}
    one {ஒரு இலக்கிய பணிக்களம்}
    other {# இலக்கிய பணிக்கள்}
  }.`,
    'workshop.collaborators.language.added': 'மொழி சேர்க்கப்பட்டது',
    'workshop.story.noChaptersFound': 'எந்த அதிகாரத்திலும் பதிவுகள் கிடைக்கவில்லை.',
    'workshop.fanfic.needUniverseInLibrary': 'அல்லது அல்லாத பண்புகள் படித்தலைவர்களிடமிருந்து எழுத விரும்புகின்றீர்களா? அவர்களை முதன்முதலில் உங்கள் நூலகத்தில் சேர்க்கவும்.',
    'workshop.fanfic.findUniverse': 'ஒரு அற்புதமான உலகத்தைக் கண்டுபிடிக்கவும்!',
    'workshop.encSettings': 'Encyclopedia settings',
    'workshop.collaborators.removeUser': 'பயனரை நீக்கு',
    'workshop.collaborators.cancelInvite': 'அழிவு ரத்து செய்',
    'workshop.universe.createFirstStory': 'முதல் கதையை உருவாக்கவும்',
    'workshop.storylines': 'கதை வரலாறுகள்',
    'workshop.scenesManager': 'மேலாண்மை மேலாண்மையானது',
    'workshop.collaborators.addRoleForLang': 'சேர்க்க {role} இன் மேல் {language}',
    'workshop.beta.revisionInfo': 'இது மரியாதை {revision, number}, {createdAt, date, long}அன்புடன் உருவாக்கப்பட்டது.',
    'workshop.story.notes.title': 'உங்கள் {storyTitle}க்கான குறிப்புகள்',
    'workshop.story.notes.desc': 'கதைக்கு உள்ளேயே குறிப்புகள்.',
    'workshop.story.notes.tile': 'மேலாண்மை குறிப்புகள்',
    'workshop.hideOrgs': 'அமைப்புகளிலிருந்து உள்ளீட்டை மறைக்க',
    'workshop.translation.premium': 'In order to add translations, you need to have at least Explorer subscription.',
    'workshop.story.finished': 'கதை முடிந்தது',
    'workshop.story.publishing.externalSellingNotice': 'நீங்கள் இலக்கிய உணர்வுகளின் வெளியில் விற்பனை செய்யும் போது இப்போது கதையை வெளியிடலாம். உங்கள் விற்பனை பட்டியலில் இணைப்புகள் கதைக்குள் அல்லது தற்போதைய கதையின் முடிவில் தெரியும்.',
    'workshop.sharing.publicURL': 'பொது பதிப்பு',
    'workshop.fictionalTime.title': 'இலக்கிய நேரங்கள் {universeName}க்கு',
    'workshop.fictionalTime.none': 'You currently don\'t have any fictional times set-up.',
    'workshop.fictionalTime.createNow': 'Create one now!',
    'workshop.fictionalTime.createTitle': 'Create a new fictional time',
    'workshop.fictionalTime.editTitle': 'Edit {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'Time name',
    'workshop.fictionalTime.basicInfo': 'Basic information',
    'workshop.fictionalTime.timeSetup': 'Time setup',
    'workshop.fictionalTime.linkedToET': 'Does this time start on an Earth date (Gregorian calendar)?',
    'workshop.fictionalTime.timeDeclaration': 'Time declaration',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'Before units',
    'workshop.fictionalTime.declarationAfter': 'After units',
    'workshop.fictionalTime.declarationNone': 'None',
    'workshop.fictionalTime.units': 'Units',
    'workshop.fictionalTime.ETStart': 'Starting date of this time',
    'workshop.fictionalTime.unitsDescFirst': 'How many units are there in this unit from milliseconds?',
    'workshop.fictionalTime.unitsDesc': 'How many units is this one from the previous one?',
    'workshop.fictionalTime.unitsName': 'Unit name',
    'workshop.fictionalTime.unitsSeparator': 'Separator from previous unit',
    'workshop.fictionalTime.unitAdd': 'Add unit',
    'workshop.fictionalTime.clocks': 'Clocks',
    'workshop.fictionalTime.unitTransfer': 'Transfer units',
    'fictionalTime.pageStartElapsedTime': 'Time elapsed since opening this page',
    'fictionalTime.currentTime': 'Current time',
    'workshop.shoppingExternal.options': 'External purchase options',
    'workshop.shoppingExternal.explainer': 'If your story is sold elsewhere you can set the links here. The links will then show instead of the content or at the end of the content you choose to preview.',
    'workshop.shoppingExternal.amazonStore': 'Amazon store',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Store name',
    'workshop.shoppingExternal.itemUrl': 'Item URL',
    'workshop.shoppingExternal.storesOther': 'Other stores',
    'fictionalTime.units.milliseconds': '{units, number} milliseconds',
    'fictionalTime.countdownToStart': 'Countdown to time beginning',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 நாள் }
      other {{days} நாட்கள் }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {ஒரு நொடி}
      other {நொடிகள்}
    }}
    minutes {{units, plural,
      one {ஒரு நிமிடம்}
      other {நிமிடங்கள்}
    }}
    hours {{units, plural,
      one {ஒரு மணி நேரம்}
      other {மணி நேரம்}
    }}
    days {{units, plural,
      one {ஒரு நாள்}
      other {நாட்கள்}
    }}
    years {{units, plural,
      one {ஒரு ஆண்டு}
      other {ஆண்டுகள்}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'From',
    'fictionalTime.inputSelectTimeUnit': 'Select time unit',
    'fictionalTime.inputSelectETUnit': 'Select Earth time unit',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Sidebar Toolbox',
    'workshop.writerSidebar.description': 'Welcome to your story! This sidebar allows you easy access to all resources related to your story. Check the icons above to see latest comments, your notes and much more!',
    'workshop.story.authorsNotesExplained': 'உங்கள் கதையின் ஆரம்பத்தில் படிக்க வாசிப்பவர்களுக்கு உங்கள் குறிப்புகள்.',
    'workshop.story.chapterSortSwitch': 'அதிகாரத்தின் வரிசையை மாற்று',
    'workshop.universe.monetizationTitle': '{title} monetization',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} monetization',
    'workshop.universe.monetizationWebMonetization': 'வலை பணமுறியல்',
    'workshop.webMonetization.explain': 'Web Monetization will stream payments to you based on how much time user spends on your content. In your profile monetization settings you can set your own payment pointer. Here you can decide on a split with your collaborators who have Web Payment enabled. Literary Universe automatically takes 10%.',
    'workshop.webMonetization.revShare': 'Due to the limitation of Web Monetization probabilistic revenue sharing is used. Probabilistic revenue sharing works by randomly choosing from a list of predefined payment pointers each time a web monetized visitor loads your page. The visitor pays to the chosen pointer until the page is reloaded or closed.',
    'workshop.webMonetization.revShareMore': 'Learn more about Probabilistic Revenue Sharing. We use the same code as on that page.',
    'workshop.story.notEligible.licence': `The story's license does not allow for monetization.`,
    'workshop.universe.notEligible.licence': `The universe's license does not allow for monetization.`,
    'workshop.story.notEligible.fanFiction': 'Fan Fiction stories are not eligible for monetization.',
    'workshop.revShare.mustBe100': 'Share must equal 100%',
    'workshop.revShare.LUCut': 'Literary Universe & payment gate',
    'workshop.revShare.unallocated': 'Unallocated share {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'Undecided',
    'workshop.revShare.origLangCreators': 'Original language creators',
    'workshop.story.prolog': 'Prolog',
    'workshop.story.chapter': 'Chapter {sequence, number}',
    'workshop.work.includesAds': 'வேலையில் எந்தக் கடவுச்சொல் அல்லது தயாரிப்பு வேண்டுமா?',
    'workshop.universe.forumSettings': 'உள் பராமரிப்பு உலகம் மன்றம் அமைப்புகள்',
    'workshop.universe.forum': 'உள் பராமரிப்பு {universeName} மன்றம்',
    'workshop.ratingAdjusted': 'Due to complains we had to adjust your rating to the one that we felt appropriate. As such changing the rating is now disabled.',
    'workshop.selectCollaborator': 'Select collaborator',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Draft',
    'workshop.chapterStatus.scheduled': 'Scheduled',
    'workshop.chapterStatus.published': 'Published',
    'workshop.story.continuedIn': 'Which stories continue this story?',
    'workshop.story.continuedPlaceholder': 'Select story from this universe',
    'workshop.universe.isAIGenerated': 'Is the content of the universe generated by AI?',
    'workshop.universe.isAIGeneratedTooltip': 'Please let us know if any of the content in the universe was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.story.isAIGenerated': 'Is the story generated by AI?',
    'workshop.story.isAIGeneratedTooltip': 'Please let us know if any of the story was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.publicationAgreement.aria': 'Publication agreement for work',
    'workshop.publicationAgreement.intro': 'We are happy that you have chosen to publish your creative work with us. Before we proceed we just need you to look over our publication agreement, to understand what it means from the legal side of things.',
    'workshop.sortChapters': 'Sort order:',
    'workshop.sortChapters.ascending': 'From beginning',
    'workshop.sortChapters.descending': 'From latest',
    'workshop.sortChapters.aria': 'Select for which way to sort chapter listing',
    'workshop.hiatus.btn': 'Change story status to Hiatus',
    'workshop.cancelled.btn': 'Change story status to Cancelled',
    'workshop.complete.btn': 'Change story status to Completed',
    'workshop.statusChange.modalTop': 'Are you sure you want to change the status to',
    'workshop.statusName.hiatus': 'Hiatus',
    'workshop.statusName.cancelled': 'Cancelled',
    'workshop.statusName.completed': 'முடிந்தது',
    'workshop.statusExplain.hiatus1': 'Hiatus means that you are stepping away from working on this story for a while for what ever reason. It will tell your readers that they should not expect any new updates in the coming weeks or even up to few months.',
    'workshop.statusExplain.hiatus2': 'The hiatus status will be automatically lifted if you publish any chapter. Or you can change it your self.',
    'workshop.statusExplain.hiatus3': 'If you keep your story in hiatus for six months, we will automatically mark this story as cancelled.',
    'workshop.statusExplain.cancelled1': 'We are sorry to hear that you can\'t continue working on the story. On the other hand we are happy that you are willing to let your readers know.',
    'workshop.statusExplain.cancelled2': 'Cancelling story will let your readers know that they should not expect any new updates.',
    'workshop.statusExplain.cancelled3': 'You can always revert this by publishing a chapter or changing the status.',
    'workshop.statusExplain.finished1': 'Congratulations! After all that hard work you have finally reached the end of an incredible journey. While the story might end now, we hope that there will be more stories to tell in the future, but for now, relax and enjoy the well earned rest.',
    'workshop.statusExplain.finished2': 'Marking story as complete will tell the readers that the story is finished. While you shouldn\'t be adding any new chapters we won\'t stop you and adding special chapters isn\'t a bad idea, to for example add more epilogues for all characters.',
    'workshop.statusExplain.finished3': 'While you can always cancel this status we highly advice against it. If the story is to continue it might be better to start a new story.',
    'workshop.status.goActive': 'Make the story active again',
    'workshop.statusChangeEmail.storyIntro': 'We would like to inform you that your story:',
    'workshop.statusChangeEmail.hiatusTitle': 'Your story status was automatically set to hiatus',
    'workshop.statusChangeEmail.hiatusIntro': 'Due to inactivity your story status was automatically set to hiatus.',
    'workshop.statusChangeEmail.hiatusWhy': 'Has been automatically put on hiatus due to no new chapter being published for over 6 months.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'This status will be automatically lifted if you publish a new chapter. If you don\'t publish a new chapter in the next 6 months we will automatically set the story as cancelled.',
    'workshop.statusChangeEmail.cancellationIntro': 'Your story status was automatically set to cancelled.',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'This status will be automatically lifted if you publish a new chapter. If you don\'t plan to work on this story anymore there is nothing else that you need to do.',
    'workshop.startCreating': 'Start creating',
    'workshop.ownWork': 'Own work',
    'workshop.list.thumbs': 'Thumbnails list',
    'workshop.list.list': 'Short list',
    'workshop.fanfiction.new': 'Create a new fan fiction',
    'workshop.videoTrailerLink': 'வீடியோ டிரெய்லர் இணைப்பு',
    'workshop.videoTrailerPlayerTitle': 'கதை வீடியோ டிரெய்லர் பிளேயர்',
    'workshop.videoTrailer.supportedPlaftorms': 'நாங்கள் Youtube, Vimeo மற்றும் Odysee ஐ ஆதரிக்கிறோம்',
    'workshop.videoTrailer.rumble': 'நாங்கள் ரம்பிளையும் ஆதரிக்கிறோம், ஆனால் IFRAME URL ஐ நகலெடுக்க மறக்காதீர்கள்.',
    'workshop.videoTrailer.suggestPlatforms': 'உங்கள் வீடியோ தளம் இல்லையா? எங்களுக்கு தெரிவிக்கவும் எனக்குப் பின்னூட்டம் அனுப்புங்கள் <a>கருத்து</a>!',
    'workshop.cover.edit': 'Change cover',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.',
    'workshop.license.exclusiveUniverse': 'The universe uses an exclusive license, which means that all stories also have to follow the same license in order to prevent legal chaos.'
};