export default {
  "encyclopedia.add": "Legg til en ny oppføring",
  "encyclopedia.browse": "Bla gjennom encyklopedien",
  "encyclopedia.search": "Søk i encyklopedien",
  "canvas.toolbar.add": "Add:",
  "canvas.toolbar.text": "Text",
  "canvas.toolbar.link": "Link",
  "canvas.toolbar.group": "Group",
  "canvas.toolbar.entry": "Entry",
  "canvas.encPicker.title": "Pick an encyclopedia entry",
  "canvas.encPicker.search": "Search entries…",
  "canvas.dialog.pickEntry": "Pick encyclopedia entry",
  "canvas.node.link": "Link",
  "canvas.node.encEntry": "Entry",
  "canvas.entry.open": "Double-click to open entry",
  "encyclopedia.back.universe": "Tilbake til univers-siden",
  "encyclopedia.back.workshop": "Tilbake til verkstedet",
  "encyclopedia.categories": "Kategorier",
  "encyclopedia.groups": "Grupper",
  "encyclopedia.category.character": "Karakterer",
  "encyclopedia.category.event": "Hendelser",
  "encyclopedia.category.group": "Grupper",
  "encyclopedia.category.item": "Gjenstander",
  "encyclopedia.category.location": "Steder",
  "encyclopedia.category.other": "Annet",
  "encyclopedia.category.state": "Stater",
  "encyclopedia.category.governments": "Regjeringer",
  "encyclopedia.category.languages": "Språk",
  "encyclopedia.category.creatures": "Skapninger",
  "encyclopedia.category.deity": "Guder",
  "encyclopedia.category.religions": "Religioner",
  "encyclopedia.category.flora": "Flora",
  "encyclopedia.category.magic": "Magi",
  "encyclopedia.category.planets": "Planeter",
  "encyclopedia.category.species": "Arter",
  "encyclopedia.category.technologies": "Teknologier",
  "encyclopedia.category.families": "Families",
  "encyclopedia.category.jobs": "Jobs",
  "encyclopedia.category.lore": "Lore",
  "encyclopedia.category.vehicles": "Vehicles",
  "encyclopedia.category.diseases": "Diseases",
  "encyclopedia.category.traditions": "Traditions",
  "encyclopedia.category.sports": "Sports",
  "encyclopedia.category.food": "Food",
  "encyclopedia.category.landmarks": "Landmarks",
  "encyclopedia.category.buildings": "Buildings",
  "encyclopedia.category.schools": "Schools",
  "encyclopedia.category.continents": "Continents",
  "encyclopedia.category.villages": "Villages",
  "encyclopedia.category.towns": "Towns",
  "encyclopedia.category.cities": "Cities",
  "encyclopedia.category.settlements": "Settlements",
  "encyclopedia.category.countries": "Countries",
  "encyclopedia.search.found": "{results, plural,\n    =0 {Ingen relaterte oppføringer}\n    one {1 relatert oppføring}\n    other {# relaterte oppføringer}\n  } funnet.",
  "encyclopedia.help.text": "Bruk menyen på venstre side for å navigere mellom elementene i encyklopedien. Når du velger et element, vil det vises i stedet for denne teksten.",
  "encyclopedia.help.sidebar": "Verktøylinje for sidepanel",
  "encyclopedia.help.sidebar.text": "Welcome to your story! This sidebar allows you easy access to all resources related to your story. Check the icons above to see the latest comments, your notes, search your encyclopedia, browse and add new entries to your encyclopedia. If you want to add a connection to an entry from the story text, select the text where you want to place it and then click the connect button. You will then be prompted to find and select an item.",
  "encyclopedia.intro": "Velkommen til {universe} encyklopedien.",
  "encyclopedia.add.title": "Legg til en ny oppføring i encyklopedien",
  "encyclopedia.add.heading": "Hva ønsker du å legge til?",
  "encyclopedia.add.moresoon": "Flere kategorier kommer snart!",
  "encyclopedia.create": "Create new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {villages}\n    towns {towns}\n    cities {cities}\n    settlements {settlement}\n    countries {country}\n  }",
  "encyclopedia.create.header": "Creating a new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {village}\n    towns {town}\n    cities {city}\n    settlements {settlement}\n    countries {country}\n  } in {universe}",
  "encyclopedia.entry.category": "Entry category: {category, select,\n    character {Character}\n    event {Event}\n    group {Group}\n    item {Item}\n    location {Location}\n    other {Note}\n    state {State}\n    governments {Government}\n    languages {Language}\n    creatures {Creature}\n    deity {Deity}\n    religions {Religion}\n    flora {Flora}\n    magic {Magic}\n    planets {Planet}\n    species {Specie}\n    technologies {Technology}\n    families {Family}\n    jobs {Job}\n    lore {Lore}\n    vehicles {Vehicle}\n    diseases {Disease}\n    traditions {Tradition}\n    food {Food}\n    sports {Sport}\n    landmarks {Landmark}\n    buildings {Building}\n    schools {School}\n    continents {Continent}\n    villages {Village}\n    towns {Town}\n    cities {City}\n    settlements {Settlement}\n    countries {Country}\n  }",
  "encyclopedia.entry.category.legend": "Kategori",
  "encyclopedia.fields.add": "Legg til et nytt felt",
  "encyclopedia.fields.text": "Definisjon",
  "encyclopedia.fields.textarea": "Tekst",
  "encyclopedia.fields.connection": "Kobling",
  "encyclopedia.fields.time": "Tid",
  "encyclopedia.fields.image": "Bilde",
  "encyclopedia.fields.canvas": "Canvas",
  "encyclopedia.visibility": "Synlighet",
  "encyclopedia.public": "Offentlig",
  "encyclopedia.private": "Privat",
  "encyclopedia.container": "Beholder",
  "encyclopedia.container.desc": "Make this entry a container for a new group of entries. This will hide it from the categories listing.",
  "encyclopedia.entry.name": "Navn på oppføringen",
  "encyclopedia.summary": "Sammendrag",
  "encyclopedia.summary.desc": "This is a summary that will be the only initial information displayed to the reader.",
  "encyclopedia.parent": "Foreldreoppføring",
  "encyclopedia.related": "Relaterte oppføringer",
  "encyclopedia.errors.tags": "Du kan bare ha 10 koder per oppføring.",
  "encyclopedia.field.private": "Privat felt",
  "encyclopedia.ft.indev": "Denne funksjonen er under utvikling.",
  "encyclopedia.connections.remove": "Fjern kobling",
  "encyclopedia.connections.extra": "Ekstra informasjon",
  "encyclopedia.connections.existing": "Eksisterende oppføring",
  "encyclopedia.connections.existing.abbr": "EE",
  "encyclopedia.cover": "Forsidebilde",
  "encyclopedia.translation.title": "Velkommen til {universe} universoversettelse!",
  "encyclopedia.translation.desc": "Denne leksikon-grensesnittet brukes for oversettelse til {language}. Velg eksisterende oppføringer i listen til venstre for å begynne oversettelsen.",
  "encyclopedia.welcome.totalEntries": "There {totalEntries, plural, \n    zero {are no entries}\n    one {is one entry}\n    other {are # entries}\n  } in this universe.",
  "encyclopedia.settings.title": "Leksikoninnstillinger",
  "encyclopedia.settings.categoriesDesc": "Slå av og på kategorier som du ønsker å bruke i leksikonet ditt.",
  "encyclopedia.settings.introText": "Velkomstmelding som skal vises etter universbeskrivelsen.",
  "encyclopedia.fields.placeholder": "Felt navn",
  "encyclopedia.fields.delete": "Slett felt",
  "encyclopedia.timeOption.fictionalDate": "Fiktiv dato",
  "encyclopedia.timeOption.fictionalTime": "Fiktiv tid",
  "encyclopedia.timeOption.fictionalDateTime": "Fiktiv dato og tid",
  "encyclopedia.timeOption.date": "Dato",
  "encyclopedia.timeOption.time": "Tid",
  "encyclopedia.timeOption.dateTime": "Dato og tid",
  "encyclopedia.settings.groupByCategories": "Inkluder kategorier i gruppelisting",
  "encyclopedia.menuOpen": "Åpne leksikonmenyen",
  "encyclopedia.menuClose": "Lukk leksikonmenyen",
  "encyclopedia.menuAria": "Leksikonmeny",
  "enc.newField": "Nytt felt",
  "enc.entries.limit": "Du har for øyeblikket {value, number} av {max, plural,\n    =0 {ubegrensede}\n    other {{max, number}}\n  } oppføringer.",
  "enc.entries.limitReached": "Du har nådd maksimalt tillatte oppføringer i encyklopedien for ditt nåværende abonnement.",
  "encyclopedia.pronunciation.title": "Uttale",
  "encyclopedia.wip.abbreviation": "Pågående arbeid",
  "encyclopedia.wip.full": "Arbeid pågår",
  "encyclopedia.settings.templateLegend": "Malunivers",
  "encyclopedia.settings.templateDescription": "Tillat at innholdet i denne encyklopedien kan kopieres til andre univers. Dette er best hvis du ikke har noen historier og i stedet bare oppretter en mal for andre å bruke.",
  "encyclopedia.settings.templateCheckbox": "Dette er en malunivers",
  "encyclopedia.templateCopy.modalTitle": "Kopier encyklopediinnhold",
  "encyclopedia.templateCopy.description": "Kopier innholdet i denne encyklopedien til ditt univers for å berike det.",
  "encyclopedia.templateCopy.targetUniverse": "Univers å kopiere til",
  "encyclopedia.templateCopy.finished": "Kopiering fullført",
  "encyclopedia.templateCreateUniverse.modalTitle": "Create universe from template",
  "encyclopedia.templateCreateUniverse.description": "Create a new universe with pre-seeded encyclopedia content from this template. Your universe will remain private until you decide to make it public.",
  "encyclopedia.templateCreateUniverse.success": "Universe created successfully! Redirecting...",
  "encyclopedia.pronunciation.audio.play": "Play pronunciation",
  "encyclopedia.pronunciation.guide": "Use <ipaLink>IPA notation</ipaLink> when possible. Web Speech API pronunciation is best-effort; see <webSpeechLink>MDN docs</webSpeechLink>.",
  "encyclopedia.templateField.born": "Born",
  "encyclopedia.templateField.died": "Died",
  "encyclopedia.templateField.race": "Race",
  "encyclopedia.templateField.gender": "Kjønn",
  "encyclopedia.templateField.partners": "Partners",
  "encyclopedia.templateField.parents": "Parents",
  "encyclopedia.templateField.children": "Barn",
  "encyclopedia.templateField.associated-with": "Associated with",
  "encyclopedia.templateField.biography": "Biography",
  "encyclopedia.templateField.physical-appearance": "Physical appearance",
  "encyclopedia.templateField.type-of-event": "Type of event",
  "encyclopedia.templateField.preceding-events": "Preceding events",
  "encyclopedia.templateField.following-events": "Following events",
  "encyclopedia.templateField.leadup": "Leadup",
  "encyclopedia.templateField.description": "Beskrivelse",
  "encyclopedia.templateField.aftermath": "Aftermath",
  "encyclopedia.templateField.members": "Medlemmer",
  "encyclopedia.templateField.locations": "Steder",
  "encyclopedia.templateField.events": "Hendelser",
  "encyclopedia.templateField.vision": "Vision",
  "encyclopedia.templateField.mission": "Mission",
  "encyclopedia.templateField.description-of-the-organization": "Description of the organization",
  "encyclopedia.templateField.history": "Historie",
  "encyclopedia.templateField.owners": "Owners",
  "encyclopedia.templateField.function": "Function",
  "encyclopedia.templateField.content": "Content",
  "encyclopedia.templateField.population": "Population",
  "encyclopedia.templateField.culture": "Culture",
  "encyclopedia.templateField.governments": "Regjeringer",
  "encyclopedia.templateField.religions-believes": "Religions & believes",
  "encyclopedia.templateField.languages": "Språk",
  "encyclopedia.templateField.geography": "Geography",
  "encyclopedia.templateField.founding": "Founding",
  "encyclopedia.templateField.notable-events": "Notable events",
  "encyclopedia.templateField.notes": "Notater",
  "encyclopedia.templateField.type-of-government": "Type of government",
  "encyclopedia.templateField.structure": "Structure",
  "encyclopedia.templateField.power-structure": "Power structure",
  "encyclopedia.templateField.source-of-power": "Source of power",
  "encyclopedia.templateField.laws": "Laws",
  "encyclopedia.templateField.ideology": "Ideology",
  "encyclopedia.templateField.internal-politics": "Internal politics",
  "encyclopedia.templateField.external-politics": "External politics",
  "encyclopedia.templateField.leading-figures": "Leading figures",
  "encyclopedia.templateField.groups": "Grupper",
  "encyclopedia.templateField.military": "Military",
  "encyclopedia.templateField.items": "Gjenstander",
  "encyclopedia.templateField.typology": "Typology",
  "encyclopedia.templateField.dialectics": "Dialectics",
  "encyclopedia.templateField.phonology": "Phonology",
  "encyclopedia.templateField.grammar": "Grammar",
  "encyclopedia.templateField.numbers": "Numbers",
  "encyclopedia.templateField.quantifiers": "Quantifiers",
  "encyclopedia.templateField.private-notes": "Private notes",
  "encyclopedia.templateField.type": "Type",
  "encyclopedia.templateField.notable-features": "Notable features",
  "encyclopedia.templateField.traits": "Traits",
  "encyclopedia.templateField.habitat": "Habitat",
  "encyclopedia.templateField.food-sources": "Food sources",
  "encyclopedia.templateField.reproduction": "Reproduction",
  "encyclopedia.templateField.cultural-significance": "Cultural significance",
  "encyclopedia.templateField.related-creatures": "Related creatures",
  "encyclopedia.templateField.religion": "Religion",
  "encyclopedia.templateField.other-names": "Other names",
  "encyclopedia.templateField.appearance": "Appearance",
  "encyclopedia.templateField.related-to": "Related to",
  "encyclopedia.templateField.symbolism": "Symbolism",
  "encyclopedia.templateField.rituals": "Rituals",
  "encyclopedia.templateField.origin": "Origin",
  "encyclopedia.templateField.notable-figures": "Notable figures",
  "encyclopedia.templateField.deities": "Guder",
  "encyclopedia.templateField.artifacts": "Artifacts",
  "encyclopedia.templateField.believes": "Believes",
  "encyclopedia.templateField.traditions": "Traditions",
  "encyclopedia.templateField.spread": "Spread",
  "encyclopedia.templateField.classification": "Classification",
  "encyclopedia.templateField.features": "Funksjoner",
  "encyclopedia.templateField.produce": "Produce",
  "encyclopedia.templateField.ecosystem": "Ecosystem",
  "encyclopedia.templateField.effect": "Effect",
  "encyclopedia.templateField.alignment": "Alignment",
  "encyclopedia.templateField.requirements": "Requirements",
  "encyclopedia.templateField.size": "Size",
  "encyclopedia.templateField.length-of-day": "Length of day",
  "encyclopedia.templateField.length-of-night": "Length of night",
  "encyclopedia.templateField.length-of-cycle": "Length of cycle",
  "encyclopedia.templateField.moons": "Moons",
  "encyclopedia.templateField.nearby-stellar-bodies": "Nearby stellar bodies",
  "encyclopedia.templateField.climate": "Climate",
  "encyclopedia.templateField.weather": "Weather",
  "encyclopedia.templateField.natural-resources": "Natural resources",
  "encyclopedia.templateField.notable-locations": "Notable locations",
  "encyclopedia.templateField.inhabitans": "Inhabitans",
  "encyclopedia.templateField.looks": "Looks",
  "encyclopedia.templateField.production": "Production",
  "encyclopedia.templateField.use": "Use",
  "encyclopedia.templateField.related": "Related",
  "encyclopedia.templateField.location": "Location",
  "encyclopedia.templateField.significance": "Significance",
  "encyclopedia.templateField.associated-events": "Associated events",
  "encyclopedia.templateField.associated-figures": "Associated figures",
  "encyclopedia.templateField.access-restrictions": "Access restrictions",
  "encyclopedia.templateField.cultural-importance": "Cultural importance",
  "encyclopedia.templateField.founded": "Founded",
  "encyclopedia.templateField.government": "Government",
  "encyclopedia.templateField.defenses": "Defenses",
  "encyclopedia.templateField.connected-settlements": "Connected settlements",
  "encyclopedia.templateField.family-motto": "Family Motto",
  "encyclopedia.templateField.founding-date": "Founding Date",
  "encyclopedia.templateField.ethos": "Ethos",
  "encyclopedia.templateField.family-reputation": "Family Reputation",
  "encyclopedia.templateField.family-branches": "Family Branches",
  "encyclopedia.templateField.notable-vassals-retainers": "Notable vassals/retainers",
  "encyclopedia.templateField.skills-required": "Skills required",
  "encyclopedia.templateField.pay-salary": "Pay/Salary",
  "encyclopedia.templateField.associated-locations": "Associated locations",
  "encyclopedia.templateField.associated-characters": "Associated characters",
  "encyclopedia.templateField.propulsion": "Propulsion",
  "encyclopedia.templateField.capacity": "Capacity",
  "encyclopedia.templateField.speed": "Speed",
  "encyclopedia.templateField.manufacturers": "Manufacturers",
  "encyclopedia.templateField.symptoms": "Symptoms",
  "encyclopedia.templateField.causes": "Causes",
  "encyclopedia.templateField.treatment": "Treatment",
  "encyclopedia.templateField.affected-species": "Affected species",
  "encyclopedia.templateField.associated-groups": "Associated groups",
  "encyclopedia.templateField.ingredients": "Ingredients",
  "encyclopedia.templateField.preparation": "Preparation",
  "encyclopedia.templateField.rules": "Rules",
  "encyclopedia.templateField.equipment": "Equipment",
  "encyclopedia.templateField.venues": "Venues",
  "encyclopedia.templateField.architecture": "Architecture",
  "encyclopedia.templateField.curriculum": "Curriculum",
  "encyclopedia.templateField.notable-alumni": "Notable alumni",
  "encyclopedia.templateField.affiliation": "Affiliation",
  "encyclopedia.templateField.language": "Språk",
}
