export default {
  'events.upcoming': 'Kommende arrangementer',
  'events.settings.title': 'Arrangementsinnstillinger',
  'events.attendance.attending': 'Deltar',
  'events.attendance.tentative': 'Tentativ',
  'events.attendance.notAttending': 'Deltar ikke',
  'events.details.name': 'Arrangementnavn',
  'events.details.image': 'Arrangementbilde',
  'events.details.description': 'Arrangementbeskrivelse / Agenda',
  'events.details.url': 'Lenke til mer detaljer',
  'events.details.virtualLink': 'Lenke til virtuell plassering (f.eks. Zoom, Google Meet, osv.)',
  'events.details.address': 'Stedadresse',
  'events.details.startsAt': 'Arrangementstart',
  'events.details.endsAt': 'Arrangement slutter',
  'events.details.type': 'Arrangementstype',
  'events.type.inPerson': 'Fysisk',
  'events.type.virtual': 'Virtuell',
  'events.type.hybrid': 'Hybrid',
  'events.join.startsIn': 'Arrangement starter {startsAt}',
  // The startsAt is going to be in a relative time format. Eg. `in 1 minute`, `1 day ago`, etc...
  'events.join.virtual': 'Bli med på arrangementet',
  'events.selection.origin': 'Arrangementsopphav',
  'events.origin.universe': 'Univers',
  'events.origin.author': 'Forfatter',
  'events.origin.groups': 'Grupper',
  'events.origin.organizations': 'Organisasjoner',
  'events.origin.lu': 'Litterære univers arrangementer',
  'events.visibility.label': 'Arrangementets synlighet',
  'events.visibility.public': 'Offentlig - alle kan se dette arrangementet',
  'events.visibility.owner': `Eier - bare {type, select,
    group {medlemmer av gruppen din}
    universe {samarbeidspartnere og fans av universet}
    organization {medlemmer av organisasjonen din}
    other {du og de du inviterer}
  } kan se dette arrangementet`,
  'events.visibility.private': 'Privat - bare personer du inviterer vil se arrangementet',
  'events.inviting': 'Kan personer som ser dette arrangementet invitere andre?',
  'events.administration': 'Arrangementadministrasjon',
  'events.create.title': 'Opprett et nytt arrangement',
  'events.hostedBy': 'Vertskap av {hostName}',
  'events.openVirtual': 'Gå til virtuell plassering',
  'events.moreInfo': 'Mer informasjon',
  'event.visibilityShort.private': 'Privat',
  'event.visibilityShort.public': 'Offentlig',
  'event.visibilityShort.owner': 'Eier'
};