export default {
  'forums.create': 'Aktiver forum',
  'forums.archive': 'Arkiver forum',
  'forums.archive.explained': 'Arkivering av forumet vil forhindre brukere fra å legge ut mer innhold, men det vil fortsatt være synlig.',
  'forums.archive.success': 'Forumet har blitt arkivert',
  'forums.unArchive': 'Gjenopprett forum',
  'forums.unArchive.success': 'Forumet har blitt gjenopprettet!',
  'forums.settings': 'Foruminnstillinger',
  'forums.category.create': 'Opprett forumkategori',
  'forums.category.delete': 'Slett kategori',
  'forums.category.name': 'Kategorinavn',
  'forums.category.slug': 'SEO URL-del',
  'forums.category.settings': 'Kategoriinnstillinger',
  'forums.category.language': 'Begrens visning av denne kategorien til følgende språk. La være tomt hvis du vil vise kategorien på alle språk.',
  'forums.category.intlNameDescription': 'Vi har lokaliserende titler for vanlige kategorinavn for ditt valg, slik at kategorien kan være tilgjengelig på alle støttede språk.',
  'forums.thread.new': 'Ny tråd',
  'forums.thread.delete': 'Slett tråd',
  'forums.post.new': 'Ny post',
  'forums.archived.forum': 'Dette forumet har blitt arkivert på {archivedAt, date, long}. Du kan fortsatt se forumet, men du kan ikke lenger opprette nytt innhold.',
  'forums.category.archive': 'Arkiver kategori',
  'forums.category.archiveExplained': 'Kategorier uten tråder vil bli slettet, mens kategorier med innhold vil forhindre opprettelse av nye tråder.',
  'forums.category.reactivate': 'Gjenopprett kategori',
  'forums.category.isVotable': 'Tillat brukere å stemme opp/ned tråder',
  'forums.category.titleIsGlobal': 'Denne kategoritittelen vil bli vist på brukerens språk hvis vi støtter det.',
  'forums.category.languageLimited': 'Denne kategorien vil bare bli vist for brukere i dette språket.',
  'forums.threadsCounter': 'Totalt antall tråder',
  // Pre-defined category names
  'forums.category.intlName.general': 'Generelt',
  'forums.category.intlName.announcements': 'Kunngjøringer',
  'forums.category.intlName.stories': 'Historier',
  'forums.category.intlName.universes': 'Universer',
  'forums.category.intlName.universe': 'Univers',
  'forums.category.intlName.community': 'Fellesskap',
  'forums.category.intlName.meetups': 'Møter',
  'forums.category.intlName.characters': 'Karakterer',
  'forums.category.intlName.locations': 'Steder',
  'forums.category.intlName.history': 'Historie',
  'forums.category.intlName.art': 'Kunst',
  'forums.category.intlName.inspiration': 'Inspirasjon',
  'forums.category.intlName.news': 'Nyheter',
  'forums.category.intlName.help': 'Hjelp',
  'forums.category.intlName.questions': 'Spørsmål',
  'forums.category.back': 'Tilbake til forumoversikt',
  // Forum restrictions
  'forums.forumRestriction.usersOnly': 'Tillat kun tilgang for registrerte brukere',
  'forums.settings.accessControls': 'Tilgangskontroller',
  'forums.forumRestrictionsMessages.usersOnlyForum': 'Dette forumet er kun tilgjengelig for registrerte brukere.',
  'forums.noThreads': 'Ingenting å se her. Det er opp til deg å starte samtalen.',
  'forums.noPosts': 'Ingen har svart ennå. Vær den første!',
  // Threads
  'forums.createThread': 'Opprett en ny diskusjon',
  'forums.createThreadIn': 'Opprett en ny tråd i {categoryName}',
  'forums.openingPost': 'Åpningsinnlegg',
  'forums.createQuestionLabel': 'Er dette et spørsmål?',
  'forums.thread.noReplies': 'Det er for øyeblikket ingen svar her.',
  'forums.reply': 'Svar',
  'forums.post': 'Innlegg',
  'forums.posting': 'Poster...',
  'forums.reset': 'Tilbakestill',
  'forum.thread.reply': 'Legg til et svar i denne tråden',
  'forums.yourMessage': 'Din melding',
  'forums.thread.replyPosted': 'Meldingen din er publisert',
  'forums.thread.totalPosts': `{totalReplies, number} svar {totalReplies, plural,
    one {svar}
    other {svar}
  }`,
  'forums.thread.createdAt': 'Opprettet den {createdAt, date, medium}'
};