export default {
    'sharing.title': 'Del',
    'sharing.button': 'Delingsknapp',
    'sharing.share': 'Del med...',
    'sharing.feedback': 'Mangler vi noen steder du vil dele til? Gi oss beskjed om det!',
    'sharing.copy': 'Kopier',
    'sharing.email': 'E-mail',
    'sharing.sms': 'SMS',
    'sharing.messenger': 'Facebook Messenger',
    'sharing.whatsapp': 'WhatsApp',
    'sharing.twitter': 'X/Twitter',
    'sharing.linkedin': 'LinkedIn',
    'sharing.telegram': 'Telegram',
    'sharing.facebook': 'Facebook',
    'sharing.line': 'LINE',
    'sharing.mastodonSocial': 'Mastodon Social',
    'sharing.mastodonJapan': 'Mastodon Japan',
    'sharing.gab': 'Gab',
    'sharing.pinterest': 'Pinterest',
    'sharing.gettr': 'Gettr',
    'sharing.minds': 'Minds.com',
    'sharing.instagram': 'Instagram'
};