export default {
    'sharing.title': 'షేర్ చేయండి',
    'sharing.button': 'షేరింగ్ బటన్',
    'sharing.share': 'షేర్ చేయండి...',
    'sharing.feedback': 'మేము మీకు షేర్ చేయాలని ఆకాంక్షిస్తున్న ప్రాంతం లేదా ప్రదేశం లేదా లేకుండా ఉందామని మాకు తెలియజేయండి!',
    'sharing.copy': 'కాపీ చేయండి',
    'sharing.email': 'ఇమెయిల్',
    'sharing.sms': 'SMS',
    'sharing.messenger': 'ఫేస్బుక్ మెస్సెంజర్',
    'sharing.whatsapp': 'WhatsApp',
    'sharing.twitter': 'X/ట్విట్టర్',
    'sharing.linkedin': 'లింకెడిన్',
    'sharing.telegram': 'టెలిగ్రామ్',
    'sharing.facebook': 'ఫేస్బుక్',
    'sharing.line': 'LINE',
    'sharing.mastodonSocial': 'మాస్టోడాన్ సోషల్',
    'sharing.mastodonJapan': 'మాస్టోడాన్ జపాన్',
    'sharing.gab': 'గాబ్',
    'sharing.pinterest': 'పింటరెస్ట్',
    'sharing.gettr': 'గెట్ట్ర్',
    'sharing.minds': 'మైండ్స్.com',
    'sharing.instagram': 'ఇన్స్టాగ్రామ్',
    'sharing.reddit': 'రెడ్డిట్',
    'sharing.bsky': 'BlueSky'
};