/**
 * @authors Jan Dvorak
 */
export default {
  locales: ['cs', 'cs-CZ'],
  'sitename': 'Liteary Universe',
  'site.description': 'Literary Universe is a creative and publishing site for large story universes.',
  'common.signin': 'Přihlásit se',
  'common.signup': 'Registrace',
  'common.signout': 'Odhlásit se',
  'common.dashboard': 'Dashboard',
  'common.discovery': 'Discovery',
  'common.library': 'Knihovna',
  'common.library.own': 'Vaše knihovna',
  'common.blogs': 'Blogy',
  'common.workshop': 'Ateliér',
  'common.pm': 'Soukromé zprávy',
  'common.settings': 'Nastavení',
  'common.options': 'Možnosti',
  'common.profile': 'Profil',
  'common.blog': 'Blog',
  'common.blogs': 'Blogi',
  'common.about': 'O nás',
  'common.accessdenied': 'Přístup odepřen',
  'common.accessdenied.msg': 'Nemáte přístupová práva do této oblasti.',
  'common.loading': 'Načítám...',
  'common.add': 'Přidat',
  'common.save': 'Uložit',
  'common.email': 'E-mail',
  'common.soon': 'Již brzy...',
  'common.search': 'Vyhledávání',
  'common.search.do': 'Najít',
  'common.searchin': 'Hledám...',
  'common.report': 'Nahlásit',
  'common.user': 'Uživatel',
  'common.users': 'Uživatelé',
  'common.showmore': 'Více',
  'common.futurefeature': 'Budoucí funkcionalita',
  'common.futurefeature.text': 'Omlouváme se, ale tato funkcionalita je momentálně ve vývoji.',
  'common.nothingfound': 'Nic nenalezeno',
  '404': 'Stránka nenalezena',
  'search.users': 'Najdi uživatele',

  'settings.biography': 'O Vás',
  'settings.biography.placeholder': 'Něco málo o Vás, pro Váš profil.',
  'settings.avatar': 'Avatar',
  'settings.avatar.own': 'Vás avatar',
  'settings.avatar.upload': 'Vybrat obrázek',
  'settings.email': 'E-maily',
  'settings.email.msg': 'E-maily spojené s Vaším účtem',
  'settings.email.verified.not': 'not verified',
  'settings.email.add': 'Přidat e-mail',
  'settings.languages': 'Nastavení jazyku',
  'settings.languages.notice': 'Angličtina je momentálně jediný oficiálně podporovaný jazyk. Ostatní jazyky jsou možné díky práci dobrovolníků a mohou být neúplné.',
  'settings.languages.join': 'Můžete pomoci s překladem.',
  'settings.name': 'Pravé jméno',
  'settings.name.given': 'Jméno',
  'settings.name.family': 'Příjmení',
  'settings.username': 'Změnit uživatelské jméno',
  'settings.username.label': 'Uživatelské jméno',
  'settings.patreon': 'Patreon', // name of a service, don't translate
  'settings.patreon.label': 'URL k Vašemu Patreon účtu',
  'settings.password': 'Změnit heslo',
  'settings.password.current': 'Současné heslo',
  'settings.password.new': 'Nové heslo',
  'settings.password.new.repeat': 'Zopakujte nové heslo',
  'settings.password.nomatch': 'Zadané heslo se neshoduje!',
  'settings.password.badlength': 'Heslo musí mít minimálně {legth} písmen.',

  'password.reset': 'Resetovat heslo',
  'email.verification': 'E-mail verifikace',
  'email.verifying': 'Potvrzuji Váš e-mail. Hnedka to bude hotové...',
  'email.verified': 'Váš e-mail byl potvrzen!',
  'dashboard.whatsnew': 'Co je nového',

  'common.footer.tagline': 'Psaní a čtení rozsáhlách vesmírů jednoduše.',
  'common.footer.plans': 'Plany a ceny',
  'common.legal.tos': 'Smluvní podmínky',
  'common.legal.guidelines': 'Community Guidelines',
  'common.legal.privacy': 'Ochrana osobních údajů',
  'common.legal.copyright': 'Copyright Agreement',
  'common.legal.disclaimer': '© {year} Všechna práva vyhrazena, všechny texty patří jejich nálažitým vlastníkům.',

  'premium.only': 'Pouze pro premium uživatele',
  'premium.only.msg': 'Sorry, this functionality is for premium members only.',
  'premium.only.join': 'Become one today to gain access to this and many more features.',
  'premium.only.join.link': 'Check it out!',

  'user.friend.request': 'Přidat mezi přátele',
  'user.friend.requests': `Máte {num} {num, plural,
    zero {nových žádostí}
    one {novou žádost}
    few {nové žádosti}
    many {nových žádostí}
  } o přátelství`,
  'user.friend.unfriend': 'Zrušit přátelství',
  'user.block': 'Zablokovat',
  'user.unblock': 'Odblokovat',
  'user.joined': `{gender, select,
    male {Přidal}
    female {Přidala}
    other {Přidali}} se `, // keep the space at the end
  'user.friend.request.accept': 'Příjmout žádost o přátelství',
  'user.friend.request.deny': 'Otmítnout žádost o přátelství',
  'user.listing': 'Seznam uživatelů',

  'feed': 'Stream',
  'feed.post.new': 'Nový příspěvek',
  'feed.post.like': 'Like post',
  'feed.post.unlike': 'Unlike post',
  'feed.post.send': 'Pošli',
  'feed.empty': 'Žádné příspěvky k zobrazení',

  'discovery.meta.desc': 'Objevte nové příběhy a vesmíry.',
  'discovery.universes.new': 'Emerging universes',
  'discovery.stories.new': 'Nové příběhy',
  'discovery.stories.new.standalone': 'Nové samostatné příběhy',
  'discovery.stories.updated': 'Nedávno aktualizované',
  'discovery.continue': 'Pokračovat ve čtení',
  'discovery.stories.similar.new': 'New stories in the neighbourhood',
  'discovery.stories.similar': 'Stories in the neighbourhood',

  'rating': 'Rating',
  'rating.explained': '',
  'rating.all': 'Pro všechny',
  'rating.all.desc': 'Přístupné všem věkům and skupinám.',
  'rating.teens': 'Teens',
  'rating.teens.desc': 'Přístupné pro čtenáře mezi 12 a 18 lety.',
  'rating.mature': 'Mature',
  'rating.mature.desc': 'Contains advance themes, crude language and implicit scenes.',
  'rating.explicit': 'Explicitní',
  'rating.explicit.desc': 'Contains explicit scenes.',

  'universe.visit': 'Navštivte stránku tohoto vesmíru',
  'universe.fanfiction.for.see': 'See all Fan Fiction for ',

  // List of all genres
  'genre.scifi': 'Science Fiction',
  'genre.fantasy': 'Fantasy',
  'genre.adventure': 'Dobrodužství',
  'genre.poetry': 'Báseň',
  'genre.comedy': 'Komedie',
  'genre.drama': 'Drama',
  'genre.nonfiction': 'Non-fiction',
  'genre.romance': 'Romantika',
  'genre.satire': 'Satire',
  'genre.tragedy': 'Tragédie',
  'genre.crimi': 'Krimi',
  'genre.historical': 'Historická fikce',
  'genre.horror': 'Horor',
  'genre.Mystery': 'Záhada',
  'genre.thriller': 'Thriller',
  'genre.western': 'Western',
  'genre.memoir': 'Vzpomínky',
  'genre.biography': 'Biografie',
  'genre.steampunk': 'Steampunk',
  'genre.mythology': 'Mytologie',
  'genre.fairytale': 'Fairy tale',


  // you can get these messages from: https://github.com/gwendall/meteor-simple-schema-i18n/tree/master/i18n
  // but don't forget to adjust
  'simpleschema.required': '{label} je povinné pole',
  'simpleschema.minString': '{label} musí být alespoň {min} písmen',
  'simpleschema.maxString': '{label} nesmí být vice jak {max} písmen',
  'simpleschema.minNumber': '{label} musí být alespoň {min}',
  'simpleschema.maxNumber': '{label} nesmí být vice jak {max}',
  'simpleschema.minNumberExclusive': '{label} musí být více než {min}',
  'simpleschema.maxNumberExclusive': '{label} musí být méně než {max}',
  'simpleschema.minDate': '{label} musí být {min} nebo později',
  'simpleschema.maxDate': '{label} nemůže být po {max}',
  'simpleschema.badDate': '{label} není validní datum',
  'simpleschema.minCount': 'Musíte vybrat alespoň {minCount} hodnot',
  'simpleschema.maxCount': 'Nemůžete vybrat více jak {maxCount} hodnot',
  'simpleschema.noDecimal': '{label} musí být celé číslo',
  'simpleschema.notAllowed': '{label} není povolená hodnota',
  'simpleschema.expectedString': '{label} musí být text',
  'simpleschema.expectedNumber': '{label} musí být číslo',
  'simpleschema.expectedBoolean': '{label} musí být boolean',
  'simpleschema.expectedArray': '{label} musí být seznam',
  'simpleschema.expectedObject': '{label} musí být objekt',
  'simpleschema.expectedConstructor': '{label} musí být {type}',
  'simpleschema.keyNotInSchema': '{key} není povoleno schématem',
  'simpleschema.notUnique': '{label} musí být unikátní',
  'simpleschema.regEx.0': '{label} neprošlo kontrolou regularního výrazu',
  'simpleschema.regEx.1': '{label} musí být validní e-mailová adresa',
  'simpleschema.regEx.2': '{label} musí být validní e-mailová adresa',
  'simpleschema.regEx.3': '{label} musí být validní doména',
  'simpleschema.regEx.4': '{label} musí být validní doména',
  'simpleschema.regEx.5': '{label} musí být validní IPv4 nebo IPv6 adresa',
  'simpleschema.regEx.6': '{label} musí být validní IPv4 adresa',
  'simpleschema.regEx.7': '{label} musí být validní IPv6 adresa',
  'simpleschema.regEx.8': '{label} musí být validní URL',
  'simpleschema.regEx.9': '{label} musí být validní alphanumerické ID',
}