/**
 * @authors Jan Dvorak
 */
export default {
  locales: ['cs', 'cs-CZ'],
  'sitename': 'Liteary Universe',
  'site.description': 'Literary Universe is a creative and publishing site for large story universes.',
  'common.signin': 'Přihlásit se',
  'common.signup': 'Registrace',
  'common.signout': 'Odhlásit se',
  'common.dashboard': 'Dashboard',
  'common.discovery': 'Discovery',
  'common.library': 'Knihovna',
  'common.library.own': 'Vaše knihovna',
  'common.blogs': 'Blogy',
  'common.workshop': 'Ateliér',
  'common.pm': 'Soukromé zprávy',
  'common.settings': 'Nastavení',
  'common.options': 'Možnosti',
  'common.profile': 'Profil',
  'common.blog': 'Blog',
  'common.blogs': 'Blogi',
  'common.about': 'O nás',
  'common.accessdenied': 'Přístup odepřen',
  'common.accessdenied.msg': 'Nemáte přístupová práva do této oblasti.',
  'common.loading': 'Načítám...',
  'common.add': 'Přidat',
  'common.save': 'Uložit',
  'common.email': 'E-mail',
  'common.soon': 'Již brzy...',
  'common.search': 'Vyhledávání',
  'common.search.do': 'Najít',
  'common.searchin': 'Hledám...',
  'common.report': 'Nahlásit',
  'common.user': 'Uživatel',
  'common.users': 'Uživatelé',
  'common.showmore': 'Více',
  'common.futurefeature': 'Budoucí funkcionalita',
  'common.futurefeature.text': 'Omlouváme se, ale tato funkcionalita je momentálně ve vývoji.',
  'common.nothingfound': 'Nic nenalezeno',
  'common.explore': 'Objev',
  'common.by': 'od ', // keep the space at the end
  'common.scratchpad': 'Poznámky',
  'common.scratchpad.own': 'Vaše poznámky',
  'common.news': 'Novinky',
  'common.encyclopedia': 'Encyklopedie',
  'common.story': 'Příběh',
  'common.stories': 'Příběhy',
  'common.universe': 'Vesmír',
  'common.universes': 'Vesmíry',
  'common.post': 'Odeslat',
  'common.collaborator': 'Spolupracovník',
  'common.collaborators': 'Spolupracovníci',
  'common.translator': 'Překladatel',
  'common.translators': 'Překladatelé',
  'common.betareader': 'Beta čtenář',
  'common.betareaders': 'Beta čtenáři',
  'common.statistics': 'Statistiky',
  'common.lang.select': 'Vyberte jazyk',
  'common.submit': 'Uložit',
  'common.close': 'Zavřít',
  'common.comment': 'Komentář',
  'common.comments': 'Komentáře',
  '404': 'Stránka nenalezena',
  'search.users': 'Najdi uživatele',
  'common.help': 'Nápověda',

  'settings.biography': 'O Vás',
  'settings.biography.placeholder': 'Něco málo o Vás, pro Váš profil.',
  'settings.avatar': 'Avatar',
  'settings.avatar.own': 'Vás avatar',
  'settings.avatar.upload': 'Vybrat obrázek',
  'settings.email': 'E-maily',
  'settings.email.msg': 'E-maily spojené s Vaším účtem',
  'settings.email.verified.not': 'not verified',
  'settings.email.add': 'Přidat e-mail',
  'settings.languages': 'Nastavení jazyku',
  'settings.languages.notice': 'Angličtina je momentálně jediný oficiálně podporovaný jazyk. Ostatní jazyky jsou možné díky práci dobrovolníků a mohou být neúplné.',
  'settings.languages.join': 'Můžete pomoci s překladem.',
  'settings.name': 'Pravé jméno',
  'settings.name.given': 'Jméno',
  'settings.name.family': 'Příjmení',
  'settings.username': 'Změnit uživatelské jméno',
  'settings.username.label': 'Uživatelské jméno',
  'settings.patreon': 'Patreon', // name of a service, don't translate
  'settings.patreon.label': 'URL k Vašemu Patreon účtu',
  'settings.password': 'Změnit heslo',
  'settings.password.current': 'Současné heslo',
  'settings.password.new': 'Nové heslo',
  'settings.password.new.repeat': 'Zopakujte nové heslo',
  'settings.password.nomatch': 'Zadané heslo se neshoduje!',
  'settings.password.badlength': 'Heslo musí mít minimálně {legth} písmen.',
  'common.account.create': 'Vytvořit účet',
  'signup.username': 'Uživatelské jméno',
  'signup.email': 'Váš e-mail',
  'signup.password': 'Vaše heslo',
  'signup.password.repeat': 'Zopakujte Vaše heslo',
  'common.password': 'Heslo',
  'signin.password.forgot': 'Zapoměli jste heslo?',

  'password.reset': 'Resetovat heslo',
  'email.verification': 'E-mail verifikace',
  'email.verifying': 'Potvrzuji Váš e-mail. Hnedka to bude hotové...',
  'email.verified': 'Váš e-mail byl potvrzen!',
  'dashboard.whatsnew': 'Co je nového',
  'dashboard.blog': 'Autorský blog',

  'common.footer.tagline': 'Psaní a čtení rozsáhlách vesmírů jednoduše.',
  'common.footer.plans': 'Plany a ceny',
  'common.legal.tos': 'Smluvní podmínky',
  'common.legal.guidelines': 'Community Guidelines',
  'common.legal.privacy': 'Ochrana osobních údajů',
  'common.legal.copyright': 'Autorská práva',
  'common.legal.disclaimer': '© {year} Všechna práva vyhrazena, všechny texty patří jejich nálažitým vlastníkům.',

  'pm.conversation': 'Konverzace',
  'pm.showolder': 'Zobrazit starší zprávy.',
  'pm.errors.saysomething': 'Možná byste měli něco napsat...',
  'pm.errors.addrecipient': 'Musíte přidat alespoň jednoho příjemce.',
  'pm.message': 'Zpráva',
  'pm.send.message': 'Poslat zprávu',
  'pm.messages.own': 'Vaše zprávy',
  'pm.conversations.none': 'Momentálně nevedete žádné konverzace.',
  'pm.to': 'Pro:',

  'premium.only': 'Pouze pro premium uživatele',
  'premium.only.msg': 'Sorry, this functionality is for premium members only.',
  'premium.only.join': 'Become one today to gain access to this and many more features.',
  'premium.only.join.link': 'Check it out!',

  'user.friend.request': 'Přidat mezi přátele',
  'user.friend.requests': `Máte {num} {num, plural,
    zero {nových žádostí}
    one {novou žádost}
    few {nové žádosti}
    many {nových žádostí}
  } o přátelství`,
  'user.friend.unfriend': 'Zrušit přátelství',
  'user.block': 'Zablokovat',
  'user.unblock': 'Odblokovat',
  'user.joined': `{gender, select,
    male {Přidal}
    female {Přidala}
    other {Přidali}} se `, // keep the space at the end
  'user.friend.request.accept': 'Příjmout žádost o přátelství',
  'user.friend.request.deny': 'Otmítnout žádost o přátelství',
  'user.listing': 'Seznam uživatelů',
  'user.profile.visit': 'Navštiv profil pro {user}.',
  'user.friend.requests': 'Žádosti o přátelství',
  'user.friend.norequests': 'Momentálně nemáte žádné žádosti.',

  'feed': 'Stream',
  'feed.post.new': 'Nový příspěvek',
  'feed.post.like': 'Like post',
  'feed.post.unlike': 'Unlike post',
  'feed.post.send': 'Pošli',
  'feed.empty': 'Žádné příspěvky k zobrazení',

  'discovery.meta.desc': 'Objevte nové příběhy a vesmíry.',
  'discovery.universes.new': 'Emerging universes',
  'discovery.stories.new': 'Nové příběhy',
  'discovery.stories.new.standalone': 'Nové samostatné příběhy',
  'discovery.stories.updated': 'Nedávno aktualizované',
  'discovery.continue': 'Pokračovat ve čtení',
  'discovery.stories.similar.new': 'New stories in the neighbourhood',
  'discovery.stories.similar': 'Stories in the neighbourhood',

  'rating': 'Rating',
  'rating.explained': '',
  'rating.all': 'Pro všechny',
  'rating.all.desc': 'Přístupné všem věkům and skupinám.',
  'rating.teens': 'Teens',
  'rating.teens.desc': 'Přístupné pro čtenáře mezi 12 a 18 lety.',
  'rating.mature': 'Mature',
  'rating.mature.desc': 'Contains advance themes, crude language and implicit scenes.',
  'rating.explicit': 'Explicitní',
  'rating.explicit.desc': 'Contains explicit scenes.',
  'rating.selection.all': 'Pro všechny - Přístupné všem věkům and skupinám.',
  'rating.selection.teens': 'Teens (12-18) - Přístupné pro čtenáře mezi 12 a 18 lety.',
  'rating.selection.mature': 'Mature (18+) - Contains advance themes, crude language and implicit scenes.',
  'rating.selection.explicit': 'Explicitní (21+) - Contains explicit scenes.',

  'universe.visit': 'Navštivte stránku tohoto vesmíru',
  'universe.fanfiction': 'Fan Fikce',
  'universe.fanfiction.for.see': 'Všechna Fan Fikce pro ',
  'universe.fanfiction.desc': 'Fan Fikce pro {universe}',
  'universe.fanfiction.for': '{universe} Fan Fikce',
  'universe.stories.count': `Tento vesmír má {num} {num, plural,
    zero {příběhů}
    one {příběh}
    few {příběhy}
    other {příběhů}
  }.`,
  'universe.authors': 'Autoři',
  'universe.authors.desc': 'Tvůrci a spolupracovníci pro {universe}',
  'universe.contributors': 'Spolupracovníci',
  'universe.translators': 'Překladatelé',
  'universe.authors.notice': 'Each story might have additional personal that has worked on it. For more details see the details of the story.',
  'universe.createdby': 'Vytvořeno ',
  'universe.stories.for': 'Příběhy z {universe}',
  'universe.stories.own': '{universe} příběhy',
  'universe.stories.desc': 'Cannon příběhy pro {universe}',
  'universe.encyclopedia.title': '{universe} encyklopedie',
  'universe.encyclopedia.desc': 'Všechny detaily o {universe}',
  'story.chapter': 'Kapitola',
  'story.chapters': 'Kapitoly',
  'story.genre': 'Žánr',
  'story.genres': 'Žánry',
  'story.rating': 'Rating',
  'story.read': 'Číst',
  'story.lastUpdate': 'Naposledy aktualizováno {date, date, medium} {date, time, short}',
  'story.finishedAt': 'Dokončeno {date, date, medium}',
  'story.comments.for': 'Komentáře pro {story} {chapter}',
  'story.cover.alt': 'Obal pro {story}',
  'chapter.comment': 'Komentáře k této kapitole',
  'comment.write': 'Váš komentář',
  'comments.none': 'Žádné komentáře k zobrazení.',
  'comments.total': `Celkem {count, plural,
    zero {0 komentářů}
    one {1 komentář}
    few {# komentáře}
    other {# komentářů}
  }.`,
  'comments.show.older': 'Starší komentáře',
  'reader.language': 'Jazyk:',
  'reader.fullscreen.enter': 'Na celou obrazovku',
  'reader.fullscreen.exit': 'Zpátky do prohlížeče',
  'story.note.fanfiction': 'UPOZORNĚNÍ: Tento příběh je fan fikce pro {universe}.',
  'chapter.next': 'Další kapitola',
  'chapter.previous': 'Předchozí kapitola',
  'reader.details.universe': 'Detaily vesmíru',
  'reader.details.story': 'Detaily příběhu',
  'reader.darkmode': 'Zhasnout',
  'reader.flowtext': 'Přepnout velikost textu',
  'writer.save.beta': 'Revize pro Beta čtenáře',
  'writer.save.public': 'Publikovat',
  'writer.bold': 'Bold the selection',
  'writer.underline': 'Underline the selection',
  'writer.italic': 'Emphasize the selection',

  'encyclopedia.add': 'Add a new entry',
  'encyclopedia.browse': 'Browse through encyclopedia',
  'encyclopedia.search': 'Vyhledávat v encyklopedii',

  'finder.details': 'details',
  'finder.remove': 'remove the connection',
  'finder.connect': 'Connect selection to encyclopedia entry',

  'workshop.title': 'Vaše tvorba',
  'workshop.noneassigned': 'Zatím Vám bebyl žádný přidělen.',
  'workshop.notavailable': 'Tahle funkcionalita není momentálně přístupná.',
  'workshop.none': 'Momentálně nemáte žádný {name}. Vytvořte nový!',
  'workshop.collab': 'Collaborative work',
  'workshop.betareadings': 'Beta čtení',
  'workshop.translations': 'Překlady',
  'workshop.createnew': 'Vytvořit nový...',
  'workshop.story.standalone': 'Samostatný příběh',
  'workshop.story.standalone.desc': 'Toto je samostatný příběh.',
  'workshop.controlpanel': '{name} kontrolní panel',
  'workshop.universe.page': 'Universe page',
  'workshop.fictionaltime': 'Fictional time',
  'workshop.dashboard.name': '{name} kontrolní panel',
  'workshop.stories.in': 'Příběhy v {universe}',
  'workshop.universe.nostories': 'Tento vesmír nemá žádné příběhy.',
  'workshop.story.chapter.add': 'Nová kapitola',
  'workshop.universe.new': 'Vytvořit nový vesmír',
  'workshop.universe.publishing.note': 'Pokud nyní nepublikujete vesmír, tak bude automaticky publikován s prvním příběhem který je s ním spojený.',
  'workshop.universe.settings': '{universe} nastavení',
  'workshop.universe.publishedOn': 'Vesmír byl publikován ',
  'workshop.universe.description': 'Popis vesmíru',
  'workshop.title': 'Titulek',
  'workshop.title.required': 'Title is required',
  'workshop.description': 'Synopce',
  'workshop.language.primary': 'Hlavní jazyk',
  'workshop.publication.opions': 'Publication options',
  'workshop.rating': 'Rating',
  'workshop.universe.rating.desc': 'Příběhy a fan fikce nad tento rating nebudou zobrazeny na strance vesmíru anonymním uživatelům a uzivatelům kteří nedosáhli požadovaného věku.',
  'workshop.universe.license': 'License pro užívání vesmíru',
  'workshop.universe.genre.pick': 'Vyberte žánr pro vesmír',
  'workshop.story.genre.pick': 'Vyberte žánry pro vesmír',
  'workshop.cover': 'Obálka',
  'workshop.nothingtosee': 'Nic pro Vás nemám...',
  'workshop.story.cannon': 'Cannon story',
  'workshop.story.cannon.desc': 'This story is cannonical in {universe} universe.',
  'workshop.story.cannon.desc.create': 'This story will be created as a cannonical story in {universe} universe.',
  'workshop.story.fanfiction.search': 'Type in the name of the universe (it needs to be in your library). And then select from suggestions.',
  'workshop.story.error.nogenres': 'You need to select at least one genre.',
  'workshop.story.error.toomanygenres': 'Only two genres per story are allowed.',
  'workshop.story.error.fanfiction.selectuniverse': 'You need to select original universe for your fan fiction!',
  'workshop.story.error.tags.toomany': 'You can only have 10 tags per story.',
  'workshop.story.new': 'Create a new story',
  'workshop.story.publish.notice': 'The story will be published automatically once you publish the first chapter.',
  'workshop.settings.edit': 'Editovat nastavení',
  'workshop.story.publishedOn': 'Příběh byl publikován ',
  'workshop.story.settings': 'Nastavení příběhu',
  'workshop.settings.basic': 'Základní nastavení',
  'workshop.settings.genres': 'Žánry (maximálně 2)',
  'workshop.story.license': 'License příběhu',
  'workshop.story.settings.universe': 'Universe settings',
  'workshop.settings.tags': 'Tagy',
  'workshop.revision': 'Revize',
  'workshop.revisions.title': 'Revize {story}: {chapter}',
  'workshop.revisions.current': 'Pracovní verze',
  'workshop.revisions.new.beta': 'Vytvořit novou revizy ze současné verze.',
  'workshop.revisions.new.public': 'Vytvořit novou veřejnou revizi ze současné verze.',
  'workshop.revisions.toeditor': 'Vstoupit do editoru',
  'workshop.revisions.comments': 'Komentáře k revizím',
  'workshop.revisions.comments.title': '{story}: {chapter} - Revize {revision} - Komentáře',
  'workshop.revisions.comments.list': '{revision}: {publication, select, beta {pro Beta čtenáře} readers {Veřejné}} {datetime, date, medium} {datetime, time, short}',
  'workshop.revisions.comments.norevision': 'Nejdříve potřebujete vytvořit revizi.',
  'workshop.revisions.comments.select': 'Vyverte revizi',
  'workshop.collaborators.noresults': 'Nic nenalezeno',
  'workshop.collaborators.add.beta': 'Add as a Beta reader',
  'workshop.collaborators.add.collaborator': 'Add as a collaborator',
  'workshop.collaborators.add.translator': 'Add as a translator',

  'encyclopedia.back.universe': 'Zpět na stánku vesmíru',
  'encyclopedia.back.workshop': 'Zpátky do ateliéru',
  'encyclopedia.add': 'Přidat nový článek',
  'encyclopedia.categories': 'Kategorie',
  'encyclopedia.groups': 'Hyearchálně',
  'encyclopedia.category.character': 'Postavy',
  'encyclopedia.category.event': 'Události',
  'encyclopedia.category.group': 'Skupiny',
  'encyclopedia.category.item': 'Věci',
  'encyclopedia.category.location': 'Lokace',
  'encyclopedia.category.other': 'Ostatní',
  'encyclopedia.search.found': `{results, plural,
    zero {Nic nenalezeno}
    one {1 možný článek nalezen}
    few {# možné články nalezeny}
    other {# možných článků nalezeno}
  }.`,
  'encyclopedia.help.text': 'Use the menu on the left to navigate between the items in the encyclopedia. Once you select an item, it will be displayed instead of this text.',
  'encyclopedia.help.sidebar': 'Postraní encyklopedie',
  'encyclopedia.help.sidebar.text': 'Use the selection above to search, browse and add new entries to your encyclopedia. If you want to add connection to an entry from the story text, select the text where you want to place it and then click the connect button. You will be then prompted to find and select an item.',
  'encyclopedia.intro': 'Vítejte v encyklopedii pro {universe}.',
  'encyclopedia.entries.total': `Encyklopedie momentálně obsahuje {num, plural,
    zero {nula článků}
    one {jeden článek}
    few {# články}
    other {# článků}
  }.`,
  'encyclopedia.add.title': 'Přidat nový článek do encyklopedie',
  'encyclopedia.add.heading': 'Co si přejete přidat?',
  'encyclopedia.add.moresoon': 'Více katerorii, již brzy!',
  'encyclopedia.create': `Vytvořit novou {category, select,
    character {postavu}
    event {událost}
    group {skupinu}
    item {věc}
    location {lokaci}
    other {poznámku}
  }`,
  'encyclopedia.create.header': `Vytvořit novou {category, select,
    character {postavu}
    event {událost}
    group {skupinu}
    item {věc}
    location {lokaci}
    other {poznámku}
  } in {universe}`,
  'encyclopedia.entry.category': `Typ článku: {category, select,
    character {Postava}
    event {Událost}
    group {Skupina}
    item {Věc}
    location {Lokace}
    other {Ostatní}
  }`,
  'encyclopedia.fields.add': 'Přidat nové pole',
  'encyclopedia.fields.text': 'Definice',
  'encyclopedia.fields.textarea': 'Text',
  'encyclopedia.fields.connection': 'Spojení',
  'encyclopedia.fields.time': 'Čas',
  'encyclopedia.fields.image': 'Obrázek',
  'encyclopedia.visibility': 'Viditelnost článku',
  'encyclopedia.public': 'Veřejné',
  'encyclopedia.private': 'Soukromé',
  'encyclopedia.container': 'Container',
  'encyclopedia.container.desc': 'Make this entry a container for a new group of entries. This will hide it from categories listing.',
  'encyclopedia.entry.name': 'Jméno článku',
  'encyclopedia.summary': 'Shrnutí',
  'encyclopedia.summary.desc': 'Krátké shrnutí článku. Toto bude standartně zobrazeno jako jediné pole budeli článek zobrazen ve čtečce.',
  'encyclopedia.parent': 'Rodičovský článek',
  'encyclopedia.related': 'Příbuzné články',
  'encyclopedia.errors.tags': 'Můžete mít maximálně 10 tagů pro jeden článek.',
  'encyclopedia.field.private': 'Soukromé pole',
  'encyclopedia.title.save': 'Uložit titulek',
  'encyclopedia.ft.indev': 'Tato možnost je ve vývoji.',
  'encyclopedia.connections.remove': 'Ostranit spojení',
  'encyclopedia.connections.extra': 'Extra informace',
  'encyclopedia.connections.existing': 'Ecistující Článek',
  'encyclopedia.connections.existing.abbr': 'EČ', // abbreviation for Existing Entry

  // List of all genres
  'genre.scifi': 'Sci-fi',
  'genre.fantasy': 'Fantasy',
  'genre.adventure': 'Dobrodužství',
  'genre.poetry': 'Báseň',
  'genre.comedy': 'Komedie',
  'genre.drama': 'Drama',
  'genre.nonfiction': 'Non-fiction',
  'genre.romance': 'Romantika',
  'genre.satire': 'Satire',
  'genre.tragedy': 'Tragédie',
  'genre.crimi': 'Krimi',
  'genre.historical': 'Historická fikce',
  'genre.horror': 'Horor',
  'genre.mystery': 'Záhada',
  'genre.thriller': 'Thriller',
  'genre.western': 'Western',
  'genre.memoir': 'Vzpomínky',
  'genre.biography': 'Biografie',
  'genre.steampunk': 'Steampunk',
  'genre.mythology': 'Mytologie',
  'genre.fairytale': 'Fairy tale',

  // Licenses
  // https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
  'licenses.about': 'O licencích',
  'licenses.more': 'Více informací',
  'licenses.legal': 'Právní dokument',
  'licenses.name.cc-by': 'Creative Commons Attribution 4.0',
  'licenses.cc-by': 'This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.',
  'licenses.name.cc-by-sa': 'Creative Commons Attribution-ShareAlike 4.0',
  'licenses.cc-by-sa': 'This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms. This license is often compared to “copyleft” free and open source software licenses. All new works based on yours will carry the same license, so any derivatives will also allow commercial use. This is the license used by Wikipedia, and is recommended for materials that would benefit from incorporating content from Wikipedia and similarly licensed projects.',
  'licenses.name.cc-by-nd': 'Creative Commons Attribution-NoDerivs 4.0',
  'licenses.cc-by-nd': 'This license allows for redistribution, commercial and non-commercial, as long as it is passed along unchanged and in whole, with credit to you.',
  'licenses.name.cc-by-nc': 'Creative Commons Attribution-NonCommercial 4.0',
  'licenses.cc-by-nc': 'This license lets others remix, tweak, and build upon your work non-commercially, and although their new works must also acknowledge you and be non-commercial, they don’t have to license their derivative works on the same terms.',
  'licenses.name.cc-by-nc-sa': 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0',
  'licenses.cc-by-nc-sa': 'This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms.',
  'licenses.name.cc-by-nc-nd': 'Creative Commons Attribution-NonCommercial-NoDerivs 4.0',
  'licenses.cc-by-nc-nd': 'This license is the most restrictive of our six main licenses, only allowing others to download your works and share them with others as long as they credit you, but they can’t change them in any way or use them commercially.',
  'licenses.name.lu-c': 'Literary Universe Copyright',
  'licenses.lu-c': 'Standartní plný copyright license která Vám umožňuje publikování Vašeho dílá na Literary Universe s plnou ochranou Vašeho duševního vlastnictví. Tato license Vám také umožní prodávat Vaše dílo na Literary Universe.',
  'licenses.name.cc0': 'No Rights Reserved - CC0 1.0',
  'licenses.cc0': 'Put your work into public domain. In contrast to CC’s licenses that allow copyright holders to choose from a range of permissions while retaining their copyright, CC0 empowers yet another choice altogether – the choice to opt out of copyright and database protection, and the exclusive rights automatically granted to creators – the “no rights reserved” alternative to our licenses.',

  'library.add': 'Přidat do knihovny',
  'library.remove': 'Odebrat z knihovny',
  'library.bought': 'Zakoupené příběhy',
  'library.stories': 'Příběhy',
  'library.universes': 'Vesmíry',

  'homepage.welcome': 'Vítejte na Literary Universe!',
  'homepage.read': 'Čtení',
  'homepage.explore': 'Objevování',
  'homepage.create': 'Tvorba',
  'homepage.read.desc': 'Enjoy a great reading experience with access to details of the stories universe adjacent to the story text, without the need to leave the story window.',
  'homepage.explore.desc': 'Stories are not the only way to explore the literary universes. Each universe has its own page where you can explore all the minutia in the universe encyclopedia, see all the stories in the universe or explore what other fans have written.',
  'homepage.create.desc': 'Create your own stories and universes via our editor. Build and manage your ever expanding universes. We offer an expanding toolset, from a great story editor, through a great encyclopedia to management of translations of your stories and universe!',
  'homepage.begin': 'Začněte svou cestu!',
  'homepage.itisfree': 'Je to zadarmo!',

  'about.title': 'O Literary Universe',
  'about.desc': 'Historie, tajemství a lidé za Literary Universe.',
  'about.text.1': `Literary Universe is designed both for writers and for the avid reader. Writers can use the site to write original works through the workshop button in the dashboard menu. This will give you access to the main editor and encyclopedia functions which primarily focus on organizing all aspects of your personal story universe into one page. The social aspects allow authors to broadcast their work and develop a following, as well as to interact more directly if they chose with their readers.`,
  'about.text.2': `Readers can use the site primarily to read new works and follow authors but also to help edit pre-published stories if given permission by the writer. Being a reader on Literary Universe is a whole new reading experience, having access to all the background information on the same page as the main story gives you insight into the mind of the author like never before.`,
  'about.text.3': `The future for Literary Universe involves creating a marketplace for authors to sell their work and adding community features to enhance author and reader communication through blogs and forums. Writer’s tools will be added over time, with over a dozen currently either in development or on the board. Our ultimate goal is to enhance the experiences of writers and readers through providing more innovative use of the internet medium.`,
  'about.text.4': `Doufáme že se k nám přidáte a pomůžete nám objevit co internetové medium může udělat pro kreativní psaní!`,
  'about.team': 'Team',
  'about.history': 'Historie',
  'about.CEO': 'Výkonný ředitel',
  'about.CTO': 'Vedoucí vývoje',
  'about.scott': 'Scott became interested in creative writing in his early years and to this day is an avid reader. As someone who has always wanted to write his own book Scott became interested in Literary Universe when Jan Dvorak approached him with the idea for Literary Universe while they were in college. Scott has been been a part of Jan\'s development team since its inception and created the name for the site, among other notable contributions. Scott manages the business side of Literary Universe to allow Jan to focus on technological development.', 
  'about.jan': 'Honza je zakladatel, visionář a technologický mozek Literary Universe. Jako pisálek a čtenář velkých literárních vesmírů Honza měl vždycky problémy s psaním (a čtením) těchto příběhů z technického a čtenářského hlediska. Vidíce potencial ve webových technologii, Honza se rozhodl zaměřit své studia tímto směrem aby získal potřebné znalosti k vytvoření aplikace která by umožnila lepší psaní a čtení rozsáhlých literárních vesmírů.',
  'about.history.text': 'V roce 2010 Honza začal studovat webové technologie na Rochester Institute of Technology, hlavním cílem bylo získat potřebné technolgoie k vytvoření webové stránky pro kreativní psaní. První pokus o tuto stránku byl představen na jaře 2013 na školním festivalu Imagine RIT. Honza pokračoval ve svých studiích a v roce 2016 vytvořil novou verzi, tentokráte jako webovou aplikaci, jako svou dizertační práci pro magisterský titul. Tento projekt pokračoval na podzim téhož roku až do současné podoby.',

  'copyrights': 'Autorská práva',
  'copyrights.desc': 'Plné znění autorských práv pro Literary Universe.',
  'privacy.desc': 'Plné znění pro ochranu osobních údajů na Literary Universe.',
  'guidelines.desc': 'Community Guidelines of Literary Universe.',
  'guidelines.tldr': 'Ve zkratce: Buďte úžesní k ostatním!',
  'guidelines.text.1': 'This site has writers at every level of experience. It is important to respect your fellow writers and help them to succeed.',
  'guidelines.text.2': 'Collaborators, beta readers and reviewers are the backbone of our work. They help us improve as writers and make the reading experience more enjoyable for everyone. Please be respectful even when they are critical because without their efforts we would all have a much more difficult time editing our work.',
  'guidelines.text.3': 'Readers please be constructive in any critiques. Writers put in a lot of effort to create content for you to enjoy. If you do not like their work please leave reviews that are helpful and not just rude or nonsensical.',
  'guidelines.text.4': 'Pokud narazíte na nějaké problémy, kontaktujde adminy.',
  'tos.desc': 'Plné znění smluvních podmínek pro Literary Universe.',
  'plans.desc': 'Seznam plánů a funkcionality pro Literary Universe.',
  'plans.text': 'Literary Universe je v základní verzi zdarma. Nabízíme však premium verzi, která nabízí více možností.',
  'plans.account.free': 'Zakladní účet',
  'plans.account.premium': 'Premiový účet',
  'plans.eta': `Plánováno na `,
  'plans.price': 'Cena',
  'plans.price.free': 'Zadarmo',
  'plans.price.monthly': 'měsíčně',
  'plans.development': 'Ve vývoji',
  'plans.feature.publishing': 'Publikace a prodej příběhů',
  'plans.feature.scratchpad.pads': `{num, plural,
    one {1 pad}
    =5 {5 pads}
  }`,
  'plans.feature.editor': 'Příběhový editor',
  'plans.feature.encyclopedia': 'Encyklopedie',
  'plans.feature.collaborators': 'Maximální počet spolupracovníků',
  'plans.feature.collaborators.unlimited': 'Neomezeně',
  'plans.feature.fictionaltime': 'Fictional time',
  'plans.feature.stats': 'Zakladní statistiky',
  'plans.feature.stats.advanced': 'Pokročilé statistiky',
  'plans.feature.timelines': 'Timelines',
  'plans.feature.storylines': 'Storylines',
  'plans.feature.blogs': 'Autorský blog',
  'plans.feature.challenges': 'Psací výzvy',
  'plans.feature.encAdvanced': 'Pokročilejší funkcionalita pro encyklopedii',
  'plans.feature.universe.articles': 'Články pro vesmír',
  'plans.feature.universe.forums': 'Fóra pro vesmír',
  'plans.feature.collaborators.forums': 'Soukromá fóra pro spolupracovníky',
  
  'nanowrimo.settings': 'NaNoWriMo účet',
  'nanowrimo.username': 'NaNoWriMo uživatelské jméno',
  'nanowrimo.key': 'Tajný klíč',
  'nanowrimo.key.get': 'Získejte svůj NaNoWriMo klíč.',
  'nanowrimo.key.get.notice': 'Musíte být přihlášení aby jste klíč viděli.',
  'nanowrimo.ongoing': 'is in full swing! {countdown} more days to go!',
  'nanowrimo.startsin': `začne za {countdown, plural,
    one {1 den}
    few {# dny}
    other {# dnů}
    }! Připravte se!`,
  'nanowrimo.isover': 'NaNoWriMo skončilo. Naviděnou příští rok!',
  'nanowrimo.select': 'Vyberte tento příběh pro NaNoWriMo.',
  'nanowrimo.baseline': 'When NaNoWriMo starts it will take the current wordcount and use it as a baseline from which any additional words will be taken as part of NaNoWriMo.',
  'nanowrimo.victory': 'Gratulejeme! Vyhráli jste NaNoWriMo!',
  'nanowrimo.challenge': 'NaNoWriMo výzva',
  'nanowrimo.description': 'Cíl je napsat {words, number} slov dlouhou knihu během listopadu.',
  'nanowrimo.error.usernotfound': 'Username has not been found on the NaNoWriMo servers.',
  'nanowrimo.error.nobook': 'No book has been found. Please make sure you have created your book on NaNoWriMo.',
  'nanowrimo.error.wordcount': 'Unable to set wordcount on NaNoWrimo, please double check your credentials and try again.',

  'common.challenges': 'Výzvy',
  'challenges.wordcount': 'Monthly wordcount',
  'challenges.wordcount.desc': 'Set yourself a goal of how many words you want to write this month for his story.',
  'challenges.wordcount.select': 'How many words do you want to challenge yourself to?',
  'challenges.start': 'Začít výzvu',
  'challenges.report': 'Report',
  'challenges.victory': 'Congratulations! You have completed this challenge.',
  'challenges.defeat': 'Sadly you didn\'t complete this challenge.',
  'challenges.baseline': 'The current wordcount for this story is {wordcount}, this will be the starting point.',

  // you can get these messages from: https://github.com/gwendall/meteor-simple-schema-i18n/tree/master/i18n
  // but don't forget to adjust
  'simpleschema.required': '{label} je povinné pole',
  'simpleschema.minString': '{label} musí mít alespoň {min} písmen',
  'simpleschema.maxString': '{label} nesmí být vice jak {max} písmen',
  'simpleschema.minNumber': '{label} musí být alespoň {min}',
  'simpleschema.maxNumber': '{label} nesmí být vice jak {max}',
  'simpleschema.minNumberExclusive': '{label} musí být více než {min}',
  'simpleschema.maxNumberExclusive': '{label} musí být méně než {max}',
  'simpleschema.minDate': '{label} musí být {min} nebo později',
  'simpleschema.maxDate': '{label} nemůže být po {max}',
  'simpleschema.badDate': '{label} není validní datum',
  'simpleschema.minCount': 'Musíte vybrat alespoň {minCount} hodnot',
  'simpleschema.maxCount': 'Nemůžete vybrat více jak {maxCount} hodnot',
  'simpleschema.noDecimal': '{label} musí být celé číslo',
  'simpleschema.notAllowed': '{label} není povolená hodnota',
  'simpleschema.expectedString': '{label} musí být text',
  'simpleschema.expectedNumber': '{label} musí být číslo',
  'simpleschema.expectedBoolean': '{label} musí být boolean',
  'simpleschema.expectedArray': '{label} musí být seznam',
  'simpleschema.expectedObject': '{label} musí být objekt',
  'simpleschema.expectedConstructor': '{label} musí být {type}',
  'simpleschema.keyNotInSchema': '{key} není povoleno schématem',
  'simpleschema.notUnique': '{label} musí být unikátní',
  'simpleschema.regEx.0': '{label} neprošlo kontrolou regularního výrazu',
  'simpleschema.regEx.1': '{label} musí být validní e-mailová adresa',
  'simpleschema.regEx.2': '{label} musí být validní e-mailová adresa',
  'simpleschema.regEx.3': '{label} musí být validní doména',
  'simpleschema.regEx.4': '{label} musí být validní doména',
  'simpleschema.regEx.5': '{label} musí být validní IPv4 nebo IPv6 adresa',
  'simpleschema.regEx.6': '{label} musí být validní IPv4 adresa',
  'simpleschema.regEx.7': '{label} musí být validní IPv6 adresa',
  'simpleschema.regEx.8': '{label} musí být validní URL',
  'simpleschema.regEx.9': '{label} musí být validní alphanumerické ID',

  // for beta only
  'beta.notice': 'Vítejte v BETA verzi pro Literary Universe. BETA je speciální verze která je veřejně přístupná, ale ještě není plně odladěná a dokončená. To znamená že můžete narazit na problémy, chyby a nedokončenou funkcionalitu. Pokud se tak stane nebo něco nepracuje prosím informujte nás a buďte s námi trpělivý mezitím co budeme pracovat na nápravě.',
  'beta.thanks': 'Mnoho díků za Vaší podporu!',
}