export default {
  supportedLocales: ['en', 'cs'],
  languages: [
    {
      code: 'en',
      name: 'English',
      native: 'English',
      defaultLocale: 'en-US',
      supportedLocales: ['en-US', 'en-UK', 'en-CA', 'en-AU', 'en-NZ'],
      rtl: false
    },
    {
      code: 'cs',
      name: 'Czech',
      native: 'Česky',
      defaultLocale: 'cs-CZ',
      supportedLocales: ['cs-CZ'],
      rtl: false
    },
    {
      code: 'ja',
      name: 'Japanese',
      native: '日本語',
      defaultLocale: 'ja-JP',
      supportedLocales: ['ja-JP'],
      rtl: false
    }
  ],
  supportedLangs () {
    return this.languages.map(lang => lang.code) || []
  },
  /* eslint-disable object-shorthand */
  storyLanguages: function () {
    return this.languages.concat([
      {
        code: 'de',
        name: 'German',
        native: 'Deutsch',
        defaultLocale: 'de-GE',
        supportedLocales: ['de-GE'],
        rtl: false
      },
      {
        code: 'es',
        name: 'Spanish',
        native: 'Español',
        defaultLocale: 'es-ES',
        supportedLocales: ['es-ES'],
        rtl: false
      },
      {
        code: 'sk',
        name: 'Slovakian',
        native: 'Slovenčina',
        defaultLocale: 'sk-SK',
        supportedLocales: ['sk-SK'],
        rtl: false
      },
      {
        code: 'fr',
        name: 'French',
        native: 'Français',
        defaultLocale: 'fr-FR',
        supportedLocales: ['fr-FR', 'fr-CA', 'fr-CH', 'fr-LU', 'fr-BE', 'fr-MC', 'fr-CF'],
        rtl: false
      },
      {
        code: 'pl',
        name: 'Polish',
        native: 'Polski',
        defaultLocale: 'pl-PL',
        supportedLocales: ['pl-PL'],
        rtl: false
      },
      {
        code: 'pt',
        name: 'Portuguese',
        native: 'Português',
        defaultLocale: 'pt-PT',
        supportedLocales: ['pt-PT', 'pt-BR'],
        rtl: false
      },
      {
        code: 'ko',
        name: 'Korean',
        native: '한국어',
        defaultLocale: 'ko-KR',
        supportedLocales: ['ko-KR'],
        rtl: false
      },
      {
        code: 'hi',
        name: 'Hindi',
        native: 'मानक हिन्दी', // modern standard hindi
        defaultLocale: 'hi-IN',
        supportedLocales: ['hi-IN'],
        rtl: false
      },
      {
        code: 'it',
        name: 'Italian',
        native: 'Italiano',
        defaultLocale: 'it-IT',
        supportedLocales: ['it-IT', 'it-CH'],
        rtl: false
      }
    ])
  },
  storyLocales: function () {
    return this.storyLanguages().map(lang => lang.code)
  },
  /* eslint-enable object-shorthand */
  currencies: {
    USD: {
      sign: '$',
      location: 'before',
      fromUSD: 1
    },
    EUR: {
      sign: '€',
      location: 'after',
      fromUSD: 0.9
    },
    GBP: {
      sign: '$',
      location: 'before',
      fromUSD: 0.8
    },
    JPY: {
      sign: '￥',
      location: 'before',
      fromUSD: 110
    }
  },
  intlCurrencyFormats: {
    // format for MessageFormat
    number: {
      jpy: { style: 'currency', currency: 'JPY' },
      gbp: { style: 'currency', currency: 'GBP' },
      eur: { style: 'currency', currency: 'EUR' },
      usd: { style: 'currency', currency: 'USD' }
    }
  },
  countries: [
    'AF',
    'AX',
    'AL',
    'DZ',
    'AS',
    'AD',
    'AO',
    'AI',
    'AQ',
    'AG',
    'AR',
    'AM',
    'AN',
    'AW',
    'AU',
    'AT',
    'AZ',
    'BS',
    'BH',
    'BD',
    'BB',
    'BY',
    'BE',
    'BZ',
    'BJ',
    'BM',
    'BT',
    'BO',
    'BA',
    'BW',
    'BV',
    'BR',
    'IO',
    'BN',
    'BG',
    'BF',
    'BI',
    'KH',
    'CM',
    'CA',
    'CV',
    'KY',
    'CF',
    'TD',
    'CL',
    'CN',
    'CX',
    'CC',
    'CO',
    'KM',
    'CG',
    'CD',
    'CK',
    'CR',
    'CI',
    'HR',
    'CU',
    'CY',
    'CZ',
    'DK',
    'DJ',
    'DM',
    'DO',
    'EC',
    'EG',
    'SV',
    'GQ',
    'ER',
    'EE',
    'ET',
    'FK',
    'FO',
    'FJ',
    'FI',
    'FR',
    'GF',
    'PF',
    'TF',
    'GA',
    'GM',
    'GE',
    'DE',
    'GH',
    'GI',
    'GR',
    'GL',
    'GD',
    'GP',
    'GU',
    'GT',
    'GG',
    'GN',
    'GW',
    'GY',
    'HT',
    'HM',
    'VA',
    'HN',
    'HK',
    'HU',
    'IS',
    'IN',
    'ID',
    'IR',
    'IQ',
    'IE',
    'IM',
    'IL',
    'IT',
    'JM',
    'JP',
    'JE',
    'JO',
    'KZ',
    'KE',
    'KI',
    'KR',
    'KW',
    'KG',
    'LA',
    'LV',
    'LB',
    'LS',
    'LR',
    'LY',
    'LI',
    'LT',
    'LU',
    'MO',
    'MK',
    'MG',
    'MW',
    'MY',
    'MV',
    'ML',
    'MT',
    'MH',
    'MQ',
    'MR',
    'MU',
    'YT',
    'MX',
    'FM',
    'MD',
    'MC',
    'MN',
    'ME',
    'MS',
    'MA',
    'MZ',
    'MM',
    'NA',
    'NR',
    'NP',
    'NL',
    'NC',
    'NZ',
    'NI',
    'NE',
    'NG',
    'NU',
    'NF',
    'MP',
    'NO',
    'OM',
    'PK',
    'PW',
    'PS',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PN',
    'PL',
    'PT',
    'PR',
    'QA',
    'RE',
    'RO',
    'RU',
    'RW',
    'BL',
    'SH',
    'KN',
    'LC',
    'MF',
    'PM',
    'VC',
    'WS',
    'SM',
    'ST',
    'SA',
    'SN',
    'RS',
    'SC',
    'SL',
    'SG',
    'SK',
    'SI',
    'SB',
    'SO',
    'ZA',
    'GS',
    'ES',
    'LK',
    'SD',
    'SR',
    'SJ',
    'SZ',
    'SE',
    'CH',
    'SY',
    'TW',
    'TJ',
    'TZ',
    'TH',
    'TL',
    'TG',
    'TK',
    'TO',
    'TT',
    'TN',
    'TR',
    'TM',
    'TC',
    'TV',
    'UG',
    'UA',
    'AE',
    'GB',
    'US',
    'UM',
    'UY',
    'UZ',
    'VU',
    'VE',
    'VN',
    'VG',
    'VI',
    'WF',
    'EH',
    'YE',
    'ZM',
    'ZW'
  ]
}
