export default {
    'challenges.current': 'ਮੌਜੂਦਾ ਚੁਣੋਤੀਆਂ',
    'challenges.wordcount.goal': 'ਲਕੜੀ ਦੀ ਗਿਣਤੀ ਦੀ ਨਿਸ਼ਾਨਬੱਧ ਗਿਣਤੀ',
    'challenges.wordcount.dailygoal': 'ਹਰ ਰੋਜ਼ਾਨਾ ਲਿਖਿਆ ਗਿਣਤੀ ਦੀ ਨਿਸ਼ਾਨਬੱਧ ਗਿਣਤੀ',
    'challenges.wordcount.today': 'ਅੱਜ ਲਿਖਿਆ ਗਿਣਤੀ',
    'challenges.wordcount.total': 'ਕੁੱਲ ਲਿਖਿਆ ਗਿਣਤੀ',
    'challenges.wordcount.remaining': 'ਬਾਕੀ ਰਹੀ ਹੋਈਆਂ ਗਿਣਤੀ',
    'challenges.wordcount.daysleft': 'ਬਾਕੀ ਰਹੀਆਂ ਦਿਨ',
    'challenges.wordcount.currentDay': 'ਮੌਜੂਦਾ ਦਿਨ',
    'challenges.wordcount.average': 'ਔਸਤ ਦਿਨਾਂ ਵਿੱਚ ਸ਼ਬਦਾਂ ਦੀ ਗਿਣਤੀ',
    'challenges.wordcount.finishOn': 'ਮੌਜੂਦਾ ਰਫਤਾਰ ਤੇ ਤੁਸੀਂ ਖਤਮ ਕਰੋਗੇ',
    'challenges.wordcount.finishOnTime': 'ਸਮਾਂ \'ਤੇ ਖਤਮ ਕਰਨ ਲਈ ਰੋਜ਼ਾਨਾ ਲਿਖਣ ਲਈ ਸ਼ਬਦਾਂ ਦੀ ਗਿਣਤੀ',
    'challenges.wordcount.graph.day': 'ਦਿਨ {day}',
    'challenges.underway': 'ਇਹ ਚੁਣੋਤੀ ਪਹਿਲਾਂ ਹੀ ਸ਼ੁਰੂ ਹੋ ਚੁਕੀ ਹੈ।',
    'challenges.targetWords': 'ਕੁੱਲ ਨਿਸ਼ਾਨਬੱਧ ਗਿਣਤੀ',
    'challenges.startDate': 'ਸ਼ੁਰੂ ਕਰਨ ਦੀ ਮਿਤੀ',
    'challenges.endDate': 'ਅੰਤ ਦੀ ਮਿਤੀ',
    'challenges.future': 'ਆਉਣ ਵਾਲੀਆਂ ਚੁਣੋਤੀਆਂ',
    'challenges.future.wordcount': 'ਸ਼ਬਦਗਣ ਚੈਲੈਂਜ ਦੀ ਸ਼ੁਰੂਆਤ {startDate, date, short} ਨਾਲ ਕਰੋ, ਜਿਸ ਦਾ ਲਕ੍਷਼ਾਂਕ ਹੈ {target, number} ਨੂੰ {endDate, date, short}ਤੱਕ ਪਹੁੰਚਾਉਣਾ।',
    'challenges.future.nanowrimo': 'NaNoWriMo ਚੁਣੋਤੀ ਤਿਆਰ ਹੈ।',
    'challenges.wordcount': 'ਸ਼ਬਦਾਂ ਦੀ ਗਿਣਤੀ',
    'challenges.wordcount.desc': `ਇਸ ਮਹੀਨੇ ਇਸ {type, select,
    story {ਕਹਾਣੀ}
    universe {ਯੂਨੀਵਰਸ}
    other {ਵਿੱਚ ਲਿਖਣ ਲਈ ਆਪਣੇ ਨੂੰ ਇੱਕ ਲਕ੍਷਼ ਸ਼ਬਦਾਂ ਦਾ ਲਕ੍਷਼ਾ ਸੈੱਟ ਕਰੋ}
  }।`,
    'challenges.wordcount.select': 'ਤੁਸੀਂ ਕਿੰਝ ਸ਼ਬਦਾਂ ਨਾਲ ਆਪਣੇ ਨੂੰ ਚੁਣੋਤੀ ਦੇਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
    'challenges.start': 'ਚੁਣੋਤੀ ਸ਼ੁਰੂ ਕਰੋ',
    'challenges.report': 'ਰਿਪੋਰਟ',
    'challenges.victory': 'ਮੁਬਾਰਕਾਂ! ਤੁਸੀਂ ਇਸ ਚੁਣੋਤੀ ਨੂੰ ਪੂਰਾ ਕਰ ਚੁੱਕੇ ਹੋ।',
    'challenges.defeat': 'ਖੇਦ ਹੋਇਆ ਕਿ ਤੁਸੀਂ ਇਸ ਚੁਣੋਤੀ ਨੂੰ ਪੂਰਾ ਨਹੀਂ ਕਰ ਸਕੇ।',
    'challenges.baseline': 'ਇਸ ਕਹਾਣੀ ਦਾ ਮੌਜੂਦਾ ਸ਼ਬਦਗਣਤਾ ਹੈ {wordcount, number}, ਇਹ ਸ਼ੁਰੂਆਤੀ ਬਿੰਦੂ ਹੋਵੇਗਾ।',
    // NaNoWriMo
    'nanowrimo.full': 'ਨੈਸ਼ਨਲ ਨਾਵਲ ਲੇਖਣ ਮਹੀਨਾ',
    'nanowrimo.site': 'NaNoWriMo ਆਧਿਕਾਰਿਕ ਸਾਈਟ',
    'nanowrimo.settings': 'NaNoWriMo ਖਾਤਾ',
    'nanowrimo.username': 'NaNoWriMo ਯੂਜ਼ਰਨਾਮ',
    'nanowrimo.key': 'ਗੁਪਤ ਕੁੰਜੀ',
    'nanowrimo.key.get': 'ਆਪਣਾ NaNoWriMo ਕੀ ਪ੍ਰਾਪਤ ਕਰੋ।',
    'nanowrimo.key.get.notice': 'ਇਸ ਨੂੰ ਵੇਖਣ ਲਈ ਤੁਸੀਂ ਲੌਗ ਇਨ ਹੋਣ ਦੀ ਲੋੜ ਹੈ।',
    'nanowrimo.ongoing': 'ਪੂਰੀ ਤੇਜੀ ਹੋ ਰਹੀ ਹੈ! ਹੋਰ {countdown} ਦਿਨ ਬਾਕੀ ਹਨ!',
    'nanowrimo.startsin': `ਸ਼ੁਰੂ ਹੋਵੇਗਾ {countdown, plural,
      one {1 ਦਿਨ}
      other {# ਦਿਨ}
    }! ਤਿਆਰ ਹੋ ਜਾਓ!`,
    'nanowrimo.isover': 'NaNoWriMo ਖਤਮ ਹੋ ਗਿਆ ਹੈ। ਅਗਲੇ ਸਾਲ ਮਿਲਾਂਗੇ!',
    'nanowrimo.select': 'ਇਸ ਕਹਾਣੀ ਨੂੰ NaNoWriMo ਲਈ ਨਿਯੁਕਤ ਕਰੋ।',
    'nanowrimo.baseline': 'NaNoWriMo ਸ਼ੁਰੂ ਹੋਣ ਤੇ ਉਹ ਮੌਜੂਦਾ ਸ਼ਬਦਗਣਤੀ ਨੂੰ ਬੇਸਲਾਈਨ ਵਜੋਂ ਲੈਣਗਾ, ਜਿਸ ਵਿੱਚ ਕੋਈ ਵਾਧੂ ਸ਼ਬਦ ਹੋਵੇਗਾ।',
    'nanowrimo.victory': 'ਮੁਬਾਰਕਾਂ! ਤੁਸੀਂ NaNoWriMo ਜਿੱਤ ਗਏ ਹੋ!',
    'nanowrimo.challenge': 'NaNoWriMo ਚੈਲੰਜ',
    'nanowrimo.description': 'ਚੈਲੰਜ ਹੈ ਨਵੰਬਰ ਦੌਰਾਨ {words, number} ਸ਼ਬਦਾਂ ਦੀ ਇੱਕ ਨਾਵਲ ਲਿਖਣ ਵਾਲੀ।',
    'nanowrimo.error.usernotfound': 'ਯੂਜ਼ਰਨੇਮ NaNoWriMo ਸਰਵਰਾਂ \'ਤੇ ਨਹੀਂ ਲੱਭਿਆ ਗਿਆ ਹੈ।',
    'nanowrimo.error.nobook': 'ਕੋਈ ਕਿਤਾਬ ਨਹੀਂ ਲੱਭੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਨਾਨੋਵ੍ਰਿਮੋ \'ਤੇ ਆਪਣੀ ਕਿਤਾਬ ਬਣਾਈ ਹੈ ਜੀ।',
    'nanowrimo.error.wordcount': 'NaNoWrimo \'ਤੇ ਸ਼ਬਦਗਣਤੀ ਸੈੱਟ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ, ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਕ੍ਰੈਡੈਂਸ਼ਿਅਲਾਂ ਦੀ ਜਾਂਚ ਕਰੋ ਅਤੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    'nanowrimo.connected': 'ਤੁਸੀਂ ਇਸ ਕਹਾਣੀ ਨੂੰ NaNoWriMo ਲਈ ਨਿਯੁਕਤ ਕੀਤਾ ਹੈ।',
    'nanowrimo.connected.other': 'ਤੁਸੀਂ ਪਹਿਲਾਂ ਹੀ ਕੋਈ ਹੋਰ ਕਹਾਣੀ ਜੁੜ ਗਏ ਹੋ।'
};