export default {
  'courses.courses': 'ਕੋਰਸ',
  'courses.overview': 'ਕੋਰਸਾਂ ਦਾ ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
  'courses.public.title': 'Explore Courses',
  'courses.public.heading': 'Explore Courses',
  'courses.public.filters': 'Filter Courses',
  'courses.public.noResults': 'No courses found',
  'courses.public.tryDifferentFilters': 'Try different search terms or filters',
  'courses.filter.search': 'Search courses...',
  'courses.filter.allTypes': 'All Types',
  'courses.filter.clearAll': 'Clear All',
  'courses.filter.type': 'Type',
  'courses.type.course': 'Course',
  'courses.type.workshop': 'ਕਰਿਆਸ਼ਾਲਾ',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Course',
  'courses.type.workshop.lowercase': 'ਕਰਿਆਸ਼ਾਲਾ',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'ਨਵਾਂ ਕੋਰਸ ਬਣਾਓ',
  'course.reading.title': 'ਪੜ੍ਹਾਈ ਦਾ ਕੰਮ ਸਿਰਲੇਖ',
  'course.question.add': 'ਸਵਾਲ ਸ਼ਾਮਲ ਕਰੋ',
  'course.lessons.newMessage': 'ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਅਧਿਆਪਨ ਲਈ ਆਪਣੇ ਪਾਠਾਂ ਨੂੰ ਬਣਾਓ ਅਤੇ ਸੰਗਠਿਤ ਕਰੋ।',
  'course.reading.new': 'ਪੜ੍ਹਨ ਦਾ ਕੰਮ',
  'course.reading.newMessage': 'ਆਪਣੇ ਵਿਦਿਆਰਥੀਆਂ ਲਈ ਪੜ੍ਹਨ ਦੇ ਕੰਮ ਬਣਾਓ ਅਤੇ ਉਹਨਾਂ ਨੂੰ ਵਿਵਸਥਿਤ ਕਰੋ।',
  'course.writing.new': 'ਲਿਖਤੀ ਸ਼ਾਮਲਤ',
  'course.writing.newMessage': 'ਲਿਖਣ ਦੇ ਕੰਮਾਂ ਨੂੰ ਤੇਜ਼ੀ ਨਾਲ ਸੈੱਟ ਅਪ ਕਰੋ ਅਤੇ ਵੰਡੋ',
  'course.question.text': 'ਤੁਹਾਡਾ ਸਵਾਲ ਇੱਥੇ ਹੈ',
  'course.question.type': 'ਕਿਰਪਾ ਕਰਕੇ ਸਵਾਲ ਦੀ ਕਿਸਮ ਚੁਣੋ',
  'course.question.delete': 'ਸਵਾਲ ਹਟਾਓ',
  'course.type': 'Course Type',
  'course.visibility': 'ਦਿਖਾਈ ਦੀ ਚੋਣ ਚੁਣੋ',
  'course.title': 'ਸਿਰਲੇਖ',
  'course.description': 'ਵਰਣਨ',
  'course.cover': 'ਕਵਰ',
  'course.start': 'ਤੁਹਾਡਾ ਕੋਰਸ ਸ਼ੁਰੂ ਹੁੰਦਾ ਹੈ',
  'course.ends': 'ਤੁਹਾਡਾ ਕੋਰਸ ਦੇ ਬਦਲੇ ਹੁੰਦਾ ਹੈ',
  'course.curriculum': 'Course Curriculum',
  'course.members': 'ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਅਧਿਆਪਕ',
  'course.assignments': 'ਕਰਜ',
  'course.question.deleteWhole': 'ਪੂਰੀ ਪ੍ਰਸ਼ਨ ਹਟਾਓ',
  'course.question.yes': 'ਹਾਂ',
  'course.question.no': 'ਨਹੀਂ',
  'course.lesson.title': 'ਪਾਠ ਸਿਰਲੇਖ',
  'course.lesson.add.universe': 'ਕਹਾਣੀ/ਯੂਨੀਵਰਸ ਸ਼ਾਮਲ ਕਰੋ',
  'course.lesson.externalLinks': 'External links',
  'course.lesson.add.link': 'ਬਾਹਰੀ ਲਿੰਕ ਸ਼ਾਮਲ ਕਰੋ',
  'course.status': 'ਸਥਿਤੀ',
  'course.active': 'ਗਤੀਵਿਧੀ',
  'course.active.message': 'ਸਰਗਰਮ',
  'course.inactive': 'ਗੈਰ-ਸਰਗਰਮ',
  'course.upload.resource': 'Upload a resource',
  'course.question.answer': 'ਜਵਾਬ ਸ਼ਾਮਲ ਕਰੋ',
  'course.question.open': 'ਖੁੱਲ੍ਹਾ ਸਵਾਲ',
  'course.question.close': 'ਬੰਦ ਸਵਾਲ',
  'course.question.multiple': 'ਬਹੁ-ਚੋਣ ਵਾਲਾ ਸਵਾਲ',
  'course.about': 'ਇਸ ਕੋਰਸ ਬਾਰੇ',
  'course.lesson.new': 'ਇੱਕ ਨਵਾਂ ਪਾਠ ਬਣਾਓ',
  'course.lesson.type': 'ਪਾਠ ਦੀ ਕਿਸਮ',
  'course.lesson.inPerson': "ਨਿੱਜੀ ਤੌਰ 'ਤੇ",
  'course.lesson.preRecorded': 'ਪਹਿਲਾਂ ਤੋਂ ਰਿਕਾਰਡ ਕੀਤਾ',
  'course.lesson.online': 'ਆਨਲਾਈਨ',
  'course.lesson.text': 'ਸਿਰਫ਼ ਲਿਖਤ',
  'course.lesson.content': 'ਪਾਠ ਦੀ ਸਮੱਗਰੀ',
  'course.lesson.description': 'ਜਨਤਕ ਵੇਰਵਾ',
  'course.add.story': 'ਕਹਾਣੀ ਸ਼ਾਮਲ ਕਰੋ',
  'course.remove.story': 'ਕਹਾਣੀ ਹਟਾਓ',
  'course.dateOfPublish': 'ਪ੍ਰਕਾਸ਼ਨ ਦੀ ਮਿਤੀ',
  'course.lesson.meetInPerson': "ਨਿੱਜੀ ਤੌਰ 'ਤੇ ਮਿਲੋ",
  'course.curriculum.edit': 'ਪਾਠਕ੍ਰਮ ਸੰਪਾਦਿਤ ਕਰੋ',
  'course.stories.own': 'ਤੁਹਾਡੀਆਂ ਆਪਣੀਆਂ ਕਹਾਣੀਆਂ',
  'course.stories.organization': 'ਸੰਸਥਾ ਦੀਆਂ ਕਹਾਣੀਆਂ',
  'course.stories.public': 'ਜਨਤਕ ਕਹਾਣੀਆਂ',
  'course.publish.at': 'ਮੈਂ ਚਾਹੁੰਦਾ ਹਾਂ ਕਿ ਇਹ ਕੋਰਸ ਇੱਥੇ ਪ੍ਰਕਾਸ਼ਿਤ ਹੋਵੇ:',
  'course.edit.curriculum': 'ਪਾਠਕ੍ਰਮ ਸੰਪਾਦਿਤ ਕਰੋ',
  'course.assignment': 'ਕਰਤੱਵ',
  'course.lesson.removeLink': 'ਲਿੰਕ ਹਟਾਓ',
  'course.user.remove': 'Remove user',
  'course.user.invite': 'Invite user',
  'course.user.invited': 'Invited',
  'course.edit.role': 'ਭੂਮਿਕਾ ਸੰਪਾਦਿਤ ਕਰੋ',
  'course.assignment.description': 'ਅਸਾਈਨਮੈਂਟ ਦਾ ਵੇਰਵਾ',
  'course.internal': 'ਅੰਦਰੂਨੀ',
  'course.free': 'ਮੁਫ਼ਤ',
  'course.sale': 'ਛੂਟ',
  'course.announcements': 'Announcements',
  'course.announcements.full': 'Course announcements',
  'course.announcements.create': 'Create an announcement',
  'course.join': 'Join Course',
  'course.joining': 'Joining...',
  'course.join.success': 'You have successfully joined this course!',
  'course.join.error.payment': 'This course requires payment to join.',
  'course.join.error.invite': 'This course requires an invitation to join.',
  'course.join.error.generic': 'There was an error joining the course. Please try again.',
  'course.firstLesson': 'First Lesson',
  'course.upcomingLessons': 'Upcoming Lessons',
  'course.detail.title': '{courseName} | Course',
  'lessons.visibility.public': 'Public',
  'lessons.visibility.private': 'Private',
  'course.curriculum.empty': 'No curriculum items available yet.',
  'course.preview.message': 'This is a preview of the course. Join the course to access all content.',
  'course.details': 'Course Details',
  'course.tab.curriculum': 'Curriculum',
  'course.tab.details': 'Course Details',
  'course.duration': 'Duration',
  'course.perpetual': 'Perpetual',
  'course.language': 'Language',
  'course.price': 'Price',
  'course.learningObjectives': 'Learning Objectives',
  'course.prerequisites': 'Prerequisites',
  'course.tags': 'Tags',
  'course.stats.members': 'Members',
  'course.stats.lessons': 'Lessons',
  'course.assignments.comingSoon': 'Assignments view is coming soon.',
  'course.progress.comingSoon': 'Progress tracking is coming soon.',
  'course.type.free': 'ਮੁਫ਼ਤ',
  'course.type.paid': 'Paid',
  'course.type.forSale': 'For Sale',
  'course.type.invite': 'Invite Only',
  'courses.invites.tile': 'You are invited to partake in {count, plural, one {course} other {courses}}.',
  'courses.invites.noInvites': "You don't have any course invitations at the moment.",
  'courses.invites.invitedBy': 'Invited by: ',
  'course.join.heading': 'Join This Course',
  'course.oneTimePayment': 'One-time payment for full access',
  'course.member': "You're Enrolled",
  'course.member.access': 'You have full access to all course materials.',
  'courses.members.editRole': 'Edit Role',
  'courses.members.editRoleFor': 'Edit role for:',
  'courses.add.member': 'Add a new member',
  'course.member.options': 'Course member list',
  'course.navigation.curriculum': 'Curriculum',
  'course.navigation.members': 'Students & Teachers',
  'course.navigation.assignments': 'ਕਰਜ',
  'course.navigation.forums': 'Forums',
  'course.navigation.attendance': 'Attendance',
  'course.members.teachers': 'Teachers',
  'course.members.students': 'Students',
  'course.members.preview.message': 'Join this course to see all students and interact with the community.',
  'course.member.role.owner': 'ਮਾਲਕ',
  'course.member.role.teacher': 'ਅਧਿਆਪਕ',
  'course.member.role.student': 'ਵਿਦਿਆਰਥੀ',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'course.startDate': 'Start Date',
  'course.endDate': 'End Date',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Curriculum Preview',
  'course.curriculum.preview.message': 'Join this course to access all {count} lessons and assignments.',
  'course.curriculum.locked': 'Locked',
  'course.curriculum.lesson': 'Lesson',
  'course.curriculum.assignment': 'ਕਰਤੱਵ',
  'course.curriculum.reading': 'Reading',
  'course.lesson.backToCurriculum': 'Back to Curriculum',
  'course.lesson.nextLesson': 'Next Lesson',
  'course.lesson.documents': 'Documents & Resources',
  'course.lesson.meetingLink': 'Meeting Link',
  'course.lesson.location': 'Location',
  'course.lesson.virtualClassroom': 'Virtual Classroom',
  'course.lesson.joinClassroom': 'Join the virtual classroom session',
  'course.lesson.enterClassroom': 'Enter Classroom',
  'course.assignment.acceptsStories': 'ਕਹਾਣੀਆਂ ਸਵੀਕਾਰ ਕਰਦਾ ਹੈ',
  'course.assignment.acceptsUniverses': 'ਬ੍ਰਹਿਮੰਡਾਂ ਨੂੰ ਸਵੀਕਾਰ ਕਰਦਾ ਹੈ',
  'course.assignment.backToAssignments': "ਅਸਾਈਨਮੈਂਟਾਂ 'ਤੇ ਵਾਪਸ",
  'course.assignment.criteria': 'ਪੜ੍ਹਨ ਦੇ ਮਾਪਦੰਡ',
  'course.assignment.dueDate': 'ਜਮ੍ਹਾਂ ਕਰਨ ਦੀ ਮਿਤੀ: {date}',
  'course.assignment.freeReading': 'ਮੁਫ਼ਤ ਪੜ੍ਹਨ ਦੀ ਸਹੂਲਤ ਯੋਗ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ।',
  'course.assignment.grade': 'ਗਰੇਡ',
  'course.assignment.grade.received': 'ਗ੍ਰੇਡ: {grade}',
  'course.assignment.gradeSaveError': 'ਗ੍ਰੇਡ ਸੇਵ ਨਹੀਂ ਹੋ ਸਕਿਆ',
  'course.assignment.gradeSaved': 'ਗ੍ਰੇਡ ਬਚਾਇਆ ਗਿਆ।',
  'course.assignment.gradedCount': '{count, plural, one {# ਗ੍ਰੇਡ ਕੀਤਾ} other {# ਗ੍ਰੇਡ ਕੀਤਾ}}',
  'course.assignment.grading.help':
    'ਵਿਦਿਆਰਥੀਆਂ ਦੀਆਂ ਪੇਸ਼ਕਸ਼ਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ, ਲਿੰਕ ਕੀਤੀਆਂ ਕਹਾਣੀਆਂ ਜਾਂ ਬ੍ਰਹਿਮੰਡ ਖੋਲ੍ਹੋ, ਅਤੇ ਇੱਕ ਵਿਕਲਪਿਕ ਗ੍ਰੇਡ ਅਤੇ ਫੀਡਬੈਕ ਸ਼ਾਮਲ ਕਰੋ।',
  'course.assignment.grading.title': 'ਗ੍ਰੇਡਿੰਗ: {title}',
  'course.assignment.grading.unavailable': 'ਗ੍ਰੇਡਿੰਗ ਉਪਲਬਧ ਨਹੀਂ',
  'course.assignment.grading.unavailableMessage':
    'ਤੁਹਾਨੂੰ ਇਸ ਗ੍ਰੇਡਿੰਗ ਪੰਨੇ ਤੱਕ ਪਹੁੰਚ ਨਹੀਂ ਹੈ, ਜਾਂ ਅਸਾਈਨਮੈਂਟ ਨਹੀਂ ਮਿਲੀ।',
  'course.assignment.lastRead': 'ਆਖਰੀ ਵਾਰ ਪੜ੍ਹਿਆ {date}',
  'course.assignment.minutes': '{count} ਮਿੰਟ',
  'course.assignment.noSubmissions': 'ਹਾਲੇ ਤੱਕ ਕੋਈ ਦਾਖਲਾ ਨਹੀਂ।',
  'course.assignment.noWrittenResponse': 'ਕੋਈ ਲਿਖਤੀ ਜਵਾਬ ਨਹੀਂ ਦਿੱਤਾ ਗਿਆ।',
  'course.assignment.notFound': 'ਅਸਾਈਨਮੈਂਟ ਨਹੀਂ ਮਿਲੀ',
  'course.assignment.notFoundMessage': 'ਮੰਗੀ ਗਈ ਅਸਾਈਨਮੈਂਟ ਨਹੀਂ ਮਿਲੀ।',
  'course.assignment.noteForTeacher': 'ਆਪਣੇ ਅਧਿਆਪਕ ਲਈ ਇੱਕ ਨੋਟ ਸ਼ਾਮਲ ਕਰੋ',
  'course.assignment.open': 'ਖੁੱਲ੍ਹੀ ਅਸਾਈਨਮੈਂਟ',
  'course.assignment.openGrading': 'ਗ੍ਰੇਡਿੰਗ ਪੰਨਾ ਖੋਲ੍ਹੋ',
  'course.assignment.questions': 'ਸਵਾਲ',
  'course.assignment.readingProgress': 'ਵਿਦਿਆਰਥੀ ਦੀ ਪੜ੍ਹਾਈ ਵਿੱਚ ਤਰੱਕੀ',
  'course.assignment.readings': 'ਨਿਰਧਾਰਤ ਪਾਠ',
  'course.assignment.responsePlaceholder': 'ਇੱਥੇ ਆਪਣਾ ਜਵਾਬ ਲਿਖੋ',
  'course.assignment.responsePrompt': 'ਨਿਬੰਧ ਦਾ ਵਿਸ਼ਾ ਜਾਂ ਜਰਨਲ ਲਈ ਸੁਝਾਅ',
  'course.assignment.selectStoriesRead': 'ਇਸ ਅਸਾਈਨਮੈਂਟ ਲਈ ਤੁਸੀਂ ਚੁਣੀਆਂ ਕਹਾਣੀਆਂ ਚੁਣੋ।',
  'course.assignment.sharedProject.studentHelp':
    'ਉਪਰ ਦਿੱਤੇ ਸਾਂਝੇ ਪ੍ਰੋਜੈਕਟ ਵਰਕਸ ਵਿੱਚੋਂ ਕਿਸੇ ਇੱਕ ਨੂੰ ਵਰਕਸ਼ਾਪ ਵਿੱਚ ਖੋਲ੍ਹੋ ਅਤੇ ਉੱਥੇ ਯੋਗਦਾਨ ਪਾਓ। ਇਸ ਅਸਾਈਨਮੈਂਟ ਲਈ ਵੱਖਰੇ ਸਬਮਿਸ਼ਨ ਫਾਰਮ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।',
  'course.assignment.sharedProject.studentTitle': 'ਇਸ ਅਸਾਈਨਮੈਂਟ ਨੂੰ ਕਿਵੇਂ ਪੂਰਾ ਕਰਨਾ ਹੈ',
  'course.assignment.sharedProject.teacherNotice':
    'ਇਹ ਸਾਂਝੇ ਪ੍ਰੋਜੈਕਟ ਦਾ ਅਸਾਈਨਮੈਂਟ ਵਿਅਕਤੀਗਤ ਜਮ੍ਹਾਂ ਕਰਨ ਦੀ ਥਾਂ ਸਹਿਯੋਗੀ ਪਹੁੰਚ ਦੀ ਵਰਤੋਂ ਕਰਦਾ ਹੈ।',
  'course.assignment.sharedProjects': 'ਸਾਂਝੇ ਪ੍ਰੋਜੈਕਟ ਦੇ ਕੰਮ',
  'course.assignment.storiesCompleted': 'ਕਹਾਣੀਆਂ ਪੂਰੀਆਂ ਹੋਈਆਂ',
  'course.assignment.submissionCount': '{count, plural, one {# ਭੇਜੀ ਗਈ} other {# ਭੇਜੀਆਂ ਗਈਆਂ}}',
  'course.assignment.submissionSaved': 'ਸਮਰਪਣ ਸੁਰੱਖਿਅਤ ਹੋ ਗਿਆ।',
  'course.assignment.submissions': 'ਜਮ੍ਹਾਂ ਅਤੇ ਅੰਕਨ',
  'course.assignment.submit': 'ਅਸਾਈਨਮੈਂਟ ਜਮ੍ਹਾਂ ਕਰੋ',
  'course.assignment.submitError': 'ਅਸਾਈਨਮੈਂਟ ਜਮ੍ਹਾਂ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ',
  'course.assignment.submitWork': 'ਜਮ੍ਹਾਂ ਕਰਨ ਲਈ ਕੰਮ ਚੁਣੋ',
  'course.assignment.submitWork.help':
    'ਇਸ ਅਸਾਈਨਮੈਂਟ ਲਈ ਜਿਸ ਕਹਾਣੀ ਜਾਂ ਬ੍ਰਹਿਮੰਡ ਨੂੰ ਗ੍ਰੇਡ ਕੀਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ, ਉਸਨੂੰ ਚੁਣੋ।',
  'course.assignment.submitWork.label': 'ਜਮ੍ਹਾਂ ਕੀਤਾ ਕੰਮ',
  'course.assignment.submitWork.placeholder': 'ਇੱਕ ਕਹਾਣੀ ਜਾਂ ਬ੍ਰਹਿਮੰਡ ਚੁਣੋ',
  'course.assignment.submittedAt': 'ਤੇ ਜਮ੍ਹਾਂ ਕੀਤਾ ਗਿਆ {date}',
  'course.assignment.submittedWork.story': 'ਪੇਸ਼ ਕੀਤੀ ਕਹਾਣੀ: {title}',
  'course.assignment.submittedWork.universe': 'ਪੇਸ਼ ਕੀਤਾ ਬ੍ਰਹਿਮੰਡ: {title}',
  'course.assignment.supportingFiles': 'ਸਹਾਇਕ ਸਮੱਗਰੀ ਅਪਲੋਡ ਕੀਤੀ ਗਈ',
  'course.assignment.supportingMaterials': 'ਸਹਾਇਕ ਸਮੱਗਰੀ',
  'course.assignment.updateSubmission': 'ਅੱਪਡੇਟ ਜਮ੍ਹਾਂ ਕਰੋ',
  'course.assignment.yourSubmission': 'ਤੁਹਾਡੀ ਪੇਸ਼ਕਸ਼',
  'courses.role.owner': 'ਮਾਲਕ',
  'courses.role.teacher': 'ਅਧਿਆਪਕ',
  'courses.role.student': 'ਵਿਦਿਆਰਥੀ',
};
