export default {
    'workshop.title': 'ਤੁਹਾਡਾ ਕੰਮ',
    'workshop.noneassigned': 'ਤੁਹਾਡੇ ਕੋਲ ਹਾਲੇ ਕੋਈ ਵੀ ਸੌਂਪਿਆ ਨਹੀਂ ਗਿਆ ਹੈ।',
    'workshop.notavailable': 'ਇਹ ਸੁਵਿਧਾ ਹਾਲੇ ਤੱਕ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
    'workshop.none': `ਤੁਹਾਡੇ ਕੋਲ ਕੋਈ ਵੀ {type, select,
      universe {ਯੂਨੀਵਰਸ}
      story {ਕਹਾਣੀ}
      fanfiction {ਫੈਨ ਫਿਕਸ਼ਨ}
      other {}
    }ਨਹੀਂ ਹੈ। ਇਕ ਬਣਾਓ!`,
    'workshop.collab': 'ਸਹਿਯੋਗਿਤਾ ਕੰਮ',
    'workshop.betareadings': 'ਬੀਟਾ ਪੜਾਈਆਂ',
    'workshop.translations': 'ਅਨੁਵਾਦ',
    'workshop.createnew': 'ਨਵਾਂ ਬਣਾਓ...',
    'workshop.story.standalone': 'ਸਟੈਂਡਅਲੋਨ ਕਹਾਣੀ',
    'workshop.story.standalone.desc': 'ਇਹ ਇੱਕ ਸਟੈਂਡਅਲੋਨ ਕਹਾਣੀ ਹੈ।',
    'workshop.controlpanel': '{name} ਕੰਟਰੋਲ ਪੈਨਲ',
    'workshop.universe.page': 'ਯੂਨੀਵਰਸ ਪੇਜ',
    'workshop.fictionaltime': 'ਕਾਲਪਨਿਕ ਸਮਾਂ',
    'workshop.dashboard.name': '{name} ਡੈਸ਼ਬੋਰਡ',
    'workshop.stories.in': 'ਕਹਾਣੀਆਂ ਵਿੱਚ {universe}',
    'workshop.universe.nostories': 'ਇਸ ਯੂਨੀਵਰਸ ਵਿੱਚ ਕੋਈ ਕਹਾਣੀਆਂ ਨਹੀਂ ਹਨ।',
    'workshop.story.chapter.add': 'ਨਵਾਂ ਅਧਿਆਯ',
    'workshop.universe.new': 'ਨਵੀਂ ਯੂਨੀਵਰਸ ਬਣਾਓ',
    'workshop.universe.publish': 'ਯੂਨੀਵਰਸ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ',
    'workshop.universe.publishing.notice': 'ਜੇ ਤੁਸੀਂ ਯੂਨੀਵਰਸ ਪ੍ਰਕਾਸ਼ਿਤ ਨਹੀਂ ਕਰਦੇ, ਤਾਂ ਜਦੋਂ ਪਹਿਲੀ ਕਹਾਣੀ ਯੂਨੀਵਰਸ ਨਾਲ ਜੁੜੀ ਜਾਂਦੀ ਹੈ ਤਾਂ ਆਟੋਮੈਟਿਕ ਤੌਰ \'ਤੇ ਪ੍ਰਕਾਸ਼ਿਤ ਕੀਤੀ ਜਾਵੇਗੀ।',
    'workshop.universe.settings': '{universe} ਯੂਨੀਵਰਸ ਸੈਟਿੰਗਾਂ',
    'workshop.universe.publishedOn': 'ਇਹ ਯੂਨੀਵਰਸ ਦਾ ਪ੍ਰਕਾਸ਼ਿਤ ਹੋਇਆ ਹੈ {date, date, long} {date, time, short}',
    'workshop.universe.description': 'ਯੂਨੀਵਰਸ ਵੇਰਵਾ',
    'workshop.settings.title': 'ਸਿਰਲੇਖ',
    'workshop.description': 'ਵੇਰਵਾ',
    'workshop.language.primary': 'ਪ੍ਰਾਇਮਰੀ ਭਾਸ਼ਾ',
    'workshop.publication.options': 'ਪ੍ਰਕਾਸ਼ਨ ਚੋਣਾਂ',
    'workshop.rating': 'ਸਧਾਰਨ ਰੇਟਿੰਗ',
    'workshop.universe.rating.desc': 'ਇਸ ਰੇਟਿੰਗ ਤੋਂ ਉਪਰ ਦੀਆਂ ਕਹਾਣੀਆਂ ਅਨਾਮੀ ਯੂਜ਼ਰਾਂ ਅਤੇ ਉਪਯੋਗਕਰਤਾਵਾਂ ਵੱਲੋਂ ਯੂਨੀਵਰਸ ਪੇਜ ਦੀ ਸੂਚੀਬੱਧੀ ਤੋਂ ਓਹਲੇ ਜਾਣਕਾਰੀ ਵਿੱਚੋਂ ਓਹਲੀਆਂ ਰਹੇਂਗੀਆਂ।',
    'workshop.universe.license': 'ਯੂਨੀਵਰਸ ਲਾਈਸੈਂਸ',
    'workshop.universe.genre.pick': 'ਯੂਨੀਵਰਸ ਲਈ ਜਾਨਰ ਚੁਣੋ',
    'workshop.story.genre.pick': 'ਕਹਾਣੀ ਲਈ ਜਾਨਰ ਚੁਣੋ',
    'workshop.cover': 'ਕਵਰ',
    'workshop.nothingtosee': 'ਇੱਥੇ ਕੁਝ ਵੇਖਣ ਲਈ ਨਹੀਂ ਹੈ...',
    'workshop.story.cannon': 'ਕੈਨਨ ਕਹਾਣੀ',
    'workshop.story.cannon.desc': 'ਇਹ ਕਹਾਣੀ {universe} ਯੂਨੀਵਰਸ ਵਿੱਚ ਕੈਨਨੀ ਹੈ।',
    'workshop.story.cannon.desc.create': 'ਇਹ ਕਹਾਣੀ ਇੱਕ ਕੈਨਨਨਿਕ ਕਹਾਣੀ ਵਜੋਂ ਬਣਾਈ ਜਾਵੇਗੀ {universe} ਯੂਨੀਵਰਸ ਵਿੱਚ।',
    'workshop.story.fanfiction.search': 'ਯੂਨੀਵਰਸ ਦਾ ਨਾਮ ਟਾਈਪ ਕਰੋ (ਇਹ ਤੁਹਾਡੀ ਲਾਇਬ੍ਰੇਰੀ ਵਿੱਚ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ)। ਫਿਰ ਸੁਝਾਅਵਾਂ ਤੋਂ ਚੁਣੋ।',
    'workshop.story.error.nogenres': 'ਤੁਹਾਨੂੰ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਜਾਨਰ ਚੁਣਨਾ ਚਾਹੀਦਾ ਹੈ।',
    'workshop.story.error.toomanygenres': 'ਇੱਕ ਕਹਾਣੀ ਵਿੱਚ ਸਿਰਫ ਦੋ ਜਾਨਰ ਦੀ ਇਜਾਜ਼ਤ ਹੈ।',
    'workshop.story.error.fanfiction.selectuniverse': 'ਅਪਣੇ ਫੈਨ ਫਿਕਸ਼ਨ ਲਈ ਤੁਹਾਨੂੰ ਮੂਲ ਯੂਨੀਵਰਸ ਚੁਣਨੀ ਚਾਹੀਦੀ ਹੈ!',
    'workshop.story.error.tags.toomany': 'ਹਰ ਕਹਾਣੀ ਵਿੱਚ ਸਿਰਫ 10 ਟੈਗ ਹੋ ਸਕਦੇ ਹਨ।',
    'workshop.story.new': 'ਇੱਕ ਨਵੀਂ ਕਹਾਣੀ ਬਣਾਓ',
    'workshop.story.publishing.notice': 'ਪਹਿਲੇ ਅਧਿਆਇ ਨੂੰ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰਨ ਤੇ ਕਹਾਣੀ ਆਟੋਮੈਟਿਕ ਤੌਰ \'ਤੇ ਪ੍ਰਕਾਸ਼ਿਤ ਕੀਤੀ ਜਾਵੇਗੀ।',
    'workshop.settings.edit': 'ਸੈਟਿੰਗਾਂ ਨੂੰ ਸੋਧੋ',
    'workshop.story.publishedOn': 'ਇਹ ਕਹਾਣੀ ਦਾ ਪ੍ਰਕਾਸ਼ਿਤ ਹੋਇਆ ਹੈ {date, date, long} {date, time, short}',
    'workshop.story.settings': 'ਕਹਾਣੀ ਸੈਟਿੰਗਾਂ',
    'workshop.settings.basic': 'ਮੁੱਖ ਸੈਟਿੰਗਾਂ',
    'workshop.settings.genres': 'ਜਾਨਰ (ਅਧਿਕਤਮ 2)',
    'workshop.story.license': 'ਕਹਾਣੀ ਲਾਇਸੈਂਸ',
    'workshop.story.settings.universe': 'ਯੂਨੀਵਰਸ ਸੈਟਿੰਗਾਂ',
    'workshop.settings.tags': 'ਟੈਗ',
    'workshop.revision': 'ਸਰਵਿਸ਼ਨ',
    'workshop.revisions.title': '{story}: {chapter} ਸਰਵਿਸ਼ਨ',
    'workshop.revisions.current': 'ਮੌਜੂਦਾ ਡਰਾਫਟ',
    'workshop.revisions.new.beta': 'ਡਰਾਫਟ ਤੋਂ ਨਵੀਂ ਸਰਵਿਸ਼ਨ ਬਣਾਓ।',
    'workshop.revisions.new.public': 'ਡਰਾਫਟ ਤੋਂ ਨਵੀਂ ਪਬਲਿਕ ਸਰਵਿਸ਼ਨ ਬਣਾਓ।',
    'workshop.revisions.toeditor': 'ਐਡੀਟਰ \'ਤੇ ਜਾਓ',
    'workshop.revisions.comments': 'ਸਰਵਿਸ਼ਨ ਟਿੱਪਣੀਆਂ',
    'workshop.revisions.comments.title': '{story}: {chapter} - ਸਰਵਿਸ਼ਨ {revision} - ਟਿੱਪਣੀਆਂ',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {for Beta readers}
      readers {Public}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'ਤੁਹਾਨੂੰ ਪਹਿਲਾਂ ਇੱਕ ਸਰਵਿਸ਼ਨ ਬਣਾਉਣਾ ਚਾਹੀਦਾ ਹੈ।',
    'workshop.revisions.comments.select': 'ਰਿਵੀਜ਼ਨ ਚੁਣੋ',
    'workshop.collaborators.noresults': 'ਕੋਈ ਨਤੀਜੇ ਨਹੀਂ',
    'workshop.collaborators.add.beta': 'ਬੀਟਾ ਪੜਨ ਵਾਲਾ ਸ਼ਾਮਲ ਕਰੋ',
    'workshop.collaborators.add.collaborator': 'ਸਹਿਯੋਗੀ ਸ਼ਾਮਲ ਕਰੋ',
    'workshop.collaborators.add.translator': 'ਅਨੁਵਾਦਕ ਸ਼ਾਮਲ ਕਰੋ',
    'workshop.collaborators.language.add': 'ਨਵਾਂ ਅਨੁਵਾਦ ਬਣਾਓ',
    'workshop.translations.stories': 'ਅਨੁਵਾਦ - ਕਹਾਣੀਆਂ',
    'workshop.translations.universes': 'ਅਨੁਵਾਦ - ਯੂਨੀਵਰਸ',
    'workshop.revisions.beta.none': 'ਇਸ ਸਮੇਂ ਕੋਈ ਰਿਵੀਜ਼ਨ ਨਹੀਂ ਹੈ।',
    'reader.asidetoggle': 'ਦੂਜੇ ਜਾਣਕਾਰੀ ਨੂੰ ਟਾਗਲ ਕਰੋ',
    'workshop.translation.original': 'ਮੂਲ:',
    'workshop.translation.original.title': 'ਮੂਲ ਸਿਰਲੇਖ:',
    'workshop.translation.original.description': 'ਮੂਲ ਵੇਰਵਾ:',
    'workshop.translation.original.cover': 'ਮੂਲ ਕਵਰ',
    'workshop.translation.original.tags': 'ਮੂਲ ਟੈਗ',
    'workshop.cover.alt': 'ਕਵਰ ਚਿੱਤਰ',
    'workshop.translation.updatedOrig': 'ਮੂਲ ਦੀ ਆਖਰੀ ਅਪਡੇਟ: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'ਅਨੁਵਾਦ ਦੀ ਆਖਰੀ ਅਪਡੇਟ: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'ਆਖਰੀ ਰਿਵੀਜ਼ਨ {revision, number}, ਮੂਲ ਦਾ: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'ਆਖਰੀ ਰਿਵੀਜ਼ਨ {revision, number}, ਅਨੁਵਾਦ ਦਾ: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `ਹੋਰ {type, select,
    collaborator {ਸਹਿਯੋਗੀਆਂ}
    beta {ਬੀਟਾ ਪੜ੍ਹਨ ਵਾਲੇਆਂ}
    translator {ਅਨੁਵਾਦਕਾਂ}
    other {}
  }ਸ਼ਾਮਲ ਕਰਨ ਲਈ, ਤੁਹਾਡੇ ਮੈਂਬਰਸ਼ਿਪ ਟੀਅਰ ਵਧਾਉਣ ਦੀ ਜ਼ਰੂਰਤ ਹੁੰਦੀ ਹੈ।`,
    'workshop.collaborators.requests.sent': 'ਭੇਜੇ ਗਏ ਬੇਨਤੀਆਂ',
    'workshop.collaborators.requests.invite': `ਤੁਹਾਨੂੰ ਆਮੰਤਰਿਤ ਕੀਤਾ ਗਿਆ ਹੈ ਕਿ ਤੁਸੀਂ {role, select,
    beta {ਬੀਟਾ ਪੜ੍ਹਨ ਵਾਲਾ}
    translator {ਅਨੁਵਾਦਕ}
    collaborator {ਸਹਿਯੋਗੀ}
    other {}
  } ਬਣਨ ਲਈ ਨੀਚੇ ਦਿੱਤੇ ਗਏ ਹਨ:`,
    'workshop.collaborators.requests.dashboard': `ਤੁਸੀਂ ਸਹਿਯੋਗ ਲਈ ਆਮੰਤਰਿਤ ਹੋਏ ਹੋ {count, plural,
    zero {ਕੋਈ ਕੰਮ ਨਹੀਂ ਹੈ}
    one {ਇੱਕ ਸਾਹਿਤਕ ਕੰਮ ਹੈ}
    other {# ਸਾਹਿਤਕ ਕੰਮਾਂ ਹਨ}
  }.`,
    'workshop.collaborators.language.added': 'ਭਾਸ਼ਾ ਜੋੜੀ ਗਈ ਹੈ',
    'workshop.story.noChaptersFound': 'ਕੋਈ ਅਧਿਆਇਨ ਨਹੀਂ ਮਿਲੀ.',
    'workshop.fanfic.needUniverseInLibrary': 'ਬਹੁਤ ਸਾਰੇ ਵਿਸ਼ਵ ਹਨ ਜਿਨ੍ਹਾਂ ਵਿੱਚ ਤੁਸੀਂ ਲਿਖਣਾ ਚਾਹੁੰਦੇ ਹੋ. ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਆਪਣੀ ਲਾਇਬ੍ਰੇਰੀ ਵਿੱਚ ਉਹਨਾਂ ਵਿਚ ਜੋੜੋ ਤਾਂ ਕਿ ਅਸੀਂ ਉਹਨਾਂ ਨੂੰ ਲੱਭ ਸਕੀਏ.',
    'workshop.fanfic.findUniverse': 'ਇੱਕ ਆਪਸ਼ਕਤਾਵਾਂ ਵਿਸ਼ਵ ਲੱਭੋ!',
    'workshop.encSettings': 'ਜਗਤ-ਕੋਸ਼ ਸੈਟਿੰਗਾਂ',
    'workshop.collaborators.removeUser': 'ਯੂਜ਼ਰ ਹਟਾਓ',
    'workshop.collaborators.cancelInvite': 'ਆਮੰਤਰਣ ਰੱਦ ਕਰੋ',
    'workshop.universe.createFirstStory': 'ਪਹਿਲਾਂ ਕਹਾਣੀ ਬਣਾਓ',
    'workshop.storylines': 'ਕਹਾਣੀਆਂ ਦੇਖੋ',
    'workshop.scenesManager': 'ਸੀਨਾ ਪ੍ਰਬੰਧਕ',
    'workshop.collaborators.addRoleForLang': 'ਜੋੜਨ ਲਈ {role} ਸ਼ਾਮਲ ਕਰੋ {language}',
    'workshop.beta.revisionInfo': 'ਇਹ ਰਿਵੀਜ਼ਨ {revision, number}ਹੈ, ਜੋ ਬਣਾਇਆ ਗਿਆ ਹੈ {createdAt, date, long}ਨੂੰ.',
    'workshop.story.notes.title': 'ਤੁਹਾਡੇ ਨੋਟਸ {storyTitle}ਲਈ',
    'workshop.story.notes.desc': 'ਕਹਾਣੀ ਦੇ ਵੇਰਵੇ ਨੋਟਸ।',
    'workshop.story.notes.tile': 'ਵੇਰਵੇ ਨੋਟਸ',
    'workshop.hideOrgs': 'ਸੰਗਠਨਾਂ ਤੋਂ ਸਮੱਗਰੀ ਛੁਪਾਓ',
    'workshop.translation.premium': 'ਅਨੁਵਾਦ ਸ਼ਾਮਲ ਕਰਨ ਲਈ, ਤੁਹਾਡੇ ਕੋਲ ਕਮ ਵੀ ਕਮਰਸ਼ਿਅਲ ਲਈ ਪ੍ਰਿਮੀਅਮ ਨਵੀਗੇਟਰ ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।',
    'workshop.story.finished': 'ਕਹਾਣੀ ਮੁਕੰਮਲ ਹੈ',
    'workshop.story.publishing.externalSellingNotice': 'ਕਿਉਂਕਿ ਤੁਸੀਂ ਸਾਹਿਤਕ ਵਿਸ਼ਵ ਤੋਂ ਬਾਹਰ ਵਿਕਰੀ ਕਰ ਰਹੇ ਹੋ ਇਸ ਲਈ ਤੁਸੀਂ ਕਹਾਣੀ ਹੁਣ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰ ਸਕਦੇ ਹੋ. ਤੁਹਾਡੇ ਦੁਕਾਨ ਦੀ ਲਿਸਟਿੰਗ ਕਹਾਣੀ ਤੇ ਜਾਂ ਇਸ ਕਹਾਣੀ ਦੇ ਅੰਤ ਵਿੱਚ ਦਿਖਾਈ ਦੇਵੇਗੀ.',
    'workshop.sharing.publicURL': 'ਜਨਤਕ ਵਰਜਨ',
    'workshop.fictionalTime.title': 'ਕਲਪਨਿਕ ਸਮਾਂ {universeName}ਲਈ',
    'workshop.fictionalTime.none': 'ਤੁਸੀਂ ਹੁਣ ਕੋਈ ਕਿਸੇ ਕਲਪਨਿਕ ਸਮਾਂ ਨੂੰ ਸੈੱਟ ਨਹੀਂ ਕੀਤਾ ਹੈ।',
    'workshop.fictionalTime.createNow': 'ਹੁਣ ਇੱਕ ਨਵਾਂ ਬਣਾਉਣ ਕਰੋ!',
    'workshop.fictionalTime.createTitle': 'ਇੱਕ ਨਵਾਂ ਕਲਪਨਿਕ ਸਮਾਂ ਬਣਾਓ',
    'workshop.fictionalTime.editTitle': 'ਸੋਧੋ {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently this tool is limited and is only capable of creating
        symmetric times. This means you won 't be able to recreate the Mayan calendar or the Gregorian. At this moment
        this tool expects that all the times are always the same, eg. months have always 30 days no exceptions and so
        on. We will address this in later versions, but till then this tool is more suited for creating primarily
        sci-fi based times.`,
    'workshop.fictionalTime.timeName': 'ਸਮਾਂ ਦਾ ਨਾਂ',
    'workshop.fictionalTime.basicInfo': 'ਮੁੱਖ ਜਾਣਕਾਰੀ',
    'workshop.fictionalTime.timeSetup': 'ਸਮਾਂ ਸੈੱਟਅੱਪ',
    'workshop.fictionalTime.linkedToET': 'ਕੀ ਇਹ ਸਮਾਂ ਇੱਕ ਧਰਤੀ ਦੀ ਮਿਤੀ \'ਤੇ ਸ਼ੁਰੂ ਹੁੰਦਾ ਹੈ (ਗਰੇਗੋਰੀਅਨ ਕੈਲੰਡਰ)?',
    'workshop.fictionalTime.timeDeclaration': 'ਸਮਾਂ ਦਾ ਐਲਾਨ',
    'workshop.fictionalTime.declarationLocation': 'ਸਮਾਂ ਦਾ ਨਾਂ ਕਿੱਥੇ ਐਲਾਨ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ?',
    'workshop.fictionalTime.declarationBefore': 'ਇਕਾਈਆਂ ਤੋਂ ਪਹਿਲਾਂ',
    'workshop.fictionalTime.declarationAfter': 'ਇਕਾਈਆਂ ਤੋਂ ਬਾਅਦ',
    'workshop.fictionalTime.declarationNone': 'ਕੋਈ ਨਹੀਂ',
    'workshop.fictionalTime.units': 'ਇਕਾਈਆਂ',
    'workshop.fictionalTime.ETStart': 'ਇਸ ਸਮਾਂ ਦੀ ਸ਼ੁਰੂਆਤੀ ਮਿਤੀ',
    'workshop.fictionalTime.unitsDescFirst': 'ਇਸ ਇਕਾਈ ਵਿੱਚ ਕਿੰਨੀ ਇਕਾਈਆਂ ਹਨ ਮਿਲੀਸਕਾਂਡਾਂ ਤੋਂ?',
    'workshop.fictionalTime.unitsDesc': 'ਇਸ ਇਕਾਈ ਵਿੱਚ ਕਿੰਨੀ ਇਕਾਈਆਂ ਹਨ ਪਿਛਲੀ ਇਕਾਈ ਤੋਂ?',
    'workshop.fictionalTime.unitsName': 'ਇਕਾਈ ਦਾ ਨਾਂ',
    'workshop.fictionalTime.unitsSeparator': 'ਪਿਛਲੀ ਇਕਾਈ ਤੋਂ ਵੱਲ ਅਲਗਾਵ',
    'workshop.fictionalTime.unitAdd': 'ਯੂਨਿਟ ਸ਼ਾਮਲ ਕਰੋ',
    'workshop.fictionalTime.clocks': 'ਘੜੀਆਂ',
    'workshop.fictionalTime.unitTransfer': 'ਯੂਨਿਟ ਟਰਾਂਸਫਰ ਕਰੋ',
    'fictionalTime.pageStartElapsedTime': 'ਇਸ ਪੇਜ ਨੂੰ ਖੋਲਣ ਤੋਂ ਬਾਅਦ ਸਮਾਂ ਬਿਤਿਆ',
    'fictionalTime.currentTime': 'ਮੌਜੂਦਾ ਸਮਾਂ',
    'workshop.shoppingExternal.options': 'ਬਾਹਰੀ ਖਰੀਦਦਾਰੀ ਚੋਣਾਂ',
    'workshop.shoppingExternal.explainer': 'ਜੇ ਤੁਹਾਡੀ ਕਹਾਣੀ ਕਿਸੇ ਹੋਰ ਥਾਂ ਵਿੱਚ ਵਿਕਿਆ ਜਾਂਦੀ ਹੈ, ਤਾਂ ਤੁਸੀਂ ਇੱਥੇ ਲਿੰਕ ਸੈੱਟ ਕਰ ਸਕਦੇ ਹੋ। ਲਿੰਕ ਫਿਰ ਕੰਟੈਂਟ ਦੀ ਜਗ੍ਹਾ ਵੇਖਾਉਣਗੇ ਜਾਂ ਤੁਸੀਂ ਚੁਣੇ ਗਏ ਕੰਟੈਂਟ ਦੇ ਅੰਤ ਵਿੱਚ ਵੇਖਾਉਣਗੇ।',
    'workshop.shoppingExternal.amazonStore': 'ਅਮੇਜ਼ਨ ਸਟੋਰ',
    'workshop.shoppingExternal.amazon': 'ਅਮੇਜ਼ਨ',
    'workshop.shoppingExternal.storeName': 'ਸਟੋਰ ਦਾ ਨਾਮ',
    'workshop.shoppingExternal.itemUrl': 'ਆਈਟਮ URL',
    'workshop.shoppingExternal.storesOther': 'ਹੋਰ ਦੁਕਾਨਾਂ',
    'fictionalTime.units.milliseconds': '{units, number} milliseconds',
    'fictionalTime.countdownToStart': 'ਸ਼ੁਰੂ ਹੋਣ ਦੇ ਲਈ ਖੁੰਜਾਂ ਵਾਲਾ ਟਾਈਮ',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 ਦਿਨ }
      other {{days} ਦਿਨ }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {ਸਕਿੰਟ}
      other {ਸਕਿੰਟ}
    }}
    minutes {{units, plural,
      one {ਮਿੰਟ}
      other {ਮਿੰਟ}
    }}
    hours {{units, plural,
      one {ਘੰਟਾ}
      other {ਘੰਟੇ}
    }}
    days {{units, plural,
      one {ਦਿਨ}
      other {ਦਿਨ}
    }}
    years {{units, plural,
      one {ਸਾਲ}
      other {ਸਾਲ}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'ਤੋਂ',
    'fictionalTime.inputSelectTimeUnit': 'ਸਮਾਂ ਯੂਨਿਟ ਚੁਣੋ',
    'fictionalTime.inputSelectETUnit': 'ਧਰਤੀ ਦਾ ਸਮਾਂ ਯੂਨਿਟ ਚੁਣੋ',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'ਸਾਇਡਬਾਰ ਟੂਲਬਾਕਸ',
    'workshop.writerSidebar.description': 'ਤੁਹਾਡੀ ਕਹਾਣੀ ਵਾਲੇ ਸਾਈਡਬਾਰ ਵਿੱਚ ਤੁਹਾਡੇ ਲਈ ਸਭ ਸਰੋਤਾਂ ਤੱਕ ਆਸਾਨੀ ਨਾਲ ਪਹੁੰਚ ਮਿਲਦੀ ਹੈ। ਆਪਣੀਆਂ ਨੋਟਾਂ, ਆਪਣੇ ਨਵੀਨਤਮ ਟਿੱਪਣੀਆਂ ਅਤੇ ਹੋਰ ਵੀ ਵੇਖਣ ਲਈ ਉੱਪਰ ਦਿੱਤੇ ਆਈਕਾਨਾਂ ਦੀ ਜਾਂਚ ਕਰੋ!',
    'workshop.story.authorsNotesExplained': 'ਤੁਹਾਡੇ ਨੋਟ, ਜੋ ਪੜ੍ਹਨ ਵਾਲੇ ਨੂੰ ਚੈਪਟਰ ਦੇ ਸ਼ੁਰੂ ਵਿੱਚ ਪੜਣ ਲਈ ਹਨ।',
    'workshop.story.chapterSortSwitch': 'ਚੈਪਟਰ ਦੇ ਕ੍ਰਮ ਨੂੰ ਬਦਲੋ',
    'workshop.universe.monetizationTitle': '{title} monetization',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} monetization',
    'workshop.universe.monetizationWebMonetization': 'ਵੈੱਬ ਮੁਦਰਣ',
    'workshop.webMonetization.explain': 'Web Monetization will stream payments to you based on how much time user spends on your content. In your profile monetization settings you can set your own payment pointer. Here you can decide on a split with your collaborators who have Web Payment enabled. Literary Universe automatically takes 10%.',
    'workshop.webMonetization.revShare': 'Due to the limitation of Web Monetization probabilistic revenue sharing is used. Probabilistic revenue sharing works by randomly choosing from a list of predefined payment pointers each time a web monetized visitor loads your page. The visitor pays to the chosen pointer until the page is reloaded or closed.',
    'workshop.webMonetization.revShareMore': 'Learn more about Probabilistic Revenue Sharing. We use the same code as on that page.',
    'workshop.story.notEligible.licence': `The story's license does not allow for monetization.`,
    'workshop.universe.notEligible.licence': `The universe's license does not allow for monetization.`,
    'workshop.story.notEligible.fanFiction': 'Fan Fiction stories are not eligible for monetization.',
    'workshop.revShare.mustBe100': 'Share must equal 100%',
    'workshop.revShare.LUCut': 'Literary Universe & payment gate',
    'workshop.revShare.unallocated': 'Unallocated share {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'Undecided',
    'workshop.revShare.origLangCreators': 'Original language creators',
    'workshop.story.prolog': 'Prolog',
    'workshop.story.chapter': 'Chapter {sequence, number}',
    'workshop.work.includesAds': 'ਕੀ ਕੋਈ ਵਿਗਿਆਪਨਾਂ ਜਾਂ ਉਤਪਾਦਾਂ ਕਾਮ ਵਿੱਚ ਸ਼ਾਮਲ ਹਨ?',
    'workshop.universe.forumSettings': 'ਅੰਦਰੂਨੀ ਬ੍ਰਹਮਾਂਡ ਫੋਰਮ ਸੈਟਿੰਗਾਂ',
    'workshop.universe.forum': 'ਅੰਦਰੂਨੀ {universeName} ਫੋਰਮ',
    'workshop.ratingAdjusted': 'ਦੁਆਰਾ ਸ਼ਿਕਾਇਤਾਂ ਦੀ ਬਦੋਲਤ, ਅਸੀਂ ਤੁਹਾਡੇ ਰੇਟਿੰਗ ਨੂੰ ਸੰਬੰਧਿਤ ਜਾਣਕਾਰੀ ਦੇ ਅਨੁਸਾਰ ਸੰਿਧਾਰਤਮਕ ਬਦਲਾ ਕਰਨਾ ਪਿਆ। ਇਸ ਤਰ੍ਹਾਂ, ਰੇਟਿੰਗ ਬਦਲਣਾ ਅਬ ਅਯੋਗ ਕੀਤਾ ਗਿਆ ਹੈ।',
    'workshop.selectCollaborator': 'ਸਹਿਯੋਗੀ ਚੁਣੋ',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Draft',
    'workshop.chapterStatus.scheduled': 'Scheduled',
    'workshop.chapterStatus.published': 'Published',
    'workshop.story.continuedIn': 'Which stories continue this story?',
    'workshop.story.continuedPlaceholder': 'Select story from this universe',
    'workshop.universe.isAIGenerated': 'Is the content of the universe generated by AI?',
    'workshop.universe.isAIGeneratedTooltip': 'Please let us know if any of the content in the universe was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.story.isAIGenerated': 'Is the story generated by AI?',
    'workshop.story.isAIGeneratedTooltip': 'Please let us know if any of the story was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.publicationAgreement.aria': 'Publication agreement for work',
    'workshop.publicationAgreement.intro': 'We are happy that you have chosen to publish your creative work with us. Before we proceed we just need you to look over our publication agreement, to understand what it means from the legal side of things.',
    'workshop.sortChapters': 'Sort order:',
    'workshop.sortChapters.ascending': 'From beginning',
    'workshop.sortChapters.descending': 'From latest',
    'workshop.sortChapters.aria': 'Select for which way to sort chapter listing',
    'workshop.hiatus.btn': 'Change story status to Hiatus',
    'workshop.cancelled.btn': 'Change story status to Cancelled',
    'workshop.complete.btn': 'Change story status to Completed',
    'workshop.statusChange.modalTop': 'Are you sure you want to change the status to',
    'workshop.statusName.hiatus': 'Hiatus',
    'workshop.statusName.cancelled': 'Cancelled',
    'workshop.statusName.completed': 'ਮੁਕੰਮਲ',
    'workshop.statusExplain.hiatus1': 'Hiatus means that you are stepping away from working on this story for a while for what ever reason. It will tell your readers that they should not expect any new updates in the coming weeks or even up to few months.',
    'workshop.statusExplain.hiatus2': 'The hiatus status will be automatically lifted if you publish any chapter. Or you can change it your self.',
    'workshop.statusExplain.hiatus3': 'If you keep your story in hiatus for six months, we will automatically mark this story as cancelled.',
    'workshop.statusExplain.cancelled1': 'We are sorry to hear that you can\'t continue working on the story. On the other hand we are happy that you are willing to let your readers know.',
    'workshop.statusExplain.cancelled2': 'Cancelling story will let your readers know that they should not expect any new updates.',
    'workshop.statusExplain.cancelled3': 'You can always revert this by publishing a chapter or changing the status.',
    'workshop.statusExplain.finished1': 'Congratulations! After all that hard work you have finally reached the end of an incredible journey. While the story might end now, we hope that there will be more stories to tell in the future, but for now, relax and enjoy the well earned rest.',
    'workshop.statusExplain.finished2': 'Marking story as complete will tell the readers that the story is finished. While you shouldn\'t be adding any new chapters we won\'t stop you and adding special chapters isn\'t a bad idea, to for example add more epilogues for all characters.',
    'workshop.statusExplain.finished3': 'While you can always cancel this status we highly advice against it. If the story is to continue it might be better to start a new story.',
    'workshop.status.goActive': 'Make the story active again',
    'workshop.statusChangeEmail.storyIntro': 'We would like to inform you that your story:',
    'workshop.statusChangeEmail.hiatusTitle': 'Your story status was automatically set to hiatus',
    'workshop.statusChangeEmail.hiatusIntro': 'ਨਿਸ਼ਕਰਮਤਾ ਦੇ ਕਾਰਨ ਤੁਹਾਡੇ ਕਹਾਣੀ ਦੀ ਸਥਿਤੀ ਆਟੋਮੈਟਿਕ ਤੌਰ \'ਤੇ ਹਾਇਏਟਸ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ।',
    'workshop.statusChangeEmail.hiatusWhy': 'ਕਿਉਂਕਿ ਇਸ ਕਹਾਣੀ ਵਿੱਚ ਕੋਈ ਨਵਾਂ ਅਧਿਆਇਆ ਨਹੀਂ ਪ੍ਰਕਾਸ਼ਿਤ ਹੋਇਆ ਹੈ ਇਸ ਲਈ ਇਹ ਆਟੋਮੈਟਿਕ ਤੌਰ \'ਤੇ ਹਾਇਏਟਸ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ ਜੋ ਕਿ 6 ਮਹੀਨੇ ਤੋਂ ਵੱਧ ਹੋ ਗਏ ਹਨ।',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'ਜੇ ਤੁਸੀਂ ਇਸ ਕਹਾਣੀ ਵਿੱਚ ਇਕ ਨਵਾਂ ਅਧਿਆਇਆ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰਦੇ ਹੋ ਤਾਂ ਇਹ ਸਥਿਤੀ ਆਟੋਮੈਟਿਕ ਤੌਰ \'ਤੇ ਹਟ ਜਾਵੇਗੀ। ਜੇ ਤੁਸੀਂ ਅਗਲੇ 6 ਮਹੀਨੇ ਵਿੱਚ ਇਸ ਕਹਾਣੀ ਵਿੱਚ ਕੋਈ ਨਵਾਂ ਅਧਿਆਇਆ ਪ੍ਰਕਾਸ਼ਿਤ ਨਹੀਂ ਕਰਦੇ ਤਾਂ ਅਸੀਂ ਕਹਾਣੀ ਨੂੰ ਆਟੋਮੈਟਿਕ ਤੌਰ \'ਤੇ ਰੱਦ ਕਰ ਦੇਵਾਂਗੇ।',
    'workshop.statusChangeEmail.cancellationIntro': 'ਤੁਹਾਡੀ ਕਹਾਣੀ ਦੀ ਸਥਿਤੀ ਆਟੋਮੈਟਿਕ ਤੌਰ \'ਤੇ ਰੱਦ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ।',
    'workshop.statusChangeEmail.cancellationWhy': 'ਇਸ ਦਾ ਕਾਰਨ ਇਹ ਹੋਇਆ ਹੈ ਕਿ ਤੁਸੀਂ ਕਹਾਣੀ ਨੂੰ ਹਾਇਏਟਸ ਕਰਨ ਦੇ 6 ਮਹੀਨੇ ਪਹਿਲਾਂ ਤੋਂ ਇਸ ਵਿੱਚ ਕੋਈ ਨਵਾਂ ਅਧਿਆਇਆ ਪ੍ਰਕਾਸ਼ਿਤ ਨਹੀਂ ਕੀਤਾ ਹੈ। ਇਸ ਲਈ ਇਸ ਨਿਸ਼ਕਰਮਤਾ ਦੇ ਸਾਲ ਦੇ ਬਾਅਦ ਅਸੀਂ ਆਟੋਮੈਟਿਕ ਤੌਰ \'ਤੇ ਕਹਾਣੀਆਂ ਰੱਦ ਕਰ ਦਿੱਤੀਆਂ ਹਨ ਜਿਸ ਨਾਲ ਪੜ੍ਹਨ ਵਾਲਿਆਂ ਨੂੰ ਪਤਾ ਲੱਗ ਸਕੇ ਕਿ ਕਿਹੜੀ ਕਹਾਣੀਆਂ ਚੱਲ ਰਹੀਆਂ ਹਨ।',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'ਜੇ ਤੁਸੀਂ ਇਸ ਕਹਾਣੀ ਉੱਤੇ ਕੰਮ ਨਹੀਂ ਕਰਨ ਦੀ ਸੋਚ ਰਹੇ ਹੋ ਤਾਂ ਤੁਹਾਨੂੰ ਕੁਝ ਵੀ ਕਰਨ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।',
    'workshop.startCreating': 'ਬਣਾਓ ਸ਼ੁਰੂ',
    'workshop.ownWork': 'ਆਪਣੀ ਮਿਹਨਤ',
    'workshop.list.thumbs': 'ਥੰਮਨੇਲ ਸੂਚੀ',
    'workshop.list.list': 'ਛੋਟੀ ਸੂਚੀ',
    'workshop.fanfiction.new': 'ਇੱਕ ਨਵੀਂ ਫੈਨ ਫਿਕਸ਼ਨ ਬਣਾਓ'
};