/**
 * @authors Jan Dvorak
 */
export default {
    siteName: 'Domhan Liteartha',
    twitterHandle: '@lituniapp',
    'site.description': 'Is iomaíocht cruthaitheach agus foilsithe i gceann amháin atá i Littearú Cruinne, an t-ábharthacht uile-i-one do chruinne scéalta mór.',
    'site.keywords': 'scríbhneoireacht chruthaitheach, eolaíocht ficsean, ficsean eolaíochta, fantaisíocht, scríbhneoireacht, foilsitheoireacht, scéal, scéalta, cruinne, úrscéal gréasáin, úrscéal gréasáin',
    'site.logoAlt': 'Logo Litreachais an Aontais Liteartha',
    'site.titleTemplate': '{title} | {siteName}',
    mobileMenu: 'Bileog gutháin',
    'common.signin': 'Logáil isteach',
    'common.signup': 'Cláraigh',
    'common.signout': 'Logáil amach',
    'common.dashboard': 'Painéal na nIonstraimí',
    'common.discovery': 'Aimsithe',
    'common.library': 'Leabharlann',
    'common.library.own': 'Do Leabharlann',
    'common.workshop': 'Ceardlann',
    'common.pm': 'Teachtaireachtaí',
    'common.settings': 'Socruithe',
    'common.options': 'Roghanna',
    'common.profile': 'Próifíl',
    'common.blog': 'Blag',
    'common.blogs': 'Blaganna',
    'common.about': 'Eolas fúinn',
    'common.accessdenied': 'Diúltaíodh do rochtain',
    'common.accessdenied.msg': 'Níor tugadh cead duit dul anseo. Má tá cead agat dul anseo, déan teagmháil leis an úinéir agus inis dó/di na socruithe a sheiceáil go cúramach.',
    'common.loading': 'Ag luchtú...',
    'common.add': 'Cuir leis',
    'common.save': 'Sábháil',
    'common.email': 'Ríomhphost',
    'common.soon': 'Ag teacht go luath...',
    'common.search': 'Cuardach',
    'common.search.do': 'Cuardaigh',
    'common.searching': 'Ag cuardach...',
    'common.report': 'Tuairisc',
    'common.user': 'Úsáideoir',
    'common.users': 'Úsáideoirí',
    'common.showmore': 'Taispeáin níos mó',
    'common.futurefeature.title': 'Gné amach romhainn',
    'common.futurefeature.text': 'We apologize, but this feature is not available at this time. We are working hard to make it available as soon as possible.',
    'common.nothingfound': 'Rud ar bith nach bhfuil aimsithe',
    'common.explore': 'Fiosrú',
    'common.by': 'ag {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'Clár scriosta',
    'common.scratchpad.own': 'Do chlár scriosta',
    'common.news': 'Nuacht',
    'common.encyclopedia': 'Eagnaíocht',
    'common.art': 'Ealaín',
    'common.story': 'Scéal',
    'common.stories': 'Scéalta',
    'common.universe': 'Aontas',
    'common.universes': 'Aontachtaí',
    'common.collaborator': 'Comhoibrí',
    'common.collaborators': 'Comhoibrithe',
    'common.translator': 'Aistritheoir',
    'common.translators': 'Aistritheoirí',
    'common.betareader': 'Léitheoir béite',
    'common.betareaders': 'Léitheoirí béite',
    'common.post': 'Poist',
    'common.statistics': 'Staitisticí',
    'common.lang.select': 'Roghnaigh teanga',
    'common.submit': 'Cuir isteach',
    'common.close': 'Dún',
    'common.comment': 'Nóta',
    'common.comments': 'Nótaí',
    404: 'Leathanach gan aimsiú',
    'search.users': 'Cuardaigh úsáideoirí',
    'search.user': 'Cuardaigh úsáideoir',
    'common.help': 'Cabhraigh',
    'common.or': 'nó',
    'common.account.create': 'Cruthaigh cuntas',
    'signup.username': 'Ainm úsáideora',
    'signup.email': 'Do ríomhphost',
    'signup.password.label': 'Do phasfhocal',
    'signup.password.repeat': 'Athdhéan do phasfhocal',
    'common.password': 'Pasfhocal',
    'signin.password.forgot': 'Ar mhaith leat do phasfhocal a chailleadh?',
    'dashboard.whatsnew': 'Cad atá nua',
    'dashboard.blog': 'Do bhlag',
    'common.footer.tagline': 'Scríbhneoireacht agus léitheoireacht i bpobail uilíoch éasca.',
    'common.footer.plans': 'Pleananna agus Praghsáil',
    'common.legal.tos': 'Téarmaí Seirbhíse',
    'common.legal.community': 'Treoracha Pobail',
    'common.legal.privacy': 'Polasaí Príobháideachais',
    'common.legal.copyright': 'Comhaontú Cearta Cóipcheartaithe',
    'common.legal.cookies': 'About cookies',
    'cookies.desc': 'This website uses cookies to ensure you get the best experience on our website.',
    'common.legal.versionDisplay': `{type, select,
    tos {Terms of Service}
    community {Community Guidelines}
    privacy {Privacy Policy}
    copyright {Copyright Agreement}
    publishingAgreement {Publishing Agreement}
    cookies {About Cookies}
    other {Agreement}
  } Version {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'Tiocfaidh leagan nua ({newVersion}) den doiciméad seo i bhfeidhm ar {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} Gach ceart ar cosaint, tá gach téacs in úinéireacht a scríbhneoirí féin.',
    'premium.only.title': 'Rang ballraíocht níos ísle nádúrtha',
    'premium.only.msg': 'Táimid ag gabháil le leithscéal, níl do rang ballraíocht go leor chun rochtain a bheith agat ar an ggné seo.',
    'premium.only.join': 'Cuirimid roghanna éagsúla pleananna ar fáil do gach duine leis an tairbhe is mó a bhaint as An Domhan Liteartha.',
    'premium.only.link': 'Seiceáil é!',
    'universe.visit': 'Cuairt ar leathanach an tsaoil',
    'common.fanmanager': 'Bainisteoir lucht leanúna',
    'common.fanarts': 'Ealaín lucht leanúna',
    'common.fanfiction': 'Gearrscéal lucht leanúna',
    'common.fansettings': 'Socruithe lucht leanúna',
    'story.chapter': 'Caibidil',
    'story.chapters': 'Caibidlí',
    'story.genre': 'Géar',
    'story.genres': 'Géaranna',
    'story.read': 'Léigh',
    'story.lastUpdate': 'Deireadh suas ar {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Críochnaithe ar {date, date, medium}.',
    'story.hiatusAt': 'On hiatus from {date, date, medium}.',
    'story.cancelledAt': 'Cancelled on {date, date, medium}.',
    'story.comments.for': 'Nótaí maidir le {story} {chapter}.',
    'story.cover.alt': 'Íomhá clúdaigh an scéil do {story}.',
    'story.note.fanfiction': 'NÓTA: Is ficsean lucht leanúna é an scéal seo ar uileann {universe} .',
    copyrights: 'Cearta cúlra',
    'common.challenges': 'Dúshláin',
    // for beta only
    'beta.notice': 'Welcome to the Literary Universe BETA! We are excited to let you know that we are officially launching this Friday! We hope that you will join us and support us as we start a new chapter in our journey.',
    'beta.thanks': 'Thank you for your support!',
    'scratchpad.about': 'Do nótaí agus smaointe ar fáil i ngach áit ar an suíomh.',
    'common.feedback': 'Aiseolas',
    'common.createdOn': 'Cruthaithe ar {date, date, long}',
    'common.createdOn.title': 'Cruthaithe ar',
    // account types
    admin: 'Riarthóir',
    'common.saved': 'Sábháilte!',
    'common.saving': 'Ag sábháil...',
    'common.friends': 'Cairde',
    'lang.orig': 'Teanga bhunaidh',
    'lang.orig.plus': 'Teanga bhunaidh - {language}',
    buy: 'Ceannaigh',
    confirm: 'Deimhnigh',
    cancel: 'Cealaigh',
    processing: 'Ag próiseáil...',
    'common.noData': 'Gan sonraí',
    'error.title': 'Tá earráid tarlaithe. Gabhaimid leithscéal as an bhfadhb.',
    'error.oops': 'Oops! Something went seriously wrong!',
    'error.apologies': 'We apologize for the inconvenience, we will do our best to fix this soon.',
    'error.400.text': 'Error 400: {errorMessage}',
    'common.offlineStatus': 'Tá tú faoi bhriseadh córais.',
    male: 'Fireann',
    female: 'Baineann',
    'common.legal.effectiveAt': 'Feidhmeach ó {date, date, medium}',
    select: 'Roghnaigh le do thoil',
    'common.statusFailed': 'Theip ar an nasc leis an bhfreastalaí.',
    'common.statusConnecting': 'Ag iarraidh nasc a dhéanamh leis an bhfreastalaí... ({count, number})',
    'slug.checking': 'Ag dul i gcomhairle...',
    'slug.failed': 'Tá an seoladh seo ann cheana féin.',
    'slug.success': 'Tá an seoladh seo ar fáil!',
    'notVerified.msg': `Níl do chuntas {option, select,
    email {ríomhphost}
    wallet {brósaíocht}
    other {ríomhphost}
    } faighte.`,
    'notVerified.verify': `Deimhnigh do {option, select,
    email {ríomhphost}
    wallet {brósaíocht}
    other {ríomhphost}
    }le do thoil.`,
    unknown: 'anaithnid',
    'common.legal.guidelines': 'Treoracha Pobail',
    'errorLoading.title': 'Earráid le lódáil an leathanaigh',
    'errorLoading.explained': 'An error has occurred while the page was loading. We apologize for the inconvenience. Please try accessing the page again. If the problem persists, please let us know.',
    'errorLoading.retry': 'Ath-trial!',
    'errorLoading.takingLong': 'Tá sé seo ag tógáil i bhfad...',
    'common.title': 'Teideal',
    'common.timelines': 'Líne ama',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'Rialachán Ginearálta maidir le Cosaint Sonraí',
    'editor.placeholder.link': 'Cuir isteach URL...',
    'editor.placeholder.connection': 'Cuardaigh le haghaidh iontráil sa leabharlann...',
    'editor.saved.beta': 'Cruthúnas nua cruthaithe do léitheoirí Beite!',
    'editor.saved.public': 'Leagan nua foilsithe!',
    goodbyeForever: 'We are sorry to see you go. Was it something we did? Please let us know if that is the case. Either way, we wish you the best in your future endeavors and hopefully we\'ll meet again! Live long and prosper!',
    'goodbyeForever.feedback': 'Inis dúinn cad is féidir linn a dhéanamh níos fearr',
    'common.edit': 'Cuir in Eagar',
    'common.publish': 'Foilsigh',
    'common.publishAt': 'Dáta agus am foilsithe',
    'common.publishNow': 'Publish now',
    'common.publishLater': 'Publish later',
    'a11y.user.menu': 'Menu úsáideora',
    'a11y.navigation': 'Seoladh',
    'dashboard.profile': 'Do phróifíl',
    'profile.website': 'Mo láithreán gréasáin pearsanta',
    'story.notes.concept': 'Fíric',
    'story.notes.settings': 'Socruithe an scéil',
    'story.notes.theme': 'Téama',
    'story.notes.impact': 'Tionchar dírithe',
    'story.notes.outcome': 'Toradh',
    'story.notes.audience': 'Lucht féachana dírithe',
    'story.notes.pitch': 'Pitch',
    'story.notes.notes': 'Nótaí',
    'story.authorsNotes': 'Nótaí an Údair',
    'story.notes.audienceAgeGroup': 'Target audience age group',
    'story.notes.audienceSex': 'Target audience sex',
    'common.members': 'Baill',
    'common.language': 'Teanga',
    next: 'Ar Aghaidh',
    previous: 'Roimhe seo',
    'common.legal.tos.short': 'Téarmaí',
    'common.legal.privacy.short': 'Príobháideachas',
    'premium.increaseLimit': 'Cíortar suas chun cur le do theorainn.',
    'common.sharing': 'Ag roinnt',
    'story.isbn': 'ISBN',
    'common.name': 'Ainm',
    'common.remove': 'Bain',
    'common.time.milliseconds': 'Míltean',
    'common.time.seconds': 'Soicind',
    'common.time.minutes': 'Nóiméid',
    'common.time.hours': 'Uaireanta',
    'common.time.days': 'Lá',
    'common.time.weeks': 'Seachtainí',
    'common.time.months': 'Míonna',
    'common.time.years': 'Blianta',
    'common.monetization': 'Mónaithe',
    'common.tab.monetizationOptions': 'Roghanna Mónaithe',
    'common.pagination': 'Leathanaigh',
    'common.forum': 'Fóram',
    'common.2faCode': 'Cód 2FA',
    'common.2faCodeIntro': 'Cuir isteach do chód uair amháin a ghiniúnaíodh ag do chlár fíorchineálaithe.',
    'common.2faCodeAria': 'Foirm iontrála cód 2FA',
    'common.aiContent.model.label': 'AI Model',
    'common.aiContent.model.tooltip': 'Select the AI model that was used to generate content',
    'common.other': 'Other',
    'common.aiContent.model.custom.label': 'Custom AI Model',
    'common.aiContent.model.custom.placeholder': 'Enter the name of the AI model',
    'common.select': 'Select...',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Teanga réamhshocraithe',
    'signin.web3.signMessage': 'Deimhnigh le do thoil go bhfuil tú ag iarraidh dul isteach i Léann Liteartha le do bhreisféar mar mhodh dheimhnithe. Cód: {code}',
    'common.web3.confirmationCode': 'Cód deimhniúcháin: {code}',
    'common.roadmap': 'Bótharmap',
    'common.luStatsIFrameOptOut': 'Eisdiúchán staitisticí an tDomhain Liteartha',
    'common.image': 'Íomhá',
    'common.home': 'Baile',
    'common.administration': 'Riarachán',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'Grúpaí',
    'common.upload': 'Uaslódáil',
    'common.backToDashboard': 'Ar ais chuig an mbord',
    'common.accept': 'Glac',
    'common.reject': 'Diúltaigh',
    'common.events': 'Teagaisc',
    'common.event': 'Imeacht',
    'common.all': 'Gach',
    'common.social': 'Sóisialta',
    'common.discordCommunity': 'Pobal Discord',
    'common.account': 'Cuntas',
    'common.notifications': 'Fógraí',
    'common.byDeclaration': 'Le:',
    'common.done': 'Déanta',
    recommended: 'Molta',
    'select.typeToCreate': 'Tosaigh téacsú chun mír a chruthú',
    'select.noSearchResults': 'Gan torthaí do “{search}”',
    'select.removeOption': 'Bain {option}',
    create: 'Cruthaigh',
    'banner.support': 'Literary Universe is made possible thanks to the support of users like you. To help us remain independent and improve the platform, please consider subscribing to one of our plans.',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Nach bhfuil cuntas agat?',
    'common.haveAccountQuestion': 'An bhfuil cuntas agat cheana féin?',
    'common.socialLogin': 'Logáil isteach le seirbhísí eile',
    'common.viewMore': 'Féach níos mó',
    'common.overview': 'Ábhar mionsonraithe',
    'common.loggingOut': 'Logáil amach',
    'common.thankYou': 'Go raibh maith agat!',
    'common.seeYouAgain': 'Feicfidh mé arís thú!',
    'email.hello': 'Dia duit {username},',
    'common.back': 'Ar ais',
    'console.stop': 'Stop!',
    'console.explain': 'Is gné brabhsála é seo atá dírithe ar fhorbróirí. Má dúirt duine ar bith leat rud éigin a chóipeáil agus a pháistí anseo chun gné Léitheoireachta Cruinne a chumasú nó chun cuntas duine ar bith a "hackáil", is scam é sin agus tabharfaidh sé rochtain dóibh ar do chuntas Léitheoireachta Cruinne.',
    'common.coping': 'Ag cóipeáil...',
    'common.actions': 'Gníomhaíochtaí',
    'common.popular': 'Réimséach',
    'common.newest': 'Is Déanaí',
    'common.oldest': 'Seana',
    'common.noSelection': 'No selection',
    'common.content': 'Content',
    'common.theWayOfTheAuthor': 'The Way of the Author',
    'common.password.hide': 'Hide Password',
    'common.password.show': 'Show Password',
    'common.forums': 'Forums',
    'common.restriction.goodConduct': 'Due to good conduct violation we have restricted your use of this feature.',
    'common.continue': 'Continue',
    'common.authorName': 'Author Name',
    'error.invalidFileType': 'Please select a valid image file (JPEG, PNG, GIF, WebP)',
    'error.fileTooLarge': 'Image must be less than {mbSize, number}MB',
    'error.fabricInitFailed': 'Failed to initialize the image editor',
    // File upload strings
    'upload.files': 'Uploaded Files',
    'upload.dropHere': 'Drop your files here...',
    'upload.dragOrClick': 'Drag and drop files here, or click to select files',
    'upload.maxSize': 'Maximum file size: {size}',
    'upload.error.failed': 'File upload failed. Please try again.',
    'upload.error.tooManyFiles': 'You can upload a maximum of {max} files.',
    'upload.error.removeFile': 'Failed to remove file. Please try again.',
    'actions.delete': 'Delete',
    'common.aiContent.indicator': 'AI-Generated Content',
    'common.aiContent.tooltip': 'This content was created with AI assistance',
    'common.aiContent.model': 'AI Model: {model}',
    'common.aiContent.custom': 'Custom AI model',
    'common.viewAll': 'View All',
    'notice.thankYou': 'Thank you for your support!',
    'common.dropImageHere': 'Drop an image here',
    'common.legal.publishingAgreement': 'Publishing Agreement',
    'upload.dragAndDrop': 'Drag and drop files here, or click to select files',
    'common.orgs': 'Organizations',
    'universe.cover.alt': 'Universe cover image for {story}.',
    'common.license': 'License'
};