export default {
  'courses.courses': 'Cúrsaí',
  'courses.overview': 'Ábhar na gcaitheamh',
  'courses.public.title': 'Explore Courses',
  'courses.public.heading': 'Explore Courses',
  'courses.public.filters': 'Filter Courses',
  'courses.public.noResults': 'No courses found',
  'courses.public.tryDifferentFilters': 'Try different search terms or filters',
  'courses.filter.search': 'Search courses...',
  'courses.filter.allTypes': 'All Types',
  'courses.filter.clearAll': 'Clear All',
  'courses.filter.type': 'Type',
  'courses.type.course': 'Course',
  'courses.type.workshop': 'Ceardlann',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Course',
  'courses.type.workshop.lowercase': 'Ceardlann',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'Cruthaigh cúrsa nua',
  'course.reading.title': 'Teideal an tionscadail léitheoireachta',
  'course.question.add': 'Cuir ceist leis',
  'course.lessons.newMessage': 'Cruthaigh agus eagraigh do cheachtanna le haghaidh teagaisc éifeachtaigh.',
  'course.reading.new': 'Leabhar Leithe',
  'course.reading.newMessage': 'Cruthaigh agus eagraigh tascanna léitheoireachta do do chuid daltaí',
  'course.writing.new': 'Acht Scríbhneoireachta',
  'course.writing.newMessage': 'Cúraimí scríbhneoireachta a shocrú agus a dháileadh go tapa',
  'course.question.text': 'Céard atá i do cheist anseo',
  'course.question.type': 'Roghnaigh cineál ceiste, le do thoil.',
  'course.question.delete': 'Bain an cheist',
  'course.type': 'Course Type',
  'course.visibility': 'Roghnaigh rogha feidhmchlár',
  'course.title': 'Teideal',
  'course.description': 'Cur síos',
  'course.cover': 'Clúdach',
  'course.start': 'Tosaíonn do chúrsa ag',
  'course.ends': 'Críochnaíonn do chúrsa ag',
  'course.curriculum': 'Course Curriculum',
  'course.members': 'Mic léinn agus múinteoirí',
  'course.assignments': 'Sannacháin',
  'course.question.deleteWhole': 'Scrios ceist iomlán',
  'course.question.yes': 'Tá',
  'course.question.no': 'Níl',
  'course.lesson.title': 'Teideal an cheachta',
  'course.lesson.add.universe': 'Cuir Scéal/An Saolré a chur leis',
  'course.lesson.externalLinks': 'External links',
  'course.lesson.add.link': 'Cuir nasc seachtrach leis',
  'course.status': 'Stádas',
  'course.active': 'Gníomhaíocht',
  'course.active.message': 'Gníomhach',
  'course.inactive': 'Neamhghníomhach',
  'course.upload.resource': 'Upload a resource',
  'course.question.answer': 'Cuir freagra leis',
  'course.question.open': 'Ceist oscailte',
  'course.question.close': 'Ceist dúnta',
  'course.question.multiple': 'Ceist ilroghnach',
  'course.about': 'Maidir leis an gcúrsa seo',
  'course.lesson.new': 'Cruthaigh ceacht nua',
  'course.lesson.type': 'Cineál ceachta',
  'course.lesson.inPerson': 'Go pearsanta',
  'course.lesson.preRecorded': 'Réamhthaifeadta',
  'course.lesson.online': 'Ar líne',
  'course.lesson.text': 'Téacs amháin',
  'course.lesson.content': 'Ábhar an cheachta',
  'course.lesson.description': 'Cur síos poiblí',
  'course.add.story': 'Cuir scéal leis',
  'course.remove.story': 'Bain scéal',
  'course.dateOfPublish': 'Dáta an fhoilsithe',
  'course.lesson.meetInPerson': 'Buail go pearsanta',
  'course.curriculum.edit': 'Cuir an curaclam in eagar',
  'course.stories.own': 'Do scéalta féin',
  'course.stories.organization': 'Scéalta eagraíochta',
  'course.stories.public': 'Scéalta poiblí',
  'course.publish.at': 'Ba mhaith liom an cúrsa seo a fhoilsiú ag:',
  'course.edit.curriculum': 'Cuir an curaclam in eagar',
  'course.assignment': 'Leithreasc',
  'course.lesson.removeLink': 'Bain an nasc',
  'course.user.remove': 'Remove user',
  'course.user.invite': 'Invite user',
  'course.user.invited': 'Invited',
  'course.edit.role': 'Cuir ról in eagar',
  'course.assignment.description': 'Cur síos ar an tasc',
  'course.internal': 'Inmheánach',
  'course.free': 'Saor in aisce',
  'course.sale': 'Díolachán',
  'course.announcements': 'Announcements',
  'course.announcements.full': 'Course announcements',
  'course.announcements.create': 'Create an announcement',
  'course.join': 'Join Course',
  'course.joining': 'Joining...',
  'course.join.success': 'You have successfully joined this course!',
  'course.join.error.payment': 'This course requires payment to join.',
  'course.join.error.invite': 'This course requires an invitation to join.',
  'course.join.error.generic': 'There was an error joining the course. Please try again.',
  'course.firstLesson': 'First Lesson',
  'course.upcomingLessons': 'Upcoming Lessons',
  'course.detail.title': '{courseName} | Course',
  'lessons.visibility.public': 'Public',
  'lessons.visibility.private': 'Private',
  'course.curriculum.empty': 'No curriculum items available yet.',
  'course.preview.message': 'This is a preview of the course. Join the course to access all content.',
  'course.details': 'Course Details',
  'course.tab.curriculum': 'Curriculum',
  'course.tab.details': 'Course Details',
  'course.duration': 'Duration',
  'course.perpetual': 'Perpetual',
  'course.language': 'Language',
  'course.price': 'Price',
  'course.learningObjectives': 'Learning Objectives',
  'course.prerequisites': 'Prerequisites',
  'course.tags': 'Tags',
  'course.stats.members': 'Members',
  'course.stats.lessons': 'Lessons',
  'course.assignments.comingSoon': 'Assignments view is coming soon.',
  'course.progress.comingSoon': 'Progress tracking is coming soon.',
  'course.type.free': 'Saor in aisce',
  'course.type.paid': 'Paid',
  'course.type.forSale': 'For Sale',
  'course.type.invite': 'Invite Only',
  'courses.invites.tile': 'You are invited to partake in {count, plural, one {course} other {courses}}.',
  'courses.invites.noInvites': "You don't have any course invitations at the moment.",
  'courses.invites.invitedBy': 'Invited by: ',
  'courses.invites.accept': 'Accept',
  'courses.invites.reject': 'Reject',
  'course.join.heading': 'Join This Course',
  'course.oneTimePayment': 'One-time payment for full access',
  'course.member': "You're Enrolled",
  'course.member.access': 'You have full access to all course materials.',
  'courses.members.editRole': 'Edit Role',
  'courses.members.editRoleFor': 'Edit role for:',
  'courses.add.member': 'Add a new member',
  'course.member.options': 'Course member list',
  'course.navigation.curriculum': 'Curriculum',
  'course.navigation.members': 'Students & Teachers',
  'course.navigation.assignments': 'Sannacháin',
  'course.navigation.forums': 'Fóraim',
  'course.navigation.attendance': 'Attendance',
  'course.members.teachers': 'Teachers',
  'course.members.students': 'Students',
  'course.members.preview.message': 'Join this course to see all students and interact with the community.',
  'course.member.role.owner': 'Úinéir',
  'course.member.role.teacher': 'Múinteoir',
  'course.member.role.student': 'Mac léinn',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'course.startDate': 'Start Date',
  'course.endDate': 'End Date',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Curriculum Preview',
  'course.curriculum.preview.message': 'Join this course to access all {count} lessons and assignments.',
  'course.curriculum.locked': 'Locked',
  'course.curriculum.lesson': 'Lesson',
  'course.curriculum.assignment': 'Leithreasc',
  'course.curriculum.reading': 'Reading',
  'course.lesson.backToCurriculum': 'Back to Curriculum',
  'course.lesson.nextLesson': 'Next Lesson',
  'course.lesson.documents': 'Documents & Resources',
  'course.lesson.meetingLink': 'Meeting Link',
  'course.lesson.location': 'Location',
  'course.lesson.virtualClassroom': 'Virtual Classroom',
  'course.lesson.joinClassroom': 'Join the virtual classroom session',
  'course.lesson.enterClassroom': 'Enter Classroom',
  'course.assignment.acceptsStories': 'Glacann le scéalta',
  'course.assignment.acceptsUniverses': 'Glacann le héilíní',
  'course.assignment.backToAssignments': 'Ar ais chuig na tascanna',
  'course.assignment.criteria': 'Critéir léitheoireachta',
  'course.assignment.dueDate': 'Le: {date}',
  'course.assignment.freeReading': 'Léamh saor in aisce cumasaithe',
  'course.assignment.grade': 'Gráid',
  'course.assignment.grade.received': 'Gráid: {grade}',
  'course.assignment.gradeSaveError': 'Ní féidir an grád a shábháil',
  'course.assignment.gradeSaved': 'Gráid sábháilte.',
  'course.assignment.gradedCount': '{count, plural, one {# grádaithe} other {# grádaithe}}',
  'course.assignment.grading.help':
    'Déan athbhreithniú ar aighneachtaí na mac léinn, oscail scéalta nó cruinní nasctha, agus cuir grád roghnach agus aiseolas leis.',
  'course.assignment.grading.title': 'Grádú: {title}',
  'course.assignment.grading.unavailable': 'Níl grádú ar fáil',
  'course.assignment.grading.unavailableMessage':
    'Níl rochtain agat ar an leathanach grádaithe seo, nó níor éirigh an tasc a aimsiú.',
  'course.assignment.lastRead': 'An léamh deireanach {date}',
  'course.assignment.minutes': '{count} nós',
  'course.assignment.noSubmissions': 'Níl aon aighneachtaí ann go fóill.',
  'course.assignment.noWrittenResponse': 'Níor soláthraíodh aon fhreagra scríofa.',
  'course.assignment.notFound': 'Níor aimsíodh an tasc',
  'course.assignment.notFoundMessage': 'Níorbh fhéidir an tasc a iarradh a aimsiú.',
  'course.assignment.noteForTeacher': 'Cuir nóta le do mhúinteoir',
  'course.assignment.open': 'Tasc oscailte',
  'course.assignment.openGrading': 'Leathanach grádaithe oscailte',
  'course.assignment.questions': 'Ceisteanna',
  'course.assignment.readingProgress': 'Dul chun cinn léitheoireachta an dalta',
  'course.assignment.readings': 'Léamha sannta',
  'course.assignment.responsePlaceholder': 'Scríobh do fhreagra anseo',
  'course.assignment.responsePrompt': 'Ábhar aitribe nó spreagadh dialainne',
  'course.assignment.selectStoriesRead': 'Roghnaigh na scéalta a roghnaigh tú don tasc seo.',
  'course.assignment.sharedProject.studentHelp':
    'Oscail ceann de na tionscadail chomhroinnte thuas i Workshop agus cuir leis an obair ann. Ní theastaíonn foirm ghabhála ar leith don tasc seo.',
  'course.assignment.sharedProject.studentTitle': 'Conas an tasc seo a chríochnú',
  'course.assignment.sharedProject.teacherNotice':
    'Úsáideann an tasc tionscadail chomhroinnte seo rochtain comhoibrithe in ionad aighneachtaí aonair.',
  'course.assignment.sharedProjects': 'Oibreacha tionscadail chomhroinnte',
  'course.assignment.storiesCompleted': 'scéalta críochnaithe',
  'course.assignment.submissionCount': '{count, plural, one {# aighneacht} other {# aighneachtaí}}',
  'course.assignment.submissionSaved': 'Taisceadh an t-aighneacht.',
  'course.assignment.submissions': 'Aighneachtaí agus grádú',
  'course.assignment.submit': 'Cuir an tasc isteach',
  'course.assignment.submitError': 'Ní féidir an tasc a chur isteach.',
  'course.assignment.submitWork': 'Roghnaigh obair le cur isteach',
  'course.assignment.submitWork.help': 'Roghnaigh an scéal nó an chruinne atá le grádú don tasc seo.',
  'course.assignment.submitWork.label': 'Saothar curtha isteach',
  'course.assignment.submitWork.placeholder': 'Roghnaigh scéal nó chruinne',
  'course.assignment.submittedAt': 'Curtha isteach ar {date}',
  'course.assignment.submittedWork.story': 'Scéal curtha isteach: {title}',
  'course.assignment.submittedWork.universe': 'Uil-chruinne faoi bhráid: {title}',
  'course.assignment.supportingFiles': 'Uaslódáilte ábhair thacaíochta',
  'course.assignment.supportingMaterials': 'Ábhair thacaíochta',
  'course.assignment.updateSubmission': 'Nuashonraigh an t-aighneacht',
  'course.assignment.yourSubmission': 'Do chur isteach',
  'courses.role.owner': 'Úinéir',
  'courses.role.teacher': 'Múinteoir',
  'courses.role.student': 'Mac léinn',
};
