export default {
  "encyclopedia.add": "Cuir iontráil nua",
  "encyclopedia.browse": "Searc trí an leabharlann",
  "encyclopedia.search": "Cuardaigh san leabharlann",
  "canvas.toolbar.add": "Add:",
  "canvas.toolbar.text": "Text",
  "canvas.toolbar.link": "Link",
  "canvas.toolbar.group": "Group",
  "canvas.toolbar.entry": "Entry",
  "canvas.encPicker.title": "Pick an encyclopedia entry",
  "canvas.encPicker.search": "Search entries…",
  "canvas.dialog.pickEntry": "Pick encyclopedia entry",
  "canvas.node.link": "Link",
  "canvas.node.encEntry": "Entry",
  "canvas.entry.open": "Double-click to open entry",
  "encyclopedia.back.universe": "Ar ais chuig leathanach an aonach",
  "encyclopedia.back.workshop": "Ar ais chuig an saotharlann",
  "encyclopedia.categories": "Catagóirí",
  "encyclopedia.groups": "Grúpaí",
  "encyclopedia.category.character": "Carachtair",
  "encyclopedia.category.event": "Teagaisc",
  "encyclopedia.category.group": "Grúpaí",
  "encyclopedia.category.item": "Rudaí",
  "encyclopedia.category.location": "Láithreacha",
  "encyclopedia.category.other": "Eile",
  "encyclopedia.category.state": "Stáit",
  "encyclopedia.category.governments": "Rialacháin",
  "encyclopedia.category.languages": "Teangacha",
  "encyclopedia.category.creatures": "Créatúirí",
  "encyclopedia.category.deity": "Déithe",
  "encyclopedia.category.religions": "Creidimh",
  "encyclopedia.category.flora": "Fiadhúlra",
  "encyclopedia.category.magic": "Draíocht",
  "encyclopedia.category.planets": "Pláinéid",
  "encyclopedia.category.species": "Speicis",
  "encyclopedia.category.technologies": "Teicneolaíochtaí",
  "encyclopedia.category.families": "Families",
  "encyclopedia.category.jobs": "Jobs",
  "encyclopedia.category.lore": "Lore",
  "encyclopedia.category.vehicles": "Vehicles",
  "encyclopedia.category.diseases": "Diseases",
  "encyclopedia.category.traditions": "Traditions",
  "encyclopedia.category.sports": "Sports",
  "encyclopedia.category.food": "Food",
  "encyclopedia.category.landmarks": "Landmarks",
  "encyclopedia.category.buildings": "Buildings",
  "encyclopedia.category.schools": "Schools",
  "encyclopedia.category.continents": "Continents",
  "encyclopedia.category.villages": "Villages",
  "encyclopedia.category.towns": "Towns",
  "encyclopedia.category.cities": "Cities",
  "encyclopedia.category.settlements": "Settlements",
  "encyclopedia.category.countries": "Countries",
  "encyclopedia.search.found": "{results, plural,\n    =0 {Gan iontrálacha gaolmhara}\n    one {Iontráil gaolmhara amháin}\n    other {# iontrálacha gaolmhara}\n  } faighte.",
  "encyclopedia.help.text": "Úsáid an roghchlár ar chlé chun siúlóid a dhéanamh idir na míreanna san eolaire. Nuair a roghnaíonn tú mír, taispeánfar í in ionad an téacs seo.",
  "encyclopedia.help.sidebar": "Bosca Uirlisí ar an Taobhchlár",
  "encyclopedia.help.sidebar.text": "Welcome to your story! This sidebar allows you easy access to all resources related to your story. Check the icons above to see the latest comments, your notes, search your encyclopedia, browse and add new entries to your encyclopedia. If you want to add a connection to an entry from the story text, select the text where you want to place it and then click the connect button. You will then be prompted to find and select an item.",
  "encyclopedia.intro": "Fáilte go dtí an eolaire {universe} .",
  "encyclopedia.add.title": "Cuir iontráil nua leis an eolaire",
  "encyclopedia.add.heading": "Cad ba mhaith leat a chur leis?",
  "encyclopedia.add.moresoon": "Tuilleadh catagóirí ag teacht go luath!",
  "encyclopedia.create": "Create new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {villages}\n    towns {towns}\n    cities {cities}\n    settlements {settlement}\n    countries {country}\n  }",
  "encyclopedia.create.header": "Creating a new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {village}\n    towns {town}\n    cities {city}\n    settlements {settlement}\n    countries {country}\n  } in {universe}",
  "encyclopedia.entry.category": "Entry category: {category, select,\n    character {Character}\n    event {Event}\n    group {Group}\n    item {Item}\n    location {Location}\n    other {Note}\n    state {State}\n    governments {Government}\n    languages {Language}\n    creatures {Creature}\n    deity {Deity}\n    religions {Religion}\n    flora {Flora}\n    magic {Magic}\n    planets {Planet}\n    species {Specie}\n    technologies {Technology}\n    families {Family}\n    jobs {Job}\n    lore {Lore}\n    vehicles {Vehicle}\n    diseases {Disease}\n    traditions {Tradition}\n    food {Food}\n    sports {Sport}\n    landmarks {Landmark}\n    buildings {Building}\n    schools {School}\n    continents {Continent}\n    villages {Village}\n    towns {Town}\n    cities {City}\n    settlements {Settlement}\n    countries {Country}\n  }",
  "encyclopedia.entry.category.legend": "Catagóir",
  "encyclopedia.fields.add": "Cuir réimse nua leis",
  "encyclopedia.fields.text": "Sainmhíniú",
  "encyclopedia.fields.textarea": "Téacs",
  "encyclopedia.fields.connection": "Nasc",
  "encyclopedia.fields.time": "Am",
  "encyclopedia.fields.image": "Íomhá",
  "encyclopedia.fields.canvas": "Canvas",
  "encyclopedia.visibility": "Feidhmíocht",
  "encyclopedia.public": "Poiblí",
  "encyclopedia.private": "Príobháideach",
  "encyclopedia.container": "Sórtáil",
  "encyclopedia.container.desc": "Make this entry a container for a new group of entries. This will hide it from the categories listing.",
  "encyclopedia.entry.name": "Ainm an iontráil",
  "encyclopedia.summary": "Achoimre",
  "encyclopedia.summary.desc": "This is a summary that will be the only initial information displayed to the reader.",
  "encyclopedia.parent": "Iontráil thuismitheoir",
  "encyclopedia.related": "Iontrálacha gaolmhara",
  "encyclopedia.errors.tags": "Ní féidir leat ach 10 lipéad a bheith ag gach iontráil.",
  "encyclopedia.field.private": "Réimse príobháideach",
  "encyclopedia.ft.indev": "Tá an rogha seo faoi bhunú.",
  "encyclopedia.connections.remove": "Bain an nasc",
  "encyclopedia.connections.extra": "Eolas breise",
  "encyclopedia.connections.existing": "Iontráil atá ann cheana",
  "encyclopedia.connections.existing.abbr": "EE",
  "encyclopedia.cover": "Íomhá chlúdaithe",
  "encyclopedia.translation.title": "Fáilte go dtí {universe} aistriú domhan!",
  "encyclopedia.translation.desc": "Úsáidtear an comhoiriúnacht seo an t-athrú i gcomhair {language}. Roghnaigh iontrálacha atá ann cheana féin sa liosta ar an taobh clé chun tús a chur leis an aistriú.",
  "encyclopedia.welcome.totalEntries": "There {totalEntries, plural, \n    zero {are no entries}\n    one {is one entry}\n    other {are # entries}\n  } in this universe.",
  "encyclopedia.settings.title": "Socruithe na hEagnaíochta",
  "encyclopedia.settings.categoriesDesc": "Cas ar agus as catagóirí a mhaith leat a úsáid i d'eagnaíocht.",
  "encyclopedia.settings.introText": "Teachtaireacht fáilte a thaispeáint tar éis cur síos an domhain.",
  "encyclopedia.fields.placeholder": "Ainm an réimse",
  "encyclopedia.fields.delete": "Scrios réimse",
  "encyclopedia.timeOption.fictionalDate": "Dáta ficsin",
  "encyclopedia.timeOption.fictionalTime": "Am ficsin",
  "encyclopedia.timeOption.fictionalDateTime": "Dáta am ficsin",
  "encyclopedia.timeOption.date": "Dáta",
  "encyclopedia.timeOption.time": "Am",
  "encyclopedia.timeOption.dateTime": "Dáta agus am",
  "encyclopedia.settings.groupByCategories": "Cuir catagóirí san áireamh i liosta grúpa",
  "encyclopedia.menuOpen": "Oscail an roghchlár Eagnaíochta",
  "encyclopedia.menuClose": "Dún an roghchlár Eagnaíochta",
  "encyclopedia.menuAria": "Roghchlár Eagnaíochta",
  "enc.newField": "Réimse nua",
  "enc.entries.limit": "Tá {value, number} agat faoi láthair amháin as {max, plural,\n    =0 {iontráil neamhtheoranta}\n    other {{max, number}}\n  } .",
  "enc.entries.limitReached": "Tá tú tar éis teacht ar an líon is mó iontrálacha leabhair na heagna a cheadaítear le do síntiús reatha.",
  "encyclopedia.pronunciation.title": "Caint",
  "encyclopedia.wip.abbreviation": "Faoi Mhíniú",
  "encyclopedia.wip.full": "Obair i gCur Chun Cinn",
  "encyclopedia.settings.templateLegend": "An Saolra Teimpléad",
  "encyclopedia.settings.templateDescription": "Ceadaigh go gcuirfear cóip den ábhar sa saolra seo isteach i saolta eile. Is fearr é seo má tá tú gan aon scéalta agus má tá tú ag cruthú teimpléad amháin le haghaidh daoine eile a úsáid.",
  "encyclopedia.settings.templateCheckbox": "Seo saolra teimpléad é",
  "encyclopedia.templateCopy.modalTitle": "Cóipeáil ábhar an einciclopaidéara",
  "encyclopedia.templateCopy.description": "Cóipeáil ábhar an einciclopaidéara seo isteach i do shaolra chun é a shaibhriú.",
  "encyclopedia.templateCopy.targetUniverse": "Saolra le cóipeáil chuig",
  "encyclopedia.templateCopy.finished": "Críochnaithe cóipeáil",
  "encyclopedia.templateCreateUniverse.modalTitle": "Create universe from template",
  "encyclopedia.templateCreateUniverse.description": "Create a new universe with pre-seeded encyclopedia content from this template. Your universe will remain private until you decide to make it public.",
  "encyclopedia.templateCreateUniverse.success": "Universe created successfully! Redirecting...",
  "encyclopedia.pronunciation.audio.play": "Play pronunciation",
  "encyclopedia.pronunciation.guide": "Use <ipaLink>IPA notation</ipaLink> when possible. Web Speech API pronunciation is best-effort; see <webSpeechLink>MDN docs</webSpeechLink>.",
  "encyclopedia.templateField.born": "Born",
  "encyclopedia.templateField.died": "Died",
  "encyclopedia.templateField.race": "Race",
  "encyclopedia.templateField.gender": "Gnéas",
  "encyclopedia.templateField.partners": "Partners",
  "encyclopedia.templateField.parents": "Parents",
  "encyclopedia.templateField.children": "Leanaí",
  "encyclopedia.templateField.associated-with": "Associated with",
  "encyclopedia.templateField.biography": "Beathaisnéis",
  "encyclopedia.templateField.physical-appearance": "Physical appearance",
  "encyclopedia.templateField.type-of-event": "Type of event",
  "encyclopedia.templateField.preceding-events": "Preceding events",
  "encyclopedia.templateField.following-events": "Following events",
  "encyclopedia.templateField.leadup": "Leadup",
  "encyclopedia.templateField.description": "Cur síos",
  "encyclopedia.templateField.aftermath": "Aftermath",
  "encyclopedia.templateField.members": "Baill",
  "encyclopedia.templateField.locations": "Láithreacha",
  "encyclopedia.templateField.events": "Teagaisc",
  "encyclopedia.templateField.vision": "Vision",
  "encyclopedia.templateField.mission": "Mission",
  "encyclopedia.templateField.description-of-the-organization": "Description of the organization",
  "encyclopedia.templateField.history": "Stair",
  "encyclopedia.templateField.owners": "Owners",
  "encyclopedia.templateField.function": "Function",
  "encyclopedia.templateField.content": "Ábhar",
  "encyclopedia.templateField.population": "Population",
  "encyclopedia.templateField.culture": "Culture",
  "encyclopedia.templateField.governments": "Rialacháin",
  "encyclopedia.templateField.religions-believes": "Religions & believes",
  "encyclopedia.templateField.languages": "Teangacha",
  "encyclopedia.templateField.geography": "Geography",
  "encyclopedia.templateField.founding": "Founding",
  "encyclopedia.templateField.notable-events": "Notable events",
  "encyclopedia.templateField.notes": "Nótaí",
  "encyclopedia.templateField.type-of-government": "Type of government",
  "encyclopedia.templateField.structure": "Structure",
  "encyclopedia.templateField.power-structure": "Power structure",
  "encyclopedia.templateField.source-of-power": "Source of power",
  "encyclopedia.templateField.laws": "Laws",
  "encyclopedia.templateField.ideology": "Ideology",
  "encyclopedia.templateField.internal-politics": "Internal politics",
  "encyclopedia.templateField.external-politics": "External politics",
  "encyclopedia.templateField.leading-figures": "Leading figures",
  "encyclopedia.templateField.groups": "Grúpaí",
  "encyclopedia.templateField.military": "Military",
  "encyclopedia.templateField.items": "Rudaí",
  "encyclopedia.templateField.typology": "Typology",
  "encyclopedia.templateField.dialectics": "Dialectics",
  "encyclopedia.templateField.phonology": "Phonology",
  "encyclopedia.templateField.grammar": "Grammar",
  "encyclopedia.templateField.numbers": "Numbers",
  "encyclopedia.templateField.quantifiers": "Quantifiers",
  "encyclopedia.templateField.private-notes": "Private notes",
  "encyclopedia.templateField.type": "Type",
  "encyclopedia.templateField.notable-features": "Notable features",
  "encyclopedia.templateField.traits": "Traits",
  "encyclopedia.templateField.habitat": "Habitat",
  "encyclopedia.templateField.food-sources": "Food sources",
  "encyclopedia.templateField.reproduction": "Reproduction",
  "encyclopedia.templateField.cultural-significance": "Cultural significance",
  "encyclopedia.templateField.related-creatures": "Related creatures",
  "encyclopedia.templateField.religion": "Religion",
  "encyclopedia.templateField.other-names": "Other names",
  "encyclopedia.templateField.appearance": "Appearance",
  "encyclopedia.templateField.related-to": "Related to",
  "encyclopedia.templateField.symbolism": "Symbolism",
  "encyclopedia.templateField.rituals": "Rituals",
  "encyclopedia.templateField.origin": "Origin",
  "encyclopedia.templateField.notable-figures": "Notable figures",
  "encyclopedia.templateField.deities": "Déithe",
  "encyclopedia.templateField.artifacts": "Artifacts",
  "encyclopedia.templateField.believes": "Believes",
  "encyclopedia.templateField.traditions": "Traditions",
  "encyclopedia.templateField.spread": "Spread",
  "encyclopedia.templateField.classification": "Classification",
  "encyclopedia.templateField.features": "Gnéithe",
  "encyclopedia.templateField.produce": "Produce",
  "encyclopedia.templateField.ecosystem": "Ecosystem",
  "encyclopedia.templateField.effect": "Effect",
  "encyclopedia.templateField.alignment": "Alignment",
  "encyclopedia.templateField.requirements": "Requirements",
  "encyclopedia.templateField.size": "Size",
  "encyclopedia.templateField.length-of-day": "Length of day",
  "encyclopedia.templateField.length-of-night": "Length of night",
  "encyclopedia.templateField.length-of-cycle": "Length of cycle",
  "encyclopedia.templateField.moons": "Moons",
  "encyclopedia.templateField.nearby-stellar-bodies": "Nearby stellar bodies",
  "encyclopedia.templateField.climate": "Climate",
  "encyclopedia.templateField.weather": "Weather",
  "encyclopedia.templateField.natural-resources": "Natural resources",
  "encyclopedia.templateField.notable-locations": "Notable locations",
  "encyclopedia.templateField.inhabitans": "Inhabitans",
  "encyclopedia.templateField.looks": "Looks",
  "encyclopedia.templateField.production": "Production",
  "encyclopedia.templateField.use": "Use",
  "encyclopedia.templateField.related": "Related",
  "encyclopedia.templateField.location": "Location",
  "encyclopedia.templateField.significance": "Significance",
  "encyclopedia.templateField.associated-events": "Associated events",
  "encyclopedia.templateField.associated-figures": "Associated figures",
  "encyclopedia.templateField.access-restrictions": "Access restrictions",
  "encyclopedia.templateField.cultural-importance": "Cultural importance",
  "encyclopedia.templateField.founded": "Founded",
  "encyclopedia.templateField.government": "Government",
  "encyclopedia.templateField.defenses": "Defenses",
  "encyclopedia.templateField.connected-settlements": "Connected settlements",
  "encyclopedia.templateField.family-motto": "Family Motto",
  "encyclopedia.templateField.founding-date": "Founding Date",
  "encyclopedia.templateField.ethos": "Ethos",
  "encyclopedia.templateField.family-reputation": "Family Reputation",
  "encyclopedia.templateField.family-branches": "Family Branches",
  "encyclopedia.templateField.notable-vassals-retainers": "Notable vassals/retainers",
  "encyclopedia.templateField.skills-required": "Skills required",
  "encyclopedia.templateField.pay-salary": "Pay/Salary",
  "encyclopedia.templateField.associated-locations": "Associated locations",
  "encyclopedia.templateField.associated-characters": "Associated characters",
  "encyclopedia.templateField.propulsion": "Propulsion",
  "encyclopedia.templateField.capacity": "Capacity",
  "encyclopedia.templateField.speed": "Speed",
  "encyclopedia.templateField.manufacturers": "Manufacturers",
  "encyclopedia.templateField.symptoms": "Symptoms",
  "encyclopedia.templateField.causes": "Causes",
  "encyclopedia.templateField.treatment": "Treatment",
  "encyclopedia.templateField.affected-species": "Affected species",
  "encyclopedia.templateField.associated-groups": "Associated groups",
  "encyclopedia.templateField.ingredients": "Ingredients",
  "encyclopedia.templateField.preparation": "Preparation",
  "encyclopedia.templateField.rules": "Rules",
  "encyclopedia.templateField.equipment": "Equipment",
  "encyclopedia.templateField.venues": "Venues",
  "encyclopedia.templateField.architecture": "Architecture",
  "encyclopedia.templateField.curriculum": "Curriculum",
  "encyclopedia.templateField.notable-alumni": "Notable alumni",
  "encyclopedia.templateField.affiliation": "Affiliation",
  "encyclopedia.templateField.language": "Teanga",
}
