export default {
    'feedback.home': 'Ionad cúnamh',
    'feedback.bugs': 'Gnáthanna',
    'feedback.bugs.desc': 'Ar aimsigh tú earráid nó rud éigin eile atá mícheart nó as áit? Fág a fhios againn anseo!',
    'feedback.features': 'Sméidimh agus Moltaí',
    'feedback.features.desc': 'An bhfuil smaointe agat ar ghnéithe nua nó ar conas an suíomh a dhéanamh níos fearr? Fág a fhios dúinn!',
    'feedback.help': 'Cúnamh agus Teagasc',
    'feedback.help.desc': 'Conas a dhéanann tú _____? Téigh anseo chun na freagraí a fháil.',
    'feedback.desc': 'Fáilte chuig ár ionad cúnamh agus réiteach!',
    'feedback.faq': 'Ceisteanna Coitianta',
    'feedback.faq.desc': 'Ceisteanna a gheofar go minic',
    'feedback.open': 'Oscailte',
    'feedback.closed': 'Dúnta',
    'feedback.accepted': 'Glactha',
    'feedback.inprogress': 'Ar siúl',
    'feedback.completed': 'Críochnaithe',
    'feedback.fixed': 'Socraithe',
    'feedback.new.bugs': 'Tuairisc nua a thabhairt isteach',
    'feedback.new.features': 'Moltaí gné nua a dhéanamh',
    'feedback.lang.nosupport': 'Ní thacaítear le do theanga reatha don aiseolas, scríobh i mBéarla le do thoil. Go raibh maith agat!',
    'feedback.new.thanks': 'Go raibh maith agat as an fhógra! Féachfaimid air go gairid.',
    'feedback.comment.title': 'Nóta',
    'feedback.comment.desc': 'Cuir do chuid aiseolais chugainn',
    'feedback.comment.legend': 'Do chuid aiseolais - lig dúinn a fháil amach faoi rud ar bith',
    'feedback.comment.success': 'Go raibh maith agat as do chuid aiseolais!',
    'feedback.comment.label': 'Do chomhfhreagras',
    'feedback.copyrightReport.title': 'Coireachta cóipcheart',
    'feedback.copyrightReport.desc': 'Tuairisc a dhéanamh ar Choireachta cóipcheart',
    'feedback.report.noUser': 'Ní mór duit bheith logáilte isteach chun tuairisc a chur isteach.',
    'feedback.voting.totalVoters': 'Vótálaithe: {voted, number}',
    'feedback.voting.upvote': 'Uasmhéid',
    'feedback.voting.downvote': 'Ísleasmhéid',
    'feedback.voting.score': 'Scór Iomlán',
    'feedback.report.title': 'Tuairisc ar ábhar',
    'feedback.report.typeSelect': 'Cén fhadhb atá anseo?',
    'feedback.reportType.law': 'Breithniú dlíthiúil',
    'feedback.reportType.vulgar': 'Míshuaimneach/drochfhocal',
    'feedback.reportType.copyright': 'Breithniú ar chearta cúirte',
    'feedback.reportType.storyRating': 'Aiseolas mícheart aoisghrádú',
    'feedback.reportType.scam': 'Míol mór',
    'feedback.report.submit': 'Tuairisc',
    'feedback.report.submitting': 'Agóid...',
    'feedback.report.violationDesc': 'Sonraí',
    'feedback.report.reportSaved': 'Go raibh maith agat as an tuairisc! Scrúdóimid é agus ghlacfaidh muid gníomh más gá.',
    'feedback.report.copyrightReportSaved': 'Go raibh maith agat as an tuairisc! Scrúdóimid é agus beimid i dteagmháil.',
    'feedback.report.copyrightOwnershipDesc': 'Ráiteas úinéireachta',
    'feedback.report.copyrightNotice': 'Tabhair faoi deara go gcaithfidh tú bheith in úinéir ceart an saothair chun an fhoirm seo a úsáid. Mura bhfuil tú an úinéir, abair leis an úinéir nó úsáid an chatagóra eile chun a fhógairt dúinn. Glacaimid le coimhlintí cóipcheart cheartúil agus úsáid míúsáideach agus míchuí den fhoirm seo chomh maith.',
    'feedback.report.copyrightInternalProperty': 'Tá an saothar seo foilsithe agam ar Domhan Liteartha',
    'feedback.reportType.spam': 'Spam nó iascachta phisfheithiclí',
    'feedback.reportType.other': 'Eile',
    'feedback.report.copyrightType.propertySelectLabel': `Cén {type, select,
    universe {domhan}
    story {scéal}
    other {scéal}
  } atá á gcruthú?`,
    'faq.section.about': 'Eolas fúinn',
    'faq.section.settings': 'Socruithe',
    'faq.section.discovery': 'Aimsir ghníomhach',
    'faq.section.reader': 'Léitheoir',
    'faq.section.library': 'Leabharlann',
    'faq.section.workshop': 'Ceardlann',
    'faq.section.writer': 'Scríbhneoir',
    'faq.section.encyclopedia': 'Eagarthóireacht',
    'faq.section.groups': 'Grúpaí',
    'faq.section.blogs': 'Blagaí',
    // About us questions
    'faq.question.about.dataLocation': 'Cá bhfuil sonraí LU stóraithe?',
    'faq.answer.about.dataLocation': 'Tá sonraí Literary Universe stóraithe ar fhreastalaithe sna Stáit Aontaithe Mheiriceá, go háirithe sa réigiún AWS us-east-1.',
    'faq.question.about.incorporation': 'Cá bhfuil tú cláraithe?',
    'faq.answer.about.incorporation': 'Tá Literary Universe cláraithe i bPoblacht na Seice. Is féidir tuilleadh sonraí a fháil ar an leathanach faoi <a href="/about">faoi</a>.',
    'faq.question.about.roadmap': 'Cad iad na céimeanna eile do Literary Universe?',
    'faq.answer.about.roadmap': 'This is constantly evolving. Check out our <a href="/roadmap">roadmap</a> for more details.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Conas is féidir liom cuma Literary Universe a athrú?',
    'faq.answer.settings.changeTheme': 'Registered users can change their theme in the <a href="/user/settings/account">account settings</a> under "site theming" section. We have a light and a dark theme available. If you are not registered, then we try to determine which theme to serve you based on your browser and operating system settings.',
    'faq.question.settings.changeAvatar': 'Conas is féidir liom mo avatar a athrú?',
    'faq.answer.settings.changeAvatar': 'You can change your avatar in the <a href="/user/settings/profile">profile settings</a>.',
    'faq.question.settings.changeLanguage': 'Conas is féidir liom an teanga a athrú?',
    'faq.answer.settings.changeLanguage': 'You can change the language of Literary Universe in the <a href="/user/settings/account">account settings</a>.',
    'faq.question.settings.translationMistake': 'Fuair mé botún sa téacs ar an suíomh gréasáin, cá bhfuil méadúchán a thuairiscint air?',
    'faq.answer.settings.translationMistake': 'All our language files are available on GitHub. You can <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">submit an issue there</a> or in the Bug section of the feedback, or if you are so inclined, you can fix it directly yourself via <a href="https://crowdin.com/project/literary-universe" target="_blank">our Crowdin page</a>.'
};