export default {
    'reader.storyEnd.heading': 'An Críoch',
    'reader.storyEnd.description': 'Tá tú tar éis teacht ar chríoch an scéil.',
    'reader.externalSale.heading': 'Níl sé anseo go fóill',
    'reader.externalSale.description': 'Níl an scéal seo ar fáil ar Literary Universe ach is féidir leat é a fháil in áiteanna eile.',
    'reader.storyTBC.heading': 'Leanfaidh sé',
    'reader.storyTBC.description': 'Sin ár gceann ghortaígí go fóill don scéal, ach leanfaidh an eachtra ar aghaidh sa todhchaí, tic ar ais go luath!',
    'chapter.translation.notYetDescription': 'Tic ar ais arís go luath!',
    'reader.externalShopping.heading': 'Ceannaigh {storyName} i siopaí:',
    'chapter.next': 'An chéad chaibidil eile',
    'chapter.previous': 'Sraithcheimicí roimhe seo',
    'chapter.comment': 'Tráchtais ar an gcaibidil seo',
    'reader.language': 'Teanga:',
    'reader.fullscreen.enter': 'Bheith iomlánscáileáin',
    'reader.fullscreen.exit': 'Scoir iomlánscáileáin',
    'reader.details.universe': 'Sonraí an domhain',
    'reader.details.story': 'Sonraí an scéil',
    'reader.darkmode': 'Athraigh modh dorcha',
    'reader.flowtext': 'Athraigh méid téacs',
    'reader.menu.optionsAria': 'Choice Roghanna an léitheora',
    'reader.accessibility': 'Athraigh cur i gcéill',
    'chapter.translation.notYet': 'Níl an chaibidil seo aistrithe go fóill.',
    'externalShopping.buyLink.amazon': 'Ceannaigh ar Amazon',
    'externalShopping.buyLink.other': 'Ceannaigh ar {storeName}',
    'externalShopping.buyLink.bookshop': 'Ceannaigh ar Bookshop.org',
    'reader.accessibility.aria': 'Ghnéithe rochtana',
    'reader.accessibility.toggleDyslexic': 'Athraigh cló dyslexic',
    'reader.accessibility.toggleParagraphStripes': 'Cealla cúlra réamhsheolta creachta a athraigh',
    'reader.accessibility.toggleParagraphHighlight': 'Sonraí an chuid is roghnaithe a dhéanamh in airde',
    'reader.accessibility.toggleRules': 'Athraigh príomhgeallaire',
    'reader.nextRelease.scheduled': 'Tiocfaidh an chéad chaibidil as an {nextReleaseAt, date} ag {nextReleaseAt, time}!',
    'reader.storyContinues': 'Leanann an scéal...',
    'reader.storyOnHiatus': 'Tá an t-údar ag gabháil sos ón scéal seo faoi láthair agus tá an scéal ar fionraí. Seiceáil ar ais i mí nó dhó.',
    'reader.storyCancelled': 'Is é seo an deireadh. Tá an scéal curtha ar ceal agus is dócha nach mbeidh aon rud nua ann.',
    'reader.storyCancelled.heading': 'Cealaigh',
    'reader.nextChapterEstimation.verySoon': 'Bunaithe ar dátaí foilseachán na {chaptersCount, number} cinn deiridh, táthar ag súil go mbeidh an chéad chaibidil ar fáil go luath.',
    'reader.nextChapterEstimation.days': 'Bunaithe ar dátaí foilseachán na {chaptersCount, number} cinn deiridh, táthar ag súil go mbeidh an chéad chaibidil ar fáil i gcomhair {daysLeft, plural, one {1 lá} other {# lá}}.',
    'reader.nextChapterEstimation.notEnoughChapters': 'Tabharfaimid meastachán freisin ar an am a d\'fhéadfadh an chéad chaibidil a bheith foilsithe nuair a bheidh níos mó ná cúpla chaibidil sa scéal seo.'
};