export default {
    'workshop.title': 'Do do chuid oibre',
    'workshop.noneassigned': 'Níor ceapadh aon cheann ort fós.',
    'workshop.notavailable': 'Níl an gné seo ar fáil go fóill.',
    'workshop.none': `You currently have no {type, select,
      universe {universe}
      story {story}
      fanfiction {fan fiction}
      other {}
    }. Create one now!`,
    'workshop.collab': 'Obair comhoiriúnach',
    'workshop.betareadings': 'Léitheoireachtaí beata',
    'workshop.translations': 'Aistriúcháin',
    'workshop.createnew': 'Cruthaigh nua...',
    'workshop.story.standalone': 'Scéal neamhspleách',
    'workshop.story.standalone.desc': 'Is é seo scéal neamhspleách.',
    'workshop.controlpanel': '{name} painéal rialaithe',
    'workshop.universe.page': 'Leathanach domhain',
    'workshop.fictionaltime': 'Am ficsin',
    'workshop.dashboard.name': '{name} comhla',
    'workshop.stories.in': 'Scéalta in {universe}',
    'workshop.universe.nostories': 'Níl aon scéalta sa domhan seo.',
    'workshop.story.chapter.add': 'Caibidil nua',
    'workshop.universe.new': 'Cruthaigh domhan nua',
    'workshop.universe.publish': 'Foilsigh an domhan',
    'workshop.universe.publishing.notice': 'Má dhéanann tú an domhan a fhoilsiú, foilseofar é go huathoibríoch nuair a fhoilseofar an chéad scéal atá ceangailte leis an domhan.',
    'workshop.universe.settings': 'Socruithe an domhain {universe}',
    'workshop.universe.publishedOn': 'Tá an domhan seo foilsithe ar {date, date, long} {date, time, short}',
    'workshop.universe.description': 'Cur síos ar an Domhan',
    'workshop.settings.title': 'Teideal',
    'workshop.description': 'Cur síos',
    'workshop.language.primary': 'Teanga Phríomhúil',
    'workshop.publication.options': 'Roghanna Foilsithe',
    'workshop.rating': 'Rátáil ginearálta',
    'workshop.universe.rating.desc': 'Beidh scéalta agus fanfic thuas leis an rátáil seo dírithe ó shúil ag úsáideoirí neamhainmnithe agus úsáideoirí nach bhfuil ar an aois oiriúnach.',
    'workshop.universe.license': 'Ceadúnas an Domhain',
    'workshop.universe.genre.pick': 'Roghnaigh an seánra don domhan',
    'workshop.story.genre.pick': 'Roghnaigh seánraí don scéal',
    'workshop.cover': 'Clúdach',
    'workshop.nothingtosee': 'Rud éigin le feiceáil anseo...',
    'workshop.story.cannon': 'Scéal canónach',
    'workshop.story.cannon.desc': 'Is scéal canónach é seo sa domhan {universe}',
    'workshop.story.cannon.desc.create': 'Beidh an scéal seo cruthaithe mar scéal canónach sa {universe} domhan.',
    'workshop.story.fanfiction.search': 'Cuir ainm an domhain isteach (caithfidh sé bheith i do leabharlann). Agus ansin roghnaigh ó na moltaí.',
    'workshop.story.error.nogenres': 'Ní mór duit roghnú ar a laghad aon ghné.',
    'workshop.story.error.toomanygenres': 'Ní ceadmhach ach dhá ghéarshaol don scéal.',
    'workshop.story.error.fanfiction.selectuniverse': 'Ní mór duit domhan bunaidh a roghnú do do fhicsean de chuid na n-aoíscéalaithe!',
    'workshop.story.error.tags.toomany': 'Ní féidir leat ach 10 lipéad a bheith agat ar scéal amháin.',
    'workshop.story.new': 'Cruthaigh scéal nua',
    'workshop.story.publishing.notice': 'Cuirfear an scéal ar fáil go huathoibríoch nuair a fhoilsíonn tú an chéad chaibidil.',
    'workshop.settings.edit': 'Cuir na socruithe in eagar',
    'workshop.story.publishedOn': 'Foilsíodh an scéal seo ar {date, date, long} {date, time, short}',
    'workshop.story.settings': 'Socruithe an scéil',
    'workshop.settings.basic': 'Socruithe bunúsacha',
    'workshop.settings.genres': 'Gnéithe (uasmhéid 2)',
    'workshop.story.license': 'Ceadúnas an scéil',
    'workshop.story.settings.universe': 'Socruithe an domhain',
    'workshop.story.dangerZone': 'Danger zone',
    'workshop.story.dangerZone.desc': 'These actions affect how your story is organized across universes. Proceed carefully.',
    'workshop.story.universe.assign.missing': 'Please select a universe to continue.',
    'workshop.story.universe.assignTitle': 'Create or assign a universe',
    'workshop.story.universe.assign.desc': 'Attach this story to an existing universe, or create a brand-new universe using the story details.',
    'workshop.story.universe.assign.mode': 'Universe option',
    'workshop.story.universe.assign.existing': 'Assign to an existing universe',
    'workshop.story.universe.assign.create': 'Create a new universe from this story',
    'workshop.story.universe.assign.loading': 'Loading your universes...',
    'workshop.story.universe.assign.select': 'Select universe',
    'workshop.story.universe.assign.placeholder': 'Choose a universe',
    'workshop.story.universe.assign.none': 'You do not have any universes yet. Create a new one to continue.',
    'workshop.story.universe.assign.publishNote': 'This story is already published, so the new universe will be published too.',
    'workshop.story.universe.assign.createBtn': 'Create universe',
    'workshop.story.universe.assign.trigger': 'Create or assign a universe',
    'workshop.story.universe.standalone.title': 'Make story standalone',
    'workshop.story.universe.standalone.heading': 'Move this story out of its universe?',
    'workshop.story.universe.standalone.desc': 'This story will be removed from the universe and listed as a standalone story.',
    'workshop.story.universe.standalone.current': 'Current universe: {title}',
    'workshop.story.universe.standalone.warning1': 'Readers browsing the universe will no longer see this story listed there.',
    'workshop.story.universe.standalone.warning2': 'Existing links that point to the universe version of this story may stop working.',
    'workshop.story.universe.standalone.warning3': 'You can attach the story to a universe again later from story settings.',
    'workshop.story.universe.standalone.trigger': 'Make story standalone',
    'workshop.settings.tags': 'Lipéid',
    'workshop.revision': 'Athbhreithniú',
    'workshop.revisions.title': '{story}: {chapter} Athbhreithnithe',
    'workshop.revisions.current': 'Dréacht reatha',
    'workshop.revisions.new.beta': 'Cruthaigh athbhreithniú nua as an ndréacht.',
    'workshop.revisions.new.public': 'Cruthaigh athbhreithniú poiblí nua as an ndréacht.',
    'workshop.revisions.toeditor': 'Téigh chuig an eagarthóir',
    'workshop.revisions.comments': 'Nótaí athbhreithnithe',
    'workshop.revisions.comments.title': '{story}: {chapter} - Athbhreithniú {revision} - Nótaí',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {for Beta readers}
      readers {Public}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'Ní mór duit athbhreithniú a chruthú ar dtús.',
    'workshop.revisions.comments.select': 'Roghnaigh athbhreithniú',
    'workshop.collaborators.noresults': 'Gan torthaí',
    'workshop.collaborators.add.beta': 'Cuir Beta léitheoir leis',
    'workshop.collaborators.add.collaborator': 'Cuir comhoibrí leis',
    'workshop.collaborators.add.translator': 'Cuir aistritheoir leis',
    'workshop.collaborators.language.add': 'Cruthaigh aistriúchán nua',
    'workshop.translations.stories': 'Aistriúcháin - scéalta',
    'workshop.translations.universes': 'Aistriúcháin - uilebheistí',
    'workshop.revisions.beta.none': 'Gan athbhreithnithe faoi láthair.',
    'reader.asidetoggle': 'Comhghleacaithe faisnéise a chasadh',
    'workshop.translation.original': 'Bunaidh:',
    'workshop.translation.original.title': 'Teideal bunaidh:',
    'workshop.translation.original.description': 'Cur síos bunaidh:',
    'workshop.translation.original.cover': 'Clúdach bunaidh',
    'workshop.translation.original.tags': 'Taicfhocail bunaidh',
    'workshop.cover.alt': 'íomhá ghlúin',
    'workshop.translation.updatedOrig': 'Deireadh an nuashonruithe ar an bhunaidh: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'Deireadh an nuashonruithe ar an aistriúchán: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'Deireadh an athbhreithnithe {revision, number}, den bhunaidh: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'Deireadh an athbhreithnithe {revision, number}, den aistriúchán: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `Chun níos mó {type, select,
    collaborator {comhoibritheoirí}
    beta {léitheoirí beta}
    translator {aistritheoirí}
    other {}
  }a chur leis, caithfidh tú do leibhéal ballraíochta a ardú.`,
    'workshop.collaborators.requests.sent': 'Iarrachtaí seolta',
    'workshop.collaborators.requests.invite': `Tá cuireadh tugtha duit a bheith {role, select,
    beta {léitheoir beta}
    translator {aistritheoir}
    collaborator {comhoibrí}
    other {}
  } don seo a leanas:`,
    'workshop.collaborators.requests.dashboard': `Tá cuireadh tugtha duit chun comhoiriúnacht a dhéanamh ar {count, plural,
    zero {gan obair}
    one {saothar liteartha amháin}
    other {# saothair liteartha}
  }.`,
    'workshop.collaborators.language.added': 'Teanga curtha leis',
    'workshop.story.noChaptersFound': 'Níor aimsíodh aon chaibidlí.',
    'workshop.fanfic.needUniverseInLibrary': 'Tá go leor domhain amuigh ann. Cuir na ceannanna ar mhaith leat scríobh iontu i do leabharlann chun go mbeimid in ann iad a aimsiú.',
    'workshop.fanfic.findUniverse': 'Téigh agus aimsigh domhan iontach!',
    'workshop.encSettings': 'Socruithe na hEagnaíochta',
    'workshop.collaborators.removeUser': 'Bain úsáideoir',
    'workshop.collaborators.cancelInvite': 'Cealaigh cuireadh',
    'workshop.universe.createFirstStory': 'Cruthaigh an chéad scéal',
    'workshop.storylines': 'Línte Scéalta',
    'workshop.scenesManager': 'Bainisteoir Radhairc',
    'workshop.collaborators.addRoleForLang': 'Cuir {role} le haghaidh {language}',
    'workshop.beta.revisionInfo': 'Seo an athbhreithniú {revision, number}, cruthaithe ar {createdAt, date, long}.',
    'workshop.story.notes.title': 'Do nótaí do {storyTitle}',
    'workshop.story.notes.desc': 'Nótaí an ábhair',
    'workshop.story.notes.tile': 'Nótaí an ábhair',
    'workshop.story.alternateFormats.tile': 'Alternate formats',
    'workshop.story.alternateFormats.title': '{storyTitle}: Alternate formats',
    'workshop.story.alternateFormats.arcs.title': 'Arcs',
    'workshop.story.alternateFormats.arcs.add': 'Add arc',
    'workshop.story.alternateFormats.arc.defaultTitle': 'Arc {index}',
    'workshop.story.alternateFormats.arc.name': 'Arc name',
    'workshop.story.alternateFormats.arc.from': 'From chapter',
    'workshop.story.alternateFormats.arc.to': 'To chapter',
    'workshop.story.alternateFormats.arc.uploads': 'Files',
    'workshop.story.alternateFormats.arc.upload.epub': 'Upload EPUB',
    'workshop.story.alternateFormats.arc.upload.pdf': 'Upload PDF',
    'workshop.story.alternateFormats.fullStory.title': 'Full story file',
    'workshop.story.alternateFormats.ongoingAccess.title': 'Ongoing access',
    'workshop.story.alternateFormats.ongoingAccess.allAvailable': 'All currently available chapters',
    'workshop.story.alternateFormats.ongoingAccess.perChapter': 'Per chapter (as chapters are released)',
    'workshop.hideOrgs': 'Folaigh ábhar ó eagraíochtaí',
    'workshop.translation.premium': 'Chun aistriúcháin a chur leis, ní mór duit a bheith agat ar a laghad síntiús Explorer.',
    'workshop.story.finished': 'Tá an scéal críochnaithe',
    'workshop.story.publishing.externalSellingNotice': 'Mar gur féidir leat díol taobh amuigh de Léann Liteartha is féidir leat an scéal a fhoilsiú anois. Beidh naisc chuig do liosta siopa le feiceáil ar an scéal nó ag deireadh an scéil reatha a fhoilsiú anseo.',
    'workshop.sharing.publicURL': 'Leagan poiblí',
    'workshop.fictionalTime.title': 'Amanna finscéalacha do {universeName}',
    'workshop.fictionalTime.none': 'Níl aon amharc ficsin fós socraithe agat faoi láthair.',
    'workshop.fictionalTime.createNow': 'Cruthaigh ceann anois!',
    'workshop.fictionalTime.createTitle': 'Cruthaigh am ficsin nua',
    'workshop.fictionalTime.editTitle': 'Cuir in eagar {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'Ainm an ama',
    'workshop.fictionalTime.basicInfo': 'Eolas bunúsach',
    'workshop.fictionalTime.timeSetup': 'Socrú ama',
    'workshop.fictionalTime.linkedToET': 'An dtosaíonn an t-am seo ar dáta Domhanda (féilire Gregorian)?',
    'workshop.fictionalTime.timeDeclaration': 'Fógra ama',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'Roimh na hainmhithe',
    'workshop.fictionalTime.declarationAfter': 'Tar éis na hainmhithe',
    'workshop.fictionalTime.declarationNone': 'Neamhní',
    'workshop.fictionalTime.units': 'Aonaid',
    'workshop.fictionalTime.ETStart': 'Dáta tosaigh an ama seo',
    'workshop.fictionalTime.unitsDescFirst': 'Cé mhéad aonaid atá sa t-aonad seo ó mhílteanán?',
    'workshop.fictionalTime.unitsDesc': 'Cé mhéad aonaid atá sa cheann seo ón cheann roimhe seo?',
    'workshop.fictionalTime.unitsName': 'Ainm na h-aonaid',
    'workshop.fictionalTime.unitsSeparator': 'Séanadh ón aonad roimhe seo',
    'workshop.fictionalTime.unitAdd': 'Cuir aonad leis',
    'workshop.fictionalTime.clocks': 'Cloganna',
    'workshop.fictionalTime.unitTransfer': 'Aistriú aonaid',
    'fictionalTime.pageStartElapsedTime': 'Am a chuaigh thart ón bpointe seo a oscailt',
    'fictionalTime.currentTime': 'Am reatha',
    'workshop.shoppingExternal.options': 'Roghanna ceannaíochta seachtracha',
    'workshop.shoppingExternal.explainer': 'Má tá do scéal á díol in áiteanna eile, is féidir leat na nascanna a shocrú anseo. Beidh na nascanna sin le feiceáil in ionad an ábhar nó ag deireadh an ábhair a roghnaíonn tú chun réamhamharc a dhéanamh.',
    'workshop.shoppingExternal.amazonStore': 'Siopa Amazon',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Ainm an siopa',
    'workshop.shoppingExternal.itemUrl': 'URL an t-earra',
    'workshop.shoppingExternal.storesOther': 'Siopaí eile',
    'fictionalTime.units.milliseconds': '{units, number} millisecond',
    'fictionalTime.countdownToStart': 'Comhaireamh síos go dtosóidh an t-am',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 lá }
      other {{days} laethanta }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {soicind}
      other {soicind}
    }}
    minutes {{units, plural,
      one {nóiméad}
      other {nóiméad}
    }}
    hours {{units, plural,
      one {uair}
      other {uair}
    }}
    days {{units, plural,
      one {lá}
      other {lá}
    }}
    years {{units, plural,
      one {bliain}
      other {bliain}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'Ó',
    'fictionalTime.inputSelectTimeUnit': 'Roghnaigh aonad ama',
    'fictionalTime.inputSelectETUnit': 'Roghnaigh aonad ama Domhain',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Bosca Uirlisí ar an Taobhchlár',
    'workshop.writerSidebar.description': 'Fáilte chuig do scéal! Cuireann an taobhchlár seo rochtain éasca ar gach acmhainn a bhaineann le do scéal. Seiceáil na híomhánna thuas chun an comhrá is déanaí, do chuid nótaí agus go leor eile a fheiceáil!',
    'workshop.story.authorsNotesExplained': 'Doiciméad do na léitheoirí a léamh ag tús an cháipitil.',
    'workshop.story.chapterSortSwitch': 'Athraigh ord na gcaibidleach',
    'workshop.story.prolog': 'Prólóg',
    'workshop.story.chapter': 'Caibidil {sequence, number}',
    'workshop.work.includesAds': 'An bhfuil aon fógraíocht nó ábharáinmneacha táirgí sa saothar?',
    'workshop.universe.forumSettings': 'Socruithe fóraim inmheánacha an Aontais',
    'workshop.ratingAdjusted': 'Due to complains we had to adjust your rating to the one that we felt appropriate. As such changing the rating is now disabled.',
    'workshop.selectCollaborator': 'Select collaborator',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Draft',
    'workshop.chapterStatus.scheduled': 'Scheduled',
    'workshop.chapterStatus.published': 'Published',
    'workshop.story.continuedIn': 'Which stories continue this story?',
    'workshop.story.continuedPlaceholder': 'Select story from this universe',
    'workshop.universe.isAIGenerated': 'Is the content of the universe generated by AI?',
    'workshop.universe.isAIGeneratedTooltip': 'Please let us know if any of the content in the universe was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.story.isAIGenerated': 'Is the story generated by AI?',
    'workshop.story.isAIGeneratedTooltip': 'Please let us know if any of the story was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.publicationAgreement.aria': 'Publication agreement for work',
    'workshop.publicationAgreement.intro': 'We are happy that you have chosen to publish your creative work with us. Before we proceed we just need you to look over our publication agreement, to understand what it means from the legal side of things.',
    'workshop.sortChapters': 'Sort order:',
    'workshop.sortChapters.ascending': 'From beginning',
    'workshop.sortChapters.descending': 'From latest',
    'workshop.sortChapters.aria': 'Select for which way to sort chapter listing',
    'workshop.hiatus.btn': 'Athraigh stádas an scéil go Hiatus',
    'workshop.cancelled.btn': 'Athraigh stádas an scéil go Ceancelaithe',
    'workshop.complete.btn': 'Athraigh stádas an scéil go Criochnaithe',
    'workshop.statusChange.modalTop': 'An bhfuil tú cinnte go bhfuil tú ag iarraidh an stádas a athrú go',
    'workshop.statusName.hiatus': 'Hiatus',
    'workshop.statusName.cancelled': 'Ceancelaithe',
    'workshop.statusName.completed': 'Críochnaithe',
    'workshop.statusExplain.hiatus1': 'Tá Hiatus le rá go bhfuil tú ag dul i bhfolach ón obair ar an scéal seo ar feadh tamaillín, ar chúis ar bith. Beidh sé a insíonn do léitheoirí nach gcaithfidh siad súil a choinneáil le haon nuacht nua i rith na seachtainí atá le teacht nó fiú suas le cúpla mí.',
    'workshop.statusExplain.hiatus2': 'Déanfaidh an stádas hiatus a bheith ar leathadh go huathoibríoch má fhoilsíonn tú aon chaibidil. Nó is féidir leat é a athrú tú féin.',
    'workshop.statusExplain.hiatus3': 'Má choinníonn tú do scéal i hiatus ar feadh sé mhí, gheobhaidh muid an stádas cealaithe go huathoibríoch.',
    'workshop.statusExplain.cancelled1': 'Tá brón orainn cloisteáil nach bhfuil tú in ann leanúint ar aghaidh ag obair ar an scéal. Ar an taobh eile, táimid sásta go bhfuil tú toilteanach a chur in iúl do léitheoirí.',
    'workshop.statusExplain.cancelled2': 'Leathnóidh an cealú scéal a fhógairt do léitheoirí nach gcaithfidh siad súil a choinneáil le haon nuacht nua.',
    'workshop.statusExplain.cancelled3': 'Is féidir leat é seo a athrú trí chaibidil a fhoilsiú nó an stádas a athrú.',
    'workshop.statusExplain.finished1': 'Comhghairdeas! Tar éis an obair chrua sin tá tú deireadh na heachtraíochta iontach bainte amach. Cé go bhféadfadh an scéal deireadh a fháil anois, tá súil againn go mbeidh níos mó scéalta le insint sa todhchaí, ach anois, lig do chosa go héasca agus bain sult as an sos maith a bhfuil tuillte agat.',
    'workshop.statusExplain.finished2': 'Ag marcáil an scéil mar chríochnaithe, inseoidh tú do léitheoirí go bhfuil an scéal críochnaithe. Cé nach bhfaighfeá aon chaibidil nua a chur leis ní stopfaimid thú agus ní hé idé-eolaíocht chaibidilí speisialta a chur leis ní drochidé-eolaíocht é, mar shampla, níos mó éipilóga a chur le gach carachtar.',
    'workshop.statusExplain.finished3': 'Cé gur féidir leat an stádas seo a chealú i gcónaí, molaimid go láidir i gcoinne é. Má tá sé de dhualgas don scéal leanúint ar aghaidh, b\'fhéidir go mbeadh sé níos fearr scéal nua a thosú.',
    'workshop.status.goActive': 'Déan an scéal gníomhach arís',
    'workshop.statusChangeEmail.storyIntro': 'Ba mhaith linn a chur in iúl duit go bhfuil do scéal:',
    'workshop.statusChangeEmail.hiatusTitle': 'Arna shocrú go huathoibríoch, cuireadh an stádas hiatus ar do scéal',
    'workshop.statusChangeEmail.hiatusIntro': 'De bharr neamhghníomhacht, d\'athraíodh do stádas scéal go hiátús go huathoibríoch.',
    'workshop.statusChangeEmail.hiatusWhy': 'Cuireadh ar iátús go huathoibríoch de bharr nach raibh aon chaibidil nua foilsithe le breis agus 6 mhí.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'Beidh an stádas seo á bhaint go huathoibríoch má fhoilseofar chaibidil nua. Mura bhfoilseofar chaibidil nua sa 6 mhí atá romhainn, gheobhaidh muid an scéal a shocrú go huathoibríoch mar chuir síos.',
    'workshop.statusChangeEmail.cancellationIntro': 'D\'athraíodh do stádas scéal go huathoibríoch.',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'Beidh an stádas seo á bhaint go huathoibríoch má fhoilseofar chaibidil nua. Mura bhfuil sé ar intinn agat dul ar aghaidh leis an scéal seo níl rud ar bith eile le déanamh agat.',
    'workshop.startCreating': 'Tosaigh ag cruthú',
    'workshop.ownWork': 'Obair féin',
    'workshop.list.thumbs': 'Liosta na n-íomhánna bheaga',
    'workshop.list.list': 'Liosta ghearr',
    'workshop.fanfiction.new': 'Cruthaigh ficsean nua d\'uaillmhian',
    'workshop.videoTrailerLink': 'Nasc treilire físe',
    'workshop.videoTrailerPlayerTitle': 'Seinnteoir traileir físe Scéil',
    'workshop.videoTrailer.supportedPlaftorms': 'Tacaímid le Youtube, Vimeo agus Odysee',
    'workshop.videoTrailer.rumble': 'Tugaimid tacaíocht freisin do Rumble, ach cuimhnigh an URL IFRAME a chóipeáil.',
    'workshop.videoTrailer.suggestPlatforms': 'An bhfuil do phlátform físeáin ar iarraidh? Inis dúinn trí ár <a>feedback</a>!',
    'workshop.cover.edit': 'Change cover',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    // Chapter deletion
    'workshop.chapter.delete.modalAria': 'Confirmation modal for deleting a chapter',
    'workshop.chapter.delete.confirm': 'Delete Chapter',
    'workshop.chapter.delete.warning': 'Are you sure you want to delete "{title}"? This action cannot be undone.',
    'workshop.chapter.delete.button': 'Delete Chapter',
    'workshop.chapter.delete.deleting': 'Deleting...',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.',
    'workshop.timer.settings': 'Timer Settings',
    'workshop.timer': 'Timer',
    'workshop.timer.type': 'Type',
    'workshop.timer.timer': 'Timer',
    'workshop.timer.countdown': 'Countdown',
    'workshop.timer.pomodoro': 'Pomodoro',
    'workshop.timer.mode': 'Mode',
    'workshop.timer.regular': 'Regular',
    'workshop.timer.improved': 'Improved',
    'workshop.timer.duration': 'Duration (min)',
    'workshop.timer.workDuration': 'Work (min)',
    'workshop.timer.breakDuration': 'Break (min)',
    'workshop.timer.breakType': 'Break Type',
    'workshop.timer.softBreak': 'Soft Break',
    'workshop.timer.hardBreak': 'Hard Break',
    'workshop.timer.break': 'Break',
    'workshop.timer.breakTime': 'Break Time!',
    'workshop.timer.breakMessage': 'Take a moment to rest. Click anywhere to dismiss.',
    'workshop.timer.pause': 'Pause',
    'workshop.timer.resume': 'Resume',
    'workshop.timer.stop': 'Stop',
    'workshop.timer.start': 'Start',
    'workshop.timer.tabInactive': 'Timer paused - switch back to tab to continue',
    // Timer descriptions
    'workshop.timer.type.timer.desc': 'Simple stopwatch that starts at 0:00 and counts upward. Perfect for tracking total writing time in a session or seeing how long you\'ve been working continuously. Never ends automatically - you control when to stop.',
    'workshop.timer.type.countdown.desc': 'Countdown timer that starts from your set duration and counts down to zero. Great for time-boxed writing sessions, word sprints, or when you want to work for a specific amount of time before taking a break.',
    'workshop.timer.type.pomodoro.desc': 'Structured productivity technique: 25-minute focused work sessions alternating with 5-minute breaks. After 4 cycles, takes a longer 15-30 minute break. Scientifically proven to improve focus and prevent burnout.',
    'workshop.timer.mode.regular.desc': 'Timer runs continuously regardless of your activity. Best for disciplined writers who want to track time even when researching, editing, or taking short breaks. Timer keeps going when you switch tabs or stop typing.',
    'workshop.timer.mode.improved.desc': 'Smart timer that automatically pauses when you switch browser tabs. Perfect for focused writing sessions where you want accurate tracking of actual writing time, not total time spent on the page.',
    'workshop.timer.breakType.soft.desc': 'Gentle reminder approach: Shows a small notification when break time starts. You can choose to continue working if you\'re in \'the zone\' or take the break. Good for flexible writers who sometimes need to extend productive sessions.',
    'workshop.timer.breakType.hard.desc': 'Strict enforcement: Displays a full-screen modal that prevents further input until the break timer completes. Forces you to step away from the keyboard. Ideal for writers who struggle with self-discipline or workaholics who need enforced rest periods.',
    'workshop.timer.duration.timer.desc': 'How long you plan to write in this session. Start with 25-50 minutes for focused work, or set longer sessions (2-4 hours) for deep writing days.',
    'workshop.timer.duration.countdown.desc': 'Target writing time before the timer ends. Try 25 minutes for focused sprints, 45-60 minutes for substantial work sessions, or 90 minutes for creative deep dives.',
    'workshop.timer.workDuration.desc': 'Length of focused work sessions. Traditional Pomodoro uses 25 minutes. Try 15-20 minutes if you find it hard to concentrate for longer periods, or 45-50 minutes for experienced writers who can maintain deep focus.',
    'workshop.timer.breakDuration.desc': 'Rest period between work sessions. Standard is 5 minutes for short breaks. Use 10-15 minutes for longer breaks that allow you to step away from your desk, stretch, or get a drink. Every 4th break is automatically longer (2-3x duration).',
    'workshop.llmstxt': 'AI Access',
    'workshop.llmstxt.blocked': 'Blocked - LLMs cannot access your content',
    'workshop.llmstxt.free': 'Free - LLMs can access your content for free',
    'workshop.llmstxt.paid': 'Paid - LLMs can access your content for a fee (coming soon)',
    'workshop.ai.llmstxt.generate': 'Generate LLMs.txt',
    'workshop.ai.llmstxt.generating': 'Generating LLMs.txt...',
    'workshop.ai.llmstxt.download': 'Download LLMs.txt',
    'workshop.ai.llmstxt.title': 'Texts for AI services',
    'workshop.ai.agent.title': 'Assistant',
    'workshop.ai.llmstxt.story-info': 'Story Info LLMs.txt',
    'workshop.ai.llmstxt.full-content': 'Full Content LLMs.txt',
    'workshop.ai.llmstxt.info': 'Info LLMs.txt - Basic information for AI',
    'workshop.ai.llmstxt.infoShort': 'Basic information',
    'workshop.ai.llmstxt.full': 'Content LLMs.txt - Full content for AI',
    'workshop.ai.llmstxt.fullShort': 'Full content'
};