export default {
    'challenges.current': 'हालका चुनौतिहरू',
    'challenges.wordcount.goal': 'लक्षित शब्द संख्या',
    'challenges.wordcount.dailygoal': 'लक्षित दैनिक शब्द संख्या',
    'challenges.wordcount.today': 'आज लेखिएको',
    'challenges.wordcount.total': 'कुल लेखिएका शब्दहरू',
    'challenges.wordcount.remaining': 'बाँकी रहेका शब्दहरू',
    'challenges.wordcount.daysleft': 'बाँकी रहेका दिनहरू',
    'challenges.wordcount.currentDay': 'हालको दिन',
    'challenges.wordcount.average': 'दैनिक औसत शब्द संख्या',
    'challenges.wordcount.finishOn': 'हालको गति अनुसार तपाईंले समाप्त गर्नुहुनेछ',
    'challenges.wordcount.finishOnTime': 'समयमा समाप्त गर्न लेख्नुपर्ने दैनिक शब्दहरू',
    'challenges.wordcount.graph.day': 'दिन {day}',
    'challenges.underway': 'यो चुनौती पहिले नै सुरु भएको छ।',
    'challenges.targetWords': 'लक्षित शब्द संख्या',
    'challenges.startDate': 'सुरु मिति',
    'challenges.endDate': 'समाप्ति मिति',
    'challenges.future': 'आगामी चुनौतिहरू',
    'challenges.future.wordcount': 'Wordcount challenge staring on {startDate, date, short} with goal of {target, number} by {endDate, date, short}.',
    'challenges.future.nanowrimo': 'NaNoWriMo चुनौती तयार छ।',
    'challenges.wordcount': 'शब्द संख्या',
    'challenges.wordcount.desc': `Set yourself a goal of how many words you want to write this month for this {type, select,
    story {story}
    universe {universe}
    other {}
  }.`,
    'challenges.wordcount.select': 'तपाईंले आफ्नो चुनौतीमा कति शब्दलाई चुनौती दिन चाहानुहुन्छ?',
    'challenges.start': 'चुनौती सुरु गर्नुहोस्',
    'challenges.report': 'रिपोर्ट',
    'challenges.victory': 'शुभकामना! तपाईंले यो चुनौती सम्पन्न गर्नुभयो।',
    'challenges.defeat': 'दुःख लाग्यो, तपाईंले यो चुनौती सम्पन्न गर्न सक्नुभयो।',
    'challenges.baseline': 'The current wordcount for this story is {wordcount, number}, this will be the starting point.',
    // NaNoWriMo
    'nanowrimo.full': 'राष्ट्रिय उपन्यास लेखन महिना',
    'nanowrimo.site': 'NaNoWriMo आधिकारिक साइट',
    'nanowrimo.settings': 'NaNoWriMo खाता',
    'nanowrimo.username': 'NaNoWriMo प्रयोगकर्ता नाम',
    'nanowrimo.key': 'गोप्य कुञ्जी',
    'nanowrimo.key.get': 'तपाईंको NaNoWriMo कुञ्जी प्राप्त गर्नुहोस्।',
    'nanowrimo.key.get.notice': 'तपाईंले लग इन गर्नुपर्छ यसलाई हेर्नको लागि।',
    'nanowrimo.ongoing': 'पूर्णता छ! {countdown} थप दिन बाँकी छन्!',
    'nanowrimo.startsin': `{countdown, plural,
      one {दिनमा सुरु हुनेछ! 1 दिन}
      other {# दिनहरू}
    }! तयार हुनुहोस्!`,
    'nanowrimo.isover': 'NaNoWriMo सकिएको छ। भेटौला भेटौलीमा भेटौला!',
    'nanowrimo.select': 'यस कथालाई NaNoWriMo को लागि निर्दिष्ट गर्नुहोस्।',
    'nanowrimo.baseline': 'जब NaNoWriMo सुरु हुन्छ तब यसले हालको शब्दसंख्या लिन्छ र यसलाई NaNoWriMo को भागको रूपमा लिन्छ।',
    'nanowrimo.victory': 'बधाई छ! तपाईले NaNoWriMo जित्यौं!',
    'nanowrimo.challenge': 'NaNoWriMo चुनौती',
    'nanowrimo.description': 'चुनौती हो : नोभेम्बर मा {words, number} शब्दको उपन्यास लेख्ने।',
    'nanowrimo.error.usernotfound': 'Username लाई NaNoWriMo सर्भरहरूमा फेला परेन।',
    'nanowrimo.error.nobook': 'कुनै पुस्तक फेला परेन। कृपया निश्चित गर्नुहोस् कि तपाईंले NaNoWriMo मा आफ्नो पुस्तक सिर्जना गरेका छौं।',
    'nanowrimo.error.wordcount': 'NaNoWrimo मा शब्द संख्या सेट गर्न सकिएन, कृपया आफ्ना क्रेडेन्शियलहरू दुबैपटक जाँच गर्नुहोस् र पुन: प्रयास गर्नुहोस्।',
    'nanowrimo.connected': 'तपाईंले यस कथालाई NaNoWriMo को लागि निर्दिष्ट गर्नुभयो।',
    'nanowrimo.connected.other': 'तपाईंले पहिले नै अर्को कथा सम्बन्धित गर्नुभयो।'
};