export default {
    'encyclopedia.add': 'नयाँ प्रविष्टि थप्नुहोस्',
    'encyclopedia.browse': 'ज्ञानकोषमा ब्राउज गर्नुहोस्',
    'encyclopedia.search': 'ज्ञानकोष खोज्नुहोस्',
    'canvas.toolbar.add': 'Add:',
    'canvas.toolbar.text': 'Text',
    'canvas.toolbar.link': 'Link',
    'canvas.toolbar.group': 'Group',
    'canvas.toolbar.entry': 'Entry',
    'canvas.encPicker.title': 'Pick an encyclopedia entry',
    'canvas.encPicker.search': 'Search entries…',
    'canvas.dialog.pickEntry': 'Pick encyclopedia entry',
    'canvas.node.link': 'Link',
    'canvas.node.encEntry': 'Entry',
    'canvas.entry.open': 'Double-click to open entry',
    'encyclopedia.back.universe': 'ब्रह्माण्ड पृष्ठमा फिर्ता जानुहोस्',
    'encyclopedia.back.workshop': 'कार्यशालामा फिर्ता जानुहोस्',
    'encyclopedia.categories': 'श्रेणीहरू',
    'encyclopedia.groups': 'समूहहरू',
    'encyclopedia.category.character': 'चरित्रहरू',
    'encyclopedia.category.event': 'घटनाहरू',
    'encyclopedia.category.group': 'समूहहरू',
    'encyclopedia.category.item': 'वस्तुहरू',
    'encyclopedia.category.location': 'स्थानहरू',
    'encyclopedia.category.other': 'अन्य',
    'encyclopedia.category.state': 'राज्यहरू',
    'encyclopedia.category.governments': 'सरकारहरू',
    'encyclopedia.category.languages': 'भाषाहरू',
    'encyclopedia.category.creatures': 'प्राणीहरू',
    'encyclopedia.category.deity': 'देवताहरू',
    'encyclopedia.category.religions': 'धर्महरू',
    'encyclopedia.category.flora': 'वनस्पतिहरू',
    'encyclopedia.category.magic': 'जादू',
    'encyclopedia.category.planets': 'ग्रहहरू',
    'encyclopedia.category.species': 'जातिहरू',
    'encyclopedia.category.technologies': 'प्रविधिहरू',
    'encyclopedia.category.families': 'Families',
    'encyclopedia.category.jobs': 'Jobs',
    'encyclopedia.category.lore': 'Lore',
    'encyclopedia.category.vehicles': 'Vehicles',
    'encyclopedia.category.diseases': 'Diseases',
    'encyclopedia.category.traditions': 'Traditions',
    'encyclopedia.category.sports': 'Sports',
    'encyclopedia.category.food': 'Food',
    'encyclopedia.category.landmarks': 'Landmarks',
    'encyclopedia.category.buildings': 'Buildings',
    'encyclopedia.category.schools': 'Schools',
    'encyclopedia.category.continents': 'Continents',
    'encyclopedia.category.villages': 'Villages',
    'encyclopedia.category.towns': 'Towns',
    'encyclopedia.category.cities': 'Cities',
    'encyclopedia.category.settlements': 'Settlements',
    'encyclopedia.category.countries': 'Countries',
    'encyclopedia.search.found': '{results, plural,\n    =0 {No related entries}\n    one {1 related entry}\n    other {# related entries}\n  } found.',
    'encyclopedia.help.text': 'ज्ञानकोषमा वस्तुहरूको बीचमा भ्रमण गर्नका लागि बायाँ मेनु प्रयोग गर्नुहोस्। एक वस्तु चयन गर्नुभयो भने, यो पाठको स्थानमा देखाइनेछ।',
    'encyclopedia.help.sidebar': 'साइडबार टुलबक्स',
    'encyclopedia.help.sidebar.text': 'Welcome to your story! This sidebar allows you easy access to all resources related to your story. Check the icons above to see the latest comments, your notes, search your encyclopedia, browse and add new entries to your encyclopedia. If you want to add a connection to an entry from the story text, select the text where you want to place it and then click the connect button. You will then be prompted to find and select an item.',
    'encyclopedia.intro': 'ज्ञानकोषमा स्वागत छ {universe}।',
    'encyclopedia.add.title': 'ज्ञानकोषमा नयाँ प्रविष्टि थप्नुहोस्',
    'encyclopedia.add.heading': 'तपाईंले के थप्न चाहानुहुन्छ?',
    'encyclopedia.add.moresoon': 'थप श्रेणीहरू धेरै छाड्ने!',
    'encyclopedia.create': 'Create new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {villages}\n    towns {towns}\n    cities {cities}\n    settlements {settlement}\n    countries {country}\n  }',
    'encyclopedia.create.header': 'Creating a new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {village}\n    towns {town}\n    cities {city}\n    settlements {settlement}\n    countries {country}\n  } in {universe}',
    'encyclopedia.entry.category': 'Entry category: {category, select,\n    character {Character}\n    event {Event}\n    group {Group}\n    item {Item}\n    location {Location}\n    other {Note}\n    state {State}\n    governments {Government}\n    languages {Language}\n    creatures {Creature}\n    deity {Deity}\n    religions {Religion}\n    flora {Flora}\n    magic {Magic}\n    planets {Planet}\n    species {Specie}\n    technologies {Technology}\n    families {Family}\n    jobs {Job}\n    lore {Lore}\n    vehicles {Vehicle}\n    diseases {Disease}\n    traditions {Tradition}\n    food {Food}\n    sports {Sport}\n    landmarks {Landmark}\n    buildings {Building}\n    schools {School}\n    continents {Continent}\n    villages {Village}\n    towns {Town}\n    cities {City}\n    settlements {Settlement}\n    countries {Country}\n  }',
    'encyclopedia.entry.category.legend': 'श्रेणी',
    'encyclopedia.fields.add': 'नयाँ क्षेत्र थप्नुहोस्',
    'encyclopedia.fields.text': 'परिभाषा',
    'encyclopedia.fields.textarea': 'पाठ',
    'encyclopedia.fields.connection': 'सम्बन्ध',
    'encyclopedia.fields.time': 'समय',
    'encyclopedia.fields.image': 'तस्वीर',
    'encyclopedia.fields.canvas': 'Canvas',
    'encyclopedia.visibility': 'दृश्यता',
    'encyclopedia.public': 'सार्वजनिक',
    'encyclopedia.private': 'निजी',
    'encyclopedia.container': 'कन्टेनर',
    'encyclopedia.container.desc': 'Make this entry a container for a new group of entries. This will hide it from the categories listing.',
    'encyclopedia.entry.name': 'प्रविष्टिको नाम',
    'encyclopedia.summary': 'संक्षेप',
    'encyclopedia.summary.desc': 'This is a summary that will be the only initial information displayed to the reader.',
    'encyclopedia.parent': 'मुख्य प्रविष्टि',
    'encyclopedia.related': 'सम्बन्धित प्रविष्टिहरू',
    'encyclopedia.errors.tags': 'प्रति प्रविष्टिमा केवल १० ट्यागहरू हुन सक्छन्।',
    'encyclopedia.field.private': 'निजी क्षेत्र',
    'encyclopedia.ft.indev': 'यो विकल्प विकासमा छ।',
    'encyclopedia.connections.remove': 'कनेक्सन हटाउनुहोस्',
    'encyclopedia.connections.extra': 'अतिरिक्त जानकारी',
    'encyclopedia.connections.existing': 'मौजूदा प्रविष्टि',
    'encyclopedia.connections.existing.abbr': 'ईई',
    'encyclopedia.cover': 'कवर तस्वीर',
    'encyclopedia.translation.title': '{universe} विश्व अनुवादमा स्वागत छ!',
    'encyclopedia.translation.desc': 'यस विकिपीडिया इन्टरफेसले {language}मा अनुवाद गर्न प्रयोग गरिन्छ। अनुदित प्रविष्टिहरूलाई बायाँमा दिइएको सूचीमा छान्नुहोस्।',
    'encyclopedia.welcome.totalEntries': 'There {totalEntries, plural, \n    zero {are no entries}\n    one {is one entry}\n    other {are # entries}\n  } in this universe.',
    'encyclopedia.settings.title': 'विकिपीडिया सेटिङहरू',
    'encyclopedia.settings.categoriesDesc': 'तपाईंले आफ्नो विकिपीडियामा प्रयोग गर्न चाहने श्रेणीहरूलाई सक्षम र असक्षम गर्नुहोस्।',
    'encyclopedia.settings.introText': 'विश्व वर्णनपछि देखाउने स्वागत सन्देश।',
    'encyclopedia.fields.placeholder': 'क्षेत्रको नाम',
    'encyclopedia.fields.delete': 'क्षेत्र हटाउनुहोस्',
    'encyclopedia.timeOption.fictionalDate': 'काल्पनिक मिति',
    'encyclopedia.timeOption.fictionalTime': 'काल्पनिक समय',
    'encyclopedia.timeOption.fictionalDateTime': 'काल्पनिक मिति समय',
    'encyclopedia.timeOption.date': 'मिति',
    'encyclopedia.timeOption.time': 'समय',
    'encyclopedia.timeOption.dateTime': 'मिति र समय',
    'encyclopedia.settings.groupByCategories': 'समूह सूचीमा श्रेणीहरू समावेश गर्नुहोस्',
    'encyclopedia.menuOpen': 'विकिपीडिया मेनु खोल्नुहोस्',
    'encyclopedia.menuClose': 'विकिपीडिया मेनु बन्द गर्नुहोस्',
    'encyclopedia.menuAria': 'विकिपीडिया मेनु',
    'enc.newField': 'नयाँ क्षेत्र',
    'enc.entries.limit': 'You currently have {value, number} out of {max, plural,\n    =0 {unlimited}\n    other {{max, number}}\n  } entries.',
    'enc.entries.limitReached': 'तपाईंले आफूलाई अनुमति भएको सीमामा जानको लागि अधिकतम अनुक्रमणिका प्रवेश संख्या छ।',
    'encyclopedia.pronunciation.title': 'उच्चारण',
    'encyclopedia.wip.abbreviation': 'WIP',
    'encyclopedia.wip.full': 'काम प्रगतिमा',
    'encyclopedia.settings.templateLegend': 'टेम्पलेट ब्रह्माण्ड',
    'encyclopedia.settings.templateDescription': 'यस विज्ञानकोशको सामग्रीलाई अन्य ब्रह्माण्डमा प्रतिलिपि गर्न अनुमति दिनुहोस्। यदि तपाईंलाई कुनै कथाहरू छैनन् र तपाईंले अरूलाई प्रयोग गर्ने टेम्पलेट मात्र बनाउँदै हुनुहुन्छ।',
    'encyclopedia.settings.templateCheckbox': 'यो एउटा टेम्पलेट ब्रह्माण्ड हो',
    'encyclopedia.templateCopy.modalTitle': 'विज्ञानकोश सामग्री प्रतिलिपि गर्नुहोस्',
    'encyclopedia.templateCopy.description': 'यस विज्ञानकोशको सामग्रीलाई तपाईंको ब्रह्माण्डमा प्रतिलिपि गर्नुहोस् र यसले तपाईंको ब्रह्माण्डलाई धनी गर्दैछ।',
    'encyclopedia.templateCopy.targetUniverse': 'प्रतिलिपि गर्ने ब्रह्माण्ड',
    'encyclopedia.templateCopy.finished': 'प्रतिलिपि अद्यावधिक गरियो',
    'encyclopedia.templateCreateUniverse.modalTitle': 'Create universe from template',
    'encyclopedia.templateCreateUniverse.description': 'Create a new universe with pre-seeded encyclopedia content from this template. Your universe will remain private until you decide to make it public.',
    'encyclopedia.templateCreateUniverse.success': 'Universe created successfully! Redirecting...',
    'encyclopedia.pronunciation.audio.play': 'Play pronunciation',
    'encyclopedia.pronunciation.guide': 'Use <ipaLink>IPA notation</ipaLink> when possible. Web Speech API pronunciation is best-effort; see <webSpeechLink>MDN docs</webSpeechLink>.',
    'encyclopedia.templateField.born': 'Born',
    'encyclopedia.templateField.died': 'Died',
    'encyclopedia.templateField.race': 'Race',
    'encyclopedia.templateField.gender': 'Gender',
    'encyclopedia.templateField.partners': 'Partners',
    'encyclopedia.templateField.parents': 'Parents',
    'encyclopedia.templateField.children': 'बच्चाहरू',
    'encyclopedia.templateField.associated-with': 'Associated with',
    'encyclopedia.templateField.biography': 'Biography',
    'encyclopedia.templateField.physical-appearance': 'Physical appearance',
    'encyclopedia.templateField.type-of-event': 'Type of event',
    'encyclopedia.templateField.preceding-events': 'Preceding events',
    'encyclopedia.templateField.following-events': 'Following events',
    'encyclopedia.templateField.leadup': 'Leadup',
    'encyclopedia.templateField.description': 'Description',
    'encyclopedia.templateField.aftermath': 'Aftermath',
    'encyclopedia.templateField.members': 'Members',
    'encyclopedia.templateField.locations': 'Locations',
    'encyclopedia.templateField.events': 'Events',
    'encyclopedia.templateField.vision': 'Vision',
    'encyclopedia.templateField.mission': 'Mission',
    'encyclopedia.templateField.description-of-the-organization': 'Description of the organization',
    'encyclopedia.templateField.history': 'इतिहास',
    'encyclopedia.templateField.owners': 'Owners',
    'encyclopedia.templateField.function': 'Function',
    'encyclopedia.templateField.content': 'Content',
    'encyclopedia.templateField.population': 'Population',
    'encyclopedia.templateField.culture': 'Culture',
    'encyclopedia.templateField.governments': 'Governments',
    'encyclopedia.templateField.religions-believes': 'Religions & believes',
    'encyclopedia.templateField.languages': 'Languages',
    'encyclopedia.templateField.geography': 'Geography',
    'encyclopedia.templateField.founding': 'Founding',
    'encyclopedia.templateField.notable-events': 'Notable events',
    'encyclopedia.templateField.notes': 'Notes',
    'encyclopedia.templateField.type-of-government': 'Type of government',
    'encyclopedia.templateField.structure': 'Structure',
    'encyclopedia.templateField.power-structure': 'Power structure',
    'encyclopedia.templateField.source-of-power': 'Source of power',
    'encyclopedia.templateField.laws': 'Laws',
    'encyclopedia.templateField.ideology': 'Ideology',
    'encyclopedia.templateField.internal-politics': 'Internal politics',
    'encyclopedia.templateField.external-politics': 'External politics',
    'encyclopedia.templateField.leading-figures': 'Leading figures',
    'encyclopedia.templateField.groups': 'Groups',
    'encyclopedia.templateField.military': 'Military',
    'encyclopedia.templateField.items': 'Items',
    'encyclopedia.templateField.typology': 'Typology',
    'encyclopedia.templateField.dialectics': 'Dialectics',
    'encyclopedia.templateField.phonology': 'Phonology',
    'encyclopedia.templateField.grammar': 'Grammar',
    'encyclopedia.templateField.numbers': 'Numbers',
    'encyclopedia.templateField.quantifiers': 'Quantifiers',
    'encyclopedia.templateField.private-notes': 'Private notes',
    'encyclopedia.templateField.type': 'Type',
    'encyclopedia.templateField.notable-features': 'Notable features',
    'encyclopedia.templateField.traits': 'Traits',
    'encyclopedia.templateField.habitat': 'Habitat',
    'encyclopedia.templateField.food-sources': 'Food sources',
    'encyclopedia.templateField.reproduction': 'Reproduction',
    'encyclopedia.templateField.cultural-significance': 'Cultural significance',
    'encyclopedia.templateField.related-creatures': 'Related creatures',
    'encyclopedia.templateField.religion': 'Religion',
    'encyclopedia.templateField.other-names': 'Other names',
    'encyclopedia.templateField.appearance': 'Appearance',
    'encyclopedia.templateField.related-to': 'Related to',
    'encyclopedia.templateField.symbolism': 'Symbolism',
    'encyclopedia.templateField.rituals': 'Rituals',
    'encyclopedia.templateField.origin': 'Origin',
    'encyclopedia.templateField.notable-figures': 'Notable figures',
    'encyclopedia.templateField.deities': 'Deities',
    'encyclopedia.templateField.artifacts': 'Artifacts',
    'encyclopedia.templateField.believes': 'Believes',
    'encyclopedia.templateField.traditions': 'Traditions',
    'encyclopedia.templateField.spread': 'Spread',
    'encyclopedia.templateField.classification': 'Classification',
    'encyclopedia.templateField.features': 'Features',
    'encyclopedia.templateField.produce': 'Produce',
    'encyclopedia.templateField.ecosystem': 'Ecosystem',
    'encyclopedia.templateField.effect': 'Effect',
    'encyclopedia.templateField.alignment': 'Alignment',
    'encyclopedia.templateField.requirements': 'Requirements',
    'encyclopedia.templateField.size': 'Size',
    'encyclopedia.templateField.length-of-day': 'Length of day',
    'encyclopedia.templateField.length-of-night': 'Length of night',
    'encyclopedia.templateField.length-of-cycle': 'Length of cycle',
    'encyclopedia.templateField.moons': 'Moons',
    'encyclopedia.templateField.nearby-stellar-bodies': 'Nearby stellar bodies',
    'encyclopedia.templateField.climate': 'Climate',
    'encyclopedia.templateField.weather': 'Weather',
    'encyclopedia.templateField.natural-resources': 'Natural resources',
    'encyclopedia.templateField.notable-locations': 'Notable locations',
    'encyclopedia.templateField.inhabitans': 'Inhabitans',
    'encyclopedia.templateField.looks': 'Looks',
    'encyclopedia.templateField.production': 'Production',
    'encyclopedia.templateField.use': 'Use',
    'encyclopedia.templateField.related': 'Related',
    'encyclopedia.templateField.location': 'Location',
    'encyclopedia.templateField.significance': 'Significance',
    'encyclopedia.templateField.associated-events': 'Associated events',
    'encyclopedia.templateField.associated-figures': 'Associated figures',
    'encyclopedia.templateField.access-restrictions': 'Access restrictions',
    'encyclopedia.templateField.cultural-importance': 'Cultural importance',
    'encyclopedia.templateField.founded': 'Founded',
    'encyclopedia.templateField.government': 'Government',
    'encyclopedia.templateField.defenses': 'Defenses',
    'encyclopedia.templateField.connected-settlements': 'Connected settlements',
    'encyclopedia.templateField.family-motto': 'Family Motto',
    'encyclopedia.templateField.founding-date': 'Founding Date',
    'encyclopedia.templateField.ethos': 'Ethos',
    'encyclopedia.templateField.family-reputation': 'Family Reputation',
    'encyclopedia.templateField.family-branches': 'Family Branches',
    'encyclopedia.templateField.notable-vassals-retainers': 'Notable vassals/retainers',
    'encyclopedia.templateField.skills-required': 'Skills required',
    'encyclopedia.templateField.pay-salary': 'Pay/Salary',
    'encyclopedia.templateField.associated-locations': 'Associated locations',
    'encyclopedia.templateField.associated-characters': 'Associated characters',
    'encyclopedia.templateField.propulsion': 'Propulsion',
    'encyclopedia.templateField.capacity': 'Capacity',
    'encyclopedia.templateField.speed': 'Speed',
    'encyclopedia.templateField.manufacturers': 'Manufacturers',
    'encyclopedia.templateField.symptoms': 'Symptoms',
    'encyclopedia.templateField.causes': 'Causes',
    'encyclopedia.templateField.treatment': 'Treatment',
    'encyclopedia.templateField.affected-species': 'Affected species',
    'encyclopedia.templateField.associated-groups': 'Associated groups',
    'encyclopedia.templateField.ingredients': 'Ingredients',
    'encyclopedia.templateField.preparation': 'Preparation',
    'encyclopedia.templateField.rules': 'Rules',
    'encyclopedia.templateField.equipment': 'Equipment',
    'encyclopedia.templateField.venues': 'Venues',
    'encyclopedia.templateField.architecture': 'Architecture',
    'encyclopedia.templateField.curriculum': 'Curriculum',
    'encyclopedia.templateField.notable-alumni': 'Notable alumni',
    'encyclopedia.templateField.affiliation': 'Affiliation',
    'encyclopedia.templateField.language': 'Language'
};