export default {
    'homepage.welcome': 'स्वागत छ',
    'homepage.start': 'तपाईंको यात्रा सुरु गर्नुहोस्!',
    'homepage.iAm': 'म छु',
    'homepage.iAm.aria': 'पाठकहरू र लेखकहरूका लागि विशेषताहरूको प्रदर्शन बीचमा छान्नुहोस्',
    'homepage.reader': 'पाठक',
    'homepage.writer': 'लेखक',
    'homepage.reader.title': 'पढ्न यस्तो रोचक कहिल्यै नभएको छ',
    'homepage.reader.readingTitle': 'अनौठो पढ्ने अनुभव',
    'homepage.reader.readingDesc': 'साहित्यिक यूनिभर्समा तपाईंको पसन्दीदा कथाका भित्र थप गहिरो छलफल गर्नुहोस्। साहित्यिक यूनिभर्समा कथाहरू एकै यूनिभर्सको अन्तर्गत जोडिन्छन्, जसले तपाईंलाई कथाको पठन प्रशासनिकबाट तुरुन्त पहुँच प्रदान गर्दछ।',
    'homepage.reader.favoriteTitle': 'तपाईंको पसन्दीदा कथाहरू र लेखकहरूको बारेमा थप जान्नुहोस्',
    'homepage.reader.favoriteDesc': 'यूनिभर्स ज्ञानको संग्रहालय र लेखकको ब्लगहरू मात्रै केही सुविधाहरू हुन् जुनले तपाईंलाई आफ्नो पसन्दीदा कथाहरू, त्यसका सेटिङहरू र त्यसका निर्माताहरूको बारेमा जान्न मद्दत गर्नेछ!',
    'homepage.reader.communityTitle': 'समुदायमा सामेल हुनुहोस्',
    'homepage.reader.communityDesc': 'Meet people from across the globe on dedicated universe and author\'s forums, blogs and other community features where like-minded fans gather. All in one place.',
    'homepage.reader.readingFeatureTitle': 'Enjoy an immersive yet practical reading experience',
    'homepage.reader.readingFeatureDesc': 'From stories and universe, have the benefit of effortless reading with access to details without needing to switch between pages.',
    'homepage.reader.readingExploreTitle': 'Explore all the minutia in the universe',
    'homepage.reader.readingExploreDesc': 'Universe encyclopedia allows you to learn all the details about the universe and fully immerse yourself in the stories.',
    'homepage.reader.start': 'Start Reading',
    'homepage.writer.title': 'Showcase your universe and share your stories',
    'homepage.writer.writingTitle': 'Writing & creating made easy',
    'homepage.writer.writingDesc': 'Experience the new way of writing with Literary Universes Workshop. Create all the details of your universe in an encyclopedia to share with your readers and write amazing stories on that foundation.',
    'homepage.writer.collaborationTitle': 'Collaborative creation',
    'homepage.writer.collaborationDesc': 'Creative process often involves multiple people. No worries, we got you covered! You can easily add beta readers, co-authors and translators to your stories and universes.',
    'homepage.writer.communityTitle': 'Connect with Your readers',
    'homepage.writer.communityDesc': 'Go beyond writing and connect with your readers via blogs, forums and other community features connected to your universes or to you as a writer.',
    'homepage.writer.workshopFeatureTitle': 'One place for all your creative needs',
    'homepage.writer.workshopFeatureDesc': 'Our ever evolving workshop is the central place for your creative needs. From a simple idea create amazing universes, stories and everything else that is needed around it.',
    'homepage.writer.monetizationFeatureTitle': 'वाणिज्यीकरण',
    'homepage.writer.monetizationDesc': 'We strongly believe that people should be payed for their work and are constantly looking for new monetization opportunities for writers. Monetization feature allows you writers to be appreciated for what you do. Explore all the different options that allow your fans to show you their appreciation.',
    'homepage.writer.start': 'Setup Your workshop!',
    'homepage.featureSelection': 'Check out these popular universe!',
    'about.title': 'About Literary Universe',
    'about.desc': 'History, secrets and humans behind Literary Universe.',
    'about.text.1': 'Literary Universe is designed both for writers and for the avid reader. Writers can use the site to write original works through the workshop button in the dashboard menu. This will give you access to the main editor and encyclopedia functions which primarily focus on organizing all aspects of your personal story universe into one page. The social aspects allow authors to broadcast their work and develop a following, as well as to interact more directly if they chose with their readers.',
    'about.text.2': 'Readers can use the site primarily to read new works and follow authors but also to help edit pre-published stories if given permission by the writer. Being a reader on Literary Universe is a whole new reading experience, having access to all the background information on the same page as the main story gives you insight into the mind of the author like never before.',
    'about.text.3': 'The future for Literary Universe involves creating a marketplace for authors to sell their work and adding community features to enhance author and reader communication through blogs and forums. Writer’s tools will be added over time, with over a dozen currently either in development or on the board. Our ultimate goal is to enhance the experiences of writers and readers through providing more innovative use of the internet medium.',
    'about.text.4': 'We hope that you join us as we explore what the internet medium can do for creative writing!',
    'about.team': 'The team',
    'about.history': 'History',
    'about.company': 'कम्पनी',
    'about.companyCountry.czechia': 'चेकिया',
    'about.companyCountry.japan': 'जापान',
    'about.companyCity.prague': 'प्राग',
    'about.companyCity.sendai': 'सेंडाई',
    'about.CEO': 'Chief Executive Officer',
    'about.CTO': 'Chief Technology Officer',
    'about.jan': 'Jan is the founder, visionary and technological brain behind Literary Universe. As a writer of large literary universes, Jan had always found it difficult to write stories from a technical and readability point of view that would not compromise the reading experience. As such, Jan decided to pursue his studies in web development to create an application that would make it easy to write stories in large universes.',
    'about.history.text': 'In 2010 Jan started at Rochester Institute of Technology to learn more about web development in order to be able to build a creative writing site. This materialized in 2013 when the first proof of concept was presented at Imagine RIT. Jan continued his studies and in 2016 a new version of the app was created as a Master\'s Capstone Project. The project continued in fall 2016 and further developed into what you see today.',
    'copyrights.desc': 'The full text of Literary Universe Copyrights Agreement.',
    'privacy.desc': 'Full legal text of Privacy Policy of Literary Universe.',
    'guidelines.desc': 'साहित्यिक विश्वको समुदाय संलग्नता नियमावली।',
    'tos.desc': 'साहित्यिक विश्वको सेवा शर्तहरूको पूर्ण कानुनी पाठ।',
    'homepage.intro': 'Let Your Creativity Run Wild Across the Literary Universe',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'के तपाईंले कहाँ-कहाँ समेत बिस्तृत गरिएको कल्पनाशील विश्व विकास गर्न ख्वाइरहेका छन्? कथाकारी ब्रह्माण्डमा, हामीले यो दृष्टिबद्धीलाई वास्तविकता बनाउने उपकरणहरू प्रदान गर्दछौं। प्रत्येक कथाकारले शीर्ष-गुणस्तरको स्रोत र समर्थन प्राप्त गर्नका लागि हामीले एक सबैलाई समावेशी स्थान डिजाइन गरेका छौं। कथाकारहरूका लागि, यो सपना कार्यस्थल हो; पाठकहरूका लागि, एक अन्वेषणात्मक यात्रा हो। हामीलाई सहभागी बनाउनुहोस् जब हामी कथाकारी खगोलीय गोतामा जान्छौं, तब हाम्रो अन्तरिक्षको दूरता कति देखाउँछ।',
    'gdpr.title': 'GDPR अनुपालन',
    'gdpr.desc': 'साहित्यिक विश्व युरोपेली GDPR निर्देशनहरूको अनुपालन गर्दछ।',
    'gdpr.compliant': 'साहित्यिक विश्व GDPR अनुपालन गर्दछ',
    'gdpr.compliant.text': 'साहित्यिक विश्वले GDPR कार्यान्वयनका लागि आफ्नो कोडबेसमा विभिन्न अद्यावधिकरण र परिवर्तनहरू गरेको छ। २०१८ मे २५ गते गरी GDPR कार्यान्वयनका लागि सजिलै तयारी गरिएको छ।',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'डिजिटल मिलेनियम कपिराइट ऐक्ट',
    'common.legal.changelog': 'यस संस्करणमा परिवर्तनहरू',
    'dmca.title': 'डिजिटल मिलेनियम कपिराइट ऐक्ट (DMCA) नीति',
    'dmca.subtitle': 'कपिराइट विवाद नीति',
    'dmca.step1.title': 'कपिराइट उल्लंघनहरूको रिपोर्ट गर्ने तरिका।',
    'dmca.step2.title': 'यदि निर्दिष्ट एजेन्टले उचित बोनाफाइड उल्लंघन सूचना प्राप्त गर्छ भने।',
    'dmca.step3.title': 'निर्दिष्ट एजेन्टलाई काउन्टर-नोट प्रदान गर्ने तरिका।',
    'dmca.desc': 'हामीले कपिराइट उल्लंघनलाई गम्भीरताको साथ लिन्छौं।',
    'gdpr.access.title': 'पहुँचको अधिकार र डाटा पोर्टेबिलिटीको अधिकार',
    'gdpr.access.desc': 'प्रयोगकर्ता सेटिङहरूमा तपाईंले आफ्ना सबै डाटा निर्यात गर्न सक्नुहुन्छ। यो डाटा मानक JSON ढाँचामा हुनेछ।',
    'gdpr.forget.title': 'बिर्साने अधिकार',
    'gdpr.forget.desc': 'प्रयोगकर्ता सेटिङहरूमा कुनै खाता मेटाउन सकिन्छ। केही डाटा संचित रहन सक्छ, विशेष गरी यदि त्यस्ता डाटाहरू बिक्री गरिएका वा विवादका विषय भएका छन्।',
    'gdpr.rectification.title': 'सुधारको अधिकार',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'प्रक्रियाको सीमाबन्दीको अधिकार',
    'gdpr.processing.desc': 'कथात्मक ब्राउजर सेटिङहरूलाई पुरा रूपमा मान्यता दिन्छ, जस्तै "ट्र्याक नगर्नुहोस्" अनुरोधहरूलाई हाम्रो Matomo तथ्याङ्क सर्भरमा प्रतिवेदन गर्नका लागि।',
    'gdpr.object.title': 'आपत्ति देखाउने अधिकार',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'रिपोर्टिङ्गलाई दुवै परिदृश्यमा बाँडफाँड गरिएको छ। १. आन्तरिक सम्पदाको रिपोर्टिङ्ग (साइटमा अवस्थित सम्पत्तिमा उल्लंघन)। २. बाह्य सम्पदाको रिपोर्टिङ्ग (साइटमा अवस्थित नभएको सम्पत्तिमा उल्लंघन)।',
    'dmca.step1.desc2': 'आन्तरिक सम्पत्तिको रिपोर्टिङ्गलाई सम्पत्तिमा रिपोर्ट बटनबाट गर्न सकिन्छ। बाह्य सम्पत्ति उल्लंघनलाई प्रतिक्रिया स्क्रिनबाट गर्न सकिन्छ। दुवै मामिलामा तपाईंलाई व्यक्तिगत विवरणहरू र अतिरिक्त विवरणहरू प्रदान गर्न अनुरोध गरिनेछ जसले हामीलाई तपाईंको स्वामित्वलाई जाँच गर्न अनुमति दिनेछ।',
    'dmca.step1.desc3': 'कृपया ध्यान दिनुहोस् कि खोटा दावाहरू गर्ने तपाईंको असमर्थताले भविष्यमा तपाईंले दावाहरू दर्ता गर्न असमर्थ हुनेछ।',
    'dmca.step2.desc1': 'तपाईंको रिपोर्ट प्राप्त गर्दा हामी तपाईंको प्रमाणिकता र स्वामित्व कथन सत्यापन गर्नेछौं। सबै कुरा सामान्य छ भने हामी कथन जाँच गर्नेछौं। यदि हामीले कथनलाई सत्य मान्यता गर्छौं भने, हामी अभिभावकीय संपत्ति अवहेलना गर्ने छौं जसलाई काउन्टर-नोटिस निर्धारण वा १४ दिन पछि हटाउनेछौं।',
    'dmca.step3.desc1': 'कोठा अरुपको धारा प्राप्त गरेमा खाताधारीले १४ दिनको अवधि खाता दाखिला गर्न पाउनेछ। नियुक्त एजेन्टले त्यसपछि विवाद गब्जियाउनेछ। यस चरणमा नियुक्त एजेन्टद्वारा गरिएको कुनै पनि निर्णय अन्तिम हुनेछ।',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'जन ड्वोराक',
    'about.attributions': 'प्रशंसापत्रहरू',
    'about.attributionsIntro': 'साहित्यिक विश्वले धेरै ओपन सोर्स परियोजनाहरू र नि:शुल्क स्रोतहरूमा आधारित छ। तल तपाईंले तिनको सूचीबद्धताको आवधानमा पाउनुहुनेछ।',
    'about.attributionsMatomo': 'हाम्रो विश्लेषणहरूले स्वयंहोस्टेड मातोमो र IP2Location LITE डाटाको उपयोग गर्दछ। यसले https://lite.ip2location.com बाट उपलब्ध छ।',
    'team.name.pjakubec': 'पाभेल जाकुबेक',
    'team.name.asebesta': 'आदम शेबेस्टा',
    'about.developer': 'डेभलपर',
    'about.seniorDeveloper': 'वरिष्ठ डेभलपर',
    'about.juniorDeveloper': 'जूनियर डेभलपर',
    'about.leadDesigner': 'मुख्य डिजाइनर',
    'about.leadUX': 'मुख्य यूएक्स डिजाइनर',
    'about.intern': 'इन्टर्न',
    'about.advisor': 'सल्लाहकार',
    'about.headOfResearch': 'अनुसन्धानका मुख्य',
    'about.CFO': 'मुख्य आर्थिक अधिकारी',
    'team.name.hsconovianus': 'हेन्ड्री स्कोनोवियनस',
    'about.hendry': 'हेन्ड्री डिजाइनर हुनुहुन्छ जसमा १५ वर्षभन्दा बढी अनुभव छन्। वह २०१० देखि एजेन्सीमा काम गरिरहेका छन्, जस्तै पर्तामिना, भिओए, र पर्यटन मन्त्रालय आदि उनका ग्राहकहरू। ब्राण्डिङ, लेआउट र युआई / यूएक्सको अनुभव पनि भएका उनले साहित्यिक यूनिभर्समा डिजाइन गर्ने चुनौती महसुस गर्दछन्।',
    'about.pavel': 'Web3, मेटाभर्स, AI, सबै त र केही नयाँ केही छ जुन पावेलले जाँच्नुहुन्छ र जुनलाई साहित्यिक यूनिभर्सलाई सुधार गर्न सकिन्छ। एउटा वास्तविक बहुविज्ञानी अनुसन्धानकर्ता पावेलले धेरै क्षेत्रहरूमा अनुभव राख्छन् र साहित्यिक यूनिभर्समा नयाँ रोचक सुविधाहरू थप्न काम गर्दछन्।',
    'about.seba': 'एकपटक गेमर थिए, अब एडमले पूर्णता भएको डेभलपर बन्न पढाई गर्दै छन्।'
};