export default {
    'stats.age.groups': 'उमेर समूहहरू',
    'stats.age.range': 'उमेर सीमा',
    'stats.age.to12': '१२ सम्म',
    'stats.age.12to17': '१२ देखि १७',
    'stats.age.18to20': '१८ देखि २०',
    'stats.age.21to29': '२१ देखि २९',
    'stats.age.30to39': '३० देखि ३९',
    'stats.age.40to49': '४० देखि ४९',
    'stats.age.50to64': '५० देखि ६४',
    'stats.age.65to84': '६५ देखि ८४',
    'stats.age.above85': '८५ भन्दा माथि',
    'stats.section.aggregate': 'समष्टि तथ्याङ्क',
    'stats.section.chapter': 'अध्याय तथ्याङ्क',
    'stats.readers.title': 'तपाईंको पाठकहरूको बारेमा',
    'stats.gender.title': 'लिङ्ग',
    'stats.view.table': 'तालिका दृश्य',
    'stats.view.pie': 'पाई चार्ट दृश्य',
    'stats.view.bar': 'बार चार्ट दृश्य',
    'stats.view.chart': 'तथ्याङ्क दृश्य',
    'stats.table.total': 'कुल',
    'stats.timeline.title': 'समयरेखा',
    'stats.timeline.dateStart': 'तथ्याङ्क सुरु हुन्छ',
    'stats.timeline.dateEnd': 'तथ्याङ्क समाप्त हुन्छ',
    'stats.likeCount': 'लाइकहरूको संख्या',
    'stats.language.title': 'बोलिने भाषा',
    'stats.chapter.visitorsAndViews': 'अध्याय अनुसार कुल आगमन र भ्रमण',
    'stats.chapter.wordCount': 'प्रति अध्याय शब्द संख्या',
    'stats.chapter.chartTooltipViews': 'अध्याय {chapter, number}: {views, number} दृश्यहरू',
    'stats.chapter.chartTooltipVisitors': 'अध्याय {chapter, number}: {visitors, number} अनौठो आगमनहरू',
    'stats.chapter.chartTooltipWordCount': 'अध्याय {chapter, number}: {wordCount, number} शब्दहरू',
    'stats.totalHits': 'कुल भ्रमणहरू',
    'stats.totalVisitors': 'कुल अद्वितीय भ्रमणहरू',
    'stats.totalWords': 'कुल शब्द संख्या',
    'stats.totalEntries': 'विज्ञापनको निबन्ध',
    'stats.blogPage': 'पृष्ठ',
    'stats.blog.typeSelectionAria': 'प्रकार छनौट',
    'stats.blog.pages': 'पृष्ठहरू',
    'stats.blog.posts': 'पोस्टहरू',
    'stats.unknown': 'अज्ञात',
    'stats.noData': 'यस समयमा कुनै डाटा उपलब्ध छैन।'
};