export default {
    'workshop.title': 'तपाईंको काम',
    'workshop.noneassigned': 'तपाईंलाई कुनै पनि बुझाइएको छैन।',
    'workshop.notavailable': 'यो सुविधा अहिले सम्पन्न भएको छैन।',
    'workshop.none': `You currently have no {type, select,
      universe {universe}
      story {story}
      fanfiction {fan fiction}
      other {}
    }. Create one now!`,
    'workshop.collab': 'सहकार्यको काम',
    'workshop.betareadings': 'बेटा पठाउने',
    'workshop.translations': 'अनुवादहरू',
    'workshop.createnew': 'नयाँ बनाउनुहोस्...',
    'workshop.story.standalone': 'स्वतन्त्र कथा',
    'workshop.story.standalone.desc': 'यो एक स्वतन्त्र कथा हो।',
    'workshop.controlpanel': '{name} कन्ट्रोल प्यानल',
    'workshop.universe.page': 'ब्रह्माण्ड पृष्ठ',
    'workshop.fictionaltime': 'काल्पनिक समय',
    'workshop.dashboard.name': '{name} ड्यासबोर्ड',
    'workshop.stories.in': '{universe}मा कथाहरू',
    'workshop.universe.nostories': 'यस ब्रह्माण्डमा कुनै कथाहरू छैनन्।',
    'workshop.story.chapter.add': 'नयाँ अध्याय',
    'workshop.universe.new': 'नयाँ ब्रह्माण्ड बनाउनुहोस्',
    'workshop.universe.publish': 'ब्रह्माण्ड प्रकाशित गर्नुहोस्',
    'workshop.universe.publishing.notice': 'यदि तपाईं ब्रह्माण्डलाई प्रकाशित गर्नुहुन्न, त्यसमा जडान गरिएको पहिलो कथा प्रकाशित गरिएमा यो अपनै रूपमा प्रकाशित हुनेछ।',
    'workshop.universe.settings': '{universe} ब्रह्माण्ड सेटिङ्स',
    'workshop.universe.publishedOn': 'यो ब्रह्माण्ड प्रकाशित भएको छ {date, date, long} {date, time, short}',
    'workshop.universe.description': 'ब्रह्माण्ड वर्णन',
    'workshop.settings.title': 'शीर्षक',
    'workshop.description': 'वर्णन',
    'workshop.language.primary': 'प्राथमिक भाषा',
    'workshop.publication.options': 'प्रकाशन विकल्पहरू',
    'workshop.rating': 'सामान्य रेटिङ्ग',
    'workshop.universe.rating.desc': 'यस रेटिङ्गभन्दा माथि को कथा र फ्यानफिक्शनलाई अनाम्यस उपयोगकर्ताहरू र उपयोगकर्ताहरूलाई लगानी गरिएको ब्रह्माण्ड पृष्ठ सूचीबाट लुकाइनेछ।',
    'workshop.universe.license': 'ब्रह्माण्ड लाइसेन्स',
    'workshop.universe.genre.pick': 'ब्रह्माण्डका लागि शैली छान्नुहोस्',
    'workshop.story.genre.pick': 'कथाका लागि शैलीहरू छान्नुहोस्',
    'workshop.cover': 'कवर',
    'workshop.nothingtosee': 'यहाँ केही हेर्न केही छैन...',
    'workshop.story.cannon': 'क्यानन कथा',
    'workshop.story.cannon.desc': 'यो कथा {universe} ब्रह्माण्डमा क्यानन हो।',
    'workshop.story.cannon.desc.create': 'यो कथा {universe} यूनिभर्समा एक क्याननिकल कथा के रूपमा सिर्जना गरिनेछ।',
    'workshop.story.fanfiction.search': 'यूनिभर्सको नाम टाइप गर्नुहोस् (तपाईंको पुस्तकालयमा हुनुपर्छ)। र त्यसपछि सुझावहरूबाट छान्नुहोस्।',
    'workshop.story.error.nogenres': 'तपाईंले कम्तिमा एक शैली चयन गर्नुपर्छ।',
    'workshop.story.error.toomanygenres': 'कथामा मात्र दुई शैली अनुमति छ।',
    'workshop.story.error.fanfiction.selectuniverse': 'तपाईंले आफ्नो फ्यान फिक्सनको लागि मूल यूनिभर्स चयन गर्नुपर्छ!',
    'workshop.story.error.tags.toomany': 'प्रत्येक कथामा केवल १० ट्यागहरू हुन सक्छन्।',
    'workshop.story.new': 'नयाँ कथा सिर्जना गर्नुहोस्',
    'workshop.story.publishing.notice': 'पहिलो अध्याय प्रकाशित गर्दा कथा स्वतःमा प्रकाशित हुनेछ।',
    'workshop.settings.edit': 'सेटिङहरू सम्पादन गर्नुहोस्',
    'workshop.story.publishedOn': 'यो कथा प्रकाशित भएको छ {date, date, long} {date, time, short}',
    'workshop.story.settings': 'कथाको सेटिङहरू',
    'workshop.settings.basic': 'मूल सेटिङहरू',
    'workshop.settings.genres': 'शैलीहरू (अधिकतम २)',
    'workshop.story.license': 'कथाको लाइसेन्स',
    'workshop.story.settings.universe': 'यूनिभर्स सेटिङहरू',
    'workshop.story.dangerZone': 'Danger zone',
    'workshop.story.dangerZone.desc': 'These actions affect how your story is organized across universes. Proceed carefully.',
    'workshop.story.universe.assign.missing': 'Please select a universe to continue.',
    'workshop.story.universe.assignTitle': 'Create or assign a universe',
    'workshop.story.universe.assign.desc': 'Attach this story to an existing universe, or create a brand-new universe using the story details.',
    'workshop.story.universe.assign.mode': 'Universe option',
    'workshop.story.universe.assign.existing': 'Assign to an existing universe',
    'workshop.story.universe.assign.create': 'Create a new universe from this story',
    'workshop.story.universe.assign.loading': 'Loading your universes...',
    'workshop.story.universe.assign.select': 'Select universe',
    'workshop.story.universe.assign.placeholder': 'Choose a universe',
    'workshop.story.universe.assign.none': 'You do not have any universes yet. Create a new one to continue.',
    'workshop.story.universe.assign.publishNote': 'This story is already published, so the new universe will be published too.',
    'workshop.story.universe.assign.createBtn': 'Create universe',
    'workshop.story.universe.assign.trigger': 'Create or assign a universe',
    'workshop.story.universe.standalone.title': 'Make story standalone',
    'workshop.story.universe.standalone.heading': 'Move this story out of its universe?',
    'workshop.story.universe.standalone.desc': 'This story will be removed from the universe and listed as a standalone story.',
    'workshop.story.universe.standalone.current': 'Current universe: {title}',
    'workshop.story.universe.standalone.warning1': 'Readers browsing the universe will no longer see this story listed there.',
    'workshop.story.universe.standalone.warning2': 'Existing links that point to the universe version of this story may stop working.',
    'workshop.story.universe.standalone.warning3': 'You can attach the story to a universe again later from story settings.',
    'workshop.story.universe.standalone.trigger': 'Make story standalone',
    'workshop.settings.tags': 'ट्यागहरू',
    'workshop.revision': 'संशोधन',
    'workshop.revisions.title': '{story}: {chapter} संशोधनहरू',
    'workshop.revisions.current': 'हालको ड्राफ्ट',
    'workshop.revisions.new.beta': 'ड्राफ्टबाट नयाँ संशोधन सिर्जना गर्नुहोस्।',
    'workshop.revisions.new.public': 'ड्राफ्टबाट नयाँ सार्वजनिक संशोधन सिर्जना गर्नुहोस्।',
    'workshop.revisions.toeditor': 'सम्पादकमा जानुहोस्',
    'workshop.revisions.comments': 'संशोधन टिप्पणीहरू',
    'workshop.revisions.comments.title': '{story}: {chapter} - संशोधन {revision} - टिप्पणीहरू',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {बेटा पाठकहरूको लागि}
      readers {सार्वजनिक}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'तपाईंले पहिलो पटक संशोधन सिर्जना गर्नुपर्छ।',
    'workshop.revisions.comments.select': 'अद्यावधिक छान्नुहोस्',
    'workshop.collaborators.noresults': 'कुनै परिणाम छैनन्',
    'workshop.collaborators.add.beta': 'बेटा पाठक थप्नुहोस्',
    'workshop.collaborators.add.collaborator': 'सहकारी थप्नुहोस्',
    'workshop.collaborators.add.translator': 'अनुवादक थप्नुहोस्',
    'workshop.collaborators.language.add': 'नयाँ अनुवाद सिर्जना गर्नुहोस्',
    'workshop.translations.stories': 'अनुवादहरू - कथाहरू',
    'workshop.translations.universes': 'अनुवादहरू - विश्वहरू',
    'workshop.revisions.beta.none': 'यस समयमा कुनै संशोधनहरू छैनन्।',
    'reader.asidetoggle': 'अलग जानकारीलाई टगल गर्नुहोस्',
    'workshop.translation.original': 'मूल:',
    'workshop.translation.original.title': 'मूल शीर्षक:',
    'workshop.translation.original.description': 'मूल विवरण:',
    'workshop.translation.original.cover': 'मूल कवर',
    'workshop.translation.original.tags': 'मूल ट्यागहरू',
    'workshop.cover.alt': 'कवर छवि',
    'workshop.translation.updatedOrig': 'मूलको अन्तिम अद्यावधिक: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'अनुवादको अन्तिम अद्यावधिक: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'मूलको अन्तिम संशोधन {revision, number}, : {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'अनुवादको अन्तिम संशोधन {revision, number}, : {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `थप {type, select,
    collaborator {सहकर्मी}
    beta {बेटा पाठक}
    translator {अनुवादक}
    other {}
  }थप्न तपाईंले आफ्नो सदस्यता तह बढाउनुपर्छ।`,
    'workshop.collaborators.requests.sent': 'पठाउनुभयो अनुरोधहरू',
    'workshop.collaborators.requests.invite': `तपाईंलाई निम्नलिखितको लागि {role, select,
    beta {बेटा पाठक}
    translator {अनुवादक}
    collaborator {सहकर्मी}
    other {}
  } बन्न आमन्त्रित गरिएको छ:`,
    'workshop.collaborators.requests.dashboard': `तपाईंलाई {count, plural,
    zero {काम}
    one {एक साहित्यिक काम}
    other {# साहित्यिक कामहरू}
  }मा सहभागिता गर्नका लागि आमंत्रित गरिएको छ।`,
    'workshop.collaborators.language.added': 'भाषा थपियो',
    'workshop.story.noChaptersFound': 'कुनै अध्यायहरू फेला परेनन्।',
    'workshop.fanfic.needUniverseInLibrary': 'त्यहाँ धेरै ब्रह्माण्डहरू छन्। कृपया तपाईंको पुस्तकालयमा लेख्न चाहानुभएका विषयहरूलाई पहिले थप्नुहोस् भनेर हामी तिनीहरूलाई खोज्न सक्ने छौं।',
    'workshop.fanfic.findUniverse': 'एक अद्भुत ब्रह्माण्ड खोज्नुहोस्!',
    'workshop.encSettings': 'विकिपीडिया सेटिङहरू',
    'workshop.collaborators.removeUser': 'प्रयोगकर्ता हटाउनुहोस्',
    'workshop.collaborators.cancelInvite': 'निम्ताहरू रद्द गर्नुहोस्',
    'workshop.universe.createFirstStory': 'पहिलो कथा सिर्जना गर्नुहोस्',
    'workshop.storylines': 'कथाको रेखाचित्रहरू',
    'workshop.scenesManager': 'दृश्य प्रबन्धक',
    'workshop.collaborators.addRoleForLang': '{language}का लागि {role} थप्नुहोस्',
    'workshop.beta.revisionInfo': 'यो पुनरावलोकन {revision, number}, {createdAt, date, long}मा सिर्जना गरिएको हो।',
    'workshop.story.notes.title': 'तपाईंको {storyTitle}को लागि नोटहरू',
    'workshop.story.notes.desc': 'कथाको माथिल्लो नोटहरू।',
    'workshop.story.notes.tile': 'माथिल्लो नोटहरू',
    'workshop.story.alternateFormats.tile': 'Alternate formats',
    'workshop.story.alternateFormats.title': '{storyTitle}: Alternate formats',
    'workshop.story.alternateFormats.arcs.title': 'Arcs',
    'workshop.story.alternateFormats.arcs.add': 'Add arc',
    'workshop.story.alternateFormats.arc.defaultTitle': 'Arc {index}',
    'workshop.story.alternateFormats.arc.name': 'Arc name',
    'workshop.story.alternateFormats.arc.from': 'From chapter',
    'workshop.story.alternateFormats.arc.to': 'To chapter',
    'workshop.story.alternateFormats.arc.uploads': 'Files',
    'workshop.story.alternateFormats.arc.upload.epub': 'Upload EPUB',
    'workshop.story.alternateFormats.arc.upload.pdf': 'Upload PDF',
    'workshop.story.alternateFormats.fullStory.title': 'Full story file',
    'workshop.story.alternateFormats.ongoingAccess.title': 'Ongoing access',
    'workshop.story.alternateFormats.ongoingAccess.allAvailable': 'All currently available chapters',
    'workshop.story.alternateFormats.ongoingAccess.perChapter': 'Per chapter (as chapters are released)',
    'workshop.hideOrgs': 'संगठनहरूबाट सामग्री लुकाउनुहोस्',
    'workshop.translation.premium': 'अनुवादहरू थप्नका लागि, तपाईंलाई कम्तिमा एक्सप्लोरर सदस्यता हुनुपर्छ।',
    'workshop.story.finished': 'कथा पूरा भएको छ',
    'workshop.story.publishing.externalSellingNotice': 'कृपया लिटररी यूनिभर्सबाट बाहिर बेच्नुहुन्छ भने कथा अब प्रकाशित गर्न सक्नुहुनेछ। तपाईंको दुकान लिस्टिंगका लिंकहरू कथामा वा यहाँ प्रकाशित गरिएको हालको कथामा देखाईनेछन्।',
    'workshop.sharing.publicURL': 'सार्वजनिक संस्करण',
    'workshop.fictionalTime.title': '{universeName}का लागि काल्पनिक समयहरू',
    'workshop.fictionalTime.none': 'तपाईंले हालसम्म कुनै काल्पनिक समय सेट गर्नुभएको छैन।',
    'workshop.fictionalTime.createNow': 'अब एक बनाउनुहोस्!',
    'workshop.fictionalTime.createTitle': 'नयाँ काल्पनिक समय बनाउनुहोस्',
    'workshop.fictionalTime.editTitle': 'सम्पादन गर्नुहोस् {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'समयको नाम',
    'workshop.fictionalTime.basicInfo': 'मूलभूत जानकारी',
    'workshop.fictionalTime.timeSetup': 'समय सेट गर्नुहोस्',
    'workshop.fictionalTime.linkedToET': 'के यो समयलाई पृथ्वीको मिति (ग्रिगोरियन क्यालेण्डर) बाट सुरु हुन्छ?',
    'workshop.fictionalTime.timeDeclaration': 'समयको घोषणा',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'इकाईहरू अघि',
    'workshop.fictionalTime.declarationAfter': 'इकाईहरू पछि',
    'workshop.fictionalTime.declarationNone': 'कुनै पनि',
    'workshop.fictionalTime.units': 'इकाईहरू',
    'workshop.fictionalTime.ETStart': 'यो समयको सुरु मिति',
    'workshop.fictionalTime.unitsDescFirst': 'यस इकाईमा मिलिसेकेन्डबाट कति इकाईहरू छन्?',
    'workshop.fictionalTime.unitsDesc': 'यस एकमा अघिको एकबाट कति इकाईहरू छन्?',
    'workshop.fictionalTime.unitsName': 'इकाईको नाम',
    'workshop.fictionalTime.unitsSeparator': 'अघिको इकाईबाट विभाजक',
    'workshop.fictionalTime.unitAdd': 'एकक थप्नुहोस्',
    'workshop.fictionalTime.clocks': 'घडीहरू',
    'workshop.fictionalTime.unitTransfer': 'एकक स्थानान्तरण गर्नुहोस्',
    'fictionalTime.pageStartElapsedTime': 'यस पृष्ठ खोल्दा बितेको समय',
    'fictionalTime.currentTime': 'हालको समय',
    'workshop.shoppingExternal.options': 'बाह्य खरिद विकल्पहरू',
    'workshop.shoppingExternal.explainer': 'यदि तपाईंको कथा अरुको साथमा बिक्रि भएको छ भने तपाईं यहाँ लिंकहरू सेट गर्न सक्नुहुनेछ। त्यसपछि लिंकहरू सामग्रीको स्थानमा वा सामग्रीको अन्तमा देखाइनेछ।',
    'workshop.shoppingExternal.amazonStore': 'अमेजन स्टोर',
    'workshop.shoppingExternal.amazon': 'अमेजन',
    'workshop.shoppingExternal.storeName': 'स्टोर नाम',
    'workshop.shoppingExternal.itemUrl': 'वस्तु URL',
    'workshop.shoppingExternal.storesOther': 'अन्य स्टोरहरू',
    'fictionalTime.units.milliseconds': '{units, number} मिलिसेकेण्ड',
    'fictionalTime.countdownToStart': 'समय सुरु हुने गणना',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 दिन }
      other {{days} दिनहरू }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {सेकेण्ड}
      other {सेकेण्ड}
    }}
    minutes {{units, plural,
      one {मिनेट}
      other {मिनेट}
    }}
    hours {{units, plural,
      one {घण्टा}
      other {घण्टा}
    }}
    days {{units, plural,
      one {दिन}
      other {दिन}
    }}
    years {{units, plural,
      one {वर्ष}
      other {वर्ष}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'बाट',
    'fictionalTime.inputSelectTimeUnit': 'समय इकाई चयन गर्नुहोस्',
    'fictionalTime.inputSelectETUnit': 'पृथ्वीको समय इकाई चयन गर्नुहोस्',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'साइडबार टुलबक्स',
    'workshop.writerSidebar.description': 'तपाईंको कथामा स्वागत छ! यो साइडबारले तपाईंलाई तपाईंको कथासँग सम्बन्धित सबै स्रोतहरूमा सजिलो पहुँच प्रदान गर्दछ। नवीनतम टिप्पणीहरू, तपाईंको नोटहरू र अरू धेरै कुराहरू हेर्न यसको माथि रहेका चिन्हहरू जाँच गर्नुहोस्!',
    'workshop.story.authorsNotesExplained': 'तपाईंको नोटहरू चरणको सुरुमा पढ्न गर्ने पाठकहरूको लागि।',
    'workshop.story.chapterSortSwitch': 'अध्यायको क्रम परिवर्तन गर्नुहोस्',
    'workshop.story.prolog': 'प्रोलोग',
    'workshop.story.chapter': 'अध्याय {sequence, number}',
    'workshop.work.includesAds': 'के कुनै विज्ञापन वा उत्पादन स्थानको प्रयोग छ गर्दैछ?',
    'workshop.universe.forumSettings': 'आन्तरिक ब्रह्माण्ड फोरम सेटिङहरू',
    'workshop.ratingAdjusted': 'उपभोक्ताहरूको उद्धार गर्नका लागि हामीले तपाईंको रेटिंगलाई उचित महसुस गर्दा हामीले रेटिंग परिवर्तन गर्ने अस्थायी गरेका छौं। त्यस्तैले रेटिंग परिवर्तन अब अक्षम भएको छ।',
    'workshop.rating.disabled.sexualContent': 'Rating is locked to Explicit (21+) because you selected Sexual Content in content warnings.',
    'workshop.contentWarnings.title': 'Content Warnings',
    'workshop.contentWarnings.description': 'Select applicable content warnings to inform readers about potentially sensitive content',
    'workshop.contentWarnings.graphicViolence': 'Graphic Violence',
    'workshop.contentWarnings.graphicViolence.description': 'Detailed descriptions of violent acts, including but not limited to physical harm, bloodshed, mutilation, or any other explicit depictions of violence that may be considered disturbing or excessively graphic.',
    'workshop.contentWarnings.profanity': 'Profanity',
    'workshop.contentWarnings.profanity.description': 'Excessive or obscene swearing and cursing.',
    'workshop.contentWarnings.sensitiveContent': 'Sensitive Content',
    'workshop.contentWarnings.sensitiveContent.description': 'Descriptions of torture, slavery, substance abuse, mental illness, addiction, mentions of rape, self-harm or any other content that may be considered traumatizing or mature that does not fall under the warning tags. This content is not glorified.',
    'workshop.contentWarnings.sexualContent': 'Sexual Content',
    'workshop.contentWarnings.sexualContent.description': 'Explicit sexual content (text only), descriptive sex scenes. This will automatically set the rating to Explicit (21+).',
    'workshop.selectCollaborator': 'सहकारी छान्नुहोस्',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'प्रारूप',
    'workshop.chapterStatus.scheduled': 'नियोजित',
    'workshop.chapterStatus.published': 'प्रकाशित',
    'workshop.story.continuedIn': 'कुन कथाहरू यस कथामा जारी छन्?',
    'workshop.story.continuedPlaceholder': 'यस ब्रह्माण्डबाट कथा छान्नुहोस्',
    'workshop.universe.isAIGenerated': 'के यस ब्रह्माण्डको सामग्री AI द्वारा उत्पन्न गरिएको हो?',
    'workshop.universe.isAIGeneratedTooltip': 'कृपया हामीलाई जानकारी दिनुहोस् यदि ब्रह्माण्डको कुनै पनि सामग्री AI द्वारा उत्पन्न गरिएको वा सहयोग गरी उत्पन्न गरिएको छ। हामी यस जानकारीलाई उचित लेबलिङ र कारणको लागि प्रयोग गर्छौं र AI कार्यक्रमहरू कसरी उत्पन्न हुन्छन् त्यसको कुनै सीमा र प्रतिबन्धहरू हुन सक्छन्।',
    'workshop.story.isAIGenerated': 'के कथा AI द्वारा उत्पन्न गरिएको हो?',
    'workshop.story.isAIGeneratedTooltip': 'कृपया हामीलाई जानकारी दिनुहोस् यदि कथाको कुनै पनि भाग AI द्वारा उत्पन्न गरिएको वा सहयोग गरी उत्पन्न गरिएको छ। हामी यस जानकारीलाई उचित लेबलिङ र कारणको लागि प्रयोग गर्छौं र AI कार्यक्रमहरू कसरी उत्पन्न हुन्छन् त्यसको कुनै सीमा र प्रतिबन्धहरू हुन सक्छन्।',
    'workshop.publicationAgreement.aria': 'कामका लागि प्रकाशन सम्झौता',
    'workshop.publicationAgreement.intro': 'हामीले तपाईंलाई तपाईंको सृजनात्मक कामलाई हामीसँग प्रकाशित गर्न चयन गर्नुभयो भनेर हामी खुशी छौं। अघि बढ्नु अघि हामीले केही कानूनी दिशानिर्देशनका बारेमा जान्न चाहन्छौं।',
    'workshop.sortChapters': 'क्रमबद्ध गर्नुहोस्:',
    'workshop.sortChapters.ascending': 'सुरुबाटै',
    'workshop.sortChapters.descending': 'नवीनतम बाट',
    'workshop.sortChapters.aria': 'अध्याय सूची बढाउने तरिकामा छान्नुहोस्',
    'workshop.hiatus.btn': 'कथा स्थिति बदल्नुहोस् हायाटसमा',
    'workshop.cancelled.btn': 'कथा स्थिति बदल्नुहोस् रद्द गरिएकोमा',
    'workshop.complete.btn': 'कथा स्थिति बदल्नुहोस् सम्पन्न गरिएकोमा',
    'workshop.statusChange.modalTop': 'के तपाईं निश्चित हुन चाहानुहुन्छ कि स्थिति बदल्न चाहानुहुन्छ',
    'workshop.statusName.hiatus': 'हायाटस',
    'workshop.statusName.cancelled': 'रद्द गरिएको',
    'workshop.statusName.completed': 'पूरा गरिएको',
    'workshop.statusExplain.hiatus1': 'हायाटस भनेको तपाईंले यस कथामा काम गर्न धेरै छोड्न चाहानुभएको हो। यसले तपाईंको पाठकहरूलाई बताउनेछ कि उनीहरूले आउने हप्तामा वा केही महिनामा नयाँ अपडेटहरू अपेक्षा नगर्नुहुनेछ।',
    'workshop.statusExplain.hiatus2': 'हायाटस स्थिति स्वतःले उठाइनेछ यदि तपाईं कुनै अध्याय प्रकाशित गर्नुहुन्छ। वा तपाईं स्वयं यसलाई बदल्न सक्नुहुनेछ।',
    'workshop.statusExplain.hiatus3': 'यदि तपाईं आफ्नो कथालाई हायाटसमा छ र छह महिनासम्म राख्नुहुनेछ भने, हामी यस कथालाई स्वतः रद्द गर्नेछौं।',
    'workshop.statusExplain.cancelled1': 'कथामा काम गर्न सक्न नपाउनुलाई हेरेर हामी दुखी छौं। अरु तर्फ तपाईंले आफ्ना पाठकहरूलाई जानकारी दिन तत्पर रहँदा हामी खुशी छौं।',
    'workshop.statusExplain.cancelled2': 'कथा रद्द गर्ने तपाईंको पाठकहरूलाई जानकारी दिनेछ कि उनीहरूले नयाँ अपडेटहरूको अपेक्षा नगर्नुहुनेछ।',
    'workshop.statusExplain.cancelled3': 'तपाईं सधैं यसलाई पूर्ववत प्रकाशित गर्न सक्नुहुनेछ वा स्थिति बदल्नुहुनेछ।',
    'workshop.statusExplain.finished1': 'बधाई छ! त्यसो कठिन कामपछि तपाईंले अविश्वसनीय यात्राको अन्तिममा पुगे हो। कथा यहाँ समाप्त भएको छ, हामी आशा गर्दछौं कि भविष्यमा थप कथाहरू भन्ने कुराहरू छन्, तर हामीलाई अहिले सुस्ती लिनुहोस् र आनन्द गर्नुहोस्।',
    'workshop.statusExplain.finished2': 'कथालाई पूर्ण रूपमा चिन्हाउने तपाईंको पाठकहरूलाई जानकारी दिनेछ कि कथा समाप्त भएको छ। यदि तपाईं कुनै नयाँ अध्याय थप्नु नपर्नुहुनेछ तर हामी तपाईंलाई रोक्ने छैनौं र विशेष अध्यायहरू थप्ने कुरा पनि बिग्रिन्छौं, जस्तै सबै पात्रहरूका लागि थप इपिलोगहरू थप्ने र अरु केही विशेष अध्यायहरू थप्ने कुरा नै खराब विचार होइन।',
    'workshop.statusExplain.finished3': 'तपाईं यस स्थितिलाई पूर्ववत रद्द गर्न सक्नुहुन्छ तर हामी यसलाई अत्यावश्यक विचार विरुद्ध सल्लाह दिन्छौं। यदि कथा जारी रहने छ भने नयाँ कथा सुरु गर्न सजिलो हुन सक्छ।',
    'workshop.status.goActive': 'कथा फेरि सक्रिय गर्नुहोस्',
    'workshop.statusChangeEmail.storyIntro': 'हामी तपाईंलाई जानकारी दिन चाहान्छौं कि तपाईंको कथा:',
    'workshop.statusChangeEmail.hiatusTitle': 'तपाईंको कथा स्थिति स्वचालित रूपमा हायटसमा सेट गरियो',
    'workshop.statusChangeEmail.hiatusIntro': 'निष्क्रियताको कारणले तपाईंको कथा स्थिति स्वचालित रूपमा हायटसमा सेट गरियो।',
    'workshop.statusChangeEmail.hiatusWhy': '6 महिनाभन्दा बढी समयसम्म कुनै नयाँ अध्याय प्रकाशित नभएकोको कारणले स्वचालित रूपमा हायटसमा राखिएको छ।',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'यदि तपाईं नयाँ अध्याय प्रकाशित गर्नुहुन्छ भने यो स्थिति स्वचालित रूपमा उठाइनेछ। यदि तपाईं आउँदो 6 महिनामा कुनै नयाँ अध्याय प्रकाशित नगर्नुहुन्छ भने हामी कथालाई स्वचालित रूपमा रद्द गर्नेछौं।',
    'workshop.statusChangeEmail.cancellationIntro': 'तपाईंको कथा स्थिति स्वचालित रूपमा रद्द गरियो।',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'यदि तपाईं यो कथा अझै काम गर्न नचाहानुहुन्छ भने अरु केहि गर्नुपर्छैन।',
    'workshop.startCreating': 'सिर्जना गर्नुहोस्',
    'workshop.ownWork': 'आफ्नो काम',
    'workshop.list.thumbs': 'थंबनेलहरूको सूची',
    'workshop.list.list': 'संक्षेप सूची',
    'workshop.fanfiction.new': 'नयाँ फ्यान फिक्शन सिर्जना गर्नुहोस्',
    'workshop.videoTrailerLink': 'भिडियो ट्रेलर लिंक',
    'workshop.videoTrailerPlayerTitle': 'कथा भिडियो ट्रेलर प्लेयर',
    'workshop.videoTrailer.supportedPlaftorms': 'हामीले Youtube, Vimeo र Odysee समर्थन गर्दछौं',
    'workshop.videoTrailer.rumble': 'हामीले रम्बललाई पनि समर्थन गर्दछौं, तर याद गर्नुहोस् कि आइफ्रेम URL कोपी गर्नुहोस्।',
    'workshop.videoTrailer.suggestPlatforms': 'तपाईंको भिडियो प्लेटफर्म छुट्टै छ, हामीलाई हाम्रो <a>प्रतिक्रिया</a>द्वारा जानकारी दिनुहोस्!',
    'workshop.cover.edit': 'Change cover',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    // Chapter deletion
    'workshop.chapter.delete.modalAria': 'Confirmation modal for deleting a chapter',
    'workshop.chapter.delete.confirm': 'Delete Chapter',
    'workshop.chapter.delete.warning': 'Are you sure you want to delete "{title}"? This action cannot be undone.',
    'workshop.chapter.delete.button': 'Delete Chapter',
    'workshop.chapter.delete.deleting': 'Deleting...',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.',
    'workshop.timer.settings': 'Timer Settings',
    'workshop.timer': 'Timer',
    'workshop.timer.type': 'Type',
    'workshop.timer.timer': 'Timer',
    'workshop.timer.countdown': 'Countdown',
    'workshop.timer.pomodoro': 'Pomodoro',
    'workshop.timer.mode': 'Mode',
    'workshop.timer.regular': 'Regular',
    'workshop.timer.improved': 'Improved',
    'workshop.timer.duration': 'Duration (min)',
    'workshop.timer.workDuration': 'Work (min)',
    'workshop.timer.breakDuration': 'Break (min)',
    'workshop.timer.breakType': 'Break Type',
    'workshop.timer.softBreak': 'Soft Break',
    'workshop.timer.hardBreak': 'Hard Break',
    'workshop.timer.break': 'Break',
    'workshop.timer.breakTime': 'Break Time!',
    'workshop.timer.breakMessage': 'Take a moment to rest. Click anywhere to dismiss.',
    'workshop.timer.pause': 'Pause',
    'workshop.timer.resume': 'Resume',
    'workshop.timer.stop': 'Stop',
    'workshop.timer.start': 'Start',
    'workshop.timer.tabInactive': 'Timer paused - switch back to tab to continue',
    // Timer descriptions
    'workshop.timer.type.timer.desc': 'Simple stopwatch that starts at 0:00 and counts upward. Perfect for tracking total writing time in a session or seeing how long you\'ve been working continuously. Never ends automatically - you control when to stop.',
    'workshop.timer.type.countdown.desc': 'Countdown timer that starts from your set duration and counts down to zero. Great for time-boxed writing sessions, word sprints, or when you want to work for a specific amount of time before taking a break.',
    'workshop.timer.type.pomodoro.desc': 'Structured productivity technique: 25-minute focused work sessions alternating with 5-minute breaks. After 4 cycles, takes a longer 15-30 minute break. Scientifically proven to improve focus and prevent burnout.',
    'workshop.timer.mode.regular.desc': 'Timer runs continuously regardless of your activity. Best for disciplined writers who want to track time even when researching, editing, or taking short breaks. Timer keeps going when you switch tabs or stop typing.',
    'workshop.timer.mode.improved.desc': 'Smart timer that automatically pauses when you switch browser tabs. Perfect for focused writing sessions where you want accurate tracking of actual writing time, not total time spent on the page.',
    'workshop.timer.breakType.soft.desc': 'Gentle reminder approach: Shows a small notification when break time starts. You can choose to continue working if you\'re in \'the zone\' or take the break. Good for flexible writers who sometimes need to extend productive sessions.',
    'workshop.timer.breakType.hard.desc': 'Strict enforcement: Displays a full-screen modal that prevents further input until the break timer completes. Forces you to step away from the keyboard. Ideal for writers who struggle with self-discipline or workaholics who need enforced rest periods.',
    'workshop.timer.duration.timer.desc': 'How long you plan to write in this session. Start with 25-50 minutes for focused work, or set longer sessions (2-4 hours) for deep writing days.',
    'workshop.timer.duration.countdown.desc': 'Target writing time before the timer ends. Try 25 minutes for focused sprints, 45-60 minutes for substantial work sessions, or 90 minutes for creative deep dives.',
    'workshop.timer.workDuration.desc': 'Length of focused work sessions. Traditional Pomodoro uses 25 minutes. Try 15-20 minutes if you find it hard to concentrate for longer periods, or 45-50 minutes for experienced writers who can maintain deep focus.',
    'workshop.timer.breakDuration.desc': 'Rest period between work sessions. Standard is 5 minutes for short breaks. Use 10-15 minutes for longer breaks that allow you to step away from your desk, stretch, or get a drink. Every 4th break is automatically longer (2-3x duration).',
    'workshop.llmstxt': 'AI Access',
    'workshop.llmstxt.blocked': 'Blocked - LLMs cannot access your content',
    'workshop.llmstxt.free': 'Free - LLMs can access your content for free',
    'workshop.llmstxt.paid': 'Paid - LLMs can access your content for a fee (coming soon)',
    'workshop.ai.llmstxt.generate': 'Generate LLMs.txt',
    'workshop.ai.llmstxt.generating': 'Generating LLMs.txt...',
    'workshop.ai.llmstxt.download': 'Download LLMs.txt',
    'workshop.ai.llmstxt.title': 'Texts for AI services',
    'workshop.ai.agent.title': 'Assistant',
    'workshop.ai.llmstxt.story-info': 'Story Info LLMs.txt',
    'workshop.ai.llmstxt.full-content': 'Full Content LLMs.txt',
    'workshop.ai.llmstxt.info': 'Info LLMs.txt - Basic information for AI',
    'workshop.ai.llmstxt.infoShort': 'Basic information',
    'workshop.ai.llmstxt.full': 'Content LLMs.txt - Full content for AI',
    'workshop.ai.llmstxt.fullShort': 'Full content'
};