export default {
  'fanManager.settings.for': 'Fecti fanri narwfra',
  'fanManager.allowArtSubmissions': 'Canja fanri ckacei',
  'fanManager.displayFanArt': 'Canja fanri ckapi',
  'fanManager.allowFanStories': 'Canja fanri ckeji',
  'fanManager.displayFanStories': 'Canja fanri ckuku',
  'fanManager.state.aria': 'Binxo fanri ckolmei',
  'fanManager.state.submitted': 'Binxo',
  'fanManager.state.approved': 'Jukpa',
  'fanManager.state.rejected': 'Tosmabru',
  'fanManager.state.hidden': 'Relfuch limfa',
  'fanManager.publicComment': 'Limnazbi se labycreka',
  'fanManager.publicComment.desc': 'Platu worksien nappenzo jau burbeju tu\'a ti po binxo fanri',
  'fanManager.authorComment': 'Burbe vreji',
  'fanManager.authorComment.desc': 'Ti po binxo fanri cu do\'u binxo vreji fe tu\'a ti',
  'fanManager.stateChange.approve': 'Binxo fanri ckolmei',
  'fanManager.stateChange.reject': 'Tosmabru fanri ckolmei',
  'fanManager.stateChange.hide': 'Relfuch fanri ckolmei',
  'fanManager.stateChange.unhide': 'Jansu fanri ckolmei',
  'fanManager.fanFictionNotAllowed': 'Binxo fanri ckeji cu na cuntu tu\'a do nu casnu',
  'fanManager.fanFiction.maxRating': 'Banli di\'a sornai be lo ckeji fanri be do'
};