export default {
    'workshop.title': 'do\'u loi zukte be do',
    'workshop.noneassigned': 'do na se jalge lo ka se jbera',
    'workshop.notavailable': 'ca\'o na\'e bilga',
    'workshop.none': `You currently have no {type, select,
      universe {universe}
      story {story}
      fanfiction {fan fiction}
      other {}
    }. Create one now!`,
    'workshop.collab': 'lo se dunda be loi zukte',
    'workshop.betareadings': 'lo se beta be loi cukta',
    'workshop.translations': '.i lo kensa',
    'workshop.createnew': 'Create new...',
    'workshop.story.standalone': 'Standalone story',
    'workshop.story.standalone.desc': 'This is a standalone story.',
    'workshop.controlpanel': '{name} control panel',
    'workshop.universe.page': 'Universe page',
    'workshop.fictionaltime': 'ckaji temci',
    'workshop.dashboard.name': '{name} dashboard',
    'workshop.stories.in': 'Stories in {universe}',
    'workshop.universe.nostories': 'There are no stories in this universe.',
    'workshop.story.chapter.add': 'New chapter',
    'workshop.universe.new': 'Create a new universe',
    'workshop.universe.publish': 'Publish universe',
    'workshop.universe.publishing.notice': 'If you do not publish the universe, it will be published automatically when the first story connected to the universe is published.',
    'workshop.universe.settings': '{universe} universe settings',
    'workshop.universe.publishedOn': 'This universe has been published on {date, date, long} {date, time, short}',
    'workshop.universe.description': 'Universe description',
    'workshop.settings.title': 'Title',
    'workshop.description': 'Description',
    'workshop.language.primary': 'lo se cusku be lo nu le jecta cu zdani',
    'workshop.publication.options': 'Publication options',
    'workshop.rating': 'General rating',
    'workshop.universe.rating.desc': 'Stories and fanfiction above this rating will be hidden from the universe page listing from anonymous users and users who are not of the appropriate age.',
    'workshop.universe.license': 'Universe license',
    'workshop.universe.genre.pick': 'Select genre for the universe',
    'workshop.story.genre.pick': 'Select genres for the story',
    'workshop.cover': 'Cover',
    'workshop.nothingtosee': 'Nothing to see here...',
    'workshop.story.cannon': 'Canon story',
    'workshop.story.cannon.desc': 'This story is canonical in {universe} universe.',
    'workshop.story.cannon.desc.create': '.i lo kensa cu zbasu lo se cusku be lo si\'o fatci be fi lo kensa {universe}',
    'workshop.story.fanfiction.search': 'Tavla lo cmene be lo kensa (ri\'a lonu ri cu zvati lo do kibro tavla). A poi se jbini cu pilno',
    'workshop.story.error.nogenres': 'lo ka pilno lo se cmima cu jdika lo ka pilno lo se cmima',
    'workshop.story.error.toomanygenres': 'lo ka pilno lo se cmima cu jdika lo ka pilno lo se cmima be fi lo fatci',
    'workshop.story.error.fanfiction.selectuniverse': 'lo ka pilno lo kensa fatci cu pilno lo do fatci',
    'workshop.story.error.tags.toomany': 'lo ka pilno lo se cmima cu jdika lo ka pilno lo se cmima be fi lo fatci',
    'workshop.story.new': 'zbasu lo fatci jdini',
    'workshop.story.publishing.notice': 'lo fatci cu se xamsi lo nu do se xamsi lo se fatci be lo fatci',
    'workshop.settings.edit': 'zbasu lo se finti',
    'workshop.story.publishedOn': 'This story was published on {date, date, long} {date, time, short}',
    'workshop.story.settings': 'fatci se finti',
    'workshop.settings.basic': 'fatci se finti',
    'workshop.settings.genres': '(max 2) lo se cmima',
    'workshop.story.license': 'fatci se finti',
    'workshop.story.settings.universe': 'lo fatci cu se finti lo kensa fatci',
    'workshop.settings.tags': 'cmima',
    'workshop.revision': 'finti',
    'workshop.revisions.title': '{story}: {chapter} se finti <span class="notranslate">2</span>',
    'workshop.revisions.current': 'se finti se jmina',
    'workshop.revisions.new.beta': 'zbasu lo se finti jdini lo se finti se jmina',
    'workshop.revisions.new.public': 'zbasu lo se finti jdini lo se finti se jmina be fi lo fatci',
    'workshop.revisions.toeditor': 'navigi lo finti',
    'workshop.revisions.comments': 'lo se finti be lo finti cu se finti lo se finti be fi lo fatci',
    'workshop.revisions.comments.title': '{story}: {chapter} - se finti {revision} - se finti be fi lo fatci',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {lo te valsi be lo ka jai beta .i}
      readers {lo te valsi be lo ka jai farvi .i}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'I do not have enough information to provide a translation.',
    'workshop.revisions.comments.select': 'Jensen needs to create a revision first.',
    'workshop.collaborators.noresults': 'No results',
    'workshop.collaborators.add.beta': 'Add Beta reader',
    'workshop.collaborators.add.collaborator': 'Add collaborator',
    'workshop.collaborators.add.translator': 'Add translator',
    'workshop.collaborators.language.add': 'Create a new translation',
    'workshop.translations.stories': 'Translations - stories',
    'workshop.translations.universes': 'Translations - universes',
    'workshop.revisions.beta.none': 'No revisions at this time.',
    'reader.asidetoggle': 'Toggle aside information',
    'workshop.translation.original': 'Original:',
    'workshop.translation.original.title': 'Original title:',
    'workshop.translation.original.description': 'Original description:',
    'workshop.translation.original.cover': 'Original cover',
    'workshop.translation.original.tags': 'Original tags',
    'workshop.cover.alt': 'cover image',
    'workshop.translation.updatedOrig': 'Last update of original: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'Last update of translation: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'Last revision {revision, number}, of original: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'Last revision {revision, number}, of translation: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `To add more {type, select,
    collaborator {collaborators}
    beta {beta readers}
    translator {translators}
    other {}
  }, you need to increase your membership tier.`,
    'workshop.collaborators.requests.sent': 'Sent requests',
    'workshop.collaborators.requests.invite': `You have been invited to become {role, select,
    beta {beta reader}
    translator {translator}
    collaborator {collaborator}
    other {}
  } for the following:`,
    'workshop.collaborators.requests.dashboard': `You have been invited to collaborate on {count, plural,
    zero {no work}
    one {one literary work}
    other {# literary works}
  }.`,
    'workshop.collaborators.language.added': 'Language added',
    'workshop.story.noChaptersFound': 'No chapters found.',
    'workshop.fanfic.needUniverseInLibrary': 'There are many universes out there. Please add the ones you want to write in into your library first so that we can find them.',
    'workshop.fanfic.findUniverse': 'Go find an amazing universe!',
    'workshop.encSettings': 'spisa setca',
    'workshop.collaborators.removeUser': 'Remove user',
    'workshop.collaborators.cancelInvite': 'Cancel invite',
    'workshop.universe.createFirstStory': 'Create the first story',
    'workshop.storylines': 'Storylines',
    'workshop.scenesManager': 'Scenes Manager',
    'workshop.collaborators.addRoleForLang': 'Add {role} for {language}',
    'workshop.beta.revisionInfo': 'This is revision {revision, number}, created on {createdAt, date, long}.',
    'workshop.story.notes.title': 'Your notes for {storyTitle}',
    'workshop.story.notes.desc': 'Overview notes for the story.',
    'workshop.story.notes.tile': 'Overview notes',
    'workshop.hideOrgs': 'Hide content from organizations',
    'workshop.translation.premium': 'In order to add translations, you need to have at least Explorer subscription.',
    'workshop.story.finished': 'Story is complete',
    'workshop.story.publishing.externalSellingNotice': 'Since you are selling outside of Literary Universe you can publish the story now. Links to your store listing will appear on the story or at the end of the current story you publish here.',
    'workshop.sharing.publicURL': 'Public version',
    'workshop.fictionalTime.title': 'Fictional times for {universeName}',
    'workshop.fictionalTime.none': 'I do not currently have any fictional times set-up.',
    'workshop.fictionalTime.createNow': 'Create one now!',
    'workshop.fictionalTime.createTitle': 'Create a new fictional time',
    'workshop.fictionalTime.editTitle': 'Edit {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'Time name',
    'workshop.fictionalTime.basicInfo': 'Basic information',
    'workshop.fictionalTime.timeSetup': 'Time setup',
    'workshop.fictionalTime.linkedToET': 'Does this time start on an Earth date (Gregorian calendar)?',
    'workshop.fictionalTime.timeDeclaration': 'Time declaration',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'Before units',
    'workshop.fictionalTime.declarationAfter': 'After units',
    'workshop.fictionalTime.declarationNone': 'None',
    'workshop.fictionalTime.units': 'Units',
    'workshop.fictionalTime.ETStart': 'Starting date of this time',
    'workshop.fictionalTime.unitsDescFirst': 'How many units are there in this unit from milliseconds?',
    'workshop.fictionalTime.unitsDesc': 'How many units is this one from the previous one?',
    'workshop.fictionalTime.unitsName': 'Unit name',
    'workshop.fictionalTime.unitsSeparator': 'Separator from previous unit',
    'workshop.fictionalTime.unitAdd': 'Jmina vrici',
    'workshop.fictionalTime.clocks': 'Cmaxru',
    'workshop.fictionalTime.unitTransfer': 'Kavbu vrici',
    'fictionalTime.pageStartElapsedTime': 'Temci ku\'o lafti li\'u',
    'fictionalTime.currentTime': 'Cuxna temci',
    'workshop.shoppingExternal.options': 'Banli vamji vrici',
    'workshop.shoppingExternal.explainer': 'If your story is sold elsewhere you can set the links here. The links will then show instead of the content or at the end of the content you choose to preview.',
    'workshop.shoppingExternal.amazonStore': 'Amazon stor',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Vrici cmene',
    'workshop.shoppingExternal.itemUrl': 'Vrici URL',
    'workshop.shoppingExternal.storesOther': 'Drata vrici',
    'fictionalTime.units.milliseconds': '{units, number} milliseconds',
    'fictionalTime.countdownToStart': 'Temci cu\'o lafti',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 djedi }
      other {{days} djudi }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {sekundi}
      other {sekunde}
    }}
    minutes {{units, plural,
      one {minuti}
      other {minuta}
    }}
    hours {{units, plural,
      one {clite}
      other {clira}
    }}
    days {{units, plural,
      one {djan}
      other {djedi}
    }}
    years {{units, plural,
      one {cmene}
      other {cmeni}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'Jai',
    'fictionalTime.inputSelectTimeUnit': 'Jmina temci vrici',
    'fictionalTime.inputSelectETUnit': 'Jmina terdi temci vrici',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Sidebar Toolbox',
    'workshop.writerSidebar.description': 'Welcome to your story! This sidebar allows you easy access to all resources related to your story. Check the icons above to see latest comments, your notes and much more!',
    'workshop.story.authorsNotesExplained': '.i do se plixau lo nu do tcidu lo notci pe lo jufra le se tcika be lo jufra.',
    'workshop.story.chapterSortSwitch': '.i do se stika lo se tcika be lo jufra',
    'workshop.universe.monetizationTitle': '{title} monetization',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} monetization',
    'workshop.universe.monetizationWebMonetization': 'Web Monetization',
    'workshop.webMonetization.explain': 'Web Monetization will stream payments to you based on how much time user spends on your content. In your profile monetization settings you can set your own payment pointer. Here you can decide on a split with your collaborators who have Web Payment enabled. Literary Universe automatically takes 10%.',
    'workshop.webMonetization.revShare': 'Due to the limitation of Web Monetization probabilistic revenue sharing is used. Probabilistic revenue sharing works by randomly choosing from a list of predefined payment pointers each time a web monetized visitor loads your page. The visitor pays to the chosen pointer until the page is reloaded or closed.',
    'workshop.webMonetization.revShareMore': 'Learn more about Probabilistic Revenue Sharing. We use the same code as on that page.',
    'workshop.story.notEligible.licence': `The story's license does not allow for monetization.`,
    'workshop.universe.notEligible.licence': `The universe's license does not allow for monetization.`,
    'workshop.story.notEligible.fanFiction': 'Fan Fiction stories are not eligible for monetization.',
    'workshop.revShare.mustBe100': 'Share must equal 100%',
    'workshop.revShare.LUCut': 'Literary Universe & payment gate',
    'workshop.revShare.unallocated': 'Unallocated share {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'Undecided',
    'workshop.revShare.origLangCreators': 'Original language creators',
    'workshop.story.prolog': 'Prolog',
    'workshop.story.chapter': 'Chapter {sequence, number}',
    'workshop.work.includesAds': 'Are there any advertisements or product placements in the work?',
    'workshop.universe.forumSettings': 'Jikca be lo se jinsa be lo se ctuca be lo se karni be lo terdi',
    'workshop.universe.forum': 'Jikca be lo se jinsa {universeName} be lo se ctuca be lo se karni be lo terdi',
    'workshop.ratingAdjusted': '.ijanai lo nu mi\'o jinvi lo ka joi lo nu mi\'o zmadu lo ka jinvi lo ka se jalge .i je\'e ku\'i lo se jalge cu se ganse lo ka se zmadu lo ka jinvi',
    'workshop.selectCollaborator': 'co\'o pilno',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'ca\'o',
    'workshop.chapterStatus.scheduled': 'te\'isku',
    'workshop.chapterStatus.published': 'ca\'irgau',
    'workshop.story.continuedIn': 'lo te lisri be\'o jundi ti',
    'workshop.story.continuedPlaceholder': 'co\'o pilno lo te lisri be\'o jundi ti',
    'workshop.universe.isAIGenerated': 'ca\'o se finti lo se zukte be lo AI',
    'workshop.universe.isAIGeneratedTooltip': '.i ko catlu lo nu do finti lo se zukte be lo AI lo te zukte be\'o se finti kei gi\'e jai gau se pluka lo nu zgana fi lo ka catlu lo nu zukte .i mi finti lo te zukte be\'o se finti gi\'e jai gau se pluka lo nu zgana fi lo ka finti lo se zukte be lo AI .i ji lo nu finti lo se zukte be lo AI cu se zmadu lo ka zukte',
    'workshop.story.isAIGenerated': 'ca\'o se finti lo te lisri be\'o se finti kei gi\'e jai gau se pluka lo nu zgana fi lo ka finti lo se zukte be lo AI .i mi finti lo te zukte be\'o se finti gi\'e jai gau se pluka lo nu zgana fi lo ka finti lo se zukte be lo AI .i ji lo nu finti lo se zukte be lo AI cu se zmadu lo ka zukte',
    'workshop.story.isAIGeneratedTooltip': '.i ko catlu lo nu do finti lo se zukte be lo AI lo te zukte be\'o se finti kei gi\'e jai gau se pluka lo nu zgana fi lo ka catlu lo nu zukte .i mi finti lo te zukte be\'o se finti gi\'e jai gau se pluka lo nu zgana fi lo ka finti lo se zukte be lo AI .i ji lo nu finti lo se zukte be lo AI cu se zmadu lo ka zukte',
    'workshop.publicationAgreement.aria': 'lo ka se cinri lo nu zukte cu se cinri lo ka se cinri',
    'workshop.publicationAgreement.intro': 'mi gleki lo nu do pilno lo do se rinka be lo nu do jai se cinri lo do se zukte be\'o se cinri gi\'e jai gau se djica lo nu do zgana lo ka se cinri lo nu zukte lo ka se cinri',
    'workshop.sortChapters': 'lo se zukte be\'o gunma :',
    'workshop.sortChapters.ascending': 'lo se zukte be\'o gunma lo ka se zukte ke\'a',
    'workshop.sortChapters.descending': 'Jai la najnimre',
    'workshop.sortChapters.aria': 'Jai se cinri lo nu jdima lo jalge be lo xadni',
    'workshop.hiatus.btn': 'Jai galfi lo se dunda be lo lisri ku lo ka se finti',
    'workshop.cancelled.btn': 'Jai galfi lo se dunda be lo lisri ku lo ka se nu\'osti',
    'workshop.complete.btn': 'Jai galfi lo se dunda be lo lisri ku lo ka se finti',
    'workshop.statusChange.modalTop': 'co\'a djica lo nu do galfi lo se dunda be lo lisri ku lo ka',
    'workshop.statusName.hiatus': 'Hiatus',
    'workshop.statusName.cancelled': 'Cancelled',
    'workshop.statusName.completed': 'Completed',
    'workshop.statusExplain.hiatus1': 'Hiatus cu se finti lo nu do ba\'o pilno lo se dunda be lo lisri ku lo ka zukte lo ka na za\'o te vecnu lo drata',
    'workshop.statusExplain.hiatus2': 'lo nu se finti lo nu jdima cu se vimcu lo nu do se finti lo se dunda be lo lisri ku lo ka finti lo jalge be lo xadni. pe\'i do pu\'o se finti lo nu jdima lo xadni',
    'workshop.statusExplain.hiatus3': 'ca lo nu do zukte lo se dunda be lo lisri ku lo ka finti lo jalge be lo xadni lo nu jdima lo xadni cu se vimcu',
    'workshop.statusExplain.cancelled1': 'ca\'o se sidju lo nu do na ka\'e zukte lo se dunda be lo lisri ku lo ka finti lo jalge be lo xadni. do ba\'o finti lo nu do se dunda be lo lisri ku lo ka finti lo jalge be lo xadni',
    'workshop.statusExplain.cancelled2': 'lo nu se finti lo nu jdima cu se vimcu lo nu do se finti lo se dunda be lo lisri ku lo ka finti lo jalge be lo xadni',
    'workshop.statusExplain.cancelled3': 'do ba\'o finti lo nu jdima lo xadni. pe\'i do pu\'o finti lo nu jdima lo xadni',
    'workshop.statusExplain.finished1': 'coi do! ca lo nu do ba\'o pilno lo se dunda be lo lisri ku lo ka finti lo jalge be lo xadni cu pu\'o se finti lo nu jdima lo xadni. ca lo nu jdima lo xadni cu se finti lo nu jdima lo xadni cu zukte lo nu jdima lo xadni',
    'workshop.statusExplain.finished2': 'lo nu se finti lo nu jdima lo xadni cu se vimcu lo nu do se finti lo se dunda be lo lisri ku lo ka finti lo jalge be lo xadni. pe\'i do na pu\'o zukte lo nu jdima lo xadni. lo nu se finti lo nu jdima lo xadni cu se finti lo nu jdima lo xadni cu zukte lo nu jdima lo xadni',
    'workshop.statusExplain.finished3': 'ca\'o se sidju lo nu do na ka\'e zukte lo se dunda be lo lisri ku lo ka finti lo jalge be lo xadni. lo nu se finti lo nu jdima lo xadni cu se finti lo nu jdima lo xadni cu zukte lo nu jdima lo xadni',
    'workshop.status.goActive': 'Jai zukte lo ka jdima lo xadni se la\'edi\'u',
    'workshop.statusChangeEmail.storyIntro': 'mi cilre tu\'a do fe tu\'a lo du\'u',
    'workshop.statusChangeEmail.hiatusTitle': 'do se stati be lo du\'u lo du\'u',
    'workshop.statusChangeEmail.hiatusIntro': 'lo du\'u lo du\'u',
    'workshop.statusChangeEmail.hiatusWhy': 'lo du\'u lo du\'u',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'lo du\'u lo du\'u',
    'workshop.statusChangeEmail.cancellationIntro': 'do se stati be lo du\'u',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'lo du\'u lo du\'u',
    'workshop.startCreating': 'raktu creka',
    'workshop.ownWork': 'do\'e gunka',
    'workshop.list.thumbs': 'lo liste be lo nu cilre',
    'workshop.list.list': 'lo liste',
    'workshop.fanfiction.new': 'lo nu creka lo fanva',
    'workshop.videoTrailerLink': 'Link la video trailer',
    'workshop.videoTrailerPlayerTitle': 'Plisoi la video trailer la pelxu',
    'workshop.videoTrailer.supportedPlaftorms': 'mi pu\'o sidju le Youtube, le Vimeo je le Odysee',
    'workshop.videoTrailer.rumble': 'mi\'e la .lojban.',
    'workshop.videoTrailer.suggestPlatforms': 'Cyxu\'o la\'o gy. Is your video platform missing, let us know via our <a>feedback</a>! gy.',
    'workshop.cover.edit': 'Change cover',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.'
};