/**
 * @authors Jan Dvorak
 */
export default {
    siteName: 'ლიტერატურული უნივერსუმი',
    twitterHandle: '@lituniapp',
    'site.description': 'ლიტერატურული სამყარო არის ყოვლისმომცველი პლატფორმა კრეატიული წერისა და გამოცემისთვის, მასშტაბური ისტორიული სამყაროებისთვის.',
    'site.keywords': 'კრეატიული მწერალობა, სამაგიდო, სამაგიდო ფანტასტიკა, მწერალობა, გამოცემა, მოთხოვნა, მოთხოვნები, უნივერსუმი, ვებ ნოველა, ვებნოველი',
    'site.logoAlt': 'ლიტერატურული უნივერსის ლოგო',
    'site.titleTemplate': '{title} | {siteName}',
    mobileMenu: 'მობილური მენიუ',
    'common.signin': 'შესვლა',
    'common.signup': 'რეგისტრაცია',
    'common.signout': 'გამოსვლა',
    'common.dashboard': 'დაფა',
    'common.discovery': 'განხილვა',
    'common.library': 'ბიბლიოთეკა',
    'common.library.own': 'თქვენი ბიბლიოთეკა',
    'common.workshop': 'სამუშაობა',
    'common.pm': 'შეტყობინებები',
    'common.settings': 'პარამეტრები',
    'common.options': 'ოფციები',
    'common.profile': 'პროფილი',
    'common.blog': 'ბლოგი',
    'common.blogs': 'ბლოგები',
    'common.about': 'ჩვენ შესახებ',
    'common.accessdenied': 'წვდომა აკრძალულია',
    'common.accessdenied.msg': 'თქვენ არ გაქვთ წვდომა ამ ადგილზე. თუ უნდა გქვიათ წვდომა აქ, გთხოვთ დაუკავშირდით მფლობელს და უთხარით მას, რომ გადაამოწმოს პარამეტრები.',
    'common.loading': 'იტვირთება...',
    'common.add': 'დამატება',
    'common.save': 'შენახვა',
    'common.email': 'ელ. ფოსტა',
    'common.anonymous': 'ანონიმური',
    'common.soon': 'მომავალია...',
    'common.search': 'ძიება',
    'common.search.do': 'ძიება',
    'common.searching': 'ძიება...',
    'common.report': 'ანგარიში',
    'common.user': 'მომხმარებელი',
    'common.users': 'მომხმარებლები',
    'common.showmore': 'მეტის ჩვენება',
    'common.futurefeature.title': 'მომავალი ფუნქცია',
    'common.futurefeature.text': 'ბოდიშს გიხდით, მაგრამ ამჟამად ეს ფუნქცია ხელმისაწვდომი არ არის. ჩვენ აქტიურად ვმუშაობთ, რომ რაც შეიძლება მალე გახდეს ხელმისაწვდომი.',
    'common.nothingfound': 'ვერაფერი მოიძებნა',
    'common.explore': 'გაიგეთ მეტი',
    'common.by': 'მიერ {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'სკრაჩპედი',
    'common.scratchpad.own': 'შენი სკრაჩპედი',
    'common.news': 'სიახლეები',
    'common.encyclopedia': 'ენციკლოპედია',
    'common.art': 'ხელოვნება',
    'common.story': 'მოთავსება',
    'common.stories': 'მოთავსებები',
    'common.universe': 'უნივერსუმი',
    'common.universes': 'უნივერსუმები',
    'common.unpublished': 'გამოუქვეყნებელი',
    'common.collaborator': 'თანამშრომელი',
    'common.collaborators': 'თანამშრომლები',
    'common.translator': 'თარგმანი',
    'common.translators': 'თარგმანები',
    'common.betareader': 'ბეტა წამომმიდი',
    'common.betareaders': 'ბეტა წამომმიდებლები',
    'common.post': 'პოსტი',
    'common.statistics': 'სტატისტიკა',
    'common.lang.select': 'აირჩიე ენა',
    'common.submit': 'წარდგენა',
    'common.close': 'დახურვა',
    'common.comment': 'კომენტარი',
    'common.comments': 'კომენტარები',
    404: 'გვერდი ვერ მოიძებნა',
    'search.users': 'მომხმარებლების ძებნა',
    'search.user': 'მომხმარების ძებნა',
    'common.help': 'დახმარება',
    'common.or': 'ან',
    'common.account.create': 'ანგარიშის შექმნა',
    'signup.username': 'მომხმარებელი',
    'signup.email': 'შეიყვანეთ თქვენი ელ-ფოსტა',
    'signup.password.label': 'შეიყვანეთ თქვენი პაროლი',
    'signup.password.repeat': 'გაიმეორეთ თქვენი პაროლი',
    'common.password': 'პაროლი',
    'signin.password.forgot': 'პაროლის დაგვიკავშირება?',
    'dashboard.whatsnew': 'რა ახალია',
    'dashboard.blog': 'შენი ბლოგი',
    'common.footer.tagline': 'წერა და წაკითხვა კომპლექსური უნივერსებისთვის გამოყენებადი გახსნათ.',
    'common.footer.plans': 'გეგმები და ფასები',
    'common.legal.tos': 'მომსახურების პირობები',
    'common.legal.community': 'საზოგადოების წესები',
    'common.legal.privacy': 'კონფიდენციალურობის პოლიტიკა',
    'common.legal.copyright': 'ავტორული უფლებები',
    'common.legal.cookies': 'ჩანაწერების შესახებ',
    'cookies.desc': 'ეს ვებსაიტი იყენებს ქუქი-ფაილებს, რათა უზრუნველყოს თქვენთვის საუკეთესო გამოცდილება.',
    'common.legal.versionDisplay': `{type, select,
    tos {მომსახურების პირობები}
    community {საზოგადოების წესები}
    privacy {კონფიდენციალურობის პოლიტიკა}
    copyright {საავტორო უფლებების ხელშეკრულება}
    publishingAgreement {გამოქვეყნების ხელშეკრულება}
    cookies {ქუქი-ფაილების შესახებ}
    other {ხელშეკრულება}
  } ვერსია {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'ახალი ვერსია ({newVersion}) ამ დოკუმენტის გამოყენებაში შემოდის {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} ყველა უფლება დაცულია, ყველა ტექსტი მიერიანი ავტორის მიერ.',
    'premium.only.title': 'არასაკმარისი მემბრის რანგი',
    'premium.only.msg': 'ვწუხვართ, თქვენი მემბრის რანგი არასაკმარისია ამ ფუნქციის მისაწვდომისთვის.',
    'premium.only.join': 'ჩვენ გთავაზობთ რგებლებს ყველასთვის, რათა მიიღოთ საუკეთესო რეზუმე ლიტერატურულ უნივერსუმში.',
    'premium.only.link': 'შეამოწმეთ!',
    'universe.visit': 'მოითხოვეთ უნივერსის გვერდი',
    'common.fanmanager': 'ფან მენეჯერი',
    'common.fanarts': 'ფან ხატები',
    'common.fanfiction': 'ფან ფიქცია',
    'common.fansettings': 'ფან პარამეტრები',
    'story.chapter': 'თემა',
    'story.chapters': 'თემები',
    'story.chapter.withStory': '{story}: {chapter}',
    'story.includeUniverse': 'სათაურში ჩართეთ სამყარო',
    'story.genre': 'ჟანრი',
    'story.genres': 'ჟანრები',
    'story.read': 'წაიკითხე',
    'story.lastUpdate': 'ბოლო განახლება {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'დასრულდა {date, date, medium}.',
    'story.hiatusAt': 'პაუზაზე {date, date, medium}-დან.',
    'story.cancelledAt': 'შეწყდა {date, date, medium}-ზე.',
    'story.comments.for': 'კომენტარები {story} {chapter}.',
    'story.cover.alt': 'ისტორიის გარჩევა {story}.',
    'story.note.fanfiction': 'შენიშვნა: ეს ისტორია არის ფან ფიქცია {universe} უნივერსუმზე.',
    copyrights: 'ავტორული უფლებები',
    'common.challenges': 'თამაშები',
    // for beta only
    'beta.notice': 'კეთილი იყოს თქვენი მობრძანება ლიტერატურულ სამყარო BETA-ში! მოხარულები ვართ გაცნობოთ, რომ ოფიციალურად ვიწყებთ ამ პარასკევს! ვიმედოვნებთ, შემოგვიერთდებით და მხარს დაგვიჭერთ ჩვენი მოგზაურობის ახალი თავის დაწყებაში.',
    'beta.thanks': 'გმადლობთ მხარდაჭერისთვის!',
    'scratchpad.about': 'თქვენი შენიშვნები და იდეები ხელმისაწვდომია ნებისმიერ საიტზე.',
    'common.feedback': 'კავშირი',
    'common.createdOn': 'შეიქმნა {date, date, long}',
    'common.createdOn.title': 'შეიქმნა',
    // account types
    admin: 'ადმინისტრატორი',
    'common.saved': 'შენახულია!',
    'common.saving': 'შენახვა...',
    'common.friends': 'მეგობრები',
    'lang.orig': 'ორიგინალი ენა',
    'lang.orig.plus': 'ორიგინალი ენა - {language}',
    buy: 'შეიძინეთ',
    confirm: 'დაადასტურეთ',
    cancel: 'გაუქმება',
    processing: 'მუშავდება...',
    'common.noData': 'მონაცემები არ არის',
    'error.title': 'მოხდა შეცდომა. ბოდიშს გიხდით შექმნილი უხერხულობისთვის.',
    'error.oops': 'უი! რაღაც სერიოზულად ცუდად წავიდა!',
    'error.apologies': 'ბოდიშს გიხდით შექმნილი უხერხულობისთვის, ჩვენ ყველაფერს გავაკეთებთ, რომ ეს მალე გამოვასწოროთ.',
    'error.400.text': 'შეცდომა 400: {errorMessage}',
    'common.offlineStatus': 'თქვენ ამჟამად არ ხართ ონლაინ.',
    male: 'მამრობითი',
    female: 'ქალი',
    'common.legal.effectiveAt': 'ძალამოსიანი დაწყება {date, date, medium}',
    select: 'გთხოვთ აირჩიოთ',
    'common.statusFailed': 'სერვერთან დაკავშირება ვერ მოხერხდა.',
    'common.statusConnecting': 'სერვერთან დაკავშირების მცდელობა... ({count, number})',
    'common.swUpdate.ready.title': 'Update ready',
    'common.swUpdate.ready.description': 'A new version is ready. You can apply it now.',
    'common.swUpdate.ready.writerDescription': 'A new version is ready. Apply it when you finish your current writing edits.',
    'common.swUpdate.apply': 'Update now',
    'slug.checking': 'მოწმდება...',
    'slug.failed': 'ეს მისამართი უკვე არსებობს.',
    'slug.success': 'ეს მისამართი ხელმისაწვდომია!',
    'notVerified.msg': `თქვენი ანგარიში {option, select,
    email {ელ. ფოსტა}
    wallet {საფულე}
    other {ელ. ფოსტა}
    } არ არის დადასტურებული.`,
    'notVerified.verify': `გთხოვთ დაადასტუროთ თქვენი {option, select,
    email {ელ. ფოსტა}
    wallet {საფულე}
    other {ელ. ფოსტა}
    }.`,
    unknown: 'უცნობი',
    'common.legal.guidelines': 'საზოგადოების წესები',
    'errorLoading.title': 'გვერდის ჩატვირთვისას შეცდომა',
    'errorLoading.explained': 'გვერდის ჩატვირთვისას შეცდომა მოხდა. ბოდიშს გიხდით შექმნილი უხერხულობისთვის. გთხოვთ, კვლავ სცადოთ გვერდზე შესვლა. თუ პრობლემა შენარჩუნდება, გთხოვთ, შეგვატყობინოთ.',
    'errorLoading.retry': 'კვლავ სცადე!',
    'errorLoading.takingLong': 'ეს დიდხანს გრძელდება...',
    'common.title': 'სათაური',
    'common.timelines': 'ქრონოლოგია',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'მონაცემთა დაცვის ზოგადი რეგულაცია',
    'editor.placeholder.link': 'შეიყვანეთ URL...',
    'editor.placeholder.connection': 'ენციკლოპედიური სტატიის ძიება...',
    'editor.saved.beta': 'შექმნილია ახალი რედაქცია ბეტა-მკითხველებისთვის!',
    'editor.saved.public': 'ახალი ვერსია გამოქვეყნდა!',
    goodbyeForever: 'ვწუხვართ, რომ გადიხართ. ჩვენი ბრალი ხომ არ არის? თუ ასეა, გთხოვთ, შეგვატყობინოთ. ნებისმიერ შემთხვევაში, გისურვებთ წარმატებას მომავალ საქმიანობაში და იმედი გვაქვს, კვლავ შევხვდებით! იცოცხლეთ დიდხანს და აყვავდით!',
    'goodbyeForever.feedback': 'გვაცნობეთ, რა შეგვიძლია უკეთ გავაკეთოთ',
    'common.edit': 'რედაქტირება',
    'common.publish': 'გამოქვეყნება',
    'common.publishAt': 'გამოქვეყნების თარიღი და დრო',
    'common.publishNow': 'გამოქვეყნება ახლავე',
    'common.publishLater': 'გამოქვეყნება მოგვიანებით',
    'a11y.user.menu': 'მომხმარებლის მენიუ',
    'a11y.navigation': 'ნავიგაცია',
    'dashboard.profile': 'თქვენი პროფილი',
    'profile.website': 'ჩემი პირადი ვებსაიტი',
    'story.notes.concept': 'კონცეფცია',
    'story.notes.settings': 'ისტორიის გარემო',
    'story.notes.theme': 'თემა',
    'story.notes.impact': 'სასარგებლო შედეგი',
    'story.notes.outcome': 'შედეგი',
    'story.notes.audience': 'სამიზნე აუდიტორია',
    'story.notes.pitch': 'პირსახოცა',
    'story.notes.notes': 'შენიშვნები',
    'story.authorsNotes': 'ავტორის შინაარსი',
    'story.notes.audienceAgeGroup': 'სამიზნე აუდიტორიის ასაკობრივი ჯგუფი',
    'story.notes.audienceSex': 'სამიზნე აუდიტორიის სქესი',
    'common.members': 'წევრები',
    'common.language': 'ენა',
    next: 'შემდეგი',
    previous: 'წინა',
    'common.legal.tos.short': 'პირობები',
    'common.legal.privacy.short': 'კონფიდენციალურობა',
    'premium.increaseLimit': 'გაანალიზეთ განახლებისთვის, რათა გაზარდოთ თქვენი ლიმიტი.',
    'common.sharing': 'გაზიარება',
    'story.isbn': 'ISBN',
    'common.name': 'სახელი',
    'common.remove': 'წაშლა',
    'common.time.milliseconds': 'მილიწამები',
    'common.time.seconds': 'წამები',
    'common.time.minutes': 'წუთები',
    'common.time.hours': 'საათები',
    'common.time.days': 'დღეები',
    'common.time.weeks': 'კვირები',
    'common.time.months': 'თვეები',
    'common.time.years': 'წლები',
    'common.monetization': 'მონეტიზაცია',
    'common.tab.monetizationOptions': 'მონეტიზაციის ვარიანტები',
    'common.pagination': 'გვერდების განყოფილება',
    'common.forum': 'ფორუმი',
    'common.2faCode': '2FA კოდი',
    'common.2faCodeIntro': 'გთხოვთ შეიყვანოთ ერთჯერადი კოდი, რომელიც გენერირდება თქვენს აუტენტიფიკატორის აპლიკაციის მიერ.',
    'common.2faCodeAria': '2FA კოდის შესვლის ფორმა',
    'common.aiContent.model.label': 'ხელოვნური ინტელექტის მოდელი',
    'common.aiContent.model.tooltip': 'აირჩიეთ ხელოვნური ინტელექტის მოდელი, რომელიც გამოყენებულ იქნა კონტენტის გენერირებისთვის',
    'common.other': 'სხვა',
    'common.aiContent.model.custom.label': 'ინდივიდუალური ხელოვნური ინტელექტის მოდელი',
    'common.aiContent.model.custom.placeholder': 'შეიყვანეთ ხელოვნური ინტელექტის მოდელის სახელი',
    'common.select': 'აირჩიეთ...',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'ნაგულისხმევი ენა',
    'signin.web3.signMessage': 'გთხოვთ დაადასტუროთ, რომ გსურთ შესვლა ლიტერატურულ უნივერსუმში თქვენი საფულით. კოდი: {code}',
    'common.web3.confirmationCode': 'დადასტურების კოდი: {code}',
    'common.roadmap': 'გზავნილი',
    'common.luStatsIFrameOptOut': 'ლიტერატურული უნივერსიტეტის სტატისტიკის გამორთვა',
    'common.image': 'სურათი',
    'common.home': 'მთავარი',
    'common.administration': 'ადმინისტრაცია',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'ჯგუფები',
    'common.upload': 'ატვირთვა',
    'common.backToDashboard': 'დაბრუნება დაფაზე',
    'common.accept': 'მიღება',
    'common.reject': 'უარყოფა',
    'common.events': 'მოვლენები',
    'common.event': 'ღონისძიება',
    'common.all': 'ყველა',
    'common.social': 'სოციალური',
    'common.discordCommunity': 'Discord თანამშრომლობა',
    'common.account': 'ანგარიში',
    'common.notifications': 'შეტყობინებები',
    'common.byDeclaration': 'ავტორი:',
    'common.done': 'შესრულებულია',
    'contentSelector.noSelection': 'არჩეული არ არის არცერთი ნივთი',
    'contentSelector.selectedItems': 'რჩეული ნივთები',
    'contentSelector.entireSite': 'საიტის ძიება',
    'contentSelector.tabsLabel': 'ძიების პარამეტრები',
    'contentSelector.title': 'არჩეული კონტენტი',
    recommended: 'რეკომენდებული',
    'select.typeToCreate': 'დაწერეთ ტექსტი ახალი ელემენტის შესაქმნელად',
    'select.noSearchResults': 'არაფერია ნაპოვნი “{search}”',
    'select.removeOption': 'ამოიღე {option}',
    create: 'შექმენი',
    'banner.support': 'Literary Universe-ის არსებობა შესაძლებელია თქვენნაირი მომხმარებლების მხარდაჭერის წყალობით. იმისთვის, რომ დაგვეხმაროთ დავრჩეთ დამოუკიდებლები და გავაუმჯობესოთ პლატფორმა, გთხოვთ, განიხილოთ ერთ-ერთი ჩვენი გეგმის გამოწერა.',
    'banner.seePlans': 'დამატებითი ინფორმაციისთვის ეწვიეთ ჩვენი გეგმების გვერდს.',
    'common.noAccountQuestion': 'არ გაქვთ ანგარიში?',
    'common.haveAccountQuestion': 'უკვე გაქვთ ანგარიში?',
    'common.socialLogin': 'შესვლა სხვა სერვისებით',
    'common.viewMore': 'მეტის ნახვა',
    'common.overview': 'მიმოხილვა',
    'common.loggingOut': 'გამოსვლა',
    'common.thankYou': 'გმადლობთ!',
    'common.seeYouAgain': 'ნახვამდის!',
    'email.hello': 'გამარჯობა {username},',
    'common.back': 'უკან',
    'console.stop': 'შეჩერება!',
    'console.explain': 'ეს ბრაუზერის ფუნქციაა, რომელიც დეველოპერებისთვისაა განკუთვნილი. თუ ვინმემ გთხოვათ აქ რაიმეს კოპირება და ჩასმა Literary Universe-ის ფუნქციის გასააქტიურებლად ან ვინმეს ანგარიშზე "ჰაკერული შეღწევისთვის", ეს თაღლითობაა და მათ თქვენს Literary Universe-ის ანგარიშზე წვდომას მისცემთ.',
    'common.coping': 'კოპირება...',
    'common.actions': 'მოქმედებები',
    'common.popular': 'პოპულარული',
    'common.newest': 'ახალი',
    'common.oldest': 'უახლესი',
    'common.noSelection': 'შეურჩევა არაა',
    'common.content': 'შინაარსი',
    'common.theWayOfTheAuthor': 'ავტორის გზა',
    'common.password.hide': 'სიტყვის დამალვა',
    'common.password.show': 'პაროლის ჩვენება',
    'common.forums': 'ფორუმები',
    'common.restriction.goodConduct': 'წესების დარღვევის გამო, ჩვენ შეგიზღუდათ ამ ფუნქციის გამოყენება.',
    'common.continue': 'განაგრძეთ',
    'common.authorName': 'ავტორის სახელი',
    'error.invalidFileType': 'გთხოვთ, აირჩიოთ მოქმედი სურათის ფაილი (JPEG, PNG, GIF, WebP)',
    'error.fileTooLarge': 'სურათის ზომა უნდა იყოს {mbSize, number}მბ-ზე ნაკლები',
    'error.fabricInitFailed': 'გამოსახულების რედაქტორის ინიციალიზაცია ვერ მოხერხდა',
    // File upload strings
    'upload.files': 'გადმოტვირთული ფაილები',
    'upload.dropHere': 'დააგდეთ თქვენი ფაილები აქ...',
    'upload.dragOrClick': 'წარმოაჩინეთ და ჩამოსვით ფაილები აქ, ან დააწკაპუნეთ ფაილების ასარჩევად',
    'upload.maxSize': 'ფაილის მაქსიმალური ზომა: {size}',
    'upload.error.failed': 'ფაილის ატვირთვა ვერ მოხერხდა. გთხოვთ, სცადოთ ხელახლა.',
    'upload.error.tooManyFiles': 'შეგიძლიათ ატვირთოთ მაქსიმუმ {max} -ი ფაილი.',
    'upload.error.removeFile': 'ფაილის წაშლა ვერ მოხერხდა. გთხოვთ, სცადოთ კვლავ.',
    'actions.delete': 'წაშლა',
    'actions.sendToKindle': 'გაგზავნა Kindle-ზე',
    'common.aiContent.indicator': 'ხელოვნური ინტელექტით გენერირებული კონტენტი',
    'common.aiContent.tooltip': 'ეს კონტენტი შექმნილია ხელოვნური ინტელექტის დახმარებით.',
    'common.aiContent.model': 'ხელოვნური ინტელექტის მოდელი: {model}',
    'common.aiContent.custom': 'ინდივიდუალური ხელოვნური ინტელექტის მოდელი',
    'common.characters': 'პერსონაჟები',
    'common.words': 'სიტყვები',
    'common.quickSummary': 'მოკლე შეჯამება',
    'common.creating': 'ქმნის...'
};