export default {
    'stats.age.groups': 'ასაკის ჯგუფები',
    'stats.age.range': 'ასაკის დიაპაზონი',
    'stats.age.to12': 'მდე 12',
    'stats.age.12to17': '12-17',
    'stats.age.18to20': '18-20',
    'stats.age.21to29': '21-29',
    'stats.age.30to39': '30-39',
    'stats.age.40to49': '40-49',
    'stats.age.50to64': '50-64',
    'stats.age.65to84': '65-84',
    'stats.age.above85': '85-ზე მეტი',
    'stats.section.aggregate': 'აგრეგატის სტატისტიკა',
    'stats.section.chapter': 'თავისუფლების სტატისტიკა',
    'stats.readers.title': 'შესახებ წამოღებული წამომღების შესახებ',
    'stats.gender.title': 'სქესი',
    'stats.view.table': 'ცხრილის ხედი',
    'stats.view.pie': 'კრებულის დიაგრამის ხედი',
    'stats.view.bar': 'ზღვრის დიაგრამის ხედი',
    'stats.view.chart': 'დიაგრამის ხედი',
    'stats.table.total': 'ჯამი',
    'stats.timeline.title': 'დროის ხაზი',
    'stats.timeline.dateStart': 'სტატისტიკა დაიწყება',
    'stats.timeline.dateEnd': 'სტატისტიკა დასრულდება',
    'stats.likeCount': 'მოწონებების რაოდენობა',
    'stats.language.title': 'ლექსიკონის ჩანაწერები',
    'stats.chapter.visitorsAndViews': 'სულ მოსახერხებელი მომხმარებელი და ნახვები თავისუფლების მიხედვით',
    'stats.chapter.wordCount': 'სიტყვების რაოდენობა თითო თავისუფლებაში',
    'stats.chapter.chartTooltipViews': `თემა {chapter, number}: {views, number} ნახვები`,
    'stats.chapter.chartTooltipVisitors': `თემა {chapter, number}: {visitors, number} უნიკალური მომსახურებები`,
    'stats.chapter.chartTooltipWordCount': `თემა {chapter, number}: {wordCount, number} სიტყვები`,
    'stats.totalHits': 'სულ ნახვები',
    'stats.totalVisitors': 'სულ უნიკალური მომხმარებელი',
    'stats.totalWords': 'სულ სიტყვები',
    'stats.totalEntries': 'ენციკლოპედიის ჩანაწერები',
    'stats.blogPage': 'გვერდი',
    'stats.blog.typeSelectionAria': 'ტიპის არჩევა',
    'stats.blog.pages': 'გვერდები',
    'stats.blog.posts': 'პოსტები',
    'stats.unknown': 'უცნობი',
    'stats.noData': 'ამ დროს მონაცემები არ არის ხელმისაწვდომი.'
};