export default {
    'workshop.title': 'შენი სამუშაო',
    'workshop.noneassigned': 'შენ ჯერ არ გაქვს მინიმუმ ერთი.',
    'workshop.notavailable': 'ეს ფუნქცია ჯერ არ არის ხელმისაწვდომი.',
    'workshop.none': `ამჟამად თქვენ არ გაქვთ {type, select,
      universe {უნივერსუმის}
      story {მოთავსება}
      fanfiction {ფან-ფიქშენი}
      other {}
    }. შექმენით ახლა!`,
    'workshop.collab': 'თანაშრომლის სამუშაო',
    'workshop.betareadings': 'ბეტა წაკითხვები',
    'workshop.translations': 'თარგმანები',
    'workshop.createnew': 'შექმენით ახალი...',
    'workshop.story.standalone': 'დამოუკიდებელი ამბავი',
    'workshop.story.standalone.desc': 'ეს დამოუკიდებელი ამბავია.',
    'workshop.controlpanel': '{name} მართვის პანელი',
    'workshop.universe.page': 'კოსმოსის გვერდი',
    'workshop.fictionaltime': 'ფიქციური დრო',
    'workshop.dashboard.name': '{name} მართვის პანელი',
    'workshop.stories.in': 'ისტორიები {universe}',
    'workshop.universe.nostories': 'ამ სამყაროში არ არის ისტორიები.',
    'workshop.story.chapter.add': 'ახალი თავი',
    'workshop.universe.new': 'შექმენი ახალი სამყარო',
    'workshop.universe.publish': 'გამოქვეყნება სამყარო',
    'workshop.universe.publishing.notice': 'თუ არ გამოაქვეყნებთ სამყაროს, ის ავტომატურად გამოქვეყნდება, როდესაც სამყაროსთან დაკავშირებული პირველი ისტორია გამოქვეყნდება.',
    'workshop.universe.settings': '{universe} სამყაროს პარამეტრები',
    'workshop.universe.publishedOn': 'ამ უნივერსუმის გამოქვეყნებულია {date, date, long} {date, time, short}',
    'workshop.work.deletion.contactUs': 'If you need help, <contact>contact us</contact>.',
    'workshop.work.delete.restrictions': `You can delete this {type, select,
    universe {universe only if it has no published stories and}
    story {story only if it}
    other {work only if it}} was published less than one month ago. Need help after that? <contact>Contact us</contact>.`,
    'workshop.work.delete.notAllowed': `This {type, select,
    universe {universe}
    story {story}
    other {work}
  } can no longer be deleted through self-service. If you need it removed, <contact>contact us</contact> and we'll work with you to remove it safely.`,
    'workshop.work.delete.notAllowed.plain': `This {type, select,
    universe {universe}
    story {story}
    other {work}
  } can no longer be deleted through self-service. If you need it removed, contact us at deletions@literaryuniverse.com and we'll work with you to remove it safely.`,
    'workshop.work.danger.delete.desc': `Permanently deletes this {type, select,
    universe {universe and linked workshop data}
    story {story with all chapters, statistics, and workshop associations}
    other {work and related data}
  }.`,
    'workshop.work.makePrivate.impact': `Making this {type, select,
    universe {universe}
    story {story}
    other {work}
  } removes it from discovery and search. People who already have it in their library keep access. New users cannot add it to their library anymore{type, select,
    story { or buy it unless you gift it to them}
    other {}
  }.`,
    'workshop.work.private.notice': `This {type, select,
    universe {universe}
    story {story}
    other {work}
  } is currently private. Existing library holders still have access. New users cannot add it to their library{type, select,
    story { or buy it}
    other {}
  }.`,
    'workshop.work.makePrivate.button': `Make {type, select,
    universe {Universe}
    story {Story}
    other {Work}
  } Private`,
    'workshop.work.makePrivate.modalAria': `Confirmation modal for making a {type, select,
    universe {universe}
    story {story}
    other {work}
  } private`,
    'workshop.work.makePrivate.warning': `Making this {type, select,
    universe {universe}
    story {story}
    other {work}
  } private will remove it from public discovery and search.`,
    'workshop.work.makePublic.button': `Make {type, select,
    universe {Universe}
    story {Story}
    other {Work}
  } Public`,
    'workshop.work.makePublic.modalAria': `Confirmation modal for making a {type, select,
    universe {universe}
    story {story}
    other {work}
  } Public`,
    'workshop.work.makePublic.warning': `Making this {type, select,
    universe {universe}
    story {story}
    other {work}
  } public will make it discoverable again and allow new users to add it to their library{type, select,
    story { or buy it}
    other {}
  }.`,
    'workshop.universe.dangerZone': 'Danger zone',
    'workshop.universe.dangerZone.desc': 'You can delete this universe only when it has no published stories and was published less than one month ago. If you need to delete it after this limitation period, please contact us.',
    'workshop.universe.delete.modalAria': 'Confirmation modal for deleting a universe',
    'workshop.universe.delete.warning': 'Are you sure you want to delete "{title}"? This action cannot be undone.',
    'workshop.universe.delete.button': 'Delete Universe',
    'workshop.universe.description': 'კოსმოსის აღწერა',
    'workshop.settings.title': 'სათაური',
    'workshop.description': 'აღწერა',
    'workshop.language.primary': 'პირველადი ენა',
    'workshop.publication.options': 'გამოქვეყნების ვარიანტები',
    'workshop.rating': 'ზოგადი შეფასება',
    'workshop.universe.rating.desc': 'ამ რეიტინგზე მაღალი შეფასების მქონე ისტორიები და ფანფიკციები სამყაროს გვერდზე არსებული სიიდან დამალული იქნება ანონიმური მომხმარებლებისა და შესაბამისი ასაკის არმქონე მომხმარებლებისთვის.',
    'workshop.universe.license': 'საყოველთაო ლიცენზია',
    'workshop.universe.genre.pick': 'აირჩიეთ ჟანრი სამყაროსთვის',
    'workshop.story.genre.pick': 'ისტორიისთვის ჟანრების არჩევა',
    'workshop.cover': 'გარეკანი',
    'workshop.nothingtosee': 'აქ სანახავი არაფერია...',
    'workshop.story.cannon': 'Canon-ის ისტორია',
    'workshop.story.cannon.desc': 'ეს ამბავი კანონიკურია {universe} -ის სამყაროში.',
    'workshop.story.cannon.desc.create': 'ეს ამბავი შეიქმნება, როგორც კანონიკური ამბავი {universe} -ის სამყაროში.',
    'workshop.story.fanfiction.search': 'შეიყვანეთ სამყაროს სახელი (ის თქვენს ბიბლიოთეკაში უნდა იყოს). შემდეგ კი არჩიეთ შემოთავაზებებიდან.',
    'workshop.story.error.nogenres': 'თქვენ უნდა აირჩიოთ სულ მცირე ერთი ჟანრი.',
    'workshop.story.error.toomanygenres': 'თითოეული ისტორიისთვის მხოლოდ ორი ჟანრია დაშვებული.',
    'workshop.story.error.fanfiction.selectuniverse': 'თქვენ უნდა აირჩიოთ ორიგინალური სამყარო თქვენი ფანფიკციისთვის!',
    'workshop.story.error.tags.toomany': 'თითოეულ ამბავს მხოლოდ 10 თეგი შეიძლება ჰქონდეს.',
    'workshop.thema.primary': 'Thema Primary Classification',
    'workshop.thema.secondary': 'Thema Secondary Classifications',
    'workshop.thema.secondary.max': 'You can add up to {max} secondary classifications.',
    'workshop.thema.selectedCode': 'Code: {code}',
    'workshop.thema.searchPlaceholder': 'Search by name, e.g. "Science fiction"',
    'workshop.thema.quickRef': '📖 Thema Quick Reference',
    'workshop.story.new': 'შექმენი ახალი ამბავი',
    'workshop.story.publishing.notice': 'ისტორია ავტომატურად გამოქვეყნდება, როგორც კი პირველ თავს გამოაქვეყნებთ.',
    'workshop.story.published.congratulations.title': 'Congratulations! Your story is published',
    'workshop.story.published.congratulations.heading': 'Congratulations! Your story has been published',
    'workshop.story.published.congratulations.description': 'Your writing journey continues. Your story is now ready to be discovered and enjoyed by readers.',
    'workshop.story.published.congratulations.publicStoryBtn': 'Go to story page',
    'workshop.story.published.congratulations.imageAlt': 'Celebration illustration for published story',
    'workshop.writingHistory.title': 'Writing history',
    'workshop.writingHistory.sessions': 'Writing sessions',
    'workshop.settings.edit': 'პარამეტრების რედაქტირება',
    'workshop.story.publishedOn': 'ამ მოთხრობამ გამოქვეყნებულია {date, date, long} {date, time, short}',
    'workshop.story.settings': 'ისტორიის გარემოებები',
    'workshop.story.monetizationTitle': 'ისტორიის მონეტიზაცია',
    'workshop.settings.basic': 'ძირითადი პარამეტრები',
    'workshop.settings.genres': 'ჟანრები (მაქს. 2)',
    'workshop.story.license': 'ისტორიის ლიცენზია',
    'workshop.story.settings.universe': 'კოსმოსის პარამეტრები',
    'workshop.story.dangerZone': 'Danger zone',
    'workshop.story.dangerZone.desc': 'These actions affect how your story is organized across universes. Proceed carefully.',
    'workshop.story.universe.assign.missing': 'Please select a universe to continue.',
    'workshop.story.universe.assignTitle': 'Create or assign a universe',
    'workshop.story.universe.assign.desc': 'Attach this story to an existing universe, or create a brand-new universe using the story details.',
    'workshop.story.universe.assign.mode': 'Universe option',
    'workshop.story.universe.assign.existing': 'Assign to an existing universe',
    'workshop.story.universe.assign.create': 'Create a new universe from this story',
    'workshop.story.universe.assign.loading': 'Loading your universes...',
    'workshop.story.universe.assign.select': 'Select universe',
    'workshop.story.universe.assign.placeholder': 'Choose a universe',
    'workshop.story.universe.assign.none': 'You do not have any universes yet. Create a new one to continue.',
    'workshop.story.universe.assign.publishNote': 'This story is already published, so the new universe will be published too.',
    'workshop.story.universe.assign.createBtn': 'Create universe',
    'workshop.story.universe.assign.trigger': 'Create or assign a universe',
    'workshop.story.universe.standalone.title': 'Make story standalone',
    'workshop.story.universe.standalone.heading': 'Move this story out of its universe?',
    'workshop.story.universe.standalone.desc': 'This story will be removed from the universe and listed as a standalone story.',
    'workshop.story.universe.standalone.current': 'Current universe: {title}',
    'workshop.story.universe.standalone.warning1': 'Readers browsing the universe will no longer see this story listed there.',
    'workshop.story.universe.standalone.warning2': 'Existing links that point to the universe version of this story may stop working.',
    'workshop.story.universe.standalone.warning3': 'You can attach the story to a universe again later from story settings.',
    'workshop.story.universe.standalone.trigger': 'Make story standalone',
    'workshop.settings.tags': 'თეგები',
    'workshop.settings.tags.placeholder': 'Add a tag…',
    'workshop.revision': 'შესწორება',
    'workshop.revisions.title': '{story}: {chapter} ცვლილებები',
    'workshop.revisions.current': 'მიმდინარე ვერსია',
    'workshop.revisions.new.beta': 'შექმენით ახალი რედაქცია ნახაზიდან.',
    'workshop.revisions.new.public': 'შექმენით ახალი საჯარო რედაქცია შავი ვერსიიდან.',
    'workshop.revisions.toeditor': 'რედაქტორში გადასვლა',
    'workshop.revisions.comments': 'შენიშვნები გადასინჯვაზე',
    'workshop.revisions.comments.title': '{story} {chapter} - რედაქცია {revision} - კომენტარები',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {ბეტა-მკითხველებისთვის}
      readers {საჯარო}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'პირველ რიგში, თქვენ უნდა შექმნათ რევიზია.',
    'workshop.revisions.comments.select': 'აირჩიეთ რევიზია',
    'workshop.collaborators.noresults': 'შედეგები არ არის',
    'workshop.collaborators.add.beta': 'ბეტა წამომღებელის დამატება',
    'workshop.collaborators.add.collaborator': 'თანამშრომლის დამატება',
    'workshop.collaborators.add.translator': 'თარგმანის დამატება',
    'workshop.collaborators.language.add': 'ახალი თარგმანის შექმნა',
    'workshop.translations.stories': 'თარგმანები - მოთხოვნები',
    'workshop.translations.universes': 'თარგმანები - უნივერსები',
    'workshop.revisions.beta.none': 'ამ დროს არ არის რევიზიები.',
    'reader.asidetoggle': 'ინფორმაციის გადართვა/ჩამოსატვირთად მოხდეს',
    'workshop.translation.original': 'ორიგინალი:',
    'workshop.translation.original.title': 'ორიგინალის სათაური:',
    'workshop.translation.original.description': 'ორიგინალის აღწერა:',
    'workshop.translation.original.cover': 'ორიგინალის გარეკანი',
    'workshop.translation.original.tags': 'ორიგინალის ტეგები',
    'workshop.cover.alt': 'გარეკანის სურათი',
    'workshop.translation.updatedOrig': 'ორიგინალის ბოლო განახლება: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'თარგმნის ბოლო განახლება: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'ბოლო რევიზია {revision, number}, ორიგინალის მიხედვით: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'ბოლო რევიზია {revision, number}, თარგმნის მიხედვით: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.monetization.minPriceNotice': 'ფასები ლიცენზიისთვის დამახასიათებელ მინიმუმებთან გადამოწმდება, სანამ მათი შენახვა ან სინქრონიზაცია მოხდება.',
    'workshop.monetization.storyPrices': 'ისტორიების ფასები',
    'workshop.monetization.minPrice': 'მინიმუმი: {price}',
    'workshop.monetization.revenueSplit': 'შემოსავლების განაწილება',
    'workshop.monetization.userId': 'მონაწილის მომხმარებლის ID',
    'workshop.monetization.splitTotal': 'წვლილის გადანაწილება ჯამში: {total}%',
    'workshop.monetization.arcPricing': 'არკის ფასი',
    'workshop.monetization.arcRange': 'თავები {from}–{to}',
    'workshop.monetization.arcEnabled': 'გაყიდეთ ეს კამარა ცალკე',
    'workshop.monetization.saved': 'ფასების პარამეტრები შენახულია.',
    'workshop.monetization.synced': 'Stripe-ის პროდუქტები და ფასები სინქრონიზებულია.',
    'workshop.monetization.syncStripe': 'სინქრონიზაცია Stripe-თან',
    'workshop.monetization.fullStoryUnfinishedWarning': 'You can set a full story price before the story is complete, but the full-story purchase option will not activate until the story is marked as finished.',
    'workshop.collaborators.premium': `რომ დაამატოთ მეტი {type, select,
    collaborator {თანამშრომლისთვის}
    beta {ბეტა წამომიყვანებელი}
    translator {თარგმნელი}
    other {}
  }, უნდა გაზარდოთ თქვენი წევრობის ტიერია.`,
    'workshop.collaborators.requests.sent': 'გაგზავნილი მოთხოვნები',
    'workshop.collaborators.requests.invite': `თქვენ მოგწონთ გახდათ {role, select,
    beta {ბეტა წამომიყვანებელი}
    translator {თარგმნელი}
    collaborator {თანამშრომელი}
    other {}
  } შემდეგისთვის:`,
    'workshop.collaborators.requests.dashboard': `თქვენ მიწვეული ხართ თანამშრომლობისთვის {count, plural,
    zero {არ არის ნამუშევარი}
    one {ერთი ლიტერატურული ნაწარმოები}
    other {# ლიტერატურული ნაწარმოებები}
  }.`,
    'workshop.collaborators.language.added': 'ენა დაემატა',
    'workshop.story.noChaptersFound': 'თავები არ მოიძებნა.',
    'workshop.outliner.title': 'Storylines Outliner – {storyTitle}',
    'workshop.outliner.addScene': 'New scene column name',
    'workshop.outliner.addSceneAction': 'Add scene',
    'workshop.outliner.sceneName': 'Scene name…',
    'workshop.outliner.hideArchived': 'Hide archived',
    'workshop.outliner.showArchived': 'Show archived',
    'workshop.outliner.newStoryline': 'New storyline name…',
    'workshop.outliner.noChapters': 'Use "Plan chapter" to plan your story structure, or write your first chapter in the workshop.',
    'workshop.outliner.noScenes': 'No scenes yet',
    'workshop.outliner.storyline': 'Storyline',
    'workshop.outliner.dragHint': 'წაიღეთ ბარათები სცენებისა და სიუჟეტების ნებისმიერ სვეტებს შორის.',
    'workshop.outliner.editCard': 'Edit outliner card',
    'workshop.outliner.cardDetailsPlaceholder': 'Describe this beat, scene goal, key conflict, and any notes…',
    'workshop.outliner.dragScene': 'დრэг სცენა',
    'workshop.outliner.written': 'Mark as written',
    'workshop.outliner.emptyCard': '(empty)',
    'workshop.outliner.planChapter': 'Plan chapter',
    'workshop.outliner.addChapterHint': 'Create a planning chapter. Once a real chapter exists in your story, it will appear here automatically and this placeholder will be replaced.',
    'workshop.outliner.chapterTitlePlaceholder': 'Chapter title…',
    'workshop.outliner.hypothetical': 'draft',
    'workshop.outliner.deleteChapter': 'Delete planned chapter',
    'workshop.fanfic.needUniverseInLibrary': 'არსებობს უამრავი სამყარო. გთხოვთ, ჯერ დაამატოთ თქვენს ბიბლიოთეკაში ის სამყაროები, რომლებშიც წერის სურვილი გაქვთ, რათა ჩვენ მათ პოვნა შევძლოთ.',
    'workshop.fanfic.findUniverse': 'წადი და იპოვე საოცარი სამყარო!',
    'workshop.encSettings': 'ენციკლოპედიის პარამეტრები',
    'workshop.collaborators.removeUser': 'მომხმარებლის წაშლა',
    'workshop.collaborators.cancelInvite': 'შემოთავაზების გაუქმება',
    'workshop.collaborators.mode.search': 'მომხმარებლების ძიება',
    'workshop.collaborators.mode.email': 'მიწვევა ელფოსტით',
    'workshop.collaborators.sendInvite': 'გამოაგზავნე მოსაწვევი',
    'workshop.collaborators.emailSent': 'მიწვევა გაგზავნილია!',
    'workshop.universe.createFirstStory': 'შექმენი პირველი ამბავი',
    'workshop.storylines': 'სიუჟეტები',
    'workshop.scenesManager': 'სცენების მენეჯერი',
    'workshop.sceneManager.title': 'სცენის მენეჯერი – {storyTitle}',
    'workshop.scene.create': 'შექმენი სცენა',
    'workshop.scene.edit': 'სცენის რედაქტირება',
    'workshop.scene.empty': 'ამ თავისთვის სცენები ჯერ დაგეგმილი არ არის.',
    'workshop.scene.checklist': 'თავის სცენები',
    'workshop.scene.checklist.empty': 'ამ თავს ჯერ არცერთი სცენა არ მიუჩენია.',
    'workshop.scene.title.placeholder': 'სცენის სათაური…',
    'workshop.scene.details': 'სცენის დეტალები',
    'workshop.scene.assignments.hint': 'დააკისრეთ პერსონაჟები და ლოკაციები თქვენი ენციკლოპედიიდან.',
    'workshop.collaborators.addRoleForLang': 'დაამატეთ {role} -თვის {language}',
    'workshop.beta.revisionInfo': 'ეს არის რედაქცია {revision, number}, შექმნილი {createdAt, date, long}-ზე.',
    'workshop.story.notes.title': 'თქვენი ჩანაწერები {storyTitle}',
    'workshop.story.notes.desc': 'ისტორიის მიმოხილვის ჩანაწერები',
    'workshop.story.notes.tile': 'მიმოხილვის შენიშვნები',
    'workshop.story.alternateFormats.tile': 'Alternate formats',
    'workshop.story.alternateFormats.title': '{storyTitle}: Alternate formats',
    'workshop.story.alternateFormats.arcs.title': 'Arcs',
    'workshop.story.alternateFormats.arcs.add': 'Add arc',
    'workshop.story.alternateFormats.arc.defaultTitle': 'Arc {index}',
    'workshop.story.alternateFormats.arc.name': 'Arc name',
    'workshop.story.alternateFormats.arc.from': 'From chapter',
    'workshop.story.alternateFormats.arc.to': 'To chapter',
    'workshop.story.alternateFormats.arc.uploads': 'Files',
    'workshop.story.alternateFormats.arc.upload.epub': 'Upload EPUB',
    'workshop.story.alternateFormats.arc.upload.pdf': 'Upload PDF',
    'workshop.story.alternateFormats.epub.generate': 'Generate EPUB',
    'workshop.story.alternateFormats.epub.openGenerated': 'Open generated EPUB',
    'workshop.story.alternateFormats.epub.generatedAt': 'Generated on {generatedAt, date, medium} at {generatedAt, time, short}',
    'workshop.story.alternateFormats.epub.generationFailed': 'EPUB generation failed.',
    'workshop.story.alternateFormats.epub.saveArcBeforeGeneration': 'Save this arc first to enable EPUB generation.',
    'workshop.story.alternateFormats.fullStory.title': 'Full story file',
    'workshop.story.alternateFormats.ongoingAccess.title': 'Ongoing access',
    'workshop.story.alternateFormats.ongoingAccess.allAvailable': 'All currently available chapters',
    'workshop.story.alternateFormats.ongoingAccess.perChapter': 'Per chapter (as chapters are released)',
    'workshop.hideOrgs': 'ორგანიზაციებისგან შინაარსის დამალვა',
    'workshop.translation.premium': 'თარგმნების დამატებისთვის, საჭიროა მცირე მიმოხილვა.',
    'workshop.story.finished': 'ისტორია დასრულებულია',
    'workshop.story.publishing.externalSellingNotice': 'რადგან თქვენ ყიდით Literary Universe-ის გარეთ, შეგიძლიათ ახლავე გამოაქვეყნოთ მოთხრობა. თქვენი მაღაზიის გვერდის ბმულები გამოჩნდება მოთხრობაზე ან აქ გამოქვეყნებული მოთხრობის ბოლოს.',
    'workshop.shoppingExternal.kobo': 'Rakuten Kobo',
    'workshop.shoppingExternal.koboStore': 'Rakuten Kobo store',
    'workshop.shoppingExternal.koboStoreInternational': 'International storefront',
    'workshop.sharing.publicURL': 'საჯარო ვერსია',
    'workshop.fictionalTime.title': 'ხელოვნური დროისთვის {universeName}',
    'workshop.fictionalTime.none': 'ამჟამად თქვენ არ გაქვთ არანაირი გამოგონილი დრო დაყენებული.',
    'workshop.fictionalTime.createNow': 'შექმენით ახლა!',
    'workshop.fictionalTime.createTitle': 'შექმენი ახალი გამოგონილი დრო',
    'workshop.fictionalTime.editTitle': 'რედაქტირება {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'დროის სახელი',
    'workshop.fictionalTime.basicInfo': 'ძირითადი ინფორმაცია',
    'workshop.fictionalTime.timeSetup': 'დროის დაყენება',
    'workshop.fictionalTime.linkedToET': 'იწყება თუ არა ეს დრო დედამიწის თარიღით (გრიგორიანული კალენდარი)?',
    'workshop.fictionalTime.timeDeclaration': 'დროის დეკლარაცია',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'ერთეულებამდე',
    'workshop.fictionalTime.declarationAfter': 'ერთეულების შემდეგ',
    'workshop.fictionalTime.declarationNone': 'არცერთი',
    'workshop.fictionalTime.units': 'ერთეულები',
    'workshop.fictionalTime.ETStart': 'ამ დროის დაწყების თარიღი',
    'workshop.fictionalTime.unitsDescFirst': 'რამდენი ერთეულია ამ ერთეულში მილიწამებისგან?',
    'workshop.fictionalTime.unitsDesc': 'რამდენი ერთეულით ჩამორჩება ეს წინა ერთეულს?',
    'workshop.fictionalTime.unitsName': 'ერთეულის სახელი',
    'workshop.fictionalTime.unitsSeparator': 'წინა ერთეულისგან გამყოფი',
    'workshop.fictionalTime.unitAdd': 'ერთეულის დამატება',
    'workshop.fictionalTime.clocks': 'საათები',
    'workshop.fictionalTime.unitTransfer': 'ერთეულების გადატანა',
    'fictionalTime.pageStartElapsedTime': 'გვერდის გახსნის შემდეგ გასული დრო',
    'fictionalTime.currentTime': 'მიმდინარე დრო',
    'workshop.shoppingExternal.options': 'გარე შესყიდვების ოფციები',
    'workshop.shoppingExternal.explainer': 'თუ თქვენი ისტორია იყიდება სხვა ადგილას, თქვენ შეგიძლიათ აქ დააყენოთ ბმულები. ბმულები შემავალი კონტენტის ნაცვლად ან კონტენტის ბოლოში გამოჩენაზე გამოჩნდება.',
    'workshop.shoppingExternal.amazonStore': 'Amazon მაღაზია',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'მაღაზის სახელი',
    'workshop.shoppingExternal.itemUrl': 'ნივთის URL',
    'workshop.shoppingExternal.storesOther': 'სხვა მაღაზიები',
    'fictionalTime.units.milliseconds': '{units, number} მილიწამები',
    'fictionalTime.countdownToStart': 'ითვლის დროს განსაწილება',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 დღის }
      other {{days} დღის }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {წამი}
      other {წამი}
    }}
    minutes {{units, plural,
      one {წუთი}
      other {წუთი}
    }}
    hours {{units, plural,
      one {საათი}
      other {საათი}
    }}
    days {{units, plural,
      one {დღე}
      other {დღე}
    }}
    years {{units, plural,
      one {წელი}
      other {წელი}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'დან',
    'fictionalTime.inputSelectTimeUnit': 'დაარჩიე დროს ერთეული',
    'fictionalTime.inputSelectETUnit': 'დაარჩიე მიმდინარე დროის ერთეული',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'სარკეელი ხელსაწყოები',
    'workshop.writerSidebar.description': 'მოგესალმებით თქვენს ამბებზე! ამ სარკეელზე თქვენ მარტივად შეგიძლიათ წვდომა ყველა თქვენს ამბებს შესატყვისი რესურსებისთვის. გადააკეთეთ ზემოთ მითითებული ხატები რომ ნახოთ უახლესი კომენტარები, თქვენი შენიშვნები და სხვა ბევრი!',
    'workshop.story.authorsNotesExplained': 'თქვენი შენიშვნები წამოიყვანს წიგნის დასაწყისში წაკითხვისთვის.',
    'workshop.story.chapterSortSwitch': 'შეცვალეთ თავისუფალიანი თავისი წერტილის მიმდევრობა',
    'workshop.story.prolog': 'პროლოგი',
    'workshop.story.chapter': 'თავი {sequence, number}',
    'workshop.work.includesAds': 'არის თუ არა რეკლამები ან პროდუქტის განთავსებები საქმეში?',
    'workshop.universe.forumSettings': 'ინტერნალური უნივერსიტეტის ფორუმის პარამეტრები',
    'workshop.ratingAdjusted': 'წარდგენილი საჩივრების გამო, ჩვენ მოგვიწია თქვენი შეფასების შესაბამისობაში მოყვანა. შესაბამისად, შეფასების შეცვლის ფუნქცია ახლა გათიშულია.',
    'workshop.rating.disabled.sexualContent': 'Rating is locked to Explicit (21+) because you selected Sexual Content in content warnings.',
    'workshop.contentWarnings.title': 'Content Warnings',
    'workshop.contentWarnings.description': 'Select applicable content warnings to inform readers about potentially sensitive content',
    'workshop.contentWarnings.graphicViolence': 'Graphic Violence',
    'workshop.contentWarnings.graphicViolence.description': 'Detailed descriptions of violent acts, including but not limited to physical harm, bloodshed, mutilation, or any other explicit depictions of violence that may be considered disturbing or excessively graphic.',
    'workshop.contentWarnings.profanity': 'Profanity',
    'workshop.contentWarnings.profanity.description': 'Excessive or obscene swearing and cursing.',
    'workshop.contentWarnings.sensitiveContent': 'Sensitive Content',
    'workshop.contentWarnings.sensitiveContent.description': 'Descriptions of torture, slavery, substance abuse, mental illness, addiction, mentions of rape, self-harm or any other content that may be considered traumatizing or mature that does not fall under the warning tags. This content is not glorified.',
    'workshop.contentWarnings.sexualContent': 'Sexual Content',
    'workshop.contentWarnings.sexualContent.description': 'Explicit sexual content (text only), descriptive sex scenes. This will automatically set the rating to Explicit (21+).',
    'workshop.selectCollaborator': 'შერჩევა კოლაბორატორის',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'მასალა',
    'workshop.chapterStatus.scheduled': 'დაგეგმილი',
    'workshop.chapterStatus.published': 'გამოქვეყნდა',
    'workshop.story.continuedIn': 'რომელი ამბები აგრძელებენ ამ ისტორიას?',
    'workshop.story.continuedPlaceholder': 'აირჩიეთ ამ სამყაროდან ამბავი',
    'workshop.universe.isAIGenerated': 'გენერირებულია თუ არა სამყაროს შინაარსი ხელოვნური ინტელექტის მიერ?',
    'workshop.universe.isAIGeneratedTooltip': 'გთხოვთ, შეგვატყობინოთ, თუ სამყაროში არსებული რაიმე კონტენტი გენერირებულია ან შექმნილია ხელოვნური ინტელექტის დახმარებით. ჩვენ ამ ინფორმაციას ვიყენებთ სათანადო მარკირებისთვის და, იმის გათვალისწინებით, თუ როგორ იქმნება ხელოვნური ინტელექტის პროგრამები, შესაძლოა არსებობდეს გარკვეული შეზღუდვები.',
    'workshop.story.isAIGenerated': 'ისტორია ხელოვნური ინტელექტითაა შექმნილი?',
    'workshop.story.isAIGeneratedTooltip': 'გთხოვთ, შეგვატყობინოთ, თუ ამბის ნებისმიერი ნაწილი გენერირებულია ან შექმნილია ხელოვნური ინტელექტის დახმარებით. ჩვენ ამ ინფორმაციას ვიყენებთ სათანადო მარკირებისთვის და, იმის გათვალისწინებით, თუ როგორ იქმნება ხელოვნური ინტელექტის პროგრამები, შესაძლოა არსებობდეს გარკვეული შეზღუდვები.',
    'workshop.publicationAgreement.aria': 'ნაშრომის გამოქვეყნების ხელშეკრულება',
    'workshop.publicationAgreement.intro': 'მოხარულები ვართ, რომ თქვენი შემოქმედებითი ნაშრომის გამოქვეყნებას ჩვენთან ერთად გადაწყვიტეთ. სანამ გავაგრძელებთ, გთხოვთ, გაეცნოთ ჩვენს გამოქვეყნების ხელშეკრულებას, რათა გაიგოთ, რას ნიშნავს ეს იურიდიული თვალსაზრისით.',
    'workshop.sortChapters': 'დალაგების კრიტერიუმი:',
    'workshop.sortChapters.ascending': 'დასაწყისიდან',
    'workshop.sortChapters.descending': 'უახლესიდან',
    'workshop.sortChapters.aria': 'აირჩიეთ თავების ჩამონათავის დალაგების გზა',
    'workshop.hiatus.btn': 'ისტორიის სტატუსის შეცვლა: შესვენება',
    'workshop.cancelled.btn': 'ისტორიის სტატუსის შეცვლა: გაუქმებული',
    'workshop.complete.btn': 'ისტორიის სტატუსის შეცვლა: დასრულებული',
    'workshop.statusChange.modalTop': 'დარწმუნებული ხართ, რომ გსურთ სტატუსის შეცვლა',
    'workshop.statusName.hiatus': 'პაუზა',
    'workshop.statusName.cancelled': 'გაუქმდა',
    'workshop.statusName.completed': 'დასრულებულია',
    'workshop.statusExplain.hiatus1': 'ჰიატუსი ნიშნავს, რომ ნებისმიერი მიზეზით დროებით წყვეტთ ამ ისტორიაზე მუშაობას. ეს მკითხველს მიანიშნებს, რომ მომდევნო კვირების ან თუნდაც რამდენიმე თვის განმავლობაში ახალ განახლებებს არ უნდა ელოდონ.',
    'workshop.statusExplain.hiatus2': 'განსვენების სტატუსი ავტომატურად მოიხსნება, თუ რომელიმე თავს გამოაქვეყნებთ. ან შეგიძლიათ თავად შეცვალოთ.',
    'workshop.statusExplain.hiatus3': 'თუ თქვენს ისტორიას ექვსი თვის განმავლობაში პაუზაზე დატოვებთ, ჩვენ ავტომატურად ჩათვლით მას გაუქმებულად.',
    'workshop.statusExplain.cancelled1': 'ვწუხვართ, რომ ამბის წერას ვეღარ აგრძელებთ. მეორე მხრივ, გვიხარია, რომ თქვენს მკითხველებს ამის შესახებ შეატყობინებთ.',
    'workshop.statusExplain.cancelled2': 'ისტორიის გაუქმების შესახებ შეტყობინება თქვენს მკითხველებს აცნობებს, რომ ახალი განახლებების მოლოდინი აღარ უნდა ჰქონდეთ.',
    'workshop.statusExplain.cancelled3': 'თქვენ ყოველთვის შეგიძლიათ ამის გაუქმება თავის გამოქვეყნებით ან სტატუსის შეცვლით.',
    'workshop.statusExplain.finished1': 'გილოცავთ! ამდენი შრომის შემდეგ, თქვენ საბოლოოდ მიაღწიეთ წარმოუდგენელი მოგზაურობის დასასრულს. მიუხედავად იმისა, რომ ამბავი შესაძლოა ახლა სრულდება, ვიმედოვნებთ, რომ მომავალში კიდევ ბევრ ისტორიას მოვისმენთ. ახლა კი მოდით, მოდით და დატკბით დამსახურებული დასვენებით.',
    'workshop.statusExplain.finished2': 'ისტორიის დასრულებულად აღნიშვნა მკითხველს მიანიშნებს, რომ ის დასრულებულია. მიუხედავად იმისა, რომ ახალი თავების დამატება არ უნდა მოგინდეთ, ჩვენ ამაში ხელს არ შეგიშლით, თუმცა სპეციალური თავების დამატება ცუდი აზრი არ არის, მაგალითად, ყველა პერსონაჟისთვის მეტი ეპილოგის დასამატებლად.',
    'workshop.statusExplain.finished3': 'მიუხედავად იმისა, რომ ამ სტატუსის გაუქმება ყოველთვის შეგიძლიათ, ჩვენ ამისგან თავის შეკავებას გირჩევთ. თუ ისტორია უნდა გაგრძელდეს, შესაძლოა, უმჯობესი იყოს ახალი ისტორიის დაწყება.',
    'workshop.status.goActive': 'ისტორია კვლავ აქტიური გახადე',
    'workshop.statusChangeEmail.storyIntro': 'გსურთ გამოგვყევით, რომ თქვენი მოთხოვნა:',
    'workshop.statusChangeEmail.hiatusTitle': 'თქვენი მოთხოვნის სტატუსი ავტომატურად დაყენებულია hiatus-ზე',
    'workshop.statusChangeEmail.hiatusIntro': 'მიზეზის უმეტესობის გამო თქვენი მოთხოვნის სტატუსი ავტომატურად დაყენებულია hiatus-ზე.',
    'workshop.statusChangeEmail.hiatusWhy': 'თქვენი მოთავსებული თავისუფლებების გარეშე თქვენი მოთხოვნის სტატუსი ავტომატურად გადატანილია hiatus-ზე 6 თვის ზემოთ.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'ეს სტატუსი ავტომატურად მოიხსენით, თუ ახალი თავისუფლება გამოგიცემთ. თუ ახალი თავისუფლება არ გამოგიცემთ მომდევნო 6 თვეში, სტატუსი ავტომატურად დაყენებადია cancelled.',
    'workshop.statusChangeEmail.cancellationIntro': 'თქვენი მოთხოვნის სტატუსი ავტომატურად დაყენებულია cancelled-ზე.',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'ეს სტატუსი ავტომატურად მოიხსენით, თუ ახალი თავისუფლება გამოგიცემთ. თუ არ გინდათ მუშაობა ამ მოთავსებით, დანარჩენია არაფერი, რაც საჭიროებს გაკეთებას.',
    'workshop.startCreating': 'შექმენით',
    'workshop.ownWork': 'თქვენი თავისუფლება',
    'workshop.list.thumbs': 'მინიატურების სია',
    'workshop.list.list': 'მოკლე სია',
    'workshop.fanfiction.new': 'შექმენით ახალი ფანფიქშენი',
    'workshop.videoTrailerLink': 'ვიდეო ტრეილერის ბმული',
    'workshop.videoTrailerPlayerTitle': 'სიმართლის ვიდეო ტრეილერის პლეიერი',
    'workshop.videoTrailer.supportedPlaftorms': 'ჩვენ გვხვდება Youtube, Vimeo და Odysee',
    'workshop.videoTrailer.rumble': 'ჩვენ ასევე გვეხმარებათ Rumble-ს, მაგრამ არ დაგვიკავშირდეთ იმის დაკოპირებისას IFRAME URL-ს.',
    'workshop.videoTrailer.suggestPlatforms': 'თქვენი ვიდეო პლატფორმა არაა მოცემული, გთხოვთ გამოგვყევით ჩვენს <a>კავშირთავის</a>!',
    'workshop.cover.edit': 'გვერდის შეცვლა',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.story.showChapterNumbersInListing': 'Show chapter numbers in chapter listing',
    'workshop.story.showChapterNumbersInListingTooltip': 'When enabled, chapter numbers are visible to readers in story chapter listings.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    'workshop.story.delete.modalAria': 'Confirmation modal for deleting a story',
    'workshop.story.delete.warning': 'Are you sure you want to delete "{title}"? This action cannot be undone.',
    'workshop.story.delete.button': 'Delete Story',
    'workshop.story.private.universeExplain': 'This story is private because its universe is private.',
    'workshop.story.makePublicWithUniverse.button': 'Make Story and Universe Public',
    'workshop.universe.makePublic.only.button': 'Make Universe Public Only',
    'workshop.universe.makePublic.only.modalAria': 'Confirmation modal for making a universe public only',
    'workshop.universe.makePublic.only.warning': 'This makes only the universe public. Stories in this universe stay private until made public individually.',
    'workshop.universe.makePublic.withStories.button': 'Make Universe and All Stories Public',
    'workshop.universe.makePublic.withStories.modalAria': 'Confirmation modal for making a universe and all stories public',
    'workshop.universe.makePublic.withStories.warning': 'This makes the universe and all linked stories public.',
    // Chapter deletion
    'workshop.chapter.delete.modalAria': 'Confirmation modal for deleting a chapter',
    'workshop.chapter.delete.warning': 'Are you sure you want to delete "{title}"? This action cannot be undone.',
    'workshop.chapter.delete.button': 'Delete Chapter',
    'workshop.chapter.delete.deleting': 'Deleting...',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'ხელოვნური ინტელექტით გენერირებული კონტენტი',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'ხელოვნური ინტელექტის მოდელი',
    'workshop.chapter.aiModel.tooltip': 'აირჩიეთ ხელოვნური ინტელექტის მოდელი, რომელიც გამოყენებულ იქნა კონტენტის გენერირებისთვის',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'შეიყვანეთ ხელოვნური ინტელექტის მოდელის სახელი',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.',
    'workshop.timer.settings': 'Timer Settings',
    'workshop.timer': 'Timer',
    'workshop.timer.type': 'Type',
    'workshop.timer.timer': 'Timer',
    'workshop.timer.countdown': 'Countdown',
    'workshop.timer.pomodoro': 'Pomodoro',
    'workshop.timer.mode': 'Mode',
    'workshop.timer.regular': 'Regular',
    'workshop.timer.improved': 'Improved',
    'workshop.timer.duration': 'Duration (min)',
    'workshop.timer.workDuration': 'Work (min)',
    'workshop.timer.breakDuration': 'Break (min)',
    'workshop.timer.breakType': 'Break Type',
    'workshop.timer.softBreak': 'Soft Break',
    'workshop.timer.hardBreak': 'Hard Break',
    'workshop.timer.break': 'Break',
    'workshop.timer.breakTime': 'Break Time!',
    'workshop.timer.breakMessage': 'Take a moment to rest. Click anywhere to dismiss.',
    'workshop.timer.pause': 'Pause',
    'workshop.timer.resume': 'Resume',
    'workshop.timer.stop': 'Stop',
    'workshop.timer.start': 'Start',
    'workshop.timer.tabInactive': 'Timer paused - switch back to tab to continue',
    // Timer descriptions
    'workshop.timer.type.timer.desc': 'Simple stopwatch that starts at 0:00 and counts upward. Perfect for tracking total writing time in a session or seeing how long you\'ve been working continuously. Never ends automatically - you control when to stop.',
    'workshop.timer.type.countdown.desc': 'Countdown timer that starts from your set duration and counts down to zero. Great for time-boxed writing sessions, word sprints, or when you want to work for a specific amount of time before taking a break.',
    'workshop.timer.type.pomodoro.desc': 'Structured productivity technique: 25-minute focused work sessions alternating with 5-minute breaks. After 4 cycles, takes a longer 15-30 minute break. Scientifically proven to improve focus and prevent burnout.',
    'workshop.timer.mode.regular.desc': 'Timer runs continuously regardless of your activity. Best for disciplined writers who want to track time even when researching, editing, or taking short breaks. Timer keeps going when you switch tabs or stop typing.',
    'workshop.timer.mode.improved.desc': 'Smart timer that automatically pauses when you switch browser tabs. Perfect for focused writing sessions where you want accurate tracking of actual writing time, not total time spent on the page.',
    'workshop.timer.breakType.soft.desc': 'Gentle reminder approach: Shows a small notification when break time starts. You can choose to continue working if you\'re in \'the zone\' or take the break. Good for flexible writers who sometimes need to extend productive sessions.',
    'workshop.timer.breakType.hard.desc': 'Strict enforcement: Displays a full-screen modal that prevents further input until the break timer completes. Forces you to step away from the keyboard. Ideal for writers who struggle with self-discipline or workaholics who need enforced rest periods.',
    'workshop.timer.duration.timer.desc': 'How long you plan to write in this session. Start with 25-50 minutes for focused work, or set longer sessions (2-4 hours) for deep writing days.',
    'workshop.timer.duration.countdown.desc': 'Target writing time before the timer ends. Try 25 minutes for focused sprints, 45-60 minutes for substantial work sessions, or 90 minutes for creative deep dives.',
    'workshop.timer.workDuration.desc': 'Length of focused work sessions. Traditional Pomodoro uses 25 minutes. Try 15-20 minutes if you find it hard to concentrate for longer periods, or 45-50 minutes for experienced writers who can maintain deep focus.',
    'workshop.timer.breakDuration.desc': 'Rest period between work sessions. Standard is 5 minutes for short breaks. Use 10-15 minutes for longer breaks that allow you to step away from your desk, stretch, or get a drink. Every 4th break is automatically longer (2-3x duration).',
    'workshop.llmstxt': 'AI Access',
    'workshop.llmstxt.blocked': 'Blocked - LLMs cannot access your content',
    'workshop.llmstxt.limited': 'Limited - LLMs can only access meta data',
    'workshop.llmstxt.free': 'Free - LLMs can access your content for free',
    'workshop.llmstxt.paid': 'Paid - LLMs can access your content for a fee (coming soon)',
    'workshop.ai.llmstxt.generate': 'Generate LLMs.txt',
    'workshop.ai.llmstxt.generating': 'Generating LLMs.txt...',
    'workshop.ai.llmstxt.download': 'Download LLMs.txt',
    'workshop.ai.llmstxt.title': 'Texts for AI services',
    'workshop.ai.agent.title': 'Assistant',
    'workshop.ai.llmstxt.story-info': 'Story Info LLMs.txt',
    'workshop.ai.llmstxt.full-content': 'Full Content LLMs.txt',
    'workshop.ai.llmstxt.info': 'Info LLMs.txt - Basic information for AI',
    'workshop.ai.llmstxt.infoShort': 'ძირითადი ინფორმაცია',
    'workshop.ai.llmstxt.full': 'Content LLMs.txt - Full content for AI',
    'workshop.ai.llmstxt.fullShort': 'Full content'
};