export default {
    'writer.menu.optionsAria': 'არჩევის მენიუ რედაქტორში',
    'writer.menu.saveOptionsAria': 'ოფციების შენახვის მენიუ',
    'writer.undo': 'გაუქმება',
    'writer.redo': 'განათება',
    'writer.ul': 'უსახელო სია',
    'writer.ol': 'დალაგებული სია',
    'writer.blockquote': 'ციტატა',
    'writer.link': 'ბმულის ჩასმა',
    'writer.image': 'სურათის ჩასმა',
    'writer.bold': 'მონიშნების მსხვილის გამოყენება',
    'writer.underline': 'მონიშნების ქვეყნის გამოყენება',
    'writer.italic': 'მონიშნების მონიშვნა',
    'writer.wordCount': '{characters, number} სიმბოლო, {words, number} სიტყვა',
    'writer.characterCount': '{characters, number} სიმბოლო',
    'finder.details': 'დეტალები',
    'finder.remove': 'კავშირის მოხსნა',
    'finder.connect': 'მონიშვნის დაკავშირება ენციკლოპედიის ჩანართში',
    'writer.aside.ariaLabel': 'დახმარებას შეარჩიეთ მენიუ ვარიანტები',
    'writer.nothingToSave': 'არაფერია შენახვა',
    'writer.link.placeholder': 'Enter a URL',
    'writer.link.error.empty': 'URL cannot be empty',
    'writer.link.error.invalid': 'Please enter a valid URL',
    'writer.fontFamily': 'Font Family',
    'writer.fontFamily.select': 'Select font',
    'writer.publish.publishAria': 'Publication options',
    'writer.publish.scheduleExplained': 'შეგიძლიათ ან მართეთ პუბლიკაცია ადრეულად, ან დააგენერირეთ თარიღი როგორც მომდევნო თარიღით.',
    'writer.publish.schedule': 'დააგენერირეთ გამოქვეყნების თარიღი დროით',
    'writer.publish.previousChapterPublished': 'წინა თავში გამოქვეყნდა {publishDate, date, short} თარიღს, {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'წინა თავში გამოქვეყნდა დაგენერირებული ადგილი {publishDate, date, short} თარიღს, {publishDate, time}',
    'writer.publish.alreadyPublished': 'ეს თავისუფალი თავად გამოქვეყნდა {publishedAt, date, short}. ახალი ვერსიები იქნება გამოქვეყნებული მყიდველი.',
    'writer.publish.betaReader': 'ბეტა',
    'writer.publish.public': 'Publish',
    'writer.publish.now': 'Publish now',
    'writer.publish.schedulePrevious': 'You need to publish or schedule publication of previous chapter before you can publish this one.',
    'writer.publish.earlyAccess.title': 'Early access for fans',
    'writer.publish.earlyAccess.groupLine': '{days} days early: {tiers} — fans get access on {date, date, short} at {date, time}'
};