export default {
    'plans.desc': 'คำอธิบายเกี่ยวกับแผนและคุณสมบัติของจักรวาลวรรณกรรม',
    'plans.title': 'รับประสบการณ์ที่ดีกว่าจากจักรวาลวรรณกรรม!',
    'plans.text': 'จักรวาลวรรณกรรมให้บริการฟังก์ชันพื้นฐานฟรี หากคุณเป็นผู้อ่านหรือผู้สร้างคุณอาจพบว่าสมาชิกขั้นสูงของเราเหมาะกับคุณมากกว่า',
    'plans.faq.basicsPriced': 'ทำไมสมาชิกฟรีมีสิ่งน้อยมาก?',
    'plans.faq.justification': 'ที่นี่ที่ Literary Universe เราให้ความสำคัญกับความเป็นส่วนตัวและทรัพย์สินทางปัญญาของคุณ ดังนั้นเราไม่ใช้ข้อมูลของคุณเพื่อการขายโฆษณาหรือให้กับบริษัทอื่น นี่หมายความว่าเราต้องสร้างสรรค์สิ่งมากมายด้วยตัวเอง ซึ่งใช้เวลาและมีค่าใช้จ่ายสูงในการดำเนินการ ดังนั้นเราจึงสร้างสมาชิกฟรีเป็นการแสดงตัวอย่างเล็กน้อยของ Literary Universe (ที่ยังอนุญาตให้คุณทำสิ่งที่สำคัญที่สุด) พร้อมกับการมีหลายระดับสมาชิกและเพิ่มเติมเพื่อเข้ากันได้กับความต้องการของทุกคนในขณะเดียวกันยังอนุญาตให้เราดำเนินการให้บริการได้ต่อเนื่องและดำเนินการพัฒนาต่อไป หากคุณชอบสิ่งที่เรากำลังสร้างขอให้คิดจะสมัครเป็นสมาชิกในหนึ่งในตัวเลือกที่เสียเงิน ขอบคุณค่ะ',
    'plans.limits': 'ข้อจำกัด',
    'plans.features': 'คุณสมบัติ',
    'plans.account.user': 'ผู้เยี่ยมชม',
    'plans.account.user.desc': 'บัญชีทดลองเริ่มต้นเพื่อลองสิ่งต่าง ๆ',
    'plans.account.explorer': 'นักสำรวจ',
    'plans.account.explorer.desc': 'สำหรับนักอดีตและเพื่อน',
    'plans.account.adventurer': 'นักผจญภัย',
    'plans.account.adventurer.desc': 'สำหรับผู้สร้างและผู้สนับสนุนของเรา',
    'plans.account.storyteller': 'นักเล่าเรื่อง',
    'plans.account.storyteller.desc': 'สำหรับผู้ที่มีความคิดสร้างสรรค์และอุทิศตน',
    'plans.unlimited': 'ไม่ จำกัด',
    'plans.price': 'ราคา',
    'plans.price.free': 'ฟรี',
    'plans.price.monthly': 'ต่อเดือน*',
    'plans.price.annually': 'ต่อปี*',
    'plans.price.perMonth': '{price} / เดือน*',
    'plans.price.perYear': '{price} / ปี*',
    'plans.development': 'กำลังพัฒนา',
    'plans.limits.encEntries': 'รายการสารบัญ',
    'plans.limits.maxCollaborators': 'ผู้ร่วมงานต่อโครงการ',
    'plans.limits.pmChats': 'จำนวนสูงสุดของผู้รับข้อความส่วนตัว',
    'plans.feature.creative': 'สร้างจักรวาลและเรื่องราวที่น่าทึ่ง',
    'plans.feature.encCustomFields': 'ฟิลด์สารานุกรมที่กำหนดเองบนรายการ',
    'plans.feature.encAdvCategories': 'หมวดหมู่สารานุกรมเพิ่มเติม',
    'plans.feature.scratchpad': 'สแครตช์แพด',
    'plans.feature.library': 'ห้องสมุด',
    'plans.feature.blog': 'บล็อกส่วนตัวและจักรวาล',
    'plans.feature.customBlogTheme': 'ธีมบล็อกที่กำหนดเอง',
    'plans.feature.advanceStats': 'สถิติขั้นสูง',
    'plans.feature.challenges': 'ท้าทายในการเขียน',
    'plans.feature.newFeaturesVote': 'ลงคะแนนเสียงสำหรับคุณสมบัติใหม่',
    'plans.feature.newFeaturesSuggest': 'เสนอคุณสมบัติใหม่',
    'plans.feature.accessToBeta': 'เข้าถึงคุณสมบัติเบต้า',
    'plans.feature.userGroups': 'กลุ่มผู้ใช้',
    'plans.feature.privateUserGroups': 'สร้างกลุ่มผู้ใช้ส่วนตัวและซ่อนไว้',
    'plans.feature.internalUniverseForums': 'ฟอรั่มภายในสำหรับจักรวาล',
    'plans.feature.fictionalTime': 'เวลาเพิ่มเข้ามาในเรื่องจากนิยาย',
    'plans.feature.forums': 'ฟอรัมในบล็อกและหน้ายูนิเวิร์ส',
    'plans.feature.timelines': 'ไทม์ไลน์ของยูนิเวิร์ส',
    'plans.feature.webMonetization': 'การชำระเงินผ่านเว็บ',
    'plans.feature.storyMonetization': 'การทำเงินจากเรื่องราว',
    'plans.feature.fanClub': 'แฟนคลับ',
    'plans.feature.translations': 'ความสามารถในการแปล',
    'plans.feature.fanFiction': 'เขียนและจัดการนิยายแฟนตาซี',
    'plans.feature.universeFanArt': 'ผู้จัดการภาพแฟนอาร์ต',
    'plans.feature.overviewNotes': 'บันทึกภาพรวมของเรื่อง',
    'plans.feature.personalNotesStoriesUniverses': 'บันทึกส่วนตัวเกี่ยวกับเรื่องราวและยูนิเวิร์ส',
    'plans.feature.storyReviews': 'บทวิจารณ์เรื่อง',
    'plans.feature.readingLists': 'รายการอ่าน',
    'plans.feature.scenesManager': 'ผู้จัดการฉาก',
    'plans.feature.glossaries': 'พจนานุกรมแปลภาษา',
    'plans.feature.chatSupport': 'สนับสนุนทางแชท',
    'plans.currency.select': 'เลือกสกุลเงิน',
    'plans.subscription.ownAlready': 'คุณมีแผนนี้อยู่แล้ว',
    'plans.subscription.title': 'Subscriptions & payments',
    'plans.see': 'ดูแผนการสมัครสมาชิกที่มีอยู่',
    'plans.current.none': 'คุณยังไม่รองรับ Literary Universe',
    'plans.current.buying': 'อาจใช้เวลาสักครู่ในการยืนยันการซื้อของคุณ เราขอขอบคุณสำหรับความอดทนของคุณ',
    'plans.current.heading': 'แผนการสมัครสมาชิกปัจจุบัน',
    'payment.methods.title': 'Monetization',
    'payment.methods.tabs': 'ตัวเลือกการชำระเงิน',
    'payment.option.title': 'ตัวเลือกการชำระเงิน',
    'payment.option.notFount': 'คุณไม่มีตัวเลือกการชำระเงินที่บันทึกไว้',
    'payment.option.create': 'เพิ่มตัวเลือกการชำระเงินใหม่',
    'payment.option.description': 'นี่คือรายการวิธีการชำระเงินที่คุณบันทึกไว้ คุณสามารถบันทึกวิธีการชำระเงินใหม่ที่นี่เพื่อชำระเงินได้เร็วขึ้น  Literary Universe ไม่เก็บรักษาหรือประมวลผลข้อมูลการชำระเงินของคุณเช่นหมายเลขบัตรเครดิต',
    'payment.history.title': 'ประวัติการชำระเงิน',
    'payment.history.tab': 'History',
    'payment.history.none': 'เราไม่มีบันทึกการชำระเงินย้อนหลังใด ๆ',
    'plans.options.aria': 'ตัวเลือกการชำระเงิน',
    'plans.options.creditCard': 'บัตรเครดิต',
    'plans.options.creditCardNew': 'บัตรเครดิตใหม่',
    'plans.options.existingCards': 'บัตรเครดิตที่บันทึกไว้',
    'plans.purchase.action': 'สมัครสมาชิก',
    'plans.purchase.title': 'ซื้อการสมัครสมาชิก Literary Universe',
    'payment.creditCard.details': 'รายละเอียดบัตรเครดิต',
    'payments.zipcode.label': 'รหัสไปรษณีย์',
    'payment.card.name': 'ชื่อบนบัตร',
    'plans.subscribed.thankYou': 'ขอบคุณที่สนับสนุน Literary Universe',
    'plans.subscribed.periodEnd': 'การสมัครสมาชิกของคุณใช้ได้จนถึง: {end, date, medium}',
    'plans.subscribed.renewal': `ในที่สุดการสมัครสมาชิกของคุณจะถูกต่ออายุโดยอัตโนมัติ {method, select,
    charge_automatically {ต่ออายุหลังจากชำระใบแจ้งหนี้}
    send_invoice {}
    other {}
  }.`,
    'plans.subscribed.paymentMethod': 'วิธีการชำระเงินเริ่มต้นของคุณจะถูกใช้ในการชำระเงินสำหรับรอบถัดไป',
    'plans.subscribed.status': `สถานะการสมัครสมาชิก: {status, select,
    active {ใช้งาน}
    incomplete {มีบางอย่างขาดหาย}
    incomplete_expired {มีบางอย่างขาดหาย}
    trialing {ทดลองใช้}
    past_due {เราไม่ได้รับการชำระเงินของคุณ}
    cancelled {ยกเลิก}
    unpaid {ยังไม่ได้ชำระเงิน}
    expired {หมดอายุ}
    other {}
  }`,
    'payments.changeMethod': 'เปลี่ยนวิธีการชำระเงิน',
    'plans.subscribed.willNotRenew': ', จะไม่ต่ออายุในสิ้นสุดของรอบ',
    'plans.cancel.button': 'ยกเลิกการสมัครสมาชิก',
    'plans.cancel.question': 'คุณแน่ใจหรือไม่ว่าต้องการยกเลิกการสมัครสมาชิกของคุณ? การสมัครสมาชิกของคุณจะยังคงใช้งานได้จนกว่าจะสิ้นสุดรอบการเรียกเก็บเงิน',
    'plans.cancel.confirmationButton': 'ใช่ ฉันต้องการยกเลิกการสมัครสมาชิกของฉัน',
    'plans.cancel.failed': 'ขออภัยเราไม่สามารถยกเลิกแผนของคุณในขณะนี้ โปรดลองอีกครั้งในภายหลัง',
    'plans.cancel.restoreBtn': 'กู้คืนการสมัครสมาชิก',
    'plans.cancel.restoreFailed': 'ขออภัยเราไม่สามารถกู้คืนการสมัครสมาชิกในขณะนี้ โปรดลองอีกครั้งในภายหลัง',
    'plans.change.button': 'เปลี่ยนแผนการสมัครสมาชิก',
    'plans.change.explanation': 'Select the plan you want to upgrade or downgrade to. You will be billed or prorated the difference in price immediately.',
    'plans.change.failed': 'ขออภัยเราไม่สามารถเปลี่ยนแผนของคุณในขณะนี้ โปรดลองอีกครั้งในภายหลัง',
    'plans.change.upgrade': 'อัปเกรด',
    'payments.disclaimer': 'ข้อมูลการชำระเงินและการประมวลผลจะดำเนินการผ่าน Stripe  เราไม่เก็บข้อมูลบัตรเครดิตหรือบัญชีธนาคารใดๆ บนเซิร์ฟเวอร์ของเรา',
    'buy.payment.optionsSelect': 'เลือกตัวเลือกการชำระเงิน',
    'payments.card.number': 'หมายเลขบัตร',
    'payments.card.expire': 'ใช้ได้ถึงวันที่',
    'payments.card.cvv': 'CVV',
    'payments.card.info': '{cardType} บัตร สิ้นสุดลงใน {ending}',
    'payments.none': 'ไม่พบตัวเลือกการชำระเงินที่บันทึกไว้',
    'payments.none.cards': 'ไม่พบบัตร',
    'payments.added': 'เพิ่มวิธีการชำระเงินใหม่เรียบร้อยแล้ว',
    'payments.delete.confirm': 'คุณแน่ใจหรือไม่ว่าต้องการลบ {cardType}ที่สิ้นสุดด้วย {ending}?',
    'payment.invoice.status': 'สถานะใบแจ้งหนี้',
    'payment.invoice.statusMessage': `{status, select,
    draft {ร่าง}
    open {เปิด}
    paid {ชำระเงินแล้ว}
    uncollectible {ไม่สามารถเรียกเก็บเงินได้}
    void {ยกเลิก}
    other {}
  }`,
    'payment.invoice.id': 'รหัสใบแจ้งหนี้',
    'payment.invoice.pdf': 'ไฟล์ PDF ใบแจ้งหนี้',
    'payment.invoice.total': 'รวมทั้งสิ้น',
    'payment.invoice.what': 'รายละเอียดใบแจ้งหนี้',
    'payment.stripe.powered': 'ขับเคลื่อนด้วย ',
    'payment.listMethods.card': 'บัตร',
    'payment.expiresAt': 'หมดอายุ {month}/{year}',
    'payment.card.details': `{type, select,
    credit {บัตรเครดิต}
    debit {บัตรเดบิต}
    other {บัตร}
  } สิ้นสุดด้วย {last4}`,
    'payment.options.default': 'ค่าเริ่มต้น',
    'payment.method.add': 'เพิ่มวิธีการชำระเงินใหม่',
    'payment.methods.adding': 'วิธีการชำระเงินใหม่ของคุณถูกเพิ่มเข้าสู่บัญชีของคุณแล้ว',
    'payment.methods.delete': 'ลบวิธีการชำระเงิน',
    'payment.upgradePlan.option': '{plan} - {price}',
    'payment.methods.webMonetization': 'การชำระเงินผ่านเว็บ',
    'settings.webMonetization.placeholder': 'พอยต์การชำระเงินของคุณ',
    'payment.webMonetization.explained': 'การชำระเงินผ่านเว็บ (Web Monetization) เป็นมาตรฐานที่นำเสนอสำหรับการชำระเงินผ่านเว็บไซต์ ที่นี่คุณสามารถเพิ่มพอยต์การชำระเงินของคุณซึ่งจะถูกเพิ่มลงในหน้าโปรไฟล์ของคุณ บล็อก ยูนิเวิร์ส และเรื่องราว เพื่อให้เว็บไซต์สามารถใช้งานได้ผ่าน Web Monetization',
    'payment.webMonetization.learnMore': 'เรียนรู้เพิ่มเติมเกี่ยวกับการชำระเงินผ่านเว็บ (Web Monetization)',
    'plans.subscription.settingsAria': 'ตัวเลือกการตั้งค่าการสมัครสมาชิก',
    'plans.buttonStatus.submitting': 'กำลังส่งคำขอของคุณ...',
    'plans.button.manageOnStripe': 'จัดการการเรียกเก็บเงินใน Stripe',
    'plans.call.signUpBottom': 'ลงทะเบียนสำหรับบัญชี Literary Universe ฟรีและเริ่มสร้างสรรค์ได้ทันที!',
    'plans.button.seeComparison': 'ดูข้อมูลเพิ่มเติมเกี่ยวกับแผนและราคาในหน้าเปรียบเทียบของเรา!',
    'plans.button.chooseThisSubscription': 'เลือกแผนนี้',
    'plans.button.chooseFree': 'เริ่มต้นฟรี',
    'plans.features.allInPreviousTiers': 'ทุกอย่างในระดับก่อนหน้านี้',
    'plan.button.chooseNow': 'เลือกแผน Literary Universe ของคุณตอนนี้',
    'plans.subscription.manage': 'จัดการการสมัครสมาชิก',
    'plans.taxMayApply': '* อาจมีการเรียกเก็บภาษีมูลค่าเพิ่มและภาษีท้องถิ่นอื่นๆ',
    'plans.faq.crypto': 'คุณจะให้บริการชำระเงินด้วยเครดิตโดยเงินสกุลดิจิตอลหรือไม่?',
    'plans.faq.cryptoAnswer': 'ใช่ เรากำลังทำงานในเรื่องนี้ เราเป็นแฟน Web3 เรากำลังมองหาวิธีการรวม Web3 เข้ากับแพลตฟอร์มในอนาคตใกล้ ในขณะนี้เราอนุญาตให้เข้าสู่ระบบด้วย Web3 และเรากำลังมองหาวิธีการขยายการให้ค่าตอบแทนให้กับผู้สร้างและให้ผู้สร้างสามารถเลือกตัวเลือกการชำระเงินที่เป็นไปได้ทั้งหมดที่พวกเขาต้องการ',
    'plans.subscribed.updating': 'อาจใช้เวลาสักครู่ในการอัปเดตข้อมูลการสมัครสมาชิกของคุณ ขอบคุณสำหรับความอดทนของคุณ!',
    'payments.methods.webMonetization': 'การชำระเงินผ่านเว็บ',
    'stripeConnect.settings.title': 'การตั้งค่าการจ่ายเงิน',
    'stripeConnect.settings.intro': 'หากคุณต้องการรับเงินหรือขายผ่าน Literary Universe คุณต้องสร้างบัญชี Stripe ผ่านปุ่มด้านล่าง',
    'stripeConnect.settings.connectAccount': 'ตั้งค่าบัญชี Stripe',
    'stripeConnect.settings.ongoing': 'เรากำลังรอคำตอบจาก Stripe เกี่ยวกับบัญชีของคุณ อาจใช้เวลาสักครู่ หากใช้เวลานานเกินไป คลิกที่ปุ่มด้านล่างเพื่อกลับไปที่ Stripe',
    'stripeConnect.settings.finished': 'คุณได้ตั้งค่าเสร็จสิ้นเพื่อรับเงินผ่าน Stripe Connect',
    'stripeConnect.settings.balance': 'ยอดคงเหลือ',
    'stripeConnect.settings.balanceAvailable': 'ยอดคงเหลือที่สามารถใช้ได้',
    'stripeConnect.settings.balancePending': 'ยอดคงเหลือที่รอดำเนินการ',
    'stripeConnect.settings.recentTransfers': 'การโอนล่าสุด',
    'stripeConnect.transfers.amount': 'จำนวนเงิน',
    'stripeConnect.transfers.reason': 'เหตุผล',
    'payment.settings.donations': 'การตั้งค่าการบริจาค',
    'plans.fanClub.heading': 'สโมสรแฟนคลับ',
    'payment.donations.enable': 'เปิดใช้งานการบริจาค',
    'payment.donations.suggestedAmount': 'จำนวนที่แนะนำ',
    'payment.donations.amount': 'จำนวนเงิน',
    'payment.donations.preferredCurrency': 'สกุลเงินที่ต้องการ',
    'payment.donations.currency': 'สกุลเงิน',
    'payment.donations.stripeDescription': 'การบริจาคให้กับ {username}',
    'payment.donations.support': 'สนับสนุน {username}',
    'payment.donations.donate': 'บริจาค',
    'payment.donations.donationModal': 'ยืนยันการบริจาค',
    'payment.donations.payNowUSD': 'บริจาค {donation, number, ::compact-short currency/USD} ไปยัง {username}',
    'payment.donations.payNowJPY': 'บริจาค {donation, number, ::compact-short currency/JPY} ไปยัง {username}',
    'payment.donations.payNowEUR': 'บริจาค {donation, number, ::compact-short currency/EUR} ไปยัง {username}',
    'payment.donations.payNowCZK': 'บริจาค {donation, number, ::compact-short currency/CZK} ให้กับ {username}',
    'payment.donations.payNowGBP': 'บริจาค {donation, number, ::compact-short currency/GBP} ให้กับ {username}',
    'payment.donations.thankYouTitle': 'ขอบคุณสำหรับการบริจาคของคุณให้กับ {username}',
    'payment.donations.thankYouContinue': 'ขอบคุณสำหรับการสนับสนุน {username}เราหวังว่าคุณจะยังคงเพลิดเพลินกับงานของพวกเขาและพิจารณาสนับสนุนอีกครั้งในอนาคต',
    'payment.success': 'การชำระเงินสำเร็จแล้ว!',
    'payment.processing': 'การชำระเงินของคุณกำลังดำเนินการ',
    'payment.failed': 'การชำระเงินของคุณไม่สำเร็จ โปรดลองอีกครั้ง',
    'payment.generalError': 'เกิดข้อผิดพลาดบางอย่าง',
    'payment.unexpectedError': 'เกิดข้อผิดพลาดบางอย่าง',
    'payments.transferType.donation': 'บริจาค',
    'payment.donation.backToProfile': 'กลับไปที่โปรไฟล์ของ {username}',
    'payment.author.requirementStripeConnect': 'ก่อนที่เราจะดำเนินการทางการเงินใด ๆ คุณจำเป็นต้องสร้างและเชื่อมต่อบัญชี Stripe Connect ของคุณ',
    'payment.author.requirementPublishWork': 'ก่อนที่คุณจะดำเนินการต่อ โปรดเผยแพร่งานอย่างน้อย 1 รายการ (เรื่องหรือจักรวาล)',
    'payment.author.createWork': 'สร้างงานใหม่',
    'payment.author.directivesTitle': 'คำแนะนำ',
    'payment.author.directivesExplained': 'เรามีคำแนะนำเพิ่มเติมที่คุณควรปฏิบัติก่อนเปิดใช้บริการการชำระเงินเพื่อเพิ่มโอกาสในการสำเร็จ',
    'payment.author.directivesStoryPublished': 'เผยแพร่เรื่องอย่างน้อย 1 เรื่องฟรีเพื่อแสดงความสามารถในการเขียนของคุณ',
    'payment.author.directivesFreeStoryFinished': 'เสร็จสิ้นเรื่องฟรีอย่างน้อย 1 เรื่องเพื่อแสดงให้ผู้อ่านรู้ว่าคุณจะไม่ทิ้งพวกเขาในช่วงกลางการเดินทาง',
    'payment.universe.directivesUniversePublished': 'เผยแพร่จักรวาลของคุณ',
    'payment.universe.directivesEncFull': 'กรอกข้อมูลในสารานุกรมของคุณให้ครบถ้วน มีอย่างน้อย 30 รายการ! ดีกว่าหากคุณกำลังเพิ่มขีดจำกัดที่ 100',
    'payment.universe.haveFans': 'การให้บุคคลที่สนับสนุนคุณเป็นเรื่องง่ายขึ้นถ้าพวกเขามีความสนใจในสิ่งที่คุณกำลังทำอยู่แล้ว 100 แฟนที่เพิ่มจักรวาลของคุณเข้าสู่ห้องสมุดของพวกเขาเป็นเส้นตรงเริ่มต้น',
    'payment.settings.yourFanClub': 'สโมสรแฟนของคุณ',
    'payment.settings.newWork': 'สร้างงานใหม่',
    'payment.amount.withNet': `{amount} (net: {netAmount})`,
    'payment.fanClub.intro': 'In this section you can modify your fan club settings. From subscription tiers to history of payments.',
    'payment.fanClub.tiers': 'Tiers',
    'payment.fanClub.tierName': 'ชื่อระดับ',
    'payment.fanClub.createTier': 'เพิ่มชั้น',
    'payment.fanClub.description': 'คำอธิบายของชั้น',
    'payment.fanClub.picture': 'รูปภาพของชั้น',
    'payment.fanClub.priceBreakdown': 'Subscriber will pay: {amount}. Platform fee is {fee} ({platformPercentage}), you will get (estimated): {net}',
    'payment.fanClub.platformFeeExplained': 'We are working towards our platform fee covering fees from payment providers such as credit card fees and others, but sometimes there might be overflow. If that happens please let us know so that we can investigate and reduce the impact in the future. As such you should not see any of those fees effect your total, but if you do please let us know. Another big impact on your net value are taxes. In countries like USA where it is common to have taxes to be exclusive of the price you will not be affected, in countries where it is common to have taxes inclusive in the price (like the EU), you need to account for your country\'s VAT when setting the subscription price.',
    'payment.fanClub.learnStripeFees': 'เรียนรู้เพิ่มเติมเกี่ยวกับค่าธรรมเนียม Stripe',
    'payment.feeNotice': 'Please do note that this is an estimate and the actual Stripe fee might be different based on customer\'s payment type and additional charges from the pay gate and applicable taxes.',
    'payment.fanClub.perks': 'สิ่งที่ได้รับเปรียบเสมอ',
    'stripeConnect.settings.notifications': 'การแจ้งเตือนจาก Stripe',
    'plans.pricePerMonth': 'จำนวนเงินต่อเดือน',
    'payment.fanClub.perkType': 'ประเภทสิทธิพิเศษ',
    'payment.fanClub.addPerk': 'เพิ่มสิทธิพิเศษ',
    'payment.fanClub.perksExplained': 'นี่คือสิทธิประโยชน์ที่ได้รับโดยอัตโนมัติสำหรับแฟนคลับผ่าน Literary Universe',
    'plans.deleteTier.header': 'คุณแน่ใจหรือว่าต้องการลบระดับ {tierName} หรือไม่?',
    'plans.deleteTier.explainer': 'หากในระดับนี้ไม่มีผู้ติดตาม ระดับนี้จะถูกลบทิ้งไป ในกรณีอื่นๆ ระดับนี้จะถูกปิดการใช้งานสำหรับการสมัครสมาชิกใหม่ แต่การสมัครสมาชิกที่มีอยู่ในปัจจุบันจะดำเนินการต่อไปจนกว่าแฟนจะเปลี่ยนแปลงสมาชิกของตนเอง',
    'plans.fanClub.userSettings': 'จัดการการสมัครสมาชิกแฟนคลับของคุณ',
    'plans.fanClub.subscribers': 'ผู้ติดตาม',
    'plans.fanClub.activatedLabel': 'เปิดใช้งานแฟนคลับ',
    'plans.fanClub.inactiveWarning': 'คลับแฟนของคุณยังไม่ได้เปิดใช้งาน คุณยังสามารถเตรียมแผนและเมื่อคุณพร้อมแล้วคุณสามารถเปิดใช้งานได้ในการตั้งค่า',
    'payment.fanClub.editTier': 'Edit tier',
    'plans.deletePlan.modalAria': 'Delete plan confirmation',
    'payment.fanClub.paymentDescriptorFull': 'LU - {username} fan club',
    'payment.fanClub.paymentDescriptorShort': 'LU-{username} fan club',
    'payment.fanClub.paymentDescriptorMinimal': '{username} fan club',
    'payment.fanClub.paymentDescriptorBackup': 'LU - author fan club',
    'payment.fanClub.perMonth': '{amount} / per month',
    'plans.fanClub.notCreated': 'Oops! Something went wrong and your fan club did not get create when it should have, but worry not, we have a backup plan ready! Just click the button bellow and you will be all set!',
    'plans.fanClub.create': 'Create fan club',
    'plans.subscription.error.unexpected': 'Unexpected error occurred. Please try again later.',
    'plans.subscription.error.invalidPrice': 'The selected subscription plan is not available. Please try a different plan.',
    'plans.subscription.error.notConfigured': 'Payment provider is not properly configured. Please contact support.',
    'plans.subscription.error.generic': 'An error occurred while setting up checkout. Please try again later.',
    'plans.subscription.error.portalFailed': 'Could not open customer portal. Please try again later.',
    'plans.subscription.error.noCustomer': 'Customer account not found. Please contact support.',
    'plans.subscription.error.stripeError': 'Error connecting to payment provider. Please try again later.',
    'plans.subscription.error.noCustomer': 'Customer account not found. Please contact support.',
    'plans.subscription.error.stripeError': 'Error connecting to payment provider. Please try again later.',
    'plans.subscription.error.generic': 'An error occurred. Please try again later.',
    'plans.subscription.error.portalFailed': 'Could not open customer portal. Please try again later.',
    'plans.subscription.error.stripeNotConfigured': 'Payment provider is not properly configured. Please contact support.',
    'plans.subscription.error.customerNotInStripe': 'Your customer account was not found in the payment system. Please contact support.',
    'plans.subscription.error.vendorNotFound': 'Vendor account not found. Please contact support.',
    'plans.subscription.error.invalidPlan': 'Invalid plan configuration. Please contact support.',
    'plans.subscription.error.noVendor': 'Vendor account not found. Please contact support.',
    'plans.subscription.fallback.message': 'We\'re having trouble connecting to the billing portal right now. Here are some options to manage your subscription:',
    'plans.subscription.fallback.tryAgain': 'Try accessing the portal again later',
    'plans.subscription.fallback.contactSupport': 'Contact our support team for assistance',
    'plans.subscription.fallback.refreshPage': 'Refresh the page and try again',
    'plans.subscription.fallback.tryAgainButton': 'Try Again',
    'plans.upgrade': 'UPGRADE',
    'plans.current': 'CURRENT',
    'plans.currentPlan': 'Current Plan',
    'plans.selectPlan': 'Select Plan',
    'plans.upgrade.confirm': 'Confirm Upgrade',
    'plans.lifetime.pageTitle': 'Lifetime Membership - Literary Universe',
    'plans.lifetime.title': 'Limited Lifetime Membership Offer',
    'plans.lifetime.intro': 'Become a permanent part of Literary Universe with our exclusive lifetime membership offer. This is a limited-time opportunity to secure Storyteller tier benefits forever with a one-time payment.',
    'plans.lifetime.limitedTimeOffer': 'This offer is available until {endDate}. Don\'t miss out!',
    'plans.lifetime.benefitsTitle': 'Lifetime Membership Benefits',
    'plans.lifetime.benefit1': 'Storyteller tier membership benefits forever',
    'plans.lifetime.benefit2': 'Champion or request a feature that we will implement with priority',
    'plans.lifetime.benefit3': 'Special badge on your profile',
    'plans.lifetime.benefit4': 'Individual assessment and assignment of The Way of the Author level',
    'plans.lifetime.benefit5': 'Custom avatar from our designer',
    'plans.lifetime.benefit6': 'Monthly calls with the crew on the progress of the platform',
    'plans.lifetime.priceTitle': 'One-time Payment',
    'plans.lifetime.price': '€999',
    'plans.lifetime.loginRequired': 'You need to be logged in to purchase the lifetime membership.',
    'plans.lifetime.alreadyMember': 'You already have lifetime membership benefits. Thank you for your support!',
    'plans.lifetime.buyButton': 'Purchase Lifetime Membership',
    'plans.lifetime.establishedAuthorsNote': 'Are you an established author? Contact us for an individual offer tailored to your needs.',
    'plans.button.buyLifetimeMembership': 'Buy Lifetime Membership',
    'plans.lifetime.banner.title': 'Limited Time Offer: Lifetime Membership',
    'plans.lifetime.banner.description': 'Secure Storyteller benefits forever with our exclusive one-time payment option. Available until July 31st, 2025.',
    'plans.lifetime.banner.button': 'View Lifetime Offer',
    'plans.lifetime.thankYou.pageTitle': 'Thank You for Your Lifetime Membership - Literary Universe',
    'plans.lifetime.thankYou.celebrationImageAlt': 'Celebration',
    'plans.lifetime.thankYou.title': 'Welcome to the Literary Universe Family!',
    'plans.lifetime.thankYou.message': 'Thank you for purchasing the lifetime membership! Your support means the world to us and helps ensure the future of Literary Universe.',
    'plans.lifetime.thankYou.whatsNextTitle': 'What Happens Next?',
    'plans.lifetime.thankYou.nextStep1': 'Your account has been upgraded to Storyteller tier permanently',
    'plans.lifetime.thankYou.nextStep2': 'You\'ll receive an email with details about your custom avatar design process',
    'plans.lifetime.thankYou.nextStep3': 'Our team will contact you to schedule your first monthly call',
    'plans.lifetime.thankYou.nextStep4': 'You can now submit your feature request through our feedback system',
    'plans.lifetime.thankYou.enjoyMessage': 'Enjoy all the benefits of your lifetime membership and start creating amazing stories!',
    'plans.lifetime.thankYou.goToDashboard': 'Go to Dashboard',
    'plans.lifetime.error.unexpected': 'Unexpected error occurred. Please try again later.',
    'plans.lifetime.error.invalidPrice': 'The lifetime membership plan is not available. Please try again later.',
    'plans.lifetime.error.notConfigured': 'Payment provider is not properly configured. Please contact support.',
    'plans.lifetime.error.notLoggedIn': 'You must be logged in to purchase a lifetime membership.',
    'plans.lifetime.error.generic': 'An error occurred while setting up checkout. Please try again later.',
    'plans.lifetime.error.alreadyMember': 'You already have a lifetime membership.',
    'plans.lifetime.subscription.title': 'Lifetime Membership',
    'plans.lifetime.subscription.description': 'You have a lifetime membership with Literary Universe. Thank you for your incredible support!',
    'plans.lifetime.subscription.status': 'Status: Active Forever',
    'plans.lifetime.subscription.purchaseDate': 'Purchased on: {date, date, medium}',
    'plans.lifetime.subscription.noActions': 'Your lifetime membership requires no further action. Enjoy your benefits forever!',
    'plans.lifetime.subscription.benefitsTitle': 'Your Lifetime Benefits',
    'plans.lifetime.subscription.benefit1': 'Permanent Storyteller tier access',
    'plans.lifetime.subscription.benefit2': 'Custom avatar design',
    'plans.lifetime.subscription.benefit3': 'Monthly team calls',
    'plans.lifetime.subscription.benefit4': 'Feature request priority',
    'plans.subscription.lifetimeMember': 'You have a lifetime membership',
    'plans.lifetime.announcement': 'You have now a limited opportunity to gain lifetime membership! Check it out!'
};