export default {
    'challenges.current': 'Huidige uitdagings',
    'challenges.wordcount.goal': 'Teiken woordtelling',
    'challenges.wordcount.dailygoal': 'Teiken daaglikse woordtelling',
    'challenges.wordcount.today': 'Vandag geskryf',
    'challenges.wordcount.total': 'Totale woorde geskryf',
    'challenges.wordcount.remaining': 'Woorde wat oorbly',
    'challenges.wordcount.daysleft': 'Dae wat oorbly',
    'challenges.wordcount.currentDay': 'Huidige dag',
    'challenges.wordcount.average': 'Gemiddelde woorde per dag',
    'challenges.wordcount.finishOn': 'Met die huidige spoed sal jy klaarmaak op',
    'challenges.wordcount.finishOnTime': 'Woorde wat daagliks geskryf moet word om betyds klaar te maak',
    'challenges.wordcount.graph.day': 'Dag {day}',
    'challenges.underway': 'Hierdie uitdaging is reeds aan die gang.',
    'challenges.targetWords': 'Totale teiken woordtelling',
    'challenges.startDate': 'Begin datum',
    'challenges.endDate': 'Eind datum',
    'challenges.future': 'Komende uitdagings',
    'challenges.future.wordcount': 'Wordcount challenge staring on {startDate, date, short} with goal of {target, number} by {endDate, date, short}.',
    'challenges.future.nanowrimo': 'NaNoWriMo-uitdaging is gereed.',
    'challenges.wordcount': 'Woordtelling',
    'challenges.wordcount.desc': `Set yourself a goal of how many words you want to write this month for this {type, select,
    story {story}
    universe {universe}
    other {}
  }.`,
    'challenges.wordcount.select': 'Hoeveel woorde wil jy jouself uitdaag om te skryf?',
    'challenges.start': 'Begin uitdaging',
    'challenges.report': 'Rapporteer',
    'challenges.victory': 'Gelukwens! Jy het hierdie uitdaging voltooi.',
    'challenges.defeat': 'Ongelukkig het jy hierdie uitdaging nie voltooi nie.',
    'challenges.baseline': 'The current wordcount for this story is {wordcount, number}, this will be the starting point.',
    // NaNoWriMo
    'nanowrimo.full': 'Nasionale Roman Skryf Maand',
    'nanowrimo.site': 'NaNoWriMo-amptelike webwerf',
    'nanowrimo.settings': 'NaNoWriMo-rekening',
    'nanowrimo.username': 'NaNoWriMo-gebruikersnaam',
    'nanowrimo.key': 'Geheime sleutel',
    'nanowrimo.key.get': 'Kry jou NaNoWriMo-sleutel.',
    'nanowrimo.key.get.notice': 'Jy moet ingeteken wees om dit te sien.',
    'nanowrimo.ongoing': 'is in volle swang! {countdown} meer dae om te gaan!',
    'nanowrimo.startsin': `sal begin in {countdown, plural,
      one {1 dag}
      other {# dae}
    }! Maak gereed!`,
    'nanowrimo.isover': 'NaNoWriMo is verby. Sien jou volgende jaar!',
    'nanowrimo.select': 'Ken hierdie storie toe aan NaNoWriMo.',
    'nanowrimo.baseline': 'Wanneer NaNoWriMo begin, sal dit die huidige woordtelling neem en dit as \'n basislyn gebruik waarvan enige addisionele woorde as deel van NaNoWriMo geneem sal word.',
    'nanowrimo.victory': 'Gelukwensing! Jy het NaNoWriMo gewen!',
    'nanowrimo.challenge': 'NaNoWriMo-uitdaging',
    'nanowrimo.description': 'Die uitdaging is om \'n roman van {words, number} woorde te skryf gedurende November.',
    'nanowrimo.error.usernotfound': 'Gebruikersnaam is nie op die NaNoWriMo-bedieners gevind nie.',
    'nanowrimo.error.nobook': 'Geen boek is gevind nie. Maak asseblief seker dat jy jou boek op NaNoWriMo geskep het.',
    'nanowrimo.error.wordcount': 'Kon nie woordtelling op NaNoWrimo stel nie, maak asseblief seker dat jou inligting korrek is en probeer weer.',
    'nanowrimo.connected': 'Jy het hierdie storie aan NaNoWriMo toegeken.',
    'nanowrimo.connected.other': 'Jy het reeds \'n ander storie gekoppel.'
};