export default {
  'courses.courses': 'Courses',
  'courses.overview': 'Oorsig van kursusse',
  'course.create': "Skep 'n nuwe kursus",
  'course.reading.title': 'Reading assignment title',
  'course.question.add': 'Add question',
  'course.add.courseElement': 'Add a new course element',
  'course.lessons.newMessage': 'Create and organize your lessons for effective teaching',
  'course.reading.new': 'Reading Assignment',
  'course.reading.newMessage': 'Create and organize reading assignments for your students',
  'course.writing.new': 'Skryfopdrag',
  'course.writing.newMessage': 'Quickly set up and distribute writing tasks',
  'course.question.text': 'Jou vraag gaan hier',
  'course.question.type': 'Please select a type of question',
  'course.question.delete': 'Remove question',
  'course.type': 'Kies tipe kursus',
  'course.visibility': 'Kies sigbaarheid opsie',
  'course.title': 'Titel',
  'course.description': 'Beskrywing',
  'course.cover': 'Omslag',
  'course.start': 'Jou kursus begin op',
  'course.ends': 'Jou kursus eindig op',
  'course.curriculum': 'Kurrikulum',
  'course.members': 'Studente & onderwysers',
  'course.assignments': 'Assignments',
  'course.question.deleteWhole': 'Verwyder hele vraag',
  'course.question.yes': 'Ja',
  'course.question.no': 'Nee',
  'course.lesson.title': 'Les titel',
  'course.lesson.add.universe': 'Voeg Verhaal/Heelal by',
  'course.lesson.add.link': 'Voeg eksterne skakel by',
  'course.status': 'Status',
  'course.active': 'Activity',
  'course.active.message': 'Active',
  'course.inactive': 'Inactive',
  'course.module.edit': 'Edit module name',
  'course.upload.resource': 'Upload a file resource',
  'course.question.answer': 'Add answer',
  'course.question.open': 'Open question',
  'course.question.close': 'Closed question',
  'course.question.multiple': 'Multiple-choice question',
  'course.about': 'About this course',
  'course.lesson.new': 'Create a new lesson',
  'course.lesson.type': 'Lesson type',
  'course.lesson.inPerson': 'In person',
  'course.lesson.preRecorded': 'Pre-recorded',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Text only',
  'course.lesson.content': 'Lesson content',
  'course.lesson.description': 'Public description',
};
