export default {
    'genre.scifi': 'Wetenskapsfiksie',
    'genre.fantasy': 'Fantasie',
    'genre.adventure': 'Avontuur',
    'genre.poetry': 'Poetry',
    'genre.comedy': 'Komedie',
    'genre.drama': 'Drama',
    'genre.nonfiction': 'Non-fiction',
    'genre.fiction': 'Fiksie',
    'genre.romance': 'Romanse',
    'genre.satire': 'Satire',
    'genre.tragedy': 'Tragedie',
    'genre.crimi': 'Crimi',
    'genre.historical': 'Historical fiction',
    'genre.horror': 'Gruwel',
    'genre.mystery': 'Misterie',
    'genre.thriller': 'Riller',
    'genre.western': 'Western',
    'genre.memoir': 'Memoir',
    'genre.biography': 'Biografie',
    'genre.steampunk': 'Steampunk',
    'genre.mythology': 'Mythology',
    'genre.fairytale': 'Fairy tale',
    'genre.superhero': 'Superhero',
    'genre.children': 'Children'
};