export default {
  'personalNotes.personalNotes': 'Persoonlike Notas',
  'personalNotes.chooseType': 'Kies die tipe persoonlike nota',
  'personalNotes.storyNotes': 'Storie Notas',
  'personalNotes.chapterNotes': 'Hoofstuk Notas',
  'personalNotes.universeNotes': 'Heelal Notas',
  'personalNotes.encyclopediaNotes': 'Ensiklopedie Notas',
  'personalNotes.storyPersonalNotesHeading': 'Persoonlike Notas oor Stories',
  'personalNotes.encyclopediaPersonalNotesHeading': 'Persoonlike Notas oor Ensiklopedie',
  'personalNotes.searchPersonalNotesHeading': 'Soek Persoonlike Notas',
  'personalNotes.goToStory': 'Gaan na storie',
  'personalNotes.goToChapter': 'Gaan na hoofstuk',
  'personalNotes.goToEncyclopedia': 'Gaan na Ensiklopedie van die Heelal',
  'personalNotes.goToEncEntry': 'Gaan na inskrywing',
  'personalNotes.closeDropdown': 'Maak die dropdown toe',
  'personalNotes.chapterName': 'Hoofstuk {sequence} - {title}',
  'personalNotes.objectPersonalNotes': '{object} persoonlike nota',
  'personalNotes.searchResults': 'Soekresultate',
  'personalNotes.type.story': 'Storie',
  'personalNotes.type.universe': 'Heelal',
  'personalNotes.type.chapter': 'Hoofstuk',
  'personalNotes.type.encEntry': 'Ensiklopedie Inskrywing',
  'personalNotes.type.revTextBlock': 'Hersiening Teksblok',
  'personalNotes.chapter': 'Hoofstuk',
  'personalNotes.recentSearches': 'Onlangse Soek:'
};