export default {
    'workshop.title': 'Jou werk',
    'workshop.noneassigned': 'Jy is nog nie enige een toegewys nie.',
    'workshop.notavailable': 'Hierdie funksie is nog nie beskikbaar nie.',
    'workshop.none': `Jy het tans geen {type, select,
      universe {heelal}
      story {verhaal}
      fanfiction {fanfiksie}
      other {}
    }nie. Skep nou een!`,
    'workshop.collab': 'Samewerkende werk',
    'workshop.betareadings': 'Proeflesings',
    'workshop.translations': 'Vertalings',
    'workshop.createnew': 'Skep nuwe...',
    'workshop.story.standalone': 'Standalone storie',
    'workshop.story.standalone.desc': 'Hierdie is \'n enkelverhaal.',
    'workshop.controlpanel': '{name} beheerpaneel',
    'workshop.universe.page': 'Heelal bladsy',
    'workshop.fictionaltime': 'Fiktiewe tyd',
    'workshop.dashboard.name': '{name} paneel',
    'workshop.stories.in': 'Stories in {universe}',
    'workshop.universe.nostories': 'Daar is geen stories in hierdie heelal nie.',
    'workshop.story.chapter.add': 'Nuwe hoofstuk',
    'workshop.universe.new': 'Skep \'n nuwe heelal',
    'workshop.universe.publish': 'Publiseer heelal',
    'workshop.universe.publishing.notice': 'As jy die heelal nie publiseer nie, sal dit outomaties gepubliseer word wanneer die eerste verhaal wat verbind is met die heelal gepubliseer word.',
    'workshop.universe.settings': '{universe} heelal instellings',
    'workshop.universe.publishedOn': 'Hierdie heelal is gepubliseer op {date, date, long} {date, time, short}',
    'workshop.universe.description': 'Heelal beskrywing',
    'workshop.settings.title': 'Titel',
    'workshop.description': 'Beskrywing',
    'workshop.language.primary': 'Primêre taal',
    'workshop.publication.options': 'Publikasie opsies',
    'workshop.rating': 'Algemene gradering',
    'workshop.universe.rating.desc': 'Stories en fanfiksie bokant hierdie gradering sal weggesteek word van die heelal bladsy lys van anonieme gebruikers en gebruikers wat nie die gepaste ouderdom het nie.',
    'workshop.universe.license': 'Heelal lisensie',
    'workshop.universe.genre.pick': 'Kies genre vir die heelal',
    'workshop.story.genre.pick': 'Kies genres vir die storie',
    'workshop.cover': 'Omslag',
    'workshop.nothingtosee': 'Niks om hier te sien nie...',
    'workshop.story.cannon': 'Kanon verhaal',
    'workshop.story.cannon.desc': 'Hierdie verhaal is kanonies in {universe} heelal.',
    'workshop.story.cannon.desc.create': 'Hierdie verhaal sal geskep word as \'n kanoniese verhaal in {universe} heelal.',
    'workshop.story.fanfiction.search': 'Tik die naam van die heelal in (dit moet in jou biblioteek wees). En kies dan uit die voorstelle.',
    'workshop.story.error.nogenres': 'Jy moet ten minste een genre kies.',
    'workshop.story.error.toomanygenres': 'Slegs twee genres per storie is toegelaat.',
    'workshop.story.error.fanfiction.selectuniverse': 'Jy moet \'n oorspronklike heelal kies vir jou fanfiksie!',
    'workshop.story.error.tags.toomany': 'Jy kan slegs 10 etikette per storie hê.',
    'workshop.story.new': 'Skep \'n nuwe storie',
    'workshop.story.publishing.notice': 'Die storie sal outomaties gepubliseer word sodra jy die eerste hoofstuk publiseer.',
    'workshop.settings.edit': 'Wysig instellings',
    'workshop.story.publishedOn': 'Hierdie verhaal is gepubliseer op {date, date, long} {date, time, short}',
    'workshop.story.settings': 'Storie-instellings',
    'workshop.settings.basic': 'Basiese instellings',
    'workshop.settings.genres': 'Genres (maks. 2)',
    'workshop.story.license': 'Storie lisensie',
    'workshop.story.settings.universe': 'Heelal instellings',
    'workshop.settings.tags': 'Etikette',
    'workshop.revision': 'Hersiening',
    'workshop.revisions.title': '{story}: {chapter} Hersienings',
    'workshop.revisions.current': 'Huidige konsep',
    'workshop.revisions.new.beta': 'Skep \'n nuwe hersiening uit die konsep.',
    'workshop.revisions.new.public': 'Skep \'n nuwe openbare hersiening uit die konsep.',
    'workshop.revisions.toeditor': 'Gaan na die redakteur',
    'workshop.revisions.comments': 'Hersiening kommentaar',
    'workshop.revisions.comments.title': '{story}: {chapter} - Hersiening {revision} - Kommentaar',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {vir Beta lesers}
      readers {Publiek}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'Jy moet eers \'n hersiening skep.',
    'workshop.revisions.comments.select': 'Kies hersiening',
    'workshop.collaborators.noresults': 'Geen resultate nie',
    'workshop.collaborators.add.beta': 'Voeg Beta lesers by',
    'workshop.collaborators.add.collaborator': 'Voeg samewerker by',
    'workshop.collaborators.add.translator': 'Voeg vertaler by',
    'workshop.collaborators.language.add': 'Skep \'n nuwe vertaling',
    'workshop.translations.stories': 'Vertalings - stories',
    'workshop.translations.universes': 'Vertalings - universes',
    'workshop.revisions.beta.none': 'Geen hersienings op hierdie stadium nie.',
    'reader.asidetoggle': 'Skakel asid inligting',
    'workshop.translation.original': 'Oorspronklik:',
    'workshop.translation.original.title': 'Oorspronklike titel:',
    'workshop.translation.original.description': 'Oorspronklike beskrywing:',
    'workshop.translation.original.cover': 'Oorspronklike omslag',
    'workshop.translation.original.tags': 'Oorspronklike etikette',
    'workshop.cover.alt': 'omslagbeeld',
    'workshop.translation.updatedOrig': 'Laaste opdatering van oorspronklike: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'Laaste opdatering van vertaling: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'Laaste hersiening {revision, number}, van oorspronklike: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'Laaste hersiening {revision, number}, van vertaling: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `Om meer {type, select,
    collaborator {kolaborateurs}
    beta {beta lesers}
    translator {vertalers}
    other {}
  }by te voeg, moet jy jou lidmaatskapvlak verhoog.`,
    'workshop.collaborators.requests.sent': 'Gestuurde versoeke',
    'workshop.collaborators.requests.invite': `Jy is genooi om {role, select,
    beta {beta leser}
    translator {vertaler}
    collaborator {kolaborateur}
    other {}
  } te word vir die volgende:`,
    'workshop.collaborators.requests.dashboard': `Jy is genooi om saam te werk aan {count, plural,
    zero {geen werk}
    one {een letterkundige werk}
    other {# letterkundige werke}
  }.`,
    'workshop.collaborators.language.added': 'Taal bygevoeg',
    'workshop.story.noChaptersFound': 'Geen hoofstukke gevind nie.',
    'workshop.fanfic.needUniverseInLibrary': 'Daar is baie heelalle daar buite. Voeg asseblief die een waarin jy wil skryf by in jou biblioteek sodat ons dit kan vind.',
    'workshop.fanfic.findUniverse': 'Gaan vind \'n wonderlike heelal!',
    'workshop.encSettings': 'Ensiklopedie-instellings',
    'workshop.collaborators.removeUser': 'Verwyder gebruiker',
    'workshop.collaborators.cancelInvite': 'Kanselleer uitnodiging',
    'workshop.universe.createFirstStory': 'Skep die eerste storie',
    'workshop.storylines': 'Storilyne',
    'workshop.scenesManager': 'Toneelbestuurder',
    'workshop.collaborators.addRoleForLang': 'Voeg {role} by vir {language}',
    'workshop.beta.revisionInfo': 'Hierdie is hersiening {revision, number}, geskep op {createdAt, date, long}.',
    'workshop.story.notes.title': 'Jou notas vir {storyTitle}',
    'workshop.story.notes.desc': 'Oorsig notas vir die storie.',
    'workshop.story.notes.tile': 'Oorsig notas',
    'workshop.hideOrgs': 'Versteek inhoud van organisasies',
    'workshop.translation.premium': 'Om vertalings by te voeg, moet jy ten minste \'n Explorer intekening hê.',
    'workshop.story.finished': 'Storie is voltooi',
    'workshop.story.publishing.externalSellingNotice': 'Aangesien jy buite die Literêre Heelal verkoop, kan jy die storie nou publiseer. Skakels na jou winkelvermelding sal verskyn op die storie of aan die einde van die huidige storie wat jy hier publiseer.',
    'workshop.sharing.publicURL': 'Openbare weergawe',
    'workshop.fictionalTime.title': 'Fiktiewe tye vir {universeName}',
    'workshop.fictionalTime.none': 'Jy het tans geen fiktiewe tye opgestel nie.',
    'workshop.fictionalTime.createNow': 'Skep een nou!',
    'workshop.fictionalTime.createTitle': 'Skep \'n nuwe fiktiewe tyd',
    'workshop.fictionalTime.editTitle': 'Wysig {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'Tydnaam',
    'workshop.fictionalTime.basicInfo': 'Basiese inligting',
    'workshop.fictionalTime.timeSetup': 'Tydopstelling',
    'workshop.fictionalTime.linkedToET': 'Begin hierdie tyd op \'n Aardse datum (Gregoriaanse kalender)?',
    'workshop.fictionalTime.timeDeclaration': 'Tydverklaring',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'Voor eenhede',
    'workshop.fictionalTime.declarationAfter': 'Na eenhede',
    'workshop.fictionalTime.declarationNone': 'Geen',
    'workshop.fictionalTime.units': 'Eenhede',
    'workshop.fictionalTime.ETStart': 'Begin datum van hierdie tyd',
    'workshop.fictionalTime.unitsDescFirst': 'Hoeveel eenhede is daar in hierdie eenheid vanaf millisekondes?',
    'workshop.fictionalTime.unitsDesc': 'Hoeveel eenhede is hierdie een van die vorige eenheid?',
    'workshop.fictionalTime.unitsName': 'Eenheidsnaam',
    'workshop.fictionalTime.unitsSeparator': 'Skeier van vorige eenheid',
    'workshop.fictionalTime.unitAdd': 'Voeg eenheid by',
    'workshop.fictionalTime.clocks': 'Horlosies',
    'workshop.fictionalTime.unitTransfer': 'Oordrag eenhede',
    'fictionalTime.pageStartElapsedTime': 'Tyd verloop sedert die opening van hierdie bladsy',
    'fictionalTime.currentTime': 'Huidige tyd',
    'workshop.shoppingExternal.options': 'Eksterne koopopsies',
    'workshop.shoppingExternal.explainer': 'As jou storie elders verkoop word, kan jy die skakels hier instel. Die skakels sal dan wys in plaas van die inhoud of aan die einde van die inhoud wat jy kies om vooraf te kyk.',
    'workshop.shoppingExternal.amazonStore': 'Amazon-winkel',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Winkel Naam',
    'workshop.shoppingExternal.itemUrl': 'Item-URL',
    'workshop.shoppingExternal.storesOther': 'Ander winkels',
    'fictionalTime.units.milliseconds': '{units, number} millisecondes',
    'fictionalTime.countdownToStart': 'Aftelling tot tyd begin',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 dag }
      other {{days} dae }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {sekonde}
      other {sekondes}
    }}
    minutes {{units, plural,
      one {minuut}
      other {minute}
    }}
    hours {{units, plural,
      one {uur}
      other {ure}
    }}
    days {{units, plural,
      one {dag}
      other {dae}
    }}
    years {{units, plural,
      one {jaar}
      other {jare}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'Vanaf',
    'fictionalTime.inputSelectTimeUnit': 'Kies tydeenhede',
    'fictionalTime.inputSelectETUnit': 'Kies Aardse tydeenheid',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Kantbalk-gereedskapkas',
    'workshop.writerSidebar.description': 'Welkom by jou storie! Hierdie kantbalk gee jou maklike toegang tot alle hulpbronne wat verband hou met jou storie. Kyk na die ikone hierbo om die nuutste kommentaar, jou notas en baie meer te sien!',
    'workshop.story.authorsNotesExplained': 'Jou notas vir die lesers om aan die begin van die hoofstuk te lees.',
    'workshop.story.chapterSortSwitch': 'Wissel die volgorde van die hoofstukke.',
    'workshop.universe.monetizationTitle': '{title} monetisering',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} monetisering',
    'workshop.universe.monetizationWebMonetization': 'Web Monetization',
    'workshop.webMonetization.explain': 'Web Monetization sal betalings aan jou stroom op grond van hoeveel tyd \'n gebruiker deurbring op jou inhoud. In jou profiel monetisering instellings kan jy jou eie betalingsaanwyser stel. Hier kan jy besluit oor \'n verdeel met jou medewerkers wat Web Betaling geaktiveer het. Literary Universe neem outomaties 10%.',
    'workshop.webMonetization.revShare': 'As gevolg van die beperking van Web Monetization word probabilistiese inkomste-deling gebruik. Probabilistiese inkomste-deling werk deur willekeurig te kies uit \'n lys van vooraf gedefinieerde betalingsaanwysers elke keer as \'n web gemonetiseerde besoeker jou bladsy laai. Die besoeker betaal aan die gekose aanwyser totdat die bladsy herlaai of gesluit word.',
    'workshop.webMonetization.revShareMore': 'Leer meer oor Probabilistiese Inkomste-deling. Ons gebruik dieselfde kode as op daardie bladsy.',
    'workshop.story.notEligible.licence': `Die lisensie van die verhaal staan nie monetisering toe nie.`,
    'workshop.universe.notEligible.licence': `Die lisensie van die heelal staan nie monetisering toe nie.`,
    'workshop.story.notEligible.fanFiction': 'Fan Fiksie stories kom nie in aanmerking vir monetisering nie.',
    'workshop.revShare.mustBe100': 'Deel moet gelyk wees aan 100%',
    'workshop.revShare.LUCut': 'Literary Universe & betalingshek',
    'workshop.revShare.unallocated': 'Ongeallokeerde deel {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'Onbeslis',
    'workshop.revShare.origLangCreators': 'Oorspronklike taal skeppers',
    'workshop.story.prolog': 'Proloog',
    'workshop.story.chapter': 'Hoofstuk {sequence, number}',
    'workshop.work.includesAds': 'Is daar enige advertensies of produkplasings in die werk?',
    'workshop.universe.forumSettings': 'Interne universum forum instellings',
    'workshop.universe.forum': 'Interne {universeName} forum',
    'workshop.ratingAdjusted': 'As gevolg van klagtes moes ons jou waardering aanpas na die een wat ons gepas geag het. As sulks is die verandering van die waardering nou gedeaktiveer.',
    'workshop.selectCollaborator': 'Kies samewerker',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Konsep',
    'workshop.chapterStatus.scheduled': 'Geskeduleer',
    'workshop.chapterStatus.published': 'Gepubliseer',
    'workshop.story.continuedIn': 'Watter stories gaan voort met hierdie storie?',
    'workshop.story.continuedPlaceholder': 'Kies storie uit hierdie heelal',
    'workshop.universe.isAIGenerated': 'Word die inhoud van die heelal deur KI gegenereer?',
    'workshop.universe.isAIGeneratedTooltip': 'Laat weet ons asseblief of enige van die inhoud in die heelal gegenereer is deur of met die hulp van KI. Ons gebruik hierdie inligting vir korrekte etikettering en as gevolg van hoe KI-programme gegenereer word, mag daar sekere beperkings en beperkings wees.',
    'workshop.story.isAIGenerated': 'Word die storie deur KI gegenereer?',
    'workshop.story.isAIGeneratedTooltip': 'Laat weet ons asseblief of enige van die storie gegenereer is deur of met die hulp van KI. Ons gebruik hierdie inligting vir korrekte etikettering en as gevolg van hoe KI-programme gegenereer word, mag daar sekere beperkings en beperkings wees.',
    'workshop.publicationAgreement.aria': 'Publikasie-ooreenkoms vir werk',
    'workshop.publicationAgreement.intro': 'Ons is bly dat jy gekies het om jou kreatiewe werk by ons te publiseer. Voordat ons voortgaan, vra ons jou net om ons publikasie-ooreenkoms deur te lees, sodat jy kan verstaan wat dit vanuit die regskant beteken.',
    'workshop.sortChapters': 'Sorteer volgorde:',
    'workshop.sortChapters.ascending': 'Van begin af',
    'workshop.sortChapters.descending': 'Van die nuutste',
    'workshop.sortChapters.aria': 'Kies vir watter manier om hoofstuklys te sorteer',
    'workshop.hiatus.btn': 'Verander storie status na Hiatus',
    'workshop.cancelled.btn': 'Verander storie status na Gekanselleer',
    'workshop.complete.btn': 'Verander storie status na Voltooid',
    'workshop.statusChange.modalTop': 'Is jy seker jy wil die status verander na',
    'workshop.statusName.hiatus': 'Hiatus',
    'workshop.statusName.cancelled': 'Gekanselleer',
    'workshop.statusName.completed': 'Voltooid',
    'workshop.statusExplain.hiatus1': 'Hiatus beteken dat jy vir \'n rukkie wegstap van die werk aan hierdie storie vir enige rede. Dit sal jou lesers vertel dat hulle nie nuwe opdaterings in die komende weke of selfs tot \'n paar maande kan verwag nie.',
    'workshop.statusExplain.hiatus2': 'Die hiatus-status sal outomaties opgehef word as jy enige hoofstuk publiseer. Of jy kan dit self verander.',
    'workshop.statusExplain.hiatus3': 'As jy jou storie vir ses maande in hiatus hou, sal ons dit outomaties as gekanselleer merk.',
    'workshop.statusExplain.cancelled1': 'Ons is jammer om te hoor dat jy nie kan voortgaan om aan die storie te werk nie. Aan die ander kant is ons bly dat jy bereid is om jou lesers te laat weet.',
    'workshop.statusExplain.cancelled2': 'Om die storie te kanselleer sal jou lesers laat weet dat hulle nie nuwe opdaterings kan verwag nie.',
    'workshop.statusExplain.cancelled3': 'Jy kan dit altyd terugdraai deur \'n hoofstuk te publiseer of die status te verander.',
    'workshop.statusExplain.finished1': 'Gelukwens! Na al daardie harde werk het jy uiteindelik die einde van \'n ongelooflike reis bereik. Terwyl die storie nou mag eindig, hoop ons dat daar in die toekoms nog meer stories sal wees om te vertel, maar vir nou, ontspan en geniet die welverdiende rus.',
    'workshop.statusExplain.finished2': 'Om die storie as voltooid te merk, sal dit aan die lesers sê dat die storie klaar is. Alhoewel jy nie nuwe hoofstukke moet byvoeg nie, sal ons jou nie keer nie en dit is nie \'n slegte idee om spesiale hoofstukke by te voeg nie, byvoorbeeld om meer epiloge vir al die karakters by te voeg nie.',
    'workshop.statusExplain.finished3': 'Alhoewel jy hierdie status altyd kan kanselleer, beveel ons sterk daarteen. As die storie moet voortgaan, is dit dalk beter om \'n nuwe storie te begin.',
    'workshop.status.goActive': 'Maak die storie weer aktief',
    'workshop.statusChangeEmail.storyIntro': 'Ons wil jou graag inlig dat jou storie:',
    'workshop.statusChangeEmail.hiatusTitle': 'Jou storie status is outomaties na hiatus gestel',
    'workshop.statusChangeEmail.hiatusIntro': 'As gevolg van onaktiwiteit is jou storie status outomaties na hiatus gestel.',
    'workshop.statusChangeEmail.hiatusWhy': 'Dit is outomaties op hiatus geplaas as gevolg van geen nuwe hoofstuk wat in die afgelope 6 maande gepubliseer is.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'Hierdie status sal outomaties opgehef word as jy \'n nuwe hoofstuk publiseer. As jy nie binne die volgende 6 maande \'n nuwe hoofstuk publiseer nie, sal ons die storie outomaties as gekanselleer stel.',
    'workshop.statusChangeEmail.cancellationIntro': 'Jou storie status is outomaties na gekanselleer gestel.',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'Hierdie status sal outomaties opgehef word as jy \'n nuwe hoofstuk publiseer. As jy nie van plan is om aan hierdie storie te werk nie, hoef jy niks anders te doen nie.',
    'workshop.startCreating': 'Begin skep',
    'workshop.ownWork': 'Eie werk',
    'workshop.list.thumbs': 'Duimnaillys',
    'workshop.list.list': 'Kort lys',
    'workshop.fanfiction.new': 'Skep \'n nuwe fanfiksie',
    'workshop.videoTrailerLink': 'Skakel na video-aankondiging',
    'workshop.videoTrailerPlayerTitle': 'Spel video-aankondigingspeler',
    'workshop.videoTrailer.supportedPlaftorms': 'Ons ondersteun Youtube, Vimeo en Odysee',
    'workshop.videoTrailer.rumble': 'Ons ondersteun ook Rumble, maar onthou om die IFRAME URL te kopieer.',
    'workshop.videoTrailer.suggestPlatforms': 'Is jou video platform afwesig, laat ons weet via ons <a>terugvoer</a>!',
    'workshop.cover.edit': 'Change cover',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.',
    'workshop.license.exclusiveUniverse': 'The universe uses an exclusive license, which means that all stories also have to follow the same license in order to prevent legal chaos.'
};