export default {
  'courses.courses': 'Courses',
  'courses.overview': 'コースの概要',
  'course.create': '新しいコースを作成する',
  'course.reading.title': 'Reading assignment title',
  'course.question.add': 'Add question',
  'course.add.module': 'Add module',
  'course.lessons.newMessage': 'Create and organize your lessons for effective teaching',
  'course.reading.new': 'Reading Assignment',
  'course.reading.newMessage': 'Create and organize reading assignments for your students',
  'course.writing.new': '作文課題',
  'course.writing.newMessage': 'Quickly set up and distribute writing tasks',
  'course.question.text': 'ここに質問を入力してください',
  'course.question.type': 'Please select a type of question',
  'course.question.delete': 'Remove question',
  'course.type': 'コースの種類を選択してください',
  'course.visibility': '表示オプションを選択してください',
  'course.title': 'タイトル',
  'course.description': 'あらすじ',
  'course.cover': 'カバーアート',
  'course.start': 'コースの開始日',
  'course.ends': 'コースの終了日',
  'course.curriculum': 'カリキュラム',
  'course.members': '生徒と教師',
  'course.assingments': '課題',
  'course.question.deleteWhole': '質問全体を削除する',
  'course.question.yes': 'はい',
  'course.question.no': 'いいえ',
};
