export default {
    'genre.scifi': 'SF',
    'genre.fantasy': 'ファンタジー',
    'genre.adventure': 'アドベンチャー',
    'genre.poetry': '詩',
    'genre.comedy': 'コメディー',
    'genre.drama': 'ドラマ',
    'genre.nonfiction': 'ノンフィクション',
    'genre.fiction': 'フィクション',
    'genre.romance': 'ロマンス',
    'genre.satire': '風刺',
    'genre.tragedy': '悲劇',
    'genre.crime': 'Crime',
    'genre.historical': '歴史小説',
    'genre.horror': 'ホラー小説',
    'genre.mystery': 'ミステリー小説',
    'genre.thriller': 'スリラー小説',
    'genre.western': '西部劇',
    'genre.memoir': '自叙伝',
    'genre.biography': '伝記小説',
    'genre.steampunk': 'スチームパンク小説',
    'genre.mythology': '神話',
    'genre.fairytale': 'おとぎ話',
    'genre.superhero': 'スーパーヒーロー物語',
    'genre.children': '子ども向け',
    'genre.postapocalyptic': '終末ものフィクション',
    'genre.political': '政治関連書',
    'genre.history': '歴史',
    'genre.isekai': '異世界',
    'genre.scifi.description': 'Science fiction is a literary genre that explores speculative or futuristic concepts, often incorporating scientific and technological elements. It often deals with imaginative and futuristic concepts, such as advanced science and technology, space exploration, time travel, parallel universes, and extraterrestrial life. Science fiction often delves into social, political, and philosophical issues, reflecting and commenting on contemporary society. It can be categorized into sub-genres such as cyberpunk, hard science fiction, dystopian fiction, and space opera, among others.',
    'genre.fantasy.description': 'ファンタジー小説は、魔法、超常現象、伝説上の怪物などが登場して想像上の世界で展開される物語です。物語の中には善と悪を追求する戦いに挑むヒーローや、一人前になるまでのある主人公を題材にすることもあります。ファンタジーも、ハイファンタジー、アーバンファンタジー、ダークファンタジー、おとぎ話などに分けられます。それら物語は、道徳心、倫理観をテーマにしたり、さらには善と悪の本質について語るものもあります。',
    'genre.adventure.description': 'アドベンチャー小説は、心躍らせるもの、危険を伴う旅や探検で、体を張ったアクション、チャレンジなどが。現実の世界、または、架空の世界を舞台にしたものや探検、宝探し、難解に立ち向かいながら生存することを描いた物語です。アドベンチャー小説は、一人の英雄、または複数のヒーロー達が困難に直面しつつも、時には知恵と優れた身体能力で障害を乗り越える様子を描いています。このジャンルは剣者物語、生還物語、スパイフィクション等にさらに分かれます。',
    'genre.poetry.description': '詩は、高度に構成された言い回しで感情、考え、想像を伝え・表現する文学です。詩の中には、韻律、音韻、比喩表現を用いて独特で影響力のある詩を生み出すこともあります。詩の表現方法は、短詩、俳句、自由詩、バラッドなどさまざまです。',
    'genre.comedy.description': 'コメディ小説は、ユーモアや、ウイット、風刺を通じて人をもてなしたり楽しませる、最も古い文学の一つです。観客からの笑いや喜びを引き出そうと、時には大げさにキャラクターを演出したり、場面設定をすることがあります。コメディは、演劇、小説、映画など様々な形で表現されますが、テーマは社会通念、人間関係、文化の違いなどがあり、面白おかしくコメントを述べたり現代の課題を取り上げることもあります。',
    'genre.drama.description': '芝居は、時に複雑なキャラクターや葛藤を対話や演技で語る古い文学の一つで、演劇や、映画、テレビなど、その演出方法は多くあります。芝居は、人間関係や人の感情を表したり、愛や裏切り、また悲しみをテーマにすることもあります。また、社会論評、現代が抱える問題や姿勢を反映することもあります。',
    'genre.nonfiction.description': 'ノンフィクションは、現実にあった出来事や人、また、本当に経験したことを述べた文学です。このジャンルの文学は回顧録から伝記、随筆、ジャーナリズム、また、歴史的記述に至るまで幅広いものがあります。ノンフィクションは、伝えること、教育すること、読者に納得してもらうこと、事実を明確かつ人を引き付ける方法で伝えることを目的としていることがよくあります。内容は、社会面、政治面、科学に関して、あるいは、文化的課題にまで及び、また、人類の状態について知見を述べるものもあります。',
    'genre.fiction.description': 'フィクションは、創作話、架空の登場人物、そして出来事に関連する文学で、よくサイエンスフィクションやファンタジーの部類と区分けされます。この文学は、小説、短編小説、中編小説などその形式は様々で、そこに描かれる内容は、恋愛や喪失、そして償いなどを体験した人間模様を描く場合がよくあります。サイエンスフィクションやファンタジー小説とは違い、フィクションは、超常的、あるいは、推測的な要素は絡めない現実的な日常をもとに描かれています。とはいえ、フィクションとその他の文学とジャンルとして重なり合う部分もあり、このジャンルの文学は複数のジャンルに当てはめることもできます。',
    'genre.romance.description': 'ロマンスは、ロマンティックな恋愛や登場する人物との関係に焦点を当てたジャンルの文学です。ロマンス文学は2人の登場人物が一緒になるのに越えなければならない障害や葛藤を描く中心的なラブストーリーです。中には、情熱、裏切り、償いをテーマとしたものもあり、古代ロマンス、現代ロマンス、パラノーマルロマンスなどにジャンル分けされるものもあります。',
    'genre.satire.description': '風刺は、社会や政治、または個人の不備、不道徳さをユーモアや皮肉、誇張を用いて批判したり、暴いているジャンルの文学です。主な目的は批判的なメッセージ、根本的な社会論評です。それとは別に、コメディは、ユーモア、ウイット、風刺を通じて人をもてなしたり楽しませることを目的としたジャンルです。コメディが社会通念や人間関係をユーモラスに展開する一方で、必ずしも批判的なメッセージや根本的な社会論評を伝えているということではありません。風刺はどちらかというととげとげしく批判的なものであることがよくある反面、コメディはより愉快で陽気なものとなっています。',
    'genre.tragedy.description': 'Tragedy is one of the oldest literary genres that portrays the downfall or suffering of a tragic hero or heroine due to a fatal flaw or an unfortunate circumstance. It often evokes feelings of pity and fear in the reader or audience, and may explore themes such as fate, destiny, and the human condition. Tragedy aims to provide a cathartic experience for the audience and often has a moral or philosophical message.',
    'genre.crime.description': '犯罪小説は、殺人、窃盗など違法行為など犯罪にまつわる捜査、犯罪行為、犯罪解決と展開する内容の文学です。犯罪小説に登場する人物は複雑な性格、奇妙な動機、複雑な関係性をはらむことがあり、その内容は、正義、道徳心、人間の精神をテーマにする場合もあります。このタイプの小説は犯罪が解決したとき、または、正義が果たされたとき、読者に終幕感を与えることがあります。',
    'genre.historical.description': 'Historical fiction is a literary genre that is set in the past and uses fictional characters and events to explore historical events, cultures, and customs. It often involves extensive research to ensure historical accuracy and may incorporate real-life figures or events. It aims to transport the reader or audience to a different time and place, while also providing insight into the human experience across history.',
    'genre.horror.description': 'ホラーは、読者や観客に強い恐怖感、畏怖の念、嫌悪感を抱かせることを目的としたジャンルの文学です。その中には、幽霊、モンスターといった不可思議で解釈しがたいものが登場し、死や怒り，または未知なるものをテーマにすることもあります。ホラー小説は観客の直感的反応を駆り立て、社会的不安や恐怖を描いていることもあります。',
    'genre.mystery.description': 'ミステリーは、解決すべき犯罪や謎を展開するフィクションのジャンルです。主人公は刑事や素人探偵である場合がよくあり、ミステリーには通常、事件の手掛かり、容疑者、最終的に容疑者に吐かせるなど、ミステリーの解決策といったものが要素となっていることがあります。このジャンルはサスペンス、犯罪、心理的なスリラーの要素が含まれることもあります。',
    'genre.thriller.description': 'スリラーは、読者が緊張やわくわく感、不安を感じるように構成されたフィクションのジャンルです。通常、大金が絡んでいたり、危険で激しいアクションなども起こるスリラー小説は、さらにスパイ小説、法律や医療、また心理的スリラーなどサブジャンルとして広範囲に及びます。このジャンルが目指すものは、読者をハラハラドキドキさせてストーリのとりこになってもらうことです。',
    'genre.western.description': 'ウェスタン小説は、昔のアメリカ西部を舞台にカウボーイ、用心棒、そして保安官が主な登場人物として繰り広げるフィクションです。このジャンルの作品は、文明化が開拓地にも広がる時代の名誉、正義、個人主義をテーマとすることもある。ウェスタン小説はさらに、伝統的な西部劇、修正主義西部劇、またはスパゲティうウェスタンに分類される。',
    'genre.memoir.description': '回顧録はノンフィクション小説で、一人の人生やある特定の時代の人々を語ったものです。生涯について述べた自叙伝と違い、回顧録は特定の側面や出来事に焦点を当てたり、文学的テクニックを用いて人を動かす感動的な話を伝えます。回顧録は、有名人から一般人と、誰でも書くことができ、その内容や体験談もとても広範囲に及びます。',
    'genre.biography.description': '伝記は、ある人の生涯を伝えるノンフィクション小説です。ある特定の時代や、ある特定の人の一面に焦点を当てた回顧録とは違い、伝記小説はその人の一生涯を大観的に語ることを目的としています。伝記は歴史上の人物から現代の著名人に至るまで書かれ、政治面、文化面、スポーツ面とさらにジャンルを分けることができます。',
    'genre.steampunk.description': 'スチームパンクは、ビクトリア朝時代の美と、テクノロジー、文化を未来志向でファンタスティックに融合させたフィクションのジャンルです。通常、話の舞台は19世紀に置き換えられていて、スチームパンクには、蒸気機械やゼンマイ仕掛けの機械、飛行船などが登場します。このジャンルは、スチームパンクミステリーやスチームパンクロマンスなど、幅広いサブジャンルに展開されます。',
    'genre.mythology.description': '神話集は神話、伝説、また、特定の文化・社会に関する物語を指します。その中には、神、女神、英雄や怪物も登場して、文化的信仰心を伝えるものもあります。ギリシャ神話、北欧神話、世界の神話とさらにジャンルが分かれます。',
    'genre.fairytale.description': 'おとぎ話は、魔法や、空想の生き物が登場し、うっとりするような設定で描かれるフィクションのジャンルです。対象は子供であることが多く、おとぎ話は通常、道徳や教訓を扱い、世界中で語りづかれたものである場合もあります。このジャンルは、伝統的なおとぎ話、現代版に書き直されたもの、ダークなおとぎ話など、幅広いサブジャンルがあります。',
    'genre.superhero.description': 'Superhero is a genre of fiction that typically features characters with extraordinary abilities or powers who use them to protect the world from evil or harm. Often wearing distinctive costumes or masks, superheroes can embody a variety of ideals and values, such as justice, compassion, or freedom. The genre can encompass a wide variety of sub-genres, such as superhero team-ups, origin stories, or alternate universes.',
    'genre.children.description': '子供向け文学書は乳幼児から10代始めの特に年例の若い人を対象にしています。これら作品はトピック、テーマも幅広くアドベンチャーやファンタジー、また文学を通じて子供たちへの教育、道徳を伝えるものもあります。子供向け文学作品の目的は、年齢の若い読者に本を好きになってもらえるよう育成しつつ、読書を楽しみ、読み物に触れ、読書を通じて教育をしていくことです。',
    'genre.postapocalyptic.description': 'This sub-genre of science fiction or speculative fiction is set in a world or society after a catastrophic event has occurred, such as a global disaster, war, or pandemic. Post-apocalyptic stories often explore themes of survival, adaptation, and rebuilding, with characters fighting to survive against harsh environments and societal breakdowns. Often bleak and harrowing, these stories can also offer a glimmer of hope for humanity\'s future.',
    'genre.political.description': '文書は、政治や社会問題、また、芸術的施策といったものを主に扱っています。',
    'genre.history.description': '歴史的文書や、その他歴史に関する重要事項・出来事を描いた作品',
    'genre.isekai.description': 'This sub-genre of Japanese light novels, manga, and anime revolves around a character being transported or reincarnated into a different world or alternate universe. The protagonist must navigate and adapt to the new world\'s unique cultures and environments, often gaining new abilities and encountering new allies and enemies along the way. These stories can range from light-hearted and comedic to dark and intense, but always offer a fresh and imaginative take on classic adventure themes.'
};