/**
 * Licenses for creative works
 * https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
 */
export default {
    'licenses.about': 'ライセンスについて',
    'licenses.more': '詳しくは',
    'licenses.legal': '法的書類',
    'licenses.name.cc-by': 'クリエイティブ・コモンズ　表示 4.0',
    'licenses.cc-by': 'このライセンスはあなたのオリジナル作品が評価されると商業目的であっても、あなたの作品を配布、リミックス、微調整、構築することができます。このライセンスは、提供されているライセンスの中で最も順応性があり、許可された作品を最大限に普及させ、使用するために推奨されたものです。',
    'licenses.name.cc-by-sa': 'クリエイティブ・コモンズ　表示 - 継承 4.0',
    'licenses.cc-by-sa': 'このライセンスは、商用目的であっても、あなたのクレジットを表示し、同じ条項で新しい創作物をライセンスする限り、他の人があなたの作品をリミックスし、微調整し、構築することを許可します。このライセンスは、しばしば「コピーレフト」フリーソフトウェアやオープンソースソフトウェアのライセンスと比較されます。あなたの作品を元にした新しい作品はすべて同じライセンスが適用されるので、派生物も商用利用が許可されます。これはウィキペディアで使われているライセンスであり、ウィキペディアや同様のライセンスのプロジェクトのコンテンツを取り入れることで利益を得るような資料には推奨されます。',
    'licenses.name.cc-by-nd': '表示 - 改変禁止 4.0',
    'licenses.cc-by-nd': 'このライセンスでは、あなたのクレジットを表示し変更しない限り、商用・非商用を問わず再配布が可能です。',
    'licenses.name.cc-by-nc': 'クリエイティブ・コモンズ　表示 - 非営利 4.0',
    'licenses.cc-by-nc': 'このライセンスは、他の人があなたの作品をリミックスし、微調整し、非商業的に構築することを許可するもので、その新しい作品はあなたを認め、非商業的でなければなりませんが、その二次的著作物を同じ条件でライセンスする必要はありません。',
    'licenses.name.cc-by-nc-sa': 'クリエイティブ・コモンズ　表示 - 非営利 - 継承 4.0',
    'licenses.cc-by-nc-sa': 'このライセンスは、あなたのクレジットを表示し、同一の条件で新しい作品をライセンスする限り、他の人があなたの作品を非商業的にリミックス、微調整、構築することを許可するものです。',
    'licenses.name.cc-by-nc-nd': 'クリエイティブ・コモンズ表示 - 非営利 - 改変禁止 4.0',
    'licenses.cc-by-nc-nd': 'このライセンスは、私たちの6つの主要なライセンスの中で最も制限が厳しく、あなたのクレジットを表示する限り、他の人があなたの作品をダウンロードし、他の人と共有することのみを許可しますが、いかなる方法によっても変更したり、商業的に使用したりすることはできません。',
    'licenses.name.lu-c': 'Lieterary Universeの著作権について',
    'licenses.lu-c': '標準的な完全著作権ライセンスで、あなたの作品を好きなように販売したり、出版したりすることができ、その権利が保護されます。また、このライセンスでは、Literary Universeでの販売も可能です。',
    'licenses.name.lu-e': '文学ユニバース独占',
    'licenses.lu-e': '本ライセンスは、リテラリーユニバースに対し、あなたの作品をオンラインで出版・頒布する独占的権利を許諾するものです。著作権はお客様に帰属しますが、作品をオンラインで出版・頒布する権利はリテラリーユニバースに帰属します。',
    'licenses.name.lu-ne': '文学ユニバース非独占',
    'licenses.lu-ne': '本ライセンスは、Literary Universeに対し、あなたの作品をオンラインで出版・頒布する非独占的権利を付与するものです。あなたは著作権を保持し、あなたの作品を他のルートで出版・配布する権利を保持します。',
    'licenses.name.cc0': '著作権なし CC0 1.0 全世界',
    'licenses.cc0': 'あなたの作品をパブリックドメインに。CC0は、著作権者が著作権を保持したまま、様々な許可を選択できるCCライセンスとは対照的に、著作権やデータベース保護、そしてクリエイターに自動的に付与される排他的権利を放棄するという、まったく別の選択を可能にします。',
    // License Chooser Modal
    'licenses.chooser.title': 'ライセンス・チューザー',
    'licenses.chooser.button': 'ライセンス選びを手伝ってください',
    'licenses.chooser.ariaLabel': '作品のライセンスを選択する',
    'licenses.chooser.introduction': 'このツールは、あなたの作品に最も適したライセンスを選択するのに役立ちます。ライセンスは、他の人があなたの作品をどのように使用できるかを決定し、Literary Universeでそれを収益化する能力に影響を与えます。',
    // License Chooser Wizard Steps
    'licenses.chooser.step.contentType.title': 'どのようなタイプのコンテンツをライセンス供与していますか？',
    'licenses.chooser.step.contentType.description': 'コンテンツの種類によって、利用できるライセンスが異なります。',
    'licenses.chooser.step.contentType.original': 'オリジナル作品',
    'licenses.chooser.step.contentType.fanfiction': 'ファン・フィクション',
    'licenses.chooser.step.contentType.fanfictionNote': 'Literary Universeのファンフィクション作品には、自動的にクリエイティブ・コモンズ表示-非営利ライセンス（CC BY-NC）が付与されます。これは、ファンフィクションは他者が所有する著作物を元にしており、商用利用はそれらの権利を侵害する可能性があるためです。',
    'licenses.chooser.step.commercial.title': '作品を収益化したいですか？',
    'licenses.chooser.step.commercial.description': '作品の収益化を選択することは、どのライセンスが最も適切であるかに影響する。',
    'licenses.chooser.step.commercial.yes': 'はい、自分の仕事を収益化したいです。',
    'licenses.chooser.step.commercial.no': 'いや、自分の仕事をマネタイズしたいとは思わない',
    'licenses.chooser.step.commercial.monetizeNote': 'Literary Universeで作品を収益化するには、いずれかの商用ライセンスをご利用いただく必要があります。これらのライセンスにより、著作権保護を維持したまま作品を販売することができます。',
    'licenses.chooser.step.exclusivity.title': 'リテラリーユニバースで独占的に出版したいですか？',
    'licenses.chooser.step.exclusivity.description': '独占権を選択すると、プラットフォーム料金や出版オプションに影響する。',
    'licenses.chooser.step.exclusivity.yes': 'はい。',
    'licenses.chooser.step.exclusivity.no': 'いや、他の場所でも発表したい',
    'licenses.chooser.step.exclusivity.exclusiveNote': 'Literary Universeでの独占出版では、10％という低いプラットフォーム手数料の恩恵を受けることができます。つまり、収益の90％があなたの手元に残ります。',
    'licenses.chooser.step.exclusivity.nonExclusiveNote': '非独占出版では、他のプラットフォームでも作品を出版することができます。プラットフォーム手数料は30％で、リテラリーユニバースでの収益の70％があなたの手元に残ります。将来的には、リテラリーユニバースから直接他のプラットフォームへ出版するためのツールを提供する予定です。',
    'licenses.chooser.step.derivatives.title': '他人が二次的著作物を創作することを許可しますか？',
    'licenses.chooser.step.derivatives.description': '二次的著作物には、あなたのオリジナル作品の翻案、リミックス、変形が含まれます。',
    'licenses.chooser.step.derivatives.yes': 'はい、二次的著作物を許可します',
    'licenses.chooser.step.derivatives.no': '二次創作は認めない',
    'licenses.chooser.step.derivatives.allowNote': '二次的著作物を許可するということは、他者があなたの作品を翻案、リミックス、変形できることを意味します。これは、あなたのコンテンツのより広い配布と創造的な再利用につながります。',
    'licenses.chooser.step.derivatives.disallowNote': '二次的著作物を認めないということは、あなたの作品をそのまま、全体として伝えなければならないということです。',
    'licenses.chooser.step.attribution.title': '帰属表示を要求しますか？',
    'licenses.chooser.step.attribution.description': '帰属とは、他者があなたの作品を使用する際、あなたにクレジットを与えなければならないということです。',
    'licenses.chooser.step.attribution.yes': '帰属表示が必要',
    'licenses.chooser.step.attribution.no': 'パブリックドメイン(CC0)',
    'licenses.chooser.step.attribution.requireNote': '帰属表示を要求するということは、あなたの作品を使用する人は、あなたが要求する方法でクレジットを与えなければならないということです。',
    'licenses.chooser.step.attribution.publicDomainNote': 'あなたの作品をパブリック・ドメイン（CC0）に置くことは、あなたがすべての著作権および関連する権利を放棄することを意味します。他の人は、いかなる目的であれ、帰属表示なしにあなたの作品を自由に使用することができます。',
    // License Result
    'licenses.chooser.result.commercialTitle': '商業情報',
    'licenses.chooser.result.exclusiveInfo': 'Literary Universe Exclusiveライセンスでは、プラットフォーム使用料が10％に抑えられます。つまり、収益の90％はあなたのものですが、この作品を出版できるのはリテラリーユニバースだけです。',
    'licenses.chooser.result.nonExclusiveInfo': 'Literary Universeの非独占ライセンスでは、他のプラットフォームでも作品を出版することができます。プラットフォーム手数料は30％で、リテラリーユニバースでの収益の70％があなたの手元に残ります。将来的には、リテラリーユニバースから直接他のプラットフォームへ出版するためのツールを提供する予定です。',
    'licenses.chooser.result.fanfictionNote': 'ファン・フィクション作品は、他者が所有する著作物に基づいているため、このライセンスが自動的に適用されます。商業的利用はこれらの権利を侵害する可能性があります。',
    'licenses.chooser.result.selectLicense': 'このライセンスを選択する'
};