export default {
    'org.auditLog.title': '監査ログ',
    'org.settings.title': '組織設定',
    'org.settings.name': '組織名',
    'org.settings.membersPrivate': 'メンバー名を公開しない',
    'org.logo': '組織ロゴ',
    'org.logo.alt': '{organizationName} ロゴ',
    'org.superAdmin': 'スーパーアドミン',
    'org.settings.language': '主言語',
    'org.meta.desc': 'Lieterary Universeに掲載されている団体やクリエイティブなグループを紹介します。',
    'org.luOrgs': 'Lieterary Universeの組織',
    'org.otherOrgs': 'ギルドと組織',
    'org.aboutTitle': '{orgName}について',
    'org.membersTitle': '組織のメンバー',
    'org.membersNone': 'メンバーは非公開です',
    'org.storiesTitle': '{orgName}の物語',
    'org.universesTitle': '{orgName}からの宇宙小説',
    'org.userDashboardTitle': 'あなたの属する組織',
    'org.settings.hideMembers.label': 'メンバーを一般公開しない',
    'org.visit': '{organization}のページへ',
    'org.authorOverride.legend': '著者のオーバーライド',
    'org.authorOverride.desc': '組織名の代わりにこの文字を表示します。',
    'org.authorOverride.label': '著者名',
    'org.membersAdd.title': 'メンバーを組織に招待する',
    'org.flashnews.admin': 'フラッシュニュースの運営',
    'org.settings.tabListAria': '組織のセクション設定',
    'org.forums.title': '{orgName} 掲示板',
    'org.flashnews.internal': '社内ニュース速報',
    'org.flashnews.publicAll': '全領域の公開ニュースフラッシュ',
    'org.flashnews.createTitle': `{type, select,
    internal {組織のための新しいニュースフラッシュを作成します。}
    allProperties {すべてのプロパティで一般に表示するための新しいニュースフラッシュを作成します。}
    other {組織のための新しいニュースフラッシュを作成します。}
  }`,
    'org.members.invited': '招待されたメンバー',
    'org.members.list': '組織のメンバー',
    'org.invitesTileNotice': 'あなたは{count, number}{count, plural,one {団体に招待されています} other {つの組織に招待されています}}',
    'org.invitePage.title': '組織への招待',
    'org.invitePage.invitedAt': 'あなたは{invitedAt, date, short}に招待されています。',
    'org.invitePage.ignoring': 'あなたはこの招待状の対応をとっておらずまだアクティブの状態ですが、通知を気にすることはありません。',
    'org.invitePage.expiresAt': 'この招待状は{expiresAt, date, short} {expiresAt, time}で無効となります。',
    'org.invitePage.accept': '組織に参加',
    'org.invitePage.reject': '招待を拒否する',
    'org.invitePage.ignore': '今のところ対応しない',
    'org.leaveOrg.title': '組織を脱会する',
    'org.leaveOrg.confirm': 'これは損ねる行為であり、この組織をいったん脱会されますとこの組織へのアクセスがすべて失われます。この組織からの脱会でよろしいですか？',
    'org.confirmRemove.aria': 'ユーザーの削除を確認しました',
    'org.confirmRemove.confirm': '本当に{username}を{organization}から脱会しますか？',
    'org.confirmRemove.remove': 'ユーザーの削除',
    'org.mainBlog': 'メインブログ',
    'org.teams': 'チーム',
    'org.teams.total': 'チームの合計数： {totalTeams, number}',
    'org.teams.create': '新しいチームを作る',
    'org.teams.settings': 'チーム設定',
    'org.workshop.ownerUser': 'ギルド作品ではありません',
    'org.workshop.caption': 'ギルドの所有権'
};