export default {
  'personalNotes.personalNotes': '個人メモ',
  'personalNotes.chooseType': '個人メモのタイプを選択してください',
  'personalNotes.storyNotes': 'ストーリーメモ',
  'personalNotes.chapterNotes': 'チャプターメモ',
  'personalNotes.universeNotes': 'ユニバースメモ',
  'personalNotes.encyclopediaNotes': '百科事典のメモ',
  'personalNotes.storyPersonalNotesHeading': 'ストーリーの個人メモ',
  'personalNotes.encyclopediaPersonalNotesHeading': '百科事典の個人メモ',
  'personalNotes.searchPersonalNotesHeading': '個人メモを検索する',
  'personalNotes.goToStory': 'ストーリーに移動する',
  'personalNotes.goToChapter': 'チャプターに移動する',
  'personalNotes.goToEncyclopedia': 'ユニバースの百科事典に移動する',
  'personalNotes.goToEncEntry': 'エントリーに移動する',
  'personalNotes.closeDropdown': 'ドロップダウンを閉じる',
  'personalNotes.chapterName': 'チャプター {sequence} - {title}',
  'personalNotes.objectPersonalNotes': '{object} 個人メモ',
  'personalNotes.searchResults': '検索結果',
  'personalNotes.type.story': '物語',
  'personalNotes.type.universe': '宇宙',
  'personalNotes.type.chapter': '章',
  'personalNotes.type.encEntry': '百科事典エントリー',
  'personalNotes.type.revTextBlock': '改訂テキストブロック',
  'personalNotes.chapter': '章',
  'personalNotes.recentSearches': '最近の検索:'
};