export default {
    'plans.desc': 'Lieterary Universeの今後の計画と特徴についての説明',
    'plans.title': 'Literary Universeをもっと活用しましょう',
    'plans.text': 'Literary Universeでは、基本的な機能を無償で提供しています。読書愛好家、クリエイターの方には、お好みのものを見つけられるアドバンス・メンバーシップをお勧めします。',
    'plans.faq.basicsPriced': 'なぜ無料会員で得られるのはそんなに少ないのですか？',
    'plans.faq.justification': 'Literary Universeでは、お客様のプライバシーと知的財産を重視しています。お客様のデータを使って広告を販売したり、他社に提供したりすることはありません。自分たちで多くのものを作らなければなりません。そのためには多大なる時間と多額の運用費がかかります。\nそこで私たちは、Literary Universeの重要な部分にはアクセスできる小規模プレビューを設け、メンバーシップのレベルを複数に分けました。皆様のニーズにお応えすると同時に、私たちのサービス維持と常に開発し続けられるようになっています。もし、私たちが作っているものにご賛同いただけるようであれば、有料オプションへのサインアップをご検討ください。よろしくお願いいたします。',
    'plans.limits': '制限',
    'plans.features': '特徴',
    'plans.account.user': 'ビジター',
    'plans.account.user.desc': 'お試し用トライアルアカウント。',
    'plans.account.explorer': '試し',
    'plans.account.explorer.desc': '愛好家や友人向け',
    'plans.account.adventurer': '冒険家',
    'plans.account.adventurer.desc': 'クリエイターとサポーター向け',
    'plans.account.storyteller': '語り部向け',
    'plans.account.storyteller.desc': '想像力に富んだ専門家向け',
    'plans.unlimited': '無制限',
    'plans.price': '価格',
    'plans.price.free': '無料',
    'plans.price.monthly': '一か月*',
    'plans.price.annually': '年間*',
    'plans.price.perMonth': '{price}/月*',
    'plans.price.perYear': '{price}/年*',
    'plans.development': '開発中',
    'plans.limits.encEntries': '百科事典のエントリー',
    'plans.limits.maxCollaborators': 'プロジェクトごとの協力者',
    'plans.limits.pmChats': 'プライベートメッセージの最高受信者数',
    'plans.feature.creative': '素晴らしい宇宙と物語の作成',
    'plans.feature.encCustomFields': 'エントリ上のカスタマイズ可能な百科事典のフィールド',
    'plans.feature.encAdvCategories': 'その他の百科事典のカテゴリ',
    'plans.feature.scratchpad': 'メモ帳',
    'plans.feature.library': 'ライブラリー',
    'plans.feature.blog': '個人/宇宙に関するブログ',
    'plans.feature.customBlogTheme': 'カスタマイズ可能なブログのテーマ',
    'plans.feature.advanceStats': '高度な統計数字',
    'plans.feature.challenges': '文書作成の課題とは',
    'plans.feature.newFeaturesVote': '新機能に投票する',
    'plans.feature.newFeaturesSuggest': '新機能の提案',
    'plans.feature.accessToBeta': 'ベータ版の機能にアクセスする',
    'plans.feature.userGroups': 'ユーザーグループ',
    'plans.feature.privateUserGroups': 'プライベートおよび非表示のユーザーグループ作成',
    'plans.feature.internalUniverseForums': '宇宙に関する社内フォーラム',
    'plans.feature.fictionalTime': '架空の時間',
    'plans.feature.forums': 'ブログフォーラム&宇宙関連ページ',
    'plans.feature.timelines': '宇宙のタイムライン',
    'plans.feature.webMonetization': 'ウェブマネタイズ',
    'plans.feature.storyMonetization': '物語のマネタイズ',
    'plans.feature.authorSupport': '作家支援',
    'plans.feature.translations': '翻訳機能',
    'plans.feature.fanFiction': 'ファンフィクションの執筆・管理',
    'plans.feature.universeFanArt': 'ファンアートマネージャー',
    'plans.feature.overviewNotes': '物語の概要メモ',
    'plans.feature.personalNotesStoriesUniverses': '物語と宇宙に関する個人用メモ',
    'plans.feature.storyReviews': 'ストーリーレビュー',
    'plans.feature.readingLists': 'リーディングリスト',
    'plans.feature.scenesManager': 'シーンマネージャー',
    'plans.feature.glossaries': '翻訳向け用語集',
    'plans.feature.chatSupport': 'チャット支援',
    'plans.currency.select': '通貨の選択',
    'plans.subscription.ownAlready': '現在ご使用中のプラン',
    'plans.subscription.title': 'サブスクリプション',
    'plans.see': '利用可能なサブスクリプションプランを見る',
    'plans.current.none': '現在あなたはLiterary Universeをサポートしていません。',
    'plans.current.buying': 'ご購入内容の確認に時間がかかる場合があります。お待ちいただけますよう、お願いいたします。',
    'plans.current.heading': '現在のサブスクリプションプラン',
    'payment.methods.title': 'ペイメント＆マネタイズ',
    'payment.methods.tabs': '支払い方法',
    'payment.option.title': '支払い方法',
    'payment.option.notFount': '決済方法が保存されていません。',
    'payment.option.create': '新しい支払い方法の追加',
    'payment.option.description': '保存されているお支払い方法の一覧です。ここで新しいお支払い方法を保存しておくと、チェックアウトが早くなります。リテラリー・ユニバースでは、お客様のクレジットカード番号などのお支払い情報を保存したり、処理したりすることはありません。',
    'payment.history.title': '支払履歴',
    'payment.history.tab': '支払履歴',
    'payment.history.none': '過去の支払いに関する記録はありません。',
    'plans.options.aria': '支払い方法',
    'plans.options.creditCard': 'クレジットカード',
    'plans.options.creditCardNew': '新クレジットカード',
    'plans.options.existingCards': '保存されたクレジットカード',
    'plans.purchase.action': '購読する',
    'plans.purchase.title': '文学の宇宙のサブスクリプションを購入する',
    'payment.creditCard.details': 'クレジットカードの詳細',
    'payments.zipcode.label': '郵便番号',
    'payment.card.name': 'カードの名前',
    'plans.subscribed.thankYou': '文学の宇宙を支援していただきありがとうございます。',
    'plans.subscribed.periodEnd': 'ご利用期間は{end, date, medium}までです。',
    'plans.subscribed.renewal': `{method, select,
    charge_automatically {契約終了時には自動的に更新}
    send_invoice {終了時に請求書をお支払いいただくと、契約が更新}
    other {}
  }更新されます。`,
    'plans.subscribed.paymentMethod': '次のサイクルのお支払いには、お客様のデフォルトのお支払い方法が使用されます。',
    'plans.subscribed.status': `購読状況：{status, select,
    active {アクティブ}
    incomplete {何かが足りない}
    incomplete_expired {何かが足りない}
    trialing {トライアル}
    past_due {お支払いが滞っています}
    canceled {キャンセル}
    unpaid {未払い}
    other {}
  }`,
    'payments.changeMethod': '支払い方法の変更',
    'plans.subscribed.willNotRenew': 'は、サイクルの終わりには更新されません。',
    'plans.cancel.button': '購読解除',
    'plans.cancel.question': '月額プランをキャンセルしてもよろしいですか？お客様のサブスクリプションは、請求サイクルの最後まで有効です。',
    'plans.cancel.confirmationButton': 'はい、解約したいと思います。',
    'plans.cancel.failed': '申し訳ありませんが、現時点ではお客様のプランをキャンセルすることができませんでした。後でもう一度お試しください。',
    'plans.cancel.restoreBtn': 'サブスクリプションの復元',
    'plans.cancel.restoreFailed': '申し訳ありませんが、現時点では購読の復元ができませんでした。後でもう一度お試しください。',
    'plans.change.button': 'サブスクリプションの変更',
    'plans.change.explanation': 'アップグレードまたはダウングレードしたいプランを選択してください。差額分の料金がすぐに請求されます。',
    'plans.change.failed': '申し訳ありませんが、現時点ではお客様のプランを変更することができませんでした。後日、再度お試しください。',
    'plans.change.upgrade': 'アップグレード',
    'payments.disclaimer': 'お支払いの情報と処理は、Stripeを介して行われます。クレジットカードや銀行口座の情報は、当社のサーバーには一切保存されません。',
    'buy.payment.optionsSelect': '支払い方法の選択',
    'payments.card.number': 'カード番号',
    'payments.card.expire': '有効なスルー',
    'payments.card.cvv': 'CVV',
    'payments.card.info': '{cardType}カード、{ending}で終わる',
    'payments.none': '保存された支払い方法は見つかりませんでした。',
    'payments.none.cards': 'クレジットカードは見つかりませんでした。',
    'payments.added': '新しい支払い方法の追加に成功しました。',
    'payments.delete.confirm': '本当に{ending}で終わる{cardType}を削除したいのですか？',
    'payment.invoice.status': '請求書のステータス',
    'payment.invoice.statusMessage': `{status, select,
    draft {ドラフト}
    open {開}
    paid {有料}
    uncollectible {貸し倒れ}
    void {ボイド}
    other {}
  }`,
    'payment.invoice.id': '請求書ID',
    'payment.invoice.pdf': '請求書のpdf',
    'payment.invoice.total': '合計',
    'payment.invoice.what': '請求書の説明',
    'payment.stripe.powered': 'Powered by ',
    'payment.listMethods.card': 'カード',
    'payment.expiresAt': '期限は{month}/{year}です。',
    'payment.card.details': `{last4}で終わる{type, select,
    credit {クレジット・カード}
    debit {デビットカード}
    other {カード}
  }`,
    'payment.options.default': 'デフォルト',
    'payment.method.add': '新しい支払方法の追加',
    'payment.methods.adding': 'お客様のアカウントに新しいお支払い方法が追加されました。',
    'payment.methods.delete': '決済方法の削除',
    'payment.upgradePlan.option': '{plan} - {price}',
    'payment.methods.webMonetization': 'ウェブマネタイズ',
    'settings.webMonetization.placeholder': 'お支払い方法',
    'payment.webMonetization.explained': 'Web Monetizationは、ウェブ決済の標準規格として提案されています。ここでは、あなたのプロフィールページ、ブログ、ユニバース、ストーリーに、Webマネタイズで利用される決済ポインタを追加することができます。',
    'payment.webMonetization.learnMore': 'ウェブマネタイズについて詳しくはこちら',
    'plans.subscription.settingsAria': 'サブスクリプション設定オプション',
    'plans.buttonStatus.submitting': 'リクエストを送信する...',
    'plans.button.manageOnStripe': 'Stripeで課金を管理する',
    'plans.call.signUpBottom': 'Literary Universeの無料アカウントに登録し、作成を開始します！',
    'plans.button.seeComparison': 'プランと価格の詳細は、比較ページでご確認ください！',
    'plans.button.chooseThisSubscription': 'このプランを選択する',
    'plans.button.chooseFree': '無料で始める',
    'plans.features.allInPreviousTiers': '前段階のすべて',
    'plan.button.chooseNow': 'Literary Universeのプランを今すぐ選ぶ',
    'plans.subscription.manage': 'サブスクリプションの管理',
    'plans.taxMayApply': '* VATおよびその他の現地税が適用される場合があります。',
    'plans.faq.crypto': '暗号決済を提供するのですか',
    'plans.faq.cryptoAnswer': 'はい、私たちはそれに取り組んでいます。私たちはWeb3の大ファンであり、近い将来、Web3をプラットフォームに統合する方法を探しています。現在、Web3でのログインを可能にしていますが、特にクリエイターへの報酬の提供や、クリエイターが受け入れたい支払い方法をすべて選択できるようにするために、このサービスを拡張することを検討しています。',
    'plans.subscribed.updating': 'サブスクリプション情報を更新するには少し時間がかかる場合があります。お待ちください。'
};