export default {
    'workshop.title': 'あなたの文芸作品',
    'workshop.noneassigned': 'あなたにはまだ何も割り当てられていません。',
    'workshop.notavailable': 'この機能はまだ利用できません。',
    'workshop.none': `現在、あなたには{type, select,
      universe {宇宙}
      story {物語}
      fanfiction {ファンフィクション}
      other {}
    }がありません。今すぐ作成してください。`,
    'workshop.collab': '共同作業',
    'workshop.betareadings': 'ベータの読み',
    'workshop.translations': '翻訳',
    'workshop.createnew': '新規作成',
    'workshop.story.standalone': '独立した物語',
    'workshop.story.standalone.desc': 'これは独立した物語です。',
    'workshop.controlpanel': '{name}コントロールパネル',
    'workshop.universe.page': '宇宙のページ',
    'workshop.fictionaltime': '架空の時間',
    'workshop.dashboard.name': '{name} ダッシュボード',
    'workshop.stories.in': '{universe}の物語',
    'workshop.universe.nostories': 'この宇宙には物語がない。',
    'workshop.story.chapter.add': '新しい章',
    'workshop.universe.new': '新しい宇宙を作る',
    'workshop.universe.publish': '宇宙を公開する',
    'workshop.universe.publishing.notice': '宇宙を公開していない場合は、宇宙に接続された最初の物語が公開されると自動的に公開されます。',
    'workshop.universe.settings': '{universe} 宇宙設定',
    'workshop.universe.publishedOn': 'この宇宙は {date, date, long} {date, time, short}に公開されました。',
    'workshop.universe.description': '宇宙の説明',
    'workshop.settings.title': '題名',
    'workshop.description': 'あらすじ',
    'workshop.language.primary': '母国語',
    'workshop.publication.options': '公開オプション',
    'workshop.rating': '一般的な評価',
    'workshop.universe.rating.desc': 'このレーティング以上の物語やファンフィクションは、匿名のユーザーや適切な年齢に達していないユーザーのユニバースページのリストから隠されます。',
    'workshop.universe.license': '宇宙ライセンス',
    'workshop.universe.genre.pick': '宇宙のジャンルを選ぶ',
    'workshop.story.genre.pick': '物語のジャンルを選ぶ',
    'workshop.cover': 'カバーアート',
    'workshop.nothingtosee': '申し訳ありませんが、現在ここに表示されるものはありません。',
    'workshop.story.cannon': 'カノン物語',
    'workshop.story.cannon.desc': 'この物語は{universe}宇宙では標準的です。',
    'workshop.story.cannon.desc.create': 'この物語は、{universe}宇宙のカノニカルな物語として作成されます。',
    'workshop.story.fanfiction.search': '宇宙の名前を入力します（ライブラリに入っている必要があります）。そして、サジェストから選択します。',
    'workshop.story.error.nogenres': '最低でも1つのジャンルを選択する必要があります。',
    'workshop.story.error.toomanygenres': '1話につき2つのジャンルのみ可能です。',
    'workshop.story.error.fanfiction.selectuniverse': 'ファンフィクションにはオリジナルの世界観を選択する必要があるのです。',
    'workshop.story.error.tags.toomany': 'タグは1つの物語につき10個までしか設定できません。',
    'workshop.story.new': '新しい物語の作成',
    'workshop.story.publishing.notice': '第一章を公開すると、物語が自動的に公開されます。',
    'workshop.settings.edit': '設定の変更',
    'workshop.story.publishedOn': 'この物語は{date, date,long} {date, time,short}に公開されました。',
    'workshop.story.settings': '物語の設定',
    'workshop.settings.basic': '基本設定',
    'workshop.settings.genres': 'ジャンル(最大2)',
    'workshop.story.license': '物語の著作権',
    'workshop.story.settings.universe': '宇宙の設定',
    'workshop.settings.tags': 'タグ',
    'workshop.revision': 'リビション',
    'workshop.revisions.title': '{story}: {chapter} リビジョン',
    'workshop.revisions.current': '現在のドラフト',
    'workshop.revisions.new.beta': 'ドラフトから新しいリビジョンを作成します。',
    'workshop.revisions.new.public': 'ドラフトから新しいパブリックリビジョンを作成します。',
    'workshop.revisions.toeditor': 'エディターへ',
    'workshop.revisions.comments': '修正コメント',
    'workshop.revisions.comments.title': '{story}：{chapter} - リビジョン {revision} - コメント',
    'workshop.revisions.comments.list': '{revision}：{publication, select, beta {ベータ版読者のために} readers {公開用} other {}}{datetime, date,medium}{datetime, time,short}',
    'workshop.revisions.comments.norevision': 'まずリビジョンを作成する必要があります。',
    'workshop.revisions.comments.select': 'リビジョンの選択',
    'workshop.collaborators.noresults': '結果がありません',
    'workshop.collaborators.add.beta': 'ベータリーダーの追加',
    'workshop.collaborators.add.collaborator': 'コラボレーターの追加',
    'workshop.collaborators.add.translator': '翻訳者の追加',
    'workshop.collaborators.language.add': '新規翻訳の作成',
    'workshop.translations.stories': '翻訳 - 物語',
    'workshop.translations.universes': '翻訳 - 宇宙',
    'workshop.revisions.beta.none': '今のところ修正はありません。',
    'reader.asidetoggle': '脇の情報をトグル',
    'workshop.translation.original': '元:',
    'workshop.translation.original.title': '元のタイトル:',
    'workshop.translation.original.description': '元の概要:',
    'workshop.translation.original.cover': '元のカバー',
    'workshop.translation.original.tags': '元のタグ',
    'workshop.cover.alt': 'カバー画像',
    'workshop.translation.updatedOrig': 'オリジナルの最終更新日：{updatedAt, date,long}{updatedAt, time,medium}',
    'workshop.translation.updatedTrs': '翻訳の最終更新日：{updatedAt, date,long}{updatedAt, time,medium}',
    'workshop.translation.revisionOrig': 'オリジナルの最終改訂{revision, number}：{updatedAt, date, long}{updatedAt, time, medium}',
    'workshop.translation.revisionTrs': '翻訳の最終改訂{revision, number}：{updatedAt, date,long}{updatedAt, time,medium}',
    'workshop.collaborators.premium': `{type, select,
    collaborator {協力者を増やす}
    beta {ベータリーダーを追加する}
    translator {翻訳者を増やす}
    other {}
  }には、会員ランクを上げる必要があります。`,
    'workshop.collaborators.requests.sent': 'リクエストの送信',
    'workshop.collaborators.requests.invite': `あなたは、以下の{role, select,
    beta {ベータ・リーダー}
    translator {翻訳者}
    collaborator {ことで協力者}
    other {}
  }として招待されました。`,
    'workshop.collaborators.requests.dashboard': `あなたは、{count, plural,
    zero {文学作品ではなく、コラボレーションに招待されました。}
    other {#つの文学作品を共同で制作するよう招待されています。}
  }`,
    'workshop.collaborators.language.added': '言語追加',
    'workshop.story.noChaptersFound': '章は見つかりませんでした。',
    'workshop.fanfic.needUniverseInLibrary': '世の中にはたくさんの宇宙があります。あなたが書きたい宇宙は、まずあなたのライブラリーに入れてください。',
    'workshop.fanfic.findUniverse': '素晴らしい宇宙を見つけてください。',
    'workshop.encSettings': '百科事典の設定',
    'workshop.collaborators.removeUser': 'ユーザーを削除',
    'workshop.collaborators.cancelInvite': '招待をキャンセル',
    'workshop.universe.createFirstStory': '最初の物語を作成する',
    'workshop.storylines': 'ストーリーライン',
    'workshop.scenesManager': 'シーンマネージャー',
    'workshop.collaborators.addRoleForLang': '{language}に{role}を追加',
    'workshop.beta.revisionInfo': 'これは、{createdAt, date, long}で作成されたリビジョン {revision, number}です。',
    'workshop.story.notes.title': '{storyTitle}の注意点',
    'workshop.story.notes.desc': '物語の概要メモ',
    'workshop.story.notes.tile': '物語概要メモ',
    'workshop.hideOrgs': '組織からコンテンツを非表示にする',
    'workshop.translation.premium': '翻訳を追加するには、最低でも「エクスプローラー」のサブスクリプションが必要です。',
    'workshop.story.finished': '物語が完成しました',
    'workshop.story.publishing.externalSellingNotice': 'あなたは文学の宇宙の外で販売しているので、今すぐ物語を公開することができます。あなたのストアリストへのリンクは、その物語上か、ここで公開した現在の物語の最後に表示されます。',
    'workshop.sharing.publicURL': '公開版',
    'workshop.fictionalTime.title': '{universeName}の架空の時間',
    'workshop.fictionalTime.none': '現在、フィクションの時間が設定されていません。',
    'workshop.fictionalTime.createNow': '架空の時間を今すぐ作る！',
    'workshop.fictionalTime.createTitle': '新しい架空の時間を作る',
    'workshop.fictionalTime.editTitle': '編集{ftName}',
    'workshop.fictionalTime.formDescription': `ここでは、あなた自身の架空の時間を作ることができます。現在、このツールには制限があり、対称的な時間を作成することしかできません。つまり、マヤ暦やグレゴリオ暦を再現することはできません。現時点では、このツールは、すべての時間が常に同じであることを期待しています、例えば、月は常に30日であり、例外はありません。を想定しています。この点については、今後のバージョンで対応する予定ですが、それまでは、このツールは主に このツールは、主にSFベースの時間を作成するのに適しています。`,
    'workshop.fictionalTime.timeName': '時間名',
    'workshop.fictionalTime.basicInfo': '基本情報',
    'workshop.fictionalTime.timeSetup': '時間設定',
    'workshop.fictionalTime.linkedToET': 'この時間は地球上の日付（グレゴリオ暦）から始まるのですか。',
    'workshop.fictionalTime.timeDeclaration': '時間宣言',
    'workshop.fictionalTime.declarationLocation': '時間の名前をどこで宣言するか。',
    'workshop.fictionalTime.declarationBefore': '時間単位の前',
    'workshop.fictionalTime.declarationAfter': '時間単位の後',
    'workshop.fictionalTime.declarationNone': 'なし',
    'workshop.fictionalTime.units': '時間単位',
    'workshop.fictionalTime.ETStart': '今回の開始日',
    'workshop.fictionalTime.unitsDescFirst': 'この単位は、ミリ秒から何番目の単位なのか？',
    'workshop.fictionalTime.unitsDesc': '今回は前作から何台目ですか？',
    'workshop.fictionalTime.unitsName': '単位名',
    'workshop.fictionalTime.unitsSeparator': '前機種のセパレーター',
    'workshop.fictionalTime.unitAdd': 'ユニットの追加',
    'workshop.fictionalTime.clocks': '時計',
    'workshop.fictionalTime.unitTransfer': '転送ユニット',
    'fictionalTime.pageStartElapsedTime': 'このページを開いてからの経過時間',
    'fictionalTime.currentTime': '現在の時刻',
    'workshop.shoppingExternal.options': '外部購入オプション',
    'workshop.shoppingExternal.explainer': '物語が他の場所で販売されている場合は、ここにリンクを設定できます。 リンクは、コンテンツの代わりに、またはプレビューするように選択したコンテンツの最後に表示されます。',
    'workshop.shoppingExternal.amazonStore': 'アマゾンストア',
    'workshop.shoppingExternal.amazon': 'アマゾン',
    'workshop.shoppingExternal.storeName': '店名',
    'workshop.shoppingExternal.itemUrl': 'アイテムのURL',
    'workshop.shoppingExternal.storesOther': '他の店',
    'fictionalTime.units.milliseconds': '{units, number}ミリ秒',
    'fictionalTime.countdownToStart': '始まりの時間までのカウントダウン',
    'fictionalTime.unitsToETList': `{units, number} {unitName}＝{days, plural,
      =0 {}
      other {{days}日}
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number}{unitType, select,
    seconds {{units, plural,
      other {秒}
    }}
    minutes {{units, plural,
      other {分}
    }}
    hours {{units, plural,
      other {時間}
    }}
    days {{units, plural,
      other {日}
    }}
    years {{units, plural,
      other {年}
    }}
    other {}
  }＝{targetResult, number}{targetType}`,
    'fictionalTime.inputFrom': 'から',
    'fictionalTime.inputSelectTimeUnit': '時間単位の選択',
    'fictionalTime.inputSelectETUnit': '地球時間単位の選択',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'サイドバーツールボックス',
    'workshop.writerSidebar.description': 'あなたのストーリーへようこそ このサイドバーでは、あなたのストーリーに関連するすべてのリソースに簡単にアクセスすることができます。上のアイコンをクリックすると、最新のコメントやあなたのメモなどを見ることができます。',
    'workshop.story.textopian': 'Textopianへのリンク',
    'workshop.story.textopianExplained': 'Textopianは、パブリックドメインの作品を読むためのディスカッションプラットフォームです。',
    'workshop.story.authorsNotesExplained': '章の最初に読者に読んでもらうためのメモ。',
    'workshop.story.chapterSortSwitch': 'チャプターの順番を入れ替える',
    'workshop.universe.monetizationTitle': '{title}マネタイズ',
    'workshop.story.monetizationTitle': '{universeTitle}：{storyTitle}マネタイズ',
    'workshop.universe.monetizationWebMonetization': 'ウェブマネタイズ',
    'workshop.webMonetization.explain': 'ウェブマネタイズは、ユーザーがあなたのコンテンツに費やした時間に応じて、あなたに支払いをストリーミングします。プロフィールのマネタイズ設定では、独自の支払いポインタを設定できます。ここでは、ウェブ決済を有効にしている協力者との分配を決めることができます。文学の宇宙は自動的に10％を取ります。',
    'workshop.webMonetization.revShare': 'ウェブマネタイズには限界があるため、確率的収益分配を使用しています。確率論的収益分配は、ウェブマネタイズされた訪問者がページを読み込むたびに、あらかじめ定義された支払いポインタのリストからランダムに選択することで機能します。訪問者は、ページが再読み込みされるか閉じられるまで、選択されたポインターに対して支払いを行います。',
    'workshop.webMonetization.revShareMore': 'Probabilistic Revenue Sharing（確率的収益分配）についてはこちらをご覧ください。そのページと同じコードを使用しています。',
    'workshop.story.notEligible.licence': `この物語のライセンスでは、マネタイズはできません。`,
    'workshop.universe.notEligible.licence': `宇宙のライセンスでは、マネタイズはできません。`,
    'workshop.story.notEligible.fanFiction': 'ファンフィクションの物語はマネタイズの対象外です。',
    'workshop.revShare.mustBe100': 'シェアが100％であること',
    'workshop.revShare.LUCut': '文学の宇宙とペイメントゲート',
    'workshop.revShare.unallocated': '未配分のシェア　{total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': '未定',
    'workshop.revShare.origLangCreators': 'オリジナル言語のクリエーター',
    'workshop.story.prolog': 'プログ',
    'workshop.story.chapter': '章 {sequence, number}',
    'workshop.work.includesAds': '作品の中に広告や商品の紹介はありますか？',
    'workshop.universe.forumSettings': '内部宇宙フォーラムの設定',
    'workshop.universe.forum': '内部 {universeName} フォーラム',
    'workshop.ratingAdjusted': 'Due to complains we had to adjust your rating to the one that we felt appropriate. As such changing the rating is now disabled.'
};