export default {
    'feedback.home': 'Trung tâm trợ giúp',
    'feedback.bugs': 'Vấn đề',
    'feedback.bugs.desc': 'Bạn đã gặp phải lỗi hoặc điều gì đó không đúng hoặc không đúng chỗ. Hãy cho chúng tôi biết ở đây!',
    'feedback.features': 'Ý tưởng & Đề xuất',
    'feedback.features.desc': 'Có ý tưởng cho các tính năng mới hoặc cách để làm cho trang web tốt hơn? Hãy cho chúng tôi biết!',
    'feedback.help': 'Trợ giúp & Hướng dẫn',
    'feedback.help.desc': 'Làm thế nào để bạn _____? Đến đây để tìm câu trả lời.',
    'feedback.desc': 'Chào mừng bạn đến trung tâm trợ giúp và giải quyết vấn đề của chúng tôi!',
    'feedback.open': 'Mở',
    'feedback.closed': 'Đã đóng',
    'feedback.accepted': 'Đã chấp nhận',
    'feedback.inprogress': 'Đang tiến hành',
    'feedback.completed': 'Hoàn thành',
    'feedback.fixed': 'Đã sửa',
    'feedback.new.bugs': 'Báo cáo vấn đề mới',
    'feedback.new.features': 'Đề xuất tính năng mới',
    'feedback.lang.nosupport': 'Ngôn ngữ hiện tại của bạn không được hỗ trợ cho phản hồi, vui lòng viết bằng tiếng Anh. Cảm ơn bạn!',
    'feedback.new.thanks': 'Cảm ơn bạn đã thông báo! Chúng tôi sẽ xem xét nhanh chóng.',
    'feedback.comment.title': 'Bình luận',
    'feedback.comment.desc': 'Gửi phản hồi của bạn cho chúng tôi',
    'feedback.comment.legend': 'Phản hồi của bạn - hãy cho chúng tôi biết về bất cứ điều gì',
    'feedback.comment.success': 'Cảm ơn bạn đã gửi phản hồi!',
    'feedback.comment.label': 'Ý kiến của bạn',
    'feedback.copyrightReport.title': 'Vi phạm bản quyền',
    'feedback.copyrightReport.desc': 'Báo cáo vi phạm bản quyền',
    'feedback.report.noUser': 'Bạn cần đăng nhập để gửi báo cáo.',
    'feedback.voting.totalVoters': 'Người dùng đã bình chọn: {voted, number}',
    'feedback.voting.upvote': 'Bình chọn thuận',
    'feedback.voting.downvote': 'Bình chọn chống',
    'feedback.voting.score': 'Tổng điểm',
    'feedback.report.title': 'Báo cáo nội dung',
    'feedback.report.typeSelect': 'Vấn đề ở đây là gì?',
    'feedback.reportType.law': 'Vi phạm pháp luật',
    'feedback.reportType.vulgar': 'Tục tỉu/khêu gợi',
    'feedback.reportType.copyright': 'Vi phạm bản quyền',
    'feedback.reportType.storyRating': 'Incorrect age rating',
    'feedback.reportType.scam': 'Scam',
    'feedback.report.submit': 'Báo cáo',
    'feedback.report.submitting': 'Reporting...',
    'feedback.report.violationDesc': 'Details',
    'feedback.report.reportSaved': 'Thank you for the report! We will investigate and take action if needed.',
    'feedback.report.copyrightReportSaved': 'Thank you for the report! We will investigate and be in touch.',
    'feedback.report.copyrightOwnershipDesc': 'Ownership statement',
    'feedback.report.copyrightNotice': 'Please note that you need to be the rightful owner of the work to use this form. If you are not the owner, please inform the owner or use the other category to inform us. We take copyright violations extremely seriously and the same applies to improper and abusive use of this form.',
    'feedback.report.copyrightInternalProperty': 'I have published this work on Literary Universe',
    'feedback.reportType.spam': 'Spam or phishing',
    'feedback.reportType.other': 'Other',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`
};