export default {
    'workshop.title': 'Công việc của bạn',
    'workshop.noneassigned': 'Bạn chưa được giao công việc nào.',
    'workshop.notavailable': 'Tính năng này chưa được khả dụng.',
    'workshop.none': `You currently have no {type, select,
      universe {universe}
      story {story}
      fanfiction {fan fiction}
      other {}
    }. Create one now!`,
    'workshop.collab': 'Công việc cộng tác',
    'workshop.betareadings': 'Đọc thử phiên bản beta',
    'workshop.translations': 'Bản dịch',
    'workshop.createnew': 'Tạo mới...',
    'workshop.story.standalone': 'Câu chuyện độc lập',
    'workshop.story.standalone.desc': 'Đây là một câu chuyện độc lập.',
    'workshop.controlpanel': '{name} bảng điều khiển',
    'workshop.universe.page': 'Trang vũ trụ',
    'workshop.fictionaltime': 'Thời gian hư cấu',
    'workshop.dashboard.name': '{name} bảng điều khiển',
    'workshop.stories.in': 'Các câu chuyện trong {universe}',
    'workshop.universe.nostories': 'Không có câu chuyện nào trong vũ trụ này.',
    'workshop.story.chapter.add': 'Chương mới',
    'workshop.universe.new': 'Tạo một vũ trụ mới',
    'workshop.universe.publish': 'Xuất bản vũ trụ',
    'workshop.universe.publishing.notice': 'Nếu bạn không xuất bản vũ trụ, nó sẽ được tự động xuất bản khi câu chuyện đầu tiên liên kết với vũ trụ được xuất bản.',
    'workshop.universe.settings': '{universe} cài đặt vũ trụ',
    'workshop.universe.publishedOn': 'Vũ trụ này đã được xuất bản trên {date, date, long} {date, time, short}',
    'workshop.universe.description': 'Mô tả vũ trụ',
    'workshop.settings.title': 'Tiêu đề',
    'workshop.description': 'Mô tả',
    'workshop.language.primary': 'Ngôn ngữ chính',
    'workshop.publication.options': 'Tùy chọn xuất bản',
    'workshop.rating': 'Xếp hạng chung',
    'workshop.universe.rating.desc': 'Các câu chuyện và fanfiction có xếp hạng cao hơn sẽ bị ẩn khỏi trang liệt kê của trang vũ trụ đối với người dùng ẩn danh và người dùng không đủ tuổi.',
    'workshop.universe.license': 'Giấy phép vũ trụ',
    'workshop.universe.genre.pick': 'Chọn thể loại cho vũ trụ',
    'workshop.story.genre.pick': 'Chọn thể loại cho câu chuyện',
    'workshop.cover': 'Bìa',
    'workshop.nothingtosee': 'Không có gì để xem ở đây...',
    'workshop.story.cannon': 'Câu chuyện chính thức',
    'workshop.story.cannon.desc': 'Câu chuyện này là chính thức trong vũ trụ {universe}',
    'workshop.story.cannon.desc.create': 'Câu chuyện này sẽ được tạo thành câu chuyện gốc trong vũ trụ {universe} .',
    'workshop.story.fanfiction.search': 'Nhập tên của vũ trụ (nó cần phải có trong thư viện của bạn). Sau đó chọn từ các gợi ý.',
    'workshop.story.error.nogenres': 'Bạn cần chọn ít nhất một thể loại.',
    'workshop.story.error.toomanygenres': 'Chỉ cho phép hai thể loại cho mỗi câu chuyện.',
    'workshop.story.error.fanfiction.selectuniverse': 'Bạn cần chọn vũ trụ gốc cho fan fiction của bạn!',
    'workshop.story.error.tags.toomany': 'Bạn chỉ có thể có tối đa 10 thẻ cho mỗi câu chuyện.',
    'workshop.story.new': 'Tạo một câu chuyện mới',
    'workshop.story.publishing.notice': 'Câu chuyện sẽ được xuất bản tự động sau khi bạn xuất bản chương đầu tiên.',
    'workshop.settings.edit': 'Chỉnh sửa cài đặt',
    'workshop.story.publishedOn': 'Truyện này đã được xuất bản vào {date, date, long} {date, time, short}',
    'workshop.story.settings': 'Cài đặt câu chuyện',
    'workshop.settings.basic': 'Cài đặt cơ bản',
    'workshop.settings.genres': 'Thể loại (tối đa 2)',
    'workshop.story.license': 'Giấy phép câu chuyện',
    'workshop.story.settings.universe': 'Cài đặt vũ trụ',
    'workshop.settings.tags': 'Thẻ',
    'workshop.revision': 'Phiên bản',
    'workshop.revisions.title': '{story}: {chapter} Phiên bản',
    'workshop.revisions.current': 'Bản nháp hiện tại',
    'workshop.revisions.new.beta': 'Tạo một phiên bản mới từ bản nháp.',
    'workshop.revisions.new.public': 'Tạo một phiên bản công khai mới từ bản nháp.',
    'workshop.revisions.toeditor': 'Đi đến trình soạn thảo',
    'workshop.revisions.comments': 'Bình luận về phiên bản',
    'workshop.revisions.comments.title': '{story}: {chapter} - Phiên bản {revision} - Bình luận',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {cho người đọc Beta}
      readers {Công cộng}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'Bạn cần tạo một phiên bản trước.',
    'workshop.revisions.comments.select': 'Chọn phiên bản',
    'workshop.collaborators.noresults': 'Không có kết quả',
    'workshop.collaborators.add.beta': 'Thêm Beta reader',
    'workshop.collaborators.add.collaborator': 'Thêm người cộng tác',
    'workshop.collaborators.add.translator': 'Thêm người dịch',
    'workshop.collaborators.language.add': 'Tạo bản dịch mới',
    'workshop.translations.stories': 'Bản dịch - truyện',
    'workshop.translations.universes': 'Bản dịch - vũ trụ',
    'workshop.revisions.beta.none': 'Không có phiên bản sửa đổi vào thời điểm này.',
    'reader.asidetoggle': 'Chuyển đổi thông tin bên',
    'workshop.translation.original': 'Nguyên bản:',
    'workshop.translation.original.title': 'Tiêu đề nguyên bản:',
    'workshop.translation.original.description': 'Mô tả nguyên bản:',
    'workshop.translation.original.cover': 'Ảnh bìa nguyên bản',
    'workshop.translation.original.tags': 'Thẻ nguyên bản',
    'workshop.cover.alt': 'hình ảnh bìa',
    'workshop.translation.updatedOrig': 'Cập nhật cuối cùng của nguyên bản: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'Cập nhật cuối cùng của bản dịch: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'Phiên bản sửa đổi cuối cùng {revision, number}, của nguyên bản: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'Phiên bản sửa đổi cuối cùng {revision, number}, của bản dịch: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `To add more {type, select,
    collaborator {collaborators}
    beta {beta readers}
    translator {translators}
    other {}
  }, you need to increase your membership tier.`,
    'workshop.collaborators.requests.sent': 'Yêu cầu đã gửi',
    'workshop.collaborators.requests.invite': `Bạn đã được mời trở thành {role, select,
    beta {người đọc beta}
    translator {người dịch}
    collaborator {người cộng tác}
    other {}
  } cho những nội dung sau:`,
    'workshop.collaborators.requests.dashboard': `Bạn đã được mời để cộng tác trên {count, plural,
    zero {không có công việc}
    one {một tác phẩm văn học}
    other {# tác phẩm văn học}
  }.`,
    'workshop.collaborators.language.added': 'Ngôn ngữ đã được thêm',
    'workshop.story.noChaptersFound': 'Không tìm thấy các chương.',
    'workshop.fanfic.needUniverseInLibrary': 'Có rất nhiều vũ trụ ở đây. Vui lòng thêm những vũ trụ mà bạn muốn viết vào thư viện của bạn trước để chúng tôi có thể tìm thấy chúng.',
    'workshop.fanfic.findUniverse': 'Hãy tìm một vũ trụ tuyệt vời!',
    'workshop.encSettings': 'Cài đặt bách khoa toàn thư',
    'workshop.collaborators.removeUser': 'Xóa người dùng',
    'workshop.collaborators.cancelInvite': 'Hủy lời mời',
    'workshop.universe.createFirstStory': 'Tạo câu chuyện đầu tiên',
    'workshop.storylines': 'Các dòng truyện',
    'workshop.scenesManager': 'Quản lý Cảnh',
    'workshop.collaborators.addRoleForLang': 'Thêm {role} cho {language}',
    'workshop.beta.revisionInfo': 'Đây là phiên bản sửa đổi {revision, number}, được tạo vào {createdAt, date, long}.',
    'workshop.story.notes.title': 'Ghi chú của bạn cho {storyTitle}',
    'workshop.story.notes.desc': 'Ghi chú tổng quan cho câu chuyện.',
    'workshop.story.notes.tile': 'Ghi chú tổng quan',
    'workshop.hideOrgs': 'Ẩn nội dung khỏi tổ chức',
    'workshop.translation.premium': 'Để thêm bản dịch, bạn cần có ít nhất gói Explorer.',
    'workshop.story.finished': 'Câu chuyện đã hoàn thành',
    'workshop.story.publishing.externalSellingNotice': 'Vì bạn đang bán ngoài Vũ Trụ Văn Học, bạn có thể xuất bản câu chuyện ngay bây giờ. Liên kết đến danh sách cửa hàng của bạn sẽ xuất hiện trên câu chuyện hoặc cuối câu chuyện hiện tại mà bạn xuất bản ở đây.',
    'workshop.sharing.publicURL': 'Phiên bản công khai',
    'workshop.fictionalTime.title': 'Thời gian hư cấu cho {universeName}',
    'workshop.fictionalTime.none': 'Hiện tại bạn chưa thiết lập bất kỳ thời gian hư cấu nào.',
    'workshop.fictionalTime.createNow': 'Hãy tạo một thời gian hư cấu ngay bây giờ!',
    'workshop.fictionalTime.createTitle': 'Tạo một thời gian hư cấu mới',
    'workshop.fictionalTime.editTitle': 'Chỉnh sửa {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently this tool is limited and is only capable of creating
        symmetric times. This means you won 't be able to recreate the Mayan calendar or the Gregorian. At this moment
        this tool expects that all the times are always the same, eg. months have always 30 days no exceptions and so
        on. We will address this in later versions, but till then this tool is more suited for creating primarily
        sci-fi based times.`,
    'workshop.fictionalTime.timeName': 'Tên thời gian',
    'workshop.fictionalTime.basicInfo': 'Thông tin cơ bản',
    'workshop.fictionalTime.timeSetup': 'Thiết lập thời gian',
    'workshop.fictionalTime.linkedToET': 'Thời gian này có bắt đầu từ một ngày trên Trái Đất (lịch Gregory) không?',
    'workshop.fictionalTime.timeDeclaration': 'Tuyên bố thời gian',
    'workshop.fictionalTime.declarationLocation': 'Nơi nên tuyên bố tên thời gian?',
    'workshop.fictionalTime.declarationBefore': 'Trước các đơn vị',
    'workshop.fictionalTime.declarationAfter': 'Sau các đơn vị',
    'workshop.fictionalTime.declarationNone': 'Không có',
    'workshop.fictionalTime.units': 'Các đơn vị',
    'workshop.fictionalTime.ETStart': 'Ngày bắt đầu của thời gian này',
    'workshop.fictionalTime.unitsDescFirst': 'Có bao nhiêu đơn vị trong đơn vị này từ mili giây?',
    'workshop.fictionalTime.unitsDesc': 'Có bao nhiêu đơn vị trong đơn vị này so với đơn vị trước đó?',
    'workshop.fictionalTime.unitsName': 'Tên đơn vị',
    'workshop.fictionalTime.unitsSeparator': 'Dấu phân cách từ đơn vị trước',
    'workshop.fictionalTime.unitAdd': 'Thêm đơn vị',
    'workshop.fictionalTime.clocks': 'Đồng hồ',
    'workshop.fictionalTime.unitTransfer': 'Chuyển đơn vị',
    'fictionalTime.pageStartElapsedTime': 'Thời gian đã trôi qua kể từ khi mở trang này',
    'fictionalTime.currentTime': 'Thời gian hiện tại',
    'workshop.shoppingExternal.options': 'Tùy chọn mua từ ngoài',
    'workshop.shoppingExternal.explainer': 'Nếu câu chuyện của bạn được bán ở nơi khác, bạn có thể đặt các liên kết ở đây. Các liên kết sẽ hiển thị thay vì nội dung hoặc ở cuối nội dung bạn chọn để xem trước.',
    'workshop.shoppingExternal.amazonStore': 'Cửa hàng Amazon',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Tên cửa hàng',
    'workshop.shoppingExternal.itemUrl': 'URL mặt hàng',
    'workshop.shoppingExternal.storesOther': 'Các cửa hàng khác',
    'fictionalTime.units.milliseconds': '{units, number} mili giây',
    'fictionalTime.countdownToStart': 'Đếm ngược đến thời gian bắt đầu',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 ngày }
      other {{days} ngày }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {giây}
      other {giây}
    }}
    minutes {{units, plural,
      one {phút}
      other {phút}
    }}
    hours {{units, plural,
      one {giờ}
      other {giờ}
    }}
    days {{units, plural,
      one {ngày}
      other {ngày}
    }}
    years {{units, plural,
      one {năm}
      other {năm}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'Từ',
    'fictionalTime.inputSelectTimeUnit': 'Chọn đơn vị thời gian',
    'fictionalTime.inputSelectETUnit': 'Chọn đơn vị thời gian Trái đất',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Hộp công cụ thanh bên',
    'workshop.writerSidebar.description': 'Chào mừng đến với câu chuyện của bạn! Thanh bên này cho phép bạn dễ dàng truy cập vào tất cả các tài nguyên liên quan đến câu chuyện của bạn. Kiểm tra các biểu tượng phía trên để xem các bình luận mới nhất, ghi chú của bạn và nhiều hơn nữa!',
    'workshop.story.authorsNotesExplained': 'Ghi chú của bạn để đọc cho độc giả ở đầu chương.',
    'workshop.story.chapterSortSwitch': 'Thay đổi thứ tự chương',
    'workshop.universe.monetizationTitle': '{title} tiền tệ',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} tiền tệ',
    'workshop.universe.monetizationWebMonetization': 'Web Monetization',
    'workshop.webMonetization.explain': 'Web Monetization sẽ truyền dữ liệu thanh toán cho bạn dựa trên thời gian người dùng dành cho nội dung của bạn. Trong cài đặt tiền tệ của hồ sơ của bạn, bạn có thể đặt chính mình điểm thanh toán. Ở đây, bạn có thể quyết định chia sẻ với những người cộng tác viên của bạn có bật thanh toán web. Literary Universe tự động lấy 10%.',
    'workshop.webMonetization.revShare': 'Do hạn chế của Web Monetization, chúng tôi sử dụng chia sẻ doanh thu ngẫu nhiên. Chia sẻ doanh thu ngẫu nhiên hoạt động bằng cách ngẫu nhiên chọn từ danh sách các điểm thanh toán được xác định trước mỗi khi một khách truy cập có thanh toán web tải trang của bạn. Khách truy cập thanh toán cho điểm được chọn cho đến khi trang được tải lại hoặc đóng.',
    'workshop.webMonetization.revShareMore': 'Tìm hiểu thêm về Chia sẻ Doanh thu Ngẫu nhiên. Chúng tôi sử dụng cùng mã code như trên trang đó.',
    'workshop.story.notEligible.licence': `Giấy phép câu chuyện không cho phép tiền tệ.`,
    'workshop.universe.notEligible.licence': `Giấy phép vũ trụ không cho phép tiền tệ.`,
    'workshop.story.notEligible.fanFiction': 'Các câu chuyện Fan Fiction không đủ điều kiện để tiền tệ.',
    'workshop.revShare.mustBe100': 'Chia sẻ phải bằng 100%',
    'workshop.revShare.LUCut': 'Literary Universe & cổng thanh toán',
    'workshop.revShare.unallocated': 'Chia sẻ chưa phân bổ {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'Chưa quyết định',
    'workshop.revShare.origLangCreators': 'Người tạo ngôn ngữ gốc',
    'workshop.story.prolog': 'Lời mở đầu',
    'workshop.story.chapter': 'Chương {sequence, number}',
    'workshop.work.includesAds': 'Có quảng cáo hoặc đặt sản phẩm trong tác phẩm không?',
    'workshop.universe.forumSettings': 'Cài đặt diễn đàn vũ trụ nội bộ',
    'workshop.universe.forum': 'Diễn đàn nội bộ {universeName}',
    'workshop.ratingAdjusted': 'Do vấn đề phản đối, chúng tôi đã phải điều chỉnh xếp hạng của bạn thành một xếp hạng mà chúng tôi cho là phù hợp. Do đó, việc thay đổi xếp hạng hiện đã bị vô hiệu hóa.',
    'workshop.selectCollaborator': 'Chọn người cộng tác',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Bản nháp',
    'workshop.chapterStatus.scheduled': 'Đã lên lịch',
    'workshop.chapterStatus.published': 'Đã xuất bản',
    'workshop.story.continuedIn': 'Những câu chuyện nào tiếp tục câu chuyện này?',
    'workshop.story.continuedPlaceholder': 'Chọn câu chuyện từ vũ trụ này',
    'workshop.universe.isAIGenerated': 'Nội dung của vũ trụ có được tạo ra bởi trí tuệ nhân tạo không?',
    'workshop.universe.isAIGeneratedTooltip': 'Vui lòng cho chúng tôi biết nếu bất kỳ nội dung nào trong vũ trụ đã được tạo ra bởi hoặc với sự trợ giúp của trí tuệ nhân tạo. Chúng tôi sử dụng thông tin này để đánh dấu đúng và do cách các chương trình trí tuệ nhân tạo được tạo ra, có thể có một số hạn chế và hạn chế.',
    'workshop.story.isAIGenerated': 'Câu chuyện có được tạo ra bởi trí tuệ nhân tạo không?',
    'workshop.story.isAIGeneratedTooltip': 'Vui lòng cho chúng tôi biết nếu bất kỳ phần nào của câu chuyện đã được tạo ra bởi hoặc với sự trợ giúp của trí tuệ nhân tạo. Chúng tôi sử dụng thông tin này để đánh dấu đúng và do cách các chương trình trí tuệ nhân tạo được tạo ra, có thể có một số hạn chế và hạn chế.',
    'workshop.publicationAgreement.aria': 'Thỏa thuận xuất bản cho công việc',
    'workshop.publicationAgreement.intro': 'Chúng tôi rất vui mừng khi bạn đã chọn xuất bản tác phẩm sáng tạo của mình với chúng tôi. Trước khi tiếp tục, chúng tôi chỉ cần bạn xem qua thỏa thuận xuất bản của chúng tôi, để hiểu ý nghĩa từ phía pháp lý.',
    'workshop.sortChapters': 'Sắp xếp theo:',
    'workshop.sortChapters.ascending': 'Từ đầu',
    'workshop.sortChapters.descending': 'Từ mới nhất',
    'workshop.sortChapters.aria': 'Chọn cách sắp xếp danh sách chương',
    'workshop.hiatus.btn': 'Thay đổi trạng thái truyện thành Tạm ngừng',
    'workshop.cancelled.btn': 'Thay đổi trạng thái truyện thành Đã hủy',
    'workshop.complete.btn': 'Thay đổi trạng thái truyện thành Hoàn thành',
    'workshop.statusChange.modalTop': 'Bạn có chắc chắn muốn thay đổi trạng thái thành',
    'workshop.statusName.hiatus': 'Tạm ngừng',
    'workshop.statusName.cancelled': 'Đã hủy',
    'workshop.statusName.completed': 'Hoàn thành',
    'workshop.statusExplain.hiatus1': 'Tạm ngừng có nghĩa là bạn tạm thời không làm việc trên câu chuyện này trong một thời gian ngắn vì bất kỳ lý do gì. Nó sẽ thông báo cho độc giả của bạn biết rằng họ không nên mong đợi bất kỳ bản cập nhật mới trong những tuần tới hoặc thậm chí trong vài tháng.',
    'workshop.statusExplain.hiatus2': 'Trạng thái tạm ngừng sẽ tự động bị gỡ bỏ nếu bạn xuất bản bất kỳ chương nào. Hoặc bạn có thể tự thay đổi nó.',
    'workshop.statusExplain.hiatus3': 'Nếu bạn giữ câu chuyện trong trạng thái tạm ngừng trong sáu tháng, chúng tôi sẽ tự động đánh dấu câu chuyện này là đã hủy.',
    'workshop.statusExplain.cancelled1': 'Chúng tôi rất tiếc khi nghe bạn không thể tiếp tục làm việc trên câu chuyện. Tuy nhiên, chúng tôi rất vui mừng khi bạn sẵn lòng cho độc giả của mình biết.',
    'workshop.statusExplain.cancelled2': 'Hủy câu chuyện sẽ cho độc giả biết rằng họ không nên mong đợi bất kỳ bản cập nhật mới nào.',
    'workshop.statusExplain.cancelled3': 'Bạn luôn có thể hoàn tác điều này bằng cách xuất bản một chương hoặc thay đổi trạng thái.',
    'workshop.statusExplain.finished1': 'Xin chúc mừng! Sau tất cả những công sức đó, bạn đã cuối cùng đạt được điểm cuối cùng của một cuộc hành trình tuyệt vời. Trong khi câu chuyện có thể kết thúc ngay bây giờ, chúng tôi hy vọng sẽ có nhiều câu chuyện khác để kể trong tương lai, nhưng hiện tại, hãy thư giãn và tận hưởng những giây phút nghỉ ngơi xứng đáng.',
    'workshop.statusExplain.finished2': 'Đánh dấu câu chuyện là hoàn thành sẽ cho độc giả biết rằng câu chuyện đã kết thúc. Mặc dù bạn không nên thêm bất kỳ chương mới nào, nhưng chúng tôi sẽ không ngăn bạn và việc thêm các chương đặc biệt cũng không phải ý tưởng tồi, ví dụ như thêm thêm phần kết cho tất cả các nhân vật.',
    'workshop.statusExplain.finished3': 'Trong khi bạn luôn có thể hủy trạng thái này, chúng tôi khuyến nghị không nên làm điều đó. Nếu câu chuyện tiếp tục, có thể tốt hơn nếu bạn bắt đầu một câu chuyện mới.',
    'workshop.status.goActive': 'Làm cho câu chuyện trở lại hoạt động',
    'workshop.statusChangeEmail.storyIntro': 'Chúng tôi muốn thông báo cho bạn rằng câu chuyện của bạn:',
    'workshop.statusChangeEmail.hiatusTitle': 'Trạng thái câu chuyện của bạn đã tự động chuyển sang tạm ngưng',
    'workshop.statusChangeEmail.hiatusIntro': 'Do không hoạt động, trạng thái câu chuyện của bạn đã tự động chuyển sang tạm ngưng.',
    'workshop.statusChangeEmail.hiatusWhy': 'Đã tự động đưa câu chuyện vào tạm ngưng do không có chương mới được đăng trong hơn 6 tháng.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'Trạng thái này sẽ được tự động bỏ nếu bạn đăng một chương mới. Nếu bạn không đăng một chương mới trong 6 tháng tới, chúng tôi sẽ tự động đặt câu chuyện là đã hủy.',
    'workshop.statusChangeEmail.cancellationIntro': 'Trạng thái câu chuyện của bạn đã tự động chuyển sang đã hủy.',
    'workshop.statusChangeEmail.cancellationWhy': 'Điều này đã xảy ra vì bạn không đăng bất kỳ chương mới nào cho câu chuyện kể từ khi nó được đặt vào tạm ngưng 6 tháng trước. Vì vậy, sau một năm không hoạt động, chúng tôi tự động đặt câu chuyện là đã hủy để độc giả biết những câu chuyện nào đang hoạt động.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'Trạng thái này sẽ được tự động bỏ nếu bạn đăng một chương mới. Nếu bạn không có ý định làm việc với câu chuyện này nữa, không có gì khác bạn cần phải làm.',
    'workshop.startCreating': 'Bắt đầu tạo',
    'workshop.ownWork': 'Công việc của bạn',
    'workshop.list.thumbs': 'Danh sách hình thu nhỏ',
    'workshop.list.list': 'Danh sách ngắn',
    'workshop.fanfiction.new': 'Tạo một fan fiction mới'
};