/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'Literary Universe',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe is an all-in-one creative and publishing platform for grand story universes.',
    'site.keywords': 'creative writing, scifi, sci-fi, fantasy, writing, publishing, story, stories, universe, web novel, webnovel',
    'site.logoAlt': 'साहित्यिक ब्रह्माण्ड लोगो',
    mobileMenu: 'मोबाइल मेनू',
    'common.signin': 'लॉगिन',
    'common.signup': 'रजिस्टर',
    'common.signout': 'लॉगआउट',
    'common.dashboard': 'डैशबोर्ड',
    'common.discovery': 'खोज',
    'common.library': 'पुस्तकालय',
    'common.library.own': 'तपाईंको पुस्तकालय',
    'common.workshop': 'कार्यशाला',
    'common.pm': 'सन्देशहरू',
    'common.settings': 'सेटिंग्स',
    'common.options': 'विकल्पहरू',
    'common.profile': 'प्रोफाइल',
    'common.blog': 'ब्लग',
    'common.blogs': 'ब्लगहरू',
    'common.about': 'हाम्रोबारेमा',
    'common.accessdenied': 'पहुँच अस्वीकृत',
    'common.accessdenied.msg': 'तपाईंलाई यहाँ जानकारी दिइएको छैन। यदि तपाईंलाई यहाँ पहुँच हुनुपर्छ भने, कृपया मालिकलाई सम्पर्क गर्नुहोस् र त्यसले सेटिंगहरू दुबैबारे जाँच गर्न भन्नुहोस्।',
    'common.loading': 'लोड हुँदैछ...',
    'common.add': 'थप्नुहोस्',
    'common.save': 'सुरक्षित गर्नुहोस्',
    'common.email': 'ई-मेल',
    'common.soon': 'धेरैजसो छ...',
    'common.search': 'खोज',
    'common.search.do': 'खोज गर्नुहोस्',
    'common.searching': 'खोजी हुँदैछ...',
    'common.report': 'रिपोर्ट',
    'common.user': 'प्रयोगकर्ता',
    'common.users': 'प्रयोगकर्ताहरू',
    'common.showmore': 'थप देखाउनुहोस्',
    'common.futurefeature.title': 'भविष्यका सुविधा',
    'common.futurefeature.text': 'हामी धेरै खेद छौं, तर यस सुविधा यस समय उपलब्ध छैन। हामी काठिन परिश्रम गर्दै छौं र यसलाई चाँडै उपलब्ध गराउने को लागि काम गरिरहेका छौं।',
    'common.nothingfound': 'केही पनि फेला परेन',
    'common.explore': 'अन्वेषण गर्नुहोस्',
    'common.by': '{author}द्वारा',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'स्क्रैचपैड',
    'common.scratchpad.own': 'तपाईंको स्क्रैचपैड',
    'common.news': 'समाचार',
    'common.encyclopedia': 'ज्ञानकोष',
    'common.art': 'Art',
    'common.story': 'कथा',
    'common.stories': 'कथाहरू',
    'common.universe': 'ब्रह्माण्ड',
    'common.universes': 'ब्रह्माण्डहरू',
    'common.collaborator': 'सहकारी',
    'common.collaborators': 'सहकारीहरू',
    'common.translator': 'अनुवादक',
    'common.translators': 'अनुवादकहरू',
    'common.betareader': 'बीटा पाठक',
    'common.betareaders': 'बीटा पाठकहरू',
    'common.post': 'पोस्ट',
    'common.statistics': 'आँकड़ा',
    'common.lang.select': 'भाषा छान्नुहोस्',
    'common.submit': 'पेश गर्नुहोस्',
    'common.close': 'बन्द गर्नुहोस्',
    'common.comment': 'टिप्पणी',
    'common.comments': 'टिप्पणीहरू',
    404: 'पृष्ठ भेटिएन',
    'search.users': 'प्रयोगकर्ताहरू खोज्नुहोस्',
    'search.user': 'प्रयोगकर्ता खोज्नुहोस्',
    'common.help': 'सहायता',
    'common.or': 'वा',
    'common.account.create': 'खाता बनाउनुहोस्',
    'signup.username': 'प्रयोगकर्तानाम',
    'signup.email': 'तपाईंको इमेल',
    'signup.password.label': 'तपाईंको पासवर्ड',
    'signup.password.repeat': 'तपाईंको पासवर्ड फेरी लेख्नुहोस्',
    'common.password': 'पासवर्ड',
    'signin.password.forgot': 'पासवर्ड बिर्सनुभयो?',
    'dashboard.whatsnew': 'नयाँ के हो',
    'dashboard.blog': 'तपाईंको ब्लग',
    'common.footer.tagline': 'कठिन ब्रह्माण्डहरूलाई लेख्न र पढ्न सजिलो बनाउनुहोस्।',
    'common.footer.plans': 'योजना र मुल्य निर्धारण',
    'common.legal.tos': 'सेवा संबंधी नियमावली',
    'common.legal.community': 'सामुदायिक दिशानिर्देश',
    'common.legal.privacy': 'गोपनीयता नीति',
    'common.legal.copyright': 'कपिराइट समझौता',
    'common.legal.versionDisplay': `{type, select,
    tos {Terms of Service}
    community {Community Guidelines}
    privacy {Privacy Policy}
    copyright {Copyright Agreement}
    publishingAgreement {Publishing Agreement}
    other {Agreement}
  } Version {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'A new version ({newVersion}) of this document will come into effect on {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} सर्वाधिकार सुरक्षित छ, सबै पाठहरू आफ्ना निर्माताहरूको हुन्।',
    'premium.only.title': 'पर्याप्त उच्च सदस्यता श्रेणी छैन',
    'premium.only.msg': 'हामीले क्षमा चाहन्छौं, तपाईंको सदस्यता श्रेणी पर्याप्त उच्च छैन।',
    'premium.only.join': 'हामीले विभिन्न योजनाहरू प्रदान गर्दछौं जसले सबैलाई लिटेररी युनिभर्सबाट सबैभन्दा बढी लाभ उठाउँछ।',
    'premium.only.link': 'हेर्नुहोस्!',
    'universe.visit': 'ब्रह्माण्ड पृष्ठ भ्रमण गर्नुहोस्',
    'common.fanmanager': 'Fan manager',
    'common.fanarts': 'Fan arts',
    'common.fanfiction': 'Fan fiction',
    'common.fansettings': 'Fan settings',
    'story.chapter': 'अध्याय',
    'story.chapters': 'अध्यायहरू',
    'story.genre': 'शैली',
    'story.genres': 'शैलीहरू',
    'story.read': 'पढ्नुहोस्',
    'story.lastUpdate': 'अन्तिम अद्यावधिक गरिएको {date, date, medium} {date, time, short}.',
    'story.finishedAt': '{date, date, medium}मा समाप्त भएको।',
    'story.comments.for': '{story} {chapter}को लागि टिप्पणीहरू।',
    'story.cover.alt': '{story}को कथा कवर चित्र।',
    'story.note.fanfiction': 'नोट: यो कथा {universe} ब्रह्माण्डमा एक प्रशंसापत्र हो।',
    copyrights: 'कपिराइटहरू',
    'common.challenges': 'चुनौतिहरू',
    // for beta only
    'beta.notice': 'लिटररी यूनिवर्स बीटा में आपका स्वागत है। यह एक सार्वजनिक पूर्वावलोकन है और इसलिए ऐप अभी भी काम चल रहा है। इसका मतलब है कि आपको त्रुटियों और अधूरे सुविधाओं की उम्मीद की जा सकती है। अगर आप कोई त्रुटि या काम नहीं कर रहा है तो कृपया हमें बताएं और कृपया सब्र करें जब तक हम सब कुछ सुविधानुसार नहीं कर लेते हैं।',
    'beta.thanks': 'आपके समर्थन के लिए धन्यवाद!',
    'scratchpad.about': 'आपके नोट और विचार साइट के किसी भी स्थान पर उपलब्ध हैं।',
    'common.feedback': 'प्रतिक्रिया',
    'common.createdOn': 'Created on {date, date, long}',
    'common.createdOn.title': 'Created on',
    // account types
    admin: 'प्रशासक',
    'common.saved': 'सहेज लिया गया!',
    'common.saving': 'सहेज रहा है...',
    'common.friends': 'मित्र',
    'lang.orig': 'मूल भाषा',
    'lang.orig.plus': 'मूल भाषा - {language}',
    buy: 'किन्नुहोस्',
    confirm: 'पुष्टि गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    processing: 'कार्यमा...',
    'common.noData': 'No data',
    'error.title': 'त्रुटि भयो। क्षमा गर्नुहोस्।',
    'common.offlineStatus': 'तपाईं वर्तमानमा अनलाइन छैनन्।',
    male: 'पुरुष',
    female: 'महिला',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: 'कृपया चयन करें',
    'common.statusFailed': 'सर्वर से कनेक्ट करने में विफल हुआ।',
    'common.statusConnecting': 'सर्वर से कनेक्ट करने का प्रयास किया जा रहा है... ({count, number})',
    'slug.checking': 'जाँच हो रही है...',
    'slug.failed': 'यह पता पहले से मौजूद है।',
    'slug.success': 'यह पता उपलब्ध है!',
    'notVerified.msg': `Your account {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    } is not verified.`,
    'notVerified.verify': `Please verify your {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    }.`,
    unknown: 'अज्ञात',
    'common.legal.guidelines': 'सामुदायिक दिशानिर्देश',
    'errorLoading.title': 'पृष्ठ लोड करते समय त्रुटि',
    'errorLoading.explained': 'पृष्ठ लोड हो रहे समय त्रुटि हुई है। हम आपको असुविधा के लिए खेद करते हैं। कृपया पृष्ठ को फिर से एक्सेस करने का प्रयास करें। यदि समस्या बरकरार रहती है, तो कृपया हमें बताएं।',
    'errorLoading.retry': 'पुनः प्रयास करें!',
    'errorLoading.takingLong': 'यह काफी समय ले रहा है...',
    'common.title': 'शीर्षक',
    'common.timelines': 'समयरेखाएँ',
    'common.legal.gdpr': 'जीडीपीआर',
    'common.legal.gdpr.long': 'सामान्य डेटा संरक्षण नियमावली',
    'editor.placeholder.link': 'URL दर्ज करें...',
    'editor.placeholder.connection': 'संदर्भ पुस्तक के लिए खोजें...',
    'editor.saved.beta': 'बीटा पाठकों के लिए नया संशोधन बनाया गया है!',
    'editor.saved.public': 'नई संस्करण प्रकाशित हुआ है!',
    goodbyeForever: 'हमें आपको जाते देखकर दुःख हुआ। क्या हमने कुछ गलती की थी? कृपया हमें बताएं कि क्या ऐसा हुआ है। हर हाल में, हम आपके भविष्य के प्रयासों में शुभकामनाएँ देते हैं और उम्मीद करते हैं कि हम फिर मिलेंगे! लंबी उम्र हो और बढ़िया रहो!',
    'goodbyeForever.feedback': 'हमें बताएं कि हम क्या और बेहतर कर सकते हैं',
    'common.edit': 'संपादित करें',
    'common.publish': 'प्रकाशित करें',
    'common.publishAt': 'प्रकाशन तिथि और समय',
    'a11y.user.menu': 'उपयोगकर्ता मेनू',
    'a11y.navigation': 'Navigation',
    'dashboard.profile': 'आपकी प्रोफ़ाइल',
    'profile.website': 'मेरी व्यक्तिगत वेबसाइट',
    'story.notes.concept': 'अवधारणा',
    'story.notes.settings': 'कथा सेटिंग',
    'story.notes.theme': 'थीम',
    'story.notes.impact': 'इच्छित प्रभाव',
    'story.notes.outcome': 'परिणाम',
    'story.notes.audience': 'लक्षित दर्शक समूह',
    'story.notes.pitch': 'पिच',
    'story.notes.notes': 'नोट्स',
    'story.authorsNotes': 'Author\'s notes',
    'common.members': 'सदस्य',
    'common.language': 'भाषा',
    next: 'अगाडि',
    previous: 'Previous',
    'common.legal.tos.short': 'नियमावली',
    'common.legal.privacy.short': 'गोपनीयता',
    'premium.increaseLimit': 'आपकी सीमा बढ़ाने के लिए अपग्रेड करें।',
    'common.sharing': 'साझा करना',
    'story.isbn': 'ISBN',
    'common.name': 'नाम',
    'common.remove': 'हटाएँ',
    'common.time.milliseconds': 'मिलीसेकंड',
    'common.time.seconds': 'सेकंड',
    'common.time.minutes': 'मिनट',
    'common.time.hours': 'घंटे',
    'common.time.days': 'दिन',
    'common.time.weeks': 'सप्ताह',
    'common.time.months': 'महीने',
    'common.time.years': 'वर्ष',
    'common.monetization': 'Monetization',
    'common.tab.monetizationOptions': 'Monetization options',
    'common.pagination': 'Pagination',
    'common.forum': 'Forum',
    'common.2faCode': '2FA code',
    'common.2faCodeIntro': 'Please enter your one time code generated by your authenticator application.',
    'common.2faCodeAria': '2FA code entry form',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Default language',
    'signin.web3.signMessage': 'Please confirm that you want to enter Literary Universe with your wallet as authentication method. Code: {code}',
    'common.web3.confirmationCode': 'Confirmation code: {code}',
    'common.roadmap': 'Roadmap',
    'common.luStatsIFrameOptOut': 'Literary Universe statistics opt-out',
    'common.image': 'Image',
    'common.home': 'Home',
    'common.administration': 'Administration',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'Groups',
    'common.upload': 'Upload',
    'common.backToDashboard': 'Back to dashboard',
    'common.accept': 'Accept',
    'common.reject': 'Reject',
    'common.events': 'Events',
    'common.event': 'Event',
    'common.all': 'All',
    'common.social': 'Social',
    'common.discordCommunity': 'Discord Community',
    'common.account': 'Account',
    'common.notifications': 'Notifications',
    'common.byDeclaration': 'By:',
    'common.done': 'Done',
    recommended: 'Recommended',
    'select.typeToCreate': 'Start typing to create an item',
    'select.noSearchResults': 'No results for “{search}”',
    'select.removeOption': 'Remove {option}',
    create: 'Create',
    'banner.support': 'Literary Universe is supported by users like you! Please consider subscribing to one of our subscription plans to stay independent and make Literary Universe event better!',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Don\'t have an account?',
    'common.haveAccountQuestion': 'Already have an account?',
    'common.socialLogin': 'Login with other services',
    'common.viewMore': 'View more',
    'common.overview': 'Overview',
    'common.loggingOut': 'Logging out',
    'common.thankYou': 'Thank you!',
    'common.seeYouAgain': 'See you again!',
    'email.hello': 'Hello {username},',
    'common.back': 'Back',
    'console.stop': 'रुक!',
    'console.explain': 'यह एक ब्राउज़र सुविधा है जो डेवलपर्स के लिए है। यदि किसी ने आपको यहां कुछ कॉपी-पेस्ट करने के लिए कहा है ताकि आप एक साहित्यिक यूनिवर्स फ़ीचर या किसी खाते को "हैक" कर सकें, तो यह एक धोखाधड़ी है और उन्हें आपके साहित्यिक यूनिवर्स खाते तक पहुंच देगी।'
}    /* eslint-enable max-len */;