export default {
    'feedback.home': 'सहायता केंद्र',
    'feedback.bugs': 'मुद्दे',
    'feedback.bugs.desc': 'के तपाईंले कुनै त्रुटि वा केहि अन्य गलत वा अस्थायी ठाउँ पाएका छन्? यहाँ जानकारी दिनुहोस्!',
    'feedback.features': 'विचार र प्रस्तावहरू',
    'feedback.features.desc': 'नयाँ सुविधाहरू वा वेबसाइटलाई राम्रो बनाउने तरिकाहरूको लागि कुनै विचार छन्? हामीलाई जानकारी दिनुहोस्!',
    'feedback.help': 'सहायता र ट्युटोरियलहरू',
    'feedback.help.desc': 'तपाईंले कसरी _____? उत्तरहरू यहाँ खोज्नुहोस्।',
    'feedback.desc': 'हाम्रो सहायता र समस्या केन्द्रमा तपाईंलाई स्वागत छ!',
    'feedback.open': 'खोला',
    'feedback.closed': 'बन्द',
    'feedback.accepted': 'स्वीकृत',
    'feedback.inprogress': 'कार्यान्वयनमा',
    'feedback.completed': 'पूरा भयो',
    'feedback.fixed': 'त्रुटि ठिक गरियो',
    'feedback.new.bugs': 'नयाँ मुद्दा सूचना दिनुहोस्',
    'feedback.new.features': 'नयाँ सुविधा सुझाव दिनुहोस्',
    'feedback.lang.nosupport': 'तपाईंको हालको भाषा मुद्दाको लागि समर्थित छैन, कृपया अंग्रेजीमा लेख्नुहोस्। धन्यवाद!',
    'feedback.new.thanks': 'सूचना दिनुभएकोका लागि धन्यवाद! हामी छोटोमा हेर्नेछौं।',
    'feedback.comment.title': 'टिप्पणी',
    'feedback.comment.desc': 'हामीलाई आफ्नो प्रतिक्रिया पठाउनुहोस्',
    'feedback.comment.legend': 'तपाईंको प्रतिक्रिया - कुनै पनि कुराबारे हामीलाई जानकारी दिनुहोस्',
    'feedback.comment.success': 'तपाईंको प्रतिक्रिया धन्यवाद!',
    'feedback.comment.label': 'तपाईंको टिप्पणी',
    'feedback.copyrightReport.title': 'कपीराइट उल्लंघन',
    'feedback.copyrightReport.desc': 'कपीराइट उल्लंघन सूचना दिनुहोस्',
    'feedback.report.noUser': 'कृपया रिपोर्ट फाइल गर्नका लागि साइन इन गर्नुहोस्।',
    'feedback.voting.totalVoters': 'प्रयोगकर्ताहरूले मत दिएको छन्: {voted, number}',
    'feedback.voting.upvote': 'मत दिनुहोस्',
    'feedback.voting.downvote': 'मत नदिनुहोस्',
    'feedback.voting.score': 'कुल अंक',
    'feedback.report.title': 'अहवाल सामग्री',
    'feedback.report.typeSelect': 'यहाँ समस्या के है?',
    'feedback.reportType.law': 'कानून उल्लंघन',
    'feedback.reportType.vulgar': 'अश्लील/अपमानजनक',
    'feedback.reportType.copyright': 'कॉपीराइट उल्लंघन',
    'feedback.reportType.storyRating': 'Incorrect age rating',
    'feedback.reportType.scam': 'Scam',
    'feedback.report.submit': 'Report',
    'feedback.report.submitting': 'Reporting...',
    'feedback.report.violationDesc': 'Details',
    'feedback.report.reportSaved': 'Thank you for the report! We will investigate and take action if needed.',
    'feedback.report.copyrightReportSaved': 'Thank you for the report! We will investigate and be in touch.',
    'feedback.report.copyrightOwnershipDesc': 'Ownership statement',
    'feedback.report.copyrightNotice': 'Please note that you need to be the rightful owner of the work to use this form. If you are not the owner, please inform the owner or use the other category to inform us. We take copyright violations extremely seriously and the same applies to improper and abusive use of this form.',
    'feedback.report.copyrightInternalProperty': 'I have published this work on Literary Universe',
    'feedback.reportType.spam': 'Spam or phishing',
    'feedback.reportType.other': 'Other',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`
};