export default {
    'feedback.home': 'सहायता केंद्र',
    'feedback.bugs': 'मुद्दे',
    'feedback.bugs.desc': 'Did you encounter an error or something else that is wrong or out of place? Let us know here!',
    'feedback.features': 'विचार र प्रस्तावहरू',
    'feedback.features.desc': 'नयाँ सुविधाहरू वा वेबसाइटलाई राम्रो बनाउने तरिकाहरूको लागि कुनै विचार छन्? हामीलाई जानकारी दिनुहोस्!',
    'feedback.help': 'सहायता र ट्युटोरियलहरू',
    'feedback.help.desc': 'तपाईंले कसरी _____? उत्तरहरू यहाँ खोज्नुहोस्।',
    'feedback.desc': 'हाम्रो सहायता र समस्या केन्द्रमा तपाईंलाई स्वागत छ!',
    'feedback.faq': 'FAQ',
    'feedback.faq.desc': 'अक्सर पूछे जाने वाले प्रश्न',
    'feedback.open': 'खोला',
    'feedback.closed': 'बन्द',
    'feedback.accepted': 'स्वीकृत',
    'feedback.inprogress': 'कार्यान्वयनमा',
    'feedback.completed': 'पूरा भयो',
    'feedback.fixed': 'त्रुटि ठिक गरियो',
    'feedback.new.bugs': 'नयाँ मुद्दा सूचना दिनुहोस्',
    'feedback.new.features': 'नयाँ सुविधा सुझाव दिनुहोस्',
    'feedback.lang.nosupport': 'तपाईंको हालको भाषा मुद्दाको लागि समर्थित छैन, कृपया अंग्रेजीमा लेख्नुहोस्। धन्यवाद!',
    'feedback.new.thanks': 'Thank you for the notice! We will look into it shortly.',
    'feedback.comment.title': 'टिप्पणी',
    'feedback.comment.desc': 'हामीलाई आफ्नो प्रतिक्रिया पठाउनुहोस्',
    'feedback.comment.legend': 'तपाईंको प्रतिक्रिया - कुनै पनि कुराबारे हामीलाई जानकारी दिनुहोस्',
    'feedback.comment.success': 'तपाईंको प्रतिक्रिया धन्यवाद!',
    'feedback.comment.label': 'तपाईंको टिप्पणी',
    'feedback.copyrightReport.title': 'कपीराइट उल्लंघन',
    'feedback.copyrightReport.desc': 'कपीराइट उल्लंघन सूचना दिनुहोस्',
    'feedback.report.noUser': 'कृपया रिपोर्ट फाइल गर्नका लागि साइन इन गर्नुहोस्।',
    'feedback.voting.totalVoters': 'प्रयोगकर्ताहरूले मत दिएको छन्: {voted, number}',
    'feedback.voting.upvote': 'मत दिनुहोस्',
    'feedback.voting.downvote': 'मत नदिनुहोस्',
    'feedback.voting.score': 'कुल अंक',
    'feedback.report.title': 'अहवाल सामग्री',
    'feedback.report.typeSelect': 'यहाँ समस्या के है?',
    'feedback.reportType.law': 'कानून उल्लंघन',
    'feedback.reportType.vulgar': 'अश्लील/अपमानजनक',
    'feedback.reportType.copyright': 'कॉपीराइट उल्लंघन',
    'feedback.reportType.storyRating': 'गलत उम्र रेटिंग',
    'feedback.reportType.scam': 'धोखाधड़ी',
    'feedback.report.submit': 'रिपोर्ट',
    'feedback.report.submitting': 'रिपोर्टिंग...',
    'feedback.report.violationDesc': 'विवरण',
    'feedback.report.reportSaved': 'रिपोर्ट के लिए धन्यवाद! हम जांच करेंगे और यदि आवश्यक हो तो कार्रवाई करेंगे।',
    'feedback.report.copyrightReportSaved': 'रिपोर्ट के लिए धन्यवाद! हम जांच करेंगे और संपर्क में रहेंगे।',
    'feedback.report.copyrightOwnershipDesc': 'स्वामित्व का दावा',
    'feedback.report.copyrightNotice': 'Please note that you need to be the rightful owner of the work to use this form. If you are not the owner, please inform the owner or use the other category to inform us. We take copyright violations extremely seriously, and the same applies to improper and abusive use of this form.',
    'feedback.report.copyrightInternalProperty': 'मैंने इस कार्य को लिटररी यूनिवर्स पर प्रकाशित किया है',
    'feedback.reportType.spam': 'स्पैम या फिशिंग',
    'feedback.reportType.soliciting': 'Soliciting',
    'feedback.reportType.aiUnmarked': 'Unmarked AI-generated content',
    'feedback.reportType.other': 'अन्य',
    'feedback.report.copyrightType.propertySelectLabel': `कुन {type, select,
    universe {यूनिभर्स}
    story {कथा}
    other {कथा}
  } उल्लंघन गरिएको छ?`,
    'feedback.help.overview': 'Overview',
    'feedback.help.articles': 'Articles',
    'feedback.help.courses': 'Courses',
    'feedback.help.videoTutorials': 'Video tutorials',
    'feedback.help.featuredArticles': 'Featured Articles',
    'feedback.help.featuredCourses': 'Featured Courses',
    'feedback.help.featuredVideos': 'Featured Videos',
    'feedback.help.subCategories': 'Sub-categories',
    'feedback.resolution.title': 'Resolution center',
    'feedback.resolution.desc': 'Manage and resolve reported violations',
    'feedback.reportType.aiGenerated': 'AI-generated content',
    'feedback.resolution.aiGeneration': 'AI Generation Status',
    'feedback.resolution.aiGenerated': 'AI Generated',
    'feedback.resolution.notAiGenerated': 'Not AI Generated',
    'feedback.center.noReports': 'All clear! There are no reported violations.',
    // Added for Resolution Center lists
    'feedback.reportType.unknown': 'Unknown',
    'feedback.report.status.reported': 'Reported',
    'feedback.report.status.investigating': 'Investigating',
    'feedback.report.status.accepted': 'Accepted',
    'feedback.report.status.disputed': 'Disputed',
    'feedback.report.status.fixed': 'Fixed',
    'feedback.report.status.invalid': 'Invalid',
    'feedback.report.status.rejected': 'Rejected',
    'feedback.report.dateDetails': 'Created: {createdAt, date} | Updated: {updatedAt, date}',
    'feedback.report.quickResolution': 'Quick resolution',
    'feedback.report.actions.none': 'No quick action available',
    'feedback.report.actions.storySettings': 'Go to story settings',
    'feedback.report.actions.universeSettings': 'Go to universe settings',
    'feedback.report.description': 'Provided description',
    'feedback.report.copyrightReport': 'We have received copyright claim to this work. We will review the claim and make determination. If you want to provide any additional comment or context, please do so bellow.',
    // Slider component strings
    'feedback.help.selectFeaturedArticles': 'Select featured articles',
    'feedback.help.featuredArticlesDescription': 'These articles will be displayed in a slider on the category page. Articles should have a cover image for best appearance.',
    'feedback.help.addFeatured': 'Add to featured',
    'feedback.help.removeFeatured': 'Remove from featured',
    'feedback.help.noFeaturedArticles': 'No featured articles selected.',
    'feedback.help.noArticles': 'No articles in this category.',
    'feedback.help.noVideos': 'No videos',
    'feedback.help.noCourse': 'No courses',
    'feedback.help.videos': 'Help Videos',
    'feedback.help.noFeaturedVideos': 'No featured videos available yet.',
    'feedback.help.selectFeaturedVideos': 'Select featured videos',
    'feedback.help.featuredVideosDescription': 'These videos will be displayed in a slider on the category page. Videos should have a thumbnail for best appearance.',
    'feedback.help.backToCategory': 'Back to category',
    'feedback.help.watchVideo': 'Watch video'
};