export default {
    'workshop.title': 'तपाईंको काम',
    'workshop.noneassigned': 'तपाईंलाई अहिले सम्पादन गर्ने कुनै काम बुझाइएको छैन।',
    'workshop.notavailable': 'यो सुविधा अहिले सम्पन्न भएको छैन।',
    'workshop.none': `आपके पास वर्तमान में कोई {type, select,
      universe {ब्रह्मांड}
      story {कहानी}
      fanfiction {प्रशंसा करने वाली कथा}
      other {}
    }नहीं है। अब एक बनाएं!`,
    'workshop.collab': 'सहकारी काम',
    'workshop.betareadings': 'बीटा पठाउने',
    'workshop.translations': 'Translations',
    'workshop.createnew': 'Create new...',
    'workshop.story.standalone': 'Standalone story',
    'workshop.story.standalone.desc': 'This is a standalone story.',
    'workshop.controlpanel': '{name} control panel',
    'workshop.universe.page': 'Universe page',
    'workshop.fictionaltime': 'काल्पनिक समय',
    'workshop.dashboard.name': '{name} dashboard',
    'workshop.stories.in': 'Stories in {universe}',
    'workshop.universe.nostories': 'There are no stories in this universe.',
    'workshop.story.chapter.add': 'New chapter',
    'workshop.universe.new': 'Create a new universe',
    'workshop.universe.publish': 'Publish universe',
    'workshop.universe.publishing.notice': 'If you do not publish the universe, it will be published automatically when the first story connected to the universe is published.',
    'workshop.universe.settings': '{universe} universe settings',
    'workshop.universe.publishedOn': 'यह ब्रह्मांड प्रकाशित किया गया है {date, date, long} {date, time, short}',
    'workshop.universe.description': 'Universe description',
    'workshop.settings.title': 'शीर्षक',
    'workshop.description': 'Description',
    'workshop.language.primary': 'प्राथमिक भाषा',
    'workshop.publication.options': 'Publication options',
    'workshop.rating': 'General rating',
    'workshop.universe.rating.desc': 'Stories and fanfiction above this rating will be hidden from the universe page listing from anonymous users and users who are not of the appropriate age.',
    'workshop.universe.license': 'Universe license',
    'workshop.universe.genre.pick': 'Select genre for the universe',
    'workshop.story.genre.pick': 'Select genres for the story',
    'workshop.cover': 'Cover',
    'workshop.nothingtosee': 'Nothing to see here...',
    'workshop.story.cannon': 'Canon story',
    'workshop.story.cannon.desc': 'This story is canonical in {universe} universe.',
    'workshop.story.cannon.desc.create': 'यह कथा {universe} यूनिवर्स में एक कैननिकल कथा के रूप में बनाई जाएगी।',
    'workshop.story.fanfiction.search': 'यूनिवर्स का नाम टाइप करें (यह आपकी पुस्तकालय में होना चाहिए)। और फिर सुझाव से चुनें।',
    'workshop.story.error.nogenres': 'आपको कम से कम एक शैली का चयन करना चाहिए।',
    'workshop.story.error.toomanygenres': 'केवल दो शैली ही की कथा स्वीकार्य है।',
    'workshop.story.error.fanfiction.selectuniverse': 'आपको अपनी फैन फिक्शन के लिए मूल यूनिवर्स का चयन करना चाहिए!',
    'workshop.story.error.tags.toomany': 'प्रति कथा में केवल 10 टैग हो सकते हैं।',
    'workshop.thema.primary': 'Thema Primary Classification',
    'workshop.thema.secondary': 'Thema Secondary Classifications',
    'workshop.thema.secondary.max': 'You can add up to {max} secondary classifications.',
    'workshop.thema.selectedCode': 'Code: {code}',
    'workshop.thema.searchPlaceholder': 'Search by name, e.g. "Science fiction"',
    'workshop.thema.quickRef': '📖 Thema Quick Reference',
    'workshop.story.new': 'एक नई कथा बनाएं',
    'workshop.story.publishing.notice': 'पहले अध्याय प्रकाशित करने पर कथा स्वचालित रूप से प्रकाशित की जाएगी।',
    'workshop.settings.edit': 'सेटिंग्स संपादित करें',
    'workshop.story.publishedOn': 'यह कहानी प्रकाशित की गई है {date, date, long} {date, time, short}',
    'workshop.story.settings': 'कथा सेटिंग्स',
    'workshop.settings.basic': 'मूल सेटिंग्स',
    'workshop.settings.genres': 'शैली (अधिकतम 2)',
    'workshop.story.license': 'कथा लाइसेंस',
    'workshop.story.settings.universe': 'यूनिवर्स सेटिंग्स',
    'workshop.story.dangerZone': 'Danger zone',
    'workshop.story.dangerZone.desc': 'These actions affect how your story is organized across universes. Proceed carefully.',
    'workshop.story.universe.assign.missing': 'Please select a universe to continue.',
    'workshop.story.universe.assignTitle': 'Create or assign a universe',
    'workshop.story.universe.assign.desc': 'Attach this story to an existing universe, or create a brand-new universe using the story details.',
    'workshop.story.universe.assign.mode': 'Universe option',
    'workshop.story.universe.assign.existing': 'Assign to an existing universe',
    'workshop.story.universe.assign.create': 'Create a new universe from this story',
    'workshop.story.universe.assign.loading': 'Loading your universes...',
    'workshop.story.universe.assign.select': 'Select universe',
    'workshop.story.universe.assign.placeholder': 'Choose a universe',
    'workshop.story.universe.assign.none': 'You do not have any universes yet. Create a new one to continue.',
    'workshop.story.universe.assign.publishNote': 'This story is already published, so the new universe will be published too.',
    'workshop.story.universe.assign.createBtn': 'Create universe',
    'workshop.story.universe.assign.trigger': 'Create or assign a universe',
    'workshop.story.universe.standalone.title': 'Make story standalone',
    'workshop.story.universe.standalone.heading': 'Move this story out of its universe?',
    'workshop.story.universe.standalone.desc': 'This story will be removed from the universe and listed as a standalone story.',
    'workshop.story.universe.standalone.current': 'Current universe: {title}',
    'workshop.story.universe.standalone.warning1': 'Readers browsing the universe will no longer see this story listed there.',
    'workshop.story.universe.standalone.warning2': 'Existing links that point to the universe version of this story may stop working.',
    'workshop.story.universe.standalone.warning3': 'You can attach the story to a universe again later from story settings.',
    'workshop.story.universe.standalone.trigger': 'Make story standalone',
    'workshop.settings.tags': 'टैग',
    'workshop.revision': 'संशोधन',
    'workshop.revisions.title': '{story}: {chapter} संशोधन',
    'workshop.revisions.current': 'वर्तमान प्रारूप',
    'workshop.revisions.new.beta': 'ड्राफ्ट से एक नई संशोधन बनाएं।',
    'workshop.revisions.new.public': 'ड्राफ्ट से एक नई सार्वजनिक संशोधन बनाएं।',
    'workshop.revisions.toeditor': 'संपादक पर जाएं',
    'workshop.revisions.comments': 'संशोधन टिप्पणियाँ',
    'workshop.revisions.comments.title': '{story}: {chapter} - संशोधन {revision} - टिप्पणियाँ',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {बेटा वाचकांसाठी}
      readers {सार्वजनिक}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'तपाईंले पहिले एक संशोधन सिर्जना गर्नुपर्छ।',
    'workshop.revisions.comments.select': 'संशोधन छान्नुहोस्',
    'workshop.collaborators.noresults': 'कुनै परिणामहरू छैनन्',
    'workshop.collaborators.add.beta': 'बीटा पाठक थप्नुहोस्',
    'workshop.collaborators.add.collaborator': 'सहकर्मी थप्नुहोस्',
    'workshop.collaborators.add.translator': 'अनुवादक थप्नुहोस्',
    'workshop.collaborators.language.add': 'नयाँ अनुवाद सिर्जना गर्नुहोस्',
    'workshop.translations.stories': 'अनुवादहरू - कथाहरू',
    'workshop.translations.universes': 'अनुवादहरू - विश्वहरू',
    'workshop.revisions.beta.none': 'यस समयमा कुनै संशोधनहरू छैनन्।',
    'reader.asidetoggle': 'अलग जानकारीलाई टगल गर्नुहोस्',
    'workshop.translation.original': 'मूल:',
    'workshop.translation.original.title': 'मूल शीर्षक:',
    'workshop.translation.original.description': 'मूल वर्णन:',
    'workshop.translation.original.cover': 'मूल कवर',
    'workshop.translation.original.tags': 'मूल ट्यागहरू',
    'workshop.cover.alt': 'कवर छवि',
    'workshop.translation.updatedOrig': 'मूलको अन्तिम अद्यावधिकरण: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'अनुवादको अन्तिम अद्यावधिकरण: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'मूलको अन्तिम संशोधन {revision, number}, : {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'अनुवादको अन्तिम संशोधन {revision, number}, : {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `अधिक {type, select,
    collaborator {सहकर्मी}
    beta {बीटा पाठक}
    translator {अनुवादक}
    other {}
  }जोड़ने के लिए, आपको अपने सदस्यता स्तर को बढ़ाना होगा।`,
    'workshop.collaborators.requests.sent': 'पठाएको अनुरोधहरू',
    'workshop.collaborators.requests.invite': `आपको निम्नलिखित के लिए आमंत्रित किया गया है {role, select,
    beta {बीटा पाठक}
    translator {अनुवादक}
    collaborator {सहकर्मी}
    other {}
  } बनने के लिए:`,
    'workshop.collaborators.requests.dashboard': `तपाईंलाई सहयोगमा आमंत्रित गरिएको छ {count, plural,
    zero {कुनै कार्य छैन}
    one {एक साहित्यिक कार्य}
    other {# साहित्यिक कार्यहरू}
  }।`,
    'workshop.collaborators.language.added': 'भाषा थपियो',
    'workshop.story.noChaptersFound': 'कुनै अध्यायहरू भेटिएन।',
    'workshop.fanfic.needUniverseInLibrary': 'यहाँ धेरै ब्रह्माण्डहरू छन्। कृपया तपाईंको पुस्तकालयमा लेख्न चाहानुभएका व्रतहरू थप्नुहोस् भनेरै हामीले तिनीहरूलाई खोज्न सक्छौं।',
    'workshop.fanfic.findUniverse': 'एक अद्भुत ब्रह्माण्ड खोज्नुहोस्!',
    'workshop.encSettings': 'विज्ञानकोष सेटिंग्स',
    'workshop.collaborators.removeUser': 'प्रयोगकर्ता हटाउनुहोस्',
    'workshop.collaborators.cancelInvite': 'आमंत्रण रद्द गर्नुहोस्',
    'workshop.universe.createFirstStory': 'पहिलो कथा सिर्जना गर्नुहोस्',
    'workshop.storylines': 'कथाको रेखाचित्रहरू',
    'workshop.scenesManager': 'दृश्य प्रबन्धक',
    'workshop.collaborators.addRoleForLang': '{language}को लागि {role} थप्नुहोस्',
    'workshop.beta.revisionInfo': 'यो संशोधन {revision, number}, {createdAt, date, long}मा सिर्जना गरिएको हो।',
    'workshop.story.notes.title': 'तपाईंको {storyTitle}को लागि नोटहरू',
    'workshop.story.notes.desc': 'कथाको बारेमा अवलोकन नोटहरू।',
    'workshop.story.notes.tile': 'अवलोकन नोटहरू',
    'workshop.story.alternateFormats.tile': 'Alternate formats',
    'workshop.story.alternateFormats.title': '{storyTitle}: Alternate formats',
    'workshop.story.alternateFormats.arcs.title': 'Arcs',
    'workshop.story.alternateFormats.arcs.add': 'Add arc',
    'workshop.story.alternateFormats.arc.defaultTitle': 'Arc {index}',
    'workshop.story.alternateFormats.arc.name': 'Arc name',
    'workshop.story.alternateFormats.arc.from': 'From chapter',
    'workshop.story.alternateFormats.arc.to': 'To chapter',
    'workshop.story.alternateFormats.arc.uploads': 'Files',
    'workshop.story.alternateFormats.arc.upload.epub': 'Upload EPUB',
    'workshop.story.alternateFormats.arc.upload.pdf': 'Upload PDF',
    'workshop.story.alternateFormats.epub.generate': 'Generate EPUB',
    'workshop.story.alternateFormats.epub.openGenerated': 'Open generated EPUB',
    'workshop.story.alternateFormats.epub.generatedAt': 'Generated on {generatedAt, date, medium} at {generatedAt, time, short}',
    'workshop.story.alternateFormats.epub.generationFailed': 'EPUB generation failed.',
    'workshop.story.alternateFormats.epub.saveArcBeforeGeneration': 'Save this arc first to enable EPUB generation.',
    'workshop.story.alternateFormats.fullStory.title': 'Full story file',
    'workshop.story.alternateFormats.ongoingAccess.title': 'Ongoing access',
    'workshop.story.alternateFormats.ongoingAccess.allAvailable': 'All currently available chapters',
    'workshop.story.alternateFormats.ongoingAccess.perChapter': 'Per chapter (as chapters are released)',
    'workshop.hideOrgs': 'संगठनहरूबाट सामग्री लुकाउनुहोस्',
    'workshop.translation.premium': 'अनुवादहरू थप्नका लागि, तपाईंलाई कम्तीमा एक्स्प्लोरर सदस्यता हुनुपर्छ।',
    'workshop.story.finished': 'कथा पूर्ण भयो',
    'workshop.story.publishing.externalSellingNotice': 'तपाईं लेखन यूनिभर्सबाट बाहिर बेचिरहेका छन्, यसले तपाईंलाई कथा अब तुरुन्तै प्रकाशित गर्ने छ। तपाईंको स्टोर लिस्टिंगमा लिङ्कहरू कथाको अन्तिममा वा कथाको अन्तिममा देखाइनेछ।',
    'workshop.sharing.publicURL': 'सार्वजनिक संस्करण',
    'workshop.fictionalTime.title': '{universeName}को लागि काल्पनिक समयहरू',
    'workshop.fictionalTime.none': 'तपाईंले वर्तमानमा कुनै काल्पनिक समय सेट-अप गरेका छैनन्।',
    'workshop.fictionalTime.createNow': 'अब एक बनाउनुहोस्!',
    'workshop.fictionalTime.createTitle': 'नयाँ काल्पनिक समय बनाउनुहोस्',
    'workshop.fictionalTime.editTitle': 'सम्पादन गर्नुहोस् {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'समयको नाम',
    'workshop.fictionalTime.basicInfo': 'मूलभूत जानकारी',
    'workshop.fictionalTime.timeSetup': 'समय सेट-अप',
    'workshop.fictionalTime.linkedToET': 'के यो समय भूमिकोमा प्रारम्भ हुन्छ (ग्रेगोरियन क्यालेण्डर)?',
    'workshop.fictionalTime.timeDeclaration': 'समय घोषणा',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'इकाईहरू अघि',
    'workshop.fictionalTime.declarationAfter': 'इकाईहरू पछि',
    'workshop.fictionalTime.declarationNone': 'कुनै पनि',
    'workshop.fictionalTime.units': 'इकाईहरू',
    'workshop.fictionalTime.ETStart': 'यस समयको प्रारम्भ मिति',
    'workshop.fictionalTime.unitsDescFirst': 'यस इकाईमा कति इकाईहरू छन् मिलिसेकेण्डबाट?',
    'workshop.fictionalTime.unitsDesc': 'यो एक देखि पहिले एक इकाईमा कति इकाईहरू छन्?',
    'workshop.fictionalTime.unitsName': 'इकाईको नाम',
    'workshop.fictionalTime.unitsSeparator': 'अघिको इकाईबाट विभाजक',
    'workshop.fictionalTime.unitAdd': 'इकाई थप्नुहोस्',
    'workshop.fictionalTime.clocks': 'घडीहरू',
    'workshop.fictionalTime.unitTransfer': 'इकाईहरू स्थानान्तरण गर्नुहोस्',
    'fictionalTime.pageStartElapsedTime': 'यस पृष्ठ खोल्नु भएको बेला बितेको समय',
    'fictionalTime.currentTime': 'वर्तमान समय',
    'workshop.shoppingExternal.options': 'बाह्य खरिद विकल्पहरू',
    'workshop.shoppingExternal.explainer': 'यदि तपाईंको कथा अरु कही बेचिएको छ भने तपाइँ यहाँ लिंकहरू सेट गर्न सक्नुहुन्छ। त्यसपछि लिंकहरू सामग्रीको स्थानमा वा सामग्रीको अन्तमा देखाइनेछ।',
    'workshop.shoppingExternal.amazonStore': 'अमेज़न स्टोर',
    'workshop.shoppingExternal.amazon': 'अमेज़न',
    'workshop.shoppingExternal.storeName': 'स्टोर नाम',
    'workshop.shoppingExternal.itemUrl': 'वस्तु URL',
    'workshop.shoppingExternal.storesOther': 'अन्य स्टोरहरू',
    'fictionalTime.units.milliseconds': '{units, number} मिलिसेकेण्ड',
    'fictionalTime.countdownToStart': 'समय सुरु हुने गणना',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 दिन }
      other {{days} दिन }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {सेकेण्ड}
      other {सेकेण्ड}
    }}
    minutes {{units, plural,
      one {मिनट}
      other {मिनट}
    }}
    hours {{units, plural,
      one {घंटा}
      other {घंटे}
    }}
    days {{units, plural,
      one {दिन}
      other {दिन}
    }}
    years {{units, plural,
      one {वर्ष}
      other {वर्ष}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'देखि',
    'fictionalTime.inputSelectTimeUnit': 'समय इकाई छान्नुहोस्',
    'fictionalTime.inputSelectETUnit': 'पृथ्वीको समय इकाई छान्नुहोस्',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'साइडबार टुलबक्स',
    'workshop.writerSidebar.description': 'तपाईंको कथामा स्वागत छ! यो साइडबारले तपाईंलाई तपाईंको कथासँग सम्बन्धित सबै स्रोतहरूमा सजिलै पहुँच प्रदान गर्दछ। नवीनतम टिप्पणीहरू, तपाईंका नोटहरू र अरु कुराहरू हेर्न यहाँ उपलब्ध चिन्हहरू जाँच्नुहोस्।',
    'workshop.story.authorsNotesExplained': 'अपने नोट्स चैप्टर के शुरुआत में पाठकों को पढ़ने के लिए।',
    'workshop.story.chapterSortSwitch': 'अध्याय के क्रम को बदलें',
    'workshop.story.prolog': 'प्रोलोग',
    'workshop.story.chapter': 'अध्याय {sequence, number}',
    'workshop.work.includesAds': 'क्या कार्य में कोई विज्ञापन या उत्पाद स्थानन शामिल हैं?',
    'workshop.universe.forumSettings': 'आन्तरिक ब्रह्माण्ड फोरम सेटिंग्स',
    'workshop.ratingAdjusted': 'उद्धार कारणात आम्ही आपल्या रेटिंगला त्याच्या आपल्याला योग्य वाटलेल्या एकाच रेटिंगवर बदल करणे अक्षम केले आहे. असा कारण आता रेटिंग बदलणे अक्षम आहे.',
    'workshop.rating.disabled.sexualContent': 'Rating is locked to Explicit (21+) because you selected Sexual Content in content warnings.',
    'workshop.contentWarnings.title': 'Content Warnings',
    'workshop.contentWarnings.description': 'Select applicable content warnings to inform readers about potentially sensitive content',
    'workshop.contentWarnings.graphicViolence': 'Graphic Violence',
    'workshop.contentWarnings.graphicViolence.description': 'Detailed descriptions of violent acts, including but not limited to physical harm, bloodshed, mutilation, or any other explicit depictions of violence that may be considered disturbing or excessively graphic.',
    'workshop.contentWarnings.profanity': 'Profanity',
    'workshop.contentWarnings.profanity.description': 'Excessive or obscene swearing and cursing.',
    'workshop.contentWarnings.sensitiveContent': 'Sensitive Content',
    'workshop.contentWarnings.sensitiveContent.description': 'Descriptions of torture, slavery, substance abuse, mental illness, addiction, mentions of rape, self-harm or any other content that may be considered traumatizing or mature that does not fall under the warning tags. This content is not glorified.',
    'workshop.contentWarnings.sexualContent': 'Sexual Content',
    'workshop.contentWarnings.sexualContent.description': 'Explicit sexual content (text only), descriptive sex scenes. This will automatically set the rating to Explicit (21+).',
    'workshop.selectCollaborator': 'सहकारी निवडा',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'ड्राफ्ट',
    'workshop.chapterStatus.scheduled': 'नियोजित',
    'workshop.chapterStatus.published': 'प्रकाशित',
    'workshop.story.continuedIn': 'कोणती कथा ही कथा सुरू करतात?',
    'workshop.story.continuedPlaceholder': 'या विश्वातील कथा निवडा',
    'workshop.universe.isAIGenerated': 'किंवा या विश्वाचे सामग्री AI द्वारे उत्पन्न केली जाते का?',
    'workshop.universe.isAIGeneratedTooltip': 'कृपया आपल्याला सांगा की कोणतीही विश्वाची सामग्री AI द्वारे किंवा मदतीसह उत्पन्न केली गेली आहे का. आपण या माहितीचा उच्चारण ठेवतो आणि AI कार्यक्रम उत्पन्न कसे होतात ह्यामुळे काही मर्यादा आणि प्रतिबंध्या असू शकतात.',
    'workshop.story.isAIGenerated': 'किंवा कथा AI द्वारे उत्पन्न केली जाते का?',
    'workshop.story.isAIGeneratedTooltip': 'कृपया आपल्याला सांगा की कोणत्याही कथेची सामग्री AI द्वारे किंवा मदतीसह उत्पन्न केली गेली आहे का. आपण या माहितीचा उच्चारण ठेवतो आणि AI कार्यक्रम उत्पन्न कसे होतात ह्यामुळे काही मर्यादा आणि प्रतिबंध्या असू शकतात.',
    'workshop.publicationAgreement.aria': 'कामासाठी प्रकाशन समजूती',
    'workshop.publicationAgreement.intro': 'आपण आपल्या सृजनशील कामाचे प्रकाशन आपल्यासोबत केले असल्याबद्दल आपल्याला आनंद आहे. आपण आगाऊ जाण्यासाठी आपल्याला केवळ आमच्या प्रकाशन समजूतीवर दृष्टी ठेवायला हवं.',
    'workshop.sortChapters': 'क्रमवारी:',
    'workshop.sortChapters.ascending': 'प्रारंभापासून',
    'workshop.sortChapters.descending': 'नवीनतम बाट',
    'workshop.sortChapters.aria': 'अध्याय सूचीको कुन तरिकामा क्रमबद्ध गर्नुहोस् चयन गर्नुहोस्',
    'workshop.hiatus.btn': 'कथा स्थिति बदल्नुहोस् हायाटसमा',
    'workshop.cancelled.btn': 'कथा स्थिति बदल्नुहोस् रद्द गरिएकोमा',
    'workshop.complete.btn': 'कथा स्थिति बदल्नुहोस् पूरा गरिएकोमा',
    'workshop.statusChange.modalTop': 'के तपाईं निश्चित हुन चाहानुहुन्छ कि स्थिति बदल्नुहोस्',
    'workshop.statusName.hiatus': 'हायाटस',
    'workshop.statusName.cancelled': 'रद्द गरिएको',
    'workshop.statusName.completed': 'पूरा भयो',
    'workshop.statusExplain.hiatus1': 'हायाटस भनेको तपाईंले यस कथामा काम गर्न तालाछ राख्नु भएको हो। यसले तपाईंका पाठकलाई बताउनेछ कि आउने हप्तामा वा केही महिनासम्म कुनै नयाँ अद्यावधिकहरूको आशा नगर्नुहोस्।',
    'workshop.statusExplain.hiatus2': 'हायाटस स्थिति आफूले कुनै अध्याय प्रकाशित गरेमा स्वतःले उठाईनेछ। वा तपाईंले यसलाई आफूले बदल्न सक्नुहुन्छ।',
    'workshop.statusExplain.hiatus3': 'यदि तपाईं आफ्नो कथालाई हायाटसमा छ र ६ महिनासम्म राख्नुहुन्छ, हामी यस कथालाई स्वतः रद्द गर्नेछौं।',
    'workshop.statusExplain.cancelled1': 'कथा मा काम गर्न सम्भव नभएकोले हामी छानबिन गर्न खुसी छौं। अर्को बाट हामीले यो जानकारी दिनुलाई तपाईंलाई धेरै खुसी छौं।',
    'workshop.statusExplain.cancelled2': 'कथा रद्द गर्ने तपाईंका पाठकलाई बताउनेछ कि नयाँ अद्यावधिकहरूको आशा नगर्नुहोस्।',
    'workshop.statusExplain.cancelled3': 'तपाईं सधैं यसलाई फेरी प्रकाशित गर्न सक्नुहुन्छ वा स्थिति बदल्न सक्नुहुन्छ।',
    'workshop.statusExplain.finished1': 'बधाई छ! सबै उठाएको कठिन कामपछि तपाईं अब अत्यन्तै अद्भुत यात्राको अन्तिम भागमा पुगे हुनुभयो। कथामा अब समाप्त भएकोले, भविष्यमा बढी कथाहरू छन् भनेर हामी आशा गर्छौं, तर अहिले समय नै आराम गर्नुहोस् र आनन्द लिनुहोस्।',
    'workshop.statusExplain.finished2': 'कथालाई पूर्ण मान्ने लाई पाठकलाई बताउनेछ कि कथा समाप्त भएको छ। तपाईंले कुनै नयाँ अध्याय थप्नु नपर्नुपर्छ तर हामी तपाईंलाई रोक्ने छैनौं। विशेष अध्यायहरू थप्ने कुरा बिर्सनुहोस्, जस्तै सबै पात्रहरूका लागि अधिक निवास दिने लागि।',
    'workshop.statusExplain.finished3': 'तपाईं यस स्थिति रद्द गर्न सक्नुहुन्छ तर हामी त्यसलाई अत्यन्तै विरोध गर्दछौं। यदि कथा जारी राख्ने भएमा नयाँ कथा सुरु गर्न अझै राम्रो हुन सक्छ।',
    'workshop.status.goActive': 'कथा फेरी सक्रिय बनाउनुहोस्',
    'workshop.statusChangeEmail.storyIntro': 'हम तपाईंलाई सूचित गर्न चाहन्छौं कि तपाईंको कथा:',
    'workshop.statusChangeEmail.hiatusTitle': 'तपाईंको कथा स्थिति स्वचालित रूपमा हाइअसमा सेट गरियो',
    'workshop.statusChangeEmail.hiatusIntro': 'निष्क्रियता कारण तपाईंको कथा स्थिति स्वचालित रूपमा हाइअसमा सेट गरियो।',
    'workshop.statusChangeEmail.hiatusWhy': '6 महिना भन्दा बढी समयदेखि कुनै नयाँ अध्याय प्रकाशित नभएको कारण यो स्वचालित रूपमा हाइअसमा राखिएको छ।',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'यदि तपाईं नयाँ अध्याय प्रकाशित गर्नुहुन्छ भने यो स्थिति स्वचालित रूपमा उठाइनेछ। यदि तपाईं 6 महिना भित्र नयाँ अध्याय प्रकाशित नगर्नुहुन्छ भने हामी स्वचालित रूपमा कथा रद्द गर्नेछौं।',
    'workshop.statusChangeEmail.cancellationIntro': 'तपाईंको कथा स्थिति स्वचालित रूपमा रद्द गरियो।',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'यदि तपाईं नयाँ अध्याय प्रकाशित गर्न योजना नगर्नुहुन्छ भने तपाईंलाई अरु कुनै काम गर्नुपर्ने छैन।',
    'workshop.startCreating': 'सृजना गर्नुहोस्',
    'workshop.ownWork': 'आफ्नो काम',
    'workshop.list.thumbs': 'थम्बनेलहरूको सूची',
    'workshop.list.list': 'संक्षेप्त सूची',
    'workshop.fanfiction.new': 'नयाँ फ्यान फिक्शन सिर्जना गर्नुहोस्',
    'workshop.videoTrailerLink': 'भिड़ियो ट्रेलर लिंक',
    'workshop.videoTrailerPlayerTitle': 'कथा भिड़ियो ट्रेलर प्लेयर',
    'workshop.videoTrailer.supportedPlaftorms': 'हम Youtube, Vimeo और Odysee का समर्थन करते हैं',
    'workshop.videoTrailer.rumble': 'हम रुम्बल भी समर्थित करते हैं, लेकिन याद रखें कि IFRAME URL की प्रतिलिपि बनाएं।',
    'workshop.videoTrailer.suggestPlatforms': 'तपाईंको भिडियो प्लatform नभएको छ, हामीलाई <a>प्रतिक्रिया</a>द्वारा जानकारी दिनुहोस्!',
    'workshop.cover.edit': 'Change cover',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    // Chapter deletion
    'workshop.chapter.delete.modalAria': 'Confirmation modal for deleting a chapter',
    'workshop.chapter.delete.confirm': 'Delete Chapter',
    'workshop.chapter.delete.warning': 'Are you sure you want to delete "{title}"? This action cannot be undone.',
    'workshop.chapter.delete.button': 'Delete Chapter',
    'workshop.chapter.delete.deleting': 'Deleting...',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.',
    'workshop.timer.settings': 'Timer Settings',
    'workshop.timer': 'Timer',
    'workshop.timer.type': 'Type',
    'workshop.timer.timer': 'Timer',
    'workshop.timer.countdown': 'Countdown',
    'workshop.timer.pomodoro': 'Pomodoro',
    'workshop.timer.mode': 'Mode',
    'workshop.timer.regular': 'Regular',
    'workshop.timer.improved': 'Improved',
    'workshop.timer.duration': 'Duration (min)',
    'workshop.timer.workDuration': 'Work (min)',
    'workshop.timer.breakDuration': 'Break (min)',
    'workshop.timer.breakType': 'Break Type',
    'workshop.timer.softBreak': 'Soft Break',
    'workshop.timer.hardBreak': 'Hard Break',
    'workshop.timer.break': 'Break',
    'workshop.timer.breakTime': 'Break Time!',
    'workshop.timer.breakMessage': 'Take a moment to rest. Click anywhere to dismiss.',
    'workshop.timer.pause': 'Pause',
    'workshop.timer.resume': 'Resume',
    'workshop.timer.stop': 'Stop',
    'workshop.timer.start': 'Start',
    'workshop.timer.tabInactive': 'Timer paused - switch back to tab to continue',
    // Timer descriptions
    'workshop.timer.type.timer.desc': 'Simple stopwatch that starts at 0:00 and counts upward. Perfect for tracking total writing time in a session or seeing how long you\'ve been working continuously. Never ends automatically - you control when to stop.',
    'workshop.timer.type.countdown.desc': 'Countdown timer that starts from your set duration and counts down to zero. Great for time-boxed writing sessions, word sprints, or when you want to work for a specific amount of time before taking a break.',
    'workshop.timer.type.pomodoro.desc': 'Structured productivity technique: 25-minute focused work sessions alternating with 5-minute breaks. After 4 cycles, takes a longer 15-30 minute break. Scientifically proven to improve focus and prevent burnout.',
    'workshop.timer.mode.regular.desc': 'Timer runs continuously regardless of your activity. Best for disciplined writers who want to track time even when researching, editing, or taking short breaks. Timer keeps going when you switch tabs or stop typing.',
    'workshop.timer.mode.improved.desc': 'Smart timer that automatically pauses when you switch browser tabs. Perfect for focused writing sessions where you want accurate tracking of actual writing time, not total time spent on the page.',
    'workshop.timer.breakType.soft.desc': 'Gentle reminder approach: Shows a small notification when break time starts. You can choose to continue working if you\'re in \'the zone\' or take the break. Good for flexible writers who sometimes need to extend productive sessions.',
    'workshop.timer.breakType.hard.desc': 'Strict enforcement: Displays a full-screen modal that prevents further input until the break timer completes. Forces you to step away from the keyboard. Ideal for writers who struggle with self-discipline or workaholics who need enforced rest periods.',
    'workshop.timer.duration.timer.desc': 'How long you plan to write in this session. Start with 25-50 minutes for focused work, or set longer sessions (2-4 hours) for deep writing days.',
    'workshop.timer.duration.countdown.desc': 'Target writing time before the timer ends. Try 25 minutes for focused sprints, 45-60 minutes for substantial work sessions, or 90 minutes for creative deep dives.',
    'workshop.timer.workDuration.desc': 'Length of focused work sessions. Traditional Pomodoro uses 25 minutes. Try 15-20 minutes if you find it hard to concentrate for longer periods, or 45-50 minutes for experienced writers who can maintain deep focus.',
    'workshop.timer.breakDuration.desc': 'Rest period between work sessions. Standard is 5 minutes for short breaks. Use 10-15 minutes for longer breaks that allow you to step away from your desk, stretch, or get a drink. Every 4th break is automatically longer (2-3x duration).',
    'workshop.llmstxt': 'AI Access',
    'workshop.llmstxt.blocked': 'Blocked - LLMs cannot access your content',
    'workshop.llmstxt.limited': 'Limited - LLMs can only access meta data',
    'workshop.llmstxt.free': 'Free - LLMs can access your content for free',
    'workshop.llmstxt.paid': 'Paid - LLMs can access your content for a fee (coming soon)',
    'workshop.ai.llmstxt.generate': 'Generate LLMs.txt',
    'workshop.ai.llmstxt.generating': 'Generating LLMs.txt...',
    'workshop.ai.llmstxt.download': 'Download LLMs.txt',
    'workshop.ai.llmstxt.title': 'Texts for AI services',
    'workshop.ai.agent.title': 'Assistant',
    'workshop.ai.llmstxt.story-info': 'Story Info LLMs.txt',
    'workshop.ai.llmstxt.full-content': 'Full Content LLMs.txt',
    'workshop.ai.llmstxt.info': 'Info LLMs.txt - Basic information for AI',
    'workshop.ai.llmstxt.infoShort': 'Basic information',
    'workshop.ai.llmstxt.full': 'Content LLMs.txt - Full content for AI',
    'workshop.ai.llmstxt.fullShort': 'Full content'
};