/**
 * Licenses for creative works
 * https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
 */
export default {
    'licenses.about': 'Om licenser',
    'licenses.more': 'Flere oplysninger',
    'licenses.legal': 'Juridisk dokument',
    'licenses.name.cc-by': 'Creative Commons Kreditering 4.0',
    'licenses.cc-by': 'Denne licens giver andre lov til at distribuere, remixe, justere og bygge videre på dit arbejde, selv kommercielt, så længe de giver dig kredit for det oprindelige værk. Dette er den mest imødekommende licens, der tilbydes. Anbefales til maksimal spredning og brug af licenseret materiale.',
    'licenses.name.cc-by-sa': 'Creative Commons Kreditering-Deling på samme vilkår 4.0',
    'licenses.cc-by-sa': 'Denne licens giver andre mulighed for at remixe, tilpasse og bygge videre på dit arbejde, selv til kommercielle formål, så længe de krediterer dig og giver licens til deres nye kreationer under de samme vilkår. Denne licens sammenlignes ofte med "copyleft"-licenser til gratis og open source-software. Alle nye værker, der er baseret på dit, vil have samme licens, så alle afledte værker vil også tillade kommerciel brug. Det er den licens, der bruges af Wikipedia, og den anbefales til materialer, der vil have gavn af at inkorporere indhold fra Wikipedia og lignende projekter med samme licens.',
    'licenses.name.cc-by-nd': 'Creative Commons Kreditering-Ingen afledninger 4.0',
    'licenses.cc-by-nd': 'Denne licens tillader redistribution, kommerciel og ikke-kommerciel, så længe den videregives uændret og i sin helhed, med kredit til dig.',
    'licenses.name.cc-by-nc': 'Creative Commons Kreditering-Ikkekommerciel 4.0',
    'licenses.cc-by-nc': 'Denne licens giver andre mulighed for at remixe, tilpasse og bygge videre på dit værk på ikke-kommerciel vis, og selvom deres nye værker også skal anerkende dig og være ikke-kommercielle, behøver de ikke at give licens til deres afledte værker på de samme vilkår.',
    'licenses.name.cc-by-nc-sa': 'Creative Commons Kreditering-Ikkekommerciel-Deling på samme vilkår 4.0',
    'licenses.cc-by-nc-sa': 'Denne licens giver andre lov til at remixe, justere og bygge videre på dit arbejde ikke-kommercielt, så længe de giver dig kredit og licenserer deres nye kreationer under de samme vilkår.',
    'licenses.name.cc-by-nc-nd': 'Creative Commons Kreditering-Ikkekommerciel-Ingen afledninger 4.0',
    'licenses.cc-by-nc-nd': 'Denne licens er den mest restriktive af vores seks hovedlicenser og tillader kun andre at downloade dine værker og dele dem med andre, så længe de krediterer dig, men de kan ikke ændre dem på nogen måde eller bruge dem kommercielt.',
    'licenses.name.lu-c': 'Litterære Universe Ophavsrettigheder',
    'licenses.lu-c': 'Standard fulde ophavsrettighedslicens, der giver dig lov til at sælge og udgive dit arbejde, som du ønsker, og beskytter dine rettigheder til det. Denne licens giver dig også mulighed for at sælge dine historier på Litterære Universe.',
    'licenses.name.lu-e': 'Litterært univers eksklusivt',
    'licenses.lu-e': 'Denne licens giver Literary Universe eksklusiv ret til at udgive og distribuere dit værk online. Du beholder ophavsretten, men Literary Universe har eneret til at udgive og distribuere dit værk online.',
    'licenses.name.lu-ne': 'Litterært univers ikke-eksklusivt',
    'licenses.lu-ne': 'Denne licens giver Literary Universe ikke-eksklusive rettigheder til at udgive og distribuere dit værk online. Du beholder ophavsretten og retten til at udgive og distribuere dit værk gennem andre kanaler.',
    'licenses.name.cc0': 'Ingen ophavsret - CC0 1.0',
    'licenses.cc0': 'Gør dit arbejde offentligt tilgængeligt. I modsætning til CC\'s licenser, der giver indehavere af ophavsret mulighed for at vælge mellem en række tilladelser, mens de bevarer deres ophavsret, giver CC0 mulighed for endnu et valg - valget om at fravælge ophavsret og databasebeskyttelse og de eksklusive rettigheder, der automatisk gives til skabere - alternativet "ingen rettigheder forbeholdt" til vores licenser.',
    // License Chooser Modal
    'licenses.chooser.title': 'Valg af licens',
    'licenses.chooser.button': 'Hjælp mig med at vælge en licens',
    'licenses.chooser.ariaLabel': 'Vælg en licens til dit arbejde',
    'licenses.chooser.introduction': 'Dette værktøj hjælper dig med at vælge den mest passende licens til dit værk. Licensen afgør, hvordan andre kan bruge dit værk, og påvirker dine muligheder for at tjene penge på det i Literary Universe.',
    // License Chooser Wizard Steps
    'licenses.chooser.step.contentType.title': 'Hvilken type indhold giver du licens til?',
    'licenses.chooser.step.contentType.description': 'Typen af indhold påvirker, hvilke licenser der er tilgængelige for dig.',
    'licenses.chooser.step.contentType.original': 'Originalt værk',
    'licenses.chooser.step.contentType.fanfiction': 'Fanfiktion',
    'licenses.chooser.step.contentType.fanfictionNote': 'Fanfiction-værker på Literary Universe tildeles automatisk Creative Commons Attribution-NonCommercial-licensen (CC BY-NC). Det skyldes, at fanfiktion er baseret på ophavsretligt beskyttede værker, der ejes af andre, og at kommerciel brug potentielt ville krænke disse rettigheder.',
    'licenses.chooser.step.commercial.title': 'Vil du tjene penge på dit arbejde?',
    'licenses.chooser.step.commercial.description': 'Hvis du vælger at tjene penge på dit arbejde, påvirker det, hvilken licens der er mest hensigtsmæssig.',
    'licenses.chooser.step.commercial.yes': 'Ja, jeg vil tjene penge på mit arbejde',
    'licenses.chooser.step.commercial.no': 'Nej, jeg vil ikke tjene penge på mit arbejde',
    'licenses.chooser.step.commercial.monetizeNote': 'Hvis du vil tjene penge på dit arbejde på Literary Universe, skal du bruge en af vores kommercielle licenser. Disse licenser giver dig mulighed for at sælge dit arbejde, mens du bevarer din ophavsretlige beskyttelse.',
    'licenses.chooser.step.exclusivity.title': 'Vil du udgive eksklusivt på Literary Universe?',
    'licenses.chooser.step.exclusivity.description': 'Valg af eksklusivitet påvirker platformens gebyr og udgivelsesmuligheder.',
    'licenses.chooser.step.exclusivity.yes': 'Ja, udelukkende på Literary Universe',
    'licenses.chooser.step.exclusivity.no': 'Nej, jeg vil også gerne udgive andre steder',
    'licenses.chooser.step.exclusivity.exclusiveNote': 'Med eksklusiv udgivelse på Literary Universe får du fordel af et lavere platformsgebyr på 10 %. Det betyder, at du beholder 90 % af din indtjening.',
    'licenses.chooser.step.exclusivity.nonExclusiveNote': 'Med ikke-eksklusiv udgivelse kan du også udgive dit værk på andre platforme. Platformsgebyret er 30 %, hvilket betyder, at du beholder 70 % af din indtjening på Literary Universe. I fremtiden vil vi tilbyde værktøjer, der kan hjælpe dig med at udgive på andre platforme direkte fra Literary Universe.',
    'licenses.chooser.step.derivatives.title': 'Vil du tillade andre at skabe afledte værker?',
    'licenses.chooser.step.derivatives.description': 'Afledte værker omfatter tilpasninger, remix eller transformationer af dit originale værk.',
    'licenses.chooser.step.derivatives.yes': 'Ja, tillad afledte værker',
    'licenses.chooser.step.derivatives.no': 'Nej, tillad ikke afledte værker',
    'licenses.chooser.step.derivatives.allowNote': 'At tillade afledte værker betyder, at andre kan tilpasse, remixe eller transformere dit arbejde. Det kan føre til bredere distribution og kreativ genbrug af dit indhold.',
    'licenses.chooser.step.derivatives.disallowNote': 'Hvis du ikke tillader afledte værker, betyder det, at dit værk skal videregives uændret og i sin helhed, selvom det stadig kan deles med korrekt henvisning.',
    'licenses.chooser.step.attribution.title': 'Vil du kræve attribution?',
    'licenses.chooser.step.attribution.description': 'Attribution betyder, at andre skal give dig kredit, når de bruger dit arbejde.',
    'licenses.chooser.step.attribution.yes': 'Ja, kræver tilskrivning',
    'licenses.chooser.step.attribution.no': 'Nej, placer i offentligt domæne (CC0)',
    'licenses.chooser.step.attribution.requireNote': 'At kræve kreditering betyder, at alle, der bruger dit arbejde, skal give dig kredit på den måde, du beder om.',
    'licenses.chooser.step.attribution.publicDomainNote': 'Hvis du placerer dit værk i det offentlige domæne (CC0), betyder det, at du giver afkald på al ophavsret og relaterede rettigheder. Andre kan frit bruge dit værk til ethvert formål uden at angive det.',
    // License Result
    'licenses.chooser.result.commercialTitle': 'Kommerciel information',
    'licenses.chooser.result.exclusiveInfo': 'Med Literary Universe Exclusive-licensen får du fordel af et lavere platformsgebyr på 10 %. Det betyder, at du beholder 90 % af din indtjening, men du kan kun udgive dit værk på Literary Universe.',
    'licenses.chooser.result.nonExclusiveInfo': 'Med Literary Universe Non-Exclusive-licensen kan du også udgive dit værk på andre platforme. Platformsgebyret er 30 %, hvilket betyder, at du beholder 70 % af din indtjening på Literary Universe. I fremtiden vil vi stille værktøjer til rådighed, som kan hjælpe dig med at udgive på andre platforme direkte fra Literary Universe.',
    'licenses.chooser.result.fanfictionNote': 'Denne licens gælder automatisk for fanfiktionsværker, fordi de er baseret på ophavsretligt beskyttet materiale, der ejes af andre. Kommerciel brug ville potentielt krænke disse rettigheder.',
    'licenses.chooser.result.selectLicense': 'Vælg denne licens',
    // Adding missing internationalization strings
    'licenseChooser.contentType.title': 'Hvilken type indhold giver du licens til?',
    'licenseChooser.contentType.description': 'Typen af indhold påvirker, hvilke licenser der er tilgængelige for dig.',
    'licenseChooser.contentType.original.title': 'Originalt værk',
    'licenseChooser.contentType.original.description': 'Indhold, som du helt selv har skabt.',
    'licenseChooser.contentType.fanfiction.title': 'Fanfiktion',
    'licenseChooser.contentType.fanfiction.description': 'Indhold baseret på eksisterende værker af andre skabere.',
    'licenseChooser.contentType.fanfiction.note': 'Fanfiction-værker på Literary Universe tildeles automatisk Creative Commons Attribution-NonCommercial-licensen (CC BY-NC). Det skyldes, at fanfiktion er baseret på ophavsretligt beskyttede værker, der ejes af andre, og at kommerciel brug potentielt ville krænke disse rettigheder.',
    'licenseChooser.commercial.title': 'Vil du tjene penge på dit arbejde?',
    'licenseChooser.commercial.description': 'Hvis du vælger at tjene penge på dit arbejde, påvirker det, hvilken licens der er mest hensigtsmæssig.',
    'licenseChooser.commercial.yes.title': 'Ja, jeg vil tjene penge',
    'licenseChooser.commercial.yes.description': 'Jeg vil gerne tjene penge på mit arbejde på Literary Universe.',
    'licenseChooser.commercial.no.title': 'Nej, jeg vil ikke tjene penge på det',
    'licenseChooser.commercial.no.description': 'Jeg vil gerne dele mit arbejde frit uden at tjene penge på det.',
    'licenseChooser.commercial.note': 'Hvis du vil tjene penge på dit arbejde på Literary Universe, skal du bruge en af vores kommercielle licenser. Disse licenser giver dig mulighed for at sælge dit arbejde, mens du bevarer din ophavsretlige beskyttelse.',
    'licenseChooser.exclusivity.title': 'Vil du udgive eksklusivt på Literary Universe?',
    'licenseChooser.exclusivity.description': 'Valg af eksklusivitet påvirker platformens gebyr og udgivelsesmuligheder.',
    'licenseChooser.exclusivity.yes.title': 'Ja, udelukkende på Literary Universe',
    'licenseChooser.exclusivity.yes.description': 'Jeg vil kun udgive dette værk på Literary Universe.',
    'licenseChooser.exclusivity.no.title': 'Nej, jeg vil også gerne udgive andre steder',
    'licenseChooser.exclusivity.no.description': 'Jeg vil også gerne udgive dette arbejde på andre platforme.',
    'licenseChooser.exclusivity.exclusive.note': 'Med eksklusiv udgivelse på Literary Universe får du fordel af et lavere platformsgebyr på 10 %. Det betyder, at du beholder 90 % af din indtjening.',
    'licenseChooser.exclusivity.nonExclusive.note': 'Med ikke-eksklusiv udgivelse kan du også udgive dit værk på andre platforme. Platformsgebyret er 30 %, hvilket betyder, at du beholder 70 % af din indtjening på Literary Universe.',
    'licenseChooser.derivatives.title': 'Vil du tillade andre at skabe afledte værker?',
    'licenseChooser.derivatives.description': 'Afledte værker omfatter tilpasninger, remix eller transformationer af dit originale værk.',
    'licenseChooser.derivatives.yes.title': 'Ja, tillad afledte værker',
    'licenseChooser.derivatives.yes.description': 'Andre kan tilpasse, remixe eller transformere mit arbejde.',
    'licenseChooser.derivatives.no.title': 'Nej, tillad ikke afledte værker',
    'licenseChooser.derivatives.no.description': 'Mit arbejde skal gives videre uændret og i sin helhed.',
    'licenseChooser.attribution.title': 'Vil du kræve attribution?',
    'licenseChooser.attribution.description': 'Attribution betyder, at andre skal give dig kredit, når de bruger dit arbejde.',
    'licenseChooser.attribution.yes.title': 'Ja, kræver tilskrivning',
    'licenseChooser.attribution.yes.description': 'Andre skal give mig kredit, når de bruger mit arbejde.',
    'licenseChooser.attribution.no.title': 'Nej, placér i offentligt domæne (CC0)',
    'licenseChooser.attribution.no.description': 'Jeg giver afkald på alle ophavsrettigheder og beslægtede rettigheder til mit arbejde.',
    'licenseChooser.commercialUse.title': 'Vil du tillade kommerciel brug af dit arbejde?',
    'licenseChooser.commercialUse.description': 'Kommerciel brug betyder, at andre kan bruge dit arbejde til kommercielle formål.',
    'licenseChooser.commercialUse.yes.title': 'Ja, tillad kommerciel brug',
    'licenseChooser.commercialUse.yes.description': 'Andre kan bruge mit arbejde til kommercielle formål.',
    'licenseChooser.commercialUse.no.title': 'Nej, kun til ikke-kommerciel brug',
    'licenseChooser.commercialUse.no.description': 'Andre må kun bruge mit arbejde til ikke-kommercielle formål.',
    'licenseChooser.shareAlike.title': 'Ønsker du at kræve Share-Alike?',
    'licenseChooser.shareAlike.description': 'Vælg, om andre skal dele deres tilpasninger på samme vilkår.',
    'licenseChooser.shareAlike.yes.title': 'Det er nødvendigt at dele på samme måde (SA)',
    'licenseChooser.shareAlike.yes.description': 'Hvis andre remixer, transformerer eller bygger videre på dit arbejde, skal de distribuere deres bidrag under samme licens som originalen.',
    'licenseChooser.shareAlike.no.title': 'Share-Alike ikke påkrævet',
    'licenseChooser.shareAlike.no.description': 'Andre kan distribuere bearbejdninger under alle vilkår, også selvom de er mere restriktive end din oprindelige licens.',
    'licenseChooser.shareAlike.yes': 'Ja, kræver Share-Alike (SA)',
    'licenseChooser.shareAlike.no': 'Nej, kræver ikke Share-Alike',
    'licenseChooser.cc0Confirmation.title': 'Bekræft CC0-licens (offentligt domæne)',
    'licenseChooser.cc0Confirmation.description': 'CC0 giver afkald på al ophavsret og relaterede rettigheder til dit arbejde og placerer det effektivt i det offentlige domæne. Bekræft venligst din forståelse.',
    'licenseChooser.cc0Confirmation.important': 'Vigtig information',
    'licenseChooser.cc0Confirmation.details': 'Ved at vælge CC0 giver du afkald på al ophavsret og relaterede rettigheder til dit værk, i det omfang loven tillader det. Det betyder, at:',
    'licenseChooser.cc0Confirmation.point1': 'Alle kan bruge dit arbejde til ethvert formål, herunder kommerciel brug.',
    'licenseChooser.cc0Confirmation.point2': 'Der kræves ingen kildeangivelse (selvom det værdsættes).',
    'licenseChooser.cc0Confirmation.point3': 'Andre kan ændre dit arbejde og ikke dele disse ændringer',
    'licenseChooser.cc0Confirmation.point4': 'Denne beslutning er uigenkaldelig, når du publicerer',
    'licenseChooser.cc0Confirmation.waiver': 'Jeg forstår, at jeg giver afkald på al ophavsret og relaterede rettigheder til mit arbejde.',
    'licenseChooser.cc0Confirmation.understanding': 'Jeg forstår vilkårene og den juridiske effekt af CC0 på mit arbejde.',
    'licenses.learnMore': 'Få mere at vide',
    'licenses.legalText': 'Juridisk tekst',
    'licenses.chooser.back': 'Tilbage',
    'licenses.chooser.select': 'Vælg denne licens',
    'licenses.commercial.title': 'Oplysninger om kommerciel licens'
};