export default {
  'courses.courses': 'Cursos',
  'courses.overview': 'Visão geral dos cursos',
  'courses.public.title': 'Explore os cursos',
  'courses.public.heading': 'Explore os cursos',
  'courses.public.filters': 'Filtrar cursos',
  'courses.public.noResults': 'Nenhum curso encontrado',
  'courses.public.tryDifferentFilters': 'Experimente termos ou filtros de pesquisa diferentes',
  'courses.filter.search': 'Pesquise cursos...',
  'courses.filter.allTypes': 'Todos os tipos',
  'courses.filter.clearAll': 'Limpar tudo',
  'courses.type.course': 'Curso',
  'courses.type.workshop': 'Oficina',
  'courses.type.seminar': 'Seminário',
  'courses.type.course.lowercase': 'Curso',
  'courses.type.workshop.lowercase': 'Oficina',
  'courses.type.seminar.lowercase': 'Seminário',
  'course.create': 'Criar um novo curso',
  'course.reading.title': 'Título da tarefa de leitura',
  'course.question.add': 'Adicionar pergunta',
  'course.add.courseElement': 'Adicione um novo elemento da disciplina',
  'course.lessons.newMessage': 'Criar e organizar suas aulas para um ensino eficaz',
  'course.reading.new': 'Tarefa de Leitura',
  'course.reading.newMessage': 'Criar e organizar tarefas de leitura para seus alunos',
  'course.writing.new': 'Tarefa de escrita',
  'course.writing.newMessage': 'Configurar e distribuir rapidamente tarefas de escrita',
  'course.question.text': 'A sua pergunta vai aqui',
  'course.question.type': 'Por favor, selecione um tipo de pergunta',
  'course.question.delete': 'Remover pergunta',
  'course.type': 'Tipo de curso',
  'course.visibility': 'Selecione a opção de visibilidade',
  'course.title': 'Título',
  'course.description': 'Descrição',
  'course.cover': 'Capa',
  'course.start': 'O seu curso começa em',
  'course.ends': 'O seu curso termina em',
  'course.curriculum': 'Currículo do curso',
  'course.members': 'Alunos e professores',
  'course.assignments': 'Atribuições',
  'course.question.deleteWhole': 'Excluir toda a pergunta',
  'course.question.yes': 'Sim',
  'course.question.no': 'Não',
  'course.lesson.title': 'Título da lição',
  'course.lesson.add.universe': 'Adicionar História/Universo',
  'course.lesson.externalLinks': 'Ligações externas',
  'course.lesson.add.link': 'Adicionar link externo',
  'course.status': 'Estado',
  'course.active': 'Atividade',
  'course.active.message': 'Ativo',
  'course.inactive': 'Inativo',
  'course.module.edit': 'Editar o nome do módulo',
  'course.upload.resource': 'Carregue um recurso',
  'course.question.answer': 'Adicionar resposta',
  'course.question.open': 'Pergunta aberta',
  'course.question.close': 'Pergunta fechada',
  'course.question.multiple': 'Pergunta de escolha múltipla',
  'course.about': 'Sobre este curso',
  'course.lesson.new': 'Crie uma nova lição',
  'course.lesson.type': 'Tipo de aula',
  'course.lesson.inPerson': 'Pessoalmente',
  'course.lesson.preRecorded': 'Pré-gravado',
  'course.lesson.online': 'Em linha',
  'course.lesson.text': 'Apenas texto',
  'course.lesson.content': 'Conteúdo da aula',
  'course.lesson.description': 'Descrição pública',
  'course.add.module': 'Adicionar novo módulo',
  'course.add.story': 'Adicionar história',
  'course.remove.story': 'Remover história',
  'course.dateOfPublish': 'Data de publicação',
  'course.lesson.meetInPerson': 'Encontre-se pessoalmente',
  'course.curriculum.edit': 'Editar o currículo',
  'course.stories.own': 'As suas próprias histórias',
  'course.stories.organization': 'Histórias de organizações',
  'course.stories.public': 'Histórias públicas',
  'course.publish.at': 'Quero que este curso seja publicado em:',
  'course.edit.curriculum': 'Editar o currículo',
  'course.assignment': 'Atribuição',
  'course.lesson.removeLink': 'Remover a ligação',
  'course.user.remove': 'Remover utilizador',
  'course.user.invite': 'Convidar utilizador',
  'course.user.invited': 'Convidado',
  'course.edit.role': 'Editar função',
  'course.assignment.description': 'Descrição da tarefa',
  'course.internal': 'Interno',
  'course.free': 'Grátis',
  'course.sale': 'Venda',
  'course.announcements': 'Anúncios',
  'course.announcements.full': 'Anúncios de cursos',
  'course.announcements.create': 'Crie um anúncio',
  'course.join': 'Participe no curso',
  'course.joining': 'Junte-se a...',
  'course.join.success': 'Inscreveu-se com sucesso neste curso!',
  'course.join.error.payment': 'Este curso requer pagamento para participar.',
  'course.join.error.invite': 'Este curso requer um convite para participar.',
  'course.join.error.generic': 'Ocorreu um erro ao registar-se no curso. Por favor, tente novamente.',
  'course.firstLesson': 'Primeira lição',
  'course.upcomingLessons': 'Próximas aulas',
  'course.detail.title': '{courseName} | Curso',
  'lessons.visibility.public': 'Público',
  'lessons.visibility.private': 'Privado',
  'course.curriculum.empty': 'Ainda não há itens de currículo disponíveis.',
  'course.preview.message': 'Esta é uma antevisão do curso. Inscreva-se no curso para aceder a todos os conteúdos.',
  'course.modules.locked': '{count} mais {count, plural, one {módulo} other {módulos}} (bloqueado)',
  'course.details': 'Detalhes do curso',
  'course.tab.curriculum': 'Currículo',
  'course.tab.details': 'Detalhes do curso',
  'course.duration': 'Duração',
  'course.perpetual': 'Perpétuo',
  'course.language': 'Língua',
  'course.price': 'Preço',
  'course.learningObjectives': 'Objectivos de aprendizagem',
  'course.prerequisites': 'Pré-requisitos',
  'course.tags': 'Etiquetas',
  'course.stats.members': 'Membros',
  'course.stats.modules': 'Módulos',
  'course.stats.lessons': 'Lições',
  'course.assignments.comingSoon': 'A vista de tarefas está a chegar.',
  'course.progress.comingSoon': 'O acompanhamento do progresso está a chegar.',
  'course.type.free': 'Grátis',
  'course.type.paid': 'Pago',
  'course.type.invite': 'Apenas para convidados',
  'courses.invites.tile': 'Está convidado a participar em {count, plural, one {curso} other {cursos}}.',
  'courses.invites.noInvites': 'De momento, não tem quaisquer convites para cursos.',
  'courses.invites.invitedBy': 'Convidado por: ',
  'courses.invites.accept': 'Aceitar',
  'courses.invites.reject': 'Rejeitar',
  'course.join.heading': 'Inscreva-se neste curso',
  'course.oneTimePayment': 'Pagamento único para acesso total',
  'course.member': 'Está inscrito',
  'course.member.access': 'Tem acesso total a todos os materiais do curso.',
  'courses.members.editRole': 'Editar função',
  'courses.members.editRoleFor': 'Edite a função para:',
  'courses.add.member': 'Adicionar um novo membro',
  'course.member.options': 'Lista de membros do curso',
  'course.navigation.curriculum': 'Currículo',
  'course.navigation.members': 'Estudantes e professores',
  'course.navigation.assignments': 'Atribuições',
  'course.navigation.forums': 'Fóruns',
  'course.navigation.attendance': 'Presença',
  'course.members.teachers': 'Professores',
  'course.members.students': 'Estudantes',
  'course.members.preview.message': 'Participe neste curso para ver todos os alunos e interagir com a comunidade.',
  'course.member.role.owner': 'Proprietário',
  'course.member.role.teacher': 'Professor',
  'course.member.role.student': 'Estudante',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'contentSelector.noSelection': 'No item selected',
  'contentSelector.selectedItems': 'Selected items',
  'contentSelector.entireSite': 'Entire site',
  'contentSelector.myLibrary': 'My library',
  'contentSelector.tabsLabel': 'Search options',
  'contentSelector.title': 'Select Content',
  'course.startDate': 'Data de início',
  'course.endDate': 'Data final',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Pré-visualização do currículo',
  'course.curriculum.preview.message': 'Inscreva-se neste curso para aceder a todas as lições e tarefas de {count} .',
  'course.curriculum.locked': 'Bloqueado',
  'course.curriculum.module': 'Módulo',
  'course.curriculum.lesson': 'Lição',
  'course.curriculum.assignment': 'Atribuição',
  'course.curriculum.reading': 'Ler',
  'course.lesson.backToCurriculum': 'Voltar ao currículo',
  'course.lesson.nextLesson': 'Próxima lição',
  'course.lesson.documents': 'Documentos e recursos',
  'course.lesson.meetingLink': 'Ligação à reunião',
  'course.lesson.location': 'Localização',
  'course.lesson.virtualClassroom': 'Sala de aula virtual',
  'course.lesson.joinClassroom': 'Participe na sessão de sala de aula virtual',
  'course.lesson.enterClassroom': 'Entre na sala de aula',
  'courses.module.defaultTitle': 'Módulo {count, number}',
};
