export default {
    'feedback.home': 'Centro de ajuda',
    'feedback.bugs': 'Problemas',
    'feedback.bugs.desc': 'Encontrou um erro ou outra coisa que esteja errada ou fora de lugar. Diga-nos aqui!',
    'feedback.features': 'Ideias & Propostas',
    'feedback.features.desc': 'Tem ideias para novas funcionalidades ou como tornar o site melhor? Diga-nos!',
    'feedback.help': 'Ajuda & Tutoriais',
    'feedback.help.desc': 'Como é que _____? Venha aqui para encontrar as respostas.',
    'feedback.desc': 'Bem-vindo ao nosso centro de ajuda e resolução!',
    'feedback.open': 'Aberto',
    'feedback.closed': 'Fechado',
    'feedback.accepted': 'Aceite',
    'feedback.inprogress': 'Em progresso',
    'feedback.completed': 'Concluído',
    'feedback.fixed': 'Fixo',
    'feedback.new.bugs': 'Reportar novo problema',
    'feedback.new.features': 'Sugerir uma nova funcionalidade',
    'feedback.lang.nosupport': 'A sua língua atual não é suportada para o feedback, por favor escreva em inglês. Obrigado!',
    'feedback.new.thanks': 'Obrigado pelo aviso! Iremos analisá-lo em breve.',
    'feedback.comment.title': 'Comentário',
    'feedback.comment.desc': 'Envie-nos o seu feedback',
    'feedback.comment.legend': 'O seu feedback - informe-nos sobre qualquer coisa',
    'feedback.comment.success': 'Obrigado pelo seu feedback!',
    'feedback.comment.label': 'O seu comentário',
    'feedback.copyrightReport.title': 'Violação de direitos de autor',
    'feedback.copyrightReport.desc': 'Denunciar violação de direitos de autor',
    'feedback.report.noUser': 'Precisa de estar conectado para preencher um relatório.',
    'feedback.voting.totalVoters': 'Os utilizadores votaram: {voted, number}',
    'feedback.voting.upvote': 'Voto ascendente',
    'feedback.voting.downvote': 'Voto descendente',
    'feedback.voting.score': 'Pontuação final',
    'feedback.report.title': 'Reportar conteúdo',
    'feedback.report.typeSelect': 'Qual é o problema aqui?',
    'feedback.reportType.law': 'Violação da lei',
    'feedback.reportType.vulgar': 'Vulgar/obsceno',
    'feedback.reportType.copyright': 'Violação dos direitos de autor',
    'feedback.reportType.storyRating': 'Classificação de idade incorreta',
    'feedback.reportType.scam': 'Fraude',
    'feedback.report.submit': 'Denunciar',
    'feedback.report.submitting': 'A denunciar...',
    'feedback.report.violationDesc': 'Detalhes',
    'feedback.report.reportSaved': 'Obrigado pela denúncia! Vamos investigar e tomar medidas, se necessário.',
    'feedback.report.copyrightReportSaved': 'Obrigado pela denúncia! Iremos investigar e manter-nos em contacto.',
    'feedback.report.copyrightOwnershipDesc': 'Declaração de propriedade',
    'feedback.report.copyrightNotice': 'Por favor note que precisa de ser o legítimo proprietário da obra para utilizar este formulário. Se não for o proprietário, por favor informe o proprietário ou utilize a outra categoria para nos informar. Levamos as violações dos direitos de autor extremamente a sério e o mesmo se aplica à utilização imprópria e abusiva deste formulário.',
    'feedback.report.copyrightInternalProperty': 'Publiquei esta obra no Universo Literário',
    'feedback.reportType.spam': 'Spam ou phishing',
    'feedback.reportType.other': 'Outros',
    'feedback.report.copyrightType.propertySelectLabel': `Qual {type, select,
    universe {universo}
    story {história}
    other {história}
  } está a ser infringido?`
};