export default {
    'org.auditLog.title': 'Registo de auditoria',
    'org.settings.title': 'Definições da organização',
    'org.settings.name': 'Nome da organização',
    'org.settings.membersPrivate': 'NÃO exibir membros publicamente',
    'org.logo': 'Logótipo da organização',
    'org.logo.alt': '{organizationName} logo',
    'org.superAdmin': 'Super Administrador',
    'org.settings.language': 'Língua principal',
    'org.meta.desc': 'Organizações e grupos criativos no Universo Literário.',
    'org.luOrgs': 'Organizações do Universo Literário',
    'org.otherOrgs': 'Guilds e Organizações',
    'org.aboutTitle': 'Sobre {orgName}',
    'org.membersTitle': 'Membros da organização',
    'org.membersNone': 'Os membros não são públicos',
    'org.storiesTitle': 'Histórias de {orgName}',
    'org.universesTitle': 'Universos de {orgName}',
    'org.userDashboardTitle': 'As suas organizações',
    'org.settings.hideMembers.label': 'Ocultar membros do público',
    'org.visit': 'Ir para a página de {organization}',
    'org.authorOverride.legend': 'Anulação do autor',
    'org.authorOverride.desc': 'Mostra este texto em vez do nome da organização.',
    'org.authorOverride.label': 'Nome do autor',
    'org.membersAdd.title': 'Convidar membros para a organização',
    'org.flashnews.admin': 'Notícias recentes da administração',
    'org.settings.tabListAria': 'Definindo seções para organização',
    'org.forums.title': '{orgName} fóruns',
    'org.flashnews.internal': 'Notícias recentes internas',
    'org.flashnews.publicAll': 'Notícias recentes públicas para todas as propriedades',
    'org.flashnews.createTitle': `Criar um novo flash de notícias para {type, select,
    internal {a organização}
    allProperties {mostrar ao público em todas as propriedades}
    other {a organização}
  }`,
    'org.members.invited': 'Membros convidados',
    'org.members.list': 'Membros da organização',
    'org.invitesTileNotice': 'Foi convidado a {count, number}{count, plural, one {organização} other {organizações}}',
    'org.invitePage.title': 'Convites para organizações',
    'org.invitePage.invitedAt': 'Foi convidado no {invitedAt, date, short}.',
    'org.invitePage.ignoring': 'Atualmente está a ignorar este convite, o que significa que ainda está ativo, mas que não se incomoda com notificações.',
    'org.invitePage.expiresAt': 'Este convite expirará em {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Junte-se à organização',
    'org.invitePage.reject': 'Rejeitar convite',
    'org.invitePage.ignore': 'Ignorar por agora',
    'org.leaveOrg.title': 'Deixar a organização',
    'org.leaveOrg.confirm': 'Isto é uma ação destrutiva. Uma vez que se vá embora, perderá todo o acesso a esta organização. Tem a certeza de querer deixar a organização?',
    'org.confirmRemove.aria': 'Confirmar a remoção do utilizador',
    'org.confirmRemove.confirm': 'Tem a certeza que quer remover {username} de {organization}?',
    'org.confirmRemove.remove': 'Remover utilizador',
    'org.mainBlog': 'Blog principal',
    'org.teams': 'Equipas',
    'org.teams.total': 'Equipas totais: {totalTeams, number}',
    'org.teams.create': 'Crie uma nova equipa',
    'org.teams.settings': 'Configurações da equipa',
    'org.workshop.ownerUser': 'Não é um trabalho de guid',
    'org.workshop.caption': 'Propriedade da guild'
};