export default {
    'homepage.welcome': 'Bem-vindo a',
    'homepage.start': 'Comece a Sua viagem!',
    'homepage.iAm': 'Eu sou um',
    'homepage.iAm.aria': 'Selecione entre a exibição de características para leitores e escritores',
    'homepage.reader': 'LEITOR',
    'homepage.writer': 'ESCRITOR',
    'homepage.reader.title': 'Ler nunca foi tão interessante assim',
    'homepage.reader.readingTitle': 'Experiência única de leitura',
    'homepage.reader.readingDesc': 'Mergulhe mais profundamente no seu universo de ficção preferido no Universo Literário. As histórias no Universo Literário estão ligadas dentro do mesmo universo, dando-lhe acesso imediato à enciclopédia do universo a partir do leitor de histórias.',
    'homepage.reader.favoriteTitle': 'Descubra mais sobre as duas histórias e autores favoritos',
    'homepage.reader.favoriteDesc': 'A enciclopédia do universo e os blogs do autor são apenas algumas características que o ajudarão a descobrir tudo o que precisa de saber sobre as suas histórias favoritas, os seus cenários e os seus criadores!',
    'homepage.reader.communityTitle': 'Junte-se à comunidade',
    'homepage.reader.communityDesc': 'Conhecer pessoas de todo o mundo em fóruns dedicados ao universo e ao autor, blogs e outras funcionalidades da comunidade onde se reúnem fãs com ideias semelhantes. Tudo num só lugar.',
    'homepage.reader.readingFeatureTitle': 'Desfrute de uma experiência de leitura imersiva mas prática',
    'homepage.reader.readingFeatureDesc': 'A partir de histórias e de universos, tem o benefício de uma leitura sem esforço com acesso aos detalhes sem necessidade de alternar entre páginas.',
    'homepage.reader.readingExploreTitle': 'Explore toda a minúcia do universo',
    'homepage.reader.readingExploreDesc': 'A enciclopédia do universo permite-lhe aprender todos os detalhes sobre o universo e imergir-se totalmente nas histórias.',
    'homepage.reader.start': 'Iniciar Leitura',
    'homepage.writer.title': 'Mostre seu universo e partilhe suas histórias',
    'homepage.writer.writingTitle': 'Escrita & criação facilitada',
    'homepage.writer.writingDesc': 'Experimente a nova forma de escrever com o Workshop do Universo Literário. Crie todos os detalhes do seu universo numa enciclopédia para partilhar com os seus leitores e escreva histórias espantosas sobre essa base.',
    'homepage.writer.collaborationTitle': 'Criação colaborativa',
    'homepage.writer.profitDesc': 'O processo criativo envolve frequentemente múltiplas pessoas. Não se preocupe, nós tratamos de si! Pode facilmente adicionar leitores beta, co-autores e tradutores às suas histórias e universos.',
    'homepage.writer.communityTitle': 'Conecte-se com os seus leitores',
    'homepage.writer.communityDesc': 'Vá além da escrita e conecte-se com os seus leitores através de blogs, fóruns e outras características da comunidade ligadas aos seus universos ou a si como escritor.',
    'homepage.writer.workshopFeatureTitle': 'Um lugar para todas as suas necessidades criativas',
    'homepage.writer.workshopFeatureDesc': 'O nosso workshop em constante evolução é o lugar central para as suas necessidades criativas. A partir de uma simples ideia crie universos, histórias e tudo o mais que é necessário à sua volta.',
    'homepage.writer.monetizationFeatureTitle': 'Monetização',
    'homepage.writer.monetizationDesc': 'Acreditamos firmemente que as pessoas devem ser pagas pelo seu trabalho e estamos constantemente à procura de novas oportunidades de monetização para os escritores. O recurso de monetização permite que os escritores sejam apreciados pelo que fazem. Explore todas as diferentes opções que permitem que os seus fãs lhe mostrem a sua apreciação.',
    'homepage.writer.start': 'Organize o seu workshop!',
    'homepage.featureSelection': 'Veja este universo popular!',
    'about.title': 'Sobre o Universo Literário',
    'about.desc': 'História, segredos e humanos por detrás do Universo Literário.',
    'about.text.1': 'O Universo literário foi concebido tanto para escritores como para o leitor ávido. Os escritores podem utilizar o site para escrever obras originais através do botão workshop no menu do painel de controlo. Isto dar-lhe-á acesso ao editor principal e às funções enciclopédicas que se concentram principalmente na organização de todos os aspetos do seu universo de histórias pessoais numa única página. Os aspetos sociais permitem aos autores transmitir o seu trabalho e desenvolver um seguimento, assim como interagir mais diretamente se escolherem com os seus leitores.',
    'about.text.2': 'Os leitores podem utilizar o site principalmente para ler novas obras e seguir autores, mas também para ajudar a editar histórias pré-publicadas, se o autor o autorizar. Ser um leitor no Universo Literário é uma experiência de leitura totalmente nova, ter acesso a toda a informação de base na mesma página da história principal dá-lhe uma visão da mente do autor como nunca antes.',
    'about.text.3': 'O futuro do Universo Literário envolve a criação de um mercado para os autores venderem a sua obra e a adição de características comunitárias para melhorar a comunicação entre autor e leitor através de blogs e fóruns. As ferramentas do escritor serão acrescentadas ao longo do tempo, com mais de uma dúzia atualmente em desenvolvimento ou no quadro. O nosso objetivo final é melhorar as experiências dos escritores e leitores através de uma utilização mais inovadora do meio da Internet.',
    'about.text.4': 'Esperamos que se junte a nós enquanto exploramos o que o meio da Internet pode fazer pela escrita criativa!',
    'about.team': 'A equipa',
    'about.history': 'História',
    'about.company': 'A empresa',
    'about.companyCountry.czechia': 'República Checa',
    'about.companyCountry.japan': 'Japão',
    'about.companyCity.prague': 'Praga',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Diretor Executivo',
    'about.CTO': 'Diretor de Tecnologia',
    'about.jan': 'Jan is the founder, visionary and technological brain behind Literary Universe. As a writer of large literary universes, Jan had always found it difficult to write stories from a technical and readability point of view that would not compromise the reading experience. As such, Jan decided to pursue his studies in web development to create an application that would make it easy to write stories in large universes.',
    'about.history.text': 'In 2010 Jan started at Rochester Institute of Technology to learn more about web development in order to be able to build a creative writing site. This materialized in 2013 when the first proof of concept was presented at Imagine RIT. Jan continued his studies and in 2016 a new version of the app was created as a Master\'s Capstone Project. The project continued in fall 2016 and further developed into what you see today.',
    'copyrights.desc': 'The full text of Literary Universe Copyrights Agreement.',
    'privacy.desc': 'Full legal text of Privacy Policy of Literary Universe.',
    'guidelines.desc': 'Community Guidelines of Literary Universe.',
    'tos.desc': 'Full legal text of Terms of Service of Literary Universe.',
    'homepage.intro': 'Explore and create literally universes & great stories.',
    'homepage.explanation': 'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'gdpr.title': 'GDPR Compliance',
    'gdpr.desc': 'Literary Universe is compliant with the EU GDPR directives.',
    'gdpr.compliant': 'Literary Universe is GDPR Compliant',
    'gdpr.compliant.text': 'Literary Universe has implemented various updates and changes to its codebase in preparation for GDPR enforcement on May 25th 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'Changes in this version',
    'dmca.title': 'Digital Millennium Copyright Act (DMCA) Policy',
    'dmca.subtitle': 'Copyright Dispute Policy',
    'dmca.step1.title': 'Procedure for Reporting Copyright Infringements.',
    'dmca.step2.title': 'Once Proper Bona Fide Infringement Notification is Received by the Designated Agent.',
    'dmca.step3.title': 'Procedure to Supply a Counter-Notice to the Designated Agent.',
    'dmca.desc': 'We take copyright violations seriously.',
    'gdpr.access.title': 'Right of Access and Right of Data Portability',
    'gdpr.access.desc': 'In user settings you can export all your data. This data will be in standard JSON format.',
    'gdpr.forget.title': 'Right to be forgotten',
    'gdpr.forget.desc': 'Any account can be deleted via user settings. Some data might be preserved, especially if they have been subject to sale and/or disputes.',
    'gdpr.rectification.title': 'Right to Rectification',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'Right to restriction of processing',
    'gdpr.processing.desc': 'Literary Universe fully respects the browser settings, such as "Do not track" requests for reporting to our Matomo statistics server.',
    'gdpr.object.title': 'Right to Object',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'Reporting is split into two scenarios. 1. Internal property (infringement on site of property existing on site). 2. External property (infringement on site of property not existing on site).',
    'dmca.step1.desc2': 'Reporting internal property can be done via report button on the property. Reporting external property infringement can be done via feedback screen. In both cases you will be asked to provide personal details and additional details that will allow us to check your ownership.',
    'dmca.step1.desc3': 'Please note that making a false claims will result in your inability to file claims in the future.',
    'dmca.step2.desc1': 'Upon receiving your report we will verify your credentials and ownership claim. If everything is fine we will proceed to check claim. If we determine claim as true we will make the infringing property inaccessible until counter-notice determination or 14 days have passed after which it will be deleted.',
    'dmca.step3.desc1': 'Once a complaint has been received the owner of designated property will have 14 days to file a counter notice. Designated Agent will then proceed to investigate the dispute. Any decision by the Designated Agent at this stage will be final.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Attributions',
    'about.attributionsIntro': 'Literary Universe builds on top of many Open Source projects and free resources. Bellow you will find their listing.',
    'about.attributionsMatomo': 'Our analytics use self-hosted Matomo with IP2Location LITE data available from https://lite.ip2location.com.',
    'about.attributionIcons': 'The following icons are used through the site via styled-icons:',
    'team.name.pjakubec': 'Pavel Jakubec',
    'team.name.asebesta': 'Adam Šebesta',
    'about.developer': 'Developer',
    'about.seniorDeveloper': 'Senior Developer',
    'about.juniorDeveloper': 'Junior Developer',
    'about.leadDesigner': 'Lead designer',
    'about.leadUX': 'Lead UX designer',
    'about.intern': 'Intern',
    'about.advisor': 'Advisor',
    'about.headOfResearch': 'Head of Research',
    'about.CFO': 'Chief Financial Officer',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry is a designer with more than 15 years experience. He\'s been working in agency since 2010, his client such as PERTAMINA, VOA, and Ministry tourism of Indonesia. Experienced in Branding, layout and also UI/UX he feels challenged to design Literary Universe.',
    'about.pavel': 'Web3, Metaverse, AI, all that and anything new is what Pavel looks into and how it can be added to improve Literary Universe. A true multidisciplinary researcher Pavel holds insight into many areas and works on adding new interesting features to Literary Universe',
    'about.seba': 'Once a gamer, Adam is now studying to become a fully fledged developer.'
};