/**
 * @authors Jan Dvorak
 */
export default {
    siteName: 'ସାହିତ୍ୟିକ ବିଶ୍ବ',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe is an all-in-one creative and publishing platform for grand story universes.',
    'site.keywords': 'creative writing, scifi, sci-fi, fantasy, writing, publishing, story, stories, universe, web novel, webnovel',
    'site.logoAlt': 'Literary Universe logo',
    mobileMenu: 'Mobile menu',
    'common.signin': 'Login',
    'common.signup': 'Register',
    'common.signout': 'Logout',
    'common.dashboard': 'Dashboard',
    'common.discovery': 'Discovery',
    'common.library': 'Library',
    'common.library.own': 'Your Library',
    'common.workshop': 'Workshop',
    'common.pm': 'Messages',
    'common.settings': 'Settings',
    'common.options': 'ଵିକଳ୍ପ',
    'common.profile': 'Profile',
    'common.blog': 'Blog',
    'common.blogs': 'Blogs',
    'common.about': 'About us',
    'common.accessdenied': 'Access denied',
    'common.accessdenied.msg': 'You were not given permission to go here. If you should have access here, please contact the owner and tell them to double check the settings.',
    'common.loading': 'Loading...',
    'common.add': 'Add',
    'common.save': 'Save',
    'common.email': 'E-mail',
    'common.soon': 'Coming soon...',
    'common.search': 'Search',
    'common.search.do': 'Search',
    'common.searching': 'Searching...',
    'common.report': 'Report',
    'common.user': 'User',
    'common.users': 'Users',
    'common.showmore': 'Show more',
    'common.futurefeature.title': 'Future feature',
    'common.futurefeature.text': 'We apologize, but this feature is not available at this time. We are working hard to make it available as soon as possible.',
    'common.nothingfound': 'Nothing found',
    'common.explore': 'Explore',
    'common.by': 'ଦ୍ୱାରା {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'Scratchpad',
    'common.scratchpad.own': 'ଆପଣଙ୍କର ସ୍କ୍ରାଚପାଡ଼',
    'common.news': 'ଖବର',
    'common.encyclopedia': 'ଜ୍ଞାନସର୍ବଜ୍ଞାନ',
    'common.art': 'Art',
    'common.story': 'କାହାଣୀ',
    'common.stories': 'କାହାଣୀଗୁଡ଼ିକ',
    'common.universe': 'ବିଶ୍ବ',
    'common.universes': 'ବିଶ୍ଵଗୁଡ଼ିକ',
    'common.collaborator': 'ସହଯୋଗୀ',
    'common.collaborators': 'ସହଯୋଗୀଗୁଡ଼ିକ',
    'common.translator': 'ଅନୁବାଦକ',
    'common.translators': 'ଅନୁବାଦକ୍ରମି',
    'common.betareader': 'ବେଟା ପଠକ',
    'common.betareaders': 'ବେଟା ପଠକ୍ରମି',
    'common.post': 'ପୋଷ୍ଟ',
    'common.statistics': 'ପ୍ରାପ୍ତିଗୁଡ଼ିକ',
    'common.lang.select': 'ଭାଷା ବାଛନ୍ତୁ',
    'common.submit': 'ଦାଖଲ କରନ୍ତୁ',
    'common.close': 'ବନ୍ଦ କରନ୍ତୁ',
    'common.comment': 'ମତାମତ',
    'common.comments': 'ମତାମତଗୁଡ଼ିକ',
    404: 'ପୃଷ୍ଠା ପାଇଁ ପାଇନାହିଁନ୍ତି',
    'search.users': 'ବ୍ୟବହାରକାରୀଙ୍କୁ ଖୋଜନ୍ତୁ',
    'search.user': 'ବ୍ୟବହାରକାରୀଙ୍କୁ ଖୋଜନ୍ତୁ',
    'common.help': 'ସହାୟତା',
    'common.or': 'ଅଥବା',
    'common.account.create': 'ଏକ ଅକାଉଣ୍ଟ ତିଆରି କରନ୍ତୁ',
    'signup.username': 'ଇଉଜରନେମ୍',
    'signup.email': 'ଆପଣଙ୍କର ଇମେଲ୍',
    'signup.password.label': 'ଆପଣଙ୍କର ପାସ୍‌ୱାର୍ଡ୍',
    'signup.password.repeat': 'ଆପଣଙ୍କର ପାସ୍‌ୱାର୍ଡ୍ ପୁଣିଥରେ ଦିଅନ୍ତୁ',
    'common.password': 'ପାସ୍‌ୱାର୍ଡ୍',
    'signin.password.forgot': 'ପାସ୍‌ୱାର୍ଡ୍ ଭୁଲିଗଲା?',
    'dashboard.whatsnew': 'ନୂତନ କିମ୍ବା ନୂତନ କିଛି କିଛି',
    'dashboard.blog': 'ଆପଣଙ୍କର ବ୍ଲଗ',
    'common.footer.tagline': 'ଲେଖନ ଓ ପଢ଼ନ୍ତୁ କଠିନ ବିଶ୍ଵଗୁଡ଼ିକ ସୁବିଧାପୂର୍ଣ କରନ୍ତୁ',
    'common.footer.plans': 'Plans & Pricing',
    'common.legal.tos': 'Terms of Service',
    'common.legal.community': 'Community Guidelines',
    'common.legal.privacy': 'Privacy Policy',
    'common.legal.copyright': 'Copyright Agreement',
    'common.legal.versionDisplay': `{type, select,
    tos {ସେବା ଶର୍ତାବଳୀ}
    community {ଜାମିନ ମାର୍ଗଦର୍ଶିକା}
    privacy {ଗୋପନୀୟତା ନୀତି}
    copyright {କାପିରାଇଟ୍ ଚୁକ୍ତି}
    publishingAgreement {ପ୍ରକାଶନ ଚୁକ୍ତି}
    other {ଚୁକ୍ତି}
  } ସଂସ୍କରଣ {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'ଏହି ନିମନ୍ତେ ଏକ ନୂଆ ସଂସ୍କରଣ ({newVersion}) ପ୍ରଭାବିତ ହେବ {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} All rights reserved, all texts belong to their respective authors.',
    'premium.only.title': 'Not high enough membership rank',
    'premium.only.msg': 'We apologize, your membership rank is not high enough to access this feature.',
    'premium.only.join': 'We offer varieties of plans for everyone to get the most out of Literary Universe.',
    'premium.only.link': 'Check it out!',
    'universe.visit': 'Visit universe page',
    'common.fanmanager': 'Fan manager',
    'common.fanarts': 'Fan arts',
    'common.fanfiction': 'Fan fiction',
    'common.fansettings': 'Fan settings',
    'story.chapter': 'Chapter',
    'story.chapters': 'Chapters',
    'story.genre': 'Genre',
    'story.genres': 'Genres',
    'story.read': 'Read',
    'story.lastUpdate': 'Last updated on {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Finished on {date, date, medium}.',
    'story.hiatusAt': 'On hiatus from {date, date, medium}.',
    'story.cancelledAt': 'Cancelled on {date, date, medium}.',
    'story.comments.for': 'Comments for {story} {chapter}.',
    'story.cover.alt': 'Story cover image for {story}.',
    'story.note.fanfiction': 'NOTE: This story is a fan fiction on {universe} universe.',
    copyrights: 'Copyrights',
    'common.challenges': 'Challenges',
    // for beta only
    'beta.notice': 'Welcome to the Literary Universe BETA! We are excited to let you know that we are officially launching this Friday! We hope that you will join us and support us as we start a new chapter in our journey.',
    'beta.thanks': 'Thank you for your support!',
    'scratchpad.about': 'Your notes and ideas accessible anywhere on the site.',
    'common.feedback': 'Feedback',
    'common.createdOn': 'ସୃଷ୍ଟି ହୋଇଥିବା {date, date, long}',
    'common.createdOn.title': 'ସୃଷ୍ଟି ହୋଇଥିବା',
    // account types
    admin: 'Admin',
    'common.saved': 'Saved!',
    'common.saving': 'Saving...',
    'common.friends': 'Friends',
    'lang.orig': 'ସମ୍ପୂର୍ଣ୍ଣ ଭାଷା',
    'lang.orig.plus': 'ସମ୍ପୂର୍ଣ୍ଣ ଭାଷା - {language}',
    buy: 'କେଣିବା',
    confirm: 'ନିଶ୍ଚୟ କରନ୍ତୁ',
    cancel: 'ରଦ୍ଦ କରନ୍ତୁ',
    processing: 'ପ୍ରକ୍ରିୟା ଚଳିକାଅଛି...',
    'common.noData': 'କୌଣସି ତଥ୍ୟ ନାହିଁ',
    'error.title': 'ଏକ ତ୍ରୁଟି ଘଟିଛି। ଅସୁବିଧାର ଜୋରରେ ଦୁଃଖ ପାଇବା ଅତ୍ୟନ୍ତ କ୍ୟାମ୍ପରିଶନ।',
    'error.oops': 'Oops! Something went seriously wrong!',
    'error.apologies': 'We apologize for the inconvenience, we will do our best to fix this soon.',
    'error.400.text': 'Error 400: {errorMessage}',
    'common.offlineStatus': 'ଆପଣ ବର୍ତମାନରେ ଅଫଲାଇନ୍ ଅଛନ୍ତି।',
    male: 'ପୁରୁଷ',
    female: 'Female',
    'common.legal.effectiveAt': 'ପ୍ରଭାବଶାଳୀ ହେବ {date, date, medium}',
    select: 'Please select',
    'common.statusFailed': 'Failed to connect to the server.',
    'common.statusConnecting': 'Attempting to connect to the server... ({count, number})',
    'slug.checking': 'Checking...',
    'slug.failed': 'This address already exists.',
    'slug.success': 'This address is available!',
    'notVerified.msg': `ଆପଣଙ୍କର ଅକାଉଣ୍ଟ {option, select,
    email {ଇମେଲ}
    wallet {ଓଲେଟ}
    other {ଇମେଲ}
    } ଯାଞ୍ଚିତ ନାହିଁ |`,
    'notVerified.verify': `ଦୟାକରି ଆପଣଙ୍କର {option, select,
    email {ଇମେଲ}
    wallet {ଓଲେଟ}
    other {ଇମେଲ}
    }ଯାଞ୍ଚିତ କରନ୍ତୁ |`,
    unknown: 'unknown',
    'common.legal.guidelines': 'Community Guidelines',
    'errorLoading.title': 'Error during page load',
    'errorLoading.explained': 'An error has occurred while the page was loading. We apologize for the inconvenience. Please try accessing the page again. If the problem persists, please let us know.',
    'errorLoading.retry': 'Retry!',
    'errorLoading.takingLong': 'This is taking a long time...',
    'common.title': 'Title',
    'common.timelines': 'Timelines',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'General Data Protection Regulation',
    'editor.placeholder.link': 'Enter URL...',
    'editor.placeholder.connection': 'Search for encyclopedia entry...',
    'editor.saved.beta': 'New revision for Beta readers created!',
    'editor.saved.public': 'New version published!',
    goodbyeForever: 'We are sorry to see you go. Was it something we did? Please let us know if that is the case. Either way, we wish you the best in your future endeavors and hopefully we\'ll meet again! Live long and prosper!',
    'goodbyeForever.feedback': 'Let us know what we can do better',
    'common.edit': 'Edit',
    'common.publish': 'Publish',
    'common.publishAt': 'Publication date and time',
    'common.publishNow': 'Publish now',
    'common.publishLater': 'Publish later',
    'a11y.user.menu': 'User menu',
    'a11y.navigation': 'ଦିଗଚଳନ',
    'dashboard.profile': 'Your profile',
    'profile.website': 'My personal website',
    'story.notes.concept': 'Concept',
    'story.notes.settings': 'କଥା ସଜ୍ଜାକରଣ',
    'story.notes.theme': 'Theme',
    'story.notes.impact': 'କାମନ୍ୟତା ପ୍ରଭାବ',
    'story.notes.outcome': 'ଫଳାଫଳ',
    'story.notes.audience': 'ଲକ୍ଷ୍ୟ ଶ୍ରେଣୀ',
    'story.notes.pitch': 'ପିଚ୍',
    'story.notes.notes': 'ନୋଟ',
    'story.authorsNotes': 'ଲେଖକଙ୍କ ନୋଟ',
    'story.notes.audienceAgeGroup': 'Target audience age group',
    'story.notes.audienceSex': 'Target audience sex',
    'common.members': 'ସଭ୍ୟ',
    'common.language': 'ଭାଷା',
    next: 'ପରବର୍ତ୍ତୀ',
    previous: 'Previous',
    'common.legal.tos.short': 'ଶର୍ତାବଳୀ',
    'common.legal.privacy.short': 'ଗୋପନୀୟତା',
    'premium.increaseLimit': 'ଆପଣଙ୍କୁ ଆପଣଙ୍କର ମର୍ଯ୍ୟାଦା ବୃଦ୍ଧି କରିବା ପାଇଁ ଆପଗ୍ରେଡ୍ କରନ୍ତୁ।',
    'common.sharing': 'ଭାଗକ୍ରିୟା',
    'story.isbn': 'ISBN',
    'common.name': 'ନାମ',
    'common.remove': 'କାଢନ୍ତୁ',
    'common.time.milliseconds': 'ମିଲିସେକଣ୍ଟ',
    'common.time.seconds': 'ସେକେଣ୍ଡ',
    'common.time.minutes': 'ମିନିଟ',
    'common.time.hours': 'ଘଣ୍ଟା',
    'common.time.days': 'ଦିନ',
    'common.time.weeks': 'ସପ୍ତାହ',
    'common.time.months': 'ମାସ',
    'common.time.years': 'ବର୍ଷ',
    'common.monetization': 'ମୋନେଟାଇଜେସନ୍',
    'common.tab.monetizationOptions': 'ମୋନେଟାଇଜେସନ୍ ବିକଳ୍ପଗୁଡ଼ିକ',
    'common.pagination': 'ପେଜିନେସନ୍',
    'common.forum': 'ଫୋରମ୍',
    'common.2faCode': '2FA କୋଡ୍',
    'common.2faCodeIntro': 'ଦୟାକରି ଆପଣଙ୍କର ଏକ ସମୟ କୋଡ୍ ପ୍ରବିଷ୍ଟ କରନ୍ତୁ ଯାହା ଆପଣଙ୍କର ପ୍ରମାଣିକରଣ ଅନୁପ୍ରଯୁକ୍ତି ଅନୁସୃତ ହେଉଛି |',
    'common.2faCodeAria': '2FA କୋଡ୍ ପ୍ରବେଶ ଫର୍ମ',
    'common.aiContent.model.label': 'AI Model',
    'common.aiContent.model.tooltip': 'Select the AI model that was used to generate content',
    'common.other': 'Other',
    'common.aiContent.model.custom.label': 'Custom AI Model',
    'common.aiContent.model.custom.placeholder': 'Enter the name of the AI model',
    'common.select': 'Select...',
    'common.flashnews': 'ଫ୍ଲାଶନ୍ୟୁଜ୍',
    'common.defaultLanguage': 'ଡିଫାଲ୍ଟ ଭାଷା',
    'signin.web3.signMessage': 'ଦୟାକରି ନିଶ୍ଚିତ କରନ୍ତୁ ଆପଣ ଲିଟେରରୀ ଇୟୁନିଭର୍ସରେ ଆପଣଙ୍କର ଓଲେଟରେ ପ୍ରମାଣିକରଣ ପସନ୍ଦ କରନ୍ତୁ | କୋଡ୍: {code}',
    'common.web3.confirmationCode': 'ପ୍ରମାଣିକରଣ କୋଡ୍: {code}',
    'common.roadmap': 'ରୋଡମାପ୍',
    'common.luStatsIFrameOptOut': 'ସାହିତ୍ୟିକ ବିଶ୍ବ ପରିଚୟ ବାଦ ଦେବା',
    'common.image': 'Image',
    'common.home': 'ମୁଖପୃଷ୍ଠ',
    'common.administration': 'ପ୍ରଶାସନ',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'ଗୋଷ୍ଠୀଗୁଡ଼ିକ',
    'common.upload': 'ଆପଲୋଡ୍ କରନ୍ତୁ',
    'common.backToDashboard': 'ଡାଷବୋର୍ଡରେ ଫେରନ୍ତୁ',
    'common.accept': 'ସ୍ଵୀକାର କରନ୍ତୁ',
    'common.reject': 'ପ୍ରତିଷ୍ଠା କରନ୍ତୁ',
    'common.events': 'ଘଟଣାଗୁଡ଼ିକ',
    'common.event': 'Event',
    'common.all': 'ସବୁ',
    'common.social': 'Social',
    'common.discordCommunity': 'Discord Community',
    'common.account': 'Account',
    'common.notifications': 'ଵିଜ୍ଞପ୍ତି',
    'common.byDeclaration': 'By:',
    'common.done': 'Done',
    recommended: 'Recommended',
    'select.typeToCreate': 'Start typing to create an item',
    'select.noSearchResults': 'No results for “{search}”',
    'select.removeOption': 'Remove {option}',
    create: 'Create',
    'banner.support': 'Literary Universe is made possible thanks to the support of users like you. To help us remain independent and improve the platform, please consider subscribing to one of our plans.',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Don\'t have an account?',
    'common.haveAccountQuestion': 'Already have an account?',
    'common.socialLogin': 'Login with other services',
    'common.viewMore': 'View more',
    'common.overview': 'Overview',
    'common.loggingOut': 'ବାହାର ହୋଇଛି',
    'common.thankYou': 'ଧନ୍ୟବାଦ!',
    'common.seeYouAgain': 'ପୁଣି ଦେଖିବାକୁ ଆଶା କରୁଛି!',
    'email.hello': 'ନମସ୍କାର {username},',
    'common.back': 'ପିଠିବରକୁ',
    'console.stop': 'ଥମ୍ବ!',
    'console.explain': 'This is a browser feature intended for developers. If someone told you to copy-paste something here to enable a Literary Universe feature or "hack" someone\'s account, it is a scam and will give them access to your Literary Universe account.',
    'common.coping': 'ଅନୁଲେଖନ କରୁଛି...',
    'common.actions': 'କାର୍ଯ୍ୟଗୁଡ଼ିକ',
    'common.popular': 'ପ୍ରସିଦ୍ଧ',
    'common.newest': 'ନବିନତମ',
    'common.oldest': 'ପୁରୁଣା',
    'common.noSelection': 'No selection',
    'common.content': 'Content',
    'common.theWayOfTheAuthor': 'The Way of the Author',
    'common.password.hide': 'Hide Password',
    'common.password.show': 'Show Password',
    'common.forums': 'Forums',
    'common.restriction.goodConduct': 'Due to good conduct violation we have restricted your use of this feature.',
    'common.continue': 'Continue',
    'common.authorName': 'Author Name',
    'error.invalidFileType': 'Please select a valid image file (JPEG, PNG, GIF, WebP)',
    'error.fileTooLarge': 'Image must be less than {mbSize, number}MB',
    'error.fabricInitFailed': 'Failed to initialize the image editor',
    // File upload strings
    'upload.files': 'Uploaded Files',
    'upload.dropHere': 'Drop your files here...',
    'upload.dragOrClick': 'Drag and drop files here, or click to select files',
    'upload.maxSize': 'Maximum file size: {size}',
    'upload.error.failed': 'File upload failed. Please try again.',
    'upload.error.tooManyFiles': 'You can upload a maximum of {max} files.',
    'upload.error.removeFile': 'Failed to remove file. Please try again.',
    'actions.delete': 'Delete',
    'common.aiContent.indicator': 'AI-Generated Content',
    'common.aiContent.tooltip': 'This content was created with AI assistance',
    'common.aiContent.model': 'AI Model: {model}',
    'common.aiContent.custom': 'Custom AI model'
};