export default {
    'org.auditLog.title': 'ଅଡିଟ୍ ଲଗ୍',
    'org.settings.title': 'ସଂଗଠନ ସେଟିଂସମୂହ',
    'org.settings.name': 'ସଂଗଠନ ନାମ',
    'org.settings.membersPrivate': 'ସାର୍ବଜନିକରେ ସଭ୍ୟଙ୍କ ପ୍ରଦର୍ଶନ ନକରନ୍ତୁ',
    'org.logo': 'ସଂଗଠନ ଲୋଗୋ',
    'org.logo.alt': '{organizationName} logo',
    'org.superAdmin': 'ସୁପର୍ ଅଡିମିନ୍',
    'org.settings.language': 'ପ୍ରାଥମିକ ଭାଷା',
    'org.meta.desc': 'ଲିଟେରରୀ ଇୟୁନିଭର୍ସ୍ ସଂଗଠନସମୂହ ଏବଂ ସୃଜନାତ୍ମକ ଗୋଷ୍ଠୀମାନଙ୍କରେ',
    'org.luOrgs': 'ଲିଟେରରୀ ଇୟୁନିଭର୍ସ୍ ସଂଗଠନସମୂହ',
    'org.otherOrgs': 'Organizations',
    'org.aboutTitle': 'ବିଷୟରେ {orgName}',
    'org.membersTitle': 'ସଂଗଠନ ସଦସ୍ୟଙ୍କ',
    'org.membersNone': 'ସଦସ୍ୟଙ୍କ ପ୍ରକାଶନ ନେଇ',
    'org.storiesTitle': '{orgName}ରୁ ଗଳ୍ପ',
    'org.universesTitle': '{orgName}ରୁ ବିଶ୍ୱ',
    'org.userDashboardTitle': 'ଆପଣଙ୍କର ସଂଗଠନଗୁଡିକ',
    'org.settings.hideMembers.label': 'ସାର୍ବଜନିକରୁ ସଦସ୍ୟଙ୍କ ଲୁଚାନ୍ତି କର',
    'org.visit': '{organization} ପୃଷ୍ଠାରେ ଯାଆନ୍ତୁ',
    'org.authorOverride.legend': 'ଲେଖକ ଓଭରାଇଡ',
    'org.authorOverride.desc': 'ଏହି ପ୍ରସଙ୍ଗଟି ସଂଗଠନଙ୍କ ନାମରେ ପ୍ରଦର୍ଶିତ ହେବ।',
    'org.authorOverride.label': 'ଲେଖକଙ୍କ ନାମ',
    'org.membersAdd.title': 'ସଂଗଠନରେ ସଦସ୍ୟଙ୍କୁ ଆମନ୍ତ୍ରିତ କରନ୍ତୁ',
    'org.flashnews.admin': 'ଫ୍ଲାଶନ୍ୟୁଜ୍ ପ୍ରଶାସନ',
    'org.settings.tabListAria': 'ସଂଗଠନ ପାଇଁ ବିଭାଗ ସେଟିଂସ୍',
    'org.forums.title': '{orgName} ଫୋରମ୍‌ଗୁଡିକ',
    'org.flashnews.internal': 'ଆନ୍ତରିକ ଖବର ଫ୍ଲାଶ୍',
    'org.flashnews.publicAll': 'ସର୍ବସାଧାରଣ ପ୍ରକାଶନ ଫ୍ଲାଶ୍‌ଗୁଡିକ ସମସ୍ତ ମଲିକାଙ୍କ ପାଇଁ',
    'org.flashnews.createTitle': `ନୂତନ ଏକ ନୂଆକାର ଖବର ଫ୍ଲାଶ୍ ସର୍ବସାଧାରଣ ପ୍ରକାଶନ ପାଇଁ {type, select,
    internal {ସଂଗଠନ}
    allProperties {ଉପରେ ସର୍ବସାଧାରଣ ପ୍ରକାଶନ ପାଇଁ}
    other {ସଂଗଠନ}
  }ଉପରେ ପ୍ରଦର୍ଶିତ ହେବ`,
    'org.members.invited': 'Invited members',
    'org.members.list': 'ସଂଗଠନ ସଦସ୍ୟଙ୍କ',
    'org.invitesTileNotice': 'You have been invited to {count, number} {count, plural, one {organization} other {organizations}}',
    'org.invitePage.title': 'Invitations to organizations',
    'org.invitePage.invitedAt': 'You have been invited on {invitedAt, date, short}.',
    'org.invitePage.ignoring': 'You are currently ignoring this invitation, which means that it is still active, but doesn\'t bothers with notifications.',
    'org.invitePage.expiresAt': 'This invitation will expire at {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Join organization',
    'org.invitePage.reject': 'Reject invitation',
    'org.invitePage.ignore': 'Ignore for now',
    'org.leaveOrg.title': 'Leave organization',
    'org.leaveOrg.confirm': 'This is a destructive action. Once you leave you will loose all access to this organization. Are you sure you want to leave the organization?',
    'org.confirmRemove.aria': 'Confirm user removal',
    'org.confirmRemove.confirm': 'Are you sure that you want to remove {username} from {organization}?',
    'org.confirmRemove.remove': 'Remove user',
    'org.mainBlog': 'Main blog',
    'org.teams': 'Teams',
    'org.teams.total': 'Total teams: {totalTeams, number}',
    'org.teams.create': 'Create a new team',
    'org.teams.settings': 'Team settings',
    'org.workshop.ownerUser': 'କିମ୍ବା ଗୁଇଲ୍ଡ କାର୍ଯ୍ୟ ନୁହେଁ',
    'org.workshop.caption': 'ଗୁଇଲ୍ଡ ମାଲିକା',
    'org.workshop.title': 'ସଂଗଠନ କାର୍ଯ୍ୟଶାଳା',
    'org.title': 'ସଂଗଠନ',
    'org.hall.title': '{orgName} members hall',
    'org.member.leave': 'Leave organization',
    'org.member.leaveModalTitle': 'Leaving organization confirmation',
    'org.member.leaveModalHeading': 'Are you sure you want to leave {orgName}',
    'org.member.leaveModalExplain': 'Once you leave the organization you will loose access to all of the organization\'s associated resources and works. This action can\'t be undone.',
    // Role management strings
    'org.member.manageRoles': 'Manage Roles',
    'org.roles.error': 'Error: {error}',
    'org.roles.manageFor': 'Managing roles for {name}',
    'org.roles.selectRole': 'Select role',
    'org.roles.noRole': 'No role (permissions only)',
    'org.roles.admin': 'Admin',
    'org.roles.member': 'Member',
    'org.roles.author': 'Author',
    'org.roles.workshop': 'Workshop',
    'org.roles.teacher': 'Teacher',
    'org.permissions.title': 'Permissions',
    'org.permissions.includedInRole': '(included in role)',
    // Permission names
    'org.permissions.members.add': 'Add members',
    'org.permissions.members.remove': 'Remove members',
    'org.permissions.members.view': 'View members',
    'org.permissions.settings': 'Manage settings',
    'org.permissions.auditLog': 'View audit log',
    'org.permissions.flashnews': 'Manage flash news',
    'org.permissions.workshop.view': 'View workshop',
    'org.permissions.workshop.create': 'Create workshop items',
    'org.permissions.workshop.transfer': 'Transfer ownership',
    'org.permissions.workshop.viewAll': 'View all workshop items',
    'org.permissions.forum.manager': 'Manage forums',
    'org.permissions.blog.manage': 'Manage blog',
    'org.permissions.blog.post': 'Create blog posts'
};