/**
 * @authors Jan Dvorak
 */
export default {
    siteName: 'ជំនាញអត្តន័យសង្គម',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe is an all-in-one creative writing and publishing platform for grand story universes.',
    'site.keywords': 'ការ​សរសេរ​ប្រចាំ​ថ្ងៃ, សាកលវិទ្យាស្ថាន​ព្រៃ​ស៊ីហ្វី, សាកលវិទ្យាស្ថាន​ស្តាប់រឿងអន្តរជាតិ, រឿងអន្តរជាតិ, ហ្វេន្ទីហ្វី, សរសេរ, ប្រជាជន, ជំនុំ, ជំនុំរឿង, ជំនុំរឿងអន្តរជាតិ, ជំនុំវេបសាយ, ជំនុំវេបសាយបច្ចុប្បន្ន, ជំនុំវេបសាយបច្ចុប្បន្នអន្តរជាតិ',
    'site.logoAlt': 'រូបសញ្ញាសិប្បកម្មបណ្ដាញសង្គម',
    'site.titleTemplate': '{title} | {siteName}',
    mobileMenu: 'ម៉ូលុយសំណុំទូរស័ព្ទ',
    'common.signin': 'ចូលប្រើប្រាស់',
    'common.signup': 'ចុះឈ្មោះ',
    'common.signout': 'ចាកចេញ',
    'common.dashboard': 'ផ្ទាំងគ្រប់គ្រង',
    'common.discovery': 'រកមើល',
    'common.library': 'បណ្តាញសម្បត្តិ',
    'common.library.own': 'បណ្តាញសម្បត្តិរបស់អ្នក',
    'common.workshop': 'សម្រង់ការងារ',
    'common.pm': 'សារ',
    'common.settings': 'ការកំណត់',
    'common.options': 'ជម្រើស',
    'common.profile': 'ប្រវត្តិរូប',
    'common.blog': 'ប្លុក',
    'common.blogs': 'ប្លុក',
    'common.about': 'អំពី​យើង',
    'common.accessdenied': 'បាន​បដិសេធការ​ចូលទៅ',
    'common.accessdenied.msg': 'អ្នក​មិន​បាន​បញ្ជាក់​ការ​ចូល​ទៅ​ទីនេះ​ទេ។ ប្រសិន​បើ​អ្នក​គួរ​តែ​មាន​សិទ្ធិ​ក្នុង​ការ​ចូល​ទៅ​ទីនេះ​សូម​ទាក់ទង​មក​វិញ​នូវ​ម្ចាស់​និង​បញ្ជាក់​ថា​អ្នក​បាន​កំណត់​ការ​កំណត់​ត្រាំង​របស់​វាឡើង។',
    'common.loading': 'កំពុង​ផ្ទុក...',
    'common.add': 'បន្ថែម',
    'common.save': 'រក្សាទុក',
    'common.email': 'អ៊ីមែល',
    'common.anonymous': 'Anonymous',
    'common.soon': 'មកដល់ឆាប់រហ័ស...',
    'common.search': 'ស្វែងរក',
    'common.search.do': 'ស្វែងរក',
    'common.searching': 'កំពុងស្វែងរក...',
    'common.report': 'របាយការណ៍',
    'common.user': 'អ្នក',
    'common.users': 'អ្នកប្រើប្រាស់',
    'common.showmore': 'បង្ហាញច្រើនទៀត',
    'common.futurefeature.title': 'លក្ខណៈសម្បត្តិក្នុងអនុវត្ត',
    'common.futurefeature.text': 'We apologize, but this feature is not available at this time. We are working hard to make it available as soon as possible.',
    'common.nothingfound': 'មិនបានរកឃើញអ្វីទាំងអស់',
    'common.explore': 'រកមើល',
    'common.by': 'ដោយ {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'ក្រុមចម្លងសម្លេង',
    'common.scratchpad.own': 'ក្រុមចម្លងរបស់អ្នក',
    'common.news': 'ព័ត៌មាន',
    'common.encyclopedia': 'អត្ថបទបណ្ណ័ប្រភេទសម្លេង',
    'common.art': 'សិល្បៈ',
    'common.story': 'រឿងនិទាន',
    'common.stories': 'រឿងនិទាន',
    'common.universe': 'ពិភពលោក',
    'common.universes': 'ពិភពលោក',
    'common.unpublished': 'Unpublished',
    'common.collaborator': 'អ្នកសម្រង់',
    'common.collaborators': 'អ្នកសម្រង់',
    'common.translator': 'អ្នកបកប្រែ',
    'common.translators': 'អ្នកបកប្រែ',
    'common.betareader': 'អ្នកអានសំណួរសម្រាប់អតិថិជនសម្រាប់ការបង្ហាញសំណួរ',
    'common.betareaders': 'អ្នកអានសំណួរសម្រាប់អតិថិជនសម្រាប់ការបង្ហាញសំណួរ',
    'common.post': 'ប្រកាស',
    'common.statistics': 'ស្ថិតិស្ថាប័ន',
    'common.lang.select': 'ជ្រើសរើសភាសា',
    'common.submit': 'ដាក់ស្នើ',
    'common.close': 'បិទ',
    'common.comment': 'មតិ',
    'common.comments': 'មតិ',
    404: 'រកមិនឃើញទំព័រ',
    'search.users': 'ស្វែងរកអ្នកប្រើប្រាស់',
    'search.user': 'ស្វែងរកអ្នកប្រើប្រាស់',
    'common.help': 'ជំនួយ',
    'common.or': 'ឬ',
    'common.account.create': 'បង្កើតគណនី',
    'signup.username': 'ឈ្មោះអ្នកប្រើប្រាស់',
    'signup.email': 'អ៊ីម៉ែលរបស់អ្នក',
    'signup.password.label': 'ពាក្យសម្ងាត់របស់អ្នក',
    'signup.password.repeat': 'បញ្ជាក់ពាក្យសម្ងាត់របស់អ្នកឡើងវិញ',
    'common.password': 'ពាក្យសម្ងាត់',
    'signin.password.forgot': 'ភ្លេចពាក្យសម្ងាត់?',
    'dashboard.whatsnew': 'អ្វីដែលថ្មី',
    'dashboard.blog': 'ប្លុករបស់អ្នក',
    'common.footer.tagline': 'ការ​សរសេរ​និង​អាន​ពី​ពិភព​របស់​ជីវិត​ដោយ​ស្រស់។',
    'common.footer.plans': 'ផែនទី & តម្លៃ',
    'common.legal.tos': 'លោកសំណើសារពេទ្យ',
    'common.legal.community': 'របាយការណ៍​សង្គម​សហគ្រាសជំនួយ',
    'common.legal.privacy': 'គោលការណ៍​ភាពឯកជន',
    'common.legal.copyright': 'កិនស្តេចអាក្រក់',
    'common.legal.cookies': 'About cookies',
    'cookies.desc': 'This website uses cookies to ensure you get the best experience on our website.',
    'common.legal.versionDisplay': `{type, select,
    tos {Terms of Service}
    community {Community Guidelines}
    privacy {Privacy Policy}
    copyright {Copyright Agreement}
    publishingAgreement {Publishing Agreement}
    cookies {About Cookies}
    other {Agreement}
  } Version {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'នៅក្នុងការនេះ មានកំណែថ្មី ({newVersion}) នឹងមានសម្រាប់ប្រើប្រាស់តាមរយៈ {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} រក្សាសិទ្ធិ​គ្រប់គ្រង, អត្ថបទ​ទាំងអស់​គឺ​ជា​ក្រុមហ៊ុន​របស់​អ្នក​និពន្ធន័យ។',
    'premium.only.title': 'មិនខ្ពស់បំពេញការចុះបញ្ជីសមាជិក',
    'premium.only.msg': 'សូមសង្ខេប, ការចុះបញ្ជីសមាជិករបស់អ្នកមិនខ្ពស់បំពេញការចូលដំណើរការនេះទេ។',
    'premium.only.join': 'យើងផ្តល់ជូនអ្វីដែលប្រសើរឡើងសម្រាប់អ្នកដើម្បីទទួលបានច្បាស់លាស់ជាមួយជីវិតអាន។',
    'premium.only.link': 'ពិនិត្យមើលវា!',
    'universe.visit': 'ទស្សនាទំព័រជីវិត',
    'common.fanmanager': 'អ្នកគ្រប់គ្រងអ្នកចូលរួម',
    'common.fanarts': 'សិល្បៈអ្នកចូលរួម',
    'common.fanfiction': 'រឿងអន្តរជាតិអ្នកចូលរួម',
    'common.fansettings': 'ការកំណត់អ្នកចូលរួម',
    'story.chapter': 'ជើងសារ',
    'story.chapters': 'ជើងសារ',
    'story.chapter.withStory': '{story}: {chapter}',
    'story.includeUniverse': 'Include universe in title',
    'story.genre': 'ប្រភេទ',
    'story.genres': 'ប្រភេទ',
    'story.read': 'អាន',
    'story.lastUpdate': 'កាលបរិច្ឆេទចុងក្រោយនៅលើ {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'បញ្ចប់នៅលើ {date, date, medium}.',
    'story.hiatusAt': 'On hiatus from {date, date, medium}.',
    'story.cancelledAt': 'Cancelled on {date, date, medium}.',
    'story.comments.for': 'មតិយោបល់សម្រាប់ {story} {chapter}.',
    'story.cover.alt': 'រូបភាពត្រូវប្រើប្រាស់ស្ថាបនាំពី {story}.',
    'story.note.fanfiction': 'ចំណាត់ថ្នាក់កិរិយាសព្វរក្សាអ្នកសរសេរនេះគឺជា​ការសរសេរអំពី​ជីវិត {universe}.',
    copyrights: 'ការការពារសិទ្ធិ',
    'common.challenges': 'ការបែកសំណួរ',
    // for beta only
    'beta.notice': 'Welcome to the Literary Universe BETA! We are excited to let you know that we are officially launching this Friday! We hope that you will join us and support us as we start a new chapter in our journey.',
    'beta.thanks': 'Thank you for your support!',
    'scratchpad.about': 'កំណត់ត្រាណូអេសអេ។',
    'common.feedback': 'មតិយោបល់',
    'common.createdOn': 'បានបង្កើតនៅលើ {date, date, long}',
    'common.createdOn.title': 'បានបង្កើតនៅលើ',
    // account types
    admin: 'អ្នកគ្រប់គ្រង',
    'common.saved': 'បានរក្សាទុក!',
    'common.saving': 'កំពុងរក្សាទុក...',
    'common.friends': 'មិត្តភ័ក្ដិកូនរបស់អ្នក',
    'lang.orig': 'ភាសាដើម',
    'lang.orig.plus': 'ភាសាដើម - {language}',
    buy: 'ទិញ',
    confirm: 'បញ្ជាក់',
    cancel: 'បោះបង់',
    processing: 'កំពុងដំណើរការ...',
    'common.noData': 'គ្មានទិន្នន័យ',
    'error.title': 'កូនរបស់យើងមានបញ្ហាបាន។ យើងសូមសោកស្តាយចំពោះការពិតប្រាកដមែន។',
    'error.oops': 'Oops! Something went seriously wrong!',
    'error.apologies': 'We apologize for the inconvenience, we will do our best to fix this soon.',
    'error.400.text': 'Error 400: {errorMessage}',
    'common.offlineStatus': 'អ្នកកំពុងក្រោយបណ្តោះអាសន្ន។',
    male: 'ប្រុស',
    female: 'ស្រី',
    'common.legal.effectiveAt': 'មានសុពលភាពចាប់ផ្តើមពី {date, date, medium}',
    select: 'Please select',
    'common.statusFailed': 'Failed to connect to the server.',
    'common.statusConnecting': 'Attempting to connect to the server... ({count, number})',
    'common.swUpdate.ready.title': 'Update ready',
    'common.swUpdate.ready.description': 'A new version is ready. You can apply it now.',
    'common.swUpdate.ready.writerDescription': 'A new version is ready. Apply it when you finish your current writing edits.',
    'common.swUpdate.apply': 'Update now',
    'slug.checking': 'Checking...',
    'slug.failed': 'This address already exists.',
    'slug.success': 'This address is available!',
    'notVerified.msg': `គណនីរបស់អ្នក {option, select,
    email {អ៊ីមែល}
    wallet {សាច់ប្រាក់}
    other {អ៊ីមែល}
    } មិនបានបញ្ជាក់ទេ។`,
    'notVerified.verify': `សូមបញ្ជាក់អ៊ីមែល {option, select,
    email {សាច់ប្រាក់}
    wallet {អ៊ីមែល}
    other {អ៊ីមែល}
    }។`,
    unknown: 'unknown',
    'common.legal.guidelines': 'របាយការណ៍​សង្គម​សហគ្រាសជំនួយ',
    'errorLoading.title': 'Error during page load',
    'errorLoading.explained': 'An error has occurred while the page was loading. We apologize for the inconvenience. Please try accessing the page again. If the problem persists, please let us know.',
    'errorLoading.retry': 'Retry!',
    'errorLoading.takingLong': 'This is taking a long time...',
    'common.title': 'Title',
    'common.timelines': 'Timelines',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'General Data Protection Regulation',
    'editor.placeholder.link': 'Enter URL...',
    'editor.placeholder.connection': 'Search for encyclopedia entry...',
    'editor.saved.beta': 'New revision for Beta readers created!',
    'editor.saved.public': 'New version published!',
    goodbyeForever: 'We are sorry to see you go. Was it something we did? Please let us know if that is the case. Either way, we wish you the best in your future endeavors and hopefully we\'ll meet again! Live long and prosper!',
    'goodbyeForever.feedback': 'Let us know what we can do better',
    'common.edit': 'Edit',
    'common.publish': 'Publish',
    'common.publishAt': 'Publication date and time',
    'common.publishNow': 'Publish now',
    'common.publishLater': 'Publish later',
    'a11y.user.menu': 'User menu',
    'a11y.navigation': 'ការរុករក',
    'dashboard.profile': 'Your profile',
    'profile.website': 'My personal website',
    'story.notes.concept': 'Concept',
    'story.notes.settings': 'Story setting',
    'story.notes.theme': 'ប្រធានបទ',
    'story.notes.impact': 'គុណភាពចង់បាន',
    'story.notes.outcome': 'លទ្ធផល',
    'story.notes.audience': 'អត្តសញ្ញាណកម្មគោលដៅ',
    'story.notes.pitch': 'ការប្រកាស',
    'story.notes.notes': 'កំណត់ត្រា',
    'story.authorsNotes': 'កំណត់ចំណាំរបស់អ្នកនិពន្ធនាការ',
    'story.notes.audienceAgeGroup': 'Target audience age group',
    'story.notes.audienceSex': 'Target audience sex',
    'common.members': 'សមាជិក',
    'common.language': 'ភាសា',
    next: 'បន្ទាប់',
    previous: 'មុន​បញ្ចប់',
    'common.legal.tos.short': 'លោកអ្នកប្រើប្រាស់',
    'common.legal.privacy.short': 'ភាសាសម្រាប់ឯកជនឯកទេសរបស់អ្នក',
    'premium.increaseLimit': 'សូមធ្វើការធ្វើឱ្យបានលើសពីទឹកប្រាក់ដើម្បីបន្ថែមការប្រើប្រាស់របស់អ្នក',
    'common.sharing': 'ចែករំលែក',
    'story.isbn': 'ISBN',
    'common.name': 'ឈ្មោះ',
    'common.remove': 'យកចេញ',
    'common.time.milliseconds': 'មីលីវិនាទី',
    'common.time.seconds': 'វិនាទី',
    'common.time.minutes': 'នាទី',
    'common.time.hours': 'ម៉ោង',
    'common.time.days': 'ថ្ងៃ',
    'common.time.weeks': 'សប្តាហ៍',
    'common.time.months': 'ខែ',
    'common.time.years': 'ឆ្នាំ',
    'common.monetization': 'ការប្រើប្រាស់ជាប្រាក់',
    'common.tab.monetizationOptions': 'ជម្រើសការប្រើប្រាស់ជាប្រាក់',
    'common.pagination': 'ការចែកចាយទំព័រ',
    'common.forum': 'វេទិកាពិភាក្សា',
    'common.2faCode': 'លេខកូដ 2FA',
    'common.2faCodeIntro': 'សូមបញ្ចូលកូដមួយដែលបានបង្កើតដោយកម្មវិធីបញ្ជាក់ពីកូដមួយក្នុងរបៀបបញ្ជាក់ទៀតរបស់អ្នក។',
    'common.2faCodeAria': 'បែបកូដ 2FA',
    'common.aiContent.model.label': 'AI Model',
    'common.aiContent.model.tooltip': 'Select the AI model that was used to generate content',
    'common.other': 'Other',
    'common.aiContent.model.custom.label': 'Custom AI Model',
    'common.aiContent.model.custom.placeholder': 'Enter the name of the AI model',
    'common.select': 'Select...',
    'common.flashnews': 'ព័ត៌មានថ្មីៗ',
    'common.defaultLanguage': 'ភាសាលំនាំដើម',
    'signin.web3.signMessage': 'សូមបញ្ជាក់ថាអ្នកចង់ចូលទៅកាន់សកម្មវិធី Literary Universe ដោយប្រើវិធីការបញ្ជាក់ជាសាច់ប្រាក់របស់អ្នក។ លេខកូដ: {code}',
    'common.web3.confirmationCode': 'លេខកូដបញ្ជាក់: {code}',
    'common.roadmap': 'ផែនការរបស់ផ្លូវទីក្រុង',
    'common.luStatsIFrameOptOut': 'បដិសេធអត្ថបទសិក្សាពិតប្រាកដ',
    'common.image': 'រូបភាព',
    'common.home': 'ទំព័រដើម',
    'common.administration': 'ការគ្រប់គ្រង',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'ក្រុម',
    'common.upload': 'បញ្ចូល',
    'common.backToDashboard': 'ត្រឡប់ទៅផ្ទាំងគ្រប់គ្រង',
    'common.accept': 'ទទួលយក',
    'common.reject': 'បដិសេធ',
    'common.events': 'ព្រឹត្តិការណ៍',
    'common.event': 'ព្រឹត្តិការណ៍',
    'common.all': 'ទាំងអស់',
    'common.social': 'សង្គមសង្គម',
    'common.discordCommunity': 'ក្រុមហ៊ុន Discord',
    'common.account': 'គណនី',
    'common.notifications': 'Notifications',
    'common.byDeclaration': 'ដោយ៖',
    'common.done': 'រួចរាល់',
    'contentSelector.noSelection': 'No items selected',
    'contentSelector.selectedItems': 'Selected items',
    'contentSelector.entireSite': 'Search Site',
    'contentSelector.tabsLabel': 'Search options',
    'contentSelector.title': 'Select Content',
    recommended: 'បានណែនាំ',
    'select.typeToCreate': 'ចាប់ផ្ដើមវាយតម្លៃដើម្បីបង្កើតធាតុ',
    'select.noSearchResults': 'គ្មានលទ្ធផលសម្រាប់ “{search}”',
    'select.removeOption': 'ដកចេញ {option}',
    create: 'បង្កើត',
    'banner.support': 'Literary Universe is made possible thanks to the support of users like you. To help us remain independent and improve the platform, please consider subscribing to one of our plans.',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'មិនមានគណនីមែនទេ?',
    'common.haveAccountQuestion': 'មានគណនីរួចហើយមែនទេ?',
    'common.socialLogin': 'ចូលប្រើដោយប្រើប្រាស់សេវាកម្មផ្សេងៗ',
    'common.viewMore': 'មើលបន្ថែម',
    'common.overview': 'ទិដ្ឋភាព',
    'common.loggingOut': 'ចាកចេញពីប្រព័ន្ធ',
    'common.thankYou': 'សូមអរគុណ!',
    'common.seeYouAgain': 'អរគុណចំពោះការទស្សនា!',
    'email.hello': 'សួស្តី {username},',
    'common.back': 'ត្រឡប់ក្រោយ',
    'console.stop': 'ឈប់វាយតម្លៃទូរស័ព្ទ។',
    'console.explain': 'This is a browser feature intended for developers. If someone told you to copy-paste something here to enable a Literary Universe feature or "hack" someone\'s account, it is a scam and will give them access to your Literary Universe account.',
    'common.coping': 'កិច្ចការចម្លង...',
    'common.actions': 'សកម្មភាព',
    'common.popular': 'ទំនាក់ទំនងជាមួយជួរដេក',
    'common.newest': 'ថ្មីបំផុត',
    'common.oldest': 'អាក្រក់ជាងចាស់បំផុត',
    'common.noSelection': 'No selection',
    'common.content': 'Content',
    'common.theWayOfTheAuthor': 'The Way of the Author',
    'common.password.hide': 'Hide Password',
    'common.password.show': 'Show Password',
    'common.forums': 'Forums',
    'common.restriction.goodConduct': 'Due to good conduct violation we have restricted your use of this feature.',
    'common.continue': 'Continue',
    'common.authorName': 'Author Name',
    'error.invalidFileType': 'Please select a valid image file (JPEG, PNG, GIF, WebP)',
    'error.fileTooLarge': 'Image must be less than {mbSize, number}MB',
    'error.fabricInitFailed': 'Failed to initialize the image editor',
    // File upload strings
    'upload.files': 'Uploaded Files',
    'upload.dropHere': 'Drop your files here...',
    'upload.dragOrClick': 'Drag and drop files here, or click to select files',
    'upload.maxSize': 'Maximum file size: {size}',
    'upload.error.failed': 'File upload failed. Please try again.',
    'upload.error.tooManyFiles': 'You can upload a maximum of {max} files.',
    'upload.error.removeFile': 'Failed to remove file. Please try again.',
    'actions.delete': 'Delete',
    'actions.sendToKindle': 'Send to Kindle',
    'common.aiContent.indicator': 'AI-Generated Content',
    'common.aiContent.tooltip': 'This content was created with AI assistance',
    'common.aiContent.model': 'AI Model: {model}',
    'common.aiContent.custom': 'Custom AI model',
    'common.characters': 'characters',
    'common.words': 'words',
    'common.quickSummary': 'Quick Summary',
    'common.creating': 'Creating...'
};