---
blank_issues_enabled: false
contact_links:
  - about: Help translate Literary Universe on Weblate
    name: 📜 Translate
    url: https://trs.literaryuniverse.com
  - about: Do you have a question or feedback?
    name: ❓ Questions & Feedback
    url: https://www.literaryuniverse.com/feedback
  - about: Chat on our Discord community
    name: 🗯 Chat
    url: https://discord.gg/qR6dkFd
  - about: The official Literary Universe website
    name: ℹ️ Website
    url: https://www.literaryuniverse.com/
