/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'Literary Universe',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe is an all-in-one creative and publishing platform for grand story universes.',
    'site.keywords': 'creative writing, scifi, sci-fi, fantasy, writing, publishing, story, stories, universe, web novel, webnovel',
    'site.logoAlt': 'Logotipas Literatinės Visatos',
    mobileMenu: 'Mobilusis meniu',
    'common.signin': 'Prisijungti',
    'common.signup': 'Registruotis',
    'common.signout': 'Atsijungti',
    'common.dashboard': 'Valdymo skydelis',
    'common.discovery': 'Paieška',
    'common.library': 'Biblioteka',
    'common.library.own': 'Jūsų biblioteka',
    'common.workshop': 'Dirbtuvė',
    'common.pm': 'Pranešimai',
    'common.settings': 'Nustatymai',
    'common.options': 'Parinktys',
    'common.profile': 'Profilis',
    'common.blog': 'Tinklaraštis',
    'common.blogs': 'Tinklaraščiai',
    'common.about': 'Apie mus',
    'common.accessdenied': 'Prieiga uždrausta',
    'common.accessdenied.msg': 'Jums nebuvo suteikta leidimas nueiti čia. Jei turėtumėte turėti čia prieigą, prašome susisiekti su savininku ir paprašyti patikrinti nustatymus.',
    'common.loading': 'Įkeliama...',
    'common.add': 'Pridėti',
    'common.save': 'Įrašyti',
    'common.email': 'El. paštas',
    'common.soon': 'Netrukus...',
    'common.search': 'Ieškoti',
    'common.search.do': 'Ieškoti',
    'common.searching': 'Ieškoma...',
    'common.report': 'Ataskaita',
    'common.user': 'Naudotojas',
    'common.users': 'Naudotojai',
    'common.showmore': 'Rodyti daugiau',
    'common.futurefeature.title': 'Ateities funkcija',
    'common.futurefeature.text': 'Labai atsiprašome, bet ši funkcija šiuo metu nėra pasiekiama. Mes labai stengiamės, kad ji taptų pasiekiama kuo greičiau.',
    'common.nothingfound': 'Nieko nerasta',
    'common.explore': 'Tyrinėti',
    'common.by': 'pagal {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'Užrašų knygelė',
    'common.scratchpad.own': 'Jūsų užrašų knygelė',
    'common.news': 'Naujienos',
    'common.encyclopedia': 'Enciklopedija',
    'common.art': 'Art',
    'common.story': 'Pasaka',
    'common.stories': 'Pasakos',
    'common.universe': 'Visata',
    'common.universes': 'Visatos',
    'common.collaborator': 'Bendradarbis',
    'common.collaborators': 'Bendradarbiai',
    'common.translator': 'Vertėjas',
    'common.translators': 'Vertėjai',
    'common.betareader': 'Beta skaitytojas',
    'common.betareaders': 'Beta skaitytojai',
    'common.post': 'Įrašas',
    'common.statistics': 'Statistika',
    'common.lang.select': 'Pasirinkite kalbą',
    'common.submit': 'Pateikti',
    'common.close': 'Uždaryti',
    'common.comment': 'Komentaras',
    'common.comments': 'Komentarai',
    404: 'Puslapis nerastas',
    'search.users': 'Ieškoti vartotojų',
    'search.user': 'Ieškoti vartotojo',
    'common.help': 'Pagalba',
    'common.or': 'arba',
    'common.account.create': 'Sukurti paskyrą',
    'signup.username': 'Vartotojo vardas',
    'signup.email': 'Jūsų el. paštas',
    'signup.password.label': 'Jūsų slaptažodis',
    'signup.password.repeat': 'Pakartokite slaptažodį',
    'common.password': 'Slaptažodis',
    'signin.password.forgot': 'Pamiršote slaptažodį?',
    'dashboard.whatsnew': 'Kas naujo',
    'dashboard.blog': 'Jūsų tinklaraštis',
    'common.footer.tagline': 'Rašyti ir skaityti sudėtingus universus tapo lengva.',
    'common.footer.plans': 'Planai ir kainodara',
    'common.legal.tos': 'Paslaugų teikimo sąlygos',
    'common.legal.community': 'Bendruomenės gairės',
    'common.legal.privacy': 'Privatumo politika',
    'common.legal.copyright': 'Autorių teisių susitarimas',
    'common.legal.versionDisplay': `{type, select,
    tos {Terms of Service}
    community {Community Guidelines}
    privacy {Privacy Policy}
    copyright {Copyright Agreement}
    publishingAgreement {Publishing Agreement}
    other {Agreement}
  } Version {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'A new version ({newVersion}) of this document will come into effect on {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} Visos teisės saugomos, visi tekstai priklauso jų atitinkamiems autoriams.',
    'premium.only.title': 'Nepakankamai aukštas narystės lygis',
    'premium.only.msg': 'Atsiprašome, jūsų narystės lygis nepakankamai aukštas, kad galėtumėte pasiekti šią funkciją.',
    'premium.only.join': 'Mes siūlome įvairius planus kiekvienam, kad kiekvienas galėtų išgauti daugiausia iš Literary Universe.',
    'premium.only.link': 'Patikrinkite!',
    'universe.visit': 'Aplankykite universo puslapį',
    'common.fanmanager': 'Fan manager',
    'common.fanarts': 'Fan arts',
    'common.fanfiction': 'Fan fiction',
    'common.fansettings': 'Fan settings',
    'story.chapter': 'Skyrius',
    'story.chapters': 'Skyriai',
    'story.genre': 'Žanras',
    'story.genres': 'Žanrai',
    'story.read': 'Skaityti',
    'story.lastUpdate': 'Paskutinį kartą atnaujinta {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Baigta {date, date, medium}.',
    'story.comments.for': 'Komentarai skirti {story} {chapter}.',
    'story.cover.alt': 'Pasakos viršelio paveikslėlis skirtas {story}.',
    'story.note.fanfiction': 'PASTABA: Ši pasaka yra fanų kūrinys apie {universe} universą.',
    copyrights: 'Autorių teisės',
    'common.challenges': 'Iššūkiai',
    // for beta only
    'beta.notice': 'Sveiki atvykę į Literary Universe BETA. Tai viešas peržiūros variantas, todėl programa vis dar yra darbo eiga. Tai reiškia, kad vis dar galite tikėtis klaidų ir nepabaigtų funkcijų. Jei susiduriate su klaida arba kažkas neveikia, prašome pranešti mums ir prašome būti kantrūs, kol viską sutvarkysime.',
    'beta.thanks': 'Dėkojame už jūsų paramą!',
    'scratchpad.about': 'Jūsų pastabos ir idėjos pasiekiamos bet kur svetainėje.',
    'common.feedback': 'Atsiliepimai',
    'common.createdOn': 'Created on {date, date, long}',
    'common.createdOn.title': 'Created on',
    // account types
    admin: 'Administratorius',
    'common.saved': 'Išsaugota!',
    'common.saving': 'Saugoma...',
    'common.friends': 'Draugai',
    'lang.orig': 'Originali kalba',
    'lang.orig.plus': 'Originali kalba - {language}',
    buy: 'Pirkti',
    confirm: 'Patvirtinti',
    cancel: 'Atšaukti',
    processing: 'Vykdoma...',
    'common.noData': 'No data',
    'error.title': 'Įvyko klaida. Atsiprašome už nepatogumus.',
    'common.offlineStatus': 'Jūs esate neprisijungęs.',
    male: 'Vyras',
    female: 'Moteris',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: 'Prašome pasirinkti',
    'common.statusFailed': 'Nepavyko prisijungti prie serverio.',
    'common.statusConnecting': 'Bandoma prisijungti prie serverio... ({count, number})',
    'slug.checking': 'Tikrinama...',
    'slug.failed': 'Šis adresas jau egzistuoja.',
    'slug.success': 'Šis adresas yra prieinamas!',
    'notVerified.msg': `Your account {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    } is not verified.`,
    'notVerified.verify': `Please verify your {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    }.`,
    unknown: 'nežinoma',
    'common.legal.guidelines': 'Bendruomenės gairės',
    'errorLoading.title': 'Klaida įkeliant puslapį',
    'errorLoading.explained': 'Klaida įkeliant puslapį. Atsiprašome už nepatogumus. Prašome bandyti prieigą prie puslapio dar kartą. Jei problema tęsiasi, prašome mus informuoti.',
    'errorLoading.retry': 'Bandyti dar kartą!',
    'errorLoading.takingLong': 'Tai užtrunka ilgai...',
    'common.title': 'Pavadinimas',
    'common.timelines': 'Laiko juostos',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'Bendroji duomenų apsaugos reglamentacija',
    'editor.placeholder.link': 'Įveskite URL...',
    'editor.placeholder.connection': 'Ieškoti enciklopedijos įrašo...',
    'editor.saved.beta': 'Nauja Beta skaitytojams skirta versija sukurta!',
    'editor.saved.public': 'Nauja versija paskelbta!',
    goodbyeForever: 'Gaila, kad mus paliekate. Ar tai buvo mūsų kaltė? Prašome pranešti, jei taip. Vis tiek linkime jums sėkmės ateityje ir tikiuosi, kad dar susitiksime! Ilgai ir laimingai!',
    'goodbyeForever.feedback': 'Pasakykite, ką galime pagerinti',
    'common.edit': 'Redaguoti',
    'common.publish': 'Publikuoti',
    'common.publishAt': 'Publikavimo data ir laikas',
    'a11y.user.menu': 'Vartotojo meniu',
    'a11y.navigation': 'Navigation',
    'dashboard.profile': 'Jūsų profilis',
    'profile.website': 'Mano asmeninė svetainė',
    'story.notes.concept': 'Konceptas',
    'story.notes.settings': 'Pasakojimo aplinka',
    'story.notes.theme': 'Tema',
    'story.notes.impact': 'Norimas poveikis',
    'story.notes.outcome': 'Rezultatas',
    'story.notes.audience': 'Tikslinė auditorija',
    'story.notes.pitch': 'Pristatymas',
    'story.notes.notes': 'Pastabos',
    'story.authorsNotes': 'Author\'s notes',
    'common.members': 'Nariai',
    'common.language': 'Kalba',
    next: 'Kitas',
    previous: 'Previous',
    'common.legal.tos.short': 'Sąlygos',
    'common.legal.privacy.short': 'Privatumas',
    'premium.increaseLimit': 'Svarstykite atnaujinimą, kad padidintumėte savo limitą.',
    'common.sharing': 'Dalijimasis',
    'story.isbn': 'ISBN',
    'common.name': 'Vardas',
    'common.remove': 'Pašalinti',
    'common.time.milliseconds': 'Milisekundės',
    'common.time.seconds': 'Sekundės',
    'common.time.minutes': 'Minutės',
    'common.time.hours': 'Valandos',
    'common.time.days': 'Dienos',
    'common.time.weeks': 'Savaitės',
    'common.time.months': 'Mėnesiai',
    'common.time.years': 'Metai',
    'common.monetization': 'Monetization',
    'common.tab.monetizationOptions': 'Monetization options',
    'common.pagination': 'Pagination',
    'common.forum': 'Forum',
    'common.2faCode': '2FA code',
    'common.2faCodeIntro': 'Please enter your one time code generated by your authenticator application.',
    'common.2faCodeAria': '2FA code entry form',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Default language',
    'signin.web3.signMessage': 'Please confirm that you want to enter Literary Universe with your wallet as authentication method. Code: {code}',
    'common.web3.confirmationCode': 'Confirmation code: {code}',
    'common.roadmap': 'Roadmap',
    'common.luStatsIFrameOptOut': 'Literary Universe statistics opt-out',
    'common.image': 'Image',
    'common.home': 'Home',
    'common.administration': 'Administration',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'Groups',
    'common.upload': 'Upload',
    'common.backToDashboard': 'Back to dashboard',
    'common.accept': 'Accept',
    'common.reject': 'Reject',
    'common.events': 'Events',
    'common.event': 'Event',
    'common.all': 'All',
    'common.social': 'Social',
    'common.discordCommunity': 'Discord Community',
    'common.account': 'Account',
    'common.notifications': 'Notifications',
    'common.byDeclaration': 'By:',
    'common.done': 'Done',
    recommended: 'Recommended',
    'select.typeToCreate': 'Start typing to create an item',
    'select.noSearchResults': 'No results for “{search}”',
    'select.removeOption': 'Remove {option}',
    create: 'Create',
    'banner.support': 'Literary Universe is supported by users like you! Please consider subscribing to one of our subscription plans to stay independent and make Literary Universe event better!',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Don\'t have an account?',
    'common.haveAccountQuestion': 'Already have an account?',
    'common.socialLogin': 'Login with other services',
    'common.viewMore': 'View more',
    'common.overview': 'Overview',
    'common.loggingOut': 'Logging out',
    'common.thankYou': 'Thank you!',
    'common.seeYouAgain': 'See you again!',
    'email.hello': 'Hello {username},',
    'common.back': 'Back',
    'console.stop': 'Sustok!',
    'console.explain': 'Tai yra naršyklės funkcija, skirta programuotojams. Jei kas nors pasakė jums, kad čia nukopijuosite kažką, kad įgalintumėte „Literary Universe“ funkciją arba „įsilaužtumėte“ į kieno nors paskyrą, tai yra apgavystė ir leis jiems patekti į jūsų „Literary Universe“ paskyrą.'
}    /* eslint-enable max-len */;