export default {
    'groups.listing.title': 'Vartotojų grupės',
    'groups.listing.organizationTitle': 'Komandos',
    'groups.create.title': 'Sukurti naują grupę',
    'groups.type.label': 'Tipas',
    'groups.type.open': 'Atidaryta',
    'groups.type.openDesc': 'Atvira - Bet kas gali prisijungti prie grupės.',
    'groups.type.closed': 'Uždaryta',
    'groups.type.closedDesc': 'Uždaryta - Žmonės turi būti patvirtinti prieš galėdami prisijungti prie jūsų grupės.',
    'groups.type.hidden': 'Paslėpta',
    'groups.type.hiddenDesc': 'Paslėpta - Tik žmonės, kuriuos pakvietėte, gali prisijungti.',
    'groups.imageAlt': '{groupName} paveikslėlis',
    'groups.members': 'Nariai',
    'groups.members.total': `There {totalMembers, plural,
    zero {are no members}
    one {is one member}
    other {are # members}
  } in this group`,
    'groups.leaveGroup': 'Palikti grupę',
    'groups.leaveGroup.confirm': 'Tikrai norite palikti {groupName}?',
    'group.settings': 'Grupės nustatymai',
    'group.role.member': 'Narys',
    'group.role.moderator': 'Moderatorius',
    'group.role.admin': 'Administratorius',
    'groups.join.openGroup': 'Prisijungti prie grupės',
    'groups.join.closedGroup': 'Prašyti prisijungti prie grupės',
    'groups.join.questionToJoin': 'Klausimas naujiems nariams',
    'groups.join.closedAria': 'Uždarytos grupės prisijungimo forma',
    'groups.join.questionDefault': 'Kodėl turėtumėte būti leidžiamas prisijungti?',
    'groups.join.pendingRequest': 'Jūsų prašymas prisijungti prie šios grupės laukia patvirtinimo iš grupės administratorių.',
    'groups.join.requesting': 'Prašoma prisijungti',
    'groups.invite.btn': 'Pakviesti į grupę',
    'groups.invite.modalAria': 'Pakviesti vartotojus į grupės dialogą',
    'groups.invite.send': 'Siųsti kvietimą',
    'groups.invite.label': 'Rasti vartotoją, kurį pakviesti',
    'groups.invite.tileMsg': `Turite {count, plural,
    other {# grupių kvietimus}
  }`,
    'groups.invites.title': 'Grupės pakvietimai',
    'group.invite.accept': 'Priimti kvietimą',
    'group.noticeBoard': 'Skelbimų lentelė'
};