export default {
    'settings.biography': 'Biografija',
    'settings.biography.placeholder': 'Truputėlį apie save, kuris bus rodomas jūsų profilyje.',
    'settings.avatar.title': 'Avataras',
    'settings.avatar.own': 'Jūsų avataras',
    'settings.avatar.upload': 'Pasirinkite paveikslėlį',
    'settings.email': 'El. paštas',
    'settings.email.msg': 'El. paštas, susijęs su jūsų paskyra',
    'settings.email.verified.false': 'Nepatikrinta, spustelėkite, jei norite dar kartą išsiųsti patvirtinimo el. laišką.',
    'settings.email.verified.true': 'Patvirtintas el. paštas',
    'settings.email.add': 'Pridėti el. paštą',
    'settings.languages.title': 'Kalbos nustatymai',
    'settings.languages.notice': 'Anglų ir čekų kalbos šiuo metu yra vienintelės oficialiai palaikomos kalbos. Kitos kalbos yra prieinamos dėka nuostabių savanorių ir dirbtinio intelekto vertimo, tačiau jos gali būti nepilnos ir neteisingos kai kuriose vietose.',
    'settings.languages.join': 'Jei norite padėti mums, galite išversti ir Literary Universe.',
    'settings.name.title': 'Tikroji vardas',
    'settings.name.given': 'Vardas',
    'settings.name.family': 'Pavardė',
    'settings.username.change': 'Pakeisti vartotojo vardą',
    'settings.username.label': 'Vartotojo vardas',
    'settings.password.title': 'Pakeisti slaptažodį',
    'settings.password.current': 'Dabartinis slaptažodis',
    'settings.password.new': 'Naujas slaptažodis',
    'settings.password.repeat': 'Pakartokite naują slaptažodį',
    'settings.password.nomatch': 'Naujas slaptažodis nesutampa!',
    'settings.password.reset': 'Atstatykite savo slaptažodį',
    'settings.password.resetSend': 'El. laiškas su instrukcijomis, kaip atstatyti slaptažodį, buvo išsiųstas!',
    'settings.socialConnectTitle': 'Prisijunkite prie savo paskyrų iš kitų paslaugų',
    'settings.socialDisconnect': 'Atjungti',
    'settings.socialConnect': 'Prisijungti',
    'settings.loginWith': 'Prisijungti su {service}',
    'settings.connectTo': 'Prisijungti prie {service}',
    'settings.export.title': 'Eksportuoti duomenis',
    'settings.export.explain': 'Tai leis jums gauti visus jūsų duomenis, kurie yra saugomi mūsų duomenų bazėje JSON formatu.',
    'settings.export.submit': 'Eksportuoti duomenis',
    'settings.delete.title': 'Ištrinti paskyrą',
    'settings.delete.warning': `ĮSPĖJIMAS: Ištrindami paskyrą, prarasite prieigą prie šios paskyros ir
    ir jos nebebus galima atkurti. Atkreipkite dėmesį, kad tai gali neautomatiškai ištrinti jūsų publikuotų darbų,
    komentarų ir kt. Išsamesnę informaciją rasite paslaugų teikimo sąlygose.`,
    'settings.delete.confirm': 'Tik norint įsitikinti. Ar tikrai norite ištrinti savo paskyrą?',
    'settings.delete.cancel': 'Aš nenoriu ištrinti savo paskyros',
    'settings.delete.submit': 'Ištrinti mano paskyrą',
    'settings.legal.title': 'Vartotojo sutartys',
    'settings.legal.explained': 'Čia galite valdyti savo sutarimus su įvairiais teisiniais dokumentais.',
    'settings.legal.analytics.title': 'Analizė ir stebėjimas',
    'settings.legal.analytics.description': 'Galite valdyti "Literary Universe" naudojamas analizės ir stebėjimo paslaugas. Šiame skyriuje bus išvardytos visos paslaugos, kai jas pridėsime.',
    'settings.legal.analytics.ostrio': 'Norėdami išjungti "Ostrio Analytics" stebėjimą, apsilankykite jų atsisakymo puslapyje:',
    'settings.legal.analytics.ostrioOptOut': 'Tvarkykite "Ostrio Analytics" atsisakymą',
    'settings.legal.analytics.future': 'Papildomus paslaugų teikėjus, pavyzdžiui, "Google Analytics" arba "Seznam", įtrauksime čia, kai jie bus įgalinti.',
    'settings.name.private': 'Vardas bus privatus',
    'settings.emailSubscriptions.title': 'El. pašto pranešimų nustatymai',
    'settings.emailSubscriptions.explain': 'Pasirinkite, kokius el. pašto pranešimus norite gauti iš mūsų.',
    'settings.emailSubscriptions.newsletter': 'Periodinis biuletenis',
    'settings.profile': 'Profilio nustatymai',
    'settings.profile.basic': 'Pagrindinė profilio informacija',
    'settings.profile.identity': 'Tapatybė',
    'settings.profile.about': 'Apie jus',
    'settings.profile.basic.description': 'Tvarkykite pagrindinę profilio informaciją, kuri bus matoma kitiems naudotojams.',
    'settings.interests.title': 'Jūsų interesai',
    'settings.account': 'Paskyros nustatymai',
    'settings.legal.export.download': 'Atsisiųsti savo duomenis',
    'settings.legal.export.gathering': 'Renkami jūsų duomenys... Tai gali užtrukti kurį laiką.',
    'settings.gender.title': 'Jūsų lytis',
    'settings.gender.usage': 'Ši informacija liks privati. Mes naudojame šiuos duomenis platformos analitikai ir anonimizuotai analizei kūrėjams, kai jūs skaitote jų pasakojimus.',
    'settings.age.title': 'Jūsų amžius',
    'settings.age.explicit': 'Show explicit content (age rating 21+)',
    'settings.age.birthday': 'Gimimo data',
    'settings.age.usage': 'Ši informacija liks privati. Mes esame teisiškai įpareigoti paklausti apie jūsų amžių. Mes naudojame šiuos duomenis platformos analitikai, rodyti turinį pagal reitingus ir anonimizuotai analizei kūrėjams, kai jūs skaitote jų pasakojimus.',
    'settings.country.title': 'Jūsų šalis',
    'settings.country.usage': 'Mes esame teisiškai įpareigoti paklausti apie jūsų šalį, kad galėtume atsakyti į vyriausybės užklausas. Mes naudojame šiuos duomenis platformos analitikai ir anonimizuotai analizei kūrėjams, kai jūs skaitote jų pasakojimus. Jei norite, galite rodyti šią informaciją savo profilyje.',
    'settings.country.public': 'Rodyti jūsų šalį viešai',
    'settings.country.select': 'Pasirinkite savo šalį',
    'settings.emailSubscriptions.newsletterTech': 'Periodinis naujienlaiškis iš mūsų kūrėjų',
    'settings.emailSubscriptions.newsletterFeatures': 'Informacija apie naujas funkcijas',
    'settings.emailNotifications.title': 'Pranešimai',
    'settings.emailNotifications.pm': 'Nauji žinučių',
    'settings.emailNotifications.newChapters': 'Nauji sekamų istorijų skyriai',
    'settings.emailNotifications.newStories': 'Naujos istorijos visatose arba iš autorių, kuriuos sekate',
    'settings.emailNotifications.newUniverses': 'Naujos sekamų autorių visatos',
    'settings.resetPasswordEmailSend': 'Mes išsiuntėme jums instrukcijas, kaip atkurti slaptažodį jūsų el. paštu.',
    'settings.theme.title': 'Svetainės tematika',
    'settings.theme.label': 'Svetainės tema',
    'settings.theme.light': 'Šviesi',
    'settings.theme.dark': 'Tamsi',
    'settings.links.title': 'Nuoroda į jūsų kitas svetaines',
    'settings.links.description': 'Šios nuorodos bus rodomos jūsų profilio puslapyje.',
    'settings.links.website': 'Jūsų asmeninė svetainė',
    'settings.links.social': 'Kitos svetainės',
    'settings.links.select': 'Pasirinkite svetainę, kurią norite pridėti',
    // 2FA
    'settings.2fa.title': 'Dviejų veiksnių autentifikacija',
    'settings.2fa.explained': 'Dviejų veiksnių autentifikacija suteikia papildomą saugos lygį jūsų paskyrai, pridedant papildomą autentifikacijos žingsnį prisijungimo metu. Tai neleidžia kenkėjiškiems veikėjams patekti į jūsų paskyrą, jei pirmas prisijungimo žingsnis yra pažeistas.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Dviejų veiksnių autentifikacija su OTP kodu sukuria vienkartinį slaptažodį per autentifikavimo programas (pvz., Authy, Google/Microsoft Authenticator ir kt.), kurį įvedate prisijungimo metu.',
    'settings.2fa.otpModalAria': '2FA OTP metodas',
    'settings.2fa.otpAdd': 'Pridėti 2FA OTP',
    'settings.2fa.confirmCode': 'Kodas, kuris rodomas jūsų autentifikavimo programoje',
    'settings.2fa.svgAlt': 'QR kodas autentifikavimo programai',
    'settings.2fa.codeHeading': 'Jei negalite nuskaityti QR kodo, galite rankiniu būdu įvesti šį kodą:',
    'settings.2fa.instructionsTitle': 'Instrukcijos',
    'settings.2fa.instructions1': 'Įdiekite ir atidarykite pasirinktą autentifikavimo programą (Authy, Google/Microsoft Authenticator, FreeOTP ir kt.)',
    'settings.2fa.instructions2': 'Pasirinkite „Pridėti paskyrą“ (gali būti matoma „+“ piktograma arba gali būti paslėpta meniu)',
    'settings.2fa.instructions3': 'Nuskaitykite QR kodą, kuris rodomas čia, arba jei tai neįmanoma, įveskite kodą žemiau.',
    'settings.2fa.instructions4': 'Įveskite 6 skaičius, kurie rodomi ekrane, įvesties lauke čia, kad užbaigtumėte.',
    'settings.2fa.saved': 'Dviejų veiksnių autentifikacija sėkmingai įdiegta!',
    'settings.2fa.disableOTP': 'Išjungti OTP dviejų veiksnių autentifikaciją',
    // API Keys
    'settings.apiKeys.title': 'API raktai',
    'settings.apiKeys.description': 'API raktai leidžia trečiųjų šalių programoms jūsų vardu pasiekti "Literary Universe" duomenis. Elkitės su jais kaip su slaptažodžiais ir niekada jais nesidalykite.',
    'settings.apiKeys.noKeys': 'Dar neturite jokių API raktų.',
    'settings.apiKeys.created': 'Sukurta {date, date, medium} adresu {date, time, short}',
    'settings.apiKeys.lastUsed': 'Paskutinį kartą naudotas {time}',
    'settings.apiKeys.neverUsed': 'Niekada nenaudota',
    'settings.apiKeys.expires': 'Galioja {date, date, medium}',
    'settings.apiKeys.name': 'Rakto pavadinimas',
    'settings.apiKeys.name.placeholder': 'pvz., "Obsidian" įskiepis',
    'settings.apiKeys.permissions': 'Leidimai',
    'settings.apiKeys.generate': 'API rakto generavimas',
    'settings.apiKeys.generated.title': 'Sukurtas API raktas',
    'settings.apiKeys.generated.warning': 'Išsaugokite šį raktą dabar! Daugiau jo nebegalėsite pamatyti.',
    'settings.apiKeys.copyToClipboard': 'Kopijuoti į iškarpinę',
    'settings.apiKeys.expiration': 'Galiojimo pabaiga',
    'settings.apiKeys.expiration.duration': `{months, plural,
    =1 {1 mėnuo}
    =3 {3 mėnesiai}
    =6 {6 mėnesiai}
    =12 {1 metai (rekomenduojama)}
    =24 {2 metai}
    other {~{months} mėnesiai}
  }`,
    'settings.apiKeys.revoke.confirm': 'Ar tikrai norite atšaukti šį API raktą? Šio veiksmo atšaukti negalima.',
    'settings.apiKeys.delete.confirm': 'Ar tikrai norite ištrinti šį API raktą? Šio veiksmo atšaukti negalima.',
    'settings.apiKeys.error.nameRequired': 'Įveskite savo API rakto pavadinimą',
    'settings.apiKeys.error.scopesRequired': 'Pasirinkite bent vieną leidimą',
    'settings.apiKeys.security.title': 'Saugumo pranešimas',
    'settings.apiKeys.security.1': 'Niekada su niekuo nesidalykite savo API raktu',
    'settings.apiKeys.security.2': 'Elkitės su juo kaip su slaptažodžiu',
    'settings.apiKeys.security.3': 'Galite bet kada atšaukti prieigą',
    'settings.apiKeys.security.4': 'Raktas bus rodomas tik vieną kartą',
    'settings.apiKeys.scope.story.read': 'Skaityti istorijas',
    'settings.apiKeys.scope.story.read.desc': 'Prieiga prie istorijos pavadinimų, turinio ir skyrių',
    'settings.apiKeys.scope.story.write': 'Kurkite ir redaguokite istorijas',
    'settings.apiKeys.scope.story.write.desc': 'Kurkite naujas istorijas ir atnaujinkite esamas',
    'settings.apiKeys.scope.universe.read': 'Skaityti visatas',
    'settings.apiKeys.scope.universe.read.desc': 'Prieiga prie enciklopedijos įrašų ir pasaulio kūrimo duomenų',
    'settings.apiKeys.scope.universe.write': 'Kurkite ir redaguokite visatas',
    'settings.apiKeys.scope.universe.write.desc': 'Kurti ir atnaujinti enciklopedijos įrašus',
    'settings.apiKeys.scope.scratchpad.read': 'Skaityti pastabas',
    'settings.apiKeys.scope.scratchpad.read.desc': 'Prieiga prie asmeninių užrašų ir užrašų knygelės',
    'settings.apiKeys.scope.scratchpad.write': 'Kurkite ir redaguokite pastabas',
    'settings.apiKeys.scope.scratchpad.write.desc': 'Sukurkite ir atnaujinkite užrašus',
    'settings.apiKeys.scope.blog.read': 'Skaityti tinklaraščio įrašus',
    'settings.apiKeys.scope.blog.read.desc': 'Prieiga prie tinklaraščio įrašų ir juodraščių',
    'settings.apiKeys.scope.blog.write': 'Kurti ir redaguoti tinklaraščio įrašus',
    'settings.apiKeys.scope.blog.write.desc': 'Sukurti ir atnaujinti tinklaraščio įrašus',
    'settings.apiKeys.scope.user.read': 'Skaityti profilį',
    'settings.apiKeys.scope.user.read.desc': 'Prieiga prie vartotojo vardo, avataro ir viešo profilio',
    'settings.apiKeys.scope.library.read': 'Skaityti biblioteką',
    'settings.apiKeys.scope.library.read.desc': 'Prieiga prie skaitymo sąrašų ir išsaugotų istorijų',
    // Web3
    'settings.web3.legend': 'Web3 piniginės prisijungimas',
    'settings.web3.explained': 'Galite prisijungti savo Web3 kriptopiniginę prie jūsų Literary Universe paskyros. Kai prisijungsite, galėsite prisijungti su savo pinigine ir ateityje atlikti dar daugiau veiksmų, išplečiant mūsų Web3 pasiūlymą.',
    'settings.web3.connect': 'Prijungti savo piniginę',
    'settings.web3.address': 'Prijungtas adresas: {address}',
    'settings.web3.verify': 'Patvirtinkite savo adresą',
    'settings.web3.verify.explained': 'Norint patvirtinti, kad šis adresas jums priklauso, mes paprašysime jus pasirašyti žinutę, kad užtikrintume jūsų piniginės nuosavybę.',
    'settings.web3.verified': 'Patvirtinta',
    'settings.web3.verificationMessage': 'Vartotojo {username} patikrinimas Literary Universe. Kodas: {code}',
    'settings.web3.unlink': 'Pašalinti piniginę',
    'settings.web3.linkingMessage': 'Prašome patvirtinti, kad norite susieti savo piniginę su Literary Universe. Kodas: {code}',
    'settings.web3.linkError': 'Šis adresas jau yra sąraše ir negali būti priskirtas!',
    // Reader settings
    'settings.reader.title': 'Skaitymo nustatymai',
    'settings.reader.darkMode': 'Visada rodyti tamsiuoju režimu',
    'settings.reader.asideView': 'Rodyti magišką šoninę juostą',
    'settings.reader.textSize': 'Rodyti tekstą didesniu šriftu',
    'settings.reader.storyRecommendations': 'Istorijos rekomendacijos',
    'settings.reader.storyRecommendationsHelp': 'Įgalinkite asmenines istorijų rekomendacijas.',
    // AI settings
    'settings.ai.title': 'AI nustatymai',
    'settings.ai.explained': 'Konfigūruokite, kaip dirbtinio intelekto funkcijos veikia "Literary Universe".',
    // Accessibility
    'settings.accessibility.title': 'Skaitymo prieinamumas',
    'settings.accessibility.openDyslexic': 'Naudoti OpenDyslexic šriftą',
    'settings.accessibility.paragraphStripes': 'Alternatyvi fono spalva pastraipoms',
    'settings.accessibility.paragraphHighlighting': 'Paryškinti dabartinę pastraipą, kuriuo būsite užvedę pelę',
    'settings.accessibility.ruler': 'Prisegti linijalą prie pelės',
    // Story Recommendations
    'settings.storyRecommendations.title': 'Istorijos rekomendacijos',
    'settings.storyRecommendations.explained': 'Įgalinkite asmenines istorijų rekomendacijas visoje programėlėje pagal savo skaitymo pageidavimus ir istoriją.',
    'settings.tab.legal': 'Teisiniai dokumentai',
    'settings.tab.exportDelete': 'Eksportuoti duomenis ir ištrinti paskyrą',
    'settings.languages.uiLanguage': 'Sąsajos kalba',
    'settings.languages.readingLanguage': 'Skaitymo kalba',
    'settings.languages.readingLanguageExplained': 'Ieškodami istorijų, pasiūlysime jums istorijas ir jų vertimus šia kalba, nebent nurodysite kitaip.',
    'settings.biography.help': 'Papasakokite kitiems apie save',
    'settings.username.help': 'Jūsų unikalus naudotojo vardas platformoje',
    'settings.interests.tags.custom.help': 'Įveskite kableliais atskirtą žymų sąrašą',
    'settings.interests.tags.placeholder': 'Pridėti žymas',
    'settings.interests.avoidGenres.help': 'Pasirinkite žanrus, kurių nenorėtumėte matyti rekomendacijose.',
    'settings.interests.avoidGenres': 'Žanrai, kurių reikia vengti',
    'settings.notifications': 'Pranešimai ir naujienlaiškiai',
    'settings.kindleEmail': 'Jūsų "Kindle" el. paštas',
    'settings.kindleEmail.explained': 'Jei turite šį nustatymą, jei įmanoma, pasiūlysime jums galimybę siųsti istorijas į "Kindle" vienu spustelėjimu. Savo "Kindle" el. pašto adresą galite rasti "Amazon" nustatymuose, skiltyje Turinys ir įrenginiai -> Įrenginiai -> pasirinkite savo "Kindle", kad peržiūrėtumėte jo duomenis, ir ten rasite nurodytą el. pašto adresą.'
};