export default {
    'sharing.title': 'Dalintis',
    'sharing.button': 'Dalintis mygtuku',
    'sharing.share': 'Dalintis su...',
    'sharing.feedback': 'Ar trūksta vietos, kur norėtumėte dalintis? Praneškite mums apie tai!',
    'sharing.copy': 'Kopijuoti',
    'sharing.email': 'El. paštas',
    'sharing.sms': 'SMS',
    'sharing.messenger': 'Facebook Messenger',
    'sharing.whatsapp': 'WhatsApp',
    'sharing.twitter': 'X/Twitter',
    'sharing.linkedin': 'LinkedIn',
    'sharing.telegram': 'Telegram',
    'sharing.facebook': 'Facebook',
    'sharing.line': 'LINE',
    'sharing.mastodonSocial': 'Mastodon Social',
    'sharing.mastodonJapan': 'Mastodon Japan',
    'sharing.gab': 'Gab',
    'sharing.pinterest': 'Pinterest',
    'sharing.gettr': 'Gettr',
    'sharing.minds': 'Minds.com',
    'sharing.instagram': 'Instagram',
    'sharing.reddit': 'Reddit',
    'sharing.bsky': 'BlueSky',
    // Advanced sharing with QR codes
    'sharing.advanced.link': 'Išplėstinis bendrinimas naudojant QR kodą',
    'sharing.advanced.pageTitle': 'QR kodai',
    'sharing.advanced.title': 'Išplėstinis bendrinimas',
    'sharing.advanced.description': 'Kurkite gražias dalijimosi korteles su QR kodais savo turiniui.',
    'sharing.advanced.modeSocial': 'Internetinis vaizdas',
    'sharing.advanced.modePrint': 'Spausdinti',
    'sharing.advanced.paperSize': 'Popieriaus dydis',
    'sharing.advanced.documentSize': 'Dokumento dydis',
    'sharing.advanced.letter': 'JAV laiškas',
    'sharing.advanced.qrPreview': 'QR kodo peržiūra',
    'sharing.advanced.qrAlt': 'QR kodo nuoroda į turinį',
    'sharing.advanced.download': 'Atsisiųsti',
    'sharing.advanced.downloadQR': 'Atsisiųsti QR kodą',
    'sharing.advanced.downloadImage': 'Atsisiųsti vaizdą',
    'sharing.advanced.copyLink': 'Kopijuoti nuorodą',
    'sharing.advanced.copied': 'Nukopijuota!',
    'sharing.advanced.qrError': 'Nepavyko sukurti QR kodo',
    'sharing.advanced.generateError': 'Nepavyko sukurti bendrinimo vaizdo',
    'sharing.advanced.seoTitle': 'Išplėstinis bendrinimas - {title}',
    'sharing.advanced.layoutEditor': 'Maketavimo redaktorius',
    'sharing.advanced.preview': 'Vaizdų peržiūra',
    'sharing.advanced.socialDescription': 'Sukurkite bendrinimui internete skirtą vaizdą.',
    'sharing.advanced.shareOnSocial': 'Internetinis vaizdas',
    'sharing.advanced.print': 'Spausdinti',
    'sharing.advanced.selectLayout': 'Pasirinkite išdėstymą',
    'sharing.advanced.layout1': '"Instagram"',
    'sharing.advanced.layout2': '"Facebook"',
    'sharing.advanced.layout3': 'X / "Twitter',
    'sharing.advanced.backgroundColor': 'Vaizdo elemento spalva',
    'sharing.advanced.glassPanelColor': 'Stiklo plokštės spalva',
    'sharing.advanced.genreBackground': 'Žanro fonas',
    'sharing.advanced.printLayout': 'Spausdinti maketą',
    'sharing.advanced.printTemplate1': '1 šablonas',
    'sharing.advanced.printTemplate2': '2 šablonas',
    'sharing.advanced.printTemplate3': '3 šablonas',
    'sharing.advanced.printTemplate4': '4 šablonas',
    'sharing.advanced.printTemplate5': '5 šablonas',
    'sharing.advanced.printTemplate6': '6 šablonas',
    'sharing.advanced.fontColor': 'Šrifto spalva',
    // Canvas labels
    'sharing.canvas.by': 'pagal',
    'sharing.canvas.chapter': 'Skyrius {chapterNumber}',
    'sharing.canvas.publishesOn': 'Skelbiama svetainėje {date}'
};