export default {
  "encyclopedia.add": "ഒരു പുതിയ എന്‍ട്രി ചേര്‍ക്കുക",
  "encyclopedia.browse": "എന്‍സൈക്ലോപീഡിയ മൂലകളില്‍ ബ്രൗസ് ചെയ്യുക",
  "encyclopedia.search": "എന്‍സൈക്ലോപീഡിയയില്‍ തിരയുക",
  "encyclopedia.back.universe": "യൂണിവേഴ്‌സ് പേജിലേക്ക് മടങ്ങുക",
  "encyclopedia.back.workshop": "വർക്ക്ഷോപ്പിലേക്ക് മടങ്ങുക",
  "encyclopedia.categories": "വിഭാഗങ്ങൾ",
  "encyclopedia.groups": "ഗ്രൂപ്പുകൾ",
  "encyclopedia.category.character": "കഥാപാത്രങ്ങൾ",
  "encyclopedia.category.event": "സംഭവങ്ങൾ",
  "encyclopedia.category.group": "ഗ്രൂപ്പുകൾ",
  "encyclopedia.category.item": "ഇനങ്ങൾ",
  "encyclopedia.category.location": "സ്ഥലങ്ങൾ",
  "encyclopedia.category.other": "മറ്റുള്ളവ",
  "encyclopedia.category.state": "സംസ്ഥാനങ്ങൾ",
  "encyclopedia.category.governments": "ഗവേണ്‍മെന്റുകൾ",
  "encyclopedia.category.languages": "ഭാഷകൾ",
  "encyclopedia.category.creatures": "ജീവികള്‍",
  "encyclopedia.category.deity": "ദൈവങ്ങൾ",
  "encyclopedia.category.religions": "മതങ്ങൾ",
  "encyclopedia.category.flora": "സസ്യങ്ങൾ",
  "encyclopedia.category.magic": "മാന്ത്രികം",
  "encyclopedia.category.planets": "ഗ്രഹങ്ങൾ",
  "encyclopedia.category.species": "ജാതികള്‍",
  "encyclopedia.category.technologies": "പ്രവർത്തനങ്ങൾ",
  "encyclopedia.category.families": "Families",
  "encyclopedia.category.jobs": "Jobs",
  "encyclopedia.category.lore": "Lore",
  "encyclopedia.category.vehicles": "Vehicles",
  "encyclopedia.category.diseases": "Diseases",
  "encyclopedia.category.traditions": "Traditions",
  "encyclopedia.category.sports": "Sports",
  "encyclopedia.category.food": "Food",
  "encyclopedia.category.landmarks": "Landmarks",
  "encyclopedia.category.buildings": "Buildings",
  "encyclopedia.category.schools": "Schools",
  "encyclopedia.category.continents": "Continents",
  "encyclopedia.category.villages": "Villages",
  "encyclopedia.category.towns": "Towns",
  "encyclopedia.category.cities": "Cities",
  "encyclopedia.category.settlements": "Settlements",
  "encyclopedia.category.countries": "Countries",
  "encyclopedia.search.found": "{results, plural,\n    =0 {സംബന്ധിച്ച എന്തെങ്കിലും പ്രവേശനങ്ങൾ ഇല്ലെങ്കിൽ}\n    one {1 സംബന്ധിച്ച പ്രവേശനം കാണുന്നു}\n    other {# സംബന്ധിച്ച പ്രവേശനങ്ങൾ കാണുന്നു}\n  } കണ്ടെത്തി.",
  "encyclopedia.help.text": "എൽഎൽഎസ്റ്റിൽ ഇൻസൈക്ലോപീഡിയ ഇനങ്ങളിലേക്ക് നാവിഗേറ്റുചെയ്യുവാൻ ഇടയാക്കാനുള്ള മെനു ഉപയോഗിക്കുക. ഒരു ഇനം തിരഞ്ഞെടുത്താൽ, ഈ ടെക്സ്റ്റ് പ്രദർശിപ്പിക്കപ്പെടും.",
  "encyclopedia.help.sidebar": "സൈഡ്ബാര്‍ ടൂള്‍ബോക്സ്",
  "encyclopedia.help.sidebar.text": "Welcome to your story! This sidebar allows you easy access to all resources related to your story. Check the icons above to see the latest comments, your notes, search your encyclopedia, browse and add new entries to your encyclopedia. If you want to add a connection to an entry from the story text, select the text where you want to place it and then click the connect button. You will then be prompted to find and select an item.",
  "encyclopedia.intro": "സ്വാഗതം {universe} എൻസൈക്ലോപീഡിയയിലേക്ക്.",
  "encyclopedia.add.title": "എൻസൈക്ലോപീഡിയയിലേക്ക് ഒരു പുതിയ പ്രവേശനം ചേർക്കുക",
  "encyclopedia.add.heading": "നിങ്ങൾ എന്താണ് ചേർക്കാൻ ആഗ്രഹിക്കുന്നത്?",
  "encyclopedia.add.moresoon": "കൂടുതൽ വിഭാഗങ്ങൾ വേണമെങ്കിൽ വരികളുംകൂടി വരിക്കുന്നു!",
  "encyclopedia.create": "Create new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {villages}\n    towns {towns}\n    cities {cities}\n    settlements {settlement}\n    countries {country}\n  }",
  "encyclopedia.create.header": "Creating a new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {village}\n    towns {town}\n    cities {city}\n    settlements {settlement}\n    countries {country}\n  } in {universe}",
  "encyclopedia.entry.category": "Entry category: {category, select,\n    character {Character}\n    event {Event}\n    group {Group}\n    item {Item}\n    location {Location}\n    other {Note}\n    state {State}\n    governments {Government}\n    languages {Language}\n    creatures {Creature}\n    deity {Deity}\n    religions {Religion}\n    flora {Flora}\n    magic {Magic}\n    planets {Planet}\n    species {Specie}\n    technologies {Technology}\n    families {Family}\n    jobs {Job}\n    lore {Lore}\n    vehicles {Vehicle}\n    diseases {Disease}\n    traditions {Tradition}\n    food {Food}\n    sports {Sport}\n    landmarks {Landmark}\n    buildings {Building}\n    schools {School}\n    continents {Continent}\n    villages {Village}\n    towns {Town}\n    cities {City}\n    settlements {Settlement}\n    countries {Country}\n  }",
  "encyclopedia.entry.category.legend": "വിഭാഗം",
  "encyclopedia.fields.add": "പുതിയ ഫീൽഡ് ചേർക്കുക",
  "encyclopedia.fields.text": "വ്യാഖ്യാനം",
  "encyclopedia.fields.textarea": "ടെക്സ്റ്റ്",
  "encyclopedia.fields.connection": "ബന്ധം",
  "encyclopedia.fields.time": "സമയം",
  "encyclopedia.fields.image": "ചിത്രം",
  "encyclopedia.visibility": "ദൃശ്യത്തിലേക്ക്",
  "encyclopedia.public": "പൊതുവായി",
  "encyclopedia.private": "സ്വകാര്യമായി",
  "encyclopedia.container": "കൺറ്റെയ്നർ",
  "encyclopedia.container.desc": "Make this entry a container for a new group of entries. This will hide it from the categories listing.",
  "encyclopedia.entry.name": "പ്രവേശനത്തിന്റെ പേര്",
  "encyclopedia.summary": "സംഗ്രഹം",
  "encyclopedia.summary.desc": "This is a summary that will be the only initial information displayed to the reader.",
  "encyclopedia.parent": "പാരന്റ് പ്രവേശനം",
  "encyclopedia.related": "ബന്ധിപ്പിക്കുന്ന പ്രവേശനങ്ങൾ",
  "encyclopedia.errors.tags": "പ്രവേശനത്തിന് മാത്രം 10 ടാഗുകൾ ഉണ്ടാക്കാവുന്നു.",
  "encyclopedia.field.private": "സ്വകാര്യ ഫീൽഡ്",
  "encyclopedia.ft.indev": "ഈ ഓപ്ഷൻ വികസനത്തിൽ ഉണ്ടാക്കപ്പെടുന്നു.",
  "encyclopedia.connections.remove": "കണക്ഷൻ നീക്കം ചെയ്യുക",
  "encyclopedia.connections.extra": "അധിക വിവരങ്ങൾ",
  "encyclopedia.connections.existing": "നിലവിലുള്ള എൻട്രി",
  "encyclopedia.connections.existing.abbr": "EE",
  "encyclopedia.cover": "കവർ ചിത്രം",
  "encyclopedia.translation.title": "{universe} യൂണിവേഴ്സ് പരിഭാഷ സ്വാഗതം!",
  "encyclopedia.translation.desc": "ഈ എൻസൈക്ലോപീഡിയ ഇന്റർഫേസ് {language}ലേക്ക് പരിഭാഷ ചെയ്യാൻ ഉപയോഗിക്കുന്നു. പ്രത്യേക എൻട്രികൾ പട്ടികയിൽ നിന്നും നിങ്ങളുടെ പരിഭാഷ ആരംഭിക്കാൻ തയ്യാറാക്കുക.",
  "encyclopedia.welcome.totalEntries": "There {totalEntries, plural, \n    zero {are no entries}\n    one {is one entry}\n    other {are # entries}\n  } in this universe.",
  "encyclopedia.settings.title": "എൻസൈക്ലോപീഡിയ ക്രമീകരണങ്ങൾ",
  "encyclopedia.settings.categoriesDesc": "നിങ്ങൾ എന്തെങ്കിലും ഉപയോഗിക്കാനുള്ള വിഭാഗങ്ങൾ ഓൺ ആക്കാം അല്ലെങ്കിൽ ഓഫ് ആക്കാം.",
  "encyclopedia.settings.introText": "യൂണിവേഴ്സ് വിവരണത്തിന് ശേഷം കാണിക്കാൻ ആദ്യസ്ഥാനം സംവിധാനം സന്ദർശിക്കുന്ന സ്വാഗത സന്ദേശം.",
  "encyclopedia.fields.placeholder": "ഫീൽഡ് പേര്",
  "encyclopedia.fields.delete": "ഫീൽഡ് ഇല്ലാതാക്കുക",
  "encyclopedia.timeOption.fictionalDate": "കഥാസമയം",
  "encyclopedia.timeOption.fictionalTime": "കഥാസമയ സമയം",
  "encyclopedia.timeOption.fictionalDateTime": "കഥാസമയ തീയതി സമയം",
  "encyclopedia.timeOption.date": "തീയതി",
  "encyclopedia.timeOption.time": "സമയം",
  "encyclopedia.timeOption.dateTime": "തീയതിയും സമയവും",
  "encyclopedia.settings.groupByCategories": "ഗ്രൂപ്പ് ലിസ്റ്റിംഗിൽ വിഭാഗങ്ങൾ ഉൾപ്പെടുത്തുക",
  "encyclopedia.menuOpen": "എൻസൈക്ലോപീഡിയ മെനു തുറക്കുക",
  "encyclopedia.menuClose": "എൻസൈക്ലോപീഡിയ മെനു അടയ്ക്കുക",
  "encyclopedia.menuAria": "എൻസൈക്ലോപീഡിയ മെനു",
  "enc.newField": "പുതിയ ഫീൽഡ്",
  "enc.entries.limit": "നിങ്ങൾക്ക് നിലവിലുള്ളത് {value, number} എന്നതിൽ {max, plural,\n    =0 {അപരിമിതമായ}\n    other {{max, number}}\n  } എൻട്രീകൾ ഉണ്ട്.",
  "enc.entries.limitReached": "നിങ്ങൾക്ക് നിയമനിർമ്മിതമായ എൻട്രീകൾക്കായി ഏറ്റവും പരമാവധി അനുവദനീയമായിരിക്കുന്നു.",
  "encyclopedia.pronunciation.title": "ഉച്ചാരണം",
  "encyclopedia.wip.abbreviation": "WIP",
  "encyclopedia.wip.full": "പ്രവർത്തനത്തിൽ ഉൾപ്പെടുന്നു",
  "encyclopedia.settings.templateLegend": "ടെംപ്ലേറ്റ് യൂണിവേഴ്‌സ്",
  "encyclopedia.settings.templateDescription": "ഈ എൻസൈക്ലോപീഡിയയുടെ ഉള്ളടക്കം മറ്റ് യൂണിവേഴ്‌സുകളിൽ പകർത്താൻ അനുവദിക്കുന്നു. നിങ്ങൾക്ക് സ്റ്റോറികളും അല്ലെങ്കിൽ മറ്റൊരുവഴിയിൽ സൃഷ്ടിക്കുന്നതാണെങ്കിൽ, മറ്റുള്ളവരുടെ ഉപയോഗത്തിനായി ഒരു ടെംപ്ലേറ്റ് സൃഷ്ടിക്കുന്നതിനാണ് ഇത് മികച്ചത്.",
  "encyclopedia.settings.templateCheckbox": "ഇത് ഒരു ടെംപ്ലേറ്റ് യൂണിവേഴ്‌സ് ആണ്",
  "encyclopedia.templateCopy.modalTitle": "എൻസൈക്ലോപീഡിയ ഉള്ളടക്കം പകർത്തുക",
  "encyclopedia.templateCopy.description": "ഈ എൻസൈക്ലോപീഡിയയുടെ ഉള്ളടക്കം നിങ്ങളുടെ യൂണിവേഴ്‌സിലേക്ക് പകർത്തിയിട്ട് അതിനു പിന്നിൽ അതു പ്രശ്നങ്ങൾക്ക് പരിഹരിക്കാൻ സഹായിക്കുക.",
  "encyclopedia.templateCopy.targetUniverse": "പകർത്താൻ യൂണിവേഴ്‌സ്",
  "encyclopedia.templateCopy.finished": "പകർപ്പിച്ചു കഴിഞ്ഞു",
  "encyclopedia.templateCreateUniverse.modalTitle": "Create universe from template",
  "encyclopedia.templateCreateUniverse.description": "Create a new universe with pre-seeded encyclopedia content from this template. Your universe will remain private until you decide to make it public.",
  "encyclopedia.templateCreateUniverse.success": "Universe created successfully! Redirecting...",
  "encyclopedia.pronunciation.audio.play": "Play pronunciation",
  "encyclopedia.pronunciation.guide": "Use <ipaLink>IPA notation</ipaLink> when possible. Web Speech API pronunciation is best-effort; see <webSpeechLink>MDN docs</webSpeechLink>.",
  "encyclopedia.templateField.born": "Born",
  "encyclopedia.templateField.died": "Died",
  "encyclopedia.templateField.race": "Race",
  "encyclopedia.templateField.gender": "ലിംഗം",
  "encyclopedia.templateField.partners": "Partners",
  "encyclopedia.templateField.parents": "Parents",
  "encyclopedia.templateField.children": "Children",
  "encyclopedia.templateField.associated-with": "Associated with",
  "encyclopedia.templateField.biography": "ജീവചരിത്രം",
  "encyclopedia.templateField.physical-appearance": "Physical appearance",
  "encyclopedia.templateField.type-of-event": "Type of event",
  "encyclopedia.templateField.preceding-events": "Preceding events",
  "encyclopedia.templateField.following-events": "Following events",
  "encyclopedia.templateField.leadup": "Leadup",
  "encyclopedia.templateField.description": "വിവരണം",
  "encyclopedia.templateField.aftermath": "Aftermath",
  "encyclopedia.templateField.members": "അംഗങ്ങൾ",
  "encyclopedia.templateField.locations": "സ്ഥലങ്ങൾ",
  "encyclopedia.templateField.events": "സംഭവങ്ങൾ",
  "encyclopedia.templateField.vision": "Vision",
  "encyclopedia.templateField.mission": "Mission",
  "encyclopedia.templateField.description-of-the-organization": "Description of the organization",
  "encyclopedia.templateField.history": "History",
  "encyclopedia.templateField.owners": "Owners",
  "encyclopedia.templateField.function": "Function",
  "encyclopedia.templateField.content": "Content",
  "encyclopedia.templateField.population": "Population",
  "encyclopedia.templateField.culture": "Culture",
  "encyclopedia.templateField.governments": "ഗവേണ്‍മെന്റുകൾ",
  "encyclopedia.templateField.religions-believes": "Religions & believes",
  "encyclopedia.templateField.languages": "ഭാഷകൾ",
  "encyclopedia.templateField.geography": "Geography",
  "encyclopedia.templateField.founding": "Founding",
  "encyclopedia.templateField.notable-events": "Notable events",
  "encyclopedia.templateField.notes": "കുറിപ്പുകൾ",
  "encyclopedia.templateField.type-of-government": "Type of government",
  "encyclopedia.templateField.structure": "Structure",
  "encyclopedia.templateField.power-structure": "Power structure",
  "encyclopedia.templateField.source-of-power": "Source of power",
  "encyclopedia.templateField.laws": "Laws",
  "encyclopedia.templateField.ideology": "Ideology",
  "encyclopedia.templateField.internal-politics": "Internal politics",
  "encyclopedia.templateField.external-politics": "External politics",
  "encyclopedia.templateField.leading-figures": "Leading figures",
  "encyclopedia.templateField.groups": "ഗ്രൂപ്പുകൾ",
  "encyclopedia.templateField.military": "Military",
  "encyclopedia.templateField.items": "ഇനങ്ങൾ",
  "encyclopedia.templateField.typology": "Typology",
  "encyclopedia.templateField.dialectics": "Dialectics",
  "encyclopedia.templateField.phonology": "Phonology",
  "encyclopedia.templateField.grammar": "Grammar",
  "encyclopedia.templateField.numbers": "Numbers",
  "encyclopedia.templateField.quantifiers": "Quantifiers",
  "encyclopedia.templateField.private-notes": "Private notes",
  "encyclopedia.templateField.type": "Type",
  "encyclopedia.templateField.notable-features": "Notable features",
  "encyclopedia.templateField.traits": "Traits",
  "encyclopedia.templateField.habitat": "Habitat",
  "encyclopedia.templateField.food-sources": "Food sources",
  "encyclopedia.templateField.reproduction": "Reproduction",
  "encyclopedia.templateField.cultural-significance": "Cultural significance",
  "encyclopedia.templateField.related-creatures": "Related creatures",
  "encyclopedia.templateField.religion": "Religion",
  "encyclopedia.templateField.other-names": "Other names",
  "encyclopedia.templateField.appearance": "Appearance",
  "encyclopedia.templateField.related-to": "Related to",
  "encyclopedia.templateField.symbolism": "Symbolism",
  "encyclopedia.templateField.rituals": "Rituals",
  "encyclopedia.templateField.origin": "Origin",
  "encyclopedia.templateField.notable-figures": "Notable figures",
  "encyclopedia.templateField.deities": "ദൈവങ്ങൾ",
  "encyclopedia.templateField.artifacts": "Artifacts",
  "encyclopedia.templateField.believes": "Believes",
  "encyclopedia.templateField.traditions": "Traditions",
  "encyclopedia.templateField.spread": "Spread",
  "encyclopedia.templateField.classification": "Classification",
  "encyclopedia.templateField.features": "Features",
  "encyclopedia.templateField.produce": "Produce",
  "encyclopedia.templateField.ecosystem": "Ecosystem",
  "encyclopedia.templateField.effect": "Effect",
  "encyclopedia.templateField.alignment": "Alignment",
  "encyclopedia.templateField.requirements": "Requirements",
  "encyclopedia.templateField.size": "Size",
  "encyclopedia.templateField.length-of-day": "Length of day",
  "encyclopedia.templateField.length-of-night": "Length of night",
  "encyclopedia.templateField.length-of-cycle": "Length of cycle",
  "encyclopedia.templateField.moons": "Moons",
  "encyclopedia.templateField.nearby-stellar-bodies": "Nearby stellar bodies",
  "encyclopedia.templateField.climate": "Climate",
  "encyclopedia.templateField.weather": "Weather",
  "encyclopedia.templateField.natural-resources": "Natural resources",
  "encyclopedia.templateField.notable-locations": "Notable locations",
  "encyclopedia.templateField.inhabitans": "Inhabitans",
  "encyclopedia.templateField.looks": "Looks",
  "encyclopedia.templateField.production": "Production",
  "encyclopedia.templateField.use": "Use",
  "encyclopedia.templateField.related": "Related",
  "encyclopedia.templateField.location": "Location",
  "encyclopedia.templateField.significance": "Significance",
  "encyclopedia.templateField.associated-events": "Associated events",
  "encyclopedia.templateField.associated-figures": "Associated figures",
  "encyclopedia.templateField.access-restrictions": "Access restrictions",
  "encyclopedia.templateField.cultural-importance": "Cultural importance",
  "encyclopedia.templateField.founded": "Founded",
  "encyclopedia.templateField.government": "Government",
  "encyclopedia.templateField.defenses": "Defenses",
  "encyclopedia.templateField.connected-settlements": "Connected settlements",
  "encyclopedia.templateField.family-motto": "Family Motto",
  "encyclopedia.templateField.founding-date": "Founding Date",
  "encyclopedia.templateField.ethos": "Ethos",
  "encyclopedia.templateField.family-reputation": "Family Reputation",
  "encyclopedia.templateField.family-branches": "Family Branches",
  "encyclopedia.templateField.notable-vassals-retainers": "Notable vassals/retainers",
  "encyclopedia.templateField.skills-required": "Skills required",
  "encyclopedia.templateField.pay-salary": "Pay/Salary",
  "encyclopedia.templateField.associated-locations": "Associated locations",
  "encyclopedia.templateField.associated-characters": "Associated characters",
  "encyclopedia.templateField.propulsion": "Propulsion",
  "encyclopedia.templateField.capacity": "Capacity",
  "encyclopedia.templateField.speed": "Speed",
  "encyclopedia.templateField.manufacturers": "Manufacturers",
  "encyclopedia.templateField.symptoms": "Symptoms",
  "encyclopedia.templateField.causes": "Causes",
  "encyclopedia.templateField.treatment": "Treatment",
  "encyclopedia.templateField.affected-species": "Affected species",
  "encyclopedia.templateField.associated-groups": "Associated groups",
  "encyclopedia.templateField.ingredients": "Ingredients",
  "encyclopedia.templateField.preparation": "Preparation",
  "encyclopedia.templateField.rules": "Rules",
  "encyclopedia.templateField.equipment": "Equipment",
  "encyclopedia.templateField.venues": "Venues",
  "encyclopedia.templateField.architecture": "Architecture",
  "encyclopedia.templateField.curriculum": "Curriculum",
  "encyclopedia.templateField.notable-alumni": "Notable alumni",
  "encyclopedia.templateField.affiliation": "Affiliation",
  "encyclopedia.templateField.language": "ഭാഷ",
}
