export default {
  'courses.courses': 'Courses',
  'courses.overview': 'Kurssien yleiskatsaus',
  'course.create': 'Luo uusi kurssi',
  'course.reading.title': 'Reading assignment title',
  'course.question.add': 'Add question',
  'course.add.courseElement': 'Add a new course element',
  'course.lessons.newMessage': 'Create and organize your lessons for effective teaching',
  'course.reading.new': 'Reading Assignment',
  'course.reading.newMessage': 'Create and organize reading assignments for your students',
  'course.writing.new': 'Kirjoitustehtävä',
  'course.writing.newMessage': 'Quickly set up and distribute writing tasks',
  'course.question.text': 'Kysymyksesi tähän',
  'course.question.type': 'Please select a type of question',
  'course.question.delete': 'Remove question',
  'course.type': 'Valitse kurssin tyyppi',
  'course.visibility': 'Valitse näkyvyysasetus',
  'course.title': 'Otsikko',
  'course.description': 'Kuvaus',
  'course.cover': 'Kansi',
  'course.start': 'Kurssisi alkaa',
  'course.ends': 'Kurssisi päättyy',
  'course.curriculum': 'Opetussuunnitelma',
  'course.members': 'Opiskelijat & opettajat',
  'course.assignments': 'Assignments',
  'course.question.deleteWhole': 'Poista koko kysymys',
  'course.question.yes': 'Kyllä',
  'course.question.no': 'Ei',
  'course.lesson.title': 'Oppitunnin otsikko',
  'course.lesson.add.universe': 'Lisää tarina/maailma',
  'course.lesson.add.link': 'Lisää ulkoinen linkki',
  'course.status': 'Status',
  'course.active': 'Activity',
  'course.active.message': 'Active',
  'course.inactive': 'Inactive',
  'course.module.edit': 'Edit module name',
  'course.upload.resource': 'Upload a file resource',
  'course.question.answer': 'Add answer',
  'course.question.open': 'Open question',
  'course.question.close': 'Closed question',
  'course.question.multiple': 'Multiple-choice question',
  'course.about': 'About this course',
  'course.lesson.new': 'Create a new lesson',
  'course.lesson.type': 'Lesson type',
  'course.lesson.inPerson': 'In person',
  'course.lesson.preRecorded': 'Pre-recorded',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Text only',
  'course.lesson.content': 'Lesson content',
  'course.lesson.description': 'Public description',
};
