export default {
    'groups.listing.title': 'Käyttäjäryhmät',
    'groups.listing.organizationTitle': 'Tiimit',
    'groups.create.title': 'Luo uusi ryhmä',
    'groups.type.label': 'Tyyppi',
    'groups.type.open': 'Avaa',
    'groups.type.openDesc': 'Avoin - Kuka tahansa voi liittyä ryhmään.',
    'groups.type.closed': 'Suljettu',
    'groups.type.closedDesc': 'Suljettu - Ihmisten on hyväksyttävä liittyminen ryhmään.',
    'groups.type.hidden': 'Piilotettu',
    'groups.type.hiddenDesc': 'Piilotettu - Vain kutsutut voivat liittyä.',
    'groups.imageAlt': '{groupName} kuva',
    'groups.members': 'Jäsenet',
    'groups.members.total': `There {totalMembers, plural,
    zero {are no members}
    one {is one member}
    other {are # members}
  } in this group`,
    'groups.leaveGroup': 'Poistu ryhmästä',
    'groups.leaveGroup.confirm': 'Varmista. Oletko varma, että haluat poistua ryhmästä {groupName}?',
    'group.settings': 'Ryhmän asetukset',
    'group.role.member': 'Jäsen',
    'group.role.moderator': 'Moderaattori',
    'group.role.admin': 'Ylläpitäjä',
    'groups.join.openGroup': 'Liity ryhmään',
    'groups.join.closedGroup': 'Pyydä liittyä ryhmään',
    'groups.join.questionToJoin': 'Kysymys uusille jäsenille',
    'groups.join.closedAria': 'Lomake pyytää liittymistä suljettuun ryhmään',
    'groups.join.questionDefault': 'Miksi sinun pitäisi saada liittyä?',
    'groups.join.pendingRequest': 'Pyyntösi liittyä tähän ryhmään odottaa hyväksyntää ryhmän ylläpitäjiltä.',
    'groups.join.requesting': 'Pyydetään liittymään',
    'groups.invite.btn': 'Kutsu ryhmään',
    'groups.invite.modalAria': 'Kutsu käyttäjiä ryhmäkeskusteluun',
    'groups.invite.send': 'Lähetä kutsu',
    'groups.invite.label': 'Etsi käyttäjä kutsuttavaksi',
    'groups.invite.tileMsg': `Sinulla on {count, plural,
    other {# ryhmäkutsua}
  }`,
    'groups.invites.title': 'Ryhmäkutsut',
    'group.invite.accept': 'Hyväksy kutsu',
    'group.noticeBoard': 'Ilmoitustaulu'
};