export default {
    'reader.storyEnd.heading': 'LOPPU',
    'reader.storyEnd.description': 'Olet saapunut tarinan loppuun.',
    'reader.externalSale.heading': 'Ei vielä täällä',
    'reader.externalSale.description': 'Tätä tarinaa ei ole saatavilla Literary Universessa, mutta voit löytää sen muualta.',
    'reader.storyTBC.heading': 'Jatketaan...',
    'reader.storyTBC.description': 'Tämä on kaikki mitä tällä hetkellä on tarinasta, mutta seikkailu jatkuu tulevaisuudessa. Tarkista uudelleen pian!',
    'chapter.translation.notYetDescription': 'Tarkista uudelleen pian!',
    'reader.externalShopping.heading': 'Osta {storyName} kaupoista:',
    'chapter.next': 'Seuraava luku',
    'chapter.previous': 'Edellinen luku',
    'chapter.comment': 'Kommentit tähän lukuun',
    'reader.language': 'Kieli:',
    'reader.fullscreen.enter': 'Mene koko näytölle',
    'reader.fullscreen.exit': 'Poistu koko näytön tilasta',
    'reader.details.universe': 'Yksityiskohdat universumista',
    'reader.details.story': 'Tarinan yksityiskohdat',
    'reader.darkmode': 'Vaihda tumma tila',
    'reader.flowtext': 'Vaihda tekstin kokoa',
    'reader.menu.optionsAria': 'Lukijan asetukset valikko',
    'reader.accessibility': 'Vaihda saavutettavuutta',
    'chapter.translation.notYet': 'Tämä luku ei ole vielä käännetty.',
    'externalShopping.buyLink.amazon': 'Osta Amazonista',
    'externalShopping.buyLink.other': 'Osta {storeName}',
    'externalShopping.buyLink.bookshop': 'Osta Bookshop.orgista',
    'reader.accessibility.aria': 'Saavutettavuusasetukset',
    'reader.accessibility.toggleDyslexic': 'Vaihda dyslektistä fonttia',
    'reader.accessibility.toggleParagraphStripes': 'Vaihda kappaleiden taustan muokkausta',
    'reader.accessibility.toggleParagraphHighlight': 'Vaihda valitun kappaleen korostusta',
    'reader.accessibility.toggleRules': 'Vaihda avustavaa viivoitinta',
    'reader.nextRelease.scheduled': 'Seuraava luku saapuu {nextReleaseAt, date} {nextReleaseAt, time}!',
    'reader.storyContinues': 'Tarina jatkuu...',
    'reader.storyOnHiatus': 'Kirjailija pitää tällä hetkellä taukoa tästä tarinasta, ja tarina on toistaiseksi tauolla. Tarkista uudelleen kuukauden tai kahden kuluttua.',
    'reader.storyCancelled': 'Valitettavasti tämä on kaikki. Tarina on peruutettu, joten uutta sisältöä ei todennäköisesti tule.',
    'reader.storyCancelled.heading': 'Peruutettu',
    'reader.nextChapterEstimation.verySoon': 'Based on the publication dates of the last {chaptersCount, number} chapters, the next chapter is expected to be released very soon.',
    'reader.nextChapterEstimation.days': 'Based on the publication dates of the last {chaptersCount, number} chapters, the next chapter should be available in approximately {daysLeft, plural, one {1 day} other {# days}}.',
    'reader.nextChapterEstimation.notEnoughChapters': 'Kun tarinalla on enemmän kuin yksi luku, annamme myös arvion siitä, milloin seuraava luku saattaisi ilmestyä.'
};