export default {
    'feedback.home': 'Tulong na sentro',
    'feedback.bugs': 'Mga Isyu',
    'feedback.bugs.desc': 'Nakaranas ka ba ng error o ibang bagay na mali o hindi nasa tamang lugar. Sabihin mo sa amin dito!',
    'feedback.features': 'Mga Ideya at Mungkahi',
    'feedback.features.desc': 'May mga ideya ka ba para sa mga bagong feature o para mas mapaganda ang site? Sabihin mo sa amin!',
    'feedback.help': 'Tulong at Mga Tutorial',
    'feedback.help.desc': 'Paano mo ginagamit ang _____? Pumunta dito para makahanap ng mga sagot.',
    'feedback.desc': 'Maligayang pagdating sa aming sentro ng tulong at resolusyon!',
    'feedback.faq': 'Mga Madalas Itanong',
    'feedback.faq.desc': 'Madalas Itanong',
    'feedback.open': 'Buksan',
    'feedback.closed': 'Isara',
    'feedback.accepted': 'Tinanggap',
    'feedback.inprogress': 'Nasa progreso',
    'feedback.completed': 'Natapos',
    'feedback.fixed': 'Naayos',
    'feedback.new.bugs': 'Iulat ang bagong isyu',
    'feedback.new.features': 'Magmungkahi ng bagong feature',
    'feedback.lang.nosupport': 'Hindi suportado ang iyong kasalukuyang wika para sa feedback, magpakasulatan sa Ingles. Salamat!',
    'feedback.new.thanks': 'Salamat sa abiso! Ating titingnan ito nang maaga.',
    'feedback.comment.title': 'Komento',
    'feedback.comment.desc': 'Ipadala ang iyong feedback',
    'feedback.comment.legend': 'Iyong feedback - sabihin mo sa amin tungkol sa anumang bagay',
    'feedback.comment.success': 'Salamat sa iyong feedback!',
    'feedback.comment.label': 'Iyong komento',
    'feedback.copyrightReport.title': 'Paglabag sa karapatan sa pag-aaring intelektwal',
    'feedback.copyrightReport.desc': 'Iulat ang Paglabag sa Karapatan sa Pag-aaring Intelektwal',
    'feedback.report.noUser': 'Kailangan mong mag-sign in upang mag-file ng ulat.',
    'feedback.voting.totalVoters': 'Mga bumoto na mga user: {voted, number}',
    'feedback.voting.upvote': 'Up vote',
    'feedback.voting.downvote': 'Down vote',
    'feedback.voting.score': 'Kabuuang score',
    'feedback.report.title': 'Ulat ng Nilalaman',
    'feedback.report.typeSelect': 'Ano ang problema dito?',
    'feedback.reportType.law': 'Paglabag sa Batas',
    'feedback.reportType.vulgar': 'Bastos/malaswa',
    'feedback.reportType.copyright': 'Paglabag sa Karapatan ng Pag-aaring Intelektwal',
    'feedback.reportType.storyRating': 'Maling rating sa edad',
    'feedback.reportType.scam': 'Panloloko',
    'feedback.report.submit': 'Iulat',
    'feedback.report.submitting': 'Nagre-report...',
    'feedback.report.violationDesc': 'Mga Detalye',
    'feedback.report.reportSaved': 'Salamat sa pagre-report! Iimbestigahan namin at gagawa ng aksyon kung kinakailangan.',
    'feedback.report.copyrightReportSaved': 'Salamat sa pagre-report! Iimbestigahan namin at makikipag-ugnayan.',
    'feedback.report.copyrightOwnershipDesc': 'Pahayag ng pagmamay-ari',
    'feedback.report.copyrightNotice': 'Pakitandaan na kailangan mong maging tunay na may-ari ng gawain upang magamit ang form na ito. Kung hindi ka ang may-ari, mangyaring ipaalam sa may-ari o gamitin ang ibang kategorya upang ipaalam sa amin. Kami ay labis na seryoso sa mga paglabag sa karapatan ng may-ari ng copyright at pareho rin ito sa maling at abusadong paggamit ng form na ito.',
    'feedback.report.copyrightInternalProperty': 'Inilathala ko ang gawain na ito sa Literary Universe',
    'feedback.reportType.spam': 'Spam o phishing',
    'feedback.reportType.soliciting': 'Soliciting',
    'feedback.reportType.aiUnmarked': 'Unmarked AI-generated content',
    'feedback.reportType.other': 'Iba Pa',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`,
    'feedback.help.overview': 'Overview',
    'feedback.help.articles': 'Articles',
    'feedback.help.courses': 'Courses',
    'feedback.help.videos': 'Video tutorials',
    'feedback.help.featuredArticles': 'Featured Articles',
    'feedback.help.featuredCourses': 'Featured Courses',
    'feedback.help.featuredVideos': 'Featured Videos',
    'feedback.help.subCategories': 'Sub-categories'
};