export default {
  'forum.thread.reply': 'Magdagdag ng tugon sa talakayang ito',
  'forums.archive': 'I-archive ang forum',
  'forums.archive.explained': 'Ang pagsasara ng forum ay magpapigil sa mga gumagamit na mag-post ng anumang karagdagang nilalaman, ngunit mananatiling nakikita ito.',
  'forums.archive.success': 'Ang forum ay na-archives na',
  'forums.archived.forum': 'Ang forums na ito ay na-archives sa {archivedAt, date, long}. Maaari ka pa ring tingnan ang mga forums, ngunit hindi ka na makakagawa ng bagong nilalaman.',
  'forums.category.archive': 'I-archive ang kategorya',
  'forums.category.archiveExplained': 'Ang kategoryang walang mga thread ay mabubura, samantalang ang mga kategoryang may laman ay magpapigil sa paglikha ng bagong mga thread.',
  'forums.category.back': 'Bumalik sa pangkalahatang-ideya ng forum',
  'forums.category.create': 'Lumikha ng kategorya ng forum',
  'forums.category.delete': 'Tanggalin ang kategorya',
  'forums.category.intlName.announcements': 'Mga Anunsyo',
  'forums.category.intlName.art': 'Sining',
  'forums.category.intlName.characters': 'Mga Tauhan',
  'forums.category.intlName.community': 'Komunidad',
  // Pre-defined category names
  'forums.category.intlName.general': 'Pangkalahatan',
  'forums.category.intlName.help': 'Tulong',
  'forums.category.intlName.history': 'Kasaysayan',
  'forums.category.intlName.inspiration': 'Inspirasyon',
  'forums.category.intlName.locations': 'Mga Lokasyon',
  'forums.category.intlName.meetups': 'Mga Pagtitipon',
  'forums.category.intlName.news': 'Balita',
  'forums.category.intlName.questions': 'Mga Tanong',
  'forums.category.intlName.stories': 'Mga Kuwento',
  'forums.category.intlName.universe': 'Uniberso',
  'forums.category.intlName.universes': 'Mga Uniberso',
  'forums.category.intlNameDescription': 'May mga lokal na pamagat ng pangkaraniwang mga pangalan ng kategorya para sa iyong pagpili, upang ang kategorya ay magamit sa lahat ng suportadong wika.',
  'forums.category.isVotable': 'Payagan ang mga user na bumoto pataas/pababa sa mga thread',
  'forums.category.language': 'Limitahan ang pagpapakita ng kategoryang ito sa sumusunod na wika. Iwanan bilang walang laman kung nais mong ipakita ang kategorya sa lahat ng wika.',
  'forums.category.languageLimited': 'Ang kategoryang ito ay ipapakita lamang sa mga user sa wikang ito.',
  'forums.category.name': 'Pangalan ng kategorya',
  'forums.category.reactivate': 'I-re-activate ang kategorya',
  'forums.category.settings': 'Mga setting ng kategorya',
  'forums.category.slug': 'Bahagi ng SEO URL',
  'forums.category.titleIsGlobal': 'Ang pamagat ng kategoryang ito ay ipapakita sa wika ng user kung suportado natin ito.',
  'forums.create': 'Paganahin ang forum',
  'forums.createQuestionLabel': 'Ito ba ay tanong?',
  // Threads
  'forums.createThread': 'Lumikha ng bagong talakayan',
  'forums.createThreadIn': 'Lumikha ng bagong talakayan sa {categoryName}',
  // Forum restrictions
  'forums.forumRestriction.usersOnly': 'Pahintulutan lamang ang pag-access ng mga naka-rehistrong user',
  'forums.forumRestrictionsMessages.usersOnlyForum': 'Ang forum na ito ay ma-access lamang ng mga rehistradong gumagamit.',
  'forums.noPosts': 'Walang sumagot pa. Ikaw na ang unang sumagot!',
  'forums.noThreads': 'Walang makikita dito. Nasa iyo na ang desisyon kung mag-uumpisa ka ng pag-uusap.',
  'forums.openingPost': 'Pagsisimula ng talakayan',
  'forums.post': 'I-post',
  'forums.post.new': 'Bagong post',
  'forums.posting': 'Nagpo-post...',
  'forums.reply': 'Tumugon',
  'forums.reset': 'I-reset',
  'forums.settings': 'Mga setting ng forum',
  'forums.settings.accessControls': 'Mga kontrol sa pag-access',
  'forums.thread.createdAt': 'Nilikha noong {createdAt, date, medium}',
  'forums.thread.delete': 'Tanggalin ang thread',
  'forums.thread.new': 'Bagong thread',
  'forums.thread.noReplies': 'Walang mga sagot dito sa ngayon.',
  'forums.thread.replyPosted': 'Naipaskil na ang iyong mensahe',
  'forums.thread.totalPosts': `{totalReplies, number} {totalReplies, plural,
    one {tugon}
    other {mga tugon}
  }`,
  'forums.threadsCounter': 'Kabuuang bilang ng mga paksa at talakayan',
  'forums.unArchive': 'I-re-activate ang mga forum',
  'forums.unArchive.success': 'Ang forum ay na-re-activate na!',
  'forums.universeTitle': 'Universe forums for {universeName}',
  'forums.yourMessage': 'Iyong mensahe'
};