export default {
    'plans.desc': 'Paglalarawan ng mga plano at mga tampok ng Literary Universe.',
    'plans.title': 'Magkaroon ng mas marami sa Literary Universe!',
    'plans.text': 'Ang Literary Universe ay nag-aalok ng mga batayang kakayahan nang libre. Kung ikaw ay isang masugid na mambabasa o isang lumikha, maaaring mas gusto mo ang aming advanced membership.',
    'plans.faq.basicsPriced': 'Bakit ang libreng membership ay may kaunting mga bagay lamang?',
    'plans.faq.justification': 'Dito sa Literary Universe, pinahahalagahan namin ang iyong privacy at intellectual property. Kaya hindi namin ginagamit ang iyong data upang magbenta ng mga advertisements o ibigay ito sa ibang mga kumpanya. Ibig sabihin nito, kailangan naming magtayo ng maraming bagay sa sarili namin. Ito ay nangangailangan ng maraming oras at gastos upang mapatakbo. Kaya itinatag namin ang libreng membership bilang isang maliit na preview ng Literary Universe (na nagbibigay pa rin sa iyo ng mga pinakamahalagang bagay) na may iba\'t ibang membership tiers at addons upang matugunan ang mga pangangailangan ng lahat habang patuloy naming pinapanatili ang serbisyo at pagpapaunlad. Kung nagustuhan mo ang aming ginagawa, mangyaring isaalang-alang ang pag-sign up sa isa sa mga bayad na pagpipilian. Salamat!',
    'plans.limits': 'Mga Limitasyon',
    'plans.features': 'Mga Tampok',
    'plans.account.user': 'Bisita',
    'plans.account.user.desc': 'Simulang pagsubok na account, upang subukan ang mga bagay.',
    'plans.account.explorer': 'Mananaliksik',
    'plans.account.explorer.desc': 'Para sa mga hobista at mga kaibigan.',
    'plans.account.adventurer': 'Manlalakbay',
    'plans.account.adventurer.desc': 'Para sa mga lumilikha at sa aming mga tagasuporta.',
    'plans.account.storyteller': 'Kuwentista',
    'plans.account.storyteller.desc': 'Para sa pinakamahusay na malikhain at dedikado.',
    'plans.unlimited': 'Walang Hanggan',
    'plans.price': 'Presyo',
    'plans.price.free': 'LIBRE',
    'plans.price.monthly': 'isang buwan*',
    'plans.price.annually': 'taun-taon*',
    'plans.price.perMonth': '{price} / buwan*',
    'plans.price.perYear': '{price} / taon*',
    'plans.development': 'Nasa pagpapaunlad',
    'plans.limits.encEntries': 'Mga entry sa ensiklopedya',
    'plans.limits.maxCollaborators': 'Mga kasamahan sa bawat proyekto',
    'plans.limits.pmChats': 'Pinakamataas na bilang ng tatanggap para sa pribadong mensahe',
    'plans.feature.creative': 'Lumikha ng kamangha-manghang mga universe at mga kuwento',
    'plans.feature.encCustomFields': 'Mga pasadyang patlang sa isang entry ng ensiklopedya',
    'plans.feature.encAdvCategories': 'Mas maraming kategorya ng ensiklopedya',
    'plans.feature.scratchpad': 'Scratchpad',
    'plans.feature.library': 'Aklatan',
    'plans.feature.blog': 'Personal at mga blog ng universe',
    'plans.feature.customBlogTheme': 'Mga pasadyang tema ng blog',
    'plans.feature.advanceStats': 'Mga abanteng estadistika',
    'plans.feature.challenges': 'Mga hamon sa pagsusulat',
    'plans.feature.newFeaturesVote': 'Bumoto sa mga bagong tampok',
    'plans.feature.newFeaturesSuggest': 'Magmungkahi ng mga bagong tampok',
    'plans.feature.accessToBeta': 'Access sa mga Beta na tampok',
    'plans.feature.userGroups': 'Mga grupo ng mga gumagamit',
    'plans.feature.privateUserGroups': 'Lumikha ng pribadong at nakatagong mga grupo ng mga user',
    'plans.feature.internalUniverseForums': 'Internal forum para sa mga universe',
    'plans.feature.fictionalTime': 'Pantasya na oras',
    'plans.feature.forums': 'Mga forum sa mga blog at mga pahina ng universe',
    'plans.feature.timelines': 'Mga timeline ng universe',
    'plans.feature.webMonetization': 'Web Monetization',
    'plans.feature.storyMonetization': 'Pagpapakabuhay ng kuwento',
    'plans.feature.fanClub': 'Fan Club',
    'plans.feature.translations': 'Kakayahan sa pagsasalin',
    'plans.feature.fanFiction': 'Magsulat at pamahalaan ang fan fiction',
    'plans.feature.universeFanArt': 'Pamamahala ng fan art',
    'plans.feature.overviewNotes': 'Mga tala sa pangkalahatang-ideya ng kuwento',
    'plans.feature.personalNotesStoriesUniverses': 'Personal na mga tala sa mga kuwento at mga universe',
    'plans.feature.storyReviews': 'Mga pagsusuri ng kuwento',
    'plans.feature.readingLists': 'Mga listahan ng pagbasa',
    'plans.feature.scenesManager': 'Pamamahala ng mga eksena',
    'plans.feature.glossaries': 'Mga talahuluganan sa pagsasalin',
    'plans.feature.chatSupport': 'Suporta sa Chat',
    'plans.currency.select': 'Pumili ng currency',
    'plans.subscription.ownAlready': 'Nasa iyo na ang plan na ito',
    'plans.subscription.title': 'Subscription',
    'plans.see': 'Tingnan ang mga available na subscription plans',
    'plans.current.none': 'Sa ngayon, hindi mo sinusuportahan ang Literary Universe.',
    'plans.current.buying': 'Maaaring tumagal ng ilang sandali upang i-verify ang iyong pagbili. Lubos naming pinahahalagahan ang iyong pasensya.',
    'plans.current.heading': 'Kasalukuyang subscription plan',
    'payment.methods.title': 'Mga Bayad at Pagpapakakitaan',
    'payment.methods.tabs': 'Mga pagpipilian sa pagbabayad',
    'payment.option.title': 'Pagpipilian sa pagbabayad',
    'payment.option.notFount': 'Wala kang anumang nakasimpan na pagpipilian sa pagbabayad.',
    'payment.option.create': 'Magdagdag ng bagong pagpipilian sa pagbabayad',
    'payment.option.description': 'Narito ang listahan ng iyong mga na-save na paraan ng pagbabayad. Maaari kang magdagdag ng mga bagong paraan ng pagbabayad dito para mas mabilis na mag-checkout. Ang Literary Universe ay hindi nag-iimbak o nagpo-proseso ng iyong mga detalye sa pagbabayad tulad ng credit card number.',
    'payment.history.title': 'Kasaysayan ng pagbabayad',
    'payment.history.tab': 'Kasaysayan',
    'payment.history.none': 'Wala kaming anumang tala ng mga nakaraang pagbabayad.',
    'plans.options.aria': 'Mga pagpipilian sa pagbabayad',
    'plans.options.creditCard': 'Credit Card',
    'plans.options.creditCardNew': 'Bagong Credit Card',
    'plans.options.existingCards': 'Nakaimbak na mga Credit Card',
    'plans.purchase.action': 'Mag-subscribe',
    'plans.purchase.title': 'Bumili ng Literary Universe subscription',
    'payment.creditCard.details': 'Mga detalye ng Credit Card',
    'payments.zipcode.label': 'ZIP code',
    'payment.card.name': 'Pangalan sa card',
    'plans.subscribed.thankYou': 'Salamat sa pagsuporta sa Literary Universe',
    'plans.subscribed.periodEnd': 'Ang iyong subscription ay balido hanggang: {end, date, medium}',
    'plans.subscribed.renewal': `Sa katapusan, ang iyong subscription ay magiging {method, select,
    charge_automatically {renewed automatically}
    send_invoice {renewed after paying an invoice}
    other {}
  }.`,
    'plans.subscribed.paymentMethod': 'Ang iyong default na paraan ng pagbabayad ay gagamitin para sa susunod na siklo.',
    'plans.subscribed.status': `Katayuan ng subscription: {status, select,
    active {Aktibo}
    incomplete {May nawawalang bagay}
    incomplete_expired {May nawawalang bagay}
    trialing {Pagsusubok}
    past_due {Nawawala ang iyong pagbabayad}
    cancelled {Kinansela}
    unpaid {Hindi nabayaran}
    expired {Nag-expire}
    other {}
  }`,
    'payments.changeMethod': 'Baguhin ang paraan ng pagbabayad',
    'plans.subscribed.willNotRenew': ', hindi irerenew sa katapusan ng siklo.',
    'plans.cancel.button': 'I-cancel ang subscription',
    'plans.cancel.question': 'Sigurado ka bang gusto mong kanselahin ang iyong subscription? Ang iyong subscription ay mananatiling aktibo hanggang sa katapusan ng billing cycle.',
    'plans.cancel.confirmationButton': 'Oo, gusto kong kanselahin ang aking subscription',
    'plans.cancel.failed': 'Paumanhin, hindi namin magawang kanselahin ang iyong plano sa ngayon. Subukan muli mamaya.',
    'plans.cancel.restoreBtn': 'Ibalik ang subscription',
    'plans.cancel.restoreFailed': 'Paumanhin, hindi namin magawang ibalik ang subscription sa ngayon. Subukan muli mamaya.',
    'plans.change.button': 'Baguhin ang subscription',
    'plans.change.explanation': 'Pumili ng plano na nais mong i-upgrade o i-downgrade. Ikaw ay babayaran ng agad ang pagkakaiba sa presyo.',
    'plans.change.failed': 'Paumanhin, hindi namin magawang baguhin ang iyong plano sa ngayon. Subukan muli mamaya.',
    'plans.change.upgrade': 'Mag-upgrade',
    'payments.disclaimer': 'Ang impormasyon at pagproseso ng pagbabayad ay ginagawa sa pamamagitan ng Stripe. Hindi namin iniimbak ang anumang impormasyon ng credit card o bank account sa aming mga server.',
    'buy.payment.optionsSelect': 'Pumili ng paraan ng pagbabayad',
    'payments.card.number': 'Numero ng card',
    'payments.card.expire': 'Valid Thru',
    'payments.card.cvv': 'CVV',
    'payments.card.info': '{cardType} card, nagtatapos sa {ending}',
    'payments.none': 'Walang mga saved na pagpipilian sa pagbabayad ang natagpuan.',
    'payments.none.cards': 'Walang mga card na natagpuan.',
    'payments.added': 'Ang bagong pagpipilian sa pagbabayad ay matagumpay na idinagdag.',
    'payments.delete.confirm': 'Sigurado ka bang gusto mong tanggalin ang {cardType}, na nagtatapos sa {ending}?',
    'payment.invoice.status': 'Katayuan ng invoice',
    'payment.invoice.statusMessage': `{status, select,
    draft {Draft}
    open {Open}
    paid {Paid}
    uncollectible {Uncollectible}
    void {Void}
    other {}
  }`,
    'payment.invoice.id': 'ID ng invoice',
    'payment.invoice.pdf': 'PDF ng invoice',
    'payment.invoice.total': 'Kabuuan',
    'payment.invoice.what': 'Paglalarawan ng invoice',
    'payment.stripe.powered': 'Powered by ',
    'payment.listMethods.card': 'Mga Card',
    'payment.expiresAt': 'Magwawakas sa {month}/{year}',
    'payment.card.details': `{type, select,
    credit {Credit card}
    debit {Debit card}
    other {Card}
  } na nagtatapos sa {last4}`,
    'payment.options.default': 'Default',
    'payment.method.add': 'Magdagdag ng bagong paraan ng pagbabayad',
    'payment.methods.adding': 'Ang iyong bagong paraan ng pagbabayad ay idinagdag sa iyong account.',
    'payment.methods.delete': 'Tanggalin ang paraan ng pagbabayad',
    'payment.upgradePlan.option': '{plan} - {price}',
    'payment.methods.webMonetization': 'Web Monetization',
    'settings.webMonetization.placeholder': 'Ang iyong payment pointer',
    'payment.webMonetization.explained': 'Ang Web Monetization ay isang inirerekomendang pamantayan para sa mga pagbabayad sa web. Dito ay maaari mong idagdag ang iyong payment pointer na magagamit sa iyong profile page, blog, universes at mga kuwento.',
    'payment.webMonetization.learnMore': 'Alamin ang karagdagang impormasyon tungkol sa Web Monetization',
    'plans.subscription.settingsAria': 'Mga pagpipilian sa mga setting ng subscription',
    'plans.buttonStatus.submitting': 'Nagpapasa ng iyong kahilingan...',
    'plans.button.manageOnStripe': 'Pamahalaan ang Pagbabayad sa Stripe',
    'plans.call.signUpBottom': 'Mag-sign up para sa libreng account sa Literary Universe at magsimulang lumikha!',
    'plans.button.seeComparison': 'Alamin ang iba pang tungkol sa mga plano at presyo sa aming pahina ng paghahambing!',
    'plans.button.chooseThisSubscription': 'Pumili ng plan na ito',
    'plans.button.chooseFree': 'Magsimula ng libre',
    'plans.features.allInPreviousTiers': 'Lahat ng nasa nakaraang antas',
    'plan.button.chooseNow': 'Piliin ang iyong Literary Universe plan ngayon',
    'plans.subscription.manage': 'Pamahalaan ang subscription',
    'plans.taxMayApply': '* Maaaring mag-apply ang VAT at iba pang lokal na buwis',
    'plans.faq.crypto': 'Mag-aalok ka ba ng mga pagbabayad sa crypto?',
    'plans.faq.cryptoAnswer': 'Oo, kami ay nagtatrabaho dito. Kami ay malalaking tagahanga ng Web3 at hinahanap namin ang mga paraan upang maisama ang Web3 sa platform sa malapit na hinaharap. Sa kasalukuyan, pinapayagan namin ang login gamit ang Web3 at hinahanap namin na palawakin ang alok na ito lalo na pagdating sa pagbibigay ng kabayaran sa mga lumikha at pagbibigay sa mga lumikha ng kakayahang pumili ng lahat ng posibleng mga pagpipilian sa pagbabayad na nais nilang tanggapin.',
    'plans.subscribed.updating': 'Maaaring tumagal ng kaunting oras upang i-update ang impormasyon ng iyong subscription. Salamat sa iyong pasensya!',
    'payments.methods.webMonetization': 'Web Monetization',
    'stripeConnect.settings.title': 'Mga Setting ng Pagpapalabas',
    'stripeConnect.settings.intro': 'Kung nais mong tumanggap ng pondo o magbenta sa pamamagitan ng Literary Universe, kailangan mong lumikha ng Stripe account sa pamamagitan ng pindutan sa ibaba.',
    'stripeConnect.settings.connectAccount': 'Itakda ang Stripe Account',
    'stripeConnect.settings.ongoing': 'Naghihintay kami ng tugon mula sa Stripe tungkol sa iyong account. Maaaring tumagal ito ng kaunti. Kung masyadong matagal na ito, mag-click sa pindutan sa ibaba na magdadala sa iyo pabalik sa Stripe.',
    'stripeConnect.settings.finished': 'Handa ka nang tumanggap ng pera sa pamamagitan ng Stripe Connect.',
    'stripeConnect.settings.balance': 'Balanseng Pera',
    'stripeConnect.settings.balanceAvailable': 'Magagamit na balanse',
    'stripeConnect.settings.balancePending': 'Nakabinbin na balanse',
    'stripeConnect.settings.recentTransfers': 'Mga Kamakailang Pagsasalin',
    'stripeConnect.transfers.amount': 'Halaga',
    'stripeConnect.transfers.reason': 'Dahilan',
    'payment.settings.donations': 'Mga Setting ng Donasyon',
    'plans.fanClub.heading': 'Mga Fan Club',
    'payment.donations.enable': 'Paganahin ang mga donasyon',
    'payment.donations.suggestedAmount': 'Inirerekomendang halaga',
    'payment.donations.amount': 'Halaga',
    'payment.donations.preferredCurrency': 'Preferensyal na pera',
    'payment.donations.currency': 'Pera',
    'payment.donations.stripeDescription': 'Donasyon kay {username}',
    'payment.donations.support': 'Suporta kay {username}',
    'payment.donations.donate': 'Mag-donate',
    'payment.donations.donationModal': 'Kumpirmasyon ng donasyon',
    'payment.donations.payNowUSD': 'Mag-donate ng {donation, number, ::compact-short currency/USD} kay {username}',
    'payment.donations.payNowJPY': 'Mag-donate ng {donation, number, ::compact-short currency/JPY} kay {username}',
    'payment.donations.payNowEUR': 'Mag-donate ng {donation, number, ::compact-short currency/EUR} kay {username}',
    'payment.donations.payNowCZK': 'Mag-donate ng {donation, number, ::compact-short currency/CZK} kay {username}',
    'payment.donations.payNowGBP': 'Mag-donate ng {donation, number, ::compact-short currency/GBP} kay {username}',
    'payment.donations.thankYouTitle': 'Salamat sa iyong donasyon kay {username}',
    'payment.donations.thankYouContinue': 'Salamat sa suporta mo kay {username}, umaasa kami na patuloy mong i-enjoy ang kanilang trabaho at isaalang-alang na suportahan sila muli sa hinaharap.',
    'payment.success': 'Tagumpay ang pagbabayad!',
    'payment.processing': 'Ang iyong pagbabayad ay inaayos.',
    'payment.failed': 'Ang iyong pagbabayad ay hindi successful, subukan muli.',
    'payment.generalError': 'May nangyaring hindi maganda.',
    'payment.unexpectedError': 'May nangyaring hindi maganda.',
    'payments.transferType.donation': 'Donasyon',
    'payment.donation.backToProfile': 'Bumalik sa profile ni {username}',
    'payment.author.requirementStripeConnect': 'Bago natin maiproseso ang anumang mga transaksiyon sa pera, kailangan mong lumikha at kumonekta ng iyong Stripe Connect account.',
    'payment.author.requirementPublishWork': 'Bago ka magpatuloy, mangyaring mag-publish ng hindi bababa sa isang gawa (kwento o universe).',
    'payment.author.createWork': 'Lumikha ng bagong gawa',
    'payment.author.directivesTitle': 'Mga Rekomendasyon',
    'payment.author.directivesExplained': 'Mayro kaming ilang karagdagang rekomendasyon na dapat mong matupad bago paganahin ang mga serbisyong pangbayad upang madagdagan ang iyong tsansa sa tagumpay.',
    'payment.author.directivesStoryPublished': 'Mag-publish ng hindi bababa sa isang kwento nang libre upang ipakita ang iyong galing.',
    'payment.author.directivesFreeStoryFinished': 'Tapusin ang hindi bababa sa isang libreng kwento upang ipakita sa iyong mga mambabasa na hindi mo sila iiwan sa gitna ng kanilang paglalakbay.',
    'payment.universe.directivesUniversePublished': 'I-publish ang iyong universe',
    'payment.universe.directivesEncFull': 'Punan ang iyong ensiklopedya, magkaroon ng hindi bababa sa 30 na mga entry! Mas maganda kung higit sa 100 ang iyong target.',
    'payment.universe.haveFans': 'Mas madali kang makakakuha ng mga taong susuporta sa iyo kung sila ay interesado na sa ginagawa mo. Ang 100 na fans na nagdadagdag ng iyong universe sa kanilang library ang simula.',
    'payment.settings.yourFanClub': 'Ang iyong fan club',
    'payment.settings.newWork': 'Lumikha ng bagong gawa',
    'payment.amount.withNet': `{amount} (net: {netAmount})`,
    'payment.fanClub.intro': 'In this section you can modify your fan club settings. From subscription tiers to history of payments.',
    'payment.fanClub.tiers': 'Tiers',
    'payment.fanClub.tierName': 'Pangalan ng antas',
    'payment.fanClub.createTier': 'Magdagdag ng tier',
    'payment.fanClub.description': 'Deskripsyon ng tier',
    'payment.fanClub.picture': 'Larawan ng tier',
    'payment.fanClub.priceBreakdown': 'Ang Subscriber ay magbabayad ng: {amount}. Ang bayad ng platform ay {fee} ({platformPercentage}), inaasahang bayad mula sa Stripe: {stripeFee} ({stripeBaseFee} base na bayad sa transaksyon + porsyento ng uri ng pagbabayad), makukuha mo (inaasahan): {net}',
    'payment.fanClub.learnStripeFees': 'Matuto ng higit pa tungkol sa mga bayarin ng Stripe.',
    'payment.feeNotice': 'Mangyaring tandaan na ito ay isang tantiya lamang at maaaring magkaiba ang aktuwal na bayad ng Stripe batay sa uri ng pagbabayad ng customer at karagdagang mga bayarin mula sa pay gate.',
    'payment.fanClub.perks': 'Mga Benepisyo',
    'stripeConnect.settings.notifications': 'Mga Abiso mula sa Stripe',
    'plans.pricePerMonth': 'Halaga kada buwan',
    'payment.fanClub.perkType': 'Uri ng benepisyo',
    'payment.fanClub.addPerk': 'Magdagdag ng benepisyo',
    'payment.fanClub.perksExplained': 'Ito ay mga pribilehiyo na awtomatikong ipinagkakaloob sa fan sa pamamagitan ng Literary Universe.',
    'plans.deleteTier.header': 'Sigurado ka bang gusto mong tanggalin ang tier na {tierName}?',
    'plans.deleteTier.explainer': 'Kung ang tier na ito ay walang mga subscribers, ito ay matatanggal. Kung may mga subscribers naman ito, ito ay ide-disable para sa mga bagong subscription, ngunit magpapatuloy ang mga kasalukuyang subscription hanggang sa magbago ang fan ng kanilang subscription.',
    'plans.fanClub.userSettings': 'Pamahalaan ang iyong mga subscription sa fan club',
    'plans.fanClub.subscribers': 'Mga Subskripsyon',
    'plans.fanClub.activatedLabel': 'Napagana ang Fan Club',
    'plans.fanClub.inactiveWarning': 'Ang iyong fan club ay hindi pa naaaktibo, maaari ka pa ring maghanda ng mga plano at kapag handa ka na, maaari mong aaktibahin ito sa mga setting.',
    'payment.fanClub.editTier': 'Edit tier',
    'plans.deletePlan.modalAria': 'Delete plan confirmation',
    'payment.fanClub.paymentDescriptorFull': 'LU - {username} fan club',
    'payment.fanClub.paymentDescriptorShort': 'LU-{username} fan club',
    'payment.fanClub.paymentDescriptorMinimal': '{username} fan club',
    'payment.fanClub.paymentDescriptorBackup': 'LU - author fan club',
    'payment.fanClub.perMonth': '{amount} / per month'
};