export default {
    'reader.storyEnd.heading': 'The END',
    'reader.storyEnd.description': 'You have reached the end of the story.',
    'reader.externalSale.heading': 'Not here yet',
    'reader.externalSale.description': 'This story is not available on Literary Universe, but you can get it in other places.',
    'reader.storyTBC.heading': 'To be continued...',
    'reader.storyTBC.description': 'This is all we have for the story so far, but the adventure will continue in the future, check back soon!',
    'chapter.translation.notYetDescription': 'Check back again soon!',
    'reader.externalShopping.heading': 'Bumili ng {storyName} sa mga tindahan:',
    'chapter.next': 'Next chapter',
    'chapter.previous': 'Previous chapter',
    'chapter.comment': 'Comments on this chapter',
    'reader.language': 'Language:',
    'reader.fullscreen.enter': 'Enter fullscreen',
    'reader.fullscreen.exit': 'Exit fullscreen',
    'reader.details.universe': 'Universe details',
    'reader.details.story': 'Story details',
    'reader.darkmode': 'Toggle dark mode',
    'reader.flowtext': 'Toggle text size',
    'reader.menu.optionsAria': 'Reader options menu',
    'reader.accessibility': 'Toggle accessibility',
    'chapter.translation.notYet': 'This chapter has not yet been translated.',
    'externalShopping.buyLink.amazon': 'Buy on Amazon',
    'externalShopping.buyLink.other': 'Bumili sa {storeName}',
    'externalShopping.buyLink.bookshop': 'Buy on Bookshop.org',
    'reader.accessibility.aria': 'Accessibility options',
    'reader.accessibility.toggleDyslexic': 'Toggle dyslexic font',
    'reader.accessibility.toggleParagraphStripes': 'Toggle paragraphs background alteration',
    'reader.accessibility.toggleParagraphHighlight': 'Toggle selected paragraph highlighting',
    'reader.accessibility.toggleRules': 'Toggle assistive ruler',
    'reader.nextRelease.scheduled': 'Ang susunod na kabanata ay darating sa {nextReleaseAt, date} sa {nextReleaseAt, time}!',
    'reader.storyContinues': 'Ang kwento ay patuloy...',
    'reader.storyOnHiatus': 'Sa kasalukuyan, ang may-akda ay nagpapahinga muna sa kwentong ito at pansamantalang hindi ito maipapagpatuloy. Tignan muli ito pagkatapos ng isang buwan o dalawa.',
    'reader.storyCancelled': 'Sa kasamaang palad, ito na ang wakas. Itinigil na ang kwento kaya malamang wala nang bago dito.',
    'reader.storyCancelled.heading': 'Itinigil',
    'reader.nextChapterEstimation.verySoon': 'Based on the publication dates of the last {chaptersCount, number} chapters, the next chapter is expected to be released very soon.',
    'reader.nextChapterEstimation.days': 'Based on the publication dates of the last {chaptersCount, number} chapters, the next chapter should be available in approximately {daysLeft, plural, one {1 day} other {# days}}.',
    'reader.nextChapterEstimation.notEnoughChapters': 'Magbibigay din kami ng taya kung kailan maaaring mai-publish ang susunod na kabanata kapag mayroon nang higit sa isang kabanata ang kwentong ito.'
};