export default {
  'courses.courses': 'Cursos',
  'courses.overview': 'Vista general de cursos',
  'courses.public.title': 'Explorar cursos',
  'courses.public.heading': 'Explorar cursos',
  'courses.public.filters': 'Filtrar cursos',
  'courses.public.noResults': 'No se han encontrado cursos',
  'courses.public.tryDifferentFilters': 'Pruebe con diferentes términos de búsqueda o filtros',
  'courses.filter.search': 'Buscar cursos...',
  'courses.filter.allTypes': 'Todos los tipos',
  'courses.filter.clearAll': 'Borrar todo',
  'courses.type.course': 'Curso',
  'courses.type.workshop': 'Taller',
  'courses.type.seminar': 'Seminario',
  'courses.type.course.lowercase': 'Curso',
  'courses.type.workshop.lowercase': 'Taller',
  'courses.type.seminar.lowercase': 'Seminario',
  'course.create': 'Comienza un nuevo curso',
  'course.reading.title': 'Título de la tarea de lectura',
  'course.question.add': 'Añadir pregunta',
  'course.add.courseElement': 'Añadir un nuevo elemento de curso',
  'course.lessons.newMessage': 'Cree y organice sus lecciones para una enseñanza eficaz',
  'course.reading.new': 'Tarea de lectura',
  'course.reading.newMessage': 'Cree y organice tareas de lectura para sus alumnos',
  'course.writing.new': 'Tarea de escritura',
  'course.writing.newMessage': 'Establezca y distribuya rápidamente las tareas de escritura',
  'course.question.text': 'Tu pregunta va aquí',
  'course.question.type': 'Seleccione un tipo de pregunta',
  'course.question.delete': 'Eliminar pregunta',
  'course.type': 'Selecciona el tipo de curso',
  'course.visibility': 'Selecciona la opción de visibilidad',
  'course.title': 'Título',
  'course.description': 'Descripción',
  'course.cover': 'Portada',
  'course.start': 'Tu curso comienza el',
  'course.ends': 'Tu curso termina el',
  'course.curriculum': 'Currículum',
  'course.members': 'Estudiantes y profesores',
  'course.assignments': 'Asignaciones',
  'course.question.deleteWhole': 'Eliminar toda la pregunta',
  'course.question.yes': 'Sí',
  'course.question.no': 'No',
  'course.lesson.title': 'Título de la lección',
  'course.lesson.add.universe': 'Agregar Historia/Universo',
  'course.lesson.externalLinks': 'Enlaces externos',
  'course.lesson.add.link': 'Agregar enlace externo',
  'course.status': 'Estado',
  'course.active': 'Actividad',
  'course.active.message': 'Activo',
  'course.inactive': 'Inactivo',
  'course.module.edit': 'Editar el nombre del módulo',
  'course.upload.resource': 'Cargar un recurso',
  'course.question.answer': 'Añadir respuesta',
  'course.question.open': 'Pregunta abierta',
  'course.question.close': 'Pregunta cerrada',
  'course.question.multiple': 'Pregunta tipo test',
  'course.about': 'Sobre este curso',
  'course.lesson.new': 'Crear una nueva lección',
  'course.lesson.type': 'Tipo de lección',
  'course.lesson.inPerson': 'En persona',
  'course.lesson.preRecorded': 'Pregrabado',
  'course.lesson.online': 'En línea',
  'course.lesson.text': 'Sólo texto',
  'course.lesson.content': 'Contenido de la lección',
  'course.lesson.description': 'Descripción pública',
  'course.add.module': 'Añadir nuevo módulo',
  'course.add.story': 'Añadir historia',
  'course.remove.story': 'Eliminar historia',
  'course.dateOfPublish': 'Fecha de publicación',
  'course.lesson.meetInPerson': 'Reunirse en persona',
  'course.curriculum.edit': 'Editar plan de estudios',
  'course.stories.own': 'Sus propias historias',
  'course.stories.organization': 'Historias de organizaciones',
  'course.stories.public': 'Historias públicas',
  'course.publish.at': 'Quiero que este curso se publique en:',
  'course.edit.curriculum': 'Editar plan de estudios',
  'course.assignment': 'Asignación',
  'course.lesson.removeLink': 'Eliminar enlace',
  'course.user.remove': 'Eliminar usuario',
  'course.user.invite': 'Invitar al usuario',
  'course.user.invited': 'Invitado',
  'course.edit.role': 'Editar rol',
  'course.assignment.description': 'Descripción de la tarea',
  'course.internal': 'Interno',
  'course.free': 'Gratis',
  'course.sale': 'Venta',
  'course.announcements': 'Anuncios',
  'course.announcements.full': 'Anuncios de cursos',
  'course.announcements.create': 'Crear un anuncio',
  'course.join': 'Únase al curso',
  'course.firstLesson': 'Primera lección',
  'course.upcomingLessons': 'Próximas lecciones',
  'course.detail.title': '{courseName} | Curso',
  'lessons.visibility.public': 'Público',
  'lessons.visibility.private': 'Privado',
  'lessons.visibility.hidden': 'Oculto',
  'courses.members.search.placeholder': 'Buscar usuario...',
  'course.search.user': 'Buscar usuario',
  'course.user.addFinished': 'Terminado',
  // Course invites
  'courses.invites.title': 'Invitaciones a cursos',
  'courses.invites.heading': 'Invitaciones a cursos',
  'courses.invites.tile': 'Le invitamos a participar en {count, plural, one {cursos} other {cursos}}.',
  'courses.invites.noInvites': 'Por el momento no tiene ninguna invitación a un curso.',
  'courses.invites.invitedBy': 'Invitado por: ',
  'courses.invites.accept': 'Acepte',
  'courses.invites.reject': 'Rechace',
  'courses.role.owner': 'Propietario',
  'courses.role.teacher': 'Profesor',
  'courses.role.student': 'Estudiante',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'contentSelector.noSelection': 'No item selected',
  'contentSelector.selectedItems': 'Selected items',
  'contentSelector.entireSite': 'Entire site',
  'contentSelector.myLibrary': 'My library',
  'contentSelector.tabsLabel': 'Search options',
  'contentSelector.title': 'Select Content',
};
