export default {
    'feedback.home': 'Centro de asistencia',
    'feedback.bugs': 'Incidencias',
    'feedback.bugs.desc': '¿Has encontrado algún fallo o algo incorrecto o desubicado? ¡Háznoslo saber aquí!',
    'feedback.features': 'Ideas y propuestas',
    'feedback.features.desc': '¿Tienes alguna idea sobre nuevas funciones o mejoras para el sitio? ¡Dínoslo!',
    'feedback.help': 'Ayuda y tutoriales',
    'feedback.help.desc': '¿Cómo puedo _____? Encuentra aquí la respuesta.',
    'feedback.desc': '¡Bienvenido a nuestro centro de asistencia y solución de problemas!',
    'feedback.faq': 'Preguntas frecuentes',
    'feedback.faq.desc': 'Preguntas frecuentes',
    'feedback.open': 'Abierto',
    'feedback.closed': 'Cerrado',
    'feedback.accepted': 'Aceptado',
    'feedback.inprogress': 'En progreso',
    'feedback.completed': 'Completado',
    'feedback.fixed': 'Arreglado',
    'feedback.new.bugs': 'Informar de una incidencia',
    'feedback.new.features': 'Sugerir una nueva función',
    'feedback.lang.nosupport': 'Tu lengua no está disponible para comentarios y valoraciones, por favor escribe en inglés. ¡Gracias!',
    'feedback.new.thanks': '¡Gracias por el aviso! Lo examinaremos en breve.',
    'feedback.comment.title': 'Comentario',
    'feedback.comment.desc': 'Mándanos tus comentarios y valoraciones',
    'feedback.comment.legend': 'Tus comentarios y valoraciones - infórmanos sobre lo que quieras',
    'feedback.comment.success': '¡Gracias por tus comentarios!',
    'feedback.comment.label': 'Tu comentario',
    'feedback.copyrightReport.title': 'Violación de los derechos de autor',
    'feedback.copyrightReport.desc': 'Informar sobre violación de los derechos de autor',
    'feedback.report.noUser': 'Tienes que iniciar sesión para mandar un reporte.',
    'feedback.voting.totalVoters': 'Usuarios votados: {voted, number}',
    'feedback.voting.upvote': 'Voto positivo',
    'feedback.voting.downvote': 'Voto negativo',
    'feedback.voting.score': 'Puntuación total',
    'feedback.report.title': 'Reportar contenido',
    'feedback.report.typeSelect': '¿Cuál es la incidencia?',
    'feedback.reportType.law': 'Infracción legal',
    'feedback.reportType.vulgar': 'Vulgar/obsceno',
    'feedback.reportType.copyright': 'Violación de los derechos de autor',
    'feedback.reportType.storyRating': 'Clasificación de edad incorrecta',
    'feedback.reportType.scam': 'Estafa',
    'feedback.report.submit': 'Reportar',
    'feedback.report.submitting': 'Reportando...',
    'feedback.report.violationDesc': 'Detalles',
    'feedback.report.reportSaved': '¡Gracias por tu reporte! Lo examinaremos y tomaremos las medidas oportunas.',
    'feedback.report.copyrightReportSaved': '¡Gracias por el reporte! Lo examinaremos y nos mantendremos en contacto.',
    'feedback.report.copyrightOwnershipDesc': 'Sentencia de titularidad',
    'feedback.report.copyrightNotice': 'Ten en cuenta que debes ser el propietario de la obra para utilizar este formulario. Si no eres el propietario, informa al propietario o utiliza la otra categoría para informarnos. Nos tomamos muy en serio las violaciones de derechos de autor al igual que el uso inadecuado y abusivo de este formulario.',
    'feedback.report.copyrightInternalProperty': 'He publicado esta obra en Literary Universe',
    'feedback.reportType.spam': 'Spam o phishing',
    'feedback.reportType.other': 'Otros',
    'feedback.report.copyrightType.propertySelectLabel': `¿Qué {type, select,
    universe {universo}
    story {historia}
    other {historia}
  } se está infringiendo?`,
    'faq.section.about': 'Sobre nosotros',
    'faq.section.settings': 'Configuración',
    'faq.section.discovery': 'Descubrir',
    'faq.section.reader': 'Lector',
    'faq.section.library': 'Biblioteca',
    'faq.section.workshop': 'Taller',
    'faq.section.writer': 'Escritor',
    'faq.section.encyclopedia': 'Enciclopedia',
    'faq.section.groups': 'Grupos',
    'faq.section.blogs': 'Blogs',
    'faq.section.guilds': 'Gremios',
    // About us questions
    'faq.question.about.whatIsLU': '¿Qué es Literary Universe?',
    'faq.answer.about.whatIsLU': 'Literary Universe es una plataforma para escritores y lectores para crear, compartir y descubrir historias y mundos.',
    'faq.question.about.difference': '¿Cuál es la diferencia entre Literary Universe y otras plataformas de lectura en línea?',
    'faq.answer.about.difference': 'Literary Universe es una plataforma todo en uno, lo que significa que incluye herramientas para escribir, leer, construir mundos y crear comunidad. La diferencia clave es la inclusión de todas estas herramientas juntas en una plataforma y su interconexión.',
    'faq.question.about.dataLocation': '¿Dónde se almacenan los datos de LU?',
    'faq.answer.about.dataLocation': 'Los datos del Universo Literario se almacenan en servidores en los Estados Unidos de América, específicamente en la región AWS us-east-1.',
    'faq.question.about.incorporation': '¿Dónde estás incorporado?',
    'faq.answer.about.incorporation': 'Literary Universe está incorporado en la República Checa. Puedes encontrar más detalles en la página <a href="/about">sobre nosotros</a>.',
    'faq.question.about.roadmap': '¿Cuáles son los próximos pasos para Literary Universe?',
    'faq.answer.about.roadmap': 'Esto está en constante evolución. Consulta nuestro <a href="/roadmap">plan de desarrollo</a> para más detalles.',
    // Settings questions
    'faq.question.settings.changeTheme': '¿Cómo cambio la apariencia de Literary Universe?',
    'faq.answer.settings.changeTheme': 'Los usuarios registrados pueden cambiar su apariencia en la configuración de la cuenta <a href="/user/settings/account"></a> en la sección "temas del sitio". Tenemos un tema claro y un tema oscuro disponibles. Si no estás registrado, intentamos determinar qué tema ofrecerte según la configuración de tu navegador y sistema operativo.',
    'faq.question.settings.changeAvatar': '¿Cómo cambio mi avatar?',
    'faq.answer.settings.changeAvatar': 'Puedes cambiar tu avatar en la configuración del perfil <a href="/user/settings/profile"></a>.',
    'faq.question.settings.changeLanguage': '¿Cómo cambio el idioma?',
    'faq.answer.settings.changeLanguage': 'Puedes cambiar el idioma de Literary Universe en la configuración de la cuenta <a href="/user/settings/account"></a>.',
    'faq.question.settings.translationMistake': 'Encontré un error en el texto del sitio web, ¿dónde puedo reportarlo?',
    'faq.answer.settings.translationMistake': 'Todos nuestros archivos de idioma están disponibles en GitHub. Puedes <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">enviar un informe allí</a> o en la sección de errores de la retroalimentación, o si lo prefieres, puedes corregirlo directamente tú mismo a través de <a href="https://crowdin.com/project/literary-universe" target="_blank">nuestra página de Crowdin</a>.',
    // Discovery questions
    'faq.question.discovery.explain': '¿Qué es la sección Descubrimiento?',
    'faq.answer.discovery.explain': 'La sección Descubrimiento es donde puedes encontrar nuevas historias, universos, blogs, grupos y otro contenido. Es un lugar para explorar y encontrar cosas nuevas para leer y disfrutar.',
    // Writer
    'faq.question.writer.howToCreateStory': '¿Cómo creo una nueva historia en Literary Universe?',
    'faq.answer.writer.howToCreateStory': 'You can create a new story by going to the <a href="/workshop">workshop</a> and clicking on one of the create buttons or go to the main <a href="/workshop/create">create page</a> where you can select a <a href="/workshop/create/story">new standalone story</a> or <a href="/workshop/create/fanfiction">fan fiction</a>. To create a new story in a universe, go first to that universe and then select "stories" on the dashboard and on the next page click the big red button on the right side of the page title. You will be asked to fill in the details of your story and then you can start writing.',
    'faq.question.writer.schedule': '¿Cómo programo la publicación de un capítulo en Literary Universe?',
    'faq.answer.writer.schedule': 'Puedes programar la publicación de un capítulo al hacer clic en el botón publicar en el editor de capítulos. Se mostrará un modal donde tendrás la opción de programar la publicación o publicar inmediatamente. Si eliges programar la publicación, se te pedirá que selecciones la fecha y hora en la que deseas que se publique el capítulo. Recomendamos programar los capítulos al menos con 24 horas de anticipación para dar tiempo a los lectores a prepararse para el nuevo capítulo y para publicarlo en el mismo día y hora de la semana.',
    // Reader
    'faq.question.reader.creativeTypes': '¿Cuál es la diferencia entre Universo, Historias y Fan Fiction?',
    'faq.answer.reader.creativeTypes': 'El Universo es un lugar donde puedes encontrar todas las historias y otro contenido relacionado con un mundo literario específico. Las historias pueden ser historias independientes o parte de un universo creado por alguien más. La Fan Fiction es una historia basada en otro universo literario creado por otra persona.',
    // Workshop
    'faq.question.workshop.explain': '¿Qué es el Taller?',
    'faq.answer.workshop.explain': 'El Taller es donde puedes crear nuevas historias, fan fiction, universos y otro contenido. Es un lugar para escribir, editar y gestionar tu contenido creativo.',
    'faq.question.workshop.creativeTypes': '¿Cuál es la diferencia entre Universo, Historias y Fan Fiction?',
    'faq.answer.workshop.creativeTypes': 'El Universo es un lugar central para tu universo literario en el cual creas historias que habitan en el mismo mundo literario, gestionas una enciclopedia con todas las complejidades de tu mundo y haces cualquier otra cosa relacionada con él. La Fan Fiction es una historia basada en otra historia o universo creado por alguien más. Las historias independientes son historias que no están conectadas a ningún universo, úsalas, por ejemplo, para poesía o obras literarias que están ambientadas en el mundo real sin muchos personajes o detalles inmersivos que requieran una enciclopedia u otros beneficios de tener un universo.',
    'faq.question.workshop.continueStory': '¿Cómo puedo continuar una historia creada previamente?',
    'faq.answer.workshop.continueStory': 'You can continue a previously created story by going to the <a href="/workshop">workshop</a> and selecting the story you want to continue or if it is a story in a universe, you need to first go to the universe and select the story from the stories listing. On the story dashboard you can then click on the chapter you want to continue writing or create a new chapter.',
    'faq.question.workshop.whatIsALicense': '¿Qué es una Licencia de Historia?',
    'faq.answer.workshop.whatIsALicense': 'Una licencia de historia es un documento legal que define cómo tu historia/universo puede ser utilizado por otros. Es una forma de proteger tus derechos y definir cómo otros pueden usar tu trabajo.',
    'faq.question.workshop.licenses': '¿Qué licencias están disponibles?',
    'faq.answer.workshop.licenses': 'We offer a variety of licenses to choose from. When creating a new work in the licenses section will be a button which will list all available licenses with their full details. In general we offer full copyright protections and <a href="https://creativecommons.org/" target="_blank" rel="noreferrer noopener external">Creative Commons</a> licenses.',
    'faq.question.workshop.guildOwnership': '¿Qué es la Propiedad del Gremio?',
    'faq.answer.workshop.guildOwnership': 'La propiedad de la hermandad indica un trabajo que es propiedad de una organización, a las que llamamos hermandades. Esto podría ser un editor u otro tipo de empresa u organización sin fines de lucro. La propiedad del trabajo suele ser un poco más compleja y el autor puede no tener control total sobre el trabajo, esto significa principalmente que el trabajo se gestiona a través de la organización y no por el autor desde su cuenta personal.',
    'faq.question.workshop.howToInviteCollaborators': '¿Cómo invito a colaboradores para una historia/universo?',
    'faq.answer.workshop.howToInviteCollaborators': 'Puedes invitar a colaboradores a tu historia/universo yendo al panel de control de la historia/universo y haciendo clic en el botón "Colaboradores". Allí puedes invitar a otros usuarios a colaborar en tu historia/universo ingresando su nombre de usuario y seleccionando el rol que deseas asignarles.',
    'faq.question.workshop.howToTranslation': '¿Cómo puedo traducir mi historia o universo?',
    'faq.answer.workshop.howToTranslation': 'Puedes traducir tu historia o universo yendo al panel de control de la historia/universo y haciendo clic en el botón "Traducciones". Allí puedes agregar nuevas traducciones para tu trabajo y, si tienes a alguien para hacer la traducción, puedes invitarlos a unirse a la traducción. Desde allí también puedes gestionar las traducciones tú mismo/a.',
    'faq.question.workshop.betaReaders': '¿Qué son los Beta Readers y cuál es su propósito en mi historia?',
    'faq.answer.workshop.betaReaders': 'Los Beta Readers son personas que leen tu historia antes de que se publique y te dan comentarios. Pueden ayudarte a encontrar errores, darte ideas para mejorar y ayudarte a hacer tu historia mejor.',
    'faq.question.workshop.hiatus': '¿Qué es una pausa en el estado de la historia?',
    'faq.answer.workshop.hiatus': 'La pausa es un estado para tu historia que indica que estás tomando un descanso de escribir y publicar nuevos capítulos. Es una forma de hacer saber a tus lectores que no estás trabajando activamente en la historia en ese momento. Este estado se establece automáticamente después de 6 meses sin nuevos capítulos. Después de otros 6 meses de inactividad, la historia se marcará como cancelada.',
    'faq.question.workshop.finished': '¿Cómo indico que mi historia está terminada?',
    'faq.answer.workshop.finished': 'Puedes indicar que tu historia está terminada yendo al panel de control de la historia y en la parte inferior hay un botón verde que dice "Cambiar estado de la historia a Completada". Esto marcará la historia como terminada ajustando la última página para indicar a los lectores que la historia ha terminado y que revisen tus otras obras. También se indicará en el descubrimiento, lo que hará que tu historia sea más visible para los lectores que buscan historias terminadas.',
    'faq.question.workshop.seo': '¿Cuál es el uso de SEO-Friendly-Address en varias configuraciones?',
    'faq.answer.workshop.seo': 'SEO-Friendly-Address es una forma de hacer que tu historia, universo, entrada de blog sea más visible para los motores de búsqueda y más fácil de leer en la URL para los humanos. Es una forma de hacer que tu trabajo sea más descubrible y ayudar a las personas a encontrar tu trabajo cuando buscan algo similar.'
};