// Notifications & flashnews
export default {
  'flashnews.create': 'Crear un nuevo boletín de noticias de última hora',
  'flashnews.startsAt': 'Empezar a mostrar este mensaje a las',
  'flashnews.endsAt': 'Dejar de mostrar este mensaje a las',
  'flashnews.newLanguage': 'Seleccionar un nuevo idioma que añadir',
  'flashnews.onlyDisplayOn': 'Las noticias se mostrarán solo en los idiomas seleccionados a continuación (si es que se selecciona alguno), no se mostrarán noticias, ni siquiera en el idioma por defecto, en otros idiomas.',
  'notifications.menu.all': 'Todas las notificaciones',
  'notifications.menu.following': 'Siguiendo',
  'notifications.menu.workshop': 'Taller',
  'notifications.menu.news': 'Noticias y actualizaciones',
  'notifications.menu.markUnread': 'Marcar como no leído',
  'notifications.menu.markRead': 'Marcar como leído',
  'notifications.menu.delete': 'Borrar notificación',
  // Notification messages
  'notification.workshopStoryStatus.toHiatus': 'Tu historia {storyName} ha sido marcada como en hiato automáticamente tras 6 meses de inactividad.',
  'notification.workshopStoryStatus.toCancelled': 'Tu historia {storyName} ha sido marcada como cancelada automáticamente tras un año de inactividad.',
  'notification.followingStoryStatus.toHiatus': '{storyName} está en hiato.',
  'notification.followingStoryStatus.toCancelled': '{storyName} ha sido cancelada.',
  'notification.followingNewChapter.new': '¡Se ha publicado un nuevo capítulo de {storyName}!',
  'notification.workshopStory.newComment': 'ha comentado en {storyName}',
  // Before this text will be the username of the user
  'notification.friendRequest': 'te ha enviado una petición de amistad.',
  // Before this text will be the username of the user
  // Story notification messages - In-app notifications
  'notification.story.newComment.subject': 'Nuevo comentario sobre "{storyTitle}"',
  'notification.story.newComment.body': '{commenterName} ha comentado su historia: "{commentText}"',
  'notification.story.betaComment.subject': 'Nuevos comentarios beta en "{storyTitle}"',
  'notification.story.betaComment.body': '{commenterName} proporcionó retroalimentación beta: "{commentText}"',
  'notification.story.collaboratorAccepted.subject': 'Nuevo {role} se unió a "{storyTitle}"',
  'notification.story.collaboratorAccepted.body': '{collaboratorName} aceptado su invitación para ser un {role}',
  'notification.story.statusChange.subject': 'Actualización de estado de "{storyTitle}"',
  'notification.story.statusChange.body': 'El estado de la historia ha cambiado de {oldStatus} a {newStatus}',
  'notification.story.completed.subject': '"{storyTitle}¡" se ha completado!',
  'notification.story.completed.body': '{authorName} ha completado "{storyTitle}". Gracias por leer.',
  'notification.story.milestone.subject': 'Hito alcanzado: ¡ {milestone} en "{storyTitle}"!',
  'notification.story.milestone.body': '¡Su capítulo "{chapterTitle}" ha llegado a {count} {milestone}!',
  'notification.story.betaRevision.subject': 'Nueva revisión beta: "{chapterTitle}"',
  'notification.story.betaRevision.body': '{authorName} publicado una nueva revisión beta de "{chapterTitle}" para su revisión',
  'notification.story.authorReply.subject': '{authorName} respondido a sus comentarios',
  'notification.story.authorReply.body': '{authorName} respuesta a su comentario beta sobre "{storyTitle}": "{commentText}"',
  'notification.story.newChapterForTranslators.subject': 'Nuevos contenidos disponibles para su traducción: "{chapterTitle}"',
  'notification.story.newBetaForTranslators.body': 'La nueva revisión beta de "{chapterTitle}" está lista para su traducción',
  'notification.story.newChapterForTranslators.body': 'El nuevo capítulo "{chapterTitle}" está disponible para su traducción',
  'notification.story.newChapter.subject': 'Nuevo capítulo: "{chapterTitle}"',
  'notification.story.newChapter.body': '{authorName} publicado un nuevo capítulo de "{storyTitle}": "{chapterTitle}"',
  // Universe notifications
  'notification.universe.newStory.subject': 'Nueva historia en el universo: "{storyTitle}"',
  'notification.universe.newStory.body': '{authorName} ha añadido una nueva historia "{storyTitle}" al universo que estás siguiendo',
  'notification.universe.collaboratorChange.subject': 'Actualización de la colaboración Universe',
  'notification.universe.collaboratorChange.body': 'Equipo de colaboración cambiado para un universo en el que participa',
  'notification.universe.update.subject': 'Universo actualizado',
  'notification.universe.update.body': 'Un universo que está siguiendo ha sido actualizado',
  'notification.universe.comment.subject': 'Nuevo comentario sobre el universo',
  'notification.universe.comment.body': '{commenterName} comentó sobre un universo que está siguiendo: "{commentText}"',
  // Blog notifications
  'notification.blog.newPost.subject': 'Nueva entrada en el blog: "{postTitle}"',
  'notification.blog.newPost.body': '{authorName} ha publicado una nueva entrada "{postTitle}" en un blog que sigue',
  'notification.blog.comment.subject': 'Nuevo comentario en la entrada del blog: "{postTitle}"',
  'notification.blog.comment.body': '{commenterName} ha comentado la entrada del blog "{postTitle}": "{commentText}"',
  'notification.blog.update.subject': 'Blog actualizado',
  'notification.blog.update.body': 'Un blog que está siguiendo ha sido actualizado',
  // General comment notifications
  'notification.comment.general.subject': 'Nuevo comentario sobre "{contentTitle}"',
  'notification.comment.general.body': '{commenterName} comentado en "{contentTitle}": "{commentText}"',
  'notification.comment.reply.subject': 'Responder a su comentario',
  'notification.comment.reply.body': '{replierName} respuesta a su comentario sobre "{contentTitle}": "{replyText}"',
  'notification.comment.like.subject': 'Me ha gustado su comentario',
  'notification.comment.like.body': '{likerName} me ha gustado su comentario',
  // Content-specific comment notifications
  'notification.comment.fanArt.subject': 'Nuevo comentario sobre fan art: "{contentTitle}"',
  'notification.comment.fanArt.body': '{commenterName} ha comentado su fan art "{contentTitle}": "{commentText}"',
  'notification.comment.event.subject': 'Nuevo comentario sobre el evento: "{contentTitle}"',
  'notification.comment.event.body': '{commenterName} ha comentado el evento "{contentTitle}": "{commentText}"',
  'notification.comment.revision.subject': 'Nuevo comentario sobre la revisión',
  'notification.comment.revision.body': '{commenterName} ha comentado su revisión: "{commentText}"',
  'notification.comment.feedback.subject': 'Nuevo comentario sobre la retroalimentación',
  'notification.comment.feedback.body': '{commenterName} comentó su problema de retroalimentación: "{commentText}"',
  // Welcome notification
  'notification.welcome.body': 'Estamos encantados de tenerle a bordo.',
  'notification.welcome.cta.reader': '¡Comience a leer!',
  'notification.welcome.cta.writer': '¡Empiece a escribir!',
  // Strings for extra section
  'notificationExtra.workshopStoryStatus.goToStory': 'Ir a la historia',
  // UI strings for enhanced notifications
  'notifications.menu.community': 'Comunidad',
  'notifications.menu.reading': 'Lectura y biblioteca',
  'notifications.menu.system': 'Sistema',
  'notifications.empty': 'Ya está todo listo. Aquí no hay nada nuevo.',
  'notifications.empty.category': 'Pruebe a consultar otras categorías o a ajustar sus preferencias de notificación.',
  'notifications.error.loadFailed': 'Error al cargar las notificaciones: {error}',
  'notifications.loadMore': 'Cargar más',
  // Action button labels
  'notifications.action.viewStory': 'Ver artículo',
  'notifications.action.readChapter': 'Leer capítulo',
  'notifications.action.goToWorkshop': 'Ir al taller',
  'notifications.action.viewUniverse': 'Ver Universo',
  'notifications.action.viewBlog': 'Ver blog',
  'notifications.action.readPost': 'Leer el post',
  'notifications.action.viewComments': 'Ver comentarios',
  // Category descriptions
  'notifications.category.workshop.description': 'Notificaciones sobre sus actividades de creación y gestión de contenidos',
  'notifications.category.community.description': 'Notificaciones sobre interacciones sociales y compromiso comunitario',
  'notifications.category.reading.description': 'Notificaciones sobre nuevos contenidos y actividades de lectura',
  'notifications.category.system.description': 'Notificaciones del sistema y actualizaciones importantes'
};