export default {
    'homepage.welcome': 'Welcome to',
    'homepage.start': 'Start Your journey!',
    'homepage.iAm': 'I am a',
    'homepage.iAm.aria': 'Select between display of features for readers and writers',
    'homepage.reader': 'READER',
    'homepage.writer': 'WRITER',
    'homepage.reader.title': 'Reading has never been so interesting like this',
    'homepage.reader.readingTitle': 'Unique reading experience',
    'homepage.reader.readingDesc': 'Delve deeper into your favorite fictional universe in Literary Universe. Stories in Literary Universe are connected within the same universe, giving you immediate access to the universe encyclopedia from the story reader.',
    'homepage.reader.favoriteTitle': 'Find out more about Your favorite stories and authors',
    'homepage.reader.favoriteDesc': 'Universe encyclopedia and author\'s blogs are just a few feature that will help you find out everything you need to know about your favorite stories, their settings and their creators!',
    'homepage.reader.communityTitle': 'Join the community',
    'homepage.reader.communityDesc': 'Meet people from across the globe on dedicated universe and author\'s forums, blogs and other community features where like-minded fans gather. All in one place.',
    'homepage.reader.readingFeatureTitle': 'Enjoy an immersive yet practical reading experience',
    'homepage.reader.readingFeatureDesc': 'From stories and universe, have the benefit of effortless reading with access to details without needing to switch between pages.',
    'homepage.reader.readingExploreTitle': 'Explore all the minutia in the universe',
    'homepage.reader.readingExploreDesc': 'Universe encyclopedia allows you to learn all the details about the universe and fully immerse yourself in the stories.',
    'homepage.reader.start': 'Start Reading',
    'homepage.writer.title': 'Showcase your universe and share your stories',
    'homepage.writer.writingTitle': 'Writing & creating made easy',
    'homepage.writer.writingDesc': 'Experience the new way of writing with Literary Universes Workshop. Create all the details of your universe in an encyclopedia to share with your readers and write amazing stories on that foundation.',
    'homepage.writer.collaborationTitle': 'Collaborative creation',
    'homepage.writer.profitDesc': 'Creative process often involves multiple people. No worries, we got you covered! You can easily add beta readers, co-authors and translators to your stories and universes.',
    'homepage.writer.communityTitle': 'Connect with Your readers',
    'homepage.writer.communityDesc': 'Go beyond writing and connect with your readers via blogs, forums and other community features connected to your universes or to you as a writer.',
    'homepage.writer.workshopFeatureTitle': 'One place for all your creative needs',
    'homepage.writer.workshopFeatureDesc': 'Our ever evolving workshop is the central place for your creative needs. From a simple idea create amazing universes, stories and everything else that is needed around it.',
    'homepage.writer.monetizationFeatureTitle': 'Monetization',
    'homepage.writer.monetizationDesc': 'We strongly believe that people should be payed for their work and are constantly looking for new monetization opportunities for writers. Monetization feature allows you writers to be appreciated for what you do. Explore all the different options that allow your fans to show you their appreciation.',
    'homepage.writer.start': 'Setup Your workshop!',
    'homepage.featureSelection': 'Check out these popular universe!',
    'about.title': 'Acerca de Literary Universe',
    'about.desc': 'Historia, secretos y humanos detrás de Literary Universe.',
    'about.text.1': 'Literary Universe está ideado tanto para escritores como para ávidos lectores. Los escritores pueden utilizar este sitio para escribir obras originales por medio del botón de taller en el menú. Esto te dará acceso al editor y a la enciclopedia, que se centran en organizar todos los aspectos de tu universo personal de historias en una sola página. Los aspectos sociales permiten a los autores difundir su trabajo y formarse una base de seguidores, así como interactuar de forma más directa con sus lectores si así lo desean.',
    'about.text.2': 'Los lectores pueden utilizar el sitio para leer nuevas obras y seguir a autores, pero también pueden ayudar a editar historias prepublicadas con permiso del autor. Ser lector en Literary Universe es una experiencia totalmente innovadora que te permite acceder a toda la información de fondo en la misma página mientras la historia principal te abre una ventana a la mente del autor como nunca antes.',
    'about.text.3': 'El futuro de Literary Universe consiste en crear un mercado para autores con el fin de vender sus obras y en integrar funciones comunitarias para impulsar la comunicación entre autores y lectores por medio de blogs y foros. Las herramientas para escritores se irán añadiendo. Actualmente hay un montón de herramientas desarrollándose o pendientes de serlo. Nuestro objetivo es mejorar las experiencias de escritores y autores proporcionando un uso más innovador de Internet.',
    'about.text.4': '¡Esperamos que te unas a nosotros y que exploremos lo que puede hacer Internet por la escritura creativa!',
    'about.team': 'El equipo',
    'about.history': 'Historia',
    'about.company': 'Compañía',
    'about.companyCountry.czechia': 'Chequia',
    'about.companyCountry.japan': 'Japón',
    'about.companyCity.prague': 'Praga',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Director ejecutivo',
    'about.CTO': 'Director de tecnología',
    'about.jan': 'Jan es el fundador, visionario y cabeza tecnológica detrás de Literary Universe. Como escritor de vastos universos literarios, a Jan siempre le ha costado escribir historias desde un punto de vista técnico y de legibilidad que no comprometiese la experiencia de lectura. Es así que Jan decidió seguir sus estudios en desarollo web para crear una aplicación con la que escribir historias en universos amplios de forma sencilla.',
    'about.history.text': 'En 2010 Jan empezó a aprender más sobre desarrollo web en el Instituto de Tecnología de Rochester para poder construir un sitio de escritura creativa. Esto se materializó en 2013 cuando presentó su primera prueba de concepto en Imagine RIT. Jan continuó sus estudios y en 2016 se creó una nueva versión de la aplicación en Master\'s Capstone Project. El proyecto continuó en otoño de 2016 y siguió desarrollándose hasta lo que ves ahora mismo.',
    'copyrights.desc': 'Vista completa del acuerdo de derechos de autor de Literary Universe.',
    'privacy.desc': 'Vista completa de las políticas de privacidad de Literary Universe.',
    'guidelines.desc': 'Normas comunitarias de Literary Universe.',
    'tos.desc': 'Vista completa de condiciones de servicio de Literary Universe.',
    'homepage.intro': 'Explora y crea universos y grandes historias, literalmente.',
    'homepage.explanation': 'Literary Universe es una plataforma de lectura y escritura creativa todo en uno, centrada en el complejo universo literario. Aspiramos a proporcionar herramientas interconectadas para escribir tantos complejos universos como historias sueltas así como ofreccer una gran experiencia para fans y lectores explorando dichos universos.',
    'gdpr.title': 'Cumplimiento RGPD',
    'gdpr.desc': 'Literary Universe cumple con las directivas RGPD de la UE.',
    'gdpr.compliant': 'Literary Universe cumple con RGPD',
    'gdpr.compliant.text': 'Literary Universe ha implementado varias actualizaciones y cambios a su base de código para prepararse para un refuerzo de RGPD el 25 de mayo de 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Ley de Derechos de Autor de la Era Digital',
    'common.legal.changelog': 'Cambios en esta versión',
    'dmca.title': 'Política de Ley de Derechos de Autor de la Era Digital (DMCA)',
    'dmca.subtitle': 'Políticas de controversias de derechos de autor',
    'dmca.step1.title': 'Procedimiento para notificar infracciones de derechos de autor.',
    'dmca.step2.title': 'Procedimiento posterior a una notificación auténtica de infracción.',
    'dmca.step3.title': 'Procedimiento para proporcionar una contranotificación al agente designado.',
    'dmca.desc': 'Nos tomamos en serio las violaciones de los derechos de autor.',
    'gdpr.access.title': 'Derecho de acceso y derecho de portabilidad de datos',
    'gdpr.access.desc': 'En la configuración de usuario puedes exportar todos tus datos. Estos datos estarán en formato estándar JSON.',
    'gdpr.forget.title': 'Derecho a ser olvidado',
    'gdpr.forget.desc': 'Cualquier cuenta puede eliminarse en la configuración de usuario. Algunos datos pueden quedar guardados, especialmente si han sido objeto de venta o controversias.',
    'gdpr.rectification.title': 'Derecho a la rectificación',
    'gdpr.rectification.desc': '',
    'gdpr.processing.title': 'Derecho a la limitación del tratamiento',
    'gdpr.processing.desc': 'Literary Universe respeta plenamente la configuración de tu navegador, como las solicitudes de "No rastrear" para mandar información a nuestro servidor de estadísticas Matomo.',
    'gdpr.object.title': 'Derecho a la objeción',
    'gdpr.object.desc': '',
    'dmca.step1.desc1': 'Reportar se divide en dos escenarios 1. propiedad interna (infracción en el sitio de propiedad existente en el sitio). 2. Propiedad externa (infracción en el sitio de propiedad inexistente en el sitio).',
    'dmca.step1.desc2': 'Puede reportarse propiedad interna por medio del botón de reporte en la propiedad. Puede reportarse una infracción de propiedad externa en la pantalla de comentarios y valoraciones. En ambos casos se te pedirán datos personales y adicionales para verificar tu titularidad.',
    'dmca.step1.desc3': 'Ten en cuenta que hacer reclamaciones falsas te incapacitará para presentar reclamaciones futuras.',
    'dmca.step2.desc1': 'Al recibir tu informe verificaremos tus credenciales y reclamación de propiedad. Si todo está correcto procederemos a comprobar la reclamación. Si confirmamos la veracidad de la reclamación, limitaremos el acceso a la propiedad infractora hasta contranotificación o se eliminará en el transcurso de 14 días.',
    'dmca.step3.desc1': 'Una vez se haya recibido una queja, el propietario de la propiedad designada dispondrá de 14 días para enviar una contranotificación. El agente designado procederá a investigar la controversia. La decisión del agente designado será determinante.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Atribuciones',
    'about.attributionsIntro': 'Literary Universe se cimienta en numerosos proyectos de código abierto y recursos gratuitos. A continuación encontrarás el listado completo.',
    'about.attributionsMatomo': 'Nuestros análisis utilizan Matomo con datos IP2Location LITE disponibles en https://lite.ip2location.com.',
    'about.attributionIcons': 'Los siguientes iconos se utilizan en la página a través de styled-icons:',
    'team.name.pjakubec': 'Pavel Jakubec',
    'team.name.asebesta': 'Adam Šebesta',
    'about.developer': 'Desarrollador',
    'about.seniorDeveloper': 'Desarrollador sénior',
    'about.juniorDeveloper': 'Desarollador Junior',
    'about.leadDesigner': 'Diseñador jefe',
    'about.leadUX': 'Diseñador a cargo de la UX',
    'about.intern': 'Becario',
    'about.advisor': 'Asesor',
    'about.headOfResearch': 'Jefe de Investigación',
    'about.CFO': 'Director Financiero',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry es un diseñador con más de 15 años de experiencia. Ha estado trabajando en la agencia desde 2010 con clientela destacada como PERTAMINA, VOA, y el Ministerio de Turismo de Indonesia. Con experiencia en Branding, diseño y también en UI/UX que ha aceptado el desafío de diseñar Literary Universe.',
    'about.pavel': 'Web3, Metaverso, Inteligencia Artificial y toda tecnología puntera, eso es lo que Pavel estudia y piensa cómo se puede añadir para mejorar Literary Universe. Pavel, un verdadero investigador multidisciplinar, tiene conocimientos en muchas áreas y trabaja para añadir nuevas características interesantes a Literary Universe',
    'about.seba': 'Adam, una vez un ávido gamer, ahora estudia para convertirse en un desarrollador de pleno derecho.'
};