export default {
    'reader.storyEnd.heading': 'FIN',
    'reader.storyEnd.description': 'Has llegado al final de la historia.',
    'reader.externalSale.heading': 'No hay nada aquí todavía',
    'reader.externalSale.description': 'Esta historia no está disponible en Literary Universe, pero puedes encontrarla en otros sitios.',
    'reader.storyTBC.heading': 'Continuará...',
    'reader.storyTBC.description': 'Esto es lo que tenemos de esta historia, pero la historia continuará en el futuro, ¡vuelve pronto!',
    'chapter.translation.notYetDescription': '¡Vuelve pronto!',
    'reader.externalShopping.heading': 'Comprar {storyName} en tiendas:',
    'chapter.next': 'Capítulo siguiente',
    'chapter.previous': 'Capítulo anterior',
    'chapter.comment': 'Comentarios en este capítulo',
    'reader.language': 'Idioma:',
    'reader.fullscreen.enter': 'Mostrar en pantalla completa',
    'reader.fullscreen.exit': 'Salir de pantalla completa',
    'reader.details.universe': 'Detalles del universo',
    'reader.details.story': 'Detalles de la historia',
    'reader.darkmode': 'Activar modo noche',
    'reader.flowtext': 'Cambiar tamaño de texto',
    'reader.menu.optionsAria': 'Menú de opciones de lectura',
    'reader.accessibility': 'Cambiar accesibilidad',
    'chapter.translation.notYet': 'Todavía no se ha traducido este capítulo.',
    'externalShopping.buyLink.amazon': 'Comprar en Amazon',
    'externalShopping.buyLink.other': 'Comprar en {storeName}',
    'externalShopping.buyLink.bookshop': 'Comprar en Bookshop.org',
    'external.textopian': 'Textopian',
    'external.textopian.title': 'Leer y comentar trabajo de dominio público en Textopian',
    'reader.accessibility.aria': 'Accessibility options',
    'reader.accessibility.toggleDyslexic': 'Toggle dyslexic font',
    'reader.accessibility.toggleParagraphStripes': 'Toggle paragraphs background alteration',
    'reader.accessibility.toggleParagraphHighlight': 'Toggle selected paragraph highlighting',
    'reader.accessibility.toggleRules': 'Toggle assistive ruler'
};