export default {
    'settings.biography': 'Biografía',
    'settings.biography.placeholder': 'Cuenta un poco acerca de ti para mostrarlo en tu perfil.',
    'settings.avatar.title': 'Avatar',
    'settings.avatar.own': 'Tu avatar',
    'settings.avatar.upload': 'Seleccionar imagen',
    'settings.email': 'Correos electrónicos',
    'settings.email.msg': 'Correos electrónicos asociados con tu cuenta',
    'settings.email.verified.false': 'No verificado',
    'settings.email.verified.true': 'Correo electrónico verificado',
    'settings.email.add': 'Añadir correo electrónico',
    'settings.languages.title': 'Configuración de idioma',
    'settings.languages.notice': 'La única lengua disponible oficialmente es el inglés. Otras lenguas están disponibles gracias a unos voluntarios maravillosos, pero pueden estar incompletas.',
    'settings.languages.join': 'Si quieres ayudarnos, tú también puedes traducir Literary Universe.',
    'settings.name.title': 'Nombre',
    'settings.name.given': 'Nombre',
    'settings.name.family': 'Apellidos',
    'settings.username.change': 'Cambiar nombre de usuario',
    'settings.username.label': 'Nombre de usuario',
    'settings.password.title': 'Cambiar contraseña',
    'settings.password.current': 'Contraseña actual',
    'settings.password.new': 'Nueva contraseña',
    'settings.password.repeat': 'Repite tu nueva contraseña',
    'settings.password.nomatch': '¡La nueva contraseña no coincide!',
    'settings.password.reset': 'Restablecer contraseña',
    'settings.password.resetSend': '¡Te hemos enviado un correo con las instrucciones para restablecer tu contraseña!',
    'settings.socialConnectTitle': 'Conectar con tus cuentas de otros servicios',
    'settings.socialDisconnect': 'Desconectar',
    'settings.socialConnect': 'Conectar',
    'settings.loginWith': 'Iniciar sesión con {service}',
    'settings.connectTo': 'Conectar a {service}',
    'settings.export.title': 'Exportar datos',
    'settings.export.explain': 'Con esto obtendrás todos los datos almacenados en nuestra base de datos en formato json.',
    'settings.export.submit': 'Exportar datos',
    'settings.delete.title': 'Borrar cuenta',
    'settings.delete.warning': `ADVERTENCIA: Al borrar tu cuenta perderás acceso a ella y
   no podrás recuperarla. Ten en cuenta que puede que tus publicaciones, comentarios, etc. no se eliminen inmediatamente,
   Revisa las condiciones de servicio para más detalles.`,
    'settings.delete.confirm': '¿Estás seguro de que quieres borrar tu cuenta?',
    'settings.delete.cancel': 'No quiero borrar mi cuenta',
    'settings.delete.submit': 'Borrar mi cuenta',
    'settings.legal.title': 'Acuerdos de consentimiento del usuario',
    'settings.legal.explained': 'Aquí puedes gestionar tu acuerdo respecto a varios documentos legales.',
    'settings.name.private': 'El nombre será privado',
    'settings.emailSubscriptions.title': 'Configuración de notificaciones por correo',
    'settings.emailSubscriptions.explain': 'Selecciona qué notificaciones por correo deseas recibir de nosotros.',
    'settings.emailSubscriptions.newsletter': 'Boletín ocasional',
    'settings.profile': 'Configuración del perfil',
    'settings.account': 'Configuración de la cuenta',
    'settings.legal.export.download': 'Descargar tus datos',
    'settings.legal.export.gathering': 'Recolectando tus datos... Esto puede tardar un tiempo.',
    'settings.gender.title': 'Tu sexo',
    'settings.gender.usage': 'Está información seguirá siendo privada. Utilizamos estos datos en análisis de plataforma y anónimos para los creados cuando leas sus historias.',
    'settings.age.title': 'Edad',
    'settings.age.explicit': 'Mostrar contenido explícito (público 21+)',
    'settings.age.usage': 'Esta información seguirá siendo privada. Tenemos el imperativo legal de saber tu edad. Utilizamos esta información en análisis de plataforma para mostrar contenido según audiencia y en análisis anónimos para creadores cuando leas sus historias.',
    'settings.country.title': 'País',
    'settings.country.usage': 'Tenemos el imperativo legal de saber tu país para responder a solicitudes gubernamentales. Utilizamos esta información en análisis de plataforma y anónimos para creadores cuando leas sus historias. Si lo deseas, puedes mostrar esta información en tu perfil.',
    'settings.country.public': 'Mostrar tu país públicamente',
    'settings.country.select': 'Seleccionar país',
    'settings.emailSubscriptions.newsletterTech': 'Boletín ocasional de nuestros desarrolladores',
    'settings.emailSubscriptions.newsletterFeatures': 'Información sobre nuevas funciones',
    'settings.emailNotifications.title': 'Notificaciones',
    'settings.emailNotifications.pm': 'Nuevos mensajes',
    'settings.emailNotifications.newChapters': 'Nuevos capítulos',
    'settings.resetPasswordEmailSend': 'Te hemos enviado al correo instrucciones sobre cómo restablecer tu contraseña.',
    'settings.theme.title': 'Tema del sitio',
    'settings.theme.label': 'Tema del sitio',
    'settings.theme.light': 'Día',
    'settings.theme.dark': 'Noche',
    'settings.links.title': 'Enlazar a tus otros sitios web',
    'settings.links.description': 'Estos enlaces se mostrarán en tu página de perfil.',
    'settings.links.website': 'Tu sitio web personal',
    'settings.links.social': 'Otros sitios web',
    // 2FA
    'settings.2fa.title': 'Two-factor authentication',
    'settings.2fa.explained': 'Two-factor authentication provides an additional layer of security for your account by adding an additional authentication step during login. This prevents malicious actors from gaining access to your account if your first login step is compromised.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Two-factor authentication with OTP code creates one-time password via authenticator applications (like Authy, Google/Microsoft Authenticator, etc.) that you enter on login.',
    'settings.2fa.otpModalAria': '2FA OTP method',
    'settings.2fa.otpAdd': 'Add 2FA OTP',
    'settings.2fa.confirmCode': 'Code that shows in your authentication application',
    'settings.2fa.svgAlt': 'QR code for authentication app',
    'settings.2fa.codeHeading': 'If you can\'t scan QR code, you can manually enter the following code:',
    'settings.2fa.instructionsTitle': 'Instructions',
    'settings.2fa.instructions1': 'Install and open authenticator application of your choice (Authy, Google/Microsoft Authenticator, FreeOTP, etc.)',
    'settings.2fa.instructions2': 'Select "Add account" (can be a visible "+" icon or can be hidden in a menu)',
    'settings.2fa.instructions3': 'Scan the QR code presented on the screen here or if not possible enter the code bellow.',
    'settings.2fa.instructions4': 'Type in the 6 numbers that appear on the screen into the input here to finish.',
    'settings.2fa.saved': 'Two-factor authentication successfully established!',
    'settings.2fa.disableOTP': 'Disable OTP two-factor authentication'
};