export default {
    'stats.age.groups': 'Grupos de edad',
    'stats.age.range': 'Rango de edad',
    'stats.age.to12': 'Hasta 12 años',
    'stats.age.12to17': 'De 12 a 17 años',
    'stats.age.18to20': 'De 18 a 20 años',
    'stats.age.21to29': 'De 21 a 29 años',
    'stats.age.30to39': 'De 30 a 39 años',
    'stats.age.40to49': 'De 40 a 49 años',
    'stats.age.50to64': 'De 50 a 64 años',
    'stats.age.65to84': 'De 64 a 84 años',
    'stats.age.above85': 'Mayor de 85 años',
    'stats.section.aggregate': 'Estadísticas globales',
    'stats.section.chapter': 'Estadísticas del capítulo',
    'stats.section.type': 'Statistics type',
    'stats.section.writing': 'Writing',
    'stats.section.reading': 'Reading',
    'stats.readers.title': 'Sobre tus lectores',
    'stats.gender.title': 'Género',
    'stats.gender': '{gender, select, male {Hombre} female {Mujer} unknown {Desconocido} other {Desconocido}}',
    'stats.view.table': 'Vista en tablas',
    'stats.view.pie': 'Vista en gráfica circular',
    'stats.view.bar': 'Vista en gráfica de barras',
    'stats.view.chart': 'Vista en gráfica',
    'stats.view.mode': 'Presentation mode',
    'stats.table.total': 'Total',
    'stats.timeline.title': 'Cronología',
    'stats.timeline.dateStart': 'Las estadísticas empiezan en',
    'stats.timeline.dateEnd': 'Las estádisticas terminan en',
    'stats.likeCount': '# de me gusta',
    'stats.language.title': 'Idiomas que habla',
    'stats.chapter.visitorsAndViews': 'Total de visitantes y de visitas por capítulo',
    'stats.chapter.wordCount': 'Número de palabras por capítulo',
    'stats.chapter.chartTooltipViews': 'Capítulo {chapter, number}: {views, number} visitas',
    'stats.chapter.chartTooltipVisitors': 'Capítulo {chapter, number}: {visitors, number} visitantes únicos',
    'stats.chapter.chartTooltipWordCount': 'Capítulo {chapter, number}: {wordCount, number} palabras',
    'stats.totalHits': 'Visitas totales',
    'stats.totalVisitors': 'Total de visitantes únicos',
    'stats.totalWords': 'Palabras totales',
    'stats.totalEntries': 'Entradas de la enciclopedia',
    'stats.blogPage': 'Página',
    'stats.blog.typeSelectionAria': 'Introducir selección',
    'stats.blog.pages': 'Páginas',
    'stats.blog.posts': 'Publicaciones',
    'stats.unknown': 'Desconocido',
    'stats.noData': 'No hay información disponible ahora mismo.',
    'stats.heatmap.less': 'Less',
    'stats.heatmap.more': 'More',
    'stats.date': 'Date',
    'stats.day': 'Day',
    'stats.hour': 'Hour',
    // Author overall statistics
    'workshop.theWay.overallStats.noData': 'Aún no hay datos estadísticos disponibles. ¡Comience a publicar su trabajo para ver sus estadísticas!',
    'workshop.theWay.overallStats.content': 'Su contenido',
    'workshop.theWay.overallStats.stories': 'Historias',
    'workshop.theWay.overallStats.universes': 'Universos',
    'workshop.theWay.overallStats.chapters': 'Capítulos',
    'workshop.theWay.overallStats.wordCount': 'Palabras escritas',
    'workshop.theWay.overallStats.encyclopediaEntries': 'Entradas de la enciclopedia',
    'workshop.theWay.overallStats.publishingStreak': 'Racha editorial de una semana',
    'workshop.theWay.overallStats.monthlyPublicationStreak': 'Mes Racha de publicación',
    'workshop.theWay.overallStats.audience': 'Su público',
    'workshop.theWay.overallStats.fans': 'Abanicos',
    'workshop.theWay.overallStats.followers': 'Seguidores',
    'workshop.theWay.overallStats.uniqueReaders': 'Lectores únicos',
    'workshop.theWay.overallStats.storyViews': 'Vistas de la historia',
    'workshop.theWay.overallStats.universeViews': 'Vistas del universo',
    'workshop.theWay.overallStats.readingTime': 'Tiempo de lectura (min)',
    'workshop.theWay.overallStats.demographics': 'Demografía de los lectores',
    'workshop.theWay.overallStats.topCountry': 'Top País',
    'workshop.theWay.overallStats.topAgeGroup': 'Grupo de edad superior',
    'workshop.theWay.overallStats.genres': 'Sus géneros',
    'stats.title': '{name} - Estadísticas',
    'stats.totalCharacters': 'Total de caracteres',
    'stats.totalReadingTime': 'Tiempo total de lectura',
    'stats.totalReadingTime.description': 'Tiempo combinado que todos los lectores dedicaron a esta historia',
    'stats.averageReadingTime': 'Tiempo medio de lectura',
    'stats.averageReadingTime.description': 'Tiempo medio por lector',
    'stats.readingHabits.title': 'Hábitos de lectura por semana',
    'stats.readingHabits.sessions': 'Sesiones de lectura',
    'stats.readingHabits.averageSession': 'Sesión media',
    'stats.readingHabits.peakDay': 'Día más activo',
    'stats.readingHabits.peakHour': 'Hora más activa',
    'stats.readingHabits.profileSummary': 'Lectura en las últimas {weeks, number} semanas: {sessions, number} sesiones, {duration} total, más activo en {day} alrededor de {hour}.',
    'stats.quarterly.quarter': 'Quarter',
    'stats.storyWritingAnalytics.title': 'Writing analytics',
    'stats.storyWritingAnalytics.aggregate': 'Aggregate',
    'stats.storyWritingAnalytics.time': 'Writing time',
    'stats.storyWritingAnalytics.activeDays': 'Active days',
    'stats.storyWritingAnalytics.averageWordsPerSession': 'Average words per session',
    'stats.storyWritingAnalytics.bestDay': 'Best day',
    'stats.storyWritingAnalytics.currentStreak': 'Current streak',
    'stats.storyWritingAnalytics.longestStreak': 'Longest streak',
    'stats.storyWritingAnalytics.calendar': 'Yearly writing heatmap',
    'stats.storyWritingAnalytics.dayTooltip': '{date}: {words} words',
    'stats.storyWritingAnalytics.weekHour': 'Best writing times',
    'stats.storyWritingAnalytics.weekHourTooltip': '{day} at {hour}: {words} words, {duration}',
    'stats.storyWritingAnalytics.activityTable': 'Writing days',
    'stats.storyWritingAnalytics.topWindows': 'Top writing windows',
    'stats.storyWritingAnalytics.loadError': 'Failed to load story writing analytics',
    'stats.storyReadingAnalytics.title': 'Reading analytics',
    'stats.storyReadingAnalytics.uniqueReaders': 'Unique readers',
    'stats.storyReadingAnalytics.returningReaders': 'Returning readers',
    'stats.storyReadingAnalytics.averageSessionsPerReader': 'Average sessions per reader',
    'stats.storyReadingAnalytics.bestQuarter': 'Best quarter',
    'stats.storyReadingAnalytics.quarterTable': 'Quarterly breakdown',
    'stats.storyReadingAnalytics.weekHour': 'Reader activity by week and hour',
    'stats.storyReadingAnalytics.weekHourTooltip': '{day} at {hour}: {readers, number} readers, {sessions, number} sessions, {duration}',
    'stats.storyReadingAnalytics.topWindows': 'Top reading windows',
    'stats.storyReadingAnalytics.loadError': 'Failed to load reading analytics',
    // Writing history summary cards
    'stats.writingHistory.diaryWords': 'Palabras del diario',
    // Writing history day tooltip - per-category breakdown
    'stats.writingHistory.dayTooltip.stories': 'Historias: {words}',
    'stats.writingHistory.dayTooltip.encyclopedia': 'Enciclopedia: {words}',
    'stats.writingHistory.dayTooltip.blog': 'Blog: {words}',
    'stats.writingHistory.dayTooltip.diary': 'Diario: {words}',
    // Sales tab — 'Encyclopedia' reuses common.encyclopedia
    'stats.section.sales': 'Sales',
    // Sales summary cards
    'stats.sales.totalPurchases': 'Total Purchases',
    'stats.sales.totalRevenue': 'Total Revenue',
    'stats.sales.totalRefunds': 'Refunds',
    'stats.sales.purchasesByType': 'Purchases by Type',
    'stats.sales.type.story': 'Full story: {count}',
    'stats.sales.type.arc': 'Arc: {count}',
    'stats.sales.type.translation': 'Translation: {count}',
    // Sales sections — 'Payment history' heading reuses payment.history.title
    'stats.sales.stripePayments.description': 'Recorded Stripe payments for this story.',
    'stats.sales.stripePaymentsUniverse.description': 'Recorded Stripe payments for stories in this universe.',
    'stats.sales.history.type': 'Type',
    'stats.sales.history.status': 'Status',
    'stats.sales.history.status.refunded': 'Refunded',
    'stats.sales.product.story': 'Historia completa',
    'stats.sales.product.translation': 'Translation',
    'stats.sales.product.arc': 'Arc',
    'stats.sales.noData': 'No sales data yet. Sales will appear here once readers purchase your story.',
    'stats.sales.noDataUniverse': 'No sales data yet. Sales will appear here once readers purchase stories in this universe.',
    // Universe sales — 'Story' column reuses common.story
    'stats.sales.perStory': 'Sales by Story',
    'stats.sales.perStory.purchases': 'Purchases',
    'stats.sales.perStory.revenue': 'Revenue',
    // Workshop sales overview
    'stats.sales.overview.title': 'Sales Overview',
    'stats.sales.overview.description': 'Overview of all your sales across stories.'
};