export default {
  'courses.courses': 'སློབ་ཚན།',
  'courses.overview': 'སློབ་ཚན་གྱི་སྐོར་འགྱུར།',
  'courses.public.title': 'Explore Courses',
  'courses.public.heading': 'Explore Courses',
  'courses.public.filters': 'Filter Courses',
  'courses.public.noResults': 'No courses found',
  'courses.public.tryDifferentFilters': 'Try different search terms or filters',
  'courses.filter.search': 'Search courses...',
  'courses.filter.allTypes': 'All Types',
  'courses.filter.clearAll': 'Clear All',
  'courses.filter.type': 'Type',
  'courses.type.course': 'Course',
  'courses.type.workshop': 'Workshop',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Course',
  'courses.type.workshop.lowercase': 'Workshop',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'སློབ་ཚན་གསར་འགྱུར་གསར་བསྐྱར།',
  'course.reading.title': 'སློབ་ཚན་གྱི་མིང་འདི།',
  'course.question.add': 'དྲི་བ་གི་འདི་གིས་ །',
  'course.add.courseElement': 'Add a new course element',
  'course.lessons.newMessage':
    'སློབ་ཚན་ཡོད་རེ་བཞིན་པའི་སློབ་བརྡ་བསྐུལ་སྡེ་ཚན་ནང་བསྐུལ་གྱི་རན་པའི་དངུལ་བསྲིེགས་བཏུབ་པ་ལག་ལེན་མཐོང་བ་དང་དངུལ་ཡོད་པའི་སློབ་གཉེར་བྱེད་པ་གསོག་ལེན་བཏུབ་པའི་ཚད་མེད་པའི་དཔེ་ཚོགས་རྒྱས་བཤེས་པའི་ཞིབ་དཔྱད་བསྐྱེད་པའི་སློབ་བརྡ་གྱི་གནད་དོན་ལས་དཔྱེ་ཚོགས་ནག་པོ་གསོ།',
  'course.reading.new': 'སློབ་ཚན་གཉིས་པ།',
  'course.reading.newMessage':
    'ཁྱེད་རང་དྲི་བའི་གནད་དོན་བརྡ་གྱི་སློབ་ཚན་གྱི་ནང་དོན་ཚེས་པ་རྣམ་གཞག་བསྐུལ་རིན་པོར་གྱི་སློབ་བརྡ།',
  'course.writing.new': 'བརྡ་རྗེའི་ལས་ཁུངས།',
  'course.writing.newMessage':
    'འགྲུབ་ཐབས་སྦྱོར་སྐྱོང་བརྡའི་གནད་དོན་གྱི་སློབ་ཚན་གྱི་ནང་དོན་སློབ་བསྡོམས་འགའ་བསྐུར་བཅུད་པ་ན་སྤྱིར་འཕྲོད་དེ་འདི་བསྐྱེད་པའི་གནད་དོན་བསྐུལ་དང་བསྒང་བའི་དཔེ་ཚོགས་གཅེས་པའོ།',
  'course.question.text': 'ཁྱོད་ཀྱི་འབྲེལ་ལམ་བྱེད་པ།',
  'course.question.type': 'དྲི་བ་ཚད་བཀོལ་ནང་འདུག་པ།',
  'course.question.delete': 'དྲི་བ་བོད་ཚན་གསར་བཟུམ།',
  'course.type': 'Course Type',
  'course.visibility': 'སློབ་ཚན་བརྗོད་སྒྲིག་གི་གསལ་བཀོད།',
  'course.title': 'མགོ་མང་།',
  'course.description': 'འགོ་བཙུགས།',
  'course.cover': 'ལས་ཁུངས།',
  'course.start': 'ཁྱོད་རའི་སློབ་དཔོན་འགོག་པའི་འགྱུར།',
  'course.ends': 'ཁྱོད་རའི་སློབ་དཔོན་གསར་པ།',
  'course.curriculum': 'Course Curriculum',
  'course.members': 'སློབ་ཁྱིམ་ལས་དང་སློབ་དཔོན།',
  'course.assignments': 'Assignments',
  'course.question.deleteWhole': 'འདེམས་པས་དྲི་བའི་འདྲེན་པ་བཏོན་པས།',
  'course.question.yes': 'གདམ་ཁ།',
  'course.question.no': 'མེད།',
  'course.lesson.title': 'Lesson title',
  'course.lesson.add.universe': 'Add Story/Universe',
  'course.lesson.externalLinks': 'External links',
  'course.lesson.add.link': 'Add external link',
  'course.status': 'Status',
  'course.active': 'Activity',
  'course.active.message': 'Active',
  'course.inactive': 'Inactive',
  'course.module.edit': 'Edit module name',
  'course.upload.resource': 'Upload a resource',
  'course.question.answer': 'Add answer',
  'course.question.open': 'Open question',
  'course.question.close': 'Closed question',
  'course.question.multiple': 'Multiple-choice question',
  'course.about': 'About this course',
  'course.lesson.new': 'Create a new lesson',
  'course.lesson.type': 'Lesson type',
  'course.lesson.inPerson': 'In person',
  'course.lesson.preRecorded': 'Pre-recorded',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Text only',
  'course.lesson.content': 'Lesson content',
  'course.lesson.description': 'Public description',
  'course.add.module': 'Add new module',
  'course.add.story': 'Add story',
  'course.remove.story': 'Remove story',
  'course.dateOfPublish': 'Date of publishing',
  'course.lesson.meetInPerson': 'Meet in person',
  'course.curriculum.edit': 'Edit curriculum',
  'course.stories.own': 'Your own stories',
  'course.stories.organization': 'Organization stories',
  'course.stories.public': 'Public stories',
  'course.publish.at': 'I want this course to be published at:',
  'course.edit.curriculum': 'Edit curriculum',
  'course.assignment': 'Assignment',
  'course.lesson.removeLink': 'Remove link',
  'course.user.remove': 'Remove user',
  'course.user.invite': 'Invite user',
  'course.user.invited': 'Invited',
  'course.edit.role': 'Edit role',
  'course.assignment.description': 'Assignment description',
  'course.internal': 'Internal',
  'course.free': 'Free',
  'course.sale': 'Sale',
  'course.announcements': 'Announcements',
  'course.announcements.full': 'Course announcements',
  'course.announcements.create': 'Create an announcement',
  'course.join': 'Join Course',
  'course.joining': 'Joining...',
  'course.join.success': 'You have successfully joined this course!',
  'course.join.error.payment': 'This course requires payment to join.',
  'course.join.error.invite': 'This course requires an invitation to join.',
  'course.join.error.generic': 'There was an error joining the course. Please try again.',
  'course.firstLesson': 'First Lesson',
  'course.upcomingLessons': 'Upcoming Lessons',
  'course.detail.title': '{courseName} | Course',
  'lessons.visibility.public': 'Public',
  'lessons.visibility.private': 'Private',
  'course.curriculum.empty': 'No curriculum items available yet.',
  'course.preview.message': 'This is a preview of the course. Join the course to access all content.',
  'course.modules.locked': '{count} more {count, plural, one {module} other {modules}} (locked)',
  'course.details': 'Course Details',
  'course.tab.curriculum': 'Curriculum',
  'course.tab.details': 'Course Details',
  'course.duration': 'Duration',
  'course.perpetual': 'Perpetual',
  'course.language': 'Language',
  'course.price': 'Price',
  'course.learningObjectives': 'Learning Objectives',
  'course.prerequisites': 'Prerequisites',
  'course.tags': 'Tags',
  'course.stats.members': 'Members',
  'course.stats.modules': 'Modules',
  'course.stats.lessons': 'Lessons',
  'course.assignments.comingSoon': 'Assignments view is coming soon.',
  'course.progress.comingSoon': 'Progress tracking is coming soon.',
  'course.type.free': 'Free',
  'course.type.paid': 'Paid',
  'course.type.forSale': 'For Sale',
  'course.type.invite': 'Invite Only',
  'courses.invites.tile': 'You are invited to partake in {count, plural, one {course} other {courses}}.',
  'courses.invites.noInvites': "You don't have any course invitations at the moment.",
  'courses.invites.invitedBy': 'Invited by: ',
  'courses.invites.accept': 'Accept',
  'courses.invites.reject': 'Reject',
  'course.join.heading': 'Join This Course',
  'course.oneTimePayment': 'One-time payment for full access',
  'course.member': "You're Enrolled",
  'course.member.access': 'You have full access to all course materials.',
  'courses.members.editRole': 'Edit Role',
  'courses.members.editRoleFor': 'Edit role for:',
  'courses.add.member': 'Add a new member',
  'course.member.options': 'Course member list',
  'course.navigation.curriculum': 'Curriculum',
  'course.navigation.members': 'Students & Teachers',
  'course.navigation.assignments': 'Assignments',
  'course.navigation.forums': 'Forums',
  'course.navigation.attendance': 'Attendance',
  'course.members.teachers': 'Teachers',
  'course.members.students': 'Students',
  'course.members.preview.message': 'Join this course to see all students and interact with the community.',
  'course.member.role.owner': 'Owner',
  'course.member.role.teacher': 'Teacher',
  'course.member.role.student': 'Student',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'contentSelector.noSelection': 'No item selected',
  'contentSelector.selectedItems': 'Selected items',
  'contentSelector.entireSite': 'Entire site',
  'contentSelector.myLibrary': 'My library',
  'contentSelector.tabsLabel': 'Search options',
  'contentSelector.title': 'Select Content',
  'course.startDate': 'Start Date',
  'course.endDate': 'End Date',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Curriculum Preview',
  'course.curriculum.preview.message': 'Join this course to access all {count} lessons and assignments.',
  'course.curriculum.locked': 'Locked',
  'course.curriculum.module': 'Module',
  'course.curriculum.lesson': 'Lesson',
  'course.curriculum.assignment': 'Assignment',
  'course.curriculum.reading': 'Reading',
  'course.lesson.backToCurriculum': 'Back to Curriculum',
  'course.lesson.nextLesson': 'Next Lesson',
  'course.lesson.documents': 'Documents & Resources',
  'course.lesson.meetingLink': 'Meeting Link',
  'course.lesson.location': 'Location',
  'course.lesson.virtualClassroom': 'Virtual Classroom',
  'course.lesson.joinClassroom': 'Join the virtual classroom session',
  'course.lesson.enterClassroom': 'Enter Classroom',
  'courses.module.defaultTitle': 'Module {count, number}',
};
