export default {
    'workshop.title': 'ཁྱོད་རའི་ལས་བརྟེན།',
    'workshop.noneassigned': 'ཁྱོད་རའི་ལས་བརྟེན་མི་འདུག་མེད།',
    'workshop.notavailable': 'གནས་སྐབས་བརྟེན་མི་འདུག་མེད་འདོན་མི་འགོ་བ་མེད།',
    'workshop.none': `You currently have no {type, select,
      universe {universe}
      story {story}
      fanfiction {fan fiction}
      other {}
    }. Create one now!`,
    'workshop.collab': 'ཁྱོད་རའི་ལས་བརྟེན་གསལ་བཤད།',
    'workshop.betareadings': 'བརྟེན་འདི་འདི་གི་འགོ་བ་མེད།',
    'workshop.translations': 'Translations',
    'workshop.createnew': 'Create new...',
    'workshop.story.standalone': 'Standalone story',
    'workshop.story.standalone.desc': 'This is a standalone story.',
    'workshop.controlpanel': '{name} control panel',
    'workshop.universe.page': 'Universe page',
    'workshop.fictionaltime': 'Fictional time',
    'workshop.dashboard.name': '{name} dashboard',
    'workshop.stories.in': 'Stories in {universe}',
    'workshop.universe.nostories': 'There are no stories in this universe.',
    'workshop.story.chapter.add': 'New chapter',
    'workshop.universe.new': 'Create a new universe',
    'workshop.universe.publish': 'Publish universe',
    'workshop.universe.publishing.notice': 'If you do not publish the universe, it will be published automatically when the first story connected to the universe is published.',
    'workshop.universe.settings': '{universe} universe settings',
    'workshop.universe.publishedOn': 'This universe has been published on {date, date, long} {date, time, short}',
    'workshop.universe.description': 'Universe description',
    'workshop.settings.title': 'Title',
    'workshop.description': 'Description',
    'workshop.language.primary': 'སྒྲོག་འཛུལ་གྱི་སྐད་ཡིག།',
    'workshop.publication.options': 'Publication options',
    'workshop.rating': 'General rating',
    'workshop.universe.rating.desc': 'Stories and fanfiction above this rating will be hidden from the universe page listing from anonymous users and users who are not of the appropriate age.',
    'workshop.universe.license': 'Universe license',
    'workshop.universe.genre.pick': 'Select genre for the universe',
    'workshop.story.genre.pick': 'Select genres for the story',
    'workshop.cover': 'Cover',
    'workshop.nothingtosee': 'Nothing to see here...',
    'workshop.story.cannon': 'Canon story',
    'workshop.story.cannon.desc': 'This story is canonical in {universe} universe.',
    'workshop.story.cannon.desc.create': 'This story will be created as a canonical story in {universe} universe.',
    'workshop.story.fanfiction.search': 'Type in the name of the universe (it needs to be in your library). And then select from suggestions.',
    'workshop.story.error.nogenres': 'You need to select at least one genre.',
    'workshop.story.error.toomanygenres': 'Only two genres per story are allowed.',
    'workshop.story.error.fanfiction.selectuniverse': 'You need to select original universe for your fan fiction!',
    'workshop.story.error.tags.toomany': 'You can only have 10 tags per story.',
    'workshop.story.new': 'Create a new story',
    'workshop.story.publishing.notice': 'The story will be published automatically once you publish the first chapter.',
    'workshop.settings.edit': 'Edit settings',
    'workshop.story.publishedOn': 'This story was published on {date, date, long} {date, time, short}',
    'workshop.story.settings': 'Story settings',
    'workshop.settings.basic': 'Basic settings',
    'workshop.settings.genres': 'Genres (max 2)',
    'workshop.story.license': 'Story license',
    'workshop.story.settings.universe': 'Universe settings',
    'workshop.settings.tags': 'Tags',
    'workshop.revision': 'Revision',
    'workshop.revisions.title': '{story}: {chapter} Revisions',
    'workshop.revisions.current': 'Current draft',
    'workshop.revisions.new.beta': 'Create a new revision out of the draft.',
    'workshop.revisions.new.public': 'Create a new public revision out of the draft.',
    'workshop.revisions.toeditor': 'Go to the editor',
    'workshop.revisions.comments': 'Revision comments',
    'workshop.revisions.comments.title': '{story}: {chapter} - Revision {revision} - Comments',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {for Beta readers}
      readers {Public}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'You need to create a revision first.',
    'workshop.revisions.comments.select': 'སོར་བཞག་འབད་བཅུག',
    'workshop.collaborators.noresults': 'གྲུབ་འབྱུང་མེད་པར་བཟོ་མི།',
    'workshop.collaborators.add.beta': 'བསྣམ་འཛིན་གཏན་འཁེལ་བཞག་པ།',
    'workshop.collaborators.add.collaborator': 'གཞན་ལྷག་གཏན་འཁེལ་བཞག་པ།',
    'workshop.collaborators.add.translator': 'བསྣམ་གྲུབ་གཏན་འཁེལ་བཞག་པ།',
    'workshop.collaborators.language.add': 'སྐད་བརྗོད་གསར་བསྒྱུར་གཏན་འཁེལ་བཞག་པ།',
    'workshop.translations.stories': 'བསྣམ་གྲུབ་ཚུ་གི་གྲོགས་པར།',
    'workshop.translations.universes': 'གསར་བསྒྱུར་ཚུ་གི་གྲོགས་པར།',
    'workshop.revisions.beta.none': 'ད་མ་བསྣམ་པར་མི་མེད།',
    'reader.asidetoggle': 'དཔེ་མཛོད་འབྱིན་པ་གཞི་བཞག་པ།',
    'workshop.translation.original': 'སྒྲིག་བཅོས་:',
    'workshop.translation.original.title': 'སྒྲིག་བཅོས་གནས་སྤྱོད་:',
    'workshop.translation.original.description': 'སྒྲིག་བཅོས་བཀོད་པ་གནས་སྤྱོད་:',
    'workshop.translation.original.cover': 'སྒྲིག་བཅོས་བརྗོད་པ།',
    'workshop.translation.original.tags': 'སྒྲིག་བཅོས་ཚིག་ཡིག་པ།',
    'workshop.cover.alt': 'གོམ་པར་རིགས།',
    'workshop.translation.updatedOrig': 'སྙོམས་གནས་གསར་བསྒྱུར་དང་འབྱུང་གཏན་འཁེལ་བཞག་པ། {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'སྙོམས་གནས་གསར་བསྒྱུར་དང་སྐད་བརྗོད་གཏན་འཁེལ་བཞག་པ། {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'མགོ་རིམ་གནས་གསར་བསྒྱུར་དང་སྙོམས་གནས་གསར་བསྒྱུར་གནང་གི་ལོ་རྒྱུས་ {revision, number}, སྒྲིག་བཅོས་: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'མགོ་རིམ་གནས་གསར་བསྒྱུར་དང་སྙོམས་གནས་གསར་བསྒྱུར་གནང་གི་ལོ་རྒྱུས་ {revision, number}, སྒྲིག་བཅོས་: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `To add more {type, select,
    collaborator {collaborators}
    beta {beta readers}
    translator {translators}
    other {}
  }, you need to increase your membership tier.`,
    'workshop.collaborators.requests.sent': 'འཕྲིན་ལས་འཛིན་པ།',
    'workshop.collaborators.requests.invite': `You have been invited to become {role, select,
    beta {beta reader}
    translator {translator}
    collaborator {collaborator}
    other {}
  } for the following:`,
    'workshop.collaborators.requests.dashboard': `You have been invited to collaborate on {count, plural,
    zero {no work}
    one {one literary work}
    other {# literary works}
  }.`,
    'workshop.collaborators.language.added': 'Language added',
    'workshop.story.noChaptersFound': 'No chapters found.',
    'workshop.fanfic.needUniverseInLibrary': 'There are many universes out there. Please add the ones you want to write in into your library first so that we can find them.',
    'workshop.fanfic.findUniverse': 'Go find an amazing universe!',
    'workshop.encSettings': 'Encyclopedia settings',
    'workshop.collaborators.removeUser': 'Remove user',
    'workshop.collaborators.cancelInvite': 'Cancel invite',
    'workshop.universe.createFirstStory': 'Create the first story',
    'workshop.storylines': 'Storylines',
    'workshop.scenesManager': 'Scenes Manager',
    'workshop.collaborators.addRoleForLang': 'Add {role} for {language}',
    'workshop.beta.revisionInfo': 'This is revision {revision, number}, created on {createdAt, date, long}.',
    'workshop.story.notes.title': 'Your notes for {storyTitle}',
    'workshop.story.notes.desc': 'Overview notes for the story.',
    'workshop.story.notes.tile': 'Overview notes',
    'workshop.hideOrgs': 'Hide content from organizations',
    'workshop.translation.premium': 'In order to add translations, you need to have at least Explorer subscription.',
    'workshop.story.finished': 'Story is complete',
    'workshop.story.publishing.externalSellingNotice': 'Since you are selling outside of Literary Universe you can publish the story now. Links to your store listing will appear on the story or at the end of the current story you publish here.',
    'workshop.sharing.publicURL': 'Public version',
    'workshop.fictionalTime.title': 'Fictional times for {universeName}',
    'workshop.fictionalTime.none': 'You currently don\'t have any fictional times set-up.',
    'workshop.fictionalTime.createNow': 'Create one now!',
    'workshop.fictionalTime.createTitle': 'Create a new fictional time',
    'workshop.fictionalTime.editTitle': 'Edit {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'Time name',
    'workshop.fictionalTime.basicInfo': 'Basic information',
    'workshop.fictionalTime.timeSetup': 'Time setup',
    'workshop.fictionalTime.linkedToET': 'Does this time start on an Earth date (Gregorian calendar)?',
    'workshop.fictionalTime.timeDeclaration': 'Time declaration',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'Before units',
    'workshop.fictionalTime.declarationAfter': 'After units',
    'workshop.fictionalTime.declarationNone': 'None',
    'workshop.fictionalTime.units': 'Units',
    'workshop.fictionalTime.ETStart': 'Starting date of this time',
    'workshop.fictionalTime.unitsDescFirst': 'How many units are there in this unit from milliseconds?',
    'workshop.fictionalTime.unitsDesc': 'How many units is this one from the previous one?',
    'workshop.fictionalTime.unitsName': 'Unit name',
    'workshop.fictionalTime.unitsSeparator': 'Separator from previous unit',
    'workshop.fictionalTime.unitAdd': 'Add unit',
    'workshop.fictionalTime.clocks': 'Clocks',
    'workshop.fictionalTime.unitTransfer': 'Transfer units',
    'fictionalTime.pageStartElapsedTime': 'Time elapsed since opening this page',
    'fictionalTime.currentTime': 'Current time',
    'workshop.shoppingExternal.options': 'External purchase options',
    'workshop.shoppingExternal.explainer': 'If your story is sold elsewhere you can set the links here. The links will then show instead of the content or at the end of the content you choose to preview.',
    'workshop.shoppingExternal.amazonStore': 'Amazon store',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Store name',
    'workshop.shoppingExternal.itemUrl': 'Item URL',
    'workshop.shoppingExternal.storesOther': 'Other stores',
    'fictionalTime.units.milliseconds': '{units, number} milliseconds',
    'fictionalTime.countdownToStart': 'Countdown to time beginning',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 day }
      other {{days} days }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {སྐར་མ།}
      other {སྐར་མ་ཚུ།}
    }}
    minutes {{units, plural,
      one {ཆུ་ཚོད།}
      other {ཆུ་ཚོད་ཚུ།}
    }}
    hours {{units, plural,
      one {ཆུ་ཚོད།}
      other {ཆུ་ཚོད་ཚུ།}
    }}
    days {{units, plural,
      one {ཉིན།}
      other {ཉིན་ཚུ།}
    }}
    years {{units, plural,
      one {ལོ་ཁམས།}
      other {ལོ་ཁམས་ཚུ།}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'From',
    'fictionalTime.inputSelectTimeUnit': 'Select time unit',
    'fictionalTime.inputSelectETUnit': 'Select Earth time unit',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Sidebar Toolbox',
    'workshop.writerSidebar.description': 'Welcome to your story! This sidebar allows you easy access to all resources related to your story. Check the icons above to see latest comments, your notes and much more!',
    'workshop.story.authorsNotesExplained': 'ཁྱེད་ཀྱི་བཅོས་པ་ནང་གི་དངོས་གྲུབ་པའི་འགྲེལ་བཤད་ནང་བཀོད་པའི་བརྗོད་པ་ཚུ་གི་དོན་ལུ་གྲོལ་བར་བཀོད་པའི་བཅོས་པ།',
    'workshop.story.chapterSortSwitch': 'བཅོས་པ་གནང་དུ་བཟོ་བ་བཞག་པ།',
    'workshop.universe.monetizationTitle': '{title} monetization',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} monetization',
    'workshop.universe.monetizationWebMonetization': 'ཝེབ་མོ་ནིཊི་གི་དོན་ཚན་བྱེད་པ།',
    'workshop.webMonetization.explain': 'Web Monetization will stream payments to you based on how much time user spends on your content. In your profile monetization settings you can set your own payment pointer. Here you can decide on a split with your collaborators who have Web Payment enabled. Literary Universe automatically takes 10%.',
    'workshop.webMonetization.revShare': 'Due to the limitation of Web Monetization probabilistic revenue sharing is used. Probabilistic revenue sharing works by randomly choosing from a list of predefined payment pointers each time a web monetized visitor loads your page. The visitor pays to the chosen pointer until the page is reloaded or closed.',
    'workshop.webMonetization.revShareMore': 'Learn more about Probabilistic Revenue Sharing. We use the same code as on that page.',
    'workshop.story.notEligible.licence': `The story's license does not allow for monetization.`,
    'workshop.universe.notEligible.licence': `The universe's license does not allow for monetization.`,
    'workshop.story.notEligible.fanFiction': 'Fan Fiction stories are not eligible for monetization.',
    'workshop.revShare.mustBe100': 'Share must equal 100%',
    'workshop.revShare.LUCut': 'Literary Universe & payment gate',
    'workshop.revShare.unallocated': 'Unallocated share {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'Undecided',
    'workshop.revShare.origLangCreators': 'Original language creators',
    'workshop.story.prolog': 'Prolog',
    'workshop.story.chapter': 'Chapter {sequence, number}',
    'workshop.work.includesAds': 'Are there any advertisements or product placements in the work?',
    'workshop.universe.forumSettings': 'ཆོས་ཀྱི་འབྱུང་གནས་སྒྲིག་འཐུས་པའི་གནས་ཚུལ་གྱི་དོན་སྒྲིག་གསར་བསྐྱེད་ཀྱི་དགོས་པའི་གནས་ཚུལ།',
    'workshop.universe.forum': 'ཆོས་ཀྱི་ {universeName} གནས་ཚུལ་གྱི་དོན་སྒྲིག་གསར་བསྐྱེད།',
    'workshop.ratingAdjusted': 'Due to complains we had to adjust your rating to the one that we felt appropriate. As such changing the rating is now disabled.',
    'workshop.selectCollaborator': 'Select collaborator',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Draft',
    'workshop.chapterStatus.scheduled': 'Scheduled',
    'workshop.chapterStatus.published': 'Published',
    'workshop.story.continuedIn': 'Which stories continue this story?',
    'workshop.story.continuedPlaceholder': 'Select story from this universe',
    'workshop.universe.isAIGenerated': 'Is the content of the universe generated by AI?',
    'workshop.universe.isAIGeneratedTooltip': 'Please let us know if any of the content in the universe was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.story.isAIGenerated': 'Is the story generated by AI?',
    'workshop.story.isAIGeneratedTooltip': 'Please let us know if any of the story was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.publicationAgreement.aria': 'Publication agreement for work',
    'workshop.publicationAgreement.intro': 'We are happy that you have chosen to publish your creative work with us. Before we proceed we just need you to look over our publication agreement, to understand what it means from the legal side of things.',
    'workshop.sortChapters': 'Sort order:',
    'workshop.sortChapters.ascending': 'From beginning',
    'workshop.sortChapters.descending': 'From latest',
    'workshop.sortChapters.aria': 'Select for which way to sort chapter listing',
    'workshop.hiatus.btn': 'Change story status to Hiatus',
    'workshop.cancelled.btn': 'Change story status to Cancelled',
    'workshop.complete.btn': 'Change story status to Completed',
    'workshop.statusChange.modalTop': 'Are you sure you want to change the status to',
    'workshop.statusName.hiatus': 'Hiatus',
    'workshop.statusName.cancelled': 'Cancelled',
    'workshop.statusName.completed': 'Completed',
    'workshop.statusExplain.hiatus1': 'Hiatus means that you are stepping away from working on this story for a while for what ever reason. It will tell your readers that they should not expect any new updates in the coming weeks or even up to few months.',
    'workshop.statusExplain.hiatus2': 'The hiatus status will be automatically lifted if you publish any chapter. Or you can change it your self.',
    'workshop.statusExplain.hiatus3': 'If you keep your story in hiatus for six months, we will automatically mark this story as cancelled.',
    'workshop.statusExplain.cancelled1': 'We are sorry to hear that you can\'t continue working on the story. On the other hand we are happy that you are willing to let your readers know.',
    'workshop.statusExplain.cancelled2': 'Cancelling story will let your readers know that they should not expect any new updates.',
    'workshop.statusExplain.cancelled3': 'You can always revert this by publishing a chapter or changing the status.',
    'workshop.statusExplain.finished1': 'Congratulations! After all that hard work you have finally reached the end of an incredible journey. While the story might end now, we hope that there will be more stories to tell in the future, but for now, relax and enjoy the well earned rest.',
    'workshop.statusExplain.finished2': 'Marking story as complete will tell the readers that the story is finished. While you shouldn\'t be adding any new chapters we won\'t stop you and adding special chapters isn\'t a bad idea, to for example add more epilogues for all characters.',
    'workshop.statusExplain.finished3': 'While you can always cancel this status we highly advice against it. If the story is to continue it might be better to start a new story.',
    'workshop.status.goActive': 'Make the story active again',
    'workshop.statusChangeEmail.storyIntro': 'We would like to inform you that your story:',
    'workshop.statusChangeEmail.hiatusTitle': 'Your story status was automatically set to hiatus',
    'workshop.statusChangeEmail.hiatusIntro': 'Due to inactivity your story status was automatically set to hiatus.',
    'workshop.statusChangeEmail.hiatusWhy': 'Has been automatically put on hiatus due to no new chapter being published for over 6 months.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'This status will be automatically lifted if you publish a new chapter. If you don\'t publish a new chapter in the next 6 months we will automatically set the story as cancelled.',
    'workshop.statusChangeEmail.cancellationIntro': 'Your story status was automatically set to cancelled.',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'This status will be automatically lifted if you publish a new chapter. If you don\'t plan to work on this story anymore there is nothing else that you need to do.',
    'workshop.startCreating': 'Start creating',
    'workshop.ownWork': 'Own work',
    'workshop.list.thumbs': 'Thumbnails list',
    'workshop.list.list': 'Short list',
    'workshop.fanfiction.new': 'Create a new fan fiction',
    'workshop.videoTrailerLink': 'བརྗོད་ནང་གློག་བཀོད་པའི་ལས་བརྟེན་འདི་ལྟ་བུའི་ཐིག་ཁྲོམ་ལས་གནས་སྐབས་ཀྱི་ཡིག་སྣོད་བྱེད་པའི་ཐིག་ཁྲོམ་འདི་གིས་ཁྱོད་ཀྱིས་འགྲེལ་བཤད་ནས་བཏོན་གཏང་འབད་བས།',
    'workshop.videoTrailerPlayerTitle': 'བརྗོད་ནང་གློག་བཀོད་པའི་གློག་བཀོད་པའི་ནང་གི་བརྗོད་ཀྱི་གློག་བཀོད་པའི་ཐིག་ཁྲོམ་འདི་ལས་བརྟེན་འདི་བཟོ་བཏུབ་པའི་ཐིག་ཁྲོམ་འདི་གིས་ཁྱོད་ཀྱིས་འགྲེལ་བཤད་ནས་བཏོན་གཏང་འབད་བས།',
    'workshop.videoTrailer.supportedPlaftorms': 'ངོས་ལེན་འདི་གིས་ ཡུ་གྲོལ་འདི་དང་ བེ་ལུ་ཡིན་ནམ་ལས་ ཨོ་དོ་འདི་དང་ ཨོ་དོ་འདི་སྤྱོད་པ་ཡོད།',
    'workshop.videoTrailer.rumble': 'བདེ་བ་འདི་ལས་བརྟེན་གྱི་བདེབ་འདི་གི་དོན་ལུ་ Rumble གི་དོན་ལུ་བཟོད་པས་བཟུང་བའི་URL གི་སྒྲིག་འོང་།',
    'workshop.videoTrailer.suggestPlatforms': 'ཁྱེད་ཀྱི་ནང་བདེན་གསརཔ་འདི་མིན་འདུག སྤྱི་ཚོགས་པའི་གྲོགས་འབྱོར་འདི་ལས་འགོ་བཙུགས་པའི་<a>བསམ་ཚུལ་</a>བཟོ་ཡོད།',
    'workshop.cover.edit': 'Change cover',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.',
    'workshop.license.exclusiveUniverse': 'The universe uses an exclusive license, which means that all stories also have to follow the same license in order to prevent legal chaos.',
    'workshop.theWay.overallStats.genresDesc': 'Genres you write in',
    'workshop.theWay.overallStats.universeViewsDesc': 'Total views across all your universes',
    'workshop.theWay.overallStats.storyViewsDesc': 'Total views across all your stories',
    'workshop.theWay.overallStats.uniqueReadersDesc': 'Unique visitors who have read your stories',
    'workshop.theWay.overallStats.followersDesc': 'People who follow your work',
    'workshop.theWay.overallStats.fansDesc': 'People who have subscribed to your fan club',
    'workshop.theWay.overallStats.encyclopediaEntriesDesc': 'Total encyclopedia entries you have created',
    'workshop.theWay.overallStats.wordCountDesc': 'Total words across all your stories',
    'workshop.theWay.overallStats.chaptersDesc': 'Total chapters you have written',
    'workshop.theWay.overallStats.universesDesc': 'Total universes you have created',
    'workshop.theWay.overallStats.storiesDesc': 'Total stories you have published'
};