/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'Literary Universe',
    'site.description': 'Literary Universe ist eine Kreativ- und Publishing-Plattform für große Story-Universen.',
    'site.keywords': 'kreatives Schreiben, Scifi, Sci-Fi, Fantasie, Schreiben, Veröffentlichen, Übersetzungen, Geschichten, Universum',
    'site.logoAlt': 'Literarische Universe Logo',
    mobileMenu: 'Mobiles Menü',
    'common.signin': 'Anmelden',
    'common.signup': 'Registrieren',
    'common.signout': 'Abmelden',
    'common.dashboard': 'Dashboard',
    'common.discovery': 'Entdeckung',
    'common.library': 'Bibliothek',
    'common.library.own': 'Deine Bibliothek',
    'common.workshop': 'Werkstatt',
    'common.pm': 'Meldungen',
    'common.settings': 'Einstellungen',
    'common.options': 'Optionen',
    'common.profile': 'Profil',
    'common.blog': 'Blog',
    'common.blogs': 'Blogs',
    'common.about': 'Über uns',
    'common.accessdenied': 'Zugriff verweigert',
    'common.accessdenied.msg': 'Sie haben keine Erlaubnis erhalten, hierher zu gehen. Wenn Sie hier Zugang haben sollten, wenden Sie sich bitte an den Eigentümer und bitten Sie ihn, die Einstellungen zu überprüfen.',
    'common.loading': 'Laden...',
    'common.add': 'Hinzufügen',
    'common.save': 'Speichern',
    'common.email': 'E-mail',
    'common.soon': 'Demnächst...',
    'common.search': 'Suche',
    'common.search.do': 'Suchen',
    'common.searching': 'Suchen...',
    'common.report': 'Bericht',
    'common.user': 'Benutzer',
    'common.users': 'Benutzer',
    'common.showmore': 'Mehr anzeigen',
    'common.futurefeature.title': 'Zukünftige Funktion',
    'common.futurefeature.text': 'Es tut uns sehr leid, aber diese Funktion ist zur Zeit nicht verfügbar. Wir arbeiten hart daran, sie so bald wie möglich verfügbar zu machen.',
    'common.nothingfound': 'Nichts gefunden',
    'common.explore': 'Erkunden Sie',
    'common.by': 'von ',
    // keep the space at the end as username follows
    'common.scratchpad': 'Scratchpad',
    'common.scratchpad.own': 'Ihr Scratchpad',
    'common.news': 'Neuigkeiten',
    'common.encyclopedia': 'Enzyklopädie',
    'common.story': 'Geschichte',
    'common.stories': 'Geschichten',
    'common.universe': 'Universum',
    'common.universes': 'Universum',
    'common.collaborator': 'Mitarbeiter',
    'common.collaborators': 'Mitarbeiter',
    'common.translator': 'Übersetzer',
    'common.translators': 'Übersetzer',
    'common.betareader': 'Beta-Leser',
    'common.betareaders': 'Beta-Leser',
    'common.post': 'Beitrag',
    'common.statistics': 'Statistiken',
    'common.lang.select': 'Sprache auswählen',
    'common.submit': 'Senden',
    'common.close': 'Schließen',
    'common.comment': 'Kommentar',
    'common.comments': 'Kommentare',
    404: 'Seite nicht gefunden',
    'search.users': 'Suche nach Benutzern',
    'search.user': 'Suche nach Benutzer',
    'common.help': 'Hilfe',
    'common.or': 'oder',
    'common.account.create': 'Ein Konto erstellen',
    'signup.username': 'Benutzername',
    'signup.email': 'Ihre E-Mail',
    'signup.password.label': 'Ihr Passwort',
    'signup.password.repeat': 'Wiederholen Sie Ihr Passwort',
    'common.password': 'Passwort',
    'signin.password.forgot': 'Passwort vergessen?',
    'dashboard.whatsnew': 'Was ist neu',
    'dashboard.blog': 'Dein Blog',
    'common.footer.tagline': 'Schreiben und Lesen komplexer Universen leicht gemacht.',
    'common.footer.plans': 'Pakete & Preise',
    'common.legal.tos': 'Nutzungsbedingungen',
    'common.legal.community': 'Leitlinien der Gemeinschaft',
    'common.legal.privacy': 'Datenschutzrichtlinie',
    'common.legal.copyright': 'Copyright-Vereinbarung',
    'common.legal.disclaimer': '© {year} Alle Rechte vorbehalten, alle Texte gehören ihren jeweiligen Autoren.',
    'premium.only.title': 'Nicht ausreichend hoher Mitgliedsrang',
    'premium.only.msg': 'Entschuldigung, Ihr Mitgliedsrang ist nicht hoch genug, um auf diese Funktion zuzugreifen.',
    'premium.only.join': 'Wir bieten verschiedene Pläne an, damit jeder das Beste aus Literary Universe herausholen kann.',
    'premium.only.link': 'Check it out!',
    'universe.visit': 'Besuche die Universum Seite',
    'common.fanfiction': 'Fan-Fiktion',
    'story.chapter': 'Chapter',
    'story.chapters': 'Chapters',
    'story.genre': 'Genre',
    'story.genres': 'Genres',
    'story.read': 'Lesen',
    'story.lastUpdate': 'Last updated on {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Finished on {date, date, medium}.',
    'story.comments.for': 'Comments for {story} {chapter}.',
    'story.cover.alt': 'Story cover image for {story}.',
    'story.note.fanfiction': 'HINWEIS: Diese Geschichte ist eine Fan-Fiktion am {universe} Universum.',
    copyrights: 'Copyright',
    'common.challenges': 'Challenges',
    // for beta only
    'beta.notice': 'Welcome to Literary Universe BETA. This is a public preview and as such the app is still work in progress. This means that you can still expect errors and unfinished features. If you encounter an error or something not working please let us know and please be patient while we get get everything in place.',
    'beta.thanks': 'Vielen Dank für Ihre Unterstützung!',
    'scratchpad.about': 'Your notes and ideas accessible anywhere on the site.',
    'common.feedback': 'Feedback',
    'common.createdOn': 'Created on {date, date, long}',
    'common.createdOn.title': 'Created on',
    // account types
    admin: 'Admin',
    goodbye: 'Vielen Dank und auf Wiedersehen!',
    'common.saved': 'Gespeichert!',
    'common.saving': 'Wird gespeichert...',
    'common.friends': 'Freunde',
    'lang.orig': 'Original language',
    'lang.orig.plus': 'Original language - {language}',
    buy: 'Kaufen',
    confirm: 'Confirm',
    cancel: 'Cancel',
    processing: 'Processing...',
    'common.noData': 'No data',
    'error.title': 'An error has occurred. We apologize for the inconvenience.',
    'common.offlineStatus': 'You are currently offline.',
    male: 'Mann',
    female: 'Frau',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: 'Please select',
    'common.statusFailed': 'Failed to connect to the server.',
    'common.statusConnecting': 'Attempting to connect to the server... ({count, number})',
    'slug.checking': 'Checking...',
    'slug.failed': 'This address already exists.',
    'slug.success': 'This address is available!',
    'notVerified.msg': 'Your account e-mail is not verified.',
    'notVerified.verify': 'Please verify your e-mail.',
    unknown: 'unknown',
    'common.legal.guidelines': 'Community Guidelines',
    'errorLoading.title': 'Error during page load',
    'errorLoading.explained': 'An error has occurred while the page was loading. We apologize for the inconvenience. Please retry accessing the page again. If the problem persists, please let us known.',
    'errorLoading.retry': 'Retry!',
    'errorLoading.takingLong': 'This is taking a long time...',
    'common.title': 'Title',
    'common.timelines': 'Timelines',
    'common.legal.gdpr': 'DSGVO',
    'common.legal.gdpr.long': 'Allgemeine Datenschutzverordnung (DSGVO)',
    'editor.placeholder.link': 'URL eingeben...',
    'editor.placeholder.connection': 'Suche nach Enzyklopädie Eintrag...',
    'editor.saved.beta': 'New revision for Beta readers created!',
    'editor.saved.public': 'New version published!',
    goodbyeForever: 'We are sorry to see see you go. Was it something we did? Please let us know if that is the case. Either way we wish you the best in your future endeavors and hopefully we\'ll meet again! Live long and prosper!',
    'goodbyeForever.feedback': 'Let us know what we can do better',
    'common.edit': 'Edit',
    'common.publish': 'Publish',
    'common.publishAt': 'Publication date and time',
    'a11y.user.menu': 'User menu',
    'dashboard.profile': 'Ihr Profil',
    'profile.website': 'Persönliche Webseite',
    'story.notes.concept': 'Konzept',
    'story.notes.settings': 'Story setting',
    'story.notes.theme': 'Theme',
    'story.notes.impact': 'Desired impact',
    'story.notes.outcome': 'Outcome',
    'story.notes.audience': 'Target audience',
    'story.notes.pitch': 'Pitch',
    'story.notes.notes': 'Notes',
    'story.authorsNotes': 'Author\'s notes',
    'common.members': 'Members',
    'common.language': 'Sprache',
    next: 'Next',
    'common.legal.tos.short': 'Terms',
    'common.legal.privacy.short': 'Privacy',
    'premium.increaseLimit': 'Consider upgrading to increase you limit.',
    'common.sharing': 'Sharing',
    'story.isbn': 'ISBN',
    'common.name': 'Name',
    'common.remove': 'Remove',
    'common.time.milliseconds': 'Millisekunden',
    'common.time.seconds': 'Sekunden',
    'common.time.minutes': 'Minuten',
    'common.time.hours': 'Stunden',
    'common.time.days': 'Tage',
    'common.time.weeks': 'Wochen',
    'common.time.months': 'Monate',
    'common.time.years': 'Jahre'
}    /* eslint-enable max-len */;