export default {
  'courses.courses': 'Kurse',
  'courses.overview': 'Kursübersicht',
  'courses.public.title': 'Kurse erkunden',
  'courses.public.heading': 'Kurse erkunden',
  'courses.public.filters': 'Kurse filtern',
  'courses.public.noResults': 'Keine Kurse gefunden',
  'courses.public.tryDifferentFilters': 'Versuchen Sie andere Suchbegriffe oder Filter',
  'courses.filter.search': 'Kurse suchen...',
  'courses.filter.allTypes': 'Alle Typen',
  'courses.filter.clearAll': 'Alles löschen',
  'courses.type.course': 'Kurs',
  'courses.type.workshop': 'Workshop',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Kurs',
  'courses.type.workshop.lowercase': 'Workshop',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'Ein neuer Kurs erstellen',
  'course.reading.title': 'Titel der Leseaufgabe',
  'course.question.add': 'Frage hinzufügen',
  'course.add.courseElement': 'Einen neuen Kursbaustein hinzufügen',
  'course.lessons.newMessage': 'Erstellen und organisieren Sie Ihre Lektionen für einen effektiven Unterricht',
  'course.reading.new': 'Leseaufgabe',
  'course.reading.newMessage': 'Erstellen und organisieren Sie Leseaufträge für Ihre Studenten',
  'course.writing.new': 'Schreibaufgabe',
  'course.writing.newMessage': 'Schnelles Einrichten und Verteilen von Schreibaufgaben',
  'course.question.text': 'Deine Frage hier eingeben',
  'course.question.type': 'Bitte wählen Sie eine Art von Frage',
  'course.question.delete': 'Frage entfernen',
  'course.type': 'Wähle den Kurs-Typ aus',
  'course.visibility': 'Wähle die Sichtbarkeitsoption aus',
  'course.title': 'Titel',
  'course.description': 'Beschreibung',
  'course.cover': 'Titelbild',
  'course.start': 'Dein Kurs beginnt am',
  'course.ends': 'Dein Kurs endet am',
  'course.curriculum': 'Lehrplan',
  'course.members': 'Schüler & Lehrer',
  'course.assignments': 'Zuweisungen',
  'course.question.deleteWhole': 'Ganze Frage löschen',
  'course.question.yes': 'Ja',
  'course.question.no': 'Nein',
  'course.lesson.title': 'Lektionstitel',
  'course.lesson.add.universe': 'Story/Universum hinzufügen',
  'course.lesson.externalLinks': 'Externe Links',
  'course.lesson.add.link': 'Externe Verknüpfung hinzufügen',
  'course.status': 'Status',
  'course.active': 'Aktivität',
  'course.active.message': 'Aktiv',
  'course.inactive': 'Inaktiv',
  'course.module.edit': 'Modulname bearbeiten',
  'course.upload.resource': 'Eine Ressource hochladen',
  'course.question.answer': 'Antwort hinzufügen',
  'course.question.open': 'Offene Frage',
  'course.question.close': 'Geschlossene Frage',
  'course.question.multiple': 'Multiple-Choice-Frage',
  'course.about': 'Über diesen Kurs',
  'course.lesson.new': 'Eine neue Lektion erstellen',
  'course.lesson.type': 'Lektionstyp',
  'course.lesson.inPerson': 'Persönlich',
  'course.lesson.preRecorded': 'Voraufgezeichnete',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Nur Text',
  'course.lesson.content': 'Inhalt der Lektion',
  'course.lesson.description': 'Öffentliche Beschreibung',
  'course.add.module': 'Neues Modul hinzufügen',
  'course.add.story': 'Geschichte hinzufügen',
  'course.remove.story': 'Geschichte entfernen',
  'course.dateOfPublish': 'Datum der Veröffentlichung',
  'course.lesson.meetInPerson': 'Persönlich treffen',
  'course.curriculum.edit': 'Lehrplan bearbeiten',
  'course.stories.own': 'Ihre eigenen Geschichten',
  'course.stories.organization': 'Organisation Geschichten',
  'course.stories.public': 'Öffentliche Geschichten',
  'course.publish.at': 'Ich möchte, dass dieser Kurs veröffentlicht wird unter:',
  'course.edit.curriculum': 'Lehrplan bearbeiten',
  'course.assignment': 'Zuweisung',
  'course.lesson.removeLink': 'Link entfernen',
  'course.user.remove': 'Benutzer entfernen',
  'course.user.invite': 'Benutzer einladen',
  'course.user.invited': 'Eingeladen',
  'course.edit.role': 'Rolle bearbeiten',
  'course.assignment.description': 'Beschreibung der Aufgabe',
  'course.internal': 'Intern',
  'course.free': 'Kostenlos',
  'course.sale': 'Verkauf',
  'course.announcements': 'Ankündigungen',
  'course.announcements.full': 'Kurs-Ankündigungen',
  'course.announcements.create': 'Eine Ankündigung erstellen',
  'course.join': 'Kurs beitreten',
  'course.firstLesson': 'Erste Lektion',
  'course.upcomingLessons': 'Kommende Lektionen',
  'course.detail.title': '{courseName} | Kurs',
  'lessons.visibility.public': 'Öffentlich',
  'lessons.visibility.private': 'Privat',
  'lessons.visibility.hidden': 'Versteckt',
  'courses.members.search.placeholder': 'Suchen Sie nach Benutzer...',
  'course.search.user': 'Suche nach Benutzer',
  'course.user.addFinished': 'Fertige',
};
