export default {
  'courses.courses': 'Kurse',
  'courses.overview': 'Kursübersicht',
  'courses.public.title': 'Kurse erkunden',
  'courses.public.heading': 'Kurse erkunden',
  'courses.public.filters': 'Kurse filtern',
  'courses.public.noResults': 'Keine Kurse gefunden',
  'courses.public.tryDifferentFilters': 'Versuchen Sie andere Suchbegriffe oder Filter',
  'courses.filter.search': 'Kurse suchen...',
  'courses.filter.allTypes': 'Alle Typen',
  'courses.filter.clearAll': 'Alles löschen',
  'courses.filter.type': 'Typ',
  'courses.type.course': 'Kurs',
  'courses.type.workshop': 'Workshop',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Kurs',
  'courses.type.workshop.lowercase': 'Workshop',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'Ein neuer Kurs erstellen',
  'course.reading.title': 'Titel der Leseaufgabe',
  'course.question.add': 'Frage hinzufügen',
  'course.add.courseElement': 'Einen neuen Kursbaustein hinzufügen',
  'course.lessons.newMessage': 'Erstellen und organisieren Sie Ihre Lektionen für einen effektiven Unterricht',
  'course.reading.new': 'Leseaufgabe',
  'course.reading.newMessage': 'Erstellen und organisieren Sie Leseaufträge für Ihre Studenten',
  'course.writing.new': 'Schreibaufgabe',
  'course.writing.newMessage': 'Schnelles Einrichten und Verteilen von Schreibaufgaben',
  'course.question.text': 'Deine Frage hier eingeben',
  'course.question.type': 'Bitte wählen Sie eine Art von Frage',
  'course.question.delete': 'Frage entfernen',
  'course.type': 'Kurs Typ',
  'course.visibility': 'Wähle die Sichtbarkeitsoption aus',
  'course.title': 'Titel',
  'course.description': 'Beschreibung',
  'course.cover': 'Titelbild',
  'course.start': 'Dein Kurs beginnt am',
  'course.ends': 'Dein Kurs endet am',
  'course.curriculum': 'Kurs Curriculum',
  'course.members': 'Schüler & Lehrer',
  'course.assignments': 'Zuweisungen',
  'course.question.deleteWhole': 'Ganze Frage löschen',
  'course.question.yes': 'Ja',
  'course.question.no': 'Nein',
  'course.lesson.title': 'Lektionstitel',
  'course.lesson.add.universe': 'Story/Universum hinzufügen',
  'course.lesson.externalLinks': 'Externe Links',
  'course.lesson.add.link': 'Externe Verknüpfung hinzufügen',
  'course.status': 'Status',
  'course.active': 'Aktivität',
  'course.active.message': 'Aktiv',
  'course.inactive': 'Inaktiv',
  'course.module.edit': 'Modulname bearbeiten',
  'course.upload.resource': 'Eine Ressource hochladen',
  'course.question.answer': 'Antwort hinzufügen',
  'course.question.open': 'Offene Frage',
  'course.question.close': 'Geschlossene Frage',
  'course.question.multiple': 'Multiple-Choice-Frage',
  'course.about': 'Über diesen Kurs',
  'course.lesson.new': 'Eine neue Lektion erstellen',
  'course.lesson.type': 'Lektionstyp',
  'course.lesson.inPerson': 'Persönlich',
  'course.lesson.preRecorded': 'Voraufgezeichnete',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Nur Text',
  'course.lesson.content': 'Inhalt der Lektion',
  'course.lesson.description': 'Öffentliche Beschreibung',
  'course.add.module': 'Neues Modul hinzufügen',
  'course.add.story': 'Geschichte hinzufügen',
  'course.remove.story': 'Geschichte entfernen',
  'course.dateOfPublish': 'Datum der Veröffentlichung',
  'course.lesson.meetInPerson': 'Persönlich treffen',
  'course.curriculum.edit': 'Lehrplan bearbeiten',
  'course.stories.own': 'Ihre eigenen Geschichten',
  'course.stories.organization': 'Organisation Geschichten',
  'course.stories.public': 'Öffentliche Geschichten',
  'course.publish.at': 'Ich möchte, dass dieser Kurs veröffentlicht wird unter:',
  'course.edit.curriculum': 'Lehrplan bearbeiten',
  'course.assignment': 'Zuweisung',
  'course.lesson.removeLink': 'Link entfernen',
  'course.user.remove': 'Benutzer entfernen',
  'course.user.invite': 'Benutzer einladen',
  'course.user.invited': 'Eingeladen',
  'course.edit.role': 'Rolle bearbeiten',
  'course.assignment.description': 'Beschreibung der Aufgabe',
  'course.internal': 'Intern',
  'course.free': 'Kostenlos',
  'course.sale': 'Verkauf',
  'course.announcements': 'Ankündigungen',
  'course.announcements.full': 'Kurs-Ankündigungen',
  'course.announcements.create': 'Eine Ankündigung erstellen',
  'course.join': 'Kurs beitreten',
  'course.joining': 'Beitritt...',
  'course.join.success': 'Sie haben erfolgreich an diesem Kurs teilgenommen!',
  'course.join.error.payment': 'Für die Teilnahme an diesem Kurs ist eine Zahlung erforderlich.',
  'course.join.error.invite': 'Für die Teilnahme an diesem Kurs ist eine Einladung erforderlich.',
  'course.join.error.generic': 'Es ist ein Fehler beim Beitritt zum Kurs aufgetreten. Bitte versuchen Sie es erneut.',
  'course.firstLesson': 'Erste Lektion',
  'course.upcomingLessons': 'Kommende Lektionen',
  'course.detail.title': '{courseName} | Kurs',
  'lessons.visibility.public': 'Öffentlich',
  'lessons.visibility.private': 'Privat',
  'course.curriculum.empty': 'Noch keine Lehrplanartikel verfügbar.',
  'course.preview.message':
    'Dies ist eine Vorschau des Kurses. Melden Sie sich für den Kurs an, um auf alle Inhalte zuzugreifen.',
  'course.modules.locked': '{count} mehr {count, plural, one {Modul} other {Module}} (gesperrt)',
  'course.details': 'Kurs-Details',
  'course.tab.curriculum': 'Lehrplan',
  'course.tab.details': 'Kurs-Details',
  'course.duration': 'Dauer',
  'course.perpetual': 'Ewige',
  'course.language': 'Sprache',
  'course.price': 'Preis',
  'course.learningObjectives': 'Lernziele',
  'course.prerequisites': 'Voraussetzungen',
  'course.tags': 'Tags',
  'course.stats.members': 'Mitglieder',
  'course.stats.modules': 'Module',
  'course.stats.lessons': 'Lektionen',
  'course.assignments.comingSoon': 'Die Ansicht Zuweisungen wird bald verfügbar sein.',
  'course.progress.comingSoon': 'Die Fortschrittsverfolgung kommt bald.',
  'course.type.free': 'Kostenlos',
  'course.type.paid': 'Bezahlt',
  'course.type.forSale': 'Zu verkaufen',
  'course.type.invite': 'Nur mit Einladung',
  'courses.invites.tile': 'Sie sind eingeladen, an {count, plural, one {Kursen} other {Kursen}}teilzunehmen.',
  'courses.invites.noInvites': 'Sie haben im Moment keine Kurseinladungen.',
  'courses.invites.invitedBy': 'Eingeladen von: ',
  'courses.invites.accept': 'Akzeptieren Sie',
  'courses.invites.reject': 'Ablehnen',
  'course.join.heading': 'An diesem Kurs teilnehmen',
  'course.oneTimePayment': 'Einmalige Zahlung für vollen Zugang',
  'course.member': 'Sie sind eingeschrieben',
  'course.member.access': 'Sie haben vollen Zugang zu allen Kursmaterialien.',
  'courses.members.editRole': 'Rolle bearbeiten',
  'courses.members.editRoleFor': 'Rolle bearbeiten für:',
  'courses.add.member': 'Ein neues Mitglied hinzufügen',
  'course.member.options': 'Liste der Kursmitglieder',
  'course.navigation.curriculum': 'Lehrplan',
  'course.navigation.members': 'Studenten & Lehrer',
  'course.navigation.assignments': 'Zuweisungen',
  'course.navigation.forums': 'Foren',
  'course.navigation.attendance': 'Anwesenheit',
  'course.members.teachers': 'Lehrer',
  'course.members.students': 'Studenten',
  'course.members.preview.message':
    'Nehmen Sie an diesem Kurs teil, um alle Studenten zu sehen und mit der Gemeinschaft zu interagieren.',
  'course.member.role.owner': 'Eigentümer',
  'course.member.role.teacher': 'Lehrer',
  'course.member.role.student': 'Student',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'contentSelector.noSelection': 'No item selected',
  'contentSelector.selectedItems': 'Selected items',
  'contentSelector.entireSite': 'Entire site',
  'contentSelector.myLibrary': 'My library',
  'contentSelector.tabsLabel': 'Search options',
  'contentSelector.title': 'Select Content',
  'course.startDate': 'Startdatum',
  'course.endDate': 'Enddatum',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Lehrplan Vorschau',
  'course.curriculum.preview.message':
    'Melden Sie sich für diesen Kurs an, um Zugang zu allen {count} Lektionen und Aufgaben zu erhalten.',
  'course.curriculum.locked': 'Gesperrt',
  'course.curriculum.module': 'Modul',
  'course.curriculum.lesson': 'Lektion',
  'course.curriculum.assignment': 'Zuweisung',
  'course.curriculum.reading': 'Lesen',
  'course.lesson.backToCurriculum': 'Zurück zu Curriculum',
  'course.lesson.nextLesson': 'Nächste Lektion',
  'course.lesson.documents': 'Dokumente & Ressourcen',
  'course.lesson.meetingLink': 'Meeting Link',
  'course.lesson.location': 'Standort',
  'course.lesson.virtualClassroom': 'Virtuelles Klassenzimmer',
  'course.lesson.joinClassroom': 'Nehmen Sie an der Sitzung im virtuellen Klassenzimmer teil',
  'course.lesson.enterClassroom': 'Klassenzimmer betreten',
  'courses.module.defaultTitle': 'Modul {count, number}',
};
