export default {
    'feedback.home': 'Hilfecenter',
    'feedback.bugs': 'Probleme',
    'feedback.bugs.desc': 'Ist Ihnen ein Fehler aufgefallen oder etwas anderes, das falsch oder fehl am Platz ist. Lassen Sie es uns hier wissen!',
    'feedback.features': 'Ideen & Vorschläge',
    'feedback.features.desc': 'Haben Sie Ideen für neue Funktionen oder wie man die Seite besser machen kann? Lassen Sie es uns wissen!',
    'feedback.help': 'Hilfe & Tutorials',
    'feedback.help.desc': 'Wie funktioniert _____? Gehen Sie hier, um die Antworten zu finden.',
    'feedback.desc': 'Willkommen in unserem Hilfe- und Lösungscenter!',
    'feedback.faq': 'FAQ',
    'feedback.faq.desc': 'Häufig gestellte Fragen',
    'feedback.open': 'Geöffnet',
    'feedback.closed': 'Geschlossen',
    'feedback.accepted': 'Angenommen',
    'feedback.inprogress': 'In Arbeit',
    'feedback.completed': 'Abgeschlossen',
    'feedback.fixed': 'Festgelegt',
    'feedback.new.bugs': 'Neues Problem melden',
    'feedback.new.features': 'Eine neue Funktion vorschlagen',
    'feedback.lang.nosupport': 'Ihre aktuelle Sprache wird für Feedback nicht unterstützt, bitte schreiben Sie in Englisch. Dankeschön!',
    'feedback.new.thanks': 'Vielen Dank für den Hinweis! Wir werden uns das in Kürze ansehen.',
    'feedback.comment.title': 'Kommentar',
    'feedback.comment.desc': 'Senden Sie uns Ihr Feedback',
    'feedback.comment.legend': 'Ihr Feedback - lassen Sie uns alles wissen',
    'feedback.comment.success': 'Vielen Dank für Ihr Feedback!',
    'feedback.comment.label': 'Ihr Kommentar',
    'feedback.copyrightReport.title': 'Urheberrechtsverletzung',
    'feedback.copyrightReport.desc': 'Copyright-Verletzung melden',
    'feedback.report.noUser': 'Sie müssen angemeldet sein, um einen Bericht erstellen zu können.',
    'feedback.voting.totalVoters': 'Benutzer haben abgestimmt: {voted, number}',
    'feedback.voting.upvote': 'Aufwärts stimmen',
    'feedback.voting.downvote': 'Abwärts stimmen',
    'feedback.voting.score': 'Gesamtpunktzahl',
    'feedback.report.title': 'Inhalt des Berichts',
    'feedback.report.typeSelect': 'Was ist hier das Problem?',
    'feedback.reportType.law': 'Rechtsverletzung',
    'feedback.reportType.vulgar': 'Vulgär/obszön',
    'feedback.reportType.copyright': 'Urheberrechtsverletzung',
    'feedback.reportType.storyRating': 'Falsche Altersfreigabe',
    'feedback.reportType.scam': 'Betrug',
    'feedback.report.submit': 'Bericht',
    'feedback.report.submitting': 'Berichterstattung...',
    'feedback.report.violationDesc': 'Details',
    'feedback.report.reportSaved': 'Vielen Dank für die Meldung! Wir werden das Problem untersuchen und bei Bedarf Maßnahmen ergreifen.',
    'feedback.report.copyrightReportSaved': 'Vielen Dank für die Meldung! Wir werden das untersuchen und uns melden.',
    'feedback.report.copyrightOwnershipDesc': 'Eigentumsnachweis',
    'feedback.report.copyrightNotice': 'Bitte beachten Sie, dass Sie der rechtmäßige Eigentümer des Werks sein müssen, um dieses Formular zu verwenden. Wenn Sie nicht der Eigentümer sind, informieren Sie bitte den Eigentümer oder verwenden Sie die andere Kategorie, um uns zu informieren. Wir nehmen Urheberrechtsverletzungen äußerst ernst und dasselbe gilt für die unsachgemäße und missbräuchliche Verwendung dieses Formulars.',
    'feedback.report.copyrightInternalProperty': 'Ich habe diese Arbeit auf Literary Universe veröffentlicht',
    'feedback.reportType.spam': 'Spam oder Phishing',
    'feedback.reportType.other': 'Andere',
    'feedback.report.copyrightType.propertySelectLabel': `Welches {type, select,
    universe {Universum}
    story {Geschichte}
    other {Geschichte}
  } wird verletzt?`,
    'faq.section.about': 'Über uns',
    'faq.section.settings': 'Einstellungen',
    'faq.section.discovery': 'Entdeckung',
    'faq.section.reader': 'Leser',
    'faq.section.library': 'Bibliothek',
    'faq.section.workshop': 'Werkstatt',
    'faq.section.writer': 'Autor',
    'faq.section.encyclopedia': 'Enzyklopädie',
    'faq.section.groups': 'Gruppe',
    'faq.section.blogs': 'Blogs',
    // About us questions
    'faq.question.about.dataLocation': 'Wo werden die LU-Daten gespeichert?',
    'faq.answer.about.dataLocation': 'Die Daten des Literarischen Universums werden auf Servern in den Vereinigten Staaten von Amerika gespeichert, genauer gesagt in der AWS us-east-1 Region.',
    'faq.question.about.incorporation': 'Wo sind Sie eingetragen?',
    'faq.answer.about.incorporation': 'Literary Universe ist in der Tschechischen Republik eingetragen. Weitere Details findest du auf der <a href="/about">Über uns Seite</a>.',
    'faq.question.about.roadmap': 'Was sind die nächsten Schritte für Literary Universe?',
    'faq.answer.about.roadmap': 'Dies entwickelt sich ständig weiter. Schau dir unseren <a href="/roadmap">Fahrplan</a> für weitere Details an.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Wie ändere ich das Aussehen von Literary Universe?',
    'faq.answer.settings.changeTheme': 'Registrierte Benutzer können ihr Thema in den <a href="/user/settings/account">Kontoeinstellungen</a> unter dem Abschnitt "Seiten-Theming" ändern. Es stehen ein helles und ein dunkles Thema zur Verfügung. Wenn du nicht registriert bist, versuchen wir, das Thema basierend auf den Einstellungen deines Browsers und Betriebssystems für dich festzulegen.',
    'faq.question.settings.changeAvatar': 'Wie ändere ich meinen Avatar?',
    'faq.answer.settings.changeAvatar': 'Du kannst deinen Avatar in den <a href="/user/settings/profile">Profil-Einstellungen</a>ändern.',
    'faq.question.settings.changeLanguage': 'Wie ändere ich die Sprache?',
    'faq.answer.settings.changeLanguage': 'Du kannst die Sprache von Literary Universe in den <a href="/user/settings/account">Kontoeinstellungen</a>ändern.',
    'faq.question.settings.translationMistake': 'Ich habe einen Fehler im Text auf der Website gefunden, wo kann ich ihn melden?',
    'faq.answer.settings.translationMistake': 'Alle unsere Sprachdateien sind auf GitHub verfügbar. Du kannst dort <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">ein Problem melden</a> oder im Bug-Bereich des Feedbacks, oder wenn du es bevorzugst, kannst du es direkt selbst über unsere <a href="https://crowdin.com/project/literary-universe" target="_blank">Crowdin-Seite</a>beheben.'
};