export default {
    'homepage.welcome': 'Willkommen auf',
    'homepage.start': 'Starten Sie Ihre Reise!',
    'homepage.iAm': 'Ich bin ein',
    'homepage.iAm.aria': 'Wählen Sie zwischen der Anzeige von Funktionen für Leser und Schreiber',
    'homepage.reader': 'LESER(IN)',
    'homepage.writer': 'AUTOR(IN)',
    'homepage.reader.title': 'Lesen war noch nie so interessant wie jetzt',
    'homepage.reader.readingTitle': 'Einzigartiges Leseerlebnis',
    'homepage.reader.readingDesc': 'Tauchen Sie im Literarischen Universum tiefer in Ihr bevorzugtes fiktionales Universum ein. Die Geschichten im Literarischen Universum sind innerhalb desselben Universums miteinander verbunden, so dass Sie vom Lesegerät aus sofortigen Zugriff auf die Enzyklopädie des Universums haben.',
    'homepage.reader.favoriteTitle': 'Erfahren Sie mehr über Ihre Lieblingsgeschichten und Autoren',
    'homepage.reader.favoriteDesc': 'Die Universums-Enzyklopädie und die Autoren-Blogs sind nur einige der Funktionen, die Ihnen helfen werden, alles über Ihre Lieblingsgeschichten, ihre Schauplätze und ihre Schöpfer zu erfahren!',
    'homepage.reader.communityTitle': 'Werden Sie Mitglied der Gemeinschaft',
    'homepage.reader.communityDesc': 'Treffen Sie Menschen aus der ganzen Welt in speziellen Universums- und Autorenforen, Blogs und anderen Community-Funktionen, in denen sich gleichgesinnte Fans treffen. Alles an einem Ort.',
    'homepage.reader.readingFeatureTitle': 'Genießen Sie ein fesselndes und zugleich praktisches Leseerlebnis',
    'homepage.reader.readingFeatureDesc': 'Von Geschichten und Universum, haben den Vorteil des mühelosen Lesens mit Zugang zu Details, ohne zwischen den Seiten wechseln zu müssen.',
    'homepage.reader.readingExploreTitle': 'Erforsche alle Kleinigkeiten im Universum',
    'homepage.reader.readingExploreDesc': 'Die Universums-Enzyklopädie ermöglicht es Ihnen, alle Details über das Universum zu erfahren und vollständig in die Geschichten einzutauchen.',
    'homepage.reader.start': 'Lesen anfangen',
    'homepage.writer.title': 'Präsentieren Sie Ihr Universum und teilen Sie Ihre Geschichten',
    'homepage.writer.writingTitle': 'Schreiben und Gestalten leicht gemacht',
    'homepage.writer.writingDesc': 'Erleben Sie die neue Art des Schreibens mit dem Literary Universes Workshop. Erstellen Sie alle Details Ihres Universums in einer Enzyklopädie, um sie mit Ihren Lesern zu teilen, und schreiben Sie auf dieser Grundlage erstaunliche Geschichten.',
    'homepage.writer.collaborationTitle': 'Gemeinsame Erstellung',
    'homepage.writer.collaborationDesc': 'An einem kreativen Prozess sind oft mehrere Personen beteiligt. Keine Sorge, wir haben für Sie gesorgt! Sie können ganz einfach Beta-Leser, Co-Autoren und Übersetzer zu Ihren Geschichten und Universen hinzufügen.',
    'homepage.writer.communityTitle': 'Verbinden Sie sich mit Ihren Lesern',
    'homepage.writer.communityDesc': 'Gehen Sie über das Schreiben hinaus und verbinden Sie sich mit Ihren Lesern über Blogs, Foren und andere Community-Funktionen, die mit Ihrem Universum oder mit Ihnen als Autor verbunden sind.',
    'homepage.writer.workshopFeatureTitle': 'Ein Ort für alle Ihre kreativen Bedürfnisse',
    'homepage.writer.workshopFeatureDesc': 'Unsere sich ständig weiterentwickelnde Werkstatt ist der zentrale Ort für Ihre kreativen Bedürfnisse. Aus einer einfachen Idee entstehen erstaunliche Universen, Geschichten und alles, was sonst noch dazugehört.',
    'homepage.writer.monetizationFeatureTitle': 'Monetarisierung',
    'homepage.writer.monetizationDesc': 'Wir sind der festen Überzeugung, dass Menschen für ihre Arbeit bezahlt werden sollten, und sind ständig auf der Suche nach neuen Monetarisierungsmöglichkeiten für Autoren. Die Monetarisierungsfunktion ermöglicht es Ihnen als Autor, für Ihre Arbeit gewürdigt zu werden. Entdecken Sie all die verschiedenen Optionen, die es Ihren Fans ermöglichen, Ihnen ihre Wertschätzung zu zeigen.',
    'homepage.writer.start': 'Richten Sie Ihren Workshop ein!',
    'homepage.featureSelection': 'Sehen Sie sich dieses beliebte Universum an!',
    'about.title': 'Über Literary Universe',
    'about.desc': 'Geschichte, Geheimnisse und Menschen hinter dem Literary Universe.',
    'about.text.1': 'Literary Universe is designed for both writers and avid readers. Writers can use the platform to create original works by selecting the "Workshop" button in the dashboard menu. This provides access to the main editor and encyclopedia functions, which focus on organizing all aspects of your personal story universe on a single page. The social features allow authors to share their work, build a following, and interact more directly with their readers if they choose.',
    'about.text.2': 'Readers can use the site primarily to discover new works and follow their favorite authors, but they can also help edit pre-published stories if granted permission by the writer. Being a reader on Literary Universe offers a whole new reading experience—having access to all the background information on the same page as the main story provides insight into the author’s mind like never before.',
    'about.text.3': 'The future of Literary Universe includes creating a marketplace where authors can sell their work and adding community features to enhance communication between authors and readers through blogs and forums. We plan to introduce additional writer’s tools over time, with more than a dozen currently in development or planned. Our ultimate goal is to enrich the experiences of both writers and readers by leveraging the internet medium in innovative ways.',
    'about.text.4': 'Wir hoffen, dass Sie sich uns anschließen, wenn wir erkunden, was das Medium Internet für das kreative Schreiben tun kann!',
    'about.team': 'Das Team',
    'about.history': 'Geschichte',
    'about.company': 'Die Firma',
    'about.companyCountry.czechia': 'Tschechien',
    'about.companyCountry.japan': 'Japan',
    'about.companyCity.prague': 'Prag',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Vorstandssprecher',
    'about.CTO': 'Technischer Direktor',
    'about.jan': 'Jan is the founder, visionary, and technological mind behind Literary Universe. As a writer of expansive literary universes, Jan often struggled to write stories in a way that balanced technical precision with readability, without compromising the reader\'s experience. This challenge led him to pursue studies in web development, with the goal of creating an application that simplifies the process of writing stories within large universes.',
    'about.history.text': 'In 2010, Jan began his studies at the Rochester Institute of Technology to deepen his knowledge of web development, with the goal of building a creative writing platform. This vision took shape in 2013 when the first proof of concept was presented at Imagine RIT. Jan continued his studies, and in 2016, a new version of the app was created as his Master\'s Capstone Project. The project continued to evolve throughout the fall of 2016, eventually developing into the platform you see today.',
    'copyrights.desc': 'Der vollständige Text des Literary Universe Copyrights Agreement.',
    'privacy.desc': 'Vollständiger Rechtstext der Datenschutzrichtlinie von Literary Universe.',
    'guidelines.desc': 'Community-Richtlinien des Literary Universe.',
    'tos.desc': 'Vollständiger Rechtstext der Allgemeinen Geschäftsbedingungen von Literary Universe.',
    'homepage.intro': 'Lassen Sie Ihrer Kreativität freien Lauf im Literary Universe',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'Haben Sie jemals davon geträumt, eine so detailreiche fiktive Welt zu entwickeln, dass Sie selbst darin verloren gehen? Bei Literary Universe bieten wir die Werkzeuge, um diese Vision zur Realität werden zu lassen. Jeder Schriftsteller verdient Zugang zu erstklassigen Ressourcen und Unterstützung. Deshalb haben wir einen umfassenden Raum geschaffen, der die Kluft zwischen komplexem Geschichtenerzählen und leidenschaftlichem Lesen überbrückt. Für Schriftsteller ist es ein Traumarbeitsplatz; für Leser eine Odyssee der Entdeckung. Begleiten Sie uns, während wir den literarischen Kaninchenbau erkunden, um herauszufinden, wie weit er uns in die Welt der Vorstellungskraft führt.',
    'gdpr.title': 'DSGVO-Konformität',
    'gdpr.desc': 'Literary Universe ist konform mit den EU DSGVO-Richtlinien.',
    'gdpr.compliant': 'Literary Universe ist DSGVO-komform',
    'gdpr.compliant.text': 'Literary Universe hat in Vorbereitung auf die Umsetzung der DSGVO am 25. Mai 2018 verschiedene Updates und Änderungen an seiner Codebasis vorgenommen.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'Änderungen in dieser Version vorgenommen',
    'dmca.title': 'Richtlinie zum Digital Millennium Copyright Act (DMCA)',
    'dmca.subtitle': 'Richtlinie für Urheberrechtsstreitigkeiten',
    'dmca.step1.title': 'Verfahren zur Meldung von Copyright-Verletzungen.',
    'dmca.step2.title': 'Sobald eine ordnungsgemäße Bona-Fide-Benachrichtigung über eine Rechtsverletzung bei dem benannten Vertreter eingegangen ist.',
    'dmca.step3.title': 'Verfahren zur Übermittlung einer Gegenmitteilung an den designierten Agenten.',
    'dmca.desc': 'Wir nehmen Urheberrechtsverletzungen ernst.',
    'gdpr.access.title': 'Recht auf Zugang und Recht auf Datenübertragbarkeit',
    'gdpr.access.desc': 'In den Benutzereinstellungen können Sie alle Ihre Daten exportieren. Diese Daten liegen dann im Standard-JSON-Format vor.',
    'gdpr.forget.title': 'Recht auf Vergessenwerden',
    'gdpr.forget.desc': 'Jedes Konto kann über die Benutzereinstellungen gelöscht werden. Einige Daten können erhalten bleiben, insbesondere wenn sie Gegenstand von Verkäufen und/oder Streitigkeiten waren.',
    'gdpr.rectification.title': 'Das Recht auf Nachbesserung',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'Recht auf Einschränkung der Verarbeitung',
    'gdpr.processing.desc': 'Literary Universe respektiert in vollem Umfang die Einstellungen des Browsers, wie z. B. "Do not track"-Anfragen für Berichte an unseren Matomo-Statistikserver.',
    'gdpr.object.title': 'Recht auf Widerspruch',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'Die Berichterstattung ist in zwei Szenarien unterteilt. 1. Internes Eigentum (Verletzung von auf dem Gelände vorhandenem Eigentum). 2. Externes Eigentum (Verletzung auf dem Gelände von nicht auf dem Gelände vorhandenem Eigentum).',
    'dmca.step1.desc2': 'Das Melden von internem Eigentum kann über die Melden-Schaltfläche auf dem Eigentum erfolgen. Das Melden von externen Eigentumsverletzungen kann über den Feedback-Bildschirm erfolgen. In beiden Fällen werden Sie aufgefordert, persönliche Daten und zusätzliche Details anzugeben, die es uns ermöglichen, Ihr Eigentum zu überprüfen.',
    'dmca.step1.desc3': 'Bitte beachten Sie, dass falsche Angaben dazu führen, dass Sie in Zukunft keine Ansprüche mehr geltend machen können.',
    'dmca.step2.desc1': 'Nach Erhalt Ihres Berichts werden wir Ihre Berechtigungsnachweise und Ihren Eigentumsanspruch überprüfen. Wenn alles in Ordnung ist, fahren wir fort, die Behauptung zu prüfen. Wenn wir feststellen, dass die Behauptung wahr ist, werden wir das verletzende Eigentum unzugänglich machen, bis eine Gegenmeldung erfolgt oder 14 Tage vergangen sind, nach denen es gelöscht wird.',
    'dmca.step3.desc1': 'Sobald eine Beschwerde eingegangen ist, hat der Eigentümer der bezeichneten Immobilie 14 Tage Zeit, eine Gegenanzeige einzureichen. Der designierte Agent wird dann den Streitfall untersuchen. Jede Entscheidung des Designated Agent in diesem Stadium ist endgültig.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Urhebernachweise',
    'about.attributionsIntro': 'Literary Universe baut auf vielen Open-Source-Projekten und anderen Ressourcen auf. Unten finden Sie deren Auflistung.',
    'about.attributionsMatomo': 'Unsere Analysen verwenden das selbst gehostete Matomo mit IP2Location LITE-Daten, die unter https://lite.ip2location.com verfügbar sind.',
    'team.name.pjakubec': 'Pavel Jakubec',
    'team.name.asebesta': 'Adam Šebesta',
    'about.developer': 'Entwickler',
    'about.seniorDeveloper': 'Senior Entwickler',
    'about.juniorDeveloper': 'Junior-Entwickler',
    'about.leadDesigner': 'Lead-Designer',
    'about.leadUX': 'Lead UX-Designer',
    'about.intern': 'Praktikant',
    'about.advisor': 'Berater',
    'about.headOfResearch': 'Leiter der Forschung',
    'about.CFO': 'Finanzvorstand',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry ist ein Designer mit mehr als 15 Jahren Erfahrung. Er arbeitet seit 2010 in einer Agentur, zu seinen Kunden gehören PERTAMINA, VOA und das indonesische Tourismusministerium. Erfahren in Branding, Layout und auch UI/UX fühlt er sich herausgefordert, Literary Universe zu gestalten.',
    'about.pavel': 'Web3, the Metaverse, AI, and any emerging technology—Pavel explores it all to see how it can enhance Literary Universe. As a true multidisciplinary researcher, Pavel has insights into many fields and works on integrating new and exciting features into the platform.',
    'about.seba': 'Once a gamer, Adam is now on the path to becoming a fully-fledged developer, applying his skills and passion to Literary Universe.'
};