export default {
    'plans.desc': 'Beschreibung der Pläne und Merkmale des Literary Universe.',
    'plans.title': 'Holen Sie mehr aus dem Literary Universe heraus!',
    'plans.text': 'Literary Universe bietet eine kostenlose Basisfunktionalität. Wenn Sie ein eifriger Leser oder Schöpfer sind, könnte unsere Vorab-Mitgliedschaft mehr nach Ihrem Geschmack sein.',
    'plans.faq.basicsPriced': 'Warum hat die kostenlose Mitgliedschaft so wenige Dinge?',
    'plans.faq.justification': 'Hier bei Literary Universe schätzen wir Ihre Privatsphäre und Ihr geistiges Eigentum. Deshalb nutzen wir Ihre Daten nicht, um Werbung zu verkaufen oder sie anderen Unternehmen zur Verfügung zu stellen. Das bedeutet, dass wir viele Dinge selbst entwickeln müssen. Das kostet viel Zeit und ist teuer im Betrieb. Daher haben wir die kostenlose Mitgliedschaft als eine kleine Vorschau auf Literary Universe eingerichtet (die Ihnen immer noch erlaubt, die wichtigsten Dinge zu tun), mit mehreren Mitgliedschaftsstufen und Addons, um den Bedürfnissen aller gerecht zu werden und uns gleichzeitig zu ermöglichen, den Dienst aufrechtzuerhalten und weiterzuentwickeln.',
    'plans.limits': 'Grenzwerte',
    'plans.features': 'Funktionen',
    'plans.account.user': 'Besucher',
    'plans.account.user.desc': 'Erstes Testkonto, um Dinge auszuprobieren.',
    'plans.account.explorer': 'Entdecker',
    'plans.account.explorer.desc': 'Für Bastler & Freunde.',
    'plans.account.adventurer': 'Abenteurer',
    'plans.account.adventurer.desc': 'Für Schöpfer & unsere Unterstützer.',
    'plans.account.storyteller': 'Geschichtenerzähler',
    'plans.account.storyteller.desc': 'Für die Kreativsten und Engagiertesten.',
    'plans.unlimited': 'Unbegrenzt',
    'plans.price': 'Preis',
    'plans.price.free': 'GRATIS',
    'plans.price.monthly': 'Monat',
    'plans.price.annually': 'jährlich',
    'plans.price.perMonth': ' / Monat',
    'plans.price.perYear': ' / Jahr',
    'plans.development': 'In Entwicklung',
    'plans.limits.encEntries': 'Enzyklopädie-Einträge',
    'plans.limits.maxCollaborators': 'Mitarbeiter pro Projekt',
    'plans.limits.pmChats': 'Maximale Anzahl von Empfängern für private Nachricht',
    'plans.feature.encCustomFields': 'Anpassbare Enzyklopädie-Felder eines Eintrags',
    'plans.feature.encAdvCategories': 'Weitere Enzyklopädie-Kategorien',
    'plans.feature.scratchpad': 'Scratchpad',
    'plans.feature.library': 'Bibliothek',
    'plans.feature.blog': 'Persönliche & Universum-Blogs',
    'plans.feature.customBlogTheme': 'Anpassbare Blog-Themen',
    'plans.feature.advanceStats': 'Erweiterte Statistik',
    'plans.feature.challenges': 'Herausforderungen beim Schreiben',
    'plans.feature.newFeaturesVote': 'Abstimmen über neue Funktionen',
    'plans.feature.newFeaturesSuggest': 'Neue Funktionen vorschlagen',
    'plans.feature.accessToBeta': 'Zugriff auf Beta-Funktionen',
    'plans.feature.userGroups': 'Benutzergruppen',
    'plans.feature.privateUserGroups': 'Private und versteckte Benutzergruppen erstellen',
    'plans.feature.internalUniverseForums': 'Internes Forum für Universen',
    'plans.currency.select': 'Währung auswählen',
    'plans.subscription.ownAlready': 'Sie haben derzeit diesen Plan',
    'plans.subscription.title': 'Abonnement',
    'plans.see': 'Verfügbare Abonnementpläne anzeigen',
    'plans.current.none': 'Sie unterstützen derzeit nicht Literary Universe.',
    'plans.current.buying': 'Es kann ein paar Augenblicke dauern, um Ihren Kauf zu überprüfen. Wir danken Ihnen für Ihre Geduld.',
    'plans.current.heading': 'Aktueller Abonnementplan',
    'payment.methods.title': 'Zahlungen & Monetarisierung',
    'payment.methods.tabs': 'Zahlungsoptionen',
    'payment.option.title': 'Zahlungsoption',
    'payment.option.notFount': 'Sie haben keine Zahlungsoption gespeichert.',
    'payment.option.create': 'Eine neue Zahlungsoption hinzufügen',
    'payment.option.description': 'Hier finden Sie eine Liste Ihrer gespeicherten Zahlungsarten. Sie können hier neue Zahlungsarten speichern, um schneller zur Kasse zu gehen. Literary Universe speichert und verarbeitet Ihre Zahlungsdaten wie Kreditkartennummer nicht.',
    'payment.history.title': 'Zahlungsverlauf',
    'payment.history.tab': 'Geschichte',
    'payment.history.none': 'Wir haben keine Aufzeichnungen über vergangene Zahlungen.',
    // Added 2020-04-30
    'plans.options.aria': 'Zahlungsoptionen',
    'plans.options.creditCard': 'Kreditkarte',
    'plans.purchase.action': 'Abonnieren',
    'plans.purchase.title': 'Literary Universe Abonnement kaufen',
    'payment.creditCard.details': 'Angaben zur Kreditkarte',
    'payments.zipcode.label': 'Postleitzahl',
    'payment.card.name': 'Name auf Karte',
    'plans.subscribed.thankYou': 'Danke, dass Sie Literary Universe unterstützen',
    'plans.subscribed.periodEnd': 'Dein Abonnement ist gültig bis: {end, date, medium}',
    'plans.subscribed.renewal': `Am Ende wird dein Abonnement {method, select,
    charge_automatically {Erneuert automatisch}
    send_invoice {erneuert nach Zahlung einer Rechnung}
    other {}
  }`,
    'plans.subscribed.paymentMethod': 'Ihre Standardzahlungsmethode wird für die Bezahlung des nächsten Zyklus verwendet.',
    'plans.subscribed.status': `Abonnementstatus: {status, select,
    active {Aktiv}
    incomplete {Etwas fehlt}
    incomplete_expired {Etwas fehlt}
    trialing {Probe}
    past_due {Deine Zahlung fehlt}
    canceled {Abgebrochen}
    unpaid {Unbezahlt}
    other {}
  }`,
    'payments.changeMethod': 'Zahlungsmethode ändern',
    'plans.subscribed.willNotRenew': ', wird am Ende des Zyklus nicht erneuert.',
    'plans.cancel.button': 'Abonnement beenden',
    'plans.cancel.question': 'Sind Sie sicher, dass Sie Ihr Abonnement kündigen möchten? Ihr Abonnement bleibt bis zum Ende des Abrechnungszeitraums aktiv.',
    'plans.cancel.confirmationButton': 'Ja, ich möchte mein Abonnement kündigen',
    'plans.cancel.failed': 'Entschuldigung, wir konnten Ihren Plan in diesem Moment nicht stornieren. Bitte versuchen Sie es später noch einmal.',
    'plans.cancel.restoreBtn': 'Abonnement wiederherstellen',
    'plans.cancel.restoreFailed': 'Entschuldigung, wir konnten das Abonnement in diesem Moment nicht wiederherstellen. Bitte versuchen Sie es später noch einmal.',
    'plans.change.button': 'Abonnement ändern',
    'plans.change.explanation': 'Wählen Sie den Plan aus, auf den Sie up- oder downgraden möchten. Die Preisdifferenz wird Ihnen sofort in Rechnung gestellt.',
    'plans.change.failed': 'Entschuldigung, wir konnten Ihren Plan in diesem Moment nicht ändern. Bitte versuchen Sie es später noch einmal.',
    'plans.change.upgrade': 'Upgraden',
    'payments.disclaimer': 'Zahlungsinformationen und -abwicklung werden über Stripe abgewickelt. Wir speichern keine Kreditkarten- oder Bankkontoinformationen auf unseren Servern.',
    'buy.payment.optionsSelect': 'Zahlungsoption auswählen',
    'payments.card.number': 'Kartennummer',
    'payments.card.expire': 'Gültig bis',
    'payments.card.cvv': 'CVV',
    'payments.card.info': '{cardType} Karte, endet in {ending}',
    'payments.none': 'Keine gespeicherten Zahlungsoptionen gefunden.',
    'payments.added': 'Die neue Zahlungsoption wurde erfolgreich hinzugefügt.',
    'payments.delete.confirm': 'Sind Sie sicher, dass Sie {cardType}, endend in {ending}, löschen möchten?',
    'payment.invoice.status': 'Status der Rechnung',
    'payment.invoice.statusMessage': `{status, select,
    draft {Entwurf}
    open {Öffne}
    paid {Bezahlt}
    uncollectible {Unsammelbar}
    void {Leer}
    other {}
  }`,
    'payment.invoice.id': 'Rechnungs ID',
    'payment.invoice.pdf': 'Rechnung PDF',
    'payment.invoice.total': 'Summe',
    'payment.invoice.what': 'Rechnungsbeschreibung',
    'payment.stripe.powered': 'Angetrieben durch ',
    'payment.listMethods.card': 'Karten',
    'payment.expiresAt': 'Läuft ab {month}/{year}',
    'payment.card.details': `{type, select,
    credit {Kreditkarte}
    debit {Debitkarte}
    other {Karte}
  } endet mit {last4}`,
    'payment.options.default': 'Standard',
    // Added 2020-05-27
    'payment.method.add': 'Eine neue Zahlungsmethode hinzufügen',
    'payment.methods.adding': 'Ihre neue Zahlungsmethode wurde zu Ihrem Konto hinzugefügt.',
    'payment.methods.delete': 'Zahlungsmethode löschen',
    'payment.upgradePlan.option': '{plan} - {price}',
    'payment.methods.webMonetization': 'Web Monetisierung',
    'settings.webMonetization.placeholder': 'Ihr Zahlungszeiger',
    'payment.webMonetization.explained': 'Web Monetization ist ein vorgeschlagener Standard für Web-Zahlungen. Hier können Sie Ihren Zahlungszeiger hinzufügen, der dann zu Ihrer Profilseite, Ihrem Blog, Ihren Universen und Geschichten hinzugefügt wird, um von Web Monetization genutzt zu werden.',
    'payment.webMonetization.learnMore': 'Erfahren Sie mehr über Web-Monetarisierung'
};