export default {
    'writer.menu.optionsAria': 'Menü Editor-Optionen',
    'writer.menu.saveOptionsAria': 'Optionen speichern',
    'writer.undo': 'Rückgängig machen',
    'writer.redo': 'Wiederholen',
    'writer.ul': 'Unsortierte Liste',
    'writer.ol': 'Bestellte Liste',
    'writer.blockquote': 'Zitat',
    'writer.link': 'Einen Link einfügen',
    'writer.image': 'Einfügen eines Bildes',
    'writer.bold': 'Die Auswahl ist fett gedruckt',
    'writer.underline': 'Unterstreichen Sie die Auswahl',
    'writer.italic': 'Betonen Sie die Auswahl',
    'writer.wordcount': '{characters, number} Zeichen, {words, number} Wörter',
    'finder.details': 'Details',
    'finder.remove': 'entfernen Sie die Verbindung',
    'finder.connect': 'Auswahl mit Enzyklopädieeintrag verbinden',
    'writer.aside.ariaLabel': 'Menü Hilfeoptionen',
    'writer.nothingToSave': 'Nichts zu speichern',
    'writer.publish.publishAria': 'Optionen für die Veröffentlichung',
    'writer.publish.scheduleExplained': 'Sie können das Kapitel entweder sofort veröffentlichen oder die Veröffentlichung für einen späteren Zeitpunkt planen.',
    'writer.publish.schedule': 'Datum und Uhrzeit der Veröffentlichung festlegen',
    'writer.publish.previousChapterPublished': 'Das vorherige Kapitel wurde am {publishDate, date, short} um {publishDate, time} veröffentlicht',
    'writer.publish.previousChapterScheduled': 'Das vorherige Kapitel soll am {publishDate, date, short} um {publishDate, time} veröffentlicht werden',
    'writer.publish.alreadyPublished': 'Dieses Kapitel wurde bereits am {publishedAt, date, short} veröffentlicht. Neue Versionen werden sofort veröffentlicht.',
    'writer.publish.betaReader': 'Beta',
    'writer.publish.public': 'Veröffentlichen'
};