export default {
  'courses.courses': 'Cursuri',
  'courses.overview': 'Prezentare generală a cursurilor',
  'courses.public.title': 'Explorați cursurile',
  'courses.public.heading': 'Explorați cursurile',
  'courses.public.filters': 'Filtrează cursurile',
  'courses.public.noResults': 'Nu s-au găsit cursuri',
  'courses.public.tryDifferentFilters': 'Încercați termeni de căutare sau filtre diferite',
  'courses.filter.search': 'Căutare cursuri...',
  'courses.filter.allTypes': 'Toate tipurile',
  'courses.filter.clearAll': 'Ștergeți tot',
  'courses.type.course': 'Curs',
  'courses.type.workshop': 'Atelier de lucru',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Curs',
  'courses.type.workshop.lowercase': 'Atelier de lucru',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'Creați un curs nou',
  'course.reading.title': 'Titlul temei de lectură',
  'course.question.add': 'Adaugă întrebare',
  'course.add.courseElement': 'Adăugați un nou element de curs',
  'course.lessons.newMessage': 'Creați și organizați-vă lecțiile pentru o predare eficientă',
  'course.reading.new': 'Sarcina de lectură',
  'course.reading.newMessage': 'Creați și organizați sarcini de lectură pentru elevii dvs.',
  'course.writing.new': 'Atribuire de scriere',
  'course.writing.newMessage': 'Configurați și distribuiți rapid sarcinile de scriere',
  'course.question.text': 'Întrebarea ta este aici',
  'course.question.type': 'Vă rugăm să selectați un tip de întrebare',
  'course.question.delete': 'Eliminați întrebarea',
  'course.type': 'Selectați tipul de curs',
  'course.visibility': 'Selectați opțiunea de vizibilitate',
  'course.title': 'Titlu',
  'course.description': 'Descriere',
  'course.cover': 'Copertă',
  'course.start': 'Cursul tău începe la',
  'course.ends': 'Cursul tău se încheie la',
  'course.curriculum': 'Programă de studiu',
  'course.members': 'Studenți și profesori',
  'course.assignments': 'Atribuții',
  'course.question.deleteWhole': 'Șterge întreaga întrebare',
  'course.question.yes': 'Da',
  'course.question.no': 'Nu',
  'course.lesson.title': 'Titlu lecție',
  'course.lesson.add.universe': 'Adăugați Poveste/Univers',
  'course.lesson.externalLinks': 'Legături externe',
  'course.lesson.add.link': 'Adăugați link extern',
  'course.status': 'Statut',
  'course.active': 'Activitate',
  'course.active.message': 'Activ',
  'course.inactive': 'Inactiv',
  'course.module.edit': 'Editați numele modulului',
  'course.upload.resource': 'Încărcați o resursă',
  'course.question.answer': 'Adaugă răspuns',
  'course.question.open': 'Întrebare deschisă',
  'course.question.close': 'Întrebare închisă',
  'course.question.multiple': 'Întrebare cu alegere multiplă',
  'course.about': 'Despre acest curs',
  'course.lesson.new': 'Creați o lecție nouă',
  'course.lesson.type': 'Tipul lecției',
  'course.lesson.inPerson': 'În persoană',
  'course.lesson.preRecorded': 'Pre-înregistrat',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Numai text',
  'course.lesson.content': 'Conținutul lecției',
  'course.lesson.description': 'Descriere publică',
  'course.add.module': 'Adăugați un modul nou',
  'course.add.story': 'Adaugă o poveste',
  'course.remove.story': 'Eliminați povestea',
  'course.dateOfPublish': 'Data publicării',
  'course.lesson.meetInPerson': 'Întâlnire în persoană',
  'course.curriculum.edit': 'Editare curriculum',
  'course.stories.own': 'Poveștile tale',
  'course.stories.organization': 'Povești organizaționale',
  'course.stories.public': 'Povești publice',
  'course.publish.at': 'Vreau ca acest curs să fie publicat la:',
  'course.edit.curriculum': 'Editare curriculum',
  'course.assignment': 'Atribuire',
  'course.lesson.removeLink': 'Elimină link-ul',
  'course.remove.user': 'Eliminați utilizatorul',
  'course.add.user': 'Adăugați utilizator',
  'course.edit.role': 'Editare rol',
  'course.assignment.description': 'Descrierea misiunii',
  'course.internal': 'Interne',
  'course.free': 'Gratuit',
  'course.sale': 'Vânzare',
  'course.announcements': 'Anunțuri',
  'course.announcements.full': 'Anunțuri de curs',
  'course.announcements.create': 'Creați un anunț',
  'course.join': 'Alăturați-vă cursului',
  'course.firstLesson': 'Prima lecție',
  'course.upcomingLessons': 'Lecții viitoare',
  'course.detail.title': '{courseName} Curs | Curs',
  'lessons.visibility.public': 'Public',
  'lessons.visibility.private': 'Privat',
  'lessons.visibility.hidden': 'Ascunse',
};
