export default {
  'courses.courses': 'Cursuri',
  'courses.overview': 'Prezentare generală a cursurilor',
  'courses.public.title': 'Explorați cursurile',
  'courses.public.heading': 'Explorați cursurile',
  'courses.public.filters': 'Filtrează cursurile',
  'courses.public.noResults': 'Nu s-au găsit cursuri',
  'courses.public.tryDifferentFilters': 'Încercați termeni de căutare sau filtre diferite',
  'courses.filter.search': 'Căutare cursuri...',
  'courses.filter.allTypes': 'Toate tipurile',
  'courses.filter.clearAll': 'Ștergeți tot',
  'courses.type.course': 'Curs',
  'courses.type.workshop': 'Atelier de lucru',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Curs',
  'courses.type.workshop.lowercase': 'Atelier de lucru',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'Creați un curs nou',
  'course.reading.title': 'Titlul temei de lectură',
  'course.question.add': 'Adaugă întrebare',
  'course.add.courseElement': 'Adăugați un nou element de curs',
  'course.lessons.newMessage': 'Creați și organizați-vă lecțiile pentru o predare eficientă',
  'course.reading.new': 'Sarcina de lectură',
  'course.reading.newMessage': 'Creați și organizați sarcini de lectură pentru elevii dvs.',
  'course.writing.new': 'Atribuire de scriere',
  'course.writing.newMessage': 'Configurați și distribuiți rapid sarcinile de scriere',
  'course.question.text': 'Întrebarea ta este aici',
  'course.question.type': 'Vă rugăm să selectați un tip de întrebare',
  'course.question.delete': 'Eliminați întrebarea',
  'course.type': 'Tipul cursului',
  'course.visibility': 'Selectați opțiunea de vizibilitate',
  'course.title': 'Titlu',
  'course.description': 'Descriere',
  'course.cover': 'Copertă',
  'course.start': 'Cursul tău începe la',
  'course.ends': 'Cursul tău se încheie la',
  'course.curriculum': 'Programa cursului',
  'course.members': 'Studenți și profesori',
  'course.assignments': 'Atribuții',
  'course.question.deleteWhole': 'Șterge întreaga întrebare',
  'course.question.yes': 'Da',
  'course.question.no': 'Nu',
  'course.lesson.title': 'Titlu lecție',
  'course.lesson.add.universe': 'Adăugați Poveste/Univers',
  'course.lesson.externalLinks': 'Legături externe',
  'course.lesson.add.link': 'Adăugați link extern',
  'course.status': 'Statut',
  'course.active': 'Activitate',
  'course.active.message': 'Activ',
  'course.inactive': 'Inactiv',
  'course.module.edit': 'Editați numele modulului',
  'course.upload.resource': 'Încărcați o resursă',
  'course.question.answer': 'Adaugă răspuns',
  'course.question.open': 'Întrebare deschisă',
  'course.question.close': 'Întrebare închisă',
  'course.question.multiple': 'Întrebare cu alegere multiplă',
  'course.about': 'Despre acest curs',
  'course.lesson.new': 'Creați o lecție nouă',
  'course.lesson.type': 'Tipul lecției',
  'course.lesson.inPerson': 'În persoană',
  'course.lesson.preRecorded': 'Pre-înregistrat',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Numai text',
  'course.lesson.content': 'Conținutul lecției',
  'course.lesson.description': 'Descriere publică',
  'course.add.module': 'Adăugați un modul nou',
  'course.add.story': 'Adaugă o poveste',
  'course.remove.story': 'Eliminați povestea',
  'course.dateOfPublish': 'Data publicării',
  'course.lesson.meetInPerson': 'Întâlnire în persoană',
  'course.curriculum.edit': 'Editare curriculum',
  'course.stories.own': 'Poveștile tale',
  'course.stories.organization': 'Povești organizaționale',
  'course.stories.public': 'Povești publice',
  'course.publish.at': 'Vreau ca acest curs să fie publicat la:',
  'course.edit.curriculum': 'Editare curriculum',
  'course.assignment': 'Atribuire',
  'course.lesson.removeLink': 'Elimină link-ul',
  'course.user.remove': 'Eliminați utilizatorul',
  'course.user.invite': 'Invitați utilizatorul',
  'course.user.invited': 'Invitat',
  'course.edit.role': 'Editare rol',
  'course.assignment.description': 'Descrierea misiunii',
  'course.internal': 'Interne',
  'course.free': 'Gratuit',
  'course.sale': 'Vânzare',
  'course.announcements': 'Anunțuri',
  'course.announcements.full': 'Anunțuri de curs',
  'course.announcements.create': 'Creați un anunț',
  'course.join': 'Alăturați-vă cursului',
  'course.joining': 'Alăturați-vă...',
  'course.join.success': 'V-ați înscris cu succes la acest curs!',
  'course.join.error.payment': 'Acest curs necesită plata pentru înscriere.',
  'course.join.error.invite': 'Acest curs necesită o invitație de participare.',
  'course.join.error.generic': 'S-a produs o eroare la înscrierea la curs. Vă rugăm să încercați din nou.',
  'course.firstLesson': 'Prima lecție',
  'course.upcomingLessons': 'Lecții viitoare',
  'course.detail.title': '{courseName} Curs | Curs',
  'lessons.visibility.public': 'Public',
  'lessons.visibility.private': 'Privat',
  'course.curriculum.empty': 'Nu există încă elemente de curriculum disponibile.',
  'course.preview.message':
    'Aceasta este o previzualizare a cursului. Înscrieți-vă la curs pentru a accesa tot conținutul.',
  'course.modules.locked': '{count} more {count, plural, one {module} other {module}} (blocat)',
  'course.details': 'Detalii despre curs',
  'course.tab.curriculum': 'Curriculum',
  'course.tab.details': 'Detalii despre curs',
  'course.duration': 'Durată',
  'course.perpetual': 'Perpetuu',
  'course.language': 'Limba',
  'course.price': 'Preț',
  'course.learningObjectives': 'Obiective de învățare',
  'course.prerequisites': 'Condiții prealabile',
  'course.tags': 'Etichete',
  'course.stats.members': 'Membri',
  'course.stats.modules': 'Module',
  'course.stats.lessons': 'Lecții',
  'course.assignments.comingSoon': 'Vizualizarea sarcinilor va apărea în curând.',
  'course.progress.comingSoon': 'Urmărirea progresului se va face în curând.',
  'course.type.free': 'Gratuit',
  'course.type.paid': 'Plătite',
  'course.type.invite': 'Doar pe bază de invitație',
  'courses.invites.tile': 'Sunteți invitați să participați la {count, plural, one {curs} other {cursuri}}.',
  'courses.invites.noInvites': 'Momentan nu aveți invitații la cursuri.',
  'courses.invites.invitedBy': 'Invitat de: ',
  'courses.invites.accept': 'Acceptați',
  'courses.invites.reject': 'Respingeți',
  'course.join.heading': 'Înscrieți-vă la acest curs',
  'course.oneTimePayment': 'Plată unică pentru acces complet',
  'course.member': 'Sunteți înscris',
  'course.member.access': 'Aveți acces complet la toate materialele de curs.',
  'courses.members.editRole': 'Editare rol',
  'courses.members.editRoleFor': 'Editează rolul pentru:',
  'courses.add.member': 'Adăugați un nou membru',
  'course.member.options': 'Lista membrilor cursului',
  'course.navigation.curriculum': 'Curriculum',
  'course.navigation.members': 'Elevi și profesori',
  'course.navigation.assignments': 'Atribuții',
  'course.navigation.forums': 'Forumuri',
  'course.navigation.attendance': 'Prezența',
  'course.members.teachers': 'Profesori',
  'course.members.students': 'Studenți',
  'course.members.preview.message':
    'Alăturați-vă acestui curs pentru a vedea toți studenții și a interacționa cu comunitatea.',
  'course.member.role.owner': 'Proprietar',
  'course.member.role.teacher': 'Învățător',
  'course.member.role.student': 'Student',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'contentSelector.noSelection': 'No item selected',
  'contentSelector.selectedItems': 'Selected items',
  'contentSelector.entireSite': 'Entire site',
  'contentSelector.myLibrary': 'My library',
  'contentSelector.tabsLabel': 'Search options',
  'contentSelector.title': 'Select Content',
  'course.startDate': 'Data de începere',
  'course.endDate': 'Data de încheiere',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Previzualizare curriculum',
  'course.curriculum.preview.message':
    'Alăturați-vă acestui curs pentru a accesa toate lecțiile și sarcinile {count} .',
  'course.curriculum.locked': 'Blocat',
  'course.curriculum.module': 'Modul',
  'course.curriculum.lesson': 'Lecția',
  'course.curriculum.assignment': 'Atribuire',
  'course.curriculum.reading': 'Lectura',
  'course.lesson.backToCurriculum': 'Înapoi la Curriculum',
  'course.lesson.nextLesson': 'Lecția următoare',
  'course.lesson.documents': 'Documente și resurse',
  'course.lesson.meetingLink': 'Întâlnire Link',
  'course.lesson.location': 'Locație',
  'course.lesson.virtualClassroom': 'Sală de clasă virtuală',
  'course.lesson.joinClassroom': 'Participați la sesiunea de clasă virtuală',
  'course.lesson.enterClassroom': 'Intrați în sala de clasă',
  'courses.module.defaultTitle': 'Modul {count, number}',
};
