/**
 * Licenses for creative works
 * https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
 */
export default {
    'licenses.about': 'Despre licențe',
    'licenses.more': 'Mai multe informații',
    'licenses.legal': 'Document legal',
    'licenses.name.cc-by': 'Creative Commons Atribuire 4.0',
    'licenses.cc-by': 'Această licență permite altora să distribuie, să remodeleze, să ajusteze și să construiască pe baza lucrării dvs., chiar și în scopuri comerciale, atât timp cât vă creditează pentru creația originală. Aceasta este cea mai permisivă dintre licențele oferite. Recomandată pentru o diseminare maximă și utilizarea materialelor licențiate.',
    'licenses.name.cc-by-sa': 'Creative Commons Atribuire-Distribuire în condiții identice 4.0',
    'licenses.cc-by-sa': 'Această licență permite altora să remixeze, să modifice și să construiască pe baza lucrărilor dvs. chiar și în scopuri comerciale, cu condiția să vă crediteze și să își licențieze noile creații în condiții identice. Această licență este adesea comparată cu licențele de software liber și open source "copyleft". Toate lucrările noi bazate pe lucrarea dvs. vor purta aceeași licență, astfel încât orice derivate vor permite, de asemenea, utilizarea comercială. Aceasta este licența utilizată de Wikipedia și este recomandată pentru materialele care ar beneficia de încorporarea conținutului din Wikipedia și din proiecte cu licențe similare.',
    'licenses.name.cc-by-nd': 'Creative Commons Atribuire-FărăDerivate 4.0',
    'licenses.cc-by-nd': 'Această licență permite redistribuirea, atât în scopuri comerciale, cât și non-comerciale, atâta timp cât este transmisă nemodificată și în întregime, cu menționarea dvs. ca autor.',
    'licenses.name.cc-by-nc': 'Creative Commons Atribuire-NonComercial 4.0',
    'licenses.cc-by-nc': 'Această licență permite altora să remixeze, să modifice și să construiască pe baza lucrării dvs. în mod necomercial și, deși noile lor lucrări trebuie să vă recunoască și să fie necomerciale, nu trebuie să licențieze lucrările lor derivate în aceleași condiții.',
    'licenses.name.cc-by-nc-sa': 'Creative Commons Atribuire-NonComercial-Distribuire în condiții identice 4.0',
    'licenses.cc-by-nc-sa': 'Această licență permite altora să remodeleze, să ajusteze și să construiască pe baza lucrării dvs. în scopuri non-comerciale, atâta timp cât vă creditează și licențiază noile creații sub aceleași termeni.',
    'licenses.name.cc-by-nc-nd': 'Creative Commons Atribuire-NonComercial-FărăDerivate 4.0',
    'licenses.cc-by-nc-nd': 'Această licență este cea mai restrictivă dintre cele șase licențe principale, permițând doar altor persoane să descarce operele dvs. și să le împărtășească cu alții, atâta timp cât vă creditează, dar nu le pot modifica în niciun fel sau folosi în scopuri comerciale.',
    'licenses.name.lu-c': 'Drepturi de autor în Universul Literar',
    'licenses.lu-c': 'Licență standard de drepturi de autor care vă permite să vindeți și să publicați lucrarea dvs. așa cum doriți și să vă protejați drepturile asupra acesteia. Această licență vă oferă, de asemenea, opțiunea de a vinde poveștile dvs. pe Literary Universe.',
    'licenses.name.lu-e': 'Universul literar în exclusivitate',
    'licenses.lu-e': 'Această licență acordă Universului Literar drepturi exclusive de a publica și distribui online lucrarea dumneavoastră. Veți păstra drepturile de autor, dar Literary Universe va avea dreptul exclusiv de a publica și distribui online lucrarea dumneavoastră.',
    'licenses.name.lu-ne': 'Universul literar neexclusiv',
    'licenses.lu-ne': 'Această licență acordă Universului Literar drepturi neexclusive de publicare și distribuire a operei dvs. online. Veți păstra drepturile de autor și dreptul de a vă publica și distribui lucrarea prin alte canale.',
    'licenses.name.cc0': 'Niciun drept rezervat - CC0 1.0',
    'licenses.cc0': 'Puneți-vă munca în domeniul public. Spre deosebire de licențele CC, care permit deținătorilor de drepturi de autor să aleagă dintr-o serie de permisiuni, păstrându-și în același timp drepturile de autor, CC0 permite o cu totul altă alegere - alegerea de a renunța la protecția drepturilor de autor și a bazelor de date, precum și la drepturile exclusive acordate automat creatorilor - alternativa "niciun drept rezervat" la licențele noastre.',
    // License Chooser Modal
    'licenses.chooser.title': 'Selector de licențe',
    'licenses.chooser.button': 'Ajutați-mă să aleg o licență',
    'licenses.chooser.ariaLabel': 'Alegeți o licență pentru lucrarea dvs.',
    'licenses.chooser.introduction': 'Acest instrument vă va ajuta să alegeți cea mai potrivită licență pentru lucrarea dumneavoastră. Licența determină modul în care alții pot utiliza lucrarea dvs. și afectează capacitatea dvs. de a o monetiza pe Literary Universe.',
    // License Chooser Wizard Steps
    'licenses.chooser.step.contentType.title': 'Ce tip de conținut licențiați?',
    'licenses.chooser.step.contentType.description': 'Tipul de conținut influențează licențele care vă sunt disponibile.',
    'licenses.chooser.step.contentType.original': 'Lucrare originală',
    'licenses.chooser.step.contentType.fanfiction': 'Fan Fiction',
    'licenses.chooser.step.contentType.fanfictionNote': 'Lucrările de fan fiction de pe Literary Universe beneficiază automat de licența Creative Commons Attribution-NonCommercial (CC BY-NC). Acest lucru se datorează faptului că ficțiunea fanilor se bazează pe lucrări protejate de drepturi de autor deținute de alte persoane, iar utilizarea comercială ar putea încălca aceste drepturi.',
    'licenses.chooser.step.commercial.title': 'Doriți să vă monetizați munca?',
    'licenses.chooser.step.commercial.description': 'Alegerea de a vă monetiza munca afectează licența cea mai potrivită.',
    'licenses.chooser.step.commercial.yes': 'Da, vreau să-mi monetizez munca',
    'licenses.chooser.step.commercial.no': 'Nu, nu vreau să-mi monetizez munca',
    'licenses.chooser.step.commercial.monetizeNote': 'Pentru a vă monetiza munca pe Literary Universe, va trebui să utilizați una dintre licențele noastre comerciale. Aceste licențe vă permit să vă vindeți lucrările, păstrând în același timp protecția drepturilor de autor.',
    'licenses.chooser.step.exclusivity.title': 'Doriți să publicați exclusiv pe Literary Universe?',
    'licenses.chooser.step.exclusivity.description': 'Alegerea exclusivității afectează taxa de platformă și opțiunile de publicare.',
    'licenses.chooser.step.exclusivity.yes': 'Da, exclusiv pe Literary Universe',
    'licenses.chooser.step.exclusivity.no': 'Nu, vreau să public și în altă parte',
    'licenses.chooser.step.exclusivity.exclusiveNote': 'Cu publicarea exclusivă pe Literary Universe, veți beneficia de o taxă de platformă mai mică de 10%. Acest lucru înseamnă că veți păstra 90% din câștigurile dvs.',
    'licenses.chooser.step.exclusivity.nonExclusiveNote': 'Cu publicarea neexclusivă, vă puteți publica lucrarea și pe alte platforme. Taxa de platformă este de 30%, ceea ce înseamnă că veți păstra 70% din câștigurile dvs. pe Literary Universe. În viitor, vom oferi instrumente care să vă ajute să publicați pe alte platforme direct din Literary Universe.',
    'licenses.chooser.step.derivatives.title': 'Doriți să permiteți altora să creeze lucrări derivate?',
    'licenses.chooser.step.derivatives.description': 'Operele derivate includ adaptări, remixuri sau transformări ale operei dvs. originale.',
    'licenses.chooser.step.derivatives.yes': 'Da, permite lucrări derivate',
    'licenses.chooser.step.derivatives.no': 'Nu, nu permiteți lucrări derivate',
    'licenses.chooser.step.derivatives.allowNote': 'Permiterea lucrărilor derivate înseamnă că alții vă pot adapta, remixa sau transforma lucrarea. Acest lucru poate duce la o distribuție mai largă și la reutilizarea creativă a conținutului dumneavoastră.',
    'licenses.chooser.step.derivatives.disallowNote': 'Nepermiterea lucrărilor derivate înseamnă că lucrarea dvs. trebuie transmisă neschimbată și în întregime, deși poate fi totuși partajată cu atribuirea corespunzătoare.',
    'licenses.chooser.step.attribution.title': 'Doriți să solicitați atribuirea?',
    'licenses.chooser.step.attribution.description': 'Atribuirea înseamnă că alții trebuie să vă acorde credit atunci când folosesc munca dumneavoastră.',
    'licenses.chooser.step.attribution.yes': 'Da, necesită atribuire',
    'licenses.chooser.step.attribution.no': 'Nu, plasat în domeniul public (CC0)',
    'licenses.chooser.step.attribution.requireNote': 'Solicitarea atribuirii înseamnă că oricine utilizează munca dvs. trebuie să vă acorde credit în modul solicitat.',
    'licenses.chooser.step.attribution.publicDomainNote': 'Plasarea operei dvs. în domeniul public (CC0) înseamnă că renunțați la toate drepturile de autor și drepturile conexe. Alții pot utiliza liber lucrarea dvs. în orice scop, fără atribuire.',
    // License Result
    'licenses.chooser.result.commercialTitle': 'Informații comerciale',
    'licenses.chooser.result.exclusiveInfo': 'Cu licența Literary Universe Exclusive, veți beneficia de o taxă de platformă mai mică de 10%. Aceasta înseamnă că păstrați 90% din câștiguri, dar puteți publica această lucrare numai pe Literary Universe.',
    'licenses.chooser.result.nonExclusiveInfo': 'Cu licența neexclusivă Literary Universe, vă puteți publica lucrările și pe alte platforme. Taxa de platformă este de 30%, ceea ce înseamnă că veți păstra 70% din câștigurile dvs. pe Literary Universe. În viitor, vom oferi instrumente care să vă ajute să publicați pe alte platforme direct din Literary Universe.',
    'licenses.chooser.result.fanfictionNote': 'Această licență se aplică în mod automat lucrărilor de fan fiction, deoarece acestea se bazează pe materiale protejate de drepturi de autor deținute de alte persoane. Utilizarea comercială ar putea încălca aceste drepturi.',
    'licenses.chooser.result.selectLicense': 'Selectați această licență',
    // Adding missing internationalization strings
    'licenseChooser.contentType.title': 'Ce tip de conținut licențiați?',
    'licenseChooser.contentType.description': 'Tipul de conținut influențează licențele care vă sunt disponibile.',
    'licenseChooser.contentType.original.title': 'Lucrare originală',
    'licenseChooser.contentType.original.description': 'Conținut pe care l-ați creat în întregime singur.',
    'licenseChooser.contentType.fanfiction.title': 'Fan Fiction',
    'licenseChooser.contentType.fanfiction.description': 'Conținut bazat pe lucrări existente ale altor creatori.',
    'licenseChooser.contentType.fanfiction.note': 'Lucrările de fan fiction de pe Literary Universe beneficiază automat de licența Creative Commons Attribution-NonCommercial (CC BY-NC). Acest lucru se datorează faptului că fan fiction se bazează pe opere protejate de drepturi de autor deținute de alte persoane, iar utilizarea comercială ar putea încălca aceste drepturi.',
    'licenseChooser.commercial.title': 'Doriți să vă monetizați munca?',
    'licenseChooser.commercial.description': 'Alegerea de a vă monetiza munca afectează licența cea mai potrivită.',
    'licenseChooser.commercial.yes': 'Yes, I want to monetize my work',
    'licenseChooser.commercial.yes.title': 'Da, vreau să monetizez',
    'licenseChooser.commercial.yes.description': 'Vreau să câștig bani din munca mea pe Literary Universe.',
    'licenseChooser.commercial.no': 'No, I don\'t want to monetize my work',
    'licenseChooser.commercial.no.title': 'Nu, nu vreau să monetizez',
    'licenseChooser.commercial.no.description': 'Vreau să-mi împărtășesc munca liber, fără monetizare.',
    'licenseChooser.commercial.note': 'Pentru a vă monetiza munca pe Literary Universe, va trebui să utilizați una dintre licențele noastre comerciale. Aceste licențe vă permit să vă vindeți lucrările, păstrând în același timp protecția drepturilor de autor.',
    'licenseChooser.exclusivity.title': 'Doriți să publicați exclusiv pe Literary Universe?',
    'licenseChooser.exclusivity.description': 'Alegerea exclusivității afectează taxa de platformă și opțiunile de publicare.',
    'licenseChooser.exclusivity.yes': 'Yes, I want to publish exclusively on Literary Universe',
    'licenseChooser.exclusivity.yes.title': 'Da, exclusiv pe Literary Universe',
    'licenseChooser.exclusivity.yes.description': 'Voi publica această lucrare numai pe Literary Universe.',
    'licenseChooser.exclusivity.no': 'No, I want to publish elsewhere as well',
    'licenseChooser.exclusivity.no.title': 'Nu, vreau să public și în altă parte',
    'licenseChooser.exclusivity.no.description': 'Vreau să public această lucrare și pe alte platforme.',
    'licenseChooser.exclusivity.exclusive.note': 'Cu publicarea exclusivă pe Literary Universe, veți beneficia de o taxă de platformă mai mică de 10%. Acest lucru înseamnă că veți păstra 90% din câștigurile dvs.',
    'licenseChooser.exclusivity.nonExclusive.note': 'Cu publicarea neexclusivă, vă puteți publica lucrarea și pe alte platforme. Taxa de platformă este de 30%, ceea ce înseamnă că veți păstra 70% din câștigurile dvs. pe Literary Universe.',
    'licenseChooser.derivatives.title': 'Doriți să permiteți altora să creeze lucrări derivate?',
    'licenseChooser.derivatives.description': 'Operele derivate includ adaptări, remixuri sau transformări ale operei dvs. originale.',
    'licenseChooser.derivatives.yes': 'Yes, allow modifications',
    'licenseChooser.derivatives.yes.title': 'Da, permite lucrări derivate',
    'licenseChooser.derivatives.yes.description': 'Alții pot adapta, remixa sau transforma munca mea.',
    'licenseChooser.derivatives.no': 'No, don\'t allow modifications (ND)',
    'licenseChooser.derivatives.no.title': 'Nu, nu permiteți lucrări derivate',
    'licenseChooser.derivatives.no.description': 'Opera mea trebuie să fie transmisă neschimbată și în întregime.',
    'licenseChooser.attribution.title': 'Doriți să solicitați atribuirea?',
    'licenseChooser.attribution.description': 'Atribuirea înseamnă că alții trebuie să vă acorde credit atunci când folosesc munca dumneavoastră.',
    'licenseChooser.attribution.yes': 'Yes, require attribution (BY)',
    'licenseChooser.attribution.yes.title': 'Da, necesită atribuire',
    'licenseChooser.attribution.yes.description': 'Alții trebuie să-mi acorde credit atunci când folosesc munca mea.',
    'licenseChooser.attribution.no': 'No, allow use without attribution (CC0)',
    'licenseChooser.attribution.no.title': 'Nu, plasat în domeniul public (CC0)',
    'licenseChooser.attribution.no.description': 'Renunț la toate drepturile de autor și drepturile conexe asupra lucrării mele.',
    'licenseChooser.commercialUse.title': 'Doriți să permiteți utilizarea comercială a lucrărilor dumneavoastră?',
    'licenseChooser.commercialUse.description': 'Utilizarea comercială înseamnă că alții pot utiliza lucrarea dvs. în scopuri comerciale.',
    'licenseChooser.commercialUse.yes.title': 'Da, permite utilizarea comercială',
    'licenseChooser.commercialUse.yes.description': 'Alții pot folosi lucrările mele în scopuri comerciale.',
    'licenseChooser.commercialUse.no': 'No, non-commercial use only (NC)',
    'licenseChooser.commercialUse.no.title': 'Nu, numai pentru uz necomercial',
    'licenseChooser.commercialUse.no.description': 'Alții pot utiliza lucrările mele doar în scopuri necomerciale.',
    'licenseChooser.shareAlike.title': 'Doriți să solicitați Share-Alike?',
    'licenseChooser.shareAlike.description': 'Alegeți dacă alții trebuie să împărtășească adaptările lor în aceleași condiții.',
    'licenseChooser.shareAlike.yes.title': 'Share-Alike Necesar (SA)',
    'licenseChooser.shareAlike.yes.description': 'Dacă alții remixează, transformă sau construiesc pe baza lucrării dvs., aceștia trebuie să distribuie contribuțiile lor sub aceeași licență ca și originalul.',
    'licenseChooser.shareAlike.no.title': 'Share-Alike Nu este necesar',
    'licenseChooser.shareAlike.no.description': 'Alții pot distribui adaptări în orice condiții, chiar dacă acestea sunt mai restrictive decât licența dvs. originală.',
    'licenseChooser.shareAlike.yes': 'Da, necesită Share-Alike (SA)',
    'licenseChooser.shareAlike.no': 'Nu, nu necesită Share-Alike',
    'licenseChooser.cc0Confirmation.title': 'Confirmați Licența CC0 (Domeniul public)',
    'licenseChooser.cc0Confirmation.description': 'CC0 renunță la toate drepturile de autor și drepturile conexe pentru lucrarea dvs., plasând-o efectiv în domeniul public. Vă rugăm să confirmați înțelegerea dumneavoastră.',
    'licenseChooser.cc0Confirmation.important': 'Informații importante',
    'licenseChooser.cc0Confirmation.details': 'Prin selectarea CC0, renunțați la toate drepturile de autor și drepturile conexe pentru lucrarea dvs., în măsura permisă de lege. Aceasta înseamnă că:',
    'licenseChooser.cc0Confirmation.point1': 'Oricine poate utiliza lucrările dvs. în orice scop, inclusiv în scopuri comerciale',
    'licenseChooser.cc0Confirmation.point2': 'Nu este necesară atribuirea (deși este apreciată)',
    'licenseChooser.cc0Confirmation.point3': 'Alții vă pot modifica munca și nu pot partaja aceste modificări',
    'licenseChooser.cc0Confirmation.point4': 'Această decizie este irevocabilă odată ce ați publicat',
    'licenseChooser.cc0Confirmation.waiver': 'Înțeleg că renunț la toate drepturile de autor și drepturile conexe asupra lucrării mele',
    'licenseChooser.cc0Confirmation.understanding': 'Înțeleg termenii și efectul juridic al CC0 asupra operei mele',
    'licenses.learnMore': 'Aflați mai multe',
    'licenses.legalText': 'Text juridic',
    'licenses.chooser.back': 'Înapoi',
    'licenses.chooser.select': 'Selectați această licență',
    'licenses.commercial.title': 'Informații privind licența comercială',
    'licenses.commercial.exclusive': 'Cu această licență exclusivă, Literary Universe va percepe o taxă de 10% din câștigurile tale. Acest lucru înseamnă că veți primi 90% din veniturile generate de lucrările dvs. pe platforma noastră.',
    'licenses.commercial.nonExclusive': 'Cu această licență neexclusivă, Literary Universe va încasa o taxă de 30% din câștigurile dvs. de pe platforma noastră. Aceasta înseamnă că veți primi 70% din veniturile generate de lucrările dvs. pe Literary Universe.'
};