export default {
  'personalNotes.personalNotes': 'Note Personale',
  'personalNotes.chooseType': 'Alegeți tipul de notă personală',
  'personalNotes.storyNotes': 'Note despre Poveste',
  'personalNotes.chapterNotes': 'Note despre Capitole',
  'personalNotes.universeNotes': 'Note despre Univers',
  'personalNotes.encyclopediaNotes': 'Note de Enciclopedie',
  'personalNotes.storyPersonalNotesHeading': 'Note Personale despre Povești',
  'personalNotes.encyclopediaPersonalNotesHeading': 'Note Personale despre Enciclopedie',
  'personalNotes.searchPersonalNotesHeading': 'Căutați Note Personale',
  'personalNotes.goToStory': 'Du-te la poveste',
  'personalNotes.goToChapter': 'Du-te la capitol',
  'personalNotes.goToEncyclopedia': 'Du-te la Enciclopedia Universului',
  'personalNotes.goToEncEntry': 'Du-te la intrare',
  'personalNotes.closeDropdown': 'Închideți meniul derulant',
  'personalNotes.chapterName': 'Capitol {sequence} - {title}',
  'personalNotes.objectPersonalNotes': '{object} notă personală',
  'personalNotes.searchResults': 'Rezultate Căutare',
  'personalNotes.type.story': 'Poveste',
  'personalNotes.type.universe': 'Univers',
  'personalNotes.type.chapter': 'Capitol',
  'personalNotes.type.encEntry': 'Intrare Enciclopedie',
  'personalNotes.type.revTextBlock': 'Blox Text Revizuire',
  'personalNotes.chapter': 'Capitol',
  'personalNotes.recentSearches': 'Căutări Recent efectuate:'
};