export default {
    'writer.menu.optionsAria': 'Meniu opțiuni editor',
    'writer.menu.saveOptionsAria': 'Opțiuni de salvare',
    'writer.undo': 'Anulează',
    'writer.redo': 'Refă',
    'writer.ul': 'Listă neordonată',
    'writer.ol': 'Listă ordonată',
    'writer.blockquote': 'Citat',
    'writer.link': 'Inserați un link',
    'writer.image': 'Inserați o imagine',
    'writer.bold': 'Îngroșați selecția',
    'writer.underline': 'Subliniați selecția',
    'writer.italic': 'Emfazați selecția',
    'writer.wordCount': '{characters, number} caractere, {words, number} cuvinte',
    'writer.characterCount': '{characters, number} caractere',
    'finder.details': 'detalii',
    'finder.remove': 'Eliminați conexiunea',
    'finder.connect': 'Conectați selecția la intrarea din enciclopedie',
    'writer.aside.ariaLabel': 'Meniu de opțiuni de ajutor',
    'writer.nothingToSave': 'Nimic de salvat',
    'writer.link.placeholder': 'Introduceți o adresă URL',
    'writer.link.error.empty': 'URL-ul nu poate fi gol',
    'writer.link.error.invalid': 'Vă rugăm să introduceți o adresă URL validă',
    'writer.publish.publishAria': 'Opțiuni de publicare',
    'writer.publish.scheduleExplained': 'Puteți fie să publicați imediat, fie să programați ca capitolul să fie disponibil la o dată ulterioară.',
    'writer.publish.schedule': 'Setați data publicării',
    'writer.publish.previousChapterPublished': 'Capitolul anterior a fost publicat pe {publishDate, date, short} la {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'Capitolul precedent urmează să fie publicat pe {publishDate, date, short} la adresa {publishDate, time}',
    'writer.publish.alreadyPublished': 'Acest capitol a fost deja publicat pe {publishedAt, date, short}. Noi versiuni vor fi publicate imediat.',
    'writer.publish.betaReader': 'Beta',
    'writer.publish.public': 'Publicare',
    'writer.publish.now': 'Publică acum',
    'writer.publish.schedulePrevious': 'Trebuie să publicați sau să programați publicarea capitolului anterior înainte de a-l putea publica pe acesta.'
};