export default {
    'challenges.current': 'Aktualaj defioj',
    'challenges.wordcount.goal': 'Celo de vorto-kvanto',
    'challenges.wordcount.dailygoal': 'Celo de ĉiutaga vorto-kvanto',
    'challenges.wordcount.today': 'Hodiaŭ verkita',
    'challenges.wordcount.total': 'Entute verkita vortojn',
    'challenges.wordcount.remaining': 'Restantaj vortoj',
    'challenges.wordcount.daysleft': 'Restantaj tagoj',
    'challenges.wordcount.currentDay': 'Nuna tago',
    'challenges.wordcount.average': 'Meza vortoj por tago',
    'challenges.wordcount.finishOn': 'Je nuna rapido vi finos je',
    'challenges.wordcount.finishOnTime': 'Vortoj por verki ĉiutage por fini ĝuste',
    'challenges.wordcount.graph.day': 'Tago {day}',
    'challenges.underway': 'Ĉi tiu defio jam komenciĝis.',
    'challenges.targetWords': 'Entuta celita vorto-kvanto',
    'challenges.startDate': 'Komenco-dato',
    'challenges.endDate': 'Fino-dato',
    'challenges.future': 'Venontaj defioj',
    'challenges.future.wordcount': 'Wordcount challenge staring on {startDate, date, short} with goal of {target, number} by {endDate, date, short}.',
    'challenges.future.nanowrimo': 'NaNoWriMo defio estas preta.',
    'challenges.wordcount': 'Vorto-kvanto',
    'challenges.wordcount.desc': `Set yourself a goal of how many words you want to write this month for this {type, select,
    story {story}
    universe {universe}
    other {}
  }.`,
    'challenges.wordcount.select': 'Kiom da vortoj vi volas defii al vi mem?',
    'challenges.start': 'Komenci defion',
    'challenges.report': 'Raporti',
    'challenges.victory': 'Gratulojn! Vi sukcesis ĉi tiun defion.',
    'challenges.defeat': 'Bedaŭrinde vi ne sukcesis ĉi tiun defion.',
    'challenges.baseline': 'The current wordcount for this story is {wordcount, number}, this will be the starting point.',
    // NaNoWriMo
    'nanowrimo.full': 'Nacia Monato de Verkado de Romano',
    'nanowrimo.site': 'Oficiala retejo de NaNoWriMo',
    'nanowrimo.settings': 'Konto de NaNoWriMo',
    'nanowrimo.username': 'Uzantonomo de NaNoWriMo',
    'nanowrimo.key': 'Sekreta ŝlosilo',
    'nanowrimo.key.get': 'Prenu vian NaNoWriMo ŝlosilon.',
    'nanowrimo.key.get.notice': 'Vi devas esti ensalutita por vidi ĝin.',
    'nanowrimo.ongoing': 'estas en plena fluo! {countdown} pliaj tagoj por iri!',
    'nanowrimo.startsin': `komencos en {countdown, plural,
      one {1 tago}
      other {# tagoj}
    }! Preparu vin!`,
    'nanowrimo.isover': 'NaNoWriMo finiĝis. Ĝis revido venontjare!',
    'nanowrimo.select': 'Asignu ĉi tiun rakonton por NaNoWriMo.',
    'nanowrimo.baseline': 'Kiam NaNoWriMo komenciĝas, ĝi prenos la nunan vortkvanton kaj uzos ĝin kiel bazlinion, el kiu ajn aldonaĵaj vortoj estos konsiderataj kiel parto de NaNoWriMo.',
    'nanowrimo.victory': 'Gratulon! Vi venkis NaNoWriMo-n!',
    'nanowrimo.challenge': 'NaNoWriMo defio',
    'nanowrimo.description': 'La defio estas verki romanon de {words, number} vortoj dum novembro.',
    'nanowrimo.error.usernotfound': 'La uzantonomo ne estis trovita en la serviloj de NaNoWriMo.',
    'nanowrimo.error.nobook': 'Neniu libro estis trovita. Bonvolu certiĝi, ke vi kreis vian libron sur NaNoWriMo.',
    'nanowrimo.error.wordcount': 'Ne eblis agordi vortkvanton sur NaNoWrimo, bonvolu dufoje kontroli viajn akreditojn kaj reprovi.',
    'nanowrimo.connected': 'Vi asignis ĉi tiun rakonton por NaNoWriMo.',
    'nanowrimo.connected.other': 'Vi jam asignis alian rakonton.'
};