export default {
    'homepage.welcome': 'Welcome to Literary Universe!',
    'homepage.read': 'Legi',
    'homepage.explore': 'Esplori',
    'homepage.create': 'Krei',
    'homepage.read.desc': 'Enjoy a great reading experience with access to details of the stories\' universe adjacent to the story text, without the need to leave the story window.',
    'homepage.explore.desc': 'Stories are not the only way to explore the literary universes. Each universe has its own page where you can explore all the minutia in the universe encyclopedia, see all the stories in the universe or explore what other fans have written.',
    'homepage.create.desc': 'Create your own stories and universes via our editor. Build and manage your ever expanding universes. We offer an expanding toolset, from a great story editor, through a great encyclopedia to management of translations of your stories and universe!',
    'homepage.begin': 'Begin your journey!',
    'homepage.itisfree': 'It is free!',
    'about.title': 'About Literary Universe',
    'about.desc': 'History, secrets and humans behind Literary Universe.',
    'about.text.1': 'Literary Universe is designed both for writers and for the avid reader. Writers can use the site to write original works through the workshop button in the dashboard menu. This will give you access to the main editor and encyclopedia functions which primarily focus on organizing all aspects of your personal story universe into one page. The social aspects allow authors to broadcast their work and develop a following, as well as to interact more directly if they chose with their readers.',
    'about.text.2': 'Readers can use the site primarily to read new works and follow authors but also to help edit pre-published stories if given permission by the writer. Being a reader on Literary Universe is a whole new reading experience, having access to all the background information on the same page as the main story gives you insight into the mind of the author like never before.',
    'about.text.3': 'The future for Literary Universe involves creating a marketplace for authors to sell their work and adding community features to enhance author and reader communication through blogs and forums. Writer’s tools will be added over time, with over a dozen currently either in development or on the board. Our ultimate goal is to enhance the experiences of writers and readers through providing more innovative use of the internet medium.',
    'about.text.4': 'We hope that you join us as we explore what the internet medium can do for creative writing!',
    'about.team': 'La teamo',
    'about.history': 'Historio',
    'about.CEO': 'Chief Executive Officer',
    'about.CTO': 'Chief Technology Officer',
    'about.jan': 'Jan is the founder, visionary and technological brain behind Literary Universe. As a writer of large literary universes, Jan had always found it difficult to write stories from a technical and readability point of view that would not compromise the reading experience. As such, Jan decided to pursue his studies in web development to create an application that would make it easy to write stories in large universes.',
    'about.history.text': 'In 2010 Jan started at Rochester Institute of Technology to learn more about web development in order to be able to build a creative writing site. This materialized in 2013 when the first proof of concept was presented at Imagine RIT. Jan continued his studies and in 2016 a new version of the app was created as a Master\'s Capstone Project. The project continued in fall 2016 and further developed into what you see today.',
    'copyrights.desc': 'The full text of Literary Universe Copyrights Agreement.',
    'privacy.desc': 'Full legal text of Privacy Policy of Literary Universe.',
    'guidelines.desc': 'Community Guidelines of Literary Universe.',
    'tos.desc': 'Full legal text of Terms of Service of Literary Universe.',
    'homepage.intro': 'Explore and create literally universes & great stories.',
    'homepage.explanation': 'Literary Universe is a creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'gdpr.title': 'GDPR Compliance',
    'gdpr.desc': 'Literary Universe is compliant with the EU GDPR directives.',
    'gdpr.compliant': 'Literary Universe is GDPR Compliant',
    'gdpr.compliant.text': 'Literary Universe has implemented various updates and changes to its codebase in preparation for GDPR enforcement on May 25th 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'Changes in this version',
    'dmca.title': 'Digital Millennium Copyright Act (DMCA) Policy',
    'dmca.subtitle': 'Copyright Dispute Policy',
    'dmca.step1.title': 'Procedure for Reporting Copyright Infringements.',
    'dmca.step2.title': 'Once Proper Bona Fide Infringement Notification is Received by the Designated Agent.',
    'dmca.step3.title': 'Procedure to Supply a Counter-Notice to the Designated Agent.',
    'dmca.desc': 'We take copyright violations seriously.',
    'gdpr.access.title': 'Right of Access and Right of Data Portability',
    'gdpr.access.desc': 'In user settings you can export all your data. This data will be in standard JSON format.',
    'gdpr.forget.title': 'Right to be forgotten',
    'gdpr.forget.desc': 'Any account can be deleted via user settings. Some data might be preserved, especially if they have been subject to sale and/or disputes.',
    'gdpr.rectification.title': 'Right to Rectification',
    'gdpr.rectification.desc': '',
    'gdpr.processing.title': 'Right to restriction of processing',
    'gdpr.processing.desc': 'Literary Universe fully respects the browser settings, such as "Do not track" requests for reporting to our Matomo statistics server.',
    'gdpr.object.title': 'Right to Object',
    'gdpr.object.desc': '',
    'dmca.step1.desc1': 'Reporting is split into two scenarios. 1. Internal property (infringement on site of property existing on site). 2. External property (infringement on site of property not existing on site).',
    'dmca.step1.desc2': 'Reporting internal property can be done via report button on the property. Reporting external property infringement can be done via feedback screen. In both cases you will be asked to provide personal details and additional details that will allow us to check your ownership.',
    'dmca.step1.desc3': 'Please note that making a false claims will result in your inability to file claims in the future.',
    'dmca.step2.desc1': 'Upon receiving your report we will verify your credentials and ownership claim. If everything is fine we will proceed to check claim. If we determine claim as true we will make the infringing property inaccessible until counter-notice determination or 14 days have passed after which it will be deleted.',
    'dmca.step3.desc1': 'Once a complaint has been received the owner of designated property will have 14 days to file a counter notice. Designated Agent will then proceed to investigate the dispute. Any decision by the Designated Agent at this stage will be final.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Attributions',
    'about.attributionsIntro': 'Literary Universe builds on top of many Open Source projects and free resources. Bellow you will find their listing.',
    'about.attributionsMatomo': 'Our analytics use self-hosted Matomo with IP2Location LITE data available from https://lite.ip2location.com.',
    'about.attributionIcons': 'The following icons are used through the site via styled-icons:',
    'team.name.sedwards': 'Scott Edwards',
    'team.name.rhubbell': 'Raena Hubbell',
    'team.name.pjakubec': 'Pavel Jakubec',
    'team.name.asebesta': 'Adam Šebesta',
    'about.developer': 'Programisto',
    'about.seniorDeveloper': 'Senior Developer',
    'about.juniorDeveloper': 'Junior Developer',
    'about.apprenticeDeveloper': 'Apprentice Developer',
    'about.intern': 'Intern',
    'about.advisor': 'Advisor',
    'about.headOfResearch': 'Head of Research',
    'about.cfo': 'Chief Financial Officer'
};