export default {
    'reader.storyEnd.heading': 'Fino',
    'reader.storyEnd.description': 'Vi atingis la finon de la rakonto.',
    'reader.externalSale.heading': 'Ne ĉi tie ankoraŭ',
    'reader.externalSale.description': 'Ĉi tiu rakonto ne estas havebla en Literatura Universo, sed vi povas aĉeti ĝin en aliaj lokoj.',
    'reader.storyTBC.heading': 'Daŭrigos...',
    'reader.storyTBC.description': 'Tio estas ĉio, kion ni havas por la rakonto ĝis nun, sed la aventuro daŭros en la estonteco, revenu baldaŭ!',
    'chapter.translation.notYetDescription': 'Reiru baldaŭ!',
    'reader.externalShopping.heading': 'Aĉetu {storyName} en butikoj:',
    'chapter.next': 'Venonta ĉapitro',
    'chapter.previous': 'Antaŭa ĉapitro',
    'chapter.comment': 'Komentarioj pri ĉi tiu ĉapitro',
    'reader.language': 'Lingvo:',
    'reader.fullscreen.enter': 'Enigu tutan ekrankopion',
    'reader.fullscreen.exit': 'Eliru el la tutekrana reĝimo',
    'reader.details.universe': 'Detaloj pri universo',
    'reader.details.story': 'Detaloj pri rakonto',
    'reader.darkmode': 'Ŝalti malhelan modon',
    'reader.flowtext': 'Ŝalti teksta grandecagon',
    'reader.menu.optionsAria': 'Menuo por legantaj opcioj',
    'reader.accessibility': 'Ŝalti alireblon',
    'chapter.translation.notYet': 'Ĉi tiu ĉapitro ankoraŭ ne estas tradukita.',
    'externalShopping.buyLink.amazon': 'Aĉetu ĉe Amazon',
    'externalShopping.buyLink.other': 'Aĉetu ĉe {storeName}',
    'externalShopping.buyLink.bookshop': 'Aĉetu ĉe Bookshop.org',
    'reader.accessibility.aria': 'Alireblaj opcioj pri alirebleco',
    'reader.accessibility.toggleDyslexic': 'Ŝalti disleksian tiparon',
    'reader.accessibility.toggleParagraphStripes': 'Ŝalti fonekstran ĉaprajtorigon',
    'reader.accessibility.toggleParagraphHighlight': 'Ŝalti elektan ĉaprajton',
    'reader.accessibility.toggleRules': 'Ŝalti helpan linion',
    'reader.nextRelease.scheduled': 'Venonta ĉapitro aperos en {nextReleaseAt, date} ĉe {nextReleaseAt, time}!',
    'reader.storyContinues': 'La rakonto daŭras...',
    'reader.storyOnHiatus': 'La aŭtoro nun malfermas paŭzon ĉi pri la rakonto kaj ĝi estas interrompita. Revenu en monato aŭ du.',
    'reader.storyCancelled': 'Bedaŭrinde, tion estas ĉio. La rakonto estas nuligita do ne verŝajne estos io nova.',
    'reader.storyCancelled.heading': 'Nuligita',
    'reader.nextChapterEstimation.verySoon': 'Bazita sur la lasta {chaptersCount} ĉapitro publik-dato, la sekvonta ĉapitro devus esti eldonita tre baldaŭ.',
    'reader.nextChapterEstimation.days': 'Bazita sur la lasta {chaptersCount} ĉapitro publik-dato, la sekvonta ĉapitro devus esti eldonita post {daysLeft} tagoj',
    'reader.nextChapterEstimation.notEnoughChapters': 'Ankaŭ ni liveros antaŭŝatitan daton por la eldado de la sekvonta ĉapitro, post kiam tiu rakonto havos pli ol unu ĉapitro.'
};