/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'Universo Literário',
    'site.description': 'Universo literário é uma plataforma criativa e de publicação para universos de grandes histórias.',
    'site.keywords': 'escrita criativa, ficção cientifica, fantasia, escrita, publicação, traduções, história, histórias, universo',
    'site.logoAlt': 'Logotipo Universo Literário',
    mobileMenu: 'Menu Mobile',
    'common.signin': 'Login',
    'common.signup': 'Cadastre-se',
    'common.signout': 'Sair',
    'common.dashboard': 'Início',
    'common.discovery': 'Descobrir',
    'common.library': 'Biblioteca',
    'common.library.own': 'Sua biblioteca',
    'common.workshop': 'Workshop',
    'common.pm': 'Mensagens',
    'common.settings': 'Configurações',
    'common.options': 'Opções',
    'common.profile': 'Perfil',
    'common.blog': 'Blog',
    'common.blogs': 'Blogs',
    'common.about': 'Sobre nós',
    'common.accessdenied': 'Acesso negado',
    'common.accessdenied.msg': 'Você não tem permissão para entrar aqui. Se você deveria ter acesso, por favor, entre em contato com o proprietário e peça para verificar as configurações novamente.',
    'common.loading': 'Carregando...',
    'common.add': 'Adicionar',
    'common.save': 'Salvar',
    'common.email': 'E-mail',
    'common.soon': 'Em breve...',
    'common.search': 'Buscar',
    'common.search.do': 'Buscar',
    'common.searching': 'Procurando...',
    'common.report': 'Reportar',
    'common.user': 'Usuário',
    'common.users': 'Usuários',
    'common.showmore': 'Mostrar mais',
    'common.futurefeature.title': 'Recurso futuro',
    'common.futurefeature.text': 'Lamentamos muito, mas este recurso não está disponível neste momento. Estamos trabalhando para torná-lo disponível o mais rápido possível.',
    'common.nothingfound': 'Nada encontrado',
    'common.explore': 'Explorar',
    'common.by': 'por ',
    // keep the space at the end as username follows
    'common.scratchpad': 'Bloco de rascunho',
    'common.scratchpad.own': 'Seu bloco de rascunho',
    'common.news': 'Novidades',
    'common.encyclopedia': 'Enciclopédia',
    'common.story': 'História',
    'common.stories': 'Histórias',
    'common.universe': 'Universo',
    'common.universes': 'Universos',
    'common.collaborator': 'Colaborador',
    'common.collaborators': 'Colaboradores',
    'common.translator': 'Tradutor',
    'common.translators': 'Tradutores',
    'common.betareader': 'Beta reader',
    'common.betareaders': 'Beta readers',
    'common.post': 'Post',
    'common.statistics': 'Estatísticas',
    'common.lang.select': 'Selecionar idioma',
    'common.submit': 'Submit',
    'common.close': 'Fechar',
    'common.comment': 'Comment',
    'common.comments': 'Comments',
    404: 'Página não encontrada',
    'search.users': 'Search for users',
    'search.user': 'Search for user',
    'common.help': 'Help',
    'common.or': 'or',
    'common.account.create': 'Criar conta',
    'signup.username': 'Usuário',
    'signup.email': 'Seu e-mail',
    'signup.password.label': 'Sua senha',
    'signup.password.repeat': 'Confirme sua senha',
    'common.password': 'Senha',
    'signin.password.forgot': 'Esqueceu sua senha?',
    'dashboard.whatsnew': 'What is new',
    'dashboard.blog': 'Your blog',
    'common.footer.tagline': 'Escrever e ler universos complexos tornados fáceis.',
    'common.footer.plans': 'Plans & Pricing',
    'common.legal.tos': 'Terms of Service',
    'common.legal.community': 'Community Guidelines',
    'common.legal.privacy': 'Política de Privacidade',
    'common.legal.copyright': 'Copyright Agreement',
    'common.legal.disclaimer': '© {year} Todos os direitos reservados, todos os textos pertencem a seus respectivos autores.',
    'premium.only.title': 'Não é suficientemente alto para ser membro',
    'premium.only.msg': 'Pedimos desculpas, sua posição de membro não é alta o suficiente para acessar este recurso.',
    'premium.only.join': 'Oferecemos variedades de planos para que todos possam obter o máximo do Universo Literário.',
    'premium.only.link': 'Confira!',
    'universe.visit': 'Visite a página do universo',
    'common.fanfiction': 'Fan Fiction',
    'story.chapter': 'Chapter',
    'story.chapters': 'Chapters',
    'story.genre': 'Genre',
    'story.genres': 'Genres',
    'story.read': 'Read',
    'story.lastUpdate': 'Last updated on {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Finished on {date, date, medium}.',
    'story.comments.for': 'Comments for {story} {chapter}.',
    'story.cover.alt': 'Story cover image for {story}.',
    'story.note.fanfiction': 'NOTE: This story is a fan fiction on {universe} universe.',
    copyrights: 'Direitos autorais',
    'common.challenges': 'Desafios',
    // for beta only
    'beta.notice': 'Bem-vindo ao Universo Literário BETA. Esta é uma prévia pública e, como tal, o aplicativo ainda é um trabalho em andamento. Isto significa que você ainda pode esperar erros e características inacabadas. Se você encontrar um erro ou algo que não esteja funcionando, por favor nos avise e seja paciente enquanto colocamos tudo no lugar.',
    'beta.thanks': 'Obrigado por seu apoio!',
    'scratchpad.about': 'Suas notas e idéias acessíveis em qualquer lugar do site.',
    'common.feedback': 'Feedback',
    'common.createdOn': 'Criado em {date, date, long}',
    'common.createdOn.title': 'Criado em',
    // account types
    admin: 'Admin',
    goodbye: 'Obrigado! Até a próxima!',
    'common.saved': 'Salvo!',
    'common.saving': 'Saving...',
    'common.friends': 'Amigos',
    'lang.orig': 'Idioma original',
    'lang.orig.plus': 'Idioma original - {language}',
    buy: 'Buy',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    processing: 'Processando...',
    'common.noData': 'No data',
    'error.title': 'Ocorreu um erro. Pedimos desculpas pelo inconveniente.',
    'common.offlineStatus': 'Você está atualmente offline.',
    male: 'Masculino',
    female: 'Feminino',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: 'Favor selecionar',
    'common.statusFailed': 'Falha na conexão com o servidor.',
    'common.statusConnecting': 'Tentativa de conexão ao servidor... ({count, number})',
    'slug.checking': 'Checking...',
    'slug.failed': 'Este endereço já existe.',
    'slug.success': 'Este endereço está disponível!',
    'notVerified.msg': 'Seu e-mail não foi verificado.',
    'notVerified.verify': 'Por favor, verifique seu e-mail.',
    unknown: 'desconhecido',
    'common.legal.guidelines': 'Diretrizes Comunitárias',
    'errorLoading.title': 'Erro durante o carregamento da página',
    'errorLoading.explained': 'Ocorreu um erro enquanto a página estava carregando. Pedimos desculpas pelo inconveniente. Por favor, tente novamente acessar a página novamente. Se o problema persistir, por favor, avise-nos.',
    'errorLoading.retry': 'Tente novamente!',
    'errorLoading.takingLong': 'Isto está demorando muito tempo...',
    'common.title': 'Título',
    'common.timelines': 'Cronogramas',
    'common.legal.gdpr': 'RGPD',
    'common.legal.gdpr.long': 'General Data Protection Regulation',
    'editor.placeholder.link': 'Digite o URL...',
    'editor.placeholder.connection': 'Procurar por entrada na enciclopédia...',
    'editor.saved.beta': 'Nova revisão para leitores de Beta criada!',
    'editor.saved.public': 'Nova versão publicada!',
    goodbyeForever: 'Sentimos muito em vê-lo partir. Foi algo que nós fizemos? Por favor, nos avise se for o caso. De qualquer forma, desejamos a você o melhor em seus esforços futuros e esperamos nos encontrar novamente! Vivam muito tempo e prosperem!',
    'goodbyeForever.feedback': 'Let us know what we can do better',
    'common.edit': 'Edit',
    'common.publish': 'Publish',
    'common.publishAt': 'Publication date and time',
    'a11y.user.menu': 'User menu',
    'dashboard.profile': 'Seu perfil',
    'profile.website': 'My personal website',
    'story.notes.concept': 'Concept',
    'story.notes.settings': 'Story setting',
    'story.notes.theme': 'Theme',
    'story.notes.impact': 'Desired impact',
    'story.notes.outcome': 'Outcome',
    'story.notes.audience': 'Target audience',
    'story.notes.pitch': 'Pitch',
    'story.notes.notes': 'Notes',
    'story.authorsNotes': 'Author\'s notes',
    'common.members': 'Members',
    'common.language': 'Idioma',
    next: 'Next',
    'common.legal.tos.short': 'Termos',
    'common.legal.privacy.short': 'Privacidade',
    'premium.increaseLimit': 'Considere melhorar para aumentar seu limite.',
    'common.sharing': 'Sharing',
    'story.isbn': 'ISBN',
    'common.name': 'Nome',
    'common.remove': 'Remover',
    'common.time.milliseconds': 'Milliseconds',
    'common.time.seconds': 'Segundos',
    'common.time.minutes': 'Minutos',
    'common.time.hours': 'Horas',
    'common.time.days': 'Dias',
    'common.time.weeks': 'Semanas',
    'common.time.months': 'Meses',
    'common.time.years': 'Anos',
    'common.monetization': 'Monetization',
    'common.tab.monetizationOptions': 'Monetization options',
    'common.pagination': 'Pagination'
}    /* eslint-enable max-len */;