export default {
  'courses.courses': 'Courses',
  'courses.overview': 'Visão geral dos cursos',
  'course.create': 'Criar um novo curso',
  'course.reading.title': 'Reading assignment title',
  'course.question.add': 'Add question',
  'course.add.courseElement': 'Add a new course element',
  'course.lessons.newMessage': 'Create and organize your lessons for effective teaching',
  'course.reading.new': 'Reading Assignment',
  'course.reading.newMessage': 'Create and organize reading assignments for your students',
  'course.writing.new': 'Tarefa de escrita',
  'course.writing.newMessage': 'Quickly set up and distribute writing tasks',
  'course.question.text': 'Sua pergunta vai aqui',
  'course.question.type': 'Please select a type of question',
  'course.question.delete': 'Remove question',
  'course.type': 'Selecione o tipo de curso',
  'course.visibility': 'Selecione a opção de visibilidade',
  'course.title': 'Título',
  'course.description': 'Descrição',
  'course.cover': 'Capa',
  'course.start': 'Seu curso começa em',
  'course.ends': 'Seu curso termina em',
  'course.curriculum': 'Currículo',
  'course.members': 'Alunos e professores',
  'course.assignments': 'Assignments',
  'course.question.deleteWhole': 'Excluir a pergunta inteira',
  'course.question.yes': 'Sim',
  'course.question.no': 'Não',
  'course.lesson.title': 'Título da lição',
  'course.lesson.add.universe': 'Adicionar História/Universo',
  'course.lesson.add.link': 'Adicionar link externo',
  'course.status': 'Status',
  'course.active': 'Activity',
  'course.active.message': 'Active',
  'course.inactive': 'Inactive',
  'course.module.edit': 'Edit module name',
  'course.upload.resource': 'Upload a file resource',
  'course.question.answer': 'Add answer',
  'course.question.open': 'Open question',
  'course.question.close': 'Closed question',
  'course.question.multiple': 'Multiple-choice question',
  'course.about': 'About this course',
  'course.lesson.new': 'Create a new lesson',
  'course.lesson.type': 'Lesson type',
  'course.lesson.inPerson': 'In person',
  'course.lesson.preRecorded': 'Pre-recorded',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Text only',
  'course.lesson.content': 'Lesson content',
  'course.lesson.description': 'Public description',
  'course.add.module': 'Add new module',
  'course.add.story': 'Add story',
  'course.remove.story': 'Remove story',
  'course.dateOfPublish': 'Date of publishing',
  'course.lesson.meetInPerson': 'Meet in person',
  'course.curriculum.edit': 'Edit curriculum',
};
