export default {
    'discovery.meta.desc': 'Descubra novas histórias e universos.',
    'discovery.universes.new': 'Universos emergentes',
    'discovery.stories.new': 'Novas histórias',
    'discovery.stories.standalone.new': 'Novas histórias autônomas',
    'discovery.stories.updated': 'Histórias atualizadas recentemente',
    'discovery.continue': 'Continue lendo',
    'discovery.stories.similar.new': 'Novas histórias no bairro',
    'discovery.stories.similar.regular': 'Histórias no bairro',
    'story.estimatedReadingTime': `Esta história deve levar {hours, plural,
        =0 {}
        one {1 hora e }
        other {# horas e }
    }{minutes, plural,
        =0 {0 minutos}
        one {1 minuto}
        other {# minutos}
    }.`,
    'story.estimatedReadingTime.explained': 'Baseado em uma velocidade média de leitura de {avgReadingNum, number} palavras por minuto.',
    'discover.search.text': 'Pesquisar termo',
    'discover.searchStory.title': 'Busca de uma história',
    'discover.searchStory.description': 'Busca de uma história',
    'discover.searchUniverse.title': 'Busca de um universo',
    'discover.searchUniverse.description': 'Busca de um universo',
    'discover.search.storyStatus': 'Status do progresso da história',
    'discover.search.genres': 'Gêneros',
    'story.status.complete': 'Completo',
    'story.status.inProgress': 'Em andamento',
    'discover.search.universeConnection': 'Conexão da história com o universo',
    'story.universeRelation.standalone': 'História autônomas',
    'story.universeRelation.fanFiction': 'Ficção do ventilador',
    'story.universeRelation.universe': 'Parte de um universo',
    'discover.search.rating': 'Classificação etária',
    'discover.search.license': 'Licença de direitos autorais',
    'discover.search.language': 'Idioma',
    'discover.search.resultsTotal.universe': `{results, plural,
        =0 {Nenhum universo corresponde a seus parâmetros}
        one {1 universo encontrado}
        other {# universos encontrados}
    }.`,
    'discover.search.resultsTotal.story': `{results, plural,
        =0 {Nenhuma história corresponde aos seus parâmetros}
        one {1 história encontrada}
        other {# histórias encontradas}
    }.`,
    'discover.viewSelection.aria': 'Ver seleção',
    'discover.searchDisplay.covers': 'Listagem de coberturas',
    'discover.searchDisplay.list': 'Lista compacta',
    'discover.includesAds': 'Este trabalho tem colocação de produtos ou inclui outras formas de anúncios.',
    'discovery.featured.universes': 'Universos em destaque',
    'discovery.featured.stories': 'Histórias em destaque',
    'discovery.story.tableOfContent': 'Sumário',
    'story.status.hiatus': 'Em hiato',
    'story.status.cancelled': 'Cancelado',
    'story.chapter.wasRead': 'Lido - {readAt, date}',
    'discovery.moreDetails': 'Mais detalhes',
    'discovery.read': 'Lido',
    'discovery.chapters.showAll': 'Mostrar todos os capítulos',
    'discovery.chapters.showMore': 'Mostrar mais capítulos',
    'discovery.chaptersTotal': 'Número total de capítulos da história',
    'discovery.readFromStart': 'Ler desde o primeiro capítulo',
    'discovery.readLatest': 'Ler o último capítulo',
    'discovery.author': 'Autor',
    'discovery.aiGenerated': 'Gerado por IA',
    'discovery.isAIGenerated': 'Este trabalho foi gerado por IA.',
    'discovery.isPreview': 'Prévia',
    'discovery.isPreview.explained': 'Esta história é fornecida apenas como uma prévia do trabalho.',
    'discovery.includesAds': 'Inclui anúncios',
    // AI content related strings
    'discovery.ai.content': 'Conteúdo gerado por IA',
    'discovery.ai.universes': 'Universos gerados por IA',
    'discovery.ai.stories': 'Histórias geradas por IA',
    'discovery.ai.noContent': 'Ainda não há conteúdo gerado por IA disponível.',
    'discovery.ai.noUniverses': 'Ainda não há universos gerados por IA disponíveis.',
    'discovery.ai.noStories': 'Ainda não há histórias geradas por IA disponíveis.',
    'discover.search.aiContent': 'Conteúdo de IA',
    'discover.search.aiContent.both': 'Mostrar todo o conteúdo',
    'discover.search.aiContent.none': 'Ocultar conteúdo gerado por IA',
    'discover.search.aiContent.only': 'Mostrar apenas conteúdo gerado por IA',
    'discovery.aiContent.indicator': 'Este conteúdo foi gerado com a ajuda de IA',
    'discovery.aiContent.indicator.model': 'Modelo de IA: {model}',
    'discovery.recommendations.storiesTitle': 'Histórias recomendadas',
    'discovery.recommendations.recommendationsExplained': 'Essas histórias são recomendadas com base em nosso mecanismo de recomendações. Que usa aprendizado de máquina para recomendar histórias para o senhor.',
    'discovery.recommendations.recommendationsSettings': 'O senhor pode desativar isso em suas configurações.',
    'discover.search.templateUniverses': 'Mostrar apenas universos modelo (enciclopédias copiáveis)',
    'discover.ratingExplained': 'Classificação média de {avgRating, number} de {reviewsNum, number} avaliação',
    // Story purchase
    'story.buy.button': 'Compre para {price}',
    'story.buy.currency': 'Moeda de compra',
    'story.buy.error.generic': 'A compra falhou',
    'story.buy.redirecting': 'Redirecionando...',
    'story.price.free': 'Grátis',
    'story.price.owned': 'De propriedade',
    'story.price.paid': 'Pago',
    'story.purchase.fullStory': 'Comprar a história completa',
    'story.purchase.byArc': 'ou comprar pelo arco',
    'story.purchase.includes': 'Inclui todos os capítulos do site {chaptersCount}',
    'story.purchase.freePreview': '{count, plural, one {O primeiro capítulo é gratuito para visualização} other {Os primeiros {count} capítulos são gratuitos para visualização}}',
    'story.purchase.arcIncludes': 'Capítulos {from}-{to}',
    'story.purchase.savings': 'Salve {amount}',
    'story.purchase.allArcsCost': 'Todos os arcos separadamente: {price}',
    'story.purchase.owned': 'O senhor é o dono desta história',
    'story.purchase.arcOwned': 'De propriedade',
    'story.purchase.complete': 'Compra concluída! Agora o senhor tem acesso total a essa história.',
    'story.purchase.header': 'Obter esta história',
    'story.purchase.header.locked': 'História premium',
    'story.purchase.forFullStory': 'para ver a história completa',
    'story.purchase.secureCheckout': 'Checkout seguro via Stripe',
    'story.purchase.loginToBuy': 'Faça login para comprar',
    'story.purchase.loginToBuyArcs': 'Faça login para comprar arcos de histórias individuais',
    'story.purchase.pricingUnavailable': 'No momento, as informações sobre preços não estão disponíveis.',
    'story.buy.error.timeout': 'O tempo limite da solicitação expirou. Por favor, tente novamente.',
    'story.chapter.freePreviewEnds': 'A visualização gratuita termina aqui'
};