/**
 * Licenses for creative works
 * https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
 */
export default {
    'licenses.about': 'Sobre as licenças',
    'licenses.more': 'Mais informações',
    'licenses.legal': 'Documento legal',
    'licenses.name.cc-by': 'Creative Commons Atribuição 4.0',
    'licenses.cc-by': 'Essa licença permite que outras pessoas distribuam, remixem, ajustem e desenvolvam seu trabalho, mesmo comercialmente, desde que atribuam ao senhor o crédito pela criação original. Esta é a mais flexível das licenças oferecidas. Recomendada para a máxima disseminação e uso de materiais licenciados.',
    'licenses.name.cc-by-sa': 'Creative Commons Atribuição-CompartilhaIgual 4.0',
    'licenses.cc-by-sa': 'Essa licença permite que outras pessoas remixem, ajustem e desenvolvam seu trabalho, mesmo para fins comerciais, desde que atribuam os créditos ao senhor e licenciem suas novas criações sob os mesmos termos. Essa licença é frequentemente comparada às licenças de software livre e de código aberto "copyleft". Todos os novos trabalhos baseados no seu terão a mesma licença, portanto, quaisquer derivados também permitirão o uso comercial. Essa é a licença usada pela Wikipedia e é recomendada para materiais que se beneficiariam da incorporação de conteúdo da Wikipedia e de projetos com licenças semelhantes.',
    'licenses.name.cc-by-nd': 'Creative Commons Atribuição-SemDerivações 4.0',
    'licenses.cc-by-nd': 'Esta licença permite a redistribuição, comercial e não comercial, desde que seja repassada inalterada e na íntegra, com crédito para o senhor.',
    'licenses.name.cc-by-nc': 'Creative Commons Atribuição-NãoComercial 4.0',
    'licenses.cc-by-nc': 'Essa licença permite que outras pessoas remixem, ajustem e desenvolvam seu trabalho sem fins comerciais e, embora os novos trabalhos também devam reconhecer o senhor e ser não comerciais, eles não precisam licenciar seus trabalhos derivados nos mesmos termos.',
    'licenses.name.cc-by-nc-sa': 'Creative Commons Atribuição-NãoComercial-CompartilhaIgual 4.0',
    'licenses.cc-by-nc-sa': 'Essa licença permite que outras pessoas remixem, ajustem e desenvolvam seu trabalho sem fins comerciais, desde que atribuam os devidos créditos ao senhor e licenciem suas novas criações sob os mesmos termos.',
    'licenses.name.cc-by-nc-nd': 'Creative Commons Atribuição-NãoComercial-SemDerivações 4.0',
    'licenses.cc-by-nc-nd': 'Essa licença é a mais restritiva de nossas seis licenças principais, permitindo apenas que outras pessoas baixem seus trabalhos e os compartilhem com outras pessoas, desde que atribuam os devidos créditos ao senhor, mas não podem alterá-los de forma alguma nem usá-los comercialmente.',
    'licenses.name.lu-c': 'Direitos autorais do universo literário',
    'licenses.lu-c': 'Licença padrão de direitos autorais completos que permite que o senhor venda, publique seu trabalho como quiser e tenha seus direitos protegidos. Essa licença também lhe dá a opção de vender suas histórias no Literary Universe.',
    'licenses.name.lu-e': 'Exclusivo do Universo Literário',
    'licenses.lu-e': 'Esta licença concede ao Universo Literário direitos exclusivos para publicar e distribuir seu trabalho on-line. O senhor manterá os direitos autorais, mas o Universo Literário terá o direito exclusivo de publicar e distribuir seu trabalho on-line.',
    'licenses.name.lu-ne': 'Universo Literário Não-Exclusivo',
    'licenses.lu-ne': 'Esta licença concede ao Literary Universe direitos não exclusivos para publicar e distribuir seu trabalho on-line. O senhor manterá os direitos autorais e o direito de publicar e distribuir seu trabalho por outros canais.',
    'licenses.name.cc0': 'Sem Direito de Autor nem Direitos Conexos - CC0 1.0',
    'licenses.cc0': 'Coloque seu trabalho em domínio público. Em contraste com as licenças CC, que permitem que os detentores de direitos autorais escolham entre uma série de permissões, mantendo seus direitos autorais, a CC0 possibilita uma outra escolha: a opção de não ter direitos autorais e proteção de banco de dados, e os direitos exclusivos automaticamente concedidos aos criadores - a alternativa "sem direitos reservados" às nossas licenças.',
    // License Chooser Modal
    'licenses.chooser.title': 'Seletor de licenças',
    'licenses.chooser.button': 'Ajude-me a escolher uma licença',
    'licenses.chooser.ariaLabel': 'Escolha uma licença para seu trabalho',
    'licenses.chooser.introduction': 'Esta ferramenta o ajudará a escolher a licença mais adequada para sua obra. A licença determina como os outros podem usar seu trabalho e afeta sua capacidade de monetizá-lo no Literary Universe.',
    // License Chooser Wizard Steps
    'licenses.chooser.step.contentType.title': 'Que tipo de conteúdo o senhor está licenciando?',
    'licenses.chooser.step.contentType.description': 'O tipo de conteúdo afeta quais licenças estão disponíveis para o senhor.',
    'licenses.chooser.step.contentType.original': 'Trabalho original',
    'licenses.chooser.step.contentType.fanfiction': 'Ficção de fã',
    'licenses.chooser.step.contentType.fanfictionNote': 'Os trabalhos de ficção de fãs no Literary Universe recebem automaticamente a licença Creative Commons Attribution-NonCommercial (CC BY-NC). Isso ocorre porque a fan fiction é baseada em obras protegidas por direitos autorais de propriedade de terceiros, e o uso comercial poderia infringir esses direitos.',
    'licenses.chooser.step.commercial.title': 'O senhor deseja monetizar seu trabalho?',
    'licenses.chooser.step.commercial.description': 'A escolha de monetizar seu trabalho afeta a licença mais apropriada.',
    'licenses.chooser.step.commercial.yes': 'Sim, quero monetizar meu trabalho',
    'licenses.chooser.step.commercial.no': 'Não, não quero monetizar meu trabalho',
    'licenses.chooser.step.commercial.monetizeNote': 'Para monetizar seu trabalho no Universo Literário, o senhor precisará usar uma de nossas licenças comerciais. Essas licenças permitem que o senhor venda seu trabalho enquanto mantém a proteção de seus direitos autorais.',
    'licenses.chooser.step.exclusivity.title': 'O senhor deseja publicar exclusivamente no Literary Universe?',
    'licenses.chooser.step.exclusivity.description': 'A escolha da exclusividade afeta a taxa da plataforma e as opções de publicação.',
    'licenses.chooser.step.exclusivity.yes': 'Sim, exclusivamente no Universo Literário',
    'licenses.chooser.step.exclusivity.no': 'Não, quero publicar em outro lugar também',
    'licenses.chooser.step.exclusivity.exclusiveNote': 'Com a publicação exclusiva no Literary Universe, o senhor se beneficiará de uma taxa de plataforma mais baixa, de 10%. Isso significa que o senhor fica com 90% de seus ganhos.',
    'licenses.chooser.step.exclusivity.nonExclusiveNote': 'Com a publicação não exclusiva, o senhor pode publicar seu trabalho também em outras plataformas. A taxa da plataforma é de 30%, o que significa que o senhor mantém 70% de seus ganhos no Universo Literário. No futuro, forneceremos ferramentas para ajudar o senhor a publicar em outras plataformas diretamente do Literary Universe.',
    'licenses.chooser.step.derivatives.title': 'O senhor deseja permitir que outras pessoas criem obras derivadas?',
    'licenses.chooser.step.derivatives.description': 'Os trabalhos derivados incluem adaptações, remixes ou transformações de seu trabalho original.',
    'licenses.chooser.step.derivatives.yes': 'Sim, permitir obras derivadas',
    'licenses.chooser.step.derivatives.no': 'Não, não permita obras derivadas',
    'licenses.chooser.step.derivatives.allowNote': 'Permitir obras derivadas significa que outras pessoas podem adaptar, remixar ou transformar seu trabalho. Isso pode levar a uma distribuição mais ampla e à reutilização criativa de seu conteúdo.',
    'licenses.chooser.step.derivatives.disallowNote': 'A não permissão de trabalhos derivados significa que seu trabalho deve ser transmitido inalterado e completo, embora ainda possa ser compartilhado com a devida atribuição.',
    'licenses.chooser.step.attribution.title': 'O senhor deseja exigir atribuição?',
    'licenses.chooser.step.attribution.description': 'Atribuição significa que os outros devem dar crédito ao senhor quando usarem seu trabalho.',
    'licenses.chooser.step.attribution.yes': 'Sim, requer atribuição',
    'licenses.chooser.step.attribution.no': 'Não, colocar em domínio público (CC0)',
    'licenses.chooser.step.attribution.requireNote': 'Exigir atribuição significa que qualquer pessoa que use seu trabalho deve lhe dar crédito da maneira que o senhor solicitar.',
    'licenses.chooser.step.attribution.publicDomainNote': 'Colocar seu trabalho em domínio público (CC0) significa que o senhor renuncia a todos os direitos autorais e direitos relacionados. Outras pessoas podem usar livremente seu trabalho para qualquer finalidade, sem atribuição.',
    // License Result
    'licenses.chooser.result.commercialTitle': 'Informações comerciais',
    'licenses.chooser.result.exclusiveInfo': 'Com a licença Literary Universe Exclusive, o senhor se beneficiará de uma taxa de plataforma menor, de 10%. Isso significa que o senhor mantém 90% de seus ganhos, mas só pode publicar esse trabalho no Literary Universe.',
    'licenses.chooser.result.nonExclusiveInfo': 'Com a licença não exclusiva do Literary Universe, o senhor pode publicar seu trabalho também em outras plataformas. A taxa da plataforma é de 30%, o que significa que o senhor mantém 70% de seus ganhos no Literary Universe. No futuro, forneceremos ferramentas para ajudar o senhor a publicar em outras plataformas diretamente do Literary Universe.',
    'licenses.chooser.result.fanfictionNote': 'Essa licença é aplicada automaticamente a obras de fan fiction porque elas são baseadas em material protegido por direitos autorais de propriedade de terceiros. O uso comercial poderia infringir esses direitos.',
    'licenses.chooser.result.selectLicense': 'Selecione esta licença',
    // Adding missing internationalization strings
    'licenseChooser.contentType.title': 'Que tipo de conteúdo o senhor está licenciando?',
    'licenseChooser.contentType.description': 'O tipo de conteúdo afeta quais licenças estão disponíveis para o senhor.',
    'licenseChooser.contentType.original.title': 'Trabalho original',
    'licenseChooser.contentType.original.description': 'Conteúdo que o senhor criou inteiramente por conta própria.',
    'licenseChooser.contentType.fanfiction.title': 'Ficção de fã',
    'licenseChooser.contentType.fanfiction.description': 'Conteúdo baseado em trabalhos existentes de outros criadores.',
    'licenseChooser.contentType.fanfiction.note': 'Os trabalhos de ficção de fãs no Literary Universe recebem automaticamente a licença Creative Commons Attribution-NonCommercial (CC BY-NC). Isso ocorre porque a fan fiction é baseada em obras protegidas por direitos autorais de propriedade de terceiros, e o uso comercial poderia infringir esses direitos.',
    'licenseChooser.commercial.title': 'O senhor deseja monetizar seu trabalho?',
    'licenseChooser.commercial.description': 'A escolha de monetizar seu trabalho afeta a licença mais apropriada.',
    'licenseChooser.commercial.yes.title': 'Sim, quero monetizar',
    'licenseChooser.commercial.yes.description': 'Quero ganhar dinheiro com meu trabalho no Universo Literário.',
    'licenseChooser.commercial.no.title': 'Não, não quero monetizar',
    'licenseChooser.commercial.no.description': 'Quero compartilhar meu trabalho livremente, sem monetização.',
    'licenseChooser.commercial.note': 'Para monetizar seu trabalho no Universo Literário, o senhor precisará usar uma de nossas licenças comerciais. Essas licenças permitem que o senhor venda seu trabalho enquanto mantém a proteção de seus direitos autorais.',
    'licenseChooser.exclusivity.title': 'O senhor deseja publicar exclusivamente no Literary Universe?',
    'licenseChooser.exclusivity.description': 'A escolha da exclusividade afeta a taxa da plataforma e as opções de publicação.',
    'licenseChooser.exclusivity.yes.title': 'Sim, exclusivamente no Universo Literário',
    'licenseChooser.exclusivity.yes.description': 'Só publicarei esse trabalho no Universo Literário.',
    'licenseChooser.exclusivity.no.title': 'Não, quero publicar em outro lugar também',
    'licenseChooser.exclusivity.no.description': 'Quero publicar esse trabalho em outras plataformas também.',
    'licenseChooser.exclusivity.exclusive.note': 'Com a publicação exclusiva no Literary Universe, o senhor se beneficiará de uma taxa de plataforma mais baixa, de 10%. Isso significa que o senhor fica com 90% de seus ganhos.',
    'licenseChooser.exclusivity.nonExclusive.note': 'Com a publicação não exclusiva, o senhor pode publicar seu trabalho também em outras plataformas. A taxa da plataforma é de 30%, o que significa que o senhor mantém 70% de seus ganhos no Literary Universe.',
    'licenseChooser.derivatives.title': 'O senhor deseja permitir que outras pessoas criem obras derivadas?',
    'licenseChooser.derivatives.description': 'Os trabalhos derivados incluem adaptações, remixes ou transformações de seu trabalho original.',
    'licenseChooser.derivatives.yes.title': 'Sim, permitir obras derivadas',
    'licenseChooser.derivatives.yes.description': 'Outros podem adaptar, remixar ou transformar meu trabalho.',
    'licenseChooser.derivatives.no.title': 'Não, não permita obras derivadas',
    'licenseChooser.derivatives.no.description': 'Meu trabalho deve ser transmitido inalterado e completo.',
    'licenseChooser.attribution.title': 'O senhor deseja exigir atribuição?',
    'licenseChooser.attribution.description': 'Atribuição significa que os outros devem dar crédito ao senhor quando usarem seu trabalho.',
    'licenseChooser.attribution.yes.title': 'Sim, requer atribuição',
    'licenseChooser.attribution.yes.description': 'Os outros devem me dar crédito quando usarem meu trabalho.',
    'licenseChooser.attribution.no.title': 'Não, colocar em domínio público (CC0)',
    'licenseChooser.attribution.no.description': 'Eu renuncio a todos os direitos autorais e direitos relacionados ao meu trabalho.',
    'licenseChooser.commercialUse.title': 'O senhor deseja permitir o uso comercial de seu trabalho?',
    'licenseChooser.commercialUse.description': 'Uso comercial significa que outras pessoas podem usar seu trabalho para fins comerciais.',
    'licenseChooser.commercialUse.yes.title': 'Sim, permite o uso comercial',
    'licenseChooser.commercialUse.yes.description': 'Outros podem usar meu trabalho para fins comerciais.',
    'licenseChooser.commercialUse.no.title': 'Não, somente para uso não comercial',
    'licenseChooser.commercialUse.no.description': 'Outros só podem usar meu trabalho para fins não comerciais.',
    'licenseChooser.shareAlike.title': 'O senhor deseja solicitar o Share-Alike?',
    'licenseChooser.shareAlike.description': 'Escolha se os outros devem compartilhar suas adaptações sob os mesmos termos.',
    'licenseChooser.shareAlike.yes.title': 'Compartilhamento obrigatório (SA)',
    'licenseChooser.shareAlike.yes.description': 'Se outras pessoas remixarem, transformarem ou desenvolverem seu trabalho, elas deverão distribuir suas contribuições sob a mesma licença do original.',
    'licenseChooser.shareAlike.no.title': 'Não é necessário compartilhar',
    'licenseChooser.shareAlike.no.description': 'Outros podem distribuir adaptações sob quaisquer termos, mesmo que sejam mais restritivos do que sua licença original.',
    'licenseChooser.shareAlike.yes': 'Sim, requer Share-Alike (SA)',
    'licenseChooser.shareAlike.no': 'Não, não exija o Share-Alike',
    'licenseChooser.cc0Confirmation.title': 'Confirme a licença CC0 (domínio público)',
    'licenseChooser.cc0Confirmation.description': 'A CC0 renuncia a todos os direitos autorais e direitos relacionados ao seu trabalho, colocando-o efetivamente em domínio público. Por favor, confirme seu entendimento.',
    'licenseChooser.cc0Confirmation.important': 'Informações importantes',
    'licenseChooser.cc0Confirmation.details': 'Ao selecionar CC0, o senhor renuncia a todos os direitos autorais e direitos relacionados ao seu trabalho, na medida permitida por lei. Isso significa que:',
    'licenseChooser.cc0Confirmation.point1': 'Qualquer pessoa pode usar seu trabalho para qualquer finalidade, inclusive para uso comercial',
    'licenseChooser.cc0Confirmation.point2': 'Nenhuma atribuição é necessária (embora seja bem-vinda)',
    'licenseChooser.cc0Confirmation.point3': 'Outras pessoas podem modificar seu trabalho e não compartilhar essas modificações',
    'licenseChooser.cc0Confirmation.point4': 'Essa decisão é irrevogável quando o senhor publica',
    'licenseChooser.cc0Confirmation.waiver': 'Entendo que estou renunciando a todos os direitos autorais e direitos relacionados ao meu trabalho',
    'licenseChooser.cc0Confirmation.understanding': 'Entendo os termos e o efeito legal da CC0 em meu trabalho',
    'licenses.learnMore': 'Saiba mais',
    'licenses.legalText': 'Texto legal',
    'licenses.chooser.back': 'Voltar',
    'licenses.chooser.select': 'Selecione esta licença',
    'licenses.commercial.title': 'Informações sobre licenças comerciais'
};