export default {
    'org.auditLog.title': 'Diário de auditoria',
    'org.settings.title': 'Configurações da organização',
    'org.settings.name': 'Nome da organização',
    'org.settings.membersPrivate': 'NÃO exibir membros publicamente',
    'org.logo': 'Logotipo da organização',
    'org.logo.alt': '{organizationName} logo',
    'org.superAdmin': 'Super Admin',
    'org.settings.language': 'Idioma principal',
    'org.meta.desc': 'Organizações e grupos criativos no Universo Literário.',
    'org.luOrgs': 'Organizações do Universo Literário',
    'org.otherOrgs': 'Grémios e organizações',
    'org.aboutTitle': 'Sobre {orgName}',
    'org.membersTitle': 'Membros da organização',
    'org.membersNone': 'Os membros não são públicos',
    'org.storiesTitle': 'Histórias de {orgName}',
    'org.universesTitle': 'Universos de {orgName}',
    'org.userDashboardTitle': 'Suas organizações',
    'org.settings.hideMembers.label': 'Ocultar membros do público',
    'org.visit': 'Ir para a página {organization}',
    'org.authorOverride.legend': 'Anulação do autor',
    'org.authorOverride.desc': 'Mostra este texto em vez do nome da organização.',
    'org.authorOverride.label': 'Nome do autor',
    'org.membersAdd.title': 'Convidar membros para a organização',
    'org.flashnews.admin': 'Administração do Flashnews',
    'org.settings.tabListAria': 'Configurar seções para a organização',
    'org.forums.title': '{orgName} fóruns',
    'org.flashnews.internal': 'Flashes de notícias internas',
    'org.flashnews.publicAll': 'Flashes de notícias públicas para todas as propriedades',
    'org.flashnews.createTitle': `Criar um novo flash de notícias para {type, select,
    internal {a organização}
    allProperties {exibir para o público em todas as propriedades}
    other {da organização}
  }`,
    'org.members.invited': 'Membros convidados',
    'org.members.list': 'Membros da organização',
    'org.invitesTileNotice': 'You have been invited to {count, number} {count, plural, one {organization} other {organizations}}',
    'org.invitePage.title': 'Convites para organizações',
    'org.invitePage.invitedAt': 'Você foi convidado em {invitedAt, date, short}',
    'org.invitePage.ignoring': 'Você está ignorando este convite no momento, o que significa que ele ainda está ativo, mas não está recebendo notificações.',
    'org.invitePage.expiresAt': 'This invitation will expire at {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Entrar na organização',
    'org.invitePage.reject': 'Rejeitar convite',
    'org.invitePage.ignore': 'Ignorar por enquanto',
    'org.leaveOrg.title': 'Sair da organização',
    'org.leaveOrg.confirm': 'Esta é uma ação destrutiva. Uma vez que você sair, perderá todo o acesso a esta organização. Tem certeza de que deseja sair da organização?',
    'org.confirmRemove.aria': 'Confirmar remoção do usuário',
    'org.confirmRemove.confirm': 'Tem certeza de que deseja remover {username} de {organization}?',
    'org.confirmRemove.remove': 'Remover usuário',
    'org.mainBlog': 'Blog principal',
    'org.teams': 'Equipes',
    'org.teams.total': 'Total de equipes: {totalTeams, number}',
    'org.teams.create': 'Criar uma nova equipe',
    'org.teams.settings': 'Configurações da equipe',
    'org.workshop.ownerUser': 'Não é um trabalho de guilda',
    'org.workshop.caption': 'Propriedade da guilda'
};