export default {
    'reader.storyEnd.heading': 'FIM',
    'reader.storyEnd.description': 'Você chegou ao fim da história.',
    'reader.externalSale.heading': 'Ainda não chegou',
    'reader.externalSale.description': 'Esta história não está disponível no Universo Literário, mas você pode obtê-la em outros lugares.',
    'reader.storyTBC.heading': 'Continua...',
    'reader.storyTBC.description': 'Isto é tudo que temos para a história até agora, mas a aventura vai continuar no futuro, confira em breve!',
    'chapter.translation.notYetDescription': 'Verifique novamente em breve!',
    'reader.externalShopping.heading': 'Compre {storyName} nas lojas:',
    'chapter.next': 'Próximo capítulo',
    'chapter.previous': 'Capítulo anterior',
    'chapter.comment': 'Comentários sobre este capítulo',
    'reader.language': 'Idioma:',
    'reader.fullscreen.enter': 'Entrar no modo de tela cheia',
    'reader.fullscreen.exit': 'Sair do modo tela cheia',
    'reader.details.universe': 'Detalhes do universo',
    'reader.details.story': 'Detalhes da história',
    'reader.darkmode': 'Alternar Modo Escuro',
    'reader.flowtext': 'Alternar tamanho do texto',
    'reader.menu.optionsAria': 'Menu de opções do leitor',
    'reader.accessibility': 'Alternar a acessibilidade',
    'chapter.translation.notYet': 'Este capítulo ainda não foi traduzido.',
    'externalShopping.buyLink.amazon': 'Comprar na Amazon',
    'externalShopping.buyLink.other': 'Comprar na {storeName}',
    'externalShopping.buyLink.bookshop': 'Comprar na Bookshop.org',
    'reader.accessibility.aria': 'Opções de acessibilidade',
    'reader.accessibility.toggleDyslexic': 'Alternar fonte para disléxicos',
    'reader.accessibility.toggleParagraphStripes': 'Alternar a alteração do fundo dos parágrafos',
    'reader.accessibility.toggleParagraphHighlight': 'Alternar o destaque do parágrafo selecionado',
    'reader.accessibility.toggleRules': 'Alternar régua assistiva',
    'reader.nextRelease.scheduled': 'O próximo capítulo será lançado em {nextReleaseAt, date} em {nextReleaseAt, time}!',
    'reader.storyContinues': 'A história continua...',
    'reader.storyOnHiatus': 'O autor está atualmente dando uma pausa nessa história e ela está em hiato por enquanto. Volte em um mês ou dois.',
    'reader.storyCancelled': 'Infelizmente é isso. A história foi cancelada, portanto, é improvável que haja algo novo.',
    'reader.storyCancelled.heading': 'Cancelado',
    'reader.nextChapterEstimation.verySoon': 'Based on the publication dates of the last {chaptersCount} chapters, the next chapter is expected to be released very soon.',
    'reader.nextChapterEstimation.days': 'Based on the publication dates of the last {chaptersCount} chapters, the next chapter should be available in approximately {daysLeft} days.',
    'reader.nextChapterEstimation.notEnoughChapters': 'Também forneceremos uma estimativa de quando o próximo capítulo pode ser publicado assim que essa história tiver mais de um capítulo.'
};