export default {
    'stats.age.groups': 'Grupos de idade',
    'stats.age.range': 'Faixa etária',
    'stats.age.to12': 'Até 12',
    'stats.age.12to17': '12 a 17',
    'stats.age.18to20': '18 a 20',
    'stats.age.21to29': '21 a 29',
    'stats.age.30to39': '30 a 39',
    'stats.age.40to49': '40 a 49',
    'stats.age.50to64': '50 a 64',
    'stats.age.65to84': '64 a 84',
    'stats.age.above85': 'Acima de 85',
    'stats.section.aggregate': 'Estatísticas agregadas',
    'stats.section.chapter': 'Estatísticas do capítulo',
    'stats.readers.title': 'Sobre seus leitores',
    'stats.gender.title': 'Sexo',
    'stats.view.table': 'Visualização em tabela',
    'stats.view.pie': 'Visualização em gráfico de pizza',
    'stats.view.bar': 'Visualização em gráfico de barras',
    'stats.view.chart': 'Visualização em gráfico',
    'stats.table.total': 'Total',
    'stats.timeline.title': 'Linha do tempo',
    'stats.timeline.dateStart': 'Estatísticas a partir de',
    'stats.timeline.dateEnd': 'Estatísticas até',
    'stats.likeCount': '# de curtidas',
    'stats.language.title': 'Idioma falado',
    'stats.chapter.visitorsAndViews': 'Total de visitantes e visualizações por capítulo',
    'stats.chapter.wordCount': 'Contagem de palavras por capítulo',
    'stats.chapter.chartTooltipViews': `Capítulo {chapter, number}: {views, number} visualizações`,
    'stats.chapter.chartTooltipVisitors': `Capítulo {chapter, number}: {visitors, number} visitantes únicos`,
    'stats.chapter.chartTooltipWordCount': `Capítulo {chapter, number}: {wordCount, number} palavras`,
    'stats.totalHits': 'Total de visualizações',
    'stats.totalVisitors': 'Total de visitantes únicos',
    'stats.totalWords': 'Total de palavras',
    'stats.totalEntries': 'Entradas de enciclopédia',
    'stats.blogPage': 'Página',
    'stats.blog.typeSelectionAria': 'Seleção de tipo',
    'stats.blog.pages': 'Páginas',
    'stats.blog.posts': 'Postos',
    'stats.unknown': 'Desconhecido',
    'stats.noData': 'Não há dados disponíveis no momento.'
};