export default {
    'challenges.current': 'વર્તમાન ચુંટણીઓ',
    'challenges.wordcount.goal': 'લક્ષ્ય શબ્દગણતરી',
    'challenges.wordcount.dailygoal': 'લક્ષ્ય દૈનિક શબ્દગણતરી',
    'challenges.wordcount.today': 'આજે લખેલા શબ્દો',
    'challenges.wordcount.total': 'કુલ લખેલા શબ્દો',
    'challenges.wordcount.remaining': 'બાકી રહેલા શબ્દો',
    'challenges.wordcount.daysleft': 'બાકી રહેલા દિવસો',
    'challenges.wordcount.currentDay': 'વર્તમાન દિવસ',
    'challenges.wordcount.average': 'દિવસ પ્રતિ શબ્દોની સરેરાશ',
    'challenges.wordcount.finishOn': 'વર્તમાન ગતિ પર તમે સમાપ્ત થશે',
    'challenges.wordcount.finishOnTime': 'સમય પર સમાપ્ત થવા માટે રોજબરો લખવાના શબ્દો',
    'challenges.wordcount.graph.day': 'દિવસ {day}',
    'challenges.underway': 'આ ચૂંટણી પહેલેથી ચાલુ છે.',
    'challenges.targetWords': 'કુલ લક્ષ્ય શબ્દગણતરી',
    'challenges.startDate': 'શરૂઆતી તારીખ',
    'challenges.endDate': 'અંતિમ તારીખ',
    'challenges.future': 'આવતી ચૂંટણીઓ',
    'challenges.future.wordcount': 'Wordcount challenge staring on {startDate, date, short} with goal of {target, number} by {endDate, date, short}.',
    'challenges.future.nanowrimo': 'NaNoWriMo ચૂંટણી તૈયાર છે.',
    'challenges.wordcount': 'શબ્દગણતરી',
    'challenges.wordcount.desc': `Set yourself a goal of how many words you want to write this month for this {type, select,
    story {story}
    universe {universe}
    other {}
  }.`,
    'challenges.wordcount.select': 'તમે કેટલા શબ્દોની ચૂંટણી લેવાની ઈચ્છો છો?',
    'challenges.start': 'ચૂંટણી શરૂ કરો',
    'challenges.report': 'અહેવાલ',
    'challenges.victory': 'અભિનંદન! તમે આ ચૂંટણી પૂરી કરી લેવી ગયા છે.',
    'challenges.defeat': 'અફસોસ, તમે આ ચૂંટણી પૂરી ન કરી શક્યા.',
    'challenges.baseline': 'The current wordcount for this story is {wordcount, number}, this will be the starting point.',
    // NaNoWriMo
    'nanowrimo.full': 'નેશનલ નોવેલ લેખન મહિનો',
    'nanowrimo.site': 'NaNoWriMo આધિકારિક સાઇટ',
    'nanowrimo.settings': 'NaNoWriMo એકાઉન્ટ',
    'nanowrimo.username': 'NaNoWriMo વપરાશકર્તા નામ',
    'nanowrimo.key': 'ગુપ્ત કી',
    'nanowrimo.key.get': 'તમારો NaNoWriMo કી મેળવો.',
    'nanowrimo.key.get.notice': 'તમને તે જોવા માટે લૉગ ઇન થવું જરૂરી છે.',
    'nanowrimo.ongoing': 'is in full swing! {countdown} more days to go!',
    'nanowrimo.startsin': `will start in {countdown, plural,
      one {1 day}
      other {# days}
    }! Get ready!`,
    'nanowrimo.isover': 'NaNoWriMo પૂર્ણ થઇ ગયો છે. આગલા વર્ષે મળીશું!',
    'nanowrimo.select': 'આ કથાને NaNoWriMo માટે નમૂનાયો કરો.',
    'nanowrimo.baseline': 'NaNoWriMo શરૂ થતા વખતે તે વર્તમાન શબ્દગણતરીને લેવાનું લેશે અને તેમાં કોઈ વધારે શબ્દો ને NaNoWriMo ના ભાગ તરીકે લેશે.',
    'nanowrimo.victory': 'અભિનંદન! તમે NaNoWriMo જીત્યા છે!',
    'nanowrimo.challenge': 'NaNoWriMo ચેલેન્જ',
    'nanowrimo.description': 'The challenge is to write a novel of {words, number} words during November.',
    'nanowrimo.error.usernotfound': 'યુઝરનેમ NaNoWriMo સર્વરો પર મળ્યું નથી.',
    'nanowrimo.error.nobook': 'કોઈ પુસ્તક મળી નથી. કૃપા કરીને ખાતરી કરો કે તમે NaNoWriMo પર તમીની પુસ્તક બનાવી લીધી છે.',
    'nanowrimo.error.wordcount': 'NaNoWrimo પર શબ્દગણતરી સેટ કરવામાં અસમર્થ, કૃપા કરીને તમારી શ્રેયાને ચાચણી કરી અને ફરીથી પ્રયાસ કરો.',
    'nanowrimo.connected': 'તમે આ કથાને NaNoWriMo માટે નમૂનાયો કર્યો છે.',
    'nanowrimo.connected.other': 'તમે પહેલેથી બીજી કથા જોડાવી છે.'
};