export default {
    'plans.desc': 'સાહિત્યિક યુનિવર્સનની યોજનાઓ અને વૈશિષ્ટ્યોનું વર્ણન.',
    'plans.title': 'સાહિત્યિક યુનિવર્સનમાં વધુ મેળવો!',
    'plans.text': 'સાહિત્યિક યુનિવર્સ મફત માટે મૂળભૂત કાર્યકારીતા પૂરી પાડે છે. જો તમે એક ઉદ્યમી વાંચક અથવા સર્જક હોઈ તો તમારા માટે અમારી એડવાન્સ સભ્યતા વધુ મનપસંદ હોઈ શકે છે.',
    'plans.faq.basicsPriced': 'મફત સભ્યતામાં શું વધારે વિગતો છે?',
    'plans.faq.justification': 'અહીં સાહિત્યિક વિશ્વમાં અમે તમારી ગોપનીયતા અને બુદ્ધિશક્તિને મૂલ્યાંકન આપીએ છીએ. તેથી અમે તમારા ડેટાનો વિજ્ઞાપન વેચવા અથવા બીજી કંપનીઓને આપવા માટે નહીં ઉપયોગ કરીએ. આનો અર્થ છે કે અમને ઘણી વસ્તુઓને આપણે આપણા પ્રમાણે બનાવવી પડે છે. આ મહેનત ઘણી સમય લે છે અને ચાલવવામાં ખર્ચીપરે છે. તેથી અમે સેવાને ચાલુ રાખવા માટે અને વિકાસ જારી રાખવા માટે લાઇટરેરી યુનિવર્સની એક છોટી પૂર્વાવલોકન (જે હજી પણ તમને મુખ્ય કાર્યો કરવાની મંજુરી આપે છે) સાથે અને વધુમાં વધુ સભ્યતા પદ્ધતિઓ અને ઉપકરણોને ધ્યાનમાં રાખવા માટે એકજ અથવા વધુ પેમેન્ટ વિકલ્પોમાંથી એકમ મેમ્બરશીપ સ્થાપિત કરી છે. જો તમને શું અમુક બનાવવું લાગે છે તો કૃપા કરીને ચોક્કસ વિકલ્પોમાંથી એકમાં સાઇન અપ કરવાની આવશ્યકતા ધરાવો. આભાર!',
    'plans.limits': 'મર્યાદાઓ',
    'plans.features': 'વૈશિષ્ટ્યો',
    'plans.account.user': 'મુલાકાતી',
    'plans.account.user.desc': 'વસ્ત્રોત્પન્ન મુલાકાતી ખાતું, વસ્તુઓને આજમાવવા માટે.',
    'plans.account.explorer': 'ખોજકારી',
    'plans.account.explorer.desc': 'હોબીસ્ટ અને મિત્રો માટે.',
    'plans.account.adventurer': 'ખોજકારી',
    'plans.account.adventurer.desc': 'સર્જકો અને અમારા આધારભૂતના સમર્થકો માટે.',
    'plans.account.storyteller': 'વાર્તાકાર',
    'plans.account.storyteller.desc': 'સૌથી રચનાત્મક અને સમર્પિત માટે.',
    'plans.unlimited': 'અમર્યાદિત',
    'plans.price': 'કિંમત',
    'plans.price.free': 'મફત',
    'plans.price.monthly': 'a month*',
    'plans.price.annually': 'annually*',
    'plans.price.perMonth': '{price} / month*',
    'plans.price.perYear': '{price} / year*',
    'plans.development': 'વિકાસમાં',
    'plans.limits.encEntries': 'નાણાંકણો એન્ટ્રીઓ',
    'plans.limits.maxCollaborators': 'પ્રોજેક્ટ પ્રતિસપ્તિ પ્રતિસપ્તિઓ',
    'plans.limits.pmChats': 'ખાસ સંદેશ માટે સૌથી મોટી પ્રાપ્તકર્તાઓની સંખ્યા',
    'plans.feature.creative': 'Create amazing universes and stories',
    'plans.feature.encCustomFields': 'એન્ટ્રી પર વ્યક્તિગતીકરણ યુનિવર્સનના ક્ષેત્રો',
    'plans.feature.encAdvCategories': 'વધુ એન્ટ્રી વર્ગો',
    'plans.feature.scratchpad': 'સ્ક્રેચપેડ',
    'plans.feature.library': 'લાઇબ્રેરી',
    'plans.feature.blog': 'વ્યક્તિગત અને યુનિવર્સ બ્લોગો',
    'plans.feature.customBlogTheme': 'વ્યક્તિગત બ્લોગ થીમ્સ વ્યક્તિગતીકરણ',
    'plans.feature.advanceStats': 'ઉન્નત આંકડાં',
    'plans.feature.challenges': 'લેખન ચેલેન્જીસ',
    'plans.feature.newFeaturesVote': 'નવા વૈશિષ્ટ્યો પર મત આપો',
    'plans.feature.newFeaturesSuggest': 'નવા વૈશિષ્ટ્યો પ્રસ્તાવ કરો',
    'plans.feature.accessToBeta': 'બીટા વૈશિષ્ટ્યોનું પ્રવેશ',
    'plans.feature.userGroups': 'વપરાશકર્તા ગોઠવાઓ',
    'plans.feature.privateUserGroups': 'નિજી અને ગુપ્ત વપરાશકર્તા ગ્રુપ્સ બનાવો',
    'plans.feature.internalUniverseForums': 'યુનિવર્સો માટેનો આંતરિક ફોરમ',
    'plans.feature.fictionalTime': 'કલ્પનિક સમય',
    'plans.feature.forums': 'બ્લોગો અને વિશ્વમાં ફોરમ્સ',
    'plans.feature.timelines': 'વિશ્વમાં સમયરેખાઓ',
    'plans.feature.webMonetization': 'વેબ આર્થિક સુધારણા',
    'plans.feature.storyMonetization': 'કથાની આર્થિકતા',
    'plans.feature.fanClub': 'Fan Club',
    'plans.feature.translations': 'અનુવાદ ક્ષમતાઓ',
    'plans.feature.fanFiction': 'ફેન ફિક્શન લખો અને મેનેજ કરો',
    'plans.feature.universeFanArt': 'ફેન આર્ટ મેનેજર',
    'plans.feature.overviewNotes': 'કથા ના સંગ્રહ નોંધપાત્ર',
    'plans.feature.personalNotesStoriesUniverses': 'કથાઓ અને વિશ્વમાં વ્યક્તિગત નોંધો',
    'plans.feature.storyReviews': 'કથા સમીક્ષાઓ',
    'plans.feature.readingLists': 'વાંચવાની યાદીઓ',
    'plans.feature.scenesManager': 'દ્રશ્ય મેનેજર',
    'plans.feature.glossaries': 'અનુવાદ શબ્દકોશો',
    'plans.feature.chatSupport': 'Chat support',
    'plans.currency.select': 'ચલણ ચૂંટો',
    'plans.subscription.ownAlready': 'તમારી હાલની યોજના છે',
    'plans.subscription.title': 'Subscriptions & payments',
    'plans.see': 'ઉપલબ્ધ ગોઠવણી યોજનાઓ જુઓ',
    'plans.current.none': 'તમે હાલમાં Literary Universe ને આધાર આપતા નથી.',
    'plans.current.buying': 'તમારી ખરીદીની પરખ કરવા કેટલાક ક્ષણો લાગી શકે છે. અમે તમારી ધીરજ્ઞા આભારી છીએ.',
    'plans.current.heading': 'હાલની ગોઠવણી યોજના',
    'payment.methods.title': 'Monetization',
    'payment.methods.tabs': 'ચુકવણી વિકલ્પો',
    'payment.option.title': 'ચુકવણી વિકલ્પ',
    'payment.option.notFount': 'તમારી કોઈપણ ચુકવણી વિકલ્પ સાચવેલી નથી.',
    'payment.option.create': 'નવી ચુકવણી વિકલ્પ ઉમેરો',
    'payment.option.description': 'અહીં તમારી સાચવેલી ચુકવણી પદ્ધતિઓની યાદી છે. તમે અહીં નવી ચુકવણી પદ્ધતિઓ સાચવી શકો છો જેથી ઝડપી ચેકઆઉટ કરી શકો છો. Literary Universe ક્રેડિટ કાર્ડ નંબર જેવી તમારી ચુકવણી માહિતીઓને સંગ્રહિત નથી અને પ્રક્રિયા કરતા નથી.',
    'payment.history.title': 'ચુકવણી ઇતિહાસ',
    'payment.history.tab': 'History',
    'payment.history.none': 'We don\'t have any records of past payments.',
    'plans.options.aria': 'Payment options',
    'plans.options.creditCard': 'Credit Card',
    'plans.options.creditCardNew': 'New Credit Card',
    'plans.options.existingCards': 'Saved Credit Cards',
    'plans.purchase.action': 'Subscribe',
    'plans.purchase.title': 'Buy Literary Universe subscription',
    'payment.creditCard.details': 'Credit Card details',
    'payments.zipcode.label': 'ZIP code',
    'payment.card.name': 'Name on card',
    'plans.subscribed.thankYou': 'Thank you for supporting Literary Universe',
    'plans.subscribed.periodEnd': 'તમારી ગુનતંત્રકતા સક્રિય છે જોતાં: {end, date, medium}',
    'plans.subscribed.renewal': `અંતે તમારી સબસ્ક્રિપ્શન આપતી રહેશે {method, select,
    charge_automatically {પછીથી પ્રમાણિત પેમેન્ટ કરવામાં આવે તે પછી આપતી રહેશે}
    send_invoice {ઇનવોઇસ ચુકવી પછી પ્રમાણિત પેમેન્ટ કરવામાં આવે તે પછી આપતી રહેશે}
    other {}
  }.`,
    'plans.subscribed.paymentMethod': 'Your default payment method will be used to pay for the next cycle.',
    'plans.subscribed.status': `ગોઠવણીની સ્થિતિ: {status, select,
    active {સક્રિય}
    incomplete {કંઈ ચીજ ચૂકી ગયેલી છે}
    incomplete_expired {કંઈ ચીજ ચૂકી ગયેલી છે}
    trialing {ટ્રાયલ}
    past_due {અમને તમારી ચુકવણી થઈ ગઈ છે}
    cancelled {રદ કરેલી}
    unpaid {અપેમાનીત}
    expired {સમાપ્ત}
    other {}
  }`,
    'payments.changeMethod': 'Change payment method',
    'plans.subscribed.willNotRenew': ', will not renew at the end of the cycle.',
    'plans.cancel.button': 'Cancel subscription',
    'plans.cancel.question': 'Are you sure you want to cancel your subscription? Your subscription will remain active till the end of the billing cycle.',
    'plans.cancel.confirmationButton': 'Yes, I want to cancel my subscription',
    'plans.cancel.failed': 'Apologies, we were unable to cancel your plan at this moment. Please try again later.',
    'plans.cancel.restoreBtn': 'Restore subscription',
    'plans.cancel.restoreFailed': 'Apologies, we were unable to restore the subscription at this moment. Please try again later.',
    'plans.change.button': 'Change subscription',
    'plans.change.explanation': 'Select the plan you want to upgrade or downgrade to. You will be billed or prorated the difference in price immediately.',
    'plans.change.failed': 'Apologies, we were unable to change your plan at this moment. Please try again later.',
    'plans.change.upgrade': 'Upgrade',
    'payments.disclaimer': 'ચુકવણી માહિતી અને પ્રક્રિયા સ્ટ્રાઇપ દ્વારા થાય છે. અમારા સર્વરો પર કોઈ ક્રેડિટ કાર્ડ અથવા બેંક ખાતાની માહિતી રાખી નથી.',
    'buy.payment.optionsSelect': 'Select payment option',
    'payments.card.number': 'Card number',
    'payments.card.expire': 'Valid Thru',
    'payments.card.cvv': 'CVV',
    'payments.card.info': '{cardType} card, ending in {ending}',
    'payments.none': 'કોઈ સાચવેલ ચૂકવણી વિકલ્પો મળ્યા નથી.',
    'payments.none.cards': 'No cards were found.',
    'payments.added': 'નવી ચૂકવણી વિકલ્પ સફળતાપૂર્વક ઉમેરવામાં આવ્યો છે.',
    'payments.delete.confirm': 'શું તમે ખરેખર કરીશું છે કે તમે કાઢી નાખવા માંગો છો {cardType}, અંતમાં {ending}?',
    'payment.invoice.status': 'ચૂકવણીનો સ્થિતિ',
    'payment.invoice.statusMessage': `{status, select,
    draft {ડ્રાફ્ટ}
    open {ખુલ્લું}
    paid {ચુકવેલું}
    uncollectible {વસૂલ ન થતું}
    void {રદ કરેલું}
    other {}
  }`,
    'payment.invoice.id': 'ચૂકવણી આઈડી',
    'payment.invoice.pdf': 'ચૂકવણી PDF',
    'payment.invoice.total': 'કુલ',
    'payment.invoice.what': 'ચૂકવણીની વર્ણનાત્મક માહિતી',
    'payment.stripe.powered': 'પર આધારિત ',
    'payment.listMethods.card': 'કાર્ડો',
    'payment.expiresAt': 'સમાપ્ત થાય છે {month}/{year}',
    'payment.card.details': `{type, select,
    credit {ક્રેડિટ કાર્ડ}
    debit {ડેબિટ કાર્ડ}
    other {કાર્ડ}
  } અંતમાં {last4}`,
    'payment.options.default': 'મૂળભૂત',
    'payment.method.add': 'નવી ચૂકવણી પદ્ધતિ ઉમેરો',
    'payment.methods.adding': 'તમારા ખાતામાં તમારી નવી ચૂકવણી પદ્ધતિ ઉમેરવામાં આવી છે.',
    'payment.methods.delete': 'ચૂકવણી પદ્ધતિ કાઢી નાખો',
    'payment.upgradePlan.option': '{plan} - {price}',
    'payment.methods.webMonetization': 'વેબ આર્થિક સુધારણા',
    'settings.webMonetization.placeholder': 'તમારો ચુકવણી પોઇન્ટર',
    'payment.webMonetization.explained': 'Web Monetization વેબ ચુકવણી માટેનું એક પ્રસ્તાવિત માનક છે. અહીં તમે તમારો ચુકવણી પોઇન્ટર ઉમેરી શકો છો જે પછી તમારા પ્રોફાઇલ પેજ, બ્લોગ, યુનિવર્સ અને સ્ટોરીસમાં વપરાશમાં આવશે વેબ ચુકવણી દ્વારા.',
    'payment.webMonetization.learnMore': 'Web Monetization વિશે વધુ જાણો',
    'plans.subscription.settingsAria': 'Subscription settings options',
    'plans.buttonStatus.submitting': 'Submitting your request...',
    'plans.button.manageOnStripe': 'Manage Billing on Stripe',
    'plans.call.signUpBottom': 'Sign-up for a free Literary Universe account and start creating!',
    'plans.button.seeComparison': 'Find out more about plans and pricing on our comparison page!',
    'plans.button.chooseThisSubscription': 'Select this plan',
    'plans.button.chooseFree': 'Start for free',
    'plans.features.allInPreviousTiers': 'Everything in previous tier',
    'plan.button.chooseNow': 'Choose your Literary Universe plan now',
    'plans.subscription.manage': 'Manage subscription',
    'plans.taxMayApply': '* VAT and other local taxes may apply',
    'plans.faq.crypto': 'Will you offer crypto payments?',
    'plans.faq.cryptoAnswer': 'Yes, we are working on it. We are big fans of Web3 we are looking for ways to integrate Web3 into the platform in the near future. We currently allow for login with Web3 and we are looking to expand on this offering especially when it comes to providing compensation to creators and giving creators the ability to choose all the possible payment options that they want to accept.',
    'plans.subscribed.updating': 'It might take a bit to update your your subscription information. Thank you for your patience!',
    'payments.methods.webMonetization': 'વેબ આર્થિક સુધારણા',
    'stripeConnect.settings.title': 'પેઆઉટ સેટિંગ્સ',
    'stripeConnect.settings.intro': 'If you want to receive funds or sell through Literary Universe you need to create Stripe account via the button bellow.',
    'stripeConnect.settings.connectAccount': 'સ્ટ્રિપ એકાઉન્ટ સેટઅપ કરો',
    'stripeConnect.settings.ongoing': 'અમે તમારા એકાઉન્ટ સંદર્ભમાં સ્ટ્રિપથી જવાબ આપવા માટે રાહ જુવા માંગીએ છીએ. આ થોડીવાર લાગી શકે છે. જો આ બહુ લાંબુ લાગે તો સ્ટ્રિપ પર પાછા જવા માટે નીચેની બટન પર ક્લિક કરો.',
    'stripeConnect.settings.finished': 'તમે સ્ટ્રિપ કનેક્ટ દ્વારા પૈસા પ્રાપ્ત કરવા માટે તૈયાર છો.',
    'stripeConnect.settings.balance': 'બેલેન્સ',
    'stripeConnect.settings.balanceAvailable': 'ઉપલબ્ધ બેલેન્સ',
    'stripeConnect.settings.balancePending': 'બાકી રહેલ બેલેન્સ',
    'stripeConnect.settings.recentTransfers': 'તાજેતરના ટ્રાન્સફર્સો',
    'stripeConnect.transfers.amount': 'રકમ',
    'stripeConnect.transfers.reason': 'કારણ',
    'payment.settings.donations': 'દાન સેટિંગ્સ',
    'plans.fanClub.heading': 'ફેન ક્લબ્સ',
    'payment.donations.enable': 'દાન સક્ષમ કરો',
    'payment.donations.suggestedAmount': 'સૂચવેલી રકમ',
    'payment.donations.amount': 'રકમ',
    'payment.donations.preferredCurrency': 'પસંદગીની ચલણમાં ચલતી મુદ્રા',
    'payment.donations.currency': 'મુદ્રા',
    'payment.donations.stripeDescription': '{username}પર દાન',
    'payment.donations.support': '{username}ની સપોર્ટ કરો',
    'payment.donations.donate': 'દાન કરો',
    'payment.donations.donationModal': 'દાન પુષ્ટિકરણ',
    'payment.donations.payNowUSD': 'દાન કરો {donation, number, ::compact-short currency/USD} પર {username}',
    'payment.donations.payNowJPY': 'દાન કરો {donation, number, ::compact-short currency/JPY} પર {username}',
    'payment.donations.payNowEUR': 'દાન કરો {donation, number, ::compact-short currency/EUR} પર {username}',
    'payment.donations.payNowCZK': 'Donate {donation, number, ::compact-short currency/CZK} to {username}',
    'payment.donations.payNowGBP': 'Donate {donation, number, ::compact-short currency/GBP} to {username}',
    'payment.donations.thankYouTitle': 'Thank you for your donation to {username}',
    'payment.donations.thankYouContinue': 'Thank you for supporting {username}, we hope that you will continue enjoying their work and consider supporting them again in the future.',
    'payment.success': 'Payment succeeded!',
    'payment.processing': 'Your payment is processing.',
    'payment.failed': 'Your payment was not successful, please try again.',
    'payment.generalError': 'Something went wrong.',
    'payment.unexpectedError': 'Something went wrong.',
    'payments.transferType.donation': 'Donation',
    'payment.donation.backToProfile': 'Back to {username}\'s profile',
    'payment.author.requirementStripeConnect': 'Before we can process any financial transactions you need to create and connect your Stripe Connect account.',
    'payment.author.requirementPublishWork': 'Before you continue, please publish at least one work (story or universe).',
    'payment.author.createWork': 'Create a new work',
    'payment.author.directivesTitle': 'Recommendations',
    'payment.author.directivesExplained': 'We have some additional recommendations that you should fulfill before enabling payment services to increase your chance of success.',
    'payment.author.directivesStoryPublished': 'Publish at least one story for free to showcase your craft.',
    'payment.author.directivesFreeStoryFinished': 'Finish at least one free story to show your readers that you won\'t abandon them in the middle of the journey.',
    'payment.universe.directivesUniversePublished': 'Publish your universe',
    'payment.universe.directivesEncFull': 'Fill up your encyclopedia, have at least 30 entries! Better if you are attacking the 100 margin.',
    'payment.universe.haveFans': 'જો તમારી કરતા વ્યક્તિઓ પહેલાથીથી તેમને તમારા કાર્યક્રમમાં રુચિ રાખે છે, તો તમારે સ્પોન્સરશીપ માટે લોકોને મળવો આસાન થાય છે. 100 ફેન્સ તમારા યુનિવર્સને તેમના લાઇબ્રેરીમાં ઉમેરી રહ્યાં છે તે શરૂ કરવાની રેખા છે.',
    'payment.settings.yourFanClub': 'તમારું ફેન ક્લબ',
    'payment.settings.newWork': 'નવું કાર્ય બનાવો',
    'payment.amount.withNet': `{amount} (નેટ: {netAmount})`,
    'payment.fanClub.intro': 'In this section you can modify your fan club settings. From subscription tiers to history of payments.',
    'payment.fanClub.tiers': 'Tiers',
    'payment.fanClub.tierName': 'ટિયર નામ',
    'payment.fanClub.createTier': 'ટિયર ઉમેરો',
    'payment.fanClub.description': 'ટિયર વર્ણન',
    'payment.fanClub.picture': 'ટિયર ચિત્ર',
    'payment.fanClub.priceBreakdown': 'Subscriber will pay: {amount}. Platform fee is {fee} ({platformPercentage}), you will get (estimated): {net}',
    'payment.fanClub.platformFeeExplained': 'We are working towards our platform fee covering fees from payment providers such as credit card fees and others, but sometimes there might be overflow. If that happens please let us know so that we can investigate and reduce the impact in the future. As such you should not see any of those fees effect your total, but if you do please let us know. Another big impact on your net value are taxes. In countries like USA where it is common to have taxes to be exclusive of the price you will not be affected, in countries where it is common to have taxes inclusive in the price (like the EU), you need to account for your country\'s VAT when setting the subscription price.',
    'payment.fanClub.learnStripeFees': 'સ્ટ્રાઇપ ફીસ વિશે વધુ જાણો.',
    'payment.feeNotice': 'Please do note that this is an estimate and the actual Stripe fee might be different based on customer\'s payment type and additional charges from the pay gate and applicable taxes.',
    'payment.fanClub.perks': 'સુવિધાઓ',
    'stripeConnect.settings.notifications': 'સ્ટ્રિપમાંથી અધિસૂચનાઓ',
    'plans.pricePerMonth': 'મહિના પ્રતિષ્ઠા',
    'payment.fanClub.perkType': 'સુવિધા પ્રકાર',
    'payment.fanClub.addPerk': 'સુવિધા ઉમેરો',
    'payment.fanClub.perksExplained': 'આ છે જે perks છે જે સ્વયંચાલિત રીતે Literary Universe દ્વારા ફેનને આપવામાં આવે છે.',
    'plans.deleteTier.header': 'શું તમે ખોતું {tierName} ડિલીટ કરવા માંગો છો?',
    'plans.deleteTier.explainer': 'જો આ ટિયરની કોઈ પણ સબ્સ્ક્રાઇબર્સ નથી, તો તે ડિલીટ થશે. અન્યથા, તે નવા સબ્સ્ક્રિપ્શન્સ માટે અનચેટ થઈ જશે, પરંતુ હાલના સબ્સ્ક્રિપ્શન્સ પ્રોથમે ચાલી રહી રહેશે જ્યાં સુપોર્ટર્સે તેની પાસે પરિવર્તન ન કરે.',
    'plans.fanClub.userSettings': 'તમારા ફેન ક્લબ સબસ્ક્રિપ્શનની સંચાલન કરો',
    'plans.fanClub.subscribers': 'સબ્સ્ક્રાઇબર્સ',
    'plans.fanClub.activatedLabel': 'ફેન ક્લબ સક્રિય થઈ ગયું છે',
    'plans.fanClub.inactiveWarning': 'તમારું ફેન ક્લબ હજી સક્રિય થયું નથી, તમે હજી પણ યોજનાઓ તૈયાર કરી શકો છો અને તમે તૈયાર થયેલ પછી તેને સેટિંગ્સમાં સક્રિય કરી શકો છો.',
    'payment.fanClub.editTier': 'Edit tier',
    'plans.deletePlan.modalAria': 'Delete plan confirmation',
    'payment.fanClub.paymentDescriptorFull': 'LU - {username} fan club',
    'payment.fanClub.paymentDescriptorShort': 'LU-{username} fan club',
    'payment.fanClub.paymentDescriptorMinimal': '{username} fan club',
    'payment.fanClub.paymentDescriptorBackup': 'LU - author fan club',
    'payment.fanClub.perMonth': '{amount} / per month',
    'plans.fanClub.notCreated': 'Oops! Something went wrong and your fan club did not get create when it should have, but worry not, we have a backup plan ready! Just click the button bellow and you will be all set!',
    'plans.fanClub.create': 'Create fan club',
    'plans.subscription.error.unexpected': 'Unexpected error occurred. Please try again later.',
    'plans.subscription.error.invalidPrice': 'The selected subscription plan is not available. Please try a different plan.',
    'plans.subscription.error.notConfigured': 'Payment provider is not properly configured. Please contact support.',
    'plans.subscription.error.generic': 'An error occurred while setting up checkout. Please try again later.',
    'plans.subscription.error.portalFailed': 'Could not open customer portal. Please try again later.',
    'plans.subscription.error.noCustomer': 'Customer account not found. Please contact support.',
    'plans.subscription.error.stripeError': 'Error connecting to payment provider. Please try again later.',
    'plans.subscription.error.noCustomer': 'Customer account not found. Please contact support.',
    'plans.subscription.error.stripeError': 'Error connecting to payment provider. Please try again later.',
    'plans.subscription.error.generic': 'An error occurred. Please try again later.',
    'plans.subscription.error.portalFailed': 'Could not open customer portal. Please try again later.',
    'plans.subscription.error.stripeNotConfigured': 'Payment provider is not properly configured. Please contact support.',
    'plans.subscription.error.customerNotInStripe': 'Your customer account was not found in the payment system. Please contact support.',
    'plans.subscription.error.vendorNotFound': 'Vendor account not found. Please contact support.',
    'plans.subscription.error.invalidPlan': 'Invalid plan configuration. Please contact support.',
    'plans.subscription.error.noVendor': 'Vendor account not found. Please contact support.',
    'plans.subscription.fallback.message': 'We\'re having trouble connecting to the billing portal right now. Here are some options to manage your subscription:',
    'plans.subscription.fallback.tryAgain': 'Try accessing the portal again later',
    'plans.subscription.fallback.contactSupport': 'Contact our support team for assistance',
    'plans.subscription.fallback.refreshPage': 'Refresh the page and try again',
    'plans.subscription.fallback.tryAgainButton': 'Try Again',
    'plans.upgrade': 'UPGRADE',
    'plans.current': 'CURRENT',
    'plans.currentPlan': 'Current Plan',
    'plans.selectPlan': 'Select Plan',
    'plans.upgrade.confirm': 'Confirm Upgrade',
    'plans.lifetime.pageTitle': 'Lifetime Membership - Literary Universe',
    'plans.lifetime.title': 'Limited Lifetime Membership Offer',
    'plans.lifetime.intro': 'Become a permanent part of Literary Universe with our exclusive lifetime membership offer. This is a limited-time opportunity to secure Storyteller tier benefits forever with a one-time payment.',
    'plans.lifetime.limitedTimeOffer': 'This offer is available until {endDate}. Don\'t miss out!',
    'plans.lifetime.benefitsTitle': 'Lifetime Membership Benefits',
    'plans.lifetime.benefit1': 'Storyteller tier membership benefits forever',
    'plans.lifetime.benefit2': 'Champion or request a feature that we will implement with priority',
    'plans.lifetime.benefit3': 'Special badge on your profile',
    'plans.lifetime.benefit4': 'Individual assessment and assignment of The Way of the Author level',
    'plans.lifetime.benefit5': 'Custom avatar from our designer',
    'plans.lifetime.benefit6': 'Monthly calls with the crew on the progress of the platform',
    'plans.lifetime.priceTitle': 'One-time Payment',
    'plans.lifetime.price': '€999',
    'plans.lifetime.loginRequired': 'You need to be logged in to purchase the lifetime membership.',
    'plans.lifetime.alreadyMember': 'You already have lifetime membership benefits. Thank you for your support!',
    'plans.lifetime.buyButton': 'Purchase Lifetime Membership',
    'plans.lifetime.establishedAuthorsNote': 'Are you an established author? Contact us for an individual offer tailored to your needs.',
    'plans.button.buyLifetimeMembership': 'Buy Lifetime Membership',
    'plans.lifetime.banner.title': 'Limited Time Offer: Lifetime Membership',
    'plans.lifetime.banner.description': 'Secure Storyteller benefits forever with our exclusive one-time payment option. Available until July 31st, 2025.',
    'plans.lifetime.banner.button': 'View Lifetime Offer',
    'plans.lifetime.thankYou.pageTitle': 'Thank You for Your Lifetime Membership - Literary Universe',
    'plans.lifetime.thankYou.celebrationImageAlt': 'Celebration',
    'plans.lifetime.thankYou.title': 'Welcome to the Literary Universe Family!',
    'plans.lifetime.thankYou.message': 'Thank you for purchasing the lifetime membership! Your support means the world to us and helps ensure the future of Literary Universe.',
    'plans.lifetime.thankYou.whatsNextTitle': 'What Happens Next?',
    'plans.lifetime.thankYou.nextStep1': 'Your account has been upgraded to Storyteller tier permanently',
    'plans.lifetime.thankYou.nextStep2': 'You\'ll receive an email with details about your custom avatar design process',
    'plans.lifetime.thankYou.nextStep3': 'Our team will contact you to schedule your first monthly call',
    'plans.lifetime.thankYou.nextStep4': 'You can now submit your feature request through our feedback system',
    'plans.lifetime.thankYou.enjoyMessage': 'Enjoy all the benefits of your lifetime membership and start creating amazing stories!',
    'plans.lifetime.thankYou.goToDashboard': 'Go to Dashboard',
    'plans.lifetime.error.unexpected': 'Unexpected error occurred. Please try again later.',
    'plans.lifetime.error.invalidPrice': 'The lifetime membership plan is not available. Please try again later.',
    'plans.lifetime.error.notConfigured': 'Payment provider is not properly configured. Please contact support.',
    'plans.lifetime.error.notLoggedIn': 'You must be logged in to purchase a lifetime membership.',
    'plans.lifetime.error.generic': 'An error occurred while setting up checkout. Please try again later.',
    'plans.lifetime.error.alreadyMember': 'You already have a lifetime membership.',
    'plans.lifetime.subscription.title': 'Lifetime Membership',
    'plans.lifetime.subscription.description': 'You have a lifetime membership with Literary Universe. Thank you for your incredible support!',
    'plans.lifetime.subscription.status': 'Status: Active Forever',
    'plans.lifetime.subscription.purchaseDate': 'Purchased on: {date, date, medium}',
    'plans.lifetime.subscription.noActions': 'Your lifetime membership requires no further action. Enjoy your benefits forever!',
    'plans.lifetime.subscription.benefitsTitle': 'Your Lifetime Benefits',
    'plans.lifetime.subscription.benefit1': 'Permanent Storyteller tier access',
    'plans.lifetime.subscription.benefit2': 'Custom avatar design',
    'plans.lifetime.subscription.benefit3': 'Monthly team calls',
    'plans.lifetime.subscription.benefit4': 'Feature request priority',
    'plans.subscription.lifetimeMember': 'You have a lifetime membership'
};