export default {
    'writer.menu.optionsAria': 'સંપાદક વિકલ્પો મેન્યુ',
    'writer.menu.saveOptionsAria': 'વિકલ્પો સાચવો',
    'writer.undo': 'અનકરો',
    'writer.redo': 'ફરીથી કરો',
    'writer.ul': 'અવક્રમણ સૂચિ',
    'writer.ol': 'ક્રમાંકણ સૂચિ',
    'writer.blockquote': 'ઉદ્ધરણ',
    'writer.link': 'લિંક ઉમેરો',
    'writer.image': 'છબી ઉમેરો',
    'writer.bold': 'પસંદગી પર બોલ્ડ કરો',
    'writer.underline': 'પસંદગી પર આંતરચિહ્ન સાથે ચોખ્ખુ કરો',
    'writer.italic': 'પસંદગી પર મહત્વ આપો',
    'writer.wordCount': '{characters, number} અક્ષરો, {words, number} શબ્દો',
    'writer.characterCount': '{characters, number} અક્ષરો',
    'finder.details': 'વિગતો',
    'finder.remove': 'કનેક્શન દૂર કરો',
    'finder.connect': 'પસંદગીને વિજ્ઞાનકોશ એન્ટ્રીથી જોડો',
    'writer.aside.ariaLabel': 'મદદ વિકલ્પો મેન્યુ',
    'writer.aside.todo': 'Todo & Tasks',
    'writer.aside.ai': 'AI Assistant',
    'writer.todo.title': 'Writing Progress & Goals',
    'writer.todo.description': 'Track your writing tasks and goals for this chapter.',
    'writer.todo.currentChapter': 'Current Chapter ({sequence})',
    'writer.todo.currentStatus': 'Current Status',
    'writer.todo.currentCount': 'Current chapter: {count, number} {unit}',
    'writer.todo.storyAverage': 'Your average chapter length: {count, number} {unit}',
    'writer.todo.recommendations': 'Recommended Chapter Lengths',
    'writer.todo.recommendation': '{label}: {count, number} {unit}',
    'writer.todo.recommendation.progress': 'Progress: {current, number} / {target, number} {unit} ({percent, number}%)',
    'writer.todo.dailyPublishing': 'Daily publishing',
    'writer.todo.dailyTooltip': 'For stories published every day. Shorter chapters help maintain daily engagement and work well for serialized content.',
    'writer.todo.biDailyPublishing': 'Bi-daily publishing',
    'writer.todo.biDailyTooltip': 'For stories published 3-4 times per week. Balanced length that allows for detailed storytelling while maintaining reader engagement.',
    'writer.todo.weeklyPublishing': 'Weekly publishing',
    'writer.todo.weeklyTooltip': 'For stories published once per week. Longer chapters allow for more complex plots and character development.',
    'writer.todo.monthlyPublishing': 'Monthly publishing',
    'writer.todo.monthlyTooltip': 'For stories published once per month. Much longer chapters suitable for in-depth storytelling and complex narratives.',
    'writer.nothingToSave': 'કંઈ સાચવવા માટે નથી',
    'writer.link.placeholder': 'Enter a URL',
    'writer.link.error.empty': 'URL cannot be empty',
    'writer.link.error.invalid': 'Please enter a valid URL',
    'writer.fontFamily': 'Font Family',
    'writer.fontFamily.select': 'Select font',
    'writer.image.upload': 'Upload Image',
    'writer.image.uploading': 'Uploading image...',
    'writer.image.error.type': 'Only JPEG, PNG, and WebP images are supported',
    'writer.image.error.size': 'Image must be less than 5MB',
    'writer.image.error.upload': 'Failed to upload image. Please try again.',
    'writer.publish.publishAria': 'પ્રકાશન વિકલ્પો',
    'writer.publish.scheduleExplained': 'તમે તેમને તત્કાલ પ્રકાશિત કરી શકો છો કે તારી ચાપ ની તારીખ પછીને ઉપલબ્ધ કરી શકો છો.',
    'writer.publish.schedule': 'પ્રકાશન તારીખ સમય સેટ કરો',
    'writer.publish.previousChapterPublished': 'અગાઉની ચાપ પ્રકાશિત થઈ હતી {publishDate, date, short} પર {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'અગાઉની ચાપ પ્રકાશિત કરવામાં આવેલ છે {publishDate, date, short} પર {publishDate, time}',
    'writer.publish.alreadyPublished': 'આ ચાપ પહેલેથી પ્રકાશિત કરવામાં આવ્યી છે {publishedAt, date, short}. નવા આવૃત્તિઓ તત્કાલ પ્રકાશિત થશે.',
    'writer.publish.betaReader': 'બીટા',
    'writer.publish.betaReader.original': 'Beta (Original)',
    'writer.publish.public': 'Publish',
    'writer.publish.publish': 'Publish',
    'writer.publish.publish.original': 'Publish (Original)',
    'writer.publish.now': 'Publish now',
    'writer.publish.moreOptions': 'More save options',
    'writer.publish.schedulePrevious': 'You need to publish or schedule publication of previous chapter before you can publish this one.',
    'writer.publish.earlyAccess.title': 'Early access for fans',
    'writer.publish.earlyAccess.groupLine': '{days} days early: {tiers} — fans get access on {date, date, short} at {date, time}',
    'writer.initialLetter': 'Initial Paragraph Letter'
};