export default {
    'feedback.home': 'Pusat Bantuan',
    'feedback.bugs': 'Masalah',
    'feedback.bugs.desc': 'Apakah Anda mengalami kesalahan atau hal lain yang salah atau tidak sesuai tempatnya. Beri tahu kami di sini!',
    'feedback.features': 'Ide & Usulan',
    'feedback.features.desc': 'Punya ide untuk fitur baru atau cara membuat situs ini lebih baik? Beri tahu kami!',
    'feedback.help': 'Bantuan & Tutorial',
    'feedback.help.desc': 'Bagaimana cara Anda _____? Pergi ke sini untuk menemukan jawabannya.',
    'feedback.desc': 'Selamat datang di pusat bantuan dan penyelesaian kami!',
    'feedback.faq': 'Pertanyaan Umum',
    'feedback.faq.desc': 'Pertanyaan yang Sering Diajukan',
    'feedback.open': 'Terbuka',
    'feedback.closed': 'Tertutup',
    'feedback.accepted': 'Diterima',
    'feedback.inprogress': 'Sedang berlangsung',
    'feedback.completed': 'Selesai',
    'feedback.fixed': 'Diperbaiki',
    'feedback.new.bugs': 'Laporkan masalah baru',
    'feedback.new.features': 'Usulkan fitur baru',
    'feedback.lang.nosupport': 'Bahasa Anda saat ini tidak didukung untuk umpan balik, harap tulis dalam Bahasa Inggris. Terima kasih!',
    'feedback.new.thanks': 'Terima kasih atas pemberitahuannya! Kami akan segera memeriksanya.',
    'feedback.comment.title': 'Komentar',
    'feedback.comment.desc': 'Kirimkan umpan balik Anda',
    'feedback.comment.legend': 'Umpan balik Anda - beri tahu kami tentang apapun',
    'feedback.comment.success': 'Terima kasih atas umpan balik Anda!',
    'feedback.comment.label': 'Komentar Anda',
    'feedback.copyrightReport.title': 'Pelanggaran hak cipta',
    'feedback.copyrightReport.desc': 'Laporkan Pelanggaran Hak Cipta',
    'feedback.report.noUser': 'Anda perlu masuk, untuk melaporkan pelanggaran.',
    'feedback.voting.totalVoters': 'Pengguna yang memberikan suara: {voted, number}',
    'feedback.voting.upvote': 'Vote atas',
    'feedback.voting.downvote': 'Vote bawah',
    'feedback.voting.score': 'Skor total',
    'feedback.report.title': 'Laporkan konten',
    'feedback.report.typeSelect': 'Apa masalahnya di sini?',
    'feedback.reportType.law': 'Pelanggaran hukum',
    'feedback.reportType.vulgar': 'Kasar/obscene',
    'feedback.reportType.copyright': 'Pelanggaran hak cipta',
    'feedback.reportType.storyRating': 'Rating usia yang salah',
    'feedback.reportType.scam': 'Penipuan',
    'feedback.report.submit': 'Lapor',
    'feedback.report.submitting': 'Melaporkan...',
    'feedback.report.violationDesc': 'Detail',
    'feedback.report.reportSaved': 'Terima kasih atas laporan Anda! Kami akan menyelidiki dan mengambil tindakan jika diperlukan.',
    'feedback.report.copyrightReportSaved': 'Terima kasih atas laporan Anda! Kami akan menyelidiki dan menghubungi Anda.',
    'feedback.report.copyrightOwnershipDesc': 'Pernyataan kepemilikan',
    'feedback.report.copyrightNotice': 'Harap dicatat bahwa Anda perlu menjadi pemilik sah dari karya ini untuk menggunakan formulir ini. Jika Anda bukan pemiliknya, harap beri tahu pemilik atau gunakan kategori lain untuk memberi tahu kami. Kami sangat serius dalam menangani pelanggaran hak cipta dan hal yang sama berlaku untuk penggunaan formulir ini yang tidak pantas dan penyalahgunaan.',
    'feedback.report.copyrightInternalProperty': 'Saya telah mempublikasikan karya ini di Literary Universe',
    'feedback.reportType.spam': 'Spam atau phishing',
    'feedback.reportType.other': 'Lainnya',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`,
    'faq.section.about': 'Tentang kami',
    'faq.section.settings': 'Pengaturan',
    'faq.section.discovery': 'Jelajah',
    'faq.section.reader': 'Pembaca',
    'faq.section.library': 'Pustaka',
    'faq.section.workshop': 'Workshop',
    'faq.section.writer': 'Penulis',
    'faq.section.encyclopedia': 'Ensiklopedia',
    'faq.section.groups': 'Grup',
    'faq.section.blogs': 'Blog',
    'faq.section.guilds': 'Gilda',
    // About us questions
    'faq.question.about.whatIsLU': 'Apa itu Literary Universe?',
    'faq.answer.about.whatIsLU': 'Literary Universe is a platform for writers and readers to create, share and discover stories and worlds.',
    'faq.question.about.difference': 'What is the difference between Literary Universe and other online reading platforms?',
    'faq.answer.about.difference': 'Literary Universe is all-in-one platform which means it includes tools for writing, reading, worldbuilding, and community building. The key difference is inclusion of all these tools together in one platform and their interconnectedness.',
    'faq.question.about.dataLocation': 'Di mana data LU disimpan?',
    'faq.answer.about.dataLocation': 'Data Literary Universe disimpan di server di Amerika Serikat, khususnya di wilayah AWS us-east-1.',
    'faq.question.about.incorporation': 'Di mana Anda tergabung?',
    'faq.answer.about.incorporation': 'Literary Universe terdaftar di Republik Ceko. Anda dapat menemukan lebih banyak detail pada halaman <a href="/about">tentang kami</a>.',
    'faq.question.about.roadmap': 'Apa langkah selanjutnya untuk Literary Universe?',
    'faq.answer.about.roadmap': 'Ini terus berkembang. Lihat <a href="/roadmap">roadmap</a> kami untuk lebih banyak detail.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Bagaimana cara mengubah tampilan Literary Universe?',
    'faq.answer.settings.changeTheme': 'Pengguna terdaftar dapat mengubah tema mereka di pengaturan akun <a href="/user/settings/account"></a> di bawah bagian "tema situs". Kami memiliki tema terang dan tema gelap yang tersedia. Jika Anda tidak terdaftar, maka kami mencoba menentukan tema yang akan disajikan berdasarkan pengaturan browser dan sistem operasi Anda.',
    'faq.question.settings.changeAvatar': 'Bagaimana cara mengubah avatar saya?',
    'faq.answer.settings.changeAvatar': 'Anda dapat mengubah avatar Anda di pengaturan profil <a href="/user/settings/profile"></a>.',
    'faq.question.settings.changeLanguage': 'Bagaimana cara mengubah bahasa?',
    'faq.answer.settings.changeLanguage': 'Anda dapat mengubah bahasa Literary Universe di pengaturan akun <a href="/user/settings/account"></a>.',
    'faq.question.settings.translationMistake': 'Saya menemukan kesalahan dalam teks di situs web, di mana saya bisa melaporkannya?',
    'faq.answer.settings.translationMistake': 'Semua file bahasa kami tersedia di GitHub. Anda dapat <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">mengirimkan masalah di sana</a> atau di bagian Bug dari umpan balik, atau jika Anda ingin, Anda dapat memperbaikinya langsung melalui <a href="https://crowdin.com/project/literary-universe" target="_blank">halaman Crowdin kami</a>.',
    // Discovery questions
    'faq.question.discovery.explain': 'What is the Discovery section?',
    'faq.answer.discovery.explain': 'The Discovery section is where you can find new stories, universes, blogs, groups and other content. It is a place to explore and find new things to read and enjoy.',
    // Writer
    'faq.question.writer.howToCreateStory': 'How do I create a new story in Literary Universe?',
    'faq.answer.writer.howToCreateStory': 'You can create a new story by going to the <a href="/workshop">workshop</a> and clicking on one of the create buttons or go to the main <a href="/workshop/create">create page</a> where you can select a <a href="/workshop/create/story">new standalone story</a> or <a href="/workshop/create/fanfiction">fan fiction</a>. To create a new story in a universe, go first to that universe and then select "stories" on the dashboard and on the next page click the big red button on the right side of the page title. You will be asked to fill in the details of your story and then you can start writing.',
    'faq.question.writer.schedule': 'How do I schedule a chapter to be released in Literary Universe?',
    'faq.answer.writer.schedule': 'You can schedule a chapter to be released when clicking on the publish button in the chapter editor. A modal will be shown where you will have the option to schedule a release or publish immediately. If you choose to schedule a release, you will be asked to select the date and time when you want the chapter to be released. We recommend scheduling chapters at least 24 hours in advance to give readers time to prepare for the new chapter and to release on the same day and time of the week.',
    // Reader
    'faq.question.reader.creativeTypes': 'What is the difference between Universe, Stories and Fan Fiction?',
    'faq.answer.reader.creativeTypes': 'Universe is a place where you can find all the stories and other content related to a specific literary world. Stories are either standalone stories or part of a universe that. Fan Fiction is a story that is based on another literary universe created by someone else.',
    // Workshop
    'faq.question.workshop.explain': 'What is the Workshop?',
    'faq.answer.workshop.explain': 'The Workshop is where you can create new stories, fan fiction, universes, and other content. It is a place to write, edit and manage your creative content.',
    'faq.question.workshop.creativeTypes': 'What is the difference between Universe, Stories and Fan Fiction?',
    'faq.answer.workshop.creativeTypes': 'Universe is a central place for your literary universe in which you create stories that inhabit the same literary world, manage encyclopedia with all the intricacies of your world and do anything else related to it. Fan Fiction is a story that is based on another story or universe created by someone else. Standalone stories are stories that are not connected to any universe, use this for example for poetry or literary works that are set in real world without many characters or immersive details that would require encyclopedia or other benefits of having a universe.',
    'faq.question.workshop.continueStory': 'How do I continue a previously created story?',
    'faq.answer.workshop.continueStory': 'You can continue a previously created story by going to the <a href="/workshop">workshop</a> and selecting the story you want to continue or if it is a story in a universe, you need to first go to the universe and select the story from the stories listing. On the story dashboard you can then click on the chapter you want to continue writing or create a new chapter.',
    'faq.question.workshop.whatIsALicense': 'What is a Story License?',
    'faq.answer.workshop.whatIsALicense': 'A story license is a legal document that defines how your story/universe can be used by others. It is a way to protect your rights and to define how others can use your work.',
    'faq.question.workshop.licenses': 'What licenses are available?',
    'faq.answer.workshop.licenses': 'We offer a variety of licenses to choose from. When creating a new work in the licenses section will be a button which will list all available licenses with their full details. In general we offer full copyright protections and <a href="https://creativecommons.org/" target="_blank" rel="noreferrer noopener external">Creative Commons</a> licenses.',
    'faq.question.workshop.guildOwnership': 'What is a Guild ownership?',
    'faq.answer.workshop.guildOwnership': 'Guild ownership indicated a work that is owned by an organization, we call them Guilds. This could be a publisher or another type of a company or non-profit organization. The ownership of the work is usually bit more complex and the author might not have full control over the work, it mainly means that the work is managed through the organization and not by the author from their personal account.',
    'faq.question.workshop.howToInviteCollaborators': 'How do I invite collaborators for a story/universe?',
    'faq.answer.workshop.howToInviteCollaborators': 'You can invite collaborators to your story/universe by going to the story/universe dashboard and clicking the "collaborators" button. There you can invite other users to collaborate on your story/universe by entering their username and selecting the role you want to assign to them.',
    'faq.question.workshop.howToTranslation': 'How can I translate my story or universe?',
    'faq.answer.workshop.howToTranslation': 'You can translate your story or universe by going to the story/universe dashboard and clicking the "Translations" button. There you can add a new translations for your work and if you have someone to do the translation you can invite them to join on the translation. From there you can also manage the translations yourself.',
    'faq.question.workshop.betaReaders': 'What are Beta Readers and what is their purpose to my story?',
    'faq.answer.workshop.betaReaders': 'Beta readers are people who read your story before it is published and give you feedback. They can help you find mistakes, give you ideas for improvement, and help you make your story better.',
    'faq.question.workshop.hiatus': 'What is a hiatus in the story status?',
    'faq.answer.workshop.hiatus': 'Hiatus is a status for your story that indicates that you are taking a break from writing and publishing new chapters. It is a way to let your readers know that you are not actively working on the story at the moment. This status gets set automatically after 6 months without any new chapters. After additional 6 months of inactivity the story will be marked as cancelled.',
    'faq.question.workshop.finished': 'How do I indicate that my story is finished?',
    'faq.answer.workshop.finished': 'You can indicate that your story is finished by going to the story dashboard and on the bottom there is a green button which says "Change story status to Completed". This will mark the story as finished adjusting the last page to tell the readers that the story is finished and to check out your other works. It will also indicate so in discovery making your story more visible to readers who are looking for finished stories.',
    'faq.question.workshop.seo': 'What is the use of SEO-Friendly-Address in various settings?',
    'faq.answer.workshop.seo': 'SEO-Friendly-Address is a way to make your story, universe, blog post more visible to search engines and easier to read URL for humans. It is a way to make your work more discoverable and to help people find your work when they search for something similar.'
};