export default {
    'feedback.home': 'Pusat Bantuan',
    'feedback.bugs': 'Masalah',
    'feedback.bugs.desc': 'Apakah Anda mengalami kesalahan atau hal lain yang salah atau tidak sesuai tempatnya. Beri tahu kami di sini!',
    'feedback.features': 'Ide & Usulan',
    'feedback.features.desc': 'Punya ide untuk fitur baru atau cara membuat situs ini lebih baik? Beri tahu kami!',
    'feedback.help': 'Bantuan & Tutorial',
    'feedback.help.desc': 'Bagaimana cara Anda _____? Pergi ke sini untuk menemukan jawabannya.',
    'feedback.desc': 'Selamat datang di pusat bantuan dan penyelesaian kami!',
    'feedback.open': 'Terbuka',
    'feedback.closed': 'Tertutup',
    'feedback.accepted': 'Diterima',
    'feedback.inprogress': 'Sedang berlangsung',
    'feedback.completed': 'Selesai',
    'feedback.fixed': 'Diperbaiki',
    'feedback.new.bugs': 'Laporkan masalah baru',
    'feedback.new.features': 'Usulkan fitur baru',
    'feedback.lang.nosupport': 'Bahasa Anda saat ini tidak didukung untuk umpan balik, harap tulis dalam Bahasa Inggris. Terima kasih!',
    'feedback.new.thanks': 'Terima kasih atas pemberitahuannya! Kami akan segera memeriksanya.',
    'feedback.comment.title': 'Komentar',
    'feedback.comment.desc': 'Kirimkan umpan balik Anda',
    'feedback.comment.legend': 'Umpan balik Anda - beri tahu kami tentang apapun',
    'feedback.comment.success': 'Terima kasih atas umpan balik Anda!',
    'feedback.comment.label': 'Komentar Anda',
    'feedback.copyrightReport.title': 'Pelanggaran hak cipta',
    'feedback.copyrightReport.desc': 'Laporkan Pelanggaran Hak Cipta',
    'feedback.report.noUser': 'Anda perlu masuk, untuk melaporkan pelanggaran.',
    'feedback.voting.totalVoters': 'Pengguna yang memberikan suara: {voted, number}',
    'feedback.voting.upvote': 'Vote atas',
    'feedback.voting.downvote': 'Vote bawah',
    'feedback.voting.score': 'Skor total',
    'feedback.report.title': 'Laporkan konten',
    'feedback.report.typeSelect': 'Apa masalahnya di sini?',
    'feedback.reportType.law': 'Pelanggaran hukum',
    'feedback.reportType.vulgar': 'Kasar/obscene',
    'feedback.reportType.copyright': 'Pelanggaran hak cipta',
    'feedback.reportType.storyRating': 'Incorrect age rating',
    'feedback.reportType.scam': 'Scam',
    'feedback.report.submit': 'Lapor',
    'feedback.report.submitting': 'Reporting...',
    'feedback.report.violationDesc': 'Details',
    'feedback.report.reportSaved': 'Thank you for the report! We will investigate and take action if needed.',
    'feedback.report.copyrightReportSaved': 'Thank you for the report! We will investigate and be in touch.',
    'feedback.report.copyrightOwnershipDesc': 'Ownership statement',
    'feedback.report.copyrightNotice': 'Please note that you need to be the rightful owner of the work to use this form. If you are not the owner, please inform the owner or use the other category to inform us. We take copyright violations extremely seriously and the same applies to improper and abusive use of this form.',
    'feedback.report.copyrightInternalProperty': 'I have published this work on Literary Universe',
    'feedback.reportType.spam': 'Spam or phishing',
    'feedback.reportType.other': 'Other',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`
};