export default {
  'forums.create': 'Aktifkan forum',
  'forums.archive': 'Arsip forum',
  'forums.archive.explained': 'Mengarsipkan forum akan mencegah pengguna untuk memposting konten lebih lanjut, tetapi tetap akan terlihat.',
  'forums.archive.success': 'Forum telah diarsipkan',
  'forums.unArchive': 'Aktifkan kembali forum',
  'forums.unArchive.success': 'Forum telah diaktifkan kembali!',
  'forums.settings': 'Pengaturan forum',
  'forums.category.create': 'Buat kategori forum',
  'forums.category.delete': 'Hapus kategori',
  'forums.category.name': 'Nama kategori',
  'forums.category.slug': 'Bagian URL SEO',
  'forums.category.settings': 'Pengaturan kategori',
  'forums.category.language': 'Batasi tampilan kategori ini hanya untuk bahasa berikut. Kosongkan jika Anda ingin menampilkan kategori dalam semua bahasa.',
  'forums.category.intlNameDescription': 'Kami telah menerjemahkan judul-judul umum kategori untuk pilihan Anda, sehingga kategori dapat tersedia dalam semua bahasa yang didukung.',
  'forums.thread.new': 'Thread baru',
  'forums.thread.delete': 'Hapus thread',
  'forums.post.new': 'Pos baru',
  'forums.archived.forum': 'Forum ini telah diarsipkan pada tanggal {archivedAt, date, long}. Anda masih dapat melihat forum, tetapi Anda tidak dapat membuat konten baru.',
  'forums.category.archive': 'Arsipkan kategori',
  'forums.category.archiveExplained': 'Kategori yang tidak memiliki thread akan dihapus, sedangkan kategori dengan konten akan mencegah pembuatan thread baru.',
  'forums.category.reactivate': 'Aktifkan kembali kategori',
  'forums.category.isVotable': 'Izinkan pengguna untuk memberikan suara naik/turun pada thread',
  'forums.category.titleIsGlobal': 'Judul kategori ini akan ditampilkan dalam bahasa pengguna jika kami mendukungnya.',
  'forums.category.languageLimited': 'Kategori ini akan ditampilkan hanya kepada pengguna dalam bahasa ini.',
  'forums.threadsCounter': 'Total jumlah topik diskusi',
  // Pre-defined category names
  'forums.category.intlName.general': 'Umum',
  'forums.category.intlName.announcements': 'Pengumuman',
  'forums.category.intlName.stories': 'Cerita',
  'forums.category.intlName.universes': 'Universes',
  'forums.category.intlName.universe': 'Universe',
  'forums.category.intlName.community': 'Komunitas',
  'forums.category.intlName.meetups': 'Pertemuan',
  'forums.category.intlName.characters': 'Karakter',
  'forums.category.intlName.locations': 'Lokasi',
  'forums.category.intlName.history': 'Sejarah',
  'forums.category.intlName.art': 'Seni',
  'forums.category.intlName.inspiration': 'Inspirasi',
  'forums.category.intlName.news': 'Berita',
  'forums.category.intlName.help': 'Bantuan',
  'forums.category.intlName.questions': 'Pertanyaan',
  'forums.category.back': 'Kembali ke gambaran forum',
  // Forum restrictions
  'forums.forumRestriction.usersOnly': 'Hanya izinkan akses untuk pengguna terdaftar',
  'forums.settings.accessControls': 'Kontrol akses',
  'forums.forumRestrictionsMessages.usersOnlyForum': 'Forum ini hanya dapat diakses oleh pengguna terdaftar.',
  'forums.noThreads': 'Tidak ada yang bisa dilihat di sini. Bergantung pada Anda untuk memulai percakapan.',
  'forums.noPosts': 'Belum ada yang membalas. Jadilah yang pertama!',
  // Threads
  'forums.createThread': 'Buat diskusi baru',
  'forums.createThreadIn': 'Buat thread baru di {categoryName}',
  'forums.openingPost': 'Posting pembuka',
  'forums.createQuestionLabel': 'Apakah ini pertanyaan?',
  'forums.thread.noReplies': 'Saat ini belum ada balasan di sini.',
  'forums.reply': 'Balas',
  'forums.post': 'Kiriman',
  'forums.posting': 'Mengirim...',
  'forums.reset': 'Atur ulang',
  'forum.thread.reply': 'Tambahkan balasan ke thread ini',
  'forums.yourMessage': 'Pesan Anda',
  'forums.thread.replyPosted': 'Pesan Anda telah diposting',
  'forums.thread.totalPosts': `{totalReplies, number} {totalReplies, plural,
    one {balasan}
    other {balasan}
  }`,
  'forums.thread.createdAt': 'Dibuat pada {createdAt, date, medium}'
};