/**
 * Licenses for creative works
 * https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
 */
export default {
    'licenses.about': 'Tentang Lisensi',
    'licenses.more': 'Informasi lebih lanjut',
    'licenses.legal': 'Dokumen hukum',
    'licenses.name.cc-by': 'Creative Commons Attribution 4.0',
    'licenses.cc-by': 'Lisensi ini mengizinkan orang lain untuk mengubah, memperbaiki, membuat ciptaan turunan, dan mendistribusikan secara komersial, selama mereka mencantumkan kredit kepada Anda atas ciptaan asli. Lisensi ini merupakan lisensi yang paling bebas. Lisensi ini direkomendasikan untuk pendistribusian luas secara maksimal dan penggunaan materi berlisensi.',
    'licenses.name.cc-by-sa': 'Creative Commons Attribution-ShareAlike 4.0',
    'licenses.cc-by-sa': 'Lisensi ini mengizinkan orang lain untuk mencampur, mengubah, dan mengembangkan karya Anda bahkan untuk tujuan komersial, selama mereka memberikan kredit kepada Anda dan melisensikan kreasi baru mereka di bawah persyaratan yang sama. Lisensi ini sering dibandingkan dengan lisensi perangkat lunak bebas dan sumber terbuka "copyleft". Semua karya baru yang dibuat berdasarkan karya Anda akan menggunakan lisensi yang sama, sehingga semua turunannya juga dapat digunakan secara komersial. Ini adalah lisensi yang digunakan oleh Wikipedia, dan direkomendasikan untuk materi yang akan mendapatkan keuntungan dari penggabungan konten dari Wikipedia dan proyek-proyek berlisensi serupa.',
    'licenses.name.cc-by-nd': 'Creative Commons Attribution-NoDerivs 4.0',
    'licenses.cc-by-nd': 'Lisensi ini memungkinkan redistribusi, baik komersial maupun non-komersial, selama tetap tidak berubah dan utuh, dengan memberikan kredit kepada Anda.',
    'licenses.name.cc-by-nc': 'Creative Commons Attribution-NonCommercial 4.0',
    'licenses.cc-by-nc': 'Lisensi ini mengizinkan orang lain untuk menggubah, mengubah, dan mengembangkan karya Anda secara non-komersial, dan meskipun karya baru mereka juga harus mengakui Anda dan bersifat non-komersial, mereka tidak perlu melisensikan karya turunannya dengan ketentuan yang sama.',
    'licenses.name.cc-by-nc-sa': 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0',
    'licenses.cc-by-nc-sa': 'Lisensi ini memungkinkan orang lain untuk membuat ulang, memodifikasi, dan membangun berdasarkan karya Anda secara non-komersial, selama mereka memberikan kredit kepada Anda dan melisensikan karya baru mereka dengan persyaratan yang sama.',
    'licenses.name.cc-by-nc-nd': 'Creative Commons Attribution-NonCommercial-NoDerivs 4.0',
    'licenses.cc-by-nc-nd': 'Lisensi ini merupakan lisensi yang paling ketat dari enam lisensi utama kami, hanya mengizinkan orang lain untuk mengunduh karya Anda dan membagikannya kepada orang lain selama mereka memberikan kredit kepada Anda, tetapi mereka tidak dapat mengubahnya dengan cara apa pun atau menggunakannya secara komersial.',
    'licenses.name.lu-c': 'Hak Cipta Literary Universe',
    'licenses.lu-c': 'Lisensi hak cipta penuh standar yang memungkinkan Anda untuk menjual dan menerbitkan karya Anda sesuai keinginan dan melindungi hak-hak Anda terhadapnya. Lisensi ini juga memberi Anda opsi untuk menjual cerita Anda di Literary Universe.',
    'licenses.name.lu-e': 'Literary Universe Eksklusif',
    'licenses.lu-e': 'Lisensi ini memberikan hak eksklusif kepada Literary Universe untuk mempublikasikan dan mendistribusikan karya Anda secara online. Anda akan mempertahankan hak cipta, tetapi Literary Universe akan memiliki hak tunggal untuk mempublikasikan dan mendistribusikan karya Anda secara online.',
    'licenses.name.lu-ne': 'Semesta Sastra Non-Eksklusif',
    'licenses.lu-ne': 'Lisensi ini memberikan hak non-eksklusif kepada Literary Universe untuk mempublikasikan dan mendistribusikan karya Anda secara online. Anda akan tetap memiliki hak cipta dan hak untuk mempublikasikan dan mendistribusikan karya Anda melalui saluran lain.',
    'licenses.name.cc0': 'No Rights Reserved - CC0 1.0',
    'licenses.cc0': 'Menempatkan karya Anda ke dalam domain publik. Berbeda dengan lisensi CC yang mengizinkan pemegang hak cipta untuk memilih dari serangkaian izin sambil tetap mempertahankan hak cipta mereka, CC0 memberdayakan pilihan lain yang sama sekali berbeda, yaitu pilihan untuk tidak menggunakan hak cipta dan perlindungan basis data, dan hak eksklusif yang secara otomatis diberikan kepada pencipta, yaitu alternatif "tidak ada hak cipta" pada lisensi kami.',
    // License Chooser Modal
    'licenses.chooser.title': 'Pemilih Lisensi',
    'licenses.chooser.button': 'Bantu saya memilih lisensi',
    'licenses.chooser.ariaLabel': 'Pilih lisensi untuk pekerjaan Anda',
    'licenses.chooser.introduction': 'Alat ini akan membantu Anda memilih lisensi yang paling tepat untuk karya Anda. Lisensi menentukan bagaimana orang lain dapat menggunakan karya Anda dan memengaruhi kemampuan Anda untuk memonetisasinya di Literary Universe.',
    // License Chooser Wizard Steps
    'licenses.chooser.step.contentType.title': 'Jenis konten apa yang Anda lisensikan?',
    'licenses.chooser.step.contentType.description': 'Jenis konten memengaruhi lisensi mana yang tersedia untuk Anda.',
    'licenses.chooser.step.contentType.original': 'Karya Asli',
    'licenses.chooser.step.contentType.fanfiction': 'Fiksi Penggemar',
    'licenses.chooser.step.contentType.fanfictionNote': 'Karya-karya fiksi penggemar di Literary Universe secara otomatis diberi lisensi Creative Commons Atribusi-NonKomersial (CC BY-NC). Hal ini dikarenakan fiksi penggemar didasarkan pada karya berhak cipta yang dimiliki oleh orang lain, dan penggunaan secara komersial berpotensi melanggar hak-hak tersebut.',
    'licenses.chooser.step.commercial.title': 'Apakah Anda ingin menghasilkan uang dari karya Anda?',
    'licenses.chooser.step.commercial.description': 'Memilih untuk memonetisasi karya Anda akan memengaruhi lisensi mana yang paling tepat.',
    'licenses.chooser.step.commercial.yes': 'Ya, saya ingin menghasilkan uang dari pekerjaan saya',
    'licenses.chooser.step.commercial.no': 'Tidak, saya tidak ingin memonetisasi karya saya',
    'licenses.chooser.step.commercial.monetizeNote': 'Untuk memonetisasi karya Anda di Literary Universe, Anda harus menggunakan salah satu lisensi komersial kami. Lisensi ini memungkinkan Anda untuk menjual karya Anda dengan tetap mempertahankan perlindungan hak cipta.',
    'licenses.chooser.step.exclusivity.title': 'Apakah Anda ingin menerbitkan secara eksklusif di Literary Universe?',
    'licenses.chooser.step.exclusivity.description': 'Memilih eksklusivitas memengaruhi biaya platform dan opsi penerbitan.',
    'licenses.chooser.step.exclusivity.yes': 'Ya, secara eksklusif di Literary Universe',
    'licenses.chooser.step.exclusivity.no': 'Tidak, saya juga ingin menerbitkan di tempat lain',
    'licenses.chooser.step.exclusivity.exclusiveNote': 'Dengan penerbitan eksklusif di Literary Universe, Anda akan mendapatkan keuntungan dari biaya platform yang lebih rendah sebesar 10%. Ini berarti Anda menyimpan 90% dari penghasilan Anda.',
    'licenses.chooser.step.exclusivity.nonExclusiveNote': 'Dengan penerbitan non-eksklusif, Anda dapat menerbitkan karya Anda di platform lain juga. Biaya platform adalah 30%, yang berarti Anda menyimpan 70% dari penghasilan Anda di Literary Universe. Di masa depan, kami akan menyediakan alat untuk membantu Anda menerbitkan ke platform lain langsung dari Literary Universe.',
    'licenses.chooser.step.derivatives.title': 'Apakah Anda ingin mengizinkan orang lain membuat karya turunan?',
    'licenses.chooser.step.derivatives.description': 'Karya turunan termasuk adaptasi, remix, atau transformasi dari karya asli Anda.',
    'licenses.chooser.step.derivatives.yes': 'Ya, izinkan karya turunan',
    'licenses.chooser.step.derivatives.no': 'Tidak, jangan izinkan karya turunan',
    'licenses.chooser.step.derivatives.allowNote': 'Dengan mengizinkan karya turunan, orang lain dapat mengadaptasi, menggubah, atau mengubah karya Anda. Hal ini dapat mengarah pada distribusi yang lebih luas dan penggunaan ulang konten Anda secara kreatif.',
    'licenses.chooser.step.derivatives.disallowNote': 'Tidak mengizinkan karya turunan berarti karya Anda harus disebarkan tanpa perubahan dan secara utuh, meskipun masih dapat dibagikan dengan atribusi yang tepat.',
    'licenses.chooser.step.attribution.title': 'Apakah Anda ingin meminta atribusi?',
    'licenses.chooser.step.attribution.description': 'Atribusi berarti orang lain harus memberi Anda kredit ketika mereka menggunakan karya Anda.',
    'licenses.chooser.step.attribution.yes': 'Ya, memerlukan atribusi',
    'licenses.chooser.step.attribution.no': 'Tidak, tempatkan di domain publik (CC0)',
    'licenses.chooser.step.attribution.requireNote': 'Memerlukan atribusi berarti siapa pun yang menggunakan karya Anda harus memberi Anda kredit dengan cara yang Anda minta.',
    'licenses.chooser.step.attribution.publicDomainNote': 'Menempatkan karya Anda dalam domain publik (CC0) berarti Anda melepaskan semua hak cipta dan hak-hak terkait. Orang lain dapat dengan bebas menggunakan karya Anda untuk tujuan apa pun tanpa atribusi.',
    // License Result
    'licenses.chooser.result.commercialTitle': 'Informasi Komersial',
    'licenses.chooser.result.exclusiveInfo': 'Dengan lisensi Literary Universe Exclusive, Anda akan mendapatkan keuntungan dari biaya platform yang lebih rendah sebesar 10%. Ini berarti Anda menyimpan 90% dari penghasilan Anda, tetapi Anda hanya dapat mempublikasikan karya ini di Literary Universe.',
    'licenses.chooser.result.nonExclusiveInfo': 'Dengan lisensi Non-Eksklusif Literary Universe, Anda dapat mempublikasikan karya Anda di platform lain juga. Biaya platform adalah 30%, yang berarti Anda menyimpan 70% dari penghasilan Anda di Literary Universe. Di masa depan, kami akan menyediakan alat untuk membantu Anda menerbitkan ke platform lain langsung dari Literary Universe.',
    'licenses.chooser.result.fanfictionNote': 'Lisensi ini secara otomatis diterapkan pada karya fiksi penggemar karena karya tersebut didasarkan pada materi berhak cipta yang dimiliki orang lain. Penggunaan secara komersial berpotensi melanggar hak-hak tersebut.',
    'licenses.chooser.result.selectLicense': 'Pilih Lisensi Ini'
};