export default {
    'stats.age.groups': 'Kelompok usia',
    'stats.age.range': 'Rentang usia',
    'stats.age.to12': 'Hingga 12',
    'stats.age.12to17': '12 hingga 17',
    'stats.age.18to20': '18 hingga 20',
    'stats.age.21to29': '21 hingga 29',
    'stats.age.30to39': '30 hingga 39',
    'stats.age.40to49': '40 hingga 49',
    'stats.age.50to64': '50 hingga 64',
    'stats.age.65to84': '64 hingga 84',
    'stats.age.above85': 'Di atas 85',
    'stats.section.aggregate': 'Statistik agregat',
    'stats.section.chapter': 'Statistik bab',
    'stats.readers.title': 'Tentang pembaca Anda',
    'stats.gender.title': 'Jenis kelamin',
    'stats.view.table': 'Tampilan tabel',
    'stats.view.pie': 'Tampilan Diagram Lingkaran',
    'stats.view.bar': 'Tampilan Diagram Batang',
    'stats.view.chart': 'Tampilan diagram',
    'stats.table.total': 'Total',
    'stats.timeline.title': 'Timeline',
    'stats.timeline.dateStart': 'Statistik dimulai pada',
    'stats.timeline.dateEnd': 'Statistik berakhir pada',
    'stats.likeCount': 'Jumlah suka',
    'stats.language.title': 'Bahasa yang digunakan',
    'stats.chapter.visitorsAndViews': 'Total pengunjung dan tampilan per bab',
    'stats.chapter.wordCount': 'Jumlah kata per bab',
    'stats.chapter.chartTooltipViews': 'Bab {chapter, number}: {views, number} kali dilihat',
    'stats.chapter.chartTooltipVisitors': 'Bab {chapter, number}: {visitors, number} pengunjung unik',
    'stats.chapter.chartTooltipWordCount': 'Bab {chapter, number}: {wordCount, number} kata',
    'stats.totalHits': 'Total tampilan',
    'stats.totalVisitors': 'Total pengunjung unik',
    'stats.totalWords': 'Total kata',
    'stats.totalEntries': 'Entri ensiklopedia',
    'stats.blogPage': 'Halaman',
    'stats.blog.typeSelectionAria': 'Pemilihan jenis',
    'stats.blog.pages': 'Halaman',
    'stats.blog.posts': 'Kiriman',
    'stats.unknown': 'Tidak diketahui',
    'stats.noData': 'Tidak ada data yang tersedia saat ini.'
};