export default {
  'events.upcoming': 'Esdeveniments propers',
  'events.settings.title': 'Configuració de l\'esdeveniment',
  'events.attendance.attending': 'Assistència',
  'events.attendance.tentative': 'Pendent',
  'events.attendance.notAttending': 'No assistirà',
  'events.details.name': 'Nom de l\'esdeveniment',
  'events.details.image': 'Imatge de l\'esdeveniment',
  'events.details.description': 'Descripció de l\'esdeveniment / Agenda',
  'events.details.url': 'Enllaç a més detalls',
  'events.details.virtualLink': 'Enllaç a la ubicació virtual (p. ex., Zoom, Google Meets, etc.)',
  'events.details.address': 'Adreça del lloc',
  'events.details.startsAt': 'Inici de l\'esdeveniment',
  'events.details.endsAt': 'Final de l\'esdeveniment',
  'events.details.type': 'Tipus d\'esdeveniment',
  'events.type.inPerson': 'Presencial',
  'events.type.virtual': 'Virtual',
  'events.type.hybrid': 'Híbrid',
  'events.join.startsIn': 'L\'esdeveniment comença en {startsAt}',
  // The startsAt is going to be in a relative time format. Eg. `in 1 minute`, `1 day ago`, etc...
  'events.join.virtual': 'Unir-se a l\'esdeveniment',
  'events.selection.origin': 'Origen de l\'esdeveniment',
  'events.origin.universe': 'Univers',
  'events.origin.author': 'Autor',
  'events.origin.groups': 'Grups',
  'events.origin.organizations': 'Organitzacions',
  'events.origin.lu': 'Esdeveniments de l\'Univers Literari',
  'events.visibility.label': 'Visibilitat de l\'esdeveniment',
  'events.visibility.public': 'Públic: qualsevol persona pot veure aquest esdeveniment',
  'events.visibility.owner': `Propietari: només {type, select,
    group {membres del teu grup}
    universe {col·laboradors i fans de l'univers}
    organization {membres de la teva organització}
    other {tu i les persones que convides}
  } poden veure aquest esdeveniment`,
  'events.visibility.private': 'Privat: només les persones convidades veuran l\'esdeveniment',
  'events.inviting': 'Les persones que veuen aquest esdeveniment poden convidar altres?',
  'events.administration': 'Administració d\'esdeveniments',
  'events.create.title': 'Crear un nou esdeveniment',
  'events.hostedBy': 'Organitzat per {hostName}',
  'events.openVirtual': 'Anar a la ubicació virtual',
  'events.moreInfo': 'More information',
  'event.visibilityShort.private': 'Privada',
  'event.visibilityShort.public': 'Pública',
  'event.visibilityShort.owner': 'Propietari'
};