export default {
    'feedback.home': 'Centre d\'ajuda',
    'feedback.bugs': 'Problemes',
    'feedback.bugs.desc': 'Has trobat un error o alguna cosa que està malament o fora de lloc? Fes-nos-ho saber aquí!',
    'feedback.features': 'Idees i propostes',
    'feedback.features.desc': 'Tens idees per a noves funcionalitats o com millorar el lloc? Fes-nos-ho saber!',
    'feedback.help': 'Ajuda i tutorials',
    'feedback.help.desc': 'Com ho fas per a _____? Vés aquí per trobar les respostes.',
    'feedback.desc': 'Benvingut al nostre centre d\'ajuda i resolució!',
    'feedback.faq': 'PMF',
    'feedback.faq.desc': 'Preguntes freqüents',
    'feedback.open': 'Obert',
    'feedback.closed': 'Tancat',
    'feedback.accepted': 'Acceptat',
    'feedback.inprogress': 'En progrés',
    'feedback.completed': 'Completat',
    'feedback.fixed': 'Solucionat',
    'feedback.new.bugs': 'Informa d\'un nou problema',
    'feedback.new.features': 'Suggerir una nova funcionalitat',
    'feedback.lang.nosupport': 'El teu idioma actual no té suport per a les opinions, si us plau escriu en anglès. Gràcies!',
    'feedback.new.thanks': 'Gràcies per l\'avís! Ho revisarem aviat.',
    'feedback.comment.title': 'Comentari',
    'feedback.comment.desc': 'Envia\'ns la teva opinió',
    'feedback.comment.legend': 'La teva opinió - fes-nos saber qualsevol cosa',
    'feedback.comment.success': 'Gràcies per la teva opinió!',
    'feedback.comment.label': 'El teu comentari',
    'feedback.copyrightReport.title': 'Violació dels drets d\'autor',
    'feedback.copyrightReport.desc': 'Informar sobre una violació dels drets d\'autor',
    'feedback.report.noUser': 'Has d\'iniciar sessió per poder presentar un informe.',
    'feedback.voting.totalVoters': 'Usuaris que han votat: {voted, number}',
    'feedback.voting.upvote': 'Vot positiu',
    'feedback.voting.downvote': 'Vot negatiu',
    'feedback.voting.score': 'Puntuació total',
    'feedback.report.title': 'Informar contingut',
    'feedback.report.typeSelect': 'Quin és el problema aquí?',
    'feedback.reportType.law': 'Infracció de la llei',
    'feedback.reportType.vulgar': 'Vulgar/obscè',
    'feedback.reportType.copyright': 'Infracció de drets d\'autor',
    'feedback.reportType.storyRating': 'Valoració d\'edat incorrecta',
    'feedback.reportType.scam': 'Estafa',
    'feedback.report.submit': 'Informe',
    'feedback.report.submitting': 'Informe en curs...',
    'feedback.report.violationDesc': 'Detalls',
    'feedback.report.reportSaved': 'Gràcies per l\'informe! Investigarem i prendrem les mesures necessàries si cal.',
    'feedback.report.copyrightReportSaved': 'Gràcies per l\'informe! Investigarem i ens posarem en contacte.',
    'feedback.report.copyrightOwnershipDesc': 'Declaració de propietat',
    'feedback.report.copyrightNotice': 'Cal tenir en compte que has de ser el propietari legítim de l\'obra per utilitzar aquest formulari. Si no ho ets, informa al propietari o utilitza una altra categoria per informar-nos. Prendrem les violacions de drets d\'autor extremadament seriosament, així com l\'ús indegut i abusiu d\'aquest formulari.',
    'feedback.report.copyrightInternalProperty': 'He publicat aquesta obra a Literary Universe',
    'feedback.reportType.spam': 'Correu brossa o phishing',
    'feedback.reportType.other': 'Altres',
    'feedback.report.copyrightType.propertySelectLabel': `Quin {type, select,
    universe {univers}
    story {història}
    other {història}
  } s'està infringint?`,
    'faq.section.about': 'Sobre nosaltres',
    'faq.section.settings': 'Configuració',
    'faq.section.discovery': 'Descoberta',
    'faq.section.reader': 'Lector',
    'faq.section.library': 'Biblioteca',
    'faq.section.workshop': 'Taller',
    'faq.section.writer': 'Escriptor',
    'faq.section.encyclopedia': 'Enciclopèdia',
    'faq.section.groups': 'Grups',
    'faq.section.blogs': 'Blogs',
    'faq.section.guilds': 'Gremis',
    // About us questions
    'faq.question.about.whatIsLU': 'Què és l\'Univers Literari?',
    'faq.answer.about.whatIsLU': 'L\'Univers Literari és una plataforma per a escriptors i lectors per crear, compartir i descobrir històries i mons.',
    'faq.question.about.difference': 'Quina és la diferència entre l\'Univers Literari i altres plataformes de lectura en línia?',
    'faq.answer.about.difference': 'L\'Univers Literari és una plataforma tot en un, el que significa que inclou eines per escriure, llegir, construir mons i crear comunitats. La diferència clau és la inclusió de totes aquestes eines en una sola plataforma i la seva interconnexió.',
    'faq.question.about.dataLocation': 'On es guarda la informació de LU?',
    'faq.answer.about.dataLocation': 'La informació de Literary Universe es guarda en servidors als Estats Units d\'Amèrica, concretament a la regió AWS us-east-1.',
    'faq.question.about.incorporation': 'On esteu constituïts?',
    'faq.answer.about.incorporation': 'Literary Universe està incorporat a la República Txeca. Podeu trobar més detalls a la pàgina <a href="/about">sobre nosaltres</a>.',
    'faq.question.about.roadmap': 'Quins són els propers passos per a Literary Universe?',
    'faq.answer.about.roadmap': 'Això està en constant evolució. Consulteu el nostre <a href="/roadmap">mapa de ruta</a> per obtenir més detalls.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Com puc canviar l\'aparença de Literary Universe?',
    'faq.answer.settings.changeTheme': 'Els usuaris registrats poden canviar el seu tema a la configuració del compte <a href="/user/settings/account"></a> a la secció "tematització del lloc". Tenim disponibles un tema clar i un tema fosc. Si no esteu registrats, intentem determinar quin tema us servim en funció de la configuració del navegador i del sistema operatiu.',
    'faq.question.settings.changeAvatar': 'Com puc canviar el meu avatar?',
    'faq.answer.settings.changeAvatar': 'Podeu canviar el vostre avatar a la configuració del perfil <a href="/user/settings/profile"></a>.',
    'faq.question.settings.changeLanguage': 'Com puc canviar l\'idioma?',
    'faq.answer.settings.changeLanguage': 'Podeu canviar l\'idioma de Literary Universe a la configuració del compte <a href="/user/settings/account"></a>.',
    'faq.question.settings.translationMistake': 'He trobat un error en el text del lloc web, on el puc informar?',
    'faq.answer.settings.translationMistake': 'Tots els nostres fitxers d\'idioma estan disponibles a GitHub. Podeu <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">informar d\'un problema allà</a> o a la secció d\'Errors del feedback, o si ho preferiu, podeu corregir-lo directament vosaltres mateixos a través de <a href="https://crowdin.com/project/literary-universe" target="_blank">la nostra pàgina de Crowdin</a>.',
    // Discovery questions
    'faq.question.discovery.explain': 'Què és la secció de Descoberta?',
    'faq.answer.discovery.explain': 'La secció de Descoberta és on podeu trobar noves històries, universos, blocs, grups i altres continguts. És un lloc per explorar i trobar noves coses per llegir i gaudir.',
    // Writer
    'faq.question.writer.howToCreateStory': 'Com puc crear una nova història a l\'Univers Literari?',
    'faq.answer.writer.howToCreateStory': 'You can create a new story by going to the <a href="/workshop">workshop</a> and clicking on one of the create buttons or go to the main <a href="/workshop/create">create page</a> where you can select a <a href="/workshop/create/story">new standalone story</a> or <a href="/workshop/create/fanfiction">fan fiction</a>. To create a new story in a universe, go first to that universe and then select "stories" on the dashboard and on the next page click the big red button on the right side of the page title. You will be asked to fill in the details of your story and then you can start writing.',
    'faq.question.writer.schedule': 'Com puc programar la publicació d\'un capítol a l\'Univers Literari?',
    'faq.answer.writer.schedule': 'Podeu programar la publicació d\'un capítol en fer clic al botó de publicar a l\'editor de capítols. Es mostrarà un modal on tindreu l\'opció de programar una publicació o publicar immediatament. Si opteu per programar una publicació, se us demanarà que seleccioneu la data i l\'hora en què voleu que es publiqui el capítol. Recomanem programar els capítols amb almenys 24 hores d\'antelació per donar temps als lectors per preparar-se pel nou capítol i per publicar-lo el mateix dia i hora de la setmana.',
    // Reader
    'faq.question.reader.creativeTypes': 'Quina és la diferència entre Univers, Històries i Fan Fiction?',
    'faq.answer.reader.creativeTypes': 'L\'univers és un lloc on pots trobar totes les històries i altres continguts relacionats amb un món literari específic. Les històries poden ser històries independents o formar part d\'un univers. El Fan Fiction és una història basada en un altre univers literari creat per algú altre.',
    // Workshop
    'faq.question.workshop.explain': 'Què és el Taller?',
    'faq.answer.workshop.explain': 'El Taller és on pots crear noves històries, fan fiction, universos i altres continguts. És un lloc per escriure, editar i gestionar el teu contingut creatiu.',
    'faq.question.workshop.creativeTypes': 'Quina és la diferència entre Univers, Històries i Fan Fiction?',
    'faq.answer.workshop.creativeTypes': 'L\'univers és un lloc central per al teu univers literari en el qual pots crear històries que habiten al mateix món literari, gestionar una enciclopèdia amb totes les complexitats del teu món i fer tot el que estigui relacionat amb això. El Fan Fiction és una història basada en una altra història o univers creat per algú altre. Les històries independents són històries que no estan connectades a cap univers, utilitza això, per exemple, per a poesia o obres literàries que estan ambientades en el món real sense molts personatges o detalls immersius que requereixin una enciclopèdia o altres avantatges de tenir un univers.',
    'faq.question.workshop.continueStory': 'Com puc continuar una història creada anteriorment?',
    'faq.answer.workshop.continueStory': 'You can continue a previously created story by going to the <a href="/workshop">workshop</a> and selecting the story you want to continue or if it is a story in a universe, you need to first go to the universe and select the story from the stories listing. On the story dashboard you can then click on the chapter you want to continue writing or create a new chapter.',
    'faq.question.workshop.whatIsALicense': 'Què és una llicència d\'història?',
    'faq.answer.workshop.whatIsALicense': 'Una llicència d\'història és un document legal que defineix com es pot utilitzar la teva història/univers per altres persones. És una manera de protegir els teus drets i de definir com altres persones poden utilitzar la teva obra.',
    'faq.question.workshop.licenses': 'Quines llicències estan disponibles?',
    'faq.answer.workshop.licenses': 'We offer a variety of licenses to choose from. When creating a new work in the licenses section will be a button which will list all available licenses with their full details. In general we offer full copyright protections and <a href="https://creativecommons.org/" target="_blank" rel="noreferrer noopener external">Creative Commons</a> licenses.',
    'faq.question.workshop.guildOwnership': 'Què és la propietat d\'una guilda?',
    'faq.answer.workshop.guildOwnership': 'La propietat de la guild indica una obra que pertany a una organització, les anomenem Guilds. Això pot ser una editorial o un altre tipus d\'empresa o organització sense ànim de lucre. La propietat de l\'obra sol ser una mica més complexa i l\'autor pot no tenir un control total sobre l\'obra, simplement significa que l\'obra es gestiona a través de l\'organització i no per l\'autor des del seu compte personal.',
    'faq.question.workshop.howToInviteCollaborators': 'Com puc convidar col·laboradors per a una història/univers?',
    'faq.answer.workshop.howToInviteCollaborators': 'Pots convidar col·laboradors a la teva història/univers anant al tauler de la història/univers i fent clic al botó "col·laboradors". Allà pots convidar altres usuaris perquè col·laborin en la teva història/univers introduint el seu nom d\'usuari i seleccionant el rol que vols assignar-los.',
    'faq.question.workshop.howToTranslation': 'Com puc traduir la meva història o univers?',
    'faq.answer.workshop.howToTranslation': 'Pots traduir la teva història o univers anant al tauler de la història/univers i fent clic al botó "Traduccions". Allà pots afegir noves traduccions per a la teva obra i, si tens algú per fer la traducció, pots convidar-los a unir-se a la traducció. Des d\'allà també pots gestionar les traduccions tu mateix.',
    'faq.question.workshop.betaReaders': 'Què són els Beta Readers i quin és el seu propòsit en la meva història?',
    'faq.answer.workshop.betaReaders': 'Els Beta Readers són persones que llegeixen la teva història abans que sigui publicada i et donen feedback. Poden ajudar-te a trobar errors, donar-te idees per millorar i ajudar-te a fer la teva història millor.',
    'faq.question.workshop.hiatus': 'Què és una pausa en l\'estat de la història?',
    'faq.answer.workshop.hiatus': 'Una pausa és un estat per a la teva història que indica que estàs fent una pausa en l\'escriptura i la publicació de nous capítols. És una manera de fer saber als lectors que no estàs treballant activament en la història en aquest moment. Aquest estat es configura automàticament després de 6 mesos sense cap capítol nou. Després de 6 mesos addicionals d\'inactivitat, la història es marcarà com a cancel·lada.',
    'faq.question.workshop.finished': 'Com indico que la meva història està acabada?',
    'faq.answer.workshop.finished': 'Pots indicar que la teva història està acabada anant al tauler de la història i a la part inferior hi ha un botó verd que diu "Canviar l\'estat de la història a Completada". Això marcarà la història com a acabada, ajustant l\'última pàgina per dir als lectors que la història ha acabat i que mirin les teves altres obres. També ho indicarà a la descoberta, fent que la teva història sigui més visible pels lectors que busquen històries acabades.',
    'faq.question.workshop.seo': 'Quin és l\'ús de l\'adreça SEO-Friendly en diversos ajustos?',
    'faq.answer.workshop.seo': 'SEO-Friendly-Address és una manera de fer que la teva història, univers, entrada de blog sigui més visible per als motors de cerca i que la URL sigui més fàcil de llegir pels humans. És una manera de fer que la teva feina sigui més descobrible i d\'ajudar les persones a trobar la teva feina quan cerquen alguna cosa similar.'
};