export default {
    'org.auditLog.title': 'Registre d\'auditoria',
    'org.settings.title': 'Configuració de l\'organització',
    'org.settings.name': 'Nom de l\'organització',
    'org.settings.membersPrivate': 'NO mostrar els membres públicament',
    'org.logo': 'Logotip de l\'organització',
    'org.logo.alt': '{organizationName} logo',
    'org.superAdmin': 'Superadministrador',
    'org.settings.language': 'Idioma principal',
    'org.meta.desc': 'Organitzacions i grups creatius a Literary Universe.',
    'org.luOrgs': 'Organitzacions de Literary Universe',
    'org.otherOrgs': 'Organizations',
    'org.aboutTitle': 'Sobre {orgName}',
    'org.membersTitle': 'Membres de l\'organització',
    'org.membersNone': 'Els membres no són públics',
    'org.storiesTitle': 'Històries de {orgName}',
    'org.universesTitle': 'Universos de {orgName}',
    'org.userDashboardTitle': 'Les teves organitzacions',
    'org.settings.hideMembers.label': 'Amaga els membres al públic',
    'org.visit': 'Anar a la pàgina {organization}',
    'org.authorOverride.legend': 'Substitució de l\'autor',
    'org.authorOverride.desc': 'Mostra aquest text en lloc del nom de l\'organització.',
    'org.authorOverride.label': 'Nom de l\'autor',
    'org.membersAdd.title': 'Convida membres a l\'organització',
    'org.flashnews.admin': 'Administració de Flashnews',
    'org.settings.tabListAria': 'Configuració de seccions per a l\'organització',
    'org.forums.title': '{orgName} fòrums',
    'org.flashnews.internal': 'Flashos de notícies internes',
    'org.flashnews.publicAll': 'Flashos de notícies públiques per a totes les propietats',
    'org.flashnews.createTitle': `Crea un nou flash de notícies per a {type, select,
    internal {l'organització}
    allProperties {per mostrar públicament a totes les propietats de}
    other {l'organització}
  }`,
    'org.members.invited': 'Membres convidats',
    'org.members.list': 'Membres de l\'organització',
    'org.invitesTileNotice': 'Has estat convidat a {count, number} {count, plural, one {organització} other {organitzacions}}',
    'org.invitePage.title': 'Invitacions a organitzacions',
    'org.invitePage.invitedAt': 'Has estat convidat el {invitedAt, date, short}',
    'org.invitePage.ignoring': 'Actualment ignores aquesta invitació, el que significa que encara està activa, però no rebràs notificacions.',
    'org.invitePage.expiresAt': 'Aquesta invitació expirarà el {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Uniu-vos a l\'organització',
    'org.invitePage.reject': 'Rebutja la invitació',
    'org.invitePage.ignore': 'Ignora per ara',
    'org.leaveOrg.title': 'Deixa l\'organització',
    'org.leaveOrg.confirm': 'Aquesta acció és destructiva. Un cop marxeu, perdreu tot l\'accés a aquesta organització. Esteu segur que voleu marxar de l\'organització?',
    'org.confirmRemove.aria': 'Confirma l\'eliminació de l\'usuari',
    'org.confirmRemove.confirm': 'Esteu segur que voleu eliminar {username} de {organization}?',
    'org.confirmRemove.remove': 'Elimina l\'usuari',
    'org.mainBlog': 'Blog principal',
    'org.teams': 'Equips',
    'org.teams.total': 'Total d\'equips: {totalTeams, number}',
    'org.teams.create': 'Crea un nou equip',
    'org.teams.settings': 'Configuració de l\'equip',
    'org.workshop.ownerUser': 'Not a guild work',
    'org.workshop.caption': 'Guild ownership',
    'org.workshop.title': 'Taller d\'organització',
    'org.title': 'Organització',
    'org.hall.title': '{orgName} members hall',
    'org.member.leave': 'Leave organization',
    'org.member.leaveModalTitle': 'Leaving organization confirmation',
    'org.member.leaveModalHeading': 'Are you sure you want to leave {orgName}',
    'org.member.leaveModalExplain': 'Once you leave the organization you will loose access to all of the organization\'s associated resources and works. This action can\'t be undone.',
    // Role management strings
    'org.member.manageRoles': 'Manage Roles',
    'org.roles.error': 'Error: {error}',
    'org.roles.manageFor': 'Managing roles for {name}',
    'org.roles.selectRole': 'Select role',
    'org.roles.noRole': 'No role (permissions only)',
    'org.roles.admin': 'Admin',
    'org.roles.member': 'Member',
    'org.roles.author': 'Author',
    'org.roles.workshop': 'Workshop',
    'org.roles.teacher': 'Teacher',
    'org.permissions.title': 'Permissions',
    'org.permissions.includedInRole': '(included in role)',
    // Permission names
    'org.permissions.members.add': 'Add members',
    'org.permissions.members.remove': 'Remove members',
    'org.permissions.members.view': 'View members',
    'org.permissions.settings': 'Manage settings',
    'org.permissions.auditLog': 'View audit log',
    'org.permissions.flashnews': 'Manage flash news',
    'org.permissions.workshop.view': 'View workshop',
    'org.permissions.workshop.create': 'Create workshop items',
    'org.permissions.workshop.transfer': 'Transfer ownership',
    'org.permissions.workshop.viewAll': 'View all workshop items',
    'org.permissions.forum.manager': 'Manage forums',
    'org.permissions.blog.manage': 'Manage blog',
    'org.permissions.blog.post': 'Create blog posts'
};