export default {
    'homepage.welcome': 'Benvingut a',
    'homepage.start': 'Comença el teu viatge!',
    'homepage.iAm': 'Sóc un',
    'homepage.iAm.aria': 'Selecciona entre la visualització de funcionalitats per a lectors i escriptors',
    'homepage.reader': 'LECTOR',
    'homepage.writer': 'ESCRITOR',
    'homepage.reader.title': 'La lectura mai ha estat tan interessant com ara',
    'homepage.reader.readingTitle': 'Experiència de lectura única',
    'homepage.reader.readingDesc': 'Aprofundeix en el teu univers fictici preferit a Literary Universe. Les històries de Literary Universe estan connectades dins del mateix univers, donant-te accés immediat a l\'enciclopèdia de l\'univers des de l\'lector d\'històries.',
    'homepage.reader.favoriteTitle': 'Descobreix més sobre les teves històries i autors preferits',
    'homepage.reader.favoriteDesc': 'L\'enciclopèdia de l\'univers i els blogs dels autors són només algunes de les funcionalitats que t\'ajudaran a descobrir tot el que necessites saber sobre les teves històries preferides, els seus escenaris i els seus creadors!',
    'homepage.reader.communityTitle': 'Uneix-te a la comunitat',
    'homepage.reader.communityDesc': 'Coneix persones de tot el món en fòrums dedicats a l\'univers i a l\'autor, blocs i altres funcionalitats de la comunitat on fans afins es reuneixen. Tot en un sol lloc.',
    'homepage.reader.readingFeatureTitle': 'Gaudeix d\'una experiència de lectura immersiva però pràctica',
    'homepage.reader.readingFeatureDesc': 'Des de històries i univers, gaudeix de la lectura sense esforç amb accés als detalls sense necessitat de canviar de pàgina.',
    'homepage.reader.readingExploreTitle': 'Explora tots els detalls de l\'univers',
    'homepage.reader.readingExploreDesc': 'L\'enciclopèdia de l\'univers et permet aprendre tots els detalls sobre l\'univers i submergir-te completament en les històries.',
    'homepage.reader.start': 'Comença a llegir',
    'homepage.writer.title': 'Mostra el teu univers i comparteix les teves històries',
    'homepage.writer.writingTitle': 'Escriure i crear mai ha estat tan fàcil',
    'homepage.writer.writingDesc': 'Experimenta la nova manera d\'escriure amb el Taller d\'Universos Literaris. Crea tots els detalls del teu univers en una enciclopèdia per compartir amb els teus lectors i escriu històries increïbles sobre aquesta base.',
    'homepage.writer.collaborationTitle': 'Creació col·laborativa',
    'homepage.writer.collaborationDesc': 'El procés creatiu sovint involucra diverses persones. No et preocupis, estem aquí per ajudar-te! Pots afegir fàcilment lectors beta, coautors i traductors a les teves històries i universos.',
    'homepage.writer.communityTitle': 'Connecta amb els teus lectors',
    'homepage.writer.communityDesc': 'Ves més enllà de l\'escriptura i connecta amb els teus lectors a través de blocs, fòrums i altres funcionalitats de la comunitat connectades als teus universos o a tu com a escriptor.',
    'homepage.writer.workshopFeatureTitle': 'Un sol lloc per a totes les teves necessitats creatives',
    'homepage.writer.workshopFeatureDesc': 'El nostre taller en constant evolució és el lloc central per a totes les teves necessitats creatives. Des d\'una simple idea, crea universos increïbles, històries i tot el que calgui al voltant.',
    'homepage.writer.monetizationFeatureTitle': 'Monetització',
    'homepage.writer.monetizationDesc': 'Creiem fermament que les persones haurien de ser remunerades pel seu treball i estem constantment buscant noves oportunitats de monetització per als escriptors. La funció de monetització permet als escriptors ser apreciats pel que fan. Explora totes les diferents opcions que permeten als teus fans mostrar-te el seu apreci.',
    'homepage.writer.start': 'Configura el teu taller!',
    'homepage.featureSelection': 'Descobreix aquests universos populars!',
    'about.title': 'Sobre l\'Univers Literari',
    'about.desc': 'Història, secrets i éssers humans darrere de l\'Univers Literari.',
    'about.text.1': 'L\'Univers Literari està dissenyat tant per a escriptors com per als lectors àvids. Els escriptors poden utilitzar el lloc per escriure obres originals mitjançant el botó de taller al menú del tauler. Això us donarà accés a l\'editor principal i a les funcions de l\'enciclopèdia, que es centren principalment en organitzar tots els aspectes de l\'univers de la vostra història personal en una sola pàgina. Els aspectes socials permeten als autors difondre la seva obra i desenvolupar un seguiment, així com interactuar de manera més directa si ho trien amb els seus lectors.',
    'about.text.2': 'Els lectors poden utilitzar el lloc principalment per llegir obres noves i seguir els autors, però també per ajudar a editar històries pre-publicades si se\'ls dóna permís per part de l\'escriptor. Ser lector a l\'Univers Literari és una experiència de lectura completament nova, tenir accés a tota la informació de fons a la mateixa pàgina que la història principal us dóna un coneixement de la ment de l\'autor com mai abans.',
    'about.text.3': 'El futur de l\'Univers Literari implica crear un mercat perquè els autors puguin vendre la seva obra i afegir funcionalitats comunitàries per millorar la comunicació entre autors i lectors a través de blocs i fòrums. Amb el temps, s\'afegiran eines per als escriptors, amb més d\'una dotzena actualment en desenvolupament o en el tauler. El nostre objectiu final és millorar les experiències dels escriptors i lectors mitjançant l\'ús més innovador del mitjà d\'internet.',
    'about.text.4': 'Esperem que us uneixeu a nosaltres mentre explorem el que el mitjà d\'internet pot fer per l\'escriptura creativa!',
    'about.team': 'L\'equip',
    'about.history': 'Història',
    'about.company': 'L\'empresa',
    'about.companyCountry.czechia': 'Txèquia',
    'about.companyCountry.japan': 'Japó',
    'about.companyCity.prague': 'Praga',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Director General',
    'about.CTO': 'Director de Tecnologia',
    'about.jan': 'Jan és el fundador, visionari i cervell tecnològic darrere de l\'Univers Literari. Com a escriptor d\'universos literaris extensos, Jan sempre havia trobat difícil escriure històries des d\'un punt de vista tècnic i de llegibilitat que no comprometessin l\'experiència de lectura. Per això, Jan va decidir estudiar desenvolupament web per crear una aplicació que facilités escriure històries en universos grans.',
    'about.history.text': 'El 2010, Jan va començar a l\'Institut Tecnològic de Rochester per aprendre més sobre el desenvolupament web per poder construir un lloc web de creació literària. Això es va materialitzar el 2013 quan es va presentar la primera prova de concepte a Imagine RIT. Jan va continuar els seus estudis i el 2016 es va crear una nova versió de l\'aplicació com a projecte de final de màster. El projecte va continuar a la tardor de 2016 i es va desenvolupar més fins al que veieu avui.',
    'copyrights.desc': 'El text complet de l\'Acord de Drets d\'Autor de l\'Univers Literari.',
    'privacy.desc': 'Text legal complet de la Política de Privadesa de l\'Univers Literari.',
    'guidelines.desc': 'Directrius de la Comunitat de l\'Univers Literari.',
    'tos.desc': 'Text legal complet dels Termes del Servei de l\'Univers Literari.',
    'homepage.intro': 'Deixa que la teva creativitat es desfaci per l\'univers literari',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'Has somiat mai en desenvolupar un món fictici tan detallat que fins i tot t\'hi perds? A Literary Universe, proporcionem les eines per fer realitat aquesta visió. Cada escriptor mereix tenir accés a recursos i suport de primera categoria. Per això, hem dissenyat un espai inclusiu que uneix la narració intricada i la lectura apassionada. Per als escriptors, és un espai de treball somiat; per als lectors, una odissea d\'exploració. Uneix-te a nosaltres mentre seguim el forat de conill literari per descobrir fins on ens porta en el món de la imaginació.',
    'gdpr.title': 'Compliment de GDPR',
    'gdpr.desc': 'Literary Universe compleix amb les directrius de la GDPR de la UE.',
    'gdpr.compliant': 'Literary Universe compleix amb la GDPR',
    'gdpr.compliant.text': 'Literary Universe ha implementat diverses actualitzacions i canvis al seu codi en preparació per a l\'aplicació de la GDPR el 25 de maig de 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Llei de Drets d\'Autor del Mil·lenni Digital',
    'common.legal.changelog': 'Canvis en aquesta versió',
    'dmca.title': 'Política de la Llei de Drets d\'Autor del Mil·lenni Digital (DMCA)',
    'dmca.subtitle': 'Política de Disputa de Drets d\'Autor',
    'dmca.step1.title': 'Procediment per informar sobre infraccions de drets d\'autor.',
    'dmca.step2.title': 'Un cop rebuda la notificació de vulneració de drets d\'autor adequada i de bona fe per part de l\'Agent Designat.',
    'dmca.step3.title': 'Procediment per presentar una contranotificació a l\'Agent Designat.',
    'dmca.desc': 'Ens prenem seriosament les violacions de drets d\'autor.',
    'gdpr.access.title': 'Dret d\'accés i dret a la portabilitat de les dades',
    'gdpr.access.desc': 'En la configuració de l\'usuari podeu exportar totes les vostres dades. Aquestes dades estaran en format JSON estàndard.',
    'gdpr.forget.title': 'Dret a ser oblidat',
    'gdpr.forget.desc': 'Qualsevol compte es pot eliminar mitjançant la configuració de l\'usuari. Algunes dades poden ser conservades, especialment si han estat objecte de venda i/o disputes.',
    'gdpr.rectification.title': 'Dret de rectificació',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'Dret de limitació del tractament',
    'gdpr.processing.desc': 'L\'Univers Literari respecta plenament les configuracions del navegador, com ara les sol·licituds "No fer seguiment", per informar al nostre servidor d\'estadístiques Matomo.',
    'gdpr.object.title': 'Dret d\'oposició',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'La informació es divideix en dos escenaris. 1. Propietat interna (infracció en el lloc de la propietat que existeix en el lloc). 2. Propietat externa (infracció en el lloc de la propietat que no existeix en el lloc).',
    'dmca.step1.desc2': 'La informació de la propietat interna es pot informar mitjançant el botó d\'informe de la propietat. Es pot informar de la infracció de la propietat externa mitjançant la pantalla de comentaris. En tots dos casos se us demanarà que proporcioneu dades personals i detalls addicionals que ens permetran comprovar la vostra propietat.',
    'dmca.step1.desc3': 'Cal tenir en compte que fer afirmacions falses resultarà en la impossibilitat de presentar reclamacions en el futur.',
    'dmca.step2.desc1': 'Un cop rebem el vostre informe, verificarem les vostres credencials i reclamació de propietat. Si tot està bé, procedirem a comprovar la reclamació. Si determinem que la reclamació és certa, farem que la propietat infractora sigui inaccessible fins a la determinació de la contranotificació o fins que hagin passat 14 dies, després dels quals es suprimirà.',
    'dmca.step3.desc1': 'Un cop rebuda una queixa, el propietari de la propietat designada tindrà 14 dies per presentar una notificació de contranotificació. L\'Agent Designat procedirà a investigar la disputa. Qualsevol decisió presa per l\'Agent Designat en aquesta etapa serà final.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Atribucions',
    'about.attributionsIntro': 'L\'univers literari es basa en molts projectes de codi obert i recursos gratuïts. A continuació trobaràs la seva llista.',
    'about.attributionsMatomo': 'Les nostres analítiques utilitzen Matomo auto-alojat amb dades de IP2Location LITE disponibles a https://lite.ip2location.com.',
    'team.name.pjakubec': 'Pavel Jakubec',
    'team.name.asebesta': 'Adam Šebesta',
    'about.developer': 'Desenvolupador',
    'about.seniorDeveloper': 'Desenvolupador Sènior',
    'about.juniorDeveloper': 'Desenvolupador Junior',
    'about.leadDesigner': 'Dissenyador principal',
    'about.leadUX': 'Dissenyador principal d\'experiència d\'usuari',
    'about.intern': 'Practicant',
    'about.advisor': 'Assessor',
    'about.headOfResearch': 'Cap de Recerca',
    'about.CFO': 'Director Financer',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry és un dissenyador amb més de 15 anys d\'experiència. Ha treballat en agències des de 2010, amb clients com PERTAMINA, VOA i el Ministeri de Turisme d\'Indonèsia. Amb experiència en branding, maquetació i també UI/UX, se sent desafiat a dissenyar Literary Universe.',
    'about.pavel': 'Web3, Metaverse, IA, tot això i qualsevol cosa nova és el que en Pavel investiga i com es pot afegir per millorar Literary Universe. Pavel, un investigador multidisciplinari de debò, té coneixements en moltes àrees i treballa per afegir noves funcionalitats interessants a Literary Universe.',
    'about.seba': 'Abans era un jugador, ara l\'Adam està estudiant per esdevenir un desenvolupador de ple dret.'
};