export default {
    'workshop.title': 'La teva feina',
    'workshop.noneassigned': 'Encara no se t\'ha assignat cap.',
    'workshop.notavailable': 'Aquesta funcionalitat encara no està disponible.',
    'workshop.none': `You currently have no {type, select,
      universe {universe}
      story {story}
      fanfiction {fan fiction}
      other {}
    }. Create one now!`,
    'workshop.collab': 'Treball col·laboratiu',
    'workshop.betareadings': 'Lectures beta',
    'workshop.translations': 'Traduccions',
    'workshop.createnew': 'Crear nova...',
    'workshop.story.standalone': 'Història independent',
    'workshop.story.standalone.desc': 'Aquesta és una història independent.',
    'workshop.controlpanel': '{name} panell de control',
    'workshop.universe.page': 'Pàgina de l\'univers',
    'workshop.fictionaltime': 'Hora fictícia',
    'workshop.dashboard.name': '{name} tauler de control',
    'workshop.stories.in': 'Històries en {universe}',
    'workshop.universe.nostories': 'No hi ha històries en aquest univers.',
    'workshop.story.chapter.add': 'Capítol nou',
    'workshop.universe.new': 'Crear un nou univers',
    'workshop.universe.publish': 'Publicar univers',
    'workshop.universe.publishing.notice': 'Si no publiqueu l\'univers, es publicarà automàticament quan es publiqui la primera història connectada a l\'univers.',
    'workshop.universe.settings': '{universe} configuració de l\'univers',
    'workshop.universe.publishedOn': 'Aquest univers ha estat publicat el {date, date, long} {date, time, short}',
    'workshop.universe.description': 'Descripció de l\'univers',
    'workshop.settings.title': 'Títol',
    'workshop.description': 'Descripció',
    'workshop.language.primary': 'Idioma principal',
    'workshop.publication.options': 'Opcions de publicació',
    'workshop.rating': 'Classificació general',
    'workshop.universe.rating.desc': 'Les històries i les fanfictions amb una classificació superior a aquesta estaran amagades de la pàgina de l\'univers per als usuaris anònims i els usuaris que no tinguin l\'edat adequada.',
    'workshop.universe.license': 'Llicència de l\'univers',
    'workshop.universe.genre.pick': 'Seleccioneu el gènere per a l\'univers',
    'workshop.story.genre.pick': 'Seleccioneu els gèneres per a la història',
    'workshop.cover': 'Portada',
    'workshop.nothingtosee': 'Res a veure aquí...',
    'workshop.story.cannon': 'Història canònica',
    'workshop.story.cannon.desc': 'Aquesta història és canònica en l\'univers {universe}',
    'workshop.story.cannon.desc.create': 'Aquesta història es crearà com a història canònica en l\'univers {universe} .',
    'workshop.story.fanfiction.search': 'Escriu el nom de l\'univers (ha d\'estar a la teva biblioteca). I després selecciona de les suggerències.',
    'workshop.story.error.nogenres': 'Has de seleccionar com a mínim un gènere.',
    'workshop.story.error.toomanygenres': 'Només es permeten dos gèneres per història.',
    'workshop.story.error.fanfiction.selectuniverse': 'Has de seleccionar un univers original per a la teva fan fiction!',
    'workshop.story.error.tags.toomany': 'Només pots tenir 10 etiquetes per història.',
    'workshop.story.new': 'Crea una nova història',
    'workshop.story.publishing.notice': 'La història es publicarà automàticament una vegada que publiquis el primer capítol.',
    'workshop.settings.edit': 'Edita la configuració',
    'workshop.story.publishedOn': 'Aquesta història ha estat publicada el {date, date, long} {date, time, short}',
    'workshop.story.settings': 'Configuració de la història',
    'workshop.settings.basic': 'Configuració bàsica',
    'workshop.settings.genres': 'Gèneres (màxim 2)',
    'workshop.story.license': 'Llicència de la història',
    'workshop.story.settings.universe': 'Configuració de l\'univers',
    'workshop.settings.tags': 'Etiquetes',
    'workshop.revision': 'Revisió',
    'workshop.revisions.title': '{story}: {chapter} Revisions',
    'workshop.revisions.current': 'Esborrany actual',
    'workshop.revisions.new.beta': 'Crea una nova revisió a partir de l\'esborrany.',
    'workshop.revisions.new.public': 'Crea una nova revisió pública a partir de l\'esborrany.',
    'workshop.revisions.toeditor': 'Vés a l\'editor',
    'workshop.revisions.comments': 'Comentaris de la revisió',
    'workshop.revisions.comments.title': '{story}: {chapter} - Revisió {revision} - Comentaris',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {for Beta readers}
      readers {Public}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'Has de crear primer una revisió.',
    'workshop.revisions.comments.select': 'Selecciona la revisió',
    'workshop.collaborators.noresults': 'Sense resultats',
    'workshop.collaborators.add.beta': 'Afegir lector beta',
    'workshop.collaborators.add.collaborator': 'Afegir col·laborador',
    'workshop.collaborators.add.translator': 'Afegir traductor',
    'workshop.collaborators.language.add': 'Crear una nova traducció',
    'workshop.translations.stories': 'Traduccions - històries',
    'workshop.translations.universes': 'Traduccions - universos',
    'workshop.revisions.beta.none': 'No hi ha revisions en aquest moment.',
    'reader.asidetoggle': 'Alternar informació lateral',
    'workshop.translation.original': 'Original:',
    'workshop.translation.original.title': 'Títol original:',
    'workshop.translation.original.description': 'Descripció original:',
    'workshop.translation.original.cover': 'Portada original',
    'workshop.translation.original.tags': 'Etiquetes originals',
    'workshop.cover.alt': 'imatge de portada',
    'workshop.translation.updatedOrig': 'Última actualització de l\'original: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'Última actualització de la traducció: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'Última revisió {revision, number}, de l\'original: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'Última revisió {revision, number}, de la traducció: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `Per afegir més {type, select,
    collaborator {col·laboradors}
    beta {lectors beta}
    translator {traductors}
    other {}
  }, necessites augmentar el teu nivell de membresia.`,
    'workshop.collaborators.requests.sent': 'Sol·licituds enviades',
    'workshop.collaborators.requests.invite': `Has estat convidat a ser {role, select,
    beta {lector beta}
    translator {traductor}
    collaborator {col·laborador}
    other {}
  } per a les següents coses:`,
    'workshop.collaborators.requests.dashboard': `Has estat convidat a col·laborar en {count, plural,
    zero {cap treball}
    one {una obra literària}
    other {# obres literàries}
  }.`,
    'workshop.collaborators.language.added': 'Idioma afegit',
    'workshop.story.noChaptersFound': 'Cap capítol trobat.',
    'workshop.fanfic.needUniverseInLibrary': 'Hi ha molts universos allà fora. Si us plau, afegiu primer els que voleu escriure a la vostra biblioteca perquè els puguem trobar.',
    'workshop.fanfic.findUniverse': 'Ves a trobar un univers increïble!',
    'workshop.encSettings': 'Configuració de l\'enciclopèdia',
    'workshop.collaborators.removeUser': 'Elimina l\'usuari',
    'workshop.collaborators.cancelInvite': 'Cancel·la la invitació',
    'workshop.universe.createFirstStory': 'Crea la primera història',
    'workshop.storylines': 'Trames de la història',
    'workshop.scenesManager': 'Gestor d\'escenes',
    'workshop.collaborators.addRoleForLang': 'Afegeix {role} per {language}',
    'workshop.beta.revisionInfo': 'Aquesta és la revisió {revision, number}, creada el {createdAt, date, long}.',
    'workshop.story.notes.title': 'Les teves notes per a {storyTitle}',
    'workshop.story.notes.desc': 'Notes generals per a la història.',
    'workshop.story.notes.tile': 'Notes generals',
    'workshop.hideOrgs': 'Amaga el contingut de les organitzacions',
    'workshop.translation.premium': 'Per afegir traduccions, has de tenir com a mínim una subscripció d\'Explorer.',
    'workshop.story.finished': 'Història completa',
    'workshop.story.publishing.externalSellingNotice': 'Com que estàs venent fora de Literary Universe, ara pots publicar la història. Els enllaços a la teva fitxa de botiga apareixeran a la història o al final de la història actual que publiquis aquí.',
    'workshop.sharing.publicURL': 'Versió pública',
    'workshop.fictionalTime.title': 'Temps ficticis per a {universeName}',
    'workshop.fictionalTime.none': 'Actualment no tens cap hora fictícia configurada.',
    'workshop.fictionalTime.createNow': 'Crea\'n una ara!',
    'workshop.fictionalTime.createTitle': 'Crea un nou temps fictici',
    'workshop.fictionalTime.editTitle': 'Edita {ftName}',
    'workshop.fictionalTime.formDescription': `Aquí pots crear el teu propi temps fictici. Actualment aquesta eina és limitada i només és capaç de crear temps simètrics
        . Això vol dir que no podràs recrear el calendari maia o el gregorià. En aquest moment,
        , aquesta eina espera que tots els temps siguin sempre iguals, per exemple, els mesos sempre tenen 30 dies sense excepcions i així
        . Abordarem aquesta qüestió en versions posteriors, però fins llavors aquesta eina és més adequada per crear principalment temps basats en la ciència ficció
.`,
    'workshop.fictionalTime.timeName': 'Nom del temps',
    'workshop.fictionalTime.basicInfo': 'Informació bàsica',
    'workshop.fictionalTime.timeSetup': 'Configuració del temps',
    'workshop.fictionalTime.linkedToET': 'Aquest temps comença en una data terrestre (calendari gregorià)?',
    'workshop.fictionalTime.timeDeclaration': 'Declaració del temps',
    'workshop.fictionalTime.declarationLocation': 'On s\'hauria de declarar el nom del temps?',
    'workshop.fictionalTime.declarationBefore': 'Abans de les unitats',
    'workshop.fictionalTime.declarationAfter': 'Després de les unitats',
    'workshop.fictionalTime.declarationNone': 'Cap',
    'workshop.fictionalTime.units': 'Unitats',
    'workshop.fictionalTime.ETStart': 'Data d\'inici d\'aquest temps',
    'workshop.fictionalTime.unitsDescFirst': 'Quantes unitats hi ha en aquesta unitat des de mil·lisegons?',
    'workshop.fictionalTime.unitsDesc': 'Quantes unitats hi ha en aquesta unitat respecte a l\'anterior?',
    'workshop.fictionalTime.unitsName': 'Nom de la unitat',
    'workshop.fictionalTime.unitsSeparator': 'Separador de la unitat anterior',
    'workshop.fictionalTime.unitAdd': 'Afegeix unitat',
    'workshop.fictionalTime.clocks': 'Relojs',
    'workshop.fictionalTime.unitTransfer': 'Unitats de transferència',
    'fictionalTime.pageStartElapsedTime': 'Temps transcorregut des de l\'obertura d\'aquesta pàgina',
    'fictionalTime.currentTime': 'Hora actual',
    'workshop.shoppingExternal.options': 'Opcions de compra externa',
    'workshop.shoppingExternal.explainer': 'Si la teva història es ven en altres llocs, pots establir els enllaços aquí. Els enllaços es mostraran en lloc del contingut o al final del contingut que triïs per previsualitzar.',
    'workshop.shoppingExternal.amazonStore': 'Botiga d\'Amazon',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Nom de la botiga',
    'workshop.shoppingExternal.itemUrl': 'URL de l\'article',
    'workshop.shoppingExternal.storesOther': 'Altres botigues',
    'fictionalTime.units.milliseconds': '{units, number} mil·lisegons',
    'fictionalTime.countdownToStart': 'Compte enrere per començar',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 dia }
      other {{days} dies }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {segon}
      other {segons}
    }}
    minutes {{units, plural,
      one {minut}
      other {minuts}
    }}
    hours {{units, plural,
      one {hora}
      other {hores}
    }}
    days {{units, plural,
      one {dia}
      other {dies}
    }}
    years {{units, plural,
      one {any}
      other {anys}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'Des de',
    'fictionalTime.inputSelectTimeUnit': 'Selecciona la unitat de temps',
    'fictionalTime.inputSelectETUnit': 'Selecciona la unitat de temps de la Terra',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Caixa d\'eines de la barra lateral',
    'workshop.writerSidebar.description': 'Benvingut a la teva història! Aquesta barra lateral et permet accedir fàcilment a tots els recursos relacionats amb la teva història. Comprova les icones de dalt per veure els últims comentaris, les teves notes i molt més!',
    'workshop.story.authorsNotesExplained': 'Les teves notes per als lectors per llegir al principi del capítol.',
    'workshop.story.chapterSortSwitch': 'Canvia l\'ordre del capítol',
    'workshop.universe.monetizationTitle': '{title} monetització',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} monetització',
    'workshop.universe.monetizationWebMonetization': 'Monetització web',
    'workshop.webMonetization.explain': 'Web Monetization enviarà pagaments a tu basats en el temps que l\'usuari passa al teu contingut. En la configuració de monetització del teu perfil, pots establir el teu propi punt de pagament. Aquí pots decidir una distribució amb els teus col·laboradors que tinguin Web Payment habilitat. Literary Universe automàticament es queda amb el 10%.',
    'workshop.webMonetization.revShare': 'Degut a les limitacions de la Monetització web, s\'utilitza una distribució de guanys probabilística. La distribució probabilística de guanys funciona escollint aleatòriament d\'una llista de punts de pagament predefinits cada vegada que un visitant amb monetització web carrega la teva pàgina. El visitant paga al punt escollit fins que la pàgina es recarrega o es tanca.',
    'workshop.webMonetization.revShareMore': 'Aprèn més sobre la Distribució de Guanys Probabilística. Utilitzem el mateix codi que a aquella pàgina.',
    'workshop.story.notEligible.licence': `La llicència de la història no permet la monetització.`,
    'workshop.universe.notEligible.licence': `La llicència de l'univers no permet la monetització.`,
    'workshop.story.notEligible.fanFiction': 'Les històries de Fan Fiction no són elegibles per a la monetització.',
    'workshop.revShare.mustBe100': 'La distribució ha de ser del 100%',
    'workshop.revShare.LUCut': 'Literary Universe i el portal de pagament',
    'workshop.revShare.unallocated': 'Distribució no assignada {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'Sense decidir',
    'workshop.revShare.origLangCreators': 'Creadors en l\'idioma original',
    'workshop.story.prolog': 'Pròleg',
    'workshop.story.chapter': 'Capítol {sequence, number}',
    'workshop.work.includesAds': 'Hi ha algun anunci o producte publicitari en la feina?',
    'workshop.universe.forumSettings': 'Configuració del fòrum de l\'univers intern',
    'workshop.universe.forum': 'Fòrum intern {universeName}',
    'workshop.ratingAdjusted': 'Due to complains we had to adjust your rating to the one that we felt appropriate. As such changing the rating is now disabled.',
    'workshop.selectCollaborator': 'Select collaborator',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Draft',
    'workshop.chapterStatus.scheduled': 'Scheduled',
    'workshop.chapterStatus.published': 'Published',
    'workshop.story.continuedIn': 'Which stories continue this story?',
    'workshop.story.continuedPlaceholder': 'Select story from this universe',
    'workshop.universe.isAIGenerated': 'Is the content of the universe generated by AI?',
    'workshop.universe.isAIGeneratedTooltip': 'Please let us know if any of the content in the universe was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.story.isAIGenerated': 'Is the story generated by AI?',
    'workshop.story.isAIGeneratedTooltip': 'Please let us know if any of the story was generated by or with the help of AI. We use this information for proper labeling and due to how AI programs are generated there might be some limitations and restrictions.',
    'workshop.publicationAgreement.aria': 'Publication agreement for work',
    'workshop.publicationAgreement.intro': 'We are happy that you have chosen to publish your creative work with us. Before we proceed we just need you to look over our publication agreement, to understand what it means from the legal side of things.',
    'workshop.sortChapters': 'Sort order:',
    'workshop.sortChapters.ascending': 'From beginning',
    'workshop.sortChapters.descending': 'From latest',
    'workshop.sortChapters.aria': 'Select for which way to sort chapter listing',
    'workshop.hiatus.btn': 'Change story status to Hiatus',
    'workshop.cancelled.btn': 'Change story status to Cancelled',
    'workshop.complete.btn': 'Change story status to Completed',
    'workshop.statusChange.modalTop': 'Are you sure you want to change the status to',
    'workshop.statusName.hiatus': 'Hiatus',
    'workshop.statusName.cancelled': 'Cancelled',
    'workshop.statusName.completed': 'Completed',
    'workshop.statusExplain.hiatus1': 'Hiatus means that you are stepping away from working on this story for a while for what ever reason. It will tell your readers that they should not expect any new updates in the coming weeks or even up to few months.',
    'workshop.statusExplain.hiatus2': 'The hiatus status will be automatically lifted if you publish any chapter. Or you can change it your self.',
    'workshop.statusExplain.hiatus3': 'If you keep your story in hiatus for six months, we will automatically mark this story as cancelled.',
    'workshop.statusExplain.cancelled1': 'We are sorry to hear that you can\'t continue working on the story. On the other hand we are happy that you are willing to let your readers know.',
    'workshop.statusExplain.cancelled2': 'Cancelling story will let your readers know that they should not expect any new updates.',
    'workshop.statusExplain.cancelled3': 'You can always revert this by publishing a chapter or changing the status.',
    'workshop.statusExplain.finished1': 'Congratulations! After all that hard work you have finally reached the end of an incredible journey. While the story might end now, we hope that there will be more stories to tell in the future, but for now, relax and enjoy the well earned rest.',
    'workshop.statusExplain.finished2': 'Marking story as complete will tell the readers that the story is finished. While you shouldn\'t be adding any new chapters we won\'t stop you and adding special chapters isn\'t a bad idea, to for example add more epilogues for all characters.',
    'workshop.statusExplain.finished3': 'While you can always cancel this status we highly advice against it. If the story is to continue it might be better to start a new story.',
    'workshop.status.goActive': 'Make the story active again',
    'workshop.statusChangeEmail.storyIntro': 'We would like to inform you that your story:',
    'workshop.statusChangeEmail.hiatusTitle': 'Your story status was automatically set to hiatus',
    'workshop.statusChangeEmail.hiatusIntro': 'Due to inactivity your story status was automatically set to hiatus.',
    'workshop.statusChangeEmail.hiatusWhy': 'Has been automatically put on hiatus due to no new chapter being published for over 6 months.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'This status will be automatically lifted if you publish a new chapter. If you don\'t publish a new chapter in the next 6 months we will automatically set the story as cancelled.',
    'workshop.statusChangeEmail.cancellationIntro': 'Your story status was automatically set to cancelled.',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. So after a year of inactivity we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'This status will be automatically lifted if you publish a new chapter. If you don\'t plan to work on this story anymore there is nothing else that you need to do.',
    'workshop.startCreating': 'Start creating',
    'workshop.ownWork': 'Own work',
    'workshop.list.thumbs': 'Thumbnails list',
    'workshop.list.list': 'Short list',
    'workshop.fanfiction.new': 'Create a new fan fiction'
};