export default {
  'courses.courses': 'Kurzy',
  'courses.overview': 'Přehled kurzů',
  'courses.public.title': 'Prozkoumat kurzy',
  'courses.public.heading': 'Prozkoumat kurzy',
  'courses.public.filters': 'Filtrování kurzů',
  'courses.public.noResults': 'Nebyly nalezeny žádné kurzy',
  'courses.public.tryDifferentFilters': 'Vyzkoušejte různé vyhledávací výrazy nebo filtry',
  'courses.filter.search': 'Vyhledávání kurzů...',
  'courses.filter.allTypes': 'Všechny typy',
  'courses.filter.clearAll': 'Vymazat vše',
  'courses.filter.type': 'Typ',
  'courses.type.course': 'Kurz',
  'courses.type.workshop': 'Workshop',
  'courses.type.seminar': 'Seminář',
  'courses.type.course.lowercase': 'Kurz',
  'courses.type.workshop.lowercase': 'Workshop',
  'courses.type.seminar.lowercase': 'Seminář',
  'course.create': 'Vytvořit nový kurz',
  'course.reading.title': 'Název čtenářského úkolu',
  'course.question.add': 'Přidat otázku',
  'course.lessons.newMessage': 'Vytvořte a organizujte své lekce pro efektivní výuku',
  'course.reading.new': 'Čtenářský úkol',
  'course.reading.newMessage': 'Vytvářejte a organizujte úkoly pro studenty.',
  'course.writing.new': 'Psaní úkolu',
  'course.writing.newMessage': 'Rychle nastavte a pošlete úkoly pro psaní',
  'course.question.text': 'Vaše otázka zde',
  'course.question.type': 'Vyberte typ otázky',
  'course.question.delete': 'Odstranit otázku',
  'course.type': 'Typ kurzu',
  'course.visibility': 'Vyberte možnost viditelnosti',
  'course.title': 'Název',
  'course.description': 'Popis',
  'course.cover': 'Obal',
  'course.start': 'Váš kurz začíná v',
  'course.ends': 'Váš kurz končí v',
  'course.curriculum': 'Osnovy',
  'course.members': 'Studenti a učitelé',
  'course.assignments': 'Úkoly',
  'course.question.deleteWhole': 'Smazat celou otázku',
  'course.question.yes': 'Ano',
  'course.question.no': 'Ne',
  'course.lesson.title': 'Název lekce',
  'course.lesson.add.universe': 'Přidat příběh/univerzum',
  'course.lesson.externalLinks': 'Externí odkazy',
  'course.lesson.add.link': 'Přidat externí odkaz',
  'course.status': 'Stav',
  'course.active': 'Aktivita',
  'course.active.message': 'Aktivní',
  'course.inactive': 'Neaktivní',
  'course.upload.resource': 'Nahrát zdroj',
  'course.question.answer': 'Přidat odpověď',
  'course.question.open': 'Otevřená otázka',
  'course.question.close': 'Uzavřená otázka',
  'course.question.multiple': 'Otázka s výběrem odpovědi',
  'course.about': 'O tomto kurzu',
  'course.lesson.new': 'Vytvořit novou lekci',
  'course.lesson.type': 'Typ lekce',
  'course.lesson.inPerson': 'Osobní',
  'course.lesson.preRecorded': 'Předzaznamenané',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Pouze text',
  'course.lesson.content': 'Obsah lekce',
  'course.lesson.description': 'Veřejný popis',
  'course.add.story': 'Přidat příběh',
  'course.remove.story': 'Odebrat příběh',
  'course.dateOfPublish': 'Datum zveřejnění',
  'course.lesson.meetInPerson': 'Osobní setkání',
  'course.curriculum.edit': 'Upravit osnovy',
  'course.stories.own': 'Vaše vlastní příběhy',
  'course.stories.organization': 'Příběhy v organizaci',
  'course.stories.public': 'Veřejné příběhy',
  'course.publish.at': 'Chci, aby byl tento kurz zveřejněn:',
  'course.edit.curriculum': 'Upravit osnovy',
  'course.assignment': 'Úkol',
  'course.lesson.removeLink': 'Odstranit odkaz',
  'course.user.remove': 'Odebrat uživatele',
  'course.user.invite': 'Pozvat uživatele',
  'course.user.invited': 'Pozvánka na',
  'course.edit.role': 'Edit role',
  'course.assignment.description': 'Popis úkolu',
  'course.internal': 'Interní',
  'course.free': 'Zdarma',
  'course.sale': 'Placený',
  'course.announcements': 'Oznámení',
  'course.announcements.full': 'Oznámení kurzu',
  'course.announcements.create': 'Vytvořit oznámení',
  'course.join': 'Připojit se ke kurzu',
  'course.joining': 'Připojení k...',
  'course.join.success': 'Úspěšně jste se přihlásili do tohoto kurzu!',
  'course.join.error.payment': 'Tento kurz vyžaduje platbu za účast.',
  'course.join.error.invite': 'Tento kurz vyžaduje pozvánku k účasti.',
  'course.join.error.generic': 'V kurzu došlo k chybě. Zkuste to prosím znovu.',
  'course.firstLesson': 'První lekce',
  'course.upcomingLessons': 'Nadcházející lekce',
  'course.detail.title': '{courseName} | Kurz',
  'lessons.visibility.public': 'Veřejnost',
  'lessons.visibility.private': 'Soukromé',
  'course.curriculum.empty': 'Zatím nejsou k dispozici žádné položky učebních osnov.',
  'course.preview.message': 'Toto je náhled kurzu. Chcete-li získat přístup k celému obsahu, přihlaste se do kurzu.',
  'course.details': 'Podrobnosti o kurzu',
  'course.tab.curriculum': 'Kurikulum',
  'course.tab.details': 'Podrobnosti o kurzu',
  'course.duration': 'Doba trvání',
  'course.perpetual': 'Věčné',
  'course.language': 'Jazyk',
  'course.price': 'Cena',
  'course.learningObjectives': 'Cíle učení',
  'course.prerequisites': 'Předpoklady',
  'course.tags': 'Štítky',
  'course.stats.members': 'Členové',
  'course.stats.lessons': 'Lekce',
  'course.assignments.comingSoon': 'Zobrazení úkolů se brzy objeví.',
  'course.progress.comingSoon': 'Sledování pokroku se brzy objeví.',
  'course.type.free': 'Zdarma',
  'course.type.paid': 'Placené',
  'course.type.forSale': 'Na prodej',
  'course.type.invite': 'Pouze pro zvané',
  'courses.invites.tile': 'Zveme vás k účasti na {count, plural, one {kurzu} other {kurzech}}.',
  'courses.invites.noInvites': 'V současné době nemáte žádné pozvánky na kurzy.',
  'courses.invites.invitedBy': 'Pozvání přijal: ',
  'course.join.heading': 'Připojte se k tomuto kurzu',
  'course.oneTimePayment': 'Jednorázová platba za plný přístup',
  'course.member': 'Jste zapsáni',
  'course.member.access': 'Máte plný přístup ke všem materiálům kurzu.',
  'courses.members.editRole': 'Upravit roli',
  'courses.members.editRoleFor': 'Upravit roli pro:',
  'courses.add.member': 'Přidání nového člena',
  'course.member.options': 'Seznam členů kurzu',
  'course.navigation.curriculum': 'Kurikulum',
  'course.navigation.members': 'Studenti a učitelé',
  'course.navigation.assignments': 'Zadání',
  'course.navigation.forums': 'Fóra',
  'course.navigation.attendance': 'Docházka',
  'course.members.teachers': 'Učitelé',
  'course.members.students': 'Studenti',
  'course.members.preview.message':
    'Zapojte se do tohoto kurzu, abyste viděli všechny studenty a komunikovali s komunitou.',
  'course.member.role.owner': 'Majitel',
  'course.member.role.teacher': 'Učitel',
  'course.member.role.student': 'Student',
  'course.lesson.internalLinks': 'Díla na Literary Universe',
  'course.lesson.internalLinks.description':
    'Vyber příběhy nebo vesmíry pro propojení s touto lekcí. Ty budou studentům k dispozici jako další zdroje.',
  'course.startDate': 'Datum zahájení',
  'course.endDate': 'Datum ukončení',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Náhled učebních osnov',
  'course.curriculum.preview.message':
    'Připojte se k tomuto kurzu a získejte přístup ke všem lekcím a úkolům na {count} .',
  'course.curriculum.locked': 'Uzamčené stránky',
  'course.curriculum.lesson': 'Lekce',
  'course.curriculum.assignment': 'Zadání',
  'course.curriculum.reading': 'Čtení',
  'course.lesson.backToCurriculum': 'Zpět na učební plán',
  'course.lesson.nextLesson': 'Další lekce',
  'course.lesson.documents': 'Dokumenty a zdroje',
  'course.lesson.meetingLink': 'Odkaz na setkání',
  'course.lesson.location': 'Umístění',
  'course.lesson.virtualClassroom': 'Virtuální třída',
  'course.lesson.joinClassroom': 'Připojte se k virtuální třídě',
  'course.lesson.enterClassroom': 'Vstup do učebny',
  'course.assignment.acceptsStories': 'Přijímá příběhy',
  'course.assignment.acceptsUniverses': 'Přijímá vesmíry',
  'course.assignment.backToAssignments': 'Zpět na úkoly',
  'course.assignment.criteria': 'Kritéria pro čtení',
  'course.assignment.dueDate': 'Termín: {date}',
  'course.assignment.freeReading': 'Volné čtení povoleno',
  'course.assignment.grade': 'Třída',
  'course.assignment.grade.received': 'Třída: {grade}',
  'course.assignment.gradeSaveError': 'Nelze uložit známku',
  'course.assignment.gradeSaved': 'Uložená třída.',
  'course.assignment.gradedCount': '{count, plural, one {# graded} other {# graded}}',
  'course.assignment.grading.help':
    'Prohlédněte si příspěvky studentů, otevřete propojené příběhy nebo vesmíry a přidejte volitelnou známku a zpětnou vazbu.',
  'course.assignment.grading.title': 'Známkování: {title}',
  'course.assignment.grading.unavailable': 'Třídění není k dispozici',
  'course.assignment.grading.unavailableMessage':
    'Nemáte přístup k této stránce pro hodnocení nebo se úkol nepodařilo najít.',
  'course.assignment.lastRead': 'Poslední čtení {date}',
  'course.assignment.minutes': '{count} min',
  'course.assignment.noSubmissions': 'Zatím žádné příspěvky.',
  'course.assignment.noWrittenResponse': 'Písemná odpověď nebyla poskytnuta.',
  'course.assignment.notFound': 'Zadání nebylo nalezeno',
  'course.assignment.notFoundMessage': 'Požadované přiřazení nebylo nalezeno.',
  'course.assignment.noteForTeacher': 'Přidejte poznámku pro učitele',
  'course.assignment.open': 'Otevřené zadání',
  'course.assignment.openGrading': 'Otevřít stránku s tříděním',
  'course.assignment.questions': 'Otázky',
  'course.assignment.readingProgress': 'Pokrok žáků ve čtení',
  'course.assignment.readings': 'Zadaná četba',
  'course.assignment.responsePlaceholder': 'Zde napište svou odpověď',
  'course.assignment.responsePrompt': 'Téma eseje nebo výzva do časopisu',
  'course.assignment.selectStoriesRead': 'Vyberte příběhy, které jste si vybrali pro tento úkol.',
  'course.assignment.sharedProject.studentHelp':
    'Otevřete jednu z výše uvedených sdílených projektových prací v aplikaci Workshop a přispějte do ní. Tento úkol nevyžaduje samostatný formulář pro odevzdání.',
  'course.assignment.sharedProject.studentTitle': 'Jak dokončit tento úkol',
  'course.assignment.sharedProject.teacherNotice':
    'Tento úkol sdíleného projektu využívá přístup spolupracovníků namísto individuálního zadávání.',
  'course.assignment.sharedProjects': 'Sdílené projektové práce',
  'course.assignment.storiesCompleted': 'dokončené příběhy',
  'course.assignment.submissionCount': '{count, plural, one {# submission} other {# submissions}}',
  'course.assignment.submissionSaved': 'Uložené podání.',
  'course.assignment.submissions': 'Předkládání a klasifikace',
  'course.assignment.submit': 'Odeslání úkolu',
  'course.assignment.submitError': 'Nelze odeslat úkol',
  'course.assignment.submitWork': 'Vyberte práci, kterou chcete odeslat',
  'course.assignment.submitWork.help': 'Vyberte si příběh nebo vesmír, který by měl být hodnocen v rámci tohoto úkolu.',
  'course.assignment.submitWork.label': 'Předložená práce',
  'course.assignment.submitWork.placeholder': 'Vyberte příběh nebo vesmír',
  'course.assignment.submittedAt': 'Odesláno na {date}',
  'course.assignment.submittedWork.story': 'Předložený příběh: {title}',
  'course.assignment.submittedWork.universe': 'Předložený vesmír: {title}',
  'course.assignment.supportingFiles': 'Nahrané podkladové materiály',
  'course.assignment.supportingMaterials': 'Podpůrné materiály',
  'course.assignment.updateSubmission': 'Předkládání aktualizací',
  'course.assignment.yourSubmission': 'Vaše podání',
  'courses.role.owner': 'Majitel',
  'courses.role.teacher': 'Učitel',
  'courses.role.student': 'Student',
};
