export default {
  'courses.courses': 'Kurzy',
  'courses.overview': 'Přehled kurzů',
  'courses.public.title': 'Prozkoumat kurzy',
  'courses.public.heading': 'Prozkoumat kurzy',
  'courses.public.filters': 'Filtrování kurzů',
  'courses.public.noResults': 'Nebyly nalezeny žádné kurzy',
  'courses.public.tryDifferentFilters': 'Vyzkoušejte různé vyhledávací výrazy nebo filtry',
  'courses.filter.search': 'Vyhledávání kurzů...',
  'courses.filter.allTypes': 'Všechny typy',
  'courses.filter.clearAll': 'Vymazat vše',
  'courses.type.course': 'Kurz',
  'courses.type.workshop': 'Workshop',
  'courses.type.seminar': 'Seminář',
  'courses.type.course.lowercase': 'Kurz',
  'courses.type.workshop.lowercase': 'Workshop',
  'courses.type.seminar.lowercase': 'Seminář',
  'course.create': 'Vytvořit nový kurz',
  'course.reading.title': 'Název čtenářského úkolu',
  'course.question.add': 'Přidat otázku',
  'course.add.courseElement': 'Přidání nového prvku kurzu',
  'course.lessons.newMessage': 'Vytvořte a organizujte své lekce pro efektivní výuku',
  'course.reading.new': 'Čtenářský úkol',
  'course.reading.newMessage': 'Vytvářejte a organizujte úkoly pro studenty.',
  'course.writing.new': 'Psaní úkolu',
  'course.writing.newMessage': 'Rychle nastavte a pošlete úkoly pro psaní',
  'course.question.text': 'Vaše otázka zde',
  'course.question.type': 'Vyberte typ otázky',
  'course.question.delete': 'Odstranit otázku',
  'course.type': 'Vyberte typ kurzu',
  'course.visibility': 'Vyberte možnost viditelnosti',
  'course.title': 'Název',
  'course.description': 'Popis',
  'course.cover': 'Obal',
  'course.start': 'Váš kurz začíná v',
  'course.ends': 'Váš kurz končí v',
  'course.curriculum': 'Osnovy',
  'course.members': 'Studenti a učitelé',
  'course.assignments': 'Úkoly',
  'course.question.deleteWhole': 'Smazat celou otázku',
  'course.question.yes': 'Ano',
  'course.question.no': 'Ne',
  'course.lesson.title': 'Název lekce',
  'course.lesson.add.universe': 'Přidat příběh/univerzum',
  'course.lesson.externalLinks': 'Externí odkazy',
  'course.lesson.add.link': 'Přidat externí odkaz',
  'course.status': 'Stav',
  'course.active': 'Aktivita',
  'course.active.message': 'Aktivní',
  'course.inactive': 'Neaktivní',
  'course.module.edit': 'Upravit název modulu',
  'course.upload.resource': 'Nahrát zdroj',
  'course.question.answer': 'Přidat odpověď',
  'course.question.open': 'Otevřená otázka',
  'course.question.close': 'Uzavřená otázka',
  'course.question.multiple': 'Otázka s výběrem odpovědi',
  'course.about': 'O tomto kurzu',
  'course.lesson.new': 'Vytvořit novou lekci',
  'course.lesson.type': 'Typ lekce',
  'course.lesson.inPerson': 'Osobní',
  'course.lesson.preRecorded': 'Předzaznamenané',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Pouze text',
  'course.lesson.content': 'Obsah lekce',
  'course.lesson.description': 'Veřejný popis',
  'course.add.module': 'Přidat nový modul',
  'course.add.story': 'Přidat příběh',
  'course.remove.story': 'Odebrat příběh',
  'course.dateOfPublish': 'Datum zveřejnění',
  'course.lesson.meetInPerson': 'Osobní setkání',
  'course.curriculum.edit': 'Upravit osnovy',
  'course.stories.own': 'Vaše vlastní příběhy',
  'course.stories.organization': 'Příběhy v organizaci',
  'course.stories.public': 'Veřejné příběhy',
  'course.publish.at': 'Chci, aby byl tento kurz zveřejněn:',
  'course.edit.curriculum': 'Upravit osnovy',
  'course.assignment': 'Úkol',
  'course.lesson.removeLink': 'Odstranit odkaz',
  'course.user.remove': 'Odebrat uživatele',
  'course.user.invite': 'Pozvat uživatele',
  'course.user.invited': 'Pozvánka na',
  'course.edit.role': 'Edit role',
  'course.assignment.description': 'Popis úkolu',
  'course.internal': 'Interní',
  'course.free': 'Zdarma',
  'course.sale': 'Placený',
  'course.announcements': 'Oznámení',
  'course.announcements.full': 'Oznámení kurzu',
  'course.announcements.create': 'Vytvořit oznámení',
  'course.join': 'Připojit se ke kurzu',
  'course.firstLesson': 'První lekce',
  'course.upcomingLessons': 'Nadcházející lekce',
  'course.detail.title': '{courseName} | Kurz',
  'lessons.visibility.public': 'Veřejnost',
  'lessons.visibility.private': 'Soukromé',
  'lessons.visibility.hidden': 'Skryté stránky',
  'courses.members.search.placeholder': 'Vyhledávání uživatelů...',
  'course.search.user': 'Vyhledávání uživatele',
  'course.user.addFinished': 'Dokončeno',
  // Course invites
  'courses.invites.title': 'Pozvánky na kurzy',
  'courses.invites.heading': 'Pozvánky na kurzy',
  'courses.invites.tile': 'Zveme vás k účasti na {count, plural, one {kurzu} other {kurzech}}.',
  'courses.invites.noInvites': 'V současné době nemáte žádné pozvánky na kurzy.',
  'courses.invites.invitedBy': 'Pozvání přijal: ',
  'courses.invites.accept': 'Přijmout',
  'courses.invites.reject': 'Odmítnout',
  'courses.role.owner': 'Majitel',
  'courses.role.teacher': 'Učitel',
  'courses.role.student': 'Student',
  'course.lesson.internalLinks': 'Díla na Literary Universe',
  'course.lesson.internalLinks.description':
    'Vyber příběhy nebo vesmíry pro propojení s touto lekcí. Ty budou studentům k dispozici jako další zdroje.',
  'contentSelector.noSelection': 'Nic nebylo vybráno',
  'contentSelector.selectedItems': 'Vybrané položky',
  'contentSelector.entireSite': 'Celá platforma',
  'contentSelector.myLibrary': 'Moje knihovna',
  'contentSelector.tabsLabel': 'Možnosti vyhledávání',
  'contentSelector.title': 'Vybrat obsah',
  'course.startDate': 'Datum zahájení',
  'course.endDate': 'Datum ukončení',
};
