export default {
    'encyclopedia.add': 'Přidat nový záznam',
    'encyclopedia.browse': 'Procházet encyklopedii',
    'encyclopedia.search': 'Vyhledat v encyklopedii',
    'canvas.toolbar.add': 'Add:',
    'canvas.toolbar.text': 'Text',
    'canvas.toolbar.link': 'Link',
    'canvas.toolbar.group': 'Group',
    'canvas.toolbar.entry': 'Entry',
    'canvas.encPicker.title': 'Pick an encyclopedia entry',
    'canvas.encPicker.search': 'Search entries…',
    'canvas.dialog.pickEntry': 'Pick encyclopedia entry',
    'canvas.node.link': 'Link',
    'canvas.node.encEntry': 'Entry',
    'canvas.entry.open': 'Double-click to open entry',
    'encyclopedia.back.universe': 'Zpět na stránku vesmíru',
    'encyclopedia.back.workshop': 'Zpátky do dílny',
    'encyclopedia.categories': 'Kategorie',
    'encyclopedia.groups': 'Skupiny',
    'encyclopedia.category.character': 'Postava',
    'encyclopedia.category.event': 'Událost',
    'encyclopedia.category.group': 'Skupina',
    'encyclopedia.category.item': 'Věc',
    'encyclopedia.category.location': 'Lokalita',
    'encyclopedia.category.other': 'Ostatní',
    'encyclopedia.category.state': 'Národ',
    'encyclopedia.category.governments': 'Stát',
    'encyclopedia.category.languages': 'Jazyk',
    'encyclopedia.category.creatures': 'Bytost',
    'encyclopedia.category.deity': 'Božstvo',
    'encyclopedia.category.religions': 'Náboženství',
    'encyclopedia.category.flora': 'Flora',
    'encyclopedia.category.magic': 'Magie',
    'encyclopedia.category.planets': 'Planeta',
    'encyclopedia.category.species': 'Rasa',
    'encyclopedia.category.technologies': 'Technologie',
    'encyclopedia.category.families': 'Rodiny',
    'encyclopedia.category.jobs': 'Nabídky práce:',
    'encyclopedia.category.lore': 'Lore',
    'encyclopedia.category.vehicles': 'Vozidla',
    'encyclopedia.category.diseases': 'Nemoci',
    'encyclopedia.category.traditions': 'Tradice',
    'encyclopedia.category.sports': 'Sport',
    'encyclopedia.category.food': 'Potraviny',
    'encyclopedia.category.landmarks': 'Památky',
    'encyclopedia.category.buildings': 'Budovy',
    'encyclopedia.category.schools': 'Školy',
    'encyclopedia.category.continents': 'Kontinenty',
    'encyclopedia.category.villages': 'Vesnice',
    'encyclopedia.category.towns': 'Městečko',
    'encyclopedia.category.cities': 'Města',
    'encyclopedia.category.settlements': 'Vypořádání',
    'encyclopedia.category.countries': 'Země',
    'encyclopedia.search.found': '{results, plural,\n    =0 {No related entries}\n    one {1 related entry}\n    other {# related entries}\n  } found.',
    'encyclopedia.help.text': 'Pomocí menu vlevo se můžete pohybovat mezi položkami v encyklopedii. Jakmile vyberete položku, zobrazí se místo tohoto textu.',
    'encyclopedia.help.sidebar': 'Postranní nástroje',
    'encyclopedia.help.sidebar.text': 'Vítejte ve svém příběhu! Tento postranní panel vám umožní snadný přístup ke všem zdrojům souvisejícím s vaším příběhem. Zaškrtnutím výše uvedených ikon zobrazíte nejnovější komentáře, své poznámky, můžete vyhledávat ve své encyklopedii, procházet ji a přidávat do ní nové záznamy. Pokud chcete přidat spojení k záznamu z textu příběhu, vyberte text, kam jej chcete umístit, a poté klikněte na tlačítko připojit. Poté budete vyzváni k vyhledání a výběru položky.',
    'encyclopedia.intro': 'Vítejte v encyklopedii pro {universe}.',
    'encyclopedia.add.title': 'Přidat nový záznam do encyklopedie',
    'encyclopedia.add.heading': 'Co chcete přidat?',
    'encyclopedia.add.moresoon': 'Více kategorií již brzy!',
    'encyclopedia.create': 'Vytvořit nový {category, select,\n    character {postava}\n    event {událost}\n    group {skupina}\n    item {předmět}\n    location {místo}\n    other {poznámka}\n    state {stát}\n    governments {vláda}\n    languages {jazyk}\n    creatures {tvor}\n    deity {božstvo}\n    religions {náboženství}\n    flora {flóra}\n    magic {magie}\n    planets {planeta}\n    species {druh}\n    technologies {technologie}\n    families {rodina}\n    jobs {zaměstnání}\n    lore {pověsti}\n    vehicles {vozidlo}\n    diseases {nemoc}\n    traditions {tradice}\n    food {jídlo}\n    sports {sport}\n    landmarks {památka}\n    buildings {budova}\n    schools {škola}\n    continents {kontinent}\n    villages {vesnice}\n    towns {města}\n    cities {města}\n    settlements {osada}\n    countries {země}\n  }',
    'encyclopedia.create.header': 'Creating a new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {village}\n    towns {town}\n    cities {city}\n    settlements {settlement}\n    countries {country}\n  } in {universe}',
    'encyclopedia.entry.category': 'Kategorie přihlášek: {category, select,\n    character {Postava}\n    event {Událost}\n    group {Skupina}\n    item {Předmět}\n    location {Místo}\n    other {Poznámka}\n    state {Stát}\n    governments {Vláda}\n    languages {Jazyk}\n    creatures {Tvor}\n    deity {Božstvo}\n    religions {Náboženství}\n    flora {Flóra}\n    magic {Magie}\n    planets {Planeta}\n    species {Druh}\n    technologies {Technologie}\n    families {Rodina}\n    jobs {Práce}\n    lore {Pověst}\n    vehicles {Vozidlo}\n    diseases {Nemoc}\n    traditions {Tradice}\n    food {Jídlo}\n    sports {Sport}\n    landmarks {Pamětihodnost}\n    buildings {Budova}\n    schools {Škola}\n    continents {Kontinent}\n    villages {Vesnice}\n    towns {Město}\n    cities {Město}\n    settlements {Osada}\n    countries {Země}\n  }',
    'encyclopedia.entry.category.legend': 'Kategorie',
    'encyclopedia.fields.add': 'Přidat nové pole',
    'encyclopedia.fields.text': 'Definice',
    'encyclopedia.fields.textarea': 'Text',
    'encyclopedia.fields.connection': 'Spojení',
    'encyclopedia.fields.time': 'Čas',
    'encyclopedia.fields.image': 'Obrázek',
    'encyclopedia.fields.canvas': 'Canvas',
    'encyclopedia.visibility': 'Viditelnost',
    'encyclopedia.public': 'Veřejné',
    'encyclopedia.private': 'Soukromé',
    'encyclopedia.container': 'Kontejner',
    'encyclopedia.container.desc': 'Vytvořte z této položky kontejner pro novou skupinu položek. Tím se skryje z výpisu kategorií.',
    'encyclopedia.entry.name': 'Jméno záznamu',
    'encyclopedia.summary': 'Shrnutí',
    'encyclopedia.summary.desc': 'Jedná se o shrnutí, které bude jedinou úvodní informací zobrazenou čtenáři.',
    'encyclopedia.parent': 'Nadřazený záznam',
    'encyclopedia.related': 'Související záznamy',
    'encyclopedia.errors.tags': 'Můžete mít pouze 10 značek na záznam.',
    'encyclopedia.field.private': 'Soukromé pole',
    'encyclopedia.ft.indev': 'Tato funkce je ve vývoji.',
    'encyclopedia.connections.remove': 'Odstranit spojení',
    'encyclopedia.connections.extra': 'Další informace',
    'encyclopedia.connections.existing': 'Existující záznam',
    'encyclopedia.connections.existing.abbr': 'EZ',
    'encyclopedia.cover': 'Obrázek záznamu',
    'encyclopedia.translation.title': 'Vítejte v překladu pro {universe}!',
    'encyclopedia.translation.desc': 'Toto rozhraní encyklopedie se používá pro překlad do {language}. Chcete-li začít překládat, vyberte existující položky v levém menu.',
    'encyclopedia.welcome.totalEntries': 'There {totalEntries, plural, \n    zero {are no entries}\n    one {is one entry}\n    other {are # entries}\n  } in this universe.',
    'encyclopedia.settings.title': 'Nastavení Encyklopedie',
    'encyclopedia.settings.categoriesDesc': 'Zapněte a vypněte kategorie, které chcete použít v encyklopedii.',
    'encyclopedia.settings.introText': 'Uvítací zpráva, která bude zobrazena hned po popisku vesmíru.',
    'encyclopedia.fields.placeholder': 'Jméno pole',
    'encyclopedia.fields.delete': 'Odstranit pole',
    'encyclopedia.timeOption.fictionalDate': 'Fiktivní datum',
    'encyclopedia.timeOption.fictionalTime': 'Fiktivní čas',
    'encyclopedia.timeOption.fictionalDateTime': 'Fiktivní datum a čas',
    'encyclopedia.timeOption.date': 'Datum',
    'encyclopedia.timeOption.time': 'Čas',
    'encyclopedia.timeOption.dateTime': 'Datum a čas',
    'encyclopedia.settings.groupByCategories': 'Zahrnout kategorie do seznamu',
    'encyclopedia.menuOpen': 'Otevřít menu encyclopedie',
    'encyclopedia.menuClose': 'Zavřít menu encyclopedie',
    'encyclopedia.menuAria': 'Menu encyklopedie',
    'enc.newField': 'Nové pole',
    'enc.entries.limit': 'You currently have {value, number} out of {max, plural,\n    =0 {unlimited}\n    other {{max, number}}\n  } entries.',
    'enc.entries.limitReached': 'Dosáhli jste maximálního povoleného počtu položek pro aktuální předplatné.',
    'encyclopedia.pronunciation.title': 'Výslovnost',
    'encyclopedia.wip.abbreviation': 'WIP',
    'encyclopedia.wip.full': 'Rozpracované',
    'encyclopedia.settings.templateLegend': 'Šablona vesmíru',
    'encyclopedia.settings.templateDescription': 'Povolit kopírování obsahu této encyklopedie do jiných vesmírů. Toto je nejlepší volba, pokud nemáte žádné příběhy a místo toho jen vytváříte šablonu pro ostatní.',
    'encyclopedia.settings.templateCheckbox': 'Toto je šablona vesmíru',
    'encyclopedia.templateCopy.modalTitle': 'Kopírovat obsah encyklopedie',
    'encyclopedia.templateCopy.description': 'Zkopírujte obsah této encyklopedie do svého vesmíru, aby jste ho obohatili.',
    'encyclopedia.templateCopy.targetUniverse': 'Vesmír, do kterého se má zkopírovat',
    'encyclopedia.templateCopy.finished': 'Kopírování dokončeno',
    'encyclopedia.templateCreateUniverse.modalTitle': 'Vytvoření vesmíru ze šablony',
    'encyclopedia.templateCreateUniverse.description': 'Vytvoření nového vesmíru s přednastaveným obsahem encyklopedie z této šablony. Váš vesmír zůstane soukromý, dokud se nerozhodnete jej zveřejnit.',
    'encyclopedia.templateCreateUniverse.success': 'Vesmír úspěšně vytvořen! Přesměrování...',
    'encyclopedia.pronunciation.audio.play': 'Přehrát výslovnost',
    'encyclopedia.pronunciation.guide': 'Pokud je to možné, používejte <ipaLink>zápis IPA</ipaLink>. Výslovnost Web Speech API je nejlepší; viz <webSpeechLink>dokumentaci MDN</webSpeechLink>.',
    'encyclopedia.templateField.born': 'Born',
    'encyclopedia.templateField.died': 'Died',
    'encyclopedia.templateField.race': 'Race',
    'encyclopedia.templateField.gender': 'Gender',
    'encyclopedia.templateField.partners': 'Partners',
    'encyclopedia.templateField.parents': 'Parents',
    'encyclopedia.templateField.children': 'Children',
    'encyclopedia.templateField.associated-with': 'Associated with',
    'encyclopedia.templateField.biography': 'Biography',
    'encyclopedia.templateField.physical-appearance': 'Physical appearance',
    'encyclopedia.templateField.type-of-event': 'Type of event',
    'encyclopedia.templateField.preceding-events': 'Preceding events',
    'encyclopedia.templateField.following-events': 'Following events',
    'encyclopedia.templateField.leadup': 'Leadup',
    'encyclopedia.templateField.description': 'Description',
    'encyclopedia.templateField.aftermath': 'Aftermath',
    'encyclopedia.templateField.members': 'Members',
    'encyclopedia.templateField.locations': 'Locations',
    'encyclopedia.templateField.events': 'Events',
    'encyclopedia.templateField.vision': 'Vision',
    'encyclopedia.templateField.mission': 'Mission',
    'encyclopedia.templateField.description-of-the-organization': 'Description of the organization',
    'encyclopedia.templateField.history': 'History',
    'encyclopedia.templateField.owners': 'Owners',
    'encyclopedia.templateField.function': 'Function',
    'encyclopedia.templateField.content': 'Content',
    'encyclopedia.templateField.population': 'Population',
    'encyclopedia.templateField.culture': 'Culture',
    'encyclopedia.templateField.governments': 'Governments',
    'encyclopedia.templateField.religions-believes': 'Religions & believes',
    'encyclopedia.templateField.languages': 'Languages',
    'encyclopedia.templateField.geography': 'Geography',
    'encyclopedia.templateField.founding': 'Founding',
    'encyclopedia.templateField.notable-events': 'Notable events',
    'encyclopedia.templateField.notes': 'Notes',
    'encyclopedia.templateField.type-of-government': 'Type of government',
    'encyclopedia.templateField.structure': 'Structure',
    'encyclopedia.templateField.power-structure': 'Power structure',
    'encyclopedia.templateField.source-of-power': 'Source of power',
    'encyclopedia.templateField.laws': 'Laws',
    'encyclopedia.templateField.ideology': 'Ideology',
    'encyclopedia.templateField.internal-politics': 'Internal politics',
    'encyclopedia.templateField.external-politics': 'External politics',
    'encyclopedia.templateField.leading-figures': 'Leading figures',
    'encyclopedia.templateField.groups': 'Groups',
    'encyclopedia.templateField.military': 'Military',
    'encyclopedia.templateField.items': 'Items',
    'encyclopedia.templateField.typology': 'Typology',
    'encyclopedia.templateField.dialectics': 'Dialectics',
    'encyclopedia.templateField.phonology': 'Phonology',
    'encyclopedia.templateField.grammar': 'Grammar',
    'encyclopedia.templateField.numbers': 'Numbers',
    'encyclopedia.templateField.quantifiers': 'Quantifiers',
    'encyclopedia.templateField.private-notes': 'Private notes',
    'encyclopedia.templateField.type': 'Type',
    'encyclopedia.templateField.notable-features': 'Notable features',
    'encyclopedia.templateField.traits': 'Traits',
    'encyclopedia.templateField.habitat': 'Habitat',
    'encyclopedia.templateField.food-sources': 'Food sources',
    'encyclopedia.templateField.reproduction': 'Reproduction',
    'encyclopedia.templateField.cultural-significance': 'Cultural significance',
    'encyclopedia.templateField.related-creatures': 'Related creatures',
    'encyclopedia.templateField.religion': 'Religion',
    'encyclopedia.templateField.other-names': 'Other names',
    'encyclopedia.templateField.appearance': 'Appearance',
    'encyclopedia.templateField.related-to': 'Related to',
    'encyclopedia.templateField.symbolism': 'Symbolism',
    'encyclopedia.templateField.rituals': 'Rituals',
    'encyclopedia.templateField.origin': 'Origin',
    'encyclopedia.templateField.notable-figures': 'Notable figures',
    'encyclopedia.templateField.deities': 'Deities',
    'encyclopedia.templateField.artifacts': 'Artifacts',
    'encyclopedia.templateField.believes': 'Believes',
    'encyclopedia.templateField.traditions': 'Traditions',
    'encyclopedia.templateField.spread': 'Spread',
    'encyclopedia.templateField.classification': 'Classification',
    'encyclopedia.templateField.features': 'Features',
    'encyclopedia.templateField.produce': 'Produce',
    'encyclopedia.templateField.ecosystem': 'Ecosystem',
    'encyclopedia.templateField.effect': 'Effect',
    'encyclopedia.templateField.alignment': 'Alignment',
    'encyclopedia.templateField.requirements': 'Requirements',
    'encyclopedia.templateField.size': 'Size',
    'encyclopedia.templateField.length-of-day': 'Length of day',
    'encyclopedia.templateField.length-of-night': 'Length of night',
    'encyclopedia.templateField.length-of-cycle': 'Length of cycle',
    'encyclopedia.templateField.moons': 'Moons',
    'encyclopedia.templateField.nearby-stellar-bodies': 'Nearby stellar bodies',
    'encyclopedia.templateField.climate': 'Climate',
    'encyclopedia.templateField.weather': 'Weather',
    'encyclopedia.templateField.natural-resources': 'Natural resources',
    'encyclopedia.templateField.notable-locations': 'Notable locations',
    'encyclopedia.templateField.inhabitans': 'Inhabitans',
    'encyclopedia.templateField.looks': 'Looks',
    'encyclopedia.templateField.production': 'Production',
    'encyclopedia.templateField.use': 'Use',
    'encyclopedia.templateField.related': 'Related',
    'encyclopedia.templateField.location': 'Location',
    'encyclopedia.templateField.significance': 'Significance',
    'encyclopedia.templateField.associated-events': 'Associated events',
    'encyclopedia.templateField.associated-figures': 'Associated figures',
    'encyclopedia.templateField.access-restrictions': 'Access restrictions',
    'encyclopedia.templateField.cultural-importance': 'Cultural importance',
    'encyclopedia.templateField.founded': 'Founded',
    'encyclopedia.templateField.government': 'Government',
    'encyclopedia.templateField.defenses': 'Defenses',
    'encyclopedia.templateField.connected-settlements': 'Connected settlements',
    'encyclopedia.templateField.family-motto': 'Family Motto',
    'encyclopedia.templateField.founding-date': 'Founding Date',
    'encyclopedia.templateField.ethos': 'Ethos',
    'encyclopedia.templateField.family-reputation': 'Family Reputation',
    'encyclopedia.templateField.family-branches': 'Family Branches',
    'encyclopedia.templateField.notable-vassals-retainers': 'Notable vassals/retainers',
    'encyclopedia.templateField.skills-required': 'Skills required',
    'encyclopedia.templateField.pay-salary': 'Pay/Salary',
    'encyclopedia.templateField.associated-locations': 'Associated locations',
    'encyclopedia.templateField.associated-characters': 'Associated characters',
    'encyclopedia.templateField.propulsion': 'Propulsion',
    'encyclopedia.templateField.capacity': 'Capacity',
    'encyclopedia.templateField.speed': 'Speed',
    'encyclopedia.templateField.manufacturers': 'Manufacturers',
    'encyclopedia.templateField.symptoms': 'Symptoms',
    'encyclopedia.templateField.causes': 'Causes',
    'encyclopedia.templateField.treatment': 'Treatment',
    'encyclopedia.templateField.affected-species': 'Affected species',
    'encyclopedia.templateField.associated-groups': 'Associated groups',
    'encyclopedia.templateField.ingredients': 'Ingredients',
    'encyclopedia.templateField.preparation': 'Preparation',
    'encyclopedia.templateField.rules': 'Rules',
    'encyclopedia.templateField.equipment': 'Equipment',
    'encyclopedia.templateField.venues': 'Venues',
    'encyclopedia.templateField.architecture': 'Architecture',
    'encyclopedia.templateField.curriculum': 'Curriculum',
    'encyclopedia.templateField.notable-alumni': 'Notable alumni',
    'encyclopedia.templateField.affiliation': 'Affiliation',
    'encyclopedia.templateField.language': 'Language'
}
