export default {
    'feedback.home': 'Centrum podpory',
    'feedback.bugs': 'Problémy',
    'feedback.bugs.desc': 'Setkali jste se s chybou nebo s něčím jiným, co je špatné nebo na špatném místě. Dejte nám vědět zde!',
    'feedback.features': 'Nápady a návrhy',
    'feedback.features.desc': 'Máte nápady na nové funkce nebo jak vylepšit stránku? Dejte nám vědět!',
    'feedback.help': 'Nápověda a návody',
    'feedback.help.desc': 'Jak můžu _____? Jděte sem a najděte si odpovědi.',
    'feedback.desc': 'Vítejte v našem zákaznickém centru!',
    'feedback.open': 'Otevřeno',
    'feedback.closed': 'Uzavřeno',
    'feedback.accepted': 'Přijato',
    'feedback.inprogress': 'Ve vývoji',
    'feedback.completed': 'Dokončeno',
    'feedback.fixed': 'Opraveno',
    'feedback.new.bugs': 'Nahlásit problém',
    'feedback.new.features': 'Navrhnout vylepšení',
    'feedback.lang.nosupport': 'Váš současný jazyk není podporován pro zpětnou vazbu, pište prosím anglicky. Děkujeme!',
    'feedback.new.thanks': 'Děkujeme vám za upozornění! Brzy se na to podíváme.',
    'feedback.comment.title': 'Komentovat',
    'feedback.comment.desc': 'Zašlete nám svůj názor',
    'feedback.comment.legend': 'Váš názor - dejte nám vědět o čemkoliv',
    'feedback.comment.success': 'Děkujeme Vám za Váš názor!',
    'feedback.comment.label': 'Váš komentář',
    'feedback.copyrightReport.title': 'Porušení autorských práv',
    'feedback.copyrightReport.desc': 'Nahlásit porušení autorských práv',
    'feedback.report.noUser': 'Musíte být přihlášeni, abyste mohli podat zprávu.',
    'feedback.voting.totalVoters': 'Počet voličů: {voted, number}',
    'feedback.voting.upvote': '+1',
    'feedback.voting.downvote': '-1',
    'feedback.voting.score': 'Celkové skóre',
    'feedback.report.title': 'Nahlásit obsah',
    'feedback.report.typeSelect': 'Jaký je zde problém?',
    'feedback.reportType.law': 'Porušení zákona',
    'feedback.reportType.vulgar': 'Vulgarní/obsení',
    'feedback.reportType.copyright': 'Porušení autorských práv',
    'feedback.reportType.storyRating': 'Špatné věkové hodnocení',
    'feedback.report.submit': 'Nahlásit',
    'feedback.report.submitting': 'Oznamuji...',
    'feedback.report.violationDesc': 'Podrobnosti',
    'feedback.report.reportSaved': 'Děkujeme! Brzy se na to podíváme.',
    'feedback.report.copyrightReportSaved': 'Děkujeme za nahlášení! Budeme v kontaktu.',
    'feedback.report.copyrightOwnershipDesc': 'Prohlášení o vlastnictví',
    'feedback.report.copyrightNotice': 'Vezměte prosím na vědomí, že pro použití tohoto formuláře musíte být oprávněným vlastníkem díla. Pokud nejste vlastníkem, informujte prosím vlastníka nebo použijte jinou kategorii k informování nás. Bereme porušování autorských práv velmi vážně a totéž platí pro nesprávné a zneužívající používání tohoto formuláře.',
    'feedback.report.copyrightInternalProperty': 'Publikoval jsem toto dílo na Literary Universe',
    'feedback.reportType.spam': 'Spam nebo phishing',
    'feedback.reportType.other': 'Ostatní',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`
};