export default {
  'forum.thread.reply': 'Přidat odpověď do této diskuse',
  'forums.archive': 'Archivovat fórum',
  'forums.archive.explained': 'Archivace fóra zabrání uživatelům publikovat další obsah, ale příspěvky zůstane viditelné.',
  'forums.archive.success': 'Fórum bylo archivováno',
  'forums.archived.forum': 'Toto fórum bylo archivováno {archivedAt, date, long}. Stále můžete prohlížet fórum, ale již nemůžete vytvářet nový obsah.',
  'forums.category.archive': 'Archivovat kategorii',
  'forums.category.archiveExplained': 'Kategorie, která nemá žádná diskusní vlákna, bude smazána, zatímco kategorie s obsahem zabrání vytváření nových vláken.',
  'forums.category.back': 'Zpět na přehled fóra',
  'forums.category.create': 'Vytvořit kategorii fóra',
  'forums.category.delete': 'Smazat kategorii',
  'forums.category.intlName.announcements': 'Oznámení',
  'forums.category.intlName.art': 'Umění',
  'forums.category.intlName.characters': 'Postavy',
  'forums.category.intlName.community': 'Komunita',
  // Pre-defined category names
  'forums.category.intlName.general': 'Obecné',
  'forums.category.intlName.help': 'Pomoc',
  'forums.category.intlName.history': 'Historie',
  'forums.category.intlName.inspiration': 'Inspirace',
  'forums.category.intlName.locations': 'Lokace',
  'forums.category.intlName.meetups': 'Setkání',
  'forums.category.intlName.news': 'Novinky',
  'forums.category.intlName.questions': 'Otázky',
  'forums.category.intlName.stories': 'Příběhy',
  'forums.category.intlName.universe': 'Vesmír',
  'forums.category.intlName.universes': 'Vesmíry',
  'forums.category.intlNameDescription': 'Máme lokalizované názvy běžných kategorií pro Váš výběr, takže kategorie může být k dispozici pro všechny podporované jazyky.',
  'forums.category.isVotable': 'Povolit uživatelům nahoru/dolů hlasovací vlákna',
  'forums.category.language': 'Omezit zobrazení této kategorie na následující jazyk. Ponechte prázdné, pokud chcete zobrazit kategorii ve všech jazycích.',
  'forums.category.languageLimited': 'Tato kategorie se zobrazí pouze uživatelům v tomto jazyce.',
  'forums.category.name': 'Název kategorie',
  'forums.category.reactivate': 'Znovu aktivovat kategorii',
  'forums.category.settings': 'Nastavení kategorie',
  'forums.category.slug': 'SEO url část',
  'forums.category.titleIsGlobal': 'Tento název kategorie se zobrazí v jazyce uživatele, pokud jej podporujeme.',
  'forums.create': 'Zapnout fórum',
  'forums.createQuestionLabel': 'Je toto otázka?',
  // Threads
  'forums.createThread': 'Vytvořit novou diskuzi',
  'forums.createThreadIn': 'Vytvořit novou diskusi v {categoryName}',
  // Forum restrictions
  'forums.forumRestriction.usersOnly': 'Povolit přístup pouze registrovaným uživatelům',
  'forums.forumRestrictionsMessages.usersOnlyForum': 'Toto fórum je přístupné pouze registrovaným uživatelům.',
  'forums.noPosts': 'Zatím nikdo neodpověděl. Buďte první!',
  'forums.noThreads': 'Zatím tu nic není. Je na Vás něco začít.',
  'forums.openingPost': 'Úvodní příspěvek',
  'forums.post': 'Poslat',
  'forums.post.new': 'Nový příspěvek',
  'forums.posting': 'Odesílám...',
  'forums.reply': 'Odpovědět',
  'forums.reset': 'Resetovat',
  'forums.settings': 'Nastavení fóra',
  'forums.settings.accessControls': 'Nastavení přístupů',
  'forums.thread.createdAt': 'Vytvořeno {createdAt, date, medium}',
  'forums.thread.delete': 'Smazat diskusní vlákno',
  'forums.thread.new': 'Nové diskusní vlákno',
  'forums.thread.noReplies': 'V současné době nejsou žádné odpovědi.',
  'forums.thread.replyPosted': 'Vaše zpráva byla odeslána',
  'forums.thread.totalPosts': `{totalReplies, number} {totalReplies, plural,
    one {odpověď}
    few {odpovědi}
    many {odpovědí}
    other {odpovědí}
  }`,
  'forums.threadsCounter': 'Celkový počet diskusí',
  'forums.unArchive': 'Znovu aktivovat fórum',
  'forums.unArchive.success': 'Fórum bylo reaktivováno!',
  'forums.universeTitle': 'Vesmírná fóra pro {universeName}',
  'forums.yourMessage': 'Vaše zpráva'
};