export default {
    'homepage.welcome': 'Vítejte na',
    'homepage.start': 'Začněte Vaše dobrodužství!',
    'homepage.iAm': 'Jsem',
    'homepage.iAm.aria': 'Vyberte mezi zobrazením funkcí pro čtenáře a spisovatele',
    'homepage.reader': 'ČTENÁŘ',
    'homepage.writer': 'SPISOVATEL',
    'homepage.reader.title': 'Čtení nikdy nebylo tak zajímavé jako tohle',
    'homepage.reader.registerCTA': 'Začněte číst hned!',
    'homepage.reader.readingTitle': 'Unikátní čtecí zážitek',
    'homepage.reader.readingDesc': 'Ponořte se hlouběji do svého oblíbeného fiktivního světa v Literárním vesmíru. Příběhy v Literárním vesmíru jsou propojeny v rámci jednoho vesmíru, což vám umožňuje okamžitý přístup k encyklopedii vesmíru ze čtečky příběhů.',
    'homepage.reader.favoriteTitle': 'Zjistěte více o svých oblíbených příbězích a autorech',
    'homepage.reader.favoriteDesc': 'Encyklopedie vesmíru a blogy autorů jsou jen některé funkce, které vám pomohou zjistit vše, co potřebujete vědět o svých oblíbených příbězích, jejich prostředí a jejich tvůrcích!',
    'homepage.reader.communityTitle': 'Přidejte se k naší komunitě',
    'homepage.reader.communityDesc': 'Seznamte se s lidmi z celého světa na specializovaných fórech, blozích a dalších komunitních funkcích, kde se scházejí podobně smýšlející fanoušci. Vše na jednom místě.',
    'homepage.reader.readingFeatureTitle': 'Vychutnejte si poutavý a zároveň praktický zážitek ze čtení',
    'homepage.reader.readingFeatureDesc': 'Z příběhů a vesmíru máte výhodu snadného čtení s přístupem k podrobnostem, aniž byste museli přepínat mezi stránkami.',
    'homepage.reader.readingExploreTitle': 'Prozkoumejte všechny drobnosti ve vesmíru',
    'homepage.reader.readingExploreDesc': 'Encyklopedie vesmíru vám umožní dozvědět se všechny podrobnosti o vesmíru a plně se ponořit do příběhů.',
    'homepage.reader.start': 'Začněte číst',
    'homepage.writer.title': 'Představte Váš vesmír a sdílejte Vaše příběhy',
    'homepage.writer.writingTitle': 'Psaní & tvorba jednodušše',
    'homepage.writer.writingDesc': 'Vyzkoušejte si nový způsob psaní s workshopem Literární vesmíry. Vytvořte si v encyklopedii všechny detaily Vašeho vesmíru, které budete sdílet se čtenáři, a na tomto základě pište úžasné příběhy.',
    'homepage.writer.collaborationTitle': 'Týmová práce',
    'homepage.writer.collaborationDesc': 'Na tvůrčím procesu se často podílí více lidí. Nebojte se, máme pro vás řešení! Do Vašich příběhů a vesmírů můžete snadno přidávat beta čtenáře, spoluautory a překladatele.',
    'homepage.writer.communityTitle': 'Spojení s Vašimi čtenáři',
    'homepage.writer.communityDesc': 'Překročte rámec psaní a spojte se se svými čtenáři prostřednictvím blogů, fór a dalších komunitních funkcí spojených s vaším světem nebo s vámi jako spisovatelem.',
    'homepage.writer.workshopFeatureTitle': 'Jedno místo pro všechny Vaše kreativní potřeby',
    'homepage.writer.workshopFeatureDesc': 'Naše neustále se rozvíjející dílna je ústředním místem pro vaše tvůrčí potřeby. Z jednoduchého nápadu vytvoříte úžasné vesmíry, příběhy a vše ostatní, co je kolem něj potřeba.',
    'homepage.writer.monetizationFeatureTitle': 'Monetizace',
    'homepage.writer.monetizationDesc': 'Jsme pevně přesvědčeni, že lidé by měli být za svou práci placeni, a neustále hledáme nové možnosti zpeněžení pro autory. Funkce monetizace Vám umožňuje, abyste byli oceněni za to, co děláte. Prozkoumejte všechny různé možnosti, které Vašim fanouškům umožňují projevit vám své uznání.',
    'homepage.writer.start': 'Začněte tvořít!',
    'homepage.featureSelection': 'Podívejte se na tyto populární vesmíry!',
    'about.title': 'O Literary Universe',
    'about.desc': 'Historie, tajemství a lidé za Literary Universe.',
    'about.text.1': 'Literary Universe je navržen pro spisovatele i nadšené čtenáře. Spisovatelé mohou použít platformu k vytváření originálních děl vybráním tlačítka "Pracovna" v nabídce na nástěnce. To poskytuje přístup k hlavnímu editoru a funkcím encyklopedie, které se zaměřují na organizaci všech aspektů vašeho osobního univerza příběhů na jedné stránce. Sociální funkce umožňují autorům sdílet svou práci, budovat si sledování a případně interagovat s čtenáři přímo, pokud si to přejí.',
    'about.text.2': 'Čtenáři mohou využívat stránku především k objevování nových děl a sledování svých oblíbených autorů, ale také mohou pomáhat upravovat před-publikované příběhy, pokud jim autor udělí povolení. Být čtenářem na Literary Universe nabízí zcela nový zážitek z čtení - mít přístup ke všem informacím o pozadí příběhu na stejné stránce jako hlavní příběh poskytuje vhled do mysli autora jako nikdy předtím.',
    'about.text.3': 'Budoucnost Literary Universe zahrnuje vytvoření tržiště, kde autoři mohou prodávat svá díla, a přidání komunitních funkcí pro zlepšení komunikace mezi autory a čtenáři prostřednictvím blogů a fór. Plánujeme postupně uvést další nástroje pro spisovatele, z nichž více než tucet je v současné době ve vývoji nebo plánování. Naším konečným cílem je obohatit zážitky jak spisovatelů, tak čtenářů prostřednictvím inovativního využití internetového média.',
    'about.text.4': 'Doufáme že se k nám přidáte a pomůžete nám objevit co internetové medium může udělat pro kreativní psaní!',
    'about.team': 'Tým',
    'about.history': 'Historie',
    'about.company': 'Firma',
    'about.companyCountry.czechia': 'Česko',
    'about.companyCountry.japan': 'Japonsko',
    'about.companyCity.prague': 'Praha',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Výkonný ředitel',
    'about.CTO': 'Technický Ředitel',
    'about.jan': 'Jan je zakladatel, vizionář a technologický mozek za projektem Literary Universe. Jako spisovatel rozsáhlých literárních vesmírů se Jan často potýkal s psaním příběhů takovým způsobem, který by vyvážil technickou přesnost s čitelností, aniž by ohrozil zážitek čtenáře. Toto výzvou ho vedlo k studiu webového vývoje s cílem vytvořit aplikaci, která zjednoduší proces psaní příběhů v rámci rozsáhlých vesmírů.',
    'about.history.text': 'V roce 2010 začal Honza studovat v Rochesterském technologickém institutu, aby prohloubil své znalosti v oblasti vývoje webu, s cílem vytvořit platformu pro kreativní psaní. Tato vize se zhmotnila v roce 2013, kdy byla představena první koncepce a otestována na Imagine RIT. Honza pokračoval ve studiu a v roce 2016 byla vytvořena nová verze aplikace jako jeho diplomový projekt. Projekt pokračoval v dalším vývoji během podzimu 2016 a postupně se vyvinul do platformy, kterou vidíte dnes.',
    'copyrights.desc': 'Informace o autorských právech na Literary Universe.',
    'privacy.desc': 'Úplný právní text Zásad ochrany osobních údajů Literary Universe.',
    'guidelines.desc': 'Komunitní směrnice Literary Universe.',
    'tos.desc': 'Úplný právní text Podmínek služby Literary Universe.',
    'homepage.intro': 'Nechte vaši kreativitu vyniknout v Literary Universe',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'Snili jste někdy o tom, že vytvoříte fiktivní svět tak detailní, že se v něm ztratíte i vy? V Literary Universe Vám nabízíme nástroje, které vám pomohou tuto vizi uskutečnit. Každý spisovatel si zaslouží přístup ke špičkovým zdrojům a podpoře. Proto jsme navrhli komplexní nástroj, který překlenuje propast mezi složitým vyprávěním příběhů a vášnivým čtením. Pro spisovatele je to vysněný pracovní prostor, pro čtenáře odysea objevování. Vydejte se s námi po stopách literární králičí nory a zjistěte, kam až nás ve světě fantazie zavede.',
    'gdpr.title': 'Soulad s GDPR',
    'gdpr.what': 'Co je GDPR?',
    'gdpr.explained': 'Obecné nařízení o ochraně osobních údajů (GDPR) je zákon Evropské unie o ochraně osobních údajů, který upravuje způsob shromažďování, zpracování, ukládání a ochrany osobních údajů. GDPR má zajistit, aby každý uživatel věděl, jaké údaje jsou shromažďovány, chápal, jak jsou používány, a měl plnou kontrolu nad svými osobními údaji.',
    'gdpr.compliant': 'Přestože LiteraryUniverse působí celosvětově, uplatňujeme zásady GDPR jako standard důvěry a transparentnosti pro všechny uživatele.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'Změny v této verzi',
    'dmca.title': 'Politika digitálního zákona o autorském právu (DMCA)',
    'dmca.subtitle': 'Zásady autorských práv pro spory',
    'dmca.step1.title': 'Postup hlášení porušení autorských práv.',
    'dmca.step2.title': 'Po obdržení řádného oznámení.',
    'dmca.step3.title': 'Postup pro podání odvolání a dalšího řízení.',
    'dmca.desc': 'Porušování autorských práv bereme vážně.',
    'gdpr.summary': '<ul><li>Shromažďujeme pouze údaje nezbytné pro provoz platformy nebo ty, které chcete sdílet.</li><li>Vaše údaje neprodáváme.</li><li>Ke svým údajům můžete kdykoli přistupovat, upravovat je, exportovat nebo mazat.</li><li>K ochraně vašich údajů používáme zabezpečení odpovídající průmyslovým standardům.</li></ul>',
    'gdpr.data.title': 'Jaké údaje shromažďujeme',
    'gdpr.data.desc': 'Kromě údajů, které jste vložili do svého profilu nebo které jste vygenerovali prostřednictvím interakce (zprávy, příběhy atd.), se snažíme shromažďovat co nejméně údajů. Technické údaje, jako je IP adresa, typ prohlížeče a operační systém, shromažďujeme za účelem zajištění bezpečnosti a funkčnosti naší platformy. V omezené míře zaznamenáváme vaše akce na naší platformě pro účely zabezpečení a funkčnosti. Příležitostně můžeme shromažďovat údaje pro marketingové účely, ty budou probíhat prostřednictvím služeb třetích stran, které respektují GDPR, a vždy budete mít možnost se z nich odhlásit.',
    'gdpr.dataUse.title': 'Jak používáme vaše údaje',
    'gdpr.dataUse.desc': 'Vaše údaje se používají k následujícím účelům:<ul><li>Poskytování základních funkcí platformy (např. účty, publikování obsahu, zasílání zpráv).</li><li>Zabezpečení, prevence zneužití a odhalování podvodů</li><li>Funkční analýzy pro zlepšení výkonu a uživatelského komfortu</li><li>Dodržování právních předpisů a reagování na platné žádosti</li><li>Interně sdílíme anonymizované údaje s našimi autory, když čtete jejich příběhy.</li><li>Váš e-mail a zemi poskytujeme společnosti Stripe za účelem zpracování plateb a ochrany před podvody</li><li>Pro marketingové účely můžeme používat vaše údaje, ale vždy budete mít možnost se odhlásit (banner se soubory cookie atd.).</li></ul>',
    'gdpr.dataStorage.title': 'Ukládání a zabezpečení dat',
    'gdpr.dataStorage.desc': '<ul><li>Veškerá data (s výjimkou necitlivých audiovizuálních dat) jsou uložena pomocí zabezpečených šifrovaných systémů.</li><li>Přístup je omezen pouze na oprávněné pracovníky s využitím zabezpečeného přístupu podle průmyslových standardů.</li><li>Pravidelně provádíme bezpečnostní audity a aktualizace, abychom zajistili bezpečnost vašich dat.</li><li>Veškerá interní komunikace probíhá prostřednictvím šifrovaných kanálů</li></ul>I přes veškerou snahu není žádný online systém nikdy 100% imunní. Ve výjimečných případech narušení bezpečnosti dat budou uživatelé informováni co nejdříve, jak to vyžaduje zákon.',
    'gdpr.rights.title': 'Vaše práva podle GDPR',
    'gdpr.rights.desc': 'Podle GDPR máte následující práva. Možnosti jejich provedení naleznete ve svém uživatelském nastavení nebo u daného obsahu: <ul><li>Právo na přístup - vyžádejte si údaje, které o vás uchováváme</li><li>Právo na výmaz - Vymazání všech vašich údajů z našich serverů (platí omezení vyplývající z platných zákonů a naší dohody s vámi - pokud jde o příběhy).</li><li>Právo na omezení zpracování - omezte způsob použití vašich údajů.</li><li>Právo na přenositelnost údajů - import/export vašich údajů</li></ul>',
    'gdpr.dataRetention.title': 'Uchovávání údajů',
    'gdpr.dataRetention.desc': 'Vaše údaje ukládáme:<ul><li>Dokud je váš účet aktivní</li><li>Nebo tak dlouho, jak to vyžadují právní, bezpečnostní nebo provozní účely.</li><li>V případě zveřejněných tvůrčích děl je uchováváme idenfinitivně, pokud není dohodnuto jinak.</li></ul>',
    'gdpr.contact.title': 'Kontakt',
    'gdpr.contact.desc': 'Jsme jen lidé, takže pokud máte nějaké požadavky, dotazy, obavy nebo jsme něco přehlédli, neváhejte nás kontaktovat.<br></br>E-mail: privacy@literaryuniverse.com',
    'dmca.step1.desc1': 'Hlášení je rozděleno na dva scénáře. 1. Vnitřní majetek (porušení na stránce). 2. Externí majetek (porušení majetku, který na stránce neexistuje).',
    'dmca.step1.desc2': 'Hlášení vnitřního obsahu lze provést pomocí tlačítka hlášení u daného obsahu. Oznamování porušení vnějšího obsahu lze provést stejným způsobem. V obou případech budete požádáni o osobní údaje a další údaje, které nám umožní zkontrolovat vaše vlastnictví.',
    'dmca.step1.desc3': 'Vezměte prosím na vědomí, že falešná tvrzení povedou k vaší neschopnosti podávat žádosti v budoucnu.',
    'dmca.step2.desc1': 'Po obdržení vaší zprávy ověříme Vaše údaje a vlastnické nároky. Pokud je vše v pořádku, přistoupíme k ověření nároku. Pokud určíme nárok jako pravdivý, učiníme neoprávněné obsah nepřístupným, pokud nedojde k odvolání do 14 dní, po kterém bude tento majetek vymazán.',
    'dmca.step3.desc1': 'Po obdržení stížnosti bude mít vlastník určeného majetku 14 dní na podání odvolání. Jmenovaný agent pak přistoupí k vyšetřování sporu. Každé rozhodnutí jmenovaného agenta v této fázi bude konečné.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Atribuce',
    'about.attributionsIntro': 'Literární Universe staví na mnoha Open Source projektech a dalších zdrojích. Zde je seznam některých z nich.',
    'about.attributionsMatomo': 'Naše analytika používá vlastní Matomo s IP2Location LITE daty dostupné na https://lite.ip2location.com.',
    'team.name.pjakubec': 'Pavel Jakubec',
    'about.developer': 'Vývojář',
    'about.seniorDeveloper': 'Seniorní vývojář',
    'about.juniorDeveloper': 'Začínající vývojář',
    'about.leadDesigner': 'Hlavní designér',
    'about.leadUX': 'Hlavní UX designer',
    'about.intern': 'Stážista',
    'about.advisor': 'Poradce',
    'about.headOfResearch': 'Vedoucí výzkumu',
    'about.CFO': 'Finanční Ředitel',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry je designér s více než 15 lety zkušeností. Pracoval v agentuře od roku 2010, jeho klienty byly například PERTAMINA, VOA a ministerstvo indonéského cestovního ruchu. Se zkušenostmi s brandingem, layoutem a také UI/UX je pro něj výzva pracovat na designu pro Literary Universe.',
    'about.pavel': 'Web3, Metaverze, umělá inteligence a jakákoli nová technologie - Pavel to vše zkoumá, aby zjistil, jak může zlepšit Literary Universe. Jako skutečný multidisciplinární výzkumník Pavel má přehled v mnoha oblastech a pracuje na začleňování nových a vzrušujících funkcí do platformy.',
    'copyrights.about': 'Literární vesmír bere autorská práva velmi vážně. Veškerý obsah, který uživatelé zveřejňují, je jejich vlastní a je k dispozici pod uvedenou licencí. Kromě kompletní sady licencí Creative Commons nabízí Literary Universe také 2 komerční licence, exkluzivní a neexkluzivní.',
    'copyrights.nonExclusiveLicense': 'Nevýhradní licence Literary Universe vám umožňuje publikovat na Literary Universe, aniž byste se vzdali jakýchkoli svých autorských práv. Můžete svobodně publikovat kdekoli jinde. Literary Universe si vyhrazuje právo používat vaše duševní vlastnictví pouze pro marketingové účely. Pokud se rozhodnete prodat své duševní vlastnictví na Literary Universe, platforma si bude účtovat 30% poplatek za platformu.',
    'copyrights.exclusiveLicense': 'Exkluzivní licence Literary Universe vám umožňuje publikovat výhradně na Literary Universe. To znamená, že nemůžete publikovat své duševní vlastnictví na jiných online platformách ani na ničem jiném mimo Literary Universe. Pokud chcete publikovat na fyzickém médiu, například v knize, musíte požádat o povolení. Pokud Literary Universe neodpoví do 30 dnů, je to automatický souhlas. Doufáme, že vám v budoucnu nabídneme fyzické publikování a další služby prostřednictvím našich partnerů. Nebojte se nás kontaktovat, přejeme vám úspěch a ve většině případů si dáváme pozor jen na podvodné firmy. Přesto je to omezující, takže jako poděkování je poplatek za platformu pouze 10 %.',
    'copyrights.licensesAreImportant': 'Výběr licence je nesmírně důležitý a ovlivňuje způsob, jakým bude vaše práce v budoucnu přístupná. Pro usnadnění výběru se můžete podívat na náš výběr licencí níže.'
};