export default {
    'homepage.welcome': 'Vítejte na Literary Universe!',
    'homepage.read': 'Čtení',
    'homepage.explore': 'Objevování',
    'homepage.create': 'Tvorba',
    'homepage.read.desc': 'Užijte si skvělý zážitek z čtení s přístupem k detailům vesmíru příběhů v blízkosti textu, bez nutnosti opustit okno příběhu.',
    'homepage.explore.desc': 'Příběhy nejsou jediným způsobem, jak prozkoumat literární vesmíry. Každý vesmír má svou vlastní stránku, kde můžete prozkoumat všechny detaily ve vesmírné encyklopedii, Podívejte se na všechny příběhy ve vesmíru nebo prozkoumejte, co napsali ostatní fanoušci.',
    'homepage.create.desc': 'Vytvořte si vlastní příběhy a vesmíry prostřednictvím našeho editoru. Vytvořte a spravujte svůj stále se rozšiřující vesmír. Nabízíme rozšiřující soubor nástrojů, od skvělého editoru příběhů přes skvělou encyklopedii až po správu překladů tvých příběhů a vesmíru!',
    'homepage.begin': 'Začněte svou cestou!',
    'homepage.itisfree': 'Začněte zadarmo!',
    'about.title': 'O Literary Universe',
    'about.desc': 'Historie, tajemství a lidé za Literary Universe.',
    'about.text.1': 'Literární Universe je navržen jak pro spisovatele, tak pro velké čtenáře. Autoři mohou tuto stránku použít k psaní originálních děl prostřednictvím tlačítka ateliéru v nabídce hlavního panelu. To vám umožní přístup k hlavním funkcím editoru a encyklopedie, které se primárně zaměřují na organizaci všech aspektů vašeho osobního příběhu vesmíru na jednu stránku. Sociální aspekty umožňují autorům propagovat svou práci a rozvíjet následující aspekty, stejně jako přímé komunikace, pokud si zvolí, se svými čtenáři.',
    'about.text.2': 'Čtenáři mohou používat stránky primárně ke čtení nových děl a sledovat autory, ale také pomoci upravovat předpublikované příběhy, pokud k tomu autor udělil povolení. Být čtenář na Literary Universe je zcela nový zážitek z čtení, máte přístup ke všem informacím na pozadí na stejné stránce jako hlavní příběh Vám dává vhled do mysli autora jako nikdy dříve.',
    'about.text.3': 'Budoucnost pro Literary Universe zahrnuje vytvoření tržiště pro autory, aby mohli prodávat své dílo a přidávat funkce komunity k vylepšení autora a čtenářské komunikace prostřednictvím blogů a fór. Spisovatelské nástroje budou v průběhu času přidávány s více než tuctem, a to buď ve vývoji, nebo na palubě. Naším konečným cílem je zlepšit zkušenosti spisovatelů a čtenářů tím, že poskytneme inovativnější používání internetového média.',
    'about.text.4': 'Doufáme že se k nám přidáte a pomůžete nám objevit co internetové medium může udělat pro kreativní psaní!',
    'about.team': 'Tým',
    'about.history': 'Historie',
    'about.CEO': 'Výkonný ředitel',
    'about.CTO': 'Technický Ředitel',
    'about.jan': 'Honza je zakladatelský, vizionářský a technologický mozek za literárním vesmírem. Jako spisovatel velkých literárních vesmírů, Honza zjistil, že je těžké psát příběhy z technického a srozumitelného hlediska, které by nenarušilo požitek ze čtení jako takové. Honza se rozhodl pokračovat ve svých studiích ve vývoji webu, aby vytvořil aplikaci, která by usnadnila psaní příběhů velkých vesmírů.',
    'about.history.text': 'V roce 2010 začal Honza studovat v Rochesterském technologickém institutu, aby se dozvěděl více o vývoji webu, aby byl schopen vytvořit dobré stránky pro kreativní psaní. To se zhmotnilo v roce 2013, kdy byla představena první koncepce a otestována na Imagine RIT. Honza pokračoval ve studiu a v roce 2016 byla vytvořena nová verze aplikace jako Master\'s Capstone projekt. Projekt pokračoval v podzimu 2016 a dále se rozvinul do toho, co dnes vidíte.',
    'copyrights.desc': 'Úplné znění dohody o autorských právech.',
    'privacy.desc': 'Úplný právní text Zásad ochrany osobních údajů Literary Universe.',
    'guidelines.desc': 'Komunitní směrnice Literary Universe.',
    'tos.desc': 'Úplný právní text Podmínek služby Literary Universe.',
    'homepage.intro': 'Prozkoumejte a vytvořte literární vesmíry a skvělé příběhy.',
    'homepage.explanation': 'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'gdpr.title': 'Soulad s GDPR',
    'gdpr.desc': 'Literární Universe je v souladu s GDPR.',
    'gdpr.compliant': 'Literární Universe splňuje GDPR',
    'gdpr.compliant.text': 'Literární Universe realizoval různé aktualizace a změny své kódovací základny při přípravě prosazování GDPR 25. května 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'Změny v této verzi',
    'dmca.title': 'Politika digitálního zákona o autorském právu (DMCA)',
    'dmca.subtitle': 'Zásady autorských práv pro spory',
    'dmca.step1.title': 'Postup hlášení porušení autorských práv.',
    'dmca.step2.title': 'Po obdržení řádného oznámení.',
    'dmca.step3.title': 'Postup pro podání odvolání a dalšího řízení.',
    'dmca.desc': 'Porušování autorských práv bereme vážně.',
    'gdpr.access.title': 'Právo na přístup a právo na přenositelnost údajů',
    'gdpr.access.desc': 'V uživatelském nastavení můžete exportovat všechna data. Tato data budou ve standardním formátu JSON.',
    'gdpr.forget.title': 'Právo na zapomenutí',
    'gdpr.forget.desc': 'Jakýkoli účet může být odstraněn v nastavení uživatele. Některá data mohou být zachována, zejména pokud byla předmětem prodeje a/nebo sporů.',
    'gdpr.rectification.title': 'Právo na opravu',
    'gdpr.rectification.desc': '',
    'gdpr.processing.title': 'Právo na omezení zpracování',
    'gdpr.processing.desc': 'Literary Universe plně respektuje nastavení prohlížeče, jako například požadavky "Do not track" pro hlášení na náš statistický server Matomo.',
    'gdpr.object.title': 'Právo vznést námitku',
    'gdpr.object.desc': '',
    'dmca.step1.desc1': 'Hlášení je rozděleno na dva scénáře. 1. Vnitřní majetek (porušení na stránce). 2. Externí majetek (porušení majetku, který na stránce neexistuje).',
    'dmca.step1.desc2': 'Hlášení vnitřního obsahu lze provést pomocí tlačítka hlášení u daného obsahu. Oznamování porušení vnějšího obsahu lze provést stejným způsobem. V obou případech budete požádáni o osobní údaje a další údaje, které nám umožní zkontrolovat vaše vlastnictví.',
    'dmca.step1.desc3': 'Vezměte prosím na vědomí, že falešná tvrzení povedou k vaší neschopnosti podávat žádosti v budoucnu.',
    'dmca.step2.desc1': 'Po obdržení vaší zprávy ověříme Vaše údaje a vlastnické nároky. Pokud je vše v pořádku, přistoupíme k ověření nároku. Pokud určíme nárok jako pravdivý, učiníme neoprávněné obsah nepřístupným, pokud nedojde k odvolání do 14 dní, po kterém bude tento majetek vymazán.',
    'dmca.step3.desc1': 'Po obdržení stížnosti bude mít vlastník určeného majetku 14 dní na podání odvolání. Jmenovaný agent pak přistoupí k vyšetřování sporu. Každé rozhodnutí jmenovaného agenta v této fázi bude konečné.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Atribuce',
    'about.attributionsIntro': 'Literární Universe staví na mnoha Open Source projektech a dalších zdrojích. Zde je seznam některých z nich.',
    'about.attributionsMatomo': 'Naše analytika používá vlastní Matomo s IP2Location LITE daty dostupné na https://lite.ip2location.com.',
    'about.attributionIcons': 'Následující ikony jsou používány pomocí styled-icons:',
    'team.name.rhubbell': 'Raena Hubbell',
    'team.name.pjakubec': 'Pavel Jakubec',
    'team.name.asebesta': 'Adam Šebesta',
    'about.developer': 'Vývojář',
    'about.seniorDeveloper': 'Seniorní vývojář',
    'about.juniorDeveloper': 'Začínající vývojář',
    'about.apprenticeDeveloper': 'Učeň vývojář',
    'about.intern': 'Stážista',
    'about.advisor': 'Poradce',
    'about.headOfResearch': 'Vedoucí výzkumu',
    'about.CFO': 'Finanční Ředitel'
};