export default {
    'settings.biography': 'Biografie',
    'settings.biography.placeholder': 'Něco málo o Vás, pro zobrazení na Vašem profilu.',
    'settings.avatar.title': 'Avatar',
    'settings.avatar.own': 'Váš avatar',
    'settings.avatar.upload': 'Vyberte obrázek',
    'settings.email': 'E-maily',
    'settings.email.msg': 'E-maily spojené s Vaším účtem',
    'settings.email.verified.false': 'Neověřeno',
    'settings.email.verified.true': 'Ověřený e-mail',
    'settings.email.add': 'Přidat e-mail',
    'settings.languages.title': 'Jazyková nastavení',
    'settings.languages.notice': 'Angličtina je momentálně jediná oficiálně podporovaný jazyk. Ostatní jazyky jsou přístupné díky dobrovolníkům, ale nemusejí být úplné.',
    'settings.languages.join': 'Pokud nám chcete pomoci, můžete také přeložit Literary Universe.',
    'settings.name.title': 'Skutečné jméno',
    'settings.name.given': 'Křestní jméno',
    'settings.name.family': 'Příjmení',
    'settings.username.change': 'Změnit uživatelské jméno',
    'settings.username.label': 'Uživatelské jméno',
    'settings.password.title': 'Změnit heslo',
    'settings.password.current': 'Současné heslo',
    'settings.password.new': 'Nové heslo',
    'settings.password.repeat': 'Zopakujte své nové heslo',
    'settings.password.nomatch': 'Hesla se neshodují!',
    'settings.password.reset': 'Resetovat heslo',
    'settings.password.resetSend': 'E-mail s instrukcemi pro resetování hesla byl odeslán!',
    'settings.socialConnectTitle': 'Propojte se s Vašimi účty z jiných služeb',
    'settings.socialDisconnect': 'Odpojit',
    'settings.socialConnect': 'Připojit',
    'settings.loginWith': 'Přihlásit se přes {service}',
    'settings.connectTo': 'Spojit s {service}',
    'settings.export.title': 'Export dat',
    'settings.export.explain': 'Získejte všechna Vaše data uložená v naší databázi ve formátu json.',
    'settings.export.submit': 'Exportovat data',
    'settings.delete.title': 'Smazat účet',
    'settings.delete.warning': `VAROVÁNÍ: Odstraněním vašeho účtu ztratíte přístup k tomuto účtu a
    neexistuje způsob, jak jej získat zpět. Všimněte si, že toto nemusí automaticky odstranit vaše publikované dílo,
    komentáře atd. Podrobnosti naleznete v podmínkách služby.`,
    'settings.delete.confirm': 'Pro potvrzení. Vážně chcete smazat váš účet?',
    'settings.delete.cancel': 'Nechci smazat svůj účet',
    'settings.delete.submit': 'Smazat můj účet',
    'settings.legal.title': 'Dohody o souhlasu uživatele',
    'settings.legal.explained': 'Zde můžete spravovat svůj souhlas s různými právními dokumenty.',
    'settings.name.private': 'Jméno bude soukromé',
    'settings.emailSubscriptions.title': 'Nastavení e-mailových oznámení',
    'settings.emailSubscriptions.explain': 'Vyberte, která e-mailová oznámení od nás chcete dostávat.',
    'settings.emailSubscriptions.newsletter': 'Příležitostný bulletin',
    'settings.profile': 'Nastavení profilu',
    'settings.account': 'Nastavení účtu',
    'settings.legal.export.download': 'Stáhnout data',
    'settings.legal.export.gathering': 'Shromažďuji Vaše data... To může chvíli trvat.',
    'settings.gender.title': 'Vaše pohlaví',
    'settings.gender.usage': 'Tato informace zůstanou soukromá. Tato data používáme pro analýzu platformy a anonymizované analýzy pro tvůrce, když čtete jejich příběhy.',
    'settings.age.title': 'Váš věk',
    'settings.age.explicit': 'Zobrazit explicitní obsah (věkové hodnocení 21+)',
    'settings.age.usage': 'Tato informace zůstane soukromá. Jsme ze zákona povinni se ptát na váš věk. Používáme tento údaj pro analýzu platformy, zobrazujeme obsah na základě hodnocení a anonymizovaný analytik tvůrcům při čtení jejich příběhů.',
    'settings.country.title': 'Vaše země',
    'settings.country.usage': 'Jsme ze zákona povinni se zeptat na vaši zemi, abychom mohli reagovat na vládní dotazy. Tento údaj používáme pro vylepšení systému a anonymizovanou analýzu tvůrcům při čtení jejich příběhů. Pokud si přejete můžete zobrazit tento údaj na Vašem profilu.',
    'settings.country.public': 'Zobrazit Vaši zemi veřejně',
    'settings.country.select': 'Vyberte Vaši zemi',
    'settings.emailSubscriptions.newsletterTech': 'Příležitostný buletin od vývojářů',
    'settings.emailSubscriptions.newsletterFeatures': 'Informace o nových funkcích',
    'settings.emailNotifications.title': 'Upozornění',
    'settings.emailNotifications.pm': 'Nové zprávy',
    'settings.emailNotifications.newChapters': 'Nové kapitoly',
    'settings.resetPasswordEmailSend': 'Poslali jsme Vám pokyny, jak resetovat Vaše heslo na Váš e-mail.',
    'settings.theme.title': 'Vzhled stránky',
    'settings.theme.label': 'Motiv stránky',
    'settings.theme.light': 'Světlý',
    'settings.theme.dark': 'Tmavý',
    'settings.links.title': 'Odkazy na Vaše další webové stránky',
    'settings.links.description': 'Tyto odkazy se zobrazí na Vaší profilové stránce.',
    'settings.links.website': 'Vaše osobní stránka',
    'settings.links.social': 'Ostatní webové stránky',
    // 2FA
    'settings.2fa.title': 'Dvoufázové ověření',
    'settings.2fa.explained': 'Dvoufaktorové ověření poskytuje další vrstvu zabezpečení vašeho účtu přidáním dalšího kroku ověřování během přihlášení. To brání škodlivým aktérům získat přístup k vašemu účtu, pokud je váš první krok přihlášení zkompromitován.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Dvoufázové ověřování pomocí OTP kódu vytváří jednorázové heslo prostřednictvím autentizačních aplikací (jako je Authy, Google/Microsoft Authenticator, atd.), které zadáte při přihlášení.',
    'settings.2fa.otpModalAria': '2FA OTP metoda',
    'settings.2fa.otpAdd': 'Přidat 2FA OTP',
    'settings.2fa.confirmCode': 'Kód, který se zobrazí ve Vaší ověřovací aplikaci',
    'settings.2fa.svgAlt': 'QR kód pro autentikační aplikaci',
    'settings.2fa.codeHeading': 'Pokud nelze naskenovat QR kód, můžete ručně zadat následující kód:',
    'settings.2fa.instructionsTitle': 'Pokyny',
    'settings.2fa.instructions1': 'Nainstalujte a otevřete autentikační aplikaci dle vašeho výběru (Authy, Google/Microsoft Authenticator, FreeOTP, atd.)',
    'settings.2fa.instructions2': 'Zvolte "Přidat účet" (může být viditelná ikona "+" nebo může být skryta v nabídce)',
    'settings.2fa.instructions3': 'Naskenujte QR kód na obrazovce nebo pokud to není možné, zadejte kód níže.',
    'settings.2fa.instructions4': 'Zadejte 6 čísel, která se objeví na obrazovce do vstupu pro dokončení.',
    'settings.2fa.saved': 'Dvoufaktorové ověření bylo úspěšně vytvořeno!',
    'settings.2fa.disableOTP': 'Vypnout OTP dvoufaktorové ověřování',
    'settings.web3.legend': 'Připojení k Web3 peněžence',
    'settings.web3.explained': 'K vašemu účtu Literary Universe můžete připojit peněženku Web3. Jakmile budete připojeni, budete se moci přihlásit do Vaší peněženky a v budoucnosti bude k dispozicí ještě více funkcionality, protože rozšiřujeme naši nabídku pro Web3.',
    'settings.web3.connect': 'Připojit peněženku',
    'settings.web3.address': 'Připojená adresa: {address}',
    'settings.web3.verify': 'Podepište svou adresu',
    'settings.web3.verify.explained': 'Pro ověření, že tato adresa patří Vám, Vás požádáme, abyste podepsali zprávu pro potvrzení Vašeho vlastnictví peněženky.',
    'settings.web3.verified': 'Ověřeno',
    'settings.web3.verificationMessage': 'Ověřování uživatele {username} pro Literary Universe. Kód: {code}',
    'settings.web3.unlink': 'Odstranit peněženku',
    'settings.web3.linkingMessage': 'Potvrďte, že chcete propojit Vaši peněženku s Literary Universe. Kód: {code}',
    'settings.web3.linkError': 'Tato adresa je již uvedena v naší databázi a nemůže být přiřazena!'
};