export default {
    'stats.age.groups': 'Věková skupina',
    'stats.age.range': 'Věkové rozmezí',
    'stats.age.to12': 'Do 12 let',
    'stats.age.12to17': '12 až 17',
    'stats.age.18to20': '18 až 20',
    'stats.age.21to29': '21 až 29',
    'stats.age.30to39': '30 až 39',
    'stats.age.40to49': '40 až 49',
    'stats.age.50to64': '50 až 64',
    'stats.age.65to84': '64 až 84',
    'stats.age.above85': 'Nad 85',
    'stats.section.aggregate': 'Souhrnné statistiky',
    'stats.section.chapter': 'Statistiky kapitoly',
    'stats.readers.title': 'O vašich čtenáři',
    'stats.gender.title': 'Pohlaví',
    'stats.view.table': 'Tabulkový pohled',
    'stats.view.pie': 'Pie graf pohled',
    'stats.view.bar': 'Sloupový graf pohled',
    'stats.view.chart': 'Grafický pohled',
    'stats.table.total': 'Celkem',
    'stats.timeline.title': 'Časová osa',
    'stats.timeline.dateStart': 'Statistiky začínají v',
    'stats.timeline.dateEnd': 'Statistiky končí v',
    'stats.likeCount': '# oblíbených',
    'stats.language.title': 'Jazyky',
    'stats.chapter.visitorsAndViews': 'Celkem návštěvníků a pohledů podle kapitol',
    'stats.chapter.wordCount': 'Počet slov podle kapitoly',
    'stats.chapter.chartTooltipViews': `Kapitola {chapter}: {views} zobrazení`,
    'stats.chapter.chartTooltipVisitors': `Kapitola {chapter}: {visitors} unikátních návštěvníků`,
    'stats.chapter.chartTooltipWordCount': `Kapitola {chapter}: {wordCount} slov`,
    'stats.totalHits': 'Celkem zhlédnutí',
    'stats.totalVisitors': 'Celkem unikátních návštěvníků',
    'stats.totalWords': 'Celkem slov',
    'stats.totalEntries': 'Položek v encyklopedii',
    'stats.blogPage': 'Stránka',
    'stats.blog.typeSelectionAria': 'Type selection',
    'stats.blog.pages': 'Pages',
    'stats.blog.posts': 'Posts'
};