/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'יקום ספרותי',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe is an all-in-one creative and publishing platform for grand story universes.',
    'site.keywords': 'creative writing, scifi, sci-fi, fantasy, writing, publishing, story, stories, universe, web novel, webnovel',
    'site.logoAlt': 'לוגו של יצירת הספרות',
    mobileMenu: 'תפריט נייד',
    'common.signin': 'התחברות',
    'common.signup': 'הרשמה',
    'common.signout': 'התנתקות',
    'common.dashboard': 'לוח בקרה',
    'common.discovery': 'גילוי',
    'common.library': 'ספרייה',
    'common.library.own': 'הספריה שלך',
    'common.workshop': 'סדנה',
    'common.pm': 'הודעות',
    'common.settings': 'הגדרות',
    'common.options': 'אפשרויות',
    'common.profile': 'פרופיל',
    'common.blog': 'בלוג',
    'common.blogs': 'בלוגים',
    'common.about': 'אודותינו',
    'common.accessdenied': 'גישה נדחתה',
    'common.accessdenied.msg': 'לא ניתן לך גישה למקום זה. אם עליך לקבל גישה לכאן, אנא צור קשר עם הבעלים והסבירו לו לבדוק שוב את ההגדרות.',
    'common.loading': 'טוען...',
    'common.add': 'הוספה',
    'common.save': 'שמירה',
    'common.email': 'דוא"ל',
    'common.soon': 'מגיע בקרוב...',
    'common.search': 'חיפוש',
    'common.search.do': 'חיפוש',
    'common.searching': 'מחפש...',
    'common.report': 'דוח',
    'common.user': 'משתמש',
    'common.users': 'משתמשים',
    'common.showmore': 'הצג עוד',
    'common.futurefeature.title': 'תכונה עתידית',
    'common.futurefeature.text': 'אנו מצטערים מאוד, אך תכונה זו אינה זמינה כעת. אנו עובדים קשה כדי להפוך אותה לזמינה בהקדם האפשרי.',
    'common.nothingfound': 'לא נמצא דבר',
    'common.explore': 'חקור',
    'common.by': 'על ידי {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'מחברת טיוטה',
    'common.scratchpad.own': 'המחברת האישית שלך',
    'common.news': 'חדשות',
    'common.encyclopedia': 'אנציקלופדיה',
    'common.art': 'אמנות',
    'common.story': 'סיפור',
    'common.stories': 'סיפורים',
    'common.universe': 'יקום',
    'common.universes': 'יקומים',
    'common.collaborator': 'שותף',
    'common.collaborators': 'שותפים',
    'common.translator': 'מתרגם',
    'common.translators': 'מתרגמים',
    'common.betareader': 'בטא רידר',
    'common.betareaders': 'בטא רידרים',
    'common.post': 'פוסט',
    'common.statistics': 'סטטיסטיקות',
    'common.lang.select': 'בחר שפה',
    'common.submit': 'שלח',
    'common.close': 'סגור',
    'common.comment': 'תגובה',
    'common.comments': 'תגובות',
    404: 'הדף לא נמצא',
    'search.users': 'חפש משתמשים',
    'search.user': 'חפש משתמש',
    'common.help': 'עזרה',
    'common.or': 'או',
    'common.account.create': 'צור חשבון',
    'signup.username': 'שם משתמש',
    'signup.email': 'האימייל שלך',
    'signup.password.label': 'הסיסמה שלך',
    'signup.password.repeat': 'חזור על הסיסמה שלך',
    'common.password': 'סיסמה',
    'signin.password.forgot': 'שכחת סיסמה?',
    'dashboard.whatsnew': 'מה חדש',
    'dashboard.blog': 'הבלוג שלך',
    'common.footer.tagline': 'כתיבה וקריאה של יקומים מורכבים בקלות.',
    'common.footer.plans': 'תוכניות ומחירים',
    'common.legal.tos': 'תנאי שימוש',
    'common.legal.community': 'הנחיות הקהילה',
    'common.legal.privacy': 'מדיניות פרטיות',
    'common.legal.copyright': 'הסכם זכויות יוצרים',
    'common.legal.versionDisplay': `{type, select,
    tos {תנאי השימוש}
    community {הנחיות הקהילה}
    privacy {מדיניות פרטיות}
    copyright {הסכם זכויות יוצרים}
    publishingAgreement {הסכם לפרסום}
    other {הסכם}
  } גרסה {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'גרסה חדשה ({newVersion}) של מסמך זה תיכנס לתוקף ב {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} כל הזכויות שמורות, כל הטקסטים שייכים למחבריהם.',
    'premium.only.title': 'דרגת חברות לא מספיקה',
    'premium.only.msg': 'אנו מתנצלים, דרגת החברות שלך אינה מספיקה כדי לגשת לתכונה זו.',
    'premium.only.join': 'אנחנו מציעים מגוון של תוכניות לכולם כדי להשיג את המרב מתוך יוניברס הספרותית.',
    'premium.only.link': 'תבדוק את זה!',
    'universe.visit': 'בקר בדף היקום',
    'common.fanmanager': 'Fan manager',
    'common.fanarts': 'Fan arts',
    'common.fanfiction': 'Fan fiction',
    'common.fansettings': 'Fan settings',
    'story.chapter': 'פרק',
    'story.chapters': 'פרקים',
    'story.genre': 'ז\'אנר',
    'story.genres': 'ז\'אנרים',
    'story.read': 'קרא',
    'story.lastUpdate': 'עודכן לאחרונה ב {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'סיים ב {date, date, medium}.',
    'story.comments.for': 'תגובות ל {story} {chapter}.',
    'story.cover.alt': 'תמונת כריכה לסיפור {story}.',
    'story.note.fanfiction': 'הערה: סיפור זה הוא פאן פיקשן על יקום {universe} .',
    copyrights: 'זכויות יוצרים',
    'common.challenges': 'אתגרים',
    // for beta only
    'beta.notice': 'ברוכים הבאים לסביבת ניסיון של Literary Universe. זוהי תצוגה מקדימה ציבורית ולכן האפליקציה עוד נמצאת בתהליך של עבודה. כלומר, עדיין ניתן לצפות בשגיאות ובתכונות שטרם הושלמו. אם אתה נתקל בשגיאה או בתכונה שלא פועלת אנא דווח לנו והתאם עם סבלנות עד שנסדר את הכל במקומו.',
    'beta.thanks': 'תודה על התמיכה שלך!',
    'scratchpad.about': 'ההערות והרעיונות שלך נגישים בכל מקום באתר.',
    'common.feedback': 'משוב',
    'common.createdOn': 'נוצר בתאריך {date, date, long}',
    'common.createdOn.title': 'נוצר בתאריך',
    // account types
    admin: 'מנהל',
    'common.saved': 'נשמר!',
    'common.saving': 'שומר...',
    'common.friends': 'חברים',
    'lang.orig': 'שפה מקורית',
    'lang.orig.plus': 'שפה מקורית - {language}',
    buy: 'קנה',
    confirm: 'אשר',
    cancel: 'ביטול',
    processing: 'מעבד...',
    'common.noData': 'אין נתונים',
    'error.title': 'אירעה שגיאה. אנו מתנצלים על הלא נוחות.',
    'common.offlineStatus': 'אתה כרגע במצב לא מחובר.',
    male: 'זכר',
    female: 'נקבה',
    'common.legal.effectiveAt': 'בתוקף מ {date, date, medium}',
    select: 'בחר בבקשה',
    'common.statusFailed': 'נכשלה התחברות לשרת.',
    'common.statusConnecting': 'מנסה להתחבר לשרת... ({count, number})',
    'slug.checking': 'בודק...',
    'slug.failed': 'כתובת זו כבר קיימת.',
    'slug.success': 'כתובת זו זמינה!',
    'notVerified.msg': `Your account {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    } is not verified.`,
    'notVerified.verify': `Please verify your {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    }.`,
    unknown: 'לא ידוע',
    'common.legal.guidelines': 'הנחיות הקהילה',
    'errorLoading.title': 'שגיאה בטעינת הדף',
    'errorLoading.explained': 'אירעה שגיאה בעת טעינת הדף. אנו מתנצלים על האי נוחות. אנא נסו לגשת שוב לדף. אם הבעיה ממשיכה, אנא דעו אותנו.',
    'errorLoading.retry': 'נסו שוב!',
    'errorLoading.takingLong': 'זה דורש זמן ממושך...',
    'common.title': 'כותרת',
    'common.timelines': 'צירים זמניים',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'תקנון הגנת הפרטיות הכללי',
    'editor.placeholder.link': 'הזן כתובת URL...',
    'editor.placeholder.connection': 'חפש ערך באנציקלופדיה...',
    'editor.saved.beta': 'נוצרת גרסה חדשה עבור קוראי ביתא!',
    'editor.saved.public': 'פורסם גרסה חדשה!',
    goodbyeForever: 'אנחנו מצטערים לראות שאתה עוזב. האם זו משהו שעשינו? אנא דע לנו אם כן. בכל מקרה, אנחנו מאחלים לך הצלחה בעתיד ומקווים לפגוש שוב! חי וצור רק טוב!',
    'goodbyeForever.feedback': 'אנא ספר לנו מה אנחנו יכולים לעשות טוב יותר',
    'common.edit': 'עריכה',
    'common.publish': 'פרסום',
    'common.publishAt': 'תאריך ושעת פרסום',
    'a11y.user.menu': 'תפריט משתמש',
    'a11y.navigation': 'ניווט',
    'dashboard.profile': 'הפרופיל שלך',
    'profile.website': 'האתר האישי שלי',
    'story.notes.concept': 'מושג',
    'story.notes.settings': 'הגדרות הסיפור',
    'story.notes.theme': 'ערכת עיצוב',
    'story.notes.impact': 'Desired impact',
    'story.notes.outcome': 'Outcome',
    'story.notes.audience': 'Target audience',
    'story.notes.pitch': 'Pitch',
    'story.notes.notes': 'Notes',
    'story.authorsNotes': 'הערות המחבר',
    'common.members': 'Members',
    'common.language': 'Language',
    next: 'Next',
    previous: 'Previous',
    'common.legal.tos.short': 'Terms',
    'common.legal.privacy.short': 'Privacy',
    'premium.increaseLimit': 'Consider upgrading to increase you limit.',
    'common.sharing': 'Sharing',
    'story.isbn': 'ISBN',
    'common.name': 'Name',
    'common.remove': 'Remove',
    'common.time.milliseconds': 'Milliseconds',
    'common.time.seconds': 'Seconds',
    'common.time.minutes': 'Minutes',
    'common.time.hours': 'Hours',
    'common.time.days': 'Days',
    'common.time.weeks': 'Weeks',
    'common.time.months': 'Months',
    'common.time.years': 'Years',
    'common.monetization': 'מונטיזציה',
    'common.tab.monetizationOptions': 'אפשרויות מונטיזציה',
    'common.pagination': 'פגינציה',
    'common.forum': 'Forum',
    'common.2faCode': '2FA code',
    'common.2faCodeIntro': 'Please enter your one time code generated by your authenticator application.',
    'common.2faCodeAria': '2FA code entry form',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Default language',
    'signin.web3.signMessage': 'Please confirm that you want to enter Literary Universe with your wallet as authentication method. Code: {code}',
    'common.web3.confirmationCode': 'Confirmation code: {code}',
    'common.roadmap': 'Roadmap',
    'common.luStatsIFrameOptOut': 'סטטיסטיקות יצירת העולם הספרותית - בחירה לא להשתתף',
    'common.image': 'תמונה',
    'common.home': 'דף הבית',
    'common.administration': 'ניהול',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'קבוצות',
    'common.upload': 'העלאה',
    'common.backToDashboard': 'חזרה ללוח בקרה',
    'common.accept': 'קבל',
    'common.reject': 'דחה',
    'common.events': 'אירועים',
    'common.event': 'Event',
    'common.all': 'הכל',
    'common.social': 'Social',
    'common.discordCommunity': 'Discord Community',
    'common.account': 'Account',
    'common.notifications': 'התראות',
    'common.byDeclaration': 'By:',
    'common.done': 'Done',
    recommended: 'Recommended',
    'select.typeToCreate': 'Start typing to create an item',
    'select.noSearchResults': 'No results for “{search}”',
    'select.removeOption': 'Remove {option}',
    create: 'Create',
    'banner.support': 'Literary Universe is supported by users like you! Please consider subscribing to one of our subscription plans to stay independent and make Literary Universe event better!',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Don\'t have an account?',
    'common.haveAccountQuestion': 'Already have an account?',
    'common.socialLogin': 'Login with other services',
    'common.viewMore': 'View more',
    'common.overview': 'Overview',
    'common.loggingOut': 'התנתקות',
    'common.thankYou': 'תודה רבה!',
    'common.seeYouAgain': 'נתראה שוב!',
    'email.hello': 'שלום {username},',
    'common.back': 'חזרה',
    'console.stop': 'עצור!',
    'console.explain': 'זוהי תכונה של דפדפן המיועדת למפתחים. אם מישהו אמר לך להעתיק ולהדביס משהו כאן כדי לאפשר תכונת יצירת סיפורים או ל"האק" את חשבון מישהו, זה הונאה ויאפשר לו לגשת לחשבון הסיפורים שלך.'
}    /* eslint-enable max-len */;