export default {
  'courses.courses': 'קורסים',
  'courses.overview': 'סקירת הקורסים',
  'courses.public.title': 'Explore Courses',
  'courses.public.heading': 'Explore Courses',
  'courses.public.filters': 'Filter Courses',
  'courses.public.noResults': 'No courses found',
  'courses.public.tryDifferentFilters': 'Try different search terms or filters',
  'courses.filter.search': 'Search courses...',
  'courses.filter.allTypes': 'All Types',
  'courses.filter.clearAll': 'Clear All',
  'courses.filter.type': 'סוג',
  'courses.type.course': 'Course',
  'courses.type.workshop': 'סדנה',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Course',
  'courses.type.workshop.lowercase': 'סדנה',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'יצירת קורס חדש',
  'course.reading.title': 'כותרת מטלת הקריאה',
  'course.question.add': 'הוסף שאלה',
  'course.lessons.newMessage': 'הכינו וארגנו את השיעורים שלכם כדי ללמד ביעילות',
  'course.reading.new': 'משימת קריאה',
  'course.reading.newMessage': 'הכינו וארגנו מטלות קריאה לתלמידים שלכם',
  'course.writing.new': 'משימת כתיבה',
  'course.writing.newMessage': 'הגדר והפיץ משימות כתיבה במהירות',
  'course.question.text': 'השאלה שלך היא',
  'course.question.type': 'אנא בחר סוג שאלה',
  'course.question.delete': 'הסר את השאלה',
  'course.type': 'Course Type',
  'course.visibility': 'בחר אפשרות ניראות',
  'course.title': 'כותרת',
  'course.description': 'תיאור',
  'course.cover': 'תמונת כריכה',
  'course.start': 'הקורס שלך מתחיל בתאריך',
  'course.ends': 'הקורס שלך מסתיים בתאריך',
  'course.curriculum': 'Course Curriculum',
  'course.members': 'תלמידים ומורים',
  'course.assignments': 'משימות',
  'course.question.deleteWhole': 'מחק את השאלה במלואה',
  'course.question.yes': 'כן',
  'course.question.no': 'לא',
  'course.lesson.title': 'כותרת השיעור',
  'course.lesson.add.universe': 'הוסף סיפור/יקום',
  'course.lesson.externalLinks': 'External links',
  'course.lesson.add.link': 'הוסף קישור חיצוני',
  'course.status': 'סטטוס',
  'course.active': 'פעילות',
  'course.active.message': 'פעיל',
  'course.inactive': 'לא פעיל',
  'course.upload.resource': 'Upload a resource',
  'course.question.answer': 'הוסף תשובה',
  'course.question.open': 'שאלה פתוחה',
  'course.question.close': 'שאלה סגורה',
  'course.question.multiple': 'שאלה רב-ברירתית',
  'course.about': 'אודות הקורס',
  'course.lesson.new': 'צור שיעור חדש',
  'course.lesson.type': 'סוג השיעור',
  'course.lesson.inPerson': 'פנים אל פנים',
  'course.lesson.preRecorded': 'מוקלט מראש',
  'course.lesson.online': 'באינטרנט',
  'course.lesson.text': 'טקסט בלבד',
  'course.lesson.content': 'תוכן השיעור',
  'course.lesson.description': 'תיאור ציבורי',
  'course.add.story': 'הוסף סיפור',
  'course.remove.story': 'הסר את הסיפור',
  'course.dateOfPublish': 'תאריך הפרסום',
  'course.lesson.meetInPerson': 'להיפגש פנים אל פנים',
  'course.curriculum.edit': 'ערוך תוכנית הלימודים',
  'course.stories.own': 'הסיפורים שלכם',
  'course.stories.organization': 'סיפורי ארגונים',
  'course.stories.public': 'סיפורים פומביים',
  'course.publish.at': 'אני רוצה שהקורס הזה יפורסם בכתובת:',
  'course.edit.curriculum': 'ערוך תוכנית הלימודים',
  'course.assignment': 'משימה',
  'course.lesson.removeLink': 'הסר קישור',
  'course.user.remove': 'Remove user',
  'course.user.invite': 'Invite user',
  'course.user.invited': 'Invited',
  'course.edit.role': 'ערוך תפקיד',
  'course.assignment.description': 'תיאור המשימה',
  'course.internal': 'פנימי',
  'course.free': 'חינם',
  'course.sale': 'מבצע',
  'course.announcements': 'Announcements',
  'course.announcements.full': 'Course announcements',
  'course.announcements.create': 'Create an announcement',
  'course.join': 'Join Course',
  'course.joining': 'Joining...',
  'course.join.success': 'You have successfully joined this course!',
  'course.join.error.payment': 'This course requires payment to join.',
  'course.join.error.invite': 'This course requires an invitation to join.',
  'course.join.error.generic': 'There was an error joining the course. Please try again.',
  'course.firstLesson': 'First Lesson',
  'course.upcomingLessons': 'Upcoming Lessons',
  'course.detail.title': '{courseName} | Course',
  'lessons.visibility.public': 'Public',
  'lessons.visibility.private': 'Private',
  'course.curriculum.empty': 'No curriculum items available yet.',
  'course.preview.message': 'This is a preview of the course. Join the course to access all content.',
  'course.details': 'Course Details',
  'course.tab.curriculum': 'Curriculum',
  'course.tab.details': 'Course Details',
  'course.duration': 'Duration',
  'course.perpetual': 'Perpetual',
  'course.language': 'שפה',
  'course.price': 'Price',
  'course.learningObjectives': 'Learning Objectives',
  'course.prerequisites': 'Prerequisites',
  'course.tags': 'Tags',
  'course.stats.members': 'חברים',
  'course.stats.lessons': 'Lessons',
  'course.assignments.comingSoon': 'Assignments view is coming soon.',
  'course.progress.comingSoon': 'Progress tracking is coming soon.',
  'course.type.free': 'חינם',
  'course.type.paid': 'Paid',
  'course.type.forSale': 'למכירה',
  'course.type.invite': 'Invite Only',
  'courses.invites.tile': 'You are invited to partake in {count, plural, one {course} other {courses}}.',
  'courses.invites.noInvites': "You don't have any course invitations at the moment.",
  'courses.invites.invitedBy': 'Invited by: ',
  'course.join.heading': 'Join This Course',
  'course.oneTimePayment': 'One-time payment for full access',
  'course.member': "You're Enrolled",
  'course.member.access': 'You have full access to all course materials.',
  'courses.members.editRole': 'Edit Role',
  'courses.members.editRoleFor': 'Edit role for:',
  'courses.add.member': 'Add a new member',
  'course.member.options': 'Course member list',
  'course.navigation.curriculum': 'Curriculum',
  'course.navigation.members': 'Students & Teachers',
  'course.navigation.assignments': 'משימות',
  'course.navigation.forums': 'Forums',
  'course.navigation.attendance': 'Attendance',
  'course.members.teachers': 'Teachers',
  'course.members.students': 'Students',
  'course.members.preview.message': 'Join this course to see all students and interact with the community.',
  'course.member.role.owner': 'בעלים',
  'course.member.role.teacher': 'מורה',
  'course.member.role.student': 'סטודנט',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'course.startDate': 'Start Date',
  'course.endDate': 'End Date',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Curriculum Preview',
  'course.curriculum.preview.message': 'Join this course to access all {count} lessons and assignments.',
  'course.curriculum.locked': 'Locked',
  'course.curriculum.lesson': 'Lesson',
  'course.curriculum.assignment': 'משימה',
  'course.curriculum.reading': 'Reading',
  'course.lesson.backToCurriculum': 'Back to Curriculum',
  'course.lesson.nextLesson': 'Next Lesson',
  'course.lesson.documents': 'Documents & Resources',
  'course.lesson.meetingLink': 'Meeting Link',
  'course.lesson.location': 'Location',
  'course.lesson.virtualClassroom': 'Virtual Classroom',
  'course.lesson.joinClassroom': 'Join the virtual classroom session',
  'course.lesson.enterClassroom': 'Enter Classroom',
  'course.assignment.acceptsStories': 'מקבל סיפורים',
  'course.assignment.acceptsUniverses': 'מקבל יקומים',
  'course.assignment.backToAssignments': 'חזרה למשימות',
  'course.assignment.criteria': 'קריטריונים לקריאה',
  'course.assignment.dueDate': 'מועד הגשה: {date}',
  'course.assignment.freeReading': 'אפשרות קריאה חינמית',
  'course.assignment.grade': 'ציון',
  'course.assignment.grade.received': 'ציון: {grade}',
  'course.assignment.gradeSaveError': 'לא ניתן לשמור את הציון',
  'course.assignment.gradeSaved': 'הציון נשמר.',
  'course.assignment.gradedCount': '{count, plural, one {# מדורג} other {# מדורג}}',
  'course.assignment.grading.help':
    'בדקו את העבודות שהגישו התלמידים, פתחו סיפורים או יקומים מקושרים, והוסיפו ציון ומשוב (לפי בחירתכם).',
  'course.assignment.grading.title': 'דירוג: {title}',
  'course.assignment.grading.unavailable': 'הציון אינו זמין',
  'course.assignment.grading.unavailableMessage': 'אין לך גישה לדף הציונים הזה, או שלא נמצא את המטלה.',
  'course.assignment.lastRead': 'נקרא לאחרונה {date}',
  'course.assignment.minutes': '{count} דקה',
  'course.assignment.noSubmissions': 'עדיין לא הוגשו תגובות.',
  'course.assignment.noWrittenResponse': 'לא נמסרה תשובה בכתב.',
  'course.assignment.notFound': 'לא נמצא משימה',
  'course.assignment.notFoundMessage': 'לא נמצא את המשימה המבוקשת.',
  'course.assignment.noteForTeacher': 'הוסף הודעה למורה שלך',
  'course.assignment.open': 'משימה פתוחה',
  'course.assignment.openGrading': 'פתח את דף הציונים',
  'course.assignment.questions': 'שאלות',
  'course.assignment.readingProgress': 'התקדמות התלמידים בקריאה',
  'course.assignment.readings': 'קריאה חובה',
  'course.assignment.responsePlaceholder': 'כתוב כאן את תשובתך',
  'course.assignment.responsePrompt': 'נושא למאמר או הנחיה לכתיבת יומן',
  'course.assignment.selectStoriesRead': 'בחר את הסיפורים שבחרת למשימה זו.',
  'course.assignment.sharedProject.studentHelp':
    'פתחו את אחד מקבצי הפרויקט המשותפים שלעיל ב-Workshop והוסיפו אליו את התרומה שלכם. למשימה זו אין צורך בטופס הגשה נפרד.',
  'course.assignment.sharedProject.studentTitle': 'כיצד לבצע את המשימה הזו',
  'course.assignment.sharedProject.teacherNotice':
    'במשימה זו של פרויקט משותף נעשה שימוש בגישה לשיתוף פעולה במקום בהגשות אישיות.',
  'course.assignment.sharedProjects': 'עבודות בפרויקטים משותפים',
  'course.assignment.storiesCompleted': 'סיפורים שהושלמו',
  'course.assignment.submissionCount': '{count, plural, one {# הגשה} other {# הגשות}}',
  'course.assignment.submissionSaved': 'ההגשה נשמרה.',
  'course.assignment.submissions': 'הגשת עבודות וציונים',
  'course.assignment.submit': 'להגיש את המטלה',
  'course.assignment.submitError': 'לא ניתן לשלוח את המטלה',
  'course.assignment.submitWork': 'בחר את העבודה שברצונך להגיש',
  'course.assignment.submitWork.help': 'בחרו את הסיפור או את היקום שעליהם יינתן הציון במשימה זו.',
  'course.assignment.submitWork.label': 'עבודה שהוגשה',
  'course.assignment.submitWork.placeholder': 'בחר סיפור או יקום',
  'course.assignment.submittedAt': 'הוגש ב- {date}',
  'course.assignment.submittedWork.story': 'סיפור שהוגש: {title}',
  'course.assignment.submittedWork.universe': 'היקום שהוגש: {title}',
  'course.assignment.supportingFiles': 'חומרים נלווים שהועלו',
  'course.assignment.supportingMaterials': 'חומרי עזר',
  'course.assignment.updateSubmission': 'שליחת עדכון',
  'course.assignment.yourSubmission': 'ההגשה שלך',
  'courses.role.owner': 'בעלים',
  'courses.role.teacher': 'מורה',
  'courses.role.student': 'סטודנט',
};
