export default {
    'feedback.home': 'מרכז עזרה',
    'feedback.bugs': 'בעיות',
    'feedback.bugs.desc': 'האם נתקלת בשגיאה או משהו אחר שאינו נכון או לא במקום הנכון? תשתף אותנו בכך כאן!',
    'feedback.features': 'רעיונות והצעות',
    'feedback.features.desc': 'יש לך רעיונות לתכונות חדשות או איך לשפר את האתר? תשתף אותנו בכך!',
    'feedback.help': 'עזרה והדרכות',
    'feedback.help.desc': 'איך אתה _____? עבור לכאן כדי למצוא את התשובות.',
    'feedback.desc': 'ברוכים הבאים למרכז העזרה והפתרון שלנו!',
    'feedback.faq': 'שאלות נפוצות',
    'feedback.faq.desc': 'שאלות נפוצות',
    'feedback.open': 'פתוח',
    'feedback.closed': 'סגור',
    'feedback.accepted': 'התקבל',
    'feedback.inprogress': 'בתהליך',
    'feedback.completed': 'הושלם',
    'feedback.fixed': 'תוקן',
    'feedback.new.bugs': 'דווח על בעיה חדשה',
    'feedback.new.features': 'הצעת תכונה חדשה',
    'feedback.lang.nosupport': 'השפה הנוכחית שלך אינה נתמכת עבור משוב, אנא כתוב באנגלית. תודה!',
    'feedback.new.thanks': 'תודה על הערה! אנחנו נבדוק את זה בקרוב.',
    'feedback.comment.title': 'תגובה',
    'feedback.comment.desc': 'שלח לנו את המשוב שלך',
    'feedback.comment.legend': 'המשוב שלך - תשתף אותנו בכל דבר',
    'feedback.comment.success': 'תודה על המשוב שלך!',
    'feedback.comment.label': 'הערתך',
    'feedback.copyrightReport.title': 'הפרה של זכויות יוצרים',
    'feedback.copyrightReport.desc': 'דווח על הפרת זכויות יוצרים',
    'feedback.report.noUser': 'עליך להתחבר כדי לדווח.',
    'feedback.voting.totalVoters': 'משתמשים הצביעו: {voted, number}',
    'feedback.voting.upvote': 'הצבעה חיובית',
    'feedback.voting.downvote': 'הצבעה שלילית',
    'feedback.voting.score': 'סכום כולל',
    'feedback.report.title': 'דיווח תוכן',
    'feedback.report.typeSelect': 'מה הבעיה כאן?',
    'feedback.reportType.law': 'הפרת חוק',
    'feedback.reportType.vulgar': 'גס/מגונה',
    'feedback.reportType.copyright': 'הפרת זכויות יוצרים',
    'feedback.reportType.storyRating': 'דירוג גיל לא נכון',
    'feedback.reportType.scam': 'הונאה',
    'feedback.report.submit': 'דוח',
    'feedback.report.submitting': 'מדווח...',
    'feedback.report.violationDesc': 'פרטים',
    'feedback.report.reportSaved': 'תודה על הדיווח! אנחנו נבחן ונפעל אם יהיה צורך.',
    'feedback.report.copyrightReportSaved': 'תודה על הדיווח! אנחנו נבחן וניצור קשר.',
    'feedback.report.copyrightOwnershipDesc': 'הצהרת בעלות',
    'feedback.report.copyrightNotice': 'שים לב שעליך להיות בעל חוקי של היצירה כדי להשתמש בטופס זה. אם אתה לא הבעלים, אנא הודע לבעלים או השתמש בקטגוריה האחרת כדי להודיע לנו. אנחנו מתייחסים להפרות זכויות יוצרים ברצינות רבה ואותו דבר חל גם לשימוש לא נאות ולשימוש מותר בטופס זה.',
    'feedback.report.copyrightInternalProperty': 'פרסמתי יצירה זו ביקום הספרותי',
    'feedback.reportType.spam': 'ספאם או פישינג',
    'feedback.reportType.soliciting': 'Soliciting',
    'feedback.reportType.aiUnmarked': 'Unmarked AI-generated content',
    'feedback.reportType.other': 'אחר',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`,
    'feedback.help.overview': 'Overview',
    'feedback.help.articles': 'Articles',
    'feedback.help.courses': 'Courses',
    'feedback.help.videos': 'Video tutorials',
    'feedback.help.featuredArticles': 'Featured Articles',
    'feedback.help.featuredCourses': 'Featured Courses',
    'feedback.help.featuredVideos': 'Featured Videos',
    'feedback.help.subCategories': 'Sub-categories',
    'feedback.resolution.title': 'Resolution center',
    'feedback.resolution.desc': 'Manage and resolve reported violations',
    'feedback.reportType.aiGenerated': 'AI-generated content',
    'feedback.resolution.aiGeneration': 'AI Generation Status',
    'feedback.resolution.aiGenerated': 'AI Generated',
    'feedback.resolution.notAiGenerated': 'Not AI Generated'
};