export default {
  'forum.thread.reply': 'הוסף תגובה לטראד זה',
  'forums.archive': 'ארכיון פורום',
  'forums.archive.explained': 'ארכיבת הפורום תמנע ממשתמשים לפרסם תוכן נוסף, אך הוא יישאר גלוי.',
  'forums.archive.success': 'הפורום הועבר לארכיון',
  'forums.archived.forum': 'הפורום הזה הועבר לארכיון ב {archivedAt, date, long}. עדיין ניתן לצפות בפורומים, אך אין אפשרות ליצור תוכן חדש.',
  'forums.category.archive': 'ארכיבת קטגוריה',
  'forums.category.archiveExplained': 'קטגוריה שאין לה אשכולות תימחק, בעוד קטגוריות עם תוכן ימנעו יצירת אשכולות חדשים.',
  'forums.category.back': 'חזרה לסקירת הפורומים',
  'forums.category.create': 'צור קטגורית פורום',
  'forums.category.delete': 'מחק קטגוריה',
  'forums.category.intlName.announcements': 'הודעות',
  'forums.category.intlName.art': 'אמנות',
  'forums.category.intlName.characters': 'דמויות',
  'forums.category.intlName.community': 'קהילה',
  // Pre-defined category names
  'forums.category.intlName.general': 'כללי',
  'forums.category.intlName.help': 'עזרה',
  'forums.category.intlName.history': 'History',
  'forums.category.intlName.inspiration': 'השראה',
  'forums.category.intlName.locations': 'מיקומים',
  'forums.category.intlName.meetups': 'מפגשים',
  'forums.category.intlName.news': 'חדשות',
  'forums.category.intlName.questions': 'שאלות',
  'forums.category.intlName.stories': 'סיפורים',
  'forums.category.intlName.universe': 'יקום',
  'forums.category.intlName.universes': 'יקומים',
  'forums.category.intlNameDescription': 'יש לנו כותרות מתורגמות של שמות קטגוריות נפוצות לבחירתך, כך שהקטגוריה תהיה זמינה לכל השפות התומכות.',
  'forums.category.isVotable': 'אפשר למשתמשים להצביע בתוך נושאים',
  'forums.category.language': 'הגבל תצוגה של קטגוריה זו לשפה הבאה. השאר ריק אם ברצונך להציג את הקטגוריה בכל השפות.',
  'forums.category.languageLimited': 'קטגוריה זו תוצג רק למשתמשים בשפה זו.',
  'forums.category.name': 'שם הקטגוריה',
  'forums.category.reactivate': 'הפעלת מחדש קטגוריה',
  'forums.category.settings': 'הגדרות קטגוריה',
  'forums.category.slug': 'חלק URL למטרת SEO',
  'forums.category.titleIsGlobal': 'כותרת זו של הקטגוריה תוצג בשפת המשתמש אם אנחנו תומכים בה.',
  'forums.create': 'הפעל פורום',
  'forums.createQuestionLabel': 'האם זה שאלה?',
  // Threads
  'forums.createThread': 'צור דיון חדש',
  'forums.createThreadIn': 'צור טראד חדש ב {categoryName}',
  // Forum restrictions
  'forums.forumRestriction.usersOnly': 'אפשר גישה רק למשתמשים רשומים',
  'forums.forumRestrictionsMessages.usersOnlyForum': 'פורום זה נגיש רק למשתמשים רשומים.',
  'forums.noPosts': 'עדיין אין תגובות. היה הראשון!',
  'forums.noThreads': 'אין כאן דבר. עליך להתחיל שיחה.',
  'forums.openingPost': 'פוסט פתיחה',
  'forums.post': 'פוסט',
  'forums.post.new': 'פוסט חדש',
  'forums.posting': 'מתבצעת פרסום...',
  'forums.reply': 'הגב',
  'forums.reset': 'איפוס',
  'forums.settings': 'הגדרות הפורום',
  'forums.settings.accessControls': 'בקרת גישה',
  'forums.thread.createdAt': 'נוצר ב {createdAt, date, medium}',
  'forums.thread.delete': 'מחק נושא',
  'forums.thread.new': 'נושא חדש',
  'forums.thread.noReplies': 'אין תגובות כאן כרגע.',
  'forums.thread.replyPosted': 'הודעתך פורסמה',
  'forums.thread.totalPosts': `{totalReplies, number} {totalReplies, plural,
    one {תגובה}
    other {תגובות}
  }`,
  'forums.threadsCounter': 'סך כל הודעות ודיונים',
  'forums.unArchive': 'הפורומים הופעלו מחדש',
  'forums.unArchive.success': 'הפורום הופעל מחדש!',
  'forums.universeTitle': 'פורומים של Universe עבור {universeName}',
  'forums.yourMessage': 'הודעתך'
};