// Notifications & flashnews
export default {
  'flashnews.create': 'צור  תצוגת חדשות חטיבה',
  'flashnews.startsAt': 'התחל להציג את ההודעה בתאריך',
  'flashnews.endsAt': 'הפסק להציג את ההודעה בתאריך',
  'flashnews.newLanguage': 'בחר שפה חדשה להוסיף',
  'flashnews.onlyDisplayOn': 'החדשות יתווספו רק בשפה הנבחרת למטה (אם נבחרו), לא יוצגו חדישות באף שפה אחרת, גם לא בשפת ברירת המחדל.',
  'notifications.menu.all': 'כל התראות',
  'notifications.menu.following': 'המעקבים שלי',
  'notifications.menu.workshop': 'סדנה',
  'notifications.menu.news': 'חדשות ועדכונים',
  'notifications.menu.markUnread': 'סמן כלא נקרא',
  'notifications.menu.markRead': 'סמן כנקרא',
  'notifications.menu.delete': 'מחק התראה',
  // Notification messages
  'notification.workshopStoryStatus.toHiatus': 'הסיפור שלך {storyName} הוכרז כנעול אוטומטית לאחר 6 חודשים של חוסר פעילות.',
  'notification.workshopStoryStatus.toCancelled': 'הסיפור שלך {storyName} הוכרז כבוטל אוטומטית לאחר שנה של חוסר פעילות.',
  'notification.followingStoryStatus.toHiatus': '{storyName} מוחזק במצב נעול.',
  'notification.followingStoryStatus.toCancelled': '{storyName} בוטל.',
  'notification.followingNewChapter.new': 'פרק חדש של {storyName} פורסם!',
  'notification.workshopStory.newComment': 'הערה חדשה ב {storyName}',
  // Before this text will be the username of the user
  'notification.friendRequest': 'שלח לך בקשת חברות.',
  // Before this text will be the username of the user
  // Story notification messages - In-app notifications
  'notification.story.newComment.subject': 'תגובה חדשה על "{storyTitle}"',
  'notification.story.newComment.body': '{commenterName} הגיב על הסיפור שלך: "{commentText}"',
  'notification.story.betaComment.subject': 'משוב חדש על גרסת הבטא של "{storyTitle}"',
  'notification.story.betaComment.body': '{commenterName} סיפק משוב על גרסת הבטא: "{commentText}"',
  'notification.story.collaboratorAccepted.subject': '{role} החדש הצטרף ל"{storyTitle}"',
  'notification.story.collaboratorAccepted.body': '{collaboratorName} קיבלתי את הזמנתך להיות {role}',
  'notification.story.statusChange.subject': 'עדכון סטטוס עבור "{storyTitle}"',
  'notification.story.statusChange.body': 'סטטוס הסיפור השתנה מ- {oldStatus} ל- {newStatus}',
  'notification.story.completed.subject': '"{storyTitle}" הושלם!',
  'notification.story.completed.body': '{authorName} סיים את "{storyTitle}". תודה שקראתם!',
  'notification.story.milestone.subject': 'הישג משמעותי: {milestone} ב"{storyTitle}"!',
  'notification.story.milestone.body': 'הפרק שלך "{chapterTitle}" הגיע ל- {count} {milestone}!',
  'notification.story.betaRevision.subject': 'גרסת בטא חדשה: "{chapterTitle}"',
  'notification.story.betaRevision.body': '{authorName} פרסם גרסת בטא חדשה של "{chapterTitle}" לבדיקה',
  'notification.story.authorReply.subject': '{authorName} השבתי למשוב שלך',
  'notification.story.authorReply.body': '{authorName} השבתי לתגובתך על "{storyTitle}": "{commentText}"',
  'notification.story.newChapterForTranslators.subject': 'תוכן חדש זמין לתרגום: "{chapterTitle}"',
  'notification.story.newBetaForTranslators.body': 'גרסת בטא חדשה של "{chapterTitle}" מוכנה לתרגום',
  'notification.story.newChapterForTranslators.body': 'פרק חדש "{chapterTitle}" זמין לתרגום',
  'notification.story.newChapter.subject': 'פרק חדש: "{chapterTitle}"',
  'notification.story.newChapter.body': '{authorName} פרסם פרק חדש של "{storyTitle}": "{chapterTitle}"',
  // Universe notifications
  'notification.universe.newStory.subject': 'סיפור חדש ביקום: "{storyTitle}"',
  'notification.universe.newStory.body': '{authorName} הוספה סיפור חדש "{storyTitle}" ליקום שאתה עוקב אחריו',
  'notification.universe.collaboratorChange.subject': 'עדכון שיתוף פעולה ביקום',
  'notification.universe.collaboratorChange.body': 'צוות שיתוף הפעולה השתנה עבור יקום שאתה מעורב בו',
  'notification.universe.update.subject': 'היקום עודכן',
  'notification.universe.update.body': 'היקום שאתה עוקב אחריו עודכן',
  'notification.universe.comment.subject': 'תגובה חדשה על היקום',
  'notification.universe.comment.body': '{commenterName} הגיב על יקום שאתה עוקב אחריו: "{commentText}"',
  // Blog notifications
  'notification.blog.newPost.subject': 'פוסט חדש בבלוג: "{postTitle}"',
  'notification.blog.newPost.body': '{authorName} פרסם פוסט חדש בבלוג "{postTitle}" בבלוג שאתה עוקב אחריו.',
  'notification.blog.comment.subject': 'תגובה חדשה בבלוג: "{postTitle}"',
  'notification.blog.comment.body': '{commenterName} הגיב על הפוסט בבלוג "{postTitle}": "{commentText}"',
  'notification.blog.update.subject': 'הבלוג עודכן',
  'notification.blog.update.body': 'בלוג שאתה עוקב אחריו עודכן',
  // General comment notifications
  'notification.comment.general.subject': 'תגובה חדשה על "{contentTitle}"',
  'notification.comment.general.body': '{commenterName} הגיב על "{contentTitle}": "{commentText}"',
  'notification.comment.reply.subject': 'תגובה לתגובתך',
  'notification.comment.reply.body': '{replierName} הגיב לתגובתך על "{contentTitle}": "{replyText}"',
  'notification.comment.like.subject': 'התגובה שלך זכתה לאהדה',
  'notification.comment.like.body': '{likerName} אהבתי את התגובה שלך',
  // Content-specific comment notifications
  'notification.comment.fanArt.subject': 'תגובה חדשה על יצירת אמנות של מעריץ: "{contentTitle}"',
  'notification.comment.fanArt.body': '{commenterName} הגיב על יצירת האמנות שלך "{contentTitle}": "{commentText}"',
  'notification.comment.event.subject': 'תגובה חדשה על האירוע: "{contentTitle}"',
  'notification.comment.event.body': '{commenterName} הגיב על האירוע "{contentTitle}": "{commentText}"',
  'notification.comment.revision.subject': 'הערה חדשה על התיקון',
  'notification.comment.revision.body': '{commenterName} הגיב על התיקון שלך: "{commentText}"',
  'notification.comment.feedback.subject': 'תגובה חדשה על משוב',
  'notification.comment.feedback.body': '{commenterName} הגיב על הבעיה שהעלית: "{commentText}"',
  // Welcome notification
  'notification.welcome.body': 'אנו שמחים על הצטרפותך אלינו.',
  'notification.welcome.cta.reader': 'התחל לקרוא!',
  'notification.welcome.cta.writer': 'התחל לכתוב!',
  // Strings for extra section
  'notificationExtra.workshopStoryStatus.goToStory': 'עבור לסיפור',
  // UI strings for enhanced notifications
  'notifications.menu.community': 'קהילה',
  'notifications.menu.reading': 'קריאה וספרייה',
  'notifications.menu.system': 'מערכת',
  'notifications.empty': 'הכל מוכן! אין כאן שום דבר חדש.',
  'notifications.empty.category': 'נסה לבדוק קטגוריות אחרות או לשנות את העדפות ההודעות שלך.',
  'notifications.error.loadFailed': 'לא ניתן לטעון את ההודעות: {error}',
  'notifications.loadMore': 'טען עוד',
  // Action button labels
  'notifications.action.viewStory': 'הצג סיפור',
  'notifications.action.readChapter': 'קרא את הפרק',
  'notifications.action.goToWorkshop': 'עבור לסדנה',
  'notifications.action.viewUniverse': 'הצג יקום',
  'notifications.action.viewBlog': 'הצג בלוג',
  'notifications.action.readPost': 'קרא את הפוסט',
  'notifications.action.viewComments': 'הצג תגובות',
  // Category descriptions
  'notifications.category.workshop.description': 'הודעות על פעילויות יצירת תוכן וניהול תוכן',
  'notifications.category.community.description': 'הודעות על אינטראקציות חברתיות ומעורבות בקהילה',
  'notifications.category.reading.description': 'הודעות על תוכן חדש ופעילויות קריאה',
  'notifications.category.system.description': 'הודעות מערכת ועדכונים חשובים'
};