export default {
    'settings.biography': 'ביוגרפיה',
    'settings.biography.placeholder': 'קצת על עצמך שיהיה מוצג בפרופיל שלך.',
    'settings.avatar.title': 'אווטר',
    'settings.avatar.own': 'האווטר שלך',
    'settings.avatar.upload': 'בחירת תמונה',
    'settings.email': 'אימיילים',
    'settings.email.msg': 'אימיילים המשויכים לחשבונך',
    'settings.email.verified.false': 'לא מאומת',
    'settings.email.verified.true': 'אימייל מאומת',
    'settings.email.add': 'הוספת אימייל',
    'settings.languages.title': 'הגדרות שפה',
    'settings.languages.notice': 'באופן רשמי, אנגלית היא השפה היחידה שתומכת כרגע. שפות אחרות זמינות בזכות מתנדבים מדהימים, אך הן עדיין עשויות להיות חסרות מידע.',
    'settings.languages.join': 'אם ברצונך לעזור לנו, תוכל לתרגם את Literary Universe גם.',
    'settings.name.title': 'שם אמיתי',
    'settings.name.given': 'שם פרטי',
    'settings.name.family': 'שם משפחה',
    'settings.username.change': 'שינוי שם משתמש',
    'settings.username.label': 'שם משתמש',
    'settings.password.title': 'שינוי סיסמה',
    'settings.password.current': 'סיסמה נוכחית',
    'settings.password.new': 'סיסמה חדשה',
    'settings.password.repeat': 'חזור על הסיסמה החדשה',
    'settings.password.nomatch': 'הסיסמה החדשה אינה תואמת!',
    'settings.password.reset': 'איפוס הסיסמה שלך',
    'settings.password.resetSend': 'נשלח אליך אימייל עם הוראות לאיפוס הסיסמה שלך!',
    'settings.socialConnectTitle': 'התחבר עם חשבונות משירותים אחרים',
    'settings.socialDisconnect': 'ניתוק',
    'settings.socialConnect': 'התחברות',
    'settings.loginWith': 'התחברות עם {service}',
    'settings.connectTo': 'התחברות ל- {service}',
    'settings.export.title': 'יצוא נתונים',
    'settings.export.explain': 'זה יאפשר לך לקבל את כל הנתונים שמאוחסנים במסד הנתונים שלנו בפורמט JSON.',
    'settings.export.submit': 'יצוא נתונים',
    'settings.delete.title': 'מחיקת חשבון',
    'settings.delete.warning': `WARNING: By deleting your account you loose access to this account and
    there is no way of getting it back. Note that this might not automatically delete your published works,
    comments, etc. Please refer to Terms of Service for details.`,
    'settings.delete.confirm': 'רק כדי לוודא. האם אתה בטוח שברצונך למחוק את החשבון שלך?',
    'settings.delete.cancel': 'אני לא רוצה למחוק את החשבון שלי',
    'settings.delete.submit': 'מחק את החשבון שלי',
    'settings.legal.title': 'הסכמים להסכמות משתמש',
    'settings.legal.explained': 'כאן תוכל לנהל את ההסכמה שלך למסמכים משפטיים שונים.',
    'settings.name.private': 'השם יהיה פרטי',
    'settings.emailSubscriptions.title': 'הגדרות התראות באימייל',
    'settings.emailSubscriptions.explain': 'בחר אילו התראות באימייל אתה רוצה לקבל מאיתנו.',
    'settings.emailSubscriptions.newsletter': 'ניוזלטר מזדמן',
    'settings.profile': 'הגדרות פרופיל',
    'settings.account': 'הגדרות חשבון',
    'settings.legal.export.download': 'הורדת הנתונים שלך',
    'settings.legal.export.gathering': 'מאגד את הנתונים שלך... ייתכן וזה ייקח זמן מה.',
    'settings.gender.title': 'המין שלך',
    'settings.gender.usage': 'מידע זה יישאר פרטי. אנו משתמשים בנתונים אלו לצורך ניתוח פלטפורמה וניתוח אנונימי ליוצרים כאשר אתה קורא את הסיפורים שלהם.',
    'settings.age.title': 'הגיל שלך',
    'settings.age.explicit': 'הצג תוכן מפורט (גיל 21+)',
    'settings.age.usage': 'מידע זה יישאר פרטי. לפי חובת חוק אנו חייבים לשאול על הגיל שלך. אנו משתמשים בנתונים אלו לצורך ניתוח פלטפורמה, הצגת תוכן בהתאם לדירוגים וניתוח אנונימי ליוצרים כאשר אתה קורא את הסיפורים שלהם.',
    'settings.country.title': 'המדינה שלך',
    'settings.country.usage': 'לפי חובת חוק אנו חייבים לשאול על המדינה שלך כדי להגיב לבקשות מממשלתיות. אנו משתמשים בנתונים אלו לצורך ניתוח פלטפורמה וניתוח אנונימי ליוצרים כאשר אתה קורא את הסיפורים שלהם. אם ברצונך תוכל להציג מידע זה בפרופיל שלך.',
    'settings.country.public': 'הצג את המדינה שלך בצורה ציבורית',
    'settings.country.select': 'בחר את המדינה שלך',
    'settings.emailSubscriptions.newsletterTech': 'רשימת תפוצה מתוך המפתחים שלנו',
    'settings.emailSubscriptions.newsletterFeatures': 'מידע על תכונות חדשות',
    'settings.emailNotifications.title': 'התראות',
    'settings.emailNotifications.pm': 'הודעות חדשות',
    'settings.emailNotifications.newChapters': 'פרקים חדשים',
    'settings.resetPasswordEmailSend': 'שלחנו לך הוראות כיצד לאפס את הסיסמה שלך לכתובת הדוא"ל שלך.',
    'settings.theme.title': 'עיצוב האתר',
    'settings.theme.label': 'ערכת נושא לאתר',
    'settings.theme.light': 'בהיר',
    'settings.theme.dark': 'כהה',
    'settings.links.title': 'קישור לאתרים אחרים שלך',
    'settings.links.description': 'הקישורים הללו יוצגו בדף הפרופיל שלך.',
    'settings.links.website': 'האתר האישי שלך',
    'settings.links.social': 'אתרים אחרים',
    'settings.links.select': 'בחירת אתר להוספה',
    // 2FA
    'settings.2fa.title': 'אימות דו-שלב',
    'settings.2fa.explained': 'אימות דו-שלב מספק שכבת אבטחה נוספת לחשבונך על ידי הוספת שלב נוסף של אימות במהלך התחברות. זה מונע מפעילים זדוניים לגשת לחשבונך אם השלב הראשון של התחברות נפגע.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'אימות דו-שלב עם קוד OTP יוצר על ידי יישומים לאימות (כמו Authy, Google/Microsoft Authenticator ועוד) שאתה מזין בעת התחברות.',
    'settings.2fa.otpModalAria': 'שיטת OTP של 2FA',
    'settings.2fa.otpAdd': 'הוסף 2FA OTP',
    'settings.2fa.confirmCode': 'הקוד שמוצג ביישום האימות שלך',
    'settings.2fa.svgAlt': 'קוד QR עבור אפליקציית האימות',
    'settings.2fa.codeHeading': 'אם אינך יכול לסרוק את קוד ה-QR, תוכל להזין את הקוד הבא באופן ידני:',
    'settings.2fa.instructionsTitle': 'הוראות',
    'settings.2fa.instructions1': 'התקן ופתח את יישום האימות של בחירתך (Authy, Google/Microsoft Authenticator, FreeOTP ועוד)',
    'settings.2fa.instructions2': 'בחר "הוסף חשבון" (יכול להיות סמל "+" גלוי או מוסתר בתפריט)',
    'settings.2fa.instructions3': 'סרוק את קוד ה-QR שמוצג על המסך כאן או אם אי אפשר, הזן את הקוד למטה.',
    'settings.2fa.instructions4': 'הקלד את ה-6 מספרים שמופיעים על המסך לתוך הקלט כאן כדי לסיים.',
    'settings.2fa.saved': 'אימות דו-שלב הוקמה בהצלחה!',
    'settings.2fa.disableOTP': 'נטרל את אימות דו-שלב עם קוד OTP',
    // Web3
    'settings.web3.legend': 'חיבור כרסום Web3',
    'settings.web3.explained': 'ניתן לחבר את ארנק הקריפטו שלך בפרוטוקול Web3 לחשבון היצירתי שלך. לאחר החיבור, תוכל להתחבר עם הארנק שלך ולעשות עוד הרבה דברים בעתיד כשנרחיב את ההצעה שלנו בפרוטוקול Web3.',
    'settings.web3.connect': 'חבר את הארנק שלך',
    'settings.web3.address': 'כתובת מחוברת: {address}',
    'settings.web3.verify': 'חתום על הכתובת שלך',
    'settings.web3.verify.explained': 'כדי לאמת שכתובת זו שייכת לך, נבקש ממך לחתום על הודעה כדי לוודא את בעלותך על הארנק.',
    'settings.web3.verified': 'מאומת',
    'settings.web3.verificationMessage': 'מאמת משתמש {username} עבור Literary Universe. קוד: {code}',
    'settings.web3.unlink': 'הסר את הארנק',
    'settings.web3.linkingMessage': 'אנא אשר שברצונך לקשר את הארנק שלך ל-Literary Universe. קוד: {code}',
    'settings.web3.linkError': 'כתובת זו כבר מופיעה במסד הנתונים שלנו ולא ניתן להקצות לה!',
    // Reader settings
    'settings.reader.title': 'הגדרות הקורא',
    'settings.reader.darkMode': 'תמיד להציג במצב כהה',
    'settings.reader.asideView': 'הצג חלונית צדדית קסומה',
    'settings.reader.textSize': 'הצג טקסט בגופן גדול יותר',
    // Accessibility
    'settings.accessibility.title': 'נגישות לקורא',
    'settings.accessibility.openDyslexic': 'השתמש בגופן OpenDyslexic',
    'settings.accessibility.paragraphStripes': 'שנה צבע רקע אלטרנטיבי בפסקה',
    'settings.accessibility.paragraphHighlighting': 'הדגש את הפסקה הנוכחית שאתה מרחף מעליה',
    'settings.accessibility.ruler': 'צרף סרגל לעכבר',
    'settings.tab.legal': 'מסמכים משפטיים',
    'settings.tab.exportDelete': 'יצוא נתונים ומחיקת חשבון'
};