export default {
    'workshop.title': 'העבודה שלך',
    'workshop.noneassigned': 'לא הוקצו לך עדיין.',
    'workshop.notavailable': 'תכונה זו עדיין לא זמינה.',
    'workshop.none': `אין לך כרגע {type, select,
      universe {יצור עולם}
      story {סיפור}
      fanfiction {פאן פיקשן}
      other {}
    }. צור אחד עכשיו!`,
    'workshop.collab': 'עבודה שיתופית',
    'workshop.betareadings': 'קריאות בטא',
    'workshop.translations': 'תרגומים',
    'workshop.createnew': 'צור חדש...',
    'workshop.story.standalone': 'סיפור עצמאי',
    'workshop.story.standalone.desc': 'זהו סיפור עצמאי.',
    'workshop.controlpanel': '{name} לוח בקרה',
    'workshop.universe.page': 'דף יחידה',
    'workshop.fictionaltime': 'זמן מדומה',
    'workshop.dashboard.name': '{name} לוח מחוונים',
    'workshop.stories.in': 'סיפורים ב {universe}',
    'workshop.universe.nostories': 'אין סיפורים ביחידה זו.',
    'workshop.story.chapter.add': 'פרק חדש',
    'workshop.universe.new': 'צור יחידה חדשה',
    'workshop.universe.publish': 'פרסם יחידה',
    'workshop.universe.publishing.notice': 'אם לא תפרסם את היחידה, היא תפורסם אוטומטית כאשר הסיפור הראשון המחובר ליחידה ייפורסם.',
    'workshop.universe.settings': '{universe} הגדרות יחידה',
    'workshop.universe.publishedOn': 'היקום הזה פורסם ב- {date, date, long} {date, time, short}',
    'workshop.work.deletion.contactUs': 'אם אתה זקוק לעזרה, <contact>צור איתנו קשר</contact>.',
    'workshop.work.delete.restrictions': `ניתן למחוק את היקום הזה {type, select,
    universe {רק אם אין בו סיפורים שפורסמו, ואת הסיפור}
    story {רק אם}
    other {עובד רק אם}} פורסם לפני פחות מחודש. זקוק לעזרה לאחר מכן? <contact>צור איתנו קשר</contact>.`,
    'workshop.work.delete.notAllowed': `זה {type, select,
    universe {universe}
    story {story}
    other {work}
  } לא ניתן עוד למחוק באמצעות שירות עצמי. אם אתה צריך להסיר אותו, <contact>צור איתנו קשר</contact> ואנו נעבוד איתך כדי להסיר אותו בבטחה.`,
    'workshop.work.delete.notAllowed.plain': `זה {type, select,
    universe {universe}
    story {story}
    other {work}
  } לא ניתן עוד למחוק באמצעות שירות עצמי. אם אתה צריך להסיר אותו, פנה אלינו בכתובת deletions@literaryuniverse.com ואנו נעבוד איתך כדי להסיר אותו בבטחה.`,
    'workshop.work.danger.delete.desc': `מחק לצמיתות את היקום הזה {type, select,
    universe {ואת נתוני הסדנה המקושרים אליו}
    story {את הסיפור עם כל הפרקים, הסטטיסטיקות והקשרים לסדנה}
    other {את העבודה ואת הנתונים הקשורים אליה}
  }.`,
    'workshop.work.makePrivate.impact': `ביצוע פעולה זו {type, select,
    universe {universe}
    story {story}
    other {work}
  } מסיר אותה מהגילוי והחיפוש. אנשים שכבר יש להם אותה בספרייה שלהם שומרים על הגישה אליה. משתמשים חדשים לא יכולים להוסיף אותה לספרייה שלהם יותר{type, select,
    story { או לקנות אותה, אלא אם כן אתה נותן להם אותה במתנה}
    other {}
  }.`,
    'workshop.work.private.notice': `זה {type, select,
    universe {יקום}
    story {סיפור}
    other {עבודה}
  } הוא כרגע פרטי. למחזיקי הספרייה הקיימים עדיין יש גישה. משתמשים חדשים אינם יכולים להוסיף אותו לספרייה שלהם{type, select,
    story { או לקנות אותו}
    other {}
  }.`,
    'workshop.work.makePrivate.button': `צור {type, select,
    universe {יקום}
    story {סיפור}
    other {עבודה}
  } פרטי`,
    'workshop.work.makePrivate.modalAria': `מודל אישור ליצירת {type, select,
    universe {universe}
    story {story}
    other {work}
  } private`,
    'workshop.work.makePrivate.warning': `הפיכת {type, select,
    universe {universe}
    story {story}
    other {work}
  } לפרטי תסיר אותו מהחיפוש והגילוי הציבוריים.`,
    'workshop.work.makePublic.button': `צור {type, select,
    universe {יקום}
    story {סיפור}
    other {עבודה}
  } ציבורי`,
    'workshop.work.makePublic.modalAria': `מודל אישור ליצירת {type, select,
    universe {universe}
    story {story}
    other {work}
  } Public`,
    'workshop.work.makePublic.warning': `פרסום {type, select,
    universe {universe}
    story {story}
    other {work}
  } לציבור הרחב יאפשר לגלות אותו מחדש ויאפשר למשתמשים חדשים להוסיף אותו לספרייתם{type, select,
    story { או לרכוש אותו}
    other {}
  }.`,
    'workshop.universe.dangerZone': 'אזור סכנה',
    'workshop.universe.dangerZone.desc': 'ניתן למחוק יקום זה רק אם אין בו סיפורים שפורסמו והוא פורסם לפני פחות מחודש. אם אתה צריך למחוק אותו לאחר תקופת ההגבלה הזו, אנא פנה אלינו.',
    'workshop.universe.delete.modalAria': 'מודל אישור למחיקת יקום',
    'workshop.universe.delete.warning': 'האם אתה בטוח שברצונך למחוק את "{title}"? פעולה זו אינה ניתנת לביטול.',
    'workshop.universe.delete.button': 'מחק יקום',
    'workshop.universe.description': 'תיאור היחידה',
    'workshop.settings.title': 'כותרת',
    'workshop.description': 'תיאור',
    'workshop.language.primary': 'שפת עיקרית',
    'workshop.publication.options': 'אפשרויות פרסום',
    'workshop.rating': 'דירוג כללי',
    'workshop.universe.rating.desc': 'סיפורים ופאנפיקציה מעל הדירוג הזה ייחבאו מרשימת דף היחידה ממשתמשים אנונימיים וממשתמשים שאינם בגיל המתאים.',
    'workshop.universe.license': 'רישיון היחידה',
    'workshop.universe.genre.pick': 'בחר ז\'אנר עבור היחידה',
    'workshop.story.genre.pick': 'בחר ז\'אנרים עבור הסיפור',
    'workshop.cover': 'שער',
    'workshop.nothingtosee': 'אין כאן דבר...',
    'workshop.story.cannon': 'סיפור קנוני',
    'workshop.story.cannon.desc': 'סיפור זה הוא קנוני ביחידה {universe}',
    'workshop.story.cannon.desc.create': 'סיפור זה ייווצר כסיפור קנוני ביקום {universe}.',
    'workshop.story.fanfiction.search': 'הקלידו את שם היקום (הוא צריך להיות בספרייה שלכם). ואז בחרו מההצעות.',
    'workshop.story.error.nogenres': 'עליכם לבחור לפחות סוג ז\'אנר אחד.',
    'workshop.story.error.toomanygenres': 'ניתן לבחור רק שני ז\'אנרים לסיפור.',
    'workshop.story.error.fanfiction.selectuniverse': 'עליכם לבחור יקום מקורי עבור הסיפור שלכם!',
    'workshop.story.error.tags.toomany': 'ניתן להוסיף עד 10 תגיות לסיפור.',
    'workshop.thema.primary': 'סיווג ראשי של נושא',
    'workshop.thema.secondary': 'סיווגים משניים של נושאים',
    'workshop.thema.secondary.max': 'ניתן להוסיף עד {max} סיווגים משניים.',
    'workshop.thema.selectedCode': 'קוד: {code}',
    'workshop.thema.searchPlaceholder': 'חיפוש לפי שם, לדוגמה "מדע בדיוני"',
    'workshop.thema.quickRef': '📖 התייחסות מהירה לנושא',
    'workshop.story.new': 'צור סיפור חדש',
    'workshop.story.publishing.notice': 'הסיפור יפורסם אוטומטית ברגע שתפרסמו את הפרק הראשון.',
    'workshop.story.published.congratulations.title': 'מזל טוב! הסיפור שלך פורסם',
    'workshop.story.published.congratulations.heading': 'מזל טוב! הסיפור שלך פורסם',
    'workshop.story.published.congratulations.description': 'מסע הכתיבה שלך נמשך. הסיפור שלך מוכן כעת להיחשף ולקריאה מהנה על ידי הקוראים.',
    'workshop.story.published.congratulations.publicStoryBtn': 'עבור לדף הסיפור',
    'workshop.story.published.congratulations.imageAlt': 'איור חגיגי לסיפור שפורסם',
    'workshop.writingHistory.title': 'Writing history',
    'workshop.writingHistory.sessions': 'Writing sessions',
    'workshop.settings.edit': 'עריכת הגדרות',
    'workshop.story.publishedOn': 'הסיפור הזה פורסם ב- {date, date, long} {date, time, short}',
    'workshop.story.settings': 'הגדרות הסיפור',
    'workshop.story.monetizationTitle': 'הפקת רווחים מתוכן',
    'workshop.settings.basic': 'הגדרות בסיסיות',
    'workshop.settings.genres': 'ז\'אנרים (מקסימום 2)',
    'workshop.story.license': 'רישיון הסיפור',
    'workshop.story.settings.universe': 'הגדרות יקום',
    'workshop.story.dangerZone': 'אזור סכנה',
    'workshop.story.dangerZone.desc': 'פעולות אלה משפיעות על אופן ארגון הסיפור שלך בין יקומים. יש לנהוג בזהירות.',
    'workshop.story.universe.assign.missing': 'אנא בחר יקום כדי להמשיך.',
    'workshop.story.universe.assignTitle': 'יצירת או הקצאת יקום',
    'workshop.story.universe.assign.desc': 'צרף את הסיפור הזה ליקום קיים, או צור יקום חדש לגמרי באמצעות פרטי הסיפור.',
    'workshop.story.universe.assign.mode': 'אפשרות יקום',
    'workshop.story.universe.assign.existing': 'הקצה ליקום קיים',
    'workshop.story.universe.assign.create': 'צור יקום חדש מהסיפור הזה',
    'workshop.story.universe.assign.loading': 'טוען את היקומים שלך...',
    'workshop.story.universe.assign.select': 'בחר יקום',
    'workshop.story.universe.assign.placeholder': 'בחר יקום',
    'workshop.story.universe.assign.none': 'אין לך עדיין יקומים. צור יקום חדש כדי להמשיך.',
    'workshop.story.universe.assign.publishNote': 'הסיפור הזה כבר פורסם, ולכן גם היקום החדש יפורסם.',
    'workshop.story.universe.assign.createBtn': 'צור יקום',
    'workshop.story.universe.assign.trigger': 'יצירת או הקצאת יקום',
    'workshop.story.universe.standalone.title': 'הפוך את הסיפור לעצמאי',
    'workshop.story.universe.standalone.heading': 'להוציא את הסיפור הזה מהיקום שלו?',
    'workshop.story.universe.standalone.desc': 'הסיפור הזה יוסר מהיקום ויופיע כסיפור עצמאי.',
    'workshop.story.universe.standalone.current': 'היקום הנוכחי: {title}',
    'workshop.story.universe.standalone.warning1': 'קוראים המעיינים ביקום לא יראו עוד את הסיפור הזה ברשימה.',
    'workshop.story.universe.standalone.warning2': 'קישורים קיימים המפנים לגרסת היקום של סיפור זה עשויים להפסיק לפעול.',
    'workshop.story.universe.standalone.warning3': 'תוכל לצרף את הסיפור ליקום שוב מאוחר יותר מהגדרות הסיפור.',
    'workshop.story.universe.standalone.trigger': 'הפוך את הסיפור לעצמאי',
    'workshop.settings.tags': 'תגיות',
    'workshop.settings.tags.placeholder': 'Add a tag…',
    'workshop.revision': 'תיקון',
    'workshop.revisions.title': '{story}: {chapter} תיקונים',
    'workshop.revisions.current': 'טיוטה נוכחית',
    'workshop.revisions.new.beta': 'צור תיקון חדש מהטיוטה.',
    'workshop.revisions.new.public': 'צור תיקון ציבורי חדש מהטיוטה.',
    'workshop.revisions.toeditor': 'עבור לעורך',
    'workshop.revisions.comments': 'הערות על התיקון',
    'workshop.revisions.comments.title': '{story}: {chapter} - תיקון {revision} - הערות',
    'workshop.revisions.comments.list': `!{revision}: {language}, {publication, select,
      beta {עבור קוראי ביתה}
      readers {ציבורי}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'עליכם ליצור תיקון תחילה.',
    'workshop.revisions.comments.select': 'בחר גרסה',
    'workshop.collaborators.noresults': 'אין תוצאות',
    'workshop.collaborators.add.beta': 'הוסף קורא בטא',
    'workshop.collaborators.add.collaborator': 'הוסף שותף',
    'workshop.collaborators.add.translator': 'הוסף מתרגם',
    'workshop.collaborators.language.add': 'צור תרגום חדש',
    'workshop.translations.stories': 'תרגומים - סיפורים',
    'workshop.translations.universes': 'תרגומים - יוניברסים',
    'workshop.revisions.beta.none': 'אין גרסאות חדשות כרגע.',
    'reader.asidetoggle': 'החלף מידע צדדי',
    'workshop.translation.original': 'מקורי:',
    'workshop.translation.original.title': 'כותרת מקורית:',
    'workshop.translation.original.description': 'תיאור מקורי:',
    'workshop.translation.original.cover': 'תמונת כריכה מקורית',
    'workshop.translation.original.tags': 'תגיות מקוריות',
    'workshop.cover.alt': 'תמונת כריכה',
    'workshop.translation.updatedOrig': 'עדכון אחרון של המקור: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'עדכון אחרון של התרגום: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'תיקון אחרון {revision, number}, של המקור: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'תיקון אחרון {revision, number}, של התרגום: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.monetization.minPriceNotice': 'המחירים נבדקים מול הסכומים המינימליים הנדרשים לרישיון לפני שניתן לשמור או לסנכרן אותם.',
    'workshop.monetization.storyPrices': 'מחירי הסיפורים',
    'workshop.monetization.minPrice': 'מינימום: {price}',
    'workshop.monetization.revenueSplit': 'חלוקת ההכנסות',
    'workshop.monetization.userId': 'מזהה המשתמש התורם',
    'workshop.monetization.splitTotal': 'סה"כ חלוקת התרומות: {total}%',
    'workshop.monetization.arcPricing': 'תמחור קשת',
    'workshop.monetization.arcRange': 'פרקים {from}–{to}',
    'workshop.monetization.arcEnabled': 'למכור את הקשת הזו בנפרד',
    'workshop.monetization.saved': 'הגדרות התמחור נשמרו.',
    'workshop.monetization.synced': 'מוצרי Stripe והמחירים שלהם סונכרנו.',
    'workshop.monetization.syncStripe': 'סנכרון עם Stripe',
    'workshop.monetization.fullStoryUnfinishedWarning': 'You can set a full story price before the story is complete, but the full-story purchase option will not activate until the story is marked as finished.',
    'workshop.collaborators.premium': `כדי להוסיף עוד {type, select,
    collaborator {שותפים}
    beta {קוראי ביטא}
    translator {מתרגמים}
    other {}
  }, עליך לשדרג את תוכנית החברות שלך.`,
    'workshop.collaborators.requests.sent': 'בקשות שנשלחו',
    'workshop.collaborators.requests.invite': `התבקשת להפוך ל- {role, select,
    beta {קורא ביטא}
    translator {מתרגם}
    collaborator {שותף}
    other {}
  } עבור הבא:`,
    'workshop.collaborators.requests.dashboard': `!הוזמנת לשתף פעולה ב- {count, plural,
    zero {אין עבודה}
    one {עבודה אחת}
    other {עבודות ספרותיות}
  }.`,
    'workshop.collaborators.language.added': 'נוסף שפה',
    'workshop.story.noChaptersFound': 'לא נמצאו פרקים.',
    'workshop.outliner.title': 'Storylines Outliner – {storyTitle}',
    'workshop.outliner.addScene': 'שם עמודה חדש בסצנה',
    'workshop.outliner.addSceneAction': 'הוסף סצנה',
    'workshop.outliner.sceneName': 'שם הסצנה…',
    'workshop.outliner.hideArchived': 'הסתר בארכיון',
    'workshop.outliner.showArchived': 'הצג ארכיון',
    'workshop.outliner.newStoryline': 'שם עלילה חדש…',
    'workshop.outliner.noChapters': 'השתמש ב"תכנן פרק" כדי לתכנן את מבנה הסיפור שלך, או כתוב את הפרק הראשון שלך בסדנה.',
    'workshop.outliner.noScenes': 'אין עדיין סצנות',
    'workshop.outliner.storyline': 'עלילה',
    'workshop.outliner.dragHint': 'גרור כרטיסים בין עמודות הסצנות ובין קווי העלילה.',
    'workshop.outliner.editCard': 'ערוך כרטיס מתאר',
    'workshop.outliner.cardDetailsPlaceholder': 'תאר את הקצב, מטרת הסצנה, הקונפליקט המרכזי וכל הערות אחרות.…',
    'workshop.outliner.dragScene': 'סצנת גרירה',
    'workshop.outliner.written': 'סמן כפי שנכתב',
    'workshop.outliner.emptyCard': '(ריק)',
    'workshop.outliner.planChapter': 'פרק התוכנית',
    'workshop.outliner.addChapterHint': 'צור פרק תכנון. ברגע שפרק אמיתי יופיע בסיפור שלך, הוא יופיע כאן באופן אוטומטי והמקום הזה יוחלף.',
    'workshop.outliner.chapterTitlePlaceholder': 'כותרת הפרק…',
    'workshop.outliner.hypothetical': 'טיוטה',
    'workshop.outliner.deleteChapter': 'מחק פרק מתוכנן',
    'workshop.fanfic.needUniverseInLibrary': 'יש הרבה יקומים בעולם. אנא הוסף את אלה שברצונך לכתוב בספרייה שלך קודם כדי שנוכל למצוא אותם.',
    'workshop.fanfic.findUniverse': 'לך למצוא יקום מדהים!',
    'workshop.encSettings': 'הגדרות האנציקלופדיה',
    'workshop.collaborators.removeUser': 'הסר משתמש',
    'workshop.collaborators.cancelInvite': 'בטל הזמנה',
    'workshop.collaborators.mode.search': 'חפש משתמשים',
    'workshop.collaborators.mode.email': 'הזמן באמצעות דוא"ל',
    'workshop.collaborators.sendInvite': 'שלח הזמנה',
    'workshop.collaborators.emailSent': 'ההזמנה נשלחה!',
    'workshop.universe.createFirstStory': 'צור את הסיפור הראשון',
    'workshop.storylines': 'סיפורים',
    'workshop.scenesManager': 'מנהל הסצינות',
    'workshop.sceneManager.title': 'מנהל הסצנה – {storyTitle}',
    'workshop.scene.create': 'צור סצנה',
    'workshop.scene.edit': 'ערוך סצנה',
    'workshop.scene.empty': 'עדיין לא תוכננו סצנות לפרק זה.',
    'workshop.scene.checklist': 'סצנות בפרק',
    'workshop.scene.checklist.empty': 'עדיין לא הוקצו סצנות לפרק זה.',
    'workshop.scene.title.placeholder': 'כותרת הסצנה…',
    'workshop.scene.details': 'פרטי הסצנה',
    'workshop.scene.assignments.hint': 'הקצו דמויות ומקומות מתוך האנציקלופדיה שלכם.',
    'workshop.collaborators.addRoleForLang': 'הוסף {role} עבור {language}',
    'workshop.beta.revisionInfo': 'זוהי גרסה {revision, number}, שנוצרה ב- {createdAt, date, long}.',
    'workshop.story.notes.title': 'ההערות שלך עבור {storyTitle}',
    'workshop.story.notes.desc': 'הערות כלליות עבור הסיפור.',
    'workshop.story.notes.tile': 'הערות כלליות',
    'workshop.story.alternateFormats.tile': 'פורמטים חלופיים',
    'workshop.story.alternateFormats.title': '{storyTitle}: פורמטים חלופיים',
    'workshop.story.alternateFormats.arcs.title': 'קשתות',
    'workshop.story.alternateFormats.arcs.add': 'הוסף קשת',
    'workshop.story.alternateFormats.arc.defaultTitle': 'Arc {index}',
    'workshop.story.alternateFormats.arc.name': 'שם הקשת',
    'workshop.story.alternateFormats.arc.from': 'מהפרק',
    'workshop.story.alternateFormats.arc.to': 'לפרק',
    'workshop.story.alternateFormats.arc.uploads': 'קבצים',
    'workshop.story.alternateFormats.arc.upload.epub': 'העלה EPUB',
    'workshop.story.alternateFormats.arc.upload.pdf': 'העלה קובץ PDF',
    'workshop.story.alternateFormats.epub.generate': 'יצירת EPUB',
    'workshop.story.alternateFormats.epub.openGenerated': 'פתח EPUB שנוצר',
    'workshop.story.alternateFormats.epub.generatedAt': 'נוצר ב- {generatedAt, date, medium} ב- {generatedAt, time, short}',
    'workshop.story.alternateFormats.epub.generationFailed': 'הפקת EPUB נכשלה.',
    'workshop.story.alternateFormats.epub.saveArcBeforeGeneration': 'שמור תחילה קובץ זה כדי לאפשר יצירת EPUB.',
    'workshop.story.alternateFormats.externalUrls.secureStorageRequired': 'קישורים חיצוניים אינם זמינים עבור סיפורים המורשים תחת "Literary Universe". במקום זאת, העלו קבצים כדי שיישמרו באחסון מוצפן.',
    'workshop.story.alternateFormats.fullStory.title': 'קובץ הסיפור המלא',
    'workshop.story.alternateFormats.ongoingAccess.title': 'גישה מתמשכת',
    'workshop.story.alternateFormats.ongoingAccess.allAvailable': 'כל הפרקים הזמינים כרגע',
    'workshop.story.alternateFormats.ongoingAccess.perChapter': 'לפי פרק (עם פרסום הפרקים)',
    'workshop.hideOrgs': 'הסתר תוכן מארגונים',
    'workshop.translation.premium': 'כדי להוסיף תרגומים, עליך להיות מנוי לפחות בתוכנית Explorer.',
    'workshop.story.finished': 'הסיפור הושלם',
    'workshop.story.publishing.externalSellingNotice': 'מאחר ואתה מוכר מחוץ ליקום הספרותי, ניתן לפרסם את הסיפור כעת. קישורים לרשימת החנויות שלך יופיעו על הסיפור או בסוף הסיפור הנוכחי שאתה מפרסם כאן.',
    'workshop.shoppingExternal.kobo': 'Rakuten Kobo',
    'workshop.shoppingExternal.koboStore': 'חנות Rakuten Kobo',
    'workshop.shoppingExternal.koboStoreInternational': 'חנות בינלאומית',
    'workshop.sharing.publicURL': 'גרסה ציבורית',
    'workshop.fictionalTime.title': 'זמנים בדמיון עבור {universeName}',
    'workshop.fictionalTime.none': 'כרגע אין לך שום זמן בדיוני שהוגדר.',
    'workshop.fictionalTime.createNow': 'צור אחת כעת!',
    'workshop.fictionalTime.createTitle': 'צור זמן בדיוני חדש',
    'workshop.fictionalTime.editTitle': 'ערוך {ftName}',
    'workshop.fictionalTime.formDescription': `Here you can create your own fictional time. Currently, this tool is limited and is only capable of creating
        symmetric times. This means you won't be able to recreate the Mayan calendar or the Gregorian calendar. At this moment,
        this tool expects that all time periods are always the same, e.g., months always have 30 days with no exceptions and so
        on. We will address this in later versions, but until then, this tool is more suited for creating primarily
        sci-fi based time systems.`,
    'workshop.fictionalTime.timeName': 'שם הזמן',
    'workshop.fictionalTime.basicInfo': 'מידע בסיסי',
    'workshop.fictionalTime.timeSetup': 'הגדרת הזמן',
    'workshop.fictionalTime.linkedToET': 'האם הזמן הזה מתחיל בתאריך עפ"י הלוח הגרגוריאני (תאריך על פי כדור הארץ)?',
    'workshop.fictionalTime.timeDeclaration': 'הצהרת הזמן',
    'workshop.fictionalTime.declarationLocation': 'Where should the time name be declared?',
    'workshop.fictionalTime.declarationBefore': 'לפני יחידות',
    'workshop.fictionalTime.declarationAfter': 'אחרי יחידות',
    'workshop.fictionalTime.declarationNone': 'אף אחד',
    'workshop.fictionalTime.units': 'יחידות',
    'workshop.fictionalTime.ETStart': 'תאריך התחלה של הזמן הזה',
    'workshop.fictionalTime.unitsDescFirst': 'כמה יחידות יש ביחידה הזו מילישניות?',
    'workshop.fictionalTime.unitsDesc': 'כמה יחידות יש ביחידה הזו מהיחידה הקודמת?',
    'workshop.fictionalTime.unitsName': 'שם היחידה',
    'workshop.fictionalTime.unitsSeparator': 'מפריד מהיחידה הקודמת',
    'workshop.fictionalTime.unitAdd': 'הוסף יחידה',
    'workshop.fictionalTime.clocks': 'שעונים',
    'workshop.fictionalTime.unitTransfer': 'העבר יחידות',
    'fictionalTime.pageStartElapsedTime': 'זמן שחלף מאז פתיחת הדף הזה',
    'fictionalTime.currentTime': 'זמן נוכחי',
    'workshop.shoppingExternal.options': 'אפשרויות רכישה חיצוניות',
    'workshop.shoppingExternal.explainer': 'אם הסיפור שלך נמכר במקום אחר, תוכל להגדיר כאן את הקישורים. הקישורים יוצגו במקום התוכן או בסוף התוכן שתבחר לתצוגה מקדימה.',
    'workshop.shoppingExternal.amazonStore': 'חנות אמזון',
    'workshop.shoppingExternal.amazon': 'אמזון',
    'workshop.shoppingExternal.storeName': 'שם חנות',
    'workshop.shoppingExternal.itemUrl': 'כתובת URL של הפריט',
    'workshop.shoppingExternal.storesOther': 'חנויות אחרות',
    'workshop.shoppingExternal.copyFromOriginal': 'Copy from original',
    'workshop.shoppingExternal.copyFromOriginalHelp': 'Pre-fill this translation\'s links with the values from the original. Review and save to apply.',
    'workshop.shoppingExternal.originalReadOnly': 'Only collaborators can edit the original story\'s external sales links. Switch to a translation tab to edit links for your language.',
    'fictionalTime.units.milliseconds': '{units, number} מילישניות',
    'fictionalTime.countdownToStart': 'ספירה לתחילת הזמן',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 יום }
      other {{days} ימים }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {שנייה}
      other {שניות}
    }}
    minutes {{units, plural,
      one {דקה}
      other {דקות}
    }}
    hours {{units, plural,
      one {שעה}
      other {שעות}
    }}
    days {{units, plural,
      one {יום}
      other {ימים}
    }}
    years {{units, plural,
      one {שנה}
      other {שנים}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'מתוך',
    'fictionalTime.inputSelectTimeUnit': 'בחר יחידת זמן',
    'fictionalTime.inputSelectETUnit': 'בחר יחידת זמן על פי זמן כדור הארץ',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'סרגל כלים צדדי',
    'workshop.writerSidebar.description': 'ברוכים הבאים לסיפור שלך! הסרגל הצדדי הזה מאפשר לך גישה נוחה לכל המשאבים הקשורים לסיפור שלך. בדוק את הסמלים למעלה כדי לראות את התגובות האחרונות, ההערות שלך ועוד הרבה יותר!',
    'workshop.story.authorsNotesExplained': 'ההערות שלך לקוראים לקריאה בתחילת הפרק.',
    'workshop.story.chapterSortSwitch': 'החלף את סדר הפרקים',
    'workshop.story.prolog': 'פרולוג',
    'workshop.story.chapter': 'פרק {sequence, number}',
    'workshop.work.includesAds': 'האם יש פרסומות או הצגת מוצרים בעבודה?',
    'workshop.universe.forumSettings': 'הגדרות פורום יחידה פנימית ביקום',
    'workshop.ratingAdjusted': 'בשל תלונות שקיבלנו, היינו חייבים להתאים את הדירוג שלך לזה שחשבנו ראוי. כתוצאה מכך, שינוי הדירוג מושבת כעת.',
    'workshop.rating.disabled.sexualContent': 'הדירוג נעול על "מפורש" (21+) מכיוון שבחרת "תוכן מיני" באזהרות התוכן.',
    'workshop.contentWarnings.title': 'אזהרות תוכן',
    'workshop.contentWarnings.description': 'בחר אזהרות תוכן רלוונטיות כדי ליידע את הקוראים על תוכן שעלול להיות רגיש.',
    'workshop.contentWarnings.graphicViolence': 'אלימות גרפית',
    'workshop.contentWarnings.graphicViolence.description': 'תיאורים מפורטים של מעשי אלימות, כולל אך לא מוגבל לפגיעה גופנית, שפיכות דמים, עינויים או כל תיאור מפורש אחר של אלימות העלול להיחשב כמעורר אי נוחות או גרפי יתר על המידה.',
    'workshop.contentWarnings.profanity': 'גסות',
    'workshop.contentWarnings.profanity.description': 'קללות וגידופים מוגזמים או גסים.',
    'workshop.contentWarnings.sensitiveContent': 'תוכן רגיש',
    'workshop.contentWarnings.sensitiveContent.description': 'תיאורים של עינויים, עבדות, התמכרות לסמים, מחלות נפש, התמכרויות, אזכור של אונס, פגיעה עצמית או כל תוכן אחר שעלול להיחשב כטראומטי או בוגר, שאינו נכלל בתגיות האזהרה. תוכן זה אינו מוערץ.',
    'workshop.contentWarnings.sexualContent': 'תוכן מיני',
    'workshop.contentWarnings.sexualContent.description': 'תוכן מיני מפורש (טקסט בלבד), תיאורים של סצנות מין. הדבר יקבע אוטומטית את הדירוג כ"מפורש" (21+).',
    'workshop.selectCollaborator': 'בחר שותף',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'טיוטה',
    'workshop.chapterStatus.scheduled': 'מתוזמן',
    'workshop.chapterStatus.published': 'פורסם',
    'workshop.story.continuedIn': 'אילו סיפורים ממשיכים את הסיפור הזה?',
    'workshop.story.continuedPlaceholder': 'בחר סיפור מתוך יישות זו',
    'workshop.universe.isAIGenerated': 'האם תוכן היקום נוצר על ידי AI?',
    'workshop.universe.isAIGeneratedTooltip': 'אנא דעו אותנו אם תוכן ביקום זה נוצר על ידי או בעזרת AI. אנו משתמשים במידע זה לתוויות תקניות ובשל דרך בה מתווצרות תוכניות AI עשויות להיות קיומן בגבולות והגבלות.',
    'workshop.story.isAIGenerated': 'האם הסיפור נוצר על ידי AI?',
    'workshop.story.isAIGeneratedTooltip': 'אנא דעו אותנו אם חלק מהסיפור נוצר על ידי או בעזרת AI. אנו משתמשים במידע זה לתוויות תקניות ובשל דרך בה מתווצרות תוכניות AI עשויות להיות קיומן בגבולות והגבלות.',
    'workshop.publicationAgreement.aria': 'הסכם פרסום לעבודה',
    'workshop.publicationAgreement.intro': 'אנו שמחים שבחרת לפרסם את היצירה היצירתית שלך איתנו. לפני שנמשיך, יש לך רק לבדוק את הסכם הפרסום שלנו, כדי להבין מה הוא אומר מהצד המשפטי.',
    'workshop.sortChapters': 'סדר מיון:',
    'workshop.sortChapters.ascending': 'מהתחלה',
    'workshop.sortChapters.descending': 'מההכי עדכני',
    'workshop.sortChapters.aria': 'בחר לאיזה דרך למיין את רשימת הפרקים',
    'workshop.hiatus.btn': 'שינוי סטטוס הסיפור להיאטוס',
    'workshop.cancelled.btn': 'שינוי סטטוס הסיפור למבוטל',
    'workshop.complete.btn': 'שינוי סטטוס הסיפור להושלם',
    'workshop.statusChange.modalTop': 'האם אתה בטוח שברצונך לשנות את הסטטוס ל',
    'workshop.statusName.hiatus': 'היאטוס',
    'workshop.statusName.cancelled': 'מבוטל',
    'workshop.statusName.completed': 'הושלם',
    'workshop.statusExplain.hiatus1': 'היאטוס אומר שאתה נוטש לזמן קצר את העבודה על סיפור זה מסיבה כלשהי. זה יגיד לקוראים שלך שהם לא צריכים לצפות לעדכונים חדשים בשבועות הקרובים או אפילו עד כמה חודשים.',
    'workshop.statusExplain.hiatus2': 'סטטוס ההיאטוס יוסר אוטומטית אם תפרסם פרק כלשהו. או שתוכל לשנות אותו בעצמך.',
    'workshop.statusExplain.hiatus3': 'אם תשמור על הסיפור שלך בהיאטוס למשך שישה חודשים, אנחנו נסמן באופן אוטומטי את הסיפור הזה כמבוטל.',
    'workshop.statusExplain.cancelled1': 'אנחנו מצטערים לשמוע שאתה לא יכול להמשיך לעבוד על הסיפור. מצד שני, אנחנו שמחים שאתה מוכן להודיע לקוראים שלך.',
    'workshop.statusExplain.cancelled2': 'ביטול הסיפור יודיע לקוראים שלך שהם לא צריכים לצפות לעדכונים חדשים.',
    'workshop.statusExplain.cancelled3': 'תמיד תוכל לשחזר זאת על ידי פרסום פרק או שינוי הסטטוס.',
    'workshop.statusExplain.finished1': 'מזל טוב! לאחר כל העבודה הקשה הגעת סוף סוף לסיום של מסע מדהים. גם אם הסיפור מסתיים כעת, אנחנו מקווים שיהיו עוד סיפורים לספר בעתיד, אבל עכשיו, היכולת לנוח וליהנות מהמנוחה המגוררת.',
    'workshop.statusExplain.finished2': 'סימון הסיפור כמושלם יודיע לקוראים שהסיפור הסתיים. על אף שלא עליך להוסיף פרקים חדשים, אנחנו לא נעצור אותך והוספת פרקים מיוחדים היא רעיון טוב, לדוגמה להוסיף עוד אפילוגים לכל הדמויות.',
    'workshop.statusExplain.finished3': 'אם הסיפור צפוי להמשיך, כדאי להתחיל סיפור חדש במקום לבטל את הסטטוס הזה.',
    'workshop.status.goActive': 'הפעל את הסיפור שוב',
    'workshop.statusChangeEmail.storyIntro': 'נרצה ליידע אותך כי הסיפור שלך:',
    'workshop.statusChangeEmail.hiatusTitle': 'סטטוס הסיפור שלך הוגדר באופן אוטומטי להשהיה',
    'workshop.statusChangeEmail.hiatusIntro': 'בשל חוסר פעילות, סטטוס הסיפור שלך הוגדר באופן אוטומטי להשהיה.',
    'workshop.statusChangeEmail.hiatusWhy': 'הסיפור הונח במצב השהיה באופן אוטומטי משום שלא פורסם פרק חדש במשך למעלה מ-6 חודשים.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'הסטטוס יוסר באופן אוטומטי אם תפרסם פרק חדש. אם לא תפרסם פרק חדש בתוך ה-6 חודשים הקרובים, נגדיר באופן אוטומטי את הסיפור כמבוטל.',
    'workshop.statusChangeEmail.cancellationIntro': 'סטטוס הסיפור שלך הוגדר באופן אוטומטי למבוטל.',
    'workshop.statusChangeEmail.cancellationWhy': 'This has happened because you haven\'t posted any new chapter to the story since it was set to hiatus 6 months ago. After a year of inactivity, we automatically set stories to cancelled so that readers know which stories are active.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'הסטטוס יוסר באופן אוטומטי אם תפרסם פרק חדש. אם אין לך כוונה לעבוד על הסיפור יותר, אין צורך בפעולה נוספת.',
    'workshop.startCreating': 'התחל ליצור',
    'workshop.ownWork': 'יצירה עצמאית',
    'workshop.list.thumbs': 'רשימת תמונות ממוזערות',
    'workshop.list.list': 'רשימה קצרה',
    'workshop.fanfiction.new': 'צור פאן פיקשן חדש',
    'workshop.videoTrailerLink': 'קישור לטריילר הווידאו',
    'workshop.videoTrailerPlayerTitle': 'נגן טריילר וידאו סיפור',
    'workshop.videoTrailer.supportedPlaftorms': 'אנחנו תומכים ב-YouTube, Vimeo ו-Odysee',
    'workshop.videoTrailer.rumble': 'אנחנו תומכים גם ב־Rumble, אבל זכור להעתיק את כתובת ה-IFRAME.',
    'workshop.videoTrailer.suggestPlatforms': 'האם הפלטפורמה שלך לצפייה בסרטונים חסרה, הודיעו לנו דרך <a>משוב</a> שלנו!',
    'workshop.cover.edit': 'החלף עטיפה',
    'workshop.collaborator.leave': 'Leave project',
    'workshop.collaborator.leaveTitle': 'Please confirm that you want to leave {workName}',
    'workshop.collaborator.leaveExplained': 'Leaving project will mean that you will loose all access, association and privileges. If you are not sure what all of this means, then this is probably not what you wanted to click.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Removed on {date, date}',
    'workshop.aiGeneratedAdjusted': 'The AI generation status of this content has been adjusted, as a result of a user report, by an administrator and cannot be changed.',
    'workshop.theWay.authorProgress': 'Author Progress',
    'workshop.universe.preventPublishing': 'Prevent publishing of stories',
    'workshop.universe.preventPublishingTooltip': 'When enabled, no stories in this universe can be published. This is useful for universes that are still in development or for universes that are meant for private use only.',
    'workshop.story.preventPublishing': 'Prevent publishing',
    'workshop.story.preventPublishingTooltip': 'When enabled, this story cannot be published. This is useful for stories that are still in development or for stories that are meant for private use only.',
    'workshop.story.preventPublishingTooltipUniverse': 'Publishing is prevented because the universe has the prevent publishing setting enabled.',
    'workshop.story.showChapterNumbersInListing': 'הצג מספרי פרקים ברשימת הפרקים',
    'workshop.story.showChapterNumbersInListingTooltip': 'כאשר אפשרות זו מופעלת, מספרי הפרקים נראים לקוראים ברשימת פרקי הסיפור.',
    'workshop.revisions.new.public.disabled': 'Cannot publish while prevent publishing is enabled in story settings.',
    'workshop.publishing.restricted': 'Due to good conduct violation we have disabled your ability to publish.',
    'workshop.story.buyingSettings': 'Sale settings',
    'workshop.story.delete.modalAria': 'מודל אישור למחיקת סיפור',
    'workshop.story.delete.warning': 'האם אתה בטוח שברצונך למחוק את "{title}"? פעולה זו אינה ניתנת לביטול.',
    'workshop.story.delete.button': 'מחק סיפור',
    'workshop.story.private.universeExplain': 'הסיפור הזה הוא פרטי כי היקום שלו הוא פרטי.',
    'workshop.story.makePublicWithUniverse.button': 'הפוך את הסיפור והיקום לציבוריים',
    'workshop.universe.makePublic.only.button': 'הפוך את היקום לציבורי בלבד',
    'workshop.universe.makePublic.only.modalAria': 'מודל אישור להפוך יקום לציבורי בלבד',
    'workshop.universe.makePublic.only.warning': 'זה הופך רק את היקום לציבורי. הסיפורים ביקום זה נשארים פרטיים עד שהם מתפרסמים באופן פרטני.',
    'workshop.universe.makePublic.withStories.button': 'הפוך את היקום ואת כל הסיפורים לציבוריים',
    'workshop.universe.makePublic.withStories.modalAria': 'מודל אישור ליצירת יקום וכל הסיפורים לציבור',
    'workshop.universe.makePublic.withStories.warning': 'זה הופך את היקום ואת כל הסיפורים הקשורים אליו לציבוריים.',
    // Chapter deletion
    'workshop.chapter.delete.modalAria': 'מודל אישור למחיקת פרק',
    'workshop.chapter.delete.warning': 'האם אתה בטוח שברצונך למחוק את "{title}"? פעולה זו אינה ניתנת לביטול.',
    'workshop.chapter.delete.button': 'מחק פרק',
    'workshop.chapter.delete.deleting': 'מחיקה...',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-Generated Content',
    'workshop.chapter.aiGenerated.tooltip': 'Mark this chapter as containing AI-generated content',
    'workshop.chapter.aiGenerated.description': 'This chapter contains content that was generated with AI assistance.',
    'workshop.chapter.aiModel': 'AI Model',
    'workshop.chapter.aiModel.tooltip': 'Select the AI model that was used to generate content',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Enter the name of the AI model',
    'workshop.chapter.aiGenerated.locked': 'AI content marking cannot be changed because it has been adjusted by the moderation team.',
    'workshop.monetization.aiNotEligible': 'AI-generated content is not eligible for monetization.',
    'workshop.timer.settings': 'Timer Settings',
    'workshop.timer': 'Timer',
    'workshop.timer.type': 'Type',
    'workshop.timer.timer': 'Timer',
    'workshop.timer.countdown': 'Countdown',
    'workshop.timer.pomodoro': 'Pomodoro',
    'workshop.timer.mode': 'Mode',
    'workshop.timer.regular': 'Regular',
    'workshop.timer.improved': 'Improved',
    'workshop.timer.duration': 'Duration (min)',
    'workshop.timer.workDuration': 'Work (min)',
    'workshop.timer.breakDuration': 'Break (min)',
    'workshop.timer.breakType': 'Break Type',
    'workshop.timer.softBreak': 'Soft Break',
    'workshop.timer.hardBreak': 'Hard Break',
    'workshop.timer.break': 'Break',
    'workshop.timer.breakTime': 'Break Time!',
    'workshop.timer.breakMessage': 'Take a moment to rest. Click anywhere to dismiss.',
    'workshop.timer.pause': 'Pause',
    'workshop.timer.resume': 'Resume',
    'workshop.timer.stop': 'Stop',
    'workshop.timer.start': 'Start',
    'workshop.timer.tabInactive': 'Timer paused - switch back to tab to continue',
    // Timer descriptions
    'workshop.timer.type.timer.desc': 'Simple stopwatch that starts at 0:00 and counts upward. Perfect for tracking total writing time in a session or seeing how long you\'ve been working continuously. Never ends automatically - you control when to stop.',
    'workshop.timer.type.countdown.desc': 'Countdown timer that starts from your set duration and counts down to zero. Great for time-boxed writing sessions, word sprints, or when you want to work for a specific amount of time before taking a break.',
    'workshop.timer.type.pomodoro.desc': 'Structured productivity technique: 25-minute focused work sessions alternating with 5-minute breaks. After 4 cycles, takes a longer 15-30 minute break. Scientifically proven to improve focus and prevent burnout.',
    'workshop.timer.mode.regular.desc': 'Timer runs continuously regardless of your activity. Best for disciplined writers who want to track time even when researching, editing, or taking short breaks. Timer keeps going when you switch tabs or stop typing.',
    'workshop.timer.mode.improved.desc': 'Smart timer that automatically pauses when you switch browser tabs. Perfect for focused writing sessions where you want accurate tracking of actual writing time, not total time spent on the page.',
    'workshop.timer.breakType.soft.desc': 'Gentle reminder approach: Shows a small notification when break time starts. You can choose to continue working if you\'re in \'the zone\' or take the break. Good for flexible writers who sometimes need to extend productive sessions.',
    'workshop.timer.breakType.hard.desc': 'Strict enforcement: Displays a full-screen modal that prevents further input until the break timer completes. Forces you to step away from the keyboard. Ideal for writers who struggle with self-discipline or workaholics who need enforced rest periods.',
    'workshop.timer.duration.timer.desc': 'How long you plan to write in this session. Start with 25-50 minutes for focused work, or set longer sessions (2-4 hours) for deep writing days.',
    'workshop.timer.duration.countdown.desc': 'Target writing time before the timer ends. Try 25 minutes for focused sprints, 45-60 minutes for substantial work sessions, or 90 minutes for creative deep dives.',
    'workshop.timer.workDuration.desc': 'Length of focused work sessions. Traditional Pomodoro uses 25 minutes. Try 15-20 minutes if you find it hard to concentrate for longer periods, or 45-50 minutes for experienced writers who can maintain deep focus.',
    'workshop.timer.breakDuration.desc': 'Rest period between work sessions. Standard is 5 minutes for short breaks. Use 10-15 minutes for longer breaks that allow you to step away from your desk, stretch, or get a drink. Every 4th break is automatically longer (2-3x duration).',
    'workshop.llmstxt': 'AI Access',
    'workshop.llmstxt.blocked': 'Blocked - LLMs cannot access your content',
    'workshop.llmstxt.limited': 'מוגבל - LLM יכול לגשת רק למטא-נתונים',
    'workshop.llmstxt.free': 'Free - LLMs can access your content for free',
    'workshop.llmstxt.paid': 'Paid - LLMs can access your content for a fee (coming soon)',
    'workshop.ai.llmstxt.generate': 'Generate LLMs.txt',
    'workshop.ai.llmstxt.generating': 'Generating LLMs.txt...',
    'workshop.ai.llmstxt.download': 'Download LLMs.txt',
    'workshop.ai.llmstxt.title': 'Texts for AI services',
    'workshop.ai.agent.title': 'Assistant',
    'workshop.ai.llmstxt.story-info': 'Story Info LLMs.txt',
    'workshop.ai.llmstxt.full-content': 'Full Content LLMs.txt',
    'workshop.ai.llmstxt.info': 'Info LLMs.txt - Basic information for AI',
    'workshop.ai.llmstxt.infoShort': 'Basic information',
    'workshop.ai.llmstxt.full': 'Content LLMs.txt - Full content for AI',
    'workshop.ai.llmstxt.fullShort': 'Full content',
    'workshop.ai.assistant': 'AI Assistant',
    'workshop.ai.assistant.page.title': 'AI Assistant',
    'workshop.ai.assistant.llms.title': 'LLMs.txt',
    'workshop.ai.assistant.llms.description': 'These endpoints provide your universe content in a format optimized for Large Language Models and AI systems.',
    'workshop.ai.assistant.universe.info': 'Universe Information',
    'workshop.ai.assistant.universe.info.description': 'Basic universe information including title, description, language, and statistics.',
    'workshop.ai.assistant.encyclopedia.listing': 'Encyclopedia Listing',
    'workshop.ai.assistant.encyclopedia.listing.description': 'Complete encyclopedia with all entries organized by categories and links to detailed content.',
    'workshop.ai.assistant.access.title': 'AI Access Settings',
    'workshop.ai.assistant.access.description': 'Choose how AI systems can reach your LLMs.txt endpoints.',
    'workshop.ai.assistant.access.denied': 'Only collaborators can change AI access levels.',
    // Publisher Preview (Author's Resume)
    'workshop.story.publisherPreview.heading': 'תצוגה מקדימה של המו"ל',
    'workshop.story.publisherPreview.description': 'העלה קובץ תצוגה מקדימה מיוחד עבור הוצאות לאור שצופות בקורות החיים שלך כסופר. קובץ זה נשמר בצורה מאובטחת ונגיש רק להוצאות לאור.',
    'workshop.story.publisherPreview.freeStory': 'הסיפור הזה זמין בחינם. שקול ליצור קובץ EPUB מלא למטה במקום להעלות תצוגה מקדימה נפרדת — הוצאות לאור יכולות לגשת ליצירה המלאה.',
    'workshop.story.publisherPreview.upload': 'תצוגה מקדימה של הקובץ שהועלה (PDF, EPUB)',
    'workshop.story.publisherPreview.uploading': 'מעלה... {progress}%',
    'workshop.story.publisherPreview.uploaded': 'הועלה קובץ תצוגה מקדימה של המו"ל עבור כתבה זו.',
    'workshop.story.publisherPreview.replace': 'החלף קובץ',
    // Story monetization
    'workshop.monetization.addCurrency': 'הוסף מטבע נתמך נוסף',
    'workshop.monetization.arcDescription': 'תיאור הקשת (מוצג בעמוד התשלום ב-Stripe)',
    'workshop.monetization.arcPricingHelp': 'הגדר מחירים נפרדים לכל קשת עלילתית. כל קשת עלילתית מהווה מוצר נפרד ב-Stripe, והיא מסתנכרנת אוטומטית עם השמירה.',
    'workshop.monetization.arcPricingTitle': 'תמחור קשת',
    'workshop.monetization.currencies': 'מטבעות',
    'workshop.monetization.defaultCurrencies': 'מטבעות ברירת המחדל לשפה זו: {currencies}.',
    'workshop.monetization.errorNoPrice': 'אנא קבעו מחיר אחד לפחות.',
    'workshop.monetization.freePreview': 'תצוגה מקדימה חינם',
    'workshop.monetization.freePreviewChapters': 'פרקים לדוגמה בחינם',
    'workshop.monetization.freePreviewHelp': 'הגדר כמה פרקים מתחילת הסיפור שלך יהיו זמינים לקריאה חינם לכל אחד. זה עוזר למשוך קוראים.',
    'workshop.monetization.fullStoryPricing': 'תמחור הסיפור המלא',
    'workshop.monetization.lowPriceFee': 'תעריף קבוע מוזל בתוקף.',
    'workshop.monetization.noArcs': 'עדיין לא הוגדרו קווי עלילה. הוסף קווי עלילה בסעיף "קווי עלילה" שלמעלה.',
    'workshop.monetization.noCurrencies': 'הוסף מטבעות כדי לקבוע מחירים למהדורה זו.',
    'workshop.monetization.originalEdition': 'המקורי',
    'workshop.monetization.payoutSplits': 'חלוקת התשלומים',
    'workshop.monetization.percentageFee': 'חלוקת האחוזים פעילה.',
    'workshop.monetization.priceBounds': 'מינימום {min}. מקסימום {max}. ניכוי סטנדרטי מהפלטפורמה: {platformCut, number}% ברגע שהסכום עולה על העמלה הקבועה הנמוכה.',
    'workshop.monetization.priceEstimate': '{feeMode} מאגר היוצרים: {payout}. עמלת הפלטפורמה: {platformFee}. העמלה המשוערת של Stripe בתוך עמלת הפלטפורמה: {stripeFee}. הרווח המשוער של הפלטפורמה לאחר ניכוי Stripe: {platformNet}.',
    'workshop.monetization.priceTier': '{tierName} · {wordCount, number} {countLabel}. טווח מומלץ: {rangeMin, number, ::currency/USD}–{rangeMax, number, ::currency/USD}.',
    'workshop.monetization.pricingHelp': 'הגדר מחירים במטבעות שברצונך לתמוך בהם. המחירים מוזנים בפורמט התצוגה, לדוגמה 4.99 או 500 עבור מטבעות ללא עשרוניות.',
    'workshop.monetization.purchaseMode': 'מצב רכישה',
    'workshop.monetization.purchaseModeArc': 'לכל קשת',
    'workshop.monetization.purchaseModeBoth': 'שניהם',
    'workshop.monetization.purchaseModeFull': 'הסיפור המלא',
    'workshop.monetization.purchaseModeHelp': 'בחרו כיצד הקוראים יוכלו לרכוש את הסיפור שלכם. האפשרות "סיפור מלא" מאפשרת לרכוש את הסיפור במלואו. האפשרות "לפרק" מאפשרת לקוראים לרכוש פרקים בודדים. שתי האפשרויות זמינות.',
    'workshop.monetization.purchaseModeLabel': 'מצב רכישה',
    'workshop.monetization.saveArcPricing': 'שמור את מחירי ה-Arc',
    'workshop.monetization.saveError': 'שגיאה בשמירת הגדרות התמחור',
    'workshop.monetization.splitHelp': 'חלוקת התשלומים נקבעת כאחוזים מהמכירות ברוטו. שורת הפלטפורמה קבועה בהתאם לרישיון הסיפור, ושורות היוצרים ממלאות את היתרה.',
    'workshop.monetization.stripeSynced': '✓ Stripe',
    'workshop.monetization.suggestedPrice': 'מומלץ: {price}.',
    'workshop.monetization.tier.shortStory': 'סיפור קצר',
    'workshop.monetization.tier.novella': 'נובלה',
    'workshop.monetization.tier.novel': 'רומן',
    'workshop.monetization.tier.epic': 'אפי',
    'workshop.monetization.translationPricing': 'תמחור תרגום',
    'workshop.monetization.translationPricingHelp': 'תרגום זה נמכר כמוצר נפרד ב-Stripe. הקוראים הרוכשים מהדורה זו מקבלים גישה אך ורק לגרסת ה- {language}.',
    'workshop.monetization.translationPricingMissing': '{count, plural, one {בתרגום {languages} לא הוגדר מחיר.} other {{languages} לא הוגדר מחיר.}} הקוראים לא יוכלו לרכוש {count, plural, one {תרגום זה} other {תרגומים אלה}} עד שיוגדר מחיר.',
    // Revenue share
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.fixed': 'תוקן',
    'workshop.revShare.mustMatchCreatorShare': 'סך השורות של היוצרים חייב להסתכם ב- {creatorShare, number}%, מכיוון שחלקו של הפלטפורמה קבוע על {platformShare, number}%.',
    'workshop.revShare.owner': 'בעלים',
    'workshop.revShare.ownerLocked': 'בעל הסיפור חייב להישאר שותף לחלוקת התמורה.',
    'workshop.revShare.platformFixed': 'Platform share is fixed at {platformShare, number}% for this license. Creator rows split the remaining {creatorShare, number}%.',
    'workshop.revShare.platformShare': 'נתח השוק של הפלטפורמה',
    'workshop.revShare.unallocated': 'נתח שלא הוקצה {total, number, ::percent}',
    'workshop.revShare.undecided': 'טרם הוחלט',
    'workshop.selectCollaborator': 'בחר שותף',
    // Collaborator monetization
    'workshop.collaborators.monetizedNotice': 'סיפור זה מביא רווחים. המוזמנים חייבים להשלים את הגדרת התשלומים ב-Stripe לפני שיוכלו לקבל את ההצעה. תוכל להציע חלוקת רווחים להלן — הסכום ינוכה מהחלק שלך.',
    'workshop.collaborators.proposedSplit': 'חלוקת הרווחים המוצעת (%)',
    'workshop.collaborators.splitFromOwnerShare': 'סכום זה ינוכה מהחלק שלך. על המוזמן להשלים את הגדרת התשלום ב-Stripe לפני שיוכל לאשר את ההזמנה.',
    // Arc management on monetization page
    'workshop.monetization.arcManagement': 'קשתות עלילתיות',
    'workshop.monetization.arcManagementHelp': 'הגדירו את קווי העלילה של הסיפור שלכם על ידי קביעת טווחי פרקים. כל קו עלילה ניתן למכירה בנפרד.',
    'workshop.monetization.saveArcs': 'שמור קשתות',
    'workshop.monetization.arcsSaved': 'מבנה הקשת נשמר.',
    'workshop.monetization.lowPriceWarning': 'במחיר זה, חל המינימום של התעריף הקבוע. התשלום שתקבל יהיה נמוך יותר מחלוקת הרווחים הסטנדרטית של {platformCut, number}%. שקול לקבוע מחיר של {thresholdPrice} ומעלה כדי להבטיח את התשלום הטוב ביותר ליוצר.',
    'workshop.monetization.recommendedPrice': 'מחיר מומלץ בהתבסס על אורך הסיפור ({wordCount, number} {countLabel}): {price}.',
    // AI Chat Assistant
    'workshop.ai.chat.placeholder': 'Ask about your story...',
    'workshop.ai.chat.send': 'Send',
    'workshop.ai.chat.stop': 'Stop generating',
    'workshop.ai.chat.newConversation': 'New conversation',
    'workshop.ai.chat.history': 'Conversations',
    'workshop.ai.chat.deleteConversation': 'Delete conversation',
    'workshop.ai.chat.deleteConfirm': 'Click again to confirm',
    'workshop.ai.chat.noKey': 'Add an API key for OpenAI, Anthropic, xAI, or Google in your settings to use the AI assistant.',
    'workshop.ai.chat.noKeyLink': 'Go to Settings',
    'workshop.ai.chat.noAccess': 'Only the story author and collaborators can use the AI assistant.',
    'workshop.ai.chat.error': 'Something went wrong. Please try again.',
    'workshop.ai.chat.model': 'Model',
    'workshop.ai.chat.thinking': 'Thinking...',
    'workshop.ai.chat.lookingUp': 'Looking up {entryName}...',
    'workshop.ai.chat.clear': 'Clear conversation',
    'workshop.ai.chat.noMessages': 'Start a conversation about your story. The assistant knows about your story, universe, and encyclopedia.',
    'workshop.ai.chat.selectedText': 'Selected text',
    'workshop.ai.chat.createError': 'Failed to start a new conversation. Please try again.',
    'workshop.ai.chat.findInEditor': 'Click to find this passage in the editor',
    'workshop.ai.chat.modelLocked': 'Start a new conversation to change the model.',
    // AI Quick Actions
    'workshop.ai.quick.pacing': 'Pacing',
    'workshop.ai.quick.plotHoles': 'Plot holes',
    'workshop.ai.quick.dialog': 'Dialog',
    'workshop.ai.quick.showVsTell': 'Show vs Tell',
    'workshop.ai.quick.characters': 'Characters',
    'workshop.ai.quick.tone': 'Tone',
    'workshop.ai.quick.repetition': 'Repetition',
    'workshop.ai.quick.encyclopedia': 'Encyclopedia',
    'workshop.ai.quick.generateImage': 'Generate image',
    // BubbleMenu
    'writer.askAI': 'Ask AI about selection',
    // Encyclopedia proposal cards
    'workshop.ai.proposal.label': 'Entry proposal',
    'workshop.ai.proposal.approve': 'Confirm and add',
    'workshop.ai.proposal.dismiss': 'Dismiss',
    'workshop.ai.proposal.approved': '✓ Added to encyclopedia as draft',
    'workshop.ai.proposal.rejected': 'Dismissed',
    'workshop.ai.proposal.showMore': '+{count} more fields',
    'workshop.ai.proposal.showLess': 'Show less',
    'workshop.ai.proposal.nameLabel': 'Name',
    'workshop.ai.proposal.categoryLabel': 'Category',
    'workshop.ai.proposal.reviewHint': 'Confirm to add this as a WIP encyclopedia draft. You can change the name or category first.',
    // AI chat — image generation & save
    'aiChat.image.generatedBy': 'Generated by {model}',
    'aiChat.image.prompt': 'Prompt',
    'aiChat.image.loading': 'Generating image...',
    'aiChat.image.error': 'Image generation failed',
    'aiChat.image.addToEncyclopedia': 'Add to encyclopedia',
    'aiChat.image.saveAsCover': 'Save as cover',
    'aiChat.image.saveAsField': 'Save as field',
    'aiChat.image.discard': 'Discard',
    'aiChat.image.discardConfirm': 'Remove this image?',
    'aiChat.image.savedAsCover': 'Saved as cover of {entryName}',
    'aiChat.image.savedAsField': 'Saved to "{fieldTitle}" on {entryName}',
    'aiChat.image.picker.placeholder': 'Search encyclopedia entries...',
    'aiChat.image.picker.empty': 'No entries match "{query}"',
    'aiChat.image.fieldTitle.label': 'Field title',
    'aiChat.image.fieldTitle.placeholder': 'e.g. Portrait, Map, Flag',
    'aiChat.image.modelBadge': 'images',
    'workshop.ai.chat.modelSupportsImages': 'This model can generate images.'
};