export default {
  'courses.courses': 'Tanfolyamok',
  'courses.overview': 'Kurzusok áttekintése',
  'courses.public.title': 'Tanfolyamok felfedezése',
  'courses.public.heading': 'Tanfolyamok felfedezése',
  'courses.public.filters': 'Tanfolyamok szűrése',
  'courses.public.noResults': 'Nem találtunk tanfolyamokat',
  'courses.public.tryDifferentFilters': 'Próbáljon ki különböző keresési kifejezéseket vagy szűrőket',
  'courses.filter.search': 'Keresés tanfolyamok...',
  'courses.filter.allTypes': 'Minden típus',
  'courses.filter.clearAll': 'Mindent törölni',
  'courses.filter.type': 'Típus',
  'courses.type.course': 'Tanfolyam',
  'courses.type.workshop': 'Műhely',
  'courses.type.seminar': 'Szeminárium',
  'courses.type.course.lowercase': 'Tanfolyam',
  'courses.type.workshop.lowercase': 'Műhely',
  'courses.type.seminar.lowercase': 'Szeminárium',
  'course.create': 'Új kurzus létrehozása',
  'course.reading.title': 'Olvasási feladat címe',
  'course.question.add': 'Kérdés hozzáadása',
  'course.lessons.newMessage': 'Hozzon létre és szervezzen leckéket a hatékony tanítás érdekében',
  'course.reading.new': 'Olvasási feladat',
  'course.reading.newMessage': 'Hozzon létre és szervezzen olvasási feladatokat diákjai számára',
  'course.writing.new': 'Írásbeli feladat',
  'course.writing.newMessage': 'Az írási feladatok gyors beállítása és elosztása',
  'course.question.text': 'A kérdésed ide kerül',
  'course.question.type': 'Kérjük, válassza ki a kérdés típusát',
  'course.question.delete': 'Kérdés eltávolítása',
  'course.type': 'Tanfolyam típusa',
  'course.visibility': 'Válassz láthatósági beállítást',
  'course.title': 'Cím',
  'course.description': 'Leírás',
  'course.cover': 'Borító',
  'course.start': 'A kurzusod kezdete',
  'course.ends': 'A kurzusod vége',
  'course.curriculum': 'Tanfolyam tananyag',
  'course.members': 'Diákok és tanárok',
  'course.assignments': 'Feladatok',
  'course.question.deleteWhole': 'Teljes kérdés törlése',
  'course.question.yes': 'Igen',
  'course.question.no': 'Nem',
  'course.lesson.title': 'Lecke címe',
  'course.lesson.add.universe': 'Történet/Világ hozzáadása',
  'course.lesson.externalLinks': 'Külső hivatkozások',
  'course.lesson.add.link': 'Külső link hozzáadása',
  'course.status': 'Állapot',
  'course.active': 'Tevékenység',
  'course.active.message': 'Aktív',
  'course.inactive': 'Inaktív',
  'course.upload.resource': 'Erőforrás feltöltése',
  'course.question.answer': 'Válasz hozzáadása',
  'course.question.open': 'Nyitott kérdés',
  'course.question.close': 'Zárt kérdés',
  'course.question.multiple': 'Feleletválasztós kérdés',
  'course.about': 'Erről a tanfolyamról',
  'course.lesson.new': 'Új lecke létrehozása',
  'course.lesson.type': 'Lecke típusa',
  'course.lesson.inPerson': 'Személyesen',
  'course.lesson.preRecorded': 'Előre felvett',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Csak szöveg',
  'course.lesson.content': 'A lecke tartalma',
  'course.lesson.description': 'Nyilvános leírás',
  'course.add.story': 'Történet hozzáadása',
  'course.remove.story': 'Történet eltávolítása',
  'course.dateOfPublish': 'A közzététel dátuma',
  'course.lesson.meetInPerson': 'Személyes találkozó',
  'course.curriculum.edit': 'Tanterv szerkesztése',
  'course.stories.own': 'Saját történetek',
  'course.stories.organization': 'Szervezeti történetek',
  'course.stories.public': 'Nyilvános történetek',
  'course.publish.at': 'Szeretném, ha ez a kurzus a következő címen jelenne meg:',
  'course.edit.curriculum': 'Tanterv szerkesztése',
  'course.assignment': 'Megbízás',
  'course.lesson.removeLink': 'Link eltávolítása',
  'course.user.remove': 'Felhasználó eltávolítása',
  'course.user.invite': 'Felhasználó meghívása',
  'course.user.invited': 'Meghívott',
  'course.edit.role': 'Szerepkör szerkesztése',
  'course.assignment.description': 'Feladat leírása',
  'course.internal': 'Belső',
  'course.free': 'Ingyenes',
  'course.sale': 'Eladó',
  'course.announcements': 'Közlemények',
  'course.announcements.full': 'Tanfolyami bejelentések',
  'course.announcements.create': 'Hozzon létre egy bejelentést',
  'course.join': 'Csatlakozzon a tanfolyamhoz',
  'course.joining': 'Csatlakozás...',
  'course.join.success': 'Ön sikeresen csatlakozott ehhez a tanfolyamhoz!',
  'course.join.error.payment': 'A tanfolyamhoz való csatlakozáshoz fizetni kell.',
  'course.join.error.invite': 'Ehhez a tanfolyamhoz meghívó szükséges.',
  'course.join.error.generic': 'Hiba történt a tanfolyamhoz való csatlakozásban. Kérjük, próbálja meg újra.',
  'course.firstLesson': 'Első lecke',
  'course.upcomingLessons': 'Közelgő leckék',
  'course.detail.title': '{courseName} | Tanfolyam',
  'lessons.visibility.public': 'Nyilvános',
  'lessons.visibility.private': 'Privát',
  'course.curriculum.empty': 'Még nem állnak rendelkezésre tantervi elemek.',
  'course.preview.message':
    'Ez a tanfolyam előzetese. Csatlakozzon a tanfolyamhoz, hogy hozzáférjen az összes tartalomhoz.',
  'course.details': 'Tanfolyam részletei',
  'course.tab.curriculum': 'Tanterv',
  'course.tab.details': 'Tanfolyam részletei',
  'course.duration': 'Időtartam',
  'course.perpetual': 'Örökös',
  'course.language': 'Nyelv',
  'course.price': 'Ár',
  'course.learningObjectives': 'Tanulási célok',
  'course.prerequisites': 'Előfeltételek',
  'course.tags': 'Címkék',
  'course.stats.members': 'Tagok',
  'course.stats.lessons': 'Leckék',
  'course.assignments.comingSoon': 'A Feladatok nézet hamarosan megjelenik.',
  'course.progress.comingSoon': 'A haladás nyomon követése hamarosan megjelenik.',
  'course.type.free': 'Ingyenes',
  'course.type.paid': 'Fizetett',
  'course.type.forSale': 'Eladó',
  'course.type.invite': 'Csak meghívottaknak',
  'courses.invites.tile': 'Meghívjuk Önt, hogy vegyen részt a {count, plural, one {tanfolyam} other {tanfolyamok}}.',
  'courses.invites.noInvites': 'Jelenleg nincsenek tanfolyami meghívóid.',
  'courses.invites.invitedBy': 'Meghívott:: ',
  'courses.invites.accept': 'Elfogadom',
  'courses.invites.reject': 'Visszautasítani',
  'course.join.heading': 'Csatlakozzon ehhez a tanfolyamhoz',
  'course.oneTimePayment': 'Egyszeri fizetés a teljes hozzáférésért',
  'course.member': 'Beiratkozott',
  'course.member.access': 'Teljes hozzáférést biztosítunk az összes tananyaghoz.',
  'courses.members.editRole': 'Szerkesztési szerepkör',
  'courses.members.editRoleFor': 'Szerkeszti a szerepét:',
  'courses.add.member': 'Új tag felvétele',
  'course.member.options': 'Tanfolyam tagok listája',
  'course.navigation.curriculum': 'Tanterv',
  'course.navigation.members': 'Diákok és tanárok',
  'course.navigation.assignments': 'Feladatok',
  'course.navigation.forums': 'Fórumok',
  'course.navigation.attendance': 'Részvétel',
  'course.members.teachers': 'Tanárok',
  'course.members.students': 'Diákok',
  'course.members.preview.message':
    'Csatlakozz ehhez a tanfolyamhoz, hogy láthasd az összes diákot és kapcsolatba léphess a közösséggel.',
  'course.member.role.owner': 'Tulajdonos',
  'course.member.role.teacher': 'Tanár',
  'course.member.role.student': 'Diák',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'course.startDate': 'Kezdeti dátum',
  'course.endDate': 'Végdátum',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Tanterv előnézet',
  'course.curriculum.preview.message':
    'Csatlakozzon ehhez a tanfolyamhoz, hogy hozzáférjen az összes {count} leckéhez és feladathoz.',
  'course.curriculum.locked': 'Zárva',
  'course.curriculum.lesson': 'Lecke',
  'course.curriculum.assignment': 'Megbízás',
  'course.curriculum.reading': 'Olvasás',
  'course.lesson.backToCurriculum': 'Vissza a tantervhez',
  'course.lesson.nextLesson': 'Következő lecke',
  'course.lesson.documents': 'Dokumentumok és források',
  'course.lesson.meetingLink': 'Találkozó Link',
  'course.lesson.location': 'Helyszín',
  'course.lesson.virtualClassroom': 'Virtuális tanterem',
  'course.lesson.joinClassroom': 'Csatlakozzon a virtuális tantermi foglalkozáshoz',
  'course.lesson.enterClassroom': 'Belépés az osztályterembe',
  'course.assignment.acceptsStories': 'Elfogadja a történeteket',
  'course.assignment.acceptsUniverses': 'Elfogadja az univerzumokat',
  'course.assignment.backToAssignments': 'Vissza a megbízásokhoz',
  'course.assignment.criteria': 'Olvasási kritériumok',
  'course.assignment.dueDate': 'Esedékes: {date}',
  'course.assignment.freeReading': 'Ingyenes olvasás engedélyezve',
  'course.assignment.grade': 'Fokozat',
  'course.assignment.grade.received': 'Fokozat: {grade}',
  'course.assignment.gradeSaveError': 'Nem lehet osztályzatot menteni',
  'course.assignment.gradeSaved': 'Az osztályzat megmentve.',
  'course.assignment.gradedCount': '{count, plural, one {# graded} other {# graded}}',
  'course.assignment.grading.help':
    'Tekintse át a diákok beküldött munkáit, nyissa meg a kapcsolódó történeteket vagy univerzumokat, és adjon hozzá opcionális osztályzatot és visszajelzést.',
  'course.assignment.grading.title': 'Osztályozás: {title}',
  'course.assignment.grading.unavailable': 'Osztályozás nem elérhető',
  'course.assignment.grading.unavailableMessage':
    'Nincs hozzáférése ehhez az osztályozó oldalhoz, vagy a feladatot nem lehetett megtalálni.',
  'course.assignment.lastRead': 'Utolsó olvasat {date}',
  'course.assignment.minutes': '{count} min',
  'course.assignment.noSubmissions': 'Még nincsenek beadványok.',
  'course.assignment.noWrittenResponse': 'Írásos válasz nem érkezett.',
  'course.assignment.notFound': 'A feladat nem található',
  'course.assignment.notFoundMessage': 'A kért hozzárendelés nem található.',
  'course.assignment.noteForTeacher': 'Adj hozzá egy jegyzetet a tanárnak',
  'course.assignment.open': 'Nyílt megbízás',
  'course.assignment.openGrading': 'Osztályozási oldal megnyitása',
  'course.assignment.questions': 'Kérdések',
  'course.assignment.readingProgress': 'A diákok olvasási előrehaladása',
  'course.assignment.readings': 'Hozzárendelt olvasmányok',
  'course.assignment.responsePlaceholder': 'Írja meg válaszát itt',
  'course.assignment.responsePrompt': 'Esszé téma vagy naplófelkérés',
  'course.assignment.selectStoriesRead': 'Válassza ki a feladathoz kiválasztott történeteket.',
  'course.assignment.sharedProject.studentHelp':
    'Nyissa meg a fenti megosztott projektmunkák egyikét a Műhelyben, és járuljon hozzá. Ez a feladat nem igényel külön beadási űrlapot.',
  'course.assignment.sharedProject.studentTitle': 'Hogyan kell elvégezni ezt a feladatot',
  'course.assignment.sharedProject.teacherNotice':
    'Ez a megosztott projektfeladat egyéni beadványok helyett a munkatársak hozzáférését használja.',
  'course.assignment.sharedProjects': 'Megosztott projektmunkák',
  'course.assignment.storiesCompleted': 'befejezett történetek',
  'course.assignment.submissionCount': '{count, plural, one {# submission} other {# submissions}}',
  'course.assignment.submissionSaved': 'A benyújtás elmentve.',
  'course.assignment.submissions': 'Beadványok és osztályozás',
  'course.assignment.submit': 'Feladat beküldése',
  'course.assignment.submitError': 'Nem lehet küldeni a feladatot',
  'course.assignment.submitWork': 'Válassza ki a benyújtandó munkát',
  'course.assignment.submitWork.help':
    'Válassza ki azt a történetet vagy univerzumot, amelyet ehhez a feladathoz értékelni kell.',
  'course.assignment.submitWork.label': 'Beküldött munka',
  'course.assignment.submitWork.placeholder': 'Válasszon ki egy történetet vagy univerzumot',
  'course.assignment.submittedAt': 'Beküldve {date}',
  'course.assignment.submittedWork.story': 'Beküldött történet: {title}',
  'course.assignment.submittedWork.universe': 'Beküldött univerzum: {title}',
  'course.assignment.supportingFiles': 'Feltöltött támogató anyagok',
  'course.assignment.supportingMaterials': 'Támogató anyagok',
  'course.assignment.updateSubmission': 'Frissítés benyújtása',
  'course.assignment.yourSubmission': 'Az Ön beadványa',
  'courses.role.owner': 'Tulajdonos',
  'courses.role.teacher': 'Tanár',
  'courses.role.student': 'Diák',
};
