export default {
    'org.auditLog.title': 'Audit log',
    'org.settings.title': 'Szervezeti beállítások',
    'org.settings.name': 'Szervezet neve',
    'org.settings.membersPrivate': 'Ne jelenítse meg nyilvánosan a tagokat',
    'org.logo': 'Szervezet logó',
    'org.logo.alt': '{organizationName} logó',
    'org.superAdmin': 'Szuperadmin',
    'org.settings.language': 'Elsődleges nyelv',
    'org.meta.desc': 'Szervezetek és alkotói csoportok a Literary Universe-ben.',
    'org.luOrgs': 'Literary Universe Szervezetek',
    'org.otherOrgs': 'Céhek és Szervezetek',
    'org.aboutTitle': 'Névjegy {orgName}',
    'org.membersTitle': 'Szervezet tagjai',
    'org.membersNone': 'A tagok nem nyilvánosak',
    'org.storiesTitle': 'Történetek: {orgName}',
    'org.universesTitle': 'Univerzumok: {orgName}',
    'org.userDashboardTitle': 'Az ön szervezetei',
    'org.settings.hideMembers.label': 'Tagok elrejtése a nyilvánosság elől',
    'org.visit': 'Ugrás a(z) {organization} oldalra',
    'org.authorOverride.legend': 'Szerző felülbírálata',
    'org.authorOverride.desc': 'Ezzel a szöveggel helyettesíti a szervezet nevét.',
    'org.authorOverride.label': 'Szerző neve',
    'org.membersAdd.title': 'Tagok meghívása a szervezetbe',
    'org.flashnews.admin': 'Flashnews adminisztráció',
    'org.settings.tabListAria': 'Szervezet részeinek beállítása',
    'org.forums.title': '{orgName} fórum',
    'org.flashnews.internal': 'Belső hír villanások',
    'org.flashnews.publicAll': 'Nyilvános hír villanások az összes tulajdonhoz',
    'org.flashnews.createTitle': `Új hír villanás létrehozása {type, select,
    internal {a szervezet}
    allProperties {számára, nyilvános megjelenítés az összes tulajdonon}
    other {a szervezet}
  }`,
    'org.members.invited': 'Meghívott tagok',
    'org.members.list': 'Szervezet tagjai',
    'org.invitesTileNotice': 'Meghívtak a(z) {count, number} szervezethez/ekhez {count, plural, one {szervezet} other {szervezetek}}',
    'org.invitePage.title': 'Meghívások szervezetekhez',
    'org.invitePage.invitedAt': 'Meghívtak a(z) {invitedAt, date, short}.',
    'org.invitePage.ignoring': 'Jelenleg figyelmen kívül hagyod ezt a meghívást, ami azt jelenti, hogy még mindig érvényes, de nem kapsz értesítéseket róla.',
    'org.invitePage.expiresAt': 'Ez a meghívás lejár {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Csatlakozás a szervezethez',
    'org.invitePage.reject': 'Meghívás elutasítása',
    'org.invitePage.ignore': 'Jelenleg figyelmen kívül hagyom',
    'org.leaveOrg.title': 'Szervezet elhagyása',
    'org.leaveOrg.confirm': 'Ez egy végleges művelet. Miután elhagyod, elveszted az összes hozzáférést ehhez a szervezethez. Biztosan el akarod hagyni a szervezetet?',
    'org.confirmRemove.aria': 'Felhasználó eltávolításának megerősítése',
    'org.confirmRemove.confirm': 'Biztosan eltávolítod a(z) {username} -t a(z) {organization}-ből?',
    'org.confirmRemove.remove': 'Felhasználó eltávolítása',
    'org.mainBlog': 'Fő blog',
    'org.teams': 'Csapatok',
    'org.teams.total': 'Összes csapat: {totalTeams, number}',
    'org.teams.create': 'Új csapat létrehozása',
    'org.teams.settings': 'Csapat beállítások',
    'org.workshop.ownerUser': 'Nem egy céh munkája',
    'org.workshop.caption': 'Céh tulajdonjog'
};