export default {
    'homepage.welcome': 'Üdvözöljük a',
    'homepage.start': 'Indítsa el az utazását!',
    'homepage.iAm': 'Én vagyok egy',
    'homepage.iAm.aria': 'Válasszon az olvasók és írók számára készült funkciók megjelenítése között',
    'homepage.reader': 'OLVASÓ',
    'homepage.writer': 'ÍRÓ',
    'homepage.reader.title': 'Az olvasás még soha nem volt ilyen érdekes',
    'homepage.reader.readingTitle': 'Egyedi olvasási élmény',
    'homepage.reader.readingDesc': 'Mélyebben merüljön el kedvenc fiktív univerzumában a Literary Universe-ben. A Literary Universe történetei ugyanabba az univerzumba tartoznak, így az olvasó azonnali hozzáférést kap az univerzum enciklopédiájához a történet olvasójából.',
    'homepage.reader.favoriteTitle': 'Tudjon meg többet kedvenc történeteiről és szerzőiről',
    'homepage.reader.favoriteDesc': 'Az univerzum enciklopédiája és az írók blogjai csak néhány olyan funkció, amelyek segítenek megtudni mindent, amire szüksége van kedvenc történeteiről, beállításaikról és alkotóikról!',
    'homepage.reader.communityTitle': 'Csatlakozzon a közösséghez',
    'homepage.reader.communityDesc': 'Találkozz emberekkel az egész világról a dedikált univerzum és az írói fórumokon, blogokon és más közösségi funkciókon, ahol az azonos érdeklődésű rajongók találkoznak. Minden egy helyen.',
    'homepage.reader.readingFeatureTitle': 'Élvezd a lenyűgöző, mégis gyakorlatias olvasási élményt',
    'homepage.reader.readingFeatureDesc': 'Történetekből és univerzumokból eredően élvezd az egyszerű olvasást a részletek megtekintése nélkül, lapok között váltás nélkül.',
    'homepage.reader.readingExploreTitle': 'Fedezd fel az univerzum minden apró részletét',
    'homepage.reader.readingExploreDesc': 'Az univerzum enciklopédia lehetőséget nyújt arra, hogy megtudj mindent az univerzumról és teljesen elmerülj a történetekben.',
    'homepage.reader.start': 'Kezdj el olvasni',
    'homepage.writer.title': 'Bemutasd az univerzumodat és oszd meg a történeteidet',
    'homepage.writer.writingTitle': 'Az írás és a teremtés egyszerűvé válik',
    'homepage.writer.writingDesc': 'Tapasztald meg az írás új módját a Literary Universes Workshop segítségével. Hozz létre egy enciklopédiát az univerzumod minden részletével, hogy megoszd az olvasóiddal, és írj elképesztő történeteket erre az alapra.',
    'homepage.writer.collaborationTitle': 'Együttműködő alkotás',
    'homepage.writer.collaborationDesc': 'A kreatív folyamat gyakran több ember bevonásával jár. Ne aggódj, mi gondoskodunk róla! Egyszerűen hozzáadhatsz bétaolvasókat, társszerzőket és fordítókat a történeteidhez és univerzumaidhoz.',
    'homepage.writer.communityTitle': 'Kapcsolatot teremthetsz az olvasóiddal',
    'homepage.writer.communityDesc': 'Menj túl az íráson és kapcsolatba léphetsz az olvasóiddal blogokon, fórumokon és más közösségi funkciókon keresztül, amelyek kapcsolódnak az univerzumaidhoz vagy hozzád mint íróhoz.',
    'homepage.writer.workshopFeatureTitle': 'Egy hely minden kreatív igényednek',
    'homepage.writer.workshopFeatureDesc': 'Az állandóan fejlődő workshopunk a központi hely a kreatív igényeidnek. Egy egyszerű ötlettől kezdve hihetetlen univerzumokat, történeteket és mindent más, ami ehhez szükséges, létrehozhatsz.',
    'homepage.writer.monetizationFeatureTitle': 'Monetizáció',
    'homepage.writer.monetizationDesc': 'Erősen hisszük, hogy az embereket meg kell fizetni a munkájukért, és folyamatosan új lehetőségeket keresünk az írók számára a monetizálás terén. A monetizációs funkció lehetővé teszi, hogy az olvasóid kifejezzék megbecsülésüket. Fedezd fel az összes különböző lehetőséget, amelyek lehetővé teszik, hogy a rajongóid megmutassák neked az elismerésüket.',
    'homepage.writer.start': 'Állítsd be a műhelyedet!',
    'homepage.featureSelection': 'Nézd meg ezeket a népszerű univerzumokat!',
    'about.title': 'Az Irodalmi Univerzumról',
    'about.desc': 'Történelem, titkok és emberek az Irodalmi Univerzum mögött.',
    'about.text.1': 'Az Irodalmi Univerzumot írók és olvasók számára tervezték egyaránt. Az írók használhatják az oldalt eredeti művek írásához a műhely gomb segítségével a vezérlőpult menüben. Ez lehetővé teszi a fő szerkesztő és az enciklopédia funkciókhoz való hozzáférést, amelyek főként a személyes történetuniverzum minden aspektusának egy oldalra való rendezésére összpontosítanak. A közösségi szempontok lehetővé teszik az írók számára, hogy közzétegyék munkáikat és követőt szerezzenek, valamint közvetlenebbül is kapcsolatba lépjenek az olvasóikkal, ha úgy döntenek.',
    'about.text.2': 'Az olvasók elsősorban az oldalt új művek olvasására és szerzők követésére használhatják, de segíthetnek a már kiadott történetek szerkesztésében is, ha az író engedélyt ad rá. Az Irodalmi Univerzumon való olvasás egy teljesen új élményt nyújt, mivel az alapvető történet mellé az összes háttérinformációhoz is hozzáférhetünk ugyanazon az oldalon, ami betekintést nyújt az író gondolataiba, mint soha korábban.',
    'about.text.3': 'Az Irodalmi Univerzum jövője magában foglalja az írók számára egy piactér létrehozását, valamint közösségi funkciók hozzáadását a szerzők és az olvasók közötti kommunikáció javítása érdekében blogok és fórumok segítségével. Írói eszközök folyamatosan hozzáadásra kerülnek az idővel, jelenleg több mint egy tucat fejlesztés alatt áll vagy tervezési fázisban van. Végső célunk az írók és az olvasók élményének fokozása az internetes médium innovatívabb felhasználásával.',
    'about.text.4': 'Reméljük, hogy csatlakozol hozzánk, ahogy felfedezzük, mit tehet az internetes médium a kreatív írásért!',
    'about.team': 'A csapat',
    'about.history': 'Történelem',
    'about.company': 'A cég',
    'about.companyCountry.czechia': 'Csehország',
    'about.companyCountry.japan': 'Japán',
    'about.companyCity.prague': 'Prága',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Ügyvezető Igazgató',
    'about.CTO': 'Technológiai Igazgató',
    'about.jan': 'Jan az Irodalmi Univerzum alapítója, látomása és technológiai agya. Mint egy nagy irodalmi univerzumok írója, Jan mindig nehéznek találta olyan történetek írását technikai és olvashatósági szempontból, amelyek ne veszélyeztetnék az olvasási élményt. Ezért Jan úgy döntött, hogy webfejlesztési tanulmányait folytatja annak érdekében, hogy létrehozzon egy olyan alkalmazást, amely lehetővé teszi a történetek írását nagy univerzumokban.',
    'about.history.text': '2010-ben Jan a Rochester Institute of Technology-n kezdett tanulmányokat folytatni a webfejlesztésről annak érdekében, hogy képes legyen egy kreatív írás oldalt építeni. Ez 2013-ban valósult meg, amikor az első koncepcióbizonyítékot bemutatták az Imagine RIT-en. Jan folytatta tanulmányait, és 2016-ban egy új verziója az alkalmazásnak született, mint egy Mesteri Záródolgozat Projekt. A projekt 2016 őszén folytatódott és tovább fejlődött abba, amit ma látsz.',
    'copyrights.desc': 'Az Irodalmi Univerzum Szerzői Jogok Szerződésének teljes szövege.',
    'privacy.desc': 'Az Irodalmi Univerzum Adatvédelmi Szabályzatának teljes jogi szövege.',
    'guidelines.desc': 'Az Irodalmi Univerzum közösségi irányelvei.',
    'tos.desc': 'Az Irodalmi Univerzum Teljes Szolgáltatási Feltételeinek jogi szövege.',
    'homepage.intro': 'Engedd szabadjára a kreativitásod az irodalmi univerzumon át',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'Valaha álmodtál arról, hogy olyan képzeletbeli világot fejlesztesz ki, amely olyan részletes, hogy még te is eltévedsz benne? A Literary Universe-nél biztosítjuk az eszközöket, hogy valóra váltsd ezt a víziót. Minden írónak jogában áll hozzáférni a legjobb erőforrásokhoz és támogatáshoz. Ezért terveztünk egy mindenre kiterjedő teret, amely áthidalja az összetett történetmesélés és a szenvedélyes olvasás közötti szakadékot. Az írók számára ez egy álom munkaterület; az olvasók számára pedig egy felfedezési kaland. Csatlakozz hozzánk, ahogy követjük az irodalmi nyúlüregben, hogy felfedezzük, meddig vezet minket az elképzelés világában.',
    'gdpr.title': 'GDPR megfelelés',
    'gdpr.desc': 'Az Irodalmi Univerzum megfelel az EU GDPR irányelveinek.',
    'gdpr.compliant': 'Az Irodalmi Univerzum GDPR megfelelő',
    'gdpr.compliant.text': 'Az Irodalmi Univerzum különböző frissítéseket és változtatásokat hajtott végre a kódjában a 2018. május 25-én életbe lépő GDPR előkészítése érdekében.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digitális Millennium Szerzői Jogi Törvény',
    'common.legal.changelog': 'Változások ebben a verzióban',
    'dmca.title': 'Digitális Millennium Szerzői Jogi Törvény (DMCA) irányelvek',
    'dmca.subtitle': 'Szerzői jogviták eljárása',
    'dmca.step1.title': 'Eljárás a szerzői jog megsértésének bejelentésére.',
    'dmca.step2.title': 'Miután a kijelölt ügynök megfelelő és jóhiszemű megsértésbejelentést kapott.',
    'dmca.step3.title': 'Eljárás a válaszüzenet megküldésére a kijelölt ügynöknek.',
    'dmca.desc': 'Komolyan vesszük a szerzői jog megsértését.',
    'gdpr.access.title': 'Hozzáférési jog és adathordozhatósági jog',
    'gdpr.access.desc': 'A felhasználói beállításokban exportálhatja az összes adatát. Ezek az adatok szabványos JSON formátumban lesznek.',
    'gdpr.forget.title': 'Elfelejtéshez való jog',
    'gdpr.forget.desc': 'Minden fiók törölhető a felhasználói beállításokban. Bizonyos adatok megőrzésre kerülhetnek, különösen ha azok értékesítésre és/vagy vitákra kerültek.',
    'gdpr.rectification.title': 'Javítás joga',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'Adatkezelés korlátozásának joga',
    'gdpr.processing.desc': 'A Literary Universe teljes mértékben tiszteletben tartja a böngésző beállításait, például a "Ne kövess" kéréseket a Matomo statisztikai szerverünknek történő jelentéshez.',
    'gdpr.object.title': 'Ellenkezés joga',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'A bejelentés két forgatókönyvre osztható. 1. Belső tulajdon (a tulajdonnal kapcsolatos jogsértés a webhelyen). 2. Külső tulajdon (a tulajdonnal kapcsolatos jogsértés a webhelyen nem létező tulajdonon).',
    'dmca.step1.desc2': 'A belső tulajdonra vonatkozó bejelentést a tulajdonra vonatkozó jelentés gombbal lehet megtenni. A külső tulajdonra vonatkozó jogsértés bejelentése a visszajelzés képernyőn lehetséges. Mindkét esetben személyes adatokat és további részleteket kell megadnia, amelyek lehetővé teszik számunkra a tulajdonlás ellenőrzését.',
    'dmca.step1.desc3': 'Kérjük, vegye figyelembe, hogy hamis állítások esetén nem lesz lehetősége a jövőben igényeket benyújtani.',
    'dmca.step2.desc1': 'Miután megkapjuk a jelentését, ellenőrizzük az azonosítóit és tulajdonjogát. Ha minden rendben van, folytatjuk a jogosultság ellenőrzését. Ha igaznak találjuk a jogosultságot, akkor az illetéktelen tartalmat elérhetetlenné tesszük a jogosultság ellenértesítésének vagy a 14 nap letelte után, amikor azt töröljük.',
    'dmca.step3.desc1': 'Miután megérkezett a panasz, a kijelölt tulajdonosnak 14 napja van a válaszlevél benyújtására. A Kijelölt Ügynök ezután megvizsgálja a vitát. A Kijelölt Ügynök döntése ebben a szakaszban végleges lesz.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Közzététel',
    'about.attributionsIntro': 'A Literary Universe sok nyílt forráskódú projekt és ingyenes erőforrás alapján épül fel. Lent találja a listájukat.',
    'about.attributionsMatomo': 'Analitikánk saját szerveren futó Matomo-t használ az IP2Location LITE adatokkal, amelyek elérhetők a https://lite.ip2location.com oldalon.',
    'team.name.pjakubec': 'Pavel Jakubec',
    'team.name.asebesta': 'Adam Šebesta',
    'about.developer': 'Fejlesztő',
    'about.seniorDeveloper': 'Tapasztalt Fejlesztő',
    'about.juniorDeveloper': 'Junior Fejlesztő',
    'about.leadDesigner': 'Fő tervező',
    'about.leadUX': 'Fő UX tervező',
    'about.intern': 'Gyakornok',
    'about.advisor': 'Tanácsadó',
    'about.headOfResearch': 'Kutatási Vezető',
    'about.CFO': 'Pénzügyi Igazgató',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry egy tervező, aki több mint 15 éves tapasztalattal rendelkezik. 2010 óta dolgozik ügynökségnél, ügyfelei közé tartozik a PERTAMINA, a VOA és az Indonéziai Idegenforgalmi Minisztérium. Tapasztalata van a márkaépítésben, elrendezésben és az UI/UX tervezésben, és kihívást jelent számára a Literary Universe tervezése.',
    'about.pavel': 'Web3, Metaverse, AI, minden ilyen és minden új dolog, amit Pavel vizsgál és hogyan lehet hozzáadni a Literary Universe fejlesztéséhez. Pavel igazi multidiszciplináris kutató, sok területen van betekintése, és új érdekes funkciók hozzáadásán dolgozik a Literary Universe-höz.',
    'about.seba': 'Régen játékos volt, most pedig arra tanul, hogy teljes értékű fejlesztővé váljon.'
};