export default {
    'reader.storyEnd.heading': 'VÉGE',
    'reader.storyEnd.description': 'Elérted a történet végét.',
    'reader.externalSale.heading': 'Még nincs itt',
    'reader.externalSale.description': 'Ez a történet nem elérhető a Literary Universe-ben, de beszerezheted más helyeken.',
    'reader.storyTBC.heading': 'Folytatás következik...',
    'reader.storyTBC.description': 'Ez mind, amink van a történetből eddig, de az kaland a jövőben folytatódni fog, térj vissza hamarosan!',
    'chapter.translation.notYetDescription': 'Nézz vissza újra hamarosan!',
    'reader.externalShopping.heading': 'Vásárolj {storyName} boltban:',
    'chapter.next': 'Következő fejezet',
    'chapter.previous': 'Előző fejezet',
    'chapter.comment': 'Hozzászólások ehhez a fejezethez',
    'reader.language': 'Nyelv:',
    'reader.fullscreen.enter': 'Ugrás teljes képernyőre',
    'reader.fullscreen.exit': 'Kilépés a teljes képernyőről',
    'reader.details.universe': 'Univerzum részletei',
    'reader.details.story': 'Történet részletei',
    'reader.darkmode': 'Sötét mód kapcsolása',
    'reader.flowtext': 'Szövegméret kapcsolása',
    'reader.menu.optionsAria': 'Olvasói opciók menü',
    'reader.accessibility': 'Hozzáférhetőség kapcsolása',
    'chapter.translation.notYet': 'Ez a fejezet még nincs lefordítva.',
    'externalShopping.buyLink.amazon': 'Vásárlás az Amazonon',
    'externalShopping.buyLink.other': 'Vásárlás a {storeName}boltban',
    'externalShopping.buyLink.bookshop': 'Vásárlás a Bookshop.org-on',
    'reader.accessibility.aria': 'Hozzáférhetőségi lehetőségek',
    'reader.accessibility.toggleDyslexic': 'Olvasási nehézségek esetén Dyslexic betűtípus kapcsolása',
    'reader.accessibility.toggleParagraphStripes': 'Bekezdések háttérváltoztatásának kapcsolása',
    'reader.accessibility.toggleParagraphHighlight': 'Kijelölt bekezdés kiemelésének kapcsolása',
    'reader.accessibility.toggleRules': 'Segédrács kapcsolása',
    'reader.nextRelease.scheduled': 'Next chapter will come on {nextReleaseAt, date} at {nextReleaseAt, time}!',
    'reader.storyContinues': 'A történet folytatódik...',
    'reader.storyOnHiatus': 'Az író jelenleg szünetet tart ebben a történetben, és ez a történet jelenleg szünetel. Jöjjön vissza egy vagy két hónap múlva ellenőrizni.',
    'reader.storyCancelled': 'Sajnos ez minden. A történetet törölték, szóval valószínűleg nem lesz semmi új.',
    'reader.storyCancelled.heading': 'Törölt',
    'reader.nextChapterEstimation.verySoon': 'A legutolsó {chaptersCount} fejezet publikálásának dátuma alapján a következő fejezet nagyon hamar megjelenik.',
    'reader.nextChapterEstimation.days': 'A legutolsó {chaptersCount} fejezet publikálásának dátuma alapján a következő fejezet {daysLeft} nap múlva jelenik meg.',
    'reader.nextChapterEstimation.notEnoughChapters': 'Az következő fejezet várható közzétételének időpontját is megadunk, amint ez a történet több fejezetet tartalmaz.'
};