export default {
    'settings.biography': 'Életrajz',
    'settings.biography.placeholder': 'Egy kis információ magadról, amit megjelenítünk a profilodon.',
    'settings.avatar.title': 'Profilkép',
    'settings.avatar.own': 'Profilképed',
    'settings.avatar.upload': 'Kép kiválasztása',
    'settings.email': 'E-mailek',
    'settings.email.msg': 'Fiókhoz kapcsolt e-mailek',
    'settings.email.verified.false': 'Nem ellenőrzött, kattintson az ellenőrző e-mail újraküldéséhez.',
    'settings.email.verified.true': 'Ellenőrzött e-mail',
    'settings.email.add': 'E-mail hozzáadása',
    'settings.languages.title': 'Nyelvi beállítások',
    'settings.languages.notice': 'Az angol és a cseh jelenleg az egyetlen hivatalosan támogatott nyelvek. Más nyelvek elérhetőek fantasztikus önkéntesek és AI fordítás segítségével, de lehetnek hiányosságok és hibák bizonyos helyeken.',
    'settings.languages.join': 'Ha szeretnél segíteni, fordíthatod a Literary Universe-t is.',
    'settings.name.title': 'Valódi név',
    'settings.name.given': 'Utónév',
    'settings.name.family': 'Vezetéknév',
    'settings.username.change': 'Felhasználónév megváltoztatása',
    'settings.username.label': 'Felhasználónév',
    'settings.password.title': 'Jelszó megváltoztatása',
    'settings.password.current': 'Jelenlegi jelszó',
    'settings.password.new': 'Új jelszó',
    'settings.password.repeat': 'Ismételd meg az új jelszavad',
    'settings.password.nomatch': 'Az új jelszó nem egyezik!',
    'settings.password.reset': 'Jelszó visszaállítása',
    'settings.password.resetSend': 'E-mail a jelszó visszaállításával kapcsolatos utasításokkal elküldve!',
    'settings.socialConnectTitle': 'Kapcsolódás más szolgáltatásokkal',
    'settings.socialDisconnect': 'Kapcsolat megszüntetése',
    'settings.socialConnect': 'Kapcsolódás',
    'settings.loginWith': 'Bejelentkezés {service}',
    'settings.connectTo': 'Kapcsolódás {service}',
    'settings.export.title': 'Adatok exportálása',
    'settings.export.explain': 'Ez lehetővé teszi, hogy az adatokat json formátumban lekérje az adatbázisunkban tárolt összes adatot.',
    'settings.export.submit': 'Adatok exportálása',
    'settings.delete.title': 'Fiók törlése',
    'settings.delete.warning': `FIGYELEM: A fiók törlésével elveszted a hozzáférést ehhez a fiókhoz és
    nincs lehetőség visszaállításra. Vegye figyelembe, hogy ez nem feltétlenül törli automatikusan a közzétett műveit,
    kommentjeit stb. További részletekért kérjük, tekintse meg a Szolgáltatási feltételeket.`,
    'settings.delete.confirm': 'Csak hogy biztos legyek. Biztosan törölni szeretné a fiókját?',
    'settings.delete.cancel': 'Nem szeretném törölni a fiókomat',
    'settings.delete.submit': 'Fiókom törlése',
    'settings.legal.title': 'Felhasználói hozzájárulási megállapodások',
    'settings.legal.explained': 'Itt kezelheti a különböző jogi dokumentumokkal kapcsolatos megállapodásait.',
    'settings.legal.analytics.title': 'Analitika és nyomon követés',
    'settings.legal.analytics.description': 'Az Irodalmi Univerzumon használt analitikai és nyomkövető szolgáltatásokat ellenőrizheti. Ez a rész felsorolja az összes szolgáltatást, amint hozzáadjuk őket.',
    'settings.legal.analytics.ostrio': 'Az Ostrio Analytics nyomon követésének letiltásához látogasson el a leiratkozási oldalukra:',
    'settings.legal.analytics.ostrioOptOut': 'Ostrio Analytics opt-out kezelése',
    'settings.legal.analytics.future': 'További szolgáltatókat, például a Google Analyticset vagy a Seznamot is ide fogjuk felvenni, amint engedélyezzük őket.',
    'settings.name.private': 'A név privát lesz',
    'settings.emailSubscriptions.title': 'E-mail értesítési beállítások',
    'settings.emailSubscriptions.explain': 'Válassza ki, mely e-mail értesítéseket szeretné kapni tőlünk.',
    'settings.emailSubscriptions.newsletter': 'Időszakos hírlevél',
    'settings.profile': 'Profilbeállítások',
    'settings.profile.basic': 'Alapvető profil információk',
    'settings.profile.identity': 'Identitás',
    'settings.profile.about': 'Rólad',
    'settings.profile.basic.description': 'Kezelje a többi felhasználó számára látható alapvető profilinformációit.',
    'settings.interests.title': 'Az Ön érdekei',
    'settings.account': 'Fiókbeállítások',
    'settings.legal.export.download': 'Adatok letöltése',
    'settings.legal.export.gathering': 'Adatok összegyűjtése... Ez eltarthat egy ideig.',
    'settings.gender.title': 'Nemed',
    'settings.gender.usage': 'Ez az információ bizalmas marad. Ezt az adatot platformelemzéshez és névtelen elemzésekhez használjuk, amikor elolvassák a történeteiket.',
    'settings.age.title': 'Korod',
    'settings.age.explicit': 'Show explicit content (age rating 21+)',
    'settings.age.birthday': 'Születési dátum',
    'settings.age.usage': 'Ez az információ bizalmas marad. Jogilag kötelesek vagyunk megkérdezni a korodat. Ezt az adatot platformelemzéshez, a tartalmak megjelenítéséhez értékelések alapján és névtelen elemzésekhez használjuk, amikor elolvassák a történeteiket.',
    'settings.country.title': 'Az országod',
    'settings.country.usage': 'Jogilag kötelesek vagyunk megkérdezni az országodat a kormányi érdeklődésekkel való foglalkozáshoz. Ezt az adatot platformelemzéshez és névtelen elemzésekhez használjuk, amikor elolvassák a történeteiket. Ha szeretnéd, megjelenítheted ezt az információt a profilodon.',
    'settings.country.public': 'Az országod nyilvános megjelenítése',
    'settings.country.select': 'Válassz országot',
    'settings.emailSubscriptions.newsletterTech': 'Időszakos hírlevél a fejlesztőinktől',
    'settings.emailSubscriptions.newsletterFeatures': 'Információ az új funkciókról',
    'settings.emailNotifications.title': 'Értesítések',
    'settings.emailNotifications.pm': 'Új üzenetek',
    'settings.emailNotifications.newChapters': 'Új fejezetek az Ön által követett történetekből',
    'settings.emailNotifications.newStories': 'Új történetek az univerzumokban vagy az általad követett szerzőktől',
    'settings.emailNotifications.newUniverses': 'Új univerzumok az Ön által követett szerzőktől',
    'settings.resetPasswordEmailSend': 'Elküldtünk neked utasításokat a jelszavad visszaállításához az e-mail címedre.',
    'settings.theme.title': 'Webhely témázása',
    'settings.theme.label': 'Webhely téma',
    'settings.theme.light': 'Világos',
    'settings.theme.dark': 'Sötét',
    'settings.links.title': 'Link a másik webhelyeidre',
    'settings.links.description': 'Ezek a linkek meg fognak jelenni a profiloldaladon.',
    'settings.links.website': 'Személyes webhelyed',
    'settings.links.social': 'Egyéb webhelyek',
    'settings.links.select': 'Válasszon webhelyet hozzáadáshoz',
    // 2FA
    'settings.2fa.title': 'Kétfaktoros azonosítás',
    'settings.2fa.explained': 'A kétfaktoros azonosítás további biztonsági réteget nyújt a fiókodnak, hozzáadva egy plusz azonosítási lépést a bejelentkezés során. Ez megakadályozza a rosszindulatú személyeket abban, hogy hozzáférjenek a fiókodhoz, ha az első bejelentkezési lépésed kompromittálódott.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'A kétfaktoros azonosítás OTP kóddal egyszer használatos jelszót hoz létre hitelesítő alkalmazások segítségével (pl. Authy, Google/Microsoft Authenticator stb.), amelyet a bejelentkezéskor megadhatsz.',
    'settings.2fa.otpModalAria': '2FA OTP módszer',
    'settings.2fa.otpAdd': '2FA OTP hozzáadása',
    'settings.2fa.confirmCode': 'Kód, amely megjelenik az azonosító alkalmazásodban',
    'settings.2fa.svgAlt': 'QR-kód az azonosító alkalmazáshoz',
    'settings.2fa.codeHeading': 'Ha nem tudod beolvasni a QR-kódot, manuálisan beírhatod a következő kódot:',
    'settings.2fa.instructionsTitle': 'Utasítások',
    'settings.2fa.instructions1': 'Telepítsd és nyisd meg a választott hitelesítő alkalmazást (Authy, Google/Microsoft Authenticator, FreeOTP stb.)',
    'settings.2fa.instructions2': 'Válaszd ki a "Fiók hozzáadása" lehetőséget (lehet látható "+" ikon vagy elrejtve lehet menüben)',
    'settings.2fa.instructions3': 'Olvasd be a képernyőn megjelenő QR-kódot, vagy ha ez nem lehetséges, add meg az alábbi kódot.',
    'settings.2fa.instructions4': 'Írd be a képernyőn megjelenő 6 számot ide, hogy befejezd.',
    'settings.2fa.saved': 'Kétfaktoros azonosítás sikeresen beállítva!',
    'settings.2fa.disableOTP': 'OTP kétfaktoros azonosítás kikapcsolása',
    // API Keys
    'settings.apiKeys.title': 'API kulcsok',
    'settings.apiKeys.description': 'Az API-kulcsok lehetővé teszik harmadik fél alkalmazások számára, hogy az Ön nevében hozzáférjenek az Ön Literary Universe adataihoz. Kezelje őket jelszóként, és soha ne ossza meg őket.',
    'settings.apiKeys.noKeys': 'Még nincs API-kulcsa.',
    'settings.apiKeys.created': 'Created {date, date, medium} at {date, time, short}',
    'settings.apiKeys.lastUsed': 'Utoljára használt {time}',
    'settings.apiKeys.neverUsed': 'Soha nem használták',
    'settings.apiKeys.expires': 'Lejár {date, date, medium}',
    'settings.apiKeys.name': 'Kulcsnév',
    'settings.apiKeys.name.placeholder': 'pl. Obsidian Plugin',
    'settings.apiKeys.permissions': 'Engedélyek',
    'settings.apiKeys.generate': 'API kulcs generálása',
    'settings.apiKeys.generated.title': 'Generált API kulcs',
    'settings.apiKeys.generated.warning': 'Mentsd el ezt a kulcsot most! Többé nem fogod látni.',
    'settings.apiKeys.copyToClipboard': 'Másolás a vágólapra',
    'settings.apiKeys.expiration': 'Lejárat',
    'settings.apiKeys.expiration.duration': `{months, plural,
    =1 {1 hónap}
    =3 {3 hónap}
    =6 {6 hónap}
    =12 {1 év (ajánlott)}
    =24 {2 év}
    other {~{months} hónapok}
  }`,
    'settings.apiKeys.revoke.confirm': 'Biztos, hogy vissza akarja vonni ezt az API-kulcsot? Ez a művelet nem vonható vissza.',
    'settings.apiKeys.delete.confirm': 'Biztos, hogy törölni szeretné ezt az API-kulcsot? Ez a művelet nem vonható vissza.',
    'settings.apiKeys.error.nameRequired': 'Kérjük, adjon meg egy nevet az API-kulcsához',
    'settings.apiKeys.error.scopesRequired': 'Kérjük, válasszon ki legalább egy engedélyt',
    'settings.apiKeys.security.title': 'Biztonsági közlemény',
    'settings.apiKeys.security.1': 'Soha ne ossza meg API-kulcsát senkivel',
    'settings.apiKeys.security.2': 'Kezelje úgy, mint egy jelszót',
    'settings.apiKeys.security.3': 'A hozzáférést bármikor visszavonhatja',
    'settings.apiKeys.security.4': 'A kulcs csak egyszer jelenik meg',
    'settings.apiKeys.scope.story.read': 'Történetek olvasása',
    'settings.apiKeys.scope.story.read.desc': 'Hozzáférés a történet címeihez, tartalmához és fejezeteihez',
    'settings.apiKeys.scope.story.write': 'Történetek létrehozása és szerkesztése',
    'settings.apiKeys.scope.story.write.desc': 'Új történetek létrehozása és a meglévők frissítése',
    'settings.apiKeys.scope.universe.read': 'Univerzumok olvasása',
    'settings.apiKeys.scope.universe.read.desc': 'Hozzáférés az enciklopédia bejegyzéseihez és a világépítési adatokhoz',
    'settings.apiKeys.scope.universe.write': 'Univerzumok létrehozása és szerkesztése',
    'settings.apiKeys.scope.universe.write.desc': 'Enciklopédia bejegyzések létrehozása és frissítése',
    'settings.apiKeys.scope.scratchpad.read': 'Jegyzetek olvasása',
    'settings.apiKeys.scope.scratchpad.read.desc': 'Hozzáférés a személyes jegyzetekhez és a jegyzettömbhöz',
    'settings.apiKeys.scope.scratchpad.write': 'Jegyzetek létrehozása és szerkesztése',
    'settings.apiKeys.scope.scratchpad.write.desc': 'Jegyzetek létrehozása és frissítése',
    'settings.apiKeys.scope.blog.read': 'Blogbejegyzések olvasása',
    'settings.apiKeys.scope.blog.read.desc': 'Hozzáférés a blogbejegyzésekhez és vázlatokhoz',
    'settings.apiKeys.scope.blog.write': 'Blogbejegyzések létrehozása és szerkesztése',
    'settings.apiKeys.scope.blog.write.desc': 'Blogbejegyzések létrehozása és frissítése',
    'settings.apiKeys.scope.user.read': 'Profil olvasása',
    'settings.apiKeys.scope.user.read.desc': 'Hozzáférés a felhasználónévhez, avatárhoz és nyilvános profilhoz',
    'settings.apiKeys.scope.library.read': 'Olvassa el a könyvtárat',
    'settings.apiKeys.scope.library.read.desc': 'Hozzáférés az olvasási listákhoz és a mentett történetekhez',
    // Web3
    'settings.web3.legend': 'Web3 pénztárcakapcsolat',
    'settings.web3.explained': 'Csatlakoztathatod a Web3 kriptovaluta pénztárcádat a Literary Universe fiókodhoz. Miután csatlakoztattad, lehetőséged lesz a pénztárcáddal bejelentkezni és még több dolgot elvégezni a jövőben, ahogy bővítjük a Web3 ajánlatunkat.',
    'settings.web3.connect': 'Pénztárca csatlakoztatása',
    'settings.web3.address': 'Csatlakoztatott cím: {address}',
    'settings.web3.verify': 'Cím aláírása',
    'settings.web3.verify.explained': 'Annak ellenőrzéséhez, hogy ez a cím az Öné, kérjük, hogy írjon alá egy üzenetet az Ön pénztárcájának tulajdonjogának biztosítása érdekében.',
    'settings.web3.verified': 'Ellenőrzött',
    'settings.web3.verificationMessage': 'Felhasználó ellenőrzése {username} Literary Universe számára. Kód: {code}',
    'settings.web3.unlink': 'Pénztárca eltávolítása',
    'settings.web3.linkingMessage': 'Kérjük, erősítse meg, hogy szeretné összekapcsolni a pénztárcáját a Literary Universe-el. Kód: {code}',
    'settings.web3.linkError': 'Ez a cím már szerepel az adatbázisunkban, és nem lehet hozzárendelve!',
    // Reader settings
    'settings.reader.title': 'Olvasó beállítások',
    'settings.reader.darkMode': 'Mindig sötét módban jelenítse meg',
    'settings.reader.asideView': 'Mutassa a varázslatos oldalsávot',
    'settings.reader.textSize': 'Mutassa a szöveget nagyobb betűmérettel',
    'settings.reader.storyRecommendations': 'Történet Ajánlások',
    'settings.reader.storyRecommendationsHelp': 'Személyre szabott történetajánlások engedélyezése.',
    // AI settings
    'settings.ai.title': 'AI beállítások',
    'settings.ai.explained': 'Állítsa be, hogyan működjenek a mesterséges intelligencia funkciók az Ön számára az Irodalmi Univerzumban.',
    // Accessibility
    'settings.accessibility.title': 'Olvasó elérhetőség',
    'settings.accessibility.openDyslexic': 'Használja az OpenDyslexic betűtípust',
    'settings.accessibility.paragraphStripes': 'Váltakozó háttérszín a bekezdésekben',
    'settings.accessibility.paragraphHighlighting': 'Jelölje ki a jelenlegi bekezdést, amelyre rámutat',
    'settings.accessibility.ruler': 'Rögzítsen egy vonalzót az egérhez',
    // Story Recommendations
    'settings.storyRecommendations.title': 'Ajánlások a történethez',
    'settings.storyRecommendations.explained': 'Engedélyezze a személyre szabott történetajánlásokat az alkalmazásban az olvasási preferenciái és előzményei alapján.',
    'settings.tab.legal': 'Jogi dokumentumok',
    'settings.tab.exportDelete': 'Adatok exportálása és fiók törlése',
    'settings.languages.uiLanguage': 'Interfész nyelv',
    'settings.languages.readingLanguage': 'Olvasott nyelv',
    'settings.languages.readingLanguageExplained': 'A történetek keresésekor a történetek és fordításaik ezen a nyelven kerülnek felajánlásra, hacsak Ön nem ad meg mást.',
    'settings.biography.help': 'Mesélj magadról másoknak',
    'settings.username.help': 'Az Ön egyedi felhasználóneve a platformon',
    'settings.interests.tags.custom.help': 'Adja meg a címkék vesszővel elválasztott listáját',
    'settings.interests.tags.placeholder': 'Címkék hozzáadása',
    'settings.interests.avoidGenres.help': 'Válassza ki azokat a műfajokat, amelyeket nem szeretne látni az ajánlásokban.',
    'settings.interests.avoidGenres': 'Kerülendő műfajok',
    'settings.notifications': 'Értesítések és hírlevelek',
    'settings.kindleEmail': 'Az Ön Kindle e-mail címe',
    'settings.kindleEmail.explained': 'Ha ez a beállítás megvan, akkor lehetőség szerint felajánljuk Önnek, hogy a történeteket egyetlen kattintással elküldheti a Kindle készülékére. A Kindle e-mail címét az Amazon beállításaiban a Tartalom és eszközök -> Eszközök -> Eszközök -> válassza ki a Kindle-t a részletek megtekintéséhez, és ott találja az e-mail címét.',
    'settings.tracking.title': 'Nyomon követés és statisztikák',
    'settings.tracking.description': 'Nyomon követheti olvasási és írási idejét, hogy részletes statisztikákat kapjon olvasási szokásairól és az írásbeli fejlődéséről. Ezeket a statisztikákat a könyvtárban és a műhelyben is megtekintheti.',
    'settings.tracking.reading.title': 'Olvasási idő',
    'settings.tracking.reading.description': 'Nyomon követheti a történetek és fejezetek olvasásával töltött időt. Ezek az adatok segítenek megérteni az olvasási szokásokat, és névtelenül megosztjuk őket a történetek szerzőivel, hogy megmutassuk nekik, mennyire elkötelezettek az olvasók a műveik iránt.',
    'settings.tracking.writing.title': 'Írás ideje',
    'settings.tracking.writing.description': 'Nyomon követheti a történetek, fejezetek és lexikonbejegyzések írására fordított időt. Ez olyan részletes mérőszámokat tartalmaz, mint a gépelési tevékenység, a szószámok és a napszakok mintái.',
    'settings.tracking.trackWritingTime': 'Kövesse nyomon az írási időt',
    'settings.tracking.trackReadingTime': 'Kövesse nyomon az olvasási időt'
};