export default {
    'workshop.title': 'A munkád',
    'workshop.noneassigned': 'Még nem kaptál egyet sem.',
    'workshop.notavailable': 'Ez a funkció még nem érhető el.',
    'workshop.none': `Jelenleg nincs {type, select,
      universe {univerzumod}
      story {történeted}
      fanfiction {rajongói fikciód}
      other {}
    }. Hozz létre most egyet!`,
    'workshop.collab': 'Együttműködő munka',
    'workshop.betareadings': 'Béta olvasások',
    'workshop.translations': 'Fordítások',
    'workshop.createnew': 'Új létrehozása...',
    'workshop.story.standalone': 'Független történet',
    'workshop.story.standalone.desc': 'Ez egy független történet.',
    'workshop.controlpanel': '{name} vezérlőpult',
    'workshop.universe.page': 'Univerzum oldal',
    'workshop.fictionaltime': 'Kitalált idő',
    'workshop.dashboard.name': '{name} vezérlőpult',
    'workshop.stories.in': 'Történetek a(z) {universe}-ban',
    'workshop.universe.nostories': 'Nincsenek történetek ebben az univerzumban.',
    'workshop.story.chapter.add': 'Új fejezet',
    'workshop.universe.new': 'Új univerzum létrehozása',
    'workshop.universe.publish': 'Univerzum közzététele',
    'workshop.universe.publishing.notice': 'Ha nem teszed közzé az univerzumot, akkor automatikusan közzé lesz téve, amikor az első a univerzumhoz kapcsolódó történet közzé lesz téve.',
    'workshop.universe.settings': '{universe} univerzum beállítások',
    'workshop.universe.publishedOn': 'Ez az univerzum megjelent a következő helyen: {date, date, long} {date, time, short}',
    'workshop.universe.description': 'Univerzum leírás',
    'workshop.settings.title': 'Cím',
    'workshop.description': 'Leírás',
    'workshop.language.primary': 'Elsődleges nyelv',
    'workshop.publication.options': 'Közzétételi lehetőségek',
    'workshop.rating': 'Általános besorolás',
    'workshop.universe.rating.desc': 'Az ennél magasabb besorolású történetek és fanfiction-ök el lesznek rejtve az univerzum oldalának listájáról az anonim felhasználók és a megfelelő életkorú felhasználók számára.',
    'workshop.universe.license': 'Univerzum licenc',
    'workshop.universe.genre.pick': 'Válassz műfajt az univerzumhoz',
    'workshop.story.genre.pick': 'Válassz műfajokat a történethez',
    'workshop.cover': 'Borító',
    'workshop.nothingtosee': 'Nincs itt semmi látnivaló...',
    'workshop.story.cannon': 'Kanonikus történet',
    'workshop.story.cannon.desc': 'Ez a történet kanonikus a(z) {universe} univerzumban.',
    'workshop.story.cannon.desc.create': 'Ez a történet létre lesz hozva egy kanonikus történetként a(z) {universe} univerzumban.',
    'workshop.story.fanfiction.search': 'Írd be az univerzum nevét (azt a könyvtáradban kell lennie). Majd válassz a javaslatok közül.',
    'workshop.story.error.nogenres': 'Legalább egy műfajt ki kell választanod.',
    'workshop.story.error.toomanygenres': 'Egy történethez csak két műfaj engedélyezett.',
    'workshop.story.error.fanfiction.selectuniverse': 'Ki kell választanod eredeti univerzumot a fan fictionödnek!',
    'workshop.story.error.tags.toomany': 'Egy történeten belül csak 10 címke lehet.',
    'workshop.story.new': 'Új történet létrehozása',
    'workshop.story.publishing.notice': 'A történet automatikusan közzé lesz téve, amint közzéteszed az első fejezetet.',
    'workshop.settings.edit': 'Beállítások szerkesztése',
    'workshop.story.publishedOn': 'Ez a történet megjelent a következő helyen: {date, date, long} {date, time, short}',
    'workshop.story.settings': 'Történet beállítások',
    'workshop.settings.basic': 'Alapbeállítások',
    'workshop.settings.genres': 'Műfajok (max 2)',
    'workshop.story.license': 'Történet licenc',
    'workshop.story.settings.universe': 'Univerzum beállítások',
    'workshop.settings.tags': 'Címkék',
    'workshop.revision': 'Változat',
    'workshop.revisions.title': '{story}: {chapter} Változatok',
    'workshop.revisions.current': 'Aktuális vázlat',
    'workshop.revisions.new.beta': 'Új változat létrehozása a vázlatból.',
    'workshop.revisions.new.public': 'Új nyilvános változat létrehozása a vázlatból.',
    'workshop.revisions.toeditor': 'Ugrás az szerkesztőbe',
    'workshop.revisions.comments': 'Változat megjegyzések',
    'workshop.revisions.comments.title': '{story}: {chapter} - Változat {revision} - Megjegyzések',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {a béta olvasóknak}
      readers {Nyilvános}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'Először létre kell hoznod egy változatot.',
    'workshop.revisions.comments.select': 'Válassza ki a verziót',
    'workshop.collaborators.noresults': 'Nincs találat',
    'workshop.collaborators.add.beta': 'Beta olvasó hozzáadása',
    'workshop.collaborators.add.collaborator': 'Együttműködő hozzáadása',
    'workshop.collaborators.add.translator': 'Fordító hozzáadása',
    'workshop.collaborators.language.add': 'Új fordítás létrehozása',
    'workshop.translations.stories': 'Fordítások - történetek',
    'workshop.translations.universes': 'Fordítások - univerzumok',
    'workshop.revisions.beta.none': 'Jelenleg nincsenek javítások.',
    'reader.asidetoggle': 'Oldalsáv információ váltása',
    'workshop.translation.original': 'Eredeti:',
    'workshop.translation.original.title': 'Eredeti cím:',
    'workshop.translation.original.description': 'Eredeti leírás:',
    'workshop.translation.original.cover': 'Eredeti borító',
    'workshop.translation.original.tags': 'Eredeti címkék',
    'workshop.cover.alt': 'borító kép',
    'workshop.translation.updatedOrig': 'Eredeti utolsó frissítése: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'Fordítás utolsó frissítése: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'Utolsó javítás {revision, number}, az eredetinél: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'Utolsó javítás {revision, number}, a fordításnál: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `További {type, select,
    collaborator {közreműködők}
    beta {béta olvasók}
    translator {fordítók}
    other {}
  }hozzáadásához növelned kell a tagsági szintedet.`,
    'workshop.collaborators.requests.sent': 'Elküldött kérelmek',
    'workshop.collaborators.requests.invite': `Meghívást kaptál, hogy {role, select,
    beta {béta olvasó}
    translator {fordító}
    collaborator {közreműködő}
    other {}
  } legyél a következőhöz:`,
    'workshop.collaborators.requests.dashboard': `Meghívást kaptál a következő együttműködésre: {count, plural,
    zero {nincs munka}
    one {egy irodalmi mű}
    other {# irodalmi mű}
  }.`,
    'workshop.collaborators.language.added': 'Nyelv hozzáadva',
    'workshop.story.noChaptersFound': 'Nem található fejezet.',
    'workshop.fanfic.needUniverseInLibrary': 'Sok univerzum van ott. Kérlek először add hozzá azokat az univerzumokat a könyvtáradhoz, amelyekben írni szeretnél, hogy megtalálhassuk őket.',
    'workshop.fanfic.findUniverse': 'Indulj és találj egy fantasztikus univerzumot!',
    'workshop.encSettings': 'Enciklopédia beállítások',
    'workshop.collaborators.removeUser': 'Felhasználó eltávolítása',
    'workshop.collaborators.cancelInvite': 'Meghívás megszakítása',
    'workshop.universe.createFirstStory': 'Hozd létre az első történetet',
    'workshop.storylines': 'Történetvonalak',
    'workshop.scenesManager': 'Jelenetek kezelése',
    'workshop.collaborators.addRoleForLang': 'Hozzáadás {role} ehhez: {language}',
    'workshop.beta.revisionInfo': 'Ez a(z) {revision, number}verzió, létrehozva: {createdAt, date, long}.',
    'workshop.story.notes.title': 'A jegyzeteid a következőhöz: {storyTitle}',
    'workshop.story.notes.desc': 'Áttekintő jegyzetek a történethez.',
    'workshop.story.notes.tile': 'Áttekintő jegyzetek',
    'workshop.hideOrgs': 'Tartalom elrejtése szervezetektől',
    'workshop.translation.premium': 'A fordítások hozzáadásához legalább Explorer előfizetésre van szükséged.',
    'workshop.story.finished': 'A történet befejezve',
    'workshop.story.publishing.externalSellingNotice': 'Mivel az Irodalmi Univerzumon kívül értékesítesz, most közzéteheted a történetet. A boltod listájának linkei megjelennek a történeten vagy a jelenlegi történet végén, amit itt publikálsz.',
    'workshop.sharing.publicURL': 'Nyilvános verzió',
    'workshop.fictionalTime.title': 'Fiktív idők a következőhöz: {universeName}',
    'workshop.fictionalTime.none': 'Jelenleg nincs beállítva semmilyen képzeletbeli idő.',
    'workshop.fictionalTime.createNow': 'Hozzon létre egyet most!',
    'workshop.fictionalTime.createTitle': 'Hozzon létre egy új képzeletbeli időt',
    'workshop.fictionalTime.editTitle': 'Szerkesztés {ftName}',
    'workshop.fictionalTime.formDescription': `Itt létrehozhatod a saját fiktív idődet. Jelenleg ez az eszköz korlátozott, és csak a
        szimmetrikus idők létrehozására képes. Ez azt jelenti, hogy nem tudod majd újraalkotni a maja naptárat vagy a Gergely-naptárt. Jelenleg a
        ez az eszköz azt várja el, hogy minden időszak mindig azonos legyen, pl. a hónapok mindig 30 naposak legyenek, kivétel nélkül, és így tovább
        . A későbbi verziókban foglalkozni fogunk ezzel, de addig is ez az eszköz inkább alkalmas elsősorban
        sci-fi alapú időrendszerek létrehozására.`,
    'workshop.fictionalTime.timeName': 'Idő neve',
    'workshop.fictionalTime.basicInfo': 'Alapvető információk',
    'workshop.fictionalTime.timeSetup': 'Idő beállítása',
    'workshop.fictionalTime.linkedToET': 'Kezdődik ez az idő egy Földi dátumon (Gergely-naptár)?',
    'workshop.fictionalTime.timeDeclaration': 'Idő nyilatkozat',
    'workshop.fictionalTime.declarationLocation': 'Hol kell feltüntetni az idő nevét?',
    'workshop.fictionalTime.declarationBefore': 'Egységek előtt',
    'workshop.fictionalTime.declarationAfter': 'Egységek után',
    'workshop.fictionalTime.declarationNone': 'Egyik sem',
    'workshop.fictionalTime.units': 'Egységek',
    'workshop.fictionalTime.ETStart': 'Ez az idő kezdő dátuma',
    'workshop.fictionalTime.unitsDescFirst': 'Hány egység van ebben az egységben ezredmásodpercben?',
    'workshop.fictionalTime.unitsDesc': 'Hány egység van ez az egy az előzőhöz képest?',
    'workshop.fictionalTime.unitsName': 'Egység neve',
    'workshop.fictionalTime.unitsSeparator': 'Elválasztó az előző egységtől',
    'workshop.fictionalTime.unitAdd': 'Egység hozzáadása',
    'workshop.fictionalTime.clocks': 'Órák',
    'workshop.fictionalTime.unitTransfer': 'Egységek átvitele',
    'fictionalTime.pageStartElapsedTime': 'Az oldal megnyitása óta eltelt idő',
    'fictionalTime.currentTime': 'Aktuális idő',
    'workshop.shoppingExternal.options': 'Külső vásárlási lehetőségek',
    'workshop.shoppingExternal.explainer': 'Ha a történeted máshol van eladva, itt állíthatod be a linkeket. A linkek akkor jelennek meg a tartalom helyett vagy a tartalom végén, amelyiket előnézetként választasz.',
    'workshop.shoppingExternal.amazonStore': 'Amazon bolt',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Bolt neve',
    'workshop.shoppingExternal.itemUrl': 'Elem URL',
    'workshop.shoppingExternal.storesOther': 'Egyéb üzletek',
    'fictionalTime.units.milliseconds': '{units, number} mill másodperc',
    'fictionalTime.countdownToStart': 'Visszaszámlálás az idő kezdete előtt',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 nap }
      other {{days} napok }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {másodperc}
      other {másodperc}
    }}
    minutes {{units, plural,
      one {perc}
      other {perc}
    }}
    hours {{units, plural,
      one {óra}
      other {óra}
    }}
    days {{units, plural,
      one {nap}
      other {nap}
    }}
    years {{units, plural,
      one {év}
      other {év}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'Tól',
    'fictionalTime.inputSelectTimeUnit': 'Válassz időegységet',
    'fictionalTime.inputSelectETUnit': 'Válassz Földi időegységet',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Oldalsáv Eszköztár',
    'workshop.writerSidebar.description': 'Üdvözöllek a történetedben! Ez az oldalsáv könnyű hozzáférést biztosít az összes történetedhez kapcsolódó erőforráshoz. Nézd meg a fenti ikonokat, hogy láthasd a legújabb hozzászólásokat, a jegyzeteidet és még sok mást!',
    'workshop.story.authorsNotesExplained': 'A jegyzeteid az olvasók számára, hogy elolvashassák a fejezet elején.',
    'workshop.story.chapterSortSwitch': 'Fejezet sorrendjének megváltoztatása',
    'workshop.universe.monetizationTitle': '{title} monetizáció',
    'workshop.story.monetizationTitle': '{universeTitle}: {storyTitle} monetizáció',
    'workshop.universe.monetizationWebMonetization': 'Web Monetizáció',
    'workshop.webMonetization.explain': 'A Web Monetizáció az alapján fizetést fog közvetíteni Önnek, hogy a felhasználó mennyi időt tölt a tartalmánál. A profil monetizációs beállításainál beállíthatja saját fizetési mutatóját. Itt dönthet a Web Payment engedéllyel rendelkező együttműködő partnereivel történő megosztásról. A Literary Universe automatikusan 10%-ot vesz el.',
    'workshop.webMonetization.revShare': 'A Web Monetizáció korlátozása miatt a valószínűségi bevételmegosztás van használva. A valószínűségi bevételmegosztás úgy működik, hogy véletlenszerűen választ a meghatározott fizetési mutatók listájából minden alkalommal, amikor egy web monetizált látogató betölti az oldalát. A látogató a kiválasztott mutatónak fizet addig, amíg az oldal újra nem töltődik be vagy bezáródik.',
    'workshop.webMonetization.revShareMore': 'Tudjon meg többet a Valószínűségi Bevételek Megosztásáról. Ugyanazt a kódot használjuk, mint ezen az oldalon.',
    'workshop.story.notEligible.licence': `A történet licenc nem engedélyezi a monetizációt.`,
    'workshop.universe.notEligible.licence': `Az univerzum licenc nem engedélyezi a monetizációt.`,
    'workshop.story.notEligible.fanFiction': 'A Fan Fiction történetek nem jogosultak a monetizációra.',
    'workshop.revShare.mustBe100': 'A megosztásnak 100%-nak kell lennie',
    'workshop.revShare.LUCut': 'Literary Universe és fizetési kapu',
    'workshop.revShare.unallocated': 'Nem kiosztott részesedés {total, number, ::percent}',
    'workshop.revShare.allocation': '{username} - {total, number, ::percent}',
    'workshop.revShare.undecided': 'Nem döntött',
    'workshop.revShare.origLangCreators': 'Eredeti nyelv alkotói',
    'workshop.story.prolog': 'Előszó',
    'workshop.story.chapter': '{sequence, number}fejezet',
    'workshop.work.includesAds': 'Vannak reklámok vagy termékplasztikok a műben?',
    'workshop.universe.forumSettings': 'Belső univerzum fórum beállítások',
    'workshop.universe.forum': 'Belső {universeName} fórum',
    'workshop.ratingAdjusted': 'Panaszok miatt módosítottuk az értékelését arra az értékre, amelyet megfelelőnek tartottunk. Ennek következtében az értékelés módosítása most letiltva van.',
    'workshop.selectCollaborator': 'Válasszon együttműködőt',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Vázlat',
    'workshop.chapterStatus.scheduled': 'Ütemezett',
    'workshop.chapterStatus.published': 'Közzétett',
    'workshop.story.continuedIn': 'Mely történetek folytatják ezt a történetet?',
    'workshop.story.continuedPlaceholder': 'Válasszon történetet ebből az univerzumból',
    'workshop.universe.isAIGenerated': 'Az univerzum tartalma mesterséges intelligencia által generált?',
    'workshop.universe.isAIGeneratedTooltip': 'Kérjük, jelezze nekünk, ha az univerzum tartalmának bármely része mesterséges intelligencia által vagy annak segítségével lett generálva. Ezt az információt a megfelelő címkézéshez használjuk, és az AI programok generálásának módja miatt néhány korlátozás és megkötés lehet.',
    'workshop.story.isAIGenerated': 'A történet mesterséges intelligencia által generált?',
    'workshop.story.isAIGeneratedTooltip': 'Kérjük, jelezze nekünk, ha a történet bármely része mesterséges intelligencia által vagy annak segítségével lett generálva. Ezt az információt a megfelelő címkézéshez használjuk, és az AI programok generálásának módja miatt néhány korlátozás és megkötés lehet.',
    'workshop.publicationAgreement.aria': 'Munkára vonatkozó publikációs megállapodás',
    'workshop.publicationAgreement.intro': 'Örömmel vesszük, hogy minket választott a kreatív munkájának publikálásához. Mielőtt folytatnánk, csak arra kérjük, hogy tekintse át a publikációs megállapodásunkat, hogy megértse, mit jelent jogi szempontból.',
    'workshop.sortChapters': 'Rendezési sorrend:',
    'workshop.sortChapters.ascending': 'Kezdettől',
    'workshop.sortChapters.descending': 'A legfrissebb',
    'workshop.sortChapters.aria': 'Válasszon, hogy melyik módon szeretné rendezni a fejezetek listáját',
    'workshop.hiatus.btn': 'A történet állapotának megváltoztatása szünetre',
    'workshop.cancelled.btn': 'A történet állapotának megváltoztatása megszakítottá',
    'workshop.complete.btn': 'A történet állapotának megváltoztatása befejezettté',
    'workshop.statusChange.modalTop': 'Biztosan meg akarja változtatni az állapotot erre:',
    'workshop.statusName.hiatus': 'Szünet',
    'workshop.statusName.cancelled': 'Megszakított',
    'workshop.statusName.completed': 'Befejezve',
    'workshop.statusExplain.hiatus1': 'A szünet azt jelenti, hogy egy ideig szünetelteti a történeten való munkát bármilyen okból. Ez megmondja az olvasóknak, hogy ne várjanak új frissítéseket a következő hetekben vagy akár néhány hónapig sem.',
    'workshop.statusExplain.hiatus2': 'A szünet állapot automatikusan megszűnik, ha közzétesz egy fejezetet. Vagy megváltoztathatja önállóan.',
    'workshop.statusExplain.hiatus3': 'Ha hat hónapig szünetelteti a történetet, mi automatikusan megszüntetjük ezt a történetet.',
    'workshop.statusExplain.cancelled1': 'Sajnáljuk, hogy nem tud folytatni a történeten dolgozást. Másrészről örülünk, hogy hajlandó értesíteni az olvasókat.',
    'workshop.statusExplain.cancelled2': 'A történet megszakításával az olvasók tudomást szereznek arról, hogy ne várjanak új frissítéseket.',
    'workshop.statusExplain.cancelled3': 'Mindig visszaállíthatja ezt azzal, hogy közzétesz egy fejezetet vagy megváltoztatja az állapotot.',
    'workshop.statusExplain.finished1': 'Gratulálunk! A kemény munka után végre elérte a hihetetlen utazás végét. Habár most véget ér a történet, reméljük, hogy lesznek még újabb történetek a jövőben, de most pihenjen és élvezze az érdemelt pihenést.',
    'workshop.statusExplain.finished2': 'A történet befejezettnek jelölése azt jelenti, hogy a történet befejeződött. Habár nem kell új fejezeteket hozzáadnia, mi nem akadályozzuk meg benne, és nem is rossz ötlet különleges fejezetek hozzáadása, például több epilógus hozzáadása minden szereplőnek.',
    'workshop.statusExplain.finished3': 'Bár mindig visszavonhatja ezt az állapotot, erősen javasoljuk, hogy ne tegye. Ha a történet folytatódni fog, akkor talán jobb új történetet kezdeni.',
    'workshop.status.goActive': 'Tegye aktívvá újra a történetet',
    'workshop.statusChangeEmail.storyIntro': 'Szeretnénk tájékoztatni, hogy a történeted:',
    'workshop.statusChangeEmail.hiatusTitle': 'A történeted státusza automatikusan hiatus-ra lett állítva',
    'workshop.statusChangeEmail.hiatusIntro': 'Inaktivitás miatt a történeted státusza automatikusan hiatus-ra lett állítva.',
    'workshop.statusChangeEmail.hiatusWhy': 'A történet hiatus-ra került, mivel több mint 6 hónapja nem jelent meg új fejezet.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'Ez a státusz automatikusan feloldódik, ha közzéteszel egy új fejezetet. Ha a következő 6 hónapban nem jelentetsz meg új fejezetet, automatikusan töröljük a történetet.',
    'workshop.statusChangeEmail.cancellationIntro': 'A történeted státusza automatikusan törölve lett.',
    'workshop.statusChangeEmail.cancellationWhy': 'Ez azért történt, mert nem írtál új fejezetet a történethez, mióta 6 hónappal ezelőtt szüneteltetted. Egy év inaktivitás után automatikusan töröltre állítjuk a történeteket, hogy az olvasók tudják, mely történetek aktívak.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'Ez a státusz automatikusan feloldódik, ha közzéteszel egy új fejezetet. Ha nem tervezel tovább dolgozni ezen a történeten, nincs más teendőd.',
    'workshop.startCreating': 'Készítés megkezdése',
    'workshop.ownWork': 'Saját munka',
    'workshop.list.thumbs': 'Bélyegképek listája',
    'workshop.list.list': 'Rövid lista',
    'workshop.fanfiction.new': 'Új fan fiction létrehozása',
    'workshop.videoTrailerLink': 'Videó előzetes link',
    'workshop.videoTrailerPlayerTitle': 'Történet videó előzetes lejátszó',
    'workshop.videoTrailer.supportedPlaftorms': 'Támogatjuk a Youtube-ot, a Vimeo-t és az Odysee-t',
    'workshop.videoTrailer.rumble': 'Támogatjuk a Rumble-t is, de ne felejtsd el másolni az IFRAME URL-t.',
    'workshop.videoTrailer.suggestPlatforms': 'Hiányzik a videóplatformod? Tudasd velünk a <a>visszajelzés</a> segítségével!',
    'workshop.cover.edit': 'Fedélcsere',
    'workshop.collaborator.leave': 'Hagyja el a projektet',
    'workshop.collaborator.leaveTitle': 'Kérjük, erősítse meg, hogy el akarja hagyni a {workName}címet.',
    'workshop.collaborator.leaveExplained': 'A projekt elhagyása azt jelenti, hogy elveszít minden hozzáférést, társulást és jogosultságot. Ha nem vagy biztos benne, hogy mindez mit jelent, akkor valószínűleg nem erre akartál kattintani.',
    'workshop.collaborators.leftInfo': 'Left on {date, date}',
    'workshop.collaborators.removedInfo': 'Eltávolítva: {date, date}',
    'workshop.aiGeneratedAdjusted': 'A tartalom mesterséges intelligencia generálási státuszát egy felhasználói jelentés alapján egy rendszergazda módosította, és nem módosítható.',
    'workshop.theWay.authorProgress': 'Szerző Haladás',
    'workshop.universe.preventPublishing': 'A történetek közzétételének megakadályozása',
    'workshop.universe.preventPublishingTooltip': 'Ha engedélyezve van, ebben az univerzumban nem lehet történeteket közzétenni. Ez olyan univerzumok esetében hasznos, amelyek még fejlesztés alatt állnak, vagy olyan univerzumok esetében, amelyeket csak magánhasználatra szánnak.',
    'workshop.story.preventPublishing': 'A közzététel megakadályozása',
    'workshop.story.preventPublishingTooltip': 'Ha engedélyezve van, ez a történet nem tehető közzé. Ez olyan történeteknél hasznos, amelyek még fejlesztés alatt állnak, vagy olyan történeteknél, amelyeket csak magáncélú felhasználásra szánnak.',
    'workshop.story.preventPublishingTooltipUniverse': 'A közzététel megakadályozott, mivel az univerzumban engedélyezve van a közzététel megakadályozása beállítás.',
    'workshop.revisions.new.public.disabled': 'Nem lehet közzétenni, ha a történet beállításaiban engedélyezve van a közzététel megakadályozása.',
    'workshop.publishing.restricted': 'A jó magaviselet megsértése miatt letiltottuk a publikálási lehetőségét.',
    'workshop.story.buyingSettings': 'Értékesítési beállítások',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI-generált tartalom',
    'workshop.chapter.aiGenerated.tooltip': 'Jelölje meg ezt a fejezetet mesterséges intelligencia által generált tartalmat tartalmazónak',
    'workshop.chapter.aiGenerated.description': 'Ez a fejezet mesterséges intelligencia segítségével létrehozott tartalmat tartalmaz.',
    'workshop.chapter.aiModel': 'AI modell',
    'workshop.chapter.aiModel.tooltip': 'Válassza ki a tartalom generálásához használt mesterséges intelligencia modellt.',
    'workshop.chapter.aiModel.custom': 'Custom',
    'workshop.chapter.aiModel.custom.placeholder': 'Adja meg a mesterséges intelligencia modell nevét',
    'workshop.chapter.aiGenerated.locked': 'A mesterséges intelligencia tartalmi jelölés nem módosítható, mivel azt a moderációs csapat már módosította.',
    'workshop.monetization.aiNotEligible': 'A mesterséges intelligencia által generált tartalom nem jogosult a pénzzé tételre.'
};