/**
 * @authors Jan Dvorak
 */
export default {
    siteName: 'ಸಾಹಿತ್ಯಿಕ ಬ್ರಹ್ಮಾಂಡ',
    twitterHandle: '@lituniapp',
    'site.description': 'ಸಾಹಿತ್ಯಿಕ ಜಗತೆ ಗ್ರಂಥ ಜಗತೆಗಳ ಸಮಗ್ರ ಸೃಜಿಸುವ ಮತ್ತು ಪ್ರಕಟಣೆ ಮಾಡುವ ಒಂದು ಆಲ್ಮೆಕ್ಲೆ ಮತ್ತು ಪ್ಲ್ಯಾಟ್‌ಫಾರಂ.',
    'site.keywords': 'ಸೃಜಿಸುವ ಬರಹ, ಭೌತವಿಜ್ಞಾನ ಕಥೆ, ಸೈ-ಫೈ, ಕಲ್ಪನಾ ಕಥೆ, ಬರಹವೊಂದು, ಪ್ರಕಟಣೆ, ಕಥೆಗಳು, ಜಗತ್ತು, ವೆಬ್ ನವಲ್, ವೆಬ್‌ನವಲ್',
    'site.logoAlt': 'ಸಾಹಿತ್ಯ ಬ್ರಹ್ಮಾಂಡ ಲೋಗೋ',
    mobileMenu: 'ಮೊಬೈಲ್ ಮೆನು',
    'common.signin': 'ಲಾಗಿನ್',
    'common.signup': 'ನೆರವಾಗಿಕೊಳ್ಳಿ',
    'common.signout': 'ಲಾಗ್ ಔಟ್',
    'common.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'common.discovery': 'ಆವಿಷ್ಕಾರ',
    'common.library': 'ಗ್ರಂಥಾಲಯ',
    'common.library.own': 'ನಿಮ್ಮ ಗ್ರಂಥಾಲಯ',
    'common.workshop': 'ಕಾರ್ಯಶಾಲೆ',
    'common.pm': 'ಸಂದೇಶಗಳು',
    'common.settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
    'common.options': 'ಆಯ್ಕೆಗಳು',
    'common.profile': 'ಪ್ರೊಫೈಲ್',
    'common.blog': 'ಬ್ಲಾಗ್',
    'common.blogs': 'ಬ್ಲಾಗ್‌ಗಳು',
    'common.about': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'common.accessdenied': 'ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ',
    'common.accessdenied.msg': 'ನೀವು ಇಲ್ಲಿಗೆ ಪ್ರವೇಶವನ್ನು ಪಡೆಯಲು ಅನುಮತಿ ಇಲ್ಲದೆ ಇದ್ದೀರಿ. ನೀವು ಇಲ್ಲಿ ಪ್ರವೇಶವನ್ನು ಹೊಂದಬೇಕೆಂದು ಆಗಿದ್ದರೆ, ದಯವಿಟ್ಟು ಮಾಲಿಕನನ್ನು ಸಂಪರ್ಕಿಸಿ ಮತ್ತು ಅವರಿಗೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಎರಡರಷ್ಟು ಪರಿಶೀಲಿಸುವಂತೆ ಹೇಳಿ.',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.add': 'ಸೇರಿಸಿ',
    'common.save': 'ಉಳಿಸಿ',
    'common.email': 'ಇಮೇಲ್',
    'common.soon': 'ಬೇಗ ಬರುತ್ತಿದೆ...',
    'common.search': 'ಹುಡುಕು',
    'common.search.do': 'ಹುಡುಕು',
    'common.searching': 'ಹುಡುಕುತ್ತಿದೆ...',
    'common.report': 'ವರದಿ',
    'common.user': 'ಬಳಕೆದಾರ',
    'common.users': 'ಬಳಕೆದಾರರು',
    'common.showmore': 'ಹೆಚ್ಚಿನ ವಿವರಗಳು',
    'common.futurefeature.title': 'ಭವಿಷ್ಯ ಸೌಲಭ್ಯ',
    'common.futurefeature.text': 'We apologize, but this feature is not available at this time. We are working hard to make it available as soon as possible.',
    'common.nothingfound': 'ಯಾವುದೇ ಹುಡುಕಾಟವನ್ನು ಹೊಂದಲಾಗಲಿಲ್ಲ',
    'common.explore': 'ಅನ್ವೇಷಿಸು',
    'common.by': 'ಮೂಲಕ {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'ಸ್ಕ್ರ್ಯಾಚ್‌ಪ್ಯಾಡ್',
    'common.scratchpad.own': 'ನಿಮ್ಮ ಸ್ಕ್ರ್ಯಾಚ್‌ಪ್ಯಾಡ್',
    'common.news': 'ಸುದ್ದಿ',
    'common.encyclopedia': 'ಜ್ಞಾನಕೋಶ',
    'common.art': 'Art',
    'common.story': 'ಕಥೆ',
    'common.stories': 'ಕಥೆಗಳು',
    'common.universe': 'ಸಂಪೂರ್ಣ ಬ್ರಹ್ಮಾಂಡ',
    'common.universes': 'ಬ್ರಹ್ಮಾಂಡಗಳು',
    'common.collaborator': 'ಸಹಕರಿಸುವವರು',
    'common.collaborators': 'ಸಹಕರಿಸುವವರುಗಳು',
    'common.translator': 'ಭಾಷಾಂತರಿ',
    'common.translators': 'ಭಾಷಾಂತರಿಗಳು',
    'common.betareader': 'ಬೀಟಾ ಓದುಗರು',
    'common.betareaders': 'ಬೀಟಾ ಓದುಗರುಗಳು',
    'common.post': 'ಪೋಸ್ಟ್',
    'common.statistics': 'ಸಂಖ್ಯೆಗಳು',
    'common.lang.select': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    'common.submit': 'ಸಲ್ಲಿಸು',
    'common.close': 'ಮುಚ್ಚು',
    'common.comment': 'ಟಿಪ್ಪಣಿ',
    'common.comments': 'ಟಿಪ್ಪಣಿಗಳು',
    404: 'ಪುಟ ಕಂಡುಬರಲಿಲ್ಲ',
    'search.users': 'ಬಳಕೆದಾರರ ಹುಡುಕು',
    'search.user': 'ಬಳಕೆದಾರನ ಹುಡುಕು',
    'common.help': 'ಸಹಾಯ',
    'common.or': 'ಅಥವಾ',
    'common.account.create': 'ಖಾತೆ ತೆರೆಯಿರಿ',
    'signup.username': 'ಬಳಕೆದಾರನ ಹೆಸರು',
    'signup.email': 'ನಿಮ್ಮ ಇಮೇಲ್',
    'signup.password.label': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್',
    'signup.password.repeat': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಮರುಕರೆ',
    'common.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'signin.password.forgot': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಿ?',
    'dashboard.whatsnew': 'ಹೊಸದು ಏನು',
    'dashboard.blog': 'ನಿಮ್ಮ ಬ್ಲಾಗ್',
    'common.footer.tagline': 'ಜಟಿಲ ವಿಶ್ವಗಳನ್ನು ಬರೆದು ಓದುವುದು ಸುಲಭವಾಗಿದೆ.',
    'common.footer.plans': 'ಯೋಜನೆಗಳು ಮತ್ತು ಬೆಲೆಗಳು',
    'common.legal.tos': 'ಸೇವೆಗಳ ನಿಯಮಗಳು',
    'common.legal.community': 'ಸಮುದಾಯದ ಮಾರ್ಗದರ್ಶಿಕೆಗಳು',
    'common.legal.privacy': 'ಗೌಪ್ಯತೆ ನೀತಿ',
    'common.legal.copyright': 'ಪ್ರಾಧಿಕಾರ ಒಪ್ಪಿಗೆ',
    'common.legal.cookies': 'About cookies',
    'cookies.desc': 'This website uses cookies to ensure you get the best experience on our website.',
    'common.legal.versionDisplay': `{type, select,
    tos {Terms of Service}
    community {Community Guidelines}
    privacy {Privacy Policy}
    copyright {Copyright Agreement}
    publishingAgreement {Publishing Agreement}
    cookies {About Cookies}
    other {Agreement}
  } Version {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'A new version ({newVersion}) of this document will come into effect on {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ, ಎಲ್ಲಾ ಪಠ್ಯಗಳು ತಮ್ಮ ಪ್ರತ್ಯೇಕ ಲೇಖಕರಿಗೆ ಸೇರಿದೆ.',
    'premium.only.title': 'ಸದಸ್ಯತ್ವ ಹೆಚ್ಚಿನ ಹಂತಕ್ಕೆ ಇಲ್ಲದೆ ಇದೆ',
    'premium.only.msg': 'ಕ್ಷಮಿಸಿ, ನಿಮ್ಮ ಸದಸ್ಯತ್ವ ಹಂತ ಈ ವ್ಯಾಪ್ತಿಯನ್ನು ಪ್ರವೇಶಿಸಲು ಸಾಲದು.',
    'premium.only.join': 'ಎಲ್ಲರಿಗೂ ಸಾಹಿತ್ಯಿಕ ವಿಶ್ವದಿಂದ ಹೆಚ್ಚಿನ ಪ್ರಯೋಜನ ಪಡೆಯುವ ಯೋಜನೆಗಳನ್ನು ನಾವು ಒದಗಿಸುತ್ತಿದ್ದೇವೆ.',
    'premium.only.link': 'ಇದನ್ನು ನೋಡಿ!',
    'universe.visit': 'ವಿಶ್ವ ಪುಟವನ್ನು ಭೇಟಿಯಾಗಿ',
    'common.fanmanager': 'ಅಭಿಮಾನಿ ವ್ಯವಸ್ಥಾಪಕ',
    'common.fanarts': 'ಅಭಿಮಾನಿ ಕಲಾವಿದರು',
    'common.fanfiction': 'ಅಭಿಮಾನಿ ಕಥಾಕೃತಿ',
    'common.fansettings': 'ಅಭಿಮಾನಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'story.chapter': 'ಅಧ್ಯಾಯ',
    'story.chapters': 'ಅಧ್ಯಾಯಗಳು',
    'story.genre': 'ರಾಸಾಯನಿಕ',
    'story.genres': 'ರಾಸಾಯನಿಕಗಳು',
    'story.read': 'ಓದು',
    'story.lastUpdate': 'ಕೊನೆಯ ಹೊಸತಾಗಿ ಅಪ್ಡೇಟ್ ಮಾಡಲಾಗಿದೆ {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'ಕೊನೆಯಾಗಿ ಮುಗಿದಿದೆ {date, date, medium}.',
    'story.hiatusAt': 'On hiatus from {date, date, medium}.',
    'story.cancelledAt': 'Cancelled on {date, date, medium}.',
    'story.comments.for': '{story} {chapter}ಗೆ ಮಾಡಲಾಗಿರುವ ಕಾಮೆಂಟ್‌ಗಳು.',
    'story.cover.alt': '{story}ಗೆ ಸೇರಿದ ಕಥೆ ಕವರ್ ಚಿತ್ರ',
    'story.note.fanfiction': 'ಗಮನಿಸಿ: ಈ ಕಥೆ {universe} ವಿಶ್ವದ ಫ್ಯಾನ್ ಫಿಕ್ಷನ್ ಆಗಿದೆ.',
    copyrights: 'ಹಕ್ಕುಗಳು',
    'common.challenges': 'ಸವಾಲುಗಳು',
    // for beta only
    'beta.notice': 'Welcome to the Literary Universe BETA! We are excited to let you know that we are officially launching this Friday! We hope that you will join us and support us as we start a new chapter in our journey.',
    'beta.thanks': 'Thank you for your support!',
    'scratchpad.about': 'ನೀವು ನೋಟಗಳು ಮತ್ತು ಕನಸುಗಳನ್ನು ಯಾವುದೇ ಸ್ಥಳದಲ್ಲಿಯೂ ಪಡೆಯಬಹುದು.',
    'common.feedback': 'ಪ್ರತಿಕ್ರಿಯೆ',
    'common.createdOn': 'ಸೃಷ್ಟಿಸಲಾಯಿತು {date, date, long}',
    'common.createdOn.title': 'ಸೃಷ್ಟಿಸಲಾಯಿತು',
    // account types
    admin: 'ನಿರ್ವಾಹಕ',
    'common.saved': 'ಉಳಿದಿದೆ!',
    'common.saving': 'ಉಳಿಸುವುದು...',
    'common.friends': 'ಸ್ನೇಹಿತರು',
    'lang.orig': 'ಮೂಲ ಭಾಷೆ',
    'lang.orig.plus': 'ಮೂಲ ಭಾಷೆ - {language}',
    buy: 'ಖರೀದಿಸಿ',
    confirm: 'ದೃಢೀಕರಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    processing: 'ಪ್ರಕ್ರಿಯೆಗಾಗಿ...',
    'common.noData': 'ಮಾಹಿತಿ ಇಲ್ಲ',
    'error.title': 'ತಪ್ಪು ನಡೆದುದು. ಅಸೂಯೆಕೊಳ್ಳುವುದಕ್ಕೆ ನಾವು ಖಿಂಡಿಸುತ್ತೇವೆ.',
    'error.oops': 'Oops! Something went seriously wrong!',
    'error.apologies': 'We apologize for the inconvenience, we will do our best to fix this soon.',
    'error.400.text': 'Error 400: {errorMessage}',
    'common.offlineStatus': 'ನೀವು ಪ್ರಸ್ತುತ ಆಫ್ಲೈನ್ ಆಗಿದ್ದೀರಿ.',
    male: 'ಪುರುಷ',
    female: 'ಮಹಿಳೆ',
    'common.legal.effectiveAt': 'ಪ್ರಭಾವೀಯವಾಗಿ {date, date, medium}',
    select: 'ದಯವಿಟ್ಟು ಆಯ್ಕೆಮಾಡಿ',
    'common.statusFailed': 'ಸರ್ವರ್‌ಗೆ ಸಂಪರ್ಕ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ.',
    'common.statusConnecting': 'ಸರ್ವರ್‌ಗೆ ಸಂಪರ್ಕಿಸುವ ಪ್ರಯತ್ನ... ({count, number})',
    'slug.checking': 'ಪರಿಶೀಲಿಸುತ್ತಿದೆ...',
    'slug.failed': 'ಈ ವಿಳಾಸ ಈಗಾಗಲೇ ಇದೆ.',
    'slug.success': 'ಈ ವಿಳಾಸ ಲಭ್ಯವಿದೆ!',
    'notVerified.msg': `ನಿಮ್ಮ ಖಾತೆ {option, select,
    email {ಇ-ಮೇಲು}
    wallet {ವಾಲೆಟ್}
    other {ಇ-ಮೇಲು}
    } ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟಿದೆ.`,
    'notVerified.verify': `ದಯವಿಟ್ಟು ನಿಮ್ಮ {option, select,
    email {ಇ-ಮೇಲು}
    wallet {ವಾಲೆಟ್}
    other {ಇ-ಮೇಲು}
    }ಪರಿಶೀಲಿಸಿ.`,
    unknown: 'ಗೊತ್ತಿಲ್ಲ',
    'common.legal.guidelines': 'ಸಮುದಾಯದ ಮಾರ್ಗದರ್ಶಿಕೆಗಳು',
    'errorLoading.title': 'ಪುಟ ಲೋಡ್ ಮಾಡುವಾಗ ತಪ್ಪಾಗಿದೆ',
    'errorLoading.explained': 'An error has occurred while the page was loading. We apologize for the inconvenience. Please try accessing the page again. If the problem persists, please let us know.',
    'errorLoading.retry': 'ಮರುಪ್ರಯತ್ನಿಸಿ!',
    'errorLoading.takingLong': 'ಇದು ಹೆಚ್ಚು ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತಿದೆ...',
    'common.title': 'ಶೀರ್ಷಿಕೆ',
    'common.timelines': 'ಟೈಮ್‌ಲೈನ್‌ಗಳು',
    'common.legal.gdpr': 'ಜಿಡಿಪಿಆರ್',
    'common.legal.gdpr.long': 'ಸಾಮಾನ್ಯ ಡೇಟಾ ಸಂರಕ್ಷಣೆ ನಿಯಮಗಳು',
    'editor.placeholder.link': 'URL ಅನ್ನು ನಮೂದಿಸಿ...',
    'editor.placeholder.connection': 'ಜ್ಞಾನಕೋಶ ಲೇಖನಕ್ಕೆ ಹುಡುಕಾಟ...',
    'editor.saved.beta': 'ಬೀಟಾ ಓದುಗರಿಗೆ ಹೊಸ ಸಂಶೋಧನೆ ರಚಿಸಲಾಗಿದೆ!',
    'editor.saved.public': 'ಹೊಸ ಆವೃತ್ತಿ ಪ್ರಕಟಿಸಲಾಗಿದೆ!',
    goodbyeForever: 'We are sorry to see you go. Was it something we did? Please let us know if that is the case. Either way, we wish you the best in your future endeavors and hopefully we\'ll meet again! Live long and prosper!',
    'goodbyeForever.feedback': 'ನಮಗೆ ಉತ್ತಮವಾಗಿ ಮಾಡಬಹುದಾದ ವಿಷಯಗಳನ್ನು ತಿಳಿಸಿ',
    'common.edit': 'ಸಂಪಾದಿಸು',
    'common.publish': 'ಪ್ರಕಟಿಸು',
    'common.publishAt': 'ಪ್ರಕಟಣೆ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ',
    'common.publishNow': 'Publish now',
    'common.publishLater': 'Publish later',
    'a11y.user.menu': 'ಬಳಕೆದಾರ ಮೆನು',
    'a11y.navigation': 'Navigation',
    'dashboard.profile': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    'profile.website': 'ನನ್ನ ವೈಯಕ್ತಿಕ ವೆಬ್‌ಸೈಟ್',
    'story.notes.concept': 'ಅವಧಾನ',
    'story.notes.settings': 'ಕಥೆಯ ಹಿನ್ನೆಲೆ',
    'story.notes.theme': 'ಥೀಮ್',
    'story.notes.impact': 'ಅನುಕ್ಷಣದ ಪ್ರಭಾವ',
    'story.notes.outcome': 'ಫಲಿತಾಂಶ',
    'story.notes.audience': 'ಲಕ್ಷಿತ ಪ್ರೇಕ್ಷಕರು',
    'story.notes.pitch': 'ಪಿಚ್',
    'story.notes.notes': 'ಟಿಪ್ಪಣಿಗಳು',
    'story.authorsNotes': 'ಲೇಖಕರ ಟಿಪ್ಪಣಿಗಳು',
    'story.notes.audienceAgeGroup': 'Target audience age group',
    'story.notes.audienceSex': 'Target audience sex',
    'common.members': 'ಸದಸ್ಯರು',
    'common.language': 'ಭಾಷೆ',
    next: 'ಮುಂದುವರೆಸು',
    previous: 'ಹಿಂದಿನ',
    'common.legal.tos.short': 'ನಿಯಮಗಳು',
    'common.legal.privacy.short': 'ಗೌಪ್ಯತೆ',
    'premium.increaseLimit': 'ನಿಮ್ಮ ಮಿತಿಯನ್ನು ಹೆಚ್ಚಿಸಲು ಮೆಚ್ಚುಗೆಯಾಗಿ ಮೆರುಗುವುದನ್ನು ಪರಿಗಣಿಸಿ.',
    'common.sharing': 'ಹಂಚಿಕೆ',
    'story.isbn': 'ISBN',
    'common.name': 'ಹೆಸರು',
    'common.remove': 'ತೆಗೆದುಹಾಕು',
    'common.time.milliseconds': 'ಮಿಲಿಸೆಕೆಂಡುಗಳು',
    'common.time.seconds': 'ಸೆಕೆಂಡುಗಳು',
    'common.time.minutes': 'ನಿಮಿಷಗಳು',
    'common.time.hours': 'ಗಂಟೆಗಳು',
    'common.time.days': 'ದಿನಗಳು',
    'common.time.weeks': 'ವಾರಗಳು',
    'common.time.months': 'ತಿಂಗಳುಗಳು',
    'common.time.years': 'ವರ್ಷಗಳು',
    'common.monetization': 'Monetization',
    'common.tab.monetizationOptions': 'Monetization options',
    'common.pagination': 'Pagination',
    'common.forum': 'ಫೋರಮ್',
    'common.2faCode': '2FA ಕೋಡ್',
    'common.2faCodeIntro': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಒಮ್ಮೆಯಾದ ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ, ನಿಮ್ಮ ದೃಢೀಕರಣ ಅನ್ವಯಕ್ರಮದಿಂದ ಉಂಟಾಗಿದೆ.',
    'common.2faCodeAria': '2FA ಕೋಡ್ ನಮೂದಿಸುವ ಮೂಲಕ ಪ್ರವೇಶ ಪಟ್ಟಿ',
    'common.aiContent.model.label': 'AI Model',
    'common.aiContent.model.tooltip': 'Select the AI model that was used to generate content',
    'common.other': 'Other',
    'common.aiContent.model.custom.label': 'Custom AI Model',
    'common.aiContent.model.custom.placeholder': 'Enter the name of the AI model',
    'common.select': 'Select...',
    'common.flashnews': 'ಫ್ಲಾಶ್ ಸುದ್ದಿ',
    'common.defaultLanguage': 'ಪೂರ್ವನಿರ್ಧಾರಿತ ಭಾಷೆ',
    'signin.web3.signMessage': 'ದಯವಿಟ್ಟು ನೀವು ಸಾಹಿತ್ಯ ವಿಶ್ವದಲ್ಲಿ ನಿಮ್ಮ ವಾಲೆಟ್ ಅನ್ನು ಪ್ರಮಾಣೀಕರಣ ವಿಧಾನವಾಗಿ ನಮೂದಿಸಲು ಬಯಸುತ್ತೀರಾ. ಕೋಡ್: {code}',
    'common.web3.confirmationCode': 'ದೃಢೀಕರಣ ಕೋಡ್: {code}',
    'common.roadmap': 'ರೋಡ್‌ಮ್ಯಾಪ್',
    'common.luStatsIFrameOptOut': 'ಸಾಹಿತ್ಯಿಕ ವಿಶ್ವ ಪಟ್ಟಿ ಪಟ್ಟಿಯ ಆಪ್ಟ್-ಔಟ್',
    'common.image': 'ಚಿತ್ರ',
    'common.home': 'ಮುಖಪುಟ',
    'common.administration': 'ಆಡಳಿತ',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'ಗುಂಪುಗಳು',
    'common.upload': 'ಅಪ್ಲೋಡ್',
    'common.backToDashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    'common.accept': 'ಒಪ್ಪಿಗೆ',
    'common.reject': 'ನಿರಾಕರಿಸಿ',
    'common.events': 'ಘಟನೆಗಳು',
    'common.event': 'ಕಾರ್ಯಕ್ರಮ',
    'common.all': 'ಎಲ್ಲಾ',
    'common.social': 'ಸಾಮಾಜಿಕ',
    'common.discordCommunity': 'ಡಿಸ್ಕಾರ್ಡ್ ಸಮುದಾಯ',
    'common.account': 'ಖಾತೆ',
    'common.notifications': 'Notifications',
    'common.byDeclaration': 'ಮೂಲಕ:',
    'common.done': 'ಮುಗಿಯಿತು',
    recommended: 'ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
    'select.typeToCreate': 'ಐಟಂ ರಚಿಸಲು ಟೈಪ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ',
    'select.noSearchResults': '“{search}” ಗೆ ಯಾವುದೇ ಫಲಿತಾಂಶಗಳಿಲ್ಲ',
    'select.removeOption': 'ತೆಗೆದುಹಾಕು {option}',
    create: 'ರಚಿಸಿ',
    'banner.support': 'Literary Universe is made possible thanks to the support of users like you. To help us remain independent and improve the platform, please consider subscribing to one of our plans.',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'common.haveAccountQuestion': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    'common.socialLogin': 'ಇತರ ಸೇವೆಗಳ ಜೊತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    'common.viewMore': 'ಹೆಚ್ಚಿನದನ್ನು ವೀಕ್ಷಿಸಿ',
    'common.overview': 'ಅವಲೋಕನ',
    'common.loggingOut': 'ಲಾಗ್ ಔಟ್ ಆಗುತ್ತಿದೆ',
    'common.thankYou': 'ಧನ್ಯವಾದಗಳು!',
    'common.seeYouAgain': 'ಮತ್ತೆ ನೋಡುವ ಸಂದರ್ಭದಲ್ಲಿ ನಮಸ್ಕಾರ!',
    'email.hello': 'ನಮಸ್ಕಾರ {username},',
    'common.back': 'ಹಿಂತಿರುಗಿ',
    'console.stop': 'ನಿಲ್ಲಿ!',
    'console.explain': 'This is a browser feature intended for developers. If someone told you to copy-paste something here to enable a Literary Universe feature or "hack" someone\'s account, it is a scam and will give them access to your Literary Universe account.',
    'common.coping': 'ನಕಲಿಕೆ ಮಾಡುವುದು...',
    'common.actions': 'ಕ್ರಿಯೆಗಳು',
    'common.popular': 'ಜನಪ್ರಿಯ',
    'common.newest': 'ಹೊಸತು',
    'common.oldest': 'ಪುರಾತನ',
    'common.noSelection': 'No selection',
    'common.content': 'Content',
    'common.theWayOfTheAuthor': 'The Way of the Author',
    'common.password.hide': 'Hide Password',
    'common.password.show': 'Show Password',
    'common.forums': 'Forums',
    'common.restriction.goodConduct': 'Due to good conduct violation we have restricted your use of this feature.',
    'common.continue': 'Continue',
    'common.authorName': 'Author Name',
    'error.invalidFileType': 'Please select a valid image file (JPEG, PNG, GIF, WebP)',
    'error.fileTooLarge': 'Image must be less than {mbSize, number}MB',
    'error.fabricInitFailed': 'Failed to initialize the image editor',
    // File upload strings
    'upload.files': 'Uploaded Files',
    'upload.dropHere': 'Drop your files here...',
    'upload.dragOrClick': 'Drag and drop files here, or click to select files',
    'upload.maxSize': 'Maximum file size: {size}',
    'upload.error.failed': 'File upload failed. Please try again.',
    'upload.error.tooManyFiles': 'You can upload a maximum of {max} files.',
    'upload.error.removeFile': 'Failed to remove file. Please try again.',
    'actions.delete': 'Delete',
    'common.aiContent.indicator': 'AI-Generated Content',
    'common.aiContent.tooltip': 'This content was created with AI assistance',
    'common.aiContent.model': 'AI Model: {model}',
    'common.aiContent.custom': 'Custom AI model',
    'common.viewAll': 'View All',
    'notice.thankYou': 'Thank you for your support!',
    'common.dropImageHere': 'Drop an image here',
    'common.legal.publishingAgreement': 'Publishing Agreement',
    'upload.dragAndDrop': 'Drag and drop files here, or click to select files',
    'common.orgs': 'Organizations',
    'universe.cover.alt': 'Universe cover image for {story}.',
    'common.license': 'License'
};