/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: '文学宇宙',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe is an all-in-one creative and publishing platform for grand story universes.',
    'site.keywords': 'creative writing, scifi, sci-fi, fantasy, writing, publishing, story, stories, universe, web novel, webnovel',
    'site.logoAlt': '文学宇宙徽標',
    mobileMenu: '手機菜單',
    'common.signin': '登錄',
    'common.signup': '註冊',
    'common.signout': '登出',
    'common.dashboard': '儀表板',
    'common.discovery': '探索',
    'common.library': '音樂庫',
    'common.library.own': '我的音樂庫',
    'common.workshop': '工作坊',
    'common.pm': '訊息',
    'common.settings': '設定',
    'common.options': '選項',
    'common.profile': '個人檔案',
    'common.blog': '部落格',
    'common.blogs': '部落格',
    'common.about': '關於我們',
    'common.accessdenied': '已拒絕存取',
    'common.accessdenied.msg': '您沒有權限進入此處。如果您應該有權限進入此處，請聯繫所有者並告訴他們重新檢查設定。',
    'common.loading': '載入中...',
    'common.add': '新增',
    'common.save': '儲存',
    'common.email': '電子郵件',
    'common.soon': '即將推出...',
    'common.search': '搜尋',
    'common.search.do': '搜尋',
    'common.searching': '搜尋中...',
    'common.report': '報告',
    'common.user': '使用者',
    'common.users': '使用者',
    'common.showmore': '顯示更多',
    'common.futurefeature.title': '未來功能',
    'common.futurefeature.text': '非常抱歉，此功能目前無法使用。我們正在努力使其尽快可用。',
    'common.nothingfound': '找不到任何結果',
    'common.explore': '探索',
    'common.by': '由 {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': '草稿紙',
    'common.scratchpad.own': '您的草稿紙',
    'common.news': '新聞',
    'common.encyclopedia': '百科全書',
    'common.art': 'Art',
    'common.story': '故事',
    'common.stories': '故事',
    'common.universe': '宇宙',
    'common.universes': '宇宙',
    'common.collaborator': '合作者',
    'common.collaborators': '合作者',
    'common.translator': '翻譯者',
    'common.translators': '翻譯者',
    'common.betareader': 'Beta 閱讀者',
    'common.betareaders': 'Beta 閱讀者',
    'common.post': '發布',
    'common.statistics': '統計資料',
    'common.lang.select': '選擇語言',
    'common.submit': '提交',
    'common.close': '關閉',
    'common.comment': '評論',
    'common.comments': '評論',
    404: '找不到頁面',
    'search.users': '搜索使用者',
    'search.user': '搜索使用者',
    'common.help': '幫助',
    'common.or': '或者',
    'common.account.create': '創建帳號',
    'signup.username': '使用者名稱',
    'signup.email': '您的電子郵件',
    'signup.password.label': '您的密碼',
    'signup.password.repeat': '重複輸入您的密碼',
    'common.password': '密碼',
    'signin.password.forgot': '忘記密碼？',
    'dashboard.whatsnew': '最新消息',
    'dashboard.blog': '您的部落格',
    'common.footer.tagline': '輕鬆寫作和閱讀複雜的宇宙。',
    'common.footer.plans': '計劃和價格',
    'common.legal.tos': '服務條款',
    'common.legal.community': '社群指南',
    'common.legal.privacy': '隱私政策',
    'common.legal.copyright': '版權協議',
    'common.legal.versionDisplay': `{type, select,
    tos {Terms of Service}
    community {Community Guidelines}
    privacy {Privacy Policy}
    copyright {Copyright Agreement}
    publishingAgreement {Publishing Agreement}
    other {Agreement}
  } Version {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'A new version ({newVersion}) of this document will come into effect on {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} 版權所有，所有文字均屬於其各自的作者所有。',
    'premium.only.title': '會員等級不夠高',
    'premium.only.msg': '很抱歉，您的會員等級不夠高，無法使用此功能。',
    'premium.only.join': '我們提供各種方案，讓每個人都能充分利用《文學宇宙》。',
    'premium.only.link': '來看看吧！',
    'universe.visit': '訪問宇宙頁面',
    'common.fanmanager': 'Fan manager',
    'common.fanarts': 'Fan arts',
    'common.fanfiction': 'Fan fiction',
    'common.fansettings': 'Fan settings',
    'story.chapter': '章節',
    'story.chapters': '章節',
    'story.genre': '類型',
    'story.genres': '類型',
    'story.read': '閱讀',
    'story.lastUpdate': '最後更新於 {date, date, medium} {date, time, short}。',
    'story.finishedAt': '於 {date, date, medium}完結。',
    'story.comments.for': '對於 {story} {chapter}的評論。',
    'story.cover.alt': '{story}的故事封面圖片。',
    'story.note.fanfiction': '注意：本故事是關於 {universe} 宇宙的粉絲創作。',
    copyrights: '版權',
    'common.challenges': '挑戰',
    // for beta only
    'beta.notice': '歡迎來到《文學宇宙》BETA版。這是一個公開預覽版本，因此應用程序仍在開發中。這意味著您仍可能遇到錯誤和未完成的功能。如果遇到錯誤或有功能無法正常工作，請告訴我們，並請耐心等待我們完成所有工作。',
    'beta.thanks': '感謝您的支持！',
    'scratchpad.about': '您的筆記和想法可以在網站的任何地方訪問。',
    'common.feedback': '反饋',
    'common.createdOn': 'Created on {date, date, long}',
    'common.createdOn.title': 'Created on',
    // account types
    admin: '管理員',
    'common.saved': '已保存！',
    'common.saving': '正在保存...',
    'common.friends': '好友',
    'lang.orig': '原始語言',
    'lang.orig.plus': '原始語言 - {language}',
    buy: '購買',
    confirm: '確認',
    cancel: '取消',
    processing: '處理中...',
    'common.noData': 'No data',
    'error.title': '發生錯誤。我們為不便之處向您致以歉意。',
    'common.offlineStatus': '您目前已離線。',
    male: '男',
    female: '女',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: '請選擇',
    'common.statusFailed': '無法連接到伺服器。',
    'common.statusConnecting': '正在嘗試連接到伺服器... ({count, number})',
    'slug.checking': '檢查中...',
    'slug.failed': '此地址已存在。',
    'slug.success': '此地址可用！',
    'notVerified.msg': `Your account {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    } is not verified.`,
    'notVerified.verify': `Please verify your {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    }.`,
    unknown: '未知',
    'common.legal.guidelines': '社群指南',
    'errorLoading.title': '頁面加載時發生錯誤',
    'errorLoading.explained': '頁面加載時發生錯誤。對於給您帶來的不便，我們深感抱歉。請重新訪問頁面。如果問題仍然存在，請告訴我們。',
    'errorLoading.retry': '重試！',
    'errorLoading.takingLong': '這需要很長時間...',
    'common.title': '標題',
    'common.timelines': '時間軸',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': '一般資料保護規範',
    'editor.placeholder.link': '輸入網址...',
    'editor.placeholder.connection': '搜索百科全書條目...',
    'editor.saved.beta': '為Beta讀者創建新版本！',
    'editor.saved.public': '新版本已發佈！',
    goodbyeForever: '我們很遺憾看到您離開。是我們做錯了什麼嗎？如果是這樣，請告訴我們。無論如何，祝您未來一切順利，希望我們能再次相遇！長壽和繁榮！',
    'goodbyeForever.feedback': '請告訴我們我們可以做得更好的地方',
    'common.edit': '編輯',
    'common.publish': '發佈',
    'common.publishAt': '發佈日期和時間',
    'a11y.user.menu': '使用者選單',
    'a11y.navigation': 'Navigation',
    'dashboard.profile': '您的個人資料',
    'profile.website': '我的個人網站',
    'story.notes.concept': '概念',
    'story.notes.settings': '故事設定',
    'story.notes.theme': '主題',
    'story.notes.impact': '期望的影響',
    'story.notes.outcome': '結果',
    'story.notes.audience': '目標觀眾',
    'story.notes.pitch': '推銷',
    'story.notes.notes': '備註',
    'story.authorsNotes': 'Author\'s notes',
    'common.members': '成員',
    'common.language': '語言',
    next: '下一步',
    previous: 'Previous',
    'common.legal.tos.short': '條款',
    'common.legal.privacy.short': '隱私',
    'premium.increaseLimit': '考慮升級以增加你的限制。',
    'common.sharing': '分享',
    'story.isbn': 'ISBN',
    'common.name': '名稱',
    'common.remove': '移除',
    'common.time.milliseconds': '毫秒',
    'common.time.seconds': '秒',
    'common.time.minutes': '分鐘',
    'common.time.hours': '小時',
    'common.time.days': '天',
    'common.time.weeks': '週',
    'common.time.months': '月',
    'common.time.years': '年',
    'common.monetization': 'Monetization',
    'common.tab.monetizationOptions': 'Monetization options',
    'common.pagination': 'Pagination',
    'common.forum': 'Forum',
    'common.2faCode': '2FA code',
    'common.2faCodeIntro': 'Please enter your one time code generated by your authenticator application.',
    'common.2faCodeAria': '2FA code entry form',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Default language',
    'signin.web3.signMessage': 'Please confirm that you want to enter Literary Universe with your wallet as authentication method. Code: {code}',
    'common.web3.confirmationCode': 'Confirmation code: {code}',
    'common.roadmap': 'Roadmap',
    'common.luStatsIFrameOptOut': 'Literary Universe statistics opt-out',
    'common.image': 'Image',
    'common.home': 'Home',
    'common.administration': 'Administration',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'Groups',
    'common.upload': 'Upload',
    'common.backToDashboard': 'Back to dashboard',
    'common.accept': 'Accept',
    'common.reject': 'Reject',
    'common.events': 'Events',
    'common.event': 'Event',
    'common.all': 'All',
    'common.social': 'Social',
    'common.discordCommunity': 'Discord Community',
    'common.account': 'Account',
    'common.notifications': 'Notifications',
    'common.byDeclaration': 'By:',
    'common.done': 'Done',
    recommended: 'Recommended',
    'select.typeToCreate': 'Start typing to create an item',
    'select.noSearchResults': 'No results for “{search}”',
    'select.removeOption': 'Remove {option}',
    create: 'Create',
    'banner.support': 'Literary Universe is supported by users like you! Please consider subscribing to one of our subscription plans to stay independent and make Literary Universe event better!',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Don\'t have an account?',
    'common.haveAccountQuestion': 'Already have an account?',
    'common.socialLogin': 'Login with other services',
    'common.viewMore': 'View more',
    'common.overview': 'Overview',
    'common.loggingOut': 'Logging out',
    'common.thankYou': 'Thank you!',
    'common.seeYouAgain': 'See you again!',
    'email.hello': 'Hello {username},',
    'common.back': 'Back',
    'console.stop': '停止！',
    'console.explain': '這是一個專為開發人員設計的瀏覽器功能。如果有人告訴你在這裡複製粘貼某些內容以啟用文學宇宙功能或"駭入"某人的帳戶，這是一個詐騙行為，將使他們能夠訪問你的文學宇宙帳戶。'
}    /* eslint-enable max-len */;