export default {
  'courses.courses': '課程',
  'courses.overview': '課程概覽',
  'courses.public.title': '探索課程',
  'courses.public.heading': '探索課程',
  'courses.public.filters': '篩選課程',
  'courses.public.noResults': '未找到課程',
  'courses.public.tryDifferentFilters': '嘗試不同的搜尋詞彙或篩選條件',
  'courses.filter.search': '搜尋課程...',
  'courses.filter.allTypes': '所有類型',
  'courses.filter.clearAll': '全部清除',
  'courses.filter.type': '類型',
  'courses.type.course': '課程',
  'courses.type.workshop': '工作坊',
  'courses.type.seminar': '研討會',
  'courses.type.course.lowercase': '課程',
  'courses.type.workshop.lowercase': '工作坊',
  'courses.type.seminar.lowercase': '研討會',
  'course.create': '創建新課程',
  'course.reading.title': '閱讀作業標題',
  'course.question.add': '新增問題',
  'course.lessons.newMessage': '建立並組織您的課程，以達到有效的教學',
  'course.reading.new': '閱讀作業',
  'course.reading.newMessage': '為學生建立和組織閱讀作業',
  'course.writing.new': '寫作任務',
  'course.writing.newMessage': '快速設定和分配寫作任務',
  'course.question.text': '您的問題在這裡',
  'course.question.type': '請選擇問題類型',
  'course.question.delete': '移除問題',
  'course.type': '課程類型',
  'course.visibility': '選擇可見性選項',
  'course.title': '標題',
  'course.description': '描述',
  'course.cover': '封面',
  'course.start': '您的課程開始於',
  'course.ends': '您的課程結束於',
  'course.curriculum': '課程',
  'course.members': '學生與教師',
  'course.assignments': '作業',
  'course.question.deleteWhole': '刪除整個問題',
  'course.question.yes': '是',
  'course.question.no': '否',
  'course.lesson.title': '課堂標題',
  'course.lesson.add.universe': '新增故事/宇宙',
  'course.lesson.externalLinks': '外部連結',
  'course.lesson.add.link': '新增外部連結',
  'course.status': '狀態',
  'course.active': '活動',
  'course.active.message': '活躍',
  'course.inactive': '閒置',
  'course.upload.resource': '上傳資源',
  'course.question.answer': '新增答案',
  'course.question.open': '開放式問題',
  'course.question.close': '封閉式問題',
  'course.question.multiple': '多項選擇題',
  'course.about': '關於本課程',
  'course.lesson.new': '建立新課程',
  'course.lesson.type': '課程類型',
  'course.lesson.inPerson': '親臨',
  'course.lesson.preRecorded': '預錄',
  'course.lesson.online': '線上',
  'course.lesson.text': '僅文字',
  'course.lesson.content': '課程內容',
  'course.lesson.description': '公開說明',
  'course.add.story': '新增故事',
  'course.remove.story': '移除故事',
  'course.dateOfPublish': '出版日期',
  'course.lesson.meetInPerson': '親自會面',
  'course.curriculum.edit': '編輯課程',
  'course.stories.own': '您自己的故事',
  'course.stories.organization': '組織故事',
  'course.stories.public': '公眾故事',
  'course.publish.at': '我希望本課程發佈在',
  'course.edit.curriculum': '編輯課程',
  'course.assignment': '任務',
  'course.lesson.removeLink': '移除連結',
  'course.user.remove': '移除使用者',
  'course.user.invite': '邀請使用者',
  'course.user.invited': '受邀',
  'course.edit.role': '編輯角色',
  'course.assignment.description': '任務說明',
  'course.internal': '內部',
  'course.free': '免費',
  'course.sale': '銷售',
  'course.announcements': '公告',
  'course.announcements.full': '課程公告',
  'course.announcements.create': '建立公告',
  'course.join': '加入課程',
  'course.joining': '加入...',
  'course.join.success': '您已成功加入本課程！',
  'course.join.error.payment': '參加此課程需要付款。',
  'course.join.error.invite': '此課程需要邀請函才能加入。',
  'course.join.error.generic': '加入課程時發生錯誤。請再試一次。',
  'course.firstLesson': '第一課',
  'course.upcomingLessons': '即將推出的課程',
  'course.detail.title': '{courseName} | 課程',
  'lessons.visibility.public': '公眾',
  'lessons.visibility.private': '私人',
  'course.curriculum.empty': '目前尚未提供課程項目。',
  'course.preview.message': '這是課程的預覽。加入課程以存取所有內容。',
  'course.details': '課程詳情',
  'course.tab.curriculum': '課程',
  'course.tab.details': '課程詳情',
  'course.duration': '時間長度',
  'course.perpetual': '永續',
  'course.language': '語言',
  'course.price': '價格',
  'course.learningObjectives': '學習目標',
  'course.prerequisites': '先決條件',
  'course.tags': '標籤',
  'course.stats.members': '會員',
  'course.stats.lessons': '課程',
  'course.assignments.comingSoon': '作業檢視即將推出。',
  'course.progress.comingSoon': '進度追蹤即將推出。',
  'course.type.free': '免費',
  'course.type.paid': '已付',
  'course.type.forSale': '待售',
  'course.type.invite': '僅限邀請',
  'courses.invites.tile': '邀請您參加 {count, plural, one {課程} other {課程}}。',
  'courses.invites.noInvites': '您目前沒有任何課程邀請。',
  'courses.invites.invitedBy': '受邀者： ',
  'courses.invites.accept': '接受',
  'courses.invites.reject': '拒絕',
  'course.join.heading': '加入此課程',
  'course.oneTimePayment': '一次性付款即可取得完整使用權',
  'course.member': '您已經註冊',
  'course.member.access': '您可以完全存取所有課程資料。',
  'courses.members.editRole': '編輯角色',
  'courses.members.editRoleFor': '編輯角色為：',
  'courses.add.member': '新增會員',
  'course.member.options': '課程成員名單',
  'course.navigation.curriculum': '課程',
  'course.navigation.members': '學生與教師',
  'course.navigation.assignments': '作業',
  'course.navigation.forums': '論壇',
  'course.navigation.attendance': '出席率',
  'course.members.teachers': '教師',
  'course.members.students': '學生',
  'course.members.preview.message': '加入此課程，可以看到所有學生，並與社群互動。',
  'course.member.role.owner': '業主',
  'course.member.role.teacher': '教師',
  'course.member.role.student': '學生',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'course.startDate': '開始日期',
  'course.endDate': '結束日期',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': '課程預覽',
  'course.curriculum.preview.message': '加入此課程可存取所有 {count} 課程和作業。',
  'course.curriculum.locked': '鎖定',
  'course.curriculum.lesson': '課程',
  'course.curriculum.assignment': '任務',
  'course.curriculum.reading': '閱讀',
  'course.lesson.backToCurriculum': '回到課程',
  'course.lesson.nextLesson': '下一課',
  'course.lesson.documents': '文件與資源',
  'course.lesson.meetingLink': '會議連結',
  'course.lesson.location': '地點',
  'course.lesson.virtualClassroom': '虛擬教室',
  'course.lesson.joinClassroom': '加入虛擬教室會議',
  'course.lesson.enterClassroom': '進入教室',
  'course.assignment.acceptsStories': '接受故事',
  'course.assignment.acceptsUniverses': '接受宇宙',
  'course.assignment.backToAssignments': '返回任務',
  'course.assignment.criteria': '閱讀標準',
  'course.assignment.dueDate': '到期： {date}',
  'course.assignment.freeReading': '可免費閱讀',
  'course.assignment.grade': '等級',
  'course.assignment.grade.received': '年級: {grade}',
  'course.assignment.gradeSaveError': '無法儲存等級',
  'course.assignment.gradeSaved': '級別保存。',
  'course.assignment.gradedCount': '{count, plural, one {# graded} other {# graded}}',
  'course.assignment.grading.help': '檢閱學生提交的內容、開啟連結的故事或宇宙，並加入可選的評分和回饋。',
  'course.assignment.grading.title': '分級： {title}',
  'course.assignment.grading.unavailable': '無法評分',
  'course.assignment.grading.unavailableMessage': '您無權存取此評分網頁，或無法找到該作業。',
  'course.assignment.lastRead': '最後一次閱讀 {date}',
  'course.assignment.minutes': '{count} min',
  'course.assignment.noSubmissions': '尚未提交。',
  'course.assignment.noWrittenResponse': '未提供書面回應。',
  'course.assignment.notFound': '未找到任務',
  'course.assignment.notFoundMessage': '無法找到所要求的任務。',
  'course.assignment.noteForTeacher': '添加給老師的備注',
  'course.assignment.open': '開放式任務',
  'course.assignment.openGrading': '開啟分級頁面',
  'course.assignment.questions': '問題',
  'course.assignment.readingProgress': '學生閱讀進度',
  'course.assignment.readings': '指定閱讀',
  'course.assignment.responsePlaceholder': '在此寫下您的回應',
  'course.assignment.responsePrompt': '論文題目或日誌提示',
  'course.assignment.selectStoriesRead': '選擇您為本作業選取的故事。',
  'course.assignment.sharedProject.studentHelp':
    '在 Workshop 中開啟上述其中一個共用專案作品，並在那裡貢獻。本作業不需要單獨的提交表格。',
  'course.assignment.sharedProject.studentTitle': '如何完成此作業',
  'course.assignment.sharedProject.teacherNotice': '這項共用專案作業使用合作者存取權，而非個人提交。',
  'course.assignment.sharedProjects': '共用專案工程',
  'course.assignment.storiesCompleted': '已完成的故事',
  'course.assignment.submissionCount': '{count, plural, one {# 提交} other {# 提交}}',
  'course.assignment.submissionSaved': '提交已保存。',
  'course.assignment.submissions': '提交和評級',
  'course.assignment.submit': '提交作業',
  'course.assignment.submitError': '無法提交作業',
  'course.assignment.submitWork': '選擇要提交的作品',
  'course.assignment.submitWork.help': '選擇本作業應評分的故事或宇宙。',
  'course.assignment.submitWork.label': '提交作品',
  'course.assignment.submitWork.placeholder': '選擇故事或宇宙',
  'course.assignment.submittedAt': '提交於 {date}',
  'course.assignment.submittedWork.story': '提交的故事： {title}',
  'course.assignment.submittedWork.universe': '提交宇宙： {title}',
  'course.assignment.supportingFiles': '上傳的輔助資料',
  'course.assignment.supportingMaterials': '輔助資料',
  'course.assignment.updateSubmission': '更新提交',
  'course.assignment.yourSubmission': '您的提交',
  'courses.role.owner': '業主',
  'courses.role.teacher': '教師',
  'courses.role.student': '學生',
};
