export default {
  'fanManager.settings.for': '粉絲經理設置',
  'fanManager.allowArtSubmissions': '允許粉絲藝術提交',
  'fanManager.displayFanArt': '允許展示粉絲藝術',
  'fanManager.allowFanStories': '允許粉絲小說',
  'fanManager.displayFanStories': '允許展示粉絲故事',
  'fanManager.state.aria': '選擇提交的作品狀態',
  'fanManager.state.submitted': '已提交',
  'fanManager.state.approved': '已批准',
  'fanManager.state.rejected': '已拒絕',
  'fanManager.state.hidden': '已隱藏',
  'fanManager.publicComment': '公開評論',
  'fanManager.publicComment.desc': '此文本將作為您對此藝術品的官方評論在公共頁面上顯示。',
  'fanManager.authorComment': '給作者的評論',
  'fanManager.authorComment.desc': '這是您對此藝術品的作者的私人評論。',
  'fanManager.stateChange.approve': '批准粉絲藝術',
  'fanManager.stateChange.reject': '拒絕粉絲藝術',
  'fanManager.stateChange.hide': '隱藏粉絲藝術',
  'fanManager.stateChange.unhide': '使粉絲藝術可見',
  'fanManager.fanFictionNotAllowed': '根據您的許可證性質，不允許粉絲小說。',
  'fanManager.fanFiction.maxRating': '顯示的粉絲小說的最高評級。'
};