/**
 * Licenses for creative works
 * https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
 */
export default {
    'licenses.about': '關於許可證',
    'licenses.more': '更多資訊',
    'licenses.legal': '法律文件',
    'licenses.name.cc-by': '創用 CC 姓名標示 4.0',
    'licenses.cc-by': '這個授權讓他人可以分發、混合、調整和建立你的作品，甚至用於商業用途，只要他們為原始創作給予你應有的擔保。這是最寬鬆的授權之一，推薦用於最大程度地傳播和使用授權材料。',
    'licenses.name.cc-by-sa': '創用 CC 姓名標示-相同方式分享 4.0',
    'licenses.cc-by-sa': '此許可證允許他人在您的作品基礎上進行混音、調整和創作，即使是為了商業目的，只要他們在相同的條款下將您的名字和新創作的許可證註明在您的名下即可。此許可證通常與「copyleft」自由軟體和開放原始碼軟體的許可證相提並論。所有以您的作品為基礎的新作品都將使用相同的許可證，因此任何衍生作品也允許商業使用。這是 Wikipedia 使用的許可證，建議使用於包含 Wikipedia 及類似許可專案內容的資料。',
    'licenses.name.cc-by-nd': '創用 CC 姓名標示-禁止改作 4.0',
    'licenses.cc-by-nd': '這個授權允許在完整無誤的情況下重新分發、商業和非商業使用，並且需要將擔保歸功於你。',
    'licenses.name.cc-by-nc': '創用 CC 姓名標示-非商業性 4.0',
    'licenses.cc-by-nc': '此許可證允許他人在您的作品上進行非商業性的混音、調整和建構，雖然他們的新作品也必須承認您且為非商業性，但他們不必以相同的條款授權其衍生作品。',
    'licenses.name.cc-by-nc-sa': '創用 CC 姓名標示-非商業性-相同方式分享 4.0',
    'licenses.cc-by-nc-sa': '這個授權讓他人在非商業情況下對你的作品進行混合、調整和建立，只要他們為原作者給予應有的擔保並按照相同的條款許可他們的新創作。',
    'licenses.name.cc-by-nc-nd': '創用 CC 姓名標示-非商業性-禁止改作 4.0',
    'licenses.cc-by-nc-nd': '此許可證是我們六種主要許可證中限制性最強的一種，只允許他人下載您的作品並與他人分享，只要他們標明您的名字即可，但他們不能以任何方式變更作品或作商業用途。',
    'licenses.name.lu-c': '文學宇宙版權',
    'licenses.lu-c': '標準完全版權許可證，允許您按照自己的意願出售和發布作品，並保護您的權利。該許可證還提供了將您的故事在《文學宇宙》上出售的選擇。',
    'licenses.name.lu-e': '文學宇宙獨家',
    'licenses.lu-e': '本授權書授予Literary Universe在線上出版和發行您的作品的獨家權利。您將保有版權，但Literary Universe將擁有在線出版和發行您作品的獨家權利。',
    'licenses.name.lu-ne': '文學宇宙非獨家',
    'licenses.lu-ne': '本授權書授予Literary Universe在線上出版和發行您的作品的非專屬權利。您將保有著作權以及透過其他管道出版與發行您作品的權利。',
    'licenses.name.cc0': '無版權保留 - CC0 1.0',
    'licenses.cc0': '將您的作品置於公共領域。CC的授權條款允許著作權人在保留其著作權的同時，選擇一系列的權限，相較之下，CC0完全賦予了另一種選擇權--選擇不接受著作權和資料庫保護，以及自動賦予創作者的專屬權利--也就是我們授權條款中的「不保留權利」（no rights reserved）。',
    // License Chooser Modal
    'licenses.chooser.title': '授權選擇器',
    'licenses.chooser.button': '幫我選擇許可證',
    'licenses.chooser.ariaLabel': '為您的作品選擇授權',
    'licenses.chooser.introduction': '本工具將幫助您選擇最適合您作品的許可證。許可證決定了他人如何使用您的作品，並影響您在 Literary Universe 上獲利的能力。',
    // License Chooser Wizard Steps
    'licenses.chooser.step.contentType.title': '您要授權哪種類型的內容？',
    'licenses.chooser.step.contentType.description': '內容類型會影響您可使用的授權。',
    'licenses.chooser.step.contentType.original': '原創作品',
    'licenses.chooser.step.contentType.fanfiction': '影迷小說',
    'licenses.chooser.step.contentType.fanfictionNote': 'Literary Universe 上的同人小說作品會自動使用創用 CC 署名-非商業性授權 (CC BY-NC)。這是因為同人小說是基於他人擁有版權的作品，商業使用可能會侵犯這些權利。',
    'licenses.chooser.step.commercial.title': '您想讓您的作品獲利嗎？',
    'licenses.chooser.step.commercial.description': '選擇將您的作品貨幣化，會影響哪一種授權最為適當。',
    'licenses.chooser.step.commercial.yes': '是的，我想讓我的工作賺錢',
    'licenses.chooser.step.commercial.no': '不，我不想將我的作品金錢化',
    'licenses.chooser.step.commercial.monetizeNote': '若要在 Literary Universe 上銷售您的作品，您需要使用我們的商業授權。這些許可證允許您在維護著作權的同時出售您的作品。',
    'licenses.chooser.step.exclusivity.title': '您想在 Literary Universe 獨家出版嗎？',
    'licenses.chooser.step.exclusivity.description': '選擇獨家會影響平台費用和出版選項。',
    'licenses.chooser.step.exclusivity.yes': '是的，專屬於 Literary Universe',
    'licenses.chooser.step.exclusivity.no': '不，我也想在其他地方出版',
    'licenses.chooser.step.exclusivity.exclusiveNote': '在 Literary Universe 獨家出版，您將從 10% 的較低平台費用中獲益。這意味著您可以保留 90% 的收入。',
    'licenses.chooser.step.exclusivity.nonExclusiveNote': '使用非獨家出版，您也可以在其他平台上發表作品。平台費是30%，也就是說您保留70%在Literary Universe的收益。將來，我們會提供工具幫助您直接從 Literary Universe 發行作品到其他平台。',
    'licenses.chooser.step.derivatives.title': '您要允許他人創作衍生作品嗎？',
    'licenses.chooser.step.derivatives.description': '衍生作品包括改編、混音或轉換您的原始作品。',
    'licenses.chooser.step.derivatives.yes': '是，允許衍生作品',
    'licenses.chooser.step.derivatives.no': '不允許衍生作品',
    'licenses.chooser.step.derivatives.allowNote': '允許衍生作品意味著其他人可以改編、重製或轉換您的作品。這會使您的內容得到更廣泛的傳播和創造性的再利用。',
    'licenses.chooser.step.derivatives.disallowNote': '不允許衍生作品意味著您的作品必須原封不動地完整傳承，但仍可在適當歸屬的情況下分享。',
    'licenses.chooser.step.attribution.title': '您想要求署名嗎？',
    'licenses.chooser.step.attribution.description': '署名是指他人在使用您的作品時必須給予肯定。',
    'licenses.chooser.step.attribution.yes': '是，要求歸屬',
    'licenses.chooser.step.attribution.no': '否，置於公共領域 (CC0)',
    'licenses.chooser.step.attribution.requireNote': '要求署名意味著任何使用您作品的人都必須按照您要求的方式給您署名。',
    'licenses.chooser.step.attribution.publicDomainNote': '將您的作品置於公共領域 (CC0) 表示您放棄所有版權及相關權利。他人可以為任何目的自由使用您的作品，無需註明。',
    // License Result
    'licenses.chooser.result.commercialTitle': '商業資訊',
    'licenses.chooser.result.exclusiveInfo': '使用 Literary Universe 獨家授權，您將從 10% 的較低平台費用中獲益。這表示您可以保留 90% 的收入，但您只能在 Literary Universe 上發表此作品。',
    'licenses.chooser.result.nonExclusiveInfo': '有了 Literary Universe 非獨家授權，您也可以在其他平台發表您的作品。平台費用為30%，也就是說您可以保留70%在Literary Universe的收益。將來，我們會提供工具幫助您直接從 Literary Universe 發行作品到其他平台。',
    'licenses.chooser.result.fanfictionNote': '由於同人小說作品是基於他人擁有版權的資料，因此本授權將自動適用於同人小說作品。商業使用可能會侵犯這些權利。',
    'licenses.chooser.result.selectLicense': '選擇此授權',
    // Adding missing internationalization strings
    'licenseChooser.contentType.title': '您要授權哪種類型的內容？',
    'licenseChooser.contentType.description': '內容類型會影響您可使用的授權。',
    'licenseChooser.contentType.original.title': '原創作品',
    'licenseChooser.contentType.original.description': '完全由您自己創作的內容。',
    'licenseChooser.contentType.fanfiction.title': '影迷小說',
    'licenseChooser.contentType.fanfiction.description': '基於其他創作者現有作品的內容。',
    'licenseChooser.contentType.fanfiction.note': 'Literary Universe 上的同人小說作品會自動使用創用 CC 署名-非商業性授權 (CC BY-NC)。這是因為同人小說是基於他人擁有版權的作品，商業使用可能會侵犯這些權利。',
    'licenseChooser.commercial.title': '您想讓您的作品獲利嗎？',
    'licenseChooser.commercial.description': '選擇將您的作品貨幣化，會影響哪一種授權最為適當。',
    'licenseChooser.commercial.yes': 'Yes, I want to monetize my work',
    'licenseChooser.commercial.yes.title': '是的，我想盈利',
    'licenseChooser.commercial.yes.description': '我想從 Literary Universe 上的工作賺錢。',
    'licenseChooser.commercial.no': 'No, I don\'t want to monetize my work',
    'licenseChooser.commercial.no.title': '不，我不想盈利',
    'licenseChooser.commercial.no.description': '我想要自由分享我的作品，而不需要付費。',
    'licenseChooser.commercial.note': '若要在 Literary Universe 上銷售您的作品，您需要使用我們的商業授權。這些許可證允許您在維護著作權的同時出售您的作品。',
    'licenseChooser.exclusivity.title': '您想在 Literary Universe 獨家出版嗎？',
    'licenseChooser.exclusivity.description': '選擇獨家會影響平台費用和出版選項。',
    'licenseChooser.exclusivity.yes': 'Yes, I want to publish exclusively on Literary Universe',
    'licenseChooser.exclusivity.yes.title': '是的，專屬於 Literary Universe',
    'licenseChooser.exclusivity.yes.description': '我只在 Literary Universe 上發表這部作品。',
    'licenseChooser.exclusivity.no': 'No, I want to publish elsewhere as well',
    'licenseChooser.exclusivity.no.title': '不，我也想在其他地方出版',
    'licenseChooser.exclusivity.no.description': '我也想在其他平台上發表這部作品。',
    'licenseChooser.exclusivity.exclusive.note': '在 Literary Universe 獨家出版，您將從 10% 的較低平台費用中獲益。這意味著您可以保留 90% 的收入。',
    'licenseChooser.exclusivity.nonExclusive.note': '使用非獨家出版，您也可以在其他平台上發表作品。平台費用為 30%，也就是說您可以保留 Literary Universe 上 70% 的收益。',
    'licenseChooser.derivatives.title': '您要允許他人創作衍生作品嗎？',
    'licenseChooser.derivatives.description': '衍生作品包括改編、混音或轉換您的原始作品。',
    'licenseChooser.derivatives.yes': 'Yes, allow modifications',
    'licenseChooser.derivatives.yes.title': '是，允許衍生作品',
    'licenseChooser.derivatives.yes.description': '其他人可以改編、混音或轉換我的作品。',
    'licenseChooser.derivatives.no': 'No, don\'t allow modifications (ND)',
    'licenseChooser.derivatives.no.title': '不允許衍生作品',
    'licenseChooser.derivatives.no.description': '我的作品必須原封不動地完整傳承下去。',
    'licenseChooser.attribution.title': '您想要求署名嗎？',
    'licenseChooser.attribution.description': '署名是指他人在使用您的作品時必須給予肯定。',
    'licenseChooser.attribution.yes': 'Yes, require attribution (BY)',
    'licenseChooser.attribution.yes.title': '是，要求歸屬',
    'licenseChooser.attribution.yes.description': '其他人使用我的作品時，必須給予我肯定。',
    'licenseChooser.attribution.no': 'No, allow use without attribution (CC0)',
    'licenseChooser.attribution.no.title': '否，置於公共領域 (CC0)',
    'licenseChooser.attribution.no.description': '我放棄我作品的所有版權及相關權利。',
    'licenseChooser.commercialUse.title': '您希望允許他人將您的作品用於商業用途嗎？',
    'licenseChooser.commercialUse.description': '商業用途是指他人可以將您的作品用於商業目的。',
    'licenseChooser.commercialUse.yes.title': '是，允許商業用途',
    'licenseChooser.commercialUse.yes.description': '其他人可以將我的作品用於商業目的。',
    'licenseChooser.commercialUse.no': 'No, non-commercial use only (NC)',
    'licenseChooser.commercialUse.no.title': '否，僅限非商業用途',
    'licenseChooser.commercialUse.no.description': '其他人只能將我的作品用於非商業目的。',
    'licenseChooser.shareAlike.title': '您是否需要 Share-Alike？',
    'licenseChooser.shareAlike.description': '選擇其他人是否必須在相同條款下分享其改編作品。',
    'licenseChooser.shareAlike.yes.title': '需要類似共享 (SA)',
    'licenseChooser.shareAlike.yes.description': '如果他人在您的作品上進行混音、轉換或建構，他們必須根據與原始作品相同的許可證散佈他們的貢獻。',
    'licenseChooser.shareAlike.no.title': '不需要類似分享',
    'licenseChooser.shareAlike.no.description': '其他人可以根據任何條款散佈改編作品，即使這些條款比您的原始許可證限制更多。',
    'licenseChooser.shareAlike.yes': '是，需要「類似共用」(SA)',
    'licenseChooser.shareAlike.no': '不，不需要 Share-Alike',
    'licenseChooser.cc0Confirmation.title': '確認 CC0 授權 (公共領域)',
    'licenseChooser.cc0Confirmation.description': 'CC0放棄您作品的所有版權及相關權利，有效地將作品置於公共領域。請確認您的理解。',
    'licenseChooser.cc0Confirmation.important': '重要資訊',
    'licenseChooser.cc0Confirmation.details': '選擇CC0，即表示您在法律允許的範圍內，放棄您作品的所有著作權及相關權利。這表示',
    'licenseChooser.cc0Confirmation.point1': '任何人都可以為任何目的使用您的作品，包括商業用途',
    'licenseChooser.cc0Confirmation.point2': '不需要署名（雖然非常感激）',
    'licenseChooser.cc0Confirmation.point3': '其他人可以修改您的作品，但不能分享這些修改',
    'licenseChooser.cc0Confirmation.point4': '一旦您發佈，此決定將不可撤銷。',
    'licenseChooser.cc0Confirmation.waiver': '我瞭解我已放棄作品的所有版權及相關權利',
    'licenseChooser.cc0Confirmation.understanding': '我了解CC0對我作品的條款與法律效力',
    'licenses.learnMore': '瞭解更多',
    'licenses.legalText': '法律文本',
    'licenses.chooser.back': '返回',
    'licenses.chooser.select': '選擇此授權',
    'licenses.commercial.title': '商業執照資訊'
};