export default {
    'reader.storyEnd.heading': 'The END',
    'reader.storyEnd.description': 'You have reached the end of the story.',
    'reader.externalSale.heading': 'Not here yet',
    'reader.externalSale.description': 'This story is not available on Literary Universe, but you can get it in other places.',
    'reader.storyTBC.heading': 'To be continued...',
    'reader.storyTBC.description': 'This is all we have for the story so far, but the adventure will continue in the future, check back soon!',
    'chapter.translation.notYetDescription': 'Check back again soon!',
    'reader.externalShopping.heading': '在商店里购买 {storyName} ：',
    'chapter.next': 'Next chapter',
    'chapter.previous': 'Previous chapter',
    'chapter.comment': 'Comments on this chapter',
    'reader.language': 'Language:',
    'reader.fullscreen.enter': 'Enter fullscreen',
    'reader.fullscreen.exit': 'Exit fullscreen',
    'reader.details.universe': 'Universe details',
    'reader.details.story': 'Story details',
    'reader.darkmode': 'Toggle dark mode',
    'reader.flowtext': 'Toggle text size',
    'reader.menu.optionsAria': 'Reader options menu',
    'reader.accessibility': 'Toggle accessibility',
    'chapter.translation.notYet': 'This chapter has not yet been translated.',
    'externalShopping.buyLink.amazon': 'Buy on Amazon',
    'externalShopping.buyLink.other': '在 {storeName}上购买',
    'externalShopping.buyLink.bookshop': 'Buy on Bookshop.org',
    'reader.accessibility.aria': 'Accessibility options',
    'reader.accessibility.toggleDyslexic': 'Toggle dyslexic font',
    'reader.accessibility.toggleParagraphStripes': 'Toggle paragraphs background alteration',
    'reader.accessibility.toggleParagraphHighlight': 'Toggle selected paragraph highlighting',
    'reader.accessibility.toggleRules': 'Toggle assistive ruler',
    'reader.nextRelease.scheduled': '下一章将在 {nextReleaseAt, date} 当中发布于 {nextReleaseAt, time}!',
    'reader.storyContinues': '故事持續中...',
    'reader.storyOnHiatus': '作者目前正在休息此故事，故此故事暫停。請再過一個月或兩個月來查看。',
    'reader.storyCancelled': '很遺憾，這是結束了。這個故事已被取消，因此不太可能會有新的內容。',
    'reader.storyCancelled.heading': '已取消',
    'reader.nextChapterEstimation.verySoon': '基於最近 {chaptersCount, number} 章節的發布日期，下一章預計很快就會發布。',
    'reader.nextChapterEstimation.days': '基於最近 {chaptersCount, number} 章節的發布日期，下一章預計在大約 {daysLeft, plural, one {1天} other {天}}後可用。',
    'reader.nextChapterEstimation.notEnoughChapters': '一旦這個故事有超過一章時，我們也會提供下一章可能發布的一個估計。'
};