export default {
  // ── Editor ──────────────────────────────────────────────────────────────────
  'resume.editor.title': '作者簡歷',
  'resume.editor.preview': '以發行者身份預覽',
  'resume.editor.introduction': '簡介',
  'resume.editor.showcase': '產品展示',
  'resume.editor.contact': '聯絡人',
  'resume.editor.aboutWork': '關於我的作品',
  'resume.editor.awards': '獎項',
  'resume.editor.theme': '主題',
  'resume.editor.access': '存取',
  // General / Introduction
  'resume.editor.general.heading': '一般',
  'resume.editor.general.enabled': '啟用履歷頁面',
  'resume.editor.general.enabled.help':
    '啟用時，Literary Universe 上的出版商組織可以檢視您的簡歷。無論此設定是否啟用，您的預覽始終是可用的。',
  'resume.editor.introduction.heading': '簡介',
  'resume.editor.introduction.description': '為出版商撰寫簡短的自我介紹。這將會出現在您履歷頁面的上方。',
  // Showcase
  'resume.showcase.heading': '產品展示',
  'resume.showcase.description':
    '拖曳來重新排列您的宇宙和故事。勾選項目以包含在您的履歷中。組織擁有的作品、CC0 授權作品和小說粉絲不包括在內。',
  'resume.showcase.empty': '您還沒有任何符合條件的故事或宇宙。請先在 Workshop 中建立一些。',
  'resume.showcase.noStories': '在這個宇宙中，沒有符合條件的故事。',
  'resume.showcase.standalone': '獨立故事',
  'resume.showcase.hasPreview': '出版商預覽',
  'resume.showcase.private': '私人',
  'resume.showcase.ccLicense': 'CC 授權',
  'resume.showcase.ccWarning':
    '有些展示的故事使用 Creative Commons 授權。出版商應注意這些作品有特定的授權條款，可能會限制商業使用。',
  'resume.showcase.uploadPreview': '上傳出版商預覽',
  // Contact
  'resume.editor.contact.heading': '聯絡資訊',
  'resume.editor.contact.name': '顯示名稱',
  'resume.editor.contact.email': '電子郵件',
  'resume.editor.contact.phone': '電話',
  'resume.editor.contact.website': '網站',
  // Address
  'resume.editor.address.heading': '郵寄地址',
  'resume.editor.address.encryptionNotice': '您的地址經過加密，只有瀏覽您履歷的出版商才能看到。',
  'resume.editor.address.street': '街道地址',
  'resume.editor.address.city': '城市',
  'resume.editor.address.state': '州/省',
  'resume.editor.address.zip': '郵遞區號',
  'resume.editor.address.country': '國家',
  // About My Work
  'resume.editor.aboutWork.heading': '關於我的作品',
  'resume.editor.aboutWork.description':
    '就您的創作、過程或願景撰寫藝術家自述。此部分將與您的展示作品一起展示給出版商。若要省略此部分，請留空。',
  'resume.editor.aboutWork.label': '藝術家聲明',
  'resume.editor.aboutWork.placeholder': '分享您的創作理念、驅使您說故事的動力、您探索的主題...',
  // Awards
  'resume.editor.awards.heading': '獎項與榮譽',
  'resume.editor.awards.description': '為您的故事或宇宙添加獎項和榮譽。',
  'resume.editor.awards.title': '獎項名稱',
  'resume.editor.awards.organization': '組織架構',
  'resume.editor.awards.year': '年份',
  'resume.editor.awards.desc': '說明',
  'resume.editor.awards.add': '新增獎項',
  // Theme
  'resume.editor.theme.heading': '履歷主題',
  'resume.editor.theme.description': '為您的公開履歷頁面選擇視覺主題。',
  'resume.editor.theme.customize': '自訂',
  'resume.editor.theme.accentColor': '重點顏色覆寫',
  'resume.editor.theme.fontPreference': '字型偏好',
  // Publisher Preview Settings
  'resume.preview.settings': '出版商預覽 {title}',
  'resume.preview.mode': '預覽模式',
  'resume.preview.fromChapter': '從章節',
  'resume.preview.toChapter': '至章節',
  'resume.preview.chapterAccessInfo': '出版商將可直接在 Literary Universe 上閱讀 {from} 至 {to} 的章節。',
  'resume.preview.generateEpub': '產生 EPUB 預覽',
  'resume.preview.epubReady': '在 {date} 產生 EPUB 預覽',
  'resume.preview.remove': '移除預覽',
  'resume.preview.save': '儲存預覽設定',
  'resume.preview.banner': '這是出版商如何看到您的簡歷的預覽。無論您的存取設定為何，您都可以隨時使用。',
  'resume.preview.backToEditor': '返回編輯',
  'resume.preview.noResume': '您尚未建立履歷表。前往編輯器開始。',
  'resume.preview.goToEditor': '前往編輯',
  // ── Access Settings ─────────────────────────────────────────────────────────
  'resume.access.title': '恢復存取設定',
  'resume.access.publisher': '文學宇宙上的出版商存取',
  'resume.access.publisher.description':
    '啟用後，Literary Universe 上出版商類型組織的成員可以直接在您的作者簡介上檢視您的履歷。',
  'resume.access.publisher.toggle': '啟用出版商組織的履歷',
  'resume.access.publisher.toggleHelp': '無論是否有此設定，您都可以隨時預覽您的履歷。',
  'resume.access.links': '可分享連結',
  'resume.access.links.description':
    '建立獨特的連結，與出版商和其他人分享您的履歷。每個連結都會追蹤訪問次數，並可在洩漏時停用。',
  'resume.access.createLink': '建立新連結',
  'resume.access.createLink.title': '建立存取連結',
  'resume.access.createLink.comment': '評論（選擇性）',
  'resume.access.createLink.language': '頁面語言',
  'resume.access.noLinks': '尚未建立存取連結。建立連結來分享您的履歷。',
  'resume.access.copy': '複製',
  'resume.access.copied': '已複製！',
  'resume.access.disable': '停用',
  'resume.access.enable': '啟用',
  'resume.access.disabled': '殘障',
  'resume.access.visits': '{count, plural, one {# 訪問} other {# 訪問}}',
  'resume.access.created': '建立 {date}',
  'resume.access.viewVisits': '查看訪問詳情',
  'resume.access.noVisits': '尚未記錄任何訪問。',
  'resume.access.onsite': '現場',
  'resume.access.visitNumber': '(請造訪 #{number})',
  // ── Public Resume Page ──────────────────────────────────────────────────────
  'resume.public.works': '作品精選',
  'resume.public.standaloneWorks': '其他作品',
  'resume.public.storiesInSeries': '{count, plural, one {# 故事} other {# 故事}} 系列中',
  'resume.public.availableIn': '可用於',
  'resume.public.downloadPreview': '下載預覽',
  'resume.public.readPreview': '閱讀預覽 (Ch. {from}-{to})',
  'resume.public.chapters': '{published} 各章{total, select, 0 {} other { 之 {total} 計劃}}',
  'resume.public.publishedDate': '已出版 {date}',
  'resume.public.contentWarnings': '內容警告：',
  'resume.public.status.completed': '已完成',
  'resume.public.status.ongoing': '持續進行',
  'resume.public.status.hiatus': '暫停',
  'resume.public.status.cancelled': '已取消',
  'resume.public.aboutWork': '關於我的作品',
  'resume.public.awards': '獎項與榮譽',
  'resume.public.viewOnLU': '檢視文學宇宙 →',
  'resume.public.accessDenied': '拒絕存取',
  'resume.public.accessDenied.description': '您需要成為出版商組織的會員才能檢視此簡歷。',
  // Contact section
  'resume.public.contact': '聯絡人',
  'resume.public.contact.email': '電子郵件',
  'resume.public.contact.phone': '電話',
  'resume.public.contact.website': '網站',
  'resume.public.contact.address': '地址',
  'resume.public.readFreeStory': '閱讀完整故事',
  'resume.public.viewResume': '檢視 {user}的履歷',
  // Sharing / QR
  'resume.sharing.businessCard': '名片',
  'resume.sharing.fullPage': '全頁',
  'resume.sharing.selectLanguage': '語言 / 連結',
  'resume.sharing.selectLanguages': '選擇要包含的語言連結 (max {max})：',
  'resume.sharing.selectAtLeastOne': '至少選擇一種語言來產生 QR 代碼。',
  'resume.sharing.authorTitle': '作者',
  'resume.sharing.cardSize': '卡片尺寸',
  'resume.sharing.pageFormat': '頁面格式',
  'resume.sharing.download': '下載 PNG',
  // Theme names
  'resume.theme.light': '燈光',
  'resume.theme.dark': '黑暗',
  'resume.theme.sciFi': '科幻',
  'resume.theme.fantasy': '夢幻',
  'resume.theme.pragueUrban': '布拉格城市',
  'resume.theme.steampunk': '蒸汽朋克',
  'resume.theme.horror': '恐怖',
  'resume.theme.militarySciFi': '軍事科幻',
  'resume.theme.artDeco': '裝飾藝術',
};
