export default {
    'writer.menu.optionsAria': '編輯器選項選單',
    'writer.menu.saveOptionsAria': '儲存選項',
    'writer.undo': '復原',
    'writer.redo': '重做',
    'writer.ul': '無序清單',
    'writer.ol': '有序清單',
    'writer.blockquote': '引用',
    'writer.link': '插入連結',
    'writer.image': '插入圖片',
    'writer.bold': '將選取文字加粗',
    'writer.underline': '將選取文字加底線',
    'writer.italic': '強調選取文字',
    'writer.wordcount': '{characters, number} 字元， {words, number} 單字',
    'finder.details': '詳細資料',
    'finder.remove': '移除連結',
    'finder.connect': '將選取項目連結至百科全書條目',
    'writer.aside.ariaLabel': '幫助選項選單',
    'writer.nothingToSave': '沒有要保存的內容',
    'writer.publish.publishAria': '發布選項',
    'writer.publish.scheduleExplained': '您可以立即發布或安排章節在以後的日期可用。',
    'writer.publish.schedule': '設定發布日期和時間',
    'writer.publish.previousChapterPublished': '上一章節發布於 {publishDate, date, short} ，時間為 {publishDate, time}',
    'writer.publish.previousChapterScheduled': '上一章節預定於 {publishDate, date, short} ，時間為 {publishDate, time}發布',
    'writer.publish.alreadyPublished': '此章節已於 {publishedAt, date, short}發布。新版本將立即發布。',
    'writer.publish.betaReader': 'Beta',
    'writer.publish.public': '發佈'
};