export default {
    'org.auditLog.title': '監査ログ',
    'org.settings.title': 'Organization settings',
    'org.settings.name': '組織名',
    'org.settings.membersPrivate': 'メンバを公開しない',
    'org.logo': 'Organization logo',
    'org.superAdmin': 'スーパーアドミン',
    'org.settings.language': 'Primary language',
    'org.meta.desc': 'Organizations and creative groups on Literary Universe.',
    'org.luOrgs': '文学の宇宙組織',
    'org.otherOrgs': 'ギルドと組織',
    'org.aboutTitle': '{orgName}について',
    'org.membersTitle': 'Organization members',
    'org.membersNone': 'Members are not public',
    'org.storiesTitle': 'Stories from {orgName}',
    'org.universesTitle': 'Universes from {orgName}',
    'org.userDashboardTitle': 'あなたの組織',
    'org.settings.hideMembers.label': 'Hide members from the public',
    'org.visit': 'Go to {organization} page',
    'org.authorOverride.legend': 'Author override',
    'org.authorOverride.desc': 'Shows this text instead of the name of the organization.',
    'org.authorOverride.label': 'Author\'s name',
    'org.membersAdd.title': 'Invite members to the organization'
};