export default {
  'courses.courses': 'Courses',
  'courses.overview': 'نظرة عامة على الدورات',
  'course.create': 'إنشاء دورة جديدة',
  'course.reading.title': 'Reading assignment title',
  'course.question.add': 'Add question',
  'course.add.module': 'Add module',
  'course.lessons.newMessage': 'Create and organize your lessons for effective teaching',
  'course.reading.new': 'Reading Assignment',
  'course.reading.newMessage': 'Create and organize reading assignments for your students',
  'course.writing.new': 'مهمة الكتابة',
  'course.writing.newMessage': 'Quickly set up and distribute writing tasks',
  'course.question.text': 'سؤالك يذهب هنا',
  'course.question.type': 'Please select a type of question',
  'course.question.delete': 'Remove question',
  'course.type': 'اختر نوع الدورة',
  'course.visibility': 'اختر خيار الرؤية',
  'course.title': 'العنوان',
  'course.description': 'الوصف',
  'course.cover': 'الغلاف',
  'course.start': 'تبدأ الدورة الخاصة بك في',
  'course.ends': 'تنتهي الدورة الخاصة بك في',
  'course.curriculum': 'المنهج الدراسي',
  'course.members': 'الطلاب والمعلمون',
  'course.assingments': 'المهام',
};
