export default {
    'feedback.home': 'مركز المساعدة',
    'feedback.bugs': 'المشاكل',
    'feedback.bugs.desc': 'هل واجهت خطأ أو شيء آخر خاطئ أو في غير محله؟ أخبرنا هنا!',
    'feedback.features': 'الأفكار والمقترحات',
    'feedback.features.desc': 'هل لديك أفكار لميزات جديدة أو كيفية تحسين الموقع؟ اسمح لنا أن نعرف!',
    'feedback.help': 'المساعدة والبرامج التعليمية',
    'feedback.help.desc': 'كيف يمكن أن _____؟ انتقل هنا للعثور على الإجابات.',
    'feedback.desc': 'مرحبًا بك في مركز المساعدة والحلول الخاص بنا!',
    'feedback.faq': 'الأسئلة الشائعة',
    'feedback.faq.desc': 'الأسئلة المتكررة',
    'feedback.open': 'مفتوح',
    'feedback.closed': 'مغلق',
    'feedback.accepted': 'تم قبوله',
    'feedback.inprogress': 'قيد التنفيذ',
    'feedback.completed': 'مكتمل',
    'feedback.fixed': 'تم إصلاحه',
    'feedback.new.bugs': 'الإبلاغ عن مشكلة جديدة',
    'feedback.new.features': 'اقتراح ميزة جديدة',
    'feedback.lang.nosupport': 'لغتك الحالية غير مدعومة للملاحظات، يُرجى الكتابة باللغة الإنجليزية. شكرًا لك!',
    'feedback.new.thanks': 'شكراً على الملاحظة! سننظر في الأمر قريباً.',
    'feedback.comment.title': 'تعليق',
    'feedback.comment.desc': 'أرسل لنا ملاحظاتك',
    'feedback.comment.legend': 'ملاحظاتك - اسمح لنا أن نعرف عن أي شيء',
    'feedback.comment.success': 'شكرًا على ملاحظاتك!',
    'feedback.comment.label': 'تعليقك',
    'feedback.copyrightReport.title': 'انتهاك حقوق الطبع والنشر',
    'feedback.copyrightReport.desc': 'الإبلاغ عن انتهاك حقوق الطبع والنشر',
    'feedback.report.noUser': 'يجب أن تكون مسجلاً الدخول لتتمكن من تقديم تقرير.',
    'feedback.voting.totalVoters': 'تصويت المستخدمين: {voted, number}',
    'feedback.voting.upvote': 'التصويت لأعلى',
    'feedback.voting.downvote': 'التصويت لأسفل',
    'feedback.voting.score': 'المجموع الكلي',
    'feedback.report.title': 'الإبلاغ عن المحتوى',
    'feedback.report.typeSelect': 'ما هي المشكلة هنا؟',
    'feedback.reportType.law': 'مخالفة القانون',
    'feedback.reportType.vulgar': 'فاحشة/بذيئة',
    'feedback.reportType.copyright': 'انتهاك حقوق الطبع والنشر',
    'feedback.reportType.storyRating': 'التصنيف العمري غير صحيح',
    'feedback.reportType.scam': 'احتيال',
    'feedback.report.submit': 'إبلاغ',
    'feedback.report.submitting': 'إبلاغ...',
    'feedback.report.violationDesc': 'التفاصيل',
    'feedback.report.reportSaved': 'شكرًا لك على التقرير! سنقوم بالتحقيق واتخاذ الإجراءات اللازمة إذا لزم الأمر.',
    'feedback.report.copyrightReportSaved': 'شكرًا لك على التقرير! سنقوم بالتحقيق وسنتواصل معك.',
    'feedback.report.copyrightOwnershipDesc': 'بيان الملكية',
    'feedback.report.copyrightNotice': 'يرجى ملاحظة أنه يجب أن تكون المالك الشرعي للعمل لاستخدام هذا النموذج. إذا لم تكن أنت المالك، يرجى إبلاغ المالك أو استخدام الفئة الأخرى لإبلاغنا. نحن نأخذ انتهاكات حقوق الطبع والنشر على محمل الجد، وينطبق الأمر نفسه على الاستخدام غير السليم والمسيء لهذا النموذج.',
    'feedback.report.copyrightInternalProperty': 'لقد نشرت هذا العمل على Literary Universe',
    'feedback.reportType.spam': 'بريد مزعج أو احتيال',
    'feedback.reportType.soliciting': 'الالتماس',
    'feedback.reportType.aiUnmarked': 'محتوى غير مميز من إنشاء الذكاء الاصطناعي',
    'feedback.reportType.other': 'أخرى',
    'feedback.report.copyrightType.propertySelectLabel': `ما هو {type, select,
    universe {الكون}
    story {القصة}
    other {القصة}
  } الكون ~ ~ القصة ~ ~ القصة ~ ~ يتم التعدي عليها؟`,
    'feedback.help.overview': 'لمحة عامة',
    'feedback.help.articles': 'المقالات',
    'feedback.help.courses': 'الدورات التدريبية',
    'feedback.help.videos': 'فيديوهات تعليمية',
    'feedback.help.featuredArticles': 'مقالات مميزة',
    'feedback.help.featuredCourses': 'الدورات التدريبية المميزة',
    'feedback.help.featuredVideos': 'فيديوهات مميزة',
    'feedback.help.subCategories': 'الفئات الفرعية',
    'feedback.resolution.title': 'Resolution center',
    'feedback.resolution.desc': 'Manage and resolve reported violations',
    'feedback.reportType.aiGenerated': 'AI-generated content',
    'feedback.resolution.aiGeneration': 'AI Generation Status',
    'feedback.resolution.aiGenerated': 'AI Generated',
    'feedback.resolution.notAiGenerated': 'Not AI Generated',
    'feedback.center.noReports': 'كل شيء آمن! لم يتم الإبلاغ عن أي انتهاكات.',
    // Added for Resolution Center lists
    'feedback.reportType.unknown': 'غير معروف',
    'feedback.report.status.reported': 'تم الإبلاغ',
    'feedback.report.status.investigating': 'التحقيق',
    'feedback.report.status.accepted': 'مقبولة',
    'feedback.report.status.disputed': 'متنازع عليه',
    'feedback.report.status.fixed': 'ثابت',
    'feedback.report.status.invalid': 'غير صالح',
    'feedback.report.status.rejected': 'مرفوض',
    'feedback.report.dateDetails': 'تم الإنشاء: {createdAt, date} | محدثة: {updatedAt, date}',
    'feedback.report.quickResolution': 'حل سريع',
    'feedback.report.actions.none': 'لا يوجد إجراء سريع متاح',
    'feedback.report.actions.storySettings': 'الانتقال إلى إعدادات القصة',
    'feedback.report.actions.universeSettings': 'الانتقال إلى إعدادات الكون',
    'feedback.report.description': 'الوصف المقدم',
    'feedback.report.copyrightReport': 'لقد تلقينا مطالبة بحقوق الطبع والنشر لهذا العمل. سنقوم بمراجعة المطالبة واتخاذ قرار بشأنها. إذا كنت ترغب في تقديم أي تعليق أو سياق إضافي، يرجى القيام بذلك أدناه.',
    // Slider component strings
    'feedback.help.selectFeaturedArticles': 'اختر المقالات المميزة',
    'feedback.help.featuredArticlesDescription': 'سيتم عرض هذه المقالات في شريط تمرير على صفحة الفئة. يجب أن تحتوي المقالات على صورة غلاف للحصول على أفضل مظهر.',
    'feedback.help.addFeatured': 'إضافة إلى المميزات',
    'feedback.help.removeFeatured': 'إزالة من المميز',
    'feedback.help.noFeaturedArticles': 'لم يتم اختيار أي مقالات مميزة.',
    'feedback.help.noArticles': 'لا توجد مقالات في هذه الفئة.'
};