export default {
  'forums.create': 'تمكين المنتدى',
  'forums.archive': 'أرشفة المنتدى',
  'forums.archive.explained': 'سيؤدي أرشفة المنتدى إلى منع المستخدمين من نشر أي محتوى إضافي، ولكنه سيظل مرئيًا.',
  'forums.archive.success': 'تم أرشفة المنتدى',
  'forums.unArchive': 'إعادة تنشيط المنتديات',
  'forums.unArchive.success': 'تم إعادة تنشيط المنتدى!',
  'forums.settings': 'إعدادات المنتدى',
  'forums.category.create': 'إنشاء فئة المنتدى',
  'forums.category.delete': 'حذف التصنيف',
  'forums.category.name': 'اسم التصنيف',
  'forums.category.slug': 'جزء عنوان URL لتحسين محركات البحث',
  'forums.category.settings': 'إعدادات الفئة',
  'forums.category.language': 'قم بتحديد عرض هذه الفئة للغة التالية. اتركها فارغة إذا كنت ترغب في عرض الفئة بجميع اللغات.',
  'forums.category.intlNameDescription': 'لدينا عناوين محلية لأسماء الفئات الشائعة للاختيار منها، حتى يمكن أن تكون الفئة متاحة لجميع اللغات المدعومة.',
  'forums.thread.new': 'موضوع جديد',
  'forums.thread.delete': 'حذف الموضوع',
  'forums.post.new': 'منشور جديد',
  'forums.archived.forum': 'تم أرشفة هذا المنتدى في {archivedAt, date, long}. لا يمكنك إنشاء محتوى جديد، ولكن يمكنك مشاهدة المنتديات.',
  'forums.category.archive': 'أرشفة الفئة',
  'forums.category.archiveExplained': 'سيتم حذف الفئة التي ليس بها مواضيع، بينما ستمنع الفئات التي بها محتوى إنشاء مواضيع جديدة.',
  'forums.category.reactivate': 'إعادة تنشيط الفئة',
  'forums.category.isVotable': 'السماح للمستخدمين بالتصويت على المواضيع',
  'forums.category.titleIsGlobal': 'سيتم عرض عنوان هذه الفئة بلغة المستخدم إذا كنا ندعمها.',
  'forums.category.languageLimited': 'سيتم عرض هذه الفئة فقط للمستخدمين في هذه اللغة.',
  'forums.threadsCounter': 'إجمالي عدد المواضيع والمناقشات',
  // Pre-defined category names
  'forums.category.intlName.general': 'عام',
  'forums.category.intlName.announcements': 'الإعلانات',
  'forums.category.intlName.stories': 'قصص',
  'forums.category.intlName.universes': 'الأكوان',
  'forums.category.intlName.universe': 'الكون',
  'forums.category.intlName.community': 'المجتمع',
  'forums.category.intlName.meetups': 'التجمعات',
  'forums.category.intlName.characters': 'الشخصيات',
  'forums.category.intlName.locations': 'المواقع',
  'forums.category.intlName.history': 'السجل',
  'forums.category.intlName.art': 'الفن',
  'forums.category.intlName.inspiration': 'الإلهام',
  'forums.category.intlName.news': 'الأخبار',
  'forums.category.intlName.help': 'مساعدة',
  'forums.category.intlName.questions': 'الأسئلة',
  'forums.category.back': 'العودة إلى نظرة عامة على المنتدى',
  // Forum restrictions
  'forums.forumRestriction.usersOnly': 'السماح فقط بالوصول للمستخدمين المسجلين',
  'forums.settings.accessControls': 'ضوابط الوصول',
  'forums.forumRestrictionsMessages.usersOnlyForum': 'هذا المنتدى متاح فقط للمستخدمين المسجلين.',
  'forums.noThreads': 'لا يوجد شيء للعرض هنا. من الأمر بيدك أن تبدأ المحادثة.',
  'forums.noPosts': 'لم يرد أحد بعد. كن الأول!',
  // Threads
  'forums.createThread': 'إنشاء مناقشة جديدة',
  'forums.createThreadIn': 'إنشاء موضوع جديد في {categoryName}',
  'forums.openingPost': 'المشاركة الافتتاحية',
  'forums.createQuestionLabel': 'هل هذا سؤال؟',
  'forums.thread.noReplies': 'لا توجد ردود حاليًا هنا.',
  'forums.reply': 'الرد',
  'forums.post': 'نشر',
  'forums.posting': 'جارٍ النشر...',
  'forums.reset': 'إعادة تعيين',
  'forum.thread.reply': 'أضف ردًا على هذا الموضوع',
  'forums.yourMessage': 'رسالتك',
  'forums.thread.replyPosted': 'تم نشر رسالتك',
  'forums.thread.totalPosts': `{totalReplies, number} {totalReplies, plural,
    one {رد}
    other {ردود}
  }`,
  'forums.thread.createdAt': 'تم الإنشاء في {createdAt, date, medium}'
};