export default {
    'org.auditLog.title': 'Audit log',
    'org.settings.title': 'Organization settings',
    'org.settings.name': 'Organization name',
    'org.settings.membersPrivate': 'Do NOT display members publicly',
    'org.logo': 'Organization logo',
    'org.logo.alt': '{organizationName} logo',
    'org.superAdmin': 'Super Admin',
    'org.settings.language': 'اللغة الأساسية',
    'org.meta.desc': 'Organizations and creative groups on Literary Universe.',
    'org.luOrgs': 'Literary Universe Organizations',
    'org.otherOrgs': 'Guilds & Organizations',
    'org.aboutTitle': 'About {orgName}',
    'org.membersTitle': 'Organization members',
    'org.membersNone': 'Members are not public',
    'org.storiesTitle': 'قصص من {orgName}',
    'org.universesTitle': 'Universes from {orgName}',
    'org.userDashboardTitle': 'Your organizations',
    'org.settings.hideMembers.label': 'Hide members from the public',
    'org.visit': 'Go to {organization} page',
    'org.authorOverride.legend': 'Author override',
    'org.authorOverride.desc': 'Shows this text instead of the name of the organization.',
    'org.authorOverride.label': 'اسم المؤلف',
    'org.membersAdd.title': 'Invite members to the organization',
    'org.flashnews.admin': 'Flashnews administration',
    'org.settings.tabListAria': 'Setting sections for organization',
    'org.forums.title': 'منتديات {orgName}',
    'org.flashnews.internal': 'Internal news flashes',
    'org.flashnews.publicAll': 'Public news flashes for all properties',
    'org.flashnews.createTitle': `Create a new news flash for {type, select,
    internal {the organization}
    allProperties {display to public on all properties}
    other {the organization}
  }`,
    'org.members.invited': 'Invited members',
    'org.members.list': 'Organization members',
    'org.invitesTileNotice': 'You have been invited to {count, number} {count, plural, one {organization} other {organizations}}',
    'org.invitePage.title': 'Invitations to organizations',
    'org.invitePage.invitedAt': 'You have been invited on {invitedAt, date, short}.',
    'org.invitePage.ignoring': 'You are currently ignoring this invitation, which means that it is still active, but doesn\'t bothers with notifications.',
    'org.invitePage.expiresAt': 'This invitation will expire at {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Join organization',
    'org.invitePage.reject': 'رفض الدعوة',
    'org.invitePage.ignore': 'Ignore for now',
    'org.leaveOrg.title': 'Leave organization',
    'org.leaveOrg.confirm': 'This is a destructive action. Once you leave you will loose all access to this organization. Are you sure you want to leave the organization?',
    'org.confirmRemove.aria': 'تأكيد حذف المستخدم',
    'org.confirmRemove.confirm': 'هل أنت متأكد أنك تريد إزالة {username} من {organization}؟',
    'org.confirmRemove.remove': 'إزالة المستخدم',
    'org.mainBlog': 'المدونة الرئيسية',
    'org.teams': 'Teams',
    'org.teams.total': 'Total teams: {totalTeams, number}',
    'org.teams.create': 'إنشاء فريق جديد',
    'org.teams.settings': 'إعدادات الفريق'
};