export default {
  'personalNotes.personalNotes': 'ملاحظات شخصية',
  'personalNotes.chooseType': 'اختر نوع الملاحظة الشخصية',
  'personalNotes.storyNotes': 'ملاحظات القصة',
  'personalNotes.chapterNotes': 'ملاحظات الفصل',
  'personalNotes.universeNotes': 'ملاحظات الكون',
  'personalNotes.encyclopediaNotes': 'ملاحظات الموسوعة',
  'personalNotes.storyPersonalNotesHeading': 'ملاحظات شخصية عن القصص',
  'personalNotes.encyclopediaPersonalNotesHeading': 'ملاحظات شخصية عن الموسوعة',
  'personalNotes.searchPersonalNotesHeading': 'البحث في الملاحظات الشخصية',
  'personalNotes.goToStory': 'الانتقال إلى القصة',
  'personalNotes.goToChapter': 'الانتقال إلى الفصل',
  'personalNotes.goToEncyclopedia': 'الانتقال إلى موسوعة الكون',
  'personalNotes.goToEncEntry': 'الانتقال إلى الإدخال',
  'personalNotes.closeDropdown': 'إغلاق القائمة المنسدلة',
  'personalNotes.chapterName': 'اسم الفصل {sequence} - {title}',
  'personalNotes.objectPersonalNotes': '{object} ملاحظة شخصية',
  'personalNotes.searchResults': 'نتائج البحث',
  'personalNotes.type.story': 'قصة',
  'personalNotes.type.universe': 'كون',
  'personalNotes.type.chapter': 'فصل',
  'personalNotes.type.encEntry': 'مدخل الموسوعة',
  'personalNotes.type.revTextBlock': 'مقطع نصي للمراجعة',
  'personalNotes.chapter': 'فصل',
  'personalNotes.recentSearches': 'البحث الأخيرة:'
};