export default {
    'reader.storyEnd.heading': 'النهاية',
    'reader.storyEnd.description': 'لقد وصلت إلى نهاية القصة.',
    'reader.externalSale.heading': 'ليس هنا بعد',
    'reader.externalSale.description': 'هذه القصة غير متوفرة على Literary Universe, ولكن يمكنك الحصول عليها في أماكن أخرى.',
    'reader.storyTBC.heading': 'سيتم الاستمرار...',
    'reader.storyTBC.description': 'هذا كل ما لدينا من القصة حتى الآن، ولكن المغامرة ستستمر في المستقبل، تفقد مرة أخرى قريباً!',
    'chapter.translation.notYetDescription': 'تأكد من العودة مرة أخرى قريباً!',
    'reader.externalShopping.heading': 'اشترِ {storyName} في المتاجر:',
    'chapter.next': 'الفصل التالي',
    'chapter.previous': 'الفصل السابق',
    'chapter.comment': 'التعليقات على هذا الفصل',
    'reader.language': 'اللغة:',
    'reader.fullscreen.enter': 'الدخول في وضع ملء الشاشة',
    'reader.fullscreen.exit': 'الخروج من وضع ملء الشاشة',
    'reader.details.universe': 'تفاصيل الكون',
    'reader.details.story': 'تفاصيل القصة',
    'reader.darkmode': 'تبديل وضع الظلام',
    'reader.flowtext': 'تبديل حجم النص',
    'reader.menu.optionsAria': 'قائمة خيارات القارئ',
    'reader.accessibility': 'تبديل إمكانية الوصول',
    'chapter.translation.notYet': 'لم يتم ترجمة هذا الفصل بعد.',
    'externalShopping.buyLink.amazon': 'شراء على أمازون',
    'externalShopping.buyLink.other': 'شراء على {storeName}',
    'externalShopping.buyLink.bookshop': 'شراء على Bookshop.org',
    'reader.accessibility.aria': 'خيارات الوصول',
    'reader.accessibility.toggleDyslexic': 'تبديل الخط المريضي (ديسلكسي)',
    'reader.accessibility.toggleParagraphStripes': 'تبديل تغيير خلفية الفقرة',
    'reader.accessibility.toggleParagraphHighlight': 'تبديل تمييز الفقرة المحددة',
    'reader.accessibility.toggleRules': 'تبديل المساعد الجيوب',
    'reader.nextRelease.scheduled': 'الفصل التالي سيأتي في {nextReleaseAt, date} في {nextReleaseAt, time}!',
    'reader.storyContinues': 'ستستمر القصة...',
    'reader.storyOnHiatus': 'المؤلف حاليًا في إجازة من هذه القصة وهذه القصة في وقفة مؤقتة الآن. تفقد مرة أخرى في شهر أو اثنين.',
    'reader.storyCancelled': 'للأسف هذا هو الأمر. تم إلغاء القصة لذا من غير المرجح أن يكون هناك أي شيء جديد.',
    'reader.storyCancelled.heading': 'ملغى',
    'reader.nextChapterEstimation.verySoon': 'Based on the last {chaptersCount} chapters publish date the next chapter should be out very soon.',
    'reader.nextChapterEstimation.days': 'Based on the last {chaptersCount} chapters publish date the next chapter should be out in {daysLeft} days',
    'reader.nextChapterEstimation.notEnoughChapters': 'We will also provide an estimate of when the next chapter might be published once this story has more than one chapter.'
};