export default {
    'sharing.title': 'مشاركة',
    'sharing.button': 'Sharing Button',
    'sharing.share': 'Share with...',
    'sharing.feedback': 'Are we missing some place you would like to share to? Let us know about it!',
    'sharing.copy': 'نسخ',
    'sharing.email': 'E-mail',
    'sharing.sms': 'SMS',
    'sharing.messenger': 'Facebook Messenger',
    'sharing.whatsapp': 'WhatsApp',
    'sharing.twitter': 'X/Twitter',
    'sharing.linkedin': 'LinkedIn',
    'sharing.telegram': 'Telegram',
    'sharing.facebook': 'Facebook',
    'sharing.line': 'LINE',
    'sharing.mastodonSocial': 'Mastodon Social',
    'sharing.mastodonJapan': 'Mastodon Japan',
    'sharing.gab': 'Gab',
    'sharing.pinterest': 'Pinterest',
    'sharing.gettr': 'Gettr',
    'sharing.minds': 'Minds.com',
    'sharing.instagram': 'Instagram'
};