export default {
    'feedback.home': '도움말 센터',
    'feedback.bugs': '문제점',
    'feedback.bugs.desc': '에러나 잘못된 내용을 발견했나요? 여기에서 알려주세요!',
    'feedback.features': '아이디어 및 제안',
    'feedback.features.desc': '새로운 기능에 대한 아이디어나 사이트를 개선하는 방법이 있나요? 알려주세요!',
    'feedback.help': '도움말 및 자습서',
    'feedback.help.desc': '어떻게 _____하나요? 답변을 찾으려면 여기로 이동하세요.',
    'feedback.desc': '도움말 및 문제 해결 센터에 오신 것을 환영합니다!',
    'feedback.open': '열림',
    'feedback.closed': '닫힘',
    'feedback.accepted': '수락됨',
    'feedback.inprogress': '진행 중',
    'feedback.completed': '완료됨',
    'feedback.fixed': '수정됨',
    'feedback.new.bugs': '새로운 문제 신고',
    'feedback.new.features': '새로운 기능 제안',
    'feedback.lang.nosupport': '현재 언어는 피드백을 지원하지 않습니다. 영어로 작성해주세요. 감사합니다!',
    'feedback.new.thanks': '알려주셔서 감사합니다! 빠른 시일 내에 확인하겠습니다.',
    'feedback.comment.title': '댓글',
    'feedback.comment.desc': '의견 보내기',
    'feedback.comment.legend': '의견 - 무엇이든 알려주세요',
    'feedback.comment.success': '의견 주셔서 감사합니다!',
    'feedback.comment.label': '댓글 작성',
    'feedback.copyrightReport.title': '저작권 위반',
    'feedback.copyrightReport.desc': '저작권 위반 신고',
    'feedback.report.noUser': '신고를 제출하려면 로그인해야 합니다.',
    'feedback.voting.totalVoters': '사용자 투표: {voted, number}',
    'feedback.voting.upvote': '추천',
    'feedback.voting.downvote': '비추천',
    'feedback.voting.score': '총 점수',
    'feedback.report.title': '내용 신고',
    'feedback.report.typeSelect': '여기에 어떤 문제가 있나요?',
    'feedback.reportType.law': '법 위반',
    'feedback.reportType.vulgar': '음란/외설적인',
    'feedback.reportType.copyright': '저작권 위반',
    'feedback.reportType.storyRating': '나이 등급이 잘못 표시됨',
    'feedback.reportType.scam': '사기',
    'feedback.report.submit': '보고서',
    'feedback.report.submitting': '보고 중...',
    'feedback.report.violationDesc': '세부 정보',
    'feedback.report.reportSaved': '신고해 주셔서 감사합니다! 필요한 조치를 취할 것입니다.',
    'feedback.report.copyrightReportSaved': '신고해 주셔서 감사합니다! 조사를 진행한 후 연락드리겠습니다.',
    'feedback.report.copyrightOwnershipDesc': '소유권 성명',
    'feedback.report.copyrightNotice': '이 양식을 사용하려면 해당 작품의 정당한 소유자여야 함을 유의해 주세요. 소유자가 아닌 경우 소유자에게 알리거나 다른 카테고리를 사용하여 알려주시기 바랍니다. 저희는 저작권 침해를 매우 심각하게 여기며 이 양식의 부적절하고 남용된 사용에도 동일한 대우를 적용합니다.',
    'feedback.report.copyrightInternalProperty': '나는 Literary Universe에서 이 작품을 게시했습니다',
    'feedback.reportType.spam': '스팸 또는 피싱',
    'feedback.reportType.other': '기타',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`
};