export default {
    'feedback.home': '도움말 센터',
    'feedback.bugs': '문제점',
    'feedback.bugs.desc': '에러나 잘못된 내용을 발견했나요? 여기에서 알려주세요!',
    'feedback.features': '아이디어 및 제안',
    'feedback.features.desc': '새로운 기능에 대한 아이디어나 사이트를 개선하는 방법이 있나요? 알려주세요!',
    'feedback.help': '도움말 및 자습서',
    'feedback.help.desc': '어떻게 _____하나요? 답변을 찾으려면 여기로 이동하세요.',
    'feedback.desc': '도움말 및 문제 해결 센터에 오신 것을 환영합니다!',
    'feedback.faq': '자주 묻는 질문',
    'feedback.faq.desc': '자주 묻는 질문',
    'feedback.open': '열림',
    'feedback.closed': '닫힘',
    'feedback.accepted': '수락됨',
    'feedback.inprogress': '진행 중',
    'feedback.completed': '완료됨',
    'feedback.fixed': '수정됨',
    'feedback.new.bugs': '새로운 문제 신고',
    'feedback.new.features': '새로운 기능 제안',
    'feedback.lang.nosupport': '현재 언어는 피드백을 지원하지 않습니다. 영어로 작성해주세요. 감사합니다!',
    'feedback.new.thanks': '알려주셔서 감사합니다! 빠른 시일 내에 확인하겠습니다.',
    'feedback.comment.title': '댓글',
    'feedback.comment.desc': '의견 보내기',
    'feedback.comment.legend': '의견 - 무엇이든 알려주세요',
    'feedback.comment.success': '의견 주셔서 감사합니다!',
    'feedback.comment.label': '댓글 작성',
    'feedback.copyrightReport.title': '저작권 위반',
    'feedback.copyrightReport.desc': '저작권 위반 신고',
    'feedback.report.noUser': '신고를 제출하려면 로그인해야 합니다.',
    'feedback.voting.totalVoters': '사용자 투표: {voted, number}',
    'feedback.voting.upvote': '추천',
    'feedback.voting.downvote': '비추천',
    'feedback.voting.score': '총 점수',
    'feedback.report.title': '내용 신고',
    'feedback.report.typeSelect': '여기에 어떤 문제가 있나요?',
    'feedback.reportType.law': '법 위반',
    'feedback.reportType.vulgar': '음란/외설적인',
    'feedback.reportType.copyright': '저작권 위반',
    'feedback.reportType.storyRating': '나이 등급이 잘못 표시됨',
    'feedback.reportType.scam': '사기',
    'feedback.report.submit': '보고서',
    'feedback.report.submitting': '보고 중...',
    'feedback.report.violationDesc': '세부 정보',
    'feedback.report.reportSaved': '신고해 주셔서 감사합니다! 필요한 조치를 취할 것입니다.',
    'feedback.report.copyrightReportSaved': '신고해 주셔서 감사합니다! 조사를 진행한 후 연락드리겠습니다.',
    'feedback.report.copyrightOwnershipDesc': '소유권 성명',
    'feedback.report.copyrightNotice': '이 양식을 사용하려면 해당 작품의 정당한 소유자여야 함을 유의해 주세요. 소유자가 아닌 경우 소유자에게 알리거나 다른 카테고리를 사용하여 알려주시기 바랍니다. 저희는 저작권 침해를 매우 심각하게 여기며 이 양식의 부적절하고 남용된 사용에도 동일한 대우를 적용합니다.',
    'feedback.report.copyrightInternalProperty': '나는 Literary Universe에서 이 작품을 게시했습니다',
    'feedback.reportType.spam': '스팸 또는 피싱',
    'feedback.reportType.other': '기타',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`,
    'faq.section.about': '회사 소개',
    'faq.section.settings': '설정',
    'faq.section.discovery': '탐색',
    'faq.section.reader': '독자',
    'faq.section.library': '도서관',
    'faq.section.workshop': '작업장',
    'faq.section.writer': '작가',
    'faq.section.encyclopedia': '백과사전',
    'faq.section.groups': '그룹',
    'faq.section.blogs': '블로그',
    'faq.section.guilds': '길드',
    // About us questions
    'faq.question.about.whatIsLU': 'Literary Universe란 무엇인가요?',
    'faq.answer.about.whatIsLU': 'Literary Universe is a platform for writers and readers to create, share and discover stories and worlds.',
    'faq.question.about.difference': 'What is the difference between Literary Universe and other online reading platforms?',
    'faq.answer.about.difference': 'Literary Universe is all-in-one platform which means it includes tools for writing, reading, worldbuilding, and community building. The key difference is inclusion of all these tools together in one platform and their interconnectedness.',
    'faq.question.about.dataLocation': 'LU 데이터는 어디에 저장되나요?',
    'faq.answer.about.dataLocation': 'Literary Universe 데이터는 미국에 있는 서버, 특히 AWS us-east-1 지역에 저장되어 있습니다.',
    'faq.question.about.incorporation': '어디에 법인이 등록되어 있나요?',
    'faq.answer.about.incorporation': '문학 우주는 체코 공화국에 소속되어 있습니다. 자세한 내용은 <a href="/about">about us page</a>에서 확인할 수 있습니다.',
    'faq.question.about.roadmap': '문학 우주의 다음 단계는 무엇인가요?',
    'faq.answer.about.roadmap': '이것은 끊임없이 진화하고 있습니다. 자세한 내용은 <a href="/roadmap">roadmap</a> 를 확인해주세요.',
    // Settings questions
    'faq.question.settings.changeTheme': '문학 우주의 모습을 어떻게 변경하나요?',
    'faq.answer.settings.changeTheme': '등록된 사용자는 "사이트 테마" 섹션에서 <a href="/user/settings/account">계정 설정</a> 에서 테마를 변경할 수 있습니다. 밝은 테마와 어두운 테마를 사용할 수 있습니다. 등록되지 않은 경우에는 브라우저 및 운영 체제 설정을 기반으로 어떤 테마를 제공할지 결정합니다.',
    'faq.question.settings.changeAvatar': '어떻게 아바타를 변경하나요?',
    'faq.answer.settings.changeAvatar': '아바타를 변경하려면 <a href="/user/settings/profile">프로필 설정</a>에서 변경할 수 있습니다.',
    'faq.question.settings.changeLanguage': '언어를 어떻게 변경하나요?',
    'faq.answer.settings.changeLanguage': '문학 우주의 언어를 변경하려면 <a href="/user/settings/account">계정 설정</a>에서 변경할 수 있습니다.',
    'faq.question.settings.translationMistake': '웹 사이트의 텍스트에 오류를 발견했습니다. 어디에 신고할 수 있나요?',
    'faq.answer.settings.translationMistake': 'All our language files are available on GitHub. You can <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">submit an issue there</a> or in the Bug section of the feedback, or if you are so inclined, you can fix it directly yourself via <a href="https://crowdin.com/project/literary-universe" target="_blank">our Crowdin page</a>.',
    // Discovery questions
    'faq.question.discovery.explain': 'What is the Discovery section?',
    'faq.answer.discovery.explain': 'The Discovery section is where you can find new stories, universes, blogs, groups and other content. It is a place to explore and find new things to read and enjoy.',
    // Writer
    'faq.question.writer.howToCreateStory': 'How do I create a new story in Literary Universe?',
    'faq.answer.writer.howToCreateStory': 'You can create a new story by going to the <a href="/workshop">workshop</a> and clicking on one of the create buttons or go to the main <a href="/workshop/create">create page</a> where you can select a <a href="/workshop/create/story">new standalone story</a> or <a href="/workshop/create/fanfiction">fan fiction</a>. To create a new story in a universe, go first to that universe and then select "stories" on the dashboard and on the next page click the big red button on the right side of the page title. You will be asked to fill in the details of your story and then you can start writing.',
    'faq.question.writer.schedule': 'How do I schedule a chapter to be released in Literary Universe?',
    'faq.answer.writer.schedule': 'You can schedule a chapter to be released when clicking on the publish button in the chapter editor. A modal will be shown where you will have the option to schedule a release or publish immediately. If you choose to schedule a release, you will be asked to select the date and time when you want the chapter to be released. We recommend scheduling chapters at least 24 hours in advance to give readers time to prepare for the new chapter and to release on the same day and time of the week.',
    // Reader
    'faq.question.reader.creativeTypes': 'What is the difference between Universe, Stories and Fan Fiction?',
    'faq.answer.reader.creativeTypes': 'Universe is a place where you can find all the stories and other content related to a specific literary world. Stories are either standalone stories or part of a universe that. Fan Fiction is a story that is based on another literary universe created by someone else.',
    // Workshop
    'faq.question.workshop.explain': 'What is the Workshop?',
    'faq.answer.workshop.explain': 'The Workshop is where you can create new stories, fan fiction, universes, and other content. It is a place to write, edit and manage your creative content.',
    'faq.question.workshop.creativeTypes': 'What is the difference between Universe, Stories and Fan Fiction?',
    'faq.answer.workshop.creativeTypes': 'Universe is a central place for your literary universe in which you create stories that inhabit the same literary world, manage encyclopedia with all the intricacies of your world and do anything else related to it. Fan Fiction is a story that is based on another story or universe created by someone else. Standalone stories are stories that are not connected to any universe, use this for example for poetry or literary works that are set in real world without many characters or immersive details that would require encyclopedia or other benefits of having a universe.',
    'faq.question.workshop.continueStory': 'How do I continue a previously created story?',
    'faq.answer.workshop.continueStory': 'You can continue a previously created story by going to the <a href="/workshop">workshop</a> and selecting the story you want to continue or if it is a story in a universe, you need to first go to the universe and select the story from the stories listing. On the story dashboard you can then click on the chapter you want to continue writing or create a new chapter.',
    'faq.question.workshop.whatIsALicense': 'What is a Story License?',
    'faq.answer.workshop.whatIsALicense': 'A story license is a legal document that defines how your story/universe can be used by others. It is a way to protect your rights and to define how others can use your work.',
    'faq.question.workshop.licenses': 'What licenses are available?',
    'faq.answer.workshop.licenses': 'We offer a variety of licenses to choose from. When creating a new work in the licenses section will be a button which will list all available licenses with their full details. In general we offer full copyright protections and <a href="https://creativecommons.org/" target="_blank" rel="noreferrer noopener external">Creative Commons</a> licenses.',
    'faq.question.workshop.guildOwnership': 'What is a Guild ownership?',
    'faq.answer.workshop.guildOwnership': 'Guild ownership indicated a work that is owned by an organization, we call them Guilds. This could be a publisher or another type of a company or non-profit organization. The ownership of the work is usually bit more complex and the author might not have full control over the work, it mainly means that the work is managed through the organization and not by the author from their personal account.',
    'faq.question.workshop.howToInviteCollaborators': 'How do I invite collaborators for a story/universe?',
    'faq.answer.workshop.howToInviteCollaborators': 'You can invite collaborators to your story/universe by going to the story/universe dashboard and clicking the "collaborators" button. There you can invite other users to collaborate on your story/universe by entering their username and selecting the role you want to assign to them.',
    'faq.question.workshop.howToTranslation': 'How can I translate my story or universe?',
    'faq.answer.workshop.howToTranslation': 'You can translate your story or universe by going to the story/universe dashboard and clicking the "Translations" button. There you can add a new translations for your work and if you have someone to do the translation you can invite them to join on the translation. From there you can also manage the translations yourself.',
    'faq.question.workshop.betaReaders': 'What are Beta Readers and what is their purpose to my story?',
    'faq.answer.workshop.betaReaders': 'Beta readers are people who read your story before it is published and give you feedback. They can help you find mistakes, give you ideas for improvement, and help you make your story better.',
    'faq.question.workshop.hiatus': 'What is a hiatus in the story status?',
    'faq.answer.workshop.hiatus': 'Hiatus is a status for your story that indicates that you are taking a break from writing and publishing new chapters. It is a way to let your readers know that you are not actively working on the story at the moment. This status gets set automatically after 6 months without any new chapters. After additional 6 months of inactivity the story will be marked as cancelled.',
    'faq.question.workshop.finished': 'How do I indicate that my story is finished?',
    'faq.answer.workshop.finished': 'You can indicate that your story is finished by going to the story dashboard and on the bottom there is a green button which says "Change story status to Completed". This will mark the story as finished adjusting the last page to tell the readers that the story is finished and to check out your other works. It will also indicate so in discovery making your story more visible to readers who are looking for finished stories.',
    'faq.question.workshop.seo': 'What is the use of SEO-Friendly-Address in various settings?',
    'faq.answer.workshop.seo': 'SEO-Friendly-Address is a way to make your story, universe, blog post more visible to search engines and easier to read URL for humans. It is a way to make your work more discoverable and to help people find your work when they search for something similar.'
};