export default {
    'plans.desc': 'Literary Universe의 계획과 기능에 대한 설명입니다.',
    'plans.title': 'Literary Universe에서 더 많은 기능을 활용하세요!',
    'plans.text': 'Literary Universe는 기본 기능을 무료로 제공합니다. 독서가나 창작자라면 고급 멤버십이 더 많이 맞을 수도 있습니다.',
    'plans.faq.basicsPriced': '왜 무료 멤버십은 그렇게 적은 기능을 가지고 있나요?',
    'plans.faq.justification': 'Literary Universe에서는 개인정보와 지적 재산을 소중히 여깁니다. 그래서 광고를 판매하거나 다른 회사에 제공하는 데에는 사용하지 않습니다. 이는 우리가 많은 것을 직접 구축해야 한다는 것을 의미합니다. 이는 많은 시간이 걸리고 운영 비용도 많이 듭니다. 그래서 우리는 Literary Universe의 작은 미리보기로서 무료 회원 자격을 마련했습니다(그러나 여전히 가장 중요한 작업을 수행할 수 있습니다). 또한 다양한 회원 자격과 애드온을 제공하여 모든 사람의 요구에 맞추면서도 서비스를 유지하고 계속 발전할 수 있도록 하였습니다. 만약 우리가 구축하고 있는 것이 마음에 드신다면 유료 옵션 중 하나에 가입을 고려해 주시기 바랍니다. 감사합니다!',
    'plans.limits': '제한 사항',
    'plans.features': '기능',
    'plans.account.user': '방문자',
    'plans.account.user.desc': '시스템을 시험해 볼 수 있는 초기 평가판 계정입니다.',
    'plans.account.explorer': '탐험가',
    'plans.account.explorer.desc': '취미로 즐기거나 친구와 함께하는 경우에 적합합니다.',
    'plans.account.adventurer': '모험가',
    'plans.account.adventurer.desc': '창작자 및 우리의 서포터를 위해.',
    'plans.account.storyteller': '작가',
    'plans.account.storyteller.desc': '가장 창의적이고 헌신적인 사용자를 위한 멤버십입니다.',
    'plans.unlimited': '무제한',
    'plans.price': '가격',
    'plans.price.free': '무료',
    'plans.price.monthly': '월별*',
    'plans.price.annually': '연간*',
    'plans.price.perMonth': '{price} / 월*',
    'plans.price.perYear': '{price} / 년*',
    'plans.development': '개발 중',
    'plans.limits.encEntries': '백과사전 항목',
    'plans.limits.maxCollaborators': '프로젝트 당 공동 참여자 수',
    'plans.limits.pmChats': '개인 메시지의 최대 수신자 수',
    'plans.feature.creative': '멋진 우주와 이야기를 만들어보세요',
    'plans.feature.encCustomFields': '항목의 사용자 정의 가능한 백과사전 필드',
    'plans.feature.encAdvCategories': '더 많은 백과사전 카테고리',
    'plans.feature.scratchpad': '스크래치패드',
    'plans.feature.library': '도서관',
    'plans.feature.blog': '개인 및 우주 블로그',
    'plans.feature.customBlogTheme': '사용자 정의 가능한 블로그 테마',
    'plans.feature.advanceStats': '고급 통계',
    'plans.feature.challenges': '글쓰기 도전',
    'plans.feature.newFeaturesVote': '새로운 기능 투표',
    'plans.feature.newFeaturesSuggest': '새로운 기능 제안',
    'plans.feature.accessToBeta': '베타 기능에 접근',
    'plans.feature.userGroups': '사용자 그룹',
    'plans.feature.privateUserGroups': '사용자 그룹을 생성하고 숨길 수 있습니다',
    'plans.feature.internalUniverseForums': '대학을 위한 내부 포럼',
    'plans.feature.fictionalTime': '가상 시간',
    'plans.feature.forums': '블로그 및 우주 페이지의 포럼',
    'plans.feature.timelines': '우주 타임라인',
    'plans.feature.webMonetization': '웹 수익 창출',
    'plans.feature.storyMonetization': '이야기 수익화',
    'plans.feature.fanClub': '팬 클럽',
    'plans.feature.translations': '번역 기능',
    'plans.feature.fanFiction': '팬 픽션 작성 및 관리',
    'plans.feature.universeFanArt': '팬 아트 관리자',
    'plans.feature.overviewNotes': '이야기 개요 노트',
    'plans.feature.personalNotesStoriesUniverses': '이야기와 우주에 대한 개인 노트',
    'plans.feature.storyReviews': '이야기 리뷰',
    'plans.feature.readingLists': '읽기 목록',
    'plans.feature.scenesManager': '장면 관리자',
    'plans.feature.glossaries': '번역 용어집',
    'plans.feature.chatSupport': '채팅 지원',
    'plans.currency.select': '통화 선택',
    'plans.subscription.ownAlready': '현재 이 요금제를 사용하고 있습니다',
    'plans.subscription.title': '구독',
    'plans.see': '사용 가능한 구독 요금제 보기',
    'plans.current.none': '현재 Literary Universe를 지원하지 않고 있습니다.',
    'plans.current.buying': '구매를 확인하는 데 몇 분 정도 소요될 수 있습니다. 여러분의 인내심에 감사드립니다.',
    'plans.current.heading': '현재 구독 요금제',
    'payment.methods.title': '결제 및 수익 창출',
    'payment.methods.tabs': '결제 옵션',
    'payment.option.title': '결제 옵션',
    'payment.option.notFount': '저장된 결제 옵션이 없습니다.',
    'payment.option.create': '새로운 결제 옵션 추가',
    'payment.option.description': '여기에 저장된 결제 방법 목록이 있습니다. 빠른 체크아웃을 위해 여기에서 새로운 결제 방법을 저장할 수 있습니다. Literary Universe는 신용카드 번호와 같은 결제 자격을 저장하거나 처리하지 않습니다.',
    'payment.history.title': '결제 내역',
    'payment.history.tab': '역사',
    'payment.history.none': '과거 결제 기록이 없습니다.',
    'plans.options.aria': '결제 옵션',
    'plans.options.creditCard': '신용카드',
    'plans.options.creditCardNew': '새로운 신용카드',
    'plans.options.existingCards': '저장된 신용카드',
    'plans.purchase.action': '구독하기',
    'plans.purchase.title': 'Literary Universe 구독 구매',
    'payment.creditCard.details': '신용카드 세부 정보',
    'payments.zipcode.label': '우편번호',
    'payment.card.name': '카드상의 이름',
    'plans.subscribed.thankYou': 'Literary Universe를 지원해 주셔서 감사합니다',
    'plans.subscribed.periodEnd': '구독은 다음 날짜까지 유효합니다: {end, date, medium}',
    'plans.subscribed.renewal': `At the end your subscription will be {method, select,
    charge_automatically {renewed automatically}
    send_invoice {renewed after paying an invoice}
    other {}
  }.`,
    'plans.subscribed.paymentMethod': '다음 주기에는 기본 결제 방법이 사용됩니다.',
    'plans.subscribed.status': `구독 상태: {status, select,
    active {활성화됨}
    incomplete {누락된 항목이 있습니다}
    incomplete_expired {누락된 항목이 있습니다}
    trialing {체험판}
    past_due {결제가 누락되었습니다}
    canceled {취소됨}
    unpaid {미지급}
    expired {만료됨}
    other {}
  }`,
    'payments.changeMethod': '결제 방법 변경',
    'plans.subscribed.willNotRenew': '주기 종료 시 갱신되지 않습니다.',
    'plans.cancel.button': '구독 취소',
    'plans.cancel.question': '구독을 취소하시겠습니까? 구독은 청구 주기 종료까지 유지됩니다.',
    'plans.cancel.confirmationButton': '네, 구독을 취소하고 싶습니다',
    'plans.cancel.failed': '죄송합니다. 현재는 요금제를 취소할 수 없습니다. 나중에 다시 시도해주세요.',
    'plans.cancel.restoreBtn': '구독 복원',
    'plans.cancel.restoreFailed': '죄송합니다. 현재는 구독을 복원할 수 없습니다. 나중에 다시 시도해주세요.',
    'plans.change.button': '구독 변경',
    'plans.change.explanation': '원하는 요금제로 업그레이드 또는 다운그레이드할 요금제를 선택하세요. 가격 차액이 즉시 청구됩니다.',
    'plans.change.failed': '죄송합니다. 현재는 요금제를 변경할 수 없습니다. 나중에 다시 시도해주세요.',
    'plans.change.upgrade': '업그레이드',
    'payments.disclaimer': '결제 정보 및 처리는 Stripe를 통해 이루어집니다. 우리는 신용 카드나 은행 계좌 정보를 서버에 보관하지 않습니다.',
    'buy.payment.optionsSelect': '결제 옵션 선택',
    'payments.card.number': '카드 번호',
    'payments.card.expire': '유효 기간',
    'payments.card.cvv': 'CVV',
    'payments.card.info': '{cardType} 카드, 끝자리 {ending}',
    'payments.none': '저장된 결제 옵션이 없습니다.',
    'payments.none.cards': '카드를 찾을 수 없습니다.',
    'payments.added': '새로운 결제 옵션이 성공적으로 추가되었습니다.',
    'payments.delete.confirm': '정말로 삭제하시겠습니까? {cardType}, 끝자리는 {ending}입니다.',
    'payment.invoice.status': '송장 상태',
    'payment.invoice.statusMessage': `{status, select,
    draft {초안}
    open {열린 상태}
    paid {지불 완료}
    uncollectible {미수금 불가능}
    void {무효}
    other {}
  }`,
    'payment.invoice.id': '송장 ID',
    'payment.invoice.pdf': '송장 PDF',
    'payment.invoice.total': '총액',
    'payment.invoice.what': '송장 설명',
    'payment.stripe.powered': '제공: ',
    'payment.listMethods.card': '카드',
    'payment.expiresAt': '만료일 {month}/{year}',
    'payment.card.details': `{type, select,
    credit {신용카드}
    debit {직불카드}
    other {카드}
  } 끝자리는 {last4}입니다.`,
    'payment.options.default': '기본',
    'payment.method.add': '새로운 결제 방법 추가',
    'payment.methods.adding': '새로운 결제 방법이 계정에 추가되었습니다.',
    'payment.methods.delete': '결제 방법 삭제',
    'payment.upgradePlan.option': '{plan} - {price}',
    'payment.methods.webMonetization': '웹 수익 창출',
    'settings.webMonetization.placeholder': '당신의 결제 포인터',
    'payment.webMonetization.explained': '웹 결제에 대한 제안된 표준인 웹 모네타이제이션입니다. 여기에 웹 모네타이제이션에서 사용되는 당신의 결제 포인터를 추가할 수 있습니다. 이 포인터는 당신의 프로필 페이지, 블로그, 우주 및 이야기에 추가되어 웹 모네타이제이션에서 활용될 것입니다.',
    'payment.webMonetization.learnMore': '웹 모네타이제이션에 대해 더 알아보기',
    'plans.subscription.settingsAria': '구독 설정 옵션',
    'plans.buttonStatus.submitting': '요청을 제출하는 중...',
    'plans.button.manageOnStripe': 'Stripe에서 결제 관리',
    'plans.call.signUpBottom': '무료 Literary Universe 계정을 등록하고 창작을 시작하세요!',
    'plans.button.seeComparison': '요금제와 가격에 대해 자세히 알아보세요!',
    'plans.button.chooseThisSubscription': '이 요금제 선택하기',
    'plans.button.chooseFree': '무료로 시작하기',
    'plans.features.allInPreviousTiers': '이전 단계의 모든 기능',
    'plan.button.chooseNow': '지금 Literary Universe 요금제를 선택하세요',
    'plans.subscription.manage': '구독 관리',
    'plans.taxMayApply': '* 부가가치세 및 기타 지역세금이 적용될 수 있습니다',
    'plans.faq.crypto': '암호화폐 결제를 제공하나요?',
    'plans.faq.cryptoAnswer': '네, 현재 작업 중입니다. Web3의 큰 팬이며, 가까운 미래에 플랫폼에 Web3를 통합하는 방법을 찾고 있습니다. 현재는 Web3로 로그인할 수 있도록 허용하고 있으며, 창작자에게 보상을 제공하고 창작자가 원하는 모든 결제 옵션을 선택할 수 있도록 이 서비스를 확장하려고 노력하고 있습니다.',
    'plans.subscribed.updating': '구독 정보를 업데이트하는 데 시간이 조금 걸릴 수 있습니다. 양해해 주셔서 감사합니다!',
    'payments.methods.webMonetization': '웹 수익 창출',
    'stripeConnect.settings.title': '지급 설정',
    'stripeConnect.settings.intro': 'Literary Universe를 통해 자금을 받거나 판매하려면 아래의 버튼을 통해 Stripe 계정을 생성해야 합니다.',
    'stripeConnect.settings.connectAccount': 'Stripe 계정 설정',
    'stripeConnect.settings.ongoing': '당신의 계정에 대해 Stripe로부터 답변을 기다리고 있습니다. 이는 약간의 시간이 걸릴 수 있습니다. 너무 오래 걸린다면 아래 버튼을 클릭하여 Stripe로 돌아갈 수 있습니다.',
    'stripeConnect.settings.finished': 'Stripe Connect를 통해 돈을 받을 준비가 모두 되었습니다.',
    'stripeConnect.settings.balance': '잔액',
    'stripeConnect.settings.balanceAvailable': '사용 가능한 잔액',
    'stripeConnect.settings.balancePending': '보류 중인 잔액',
    'stripeConnect.settings.recentTransfers': '최근 이체',
    'stripeConnect.transfers.amount': '금액',
    'stripeConnect.transfers.reason': '이유',
    'payment.settings.donations': '기부 설정',
    'plans.fanClub.heading': '팬 클럽',
    'payment.donations.enable': '기부 활성화',
    'payment.donations.suggestedAmount': '제안하는 금액',
    'payment.donations.amount': '금액',
    'payment.donations.preferredCurrency': '선호하는 통화',
    'payment.donations.currency': '통화',
    'payment.donations.stripeDescription': '{username}에 대한 기부',
    'payment.donations.support': '{username}지원',
    'payment.donations.donate': '기부하기',
    'payment.donations.donationModal': '기부 확인',
    'payment.donations.payNowUSD': '{donation, number, ::compact-short currency/USD} 을(를) {username}에 기부하기',
    'payment.donations.payNowJPY': '{donation, number, ::compact-short currency/JPY} 을(를) {username}에 기부하기',
    'payment.donations.payNowEUR': '{donation, number, ::compact-short currency/EUR} 을(를) {username}에 기부하기',
    'payment.donations.payNowCZK': 'Donate {donation, number, ::compact-short currency/CZK} to {username}',
    'payment.donations.payNowGBP': 'Donate {donation, number, ::compact-short currency/GBP} to {username}',
    'payment.donations.thankYouTitle': '{username}에 대한 기부에 감사드립니다.',
    'payment.donations.thankYouContinue': '{username}을(를) 지원해주셔서 감사합니다. 앞으로도 그들의 작품을 즐기시고 계속해서 지원해주시기 바랍니다.',
    'payment.success': '결제가 성공적으로 완료되었습니다!',
    'payment.processing': '결제가 처리 중입니다.',
    'payment.failed': '결제가 실패했습니다. 다시 시도해주세요.',
    'payment.generalError': '문제가 발생했습니다.',
    'payment.unexpectedError': '문제가 발생했습니다.',
    'payments.transferType.donation': '기부',
    'payment.donation.backToProfile': '{username}의 프로필로 돌아가기',
    'payment.author.requirementStripeConnect': '금융 거래를 처리하기 위해 Stripe Connect 계정을 생성하고 연결해야 합니다.',
    'payment.author.requirementPublishWork': '계속하기 전에 적어도 하나의 작품(이야기 또는 우주)을 게시해야 합니다.',
    'payment.author.createWork': '새 작품 만들기',
    'payment.author.directivesTitle': '추천 사항',
    'payment.author.directivesExplained': '결제 서비스를 활성화하기 전에 성공 기회를 높이기 위해 몇 가지 추가 권장 사항이 있습니다.',
    'payment.author.directivesStoryPublished': '자신의 작품을 자랑하기 위해 무료로 적어도 하나의 이야기를 게시하세요.',
    'payment.author.directivesFreeStoryFinished': '독자들이 여정 중에 방치되지 않을 것을 보여주기 위해 적어도 하나의 무료 이야기를 완결 지으세요.',
    'payment.universe.directivesUniversePublished': '자신의 우주를 게시하세요.',
    'payment.universe.directivesEncFull': '백과사전을 채우세요. 최소한 30개의 항목이 있어야 합니다! 100개 이상이면 더 좋습니다.',
    'payment.universe.haveFans': '당신이 하는 일에 이미 관심이 있는 사람들이 후원자가 되는 것은 더 쉽습니다. 100명의 팬이 당신의 작품을 자신의 라이브러리에 추가하는 것이 시작선입니다.',
    'payment.settings.yourFanClub': '팬 클럽',
    'payment.settings.newWork': '새 작품 만들기'
};