export default {
    'workshop.title': '당신의 작업',
    'workshop.noneassigned': '아직 할당된 작업이 없습니다.',
    'workshop.notavailable': '이 기능은 아직 사용할 수 없습니다.',
    'workshop.none': `현재 {type, select,
      universe {우주,}
      story {작품,}
      fanfiction {팬 픽션,}
      other {}
    }이 없습니다. 지금 만드세요!`,
    'workshop.collab': '공동 작업',
    'workshop.betareadings': '베타 리딩',
    'workshop.translations': '번역',
    'workshop.createnew': '새로 만들기...',
    'workshop.story.standalone': '독립형 스토리',
    'workshop.story.standalone.desc': '이것은 독립적인 이야기입니다.',
    'workshop.controlpanel': '{name} 제어판',
    'workshop.universe.page': '우주 페이지',
    'workshop.fictionaltime': '가상 시간',
    'workshop.dashboard.name': '{name} 대시보드',
    'workshop.stories.in': '{universe}의 이야기',
    'workshop.universe.nostories': '이 우주에는 이야기가 없습니다.',
    'workshop.story.chapter.add': '새로운 챕터',
    'workshop.universe.new': '새로운 우주 만들기',
    'workshop.universe.publish': '우주 게시',
    'workshop.universe.publishing.notice': '우주를 게시하지 않으면, 우주에 연결된 첫 번째 이야기가 게시될 때 자동으로 게시됩니다.',
    'workshop.universe.settings': '{universe} 우주 설정',
    'workshop.universe.publishedOn': '이 우주는 {date, date, long} 에 게시되었습니다. {date, time, short}',
    'workshop.work.deletion.contactUs': '도움이 필요하면 <contact>문의하세요</contact>.',
    'workshop.work.delete.restrictions': `이 {type, select,
    universe {유니버스는 게시된 스토리가 없는 경우에만 삭제할 수 있으며,}
    story {스토리는}
    other {작품은}} 게시된 지 한 달이 안 된 경우에만 삭제할 수 있습니다. 그 후에도 도움이 필요하신가요? <contact>문의해</contact> 주세요.`,
    'workshop.work.delete.notAllowed': `이 {type, select,
    universe {유니버스}
    story {스토리}
    other {일}
  } 는 더 이상 셀프 서비스를 통해 삭제할 수 없습니다. 삭제가 필요한 경우 고객센터로 <contact>문의하시면</contact> 안전하게 삭제해 드리겠습니다.`,
    'workshop.work.delete.notAllowed.plain': `이 {type, select,
    universe {유니버스}
    story {스토리}
    other {일}
  } 는 더 이상 셀프 서비스를 통해 삭제할 수 없습니다. 삭제가 필요한 경우 deletions@literaryuniverse.com 으로 문의하시면 안전하게 삭제할 수 있도록 도와드리겠습니다.`,
    'workshop.work.danger.delete.desc': `이 영구 삭제 {type, select,
    universe {유니버스 및 연결된 워크샵 데이터}
    story {모든 챕터, 통계 및 워크샵 연관성이있는 스토리}
    other {작업 및 관련 데이터}
  }.`,
    'workshop.work.makePrivate.impact': `이것을 {type, select,
    universe {우주}
    story {이야기}
    other {일}
  } 로 만들면 검색 및 검색에서 제거됩니다. 이미 라이브러리에 있는 사람들은 계속 액세스할 수 있습니다. 새로운 사용자는 더 이상 라이브러리에 추가할 수 없으며{type, select,
    story { 선물하지 않는 한}
    other {}
  } 구입할 수 없습니다.`,
    'workshop.work.private.notice': `이 {type, select,
    universe {우주}
    story {이야기}
    other {일}
  } 현재 비공개입니다. 기존 라이브러리 소유자는 계속 액세스할 수 있습니다. 신규 사용자는 라이브러리에 추가하거나{type, select,
    story { 구매}
    other {}
  } 할 수 없습니다.`,
    'workshop.work.makePrivate.button': `만들기 {type, select,
    universe {유니버스}
    story {스토리}
    other {워크}
  } 비공개`,
    'workshop.work.makePrivate.modalAria': `{type, select,
    universe {우주}
    story {스토리}
    other {일}
  } 비공개로 만들기 위한 확인 모달`,
    'workshop.work.makePrivate.warning': `이 {type, select,
    universe {유니버스}
    story {스토리}
    other {워크}
  } 비공개로 설정하면 공개 검색 및 검색에서 삭제됩니다.`,
    'workshop.work.makePublic.button': `만들기 {type, select,
    universe {유니버스}
    story {스토리}
    other {작업}
  } 공개`,
    'workshop.work.makePublic.modalAria': `{type, select,
    universe {우주}
    story {스토리}
    other {작업}
  } 공개를 만들기 위한 확인 모달`,
    'workshop.work.makePublic.warning': `이것을 {type, select,
    universe {유니버스}
    story {스토리}
    other {작품}
  } 공개하면 새로운 사용자가 다시 검색할 수 있고 라이브러리{type, select,
    story { 에 추가하거나 구매}
    other {}
  } 할 수 있습니다.`,
    'workshop.universe.dangerZone': '위험 구역',
    'workshop.universe.dangerZone.desc': '이 유니버스는 게시된 스토리가 없고 게시된 지 한 달이 지나지 않은 경우에만 삭제할 수 있습니다. 이 제한 기간이 지난 후에 삭제해야 하는 경우 문의해 주세요.',
    'workshop.universe.delete.modalAria': '유니버스 삭제를 위한 확인 모달',
    'workshop.universe.delete.warning': '"{title}"를 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
    'workshop.universe.delete.button': '유니버스 삭제',
    'workshop.universe.description': '우주 설명',
    'workshop.settings.title': '제목',
    'workshop.description': '설명',
    'workshop.language.primary': '기본 언어',
    'workshop.publication.options': '게시 옵션',
    'workshop.rating': '일반 등급',
    'workshop.universe.rating.desc': '이 등급 이상의 이야기와 팬픽션은 익명 사용자 및 적합한 연령이 아닌 사용자의 우주 페이지 목록에서 숨겨집니다.',
    'workshop.universe.license': '우주 라이선스',
    'workshop.universe.genre.pick': '우주에 대한 장르 선택',
    'workshop.story.genre.pick': '이야기에 대한 장르 선택',
    'workshop.cover': '표지',
    'workshop.nothingtosee': '볼 것이 없습니다...',
    'workshop.story.cannon': '캐논 이야기',
    'workshop.story.cannon.desc': '이 이야기는 {universe} 우주에서 캐논입니다.',
    'workshop.story.cannon.desc.create': '이 이야기는 {universe} 우주에서 대표적인 이야기로 생성될 것입니다.',
    'workshop.story.fanfiction.search': '우주의 이름을 입력하세요 (당신의 라이브러리에 있어야 함). 그리고 제안에서 선택하세요.',
    'workshop.story.error.nogenres': '최소한 한 가지 장르를 선택해야 합니다.',
    'workshop.story.error.toomanygenres': '이야기당 최대 두 가지 장르만 허용됩니다.',
    'workshop.story.error.fanfiction.selectuniverse': '팬픽션을 위해 원작 우주를 선택해야 합니다!',
    'workshop.story.error.tags.toomany': '이야기당 최대 10개의 태그만 가질 수 있습니다.',
    'workshop.thema.primary': '테마 기본 분류',
    'workshop.thema.secondary': '테마 보조 분류',
    'workshop.thema.secondary.max': '최대 {max} 보조 분류를 추가할 수 있습니다.',
    'workshop.thema.selectedCode': 'Code: {code}',
    'workshop.thema.searchPlaceholder': '이름으로 검색(예: "공상 과학")',
    'workshop.thema.quickRef': '📖 테마 빠른 참조',
    'workshop.story.new': '새 이야기 만들기',
    'workshop.story.publishing.notice': '첫 번째 챕터를 게시하면 이야기가 자동으로 게시됩니다.',
    'workshop.story.published.congratulations.title': '축하합니다! 스토리가 게시되었습니다.',
    'workshop.story.published.congratulations.heading': '축하합니다! 스토리가 게시되었습니다.',
    'workshop.story.published.congratulations.description': '글쓰기 여정은 계속됩니다. 이제 여러분의 스토리를 독자들이 발견하고 즐길 준비가 되었습니다.',
    'workshop.story.published.congratulations.publicStoryBtn': '스토리 페이지로 이동',
    'workshop.story.published.congratulations.imageAlt': '게시된 스토리를 위한 축하 일러스트',
    'workshop.settings.edit': '설정 편집',
    'workshop.story.publishedOn': '이 작품은 {date, date, long} 에 게시되었습니다. {date, time, short}',
    'workshop.story.settings': '이야기 설정',
    'workshop.settings.basic': '기본 설정',
    'workshop.settings.genres': '장르 (최대 2개)',
    'workshop.story.license': '이야기 라이선스',
    'workshop.story.settings.universe': '우주 설정',
    'workshop.story.dangerZone': '위험 구역',
    'workshop.story.dangerZone.desc': '이러한 작업은 여러 유니버스에서 스토리가 구성되는 방식에 영향을 줍니다. 신중하게 진행하세요.',
    'workshop.story.universe.assign.missing': '계속하려면 유니버스를 선택하세요.',
    'workshop.story.universe.assignTitle': '유니버스 생성 또는 할당',
    'workshop.story.universe.assign.desc': '이 스토리를 기존 유니버스에 연결하거나 스토리 세부 정보를 사용하여 새로운 유니버스를 만들 수 있습니다.',
    'workshop.story.universe.assign.mode': '유니버스 옵션',
    'workshop.story.universe.assign.existing': '기존 유니버스에 할당',
    'workshop.story.universe.assign.create': '이 스토리로 새로운 우주를 창조하세요',
    'workshop.story.universe.assign.loading': '유니버스 로드 중...',
    'workshop.story.universe.assign.select': '유니버스 선택',
    'workshop.story.universe.assign.placeholder': '유니버스 선택',
    'workshop.story.universe.assign.none': '아직 우주가 없습니다. 계속하려면 새 유니버스를 만드세요.',
    'workshop.story.universe.assign.publishNote': '이 이야기는 이미 출간되었으므로 새로운 우주도 출간될 예정입니다.',
    'workshop.story.universe.assign.createBtn': '유니버스 만들기',
    'workshop.story.universe.assign.trigger': '유니버스 생성 또는 할당',
    'workshop.story.universe.standalone.title': '독립형 스토리 만들기',
    'workshop.story.universe.standalone.heading': '이 이야기를 다른 세계로 옮기시겠습니까?',
    'workshop.story.universe.standalone.desc': '이 스토리는 유니버스에서 삭제되고 독립형 스토리로 나열됩니다.',
    'workshop.story.universe.standalone.current': '현재 우주: {title}',
    'workshop.story.universe.standalone.warning1': '우주를 검색하는 독자는 더 이상 이 스토리를 볼 수 없습니다.',
    'workshop.story.universe.standalone.warning2': '이 스토리의 유니버스 버전으로 연결되는 기존 링크는 더 이상 작동하지 않을 수 있습니다.',
    'workshop.story.universe.standalone.warning3': '나중에 스토리 설정에서 스토리를 유니버스에 다시 연결할 수 있습니다.',
    'workshop.story.universe.standalone.trigger': '독립형 스토리 만들기',
    'workshop.settings.tags': '태그',
    'workshop.revision': '개정',
    'workshop.revisions.title': '{story}: {chapter} 개정',
    'workshop.revisions.current': '현재 초안',
    'workshop.revisions.new.beta': '초안에서 새 개정 생성하기.',
    'workshop.revisions.new.public': '초안에서 새 공개 개정 생성하기.',
    'workshop.revisions.toeditor': '편집기로 이동하기',
    'workshop.revisions.comments': '개정 코멘트',
    'workshop.revisions.comments.title': '{story}: {chapter} - 개정 {revision} - 코멘트',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {for Beta readers}
      readers {Public}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': '먼저 개정을 생성해야 합니다.',
    'workshop.revisions.comments.select': '번역 선택',
    'workshop.collaborators.noresults': '결과 없음',
    'workshop.collaborators.add.beta': '베타 리더 추가',
    'workshop.collaborators.add.collaborator': '공동 작업자 추가',
    'workshop.collaborators.add.translator': '번역자 추가',
    'workshop.collaborators.language.add': '새로운 번역 생성',
    'workshop.translations.stories': '번역 - 이야기',
    'workshop.translations.universes': '번역 - 우주',
    'workshop.revisions.beta.none': '현재 리비전 없음.',
    'reader.asidetoggle': '사이드 정보 전환',
    'workshop.translation.original': '원본:',
    'workshop.translation.original.title': '원본 제목:',
    'workshop.translation.original.description': '원본 설명:',
    'workshop.translation.original.cover': '원본 표지',
    'workshop.translation.original.tags': '원본 태그',
    'workshop.cover.alt': '표지 이미지',
    'workshop.translation.updatedOrig': '원본의 최신 업데이트: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': '번역의 최신 업데이트: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': '원본의 마지막 리비전 {revision, number},: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': '번역의 마지막 리비전 {revision, number},: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.collaborators.premium': `더 많은 {type, select,
    collaborator {공동 창작자,}
    beta {베타 리더,}
    translator {번역자,}
    other {}
  }를 추가하려면 멤버십 등급을 높여야 합니다.`,
    'workshop.collaborators.requests.sent': '보낸 요청',
    'workshop.collaborators.requests.invite': `다음에 대한 {role, select,
    beta {베타 리더,}
    translator {번역자,}
    collaborator {공동 창작자,}
    other {}
  } 로 초대되었습니다.`,
    'workshop.collaborators.requests.dashboard': `당신은 협업을 위해 초대되었습니다 {count, plural,
    zero {작품이 있습니다}
    one {하나의 문학 작품이 있습니다}
    other {개의 문학 작품이 있습니다}
  }.`,
    'workshop.collaborators.language.added': '언어가 추가되었습니다',
    'workshop.story.noChaptersFound': '챕터를 찾을 수 없습니다.',
    'workshop.fanfic.needUniverseInLibrary': '세상에는 많은 우주들이 있습니다. 먼저 작성하고자 하는 우주를 도서관에 추가해주세요.',
    'workshop.fanfic.findUniverse': '멋진 우주를 찾아보세요!',
    'workshop.encSettings': '백과사전 설정',
    'workshop.collaborators.removeUser': '사용자 제거',
    'workshop.collaborators.cancelInvite': '초대 취소',
    'workshop.universe.createFirstStory': '첫 번째 이야기 만들기',
    'workshop.storylines': '스토리라인',
    'workshop.scenesManager': '장면 관리자',
    'workshop.collaborators.addRoleForLang': '{language}을(를) 위한 {role} 추가',
    'workshop.beta.revisionInfo': '이것은 {createdAt, date, long}에 생성된 수정본입니다. (리비전: {revision, number})',
    'workshop.story.notes.title': '{storyTitle}에 대한 참고사항',
    'workshop.story.notes.desc': '이야기에 대한 개요 참고사항입니다.',
    'workshop.story.notes.tile': '개요 참고사항',
    'workshop.story.alternateFormats.tile': '대체 형식',
    'workshop.story.alternateFormats.title': '{storyTitle}: 대체 형식',
    'workshop.story.alternateFormats.arcs.title': 'Arcs',
    'workshop.story.alternateFormats.arcs.add': '호 추가',
    'workshop.story.alternateFormats.arc.defaultTitle': 'Arc {index}',
    'workshop.story.alternateFormats.arc.name': '아크 이름',
    'workshop.story.alternateFormats.arc.from': '장에서',
    'workshop.story.alternateFormats.arc.to': '장으로 이동',
    'workshop.story.alternateFormats.arc.uploads': '파일',
    'workshop.story.alternateFormats.arc.upload.epub': 'EPUB 업로드',
    'workshop.story.alternateFormats.arc.upload.pdf': 'PDF 업로드',
    'workshop.story.alternateFormats.epub.generate': 'EPUB 생성',
    'workshop.story.alternateFormats.epub.openGenerated': '생성된 EPUB 열기',
    'workshop.story.alternateFormats.epub.generatedAt': '{generatedAt, date, medium} 에서 {generatedAt, time, short} 생성됨',
    'workshop.story.alternateFormats.epub.generationFailed': 'EPUB 생성에 실패했습니다.',
    'workshop.story.alternateFormats.epub.saveArcBeforeGeneration': '이 아크를 먼저 저장하여 EPUB 생성을 활성화합니다.',
    'workshop.story.alternateFormats.fullStory.title': '전체 스토리 파일',
    'workshop.story.alternateFormats.ongoingAccess.title': '지속적인 액세스',
    'workshop.story.alternateFormats.ongoingAccess.allAvailable': '현재 사용 가능한 모든 챕터',
    'workshop.story.alternateFormats.ongoingAccess.perChapter': '챕터별(챕터가 출시될 때마다)',
    'workshop.hideOrgs': '기관으로부터 내용 숨기기',
    'workshop.translation.premium': '번역을 추가하려면 최소한 탐험가 구독이 필요합니다.',
    'workshop.story.finished': '이야기가 완료되었습니다',
    'workshop.story.publishing.externalSellingNotice': '문학적 우주 외부에서 판매하고 있기 때문에 이제 이야기를 게시할 수 있습니다. 스토리에 대한 상점 링크는 여기에 나타날 것입니다.',
    'workshop.sharing.publicURL': '공개 버전',
    'workshop.fictionalTime.title': '{universeName}에 대한 가상 시간',
    'workshop.fictionalTime.none': '현재 허구적인 시간이 설정되어 있지 않습니다.',
    'workshop.fictionalTime.createNow': '지금 만드세요!',
    'workshop.fictionalTime.createTitle': '새로운 허구적인 시간 만들기',
    'workshop.fictionalTime.editTitle': '편집 {ftName}',
    'workshop.fictionalTime.formDescription': `여기에서 나만의 가상의 시간을 만들 수 있습니다. 현재 이 도구는 제한적이며
        대칭 시간만 만들 수 있습니다. 즉, 마야력이나 그레고리력을 다시 만들 수 없습니다. 현재
        이 도구는 모든 기간이 항상 동일할 것으로 예상합니다(예: 월은 예외 없이 항상 30일 등
        ). 이후 버전에서 이 문제를 해결할 예정이지만 그때까지는 이 도구가 주로
        공상 과학 기반 시간 시스템을 만드는 데 더 적합합니다.`,
    'workshop.fictionalTime.timeName': '시간 이름',
    'workshop.fictionalTime.basicInfo': '기본 정보',
    'workshop.fictionalTime.timeSetup': '시간 설정',
    'workshop.fictionalTime.linkedToET': '이 시간은 지구 날짜(그레고리력)에서 시작합니까?',
    'workshop.fictionalTime.timeDeclaration': '시간 선언',
    'workshop.fictionalTime.declarationLocation': '시간 이름은 어디에 선언해야 하나요?',
    'workshop.fictionalTime.declarationBefore': '단위 앞에',
    'workshop.fictionalTime.declarationAfter': '단위 뒤에',
    'workshop.fictionalTime.declarationNone': '없음',
    'workshop.fictionalTime.units': '단위',
    'workshop.fictionalTime.ETStart': '이 시간의 시작 날짜',
    'workshop.fictionalTime.unitsDescFirst': '이 단위에서 밀리초가 몇 개 있습니까?',
    'workshop.fictionalTime.unitsDesc': '이 단위에서 이전 단위와 비교하여 몇 개의 단위가 있습니까?',
    'workshop.fictionalTime.unitsName': '단위 이름',
    'workshop.fictionalTime.unitsSeparator': '이전 단위와의 구분자',
    'workshop.fictionalTime.unitAdd': '단위 추가',
    'workshop.fictionalTime.clocks': '시계',
    'workshop.fictionalTime.unitTransfer': '단위 이동',
    'fictionalTime.pageStartElapsedTime': '이 페이지를 열고부터 경과한 시간',
    'fictionalTime.currentTime': '현재 시간',
    'workshop.shoppingExternal.options': '외부 구매 옵션',
    'workshop.shoppingExternal.explainer': '이야기가 다른 곳에서 판매되는 경우 여기에 링크를 설정할 수 있습니다. 그러면 링크가 내용 대신 표시되거나 미리보기할 내용의 끝에 표시됩니다.',
    'workshop.shoppingExternal.amazonStore': 'Amazon 스토어',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': '상점 이름',
    'workshop.shoppingExternal.itemUrl': '상품 URL',
    'workshop.shoppingExternal.storesOther': '다른 상점',
    'fictionalTime.units.milliseconds': '{units, number} 밀리초',
    'fictionalTime.countdownToStart': '시작 시간까지의 카운트다운',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 일 }
      other {{days} 일 }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {초}
      other {초}
    }}
    minutes {{units, plural,
      one {분}
      other {분}
    }}
    hours {{units, plural,
      one {시간}
      other {시간}
    }}
    days {{units, plural,
      one {일}
      other {일}
    }}
    years {{units, plural,
      one {년}
      other {년}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': '부터',
    'fictionalTime.inputSelectTimeUnit': '시간 단위 선택',
    'fictionalTime.inputSelectETUnit': '지구 시간 단위 선택',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': '사이드바 도구상자',
    'workshop.writerSidebar.description': '이야기에 오신 것을 환영합니다! 이 사이드바를 통해 이야기와 관련된 모든 리소스에 쉽게 액세스할 수 있습니다. 위의 아이콘을 확인하여 최신 댓글, 메모 등을 확인하세요!',
    'workshop.story.authorsNotesExplained': '독자들이 챕터 시작 시 읽을 수 있는 작가의 참고사항입니다.',
    'workshop.story.chapterSortSwitch': '챕터의 순서를 변경합니다.',
    'workshop.story.prolog': '프롤로그',
    'workshop.story.chapter': '장 {sequence, number}',
    'workshop.work.includesAds': '작품에 광고나 제품 배치가 있나요?',
    'workshop.universe.forumSettings': '내부 우주 포럼 설정',
    'workshop.ratingAdjusted': '불만이 있어서 우리는 적절하다고 판단한 등급으로 당신의 등급을 조정해야 했습니다. 따라서 등급 변경이 현재 비활성화되었습니다.',
    'workshop.rating.disabled.sexualContent': '콘텐츠 경고에서 선정적인 콘텐츠를 선택했기 때문에 등급이 선정적(21세 이상)으로 잠겼습니다.',
    'workshop.contentWarnings.title': '콘텐츠 경고',
    'workshop.contentWarnings.description': '해당 콘텐츠 경고를 선택하여 잠재적으로 민감한 콘텐츠에 대해 독자에게 알립니다.',
    'workshop.contentWarnings.graphicViolence': '노골적인 폭력',
    'workshop.contentWarnings.graphicViolence.description': '신체적 상해, 유혈 사태, 절단 또는 불쾌감을 주거나 지나치게 노골적인 것으로 간주될 수 있는 기타 노골적인 폭력 묘사를 포함하되 이에 국한되지 않는 폭력 행위에 대한 자세한 묘사.',
    'workshop.contentWarnings.profanity': '욕설',
    'workshop.contentWarnings.profanity.description': '과도하거나 음란한 욕설 및 저주.',
    'workshop.contentWarnings.sensitiveContent': '민감한 콘텐츠',
    'workshop.contentWarnings.sensitiveContent.description': '고문, 노예제, 약물 남용, 정신 질환, 중독, 강간, 자해에 대한 언급 또는 경고 태그에 해당하지 않는 충격적이거나 성숙한 것으로 간주될 수 있는 기타 콘텐츠에 대한 설명이 포함될 수 없습니다. 이러한 콘텐츠는 미화되지 않습니다.',
    'workshop.contentWarnings.sexualContent': '성적인 콘텐츠',
    'workshop.contentWarnings.sexualContent.description': '노골적인 성적 콘텐츠(텍스트만 해당), 묘사적인 섹스 장면. 그러면 등급이 자동으로 노골적(21세 이상)으로 설정됩니다.',
    'workshop.selectCollaborator': '협력자 선택',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': '초안',
    'workshop.chapterStatus.scheduled': '예정됨',
    'workshop.chapterStatus.published': '게시됨',
    'workshop.story.continuedIn': '어떤 이야기가 이 이야기를 계속하나요?',
    'workshop.story.continuedPlaceholder': '이 우주에서 이야기를 선택하세요',
    'workshop.universe.isAIGenerated': '우주의 내용은 AI에 의해 생성되었습니까?',
    'workshop.universe.isAIGeneratedTooltip': '우주의 내용 중 일부가 AI에 의해 생성되었거나 도움을 받았는지 알려주세요. 우리는 이 정보를 적절한 라벨링을 위해 사용하며, AI 프로그램이 생성되는 방식에 따라 제한과 제약이 있을 수 있습니다.',
    'workshop.story.isAIGenerated': '이 이야기는 AI에 의해 생성되었습니까?',
    'workshop.story.isAIGeneratedTooltip': '이 이야기 중 일부가 AI에 의해 생성되었거나 도움을 받았는지 알려주세요. 우리는 이 정보를 적절한 라벨링을 위해 사용하며, AI 프로그램이 생성되는 방식에 따라 제한과 제약이 있을 수 있습니다.',
    'workshop.publicationAgreement.aria': '작품에 대한 게시 동의',
    'workshop.publicationAgreement.intro': '작품을 저희와 함께 게시하기로 선택하셔서 기쁩니다. 진행하기 전에 법적 측면에서의 의미를 이해하기 위해 게시 동의서를 확인해 주시기 바랍니다.',
    'workshop.sortChapters': '정렬 순서:',
    'workshop.sortChapters.ascending': '처음부터',
    'workshop.sortChapters.descending': '최신 순서로',
    'workshop.sortChapters.aria': '챕터 목록을 어떤 방식으로 정렬할지 선택하세요',
    'workshop.hiatus.btn': '이야기 상태를 휴지로 변경합니다',
    'workshop.cancelled.btn': '이야기 상태를 취소됨으로 변경합니다',
    'workshop.complete.btn': '이야기 상태를 완료됨으로 변경합니다',
    'workshop.statusChange.modalTop': '상태를 변경하시겠습니까',
    'workshop.statusName.hiatus': '휴지',
    'workshop.statusName.cancelled': '취소됨',
    'workshop.statusName.completed': '완료됨',
    'workshop.statusExplain.hiatus1': '휴지란 일시적으로 이야기에 대한 작업을 중단한다는 것을 의미합니다. 독자들에게 다음 몇 주 또는 몇 개월 동안 새로운 업데이트를 기대하지 말아야 함을 알려줍니다.',
    'workshop.statusExplain.hiatus2': '휴지 상태는 새로운 챕터를 게시하면 자동으로 해제됩니다. 또는 직접 변경할 수도 있습니다.',
    'workshop.statusExplain.hiatus3': '이야기를 6개월 동안 휴지 상태로 유지하면 자동으로 이 이야기를 취소됨으로 표시합니다.',
    'workshop.statusExplain.cancelled1': '이야기 작업을 계속할 수 없다는 것을 알게 되어 안타깝습니다. 그러나 독자들에게 알려주려는 의지에는 기쁨을 느낍니다.',
    'workshop.statusExplain.cancelled2': '이야기를 취소하면 독자들에게 새로운 업데이트를 기대하지 말아야 함을 알려줍니다.',
    'workshop.statusExplain.cancelled3': '항상 챕터를 게시하거나 상태를 변경하여 이를 되돌릴 수 있습니다.',
    'workshop.statusExplain.finished1': '축하합니다! 모든 열심히 한 작업 끝에 놀라운 여정의 끝에 도달했습니다. 이야기는 지금 끝나지만, 미래에 더 많은 이야기가 있기를 바라며, 지금은 휴식을 즐기세요.',
    'workshop.statusExplain.finished2': '이야기를 완료로 표시하면 독자들에게 이야기가 끝났음을 알려줍니다. 새로운 챕터를 추가하지 않아야 하지만, 추가적인 에필로그를 모든 캐릭터에게 추가하는 것은 나쁜 생각이 아닙니다.',
    'workshop.statusExplain.finished3': '이 상태를 취소할 수는 있지만, 가능하다면 이야기가 계속될 경우 새로운 이야기를 시작하는 것이 좋을 수도 있습니다.',
    'workshop.status.goActive': '이야기를 다시 활성화합니다',
    'workshop.statusChangeEmail.storyIntro': '귀하의 이야기에 대해 알려드리고자 합니다:',
    'workshop.statusChangeEmail.hiatusTitle': '당신의 이야기 상태가 자동으로 휴지 상태로 설정되었습니다',
    'workshop.statusChangeEmail.hiatusIntro': '비활동으로 인해 당신의 이야기 상태가 자동으로 휴지 상태로 설정되었습니다.',
    'workshop.statusChangeEmail.hiatusWhy': '6개월 이상 새로운 챕터를 게시하지 않아 자동으로 휴지 상태로 전환되었습니다.',
    'workshop.statusChangeEmail.hiatusWhatFollows': '새로운 챕터를 게시하면 이 상태는 자동으로 해제됩니다. 다음 6개월 동안 새로운 챕터를 게시하지 않으면 이야기를 자동으로 취소로 설정합니다.',
    'workshop.statusChangeEmail.cancellationIntro': '당신의 이야기 상태가 자동으로 취소로 설정되었습니다.',
    'workshop.statusChangeEmail.cancellationWhy': '6개월 전에 스토리가 일시 중단으로 설정된 이후 새 챕터를 게시하지 않았기 때문에 이런 일이 발생했습니다. 1년 동안 활동이 없으면 자동으로 스토리를 취소로 설정하여 독자가 어떤 스토리가 활성화되어 있는지 알 수 있도록 합니다.',
    'workshop.statusChangeEmail.cancellationWhatFollows': '새로운 챕터를 게시하면 이 상태는 자동으로 해제됩니다. 이야기에 더 이상 작업할 계획이 없다면 할 일은 없습니다.',
    'workshop.startCreating': '만들기 시작',
    'workshop.ownWork': '자신의 작품',
    'workshop.list.thumbs': '썸네일 목록',
    'workshop.list.list': '간략한 목록',
    'workshop.fanfiction.new': '새로운 팬픽션 만들기',
    'workshop.videoTrailerLink': '비디오 예고편 링크',
    'workshop.videoTrailerPlayerTitle': '이야기 비디오 예고편 플레이어',
    'workshop.videoTrailer.supportedPlaftorms': '우리는 Youtube, Vimeo 및 Odysee를 지원합니다',
    'workshop.videoTrailer.rumble': '우리는 Rumble도 지원하지만, IFRAME URL을 복사하는 것을 기억하세요.',
    'workshop.videoTrailer.suggestPlatforms': '비디오 플랫폼이 누락되었나요? <a>피드백</a>을 통해 알려주세요!',
    'workshop.cover.edit': '표지 변경',
    'workshop.collaborator.leave': '프로젝트에서 나가기',
    'workshop.collaborator.leaveTitle': '탈퇴를 확인해주세요 {workName}',
    'workshop.collaborator.leaveExplained': '프로젝트를 탈퇴하면 모든 액세스 권한, 연결 권한 및 권한을 잃게 됩니다. 이 모든 것이 무엇을 의미하는지 잘 모르겠다면 이 버튼을 클릭하고 싶지 않으셨을 것입니다.',
    'workshop.collaborators.leftInfo': '왼쪽 {date, date}',
    'workshop.collaborators.removedInfo': '삭제됨 {date, date}',
    'workshop.aiGeneratedAdjusted': '이 콘텐츠의 AI 생성 상태는 사용자 신고에 따라 관리자에 의해 조정되었으며 변경할 수 없습니다.',
    'workshop.theWay.authorProgress': '저자 진행 상황',
    'workshop.universe.preventPublishing': '스토리 게시 방지',
    'workshop.universe.preventPublishingTooltip': '활성화하면 이 유니버스에서는 어떤 스토리도 게시할 수 없습니다. 아직 개발 중인 유니버스나 비공개 전용 유니버스에서 유용하게 사용할 수 있습니다.',
    'workshop.story.preventPublishing': '게시 방지',
    'workshop.story.preventPublishingTooltip': '이 옵션을 활성화하면 이 스토리를 게시할 수 없습니다. 아직 개발 중인 스토리나 비공개로만 사용할 수 있는 스토리에 유용합니다.',
    'workshop.story.preventPublishingTooltipUniverse': '유니버스에서 게시 금지 설정이 활성화되어 있기 때문에 게시가 금지됩니다.',
    'workshop.revisions.new.public.disabled': '스토리 설정에서 게시 금지가 활성화된 상태에서는 게시할 수 없습니다.',
    'workshop.publishing.restricted': '윤리강령 위반으로 인해 귀하의 게시 기능이 비활성화되었습니다.',
    'workshop.story.buyingSettings': '판매 설정',
    'workshop.story.delete.modalAria': '스토리 삭제를 위한 확인 모달',
    'workshop.story.delete.warning': '"{title}"를 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
    'workshop.story.delete.button': '스토리 삭제',
    'workshop.story.private.universeExplain': '이 이야기의 세계는 비공개이기 때문에 비공개입니다.',
    'workshop.story.makePublicWithUniverse.button': '스토리 및 유니버스 공개하기',
    'workshop.universe.makePublic.only.button': '유니버스 공개 전용 설정',
    'workshop.universe.makePublic.only.modalAria': '유니버스만 공개하기 위한 확인 모달',
    'workshop.universe.makePublic.only.warning': '이렇게 하면 우주만 공개됩니다. 이 유니버스의 스토리는 개별적으로 공개될 때까지 비공개로 유지됩니다.',
    'workshop.universe.makePublic.withStories.button': '유니버스 및 모든 스토리 공개',
    'workshop.universe.makePublic.withStories.modalAria': '유니버스 및 모든 스토리를 공개하기 위한 확인 모달',
    'workshop.universe.makePublic.withStories.warning': '이렇게 하면 유니버스 및 연결된 모든 스토리가 공개됩니다.',
    // Chapter deletion
    'workshop.chapter.delete.modalAria': '챕터 삭제를 위한 확인 모달',
    'workshop.chapter.delete.warning': '"{title}"를 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
    'workshop.chapter.delete.button': '장 삭제',
    'workshop.chapter.delete.deleting': '삭제...',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'AI 생성 콘텐츠',
    'workshop.chapter.aiGenerated.tooltip': '이 챕터에 AI 생성 콘텐츠가 포함된 것으로 표시하기',
    'workshop.chapter.aiGenerated.description': '이 장에는 AI의 도움을 받아 생성된 콘텐츠가 포함되어 있습니다.',
    'workshop.chapter.aiModel': 'AI 모델',
    'workshop.chapter.aiModel.tooltip': '콘텐츠 생성에 사용된 AI 모델을 선택합니다.',
    'workshop.chapter.aiModel.custom': '사용자 지정',
    'workshop.chapter.aiModel.custom.placeholder': 'AI 모델의 이름을 입력합니다.',
    'workshop.chapter.aiGenerated.locked': 'AI 콘텐츠 표시는 모더레이션 팀에서 조정했기 때문에 변경할 수 없습니다.',
    'workshop.monetization.aiNotEligible': 'AI가 생성한 콘텐츠는 수익 창출 대상이 아닙니다.',
    'workshop.timer.settings': 'Timer Settings',
    'workshop.timer': 'Timer',
    'workshop.timer.type': 'Type',
    'workshop.timer.timer': 'Timer',
    'workshop.timer.countdown': 'Countdown',
    'workshop.timer.pomodoro': 'Pomodoro',
    'workshop.timer.mode': 'Mode',
    'workshop.timer.regular': 'Regular',
    'workshop.timer.improved': 'Improved',
    'workshop.timer.duration': 'Duration (min)',
    'workshop.timer.workDuration': 'Work (min)',
    'workshop.timer.breakDuration': 'Break (min)',
    'workshop.timer.breakType': 'Break Type',
    'workshop.timer.softBreak': 'Soft Break',
    'workshop.timer.hardBreak': 'Hard Break',
    'workshop.timer.break': 'Break',
    'workshop.timer.breakTime': 'Break Time!',
    'workshop.timer.breakMessage': 'Take a moment to rest. Click anywhere to dismiss.',
    'workshop.timer.pause': 'Pause',
    'workshop.timer.resume': 'Resume',
    'workshop.timer.stop': 'Stop',
    'workshop.timer.start': 'Start',
    'workshop.timer.tabInactive': 'Timer paused - switch back to tab to continue',
    // Timer descriptions
    'workshop.timer.type.timer.desc': 'Simple stopwatch that starts at 0:00 and counts upward. Perfect for tracking total writing time in a session or seeing how long you\'ve been working continuously. Never ends automatically - you control when to stop.',
    'workshop.timer.type.countdown.desc': 'Countdown timer that starts from your set duration and counts down to zero. Great for time-boxed writing sessions, word sprints, or when you want to work for a specific amount of time before taking a break.',
    'workshop.timer.type.pomodoro.desc': 'Structured productivity technique: 25-minute focused work sessions alternating with 5-minute breaks. After 4 cycles, takes a longer 15-30 minute break. Scientifically proven to improve focus and prevent burnout.',
    'workshop.timer.mode.regular.desc': 'Timer runs continuously regardless of your activity. Best for disciplined writers who want to track time even when researching, editing, or taking short breaks. Timer keeps going when you switch tabs or stop typing.',
    'workshop.timer.mode.improved.desc': 'Smart timer that automatically pauses when you switch browser tabs. Perfect for focused writing sessions where you want accurate tracking of actual writing time, not total time spent on the page.',
    'workshop.timer.breakType.soft.desc': 'Gentle reminder approach: Shows a small notification when break time starts. You can choose to continue working if you\'re in \'the zone\' or take the break. Good for flexible writers who sometimes need to extend productive sessions.',
    'workshop.timer.breakType.hard.desc': 'Strict enforcement: Displays a full-screen modal that prevents further input until the break timer completes. Forces you to step away from the keyboard. Ideal for writers who struggle with self-discipline or workaholics who need enforced rest periods.',
    'workshop.timer.duration.timer.desc': 'How long you plan to write in this session. Start with 25-50 minutes for focused work, or set longer sessions (2-4 hours) for deep writing days.',
    'workshop.timer.duration.countdown.desc': 'Target writing time before the timer ends. Try 25 minutes for focused sprints, 45-60 minutes for substantial work sessions, or 90 minutes for creative deep dives.',
    'workshop.timer.workDuration.desc': 'Length of focused work sessions. Traditional Pomodoro uses 25 minutes. Try 15-20 minutes if you find it hard to concentrate for longer periods, or 45-50 minutes for experienced writers who can maintain deep focus.',
    'workshop.timer.breakDuration.desc': 'Rest period between work sessions. Standard is 5 minutes for short breaks. Use 10-15 minutes for longer breaks that allow you to step away from your desk, stretch, or get a drink. Every 4th break is automatically longer (2-3x duration).',
    'workshop.llmstxt': 'AI Access',
    'workshop.llmstxt.blocked': 'Blocked - LLMs cannot access your content',
    'workshop.llmstxt.limited': '제한 - LLM은 메타 데이터에만 액세스할 수 있습니다.',
    'workshop.llmstxt.free': 'Free - LLMs can access your content for free',
    'workshop.llmstxt.paid': 'Paid - LLMs can access your content for a fee (coming soon)',
    'workshop.ai.llmstxt.generate': 'Generate LLMs.txt',
    'workshop.ai.llmstxt.generating': 'Generating LLMs.txt...',
    'workshop.ai.llmstxt.download': 'Download LLMs.txt',
    'workshop.ai.llmstxt.title': 'Texts for AI services',
    'workshop.ai.agent.title': 'Assistant',
    'workshop.ai.llmstxt.story-info': 'Story Info LLMs.txt',
    'workshop.ai.llmstxt.full-content': 'Full Content LLMs.txt',
    'workshop.ai.llmstxt.info': 'Info LLMs.txt - Basic information for AI',
    'workshop.ai.llmstxt.infoShort': 'Basic information',
    'workshop.ai.llmstxt.full': 'Content LLMs.txt - Full content for AI',
    'workshop.ai.llmstxt.fullShort': 'Full content'
};