export default {
    'challenges.current': 'Praegused väljakutsed',
    'challenges.wordcount.goal': 'Sihtsõnade arv',
    'challenges.wordcount.dailygoal': 'Sihtmärgiks seatud päevane sõnade arv',
    'challenges.wordcount.today': 'Täna kirjutatud',
    'challenges.wordcount.total': 'Kokku kirjutatud sõnad',
    'challenges.wordcount.remaining': 'Jäänud sõnad',
    'challenges.wordcount.daysleft': 'Jäänud päevad',
    'challenges.wordcount.currentDay': 'Praegune päev',
    'challenges.wordcount.average': 'Keskmine sõnade arv päevas',
    'challenges.wordcount.finishOn': 'Praeguse kiiruse juures lõpetate',
    'challenges.wordcount.finishOnTime': 'Sõnu tuleb kirjutada päevas, et õigeaegselt lõpetada',
    'challenges.wordcount.graph.day': 'Päev {day}',
    'challenges.underway': 'See väljakutse on juba käimas.',
    'challenges.targetWords': 'Kokku seatud sihtsõnade arv',
    'challenges.startDate': 'Alguskuupäev',
    'challenges.endDate': 'Lõppkuupäev',
    'challenges.future': 'Tulevased väljakutsed',
    'challenges.future.wordcount': 'Wordcount challenge staring on {startDate, date, short} with goal of {target, number} by {endDate, date, short}.',
    'challenges.future.nanowrimo': 'NaNoWriMo väljakutse on valmis.',
    'challenges.wordcount': 'Sõnade arv',
    'challenges.wordcount.desc': `Set yourself a goal of how many words you want to write this month for this {type, select,
    story {story}
    universe {universe}
    other {}
  }.`,
    'challenges.wordcount.select': 'Mitu sõna soovite endale väljakutseks seada?',
    'challenges.start': 'Alusta väljakutset',
    'challenges.report': 'Aruanne',
    'challenges.victory': 'Õnnitlused! Olete selle väljakutse lõpetanud.',
    'challenges.defeat': 'Kahjuks te ei lõpetanud seda väljakutset.',
    'challenges.baseline': 'The current wordcount for this story is {wordcount, number}, this will be the starting point.',
    // NaNoWriMo
    'nanowrimo.full': 'Rahvusvaheline romaani kirjutamise kuu',
    'nanowrimo.site': 'NaNoWriMo ametlik veebisait',
    'nanowrimo.settings': 'NaNoWriMo konto',
    'nanowrimo.username': 'NaNoWriMo kasutajanimi',
    'nanowrimo.key': 'Salajane võti',
    'nanowrimo.key.get': 'Hankige oma NaNoWriMo võti.',
    'nanowrimo.key.get.notice': 'Selle nägemiseks peate olema sisse logitud.',
    'nanowrimo.ongoing': 'on täies hoos! {countdown} päeva veel!',
    'nanowrimo.startsin': `algab {countdown, plural,
      one {1 päeva}
      other {# päeva}
    }! Valmistu!`,
    'nanowrimo.isover': 'NaNoWriMo on läbi. Näeme järgmisel aastal!',
    'nanowrimo.select': 'Märgi see lugu NaNoWriMo jaoks.',
    'nanowrimo.baseline': 'Kui NaNoWriMo algab, võtab see praeguse sõnade arvu ja kasutab seda alusena, millest kõik täiendavad sõnad võetakse osana NaNoWriMo-st.',
    'nanowrimo.victory': 'Õnnitlused! Sa võitsid NaNoWriMo!',
    'nanowrimo.challenge': 'NaNoWriMo väljakutse',
    'nanowrimo.description': 'Väljakutse on kirjutada romaan, mis koosneb {words, number} sõnast novembris.',
    'nanowrimo.error.usernotfound': 'Kasutajanime ei leitud NaNoWriMo serveritest.',
    'nanowrimo.error.nobook': 'Raamatut ei leitud. Palun veendu, et oled loonud oma raamatu NaNoWriMo-s.',
    'nanowrimo.error.wordcount': 'Ei õnnestunud sõnade arvu seadistamine NaNoWrimo-s, palun kontrolli oma autentimisandmeid ja proovi uuesti.',
    'nanowrimo.connected': 'Oled märkinud selle loo NaNoWriMo jaoks.',
    'nanowrimo.connected.other': 'Oled juba ühendanud teise loo.'
};