export default {
    'encyclopedia.add': 'Lisa uus kirje',
    'encyclopedia.browse': 'Sirvi entsüklopeediat',
    'encyclopedia.search': 'Otsi entsüklopeediast',
    'canvas.toolbar.add': 'Add:',
    'canvas.toolbar.text': 'Text',
    'canvas.toolbar.link': 'Link',
    'canvas.toolbar.group': 'Group',
    'canvas.toolbar.entry': 'Entry',
    'canvas.encPicker.title': 'Pick an encyclopedia entry',
    'canvas.encPicker.search': 'Search entries…',
    'canvas.dialog.pickEntry': 'Pick encyclopedia entry',
    'canvas.node.link': 'Link',
    'canvas.node.encEntry': 'Entry',
    'canvas.entry.open': 'Double-click to open entry',
    'encyclopedia.back.universe': 'Tagasi universumi lehele',
    'encyclopedia.back.workshop': 'Tagasi töötuppa',
    'encyclopedia.categories': 'Kategooriad',
    'encyclopedia.groups': 'Grupid',
    'encyclopedia.category.character': 'Tegelased',
    'encyclopedia.category.event': 'Sündmused',
    'encyclopedia.category.group': 'Grupid',
    'encyclopedia.category.item': 'Esemed',
    'encyclopedia.category.location': 'Asukohad',
    'encyclopedia.category.other': 'Muu',
    'encyclopedia.category.state': 'Olekud',
    'encyclopedia.category.governments': 'Valitsused',
    'encyclopedia.category.languages': 'Keeled',
    'encyclopedia.category.creatures': 'Olendid',
    'encyclopedia.category.deity': 'Jumalad',
    'encyclopedia.category.religions': 'Religioonid',
    'encyclopedia.category.flora': 'Taimestik',
    'encyclopedia.category.magic': 'Maagia',
    'encyclopedia.category.planets': 'Planeedid',
    'encyclopedia.category.species': 'Liigid',
    'encyclopedia.category.technologies': 'Tehnoloogiad',
    'encyclopedia.category.families': 'Perekonnad',
    'encyclopedia.category.jobs': 'Töökohad',
    'encyclopedia.category.lore': 'Lore',
    'encyclopedia.category.vehicles': 'Sõidukid',
    'encyclopedia.category.diseases': 'Haigused',
    'encyclopedia.category.traditions': 'Traditsioonid',
    'encyclopedia.category.sports': 'Sport',
    'encyclopedia.category.food': 'Toiduained',
    'encyclopedia.category.landmarks': 'Vaatamisväärsused',
    'encyclopedia.category.buildings': 'Hooned',
    'encyclopedia.category.schools': 'Koolid',
    'encyclopedia.category.continents': 'Kontinendid',
    'encyclopedia.category.villages': 'Külad',
    'encyclopedia.category.towns': 'Linnad',
    'encyclopedia.category.cities': 'Linnad',
    'encyclopedia.category.settlements': 'Arveldused',
    'encyclopedia.category.countries': 'Riigid',
    'encyclopedia.search.found': '{results, plural,\n    =0 {No related entries}\n    one {1 related entry}\n    other {# related entries}\n  } found.',
    'encyclopedia.help.text': 'Kasuta vasakul olevat menüüd entsüklopeedia üksuste vahel navigeerimiseks. Kui valid ühe üksuse, kuvatakse see teksti asemel.',
    'encyclopedia.help.sidebar': 'Küljeriba tööriistakast',
    'encyclopedia.help.sidebar.text': 'Tere tulemast teie loo juurde! See külgriba võimaldab teile hõlpsat juurdepääsu kõigile teie looga seotud ressurssidele. Vaadake ülalpool olevaid ikoone, et näha viimaseid kommentaare, oma märkmeid, otsida oma entsüklopeediast, sirvida ja lisada uusi kirjeid oma entsüklopeediasse. Kui soovite lisada loo tekstist sissekande juurde ühenduse, valige tekst, kuhu soovite selle paigutada, ja klõpsake seejärel nupule "Ühenda". Seejärel palutakse teil leida ja valida kirje.',
    'encyclopedia.intro': 'Tere tulemast {universe} entsüklopeediasse.',
    'encyclopedia.add.title': 'Lisa uus kirje entsüklopeediasse',
    'encyclopedia.add.heading': 'Mida soovid lisada?',
    'encyclopedia.add.moresoon': 'Rohkem kategooriaid tulekul!',
    'encyclopedia.create': 'Create new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {villages}\n    towns {towns}\n    cities {cities}\n    settlements {settlement}\n    countries {country}\n  }',
    'encyclopedia.create.header': 'Creating a new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {village}\n    towns {town}\n    cities {city}\n    settlements {settlement}\n    countries {country}\n  } in {universe}',
    'encyclopedia.entry.category': 'Entry category: {category, select,\n    character {Character}\n    event {Event}\n    group {Group}\n    item {Item}\n    location {Location}\n    other {Note}\n    state {State}\n    governments {Government}\n    languages {Language}\n    creatures {Creature}\n    deity {Deity}\n    religions {Religion}\n    flora {Flora}\n    magic {Magic}\n    planets {Planet}\n    species {Specie}\n    technologies {Technology}\n    families {Family}\n    jobs {Job}\n    lore {Lore}\n    vehicles {Vehicle}\n    diseases {Disease}\n    traditions {Tradition}\n    food {Food}\n    sports {Sport}\n    landmarks {Landmark}\n    buildings {Building}\n    schools {School}\n    continents {Continent}\n    villages {Village}\n    towns {Town}\n    cities {City}\n    settlements {Settlement}\n    countries {Country}\n  }',
    'encyclopedia.entry.category.legend': 'Kategooria',
    'encyclopedia.fields.add': 'Lisa uus väli',
    'encyclopedia.fields.text': 'Definitsioon',
    'encyclopedia.fields.textarea': 'Tekst',
    'encyclopedia.fields.connection': 'Ühendus',
    'encyclopedia.fields.time': 'Aeg',
    'encyclopedia.fields.image': 'Pilt',
    'encyclopedia.fields.canvas': 'Canvas',
    'encyclopedia.visibility': 'Nähtavus',
    'encyclopedia.public': 'Avalik',
    'encyclopedia.private': 'Privaatne',
    'encyclopedia.container': 'Konteiner',
    'encyclopedia.container.desc': 'Tehke see kirje uue kirjete rühma konteineriks. See peidab selle kategooriate loetelust.',
    'encyclopedia.entry.name': 'Kirje nimi',
    'encyclopedia.summary': 'Kokkuvõte',
    'encyclopedia.summary.desc': 'See on kokkuvõte, mis on ainus esialgne teave, mida lugejale kuvatakse.',
    'encyclopedia.parent': 'Vanemkirje',
    'encyclopedia.related': 'Seotud kirjed',
    'encyclopedia.errors.tags': 'Saad lisada ainult 10 silti ühe kirje kohta.',
    'encyclopedia.field.private': 'Privaatne väli',
    'encyclopedia.spoiler.label': 'Contains spoilers for {story}',
    'encyclopedia.spoiler.chapterLabel': 'Spoiler for {story}, Chapter {chapter}',
    'encyclopedia.spoiler.multipleLabel': 'Contains spoilers for multiple stories',
    'encyclopedia.spoiler.generic': 'Contains spoilers',
    'encyclopedia.spoiler.reveal': 'Reveal spoiler',
    'encyclopedia.spoiler.scope.story': 'Story',
    'encyclopedia.spoiler.scope.story.placeholder': 'Select story',
    'encyclopedia.spoiler.scope.chapter': 'Chapter number',
    'encyclopedia.spoiler.scope.remove': 'Remove spoiler scope',
    'encyclopedia.spoiler.scope.add': 'Mark as spoiler',
    'encyclopedia.spoiler.scope.addStory': 'Add story',
    'encyclopedia.spoiler.scope.removeStory': 'Remove story',
    'encyclopedia.spoiler.scope.manage': 'Manage spoiler scope',
    'encyclopedia.spoiler.scope.manageShort': 'Spoiler',
    'encyclopedia.spoiler.scope.summary': '{count, plural, one {# story} other {# stories}}',
    'encyclopedia.spoiler.scope.chapterSummary': 'Chapter {chapter}',
    'encyclopedia.spoiler.scope.description': 'Mark this field as a spoiler. Readers who haven\'t reached the required point in these stories will see the content blurred.',
    'encyclopedia.spoiler.scope.storyChapterHint': 'Choose the chapter readers must reach before this field is shown by default.',
    'encyclopedia.spoiler.scope.storyCompletion': 'Readers must finish this story before this field is shown by default.',
    'encyclopedia.spoiler.scope.noStories': 'No stories from this universe are available yet.',
    'encyclopedia.spoiler.scope.privatePrecedence': 'Private fields are never sent to readers, so spoiler scope has no effect while the field is private.',
    'encyclopedia.ft.indev': 'See valik on arendamisel.',
    'encyclopedia.connections.remove': 'Eemalda ühendus',
    'encyclopedia.connections.extra': 'Lisainfo',
    'encyclopedia.connections.existing': 'Olemasolev sissekanne',
    'encyclopedia.connections.existing.abbr': 'EE',
    'encyclopedia.cover': 'Kaatrid pilt',
    'encyclopedia.translation.title': 'Tere tulemast {universe} universumi tõlkesse!',
    'encyclopedia.translation.desc': 'Selle entsüklopeedia liidest kasutatakse tõlkimiseks keelde {language}. Alustamiseks valige vasakul olevast loendist olemasolevad kirjed.',
    'encyclopedia.welcome.totalEntries': 'There {totalEntries, plural, \n    zero {are no entries}\n    one {is one entry}\n    other {are # entries}\n  } in this universe.',
    'encyclopedia.settings.title': 'Entsüklopeedia seaded',
    'encyclopedia.settings.categoriesDesc': 'Lülitage sisse ja välja kategooriad, mida soovite entsüklopeedias kasutada.',
    'encyclopedia.settings.introText': 'Tervitussõnum, mis kuvatakse pärast universumi kirjeldust.',
    'encyclopedia.fields.placeholder': 'Välja nimi',
    'encyclopedia.fields.delete': 'Kustuta väli',
    'encyclopedia.timeOption.fictionalDate': 'Fiktiivne kuupäev',
    'encyclopedia.timeOption.fictionalTime': 'Fiktiivne aeg',
    'encyclopedia.timeOption.fictionalDateTime': 'Fiktiivne kuupäev ja aeg',
    'encyclopedia.timeOption.date': 'Kuupäev',
    'encyclopedia.timeOption.time': 'Aeg',
    'encyclopedia.timeOption.dateTime': 'Kuupäev ja aeg',
    'encyclopedia.settings.groupByCategories': 'Kaasa kategooriad rühma loendisse',
    'encyclopedia.menuOpen': 'Ava entsüklopeedia menüü',
    'encyclopedia.menuClose': 'Sulge entsüklopeedia menüü',
    'encyclopedia.menuAria': 'Entsüklopeedia menüü',
    'enc.newField': 'Uus väli',
    'enc.entries.limit': 'You currently have {value, number} out of {max, plural,\n    =0 {unlimited}\n    other {{max, number}}\n  } entries.',
    'enc.entries.limitReached': 'Olete jõudnud oma praeguse tellimuse jaoks lubatud entsüklopeedia sisestuste maksimumini.',
    'encyclopedia.pronunciation.title': 'Hääldus',
    'encyclopedia.wip.abbreviation': 'TÖÖ',
    'encyclopedia.wip.full': 'Töö käib',
    'encyclopedia.settings.templateLegend': 'Mallide universum',
    'encyclopedia.settings.templateDescription': 'Luba selle entsüklopeedia sisu kopeerimine teistesse universumitesse. See on parim variant, kui sul pole lugusid ja lood lihtsalt malli teiste kasutamiseks.',
    'encyclopedia.settings.templateCheckbox': 'See on malli universum',
    'encyclopedia.templateCopy.modalTitle': 'Kopeeri entsüklopeedia sisu',
    'encyclopedia.templateCopy.description': 'Kopeeri selle entsüklopeedia sisu oma universumisse, et seda rikastada.',
    'encyclopedia.templateCopy.targetUniverse': 'Universum, kuhu kopeerida',
    'encyclopedia.templateCopy.finished': 'Kopeerimine lõpetatud',
    'encyclopedia.templateCreateUniverse.modalTitle': 'Universumi loomine mallist',
    'encyclopedia.templateCreateUniverse.description': 'Looge uus universum selle malli eelkülastatud entsüklopeedia sisuga. Teie universum jääb privaatseks, kuni otsustate selle avalikustada.',
    'encyclopedia.templateCreateUniverse.success': 'Universum loodud edukalt! Ümbersuunamine...',
    'encyclopedia.pronunciation.audio.play': 'Mängi hääldus',
    'encyclopedia.pronunciation.guide': 'Kasutage võimaluse korral <ipaLink>IPA märkimist</ipaLink>. Web Speech API hääldus on parim võimalik; vt <webSpeechLink>MDNi dokumente</webSpeechLink>.',
    'encyclopedia.templateField.born': 'Born',
    'encyclopedia.templateField.died': 'Died',
    'encyclopedia.templateField.race': 'Race',
    'encyclopedia.templateField.gender': 'Gender',
    'encyclopedia.templateField.partners': 'Partners',
    'encyclopedia.templateField.parents': 'Parents',
    'encyclopedia.templateField.children': 'Children',
    'encyclopedia.templateField.associated-with': 'Associated with',
    'encyclopedia.templateField.biography': 'Biography',
    'encyclopedia.templateField.physical-appearance': 'Physical appearance',
    'encyclopedia.templateField.type-of-event': 'Type of event',
    'encyclopedia.templateField.preceding-events': 'Preceding events',
    'encyclopedia.templateField.following-events': 'Following events',
    'encyclopedia.templateField.leadup': 'Leadup',
    'encyclopedia.templateField.description': 'Description',
    'encyclopedia.templateField.aftermath': 'Aftermath',
    'encyclopedia.templateField.members': 'Members',
    'encyclopedia.templateField.locations': 'Locations',
    'encyclopedia.templateField.events': 'Events',
    'encyclopedia.templateField.vision': 'Vision',
    'encyclopedia.templateField.mission': 'Mission',
    'encyclopedia.templateField.description-of-the-organization': 'Description of the organization',
    'encyclopedia.templateField.history': 'History',
    'encyclopedia.templateField.owners': 'Owners',
    'encyclopedia.templateField.function': 'Function',
    'encyclopedia.templateField.content': 'Content',
    'encyclopedia.templateField.population': 'Population',
    'encyclopedia.templateField.culture': 'Culture',
    'encyclopedia.templateField.governments': 'Governments',
    'encyclopedia.templateField.religions-believes': 'Religions & believes',
    'encyclopedia.templateField.languages': 'Languages',
    'encyclopedia.templateField.geography': 'Geography',
    'encyclopedia.templateField.founding': 'Founding',
    'encyclopedia.templateField.notable-events': 'Notable events',
    'encyclopedia.templateField.notes': 'Notes',
    'encyclopedia.templateField.type-of-government': 'Type of government',
    'encyclopedia.templateField.structure': 'Structure',
    'encyclopedia.templateField.power-structure': 'Power structure',
    'encyclopedia.templateField.source-of-power': 'Source of power',
    'encyclopedia.templateField.laws': 'Laws',
    'encyclopedia.templateField.ideology': 'Ideology',
    'encyclopedia.templateField.internal-politics': 'Internal politics',
    'encyclopedia.templateField.external-politics': 'External politics',
    'encyclopedia.templateField.leading-figures': 'Leading figures',
    'encyclopedia.templateField.groups': 'Groups',
    'encyclopedia.templateField.military': 'Military',
    'encyclopedia.templateField.items': 'Items',
    'encyclopedia.templateField.typology': 'Typology',
    'encyclopedia.templateField.dialectics': 'Dialectics',
    'encyclopedia.templateField.phonology': 'Phonology',
    'encyclopedia.templateField.grammar': 'Grammar',
    'encyclopedia.templateField.numbers': 'Numbers',
    'encyclopedia.templateField.quantifiers': 'Quantifiers',
    'encyclopedia.templateField.private-notes': 'Private notes',
    'encyclopedia.templateField.type': 'Type',
    'encyclopedia.templateField.notable-features': 'Notable features',
    'encyclopedia.templateField.traits': 'Traits',
    'encyclopedia.templateField.habitat': 'Habitat',
    'encyclopedia.templateField.food-sources': 'Food sources',
    'encyclopedia.templateField.reproduction': 'Reproduction',
    'encyclopedia.templateField.cultural-significance': 'Cultural significance',
    'encyclopedia.templateField.related-creatures': 'Related creatures',
    'encyclopedia.templateField.religion': 'Religion',
    'encyclopedia.templateField.other-names': 'Other names',
    'encyclopedia.templateField.appearance': 'Appearance',
    'encyclopedia.templateField.related-to': 'Related to',
    'encyclopedia.templateField.symbolism': 'Symbolism',
    'encyclopedia.templateField.rituals': 'Rituals',
    'encyclopedia.templateField.origin': 'Origin',
    'encyclopedia.templateField.notable-figures': 'Notable figures',
    'encyclopedia.templateField.deities': 'Deities',
    'encyclopedia.templateField.artifacts': 'Artifacts',
    'encyclopedia.templateField.believes': 'Believes',
    'encyclopedia.templateField.traditions': 'Traditions',
    'encyclopedia.templateField.spread': 'Spread',
    'encyclopedia.templateField.classification': 'Classification',
    'encyclopedia.templateField.features': 'Features',
    'encyclopedia.templateField.produce': 'Produce',
    'encyclopedia.templateField.ecosystem': 'Ecosystem',
    'encyclopedia.templateField.effect': 'Effect',
    'encyclopedia.templateField.alignment': 'Alignment',
    'encyclopedia.templateField.requirements': 'Requirements',
    'encyclopedia.templateField.size': 'Size',
    'encyclopedia.templateField.length-of-day': 'Length of day',
    'encyclopedia.templateField.length-of-night': 'Length of night',
    'encyclopedia.templateField.length-of-cycle': 'Length of cycle',
    'encyclopedia.templateField.moons': 'Moons',
    'encyclopedia.templateField.nearby-stellar-bodies': 'Nearby stellar bodies',
    'encyclopedia.templateField.climate': 'Climate',
    'encyclopedia.templateField.weather': 'Weather',
    'encyclopedia.templateField.natural-resources': 'Natural resources',
    'encyclopedia.templateField.notable-locations': 'Notable locations',
    'encyclopedia.templateField.inhabitans': 'Inhabitans',
    'encyclopedia.templateField.looks': 'Looks',
    'encyclopedia.templateField.production': 'Production',
    'encyclopedia.templateField.use': 'Use',
    'encyclopedia.templateField.related': 'Related',
    'encyclopedia.templateField.location': 'Location',
    'encyclopedia.templateField.significance': 'Significance',
    'encyclopedia.templateField.associated-events': 'Associated events',
    'encyclopedia.templateField.associated-figures': 'Associated figures',
    'encyclopedia.templateField.access-restrictions': 'Access restrictions',
    'encyclopedia.templateField.cultural-importance': 'Cultural importance',
    'encyclopedia.templateField.founded': 'Founded',
    'encyclopedia.templateField.government': 'Government',
    'encyclopedia.templateField.defenses': 'Defenses',
    'encyclopedia.templateField.connected-settlements': 'Connected settlements',
    'encyclopedia.templateField.family-motto': 'Family Motto',
    'encyclopedia.templateField.founding-date': 'Founding Date',
    'encyclopedia.templateField.ethos': 'Ethos',
    'encyclopedia.templateField.family-reputation': 'Family Reputation',
    'encyclopedia.templateField.family-branches': 'Family Branches',
    'encyclopedia.templateField.notable-vassals-retainers': 'Notable vassals/retainers',
    'encyclopedia.templateField.skills-required': 'Skills required',
    'encyclopedia.templateField.pay-salary': 'Pay/Salary',
    'encyclopedia.templateField.associated-locations': 'Associated locations',
    'encyclopedia.templateField.associated-characters': 'Associated characters',
    'encyclopedia.templateField.propulsion': 'Propulsion',
    'encyclopedia.templateField.capacity': 'Capacity',
    'encyclopedia.templateField.speed': 'Speed',
    'encyclopedia.templateField.manufacturers': 'Manufacturers',
    'encyclopedia.templateField.symptoms': 'Symptoms',
    'encyclopedia.templateField.causes': 'Causes',
    'encyclopedia.templateField.treatment': 'Treatment',
    'encyclopedia.templateField.affected-species': 'Affected species',
    'encyclopedia.templateField.associated-groups': 'Associated groups',
    'encyclopedia.templateField.ingredients': 'Ingredients',
    'encyclopedia.templateField.preparation': 'Preparation',
    'encyclopedia.templateField.rules': 'Rules',
    'encyclopedia.templateField.equipment': 'Equipment',
    'encyclopedia.templateField.venues': 'Venues',
    'encyclopedia.templateField.architecture': 'Architecture',
    'encyclopedia.templateField.curriculum': 'Curriculum',
    'encyclopedia.templateField.notable-alumni': 'Notable alumni',
    'encyclopedia.templateField.affiliation': 'Affiliation',
    'encyclopedia.templateField.language': 'Language'
};