export default {
  'events.upcoming': 'Tulevased sündmused',
  'events.settings.title': 'Sündmuse seaded',
  'events.attendance.attending': 'Osalemine',
  'events.attendance.tentative': 'Määramata',
  'events.attendance.notAttending': 'Ei osale',
  'events.details.name': 'Sündmuse nimi',
  'events.details.image': 'Sündmuse pilt',
  'events.details.description': 'Sündmuse kirjeldus / Päevakava',
  'events.details.url': 'Link täiendavatele detailidele',
  'events.details.virtualLink': 'Link virtuaalsele asukohale (nt Zoom, Google Meets jne)',
  'events.details.address': 'Asukoha aadress',
  'events.details.startsAt': 'Sündmuse algus',
  'events.details.endsAt': 'Sündmuse lõpp',
  'events.details.type': 'Sündmuse tüüp',
  'events.type.inPerson': 'Kohapeal',
  'events.type.virtual': 'Virtuaalne',
  'events.type.hybrid': 'Hübriid',
  'events.join.startsIn': 'Sündmus algab {startsAt}',
  // The startsAt is going to be in a relative time format. Eg. `in 1 minute`, `1 day ago`, etc...
  'events.join.virtual': 'Liitu sündmusega',
  'events.selection.origin': 'Sündmuse päritolu',
  'events.origin.universe': 'Universum',
  'events.origin.author': 'Autor',
  'events.origin.groups': 'Grupid',
  'events.origin.organizations': 'Organisatsioonid',
  'events.origin.lu': 'Kirjandusliku universumi sündmused',
  'events.visibility.label': 'Sündmuse nähtavus',
  'events.visibility.public': 'Avalik - kõik näevad seda sündmust',
  'events.visibility.owner': `Omanik - {type, select,
    group {ainult teie grupi liikmed saavad seda sündmust näha}
    universe {seda sündmust saavad näha ainult universumi kaastöötajad ja fännid}
    organization {ainult teie organisatsiooni liikmed saavad seda sündmust näha}
    other {ainult teie ja teie poolt kutsutud inimesed saavad seda sündmust näha}
  }`,
  'events.visibility.private': 'Privaatne - ainult kutsutud inimesed näevad sündmust',
  'events.inviting': 'Kas inimesed, kes näevad seda sündmust, saavad teisi kutsuda?',
  'events.administration': 'Sündmuste haldamine',
  'events.create.title': 'Loo uus sündmus',
  'events.hostedBy': 'Korraldaja: {hostName}',
  'events.openVirtual': 'Mine virtuaalsesse asukohta',
  'events.moreInfo': 'Rohkem infot',
  'event.visibilityShort.private': 'Privaatne',
  'event.visibilityShort.public': 'Avalik',
  'event.visibilityShort.owner': 'Omanik'
};