/**
 * Licenses for creative works
 * https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/
 */
export default {
    'licenses.about': 'Litsentsidest',
    'licenses.more': 'Rohkem infot',
    'licenses.legal': 'Õiguslik dokument',
    'licenses.name.cc-by': 'Creative Commons Attribution 4.0',
    'licenses.cc-by': 'See litsents võimaldab teistel levitada, muuta, kohandada ja luua sinu töö põhjal uusi teoseid, ka kommertslikul eesmärgil, tingimusel et nad annavad sulle autorikrediidi algse loomingu eest. See on kõige paindlikum litsents, mida pakutakse. Soovitatav maksimaalseks levitamiseks ja litsentsitud materjalide kasutamiseks.',
    'licenses.name.cc-by-sa': 'Creative Commons Attribution-ShareAlike 4.0',
    'licenses.cc-by-sa': 'See litsents lubab teistel teie tööd remixida, muuta ja täiendada, isegi ärilistel eesmärkidel, kui nad mainivad teid ja litsentseerivad oma uusi loomingut samadel tingimustel. Seda litsentsi võrreldakse sageli vaba ja avatud lähtekoodiga tarkvara "copyleft" litsentsidega. Kõik uued teosed, mis põhinevad teie teosel, kannavad sama litsentsi, nii et kõik tuletised lubavad ka kaubanduslikku kasutamist. Seda litsentsi kasutab Vikipeedia ja seda soovitatakse kasutada materjalide puhul, mis saaksid kasu Vikipeedia ja sarnaste litsentsidega projektide sisu kaasamisest.',
    'licenses.name.cc-by-nd': 'Creative Commons Attribution-NoDerivs 4.0',
    'licenses.cc-by-nd': 'See litsents võimaldab teistel levitada sinu tööd nii kommertslikul kui ka mitteärilisel eesmärgil, tingimusel et see edastatakse muutumatul kujul ja tervikuna ning antakse sulle autorikrediit.',
    'licenses.name.cc-by-nc': 'Creative Commons Attribution-NonCommercial 4.0',
    'licenses.cc-by-nc': 'See litsents lubab teistel teie teoseid remixida, muuta ja kasutada neid mitteärilistel eesmärkidel ning kuigi nende uued teosed peavad samuti teid tunnustama ja olema mittekaubanduslikud, ei pea nad oma tuletatud teoseid samadel tingimustel litsentseerima.',
    'licenses.name.cc-by-nc-sa': 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0',
    'licenses.cc-by-nc-sa': 'See litsents võimaldab teistel muuta, kohandada ja luua sinu töö põhjal uusi teoseid mitteärilisel eesmärgil, tingimusel et nad annavad sulle autorikrediidi ja litsenseerivad oma uued loomingu samadel tingimustel.',
    'licenses.name.cc-by-nc-nd': 'Creative Commons Attribution-NonCommercial-NoDerivs 4.0',
    'licenses.cc-by-nc-nd': 'See litsents on meie kuuest põhilitsentsist kõige piiravam, lubades teistel vaid teie teoseid alla laadida ja teistega jagada, kui nad mainivad teid, kuid ei saa neid kuidagi muuta ega kaubanduslikult kasutada.',
    'licenses.name.lu-c': 'Kirjandusliku Universumi autoriõigused',
    'licenses.lu-c': 'Standardne täielik autoriõiguste litsents, mis võimaldab teil oma tööd müüa ja avaldada nii, nagu soovite, ning kaitsta oma õigusi sellele. Selle litsentsi abil saate ka oma lugusid müüa Literatuurne Universumis.',
    'licenses.name.lu-e': 'Kirjanduslik universum eksklusiivne',
    'licenses.lu-e': 'See litsents annab Literary Universe\'ile ainuõiguse teie töö avaldamiseks ja levitamiseks internetis. Autoriõigused jäävad teile, kuid Literary Universe\'il on ainuõigus teie teose avaldamiseks ja levitamiseks internetis.',
    'licenses.name.lu-ne': 'Kirjanduslik universum mitteeksklusiivne',
    'licenses.lu-ne': 'See litsents annab Literary Universe\'ile mitte-eksklusiivsed õigused teie töö avaldamiseks ja levitamiseks internetis. Autoriõigus ja õigus avaldada ja levitada oma teost teiste kanalite kaudu jääb teile.',
    'licenses.name.cc0': 'Ühtegi õigust ei ole kaitstud - CC0 1.0',
    'licenses.cc0': 'Pange oma töö avalikuks. Erinevalt CC-litsentsidest, mis võimaldavad autoriõiguste omanikel valida erinevate õiguste vahel, säilitades samal ajal oma autoriõigused, annab CC0 veel ühe valiku - võimaluse loobuda autoriõiguste ja andmebaaside kaitsest ning loojatele automaatselt antud ainuõigustest - meie litsentside "no rights reserved" alternatiiv.',
    // License Chooser Modal
    'licenses.chooser.title': 'Litsentsi valija',
    'licenses.chooser.button': 'Aidake mul valida litsentsi',
    'licenses.chooser.ariaLabel': 'Valige oma töö jaoks litsents',
    'licenses.chooser.introduction': 'See tööriist aitab teil valida oma töö jaoks sobivaima litsentsi. Litsents määrab, kuidas teised saavad teie tööd kasutada, ja mõjutab teie võimet seda Literary Universe\'is rahaks teha.',
    // License Chooser Wizard Steps
    'licenses.chooser.step.contentType.title': 'Millist tüüpi sisu te litsentsite?',
    'licenses.chooser.step.contentType.description': 'Sisu tüüp mõjutab seda, millised litsentsid on teile kättesaadavad.',
    'licenses.chooser.step.contentType.original': 'Originaaltöö',
    'licenses.chooser.step.contentType.fanfiction': 'Fantastiline väljamõeldis',
    'licenses.chooser.step.contentType.fanfictionNote': 'Kirjandusuniversumi fantaasiakirjandusteoste suhtes kehtib automaatselt Creative Commons Attribution-NonCommercial litsents (CC BY-NC). Selle põhjuseks on see, et fantaasiakirjanduse aluseks on teiste autoriõigusega kaitstud teosed ja nende kasutamine ärilisel eesmärgil võib neid õigusi rikkuda.',
    'licenses.chooser.step.commercial.title': 'Kas soovite oma tööd rahaks teha?',
    'licenses.chooser.step.commercial.description': 'Teie töö rahaks muutmise valik mõjutab seda, milline litsents on kõige sobivam.',
    'licenses.chooser.step.commercial.yes': 'Jah, ma tahan oma tööga raha teenida',
    'licenses.chooser.step.commercial.no': 'Ei, ma ei taha oma tööd rahaks teha.',
    'licenses.chooser.step.commercial.monetizeNote': 'Et oma tööd Literary Universe\'ile raha teenida, peate kasutama üht meie kommertslitsentsi. Need litsentsid võimaldavad teil oma tööd müüa, säilitades samal ajal autoriõiguse kaitse.',
    'licenses.chooser.step.exclusivity.title': 'Kas soovite avaldada ainult Kirjandusuniversumis?',
    'licenses.chooser.step.exclusivity.description': 'Eksklusiivsuse valimine mõjutab platvormitasu ja avaldamisvõimalusi.',
    'licenses.chooser.step.exclusivity.yes': 'Jah, ainult kirjanduslikus universumis',
    'licenses.chooser.step.exclusivity.no': 'Ei, ma tahan ka mujal avaldada',
    'licenses.chooser.step.exclusivity.exclusiveNote': 'Kirjandusuniversumi eksklusiivse avaldamisega saate kasu madalamast platvormitasust (10%). See tähendab, et 90% sissetulekust jääb teile.',
    'licenses.chooser.step.exclusivity.nonExclusiveNote': 'Mitteeksklusiivse avaldamise korral saate oma tööd avaldada ka teistel platvormidel. Platvormi tasu on 30%, mis tähendab, et 70% oma sissetulekust jääb teile Literary Universe\'ile. Tulevikus pakume vahendeid, mis aitavad teil kirjastada teistel platvormidel otse Literary Universe\'ist.',
    'licenses.chooser.step.derivatives.title': 'Kas soovite lubada teistel luua tuletatud teoseid?',
    'licenses.chooser.step.derivatives.description': 'Tuletatud teoste hulka kuuluvad teie originaaltöö kohandused, remixid või ümberkujundused.',
    'licenses.chooser.step.derivatives.yes': 'Jah, lubada tuletatud teoseid',
    'licenses.chooser.step.derivatives.no': 'Ei, ärge lubage tuletatud teoseid',
    'licenses.chooser.step.derivatives.allowNote': 'Tuletatud teoste lubamine tähendab, et teised võivad teie tööd kohandada, remixida või ümber kujundada. See võib kaasa tuua teie sisu laiema leviku ja loomingulise taaskasutamise.',
    'licenses.chooser.step.derivatives.disallowNote': 'Tuletatud teoste mitte lubamine tähendab, et teie tööd tuleb edasi anda muutmata kujul ja tervikuna, kuigi seda võib siiski jagada, kui see on nõuetekohaselt viidatud.',
    'licenses.chooser.step.attribution.title': 'Kas soovite nõuda atribuute?',
    'licenses.chooser.step.attribution.description': 'Nimetamine tähendab, et teised peavad teie tööd kasutades teid tunnustama.',
    'licenses.chooser.step.attribution.yes': 'Jah, nõuda atribuute',
    'licenses.chooser.step.attribution.no': 'Ei, paigutada avalikku domeeni (CC0)',
    'licenses.chooser.step.attribution.requireNote': 'Nõutav viitamine tähendab, et igaüks, kes kasutab teie tööd, peab teile avaldama tunnustust teie soovitud viisil.',
    'licenses.chooser.step.attribution.publicDomainNote': 'Oma töö avalikustamine (CC0) tähendab, et loobute kõigist autoriõigustest ja sellega seotud õigustest. Teised võivad teie tööd vabalt kasutada mis tahes eesmärgil ilma viitamiseta.',
    // License Result
    'licenses.chooser.result.commercialTitle': 'Kaubanduslik teave',
    'licenses.chooser.result.exclusiveInfo': 'Kirjandusuniversumi eksklusiivse litsentsiga saate kasu 10% madalamast platvormitasust. See tähendab, et 90% sissetulekust jääb teile, kuid te saate seda tööd avaldada ainult Literary Universe\'is.',
    'licenses.chooser.result.nonExclusiveInfo': 'Literary Universe\'i mitteeksklusiivse litsentsiga saate oma teoseid avaldada ka teistel platvormidel. Platvormitasu on 30%, mis tähendab, et te säilitate 70% oma sissetulekust Literary Universe\'ile. Tulevikus pakume vahendeid, mis aitavad teil kirjastada teistel platvormidel otse Literary Universe\'ist.',
    'licenses.chooser.result.fanfictionNote': 'Seda litsentsi kohaldatakse automaatselt fantaasiakirjanduse suhtes, sest see põhineb teiste isikute autoriõigusega kaitstud materjalil. Kommertskasutus rikuks potentsiaalselt neid õigusi.',
    'licenses.chooser.result.selectLicense': 'Valige see litsents',
    // Adding missing internationalization strings
    'licenseChooser.contentType.title': 'Millist tüüpi sisu te litsentsite?',
    'licenseChooser.contentType.description': 'Sisu tüüp mõjutab seda, millised litsentsid on teile kättesaadavad.',
    'licenseChooser.contentType.original.title': 'Originaaltöö',
    'licenseChooser.contentType.original.description': 'Sisu, mille olete täielikult ise loonud.',
    'licenseChooser.contentType.fanfiction.title': 'Fantastiline väljamõeldis',
    'licenseChooser.contentType.fanfiction.description': 'Teiste loojate olemasolevatel teostel põhinev sisu.',
    'licenseChooser.contentType.fanfiction.note': 'Kirjandusuniversumi fantaasiakirjandusteoste suhtes kehtib automaatselt Creative Commons Attribution-NonCommercial litsents (CC BY-NC). Selle põhjuseks on see, et fantaasiakirjanduse aluseks on teiste autoriõigusega kaitstud teosed ja nende kasutamine ärilisel eesmärgil võib neid õigusi rikkuda.',
    'licenseChooser.commercial.title': 'Kas soovite oma tööd rahaks teha?',
    'licenseChooser.commercial.description': 'Teie töö rahaks muutmise valik mõjutab seda, milline litsents on kõige sobivam.',
    'licenseChooser.commercial.yes': 'Yes, I want to monetize my work',
    'licenseChooser.commercial.yes.title': 'Jah, ma tahan raha teenida',
    'licenseChooser.commercial.yes.description': 'Ma tahan teenida raha oma tööga Literary Universe\'ile.',
    'licenseChooser.commercial.no': 'No, I don\'t want to monetize my work',
    'licenseChooser.commercial.no.title': 'Ei, ma ei taha raha teenida.',
    'licenseChooser.commercial.no.description': 'Ma tahan oma tööd vabalt jagada ilma rahaks muutmata.',
    'licenseChooser.commercial.note': 'Et oma tööd Literary Universe\'ile raha teenida, peate kasutama üht meie kommertslitsentsi. Need litsentsid võimaldavad teil oma tööd müüa, säilitades samal ajal autoriõiguse kaitse.',
    'licenseChooser.exclusivity.title': 'Kas soovite avaldada ainult Kirjandusuniversumis?',
    'licenseChooser.exclusivity.description': 'Eksklusiivsuse valimine mõjutab platvormitasu ja avaldamisvõimalusi.',
    'licenseChooser.exclusivity.yes': 'Yes, I want to publish exclusively on Literary Universe',
    'licenseChooser.exclusivity.yes.title': 'Jah, ainult kirjanduslikus universumis',
    'licenseChooser.exclusivity.yes.description': 'Ma avaldan selle teose ainult kirjanduslikus universumis.',
    'licenseChooser.exclusivity.no': 'No, I want to publish elsewhere as well',
    'licenseChooser.exclusivity.no.title': 'Ei, ma tahan ka mujal avaldada',
    'licenseChooser.exclusivity.no.description': 'Ma tahan seda tööd avaldada ka teistel platvormidel.',
    'licenseChooser.exclusivity.exclusive.note': 'Kirjandusuniversumi eksklusiivse avaldamisega saate kasu madalamast platvormitasust (10%). See tähendab, et 90% sissetulekust jääb teile.',
    'licenseChooser.exclusivity.nonExclusive.note': 'Mitteeksklusiivse avaldamise korral saate oma tööd avaldada ka teistel platvormidel. Platvormi tasu on 30%, mis tähendab, et 70% oma sissetulekust jääb teile Literary Universe\'ile.',
    'licenseChooser.derivatives.title': 'Kas soovite lubada teistel luua tuletatud teoseid?',
    'licenseChooser.derivatives.description': 'Tuletatud teoste hulka kuuluvad teie originaaltöö kohandused, remixid või ümberkujundused.',
    'licenseChooser.derivatives.yes': 'Yes, allow modifications',
    'licenseChooser.derivatives.yes.title': 'Jah, lubada tuletatud teoseid',
    'licenseChooser.derivatives.yes.description': 'Teised võivad mu tööd kohandada, remixida või ümber kujundada.',
    'licenseChooser.derivatives.no': 'No, don\'t allow modifications (ND)',
    'licenseChooser.derivatives.no.title': 'Ei, ärge lubage tuletatud teoseid',
    'licenseChooser.derivatives.no.description': 'Minu tööd tuleb edasi anda muutmata kujul ja tervikuna.',
    'licenseChooser.attribution.title': 'Kas soovite nõuda atribuute?',
    'licenseChooser.attribution.description': 'Nimetamine tähendab, et teised peavad teie tööd kasutades teid tunnustama.',
    'licenseChooser.attribution.yes': 'Yes, require attribution (BY)',
    'licenseChooser.attribution.yes.title': 'Jah, nõuda atribuute',
    'licenseChooser.attribution.yes.description': 'Teised peavad minu tööd kasutades andma mulle tunnustust.',
    'licenseChooser.attribution.no': 'No, allow use without attribution (CC0)',
    'licenseChooser.attribution.no.title': 'Ei, paigutada avalikku domeeni (CC0)',
    'licenseChooser.attribution.no.description': 'Ma loobun kõigist autoriõigustest ja sellega seotud õigustest oma tööle.',
    'licenseChooser.commercialUse.title': 'Kas soovite lubada oma tööde ärilist kasutamist?',
    'licenseChooser.commercialUse.description': 'Kommertskasutus tähendab, et teised võivad teie tööd kasutada ärilistel eesmärkidel.',
    'licenseChooser.commercialUse.yes.title': 'Jah, lubage kaubanduslik kasutamine',
    'licenseChooser.commercialUse.yes.description': 'Teised võivad minu tööd kasutada ärilistel eesmärkidel.',
    'licenseChooser.commercialUse.no': 'No, non-commercial use only (NC)',
    'licenseChooser.commercialUse.no.title': 'Ei, ainult mittekaubanduslikuks kasutamiseks',
    'licenseChooser.commercialUse.no.description': 'Teised võivad minu tööd kasutada ainult mittekaubanduslikel eesmärkidel.',
    'licenseChooser.shareAlike.title': 'Kas soovite nõuda Share-Alike\'i?',
    'licenseChooser.shareAlike.description': 'Valige, kas teised peavad oma kohandusi jagama samadel tingimustel.',
    'licenseChooser.shareAlike.yes.title': 'Nõutav sarnane osa (SA)',
    'licenseChooser.shareAlike.yes.description': 'Kui teised remixivad, teisendavad või kasutavad teie tööd, peavad nad levitama oma panust sama litsentsi alusel, mis originaal.',
    'licenseChooser.shareAlike.no.title': 'Jagamine ei ole nõutav',
    'licenseChooser.shareAlike.no.description': 'Teised võivad levitada kohandusi mis tahes tingimustel, isegi kui need on teie algsest litsentsist piiravamad.',
    'licenseChooser.shareAlike.yes': 'Jah, nõuab Share-Alike (SA)',
    'licenseChooser.shareAlike.no': 'Ei, ei nõua Share-Alike',
    'licenseChooser.cc0Confirmation.title': 'Kinnita CC0 litsents (Public Domain)',
    'licenseChooser.cc0Confirmation.description': 'CC0 loobub kõigist autoriõigustest ja sellega seotud õigustest teie teosele, andes selle sisuliselt avalikku kasutusse. Palun kinnitage oma arusaamist.',
    'licenseChooser.cc0Confirmation.important': 'Oluline teave',
    'licenseChooser.cc0Confirmation.details': 'Valides CC0, loobute kõigist autoriõigustest ja sellega seotud õigustest oma teose suhtes seadusega lubatud ulatuses. See tähendab:',
    'licenseChooser.cc0Confirmation.point1': 'Igaüks võib teie tööd kasutada mis tahes eesmärgil, sealhulgas kaubanduslikul eesmärgil.',
    'licenseChooser.cc0Confirmation.point2': 'Märgistus ei ole nõutav (kuigi see on teretulnud).',
    'licenseChooser.cc0Confirmation.point3': 'Teised võivad teie tööd muuta ja neid muudatusi mitte jagada.',
    'licenseChooser.cc0Confirmation.point4': 'See otsus on tühistamatu, kui te avaldate',
    'licenseChooser.cc0Confirmation.waiver': 'Mõistan, et ma loobun kõigist autoriõigustest ja sellega seotud õigustest oma tööle.',
    'licenseChooser.cc0Confirmation.understanding': 'Ma mõistan CC0 tingimusi ja õiguslikku mõju minu tööle.',
    'licenses.learnMore': 'Lisateave',
    'licenses.legalText': 'Õiguslik tekst',
    'licenses.chooser.back': 'Tagasi',
    'licenses.chooser.select': 'Valige see litsents',
    'licenses.commercial.title': 'Kommertslitsentsi teave',
    'licenses.commercial.exclusive': 'Selle eksklusiivse litsentsiga võtab Literary Universe 10% tasu teie sissetulekust. See tähendab, et te saate 90% tulust, mis on saadud teie tööga meie platvormil.',
    'licenses.commercial.nonExclusive': 'Selle mitte-eksklusiivse litsentsi puhul võtab Literary Universe 30% tasu teie sissetulekust meie platvormil. See tähendab, et te saate 70% oma tööga Literary Universe\'is teenitud tuludest.'
};