export default {
    'org.auditLog.title': 'Tegevusloend',
    'org.settings.title': 'Organisatsiooni seaded',
    'org.settings.name': 'Organisatsiooni nimi',
    'org.settings.membersPrivate': 'Ära näita liikmeid avalikult',
    'org.logo': 'Organisatsiooni logo',
    'org.logo.alt': '{organizationName} logo',
    'org.superAdmin': 'Super Admin',
    'org.settings.language': 'Põhikeel',
    'org.meta.desc': 'Organisatsioonid ja loovgrupid Literary Universes.',
    'org.luOrgs': 'Literary Universes Organisatsioonid',
    'org.otherOrgs': 'Organisatsioonid',
    'org.aboutTitle': 'Teave {orgName}',
    'org.membersTitle': 'Organisatsiooni liikmed',
    'org.membersNone': 'Liikmed ei ole avalikud',
    'org.storiesTitle': 'Lood {orgName}',
    'org.universesTitle': 'Universumid {orgName}',
    'org.userDashboardTitle': 'Sinu organisatsioonid',
    'org.settings.hideMembers.label': 'Peida liikmed avalikkuse eest',
    'org.visit': 'Mine lehele {organization}',
    'org.authorOverride.legend': 'Autori ülekirjutamine',
    'org.authorOverride.desc': 'Näitab selle teksti organisatsiooni nime asemel.',
    'org.authorOverride.label': 'Autori nimi',
    'org.membersAdd.title': 'Kutsu liikmeid organisatsiooni',
    'org.flashnews.admin': 'Flashnews haldus',
    'org.settings.tabListAria': 'Seadista jaotised organisatsioonile',
    'org.forums.title': '{orgName} foorumid',
    'org.flashnews.internal': 'Sisemised uudised',
    'org.flashnews.publicAll': 'Avalikud uudised kõigile omadustele',
    'org.flashnews.createTitle': `Loo uus uudisekuulutus {type, select,
    internal {organisatsioonile}
    allProperties {kuvada avalikkusele kõikidel objektidel}
    other {organisatsioonile}
  }`,
    'org.members.invited': 'Kutsutud liikmed',
    'org.members.list': 'Organisatsiooni liikmed',
    'org.invitesTileNotice': 'Oled kutsutud organisatsiooni {count, number} {count, plural, one {organisatsioonidesse} other {}}',
    'org.invitePage.title': 'Kutsed organisatsioonidesse',
    'org.invitePage.invitedAt': 'Oled kutsutud {invitedAt, date, short}.',
    'org.invitePage.ignoring': 'Sa ignoreerid hetkel seda kutset, mis tähendab, et see on endiselt aktiivne, kuid teavitustega ei tegeleta.',
    'org.invitePage.expiresAt': 'See kutse aegub {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Liitu organisatsiooniga',
    'org.invitePage.reject': 'Keeldu kutsest',
    'org.invitePage.ignore': 'Ignoreeri hetkel',
    'org.leaveOrg.title': 'Lahku organisatsioonist',
    'org.leaveOrg.confirm': 'See on hävitav tegevus. Lahkudes kaotad kogu juurdepääsu sellele organisatsioonile. Kas oled kindel, et soovid organisatsioonist lahkuda?',
    'org.confirmRemove.aria': 'Kinnita kasutaja eemaldamine',
    'org.confirmRemove.confirm': 'Kas oled kindel, et soovid eemaldada kasutaja {username} organisatsioonist {organization}?',
    'org.confirmRemove.remove': 'Eemalda kasutaja',
    'org.mainBlog': 'Põhiline blogi',
    'org.teams': 'Meeskonnad',
    'org.teams.total': 'Kokku meeskonnad: {totalTeams, number}',
    'org.teams.create': 'Loo uus meeskond',
    'org.teams.settings': 'Meeskonna seaded',
    'org.workshop.ownerUser': 'Mitte gildi töö',
    'org.workshop.caption': 'Gildi omandus',
    'org.workshop.title': 'Organisatsiooni töötuba',
    'org.title': 'Organisatsioon',
    'org.hall.title': '{orgName} liikmete saal',
    'org.member.leave': 'Jäta korraldus',
    'org.member.leaveModalTitle': 'Organisatsioonist lahkumise kinnitus',
    'org.member.leaveModalHeading': 'Oled sa kindel, et tahad lahkuda {orgName}',
    'org.member.leaveModalExplain': 'Kui lahkute organisatsioonist, kaotate juurdepääsu kõigile organisatsiooni seotud ressurssidele ja töödele. Seda tegevust ei saa tagasi võtta.',
    // Role management strings
    'org.member.manageRoles': 'Rollide haldamine',
    'org.roles.error': 'Viga: {error}',
    'org.roles.manageFor': 'Rollide haldamine {name}',
    'org.roles.selectRole': 'Valige roll',
    'org.roles.noRole': 'Rolli ei ole (ainult õigused)',
    'org.roles.admin': 'Admin',
    'org.roles.member': 'Liikmesriik',
    'org.roles.author': 'Autor',
    'org.roles.workshop': 'Töötuba',
    'org.roles.teacher': 'Õpetaja',
    'org.permissions.title': 'Õigused',
    'org.permissions.includedInRole': '(lisatud rollile)',
    // Permission names
    'org.permissions.members.add': 'Liikmete lisamine',
    'org.permissions.members.remove': 'Eemaldage liikmed',
    'org.permissions.members.view': 'Vaata liikmeid',
    'org.permissions.settings': 'Seadete haldamine',
    'org.permissions.auditLog': 'Vaata auditilogi',
    'org.permissions.flashnews': 'Halda flash uudiseid',
    'org.permissions.workshop.view': 'Vaata töötuba',
    'org.permissions.workshop.create': 'Loo töötoa objektid',
    'org.permissions.workshop.transfer': 'Omandiõiguse üleandmine',
    'org.permissions.workshop.viewAll': 'Vaadake kõiki töötoa objekte',
    'org.permissions.forum.manager': 'Foorumite haldamine',
    'org.permissions.blog.manage': 'Halda blogi',
    'org.permissions.blog.post': 'Blogipostituste loomine'
};