export default {
    'settings.biography': 'Elulugu',
    'settings.biography.placeholder': 'Veidi endast, mida näidatakse sinu profiilil.',
    'settings.avatar.title': 'Profiilipilt',
    'settings.avatar.own': 'Sinu profiilipilt',
    'settings.avatar.upload': 'Vali pilt',
    'settings.email': 'E-post',
    'settings.email.msg': 'Sinu kontoga seotud e-postid',
    'settings.email.verified.false': 'Ei ole kontrollitud, klõpsake, et kinnitusmeil uuesti saata.',
    'settings.email.verified.true': 'Kinnitatud e-post',
    'settings.email.add': 'Lisa e-post',
    'settings.languages.title': 'Keelte seaded',
    'settings.languages.notice': 'Hetkel on inglise ja tšehhi keel ainsad ametlikult toetatud keeled. Teised keeled on saadaval tänu suurepärastele vabatahtlikele ja tehisintellekti tõlkele, kuid võivad siiski olla lõpetamata ja vigadega kohtades.',
    'settings.languages.join': 'Kui soovid meid aidata, saad tõlkida ka Literary Universet.',
    'settings.name.title': 'Tegelik nimi',
    'settings.name.given': 'Eesnimi',
    'settings.name.family': 'Perekonnanimi',
    'settings.username.change': 'Muuda kasutajanime',
    'settings.username.label': 'Kasutajanimi',
    'settings.password.title': 'Muuda parooli',
    'settings.password.current': 'Praegune parool',
    'settings.password.new': 'Uus parool',
    'settings.password.repeat': 'Korda uut parooli',
    'settings.password.nomatch': 'Uus parool ei kattu!',
    'settings.password.reset': 'Lähtesta oma parool',
    'settings.password.resetSend': 'E-kiri koos juhistega parooli lähtestamiseks on saadetud!',
    'settings.socialConnectTitle': 'Ühenda oma kontod teistest teenustest',
    'settings.socialDisconnect': 'Lahenda ühendus',
    'settings.socialConnect': 'Ühenda',
    'settings.loginWith': 'Logi sisse {service}',
    'settings.connectTo': 'Ühenda {service}',
    'settings.export.title': 'Ekspordi andmed',
    'settings.export.explain': 'See võimaldab sul saada kõik sinu andmed, mis on meie andmebaasis, json-vormingus.',
    'settings.export.submit': 'Ekspordi andmed',
    'settings.delete.title': 'Kustuta konto',
    'settings.delete.warning': `HOIATUS: Konto kustutamisel kaotad juurdepääsu sellele kontole ja
    . Tagasipöördumise võimalust pole. Pane tähele, et see ei pruugi automaatselt kustutada sinu avaldatud töid,
    kommentaare jne. Lisateabe saamiseks vaata kasutustingimusi.`,
    'settings.delete.confirm': 'Lihtsalt veendumaks. Kas oled kindel, et soovid oma kontot kustutada?',
    'settings.delete.cancel': 'Ma ei soovi oma kontot kustutada',
    'settings.delete.submit': 'Kustuta minu konto',
    'settings.legal.title': 'Kasutaja nõusoleku lepingud',
    'settings.legal.explained': 'Siin saad hallata oma nõusolekut erinevatele õigusdokumentidele.',
    'settings.name.private': 'Nimi jääb privaatseks',
    'settings.emailSubscriptions.title': 'E-kirja teavituste seaded',
    'settings.emailSubscriptions.explain': 'Vali, milliseid e-kirja teavitusi soovid meilt saada.',
    'settings.emailSubscriptions.newsletter': 'Aeg-ajalt ilmuv uudiskiri',
    'settings.profile': 'Profiili seaded',
    'settings.profile.basic': 'Põhiline profiiliinfo',
    'settings.profile.identity': 'Identiteet',
    'settings.profile.about': 'Sinust',
    'settings.profile.basic.description': 'Halda oma põhilisi profiiliandmeid, mis on teistele kasutajatele nähtavad.',
    'settings.interests.title': 'Teie huvid',
    'settings.account': 'Konto seaded',
    'settings.legal.export.download': 'Laadi oma andmed alla',
    'settings.legal.export.gathering': 'Andmete kogumine... See võib võtta aega.',
    'settings.gender.title': 'Sinu sugu',
    'settings.gender.usage': 'See teave jääb privaatseks. Kasutame neid andmeid platvormi analüütikaks ja anonüümsete analüütikate jaoks loojatele, kui loete nende lugusid.',
    'settings.age.title': 'Sinu vanus',
    'settings.age.explicit': 'Show explicit content (age rating 21+)',
    'settings.age.birthday': 'Sünniaeg',
    'settings.age.usage': 'See teave jääb privaatseks. Oleme seaduslikult kohustatud küsima sinu vanust. Kasutame neid andmeid platvormi analüütikaks, sisu kuvamiseks hinnangute alusel ja anonüümsete analüütikate jaoks loojatele, kui loete nende lugusid.',
    'settings.country.title': 'Sinu riik',
    'settings.country.usage': 'Oleme seaduslikult kohustatud küsima sinu riiki, et vastata valitsuse päringutele. Kasutame neid andmeid platvormi analüütikaks ja anonüümsete analüütikate jaoks loojatele, kui loete nende lugusid. Kui soovid, saad seda teavet kuvada oma profiilil.',
    'settings.country.public': 'Kuva oma riik avalikult',
    'settings.country.select': 'Vali oma riik',
    'settings.emailSubscriptions.newsletterTech': 'Aeg-ajalt uudiskiri meie arendajatelt',
    'settings.emailSubscriptions.newsletterFeatures': 'Teave uute funktsioonide kohta',
    'settings.emailNotifications.title': 'Teavitused',
    'settings.emailNotifications.pm': 'Uued sõnumid',
    'settings.emailNotifications.newChapters': 'Uued peatükid',
    'settings.resetPasswordEmailSend': 'Oleme saatnud sulle e-kirjaga juhised, kuidas lähtestada oma parool.',
    'settings.theme.title': 'Veebisaidi kujundus',
    'settings.theme.label': 'Veebisaidi teema',
    'settings.theme.light': 'Hele',
    'settings.theme.dark': 'Tume',
    'settings.links.title': 'Link teistele veebisaitidele',
    'settings.links.description': 'Need lingid kuvatakse sinu profiililehel.',
    'settings.links.website': 'Sinu isiklik veebisait',
    'settings.links.social': 'Muud veebisaidid',
    'settings.links.select': 'Vali veebisait, mida lisada',
    // 2FA
    'settings.2fa.title': 'Kaheastmeline autentimine',
    'settings.2fa.explained': 'Kaheastmeline autentimine lisab teie kontole täiendava turvakihi, lisades sisselogimise ajal täiendava autentimissammu. See takistab pahatahtlikel isikutel teie kontole juurdepääsu saamast, kui teie esimene sisselogimise samm on ohustatud.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Kaheastmeline autentimine OTP-koodiga loob ühekordse parooli autentimisrakenduste kaudu (nagu Authy, Google/Microsoft Authenticator jne), mida te sisestate sisselogimisel.',
    'settings.2fa.otpModalAria': '2FA OTP meetod',
    'settings.2fa.otpAdd': 'Lisa 2FA OTP',
    'settings.2fa.confirmCode': 'Kood, mis kuvatakse teie autentimisrakenduses',
    'settings.2fa.svgAlt': 'QR-kood autentimisrakendusele',
    'settings.2fa.codeHeading': 'Kui te ei saa QR-koodi skannida, saate järgmise koodi sisestada käsitsi:',
    'settings.2fa.instructionsTitle': 'Juhised',
    'settings.2fa.instructions1': 'Installige ja avage oma valitud autentimisrakendus (Authy, Google/Microsoft Authenticator, FreeOTP jne)',
    'settings.2fa.instructions2': 'Valige "Lisa konto" (võib olla nähtav "+" ikoon või peidetud menüüs)',
    'settings.2fa.instructions3': 'Skannige siin kuvatav QR-kood või kui see pole võimalik, sisestage allpool olev kood.',
    'settings.2fa.instructions4': 'Sisestage siia ekraanil kuvatavad 6 numbrit, et lõpetada.',
    'settings.2fa.saved': 'Kaheastmeline autentimine edukalt seadistatud!',
    'settings.2fa.disableOTP': 'Keela OTP kaheastmeline autentimine',
    // Web3
    'settings.web3.legend': 'Web3 rahakoti ühendus',
    'settings.web3.explained': 'Saate ühendada oma Web3 krüptorahakoti oma Literary Universe\'i kontoga. Pärast ühendamist saate oma rahakotiga sisse logida ja tulevikus teha veelgi rohkem asju, kui laiendame oma Web3 pakkumist.',
    'settings.web3.connect': 'Ühendage oma rahakott',
    'settings.web3.address': 'Ühendatud aadress: {address}',
    'settings.web3.verify': 'Allkirjastage oma aadress',
    'settings.web3.verify.explained': 'Selle aadressi kuuluvuse kontrollimiseks palume teil allkirjastada sõnum, et tagada teie rahakoti omandiõigus.',
    'settings.web3.verified': 'Kinnitatud',
    'settings.web3.verificationMessage': 'Kasutaja {username} verifitseerimine Literary Universe\'is. Kood: {code}',
    'settings.web3.unlink': 'Eemalda rahakott',
    'settings.web3.linkingMessage': 'Palun kinnitage, et soovite oma rahakoti ühendada Literary Universe\'iga. Kood: {code}',
    'settings.web3.linkError': 'See aadress on juba meie andmebaasis loetletud ega saa olla määratud!',
    // Reader settings
    'settings.reader.title': 'Lugeja seaded',
    'settings.reader.darkMode': 'Alati kuvada tumedas režiimis',
    'settings.reader.asideView': 'Näita maagilist kõrvalpaneeli',
    'settings.reader.textSize': 'Näita teksti suuremas kirjas',
    'settings.reader.storyRecommendations': 'Loo soovitused',
    'settings.reader.storyRecommendationsHelp': 'Võimaldage isikupärastatud lugude soovitused.',
    // AI settings
    'settings.ai.title': 'AI seaded',
    'settings.ai.explained': 'Seadistage, kuidas AI-funktsioonid teie jaoks kirjanduslikus universumis töötavad.',
    // Accessibility
    'settings.accessibility.title': 'Lugeja ligipääsetavus',
    'settings.accessibility.openDyslexic': 'Kasuta OpenDyslexic fonti',
    'settings.accessibility.paragraphStripes': 'Vaheta lõigu taustavärvi',
    'settings.accessibility.paragraphHighlighting': 'Tõsta esile hetkel hiirega hõljuv lõik',
    'settings.accessibility.ruler': 'Kinnita joonlaud hiire külge',
    // Story Recommendations
    'settings.storyRecommendations.title': 'Loo soovitused',
    'settings.storyRecommendations.explained': 'Võimaldage kogu rakenduses isikupärastatud lugemissoovitused, mis põhinevad teie lugemissoovitustel ja -ajalool.',
    'settings.tab.legal': 'Õigusdokumendid',
    'settings.tab.exportDelete': 'Ekspordi andmed ja kustuta konto',
    'settings.languages.uiLanguage': 'Kasutajaliidese keel',
    'settings.languages.readingLanguage': 'Keele lugemine',
    'settings.languages.readingLanguageExplained': 'Lugude otsimisel pakume teile lugusid ja nende tõlkeid selles keeles, kui te ei täpsusta teisiti.',
    'settings.biography.help': 'Räägi teistele endast',
    'settings.username.help': 'Teie unikaalne kasutajanimi platvormil'
};