export default {
    'challenges.current': 'Bieżące wyzwania',
    'challenges.wordcount.goal': 'Docelowa liczba słów',
    'challenges.wordcount.dailygoal': 'Docelowa liczba słów dziennie',
    'challenges.wordcount.today': 'Napisanych dzisiaj',
    'challenges.wordcount.total': 'Łącznie napisanych słów',
    'challenges.wordcount.remaining': 'Pozostało słów',
    'challenges.wordcount.daysleft': 'Pozostało dni',
    'challenges.wordcount.currentDay': 'Bieżący dzień',
    'challenges.wordcount.average': 'Średnia ilość słów dziennie',
    'challenges.wordcount.finishOn': 'Przy obecnej szybkości ukończysz w dniu',
    'challenges.wordcount.finishOnTime': 'Słów do napisania w celu ukończenia na czas',
    'challenges.wordcount.graph.day': 'Dzień {day}',
    'challenges.underway': 'To wyzwanie zostało już podjęte.',
    'challenges.targetWords': 'Łączna docelowa liczba słów',
    'challenges.startDate': 'Data rozpoczęcia',
    'challenges.endDate': 'Data zakończenia',
    'challenges.future': 'Nadchodzące wyzwania',
    'challenges.future.wordcount': 'Wyzwanie liczby słów rozpocznie się w dniu {startDate, date, short} z liczbą docelową {target, number} i potrwa do dnia {endDate, date, short}.',
    'challenges.future.nanowrimo': 'Wyzwanie NaNoWriMo jest gotowe.',
    'challenges.wordcount': 'Liczba słów',
    'challenges.wordcount.desc': `Set yourself a goal of how many words you want to write this month for this {type, select,
    story {story}
    universe {universe}
    other {}
  }.`,
    'challenges.wordcount.select': 'Jak wiele słów chcesz sobie narzucić?',
    'challenges.start': 'Rozpocznij wyzwanie',
    'challenges.report': 'Zgłoś',
    'challenges.victory': 'Gratulacje! To wyzwanie zostało ukończone.',
    'challenges.defeat': 'Niestety, ale nie ukończono tego wyzwania.',
    'challenges.baseline': 'Bieżąca liczba słów dla tej opowieści wynosi {wordcount, number} i będzie to punkt wyjściowy.',
    // NaNoWriMo
    'nanowrimo.full': 'Nowy Miesiąc Pisania Narodowego',
    'nanowrimo.site': 'Oficjalna strona NaNoWriMo',
    'nanowrimo.settings': 'Konto NaNoWriMo',
    'nanowrimo.username': 'Nazwa użytkownika NaNoWriMo',
    'nanowrimo.key': 'Tajny klucz',
    'nanowrimo.key.get': 'Otrzymaj swój klucz NaNoWriMo.',
    'nanowrimo.key.get.notice': 'Musisz być zalogowany, aby to zobaczyć.',
    'nanowrimo.ongoing': 'jest w pełnym rozkwicie! Pozostało jeszcze {countdown} dni!',
    'nanowrimo.startsin': `rozpocznie się za {countdown, plural,
      one {1 dzień}
      other {# dni}
    }! Przygotuj się!`,
    'nanowrimo.isover': 'NaNoWriMo zakończył się. Zobaczcie w przyszłym roku!',
    'nanowrimo.select': 'Wyznacz tę opowieść dla NaNoWriMo.',
    'nanowrimo.baseline': 'Kiedy NaNoWriMo się rozpocznie, bieżący stan słów zostanie użyty jako punkt odniesienia, z którego dodatkowe słowa będą traktowane jako część NaNoWriMo.',
    'nanowrimo.victory': 'Gratulacje! Wygrałeś NaNoWriMo!',
    'nanowrimo.challenge': 'Wyzwanie NaNoWriMo',
    'nanowrimo.description': 'Wyzwanie polega na napisaniu w ciągu listopada powieści o objętości {words, number} słów.',
    'nanowrimo.error.usernotfound': 'Nazwa użytkownika nie została znaleziona na serwerach NaNoWriMo.',
    'nanowrimo.error.nobook': 'Nie znaleziono książki. Upewnij się, że utworzyłeś swoją książkę na NaNoWriMo.',
    'nanowrimo.error.wordcount': 'Nie można ustawić liczby słów na NaNoWrimo, proszę sprawdź swoje dane logowania i spróbuj ponownie.',
    'nanowrimo.connected': 'Wyznaczyłeś to opowiadanie do NaNoWriMo.',
    'nanowrimo.connected.other': 'Połączyłeś już inną historię.'
};