export default {
    'genre.scifi': 'Fantastyka naukowa',
    'genre.fantasy': 'Fantastyka',
    'genre.adventure': 'Przygodowe',
    'genre.poetry': 'Poezja',
    'genre.comedy': 'Komedia',
    'genre.drama': 'Dramat',
    'genre.nonfiction': 'Oparte na faktach',
    'genre.fiction': 'Fikcja',
    'genre.romance': 'Romans',
    'genre.satire': 'Satyra',
    'genre.tragedy': 'Tragedia',
    'genre.crimi': 'Kryminał',
    'genre.historical': 'Fikcja historyczna',
    'genre.horror': 'Horror',
    'genre.mystery': 'Detektywistyczne',
    'genre.thriller': 'Thriller',
    'genre.western': 'Western',
    'genre.memoir': 'Pamiętnik',
    'genre.biography': 'Biografia',
    'genre.steampunk': 'Steampunk',
    'genre.mythology': 'Mitologia',
    'genre.fairytale': 'Opowieść',
    'genre.superhero': 'Superbohaterzy',
    'genre.children': 'Children'
};