export default {
    'settings.biography': 'Biografia',
    'settings.biography.placeholder': 'Trochę informacji o sobie widocznych na Twoim profilu.',
    'settings.avatar.title': 'Awatar',
    'settings.avatar.own': 'Twój awatar',
    'settings.avatar.upload': 'Wybierz obraz',
    'settings.email': 'Adresy e-mail',
    'settings.email.msg': 'Adresy e-mail powiązane z Twoim kontem',
    'settings.email.verified.false': 'Niezweryfikowany',
    'settings.email.verified.true': 'Zweryfikowany adres e-mail',
    'settings.email.add': 'Dodaj adres e-mail',
    'settings.languages.title': 'Ustawienia językowe',
    'settings.languages.notice': 'Język angielski jest obecnie jedynym oficjalnie wspieranym językiem. Pozostałe języki są dostępne dzięki niesamowitym wolontariuszom, ale nadal mogą być nieukończone.',
    'settings.languages.join': 'Jeśli chcesz nam pomóc, możesz również przetłumaczyć Literary Universe.',
    'settings.name.title': 'Dane osobowe',
    'settings.name.given': 'Imię',
    'settings.name.family': 'Nazwisko',
    'settings.username.change': 'Zmień nazwę użytkownika',
    'settings.username.label': 'Nazwa użytkownika',
    'settings.password.title': 'Zmień hasło',
    'settings.password.current': 'Bieżące hasło',
    'settings.password.new': 'Nowe hasło',
    'settings.password.repeat': 'Powtórz nowe hasło',
    'settings.password.nomatch': 'Nowe hasła nie są identyczne!',
    'settings.password.reset': 'Wyzeruj swoje hasło',
    'settings.password.resetSend': 'Wiadomość e-mail z instrukcją wyzerowania hasła została wysłana!',
    'settings.socialConnectTitle': 'Powiąż swoje konta z innych usług',
    'settings.socialDisconnect': 'Usuń powiązanie',
    'settings.socialConnect': 'Powiąż',
    'settings.loginWith': 'Zaloguj przez {service}',
    'settings.connectTo': 'Powiąż z {service}',
    'settings.export.title': 'Eksportuj dane',
    'settings.export.explain': 'Umożliwi Ci to pobranie wszystkich swoich danych przechowywanych w naszej bazie danych w formacie json.',
    'settings.export.submit': 'Eksportuj dane',
    'settings.delete.title': 'Usuń konto',
    'settings.delete.warning': `OSTRZEŻENIE: Po usunięciu swojego konta utracisz do niego dostęp
    bez możliwości cofnięcia. Nie zapewniamy, że zostaną automatycznie usunięte wszystkie Twoje opublikowane prace,
    komentarze itp. Dowiedz się więcej zapoznając się z Warunkami użytkowania.`,
    'settings.delete.confirm': 'Dla pewności. Czy na pewno chcesz usunąć swoje konto?',
    'settings.delete.cancel': 'Nie chcę usuwać swojego konta',
    'settings.delete.submit': 'Usuń moje konto',
    'settings.legal.title': 'Zgody',
    'settings.legal.explained': 'Tutaj możesz zarządzać swoimi zgodami na różne dokumenty prawne.',
    'settings.name.private': 'Nazwa pozostanie prywatna',
    'settings.emailSubscriptions.title': 'Ustawienia powiadomień e-mail',
    'settings.emailSubscriptions.explain': 'Wybierz, które z powiadomień e-mail chcesz od nas otrzymywać.',
    'settings.emailSubscriptions.newsletter': 'Okazjonalny biuletyn',
    'settings.profile': 'Ustawienia profilu',
    'settings.account': 'Ustawienia konta',
    'settings.legal.export.download': 'Pobierz swoje dane',
    'settings.legal.export.gathering': 'Gromadzenie Twoich danych... Może to chwilę potrwać.',
    'settings.gender.title': 'Twoja płeć',
    'settings.gender.usage': 'Te informacje pozostaną prywatne. Używamy tych danych do analizowania platformy oraz w anonimowych podsumowaniach dla twórców, gdy czytasz ich twórczość.',
    'settings.age.title': 'Twój wiek',
    'settings.age.explicit': 'Pokazuj treści wulgarne (kwalifikacja wiekowa 21+)',
    'settings.age.usage': 'Te informacje pozostaną prywatne. Jesteśmy prawnie zobligowani do pytania o Twój wiek. Używamy tych danych do analizowania platformy, wyświetlania treści na podstawie kwalifikacji wiekowych oraz anonimowych podsumowań dla twórców, gdy czytasz ich twórczość.',
    'settings.country.title': 'Twój kraj',
    'settings.country.usage': 'Jesteśmy prawnie zobowiązani do zapytania o Twój kraj, aby móc odpowiedzieć na zapytania rządowe. Używamy tych danych do analizy platformy oraz w anonimowej analityce dla twórców, gdy czytasz ich historie. Jeśli chcesz, możesz wyświetlić te informacje na swoim profilu.',
    'settings.country.public': 'Wyświetlaj mój kraj publicznie',
    'settings.country.select': 'Wybierz kraj',
    'settings.emailSubscriptions.newsletterTech': 'Okazjonalny biuletyn od naszych deweloperów',
    'settings.emailSubscriptions.newsletterFeatures': 'Informacje o nowych funkcjach',
    'settings.emailNotifications.title': 'Powiadomienia',
    'settings.emailNotifications.pm': 'Nowe wiadomości',
    'settings.emailNotifications.newChapters': 'Nowe rozdziały',
    'settings.resetPasswordEmailSend': 'Na Twój adres e-mail wysłaliśmy instrukcję, jak zresetować hasło.',
    'settings.theme.title': 'Dostosowanie witryny',
    'settings.theme.label': 'Motyw witryny',
    'settings.theme.light': 'Jasny',
    'settings.theme.dark': 'Ciemny',
    'settings.links.title': 'Link do innych stron internetowych',
    'settings.links.description': 'Te linki będą wyświetlane na stronie Twojego profilu.',
    'settings.links.website': 'Osobista strona internetowa',
    'settings.links.social': 'Inne strony',
    // 2FA
    'settings.2fa.title': 'Uwierzytelnianie dwuskładnikowe',
    'settings.2fa.explained': 'Uwierzytelnianie dwuskładnikowe zapewnia dodatkową warstwę bezpieczeństwa konta poprzez dodanie dodatkowego kroku uwierzytelniania podczas logowania. Zapobiega to uzyskaniu dostępu do konta przez złośliwe podmioty, jeśli pierwszy etap logowania zostanie naruszony.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Uwierzytelnianie dwuskładnikowe z kodem OTP tworzy jednorazowe hasło za pomocą aplikacji uwierzytelniających (takich jak Authy, Google/Microsoft Authenticator itp.), które wprowadza się podczas logowania.',
    'settings.2fa.otpModalAria': 'Metoda 2FA OTP',
    'settings.2fa.otpAdd': 'Dodaj 2FA OTP',
    'settings.2fa.confirmCode': 'Kod, który pojawi się w aplikacji uwierzytelniającej',
    'settings.2fa.svgAlt': 'Kod QR dla aplikacji uwierzytelniającej',
    'settings.2fa.codeHeading': 'Jeśli nie możesz zeskanować kodu QR, możesz ręcznie wprowadzić poniższy kod:',
    'settings.2fa.instructionsTitle': 'Instrukcje',
    'settings.2fa.instructions1': 'Zainstaluj i otwórz wybraną aplikację uwierzytelniającą (Authy, Google/Microsoft Authenticator, FreeOTP itp.)',
    'settings.2fa.instructions2': 'Wybierz opcję "Dodaj konto" (może to być widoczna ikona "+" lub może być ukryta w menu)',
    'settings.2fa.instructions3': 'Zeskanuj kod QR widoczny na ekranie lub, jeśli nie jest to możliwe, wpisz kod znajdujący się poniżej.',
    'settings.2fa.instructions4': 'Aby zakończyć, wpisz 6 liczb, które pojawią się na ekranie, w polu wprowadzania danych.',
    'settings.2fa.saved': 'Uwierzytelnianie dwuskładnikowe zostało pomyślnie ustanowione!',
    'settings.2fa.disableOTP': 'Wyłącz uwierzytelnianie dwuskładnikowe OTP'
};