export default {
    'settings.biography': 'Biografia',
    'settings.biography.placeholder': 'Trochę informacji o sobie widocznych na Twoim profilu.',
    'settings.avatar.title': 'Awatar',
    'settings.avatar.own': 'Twój awatar',
    'settings.avatar.upload': 'Wybierz obraz',
    'settings.email': 'Adresy e-mail',
    'settings.email.msg': 'Adresy e-mail powiązane z Twoim kontem',
    'settings.email.verified.false': 'Nie zweryfikowano, proszę kliknąć, aby ponownie wysłać wiadomość weryfikacyjną.',
    'settings.email.verified.true': 'Zweryfikowany adres e-mail',
    'settings.email.add': 'Dodaj adres e-mail',
    'settings.languages.title': 'Ustawienia językowe',
    'settings.languages.notice': 'Język angielski i czeski są obecnie jedynymi oficjalnie wspieranymi językami. Pozostałe języki są dostępne dzięki niesamowitym wolontariuszom i tłumaczeniu AI, ale mogą być nadal niekompletne i niepoprawne w niektórych miejscach.',
    'settings.languages.join': 'Jeśli chcesz nam pomóc, możesz również przetłumaczyć Literary Universe.',
    'settings.name.title': 'Dane osobowe',
    'settings.name.given': 'Imię',
    'settings.name.family': 'Nazwisko',
    'settings.username.change': 'Zmień nazwę użytkownika',
    'settings.username.label': 'Nazwa użytkownika',
    'settings.password.title': 'Zmień hasło',
    'settings.password.current': 'Bieżące hasło',
    'settings.password.new': 'Nowe hasło',
    'settings.password.repeat': 'Powtórz nowe hasło',
    'settings.password.nomatch': 'Nowe hasła nie są identyczne!',
    'settings.password.reset': 'Wyzeruj swoje hasło',
    'settings.password.resetSend': 'Wiadomość e-mail z instrukcją wyzerowania hasła została wysłana!',
    'settings.socialConnectTitle': 'Powiąż swoje konta z innych usług',
    'settings.socialDisconnect': 'Usuń powiązanie',
    'settings.socialConnect': 'Powiąż',
    'settings.loginWith': 'Zaloguj przez {service}',
    'settings.connectTo': 'Powiąż z {service}',
    'settings.export.title': 'Eksportuj dane',
    'settings.export.explain': 'Umożliwi Ci to pobranie wszystkich swoich danych przechowywanych w naszej bazie danych w formacie json.',
    'settings.export.submit': 'Eksportuj dane',
    'settings.delete.title': 'Usuń konto',
    'settings.delete.warning': `OSTRZEŻENIE: Po usunięciu swojego konta utracisz do niego dostęp
    bez możliwości cofnięcia. Nie zapewniamy, że zostaną automatycznie usunięte wszystkie Twoje opublikowane prace,
    komentarze itp. Dowiedz się więcej zapoznając się z Warunkami użytkowania.`,
    'settings.delete.confirm': 'Dla pewności. Czy na pewno chcesz usunąć swoje konto?',
    'settings.delete.cancel': 'Nie chcę usuwać swojego konta',
    'settings.delete.submit': 'Usuń moje konto',
    'settings.legal.title': 'Zgody',
    'settings.legal.explained': 'Tutaj możesz zarządzać swoimi zgodami na różne dokumenty prawne.',
    'settings.legal.analytics.title': 'Analityka i śledzenie',
    'settings.legal.analytics.description': 'Mogą Państwo kontrolować usługi analityczne i śledzące używane w Literary Universe. W tej sekcji znajdą Państwo listę wszystkich usług w miarę ich dodawania.',
    'settings.legal.analytics.ostrio': 'Aby wyłączyć śledzenie Ostrio Analytics, proszę odwiedzić stronę rezygnacji:',
    'settings.legal.analytics.ostrioOptOut': 'Zarządzanie rezygnacją z Ostrio Analytics',
    'settings.legal.analytics.future': 'Uwzględnimy tutaj dodatkowych dostawców, takich jak Google Analytics lub Seznam, gdy tylko zostaną włączeni.',
    'settings.name.private': 'Nazwa pozostanie prywatna',
    'settings.emailSubscriptions.title': 'Ustawienia powiadomień e-mail',
    'settings.emailSubscriptions.explain': 'Wybierz, które z powiadomień e-mail chcesz od nas otrzymywać.',
    'settings.emailSubscriptions.newsletter': 'Okazjonalny biuletyn',
    'settings.profile': 'Ustawienia profilu',
    'settings.profile.basic': 'Podstawowe informacje o profilu',
    'settings.profile.identity': 'Tożsamość',
    'settings.profile.about': 'O Panu',
    'settings.profile.basic.description': 'Proszę zarządzać swoimi podstawowymi informacjami profilowymi, które będą widoczne dla innych użytkowników.',
    'settings.interests.title': 'Państwa zainteresowania',
    'settings.account': 'Ustawienia konta',
    'settings.legal.export.download': 'Pobierz swoje dane',
    'settings.legal.export.gathering': 'Gromadzenie Twoich danych... Może to chwilę potrwać.',
    'settings.gender.title': 'Twoja płeć',
    'settings.gender.usage': 'Te informacje pozostaną prywatne. Używamy tych danych do analizowania platformy oraz w anonimowych podsumowaniach dla twórców, gdy czytasz ich twórczość.',
    'settings.age.title': 'Twój wiek',
    'settings.age.explicit': 'Show explicit content (age rating 21+)',
    'settings.age.birthday': 'Data urodzenia',
    'settings.age.usage': 'Te informacje pozostaną prywatne. Jesteśmy prawnie zobligowani do pytania o Twój wiek. Używamy tych danych do analizowania platformy, wyświetlania treści na podstawie kwalifikacji wiekowych oraz anonimowych podsumowań dla twórców, gdy czytasz ich twórczość.',
    'settings.country.title': 'Twój kraj',
    'settings.country.usage': 'Jesteśmy prawnie zobowiązani do zapytania o Twój kraj, aby móc odpowiedzieć na zapytania rządowe. Używamy tych danych do analizy platformy oraz w anonimowej analityce dla twórców, gdy czytasz ich historie. Jeśli chcesz, możesz wyświetlić te informacje na swoim profilu.',
    'settings.country.public': 'Wyświetlaj mój kraj publicznie',
    'settings.country.select': 'Wybierz kraj',
    'settings.emailSubscriptions.newsletterTech': 'Okazjonalny biuletyn od naszych deweloperów',
    'settings.emailSubscriptions.newsletterFeatures': 'Informacje o nowych funkcjach',
    'settings.emailNotifications.title': 'Powiadomienia',
    'settings.emailNotifications.pm': 'Nowe wiadomości',
    'settings.emailNotifications.newChapters': 'Nowe rozdziały śledzonych przez Państwa historii',
    'settings.emailNotifications.newStories': 'Nowe historie w uniwersach lub od autorów, których śledzą Państwo na bieżąco',
    'settings.emailNotifications.newUniverses': 'Nowe uniwersa od autorów, których Państwo śledzą',
    'settings.resetPasswordEmailSend': 'Na Twój adres e-mail wysłaliśmy instrukcję, jak zresetować hasło.',
    'settings.theme.title': 'Dostosowanie witryny',
    'settings.theme.label': 'Motyw witryny',
    'settings.theme.light': 'Jasny',
    'settings.theme.dark': 'Ciemny',
    'settings.links.title': 'Link do innych stron internetowych',
    'settings.links.description': 'Te linki będą wyświetlane na stronie Twojego profilu.',
    'settings.links.website': 'Osobista strona internetowa',
    'settings.links.social': 'Inne strony',
    'settings.links.select': 'Wybierz stronę internetową do dodania',
    // 2FA
    'settings.2fa.title': 'Uwierzytelnianie dwuskładnikowe',
    'settings.2fa.explained': 'Uwierzytelnianie dwuskładnikowe zapewnia dodatkową warstwę bezpieczeństwa konta poprzez dodanie dodatkowego kroku uwierzytelniania podczas logowania. Zapobiega to uzyskaniu dostępu do konta przez złośliwe podmioty, jeśli pierwszy etap logowania zostanie naruszony.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Uwierzytelnianie dwuskładnikowe z kodem OTP tworzy jednorazowe hasło za pomocą aplikacji uwierzytelniających (takich jak Authy, Google/Microsoft Authenticator itp.), które wprowadza się podczas logowania.',
    'settings.2fa.otpModalAria': 'Metoda 2FA OTP',
    'settings.2fa.otpAdd': 'Dodaj 2FA OTP',
    'settings.2fa.confirmCode': 'Kod, który pojawi się w aplikacji uwierzytelniającej',
    'settings.2fa.svgAlt': 'Kod QR dla aplikacji uwierzytelniającej',
    'settings.2fa.codeHeading': 'Jeśli nie możesz zeskanować kodu QR, możesz ręcznie wprowadzić poniższy kod:',
    'settings.2fa.instructionsTitle': 'Instrukcje',
    'settings.2fa.instructions1': 'Zainstaluj i otwórz wybraną aplikację uwierzytelniającą (Authy, Google/Microsoft Authenticator, FreeOTP itp.)',
    'settings.2fa.instructions2': 'Wybierz opcję "Dodaj konto" (może to być widoczna ikona "+" lub może być ukryta w menu)',
    'settings.2fa.instructions3': 'Zeskanuj kod QR widoczny na ekranie lub, jeśli nie jest to możliwe, wpisz kod znajdujący się poniżej.',
    'settings.2fa.instructions4': 'Aby zakończyć, wpisz 6 liczb, które pojawią się na ekranie, w polu wprowadzania danych.',
    'settings.2fa.saved': 'Uwierzytelnianie dwuskładnikowe zostało pomyślnie ustanowione!',
    'settings.2fa.disableOTP': 'Wyłącz uwierzytelnianie dwuskładnikowe OTP',
    // API Keys
    'settings.apiKeys.title': 'Klucze API',
    'settings.apiKeys.description': 'Klucze API umożliwiają aplikacjom zewnętrznym dostęp do danych Literary Universe w Państwa imieniu. Proszę traktować je jak hasła i nigdy ich nie udostępniać.',
    'settings.apiKeys.noKeys': 'Nie mają Państwo jeszcze żadnych kluczy API.',
    'settings.apiKeys.created': 'Utworzono {date, date, medium} na {date, time, short}',
    'settings.apiKeys.lastUsed': 'Ostatnio używane {time}',
    'settings.apiKeys.neverUsed': 'Nigdy nie używany',
    'settings.apiKeys.expires': 'Wygasa {date, date, medium}',
    'settings.apiKeys.name': 'Nazwa klucza',
    'settings.apiKeys.name.placeholder': 'np. wtyczka Obsidian',
    'settings.apiKeys.permissions': 'Uprawnienia',
    'settings.apiKeys.generate': 'Generowanie klucza API',
    'settings.apiKeys.generated.title': 'Wygenerowany klucz API',
    'settings.apiKeys.generated.warning': 'Proszę zapisać ten klucz! Nie będą Państwo mogli go ponownie zobaczyć.',
    'settings.apiKeys.copyToClipboard': 'Kopiuj do schowka',
    'settings.apiKeys.expiration': 'Wygaśnięcie',
    'settings.apiKeys.expiration.duration': `{months, plural,
    =1 {1 miesiąc}
    =3 {3 miesiące}
    =6 {6 miesięcy}
    =12 {1 rok (zalecane)}
    =24 {2 lata}
    other {{months} miesiące}
  }`,
    'settings.apiKeys.revoke.confirm': 'Czy na pewno chcą Państwo cofnąć ten klucz API? Tej czynności nie można cofnąć.',
    'settings.apiKeys.delete.confirm': 'Czy na pewno chcą Państwo usunąć ten klucz API? Tej czynności nie można cofnąć.',
    'settings.apiKeys.error.nameRequired': 'Proszę wprowadzić nazwę klucza API',
    'settings.apiKeys.error.scopesRequired': 'Proszę wybrać przynajmniej jedno pozwolenie',
    'settings.apiKeys.security.title': 'Powiadomienie o zabezpieczeniach',
    'settings.apiKeys.security.1': 'Proszę nigdy nie udostępniać nikomu swojego klucza API',
    'settings.apiKeys.security.2': 'Proszę traktować to jak hasło',
    'settings.apiKeys.security.3': 'Mogą Państwo cofnąć dostęp w dowolnym momencie',
    'settings.apiKeys.security.4': 'Klucz zostanie wyświetlony tylko raz',
    'settings.apiKeys.scope.story.read': 'Proszę przeczytać historie',
    'settings.apiKeys.scope.story.read.desc': 'Dostęp do tytułów, treści i rozdziałów historii',
    'settings.apiKeys.scope.story.write': 'Tworzenie i edytowanie historii',
    'settings.apiKeys.scope.story.write.desc': 'Tworzyć nowe historie i aktualizować istniejące',
    'settings.apiKeys.scope.universe.read': 'Proszę czytać wszechświaty',
    'settings.apiKeys.scope.universe.read.desc': 'Dostęp do wpisów w encyklopedii i danych tworzenia świata',
    'settings.apiKeys.scope.universe.write': 'Tworzenie i edytowanie wszechświatów',
    'settings.apiKeys.scope.universe.write.desc': 'Tworzenie i aktualizacja wpisów w encyklopedii',
    'settings.apiKeys.scope.scratchpad.read': 'Proszę przeczytać notatki',
    'settings.apiKeys.scope.scratchpad.read.desc': 'Dostęp do prywatnych notatek i notatnika',
    'settings.apiKeys.scope.scratchpad.write': 'Tworzenie i edytowanie notatek',
    'settings.apiKeys.scope.scratchpad.write.desc': 'Tworzenie i aktualizacja notatek',
    'settings.apiKeys.scope.blog.read': 'Proszę przeczytać wpisy na blogu',
    'settings.apiKeys.scope.blog.read.desc': 'Dostęp do wpisów na blogu i wersji roboczych',
    'settings.apiKeys.scope.blog.write': 'Tworzenie i edytowanie wpisów na blogu',
    'settings.apiKeys.scope.blog.write.desc': 'Tworzenie i aktualizowanie wpisów na blogu',
    'settings.apiKeys.scope.user.read': 'Proszę przeczytać profil',
    'settings.apiKeys.scope.user.read.desc': 'Dostęp do nazwy użytkownika, awatara i profilu publicznego',
    'settings.apiKeys.scope.library.read': 'Proszę przeczytać bibliotekę',
    'settings.apiKeys.scope.library.read.desc': 'Dostęp do list czytelniczych i zapisanych historii',
    // Web3
    'settings.web3.legend': 'Połączenie z portfelem Web3',
    'settings.web3.explained': 'Możesz połączyć swój portfel kryptowalutowy Web3 z kontem Literary Universe. Po połączeniu będziesz mógł logować się za pomocą swojego portfela i robić jeszcze więcej rzeczy w przyszłości, w miarę jak będziemy rozszerzać naszą ofertę Web3.',
    'settings.web3.connect': 'Podłącz swój portfel',
    'settings.web3.address': 'Adres połączony: {address}',
    'settings.web3.verify': 'Podpisz swój adres',
    'settings.web3.verify.explained': 'Aby sprawdzić, czy ten adres należy do Ciebie, poprosimy Cię o podpisanie wiadomości, która potwierdzi Twoje prawo własności do portfela.',
    'settings.web3.verified': 'Zweryfikowana',
    'settings.web3.verificationMessage': 'Weryfikacja użytkownika {username} dla Literary Universe. Kod: {code}',
    'settings.web3.unlink': 'Usuń portfel',
    'settings.web3.linkingMessage': 'Potwierdź, że chcesz połączyć swój portfel z Literary Universe. Kod: {code}',
    'settings.web3.linkError': 'Ten adres jest już zapisany w naszej bazie danych i nie może zostać przypisany!',
    // Reader settings
    'settings.reader.title': 'Ustawienia czytnika',
    'settings.reader.darkMode': 'Wyświetlanie zawsze w trybie ciemnym',
    'settings.reader.asideView': 'Pokaż magiczny panel boczny',
    'settings.reader.textSize': 'Pokaż tekst większą czcionką',
    'settings.reader.storyRecommendations': 'Zalecenia dotyczące historii',
    'settings.reader.storyRecommendationsHelp': 'Włączanie spersonalizowanych rekomendacji fabularnych.',
    // AI settings
    'settings.ai.title': 'Ustawienia sztucznej inteligencji',
    'settings.ai.explained': 'Skonfiguruj sposób działania funkcji AI w Literary Universe.',
    // Accessibility
    'settings.accessibility.title': 'Dostępność dla czytelników',
    'settings.accessibility.openDyslexic': 'Użyj czcionki OpenDyslexic',
    'settings.accessibility.paragraphStripes': 'Zmiana koloru tła akapitu',
    'settings.accessibility.paragraphHighlighting': 'Podświetlić bieżący akapit, nad którym znajduje się kursor',
    'settings.accessibility.ruler': 'Przymocuj linijkę do myszy',
    // Story Recommendations
    'settings.storyRecommendations.title': 'Zalecenia dotyczące historii',
    'settings.storyRecommendations.explained': 'Włącz spersonalizowane rekomendacje historii w aplikacji na podstawie preferencji i historii czytania.',
    'settings.tab.legal': 'Dokumenty prawne',
    'settings.tab.exportDelete': 'Eksportuj dane i usuń konto',
    'settings.languages.uiLanguage': 'Język interfejsu',
    'settings.languages.readingLanguage': 'Język czytania',
    'settings.languages.readingLanguageExplained': 'Podczas wyszukiwania historii zaoferujemy Państwu historie i ich tłumaczenia w tym języku, chyba że określą Państwo inaczej.',
    'settings.biography.help': 'Proszę opowiedzieć innym o sobie',
    'settings.username.help': 'Państwa unikalna nazwa użytkownika na platformie',
    'settings.interests.tags.custom.help': 'Proszę wprowadzić listę tagów oddzielonych przecinkami',
    'settings.interests.tags.placeholder': 'Proszę dodać tagi',
    'settings.interests.avoidGenres.help': 'Proszę wybrać gatunki, których nie chcą Państwo widzieć w rekomendacjach.',
    'settings.interests.avoidGenres': 'Gatunki, których należy unikać',
    'settings.notifications': 'Powiadomienia i biuletyny',
    'settings.kindleEmail': 'Państwa e-mail Kindle',
    'settings.kindleEmail.explained': 'Jeśli mają Państwo ustawioną tę opcję, w miarę możliwości będziemy oferować możliwość wysyłania historii na Państwa Kindle za pomocą jednego kliknięcia. Adres e-mail Kindle można znaleźć w ustawieniach Amazon w zakładce Content & Devices -> Devices -> proszę wybrać Kindle, aby wyświetlić jego szczegóły i tam znaleźć adres e-mail.'
};