export default {
  'courses.courses': 'Courses',
  'courses.overview': 'Prehľad kurzov',
  'course.create': 'Vytvoriť nový kurz',
  'course.reading.title': 'Názov úlohy na čítanie',
  'course.question.add': 'Pridať otázku',
  'course.add.courseElement': 'Add a new course element',
  'course.lessons.newMessage': 'Vytvorte a organizujte svoje lekcie pre efektívne vyučovanie',
  'course.reading.new': 'Úloha na čítanie',
  'course.reading.newMessage': 'Vytvorte a organizujte úlohy na čítanie pre svojich študentov',
  'course.writing.new': 'Písomná úloha',
  'course.writing.newMessage': 'Rýchlo nastavte a distribuujte písacie úlohy',
  'course.question.text': 'Vaša otázka sem',
  'course.question.type': 'Prosím, vyberte typ otázky',
  'course.question.delete': 'Odstrániť otázku',
  'course.type': 'Vyberte typ kurzu',
  'course.visibility': 'Vyberte možnosť viditeľnosti',
  'course.title': 'Názov',
  'course.description': 'Popis',
  'course.cover': 'Obálka',
  'course.start': 'Váš kurz začína o',
  'course.ends': 'Váš kurz končí o',
  'course.curriculum': 'Učebný plán',
  'course.members': 'Študenti a učitelia',
  'course.assignments': 'Assignments',
  'course.question.deleteWhole': 'Zmazať celú otázku',
  'course.question.yes': 'Áno',
  'course.question.no': 'Nie',
  'course.lesson.title': 'Názov lekcie',
  'course.lesson.add.universe': 'Pridať Príbeh/Vesmír',
  'course.lesson.add.link': 'Pridať externý odkaz',
  'course.status': 'Status',
  'course.active': 'Activity',
  'course.active.message': 'Active',
  'course.inactive': 'Inactive',
  'course.module.edit': 'Edit module name',
  'course.upload.resource': 'Upload a file resource',
  'course.question.answer': 'Add answer',
  'course.question.open': 'Open question',
  'course.question.close': 'Closed question',
  'course.question.multiple': 'Multiple-choice question',
  'course.about': 'About this course',
  'course.lesson.new': 'Create a new lesson',
  'course.lesson.type': 'Lesson type',
  'course.lesson.inPerson': 'In person',
  'course.lesson.preRecorded': 'Pre-recorded',
  'course.lesson.online': 'Online',
  'course.lesson.text': 'Text only',
  'course.lesson.content': 'Lesson content',
  'course.lesson.description': 'Public description',
  'course.add.module': 'Add new module',
  'course.add.story': 'Add story',
  'course.remove.story': 'Remove story',
  'course.dateOfPublish': 'Date of publishing',
  'course.lesson.meetInPerson': 'Meet in person',
  'course.curriculum.edit': 'Edit curriculum',
};
