export default {
    'homepage.welcome': 'Vitajte na',
    'homepage.start': 'Začnite svoju cestu!',
    'homepage.iAm': 'Som',
    'homepage.iAm.aria': 'Výber medzi zobrazením funkcií pre čitateľov a autorov',
    'homepage.reader': 'ČITATEĽ',
    'homepage.writer': 'SPISOVATEĽ',
    'homepage.reader.title': 'Čítanie ešte nikdy nebolo také zaujímavé ako teraz',
    'homepage.reader.registerCTA': 'Začnite čítať hneď!',
    'homepage.reader.readingTitle': 'Jedinečný zážitok z čítania',
    'homepage.reader.readingDesc': 'Ponorte sa hlbšie do svojho obľúbeného fiktívneho sveta v Literárnom vesmíre. Príbehy v Literárnom vesmíre sú prepojené v rámci toho istého univerza, čo vám umožňuje okamžitý prístup k encyklopédii univerza z čítačky príbehov.',
    'homepage.reader.favoriteTitle': 'Zistite viac o svojich obľúbených príbehoch a autoroch',
    'homepage.reader.favoriteDesc': 'Encyklopédia vesmíru a blogy autorov sú len niektoré funkcie, ktoré vám pomôžu zistiť všetko, čo potrebujete vedieť o svojich obľúbených príbehoch, ich prostredí a ich tvorcoch!',
    'homepage.reader.communityTitle': 'Pripojiť sa ku komunite',
    'homepage.reader.communityDesc': 'Zoznámte sa s ľuďmi z celého sveta na špecializovaných fórach o vesmíre a autoroch, blogoch a ďalších komunitných funkciách, kde sa stretávajú podobne zmýšľajúci fanúšikovia. Všetko na jednom mieste.',
    'homepage.reader.readingFeatureTitle': 'Vychutnajte si pohlcujúci a zároveň praktický zážitok z čítania',
    'homepage.reader.readingFeatureDesc': 'Z príbehov a vesmíru máte výhodu čítania bez námahy s prístupom k podrobnostiam bez toho, aby ste museli prepínať medzi stránkami.',
    'homepage.reader.readingExploreTitle': 'Preskúmajte všetky drobnosti vo vesmíre',
    'homepage.reader.readingExploreDesc': 'Encyklopédia vesmíru vám umožní dozvedieť sa všetky podrobnosti o vesmíre a naplno sa ponoriť do príbehov.',
    'homepage.reader.start': 'Začnite čítať',
    'homepage.writer.title': 'Prezentujte svoj vesmír a zdieľajte svoje príbehy',
    'homepage.writer.writingTitle': 'Jednoduché písanie a tvorba',
    'homepage.writer.writingDesc': 'Zažite nový spôsob písania s Literary Universe workshopom. Vytvorte si všetky detaily svojho vesmíru v encyklopédii, o ktorú sa môžete podeliť s čitateľmi, a na tomto základe píšte úžasné príbehy.',
    'homepage.writer.collaborationTitle': 'Spoločná tvorba',
    'homepage.writer.collaborationDesc': 'Na tvorivom procese sa často podieľa viacero ľudí. Nemusíte sa obávať, máme pre vás poistku! Do svojich príbehov a vesmírov môžete jednoducho pridať beta čitateľov, spoluautorov a prekladateľov.',
    'homepage.writer.communityTitle': 'Spojte sa so svojimi čitateľmi',
    'homepage.writer.communityDesc': 'Prekročte rámec písania a spojte sa so svojimi čitateľmi prostredníctvom blogov, fór a iných komunitných funkcií, ktoré súvisia s vaším svetom alebo s vami ako spisovateľom.',
    'homepage.writer.workshopFeatureTitle': 'Jedno miesto pre všetky vaše kreatívne potreby',
    'homepage.writer.workshopFeatureDesc': 'Naša neustále sa rozvíjajúca dielňa je ústredným miestom pre vaše tvorivé potreby. Z jednoduchého nápadu vytvorte úžasné vesmíry, príbehy a všetko ostatné, čo je okolo neho potrebné.',
    'homepage.writer.monetizationFeatureTitle': 'Monetizácia',
    'homepage.writer.monetizationDesc': 'Sme presvedčení, že ľudia by mali byť za svoju prácu platení, a neustále hľadáme nové možnosti monetizácie pre autorov. Funkcia monetizácie vám umožňuje, aby ste boli ocenení za to, čo robíte. Preskúmajte všetky rôzne možnosti, ktoré vašim fanúšikom umožňujú prejaviť vám svoje uznanie.',
    'homepage.writer.start': 'Vstúpte do svojej ateliéru!',
    'homepage.featureSelection': 'Pozrite si tieto populárne vesmíry!',
    'about.title': 'O Literary Universe',
    'about.desc': 'História, tajomstvá a ľudia za Literary Universe.',
    'about.text.1': 'Literary Universe je navrhnutý pre spisovateľov aj vášnivých čitateľov. Spisovatelia môžu použiť platformu na vytvorenie originálnych diel tým, že vyberú tlačidlo "Dielňa" v ponuke nástrojov. Tým získajú prístup k hlavnému editorovi a encyklopédii, ktoré sa zameriavajú na organizáciu všetkých aspektov vašej osobnej literárnej vesmíru na jednej stránke. Sociálne funkcie umožňujú autorom zdieľať svoju prácu, budovať si sledovanie a priamy kontakt s čitateľmi, ak si to želajú.',
    'about.text.2': 'Čitatelia môžu používať stránku hlavne na objavovanie nových diel a sledovanie svojich obľúbených autorov, ale tiež môžu pomôcť upraviť predpublikované príbehy, ak im autor udelí povolenie. Byť čitateľom na Literary Universe ponúka úplne nový zážitok z čítania - mať prístup ku všetkým informáciám o kontexte na tej istej stránke ako hlavný príbeh poskytuje inzight do mysle autora ako nikdy predtým.',
    'about.text.3': 'Budúcnosť Literary Universe zahŕňa vytvorenie trhoviska, kde môžu autori predávať svoje diela, a pridanie komunitných funkcií na zlepšenie komunikácie medzi autorami a čitateľmi prostredníctvom blogov a fór. Plánujeme postupne uviesť nové nástroje pre autorov, pričom momentálne je vývoji alebo plánovaných viac ako tucta. Naším konečným cieľom je obohatiť zážitky nielen autorov, ale aj čitateľov prostredníctvom inovatívneho využitia internetového média.',
    'about.text.4': 'Dúfame, že sa k nám pridáte, keď budeme skúmať, čo dokáže internetové médium urobiť pre tvorivé písanie!',
    'about.team': 'Tím',
    'about.history': 'História',
    'about.company': 'O spoločnosti',
    'about.companyCountry.czechia': 'Česko',
    'about.companyCountry.japan': 'Japonsko',
    'about.companyCity.prague': 'Praha',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Výkonný riaditeľ',
    'about.CTO': 'Technologický riaditeľ',
    'about.jan': 'Jan je zakladateľ, vizionár a technologický mozog za Literary Universe. Ako autor rozsiahlych literárnych vesmírov sa Jan často stretával so výzvou písať príbehy takým spôsobom, aby zachoval technickú presnosť a čitateľnosť bez toho, aby to ovplyvnilo zážitok čitateľa. Táto výzva ho viedla k štúdiu web developmentu s cieľom vytvoriť aplikáciu, ktorá zjednodušuje proces písania príbehov v rámci veľkých vesmírov.',
    'about.history.text': 'V roku 2010 začal Jan študovať na Rochester Institute of Technology, aby prehlbil svoje znalosti v oblasti vývoja webových stránok s cieľom vybudovať platformu pre tvorivé písanie. Táto vízia sa zhmotnila v roku 2013, keď bol na konferencii Imagine RIT predstavený prvý dôkaz konceptu. Jan pokračoval vo svojich štúdiách a v roku 2016 bola vytvorená nová verzia aplikácie ako jeho magisterský projekt Capstone. Projekt pokračoval vývojom počas jesene 2016 a nakoniec sa vyvinul do platformy, ktorú vidíte dnes.',
    'copyrights.desc': 'Informácie o autorských právach na Literárnom vesmíre.',
    'privacy.desc': 'Úplný právny text Zásady ochrany osobných údajov Literary Universe.',
    'guidelines.desc': 'Usmernenia komunity Literary Universe.',
    'tos.desc': 'Úplný právny text Podmienok poskytovania služieb Literary Universe.',
    'homepage.intro': 'Nechajte svoju kreativitu voľne prechádzať Literary Universe',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'Kedykedy snívať o vytváraní fiktívneho sveta takého podrobného, že sa v ňom vytratíte? V Literary Universe poskytujeme nástroje, aby sme splnili tento sen. Každý spisovateľ si zaslúži prístup k prvotriednym zdrojom a podpore. Preto sme navrhli všetko zahŕňajúce prostredie, ktoré prelína zložité rozprávanie a vášnivé čítanie. Pre spisovateľov je to pracovné prostredie snov; pre čitateľov je to odyssea objavovania. Pripojte sa ku nám, keď nasledujeme literárny krytý otvor, aby sme zistili, do akej miery nás to zavedie do sveta predstavivosti.',
    'gdpr.title': 'Súlad s GDPR',
    'gdpr.what': 'Čo je GDPR?',
    'gdpr.explained': 'Všeobecné nariadenie o ochrane údajov (GDPR) je zákon Európskej únie o ochrane údajov, ktorý upravuje spôsob zhromažďovania, spracovania, uchovávania a ochrany osobných údajov. GDPR existuje preto, aby každý používateľ vedel, aké údaje sa zhromažďujú, rozumel spôsobu ich použitia a mal plnú kontrolu nad svojimi osobnými údajmi.',
    'gdpr.compliant': 'Hoci LiteraryUniverse pôsobí celosvetovo, uplatňujeme zásady GDPR ako štandard dôvery a transparentnosti pre všetkých používateľov.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Zákon o autorských právach digitálneho tisícročia',
    'common.legal.changelog': 'Zmeny v teto verzii',
    'dmca.title': 'Zásady zákona o autorských právach v digitálnom tisícročí (DMCA)',
    'dmca.subtitle': 'Zásady riešenia sporov týkajúcich sa autorských práv',
    'dmca.summary': '<ul><li>Obsah porušujúci autorské práva môžete nahlásiť prostredníctvom tlačidla Nahlásiť.</li><li>Musíte preukázať, že ste vlastníkom diela, ktoré je podľa vášho tvrdenia porušené.</li><li>Všetky platné hlásenia preskúmame do 24 až 72 hodín.</li><li>Nahlásená strana má 14 dní na predloženie protioznámenia.</li></ul>',
    'dmca.explained.title': 'Čo je DMCA?',
    'dmca.explained.text': 'Digital Millennium Copyright Act (DMCA) je zákon na ochranu autorských práv, ktorý chráni originálne digitálne diela, ako sú príbehy, ilustrácie, zvukové záznamy a iný kreatívny obsah zverejnený online.\n' + 'LiteraryUniverse plne rešpektuje práva tvorcov a uplatňuje postupy DMCA na ochranu vlastníkov obsahu aj používateľov platformy spravodlivým a transparentným spôsobom.',
    'dmca.reporting.title': 'Postup pri nahlasovaní porušenia autorských práv.',
    'dmca.reporting.text': '<ol><li>Interné vlastníctvo (duševné vlastníctvo umiestnené na Literárnom vesmíre<p>)Ak duševné vlastníctvo existuje na našej platforme, môžete podať správu priamo pomocou tlačidla Nahlásiť, ktoré je k dispozícii na obsahu.Potom budete vyzvaní, aby ste vybrali, ktoré z vašich diel je porušené.</p></li><li>Externé vlastníctvo (duševné vlastníctvo, ktoré nie je umiestnené na portáli Literary Universe<p>)Ak sa duševné vlastníctvo nenachádza na portáli Literary Universe, môžete podať hlásenie pomocou tlačidla Nahlásiť na tvorivom vlastníctve, ktoré je predmetom porušovania práv.</p><p>upozorňujeme, že overenie tejto možnosti nám môže trvať dlhšie a na potvrdenie porušenia práv môžeme požadovať ďalšie materiály.</p></li></ol>',
    'dmca.reporting.requirements': 'V obidvoch prípadoch musíte poskytnúť tieto údaje:<ul><li>Vaše celé zákonné meno a kontaktné údaje</li><li>platný doklad o vlastníctve diela, ktoré bolo porušené (v prípade interného vlastníctva automaticky)</li><li>platný dôkaz o porušení práv</li><li>URL pôvodného obsahu (automaticky pre interné vlastníctvo)</li><li>čestné vyhlásenie potvrdzujúce, že správa je podľa vašich najlepších schopností a znalostí presná</li></ul>',
    'dmca.reporting.warning': 'Nepravdivé tvrdenia môžu mať za následok trvalé obmedzenie predkladania budúcich správ o autorských právach a súdne poplatky.',
    'dmca.ourActions.title': 'Naše akcie',
    'dmca.ourActions.text': 'Po prijatí riadneho oznámenia o porušení práv v dobrej viere: <ul><li>Overíme vaše poverenie a nárok na vlastníctvo.</li><li>Ak je všetko platné, pristúpime ku kontrole vášho nároku. Ak zistíme, že tvrdenie je pravdivé, zneprístupníme majetok, ktorý porušuje práva, až kým: <ul><li>bude vyriešené protioznámenie</li><li>ALEBO uplynie 14 dní bez odpovede</li></ul></li><li>Ak nedostaneme žiadne platné protioznámenie, obsah bude natrvalo odstránený.</li></ul>Naším cieľom je chrániť tvorcov a zároveň zabezpečiť spravodlivý proces pre všetkých používateľov.',
    'dmca.counterNotice.title': 'Protioznámenie',
    'dmca.counterNotice.text': '<p>Ak bol váš obsah odstránený a vy sa domnievate, že bol stiahnutý omylom, môžete podať protioznámenie v Centre riešenia problémov v príbehu alebo vo vesmíre dotknutého diela. Na podanie protioznámenia máte 14 dní od prvého oznámenia.</p><p><b>Vaše protioznámenie musí obsahovať:</b></p><ul><li>Vašu právnu totožnosť a kontaktné údaje</li><li>akýkoľvek dôkaz o vlastníctve diela</li><li>Vyhlásenie o dobrej viere, že dielo neporušuje autorské práva</li><li>právne vyhlásenie, že všetky informácie sú presné</li></ul><p>Po odoslaní náš tím spor preskúma.</p>',
    'dmca.desc': 'Porušovanie autorských práv berieme vážne.',
    'gdpr.summary': '<ul><li>Zhromažďujeme len údaje potrebné na prevádzku platformy alebo tie, ktoré chcete zdieľať.</li><li>Vaše údaje nepredávame.</li><li>K svojim údajom môžete kedykoľvek pristupovať, upravovať ich, exportovať alebo vymazať.</li><li>Na ochranu vašich údajov používame štandardné priemyselné zabezpečenie.</li></ul>',
    'gdpr.desc': 'Všeobecné nariadenie o ochrane údajov (GDPR) a spôsob ochrany údajov v spoločnosti Literary Universe.',
    'gdpr.data.title': 'Aké údaje zhromažďujeme',
    'gdpr.data.desc': 'Okrem údajov, ktoré ste vložili do svojho profilu alebo ktoré ste vygenerovali prostredníctvom interakcie (správy, príbehy atď.), sa snažíme zhromažďovať čo najmenej údajov. Technické informácie, ako je IP adresa, typ prehliadača a operačný systém, zhromažďujeme na zabezpečenie bezpečnosti a funkčnosti našej platformy. V obmedzenej miere zaznamenávame vaše činnosti na našej platforme na účely zabezpečenia a funkčnosti. Príležitostne môžeme zhromažďovať údaje na marketingové účely, tie budú realizované prostredníctvom služieb tretích strán, ktoré rešpektujú nariadenie GDPR, a vždy budete mať možnosť sa z nich odhlásiť.',
    'gdpr.dataUse.title': 'Ako používame vaše údaje',
    'gdpr.dataUse.desc': 'Vaše údaje sa používajú na tieto účely:<ul><li>Poskytovanie základných funkcií platformy (napr. účty, publikovanie obsahu, zasielanie správ)</li><li>Bezpečnosť, prevencia zneužitia a odhaľovanie podvodov</li><li>Funkčná analýza na zlepšenie výkonu a používateľského zážitku</li><li>Dodržiavanie právnych predpisov a reagovanie na platné žiadosti</li><li>Interne zdieľame anonymizované údaje s našimi autormi, keď čítate ich príbehy</li><li>Poskytujeme váš e-mail a krajinu spoločnosti Stripe na spracovanie platieb a ochranu pred podvodmi</li><li>Na marketingové účely môžeme používať vaše údaje, ale vždy budete mať možnosť sa z nich odhlásiť (banner so súbormi cookie atď.)</li></ul>',
    'gdpr.dataStorage.title': 'Ukladanie a zabezpečenie údajov',
    'gdpr.dataStorage.desc': '<ul><li>Všetky údaje (okrem necitlivých audiovizuálnych údajov) sa ukladajú pomocou zabezpečených šifrovaných systémov.</li><li>Prístup je obmedzený len na oprávnený personál, ktorý využíva štandardný zabezpečený prístup</li><li>Pravidelne vykonávame bezpečnostné audity a aktualizácie, aby sme zaistili bezpečnosť vašich údajov</li><li>Všetka interná komunikácia prebieha prostredníctvom šifrovaných kanálov</li></ul>Napriek maximálnemu úsiliu nie je žiadny online systém nikdy stopercentne odolný. V zriedkavých prípadoch porušenia ochrany údajov budú používatelia čo najskôr informovaní, ako to vyžaduje zákon.',
    'gdpr.rights.title': 'Vaše práva podľa GDPR',
    'gdpr.rights.desc': 'Podľa GDPR máte nasledujúce práva. Možnosti ich vykonania nájdete vo svojich používateľských nastaveniach alebo v danom obsahu: <ul><li>Právo na prístup - vyžiadajte si údaje, ktoré o vás uchovávame</li><li>Právo na vymazanie - Vymazať všetky vaše údaje z našich serverov (platia obmedzenia vyplývajúce z platných zákonov a našej dohody s vami - ak ide o príbehy)</li><li>Právo na obmedzenie spracovania - obmedziť spôsob používania vašich údajov</li><li>Právo na prenosnosť údajov - import/export vašich údajov</li></ul>',
    'gdpr.dataRetention.title': 'Uchovávanie údajov',
    'gdpr.dataRetention.desc': 'Vaše údaje ukladáme:<ul><li>Pokiaľ je vaše konto aktívne.</li><li>alebo tak dlho, ako to vyžadujú právne, bezpečnostné alebo prevádzkové účely</li><li>V prípade zverejnených tvorivých diel ich uchovávame idenfinitívne, pokiaľ nie je dohodnuté inak</li></ul>',
    'gdpr.contact.title': 'Kontakt',
    'gdpr.contact.desc': 'Sme len ľudia, takže ak máte nejaké požiadavky, otázky, obavy alebo sme niečo prehliadli, neváhajte nás kontaktovať.<br></br>E-mail: privacy@literaryuniverse.com',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Atribuce',
    'about.attributionsIntro': 'Literary Universe je postavený na mnohých projektoch s otvoreným zdrojovým kódom a bezplatných zdrojoch. Nižšie nájdete ich zoznam.',
    'about.attributionsMatomo': 'Naša analytika využíva vlastný hosting Matomo s údajmi IP2Location LITE dostupnými zo stránky https://lite.ip2location.com.',
    'team.name.pjakubec': 'Pavel Jakubec',
    'about.developer': 'Vývojár',
    'about.seniorDeveloper': 'Senior vývojár',
    'about.juniorDeveloper': 'Junior vývojár',
    'about.leadDesigner': 'Vedúci dizajnér',
    'about.leadUX': 'Vedúci dizajnér UX',
    'about.intern': 'Stážista',
    'about.advisor': 'Poradca',
    'about.headOfResearch': 'Vedúci výskumu',
    'about.CFO': 'Finančný riaditeľ',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry je dizajnér s viac ako 15-ročnými skúsenosťami. V agentúre pracuje od roku 2010, jeho klientmi sú napríklad PERTAMINA, VOA a Ministerstvo cestovného ruchu Indonézie. Má skúsenosti s brandingom, layoutom a tiež UI/UX, cíti sa byť výzvou pri navrhovaní Literary Universe.',
    'about.pavel': 'Web3, Metaverse, AI a akákoľvek nová technológia - Pavel skúma všetko, aby videl, ako môže zlepšiť Literary Universe. Ako skutočný multidisciplinárny výskumník Pavel má prehľad v mnohých oblastiach a pracuje na integrovaní nových a vzrušujúcich funkcií do platformy.',
    'copyrights.about': 'Literárny vesmír berie autorské práva veľmi vážne. Všetok obsah, ktorý používatelia zverejňujú, je ich vlastníctvom a je k dispozícii pod uvedenou licenciou. Okrem úplného súboru licencií Creative Commons ponúka Literary Universe aj 2 komerčné licencie, exkluzívnu a neexkluzívnu.',
    'copyrights.nonExclusiveLicense': 'Nevýhradná licencia Literary Universe vám umožňuje publikovať na Literary Universe bez toho, aby ste sa vzdali akýchkoľvek svojich práv ako držiteľa autorských práv. Môžete publikovať kdekoľvek inde. Literary Universe si vyhradzuje právo používať vaše duševné vlastníctvo len na marketingové účely. Ak sa rozhodnete predať svoje duševné vlastníctvo na Literary Universe, platforma si bude účtovať 30 % poplatok za platformu.',
    'copyrights.exclusiveLicense': 'Exkluzívna licencia Literary Universe vám umožňuje publikovať výlučne na Literary Universe. To znamená, že svoje duševné vlastníctvo nemôžete publikovať na iných online platformách ani na ničom inom mimo Literary Universe. Ak chcete publikovať na fyzickom nosiči, napríklad v knihe, musíte požiadať o povolenie. Ak Literary Universe neodpovie do 30 dní, je to automatický súhlas. Dúfame, že v budúcnosti vám ponúkneme fyzické publikovanie a ďalšie služby prostredníctvom našich partnerov. Nebojte sa nás kontaktovať, prajeme si váš úspech a vo väčšine prípadov si len dávame pozor na podvodné spoločnosti. Napriek tomu je to obmedzujúce, preto ako poďakovanie je poplatok za platformu len 10 %.',
    'copyrights.licensesAreImportant': 'Výber licencie je mimoriadne dôležitý a ovplyvňuje spôsob, akým bude vaša práca v budúcnosti prístupná. Pre uľahčenie výberu si môžete pozrieť náš výber licencií nižšie.'
};