export default {
    'sharing.title': 'Sdílet',
    'sharing.button': 'Tlačidlo zdieľať',
    'sharing.share': 'Zdielať na...',
    'sharing.feedback': 'Chýba nám nejaké miesto, na ktorém by ste chceli zdielať? Dajte nám o ňom vedieť!',
    'sharing.copy': 'Kopírovat',
    'sharing.email': 'E-mail',
    'sharing.sms': 'SMS',
    'sharing.messenger': 'Facebook Messenger',
    'sharing.whatsapp': 'WhatsApp',
    'sharing.twitter': 'X/Twitter',
    'sharing.linkedin': 'LinkedIn',
    'sharing.telegram': 'Telegram',
    'sharing.facebook': 'Facebook',
    'sharing.line': 'LINE',
    'sharing.mastodonSocial': 'Mastodon Social',
    'sharing.mastodonJapan': 'Mastodon Japonsko',
    'sharing.gab': 'Gab',
    'sharing.pinterest': 'Pinterest',
    'sharing.gettr': 'Gettr',
    'sharing.minds': 'Minds.com',
    'sharing.instagram': 'Instagram'
};