export default {
    'challenges.current': 'Aktuella utmaningar',
    'challenges.wordcount.goal': 'Måltal ordantal',
    'challenges.wordcount.dailygoal': 'Måltal dagligt ordantal',
    'challenges.wordcount.today': 'Skrivet idag',
    'challenges.wordcount.total': 'Totalt antal skrivna ord',
    'challenges.wordcount.remaining': 'Återstående ord',
    'challenges.wordcount.daysleft': 'Återstående dagar',
    'challenges.wordcount.currentDay': 'Nuvarande dag',
    'challenges.wordcount.average': 'Genomsnittligt antal ord per dag',
    'challenges.wordcount.finishOn': 'Vid nuvarande hastighet kommer du att bli klar den',
    'challenges.wordcount.finishOnTime': 'Ord att skriva dagligen för att bli klar i tid',
    'challenges.wordcount.graph.day': 'Dag {day}',
    'challenges.underway': 'Denna utmaning pågår redan.',
    'challenges.targetWords': 'Totalt måltal ordantal',
    'challenges.startDate': 'Startdatum',
    'challenges.endDate': 'Slutdatum',
    'challenges.future': 'Kommande utmaningar',
    'challenges.future.wordcount': 'Wordcount challenge staring on {startDate, date, short} with goal of {target, number} by {endDate, date, short}.',
    'challenges.future.nanowrimo': 'NaNoWriMo-utmaningen är redo.',
    'challenges.wordcount': 'Ordantal',
    'challenges.wordcount.desc': `Set yourself a goal of how many words you want to write this month for this {type, select,
    story {story}
    universe {universe}
    other {}
  }.`,
    'challenges.wordcount.select': 'Hur många ord vill du utmana dig själv att skriva?',
    'challenges.start': 'Starta utmaning',
    'challenges.report': 'Rapportera',
    'challenges.victory': 'Grattis! Du har slutfört denna utmaning.',
    'challenges.defeat': 'Tyvärr klarade du inte denna utmaning.',
    'challenges.baseline': 'The current wordcount for this story is {wordcount, number}, this will be the starting point.',
    // NaNoWriMo
    'nanowrimo.full': 'National Novel Writing Month',
    'nanowrimo.site': 'NaNoWriMo:s officiella webbplats',
    'nanowrimo.settings': 'NaNoWriMo-konto',
    'nanowrimo.username': 'NaNoWriMo-användarnamn',
    'nanowrimo.key': 'Hemlig nyckel',
    'nanowrimo.key.get': 'Hämta din NaNoWriMo-nyckel.',
    'nanowrimo.key.get.notice': 'Du måste vara inloggad för att se den.',
    'nanowrimo.ongoing': 'är i full gång! {countdown} fler dagar kvar!',
    'nanowrimo.startsin': `kommer att starta om {countdown, plural,
      one {1 dag}
      other {# dagar}
    }! Gör dig redo!`,
    'nanowrimo.isover': 'NaNoWriMo är över. Vi ses nästa år!',
    'nanowrimo.select': 'Ange den här berättelsen för NaNoWriMo.',
    'nanowrimo.baseline': 'När NaNoWriMo börjar kommer den nuvarande ordräkningen att användas som en grundlinje från vilken eventuella ytterligare ord kommer att räknas som en del av NaNoWriMo.',
    'nanowrimo.victory': 'Grattis! Du vann NaNoWriMo!',
    'nanowrimo.challenge': 'NaNoWriMo-utmaning',
    'nanowrimo.description': 'Utmaningen är att skriva en roman på {words, number} ord under november.',
    'nanowrimo.error.usernotfound': 'Användarnamnet har inte hittats på NaNoWriMo-servrarna.',
    'nanowrimo.error.nobook': 'Ingen bok har hittats. Se till att du har skapat din bok på NaNoWriMo.',
    'nanowrimo.error.wordcount': 'Det gick inte att ange ordräkningen på NaNoWriMo, kontrollera dina referenser och försök igen.',
    'nanowrimo.connected': 'Du har angett den här berättelsen för NaNoWriMo.',
    'nanowrimo.connected.other': 'Du har redan anslutit en annan berättelse.'
};