export default {
    'feedback.home': 'Hjälpcenter',
    'feedback.bugs': 'Problem',
    'feedback.bugs.desc': 'Har du stött på ett fel eller något annat som är fel eller på fel plats? Låt oss veta här!',
    'feedback.features': 'Idéer och förslag',
    'feedback.features.desc': 'Har du idéer till nya funktioner eller hur man kan förbättra webbplatsen? Låt oss veta!',
    'feedback.help': 'Hjälp och handledningar',
    'feedback.help.desc': 'Hur gör du _____? Gå hit för att hitta svaren.',
    'feedback.desc': 'Välkommen till vårt hjälp- och supportcenter!',
    'feedback.open': 'Öppen',
    'feedback.closed': 'Stängd',
    'feedback.accepted': 'Accepterad',
    'feedback.inprogress': 'Pågående',
    'feedback.completed': 'Slutförd',
    'feedback.fixed': 'Åtgärdad',
    'feedback.new.bugs': 'Rapportera nytt problem',
    'feedback.new.features': 'Föreslå en ny funktion',
    'feedback.lang.nosupport': 'Ditt nuvarande språk stöds inte för feedback, var god skriv på engelska. Tack!',
    'feedback.new.thanks': 'Tack för uppmärksamheten! Vi kommer att titta närmare på det.',
    'feedback.comment.title': 'Kommentar',
    'feedback.comment.desc': 'Skicka oss dina synpunkter',
    'feedback.comment.legend': 'Dina synpunkter - låt oss veta om allt',
    'feedback.comment.success': 'Tack för dina synpunkter!',
    'feedback.comment.label': 'Din kommentar',
    'feedback.copyrightReport.title': 'Upphovsrättsintrång',
    'feedback.copyrightReport.desc': 'Rapportera upphovsrättsintrång',
    'feedback.report.noUser': 'Du måste vara inloggad för att kunna lämna en rapport.',
    'feedback.voting.totalVoters': 'Användare har röstat: {voted, number}',
    'feedback.voting.upvote': 'Rösta upp',
    'feedback.voting.downvote': 'Rösta ner',
    'feedback.voting.score': 'Total poäng',
    'feedback.report.title': 'Rapportera innehåll',
    'feedback.report.typeSelect': 'Vad är problemet här?',
    'feedback.reportType.law': 'Lagbrott',
    'feedback.reportType.vulgar': 'Vulgärt/obscen',
    'feedback.reportType.copyright': 'Upphovsrättsbrott',
    'feedback.reportType.storyRating': 'Felaktig åldersklassificering',
    'feedback.reportType.scam': 'Bedrägeri',
    'feedback.report.submit': 'Rapportera',
    'feedback.report.submitting': 'Rapporterar...',
    'feedback.report.violationDesc': 'Detaljer',
    'feedback.report.reportSaved': 'Tack för rapporten! Vi kommer att undersöka och vidta åtgärder vid behov.',
    'feedback.report.copyrightReportSaved': 'Tack för rapporten! Vi kommer att undersöka saken och återkomma.',
    'feedback.report.copyrightOwnershipDesc': 'Äganderättsförklaring',
    'feedback.report.copyrightNotice': 'Observera att du måste vara den rättmätiga ägaren till verket för att använda detta formulär. Om du inte är ägaren, var vänlig informera ägaren eller använd den andra kategorin för att informera oss. Vi tar upphovsrättsintrång på största allvar och samma gäller för felaktig och kränkande användning av detta formulär.',
    'feedback.report.copyrightInternalProperty': 'Jag har publicerat detta verk på Literary Universe',
    'feedback.reportType.spam': 'Spam eller phishing',
    'feedback.reportType.other': 'Övrigt',
    'feedback.report.copyrightType.propertySelectLabel': `Vilket {type, select,
    universe {universum}
    story {berättelse}
    other {berättelse}
  } blir kränkt?`
};