export default {
    'org.auditLog.title': 'Revisionslogg',
    'org.settings.title': 'Organisationsinställningar',
    'org.settings.name': 'Organisationsnamn',
    'org.settings.membersPrivate': 'Visa INTE medlemmar offentligt',
    'org.logo': 'Organisationslogotyp',
    'org.logo.alt': '{organizationName} logotyp',
    'org.superAdmin': 'Superadmin',
    'org.settings.language': 'Primärt språk',
    'org.meta.desc': 'Organisationer och kreativa grupper på Litterär Universum.',
    'org.luOrgs': 'Litterär Universum Organisationer',
    'org.otherOrgs': 'Organisationer',
    'org.aboutTitle': 'Om {orgName}',
    'org.membersTitle': 'Organisationsmedlemmar',
    'org.membersNone': 'Medlemmar är inte offentliga',
    'org.storiesTitle': 'Berättelser från {orgName}',
    'org.universesTitle': 'Universum från {orgName}',
    'org.userDashboardTitle': 'Dina organisationer',
    'org.settings.hideMembers.label': 'Dölj medlemmar från allmänheten',
    'org.visit': 'Gå till sidan {organization}',
    'org.authorOverride.legend': 'Författaröverskridande',
    'org.authorOverride.desc': 'Visar denna text istället för organisationens namn.',
    'org.authorOverride.label': 'Författarens namn',
    'org.membersAdd.title': 'Bjud in medlemmar till organisationen',
    'org.flashnews.admin': 'Flashnews administration',
    'org.settings.tabListAria': 'Inställningar för organisation',
    'org.forums.title': '{orgName} forum',
    'org.flashnews.internal': 'Intern nyhetsflash',
    'org.flashnews.publicAll': 'Offentliga nyhetsflashes för alla egenskaper',
    'org.flashnews.createTitle': `Skapa en ny nyhetsflash för {type, select,
    internal {organisationen}
    allProperties {visas offentligt på alla egenskaper}
    other {organisationen}
  }`,
    'org.members.invited': 'Inbjudna medlemmar',
    'org.members.list': 'Organisationsmedlemmar',
    'org.invitesTileNotice': 'Du har blivit inbjuden till {count, number} {count, plural, one {organisation} other {organisationer}}',
    'org.invitePage.title': 'Inbjudningar till organisationer',
    'org.invitePage.invitedAt': 'Du har blivit inbjuden till {invitedAt, date, short}.',
    'org.invitePage.ignoring': 'Du ignorerar för närvarande denna inbjudan, vilket innebär att den fortfarande är aktiv men inte stör meddelanden.',
    'org.invitePage.expiresAt': 'Denna inbjudan kommer att löpa ut {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Gå med i organisationen',
    'org.invitePage.reject': 'Avvisa inbjudan',
    'org.invitePage.ignore': 'Ignorera för nu',
    'org.leaveOrg.title': 'Lämna organisationen',
    'org.leaveOrg.confirm': 'Detta är en förstörande åtgärd. När du lämnar kommer du att förlora all åtkomst till denna organisation. Är du säker på att du vill lämna organisationen?',
    'org.confirmRemove.aria': 'Bekräfta borttagning av användare',
    'org.confirmRemove.confirm': 'Är du säker på att du vill ta bort {username} från {organization}?',
    'org.confirmRemove.remove': 'Ta bort användare',
    'org.mainBlog': 'Huvudblogg',
    'org.teams': 'Lag',
    'org.teams.total': 'Totalt antal lag: {totalTeams, number}',
    'org.teams.create': 'Skapa ett nytt lag',
    'org.teams.settings': 'Laginställningar',
    'org.workshop.ownerUser': 'Inte ett gillearbete',
    'org.workshop.caption': 'Gilleägande',
    'org.workshop.title': 'Organisationsverkstad',
    'org.title': 'Organisation',
    'org.hall.title': '{orgName} medlemssal',
    'org.member.leave': 'Lämna organisation',
    'org.member.leaveModalTitle': 'Lämna organisationsbekräftelse',
    'org.member.leaveModalHeading': 'Är du säker på att du vill lämna {orgName}',
    'org.member.leaveModalExplain': 'När du lämnar organisationen förlorar du tillgång till alla organisationens tillhörande resurser och arbeten. Denna åtgärd kan inte ångras.',
    // Role management strings
    'org.member.manageRoles': 'Hantera roller',
    'org.roles.error': 'Fel: {error}',
    'org.roles.manageFor': 'Hantering av roller för {name}',
    'org.roles.selectRole': 'Välj roll',
    'org.roles.noRole': 'Ingen roll (endast behörigheter)',
    'org.roles.admin': 'Administratör',
    'org.roles.member': 'Ledamot',
    'org.roles.author': 'Författaren',
    'org.roles.workshop': 'Verkstad',
    'org.roles.teacher': 'Lärare',
    'org.permissions.title': 'Behörigheter',
    'org.permissions.includedInRole': '(ingår i roll)',
    // Permission names
    'org.permissions.members.add': 'Lägg till medlemmar',
    'org.permissions.members.remove': 'Ta bort medlemmar',
    'org.permissions.members.view': 'Visa medlemmar',
    'org.permissions.settings': 'Hantera inställningar',
    'org.permissions.auditLog': 'Visa granskningslogg',
    'org.permissions.flashnews': 'Hantera flash-nyheter',
    'org.permissions.workshop.view': 'Visa verkstad',
    'org.permissions.workshop.create': 'Skapa verkstadsartiklar',
    'org.permissions.workshop.transfer': 'Överlåtelse av äganderätt',
    'org.permissions.workshop.viewAll': 'Se alla workshopartiklar',
    'org.permissions.forum.manager': 'Hantera forum',
    'org.permissions.blog.manage': 'Hantera blogg',
    'org.permissions.blog.post': 'Skapa blogginlägg'
};