export default {
  // ── Editor ──────────────────────────────────────────────────────────────────
  'resume.editor.title': 'Författarens CV',
  'resume.editor.preview': 'Förhandsgranska som utgivare',
  'resume.editor.introduction': 'Inledning',
  'resume.editor.showcase': 'Skyltfönster',
  'resume.editor.contact': 'Kontakt',
  'resume.editor.aboutWork': 'Om mitt arbete',
  'resume.editor.awards': 'Utmärkelser',
  'resume.editor.theme': 'Tema',
  'resume.editor.access': 'Tillgång',
  // General / Introduction
  'resume.editor.general.heading': 'Allmänt',
  'resume.editor.general.enabled': 'Aktivera sidan för återupptagning',
  'resume.editor.general.enabled.help':
    'När inställningen är aktiverad kan utgivarorganisationer på Literary Universe se ditt CV. Din förhandsgranskning är alltid tillgänglig oavsett denna inställning.',
  'resume.editor.introduction.heading': 'Inledning',
  'resume.editor.introduction.description':
    'Skriv en kort introduktion om dig själv för utgivare. Den kommer att visas högst upp på sidan med ditt CV.',
  // Showcase
  'resume.showcase.heading': 'Skyltfönster',
  'resume.showcase.description':
    'Dra för att ordna om dina universum och berättelser. Markera objekt för att inkludera dem i ditt CV. Organisationsägda verk, CC0-licensierade verk och fanfiction är undantagna.',
  'resume.showcase.empty': 'Du har inga valbara berättelser eller universum ännu. Skapa några i verkstaden först.',
  'resume.showcase.noStories': 'Inga valbara historier i det här universumet.',
  'resume.showcase.standalone': 'Fristående berättelser',
  'resume.showcase.hasPreview': 'Förhandsgranskning av utgivare',
  'resume.showcase.private': 'Privat',
  'resume.showcase.ccLicense': 'CC-licensierad',
  'resume.showcase.ccWarning':
    'Vissa av de presenterade berättelserna använder en Creative Commons-licens. Utgivare bör vara medvetna om att dessa verk har specifika licensvillkor som kan begränsa kommersiell användning.',
  'resume.showcase.uploadPreview': 'Ladda upp Publisher Förhandsgranskning',
  // Contact
  'resume.editor.contact.heading': 'Kontaktuppgifter',
  'resume.editor.contact.name': 'Visa namn',
  'resume.editor.contact.email': 'E-post',
  'resume.editor.contact.phone': 'Telefon',
  'resume.editor.contact.website': 'Webbplats',
  // Address
  'resume.editor.address.heading': 'Postadress',
  'resume.editor.address.encryptionNotice':
    'Din adress är krypterad och syns bara för de utgivare som tittar på ditt CV.',
  'resume.editor.address.street': 'Gatuadress',
  'resume.editor.address.city': 'Stad',
  'resume.editor.address.state': 'Stat / provins',
  'resume.editor.address.zip': 'Postnummer',
  'resume.editor.address.country': 'Land',
  // About My Work
  'resume.editor.aboutWork.heading': 'Om mitt arbete',
  'resume.editor.aboutWork.description':
    'Skriv ett valfritt konstnärligt uttalande om ditt kreativa arbete, din process eller din vision. Detta avsnitt visas för förläggare tillsammans med dina utställda verk. Lämna tomt för att utelämna detta avsnitt.',
  'resume.editor.aboutWork.label': 'Konstnärligt uttalande',
  'resume.editor.aboutWork.placeholder':
    'Dela med dig av din kreativa filosofi, vad som driver ditt berättande, teman du utforskar...',
  // Awards
  'resume.editor.awards.heading': 'Utmärkelser och utmärkelser',
  'resume.editor.awards.description': 'Lägg till priser och utmärkelser för dina berättelser eller universum.',
  'resume.editor.awards.title': 'Prisets namn',
  'resume.editor.awards.organization': 'Organisation',
  'resume.editor.awards.year': 'År',
  'resume.editor.awards.desc': 'Beskrivning',
  'resume.editor.awards.add': 'Lägg till pris',
  'resume.editor.awards.remove': 'Ta bort',
  // Theme
  'resume.editor.theme.heading': 'Tema för CV',
  'resume.editor.theme.description': 'Välj ett visuellt tema för din offentliga CV-sida.',
  'resume.editor.theme.customize': 'Anpassningar',
  'resume.editor.theme.accentColor': 'Åsidosättande av accentfärg',
  'resume.editor.theme.fontPreference': 'Preferens för teckensnitt',
  // Publisher Preview Settings
  'resume.preview.settings': 'Förhandsgranskning av utgivare för {title}',
  'resume.preview.mode': 'Förhandsgranskningsläge',
  'resume.preview.fromChapter': 'Från kapitel',
  'resume.preview.toChapter': 'Till kapitel',
  'resume.preview.chapterAccessInfo':
    'Förläggare kommer att kunna läsa kapitlen {from} till {to} direkt på Literary Universe.',
  'resume.preview.generateEpub': 'Generera EPUB-förhandsgranskning',
  'resume.preview.epubReady': 'EPUB-förhandsgranskning genererad på {date}',
  'resume.preview.remove': 'Ta bort förhandsgranskning',
  'resume.preview.save': 'Spara inställningar för förhandsgranskning',
  'resume.preview.banner':
    'Detta är en förhandsvisning av hur utgivare kommer att se ditt CV. Det är alltid tillgängligt för dig oavsett dina åtkomstinställningar.',
  'resume.preview.backToEditor': 'Tillbaka till redaktören',
  'resume.preview.noResume': 'Du har inte skapat ett CV ännu. Gå till redigeraren för att komma igång.',
  'resume.preview.goToEditor': 'Gå till Editor',
  // ── Access Settings ─────────────────────────────────────────────────────────
  'resume.access.title': 'Inställningar för återuppta åtkomst',
  'resume.access.publisher': 'Publisher Access på Literary Universe',
  'resume.access.publisher.description':
    'När det är aktiverat kan medlemmar i organisationer av förlagstyp på Literary Universe se ditt CV direkt på din författarprofil.',
  'resume.access.publisher.toggle': 'Aktivera CV för utgivarorganisationer',
  'resume.access.publisher.toggleHelp':
    'Förhandsgranskningen av ditt CV är alltid tillgänglig för dig oavsett denna inställning.',
  'resume.access.links': 'Delbara länkar',
  'resume.access.links.description':
    'Skapa unika länkar för att dela ditt CV med utgivare och andra. Varje länk spårar besök och kan inaktiveras om den läcker ut.',
  'resume.access.createLink': 'Skapa ny länk',
  'resume.access.createLink.title': 'Skapa åtkomstlänk',
  'resume.access.createLink.comment': 'Kommentar (valfritt)',
  'resume.access.createLink.language': 'Språk på sidan',
  'resume.access.createLink.create': 'Skapa',
  'resume.access.noLinks': 'Inga åtkomstlänkar skapade ännu. Skapa en länk för att dela ditt CV.',
  'resume.access.copy': 'Kopia',
  'resume.access.copied': 'Kopierat!',
  'resume.access.disable': 'Avaktivera',
  'resume.access.enable': 'Aktivera',
  'resume.access.disabled': 'Inaktiverad',
  'resume.access.visits': '{count, plural, one {# besök} other {# besök}}',
  'resume.access.created': 'Skapad {date}',
  'resume.access.viewVisits': 'Visa detaljer om besöket',
  'resume.access.noVisits': 'Inga besök registrerade ännu.',
  'resume.access.anonymousVisitor': 'Anonym',
  'resume.access.onsite': 'På plats',
  'resume.access.visitNumber': '(besök #{number})',
  // ── Public Resume Page ──────────────────────────────────────────────────────
  'resume.public.works': 'Valda verk',
  'resume.public.standaloneWorks': 'Övriga verk',
  'resume.public.storiesInSeries': '{count, plural, one {# berättelse} other {# berättelser}} i serien',
  'resume.public.availableIn': 'Tillgänglig i:',
  'resume.public.downloadPreview': 'Förhandsgranskning av nedladdning',
  'resume.public.readPreview': 'Läs förhandsgranskning (kap. {from}-{to})',
  'resume.public.chapters': '{published} kapitel{total, select, 0 {} other { av {total} planerat}}',
  'resume.public.publishedDate': 'Publicerad {date}',
  'resume.public.contentWarnings': 'Varningar för innehåll:',
  'resume.public.status.completed': 'Färdigställd',
  'resume.public.status.ongoing': 'Pågående',
  'resume.public.status.hiatus': 'Hiatus',
  'resume.public.status.cancelled': 'Avbruten',
  'resume.public.aboutWork': 'Om mitt arbete',
  'resume.public.awards': 'Utmärkelser och utmärkelser',
  'resume.public.viewOnLU': 'Utsikt över litterärt universum →.',
  'resume.public.accessDenied': 'Åtkomst nekad',
  'resume.public.accessDenied.description': 'Du måste vara medlem i en utgivarorganisation för att se detta CV.',
  // Contact section
  'resume.public.contact': 'Kontakt',
  'resume.public.contact.email': 'E-post',
  'resume.public.contact.phone': 'Telefon',
  'resume.public.contact.website': 'Webbplats',
  'resume.public.contact.address': 'Adress',
  'resume.public.readFreeStory': 'Läs hela berättelsen',
  // Sharing / QR
  'resume.sharing.businessCard': 'Visitkort',
  'resume.sharing.fullPage': 'Hela sidan',
  'resume.sharing.selectLanguage': 'Språk / Länk',
  'resume.sharing.selectLanguages': 'Välj vilka språklänkar som ska inkluderas (max {max}):',
  'resume.sharing.selectAtLeastOne': 'Välj minst ett språk för att generera QR-koder.',
  'resume.sharing.authorTitle': 'Författaren',
  'resume.sharing.cardSize': 'Kortets storlek',
  'resume.sharing.pageFormat': 'Sidformat',
  'resume.sharing.download': 'Ladda ner PNG',
  // Theme names
  'resume.theme.light': 'Ljus',
  'resume.theme.dark': 'Mörk',
  'resume.theme.sciFi': 'Sci-Fi',
  'resume.theme.fantasy': 'Fantasi',
  'resume.theme.pragueUrban': 'Prag Urban',
  'resume.theme.steampunk': 'Steampunk',
  'resume.theme.horror': 'Skräck',
  'resume.theme.militarySciFi': 'Militär Sci-Fi',
  'resume.theme.artDeco': 'Art Deco',
};
