export default {
    'writer.menu.optionsAria': 'Redigeringsalternativsmeny',
    'writer.menu.saveOptionsAria': 'Spara alternativ',
    'writer.undo': 'Ångra',
    'writer.redo': 'Gör om',
    'writer.ul': 'Oordnad lista',
    'writer.ol': 'Ordnad lista',
    'writer.blockquote': 'Citat',
    'writer.link': 'Infoga en länk',
    'writer.image': 'Infoga en bild',
    'writer.bold': 'Fet markering av urval',
    'writer.underline': 'Understryk markeringen',
    'writer.italic': 'Framhäv markeringen',
    'writer.wordcount': '{characters, number} tecken, {words, number} ord',
    'finder.details': 'detaljer',
    'finder.remove': 'ta bort anslutningen',
    'finder.connect': 'Anslut urval till uppslagsverksinlägg',
    'writer.aside.ariaLabel': 'Hjälpalternativsmeny',
    'writer.nothingToSave': 'Inget att spara',
    'writer.publish.publishAria': 'Publiceringsalternativ',
    'writer.publish.scheduleExplained': 'Du kan antingen publicera direkt eller schemalägga kapitlet för att vara tillgängligt vid ett senare datum.',
    'writer.publish.schedule': 'Ange publiceringsdatum och tid',
    'writer.publish.previousChapterPublished': 'Det föregående kapitlet publicerades den {publishDate, date, short} kl. {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'Det föregående kapitlet är schemalagt att publiceras den {publishDate, date, short} kl. {publishDate, time}',
    'writer.publish.alreadyPublished': 'Det här kapitlet har redan publicerats den {publishedAt, date, short}. Nya versioner kommer att publiceras omedelbart.',
    'writer.publish.betaReader': 'Beta',
    'writer.publish.public': 'Publicera'
};