/**
 * @authors Jan Dvorak
 */
export default {
    siteName: 'Alam Semesta Sastera',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe adalah platform kreatif dan penerbitan serba dalam satu untuk alam semesta cerita epik.',
    'site.keywords': 'penulisan kreatif, sains fiksyen, sci-fi, fantasi, penulisan, penerbitan, cerita, kisah, alam semesta, novel web, webnovel',
    'site.logoAlt': 'Logo Literary Universe',
    mobileMenu: 'Menu Mudah Alih',
    'common.signin': 'Log masuk',
    'common.signup': 'Daftar',
    'common.signout': 'Log keluar',
    'common.dashboard': 'Papan Pemuka',
    'common.discovery': 'Penemuan',
    'common.library': 'Perpustakaan',
    'common.library.own': 'Perpustakaan Anda',
    'common.workshop': 'Bengkel',
    'common.pm': 'Mesej',
    'common.settings': 'Tetapan',
    'common.options': 'Pilihan',
    'common.profile': 'Profil',
    'common.blog': 'Blog',
    'common.blogs': 'Blog',
    'common.about': 'Tentang kami',
    'common.accessdenied': 'Akses ditolak',
    'common.accessdenied.msg': 'Anda tidak diberikan kebenaran untuk pergi ke sini. Jika anda sepatutnya mempunyai akses di sini, sila hubungi pemilik dan beritahu mereka untuk memeriksa semula tetapan.',
    'common.loading': 'Memuatkan...',
    'common.add': 'Tambah',
    'common.save': 'Simpan',
    'common.email': 'E-mel',
    'common.soon': 'Akan datang...',
    'common.search': 'Cari',
    'common.search.do': 'Cari',
    'common.searching': 'Mencari...',
    'common.report': 'Laporan',
    'common.user': 'Pengguna',
    'common.users': 'Pengguna',
    'common.showmore': 'Tunjukkan lebih banyak',
    'common.futurefeature.title': 'Ciri akan datang',
    'common.futurefeature.text': 'We apologize, but this feature is not available at this time. We are working hard to make it available as soon as possible.',
    'common.nothingfound': 'Tiada hasil dijumpai',
    'common.explore': 'Teroka',
    'common.by': 'oleh {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'Kad Kertas',
    'common.scratchpad.own': 'Kad Kertas Anda',
    'common.news': 'Berita',
    'common.encyclopedia': 'Ensiklopedia',
    'common.art': 'Seni',
    'common.story': 'Cerita',
    'common.stories': 'Cerita-cerita',
    'common.universe': 'Univers',
    'common.universes': 'Univers-univers',
    'common.collaborator': 'Rakan Kongsi',
    'common.collaborators': 'Rakan Kongsi',
    'common.translator': 'Penterjemah',
    'common.translators': 'Penterjemah-penterjemah',
    'common.betareader': 'Pembaca Beta',
    'common.betareaders': 'Pembaca Beta',
    'common.post': 'Hantar',
    'common.statistics': 'Statistik',
    'common.lang.select': 'Pilih bahasa',
    'common.submit': 'Hantar',
    'common.close': 'Tutup',
    'common.comment': 'Komen',
    'common.comments': 'Komen-komen',
    404: 'Halaman tidak dijumpai',
    'search.users': 'Cari pengguna',
    'search.user': 'Cari pengguna',
    'common.help': 'Bantuan',
    'common.or': 'atau',
    'common.account.create': 'Buka akaun',
    'signup.username': 'Nama Pengguna',
    'signup.email': 'Emel Anda',
    'signup.password.label': 'Kata Laluan Anda',
    'signup.password.repeat': 'Ulang kata laluan anda',
    'common.password': 'Kata Laluan',
    'signin.password.forgot': 'Lupa kata laluan?',
    'dashboard.whatsnew': 'Apa yang baru',
    'dashboard.blog': 'Blog anda',
    'common.footer.tagline': 'Menulis dan membaca alam semesta kompleks dengan mudah.',
    'common.footer.plans': 'Rancangan & Harga',
    'common.legal.tos': 'Terma Perkhidmatan',
    'common.legal.community': 'Panduan Komuniti',
    'common.legal.privacy': 'Polisi Privasi',
    'common.legal.copyright': 'Perjanjian Hak Cipta',
    'common.legal.versionDisplay': `{type, select,
    tos {Terma Perkhidmatan}
    community {Garis Panduan Komuniti}
    privacy {Dasar Privasi}
    copyright {Perjanjian Hak Cipta}
    publishingAgreement {Perjanjian Penerbitan}
    other {Perjanjian}
  } Versi {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'Versi baru ({newVersion}) dari dokumen ini akan berlaku pada {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} Hak cipta terpelihara, semua teks adalah hak milik penulis masing-masing.',
    'premium.only.title': 'Tidak mempunyai pangkat keahlian yang mencukupi',
    'premium.only.msg': 'Kami memohon maaf, pangkat keahlian anda tidak mencukupi untuk mengakses ciri ini.',
    'premium.only.join': 'Kami menawarkan pelbagai rancangan untuk semua orang agar dapat memanfaatkan sepenuhnya Alam Sastera.',
    'premium.only.link': 'Lihatlah!',
    'universe.visit': 'Lawati halaman alam',
    'common.fanmanager': 'Pengurus peminat',
    'common.fanarts': 'Seni peminat',
    'common.fanfiction': 'Fiksyen peminat',
    'common.fansettings': 'Tetapan peminat',
    'story.chapter': 'Bab',
    'story.chapters': 'Bab-bab',
    'story.genre': 'Genre',
    'story.genres': 'Genre-genre',
    'story.read': 'Baca',
    'story.lastUpdate': 'Dikemaskini pada {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Selesai pada {date, date, medium}.',
    'story.hiatusAt': 'On hiatus from {date, date, medium}.',
    'story.cancelledAt': 'Cancelled on {date, date, medium}.',
    'story.comments.for': 'Ulasan untuk {story} {chapter}.',
    'story.cover.alt': 'Imej sampul cerita untuk {story}.',
    'story.note.fanfiction': 'NOTA: Cerita ini adalah fiksyen peminat dalam alam {universe}.',
    copyrights: 'Hak Cipta',
    'common.challenges': 'Cabaran',
    // for beta only
    'beta.notice': 'Welcome to the Literary Universe BETA! We are excited to let you know that we are officially launching this Friday! We hope that you will join us and support us as we start a new chapter in our journey.',
    'beta.thanks': 'Thank you for your support!',
    'scratchpad.about': 'Nota dan idea anda boleh diakses di mana-mana dalam laman web ini.',
    'common.feedback': 'Maklum balas',
    'common.createdOn': 'Dicipta pada {date, date, long}',
    'common.createdOn.title': 'Dicipta pada',
    // account types
    admin: 'Admin',
    'common.saved': 'Disimpan!',
    'common.saving': 'Menyimpan...',
    'common.friends': 'Rakan',
    'lang.orig': 'Bahasa asal',
    'lang.orig.plus': 'Bahasa asal - {language}',
    buy: 'Beli',
    confirm: 'Sahkan',
    cancel: 'Batal',
    processing: 'Sedang diproses...',
    'common.noData': 'Tiada data',
    'error.title': 'Satu ralat telah berlaku. Kami memohon maaf atas kesulitan ini.',
    'error.oops': 'Oops! Something went seriously wrong!',
    'error.apologies': 'We apologize for the inconvenience, we will do our best to fix this soon.',
    'error.400.text': 'Error 400: {errorMessage}',
    'common.offlineStatus': 'Anda sedang dalam talian.',
    male: 'Lelaki',
    female: 'Wanita',
    'common.legal.effectiveAt': 'Berkuat kuasa dari {date, date, medium}',
    select: 'Sila pilih',
    'common.statusFailed': 'Gagal menghubungi pelayan.',
    'common.statusConnecting': 'Mencuba untuk menyambung ke pelayan... ({count, number})',
    'slug.checking': 'Memeriksa...',
    'slug.failed': 'Alamat ini sudah wujud.',
    'slug.success': 'Alamat ini tersedia!',
    'notVerified.msg': `Akaun anda {option, select,
    email {e-mel}
    wallet {dompet}
    other {e-mel}
    } tidak disahkan.`,
    'notVerified.verify': `Sila sahkan {option, select,
    email {e-mel}
    wallet {dompet}
    other {e-mel}
    }anda.`,
    unknown: 'tidak diketahui',
    'common.legal.guidelines': 'Panduan Komuniti',
    'errorLoading.title': 'Ralat semasa memuatkan halaman',
    'errorLoading.explained': 'An error has occurred while the page was loading. We apologize for the inconvenience. Please try accessing the page again. If the problem persists, please let us know.',
    'errorLoading.retry': 'Cuba lagi!',
    'errorLoading.takingLong': 'Ini mengambil masa yang lama...',
    'common.title': 'Tajuk',
    'common.timelines': 'Jadual masa',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'Peraturan Perlindungan Data Am',
    'editor.placeholder.link': 'Masukkan URL...',
    'editor.placeholder.connection': 'Cari entri ensiklopedia...',
    'editor.saved.beta': 'Revisi baru untuk pembaca Beta dicipta!',
    'editor.saved.public': 'Versi baru diterbitkan!',
    goodbyeForever: 'We are sorry to see you go. Was it something we did? Please let us know if that is the case. Either way, we wish you the best in your future endeavors and hopefully we\'ll meet again! Live long and prosper!',
    'goodbyeForever.feedback': 'Beritahu kami apa yang boleh kami lakukan dengan lebih baik',
    'common.edit': 'Edit',
    'common.publish': 'Terbitkan',
    'common.publishAt': 'Tarikh dan masa penerbitan',
    'common.publishNow': 'Publish now',
    'common.publishLater': 'Publish later',
    'a11y.user.menu': 'Menu pengguna',
    'a11y.navigation': 'Navigasi',
    'dashboard.profile': 'Profil anda',
    'profile.website': 'Laman web peribadi saya',
    'story.notes.concept': 'Konsep',
    'story.notes.settings': 'Tetapan Cerita',
    'story.notes.theme': 'Tema',
    'story.notes.impact': 'Impak yang Diingini',
    'story.notes.outcome': 'Hasil',
    'story.notes.audience': 'Penonton Sasaran',
    'story.notes.pitch': 'Pitch',
    'story.notes.notes': 'Nota',
    'story.authorsNotes': 'Nota Penulis',
    'story.notes.audienceAgeGroup': 'Target audience age group',
    'story.notes.audienceSex': 'Target audience sex',
    'common.members': 'Ahli',
    'common.language': 'Bahasa',
    next: 'Seterusnya',
    previous: 'Sebelumnya',
    'common.legal.tos.short': 'Terma',
    'common.legal.privacy.short': 'Privasi',
    'premium.increaseLimit': 'Pertimbangkan untuk meningkatkan had anda.',
    'common.sharing': 'Perkongsian',
    'story.isbn': 'ISBN',
    'common.name': 'Nama',
    'common.remove': 'Buang',
    'common.time.milliseconds': 'Milisaat',
    'common.time.seconds': 'Saat',
    'common.time.minutes': 'Minit',
    'common.time.hours': 'Jam',
    'common.time.days': 'Hari',
    'common.time.weeks': 'Minggu',
    'common.time.months': 'Bulan',
    'common.time.years': 'Tahun',
    'common.monetization': 'Monetisasi',
    'common.tab.monetizationOptions': 'Pilihan Monetisasi',
    'common.pagination': 'Penyelajahan Halaman',
    'common.forum': 'Forum',
    'common.2faCode': 'Kod 2FA',
    'common.2faCodeIntro': 'Sila masukkan kod satu masa yang dijana oleh aplikasi pengesah anda.',
    'common.2faCodeAria': 'Borang masukkan kod 2FA',
    'common.aiContent.model.label': 'AI Model',
    'common.aiContent.model.tooltip': 'Select the AI model that was used to generate content',
    'common.other': 'Other',
    'common.aiContent.model.custom.label': 'Custom AI Model',
    'common.aiContent.model.custom.placeholder': 'Enter the name of the AI model',
    'common.select': 'Select...',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Bahasa lalai',
    'signin.web3.signMessage': 'Sila sahkan bahawa anda ingin masuk ke Literary Universe dengan dompet anda sebagai kaedah pengesahan. Kod: {code}',
    'common.web3.confirmationCode': 'Kod pengesahan: {code}',
    'common.roadmap': 'Peta jalan',
    'common.luStatsIFrameOptOut': 'Statistik Alam Sastera - Pilihan Untuk Tidak Mengambil Bahagian',
    'common.image': 'Imej',
    'common.home': 'Laman Utama',
    'common.administration': 'Pentadbiran',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'Kumpulan',
    'common.upload': 'Muat Naik',
    'common.backToDashboard': 'Kembali ke papan pemuka',
    'common.accept': 'Terima',
    'common.reject': 'Tolak',
    'common.events': 'Peristiwa',
    'common.event': 'Acara',
    'common.all': 'Semua',
    'common.social': 'Sosial',
    'common.discordCommunity': 'Komuniti Discord',
    'common.account': 'Akaun',
    'common.notifications': 'Pemberitahuan',
    'common.byDeclaration': 'Oleh:',
    'common.done': 'Selesai',
    recommended: 'Disyorkan',
    'select.typeToCreate': 'Mulakan menaip untuk membuat item',
    'select.noSearchResults': 'Tiada hasil untuk "{search}"',
    'select.removeOption': 'Buang {option}',
    create: 'Cipta',
    'banner.support': 'Literary Universe is made possible thanks to the support of users like you. To help us remain independent and improve the platform, please consider subscribing to one of our plans.',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Tiada akaun?',
    'common.haveAccountQuestion': 'Sudah mempunyai akaun?',
    'common.socialLogin': 'Log masuk dengan perkhidmatan lain',
    'common.viewMore': 'Lihat lebih banyak',
    'common.overview': 'Penerangan keseluruhan',
    'common.loggingOut': 'Log keluar',
    'common.thankYou': 'Terima kasih!',
    'common.seeYouAgain': 'Jumpa lagi!',
    'email.hello': 'Hello {username},',
    'common.back': 'Kembali',
    'console.stop': 'Berhenti!',
    'console.explain': 'Ini adalah fungsi peramban yang ditujukan untuk para pengembang. Jika seseorang meminta Anda untuk menyalin-tempel sesuatu di sini untuk mengaktifkan fitur Literary Universe atau "membobol" akun seseorang, itu adalah penipuan dan akan memberikan mereka akses ke akun Literary Universe Anda.',
    'common.coping': 'Menyalin...',
    'common.actions': 'Tindakan',
    'common.popular': 'Popular',
    'common.newest': 'Terbaru',
    'common.oldest': 'Tertua',
    'common.noSelection': 'No selection',
    'common.content': 'Content',
    'common.theWayOfTheAuthor': 'The Way of the Author',
    'common.password.hide': 'Hide Password',
    'common.password.show': 'Show Password',
    'common.forums': 'Forums',
    'common.restriction.goodConduct': 'Due to good conduct violation we have restricted your use of this feature.',
    'common.continue': 'Continue',
    'common.authorName': 'Author Name',
    'error.invalidFileType': 'Please select a valid image file (JPEG, PNG, GIF, WebP)',
    'error.fileTooLarge': 'Image must be less than {mbSize, number}MB',
    'error.fabricInitFailed': 'Failed to initialize the image editor',
    // File upload strings
    'upload.files': 'Uploaded Files',
    'upload.dropHere': 'Drop your files here...',
    'upload.dragOrClick': 'Drag and drop files here, or click to select files',
    'upload.maxSize': 'Maximum file size: {size}',
    'upload.error.failed': 'File upload failed. Please try again.',
    'upload.error.tooManyFiles': 'You can upload a maximum of {max} files.',
    'upload.error.removeFile': 'Failed to remove file. Please try again.',
    'actions.delete': 'Delete',
    'common.aiContent.indicator': 'AI-Generated Content',
    'common.aiContent.tooltip': 'This content was created with AI assistance',
    'common.aiContent.model': 'AI Model: {model}',
    'common.aiContent.custom': 'Custom AI model',
    'common.viewAll': 'View All',
    'notice.thankYou': 'Thank you for your support!',
    'common.dropImageHere': 'Drop an image here',
    'common.legal.publishingAgreement': 'Publishing Agreement'
};