export default {
    'feedback.home': 'Pusat Bantuan',
    'feedback.bugs': 'Isu',
    'feedback.bugs.desc': 'Adakah anda menghadapi ralat atau perkara lain yang salah atau tidak kena tempat. Beritahu kami di sini!',
    'feedback.features': 'Idea & Cadangan',
    'feedback.features.desc': 'Ada idea untuk ciri-ciri baru atau bagaimana untuk menjadikan laman ini lebih baik? Beritahu kami!',
    'feedback.help': 'Bantuan & Tutorial',
    'feedback.help.desc': 'Bagaimana cara untuk _____? Pergi ke sini untuk mencari jawapan.',
    'feedback.desc': 'Selamat datang ke pusat bantuan dan penyelesaian kami!',
    'feedback.faq': 'Soalan Lazim',
    'feedback.faq.desc': 'Soalan yang Kerap Ditanya',
    'feedback.open': 'Buka',
    'feedback.closed': 'Ditutup',
    'feedback.accepted': 'Diterima',
    'feedback.inprogress': 'Dalam proses',
    'feedback.completed': 'Selesai',
    'feedback.fixed': 'Diperbaiki',
    'feedback.new.bugs': 'Laporkan isu baru',
    'feedback.new.features': 'Cadangkan ciri baru',
    'feedback.lang.nosupport': 'Bahasa anda tidak disokong untuk maklum balas, sila tulis dalam Bahasa Inggeris. Terima kasih!',
    'feedback.new.thanks': 'Terima kasih atas notisnya! Kami akan menyiasatnya segera.',
    'feedback.comment.title': 'Komen',
    'feedback.comment.desc': 'Hantar maklum balas anda',
    'feedback.comment.legend': 'Maklum balas anda - beritahu kami tentang apa-apa',
    'feedback.comment.success': 'Terima kasih atas maklum balas anda!',
    'feedback.comment.label': 'Komen anda',
    'feedback.copyrightReport.title': 'Pencerobohan hak cipta',
    'feedback.copyrightReport.desc': 'Laporkan Pencerobohan Hak Cipta',
    'feedback.report.noUser': 'Anda perlu log masuk untuk membuat laporan.',
    'feedback.voting.totalVoters': 'Pengguna telah mengundi: {voted, number}',
    'feedback.voting.upvote': 'Undi atas',
    'feedback.voting.downvote': 'Undi bawah',
    'feedback.voting.score': 'Jumlah markah',
    'feedback.report.title': 'Laporkan kandungan',
    'feedback.report.typeSelect': 'Apakah masalah di sini?',
    'feedback.reportType.law': 'Pelanggaran undang-undang',
    'feedback.reportType.vulgar': 'Kasar/lurah',
    'feedback.reportType.copyright': 'Pelanggaran hak cipta',
    'feedback.reportType.storyRating': 'Penarafan umur yang salah',
    'feedback.reportType.scam': 'Penipuan',
    'feedback.report.submit': 'Laporan',
    'feedback.report.submitting': 'Melaporkan...',
    'feedback.report.violationDesc': 'Butiran',
    'feedback.report.reportSaved': 'Terima kasih atas laporan anda! Kami akan menyiasat dan mengambil tindakan jika perlu.',
    'feedback.report.copyrightReportSaved': 'Terima kasih atas laporan anda! Kami akan menyiasat dan berhubung semula.',
    'feedback.report.copyrightOwnershipDesc': 'Pernyataan pemilikan',
    'feedback.report.copyrightNotice': 'Sila ambil perhatian bahawa anda perlu menjadi pemilik sah karya ini untuk menggunakan borang ini. Jika anda bukan pemilik, sila beritahu pemilik atau gunakan kategori lain untuk memberitahu kami. Kami mengambil pelanggaran hak cipta dengan sangat serius dan perkara yang sama berlaku untuk penggunaan borang ini yang tidak betul dan bersifat menyalahgunakan.',
    'feedback.report.copyrightInternalProperty': 'Saya telah menerbitkan karya ini di Literary Universe',
    'feedback.reportType.spam': 'Spam atau phishing',
    'feedback.reportType.other': 'Lain-lain',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`,
    'faq.section.about': 'Tentang Kami',
    'faq.section.settings': 'Tetapan',
    'faq.section.discovery': 'Penemuan',
    'faq.section.reader': 'Pembaca',
    'faq.section.library': 'Perpustakaan',
    'faq.section.workshop': 'Bengkel',
    'faq.section.writer': 'Penulis',
    'faq.section.encyclopedia': 'Ensiklopedia',
    'faq.section.groups': 'Kumpulan',
    'faq.section.blogs': 'Blog',
    'faq.section.guilds': 'Persatuan',
    // About us questions
    'faq.question.about.whatIsLU': 'Apakah Literary Universe?',
    'faq.answer.about.whatIsLU': 'Literary Universe adalah platform bagi penulis dan pembaca untuk mencipta, berkongsi, dan menemui cerita dan dunia-dunia.',
    'faq.question.about.difference': 'Apakah perbezaan antara Literary Universe dengan platform membaca dalam talian lain?',
    'faq.answer.about.difference': 'Literary Universe adalah platform serba lengkap yang bermakna ia merangkumi alat-alat untuk menulis, membaca, membina dunia, dan membina komuniti. Perbezaan utamanya adalah penyertaan semua alat ini dalam satu platform dan hubungan yang bersepadu di antara mereka.',
    'faq.question.about.dataLocation': 'Di mana data LU disimpan?',
    'faq.answer.about.dataLocation': 'Data Literary Universe disimpan di server di Amerika Syarikat, khususnya di rantau AWS us-east-1.',
    'faq.question.about.incorporation': 'Di mana anda diwujudkan?',
    'faq.answer.about.incorporation': 'Literary Universe diwujudkan di Republik Czech. Anda boleh mencari butiran lanjut di halaman <a href="/about">tentang kami</a>.',
    'faq.question.about.roadmap': 'Apakah langkah seterusnya untuk Literary Universe?',
    'faq.answer.about.roadmap': 'Ini sentiasa berkembang. Semak <a href="/roadmap">roadmap</a> kami untuk butiran lanjut.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Bagaimana saya boleh menukar paparan Literary Universe?',
    'faq.answer.settings.changeTheme': 'Pengguna yang berdaftar boleh menukar tema mereka dalam tetapan akaun <a href="/user/settings/account"></a> di bawah bahagian "pemetaan laman web". Kami mempunyai tema terang dan tema gelap yang tersedia. Jika anda tidak berdaftar, maka kami cuba untuk menentukan tema yang sesuai berdasarkan tetapan pelayar dan sistem operasi anda.',
    'faq.question.settings.changeAvatar': 'Bagaimana saya boleh menukar avatar saya?',
    'faq.answer.settings.changeAvatar': 'Anda boleh menukar avatar anda dalam tetapan profil <a href="/user/settings/profile"></a>.',
    'faq.question.settings.changeLanguage': 'Bagaimana saya boleh menukar bahasa?',
    'faq.answer.settings.changeLanguage': 'Anda boleh menukar bahasa Literary Universe dalam tetapan akaun <a href="/user/settings/account"></a>.',
    'faq.question.settings.translationMistake': 'Saya telah menemui kesilapan dalam teks di laman web, di mana saya boleh melaporkannya?',
    'faq.answer.settings.translationMistake': 'Semua fail bahasa kami tersedia di GitHub. Anda boleh <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">mengemukakan isu di sana</a> atau dalam bahagian Bug di bawah maklum balas, atau jika anda berminat, anda boleh memperbetulkannya sendiri melalui <a href="https://crowdin.com/project/literary-universe" target="_blank">laman Crowdin kami</a>.',
    // Discovery questions
    'faq.question.discovery.explain': 'Apakah bahagian Discovery?',
    'faq.answer.discovery.explain': 'Bahagian Discovery adalah tempat di mana anda boleh mencari cerita, dunia-dunia, blog, kumpulan, dan kandungan lain. Ia adalah tempat untuk meneroka dan mencari bahan bacaan baru yang menarik.',
    // Writer
    'faq.question.writer.howToCreateStory': 'Bagaimana saya boleh mencipta cerita baru di Literary Universe?',
    'faq.answer.writer.howToCreateStory': 'You can create a new story by going to the <a href="/workshop">workshop</a> and clicking on one of the create buttons or go to the main <a href="/workshop/create">create page</a> where you can select a <a href="/workshop/create/story">new standalone story</a> or <a href="/workshop/create/fanfiction">fan fiction</a>. To create a new story in a universe, go first to that universe and then select "stories" on the dashboard and on the next page click the big red button on the right side of the page title. You will be asked to fill in the details of your story and then you can start writing.',
    'faq.question.writer.schedule': 'Bagaimana saya boleh menjadualkan pengeluaran bab dalam Literary Universe?',
    'faq.answer.writer.schedule': 'Anda boleh menjadualkan pengeluaran bab apabila mengklik butang terbit dalam penyunting bab. Satu modal akan dipaparkan di mana anda akan diberi pilihan untuk menjadualkan pengeluaran atau terbit dengan serta-merta. Jika anda memilih untuk menjadualkan pengeluaran, anda akan diminta untuk memilih tarikh dan masa apabila anda mahu bab tersebut dikeluarkan. Kami mengesyorkan agar bab-bab dijadualkan sekurang-kurangnya 24 jam sebelumnya untuk memberi pembaca masa untuk bersedia dengan bab baru dan untuk dikeluarkan pada hari dan masa yang sama setiap minggu.',
    // Reader
    'faq.question.reader.creativeTypes': 'Apakah perbezaan antara Dunia, Cerita, dan Fan Fiction?',
    'faq.answer.reader.creativeTypes': 'Universe adalah tempat di mana anda boleh mencari semua cerita dan kandungan lain yang berkaitan dengan dunia sastera tertentu. Cerita boleh berdiri sendiri atau menjadi sebahagian daripada sebuah alam semesta. Fan Fiction adalah cerita yang berdasarkan alam semesta sastera yang lain yang dicipta oleh seseorang yang lain.',
    // Workshop
    'faq.question.workshop.explain': 'Apakah Workshop?',
    'faq.answer.workshop.explain': 'Workshop adalah tempat di mana anda boleh mencipta cerita baru, fan fiction, alam semesta, dan kandungan lain. Ia adalah tempat untuk menulis, mengedit, dan mengurus kandungan kreatif anda.',
    'faq.question.workshop.creativeTypes': 'Apakah perbezaan antara Universe, Cerita, dan Fan Fiction?',
    'faq.answer.workshop.creativeTypes': 'Universe adalah tempat pusat untuk alam semesta sastera anda di mana anda mencipta cerita yang mendiami dunia sastera yang sama, mengurus ensiklopedia dengan semua perincian dunia anda, dan melakukan apa sahaja yang berkaitan dengannya. Fan Fiction adalah cerita yang berdasarkan cerita atau alam semesta yang dicipta oleh seseorang yang lain. Cerita berdiri sendiri adalah cerita yang tidak berkaitan dengan mana-mana alam semesta, gunakan ini sebagai contoh untuk puisi atau karya sastera yang diletakkan dalam dunia nyata tanpa banyak watak atau perincian yang memerlukan ensiklopedia atau manfaat lain daripada mempunyai alam semesta.',
    'faq.question.workshop.continueStory': 'Bagaimana saya meneruskan cerita yang telah dicipta sebelum ini?',
    'faq.answer.workshop.continueStory': 'You can continue a previously created story by going to the <a href="/workshop">workshop</a> and selecting the story you want to continue or if it is a story in a universe, you need to first go to the universe and select the story from the stories listing. On the story dashboard you can then click on the chapter you want to continue writing or create a new chapter.',
    'faq.question.workshop.whatIsALicense': 'Apakah Lesen Cerita?',
    'faq.answer.workshop.whatIsALicense': 'Lesen cerita adalah dokumen undang-undang yang menentukan bagaimana cerita/alam semesta anda boleh digunakan oleh orang lain. Ia adalah cara untuk melindungi hak anda dan menentukan bagaimana orang lain boleh menggunakan karya anda.',
    'faq.question.workshop.licenses': 'Lesen apa yang tersedia?',
    'faq.answer.workshop.licenses': 'We offer a variety of licenses to choose from. When creating a new work in the licenses section will be a button which will list all available licenses with their full details. In general we offer full copyright protections and <a href="https://creativecommons.org/" target="_blank" rel="noreferrer noopener external">Creative Commons</a> licenses.',
    'faq.question.workshop.guildOwnership': 'Apakah Kepemilikan Guild?',
    'faq.answer.workshop.guildOwnership': 'Kepemilikan Guild menunjukkan sebuah karya yang dimiliki oleh sebuah organisasi, kita menyebutnya Guild. Ini bisa menjadi penerbit atau jenis perusahaan atau organisasi nirlaba lainnya. Kepemilikan karya biasanya sedikit lebih kompleks dan penulis mungkin tidak memiliki kontrol penuh atas karya tersebut, ini lebih berarti bahwa karya tersebut dikelola melalui organisasi dan bukan oleh penulis dari akun pribadinya.',
    'faq.question.workshop.howToInviteCollaborators': 'Bagaimana cara mengundang kolaborator untuk sebuah cerita/universitas?',
    'faq.answer.workshop.howToInviteCollaborators': 'Anda dapat mengundang kolaborator ke cerita/universitas Anda dengan pergi ke dasbor cerita/universitas dan mengklik tombol "kolaborator". Di sana Anda dapat mengundang pengguna lain untuk berkolaborasi pada cerita/universitas Anda dengan memasukkan nama pengguna mereka dan memilih peran yang ingin Anda berikan kepada mereka.',
    'faq.question.workshop.howToTranslation': 'Bagaimana cara menerjemahkan cerita atau universitas saya?',
    'faq.answer.workshop.howToTranslation': 'Anda dapat menerjemahkan cerita atau universitas Anda dengan pergi ke dasbor cerita/universitas dan mengklik tombol "Terjemahan". Di sana Anda dapat menambahkan terjemahan baru untuk karya Anda dan jika Anda memiliki seseorang untuk melakukan terjemahan, Anda dapat mengundang mereka untuk bergabung dalam terjemahan tersebut. Dari sana Anda juga dapat mengelola terjemahan sendiri.',
    'faq.question.workshop.betaReaders': 'Apa itu Beta Readers dan apa tujuan mereka dalam cerita saya?',
    'faq.answer.workshop.betaReaders': 'Beta readers adalah orang-orang yang membaca cerita Anda sebelum diterbitkan dan memberikan umpan balik. Mereka dapat membantu Anda menemukan kesalahan, memberikan ide untuk perbaikan, dan membantu Anda membuat cerita Anda lebih baik.',
    'faq.question.workshop.hiatus': 'Apa itu hiatus dalam status cerita?',
    'faq.answer.workshop.hiatus': 'Hiatus adalah status untuk cerita Anda yang menunjukkan bahwa Anda sedang istirahat dari menulis dan menerbitkan bab baru. Ini adalah cara untuk memberi tahu pembaca Anda bahwa Anda tidak sedang aktif mengerjakan cerita saat ini. Status ini diatur secara otomatis setelah 6 bulan tanpa adanya bab baru. Setelah 6 bulan tambahan tanpa aktivitas, cerita akan ditandai sebagai dibatalkan.',
    'faq.question.workshop.finished': 'Bagaimana cara menandakan bahwa cerita saya selesai?',
    'faq.answer.workshop.finished': 'Anda dapat menandakan bahwa cerita Anda selesai dengan pergi ke dasbor cerita dan di bagian bawah ada tombol hijau yang bertuliskan "Ubah status cerita menjadi Selesai". Ini akan menandai cerita sebagai selesai dengan menyesuaikan halaman terakhir untuk memberi tahu pembaca bahwa cerita sudah selesai dan untuk melihat karya-karya Anda yang lain. Ini juga akan menunjukkan demikian di penemuan membuat cerita Anda lebih terlihat oleh pembaca yang sedang mencari cerita yang sudah selesai.',
    'faq.question.workshop.seo': 'Apa penggunaan SEO-Friendly-Address dalam berbagai pengaturan?',
    'faq.answer.workshop.seo': 'SEO-Friendly-Address adalah cara untuk membuat cerita, alam semesta, dan pos blog anda lebih terlihat oleh enjin carian dan URL yang lebih mudah dibaca oleh manusia. Ia adalah cara untuk menjadikan kerja anda lebih mudah ditemui dan membantu orang mencari kerja anda apabila mereka mencari sesuatu yang serupa.'
};