export default {
    'groups.listing.title': 'Kumpulan Pengguna',
    'groups.listing.organizationTitle': 'Pasukan',
    'groups.create.title': 'Cipta kumpulan baru',
    'groups.type.label': 'Jenis',
    'groups.type.open': 'Buka',
    'groups.type.openDesc': 'Terbuka - Sesiape boleh menyertai kumpulan ini.',
    'groups.type.closed': 'Ditutup',
    'groups.type.closedDesc': 'Tertutup - Orang perlu diluluskan sebelum mereka boleh menyertai kumpulan anda.',
    'groups.type.hidden': 'Tersembunyi',
    'groups.type.hiddenDesc': 'Tersembunyi - Hanya orang yang anda jemput boleh menyertai.',
    'groups.imageAlt': '{groupName} gambar',
    'groups.members': 'Ahli',
    'groups.members.total': `Tiada {totalMembers, plural,
    zero {ahli}
    one {ada seorang ahli}
    other {ada # ahli}
  } dalam kumpulan ini`,
    'groups.leaveGroup': 'Keluar dari kumpulan',
    'groups.leaveGroup.confirm': 'Hanya untuk pastikan. Adakah anda pasti ingin keluar dari {groupName}?',
    'group.settings': 'Tetapan kumpulan',
    'group.role.member': 'Ahli',
    'group.role.moderator': 'Moderator',
    'group.role.admin': 'Admin',
    'groups.join.openGroup': 'Sertai kumpulan',
    'groups.join.closedGroup': 'Mohon untuk menyertai kumpulan',
    'groups.join.questionToJoin': 'Soalan untuk ahli baru',
    'groups.join.closedAria': 'Borang permohonan untuk menyertai kumpulan tertutup',
    'groups.join.questionDefault': 'Mengapa anda patut dibenarkan menyertai?',
    'groups.join.pendingRequest': 'Permohonan anda untuk menyertai kumpulan ini sedang menunggu kelulusan daripada pentadbir kumpulan.',
    'groups.join.requesting': 'Memohon untuk menyertai',
    'groups.invite.btn': 'Jemput ke kumpulan',
    'groups.invite.modalAria': 'Dialog jemput pengguna ke kumpulan',
    'groups.invite.send': 'Hantar jemputan',
    'groups.invite.label': 'Cari pengguna untuk dijemput',
    'groups.invite.tileMsg': `Anda mempunyai {count, plural,
    other {# jemputan kumpulan}
  }`,
    'groups.invites.title': 'Jemputan kumpulan',
    'group.invite.accept': 'Terima jemputan',
    'group.noticeBoard': 'Papan notis',
    'group.leaveGroup.modalAria': 'Confirmation that you want to leave the group.',
    'group.leaveGroup.heading': 'Are you sure that you want to leave {groupName}?',
    'group.leaveGroup.explain': 'Leaving group means that you will loose access to the group resources and won\'t be able to interact with it.'
};