export default {
    'writer.menu.optionsAria': 'Menu pilihan editor',
    'writer.menu.saveOptionsAria': 'Simpan pilihan',
    'writer.undo': 'Undo',
    'writer.redo': 'Redo',
    'writer.ul': 'Senarai tidak teratur',
    'writer.ol': 'Senarai teratur',
    'writer.blockquote': 'Petikan',
    'writer.link': 'Masukkan pautan',
    'writer.image': 'Masukkan imej',
    'writer.bold': 'Tebalkan pilihan',
    'writer.underline': 'Garis bawah pilihan',
    'writer.italic': 'Penekanan pilihan',
    'writer.wordCount': '{characters, number} karakter, {words, number} perkataan',
    'writer.characterCount': '{characters, number} karakter',
    'finder.details': 'butiran',
    'finder.remove': 'Hapuskan sambungan',
    'finder.connect': 'Sambung pilihan ke entri ensiklopedia',
    'writer.aside.ariaLabel': 'Menu pilihan bantuan',
    'writer.nothingToSave': 'Tiada yang perlu disimpan',
    'writer.link.placeholder': 'Enter a URL',
    'writer.link.error.empty': 'URL cannot be empty',
    'writer.link.error.invalid': 'Please enter a valid URL',
    'writer.fontFamily': 'Font Family',
    'writer.fontFamily.select': 'Select font',
    'writer.image.upload': 'Upload Image',
    'writer.image.uploading': 'Uploading image...',
    'writer.image.error.type': 'Only JPEG, PNG, and WebP images are supported',
    'writer.image.error.size': 'Image must be less than 5MB',
    'writer.image.error.upload': 'Failed to upload image. Please try again.',
    'writer.publish.publishAria': 'Pilihan penerbitan',
    'writer.publish.scheduleExplained': 'Anda boleh sama ada menerbitkan dengan segera atau menjadualkan bab supaya tersedia pada tarikh kemudian.',
    'writer.publish.schedule': 'Tetapkan tarikh dan masa penerbitan',
    'writer.publish.previousChapterPublished': 'Bab sebelum ini diterbitkan pada {publishDate, date, short} pada {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'Bab sebelum ini dijadualkan untuk diterbitkan pada {publishDate, date, short} pada {publishDate, time}',
    'writer.publish.alreadyPublished': 'Bab ini telah diterbitkan pada {publishedAt, date, short}. Versi baru akan diterbitkan dengan segera.',
    'writer.publish.betaReader': 'Beta',
    'writer.publish.public': 'Terbitkan',
    'writer.publish.now': 'Publish now',
    'writer.publish.schedulePrevious': 'You need to publish or schedule publication of previous chapter before you can publish this one.',
    'writer.publish.earlyAccess.title': 'Early access for fans',
    'writer.publish.earlyAccess.groupLine': '{days} days early: {tiers} — fans get access on {date, date, short} at {date, time}'
};