export default {
    'challenges.current': 'বর্তমান চ্যালেঞ্জগুলি',
    'challenges.wordcount.goal': 'লক্ষ্য শব্দ গণনা',
    'challenges.wordcount.dailygoal': 'লক্ষ্য দৈনিক শব্দ গণনা',
    'challenges.wordcount.today': 'আজ লিখিত হয়েছে',
    'challenges.wordcount.total': 'মোট লিখিত শব্দ',
    'challenges.wordcount.remaining': 'অবশিষ্ট শব্দ',
    'challenges.wordcount.daysleft': 'বাকি আছে দিন',
    'challenges.wordcount.currentDay': 'বর্তমান দিন',
    'challenges.wordcount.average': 'প্রতিদিনের গড় শব্দ সংখ্যা',
    'challenges.wordcount.finishOn': 'বর্তমান গতি অনুযায়ী আপনি শেষ করবেন',
    'challenges.wordcount.finishOnTime': 'সময়ের মধ্যে শেষ করতে প্রতিদিন লিখতে হবে কত শব্দ',
    'challenges.wordcount.graph.day': 'দিন {day}',
    'challenges.underway': 'এই চ্যালেঞ্জটি ইতিমধ্যে চালু আছে।',
    'challenges.targetWords': 'মোট লক্ষ্যযুক্ত শব্দ গণনা',
    'challenges.startDate': 'শুরুর তারিখ',
    'challenges.endDate': 'শেষ তারিখ',
    'challenges.future': 'আসন্ন চ্যালেঞ্জগুলি',
    'challenges.future.wordcount': 'Wordcount challenge staring on {startDate, date, short} with goal of {target, number} by {endDate, date, short}.',
    'challenges.future.nanowrimo': 'NaNoWriMo চ্যালেঞ্জ প্রস্তুত আছে।',
    'challenges.wordcount': 'শব্দ গণনা',
    'challenges.wordcount.desc': `Set yourself a goal of how many words you want to write this month for this {type, select,
    story {story}
    universe {universe}
    other {}
  }.`,
    'challenges.wordcount.select': 'আপনি কত শব্দের চ্যালেঞ্জ নিতে চান?',
    'challenges.start': 'চ্যালেঞ্জ শুরু করুন',
    'challenges.report': 'রিপোর্ট',
    'challenges.victory': 'অভিনন্দন! আপনি এই চ্যালেঞ্জ সম্পন্ন করেছেন।',
    'challenges.defeat': 'দুঃখিত! আপনি এই চ্যালেঞ্জ সম্পন্ন করেননি।',
    'challenges.baseline': 'The current wordcount for this story is {wordcount, number}, this will be the starting point.',
    // NaNoWriMo
    'nanowrimo.full': 'ন্যাশনাল নভেল রাইটিং মাস',
    'nanowrimo.site': 'NaNoWriMo অফিসিয়াল সাইট',
    'nanowrimo.settings': 'NaNoWriMo অ্যাকাউন্ট',
    'nanowrimo.username': 'NaNoWriMo ব্যবহারকারীর নাম',
    'nanowrimo.key': 'গোপন কী',
    'nanowrimo.key.get': 'আপনার ন্যানোরাইমো কী পান।',
    'nanowrimo.key.get.notice': 'আপনাকে এটা দেখতে লগ ইন করা লাগবে।',
    'nanowrimo.ongoing': 'পূর্ণব্যাপারে চলছে! {countdown} আরো দিন বাকি!',
    'nanowrimo.startsin': `!শুরু হবে {countdown, plural,
      one {1 দিন}
      other {# দিন}
    }! প্রস্তুত হোন!`,
    'nanowrimo.isover': 'NaNoWriMo শেষ হয়ে গেছে। আগামী বছর দেখা হবে!',
    'nanowrimo.select': 'এই গল্পটি নিযুক্ত করুন NaNoWriMo জন্য।',
    'nanowrimo.baseline': 'NaNoWriMo শুরু হলে এটি বর্তমান শব্দগণনাটিকে নিজস্ব স্থানপ্রাপ্ত করবে এবং যেকোনো অতিরিক্ত শব্দগুলি এটিতে নিয়ে যাওয়া হবে যেটি NaNoWriMo এর অংশ হিসাবে গণ্য হবে।',
    'nanowrimo.victory': 'অভিনন্দন! আপনি NaNoWriMo জিতেছেন!',
    'nanowrimo.challenge': 'NaNoWriMo চ্যালেঞ্জ',
    'nanowrimo.description': 'চ্যালেঞ্জটি হল নভেম্বর মাসে {words, number} শব্দের একটি উপন্যাস লিখা।',
    'nanowrimo.error.usernotfound': 'ব্যবহারকারীর নামটি NaNoWriMo সার্ভারগুলিতে পাওয়া যায়নি।',
    'nanowrimo.error.nobook': 'কোনও বই পাওয়া যায়নি। দয়া করে নিশ্চিত করুন আপনি NaNoWriMo এ আপনার বইটি তৈরি করেছেন।',
    'nanowrimo.error.wordcount': 'NaNoWrimo এ শব্দগণনা সেট করতে অক্ষম, দয়া করে আপনার শংসাপত্রগুলি দ্বিতীয় বার পরীক্ষা করুন এবং আবার চেষ্টা করুন।',
    'nanowrimo.connected': 'আপনি এই গল্পটি NaNoWriMo জন্য নিযুক্ত করেছেন।',
    'nanowrimo.connected.other': 'আপনি ইতিমধ্যে অন্য একটি গল্পে সংযুক্ত হয়েছেন।'
};