export default {
  'courses.courses': 'Courses',
  'courses.overview': 'কোর্স ওভারভিউ',
  'course.create': 'নতুন কোর্স তৈরি করুন',
  'course.reading.title': 'Reading assignment title',
  'course.question.add': 'Add question',
  'course.add.module': 'Add module',
  'course.lessons.newMessage': 'Create and organize your lessons for effective teaching',
  'course.reading.new': 'Reading Assignment',
  'course.reading.newMessage': 'Create and organize reading assignments for your students',
  'course.writing.new': 'লেখার অ্যাসাইনমেন্ট',
  'course.writing.newMessage': 'Quickly set up and distribute writing tasks',
  'course.question.text': 'আপনার প্রশ্নটি এখানে লিখুন',
  'course.question.type': 'Please select a type of question',
  'course.question.delete': 'Remove question',
  'course.type': 'কোর্সের ধরণ নির্বাচন করুন',
  'course.visibility': 'দৃশ্যমানতা বিকল্প নির্বাচন করুন',
  'course.title': 'শিরোনাম',
  'course.description': 'বিবরণ',
  'course.cover': 'কভার',
  'course.start': 'আপনার কোর্স শুরু হয়',
  'course.ends': 'আপনার কোর্স শেষ হয়',
  'course.curriculum': 'পাঠ্যক্রম',
  'course.members': 'শিক্ষার্থী ও শিক্ষক',
  'course.assingments': 'অ্যাসাইনমেন্ট',
  'course.question.deleteWhole': 'পুরো প্রশ্ন মুছুন',
  'course.question.yes': 'হ্যাঁ',
  'course.question.no': 'না',
  'course.lesson.title': 'পাঠের শিরোনাম',
  'course.lesson.add.universe': 'গল্প/বিশ্ব যুক্ত করুন',
  'course.lesson.add.link': 'বাহ্যিক লিঙ্ক যুক্ত করুন',
  'course.status': 'Status',
  'course.active': 'Activity',
  'course.active.message': 'Active',
  'course.inactive': 'Inactive',
  'course.module.edit': 'Edit module name',
  'course.upload.resource': 'Upload a file resource',
  'course.question.answer': 'Add answer',
  'course.question.open': 'Open question',
  'course.question.close': 'Closed question',
  'course.question.multiple': 'Multiple-choice question',
};
