export default {
  'courses.courses': 'পাঠ্যক্রম',
  'courses.overview': 'কোর্স ওভারভিউ',
  'courses.public.title': 'Explore Courses',
  'courses.public.heading': 'Explore Courses',
  'courses.public.filters': 'Filter Courses',
  'courses.public.noResults': 'No courses found',
  'courses.public.tryDifferentFilters': 'Try different search terms or filters',
  'courses.filter.search': 'Search courses...',
  'courses.filter.allTypes': 'All Types',
  'courses.filter.clearAll': 'Clear All',
  'courses.filter.type': 'Type',
  'courses.type.course': 'Course',
  'courses.type.workshop': 'কর্মশালা',
  'courses.type.seminar': 'Seminar',
  'courses.type.course.lowercase': 'Course',
  'courses.type.workshop.lowercase': 'কর্মশালা',
  'courses.type.seminar.lowercase': 'Seminar',
  'course.create': 'নতুন কোর্স তৈরি করুন',
  'course.reading.title': 'পঠন অ্যাসাইনমেন্ট শিরোনাম',
  'course.question.add': 'প্রশ্ন যোগ করুন',
  'course.lessons.newMessage': 'কার্যকর শিক্ষাদানের জন্য আপনার পাঠ তৈরি ও সংগঠিত করুন।',
  'course.reading.new': 'পঠন নির্ধারণী',
  'course.reading.newMessage': 'আপনার শিক্ষার্থীদের জন্য পাঠের কাজ তৈরি ও সংগঠিত করুন।',
  'course.writing.new': 'লেখার অ্যাসাইনমেন্ট',
  'course.writing.newMessage': 'দ্রুত লেখার কাজগুলো সেট আপ ও বিতরণ করুন',
  'course.question.text': 'আপনার প্রশ্নটি এখানে লিখুন',
  'course.question.type': 'অনুগ্রহ করে প্রশ্নের ধরন নির্বাচন করুন',
  'course.question.delete': 'প্রশ্নটি সরান',
  'course.type': 'Course Type',
  'course.visibility': 'দৃশ্যমানতা বিকল্প নির্বাচন করুন',
  'course.title': 'শিরোনাম',
  'course.description': 'বিবরণ',
  'course.cover': 'কভার',
  'course.start': 'আপনার কোর্স শুরু হয়',
  'course.ends': 'আপনার কোর্স শেষ হয়',
  'course.curriculum': 'Course Curriculum',
  'course.members': 'শিক্ষার্থী ও শিক্ষক',
  'course.assignments': 'অ্যাসাইনমেন্টসমূহ',
  'course.question.deleteWhole': 'পুরো প্রশ্ন মুছুন',
  'course.question.yes': 'হ্যাঁ',
  'course.question.no': 'না',
  'course.lesson.title': 'পাঠের শিরোনাম',
  'course.lesson.add.universe': 'গল্প/বিশ্ব যুক্ত করুন',
  'course.lesson.externalLinks': 'External links',
  'course.lesson.add.link': 'বাহ্যিক লিঙ্ক যুক্ত করুন',
  'course.status': 'অবস্থা',
  'course.active': 'ক্রিয়াকলাপ',
  'course.active.message': 'সক্রিয়',
  'course.inactive': 'অকার্যকর',
  'course.upload.resource': 'Upload a resource',
  'course.question.answer': 'উত্তর যোগ করুন',
  'course.question.open': 'খোলা প্রশ্ন',
  'course.question.close': 'বন্ধ প্রশ্ন',
  'course.question.multiple': 'বহু-বিকল্পের প্রশ্ন',
  'course.about': 'এই কোর্স সম্পর্কে',
  'course.lesson.new': 'একটি নতুন পাঠ তৈরি করুন',
  'course.lesson.type': 'পাঠের ধরন',
  'course.lesson.inPerson': 'ব্যক্তিগতভাবে',
  'course.lesson.preRecorded': 'আগে রেকর্ড করা',
  'course.lesson.online': 'অনলাইন',
  'course.lesson.text': 'শুধুমাত্র পাঠ্য',
  'course.lesson.content': 'পাঠের বিষয়বস্তু',
  'course.lesson.description': 'জনসাধারণের বর্ণনা',
  'course.add.story': 'গল্প যোগ করুন',
  'course.remove.story': 'গল্পটি সরান',
  'course.dateOfPublish': 'প্রকাশের তারিখ',
  'course.lesson.meetInPerson': 'ব্যক্তিগতভাবে দেখা করুন',
  'course.curriculum.edit': 'পাঠ্যক্রম সম্পাদনা করুন',
  'course.stories.own': 'আপনার নিজস্ব গল্পগুলো',
  'course.stories.organization': 'সংস্থার গল্প',
  'course.stories.public': 'জনসাধারণের গল্প',
  'course.publish.at': 'আমি চাই এই কোর্সটি এখানে প্রকাশিত হোক:',
  'course.edit.curriculum': 'পাঠ্যক্রম সম্পাদনা করুন',
  'course.assignment': 'অ্যাসাইনমেন্ট',
  'course.lesson.removeLink': 'লিঙ্ক সরান',
  'course.user.remove': 'Remove user',
  'course.user.invite': 'Invite user',
  'course.user.invited': 'Invited',
  'course.edit.role': 'ভূমিকা সম্পাদনা করুন',
  'course.assignment.description': 'অ্যাসাইনমেন্টের বিবরণ',
  'course.internal': 'আভ্যন্তরীণ',
  'course.free': 'বিনামূল্যে',
  'course.sale': 'বিক্রি',
  'course.announcements': 'Announcements',
  'course.announcements.full': 'Course announcements',
  'course.announcements.create': 'Create an announcement',
  'course.join': 'Join Course',
  'course.joining': 'Joining...',
  'course.join.success': 'You have successfully joined this course!',
  'course.join.error.payment': 'This course requires payment to join.',
  'course.join.error.invite': 'This course requires an invitation to join.',
  'course.join.error.generic': 'There was an error joining the course. Please try again.',
  'course.firstLesson': 'First Lesson',
  'course.upcomingLessons': 'Upcoming Lessons',
  'course.detail.title': '{courseName} | Course',
  'lessons.visibility.public': 'Public',
  'lessons.visibility.private': 'Private',
  'course.curriculum.empty': 'No curriculum items available yet.',
  'course.preview.message': 'This is a preview of the course. Join the course to access all content.',
  'course.details': 'Course Details',
  'course.tab.curriculum': 'Curriculum',
  'course.tab.details': 'Course Details',
  'course.duration': 'Duration',
  'course.perpetual': 'Perpetual',
  'course.language': 'Language',
  'course.price': 'Price',
  'course.learningObjectives': 'Learning Objectives',
  'course.prerequisites': 'Prerequisites',
  'course.tags': 'Tags',
  'course.stats.members': 'Members',
  'course.stats.lessons': 'Lessons',
  'course.assignments.comingSoon': 'Assignments view is coming soon.',
  'course.progress.comingSoon': 'Progress tracking is coming soon.',
  'course.type.free': 'বিনামূল্যে',
  'course.type.paid': 'Paid',
  'course.type.forSale': 'For Sale',
  'course.type.invite': 'Invite Only',
  'courses.invites.tile': 'You are invited to partake in {count, plural, one {course} other {courses}}.',
  'courses.invites.noInvites': "You don't have any course invitations at the moment.",
  'courses.invites.invitedBy': 'Invited by: ',
  'course.join.heading': 'Join This Course',
  'course.oneTimePayment': 'One-time payment for full access',
  'course.member': "You're Enrolled",
  'course.member.access': 'You have full access to all course materials.',
  'courses.members.editRole': 'Edit Role',
  'courses.members.editRoleFor': 'Edit role for:',
  'courses.add.member': 'Add a new member',
  'course.member.options': 'Course member list',
  'course.navigation.curriculum': 'Curriculum',
  'course.navigation.members': 'Students & Teachers',
  'course.navigation.assignments': 'অ্যাসাইনমেন্টসমূহ',
  'course.navigation.forums': 'Forums',
  'course.navigation.attendance': 'Attendance',
  'course.members.teachers': 'Teachers',
  'course.members.students': 'Students',
  'course.members.preview.message': 'Join this course to see all students and interact with the community.',
  'course.member.role.owner': 'মালিক',
  'course.member.role.teacher': 'শিক্ষক',
  'course.member.role.student': 'ছাত্র',
  'course.lesson.internalLinks': 'Works on Literary Universe',
  'course.lesson.internalLinks.description':
    'Select stories or universes to link to this lesson. These will be available to students as additional resources.',
  'course.startDate': 'Start Date',
  'course.endDate': 'End Date',
  'course.date.format': '{date, date, long}',
  'course.curriculum.preview': 'Curriculum Preview',
  'course.curriculum.preview.message': 'Join this course to access all {count} lessons and assignments.',
  'course.curriculum.locked': 'Locked',
  'course.curriculum.lesson': 'Lesson',
  'course.curriculum.assignment': 'অ্যাসাইনমেন্ট',
  'course.curriculum.reading': 'Reading',
  'course.lesson.backToCurriculum': 'Back to Curriculum',
  'course.lesson.nextLesson': 'Next Lesson',
  'course.lesson.documents': 'Documents & Resources',
  'course.lesson.meetingLink': 'Meeting Link',
  'course.lesson.location': 'Location',
  'course.lesson.virtualClassroom': 'Virtual Classroom',
  'course.lesson.joinClassroom': 'Join the virtual classroom session',
  'course.lesson.enterClassroom': 'Enter Classroom',
  'course.assignment.acceptsStories': 'গল্প গ্রহণ করে',
  'course.assignment.acceptsUniverses': 'ব্ৰহ্মাণ্ডগুলো গ্রহণ করে',
  'course.assignment.backToAssignments': 'অ্যাসাইনমেন্টে ফিরে যান',
  'course.assignment.criteria': 'পঠন মানদণ্ড',
  'course.assignment.dueDate': 'জমা দেওয়ার সময়: {date}',
  'course.assignment.freeReading': 'বিনামূল্যে পাঠ্য পড়া সক্ষম',
  'course.assignment.grade': 'গ্রেড',
  'course.assignment.grade.received': 'গ্রেড: {grade}',
  'course.assignment.gradeSaveError': 'গ্রেড সংরক্ষণ করতে অক্ষম',
  'course.assignment.gradeSaved': 'গ্রেড সংরক্ষিত হয়েছে।',
  'course.assignment.gradedCount': '{count, plural, one {# গ্রেড করা হয়েছে} other {# গ্রেড করা হয়েছে}}',
  'course.assignment.grading.help':
    'ছাত্রদের জমা দেওয়া কাজ পর্যালোচনা করুন, সংযুক্ত গল্প বা মহাবিশ্বগুলো খুলুন, এবং ঐচ্ছিক গ্রেড ও প্রতিক্রিয়া যোগ করুন।',
  'course.assignment.grading.title': 'গ্রেডিং: {title}',
  'course.assignment.grading.unavailable': 'গ্রেডিং অনুপলব্ধ',
  'course.assignment.grading.unavailableMessage':
    'আপনার এই গ্রেডিং পৃষ্ঠায় অ্যাক্সেস নেই, অথবা অ্যাসাইনমেন্টটি পাওয়া যায়নি।',
  'course.assignment.lastRead': 'শেষে পড়া {date}',
  'course.assignment.minutes': '{count} মিনিট',
  'course.assignment.noSubmissions': 'এখনও কোনো জমা পড়েনি।',
  'course.assignment.noWrittenResponse': 'লিখিত কোনো প্রতিক্রিয়া দেওয়া হয়নি।',
  'course.assignment.notFound': 'অ্যাসাইনমেন্ট পাওয়া যায়নি',
  'course.assignment.notFoundMessage': 'অনুরোধকৃত অ্যাসাইনমেন্টটি পাওয়া যায়নি।',
  'course.assignment.noteForTeacher': 'আপনার শিক্ষকের জন্য একটি নোট যোগ করুন',
  'course.assignment.open': 'খোলা অ্যাসাইনমেন্ট',
  'course.assignment.openGrading': 'গ্রেডিং পৃষ্ঠা খুলুন',
  'course.assignment.questions': 'প্রশ্নসমূহ',
  'course.assignment.readingProgress': 'ছাত্রের পাঠ অগ্রগতি',
  'course.assignment.readings': 'নির্ধারিত পাঠ্যাংশ',
  'course.assignment.responsePlaceholder': 'আপনার প্রতিক্রিয়া এখানে লিখুন',
  'course.assignment.responsePrompt': 'প্রবন্ধের বিষয় বা জার্নাল প্রম্পট',
  'course.assignment.selectStoriesRead':
    'এই অ্যাসাইনমেন্টের জন্য আপনি যে গল্পগুলো বেছে নিয়েছেন, সেগুলো নির্বাচন করুন।',
  'course.assignment.sharedProject.studentHelp':
    'উপরের শেয়ার করা প্রকল্পগুলির একটি Workshop-এ খুলুন এবং সেখানে অবদান করুন। এই অ্যাসাইনমেন্টের জন্য আলাদা কোনো জমা ফর্মের প্রয়োজন নেই।',
  'course.assignment.sharedProject.studentTitle': 'এই অ্যাসাইনমেন্টটি কীভাবে সম্পন্ন করবেন',
  'course.assignment.sharedProject.teacherNotice':
    'এই যৌথ-প্রকল্পের অ্যাসাইনমেন্টে ব্যক্তিগত জমা দেওয়ার পরিবর্তে সহযোগী অ্যাক্সেস ব্যবহার করা হয়।',
  'course.assignment.sharedProjects': 'ভাগ করা প্রকল্প কাজ',
  'course.assignment.storiesCompleted': 'সম্পূর্ণ গল্পসমূহ',
  'course.assignment.submissionCount': '{count, plural, one {# submission} other {# submissions}}',
  'course.assignment.submissionSaved': 'জমা সফল হয়েছে।',
  'course.assignment.submissions': 'জমা এবং মূল্যায়ন',
  'course.assignment.submit': 'অ্যাসাইনমেন্ট জমা দিন',
  'course.assignment.submitError': 'অ্যাসাইনমেন্ট জমা দিতে অক্ষম',
  'course.assignment.submitWork': 'জমা দেওয়ার জন্য কাজ নির্বাচন করুন',
  'course.assignment.submitWork.help':
    'এই অ্যাসাইনমেন্টের জন্য কোন গল্প বা মহাবিশ্বটি মূল্যায়ন করা হবে তা নির্বাচন করুন।',
  'course.assignment.submitWork.label': 'জমা দেওয়া কাজ',
  'course.assignment.submitWork.placeholder': 'একটি গল্প বা মহাবিশ্ব নির্বাচন করুন',
  'course.assignment.submittedAt': 'দাখিল করা হয়েছে {date}',
  'course.assignment.submittedWork.story': 'প্রেরিত গল্প: {title}',
  'course.assignment.submittedWork.universe': 'জমা দেওয়া মহাবিশ্ব: {title}',
  'course.assignment.supportingFiles': 'সহায়ক উপকরণসমূহ আপলোড করা হয়েছে',
  'course.assignment.supportingMaterials': 'সহায়ক উপকরণ',
  'course.assignment.updateSubmission': 'আপডেট জমা দিন',
  'course.assignment.yourSubmission': 'আপনার জমা',
  'courses.role.owner': 'মালিক',
  'courses.role.teacher': 'শিক্ষক',
  'courses.role.student': 'ছাত্র',
};
