export default {
    'encyclopedia.add': 'একটি নতুন এন্ট্রি যুক্ত করুন',
    'encyclopedia.browse': 'এনসাইক্লোপিডিয়ায় ব্রাউজ করুন',
    'encyclopedia.search': 'এনসাইক্লোপিডিয়ায় অনুসন্ধান করুন',
    'canvas.toolbar.add': 'Add:',
    'canvas.toolbar.text': 'Text',
    'canvas.toolbar.link': 'Link',
    'canvas.toolbar.group': 'Group',
    'canvas.toolbar.entry': 'Entry',
    'canvas.encPicker.title': 'Pick an encyclopedia entry',
    'canvas.encPicker.search': 'Search entries…',
    'canvas.dialog.pickEntry': 'Pick encyclopedia entry',
    'canvas.node.link': 'Link',
    'canvas.node.encEntry': 'Entry',
    'canvas.entry.open': 'Double-click to open entry',
    'encyclopedia.back.universe': 'মহাকাশ পৃষ্ঠায় ফিরে যান',
    'encyclopedia.back.workshop': 'কারখানায় ফিরে যান',
    'encyclopedia.categories': 'বিভাগসমূহ',
    'encyclopedia.groups': 'গোষ্ঠীসমূহ',
    'encyclopedia.category.character': 'চরিত্রসমূহ',
    'encyclopedia.category.event': 'ঘটনাসমূহ',
    'encyclopedia.category.group': 'গোষ্ঠীসমূহ',
    'encyclopedia.category.item': 'পদার্থসমূহ',
    'encyclopedia.category.location': 'অবস্থানসমূহ',
    'encyclopedia.category.other': 'অন্যান্য',
    'encyclopedia.category.state': 'রাষ্ট্রসমূহ',
    'encyclopedia.category.governments': 'সরকারসমূহ',
    'encyclopedia.category.languages': 'ভাষাসমূহ',
    'encyclopedia.category.creatures': 'প্রাণীসমূহ',
    'encyclopedia.category.deity': 'দেবতাসমূহ',
    'encyclopedia.category.religions': 'ধর্মসমূহ',
    'encyclopedia.category.flora': 'উদ্ভিদসমূহ',
    'encyclopedia.category.magic': 'জাদু',
    'encyclopedia.category.planets': 'গ্রহসমূহ',
    'encyclopedia.category.species': 'প্রজাতিসমূহ',
    'encyclopedia.category.technologies': 'প্রযুক্তিসমূহ',
    'encyclopedia.category.families': 'Families',
    'encyclopedia.category.jobs': 'Jobs',
    'encyclopedia.category.lore': 'Lore',
    'encyclopedia.category.vehicles': 'Vehicles',
    'encyclopedia.category.diseases': 'Diseases',
    'encyclopedia.category.traditions': 'Traditions',
    'encyclopedia.category.sports': 'Sports',
    'encyclopedia.category.food': 'Food',
    'encyclopedia.category.landmarks': 'Landmarks',
    'encyclopedia.category.buildings': 'Buildings',
    'encyclopedia.category.schools': 'Schools',
    'encyclopedia.category.continents': 'Continents',
    'encyclopedia.category.villages': 'Villages',
    'encyclopedia.category.towns': 'Towns',
    'encyclopedia.category.cities': 'Cities',
    'encyclopedia.category.settlements': 'Settlements',
    'encyclopedia.category.countries': 'Countries',
    'encyclopedia.search.found': '{results, plural,\n    =0 {No related entries}\n    one {1 related entry}\n    other {# related entries}\n  } found.',
    'encyclopedia.help.text': 'এনসাইক্লোপিডিয়াতে আইটেমগুলির মধ্যে সঞ্চয় করতে বামের মেনুটি ব্যবহার করুন। একটি আইটেম নির্বাচন করলে, এটি এই পাঠ্যটির পরিবর্তে প্রদর্শিত হবে।',
    'encyclopedia.help.sidebar': 'সাইডবার টুলবক্স',
    'encyclopedia.help.sidebar.text': 'Welcome to your story! This sidebar allows you easy access to all resources related to your story. Check the icons above to see the latest comments, your notes, search your encyclopedia, browse and add new entries to your encyclopedia. If you want to add a connection to an entry from the story text, select the text where you want to place it and then click the connect button. You will then be prompted to find and select an item.',
    'encyclopedia.intro': 'স্বাগতম {universe} এনসাইক্লোপিডিয়াতে।',
    'encyclopedia.add.title': 'নতুন এন্ট্রি যোগ করুন এনসাইক্লোপিডিয়ায়',
    'encyclopedia.add.heading': 'আপনি কী যোগ করতে চান?',
    'encyclopedia.add.moresoon': 'আসছে আরও ক্যাটাগরি!',
    'encyclopedia.create': 'Create new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {villages}\n    towns {towns}\n    cities {cities}\n    settlements {settlement}\n    countries {country}\n  }',
    'encyclopedia.create.header': 'Creating a new {category, select,\n    character {character}\n    event {event}\n    group {group}\n    item {item}\n    location {location}\n    other {note}\n    state {state}\n    governments {government}\n    languages {language}\n    creatures {creature}\n    deity {deity}\n    religions {religion}\n    flora {flora}\n    magic {magic}\n    planets {planet}\n    species {specie}\n    technologies {technology}\n    families {family}\n    jobs {job}\n    lore {lore}\n    vehicles {vehicle}\n    diseases {disease}\n    traditions {tradition}\n    food {food}\n    sports {sport}\n    landmarks {landmark}\n    buildings {building}\n    schools {school}\n    continents {continent}\n    villages {village}\n    towns {town}\n    cities {city}\n    settlements {settlement}\n    countries {country}\n  } in {universe}',
    'encyclopedia.entry.category': 'Entry category: {category, select,\n    character {Character}\n    event {Event}\n    group {Group}\n    item {Item}\n    location {Location}\n    other {Note}\n    state {State}\n    governments {Government}\n    languages {Language}\n    creatures {Creature}\n    deity {Deity}\n    religions {Religion}\n    flora {Flora}\n    magic {Magic}\n    planets {Planet}\n    species {Specie}\n    technologies {Technology}\n    families {Family}\n    jobs {Job}\n    lore {Lore}\n    vehicles {Vehicle}\n    diseases {Disease}\n    traditions {Tradition}\n    food {Food}\n    sports {Sport}\n    landmarks {Landmark}\n    buildings {Building}\n    schools {School}\n    continents {Continent}\n    villages {Village}\n    towns {Town}\n    cities {City}\n    settlements {Settlement}\n    countries {Country}\n  }',
    'encyclopedia.entry.category.legend': 'বিভাগ',
    'encyclopedia.fields.add': 'নতুন ক্ষেত্র যোগ করুন',
    'encyclopedia.fields.text': 'সংজ্ঞা',
    'encyclopedia.fields.textarea': 'পাঠ্য',
    'encyclopedia.fields.connection': 'সংযোগ',
    'encyclopedia.fields.time': 'সময়',
    'encyclopedia.fields.image': 'চিত্র',
    'encyclopedia.fields.canvas': 'Canvas',
    'encyclopedia.visibility': 'দৃশ্যমানতা',
    'encyclopedia.public': 'পাবলিক',
    'encyclopedia.private': 'প্রাইভেট',
    'encyclopedia.container': 'কন্টেনার',
    'encyclopedia.container.desc': 'Make this entry a container for a new group of entries. This will hide it from the categories listing.',
    'encyclopedia.entry.name': 'এন্ট্রিটির নাম',
    'encyclopedia.summary': 'সংক্ষিপ্তসার',
    'encyclopedia.summary.desc': 'This is a summary that will be the only initial information displayed to the reader.',
    'encyclopedia.parent': 'প্যারেন্ট এন্ট্রি',
    'encyclopedia.related': 'সম্পর্কিত নির্দেশিকা',
    'encyclopedia.errors.tags': 'প্রতি এন্ট্রিতে আপনি কেবলমাত্র 10 ট্যাগ থাকতে পারেন।',
    'encyclopedia.field.private': 'প্রাইভেট ফিল্ড',
    'encyclopedia.spoiler.label': 'Contains spoilers for {story}',
    'encyclopedia.spoiler.chapterLabel': 'Spoiler for {story}, Chapter {chapter}',
    'encyclopedia.spoiler.multipleLabel': 'Contains spoilers for multiple stories',
    'encyclopedia.spoiler.generic': 'Contains spoilers',
    'encyclopedia.spoiler.reveal': 'Reveal spoiler',
    'encyclopedia.spoiler.scope.story': 'Story',
    'encyclopedia.spoiler.scope.story.placeholder': 'Select story',
    'encyclopedia.spoiler.scope.chapter': 'Chapter number',
    'encyclopedia.spoiler.scope.remove': 'Remove spoiler scope',
    'encyclopedia.spoiler.scope.add': 'Mark as spoiler',
    'encyclopedia.spoiler.scope.addStory': 'Add story',
    'encyclopedia.spoiler.scope.removeStory': 'Remove story',
    'encyclopedia.spoiler.scope.manage': 'Manage spoiler scope',
    'encyclopedia.spoiler.scope.manageShort': 'Spoiler',
    'encyclopedia.spoiler.scope.summary': '{count, plural, one {# story} other {# stories}}',
    'encyclopedia.spoiler.scope.chapterSummary': 'Chapter {chapter}',
    'encyclopedia.spoiler.scope.description': 'Mark this field as a spoiler. Readers who haven\'t reached the required point in these stories will see the content blurred.',
    'encyclopedia.spoiler.scope.storyChapterHint': 'Choose the chapter readers must reach before this field is shown by default.',
    'encyclopedia.spoiler.scope.storyCompletion': 'Readers must finish this story before this field is shown by default.',
    'encyclopedia.spoiler.scope.noStories': 'No stories from this universe are available yet.',
    'encyclopedia.spoiler.scope.privatePrecedence': 'Private fields are never sent to readers, so spoiler scope has no effect while the field is private.',
    'encyclopedia.ft.indev': 'এই অপশনটি উন্নত হচ্ছে।',
    'encyclopedia.connections.remove': 'সংযোগ সরানো হচ্ছে',
    'encyclopedia.connections.extra': 'অতিরিক্ত তথ্য',
    'encyclopedia.connections.existing': 'বিদ্যমান এন্ট্রি',
    'encyclopedia.connections.existing.abbr': 'ইই',
    'encyclopedia.cover': 'কভার ইমেজ',
    'encyclopedia.translation.title': 'আপনাকে স্বাগতম জানাই {universe} ইউনিভার্স অনুবাদে!',
    'encyclopedia.translation.desc': 'এই এন্সাইক্লোপিডিয়া ইন্টারফেসটি ব্যবহার করে {language}এ অনুবাদ করা হয়। শুরু করতে বামের তালিকায় বিদ্যমান এন্ট্রিগুলি চয়ন করুন।',
    'encyclopedia.welcome.totalEntries': 'There {totalEntries, plural, \n    zero {are no entries}\n    one {is one entry}\n    other {are # entries}\n  } in this universe.',
    'encyclopedia.settings.title': 'এন্সাইক্লোপিডিয়া সেটিংস',
    'encyclopedia.settings.categoriesDesc': 'আপনি যে বিভাগগুলি আপনার এন্সাইক্লোপিডিয়ায় ব্যবহার করতে চান তা চালু এবং বন্ধ করুন।',
    'encyclopedia.settings.introText': 'ইউনিভার্স বর্ণনা পরে প্রদর্শিত হবে স্বাগত বার্তা।',
    'encyclopedia.fields.placeholder': 'ক্ষেত্রের নাম',
    'encyclopedia.fields.delete': 'ক্ষেত্র মুছে ফেলুন',
    'encyclopedia.timeOption.fictionalDate': 'কল্পকাহিনী তারিখ',
    'encyclopedia.timeOption.fictionalTime': 'কল্পকাহিনী সময়',
    'encyclopedia.timeOption.fictionalDateTime': 'কল্পকাহিনী তারিখ এবং সময়',
    'encyclopedia.timeOption.date': 'তারিখ',
    'encyclopedia.timeOption.time': 'সময়',
    'encyclopedia.timeOption.dateTime': 'তারিখ এবং সময়',
    'encyclopedia.settings.groupByCategories': 'গ্রুপ লিস্টিংয়ে বিভাগগুলি অন্তর্ভুক্ত করুন',
    'encyclopedia.menuOpen': 'এন্সাইক্লোপিডিয়া মেনু খুলুন',
    'encyclopedia.menuClose': 'এন্সাইক্লোপিডিয়া মেনু বন্ধ করুন',
    'encyclopedia.menuAria': 'এন্সাইক্লোপিডিয়া মেনু',
    'enc.newField': 'নতুন ক্ষেত্র',
    'enc.entries.limit': 'You currently have {value, number} out of {max, plural,\n    =0 {unlimited}\n    other {{max, number}}\n  } entries.',
    'enc.entries.limitReached': 'আপনি আপনার বর্তমান সাবস্ক্রিপশনের জন্য অনুমোদিত এনসাইক্লোপিডিয়া এন্ট্রিগুলির সর্বাধিক সীমা অবুদ্ধ করেছেন।',
    'encyclopedia.pronunciation.title': 'উচ্চারণ',
    'encyclopedia.wip.abbreviation': 'WIP',
    'encyclopedia.wip.full': 'চলমান প্রকল্প',
    'encyclopedia.settings.templateLegend': 'টেমপ্লেট বিশ্ব',
    'encyclopedia.settings.templateDescription': 'এই বিশ্বের বিষয়বস্তুটি অন্যান্য বিশ্বগুলিতে কপি করা যেতে পারে। এটি সেই সময়টি সবচেয়ে ভাল যখন আপনার কোনও গল্প নেই এবং আপনি শুধুমাত্র অন্যদের জন্য একটি টেমপ্লেট তৈরি করছেন।',
    'encyclopedia.settings.templateCheckbox': 'এটি একটি টেমপ্লেট বিশ্ব',
    'encyclopedia.templateCopy.modalTitle': 'বিশ্বের বিষয়বস্তু কপি করুন',
    'encyclopedia.templateCopy.description': 'এই বিশ্বের বিষয়বস্তুটি আপনার বিশ্বে কপি করে তা সমৃদ্ধ করুন।',
    'encyclopedia.templateCopy.targetUniverse': 'কপি করার জন্য বিশ্ব',
    'encyclopedia.templateCopy.finished': 'অনুলিপি সম্পন্ন হয়েছে',
    'encyclopedia.templateCreateUniverse.modalTitle': 'Create universe from template',
    'encyclopedia.templateCreateUniverse.description': 'Create a new universe with pre-seeded encyclopedia content from this template. Your universe will remain private until you decide to make it public.',
    'encyclopedia.templateCreateUniverse.success': 'Universe created successfully! Redirecting...',
    'encyclopedia.pronunciation.audio.play': 'Play pronunciation',
    'encyclopedia.pronunciation.guide': 'Use <ipaLink>IPA notation</ipaLink> when possible. Web Speech API pronunciation is best-effort; see <webSpeechLink>MDN docs</webSpeechLink>.',
    'encyclopedia.templateField.born': 'Born',
    'encyclopedia.templateField.died': 'Died',
    'encyclopedia.templateField.race': 'Race',
    'encyclopedia.templateField.gender': 'Gender',
    'encyclopedia.templateField.partners': 'Partners',
    'encyclopedia.templateField.parents': 'Parents',
    'encyclopedia.templateField.children': 'শিশু',
    'encyclopedia.templateField.associated-with': 'Associated with',
    'encyclopedia.templateField.biography': 'Biography',
    'encyclopedia.templateField.physical-appearance': 'Physical appearance',
    'encyclopedia.templateField.type-of-event': 'Type of event',
    'encyclopedia.templateField.preceding-events': 'Preceding events',
    'encyclopedia.templateField.following-events': 'Following events',
    'encyclopedia.templateField.leadup': 'Leadup',
    'encyclopedia.templateField.description': 'Description',
    'encyclopedia.templateField.aftermath': 'Aftermath',
    'encyclopedia.templateField.members': 'Members',
    'encyclopedia.templateField.locations': 'Locations',
    'encyclopedia.templateField.events': 'Events',
    'encyclopedia.templateField.vision': 'Vision',
    'encyclopedia.templateField.mission': 'Mission',
    'encyclopedia.templateField.description-of-the-organization': 'Description of the organization',
    'encyclopedia.templateField.history': 'ইতিহাস',
    'encyclopedia.templateField.owners': 'Owners',
    'encyclopedia.templateField.function': 'Function',
    'encyclopedia.templateField.content': 'Content',
    'encyclopedia.templateField.population': 'Population',
    'encyclopedia.templateField.culture': 'Culture',
    'encyclopedia.templateField.governments': 'Governments',
    'encyclopedia.templateField.religions-believes': 'Religions & believes',
    'encyclopedia.templateField.languages': 'Languages',
    'encyclopedia.templateField.geography': 'Geography',
    'encyclopedia.templateField.founding': 'Founding',
    'encyclopedia.templateField.notable-events': 'Notable events',
    'encyclopedia.templateField.notes': 'Notes',
    'encyclopedia.templateField.type-of-government': 'Type of government',
    'encyclopedia.templateField.structure': 'Structure',
    'encyclopedia.templateField.power-structure': 'Power structure',
    'encyclopedia.templateField.source-of-power': 'Source of power',
    'encyclopedia.templateField.laws': 'Laws',
    'encyclopedia.templateField.ideology': 'Ideology',
    'encyclopedia.templateField.internal-politics': 'Internal politics',
    'encyclopedia.templateField.external-politics': 'External politics',
    'encyclopedia.templateField.leading-figures': 'Leading figures',
    'encyclopedia.templateField.groups': 'গোষ্ঠীসমূহ',
    'encyclopedia.templateField.military': 'Military',
    'encyclopedia.templateField.items': 'Items',
    'encyclopedia.templateField.typology': 'Typology',
    'encyclopedia.templateField.dialectics': 'Dialectics',
    'encyclopedia.templateField.phonology': 'Phonology',
    'encyclopedia.templateField.grammar': 'Grammar',
    'encyclopedia.templateField.numbers': 'Numbers',
    'encyclopedia.templateField.quantifiers': 'Quantifiers',
    'encyclopedia.templateField.private-notes': 'Private notes',
    'encyclopedia.templateField.type': 'Type',
    'encyclopedia.templateField.notable-features': 'Notable features',
    'encyclopedia.templateField.traits': 'Traits',
    'encyclopedia.templateField.habitat': 'Habitat',
    'encyclopedia.templateField.food-sources': 'Food sources',
    'encyclopedia.templateField.reproduction': 'Reproduction',
    'encyclopedia.templateField.cultural-significance': 'Cultural significance',
    'encyclopedia.templateField.related-creatures': 'Related creatures',
    'encyclopedia.templateField.religion': 'Religion',
    'encyclopedia.templateField.other-names': 'Other names',
    'encyclopedia.templateField.appearance': 'Appearance',
    'encyclopedia.templateField.related-to': 'Related to',
    'encyclopedia.templateField.symbolism': 'Symbolism',
    'encyclopedia.templateField.rituals': 'Rituals',
    'encyclopedia.templateField.origin': 'Origin',
    'encyclopedia.templateField.notable-figures': 'Notable figures',
    'encyclopedia.templateField.deities': 'Deities',
    'encyclopedia.templateField.artifacts': 'Artifacts',
    'encyclopedia.templateField.believes': 'Believes',
    'encyclopedia.templateField.traditions': 'Traditions',
    'encyclopedia.templateField.spread': 'Spread',
    'encyclopedia.templateField.classification': 'Classification',
    'encyclopedia.templateField.features': 'Features',
    'encyclopedia.templateField.produce': 'Produce',
    'encyclopedia.templateField.ecosystem': 'Ecosystem',
    'encyclopedia.templateField.effect': 'Effect',
    'encyclopedia.templateField.alignment': 'Alignment',
    'encyclopedia.templateField.requirements': 'Requirements',
    'encyclopedia.templateField.size': 'Size',
    'encyclopedia.templateField.length-of-day': 'Length of day',
    'encyclopedia.templateField.length-of-night': 'Length of night',
    'encyclopedia.templateField.length-of-cycle': 'Length of cycle',
    'encyclopedia.templateField.moons': 'Moons',
    'encyclopedia.templateField.nearby-stellar-bodies': 'Nearby stellar bodies',
    'encyclopedia.templateField.climate': 'Climate',
    'encyclopedia.templateField.weather': 'Weather',
    'encyclopedia.templateField.natural-resources': 'Natural resources',
    'encyclopedia.templateField.notable-locations': 'Notable locations',
    'encyclopedia.templateField.inhabitans': 'Inhabitans',
    'encyclopedia.templateField.looks': 'Looks',
    'encyclopedia.templateField.production': 'Production',
    'encyclopedia.templateField.use': 'Use',
    'encyclopedia.templateField.related': 'Related',
    'encyclopedia.templateField.location': 'Location',
    'encyclopedia.templateField.significance': 'Significance',
    'encyclopedia.templateField.associated-events': 'Associated events',
    'encyclopedia.templateField.associated-figures': 'Associated figures',
    'encyclopedia.templateField.access-restrictions': 'Access restrictions',
    'encyclopedia.templateField.cultural-importance': 'Cultural importance',
    'encyclopedia.templateField.founded': 'Founded',
    'encyclopedia.templateField.government': 'Government',
    'encyclopedia.templateField.defenses': 'Defenses',
    'encyclopedia.templateField.connected-settlements': 'Connected settlements',
    'encyclopedia.templateField.family-motto': 'Family Motto',
    'encyclopedia.templateField.founding-date': 'Founding Date',
    'encyclopedia.templateField.ethos': 'Ethos',
    'encyclopedia.templateField.family-reputation': 'Family Reputation',
    'encyclopedia.templateField.family-branches': 'Family Branches',
    'encyclopedia.templateField.notable-vassals-retainers': 'Notable vassals/retainers',
    'encyclopedia.templateField.skills-required': 'Skills required',
    'encyclopedia.templateField.pay-salary': 'Pay/Salary',
    'encyclopedia.templateField.associated-locations': 'Associated locations',
    'encyclopedia.templateField.associated-characters': 'Associated characters',
    'encyclopedia.templateField.propulsion': 'Propulsion',
    'encyclopedia.templateField.capacity': 'Capacity',
    'encyclopedia.templateField.speed': 'Speed',
    'encyclopedia.templateField.manufacturers': 'Manufacturers',
    'encyclopedia.templateField.symptoms': 'Symptoms',
    'encyclopedia.templateField.causes': 'Causes',
    'encyclopedia.templateField.treatment': 'Treatment',
    'encyclopedia.templateField.affected-species': 'Affected species',
    'encyclopedia.templateField.associated-groups': 'Associated groups',
    'encyclopedia.templateField.ingredients': 'Ingredients',
    'encyclopedia.templateField.preparation': 'Preparation',
    'encyclopedia.templateField.rules': 'Rules',
    'encyclopedia.templateField.equipment': 'Equipment',
    'encyclopedia.templateField.venues': 'Venues',
    'encyclopedia.templateField.architecture': 'Architecture',
    'encyclopedia.templateField.curriculum': 'Curriculum',
    'encyclopedia.templateField.notable-alumni': 'Notable alumni',
    'encyclopedia.templateField.affiliation': 'Affiliation',
    'encyclopedia.templateField.language': 'Language'
};