export default {
    'feedback.home': 'সাহায্য কেন্দ্র',
    'feedback.bugs': 'সমস্যা',
    'feedback.bugs.desc': 'আপনি কি কোনো ত্রুটি অথবা কিছু ভুল বা অপ্রস্থান সন্ধান করেছেন? এখানে জানান!',
    'feedback.features': 'আইডিয়া এবং প্রস্তাব',
    'feedback.features.desc': 'নতুন বৈশিষ্ট্যের জন্য আপনার কি আইডিয়া আছে বা কিভাবে সাইটটি উন্নত করতে হবে? আমাদের জানান!',
    'feedback.help': 'সাহায্য এবং টিউটোরিয়াল',
    'feedback.help.desc': 'আপনি কিভাবে _____করবেন? উত্তর খুঁজতে এখানে যান।',
    'feedback.desc': 'আমাদের সাহায্য এবং সমাধান কেন্দ্রে স্বাগতম!',
    'feedback.faq': 'প্রশ্নোত্তর',
    'feedback.faq.desc': 'সচরাচর জিজ্ঞাসিত প্রশ্ন',
    'feedback.open': 'খোলা',
    'feedback.closed': 'বন্ধ',
    'feedback.accepted': 'গৃহীত',
    'feedback.inprogress': 'চলমান',
    'feedback.completed': 'সম্পন্ন',
    'feedback.fixed': 'সংশোধিত',
    'feedback.new.bugs': 'নতুন সমস্যা রিপোর্ট করুন',
    'feedback.new.features': 'নতুন বৈশিষ্ট্য সাজান',
    'feedback.lang.nosupport': 'আপনার বর্তমান ভাষা ফিডব্যাকের জন্য সমর্থিত নয়, দয়া করে ইংরেজিতে লিখুন। ধন্যবাদ!',
    'feedback.new.thanks': 'বিজ্ঞপ্তিটির জন্য ধন্যবাদ! আমরা শীঘ্রই এটি পর্যালোচনা করব।',
    'feedback.comment.title': 'মন্তব্য',
    'feedback.comment.desc': 'আমাদের কাছে আপনার মতামত পাঠান',
    'feedback.comment.legend': 'আপনার মতামত - আমাদের সম্পর্কে জানান',
    'feedback.comment.success': 'আপনার মতামতের জন্য ধন্যবাদ!',
    'feedback.comment.label': 'আপনার মন্তব্য',
    'feedback.copyrightReport.title': 'কপিরাইট লঙ্ঘন',
    'feedback.copyrightReport.desc': 'কপিরাইট লঙ্ঘন রিপোর্ট করুন',
    'feedback.report.noUser': 'আপনাকে একটি রিপোর্ট জমা দিতে অবশ্যই সাইন ইন করতে হবে।',
    'feedback.voting.totalVoters': 'ব্যবহারকারীরা ভোট দিয়েছেন: {voted, number}',
    'feedback.voting.upvote': 'উপভোট',
    'feedback.voting.downvote': 'নিম্নভোট',
    'feedback.voting.score': 'মোট স্কোর',
    'feedback.report.title': 'প্রতিবেদনের সামগ্রী',
    'feedback.report.typeSelect': 'এখানে কি সমস্যা আছে?',
    'feedback.reportType.law': 'আইন লঙ্ঘন',
    'feedback.reportType.vulgar': 'অশ্লীল/অপমানজনক',
    'feedback.reportType.copyright': 'কপিরাইট লঙ্ঘন',
    'feedback.reportType.storyRating': 'ভুল বয়স রেটিং',
    'feedback.reportType.scam': 'প্রতারণা',
    'feedback.report.submit': 'রিপোর্ট',
    'feedback.report.submitting': 'প্রতিবেদন করা হচ্ছে...',
    'feedback.report.violationDesc': 'বিস্তারিত',
    'feedback.report.reportSaved': 'প্রতিবেদনের জন্য আপনাকে ধন্যবাদ! আমরা পরিচিতি নেব এবং প্রয়োজন হলে কার্যবিধি গ্রহণ করব।',
    'feedback.report.copyrightReportSaved': 'প্রতিবেদনের জন্য আপনাকে ধন্যবাদ! আমরা পরিচিতি নেব এবং যোগাযোগ করব।',
    'feedback.report.copyrightOwnershipDesc': 'মালিকানাধীনতা বিবৃতি',
    'feedback.report.copyrightNotice': 'দয়া করে মনে রাখবেন যে, আপনাকে এই ফর্মটি ব্যবহার করার জন্য কাজের সঠিক মালিক হতে হবে। যদি আপনি মালিক না হন, দয়া করে মালিককে জানাতে বা অন্যান্য বিভাগটি ব্যবহার করে আমাদেরকে জানাতে পারেন। আমরা কপিরাইট লঙ্ঘনগুলি অত্যন্ত গুরুত্বপূর্ণভাবে নিয়মিত ভাবে নেয় এবং একই প্রয়োজন আমাদেরকে অযথা এবং অপমানজনক ব্যবহারের জন্য প্রয়োগ করা হয়।',
    'feedback.report.copyrightInternalProperty': 'আমি এই কাজটি সাহিত্যিক বিশ্বে প্রকাশ করেছি',
    'feedback.reportType.spam': 'স্প্যাম বা ফিশিং',
    'feedback.reportType.other': 'অন্যান্য',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`,
    'faq.section.about': 'আমাদের সম্পর্কে',
    'faq.section.settings': 'সেটিংস',
    'faq.section.discovery': 'আবিষ্কার',
    'faq.section.reader': 'পাঠক',
    'faq.section.library': 'লাইব্রেরি',
    'faq.section.workshop': 'ওয়ার্কশপ',
    'faq.section.writer': 'লেখক',
    'faq.section.encyclopedia': 'বিজ্ঞানকোষ',
    'faq.section.groups': 'গোষ্ঠীসমূহ',
    'faq.section.blogs': 'ব্লগ',
    // About us questions
    'faq.question.about.dataLocation': 'Where is LU data stored?',
    'faq.answer.about.dataLocation': 'Literary Universe data is stored on servers in the United States of America, specifically AWS us-east-1 region.',
    'faq.question.about.incorporation': 'Where are you incorporated?',
    'faq.answer.about.incorporation': 'লিটারেরি ইউনিভার্স চেক রিপাবলিকে প্রতিষ্ঠিত। আমাদের সম্পর্কের বিস্তারিত জানতে পারেন <a href="/about">আমাদের সম্পর্কে পৃষ্ঠা</a>এ।',
    'faq.question.about.roadmap': 'লিটারেরি ইউনিভার্সের পরবর্তী পদক্ষেপগুলি কী?',
    'faq.answer.about.roadmap': 'এটা সময়ক্রমে উন্নত হচ্ছে। বিস্তারিত জানতে আমাদের <a href="/roadmap">পথপ্রদর্শন পৃষ্ঠা</a> দেখুন।',
    // Settings questions
    'faq.question.settings.changeTheme': 'লিটারেরি ইউনিভার্সের চেহারা কিভাবে পরিবর্তন করব?',
    'faq.answer.settings.changeTheme': 'নিবন্ধিত ব্যবহারকারীরা তাদের থিমটি পরিবর্তন করতে পারেন <a href="/user/settings/account">অ্যাকাউন্ট সেটিংস</a> এর "সাইট থিমিং" সেকশনে। আমাদের একটি হালকা এবং একটি গাঢ় থিম উপলব্ধ। আপনি যদি নিবন্ধিত না হন, তবে আমরা আপনার ব্রাউজার এবং অপারেটিং সিস্টেম সেটিংস ভিত্তিক থিম পরিবর্তন করতে চেষ্টা করি।',
    'faq.question.settings.changeAvatar': 'আমি কিভাবে আমার অবতার পরিবর্তন করব?',
    'faq.answer.settings.changeAvatar': 'আপনি আপনার অবতারটি পরিবর্তন করতে পারেন <a href="/user/settings/profile">প্রোফাইল সেটিংস</a>এ।',
    'faq.question.settings.changeLanguage': 'ভাষা কিভাবে পরিবর্তন করব?',
    'faq.answer.settings.changeLanguage': 'আপনি লিটারেরি ইউনিভার্সের ভাষা পরিবর্তন করতে পারেন <a href="/user/settings/account">অ্যাকাউন্ট সেটিংস</a>এ।',
    'faq.question.settings.translationMistake': 'ওয়েবসাইটে পাঠ্যে একটি ভুল খুঁজে পেলাম, এটি কোথায় রিপোর্ট করব?',
    'faq.answer.settings.translationMistake': 'সমস্ত ভাষা ফাইলগুলি আমাদের জিটহাবে উপলব্ধ। আপনি <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">সেখানে একটি ইস্যু জমা দিতে পারেন</a> অথবা প্রতিক্রিয়ার বাগ বিভাগে বা যদি আপনি ইচ্ছাশক্তিসম্পন্ন হন তবে আপনি নিজে সরাসরি ঠিক করতে পারেন <a href="https://crowdin.com/project/literary-universe" target="_blank">আমাদের ক্রোউডিন পৃষ্ঠা</a>এর মাধ্যমে।'
};