export default {
    'org.auditLog.title': 'অডিট লগ',
    'org.settings.title': 'প্রতিষ্ঠান সেটিংস',
    'org.settings.name': 'প্রতিষ্ঠানের নাম',
    'org.settings.membersPrivate': 'সদস্যদের সার্বিকভাবে প্রদর্শন করবেন না',
    'org.logo': 'প্রতিষ্ঠানের লোগো',
    'org.logo.alt': '{organizationName} লোগো',
    'org.superAdmin': 'সুপার অ্যাডমিন',
    'org.settings.language': 'প্রাথমিক ভাষা',
    'org.meta.desc': 'সাহিত্যিক বিশ্বে প্রতিষ্ঠান এবং সৃজনশীল গোষ্ঠীসমূহ।',
    'org.luOrgs': 'সাহিত্যিক বিশ্ব প্রতিষ্ঠানসমূহ',
    'org.otherOrgs': 'Organizations',
    'org.aboutTitle': 'সম্পর্কিত {orgName}',
    'org.membersTitle': 'সংগঠনের সদস্যগণ',
    'org.membersNone': 'সদস্যরা প্রকাশ্য নয়',
    'org.storiesTitle': '{orgName}থেকে গল্পগুলি',
    'org.universesTitle': '{orgName}থেকে বিশ্বগুলি',
    'org.userDashboardTitle': 'আপনার সংগঠনসমূহ',
    'org.settings.hideMembers.label': 'সদস্যদের গোপনে রাখুন',
    'org.visit': '{organization} পৃষ্ঠায় যান',
    'org.authorOverride.legend': 'লেখক ওভাররাইড',
    'org.authorOverride.desc': 'সংগঠনের নামের পরিবর্তে এই পাঠ্যটি দেখান।',
    'org.authorOverride.label': 'লেখকের নাম',
    'org.membersAdd.title': 'সংগঠনে সদস্যদের আমন্ত্রণ জানান',
    'org.flashnews.admin': 'ফ্ল্যাশনিউজ প্রশাসন',
    'org.settings.tabListAria': 'সংগঠনের জন্য বিভাগসমূহ সেট করুন',
    'org.forums.title': '{orgName} ফোরাম',
    'org.flashnews.internal': 'অভ্যন্তরীণ নিউজ ফ্ল্যাশ',
    'org.flashnews.publicAll': 'সর্বজনীন নিউজ ফ্ল্যাশ সমস্ত সম্পত্তির জন্য',
    'org.flashnews.createTitle': `সমস্ত সম্পত্তির জন্য প্রকাশিত করতে নতুন নিউজ ফ্ল্যাশ তৈরি করুন {type, select,
    internal {সংগঠন}
    allProperties {প্রদর্শন করুন, সর্বজনীন নিউজ ফ্ল্যাশ}
    other {সংগঠন}
  }`,
    'org.members.invited': 'আমন্ত্রিত সদস্যগণ',
    'org.members.list': 'সংগঠনের সদস্যগণ',
    'org.invitesTileNotice': 'আপনি আমন্ত্রিত হন {count, number} {count, plural, one {সংগঠনে} other {সংগঠন}}',
    'org.invitePage.title': 'সংগঠনে আমন্ত্রণ',
    'org.invitePage.invitedAt': 'আপনি আমন্ত্রিত হন {invitedAt, date, short}।',
    'org.invitePage.ignoring': 'আপনি এই আমন্ত্রণটি বর্তমানে উপেক্ষা করছেন, যা মানে হল এটি এখনও কার্যকর আছে, কিন্তু বিজ্ঞপ্তি দ্বারা বিরক্ত হচ্ছে না।',
    'org.invitePage.expiresAt': 'এই আমন্ত্রণটি মেয়াদ শেষ হবে {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'সংগঠনে যোগদান করুন',
    'org.invitePage.reject': 'আমন্ত্রণ প্রত্যাখ্যান করুন',
    'org.invitePage.ignore': 'এখনই উপেক্ষা করুন',
    'org.leaveOrg.title': 'সংগঠন ছেড়ে যান',
    'org.leaveOrg.confirm': 'এটি একটি ধ্বংসপ্রবণ ক্রিয়া। একবার যখন আপনি ছেড়ে যান, তখন আপনার এই সংগঠনে সম্পূর্ণ অ্যাক্সেস হারিয়ে যাবে। আপনি কি নিশ্চিত যে আপনি সংগঠন ছেড়ে যেতে চান?',
    'org.confirmRemove.aria': 'ব্যবহারকারী সরানো নিশ্চিত করুন',
    'org.confirmRemove.confirm': 'আপনি কি নিশ্চিত যে আপনি {username} কে {organization}থেকে সরাতে চান?',
    'org.confirmRemove.remove': 'ব্যবহারকারী সরানো হয়েছে',
    'org.mainBlog': 'মূল ব্লগ',
    'org.teams': 'দলগুলি',
    'org.teams.total': 'মোট দলসমূহ: {totalTeams, number}',
    'org.teams.create': 'নতুন দল তৈরি করুন',
    'org.teams.settings': 'দলের সেটিংস',
    'org.workshop.ownerUser': 'একটি গিল্ড কাজ নয়',
    'org.workshop.caption': 'গিল্ড মালিকানাধীনতা',
    'org.workshop.title': 'প্রতিষ্ঠান কর্মশালা',
    'org.title': 'প্রতিষ্ঠান',
    'org.hall.title': '{orgName} members hall',
    'org.member.leave': 'Leave organization',
    'org.member.leaveModalTitle': 'Leaving organization confirmation',
    'org.member.leaveModalHeading': 'Are you sure you want to leave {orgName}',
    'org.member.leaveModalExplain': 'Once you leave the organization you will loose access to all of the organization\'s associated resources and works. This action can\'t be undone.',
    // Role management strings
    'org.member.manageRoles': 'Manage Roles',
    'org.roles.error': 'Error: {error}',
    'org.roles.manageFor': 'Managing roles for {name}',
    'org.roles.selectRole': 'Select role',
    'org.roles.noRole': 'No role (permissions only)',
    'org.roles.admin': 'Admin',
    'org.roles.member': 'Member',
    'org.roles.author': 'Author',
    'org.roles.workshop': 'Workshop',
    'org.roles.teacher': 'Teacher',
    'org.permissions.title': 'Permissions',
    'org.permissions.includedInRole': '(included in role)',
    // Permission names
    'org.permissions.members.add': 'Add members',
    'org.permissions.members.remove': 'Remove members',
    'org.permissions.members.view': 'View members',
    'org.permissions.settings': 'Manage settings',
    'org.permissions.auditLog': 'View audit log',
    'org.permissions.flashnews': 'Manage flash news',
    'org.permissions.workshop.view': 'View workshop',
    'org.permissions.workshop.create': 'Create workshop items',
    'org.permissions.workshop.transfer': 'Transfer ownership',
    'org.permissions.workshop.viewAll': 'View all workshop items',
    'org.permissions.forum.manager': 'Manage forums',
    'org.permissions.blog.manage': 'Manage blog',
    'org.permissions.blog.post': 'Create blog posts'
};