export default {
    'homepage.welcome': 'স্বাগতম',
    'homepage.start': 'আপনার পথ শুরু করুন!',
    'homepage.iAm': 'আমি একজন',
    'homepage.iAm.aria': 'পাঠককে এবং লেখককে ফিচারের প্রদর্শন মধ্যে নির্বাচন করুন',
    'homepage.reader': 'পাঠক',
    'homepage.writer': 'লেখক',
    'homepage.reader.title': 'এটি পড়া এখনো এতটা আকর্ষণীয় ছিল নি',
    'homepage.reader.registerCTA': 'Start reading now!',
    'homepage.reader.readingTitle': 'অনন্য পড়ার অভিজ্ঞতা',
    'homepage.reader.readingDesc': 'লেখার মধ্যে আপনার পছন্দের কথাগুলির মধ্যে আরও গভীরতর প্রবেশ করুন লিটারেরি ইউনিভার্সে। লিটারেরি ইউনিভার্সের গল্পগুলি একই ইউনিভার্সের মধ্যে সংযুক্ত হয়, যা আপনাকে গল্পের পাঠক থেকে তাত্ত্বিক ইউনিভার্সের সংক্ষিপ্ত অ্যাক্সেস প্রদান করে।',
    'homepage.reader.favoriteTitle': 'আপনার পছন্দের গল্প এবং লেখকের সম্পর্কে আরও জানুন',
    'homepage.reader.favoriteDesc': 'ইউনিভার্স এনসাইক্লোপিডিয়া এবং লেখকের ব্লগ শুধুমাত্র কিছু ফিচার যা আপনাকে আপনার পছন্দের গল্প, তাদের সেটিং এবং তাদের সৃষ্টিকার্যদের সম্পর্কে জানতে সাহায্য করবে!',
    'homepage.reader.communityTitle': 'সম্প্রদায়ে যোগ দিন',
    'homepage.reader.communityDesc': 'Meet people from across the globe on dedicated universe and author\'s forums, blogs and other community features where like-minded fans gather. All in one place.',
    'homepage.reader.readingFeatureTitle': 'Enjoy an immersive yet practical reading experience',
    'homepage.reader.readingFeatureDesc': 'From stories and universe, have the benefit of effortless reading with access to details without needing to switch between pages.',
    'homepage.reader.readingExploreTitle': 'Explore all the minutia in the universe',
    'homepage.reader.readingExploreDesc': 'Universe encyclopedia allows you to learn all the details about the universe and fully immerse yourself in the stories.',
    'homepage.reader.start': 'Start Reading',
    'homepage.writer.title': 'Showcase your universe and share your stories',
    'homepage.writer.writingTitle': 'Writing & creating made easy',
    'homepage.writer.writingDesc': 'Experience the new way of writing with Literary Universes Workshop. Create all the details of your universe in an encyclopedia to share with your readers and write amazing stories on that foundation.',
    'homepage.writer.collaborationTitle': 'Collaborative creation',
    'homepage.writer.collaborationDesc': 'Creative process often involves multiple people. No worries, we got you covered! You can easily add beta readers, co-authors and translators to your stories and universes.',
    'homepage.writer.communityTitle': 'Connect with Your readers',
    'homepage.writer.communityDesc': 'Go beyond writing and connect with your readers via blogs, forums and other community features connected to your universes or to you as a writer.',
    'homepage.writer.workshopFeatureTitle': 'One place for all your creative needs',
    'homepage.writer.workshopFeatureDesc': 'Our ever evolving workshop is the central place for your creative needs. From a simple idea create amazing universes, stories and everything else that is needed around it.',
    'homepage.writer.monetizationFeatureTitle': 'মোনেটাইজেশন',
    'homepage.writer.monetizationDesc': 'We strongly believe that people should be payed for their work and are constantly looking for new monetization opportunities for writers. Monetization feature allows you writers to be appreciated for what you do. Explore all the different options that allow your fans to show you their appreciation.',
    'homepage.writer.start': 'Setup Your workshop!',
    'homepage.featureSelection': 'Check out these popular universe!',
    'about.title': 'About Literary Universe',
    'about.desc': 'History, secrets and humans behind Literary Universe.',
    'about.text.1': 'সাহিত্যিক বিশ্ব লেখকদের এবং অনুপ্রেরণার্থী পাঠকদের জন্য তৈরি করা হয়েছে। লেখকরা প্ল্যাটফর্মটি ব্যবহার করে একটি মৌলিক কাজ তৈরি করতে পারেন একটি "কারখানা" বাটনে ক্লিক করে ড্যাশবোর্ড মেনুতে। এটি মূল সম্পাদক এবং জ্ঞানকোষ কার্যকারিতা অ্যাক্সেস প্রদান করে, যা আপনার ব্যক্তিগত গল্প বিশ্বের সমস্ত সাহিত্যিক দিকগুলি সাজানোর উপর তুলে ধরে। সামাজিক সুবিধাগুলি লেখকদের অবশ্যই পাঠকদের সাথে তাদের কাজ প্রকাশ করতে এবং সাধারণত তাদের সাথে আরও সরাসরি সম্পর্ক করতে অনুমতি দেয়।',
    'about.text.2': 'পাঠকরা প্রাথমিকভাবে এই সাইটটি ব্যবহার করতে পারেন নতুন কাজ আবিষ্কার এবং তাদের পছন্দের লেখকদের অনুসরণ করে, কিন্তু লেখকের অনুমতি পেলে তারা প্রকাশ হওয়ার আগে লেখকদের সহায়তা করতে পারেন। লেখাপড়ার উনিশ ইউনিভার্সে পাঠক একটি সম্পূর্ণ নতুন পাঠকর অভিজ্ঞতা অফার করে - প্রধান গল্পের পাশাপাশি সমস্ত পশ্চাতের তথ্যের অ্যাকসেস পাওয়া পড়ে লেখকের মনের মধ্যে প্রবেশ দেয়।',
    'about.text.3': 'সাহিত্যিক ইউনিভার্সের ভবিষ্যৎ প্রবন্ধটিতে লেখকরা তাদের কাজ বিক্রি করতে পাবেন এবং ব্লগ এবং ফোরামের মাধ্যমে পাঠক ও লেখকের মধ্যে যোগাযোগ বৃদ্ধি করার জন্য সম্প্রদানবিদ্যার বৈশিষ্ট্য যুক্ত করার উদ্যোগ নেয়। আমরা সময় সারিতে আরও অনেক লেখকের টুল প্রবেশ করানোর পরিকল্পনা করেছি, যা সংসারণ অছুটে আমাদের চুল্লির ডিজাইন কেমন করে সান্ত্বনা এবং পঠনযজ্ঞতা সংযোজন করতে সহায়তা করবে। আমাদের ট্যারগেট লেখকেও পাঠকের অভিজ্ঞতাকে সমৃদ্ধ করতে আমরা ইন্টারনেট মাধ্যম ব্যবহার করে সৃজনশীল উপায়ে প্রেরণ করতে চাই।',
    'about.text.4': 'We hope that you join us as we explore what the internet medium can do for creative writing!',
    'about.team': 'The team',
    'about.history': 'History',
    'about.company': 'কোম্পানিটি',
    'about.companyCountry.czechia': 'চেকিয়া',
    'about.companyCountry.japan': 'জাপান',
    'about.companyCity.prague': 'প্রাগ',
    'about.companyCity.sendai': 'সেন্ডাই',
    'about.CEO': 'Chief Executive Officer',
    'about.CTO': 'Chief Technology Officer',
    'about.jan': 'লিটারারি ইউনিভার্সের প্রতিষ্ঠাতা হিসাবে জান একজন প্রতীক্ষাশীল, দর্শনমূলক এবং প্রযুক্তিগত মন। একটি বিশাল সাহিত্যিক বিশ্বে লেখাজোগের মধ্যে সঠিকতার সাথে মনোহীনতার চাপটি নির্ভরযোগ্যভাবে তালুক রাখতে লেখার প্রক্রিয়াকে সহজ করতে জান অনেকেই সমস্যা হয়েছেন। এই চ্যালেঞ্জটি তাকে উদ্দীপ্ত করেছে যাতে বড় বিশ্বের লেখা অন্তর্ভুক্ত হয়ে থাকা গল্প লেখার প্রক্রিয়াটিতে টেকনিকাল সুসংগঠনশীলতা ও পঠনযজ্ঞতা একসঙ্গে বিনিময় করা যায় না। এই লক্ষ্যে সে ওয়েব উন্নয়নের পথে কিছু পর্যালোচনা শুরু করে যাচ্ছেন এবং বড় বিশেষজ্ঞতা আর উজ্জ্বল বৈশিষ্ট্যগুলি ব্লগে এবং ফোরামে এই প্রশ্নবিদ্যাতা সংযুক্ত করতে কাজ করেন।',
    'about.history.text': '২০১০ সালে, জান ওয়েব ডেভেলপমেন্টের জ্ঞানগহনের জন্য রচেস্টার ইনস্টিটিউট অফ টেকনোলজিতে তার অধ্যয়ন শুরু করেন, লেখনী platform তৈরির লক্ষ্যে। এই দরকারিকতা ২০১৩ সালে আকার নিয়েছিল যখন প্রথম প্রমাণ উদাহরণটি Imagine RIT তে প্রদর্শিত হয়। জান তাঁর অধ্যয়ন চালিয়ে এগিয়ে চলেছেন এবং 2016 সালের একটি নতুন সংস্করণ এপ্লিকেশন তাঁর মাস্টার ক্যাপস্টোন প্রকল্প হিসাবে তৈরি করা হয়েছিল। প্রকল্পটি সবোর্ক কাঁচাতে আগত হয়েছিল গ্রীষ্মকালে 2016 সালে ধারণ করে। পরিবেশটি আপনি আজ দেখতে পাচ্ছেন।',
    'copyrights.desc': 'The full text of Literary Universe Copyrights Agreement.',
    'privacy.desc': 'Full legal text of Privacy Policy of Literary Universe.',
    'guidelines.desc': 'Community Guidelines of Literary Universe.',
    'tos.desc': 'Full legal text of Terms of Service of Literary Universe.',
    'homepage.intro': 'Let Your Creativity Run Wild Across the Literary Universe',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'কি কখনো কল্পনা করেছেন যে আপনি একটি কল্পসাধারণ বিশ্ব তৈরি করতে পারেন, যা তা ততটা বিস্তৃত হবে যে আপনি নিজেই তাতে হারিয়ে যাবেন? লিটারেরি ইউনিভার্সে, আমরা এই ভিশনটি প্রকৃত করার জন্য সরঞ্জাম সরবরাহ করি। প্রতিটি লেখকের জন্য শীর্ষ-মানের সম্পদ ও সমর্থনের অ্যাক্সেস প্রয়োজন। তাই আমরা একটি সম্পূর্ণ স্থান তৈরি করেছি যা জটিল গল্পকাহিনী ও উদ্যমী পাঠকের মধ্যে সম্পর্ক স্থাপন করে। লেখকদের জন্য এটি একটি স্বপ্নের কার্যক্ষেত্র; পাঠকদের জন্য, এটি একটি অভিযানের বিষয়বস্তু। আমাদের সঙ্গে যোগদান করুন যখন আমরা সাহিত্যিক খরগোশের গর্তে পথ খুঁজে বের করতে যাই মহাকাশের মধ্যে আপনাকে কতটা নিয়ে যায়।',
    'gdpr.title': 'GDPR Compliance',
    'gdpr.desc': 'Literary Universe is compliant with the EU GDPR directives.',
    'gdpr.compliant': 'Literary Universe is GDPR Compliant',
    'gdpr.compliant.text': 'Literary Universe has implemented various updates and changes to its codebase in preparation for GDPR enforcement on May 25th 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'এই সংস্করণে পরিবর্তনসমূহ',
    'dmca.title': 'Digital Millennium Copyright Act (DMCA) Policy',
    'dmca.subtitle': 'Copyright Dispute Policy',
    'dmca.step1.title': 'Procedure for Reporting Copyright Infringements.',
    'dmca.step2.title': 'Once Proper Bona Fide Infringement Notification is Received by the Designated Agent.',
    'dmca.step3.title': 'Procedure to Supply a Counter-Notice to the Designated Agent.',
    'dmca.desc': 'আমরা কপিরাইট লঙ্ঘনগুলি সতর্কতার সাথে নিয়মিত করি।',
    'gdpr.access.title': 'Right of Access and Right of Data Portability',
    'gdpr.access.desc': 'In user settings you can export all your data. This data will be in standard JSON format.',
    'gdpr.forget.title': 'Right to be forgotten',
    'gdpr.forget.desc': 'Any account can be deleted via user settings. Some data might be preserved, especially if they have been subject to sale and/or disputes.',
    'gdpr.rectification.title': 'সংশোধনের অধিকার',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'প্রক্রিয়ার সীমাবদ্ধতা অধিকার',
    'gdpr.processing.desc': 'সাহিত্যিক মহাবিশ্ব পুরোপুরি ব্রাউজারের সেটিংস সম্মান করে, যেমন আমাদের Matomo পরিসংখ্যান সার্ভারে রিপোর্টিং এর জন্য "ট্র্যাক না করুন" অনুরোধ।',
    'gdpr.object.title': 'আপত্তির অধিকার',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'Reporting is split into two scenarios. 1. Internal property (infringement on site of property existing on site). 2. External property (infringement on site of property not existing on site).',
    'dmca.step1.desc2': 'Reporting internal property can be done via report button on the property. Reporting external property infringement can be done via feedback screen. In both cases you will be asked to provide personal details and additional details that will allow us to check your ownership.',
    'dmca.step1.desc3': 'Please note that making a false claims will result in your inability to file claims in the future.',
    'dmca.step2.desc1': 'আপনার রিপোর্ট পেলে আমরা আপনার শংসাপত্র এবং মালিকানাধীন দাবি যাচাই করব। সব ঠিক থাকলে আমরা দাবি পরীক্ষা করার জন্য অগ্রসর হব। যদি আমরা দাবির সত্যতা নিশ্চিত করি তবে হুমকি-নোটিশের নির্ধারণ বা ১৪ দিন অতিবাহিত হওয়ার পর আমরা অধিকারপ্রাপ্ত সম্পত্তি অপ্রাপ্য করে দেব।',
    'dmca.step3.desc1': 'একটি অভিযোগ পেলে নির্ধারিত সম্পত্তির মালিকের কাছে ১৪ দিনের মধ্যে কাউন্টার নোটিশ জমা দেয়া হবে। পরবর্তীতে, নির্ধারিত এজেন্ট বিবাদ তদন্ত করবে। এই পর্যায়ে ডিজিনেটেড এজেন্টের যেকোনো সিদ্ধান্তই চূড়ান্ত হবে।',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'জান ডভোরাক',
    'about.attributions': 'প্রশংসা',
    'about.attributionsIntro': 'সাহিত্যিক বিশ্ব অনেকগুলি ওপেন সোর্স প্রকল্প এবং বিনামূল্যে সম্পদ উপর নির্ভর করে। নীচে তাদের তালিকা দেওয়া হয়েছে।',
    'about.attributionsMatomo': 'আমাদের বিশ্লেষণ স্ব-হোস্টেড ম্যাটোমো ব্যবহার করে যা ইপি2লোকেশন লাইট ডেটা সহজলভ্য করা হয় https://lite.ip2location.com।',
    'team.name.pjakubec': 'পাভেল জাকুবেক',
    'team.name.asebesta': 'আদম শেবেস্তা',
    'about.developer': 'ডেভেলপার',
    'about.seniorDeveloper': 'সিনিয়র ডেভেলপার',
    'about.juniorDeveloper': 'জুনিয়র ডেভেলপার',
    'about.leadDesigner': 'প্রধান ডিজাইনার',
    'about.leadUX': 'প্রধান UX ডিজাইনার',
    'about.intern': 'ইন্টার্ন',
    'about.advisor': 'উপদেষ্টা',
    'about.headOfResearch': 'গবেষণার প্রধান',
    'about.CFO': 'প্রধান আর্থিক কর্মকর্তা',
    'team.name.hsconovianus': 'হেন্ড্রি স্কোনোভিয়ানুস',
    'about.hendry': 'হেন্ড্রি একজন ডিজাইনার যাঁর অধিকাংশ অভিজ্ঞতা আছে। তিনি ২০১০ সাল থেকে এজেন্সিতে কাজ করছেন, তাঁর ক্লায়েন্ট হলেন PERTAMINA, VOA এবং ইন্দোনেশিয়ার পর্যটন মন্ত্রণালয়। ব্র্যান্ডিং, লেআউট এবং UI/UX এ অভিজ্ঞ হওয়ার জন্য তিনি লেখাপড়া বিশ্বের ডিজাইন করতে আহ্বানিত মনে করেন।',
    'about.pavel': 'Web3, মেটাভার্স, একাই এবং প্রবর্তনশীল প্রযুক্তি - পাভেল তা সব দেখতে পারেন সে কিভাবে সে লিটারারি ইউনিভার্সকে সমৃদ্ধ করতে পারে। একজন সত্যিকার বহুবিদ্যালয়ী গবেষক হিসাবে পাভেলের অনেক বিষয়ে অভিজ্ঞতা রয়েছে এবং প্ল্যাটফর্মে নতুন এবং উত্কৃষ্ট বৈশিষ্ট্যগুলি সংযুক্ত করার কাজ করেন।',
    'about.seba': 'একবার একটি গেমার ছিলেন, আদম এখন সম্পূর্ণরূপে ডেভেলপার হতে যাচ্ছেন, তাঁর দক্ষতা এবং সম্প্রেরণা সাহিত্যিক বিশ্বে প্রযোগ করে।'
};