export default {
    'reader.storyEnd.heading': 'শেষ',
    'reader.storyEnd.description': 'আপনি গল্পের শেষে এসেছেন।',
    'reader.externalSale.heading': 'এখনও নেই',
    'reader.externalSale.description': 'এই গল্পটি লিটারের ইউনিভার্সে পাওয়া যায় না, তবে আপনি অন্য জায়গায় পেতে পারেন।',
    'reader.storyTBC.heading': 'চালিয়ে যাইবে...',
    'reader.storyTBC.description': 'এটি হল সবচেয়ে পূর্বের গল্পটি, কিন্তু ভবিষ্যতে এই অভিযান চলবে, শীঘ্রই চেক করুন!',
    'chapter.translation.notYetDescription': 'আবার চেক করুন!',
    'reader.externalShopping.heading': 'দোকানে {storyName} কেনো:',
    'chapter.next': 'পরবর্তী অধ্যায়',
    'chapter.previous': 'পূর্ববর্তী অধ্যায়',
    'chapter.comment': 'এই অধ্যায়ে মন্তব্য',
    'reader.language': 'ভাষা:',
    'reader.fullscreen.enter': 'ফুলস্ক্রিনে ঢুকুন',
    'reader.fullscreen.exit': 'সাধারিতে ফিরে যান',
    'reader.details.universe': 'অবলোকন বিস্তারিত',
    'reader.details.story': 'গল্প বিস্তারিত',
    'reader.darkmode': 'গাঢ় মোড চালু করুন',
    'reader.flowtext': 'পাঠ্যের আকার চালু / বন্ধ করুন',
    'reader.menu.optionsAria': 'পাঠকের বিকল্প মেন্যু',
    'reader.accessibility': 'সহজলভ্যতা চালু/বন্ধ করুন',
    'chapter.translation.notYet': 'এই অধ্যায়টি এখনো অনুবাদ করা হয় নি।',
    'externalShopping.buyLink.amazon': 'আমাজনে কিনুন',
    'externalShopping.buyLink.other': 'অন্য কোথাও কিনুন {storeName}',
    'externalShopping.buyLink.bookshop': 'বইশপে কিনুন',
    'reader.accessibility.aria': 'সহজলভ্যতা বিকল্পগুলি',
    'reader.accessibility.toggleDyslexic': 'ডিসলেক্সিক ফন্ট টগল করুন',
    'reader.accessibility.toggleParagraphStripes': 'প্যারাগ্রাফ পটাঘ্রাটি টগল করুন',
    'reader.accessibility.toggleParagraphHighlight': 'নির্বাচিত প্যারাগ্রাফ হাইলাইটিং টগল করুন',
    'reader.accessibility.toggleRules': 'অবস্থানের সহযোগী শাসক টগল করুন',
    'reader.nextRelease.scheduled': 'পরবর্তী অধ্যায় {nextReleaseAt, date} এ আসবে {nextReleaseAt, time}!',
    'reader.storyContinues': 'গল্প চলছে...',
    'reader.storyOnHiatus': 'লেখকটি এখনই এই গল্প থেকে বিরত হয়েছেন এবং এই গল্পটি এখন বিশ্রামের জন্যই সময়সীমার মধ্যে রয়েছে। এক মাস বা দুই মাস পরে আবার দেখতে হবে।',
    'reader.storyCancelled': 'দুর্ভাগ্যবশত এটি শেষ। গল্পটি বাতিল হয়েছে এবং মাত্র এই জন্য এখানে কিছু নতুন হবার সম্ভাবনা কম।',
    'reader.storyCancelled.heading': 'বাতিল হয়েছে',
    'reader.nextChapterEstimation.verySoon': 'Based on the publication dates of the last {chaptersCount} chapters, the next chapter is expected to be released very soon.',
    'reader.nextChapterEstimation.days': 'Based on the publication dates of the last {chaptersCount} chapters, the next chapter should be available in approximately {daysLeft} days.',
    'reader.nextChapterEstimation.notEnoughChapters': 'এই গল্পে একটি অধ্যায়ের বেশি হওয়ায়, পরবর্তী অধ্যায়ের প্রকাশের তথ্য আমরা প্রদান করব।'
};