export default {
    'settings.biography': 'জীবনীলেখ',
    'settings.biography.placeholder': 'আপনার প্রোফাইলে প্রদর্শিত হবার জন্য নিখুঁতভাবে নিজের সম্পর্কে কিছু বলুন।',
    'settings.avatar.title': 'অবতার',
    'settings.avatar.own': 'আপনার অবতার',
    'settings.avatar.upload': 'ছবি নির্বাচন করুন',
    'settings.email': 'ইমেইল',
    'settings.email.msg': 'আপনার অ্যাকাউন্টের সঙ্গে সংযুক্তিযুক্ত ইমেইলগুলি',
    'settings.email.verified.false': 'Not verified, click to resend verification email.',
    'settings.email.verified.true': 'যাচাইকৃত ইমেইল',
    'settings.email.add': 'ইমেইল যোগ করুন',
    'settings.languages.title': 'ভাষা সেটিংস',
    'settings.languages.notice': 'ইংরেজি এবং চেক বর্তমানে একমাত্র অফিসিয়ালি সমর্থিত ভাষা। অন্যান্য ভাষাগুলি অসাধারণ স্বেচ্ছাসেবকদের এবং AI অনুবাদের কারণে উপলব্ধ, তবে এটি এখনও অসম্পূর্ণ এবং অশুদ্ধ হতে পারে।',
    'settings.languages.join': 'আমাদের সাহায্য করতে চাইলে, আপনি Literary Universe কে অনুবাদ করতে পারেন।',
    'settings.name.title': 'আসল নাম',
    'settings.name.given': 'প্রদত্ত নাম',
    'settings.name.family': 'পরিবারের নাম',
    'settings.username.change': 'ইউজারনেম পরিবর্তন করুন',
    'settings.username.label': 'ব্যবহারকারীর নাম',
    'settings.password.title': 'পাসওয়ার্ড পরিবর্তন করুন',
    'settings.password.current': 'বর্তমান পাসওয়ার্ড',
    'settings.password.new': 'নতুন পাসওয়ার্ড',
    'settings.password.repeat': 'নতুন পাসওয়ার্ড পুনরায় লিখুন',
    'settings.password.nomatch': 'নতুন পাসওয়ার্ড মেলে না!',
    'settings.password.reset': 'আপনার পাসওয়ার্ড রিসেট করুন',
    'settings.password.resetSend': 'পাসওয়ার্ড রিসেট করার নির্দেশনা সহ ইমেল পাঠানো হয়েছে!',
    'settings.socialConnectTitle': 'অন্যান্য সেবাগুলির মাধ্যমে আপনার অ্যাকাউন্ট সংযুক্ত করুন',
    'settings.socialDisconnect': 'সংযোগ বিচ্ছিন্ন করুন',
    'settings.socialConnect': 'সংযোগ করুন',
    'settings.loginWith': '{service}দিয়ে লগইন করুন',
    'settings.connectTo': '{service}এ সংযুক্ত হয়ে যান',
    'settings.export.title': 'ডেটা রপ্তানি করুন',
    'settings.export.explain': 'এটি আমাদের ডাটাবেসে সংরক্ষিত আপনার সমস্ত ডেটা পেতে আপনাকে একটি JSON ফরম্যাটে দেয়া হবে।',
    'settings.export.submit': 'ডেটা রপ্তানি করুন',
    'settings.delete.title': 'অ্যাকাউন্ট মুছে ফেলুন',
    'settings.delete.warning': `সতর্কবার্তা: আপনি আপনার অ্যাকাউন্ট মুছে ফেলে যাচ্ছেন এবং
    এর সাথে এটা ফিরে পাওয়ার কোনও উপায় নেই। দয়া করে মনে রাখবেন যে এটা স্বয়ংক্রিয়ভাবে আপনার প্রকাশিত কাজগুলি,
    মন্তব্যগুলি ইত্যাদি মুছে দেয় না। বিস্তারিত জানতে দয়া করে পরিষেবার শর্তাবলীতে দেখুন।`,
    'settings.delete.confirm': 'নিশ্চিত হতে চাই। আপনি কি আপনার অ্যাকাউন্ট মুছে ফেলতে চান?',
    'settings.delete.cancel': 'আমি আমার অ্যাকাউন্ট মুছতে চাই না',
    'settings.delete.submit': 'আমার অ্যাকাউন্ট মুছে ফেলুন',
    'settings.legal.title': 'ব্যবহারকারী সম্মতি চুক্তিসমূহ',
    'settings.legal.explained': 'এখানে আপনি বিভিন্ন আইনি নথির সাথে আপনার চুক্তি পরিচালনা করতে পারেন।',
    'settings.name.private': 'নাম ব্যক্তিগত থাকবে',
    'settings.emailSubscriptions.title': 'ইমেল বিজ্ঞপ্তি সেটিংস',
    'settings.emailSubscriptions.explain': 'আপনি কোনও ইমেল বিজ্ঞপ্তি পান তা নির্বাচন করুন।',
    'settings.emailSubscriptions.newsletter': 'অনুসময়িক সংবাদপত্র',
    'settings.profile': 'প্রোফাইল সেটিংস',
    'settings.profile.basic': 'Basic Profile Information',
    'settings.profile.identity': 'Identity',
    'settings.profile.about': 'About You',
    'settings.profile.basic.description': 'Manage your basic profile information that will be visible to other users.',
    'settings.interests.title': 'Your Interests',
    'settings.account': 'অ্যাকাউন্ট সেটিংস',
    'settings.legal.export.download': 'আপনার ডেটা ডাউনলোড করুন',
    'settings.legal.export.gathering': 'আপনার ডেটা সংগ্রহ করা হচ্ছে... এটি একটু সময় নিতে পারে।',
    'settings.gender.title': 'আপনার লিঙ্গ',
    'settings.gender.usage': 'এই তথ্যটি ব্যক্তিগতভাবে অবসরপ্রাপ্ত থাকবে। আমরা এই ডেটা ব্যবহার করি প্ল্যাটফর্ম বিশ্লেষণ এবং নিরক্ষরণ বিশ্লেষণে ক্রিয়েটরদের কথা পড়তে যখন আপনি তাদের গল্প পড়েন।',
    'settings.age.title': 'আপনার বয়স',
    'settings.age.explicit': 'Show explicit content (age rating 21+)',
    'settings.age.birthday': 'Date of birth',
    'settings.age.usage': 'এই তথ্যটি ব্যক্তিগতভাবে অবসরপ্রাপ্ত থাকবে। আমরা আপনার বয়স সম্পর্কে জিজ্ঞাসা করতে আইনানুগ বাধ্য হয়েছি। আমরা এই ডেটা ব্যবহার করি প্ল্যাটফর্ম বিশ্লেষণ, রেটিং ভিত্তিতে কন্টেন্ট প্রদর্শন এবং নিরক্ষরণ বিশ্লেষণে ক্রিয়েটরদের কথা পড়তে যখন আপনি তাদের গল্প পড়েন।',
    'settings.country.title': 'আপনার দেশ',
    'settings.country.usage': 'আমরা সরকারী জিজ্ঞাসা এর জন্য আপনার দেশ সম্পর্কে জিজ্ঞাসা করতে আইনানুগ বাধ্য হয়েছি। আমরা এই ডেটা ব্যবহার করি প্ল্যাটফর্ম বিশ্লেষণ এবং নিরক্ষরণ বিশ্লেষণে ক্রিয়েটরদের কথা পড়তে যখন আপনি তাদের গল্প পড়েন। আপনি চাইলে আপনার প্রোফাইলে এই তথ্যটি প্রদর্শন করতে পারেন।',
    'settings.country.public': 'আপনার দেশ পাবলিকভাবে প্রদর্শন করুন',
    'settings.country.select': 'আপনার দেশ নির্বাচন করুন',
    'settings.emailSubscriptions.newsletterTech': 'আমাদের ডেভেলপারদের প্রতিষ্ঠান সম্পর্কিত অফিসিয়াল নিউজলেটার',
    'settings.emailSubscriptions.newsletterFeatures': 'নতুন ফিচার সম্পর্কে তথ্য',
    'settings.emailNotifications.title': 'বিজ্ঞপ্তি',
    'settings.emailNotifications.pm': 'নতুন মেসেজ',
    'settings.emailNotifications.newChapters': 'নতুন চ্যাপ্টার',
    'settings.resetPasswordEmailSend': 'আমরা আপনাকে ইমেলে পাসওয়ার্ড রিসেট করার নির্দেশনা প্রেরণ করেছি।',
    'settings.theme.title': 'সাইট থিমিং',
    'settings.theme.label': 'সাইট থিম',
    'settings.theme.light': 'হালকা',
    'settings.theme.dark': 'ডার্ক',
    'settings.links.title': 'আপনার অন্যান্য ওয়েবসাইটের লিংক',
    'settings.links.description': 'এই লিংকগুলি আপনার প্রোফাইল পৃষ্ঠায় প্রদর্শন করা হবে।',
    'settings.links.website': 'আপনার ব্যক্তিগত ওয়েবসাইট',
    'settings.links.social': 'অন্যান্য ওয়েবসাইটগুলি',
    'settings.links.select': 'যোগ করতে ওয়েবসাইট নির্বাচন করুন',
    // 2FA
    'settings.2fa.title': 'Two-factor authentication',
    'settings.2fa.explained': 'Two-factor authentication provides an additional layer of security for your account by adding an additional authentication step during login. This prevents malicious actors from gaining access to your account if your first login step is compromised.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'Two-factor authentication with OTP code creates one-time password via authenticator applications (like Authy, Google/Microsoft Authenticator, etc.) that you enter on login.',
    'settings.2fa.otpModalAria': '2FA OTP method',
    'settings.2fa.otpAdd': 'Add 2FA OTP',
    'settings.2fa.confirmCode': 'Code that shows in your authentication application',
    'settings.2fa.svgAlt': 'QR code for authentication app',
    'settings.2fa.codeHeading': 'If you can\'t scan QR code, you can manually enter the following code:',
    'settings.2fa.instructionsTitle': 'Instructions',
    'settings.2fa.instructions1': 'Install and open authenticator application of your choice (Authy, Google/Microsoft Authenticator, FreeOTP, etc.)',
    'settings.2fa.instructions2': 'Select "Add account" (can be a visible "+" icon or can be hidden in a menu)',
    'settings.2fa.instructions3': 'Scan the QR code presented on the screen here or if not possible enter the code bellow.',
    'settings.2fa.instructions4': 'Type in the 6 numbers that appear on the screen into the input here to finish.',
    'settings.2fa.saved': 'Two-factor authentication successfully established!',
    'settings.2fa.disableOTP': 'Disable OTP two-factor authentication',
    // Web3
    'settings.web3.legend': 'Web3 wallet connection',
    'settings.web3.explained': 'You can connect your Web3 crypto wallet to you Literary Universe account. Once connected you will be able to login with your wallet and do even more things in the future as we expand our Web3 offering.',
    'settings.web3.connect': 'Connect your wallet',
    'settings.web3.address': 'Connected address: {address}',
    'settings.web3.verify': 'Sign your address',
    'settings.web3.verify.explained': 'এই ঠিকানাটি আপনার মালিকানাধীনতা নিশ্চিত করতে আমরা আপনাকে একটি বার্তা সাইন করতে বলবো।',
    'settings.web3.verified': 'যাচাইকৃত',
    'settings.web3.verificationMessage': 'সাহিত্যিক বিশ্বে ব্যবহারকারী {username} যাচাই করা হচ্ছে। কোড: {code}',
    'settings.web3.unlink': 'ওয়ালেট সরান',
    'settings.web3.linkingMessage': 'দয়া করে নিশ্চিত করুন যে আপনি আপনার ওয়ালেটটি সাহিত্যিক বিশ্বের সাথে লিঙ্ক করতে চান। কোড: {code}',
    'settings.web3.linkError': 'এই ঠিকানাটি আমাদের ডাটাবেসে ইতিমধ্যেই তালিকাভুক্ত এবং নির্ধারিত করা যায়নি!',
    // Reader settings
    'settings.reader.title': 'পাঠকের সেটিংস',
    'settings.reader.darkMode': 'সর্বদা ডার্ক মোডে দেখান',
    'settings.reader.asideView': 'জাদুময় পাশের প্যানেল দেখান',
    'settings.reader.textSize': 'বড় ফন্টে পাঠ্য দেখান',
    'settings.reader.storyRecommendations': 'Story Recommendations',
    'settings.reader.storyRecommendationsHelp': 'Enable personalized story recommendations.',
    // AI settings
    'settings.ai.title': 'AI settings',
    'settings.ai.explained': 'Configure how AI features work for you on Literary Universe.',
    // Accessibility
    'settings.accessibility.title': 'পাঠকের অবসরপ্রাপ্ততা',
    'settings.accessibility.openDyslexic': 'OpenDyslexic ফন্ট ব্যবহার করুন',
    'settings.accessibility.paragraphStripes': 'প্যারাগ্রাফে পরিবর্তিত রং ব্যবহার করুন',
    'settings.accessibility.paragraphHighlighting': 'আপনি যে প্যারাগ্রাফের উপর মাউস হোভ করছেন তা হাইলাইট করুন',
    'settings.accessibility.ruler': 'মাউসের সাথে একটি সর্তকতা যোগ করুন',
    // Story Recommendations
    'settings.storyRecommendations.title': 'Story recommendations',
    'settings.storyRecommendations.explained': 'Enable personalized story recommendations throughout the app based on your reading preferences and history.',
    'settings.tab.legal': 'আইনগত নথি',
    'settings.tab.exportDelete': 'ডেটা রপ্তানি করুন এবং অ্যাকাউন্ট মুছে ফেলুন',
    'settings.languages.uiLanguage': 'Interface language',
    'settings.languages.readingLanguage': 'Reading language',
    'settings.languages.readingLanguageExplained': 'When looking up stories we will offer you stories and their translations in this language unless you specify otherwise.',
    'settings.biography.help': 'Tell others about yourself',
    'settings.username.help': 'Your unique username on the platform',
    'settings.interests.tags.custom.help': 'Enter comma separated list of tags',
    'settings.interests.tags.placeholder': 'Add tags',
    'settings.interests.avoidGenres.help': 'Select genres you\'d prefer not to see in recommendations.',
    'settings.interests.avoidGenres': 'Genres to avoid'
};