export default {
    'writer.menu.optionsAria': 'সম্পাদক বিকল্প মেনু',
    'writer.menu.saveOptionsAria': 'বিকল্প সংরক্ষণ করুন',
    'writer.undo': 'আনডু',
    'writer.redo': 'পুনরায় করুন',
    'writer.ul': 'অবিশ্বাস্য তালিকা',
    'writer.ol': 'ক্রমিক তালিকা',
    'writer.blockquote': 'উদ্ধৃতি',
    'writer.link': 'একটি লিঙ্ক সন্নিবেশ করুন',
    'writer.image': 'একটি চিত্র সন্নিবেশ করুন',
    'writer.bold': 'চিহ্নিত করুন',
    'writer.underline': 'নিচের ধারণাটি সাদা করুন',
    'writer.italic': 'ধারণাটি মুখ্য করুন',
    'writer.align.left': 'Align left',
    'writer.align.center': 'Align center',
    'writer.align.right': 'Align right',
    'writer.align.justify': 'Justify',
    'writer.wordCount': '{characters, number} অক্ষর, {words, number} শব্দ',
    'writer.characterCount': '{characters, number} অক্ষর',
    'finder.details': 'বিশদ',
    'finder.remove': 'সংযোগ সরান',
    'finder.connect': 'সংযোগ নির্বাচন করুন জ্ঞানকোষ এন্ট্রিতে',
    'writer.aside.ariaLabel': 'সাহায্য অপশন মেনু',
    'writer.aside.todo': 'Todo & Tasks',
    'writer.aside.ai': 'AI Assistant',
    'writer.todo.title': 'Writing Progress & Goals',
    'writer.todo.description': 'Track your writing tasks and goals for this chapter.',
    'writer.todo.currentChapter': 'Current Chapter ({sequence})',
    'writer.todo.currentStatus': 'Current Status',
    'writer.todo.currentCount': 'Current chapter: {count, number} {unit}',
    'writer.todo.storyAverage': 'Your average chapter length: {count, number} {unit}',
    'writer.todo.recommendations': 'Recommended Chapter Lengths',
    'writer.todo.recommendation': '{label}: {count, number} {unit}',
    'writer.todo.recommendation.progress': 'Progress: {current, number} / {target, number} {unit} ({percent, number}%)',
    'writer.todo.dailyPublishing': 'Daily publishing',
    'writer.todo.dailyTooltip': 'For stories published every day. Shorter chapters help maintain daily engagement and work well for serialized content.',
    'writer.todo.biDailyPublishing': 'Bi-daily publishing',
    'writer.todo.biDailyTooltip': 'For stories published 3-4 times per week. Balanced length that allows for detailed storytelling while maintaining reader engagement.',
    'writer.todo.weeklyPublishing': 'Weekly publishing',
    'writer.todo.weeklyTooltip': 'For stories published once per week. Longer chapters allow for more complex plots and character development.',
    'writer.todo.monthlyPublishing': 'Monthly publishing',
    'writer.todo.monthlyTooltip': 'For stories published once per month. Much longer chapters suitable for in-depth storytelling and complex narratives.',
    'writer.nothingToSave': 'সংরক্ষণ করার কিছু নেই',
    'writer.link.placeholder': 'Enter a URL',
    'writer.link.error.empty': 'URL cannot be empty',
    'writer.link.error.invalid': 'Please enter a valid URL',
    'writer.fontFamily': 'Font Family',
    'writer.fontFamily.select': 'Select font',
    'writer.image.upload': 'Upload Image',
    'writer.image.uploading': 'Uploading image...',
    'writer.image.error.type': 'Only JPEG, PNG, and WebP images are supported',
    'writer.image.error.size': 'Image must be less than 5MB',
    'writer.image.error.upload': 'Failed to upload image. Please try again.',
    'writer.publish.publishAria': 'প্রকাশনা বিকল্পগুলি',
    'writer.publish.scheduleExplained': 'আপনি এখানে ছোট করে প্রকাশ করতে পারেন বা অনুসূচীত সময়ে অ্যাডভান্সড প্রকাশ করতে পারেন।',
    'writer.publish.schedule': 'প্রকাশের তারিখ এবং সময় সেট করুন',
    'writer.publish.previousChapterPublished': 'আগের অধ্যায়টি প্রকাশ করা হয়েছে {publishDate, date, short} তারিখে {publishDate, time}',
    'writer.publish.previousChapterScheduled': 'আগের অধ্যায়টি অনুসূচিত করা হয়েছে {publishDate, date, short} তারিখে {publishDate, time}',
    'writer.publish.alreadyPublished': 'এই অধ্যায়টি ইতিমধ্যে {publishedAt, date, short}তারিখে প্রকাশ হয়েছে। নতুন সংস্করণগুলি তাৎক্ষণিকভাবে প্রকাশ করা হবে।',
    'writer.publish.betaReader': 'বেটা',
    'writer.publish.betaReader.original': 'Beta (Original)',
    'writer.publish.public': 'প্রকাশ করুন',
    'writer.publish.publish': 'Publish',
    'writer.publish.publish.original': 'Publish (Original)',
    'writer.publish.now': 'Publish now',
    'writer.publish.moreOptions': 'More save options',
    'writer.publish.schedulePrevious': 'You need to publish or schedule publication of previous chapter before you can publish this one.',
    'writer.publish.earlyAccess.title': 'Early access for fans',
    'writer.publish.earlyAccess.groupLine': '{days} days early: {tiers} — fans get access on {date, date, short} at {date, time}',
    'writer.initialLetter': 'Initial Paragraph Letter'
};