/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'Literary Universe',
    twitterHandle: '@lituniapp',
    'site.description': 'Το Literary Universe είναι μια ολοκληρωμένη δημιουργική και εκδοτική πλατφόρμα για μεγάλα ιστορικά σύμπαντα.',
    'site.keywords': 'creative writing, scifi, sci-fi, fantasy, writing, publishing, story, stories, universe, web novel, webnovel',
    'site.logoAlt': 'Λογότυπο Λογοτεχνικού Σύμπαντος',
    mobileMenu: 'Κινητό μενού',
    'common.signin': 'Σύνδεση',
    'common.signup': 'Εγγραφή',
    'common.signout': 'Αποσύνδεση',
    'common.dashboard': 'Ταμπλό',
    'common.discovery': 'Ανακάλυψη',
    'common.library': 'Βιβλιοθήκη',
    'common.library.own': 'Η Βιβλιοθήκη Σας',
    'common.workshop': 'Εργαστήριο',
    'common.pm': 'Μηνύματα',
    'common.settings': 'Ρυθμίσεις',
    'common.options': 'Επιλογές',
    'common.profile': 'Προφίλ',
    'common.blog': 'Ιστολόγιο',
    'common.blogs': 'Ιστολόγια',
    'common.about': 'Σχετικά με εμάς',
    'common.accessdenied': 'Άρνηση πρόσβασης',
    'common.accessdenied.msg': 'Δεν σας δόθηκε άδεια να πάτε εδώ. Αν θα έπρεπε να έχετε πρόσβαση εδώ, παρακαλούμε επικοινωνήστε με τον ιδιοκτήτη και πείτε του να ελέγξει ξανά τις ρυθμίσεις.',
    'common.loading': 'Φόρτωση...',
    'common.add': 'Προσθήκη',
    'common.save': 'Αποθήκευση',
    'common.email': 'E-mail',
    'common.soon': 'Έρχεται σύντομα...',
    'common.search': 'Αναζήτηση',
    'common.search.do': 'Αναζήτηση',
    'common.searching': 'Γίνεται αναζήτηση...',
    'common.report': 'Αναφορά',
    'common.user': 'Χρήστης',
    'common.users': 'Χρήστες',
    'common.showmore': 'Εμφάνιση περισσότερων',
    'common.futurefeature.title': 'Μελλοντική λειτουργία',
    'common.futurefeature.text': 'Λυπούμαστε πολύ, αλλά αυτή η λειτουργία δεν είναι διαθέσιμη αυτή τη στιγμή. Εργαζόμαστε σκληρά για να το κάνουμε διαθέσιμο το συντομότερο δυνατό.',
    'common.nothingfound': 'Δεν βρέθηκαν αποτελέσματα',
    'common.explore': 'Εξερεύνηση',
    'common.by': 'από {author}',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'Σημειωματάριο',
    'common.scratchpad.own': 'Το σημειωματάριο σας',
    'common.news': 'Νέα',
    'common.encyclopedia': 'Εγκυκλοπαίδεια',
    'common.art': 'Art',
    'common.story': 'Ιστορία',
    'common.stories': 'Ιστορίες',
    'common.universe': 'Σύμπαν',
    'common.universes': 'Σύμπαντα',
    'common.collaborator': 'Συνεργάτης',
    'common.collaborators': 'Συνεργάτες',
    'common.translator': 'Μεταφραστής',
    'common.translators': 'Μεταφραστές',
    'common.betareader': 'Κριτής βήτα',
    'common.betareaders': 'Κριτές βήτα',
    'common.post': 'Θέση',
    'common.statistics': 'Στατιστικά',
    'common.lang.select': 'Επιλογή γλώσσας',
    'common.submit': 'Υποβολή',
    'common.close': 'Κλείσιμο',
    'common.comment': 'Σχόλιο',
    'common.comments': 'Σχόλια',
    404: 'Η σελίδα δεν βρέθηκε',
    'search.users': 'Αναζήτηση χρηστών',
    'search.user': 'Αναζήτηση χρήστη',
    'common.help': 'Βοήθεια',
    'common.or': 'ή',
    'common.account.create': 'Δημιουργία λογαριασμού',
    'signup.username': 'Όνομα χρήστη',
    'signup.email': 'Το e-mail σας',
    'signup.password.label': 'Ο κωδικός σας',
    'signup.password.repeat': 'Επανάληψη του κωδικού σας',
    'common.password': 'Κωδικός',
    'signin.password.forgot': 'Ξεχάσατε τον κωδικό σας;',
    'dashboard.whatsnew': 'Τι νέο υπάρχει',
    'dashboard.blog': 'Το blog σας',
    'common.footer.tagline': 'Γράψιμο και ανάγνωση πολύπλοκων σύμπαντων γίνεται εύκολο.',
    'common.footer.plans': 'Πακέτα και Τιμοκατάλογος',
    'common.legal.tos': 'Όροι Χρήσης',
    'common.legal.community': 'Οδηγίες Κοινότητας',
    'common.legal.privacy': 'Πολιτική Απορρήτου',
    'common.legal.copyright': 'Συμφωνία Πνευματικών Δικαιωμάτων',
    'common.legal.versionDisplay': `{type, select,
    tos {Terms of Service}
    community {Community Guidelines}
    privacy {Privacy Policy}
    copyright {Copyright Agreement}
    publishingAgreement {Publishing Agreement}
    other {Agreement}
  } Version {version} - {date, date}`,
    'common.legal.newVersionAvailable': 'A new version ({newVersion}) of this document will come into effect on {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} Όλα τα δικαιώματα διατηρούνται, όλα τα κείμενα ανήκουν στους αντίστοιχους συγγραφείς τους.',
    'premium.only.title': 'Δεν έχετε αρκετά υψηλή κατάταξη μέλους',
    'premium.only.msg': 'Ζητάμε συγνώμη, η κατάταξη μέλους σας δεν είναι αρκετά υψηλή για να έχετε πρόσβαση σε αυτήν τη λειτουργία.',
    'premium.only.join': 'Προσφέρουμε ποικιλία πακέτων για να επωφεληθείτε ό,τι περισσότερο από το Literary Universe.',
    'premium.only.link': 'Ρίξτε μια ματιά!',
    'universe.visit': 'Επίσκεψη στη σελίδα του σύμπαντος',
    'common.fanmanager': 'Fan manager',
    'common.fanarts': 'Fan arts',
    'common.fanfiction': 'Fan fiction',
    'common.fansettings': 'Fan settings',
    'story.chapter': 'Κεφάλαιο',
    'story.chapters': 'Κεφάλαια',
    'story.genre': 'Είδος',
    'story.genres': 'Είδη',
    'story.read': 'Ανάγνωση',
    'story.lastUpdate': 'Τελευταία ενημέρωση στις {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Ολοκληρώθηκε στις {date, date, medium}.',
    'story.comments.for': 'Σχόλια για τον/την {story} {chapter}.',
    'story.cover.alt': 'Εικόνα εξωφύλλου ιστορίας για το {story}.',
    'story.note.fanfiction': 'ΣΗΜΕΙΩΣΗ: Αυτή η ιστορία είναι ένα fan fiction στο σύμπαν του {universe}.',
    copyrights: 'Πνευματικά δικαιώματα',
    'common.challenges': 'Προκλήσεις',
    // for beta only
    'beta.notice': 'Καλώς ήρθατε στο Λογοτεχνικό Σύμπαν BETA. Αυτή είναι μια δημόσια προεπισκόπηση και ως εκ τούτου η εφαρμογή είναι ακόμα σε εξέλιξη. Αυτό σημαίνει ότι μπορείτε ακόμα να περιμένετε λάθη και ημιτελή χαρακτηριστικά. Αν αντιμετωπίσετε κάποιο σφάλμα ή κάτι που δεν λειτουργεί, ενημερώστε μας και κάντε υπομονή όσο θα τα βάζουμε όλα στη θέση τους.',
    'beta.thanks': 'Σας ευχαριστούμε για την υποστήριξή σας!',
    'scratchpad.about': 'Οι σημειώσεις και οι ιδέες σας είναι προσβάσιμες οπουδήποτε στον ιστότοπο.',
    'common.feedback': 'Ανατροφοδότηση',
    'common.createdOn': 'Created on {date, date, long}',
    'common.createdOn.title': 'Created on',
    // account types
    admin: 'Διαχείριση',
    'common.saved': 'Αποθηκεύτηκε!',
    'common.saving': 'Αποθηκεύεται...',
    'common.friends': 'Φίλοι',
    'lang.orig': 'Αρχική γλώσσα',
    'lang.orig.plus': 'Αρχική γλώσσα - {language}',
    buy: 'Αγορά',
    confirm: 'Επιβεβαίωση',
    cancel: 'Ακύρωση',
    processing: 'Επεξεργασία...',
    'common.noData': 'No data',
    'error.title': 'Παρουσιάστηκε ένα σφάλμα. Ζητούμε συγνώμη για την αναστάτωση.',
    'common.offlineStatus': 'Αυτή τη στιγμή είστε εκτός σύνδεσης.',
    male: 'Άνδρας',
    female: 'Γυναίκα',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: 'Παρακαλώ επιλέξτε',
    'common.statusFailed': 'Αποτυχία σύνδεσης στον διακομιστή.',
    'common.statusConnecting': 'Προσπάθεια σύνδεσης στον διακομιστή... ({count, number})',
    'slug.checking': 'Έλεγχος...',
    'slug.failed': 'Αυτή η διεύθυνση υπάρχει ήδη.',
    'slug.success': 'Αυτή η διεύθυνση είναι διαθέσιμη!',
    'notVerified.msg': `Your account {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    } is not verified.`,
    'notVerified.verify': `Please verify your {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    }.`,
    unknown: 'άγνωστος',
    'common.legal.guidelines': 'Οδηγίες Κοινότητας',
    'errorLoading.title': 'Σφάλμα κατά τη φόρτωση της σελίδας',
    'errorLoading.explained': 'Συνέβη ένα σφάλμα κατά τη φόρτωση της σελίδας. Ζητούμε συγγνώμη για την αναστάτωση. Παρακαλώ προσπαθήστε ξανά να αποκτήσετε πρόσβαση στη σελίδα. Εάν το πρόβλημα εξακολουθεί να υφίσταται, παρακαλούμε ενημερώστε μας.',
    'errorLoading.retry': 'Ξαναπροσπαθήστε!',
    'errorLoading.takingLong': 'Αυτό απαιτεί πολύ χρόνο...',
    'common.title': 'Τίτλος',
    'common.timelines': 'Χρονολόγια',
    'common.legal.gdpr': 'Κανονισμός GDPR',
    'common.legal.gdpr.long': 'Γενικός Κανονισμός Προστασίας Δεδομένων',
    'editor.placeholder.link': 'Εισαγάγετε URL...',
    'editor.placeholder.connection': 'Αναζήτηση για καταχώρηση στην εγκυκλοπαίδεια...',
    'editor.saved.beta': 'Δημιουργήθηκε νέα αναθεώρηση για τους Βήτα αναγνώστες!',
    'editor.saved.public': 'Νέα έκδοση δημοσιεύτηκε!',
    goodbyeForever: 'Λυπούμαστε που σε βλέπουμε να φεύγεις. Ήταν κάτι που κάναμε εμείς; Παρακαλούμε ενημερώστε μας αν αυτό συμβαίνει. Όπως και να έχει, σας ευχόμαστε τα καλύτερα στις μελλοντικές σας προσπάθειες και ελπίζουμε να ξανασυναντηθούμε! Να ζήσετε και να ευημερήσετε!',
    'goodbyeForever.feedback': 'Ενημερώστε μας για το τι μπορούμε να κάνουμε καλύτερα',
    'common.edit': 'Επεξεργασία',
    'common.publish': 'Δημοσίευση',
    'common.publishAt': 'Ημερομηνία και ώρα δημοσίευσης',
    'a11y.user.menu': 'Μενού χρήστη',
    'a11y.navigation': 'Navigation',
    'dashboard.profile': 'Το προφίλ σας',
    'profile.website': 'Ο ιστότοπός μου',
    'story.notes.concept': 'Έννοια',
    'story.notes.settings': 'Ρύθμιση ιστορίας',
    'story.notes.theme': 'Θέμα',
    'story.notes.impact': 'Επιθυμητή επίδραση',
    'story.notes.outcome': 'Αποτέλεσμα',
    'story.notes.audience': 'Στόχος κοινού',
    'story.notes.pitch': 'Παρουσίαση',
    'story.notes.notes': 'Σημειώσεις',
    'story.authorsNotes': 'Author\'s notes',
    'common.members': 'Μέλη',
    'common.language': 'Γλώσσα',
    next: 'Επόμενο',
    previous: 'Previous',
    'common.legal.tos.short': 'Όροι',
    'common.legal.privacy.short': 'Απόρρητο',
    'premium.increaseLimit': 'Λάβετε υπόψη την αναβάθμιση για να αυξήσετε το όριο σας.',
    'common.sharing': 'Κοινή χρήση',
    'story.isbn': 'ISBN',
    'common.name': 'Όνομα',
    'common.remove': 'Αφαίρεση',
    'common.time.milliseconds': 'Χιλιοστά δευτερολέπτου',
    'common.time.seconds': 'Δευτερόλεπτα',
    'common.time.minutes': 'Λεπτά',
    'common.time.hours': 'Ώρες',
    'common.time.days': 'Ημέρες',
    'common.time.weeks': 'Εβδομάδες',
    'common.time.months': 'Μήνες',
    'common.time.years': 'Χρόνια',
    'common.monetization': 'Monetization',
    'common.tab.monetizationOptions': 'Monetization options',
    'common.pagination': 'Pagination',
    'common.forum': 'Forum',
    'common.2faCode': '2FA code',
    'common.2faCodeIntro': 'Please enter your one time code generated by your authenticator application.',
    'common.2faCodeAria': '2FA code entry form',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Default language',
    'signin.web3.signMessage': 'Please confirm that you want to enter Literary Universe with your wallet as authentication method. Code: {code}',
    'common.web3.confirmationCode': 'Confirmation code: {code}',
    'common.roadmap': 'Roadmap',
    'common.luStatsIFrameOptOut': 'Literary Universe statistics opt-out',
    'common.image': 'Image',
    'common.home': 'Home',
    'common.administration': 'Administration',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'Groups',
    'common.upload': 'Upload',
    'common.backToDashboard': 'Back to dashboard',
    'common.accept': 'Accept',
    'common.reject': 'Reject',
    'common.events': 'Events',
    'common.event': 'Event',
    'common.all': 'Όλα',
    'common.social': 'Social',
    'common.discordCommunity': 'Discord Community',
    'common.account': 'Account',
    'common.notifications': 'Notifications',
    'common.byDeclaration': 'By:',
    'common.done': 'Done',
    recommended: 'Recommended',
    'select.typeToCreate': 'Start typing to create an item',
    'select.noSearchResults': 'No results for “{search}”',
    'select.removeOption': 'Remove {option}',
    create: 'Create',
    'banner.support': 'Literary Universe is supported by users like you! Please consider subscribing to one of our subscription plans to stay independent and make Literary Universe event better!',
    'banner.seePlans': 'Visit our plans page for more information.',
    'common.noAccountQuestion': 'Don\'t have an account?',
    'common.haveAccountQuestion': 'Already have an account?',
    'common.socialLogin': 'Login with other services',
    'common.viewMore': 'View more',
    'common.overview': 'Overview',
    'common.loggingOut': 'Logging out',
    'common.thankYou': 'Thank you!',
    'common.seeYouAgain': 'See you again!',
    'email.hello': 'Hello {username},',
    'common.back': 'Back',
    'console.stop': 'Σταμάτα!',
    'console.explain': 'Αυτό είναι ένα χαρακτηριστικό του προγράμματος περιήγησης που προορίζεται για προγραμματιστές. Αν κάποιος σας είπε να αντιγράψετε-επικολλήσετε κάτι εδώ για να ενεργοποιήσετε ένα χαρακτηριστικό του Literary Universe ή να "χακάρετε" τον λογαριασμό κάποιου, είναι μια απάτη και θα τους δώσει πρόσβαση στον λογαριασμό σας στο Literary Universe.'
}    /* eslint-enable max-len */;