/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'Literary Universe',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe is a creative and publishing platform for grand story universes.',
    'site.keywords': 'creative writing, scifi, sci-fi, fantasy, writing, publishing, translations, story, stories, universe',
    'site.logoAlt': 'Literary Universe logo',
    mobileMenu: 'Κινητό μενού',
    'common.signin': 'Σύνδεση',
    'common.signup': 'Εγγραφή',
    'common.signout': 'Αποσύνδεση',
    'common.dashboard': 'Ταμπλό',
    'common.discovery': 'Ανακάλυψη',
    'common.library': 'Βιβλιοθήκη',
    'common.library.own': 'Η Βιβλιοθήκη Σας',
    'common.workshop': 'Εργαστήριο',
    'common.pm': 'Μηνύματα',
    'common.settings': 'Ρυθμίσεις',
    'common.options': 'Επιλογές',
    'common.profile': 'Προφίλ',
    'common.blog': 'Ιστολόγιο',
    'common.blogs': 'Ιστολόγια',
    'common.about': 'Σχετικά με εμάς',
    'common.accessdenied': 'Άρνηση πρόσβασης',
    'common.accessdenied.msg': 'Δεν σας δόθηκε άδεια να πάτε εδώ. Αν θα έπρεπε να έχετε πρόσβαση εδώ, παρακαλούμε επικοινωνήστε με τον ιδιοκτήτη και πείτε του να ελέγξει ξανά τις ρυθμίσεις.',
    'common.loading': 'Φόρτωση...',
    'common.add': 'Add',
    'common.save': 'Save',
    'common.email': 'E-mail',
    'common.soon': 'Coming soon...',
    'common.search': 'Search',
    'common.search.do': 'Search',
    'common.searching': 'Searching...',
    'common.report': 'Report',
    'common.user': 'User',
    'common.users': 'Users',
    'common.showmore': 'Show more',
    'common.futurefeature.title': 'Future feature',
    'common.futurefeature.text': 'Λυπούμαστε πολύ, αλλά αυτή η λειτουργία δεν είναι διαθέσιμη αυτή τη στιγμή. Εργαζόμαστε σκληρά για να το κάνουμε διαθέσιμο το συντομότερο δυνατό.',
    'common.nothingfound': 'Nothing found',
    'common.explore': 'Explore',
    'common.by': 'by ',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'Σημειωματάριο',
    'common.scratchpad.own': 'Your scratchpad',
    'common.news': 'News',
    'common.encyclopedia': 'Encyclopedia',
    'common.story': 'Story',
    'common.stories': 'Stories',
    'common.universe': 'Universe',
    'common.universes': 'Universes',
    'common.collaborator': 'Collaborator',
    'common.collaborators': 'Collaborators',
    'common.translator': 'Translator',
    'common.translators': 'Translators',
    'common.betareader': 'Beta reader',
    'common.betareaders': 'Beta readers',
    'common.post': 'Post',
    'common.statistics': 'Statistics',
    'common.lang.select': 'Select language',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.comment': 'Comment',
    'common.comments': 'Comments',
    404: 'Page not found',
    'search.users': 'Search for users',
    'search.user': 'Search for user',
    'common.help': 'Help',
    'common.or': 'or',
    'common.account.create': 'Create an account',
    'signup.username': 'Username',
    'signup.email': 'Your e-mail',
    'signup.password.label': 'Your password',
    'signup.password.repeat': 'Repeat your password',
    'common.password': 'Password',
    'signin.password.forgot': 'Forgot password?',
    'dashboard.whatsnew': 'What is new',
    'dashboard.blog': 'Your blog',
    'common.footer.tagline': 'Writing and reading complex universes made easy.',
    'common.footer.plans': 'Plans & Pricing',
    'common.legal.tos': 'Terms of Service',
    'common.legal.community': 'Community Guidelines',
    'common.legal.privacy': 'Privacy Policy',
    'common.legal.copyright': 'Copyright Agreement',
    'common.legal.newVersionAvailable': 'A new version ({newVersion}) of this document will come into effect on {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} Όλα τα δικαιώματα διατηρούνται, όλα τα κείμενα ανήκουν στους αντίστοιχους συγγραφείς τους.',
    'premium.only.title': 'Not high enough membership rank',
    'premium.only.msg': 'We apologize, your membership rank is not high enough to access this feature.',
    'premium.only.join': 'We offer varieties of plans for everyone to get the most out of Literary Universe.',
    'premium.only.link': 'Check it out!',
    'universe.visit': 'Visit universe page',
    'common.fanfiction': 'Fan Fiction',
    'story.chapter': 'Chapter',
    'story.chapters': 'Chapters',
    'story.genre': 'Genre',
    'story.genres': 'Genres',
    'story.read': 'Read',
    'story.lastUpdate': 'Last updated on {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Finished on {date, date, medium}.',
    'story.comments.for': 'Comments for {story} {chapter}.',
    'story.cover.alt': 'Story cover image for {story}.',
    'story.note.fanfiction': 'NOTE: This story is a fan fiction on {universe} universe.',
    copyrights: 'Copyrights',
    'common.challenges': 'Challenges',
    // for beta only
    'beta.notice': 'Καλώς ήρθατε στο Λογοτεχνικό Σύμπαν BETA. Αυτή είναι μια δημόσια προεπισκόπηση και ως εκ τούτου η εφαρμογή είναι ακόμα σε εξέλιξη. Αυτό σημαίνει ότι μπορείτε ακόμα να περιμένετε λάθη και ημιτελή χαρακτηριστικά. Αν αντιμετωπίσετε κάποιο σφάλμα ή κάτι που δεν λειτουργεί, ενημερώστε μας και κάντε υπομονή όσο θα τα βάζουμε όλα στη θέση τους.',
    'beta.thanks': 'Σας ευχαριστούμε για την υποστήριξή σας!',
    'scratchpad.about': 'Οι σημειώσεις και οι ιδέες σας είναι προσβάσιμες οπουδήποτε στον ιστότοπο.',
    'common.feedback': 'Feedback',
    'common.createdOn': 'Created on {date, date, long}',
    'common.createdOn.title': 'Created on',
    // account types
    admin: 'Admin',
    goodbye: 'Thank you! See you again!',
    'common.saved': 'Saved!',
    'common.saving': 'Saving...',
    'common.friends': 'Friends',
    'lang.orig': 'Original language',
    'lang.orig.plus': 'Original language - {language}',
    buy: 'Buy',
    confirm: 'Confirm',
    cancel: 'Cancel',
    processing: 'Processing...',
    'common.noData': 'No data',
    'error.title': 'An error has occurred. We apologize for the inconvenience.',
    'common.offlineStatus': 'You are currently offline.',
    male: 'Male',
    female: 'Female',
    'common.legal.effectiveAt': 'Effective from {date, date, medium}',
    select: 'Please select',
    'common.statusFailed': 'Failed to connect to the server.',
    'common.statusConnecting': 'Attempting to connect to the server... ({count, number})',
    'slug.checking': 'Checking...',
    'slug.failed': 'This address already exists.',
    'slug.success': 'This address is available!',
    'notVerified.msg': `Your account {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    } is not verified.`,
    'notVerified.verify': `Please verify your {option, select,
    email {e-mail}
    wallet {wallet}
    other {e-mail}
    }.`,
    unknown: 'unknown',
    'common.legal.guidelines': 'Community Guidelines',
    'errorLoading.title': 'Error during page load',
    'errorLoading.explained': 'Συνέβη ένα σφάλμα κατά τη φόρτωση της σελίδας. Ζητούμε συγγνώμη για την αναστάτωση. Παρακαλώ προσπαθήστε ξανά να αποκτήσετε πρόσβαση στη σελίδα. Εάν το πρόβλημα εξακολουθεί να υφίσταται, παρακαλούμε ενημερώστε μας.',
    'errorLoading.retry': 'Retry!',
    'errorLoading.takingLong': 'This is taking a long time...',
    'common.title': 'Title',
    'common.timelines': 'Timelines',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'General Data Protection Regulation',
    'editor.placeholder.link': 'Enter URL...',
    'editor.placeholder.connection': 'Search for encyclopedia entry...',
    'editor.saved.beta': 'New revision for Beta readers created!',
    'editor.saved.public': 'New version published!',
    goodbyeForever: 'Λυπούμαστε που σε βλέπουμε να φεύγεις. Ήταν κάτι που κάναμε εμείς; Παρακαλούμε ενημερώστε μας αν αυτό συμβαίνει. Όπως και να έχει, σας ευχόμαστε τα καλύτερα στις μελλοντικές σας προσπάθειες και ελπίζουμε να ξανασυναντηθούμε! Να ζήσετε και να ευημερήσετε!',
    'goodbyeForever.feedback': 'Ενημερώστε μας για το τι μπορούμε να κάνουμε καλύτερα',
    'common.edit': 'Edit',
    'common.publish': 'Publish',
    'common.publishAt': 'Publication date and time',
    'a11y.user.menu': 'User menu',
    'a11y.navigation': 'Navigation',
    'dashboard.profile': 'Your profile',
    'profile.website': 'My personal website',
    'story.notes.concept': 'Concept',
    'story.notes.settings': 'Story setting',
    'story.notes.theme': 'Theme',
    'story.notes.impact': 'Desired impact',
    'story.notes.outcome': 'Outcome',
    'story.notes.audience': 'Target audience',
    'story.notes.pitch': 'Pitch',
    'story.notes.notes': 'Notes',
    'story.authorsNotes': 'Author\'s notes',
    'common.members': 'Members',
    'common.language': 'Language',
    next: 'Next',
    'common.legal.tos.short': 'Terms',
    'common.legal.privacy.short': 'Privacy',
    'premium.increaseLimit': 'Consider upgrading to increase you limit.',
    'common.sharing': 'Sharing',
    'story.isbn': 'ISBN',
    'common.name': 'Name',
    'common.remove': 'Remove',
    'common.time.milliseconds': 'Milliseconds',
    'common.time.seconds': 'Seconds',
    'common.time.minutes': 'Minutes',
    'common.time.hours': 'Hours',
    'common.time.days': 'Days',
    'common.time.weeks': 'Weeks',
    'common.time.months': 'Months',
    'common.time.years': 'Years',
    'common.monetization': 'Monetization',
    'common.tab.monetizationOptions': 'Monetization options',
    'common.pagination': 'Pagination',
    'common.forum': 'Forum',
    'common.2faCode': '2FA code',
    'common.2faCodeIntro': 'Please enter your one time code generated by your authenticator application.',
    'common.2faCodeAria': '2FA code entry form',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Default language',
    'signin.web3.signMessage': 'Please confirm that you want to enter Literary Universe with your wallet as authentication method.'
}    /* eslint-enable max-len */;