export default {
    'feedback.home': 'Κέντρο Βοήθειας',
    'feedback.bugs': 'Προβλήματα',
    'feedback.bugs.desc': 'Συναντήσατε κάποιο σφάλμα ή κάτι άλλο που είναι λάθος ή μη τοποθετημένο. Πείτε μας εδώ!',
    'feedback.features': 'Ιδέες & Προτάσεις',
    'feedback.features.desc': 'Έχετε ιδέες για νέες λειτουργίες ή πώς να κάνετε τον ιστότοπο καλύτερο; Πείτε μας!',
    'feedback.help': 'Βοήθεια & Οδηγοί',
    'feedback.help.desc': 'Πώς μπορείτε να _____; Πηγαίνετε εδώ για να βρείτε τις απαντήσεις.',
    'feedback.desc': 'Καλώς ήρθατε στο κέντρο βοήθειας και επίλυσης προβλημάτων μας!',
    'feedback.faq': 'Συχνές ερωτήσεις',
    'feedback.faq.desc': 'Συχνές ερωτήσεις',
    'feedback.open': 'Ανοιχτό',
    'feedback.closed': 'Κλειστό',
    'feedback.accepted': 'Αποδεκτό',
    'feedback.inprogress': 'Σε εξέλιξη',
    'feedback.completed': 'Ολοκληρωμένο',
    'feedback.fixed': 'Διορθωμένο',
    'feedback.new.bugs': 'Αναφορά νέου προβλήματος',
    'feedback.new.features': 'Πρόταση νέας λειτουργίας',
    'feedback.lang.nosupport': 'Η τρέχουσα γλώσσα σας δεν υποστηρίζεται για τα σχόλια, παρακαλώ γράψτε στα Αγγλικά. Ευχαριστούμε!',
    'feedback.new.thanks': 'Σας ευχαριστούμε για την ειδοποίηση! Θα το εξετάσουμε σύντομα.',
    'feedback.comment.title': 'Σχόλιο',
    'feedback.comment.desc': 'Στείλτε μας τα σχόλιά σας',
    'feedback.comment.legend': 'Τα σχόλιά σας - πείτε μας για οτιδήποτε',
    'feedback.comment.success': 'Σας ευχαριστούμε για τα σχόλιά σας!',
    'feedback.comment.label': 'Το σχόλιό σας',
    'feedback.copyrightReport.title': 'Παραβίαση πνευματικών δικαιωμάτων',
    'feedback.copyrightReport.desc': 'Αναφορά παραβίασης πνευματικών δικαιωμάτων',
    'feedback.report.noUser': 'Πρέπει να είστε συνδεδεμένος για να καταθέσετε μια αναφορά.',
    'feedback.voting.totalVoters': 'Ψήφισαν οι χρήστες: {voted, number}',
    'feedback.voting.upvote': 'Θετική ψήφος',
    'feedback.voting.downvote': 'Αρνητική ψήφος',
    'feedback.voting.score': 'Συνολικό σκορ',
    'feedback.report.title': 'Αναφορά περιεχομένου',
    'feedback.report.typeSelect': 'Ποιο είναι το πρόβλημα εδώ;',
    'feedback.reportType.law': 'Παραβίαση νόμου',
    'feedback.reportType.vulgar': 'Ανάρμοστο/προσβλητικό',
    'feedback.reportType.copyright': 'Παραβίαση πνευματικών δικαιωμάτων',
    'feedback.reportType.storyRating': 'Εσφαλμένη κατάταξη ηλικίας',
    'feedback.reportType.scam': 'Απάτη',
    'feedback.report.submit': 'Αναφορά',
    'feedback.report.submitting': 'Αναφορά...',
    'feedback.report.violationDesc': 'Λεπτομέρειες',
    'feedback.report.reportSaved': 'Σας ευχαριστούμε για την αναφορά! Θα την ερευνήσουμε και θα προβούμε σε ενέργειες αν απαιτείται.',
    'feedback.report.copyrightReportSaved': 'Σας ευχαριστούμε για την αναφορά! Θα την ερευνήσουμε και θα επικοινωνήσουμε μαζί σας.',
    'feedback.report.copyrightOwnershipDesc': 'Δήλωση κυριότητας',
    'feedback.report.copyrightNotice': 'Παρακαλούμε σημειώστε ότι πρέπει να είστε ο νόμιμος κάτοχος του έργου για να χρησιμοποιήσετε αυτήν τη φόρμα. Εάν δεν είστε ο κάτοχος, παρακαλούμε ενημερώστε τον κάτοχο ή χρησιμοποιήστε την άλλη κατηγορία για να μας ενημερώσετε. Λαμβάνουμε τις παραβιάσεις πνευματικών δικαιωμάτων εξαιρετικά σοβαρά και το ίδιο ισχύει για την ακατάλληλη και καταχρηστική χρήση αυτής της φόρμας.',
    'feedback.report.copyrightInternalProperty': 'Έχω δημοσιεύσει αυτό το έργο στο Literary Universe',
    'feedback.reportType.spam': 'Ανεπιθύμητη αλληλογραφία ή απάτη',
    'feedback.reportType.other': 'Άλλα',
    'feedback.report.copyrightType.propertySelectLabel': `Which {type, select,
    universe {universe}
    story {story}
    other {story}
  } is being infringed?`,
    'faq.section.about': 'Σχετικά με εμάς',
    'faq.section.settings': 'Ρυθμίσεις',
    'faq.section.discovery': 'Ανακάλυψη',
    'faq.section.reader': 'Αναγνώστης',
    'faq.section.library': 'Βιβλιοθήκη',
    'faq.section.workshop': 'Εργαστήριο',
    'faq.section.writer': 'Συντάκτης',
    'faq.section.encyclopedia': 'Εγκυκλοπαίδεια',
    'faq.section.groups': 'Ομάδες',
    'faq.section.blogs': 'Ιστολόγια',
    'faq.section.guilds': 'Εταιρείες',
    // About us questions
    'faq.question.about.whatIsLU': 'Τι είναι το Λογοτεχνικό Σύμπαν;',
    'faq.answer.about.whatIsLU': 'Literary Universe is a platform for writers and readers to create, share and discover stories and worlds.',
    'faq.question.about.difference': 'What is the difference between Literary Universe and other online reading platforms?',
    'faq.answer.about.difference': 'Literary Universe is all-in-one platform which means it includes tools for writing, reading, worldbuilding, and community building. The key difference is inclusion of all these tools together in one platform and their interconnectedness.',
    'faq.question.about.dataLocation': 'Πού αποθηκεύονται τα δεδομένα του Λογοτεχνικού Σύμπαντος;',
    'faq.answer.about.dataLocation': 'Τα δεδομένα του Λογοτεχνικού Σύμπαντος αποθηκεύονται σε διακομιστές στις Ηνωμένες Πολιτείες της Αμερικής, συγκεκριμένα στην περιοχή us-east-1 της AWS.',
    'faq.question.about.incorporation': 'Σε ποια εταιρεία είστε ενσωματωμένοι;',
    'faq.answer.about.incorporation': 'Το Literary Universe είναι ενσωματωμένο στην Τσεχική Δημοκρατία. Μπορείτε να βρείτε περισσότερες λεπτομέρειες στην <a href="/about">σελίδα για εμάς</a>.',
    'faq.question.about.roadmap': 'Ποια είναι τα επόμενα βήματα για το Literary Universe;',
    'faq.answer.about.roadmap': 'Αυτό εξελίσσεται συνεχώς. Ρίξτε μια ματιά στο <a href="/roadmap">χάρτη πορείας</a> μας για περισσότερες λεπτομέρειες.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Πώς μπορώ να αλλάξω την εμφάνιση του Literary Universe;',
    'faq.answer.settings.changeTheme': 'Οι εγγεγραμμένοι χρήστες μπορούν να αλλάξουν το θέμα τους στις <a href="/user/settings/account">ρυθμίσεις λογαριασμού</a> στην ενότητα "εμφάνιση ιστότοπου". Έχουμε διαθέσιμο ένα φωτεινό και ένα σκοτεινό θέμα. Αν δεν είστε εγγεγραμμένοι, τότε προσπαθούμε να καθορίσουμε ποιο θέμα να σας εξυπηρετήσουμε με βάση τις ρυθμίσεις του προγράμματος περιήγησης και του λειτουργικού συστήματος σας.',
    'faq.question.settings.changeAvatar': 'Πώς μπορώ να αλλάξω το αβατάρ μου;',
    'faq.answer.settings.changeAvatar': 'Μπορείτε να αλλάξετε το αβατάρ σας στις <a href="/user/settings/profile">ρυθμίσεις προφίλ</a>.',
    'faq.question.settings.changeLanguage': 'Πώς μπορώ να αλλάξω τη γλώσσα;',
    'faq.answer.settings.changeLanguage': 'Μπορείτε να αλλάξετε τη γλώσσα του Literary Universe στις <a href="/user/settings/account">ρυθμίσεις λογαριασμού</a>.',
    'faq.question.settings.translationMistake': 'Βρήκα ένα λάθος στο κείμενο του ιστότοπου, πού μπορώ να το αναφέρω;',
    'faq.answer.settings.translationMistake': 'Όλα τα αρχεία γλώσσας μας είναι διαθέσιμα στο GitHub. Μπορείτε να <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">υποβάλετε ένα θέμα εκεί</a> ή στην ενότητα Σφάλματα της ανατροφοδότησης, ή αν το επιθυμείτε, μπορείτε να το διορθώσετε απευθείας μόνοι σας μέσω <a href="https://crowdin.com/project/literary-universe" target="_blank">της σελίδας μας στο Crowdin</a>.',
    // Discovery questions
    'faq.question.discovery.explain': 'What is the Discovery section?',
    'faq.answer.discovery.explain': 'The Discovery section is where you can find new stories, universes, blogs, groups and other content. It is a place to explore and find new things to read and enjoy.',
    // Writer
    'faq.question.writer.howToCreateStory': 'How do I create a new story in Literary Universe?',
    'faq.answer.writer.howToCreateStory': 'You can create a new story by going to the <a href="/workshop">workshop</a> and clicking on one of the create buttons or go to the main <a href="/workshop/create">create page</a> where you can select a <a href="/workshop/create/story">new standalone story</a> or <a href="/workshop/create/fanfiction">fan fiction</a>. To create a new story in a universe, go first to that universe and then select "stories" on the dashboard and on the next page click the big red button on the right side of the page title. You will be asked to fill in the details of your story and then you can start writing.',
    'faq.question.writer.schedule': 'How do I schedule a chapter to be released in Literary Universe?',
    'faq.answer.writer.schedule': 'You can schedule a chapter to be released when clicking on the publish button in the chapter editor. A modal will be shown where you will have the option to schedule a release or publish immediately. If you choose to schedule a release, you will be asked to select the date and time when you want the chapter to be released. We recommend scheduling chapters at least 24 hours in advance to give readers time to prepare for the new chapter and to release on the same day and time of the week.',
    // Reader
    'faq.question.reader.creativeTypes': 'What is the difference between Universe, Stories and Fan Fiction?',
    'faq.answer.reader.creativeTypes': 'Universe is a place where you can find all the stories and other content related to a specific literary world. Stories are either standalone stories or part of a universe that. Fan Fiction is a story that is based on another literary universe created by someone else.',
    // Workshop
    'faq.question.workshop.explain': 'What is the Workshop?',
    'faq.answer.workshop.explain': 'The Workshop is where you can create new stories, fan fiction, universes, and other content. It is a place to write, edit and manage your creative content.',
    'faq.question.workshop.creativeTypes': 'What is the difference between Universe, Stories and Fan Fiction?',
    'faq.answer.workshop.creativeTypes': 'Universe is a central place for your literary universe in which you create stories that inhabit the same literary world, manage encyclopedia with all the intricacies of your world and do anything else related to it. Fan Fiction is a story that is based on another story or universe created by someone else. Standalone stories are stories that are not connected to any universe, use this for example for poetry or literary works that are set in real world without many characters or immersive details that would require encyclopedia or other benefits of having a universe.',
    'faq.question.workshop.continueStory': 'How do I continue a previously created story?',
    'faq.answer.workshop.continueStory': 'You can continue a previously created story by going to the <a href="/workshop">workshop</a> and selecting the story you want to continue or if it is a story in a universe, you need to first go to the universe and select the story from the stories listing. On the story dashboard you can then click on the chapter you want to continue writing or create a new chapter.',
    'faq.question.workshop.whatIsALicense': 'What is a Story License?',
    'faq.answer.workshop.whatIsALicense': 'A story license is a legal document that defines how your story/universe can be used by others. It is a way to protect your rights and to define how others can use your work.',
    'faq.question.workshop.licenses': 'What licenses are available?',
    'faq.answer.workshop.licenses': 'We offer a variety of licenses to choose from. When creating a new work in the licenses section will be a button which will list all available licenses with their full details. In general we offer full copyright protections and <a href="https://creativecommons.org/" target="_blank" rel="noreferrer noopener external">Creative Commons</a> licenses.',
    'faq.question.workshop.guildOwnership': 'What is a Guild ownership?',
    'faq.answer.workshop.guildOwnership': 'Guild ownership indicated a work that is owned by an organization, we call them Guilds. This could be a publisher or another type of a company or non-profit organization. The ownership of the work is usually bit more complex and the author might not have full control over the work, it mainly means that the work is managed through the organization and not by the author from their personal account.',
    'faq.question.workshop.howToInviteCollaborators': 'How do I invite collaborators for a story/universe?',
    'faq.answer.workshop.howToInviteCollaborators': 'You can invite collaborators to your story/universe by going to the story/universe dashboard and clicking the "collaborators" button. There you can invite other users to collaborate on your story/universe by entering their username and selecting the role you want to assign to them.',
    'faq.question.workshop.howToTranslation': 'How can I translate my story or universe?',
    'faq.answer.workshop.howToTranslation': 'You can translate your story or universe by going to the story/universe dashboard and clicking the "Translations" button. There you can add a new translations for your work and if you have someone to do the translation you can invite them to join on the translation. From there you can also manage the translations yourself.',
    'faq.question.workshop.betaReaders': 'What are Beta Readers and what is their purpose to my story?',
    'faq.answer.workshop.betaReaders': 'Beta readers are people who read your story before it is published and give you feedback. They can help you find mistakes, give you ideas for improvement, and help you make your story better.',
    'faq.question.workshop.hiatus': 'What is a hiatus in the story status?',
    'faq.answer.workshop.hiatus': 'Hiatus is a status for your story that indicates that you are taking a break from writing and publishing new chapters. It is a way to let your readers know that you are not actively working on the story at the moment. This status gets set automatically after 6 months without any new chapters. After additional 6 months of inactivity the story will be marked as cancelled.',
    'faq.question.workshop.finished': 'How do I indicate that my story is finished?',
    'faq.answer.workshop.finished': 'You can indicate that your story is finished by going to the story dashboard and on the bottom there is a green button which says "Change story status to Completed". This will mark the story as finished adjusting the last page to tell the readers that the story is finished and to check out your other works. It will also indicate so in discovery making your story more visible to readers who are looking for finished stories.',
    'faq.question.workshop.seo': 'What is the use of SEO-Friendly-Address in various settings?',
    'faq.answer.workshop.seo': 'SEO-Friendly-Address is a way to make your story, universe, blog post more visible to search engines and easier to read URL for humans. It is a way to make your work more discoverable and to help people find your work when they search for something similar.'
};