export default {
    'org.auditLog.title': 'Αρχείο καταγραφής ελέγχου',
    'org.settings.title': 'Ρυθμίσεις οργανισμού',
    'org.settings.name': 'Όνομα οργανισμού',
    'org.settings.membersPrivate': 'Να ΜΗΝ εμφανίζονται οι μέλη δημόσια',
    'org.logo': 'Λογότυπο οργανισμού',
    'org.logo.alt': '{organizationName} λογότυπο',
    'org.superAdmin': 'Υπερδιαχειριστής',
    'org.settings.language': 'Κύρια γλώσσα',
    'org.meta.desc': 'Οργανισμοί και δημιουργικές ομάδες στο Literary Universe.',
    'org.luOrgs': 'Οργανισμοί του Literary Universe',
    'org.otherOrgs': 'Οργανισμοί',
    'org.aboutTitle': 'Σχετικά με το {orgName}',
    'org.membersTitle': 'Μέλη του οργανισμού',
    'org.membersNone': 'Τα μέλη δεν είναι δημόσια',
    'org.storiesTitle': 'Ιστορίες από τον {orgName}',
    'org.universesTitle': 'Σύμπαντα από τον {orgName}',
    'org.userDashboardTitle': 'Οι οργανισμοί σας',
    'org.settings.hideMembers.label': 'Απόκρυψη μελών από το κοινό',
    'org.visit': 'Μετάβαση στη σελίδα {organization}',
    'org.authorOverride.legend': 'Παράκαμψη συγγραφέα',
    'org.authorOverride.desc': 'Εμφανίζει αυτό το κείμενο αντί του ονόματος του οργανισμού.',
    'org.authorOverride.label': 'Όνομα του συγγραφέα',
    'org.membersAdd.title': 'Πρόσκληση μελών στον οργανισμό',
    'org.flashnews.admin': 'Διαχείριση Flashnews',
    'org.settings.tabListAria': 'Ρύθμιση ενοτήτων για τον οργανισμό',
    'org.forums.title': '{orgName} φόρουμ',
    'org.flashnews.internal': 'Εσωτερικά flash ειδήσεων',
    'org.flashnews.publicAll': 'Δημόσια flash ειδήσεις για όλες τις ιδιότητες',
    'org.flashnews.createTitle': `Δημιουργήστε ένα νέο news flash για {type, select,
    internal {τον οργανισμό}
    allProperties {εμφάνιση στο κοινό σε όλες τις ιδιότητες}
    other {τον οργανισμό}
  }`,
    'org.members.invited': 'Προσκεκλημένα μέλη',
    'org.members.list': 'Μέλη του οργανισμού',
    'org.invitesTileNotice': 'Έχετε προσκληθεί στον/στην {count, number} {count, plural, one {οργανισμός} other {οργανισμοί}}',
    'org.invitePage.title': 'Προσκλήσεις σε οργανισμούς',
    'org.invitePage.invitedAt': 'Έχετε προσκληθεί στον/στην {invitedAt, date, short}.',
    'org.invitePage.ignoring': 'Αυτή η πρόσκληση είναι ακόμα ενεργή, αλλά δεν ενοχλεί με ειδοποιήσεις, καθώς την αγνοείτε.',
    'org.invitePage.expiresAt': 'Αυτή η πρόσκληση θα λήξει στις {expiresAt, date, short} {expiresAt, time}',
    'org.invitePage.accept': 'Εγγραφή στον οργανισμό',
    'org.invitePage.reject': 'Απόρριψη πρόσκλησης',
    'org.invitePage.ignore': 'Αγνόηση αυτήν τη στιγμή',
    'org.leaveOrg.title': 'Αποχώρηση από τον οργανισμό',
    'org.leaveOrg.confirm': 'Αυτή είναι μια καταστροφική ενέργεια. Μόλις αποχωρήσετε, θα χάσετε όλη την πρόσβαση σε αυτόν τον οργανισμό. Είστε σίγουρος/η ότι θέλετε να αποχωρήσετε από τον οργανισμό;',
    'org.confirmRemove.aria': 'Επιβεβαίωση αφαίρεσης χρήστη',
    'org.confirmRemove.confirm': 'Είστε σίγουρος/η ότι θέλετε να αφαιρέσετε τον/την {username} από τον/την {organization};',
    'org.confirmRemove.remove': 'Αφαίρεση χρήστη',
    'org.mainBlog': 'Κύριο ιστολόγιο',
    'org.teams': 'Ομάδες',
    'org.teams.total': 'Συνολικές ομάδες: {totalTeams, number}',
    'org.teams.create': 'Δημιουργία νέας ομάδας',
    'org.teams.settings': 'Ρυθμίσεις ομάδας',
    'org.workshop.ownerUser': 'Δεν είναι έργο συντεχνίας',
    'org.workshop.caption': 'Ιδιοκτησία συντεχνίας',
    'org.workshop.title': 'Εργαστήριο Οργάνωσης',
    'org.title': 'Οργάνωση',
    'org.hall.title': '{orgName} αίθουσα μελών',
    'org.member.leave': 'Αφήστε την οργάνωση',
    'org.member.leaveModalTitle': 'Επιβεβαίωση αποχώρησης οργανισμού',
    'org.member.leaveModalHeading': 'Είσαι σίγουρος ότι θέλεις να φύγεις {orgName}',
    'org.member.leaveModalExplain': 'Μόλις αποχωρήσετε από τον οργανισμό, θα χάσετε την πρόσβασή σας σε όλους τους σχετικούς πόρους και τα έργα του οργανισμού. Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
    // Role management strings
    'org.member.manageRoles': 'Διαχείριση ρόλων',
    'org.roles.error': 'Σφάλμα: {error}',
    'org.roles.manageFor': 'Διαχείριση ρόλων για το {name}',
    'org.roles.selectRole': 'Επιλέξτε ρόλο',
    'org.roles.noRole': 'Κανένας ρόλος (μόνο δικαιώματα)',
    'org.roles.admin': 'Διαχειριστής',
    'org.roles.member': 'Μέλος',
    'org.roles.author': 'Συγγραφέας',
    'org.roles.workshop': 'Εργαστήριο',
    'org.roles.teacher': 'Δάσκαλος',
    'org.permissions.title': 'Δικαιώματα',
    'org.permissions.includedInRole': '(περιλαμβάνεται στο ρόλο)',
    // Permission names
    'org.permissions.members.add': 'Προσθήκη μελών',
    'org.permissions.members.remove': 'Διαγραφή μελών',
    'org.permissions.members.view': 'Προβολή μελών',
    'org.permissions.settings': 'Διαχείριση ρυθμίσεων',
    'org.permissions.auditLog': 'Προβολή αρχείου καταγραφής ελέγχου',
    'org.permissions.flashnews': 'Διαχείριση ειδήσεων flash',
    'org.permissions.workshop.view': 'Προβολή εργαστηρίου',
    'org.permissions.workshop.create': 'Δημιουργία αντικειμένων εργαστηρίου',
    'org.permissions.workshop.transfer': 'Μεταβίβαση ιδιοκτησίας',
    'org.permissions.workshop.viewAll': 'Προβολή όλων των αντικειμένων του εργαστηρίου',
    'org.permissions.forum.manager': 'Διαχείριση φόρουμ',
    'org.permissions.blog.manage': 'Διαχείριση ιστολογίου',
    'org.permissions.blog.post': 'Δημιουργία αναρτήσεων στο blog'
};