export default {
  'personalNotes.personalNotes': 'Προσωπικές Σημειώσεις',
  'personalNotes.chooseType': 'Επιλέξτε τον τύπο προσωπικής σημείωσης',
  'personalNotes.storyNotes': 'Σημειώσεις Ιστορίας',
  'personalNotes.chapterNotes': 'Σημειώσεις Κεφαλαίου',
  'personalNotes.universeNotes': 'Σημειώσεις Σύμπαντος',
  'personalNotes.encyclopediaNotes': 'Σημειώσεις Εγκυκλοπαίδειας',
  'personalNotes.storyPersonalNotesHeading': 'Προσωπικές Σημειώσεις για Ιστορίες',
  'personalNotes.encyclopediaPersonalNotesHeading': 'Προσωπικές Σημειώσεις για Εγκυκλοπαίδεια',
  'personalNotes.searchPersonalNotesHeading': 'Αναζήτηση Προσωπικών Σημειώσεων',
  'personalNotes.goToStory': 'Μετάβαση στην Ιστορία',
  'personalNotes.goToChapter': 'Μετάβαση στο Κεφάλαιο',
  'personalNotes.goToEncyclopedia': 'Μετάβαση στην Εγκυκλοπαίδεια του Σύμπαντος',
  'personalNotes.goToEncEntry': 'Μετάβαση στην καταχώρηση',
  'personalNotes.closeDropdown': 'Κλείστε το αναπτυσσόμενο μενού',
  'personalNotes.chapterName': 'Κεφάλαιο {sequence} - {title}',
  'personalNotes.objectPersonalNotes': 'Καταχώρηση {object} προσωπικής σημείωσης',
  'personalNotes.searchResults': 'Αποτελέσματα Αναζήτησης',
  'personalNotes.type.story': 'Ιστορία',
  'personalNotes.type.universe': 'Σύμπαν',
  'personalNotes.type.chapter': 'Κεφάλαιο',
  'personalNotes.type.encEntry': 'Καταχώρηση Εγκυκλοπαίδειας',
  'personalNotes.type.revTextBlock': 'Τμήμα Αναθεώρησης Κειμένου',
  'personalNotes.chapter': 'Κεφάλαιο',
  'personalNotes.recentSearches': 'Πρόσφατες Αναζητήσεις:'
};