export default {
    'stats.age.groups': 'Ομάδες ηλικίας',
    'stats.age.range': 'Εύρος ηλικίας',
    'stats.age.to12': 'Έως 12',
    'stats.age.12to17': '12 έως 17',
    'stats.age.18to20': '18 έως 20',
    'stats.age.21to29': '21 έως 29',
    'stats.age.30to39': '30 έως 39',
    'stats.age.40to49': '40 έως 49',
    'stats.age.50to64': '50 έως 64',
    'stats.age.65to84': '65 έως 84',
    'stats.age.above85': 'Άνω των 85',
    'stats.section.aggregate': 'Συγκεντρωτικά στατιστικά στοιχεία',
    'stats.section.chapter': 'Στατιστικά στοιχεία κεφαλαίου',
    'stats.readers.title': 'Σχετικά με τους αναγνώστες σας',
    'stats.gender.title': 'Φύλο',
    'stats.view.table': 'Προβολή σε μορφή πίνακα',
    'stats.view.pie': 'Προβολή σε μορφή διαγράμματος πίτας',
    'stats.view.bar': 'Προβολή σε μορφή διαγράμματος γραμμής',
    'stats.view.chart': 'Προβολή σε μορφή γραφήματος',
    'stats.table.total': 'Σύνολο',
    'stats.timeline.title': 'Χρονολόγιο',
    'stats.timeline.dateStart': 'Τα στατιστικά ξεκινούν στις',
    'stats.timeline.dateEnd': 'Τα στατιστικά τελειώνουν στις',
    'stats.likeCount': 'Αριθμός αρέσεων',
    'stats.language.title': 'Γλώσσα που μιλιέται',
    'stats.chapter.visitorsAndViews': 'Συνολικοί επισκέπτες και προβολές ανά κεφάλαιο',
    'stats.chapter.wordCount': 'Αριθμός λέξεων ανά κεφάλαιο',
    'stats.chapter.chartTooltipViews': 'Κεφάλαιο {chapter, number}: {views, number} προβολές',
    'stats.chapter.chartTooltipVisitors': 'Κεφάλαιο {chapter, number}: {visitors, number} μοναδικοί επισκέπτες',
    'stats.chapter.chartTooltipWordCount': 'Κεφάλαιο {chapter, number}: {wordCount, number} λέξεις',
    'stats.totalHits': 'Συνολικές προβολές',
    'stats.totalVisitors': 'Συνολικοί μοναδικοί επισκέπτες',
    'stats.totalWords': 'Συνολικές λέξεις',
    'stats.totalEntries': 'Καταχωρήσεις εγκυκλοπαίδειας',
    'stats.blogPage': 'Σελίδα',
    'stats.blog.typeSelectionAria': 'Επιλογή τύπου',
    'stats.blog.pages': 'Σελίδες',
    'stats.blog.posts': 'Θέσεις',
    'stats.unknown': 'Άγνωστο',
    'stats.noData': 'Δεν υπάρχουν διαθέσιμα δεδομένα αυτή τη στιγμή.',
    // Author overall statistics
    'workshop.theWay.overallStats.noData': 'Δεν υπάρχουν ακόμη διαθέσιμα στατιστικά στοιχεία. Ξεκινήστε να δημοσιεύετε το έργο σας για να δείτε τα στατιστικά σας!',
    'workshop.theWay.overallStats.content': 'Το περιεχόμενό σας',
    'workshop.theWay.overallStats.stories': 'Ιστορίες',
    'workshop.theWay.overallStats.universes': 'Σύμπαντα',
    'workshop.theWay.overallStats.chapters': 'Κεφάλαια',
    'workshop.theWay.overallStats.wordCount': 'Γραπτά λόγια',
    'workshop.theWay.overallStats.encyclopediaEntries': 'Ενδείξεις εγκυκλοπαίδειας',
    'workshop.theWay.overallStats.publishingStreak': 'Εβδομάδα Publishing Streak',
    'workshop.theWay.overallStats.monthlyPublicationStreak': 'Μήνας Σειρά δημοσίευσης',
    'workshop.theWay.overallStats.audience': 'Το κοινό σας',
    'workshop.theWay.overallStats.fans': 'Ανεμιστήρες',
    'workshop.theWay.overallStats.followers': 'Ακολουθητές',
    'workshop.theWay.overallStats.uniqueReaders': 'Μοναδικοί αναγνώστες',
    'workshop.theWay.overallStats.storyViews': 'Προβολές ιστορίας',
    'workshop.theWay.overallStats.universeViews': 'Όψεις του σύμπαντος',
    'workshop.theWay.overallStats.readingTime': 'Χρόνος ανάγνωσης (λεπτά)',
    'workshop.theWay.overallStats.demographics': 'Δημογραφικά στοιχεία αναγνωστών',
    'workshop.theWay.overallStats.topCountry': 'Κορυφή Χώρα',
    'workshop.theWay.overallStats.topAgeGroup': 'Κορυφαία ηλικιακή ομάδα',
    'workshop.theWay.overallStats.genres': 'Τα είδη σας'
};