export default {
    'feedback.home': 'Centre d\'aide',
    'feedback.bugs': 'Problèmes',
    'feedback.bugs.desc': 'Vous avez rencontré une erreur ou quelque chose d\'anormal ou de déplacé. Faites-le nous savoir ici !',
    'feedback.features': 'Idées & Propositions',
    'feedback.features.desc': 'Vous avez des idées pour de nouvelles fonctionnalités ou pour améliorer le site ? Faites-nous en part !',
    'feedback.help': 'Aide & Tutoriels',
    'feedback.help.desc': 'Comment faire pour _____ ? Allez ici pour trouver les réponses.',
    'feedback.desc': 'Bienvenue dans notre centre d\'aide et de résolution !',
    'feedback.faq': 'FAQ',
    'feedback.faq.desc': 'Questions fréquemment posées',
    'feedback.open': 'Ouvert',
    'feedback.closed': 'Fermé',
    'feedback.accepted': 'Accepté',
    'feedback.inprogress': 'En cours',
    'feedback.completed': 'Complété',
    'feedback.fixed': 'Fixé',
    'feedback.new.bugs': 'Signaler un nouveau problème',
    'feedback.new.features': 'Suggérer une nouvelle fonctionnalité',
    'feedback.lang.nosupport': 'Votre langue actuelle n\'est pas prise en charge pour les feedback, veuillez écrire en anglais. Merci !',
    'feedback.new.thanks': 'Merci pour l\'avis ! Nous allons nous en occuper rapidement.',
    'feedback.comment.title': 'Commentaire',
    'feedback.comment.desc': 'Envoyez-nous vos feedbacks',
    'feedback.comment.legend': 'Votre feedback - faites-nous part de tout ce que vous voulez',
    'feedback.comment.success': 'Merci pour votre feedback !',
    'feedback.comment.label': 'Votre commentaire',
    'feedback.copyrightReport.title': 'Violation du droit d\'auteur',
    'feedback.copyrightReport.desc': 'Signaler une violation du droit d\'auteur',
    'feedback.report.noUser': 'Vous devez être enregistré pour pouvoir rédiger un rapport.',
    'feedback.voting.totalVoters': 'Les utilisateurs ont voté : {voted, number}',
    'feedback.voting.upvote': 'Vote positif',
    'feedback.voting.downvote': 'Vote négatif',
    'feedback.voting.score': 'Score total',
    'feedback.report.title': 'Signaler le contenu',
    'feedback.report.typeSelect': 'Quel est le problème ?',
    'feedback.reportType.law': 'Violation de la loi',
    'feedback.reportType.vulgar': 'Vulgaire/obscène',
    'feedback.reportType.copyright': 'Violation du droit d\'auteur',
    'feedback.reportType.storyRating': 'Classement par âge incorrect',
    'feedback.reportType.scam': 'Arnaque',
    'feedback.report.submit': 'Signaler',
    'feedback.report.submitting': 'Signalement en cours...',
    'feedback.report.violationDesc': 'Détails',
    'feedback.report.reportSaved': 'Merci pour le rapport ! Nous allons enquêter et prendre des mesures si nécessaire.',
    'feedback.report.copyrightReportSaved': 'Merci pour le rapport ! Nous allons enquêter et prendre contact avec vous.',
    'feedback.report.copyrightOwnershipDesc': 'Déclaration de propriété',
    'feedback.report.copyrightNotice': 'Veuillez noter que vous devez être le propriétaire légitime de l\'œuvre pour utiliser ce formulaire. Si vous n\'êtes pas le propriétaire, veuillez en informer le propriétaire ou utiliser l\'autre catégorie pour nous en informer. Nous prenons très au sérieux les violations du droit d\'auteur et il en va de même pour l\'utilisation inappropriée et abusive de ce formulaire.',
    'feedback.report.copyrightInternalProperty': 'J\'ai publié ce travail sur l\'Univers Littéraire',
    'feedback.reportType.spam': 'Spam ou hameçonnage',
    'feedback.reportType.other': 'Autre',
    'feedback.report.copyrightType.propertySelectLabel': `Quel {type, select,
    universe {univers}
    story {histoire}
    other {histoire}
  } est en train d'être violée ?`,
    'faq.section.about': 'À propos de nous',
    'faq.section.settings': 'Paramètres',
    'faq.section.discovery': 'Découverte',
    'faq.section.reader': 'Lecteur',
    'faq.section.library': 'Bibliothèque',
    'faq.section.workshop': 'Workshop',
    'faq.section.writer': 'Écrivain',
    'faq.section.encyclopedia': 'Encyclopédie',
    'faq.section.groups': 'Groupes',
    'faq.section.blogs': 'Blogs',
    // About us questions
    'faq.question.about.dataLocation': 'Où les données de LU sont-elles stockées?',
    'faq.answer.about.dataLocation': 'Les données de l\'Univers Littéraire sont stockées sur des serveurs aux États-Unis d\'Amérique, plus précisément dans la région AWS us-east-1.',
    'faq.question.about.incorporation': 'Où êtes-vous incorporé?',
    'faq.answer.about.incorporation': 'L\'Univers Littéraire est incorporé en République tchèque. Vous pouvez trouver plus de détails sur la page <a href="/about">à propos de nous</a>.',
    'faq.question.about.roadmap': 'Quelles sont les prochaines étapes pour l\'Univers Littéraire?',
    'faq.answer.about.roadmap': 'This is constantly evolving. Check out our <a href="/roadmap">roadmap</a> for more details.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Comment changer l\'apparence de l\'Univers Littéraire?',
    'faq.answer.settings.changeTheme': 'Registered users can change their theme in the <a href="/user/settings/account">account settings</a> under "site theming" section. We have a light and a dark theme available. If you are not registered, then we try to determine which theme to serve you based on your browser and operating system settings.',
    'faq.question.settings.changeAvatar': 'Comment changer mon avatar?',
    'faq.answer.settings.changeAvatar': 'You can change your avatar in the <a href="/user/settings/profile">profile settings</a>.',
    'faq.question.settings.changeLanguage': 'Comment changer la langue?',
    'faq.answer.settings.changeLanguage': 'You can change the language of Literary Universe in the <a href="/user/settings/account">account settings</a>.',
    'faq.question.settings.translationMistake': 'J\'ai trouvé une erreur dans le texte sur le site web, où puis-je la signaler?',
    'faq.answer.settings.translationMistake': 'All our language files are available on GitHub. You can <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">submit an issue there</a> or in the Bug section of the feedback, or if you are so inclined, you can fix it directly yourself via <a href="https://crowdin.com/project/literary-universe" target="_blank">our Crowdin page</a>.'
};