export default {
  'forum.thread.reply': 'Ajouter une réponse à ce fil de discussion',
  'forums.archive': 'Archiver le forum',
  'forums.archive.explained': 'L\'archivage du forum empêchera les utilisateurs de publier d\'autres contenus, mais il restera visible.',
  'forums.archive.success': 'Le forum a été archivé',
  'forums.archived.forum': 'Ce forum a été archivé le {archivedAt, date, long}. Vous pouvez toujours consulter les forums, mais vous n\'êtes plus en mesure de créer un nouveau contenu.',
  'forums.category.archive': 'Archiver la catégorie',
  'forums.category.archiveExplained': 'Les catégories qui n\'ont pas de fils de discussion seront supprimées, tandis que les catégories avec du contenu empêcheront la création de nouveaux fils de discussion.',
  'forums.category.back': 'Retour à l\'aperçu du forum',
  'forums.category.create': 'Créer une catégorie de forum',
  'forums.category.delete': 'Supprimer cette catégorie',
  'forums.category.intlName.announcements': 'Annonces',
  'forums.category.intlName.art': 'Art',
  'forums.category.intlName.characters': 'Personnages',
  'forums.category.intlName.community': 'Communauté',
  // Pre-defined category names
  'forums.category.intlName.general': 'Général',
  'forums.category.intlName.help': 'Aide',
  'forums.category.intlName.history': 'Histoire',
  'forums.category.intlName.inspiration': 'Inspiration',
  'forums.category.intlName.locations': 'Emplacements',
  'forums.category.intlName.meetups': 'Rencontres',
  'forums.category.intlName.news': 'Actualités',
  'forums.category.intlName.questions': 'Questions',
  'forums.category.intlName.stories': 'Histoires',
  'forums.category.intlName.universe': 'Univers',
  'forums.category.intlName.universes': 'Univers',
  'forums.category.intlNameDescription': 'Nous avons localisé les titres des noms de catégorie courants pour votre sélection, afin que la catégorie soit disponible dans toutes les langues prises en charge.',
  'forums.category.isVotable': 'Autoriser les utilisateurs à voter vers le haut/vers le bas les fils de discussion',
  'forums.category.language': 'Limiter l\'affichage de cette catégorie à la langue suivante. Laisser vide si vous voulez afficher la catégorie dans toutes les langues.',
  'forums.category.languageLimited': 'Cette catégorie ne s\'affichera que pour les utilisateurs dans cette langue.',
  'forums.category.name': 'Nom de catégorie',
  'forums.category.reactivate': 'Réactiver la catégorie',
  'forums.category.settings': 'Paramètres de catégorie',
  'forums.category.slug': 'Partie d\'url SEO',
  'forums.category.titleIsGlobal': 'Le titre de cette catégorie sera affiché dans la langue de l\'utilisateur si nous le prenons en charge.',
  'forums.create': 'Activer le forum',
  'forums.createQuestionLabel': 'Est-ce une question ?',
  // Threads
  'forums.createThread': 'Créer une nouvelle discussion',
  'forums.createThreadIn': 'Créer un nouveau fil de discussion dans {categoryName}',
  // Forum restrictions
  'forums.forumRestriction.usersOnly': 'N\'autoriser l\'accès qu\'aux utilisateurs enregistrés',
  'forums.forumRestrictionsMessages.usersOnlyForum': 'Ce forum n\'est accessible qu\'aux utilisateurs enregistrés.',
  'forums.noPosts': 'Personne n\'a encore répondu. Soyez le premier !',
  'forums.noThreads': 'Rien à voir ici. C\'est à vous de commencer la conversation.',
  'forums.openingPost': 'Ouverture d\'un post',
  'forums.post': 'Poster',
  'forums.post.new': 'Nouveau post',
  'forums.posting': 'Publication...',
  'forums.reply': 'Répondre',
  'forums.reset': 'Réinitialiser',
  'forums.settings': 'Paramètres du forum',
  'forums.settings.accessControls': 'Contrôles d\'accès',
  'forums.thread.createdAt': 'Créé le {createdAt, date, medium}',
  'forums.thread.delete': 'Supprimer le fil de discussion',
  'forums.thread.new': 'Nouveau fil de discussion',
  'forums.thread.noReplies': 'Il n\'y a actuellement aucune réponse ici.',
  'forums.thread.replyPosted': 'Votre message a été publié',
  'forums.thread.totalPosts': `{totalReplies, number} {totalReplies, plural,
    one {réponse}
    other {réponses}
  }`,
  'forums.threadsCounter': 'Nombre total de sujets de discussion',
  'forums.unArchive': 'Réactiver les forums',
  'forums.unArchive.success': 'Le forum a été réactivé !',
  'forums.universeTitle': 'Forums de l\'Univers pour {universeName}',
  'forums.yourMessage': 'Votre message'
};