export default {
    'homepage.welcome': 'Bienvenue dans',
    'homepage.start': 'Commencez votre voyage !',
    'homepage.iAm': 'Je suis un',
    'homepage.iAm.aria': 'Select between display of features for readers and writers',
    'homepage.reader': 'READER',
    'homepage.writer': 'WRITER',
    'homepage.reader.title': 'Reading has never been so interesting like this',
    'homepage.reader.readingTitle': 'Unique reading experience',
    'homepage.reader.readingDesc': 'Delve deeper into your favorite fictional universe in Literary Universe. Stories in Literary Universe are connected within the same universe, giving you immediate access to the universe encyclopedia from the story reader.',
    'homepage.reader.favoriteTitle': 'Find out more about Your favorite stories and authors',
    'homepage.reader.favoriteDesc': 'Universe encyclopedia and author\'s blogs are just a few feature that will help you find out everything you need to know about your favorite stories, their settings and their creators!',
    'homepage.reader.communityTitle': 'Join the community',
    'homepage.reader.communityDesc': 'Meet people from across the globe on dedicated universe and author\'s forums, blogs and other community features where like-minded fans gather. All in one place.',
    'homepage.reader.readingFeatureTitle': 'Enjoy an immersive yet practical reading experience',
    'homepage.reader.readingFeatureDesc': 'From stories and universe, have the benefit of effortless reading with access to details without needing to switch between pages.',
    'homepage.reader.readingExploreTitle': 'Explore all the minutia in the universe',
    'homepage.reader.readingExploreDesc': 'Universe encyclopedia allows you to learn all the details about the universe and fully immerse yourself in the stories.',
    'homepage.reader.start': 'Start Reading',
    'homepage.writer.title': 'Showcase your universe and share your stories',
    'homepage.writer.writingTitle': 'Writing & creating made easy',
    'homepage.writer.writingDesc': 'Experience the new way of writing with Literary Universes Workshop. Create all the details of your universe in an encyclopedia to share with your readers and write amazing stories on that foundation.',
    'homepage.writer.collaborationTitle': 'Collaborative creation',
    'homepage.writer.profitDesc': 'Creative process often involves multiple people. No worries, we got you covered! You can easily add beta readers, co-authors and translators to your stories and universes.',
    'homepage.writer.communityTitle': 'Connect with Your readers',
    'homepage.writer.communityDesc': 'Go beyond writing and connect with your readers via blogs, forums and other community features connected to your universes or to you as a writer.',
    'homepage.writer.workshopFeatureTitle': 'One place for all your creative needs',
    'homepage.writer.workshopFeatureDesc': 'Our ever evolving workshop is the central place for your creative needs. From a simple idea create amazing universes, stories and everything else that is needed around it.',
    'homepage.writer.monetizationFeatureTitle': 'Monetization',
    'homepage.writer.monetizationDesc': 'We strongly believe that people should be payed for their work and are constantly looking for new monetization opportunities for writers. Monetization feature allows you writers to be appreciated for what you do. Explore all the different options that allow your fans to show you their appreciation.',
    'homepage.writer.start': 'Setup Your workshop!',
    'homepage.featureSelection': 'Check out these popular universe!',
    'about.title': 'À propos de l\'Univers Littéraire',
    'about.desc': 'Histoire, secrets et humains derrière l\'univers littéraire.',
    'about.text.1': 'L\'Univers Littéraire est conçu à la fois pour les écrivains et pour les lecteurs passionnés. Les écrivains peuvent utiliser le site pour rédiger des œuvres originales grâce au bouton "workshop" du menu du tableau de bord. Vous aurez ainsi accès aux fonctions principales de l\'éditeur et de l\'encyclopédie, qui visent principalement à organiser tous les aspects de votre univers narratif personnel en une seule page. Les aspects sociaux permettent aux auteurs de diffuser leur travail et de développer un public, ainsi que d\'interagir plus directement, s\'ils le souhaitent, avec leurs lecteurs.',
    'about.text.2': 'Les lecteurs peuvent utiliser le site principalement pour lire de nouvelles œuvres et suivre des auteurs, mais aussi pour participer à l\'édition d\'histoires prépubliées si l\'auteur leur en donne l\'autorisation. Être un lecteur sur l\'Univers Littéraire est une toute nouvelle expérience de lecture, avoir accès à toutes les informations de fond sur la même page que l\'histoire principale vous donne un aperçu de l\'esprit de l\'auteur comme jamais auparavant.',
    'about.text.3': 'L\'avenir de l\'Univers Littéraire passe par la création d\'une place de marché permettant aux auteurs de vendre leurs œuvres et par l\'ajout de fonctionnalités communautaires visant à améliorer la communication entre auteurs et lecteurs par le biais de blogs et de forums. Des outils pour les écrivains seront ajoutés au fil du temps, avec plus d\'une douzaine d\'outils actuellement en cours de développement ou sur le planning. Notre objectif ultime est d\'améliorer l\'expérience des écrivains et des lecteurs en proposant une utilisation plus innovante du média Internet.',
    'about.text.4': 'Nous espérons que vous vous joindrez à nous pour explorer ce que le média Internet peut faire pour l\'écriture créative !',
    'about.team': 'L\'équipe',
    'about.history': 'Histoire',
    'about.company': 'L\'entreprise',
    'about.companyCountry.czechia': 'Tchéquie',
    'about.companyCountry.japan': 'Japon',
    'about.companyCity.prague': 'Prague',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Directeur en chef',
    'about.CTO': 'Directeur Technique',
    'about.jan': 'Jan est le fondateur, le visionnaire et le cerveau technologique de l\'Univers Littéraire. En tant qu\'auteur de grands univers littéraires, Jan a toujours trouvé difficile d\'écrire des histoires d\'un point de vue technique et de lisibilité, sans compromettre l\'expérience de lecture. C\'est pourquoi Jan a décidé de poursuivre ses études en développement web afin de créer une application qui faciliterait l\'écriture d\'histoires dans de grands univers.',
    'about.history.text': 'En 2010, Jan a commencé à l\'Institut de technologie de Rochester pour en apprendre davantage sur le développement web afin de pouvoir créer un site d\'écriture créative. Cela s\'est concrétisé en 2013 lorsque la première preuve de concept a été présentée à Imagine RIT. Jan a poursuivi ses études et, en 2016, une nouvelle version de l\'application a été créée dans le cadre du projet Capstone du Master. Le projet s\'est poursuivi à l\'automne 2016 et s\'est développé pour devenir ce que vous voyez aujourd\'hui.',
    'copyrights.desc': 'Le texte intégral de l\'accord sur les droits d\'auteur de l\'Univers Littéraire.',
    'privacy.desc': 'Le texte légal complet de la politique de confidentialité de l\'Univers Littéraire.',
    'guidelines.desc': 'Directives Communautaires de l\'Univers Littéraire.',
    'tos.desc': 'Le texte légal complet des Conditions d\'Utilisation de l\'Univers Littéraire.',
    'homepage.intro': 'Explorez et créez littéralement des univers et de belles histoires.',
    'homepage.explanation': 'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'gdpr.title': 'GDPR Compliance',
    'gdpr.desc': 'Literary Universe is compliant with the EU GDPR directives.',
    'gdpr.compliant': 'Literary Universe is GDPR Compliant',
    'gdpr.compliant.text': 'Literary Universe has implemented various updates and changes to its codebase in preparation for GDPR enforcement on May 25th 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'Changes in this version',
    'dmca.title': 'Digital Millennium Copyright Act (DMCA) Policy',
    'dmca.subtitle': 'Copyright Dispute Policy',
    'dmca.step1.title': 'Procedure for Reporting Copyright Infringements.',
    'dmca.step2.title': 'Once Proper Bona Fide Infringement Notification is Received by the Designated Agent.',
    'dmca.step3.title': 'Procedure to Supply a Counter-Notice to the Designated Agent.',
    'dmca.desc': 'We take copyright violations seriously.',
    'gdpr.access.title': 'Right of Access and Right of Data Portability',
    'gdpr.access.desc': 'In user settings you can export all your data. This data will be in standard JSON format.',
    'gdpr.forget.title': 'Right to be forgotten',
    'gdpr.forget.desc': 'Any account can be deleted via user settings. Some data might be preserved, especially if they have been subject to sale and/or disputes.',
    'gdpr.rectification.title': 'Right to Rectification',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'Right to restriction of processing',
    'gdpr.processing.desc': 'Literary Universe fully respects the browser settings, such as "Do not track" requests for reporting to our Matomo statistics server.',
    'gdpr.object.title': 'Right to Object',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'Reporting is split into two scenarios. 1. Internal property (infringement on site of property existing on site). 2. External property (infringement on site of property not existing on site).',
    'dmca.step1.desc2': 'Reporting internal property can be done via report button on the property. Reporting external property infringement can be done via feedback screen. In both cases you will be asked to provide personal details and additional details that will allow us to check your ownership.',
    'dmca.step1.desc3': 'Please note that making a false claims will result in your inability to file claims in the future.',
    'dmca.step2.desc1': 'Upon receiving your report we will verify your credentials and ownership claim. If everything is fine we will proceed to check claim. If we determine claim as true we will make the infringing property inaccessible until counter-notice determination or 14 days have passed after which it will be deleted.',
    'dmca.step3.desc1': 'Once a complaint has been received the owner of designated property will have 14 days to file a counter notice. Designated Agent will then proceed to investigate the dispute. Any decision by the Designated Agent at this stage will be final.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Attributions',
    'about.attributionsIntro': 'Literary Universe builds on top of many Open Source projects and free resources. Bellow you will find their listing.',
    'about.attributionsMatomo': 'Our analytics use self-hosted Matomo with IP2Location LITE data available from https://lite.ip2location.com.',
    'about.attributionIcons': 'The following icons are used through the site via styled-icons:',
    'team.name.pjakubec': 'Pavel Jakubec',
    'team.name.asebesta': 'Adam Šebesta',
    'about.developer': 'Développeur',
    'about.seniorDeveloper': 'Développeur senior',
    'about.juniorDeveloper': 'Développeur Junior',
    'about.leadDesigner': 'Lead designer',
    'about.leadUX': 'Lead UX designer',
    'about.intern': 'Intern',
    'about.advisor': 'Conseiller',
    'about.headOfResearch': 'Chef de la Recherche',
    'about.CFO': 'Chief Financial Officer',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry is a designer with more than 15 years experience. He\'s been working in agency since 2010, his client such as PERTAMINA, VOA, and Ministry tourism of Indonesia. Experienced in Branding, layout and also UI/UX he feels challenged to design Literary Universe.',
    'about.pavel': 'Web3, Metaverse, AI, all that and anything new is what Pavel looks into and how it can be added to improve Literary Universe. A true multidisciplinary researcher Pavel holds insight into many areas and works on adding new interesting features to Literary Universe',
    'about.seba': 'Once a gamer, Adam is now studying to become a fully fledged developer.'
};