export default {
  'personalNotes.personalNotes': 'Notes personnelles',
  'personalNotes.chooseType': 'Choisissez le type de note personnelle',
  'personalNotes.storyNotes': 'Notes d\'histoire',
  'personalNotes.chapterNotes': 'Notes de chapitre',
  'personalNotes.universeNotes': 'Notes d\'univers',
  'personalNotes.encyclopediaNotes': 'Notes d\'encyclopédie',
  'personalNotes.storyPersonalNotesHeading': 'Notes personnelles sur les histoires',
  'personalNotes.encyclopediaPersonalNotesHeading': 'Notes personnelles sur l\'encyclopédie',
  'personalNotes.searchPersonalNotesHeading': 'Rechercher les notes personnelles',
  'personalNotes.goToStory': 'Aller à l\'histoire',
  'personalNotes.goToChapter': 'Aller au chapitre',
  'personalNotes.goToEncyclopedia': 'Aller à l\'encyclopédie de l\'univers',
  'personalNotes.goToEncEntry': 'Aller à l\'entrée',
  'personalNotes.closeDropdown': 'Fermer la liste déroulante',
  'personalNotes.chapterName': 'Chapitre {sequence} - {title}',
  'personalNotes.objectPersonalNotes': 'Note personnelle {object}',
  'personalNotes.searchResults': 'Résultats de recherche',
  'personalNotes.type.story': 'Histoire',
  'personalNotes.type.universe': 'Univers',
  'personalNotes.type.chapter': 'Chapitre',
  'personalNotes.type.encEntry': 'Entrée d\'encyclopédie',
  'personalNotes.type.revTextBlock': 'Bloc de texte révisé',
  'personalNotes.chapter': 'Chapitre',
  'personalNotes.recentSearches': 'Recherches récentes:'
};