export default {
    'plans.desc': 'Description des plans et des caractéristiques de l\'univers Littéraire.',
    'plans.title': 'Tirez le meilleur parti de l\'Univers Littéraire !',
    'plans.text': 'L\'Univers littéraire offre des fonctionnalités de base gratuites. Si vous êtes un lecteur assidu ou un créateur, vous trouverez peut-être que notre abonnement avancé vous convient le mieux.',
    'plans.faq.basicsPriced': 'Pourquoi l\'adhésion gratuite a-t-elle si peu de choses ?',
    'plans.faq.justification': 'Chez l\'Univers Littéraire, nous respectons votre vie privée et votre propriété intellectuelle. En tant que tel, nous n\'utilisons pas vos données pour vendre des publicités ou les fournir à d\'autres entreprises. Cela signifie que nous devons construire beaucoup de choses par nous-mêmes. Cela prend beaucoup de temps et coûte cher à gérer. Nous avons donc établi l\'adhésion gratuite comme un petit aperçu de l\'Univers Littéraire (qui vous permet toujours de faire les choses les plus importantes) avec plusieurs niveaux d\'adhésion et des modules complémentaires pour répondre aux besoins de chacun tout en nous permettant de maintenir le service et de poursuivre le développement. Si vous aimez ce que nous construisons, veuillez envisager de vous inscrire à l\'une des options payantes. Nous vous remercions !',
    'plans.limits': 'Limites',
    'plans.features': 'Caractéristiques',
    'plans.account.user': 'Visiteur',
    'plans.account.user.desc': 'Compte d\'essai initial pour essayer les choses.',
    'plans.account.explorer': 'Explorateur',
    'plans.account.explorer.desc': 'Pour les amateurs et les amis.',
    'plans.account.adventurer': 'Aventurier',
    'plans.account.adventurer.desc': 'Pour les créateurs et nos supporters.',
    'plans.account.storyteller': 'Conteur d\'histoires',
    'plans.account.storyteller.desc': 'Pour les plus créatifs et les plus dévoués.',
    'plans.unlimited': 'Illimité',
    'plans.price': 'Prix',
    'plans.price.free': 'GRATUIT',
    'plans.price.monthly': 'a month*',
    'plans.price.annually': 'annually*',
    'plans.price.perMonth': '{price} / month*',
    'plans.price.perYear': '{price} / year*',
    'plans.development': 'En développement',
    'plans.limits.encEntries': 'Entrées de l\'encyclopédie',
    'plans.limits.maxCollaborators': 'Collaborateurs par projet',
    'plans.limits.pmChats': '# maximum de destinataires pour les messages privés',
    'plans.feature.creative': 'Create amazing universes and stories',
    'plans.feature.encCustomFields': 'Champs d\'encyclopédie personnalisables sur une entrée',
    'plans.feature.encAdvCategories': 'Plus de catégories d\'encyclopédie',
    'plans.feature.scratchpad': 'Bloc-notes',
    'plans.feature.library': 'Bibliothèque',
    'plans.feature.blog': 'Blogs personnels et univers',
    'plans.feature.customBlogTheme': 'Thèmes de blog personnalisables',
    'plans.feature.advanceStats': 'Statistiques avancées',
    'plans.feature.challenges': 'Défis d\'écriture',
    'plans.feature.newFeaturesVote': 'Votez sur les nouvelles fonctionnalités',
    'plans.feature.newFeaturesSuggest': 'Proposer de nouvelles fonctionnalités',
    'plans.feature.accessToBeta': 'Accéder aux fonctionnalités Bêta',
    'plans.feature.userGroups': 'Groupes d\'utilisateurs',
    'plans.feature.privateUserGroups': 'Créer des groupes d\'utilisateurs privés et cachés',
    'plans.feature.internalUniverseForums': 'Forum interne pour les univers',
    'plans.feature.fictionalTime': 'Temps fictif',
    'plans.feature.forums': 'Forums sur les blogs et les pages d\'univers',
    'plans.feature.timelines': 'Chronologie de l\'univers',
    'plans.feature.webMonetization': 'Monétisation du Web',
    'plans.feature.storyMonetization': 'Monétisation des histoires',
    'plans.feature.fanClub': 'Fan Club',
    'plans.feature.translations': 'Capacités de traduction',
    'plans.feature.fanFiction': 'Écrire et gérer des fan fictions',
    'plans.feature.universeFanArt': 'Gestionnaire de fan art',
    'plans.feature.overviewNotes': 'Notes de présentation de l\'histoire',
    'plans.feature.personalNotesStoriesUniverses': 'Notes personnelles sur les histoires et les univers',
    'plans.feature.storyReviews': 'Critiques d\'histoires',
    'plans.feature.readingLists': 'Listes de lecture',
    'plans.feature.scenesManager': 'Gestionnaire de Scénarios',
    'plans.feature.glossaries': 'Glossaires de traduction',
    'plans.feature.chatSupport': 'Chat support',
    'plans.currency.select': 'Sélectionner la devise',
    'plans.subscription.ownAlready': 'Vous avez actuellement ce plan',
    'plans.subscription.title': 'Abonnement',
    'plans.see': 'Voir les plans d\'abonnement disponibles',
    'plans.current.none': 'Vous ne soutenez pas actuellement l\'Univers Littéraire.',
    'plans.current.buying': 'La vérification de votre achat peut prendre quelques instants. Nous vous remercions de votre patience.',
    'plans.current.heading': 'Plan actuel de souscription',
    'payment.methods.title': 'Paiements et monétisation',
    'payment.methods.tabs': 'Options de paiement',
    'payment.option.title': 'Option de paiement',
    'payment.option.notFount': 'Vous n\'avez pas enregistré d\'option de paiement.',
    'payment.option.create': 'Ajouter une nouvelle option de paiement',
    'payment.option.description': 'Voici une liste de vos méthodes de paiement enregistrées. Vous pouvez enregistrer de nouveaux modes de paiement ici pour accélérer le passage à la caisse. L\'Univers Littéraire ne stocke pas et ne traite pas vos informations de paiement comme le numéro de votre carte de crédit.',
    'payment.history.title': 'Historique des payements',
    'payment.history.tab': 'Historique',
    'payment.history.none': 'Nous n\'avons pas d\'historique des paiements passés.',
    'plans.options.aria': 'Options de paiement',
    'plans.options.creditCard': 'Carte de crédit',
    'plans.options.creditCardNew': 'New Credit Card',
    'plans.options.existingCards': 'Saved Credit Cards',
    'plans.purchase.action': 'S\'abonner',
    'plans.purchase.title': 'Acheter un abonnement à l\'Univers Littéraire',
    'payment.creditCard.details': 'Détails de Carte de Crédit',
    'payments.zipcode.label': 'Code postal',
    'payment.card.name': 'Nom sur la carte',
    'plans.subscribed.thankYou': 'Merci de soutenir l\'Univers Littéraire',
    'plans.subscribed.periodEnd': 'Votre abonnement est valable jusqu\'à : {end, date, medium}',
    'plans.subscribed.renewal': `A la fin, votre abonnement sera {method, select,
    charge_automatically {renouvelé automatiquement}
    send_invoice {renouvelé après le paiement d'une facture}
    other {}
  }.`,
    'plans.subscribed.paymentMethod': 'Votre mode de paiement par défaut sera utilisé pour payer le prochain cycle.',
    'plans.subscribed.status': `État de l'abonnement: {status, select,
    active {Actif}
    incomplete {Quelque chose manque}
    incomplete_expired {Quelque chose manque}
    trialing {Essai}
    past_due {Nous manquons de paiement}
    canceled {Annulé}
    unpaid {Impayé}
    expired {Expiré}
    other {}
  }`,
    'payments.changeMethod': 'Modifier le mode de paiement',
    'plans.subscribed.willNotRenew': ', ne sera pas renouvelé à la fin du cycle.',
    'plans.cancel.button': 'Annuler l\'abonnement',
    'plans.cancel.question': 'Êtes-vous sûr de vouloir annuler votre abonnement ? Votre abonnement restera actif jusqu\'à la fin du cycle de facturation.',
    'plans.cancel.confirmationButton': 'Oui, je veux annuler mon abonnement',
    'plans.cancel.failed': 'Nous sommes désolés, mais nous n\'avons pas pu annuler votre plan pour le moment. Veuillez réessayer plus tard.',
    'plans.cancel.restoreBtn': 'Restaurer l\'abonnement',
    'plans.cancel.restoreFailed': 'Nous sommes désolés, mais nous n\'avons pas été en mesure de restaurer l\'abonnement pour le moment. Veuillez réessayer plus tard.',
    'plans.change.button': 'Modifier l\'abonnement',
    'plans.change.explanation': 'Sélectionnez le plan que vous souhaitez mettre à niveau ou rétrograder. La différence de prix vous sera immédiatement facturée.',
    'plans.change.failed': 'Nous sommes désolés, mais nous n\'avons pas pu modifier votre plan pour le moment. Veuillez réessayer plus tard.',
    'plans.change.upgrade': 'Mise à niveau',
    'payments.disclaimer': 'Les informations et le traitement des paiements sont effectués via Stripe. Nous ne conservons aucune information sur les cartes de crédit ou les comptes bancaires sur nos serveurs.',
    'buy.payment.optionsSelect': 'Sélectionnez l\'option de paiement',
    'payments.card.number': 'Numéro de carte',
    'payments.card.expire': 'Valable jusqu\'au',
    'payments.card.cvv': 'CVV',
    'payments.card.info': 'Carte {cardType} , se terminant par {ending}',
    'payments.none': 'Aucune option de paiement enregistrée n\'a été trouvée.',
    'payments.none.cards': 'No cards were found.',
    'payments.added': 'Une nouvelle option de paiement a été ajoutée avec succès.',
    'payments.delete.confirm': 'Êtes-vous sûr de vouloir supprimer {cardType}, se terminant par {ending} ?',
    'payment.invoice.status': 'Statut de la facture',
    'payment.invoice.statusMessage': `{status, select,
    draft {Brouillon}
    open {Ouvert}
    paid {Payé}
    uncollectible {Incollectible}
    void {Vide}
    other {}
  }`,
    'payment.invoice.id': 'Identifiant de la facture',
    'payment.invoice.pdf': 'Facture pdf',
    'payment.invoice.total': 'Total',
    'payment.invoice.what': 'Description de la facture',
    'payment.stripe.powered': 'Propulsé par ',
    'payment.listMethods.card': 'Cartes',
    'payment.expiresAt': 'Expire le {month}/{year}',
    'payment.card.details': `{type, select,
    credit {Carte de crédit}
    debit {Carte de débit}
    other {Carte}
  } se terminant par {last4}`,
    'payment.options.default': 'Défaut',
    'payment.method.add': 'Ajouter un nouveau mode de paiement',
    'payment.methods.adding': 'Votre nouveau mode de paiement a été ajouté à votre compte.',
    'payment.methods.delete': 'Supprimer le mode de paiement',
    'payment.upgradePlan.option': '{plan} - {price}',
    'payment.methods.webMonetization': 'Web Monetization',
    'settings.webMonetization.placeholder': 'Votre pointeur de paiement',
    'payment.webMonetization.explained': 'Web Monetization est une proposition de norme pour les paiements sur le Web. Ici, vous pouvez ajouter votre pointeur de paiement qui sera ensuite ajouté à votre page de profil, votre blog, vos univers et vos histoires pour être utilisé par Web Monetization.',
    'payment.webMonetization.learnMore': 'En savoir plus sur Web Mmonetization',
    'plans.subscription.settingsAria': 'Subscription settings options',
    'plans.buttonStatus.submitting': 'Submitting your request...',
    'plans.button.manageOnStripe': 'Manage Billing on Stripe',
    'plans.call.signUpBottom': 'Sign-up for a free Literary Universe account and start creating!',
    'plans.button.seeComparison': 'Find out more about plans and pricing on our comparison page!',
    'plans.button.chooseThisSubscription': 'Select this plan',
    'plans.button.chooseFree': 'Start for free',
    'plans.features.allInPreviousTiers': 'Everything in previous tier',
    'plan.button.chooseNow': 'Choose your Literary Universe plan now',
    'plans.subscription.manage': 'Manage subscription',
    'plans.taxMayApply': '* VAT and other local taxes may apply',
    'plans.faq.crypto': 'Will you offer crypto payments?',
    'plans.faq.cryptoAnswer': 'Yes, we are working on it. We are big fans of Web3 we are looking for ways to integrate Web3 into the platform in the near future. We currently allow for login with Web3 and we are looking to expand on this offering especially when it comes to providing compensation to creators and giving creators the ability to choose all the possible payment options that they want to accept.',
    'plans.subscribed.updating': 'It might take a bit to update your your subscription information. Thank you for your patience!',
    'payments.methods.webMonetization': 'Web Monetization',
    'stripeConnect.settings.title': 'Payouts settings',
    'stripeConnect.settings.intro': 'If you want to receive funds or sell through Literary Universe you need to create Stripe account via the button bellow.',
    'stripeConnect.settings.connectAccount': 'Setup Stripe Account',
    'stripeConnect.settings.ongoing': 'We are waiting to hear back from Stripe in regards to your account. This might take a little bit. If this is taking too long click on the button bellow which will take you back to Stripe.',
    'stripeConnect.settings.finished': 'You are all set to receive money via Stripe Connect.',
    'stripeConnect.settings.balance': 'Balance',
    'stripeConnect.settings.balanceAvailable': 'Available balance',
    'stripeConnect.settings.balancePending': 'Pending balance',
    'stripeConnect.settings.recentTransfers': 'Recent transfers',
    'stripeConnect.transfers.amount': 'Amount',
    'stripeConnect.transfers.reason': 'Reason',
    'payment.settings.donations': 'Donations settings',
    'plans.fanClub.heading': 'Fan Clubs',
    'payment.donations.enable': 'Enable donations',
    'payment.donations.suggestedAmount': 'Suggested amount',
    'payment.donations.amount': 'Amount',
    'payment.donations.preferredCurrency': 'Preferred currency',
    'payment.donations.currency': 'Currency',
    'payment.donations.stripeDescription': 'Donation to {username}',
    'payment.donations.support': 'Support {username}',
    'payment.donations.donate': 'Donate',
    'payment.donations.donationModal': 'Donation confirmation',
    'payment.donations.payNowUSD': 'Donate {donation, number, ::compact-short currency/USD} to {username}',
    'payment.donations.payNowJPY': 'Donate {donation, number, ::compact-short currency/JPY} to {username}',
    'payment.donations.payNowEUR': 'Donate {donation, number, ::compact-short currency/EUR} to {username}',
    'payment.donations.payNowCZK': 'Donate {donation, number, ::compact-short currency/CZK} to {username}',
    'payment.donations.payNowGBP': 'Donate {donation, number, ::compact-short currency/GBP} to {username}',
    'payment.donations.thankYouTitle': 'Thank you for your donation to {username}',
    'payment.donations.thankYouContinue': 'Thank you for supporting {username}, we hope that you will continue enjoying their work and consider supporting them again in the future.',
    'payment.success': 'Payment succeeded!',
    'payment.processing': 'Your payment is processing.',
    'payment.failed': 'Your payment was not successful, please try again.',
    'payment.generalError': 'Something went wrong.',
    'payment.unexpectedError': 'Something went wrong.',
    'payments.transferType.donation': 'Donation',
    'payment.donation.backToProfile': 'Back to {username}\'s profile',
    'payment.author.requirementStripeConnect': 'Before we can process any financial transactions you need to create and connect your Stripe Connect account.',
    'payment.author.requirementPublishWork': 'Before you continue, please publish at least one work (story or universe).',
    'payment.author.createWork': 'Create a new work',
    'payment.author.directivesTitle': 'Recommendations',
    'payment.author.directivesExplained': 'We have some additional recommendations that you should fulfill before enabling payment services to increase your chance of success.',
    'payment.author.directivesStoryPublished': 'Publish at least one story for free to showcase your craft.',
    'payment.author.directivesFreeStoryFinished': 'Finish at least one free story to show your readers that you won\'t abandon them in the middle of the journey.',
    'payment.universe.directivesUniversePublished': 'Publish your universe',
    'payment.universe.directivesEncFull': 'Fill up your encyclopedia, have at least 30 entries! Better if you are attacking the 100 margin.',
    'payment.universe.haveFans': 'It is easier to get people to sponsor you if they are already interested in what you are doing. 100 fans adding your universe to their library is the starting line.',
    'payment.settings.yourFanClub': 'Your fan club',
    'payment.settings.newWork': 'Create a new work'
};