export default {
    'reader.storyEnd.heading': 'La FIN',
    'reader.storyEnd.description': 'Vous avez atteint la fin de l\'histoire.',
    'reader.externalSale.heading': 'Pas encore arrivé',
    'reader.externalSale.description': 'Cette histoire n\'est pas disponible sur L\'Univers Littéraire, mais vous pouvez l\'obtenir dans d\'autres endroits.',
    'reader.storyTBC.heading': 'À suivre...',
    'reader.storyTBC.description': 'C\'est tout ce que nous avons pour l\'histoire jusqu\'à présent, mais l\'aventure continuera dans le futur, revenez bientôt !',
    'chapter.translation.notYetDescription': 'Revenez voir bientôt !',
    'reader.externalShopping.heading': 'Achetez {storyName} dans les magasins :',
    'chapter.next': 'Chapitre suivant',
    'chapter.previous': 'Chapitre précédent',
    'chapter.comment': 'Commentaires sur ce chapitre',
    'reader.language': 'Langue :',
    'reader.fullscreen.enter': 'Entrer en mode plein écran',
    'reader.fullscreen.exit': 'Quitter le mode plein écran',
    'reader.details.universe': 'Détails de l\'univers',
    'reader.details.story': 'Détails de l\'histoire',
    'reader.darkmode': 'Basculer en mode sombre',
    'reader.flowtext': 'Basculer la taille du texte',
    'reader.menu.optionsAria': 'Options du menu lecteur',
    'reader.accessibility': 'Basculer en mode accessibilité',
    'chapter.translation.notYet': 'Ce chapitre n\'a pas encore été traduit.',
    'externalShopping.buyLink.amazon': 'Acheter sur Amazon',
    'externalShopping.buyLink.other': 'Acheter sur {storeName}',
    'externalShopping.buyLink.bookshop': 'Acheter sur Bookshop.org',
    'reader.accessibility.aria': 'Options d\'accessibilité',
    'reader.accessibility.toggleDyslexic': 'Basculer la police dyslexique',
    'reader.accessibility.toggleParagraphStripes': 'Basculer la modification de l\'arrière-plan des paragraphes',
    'reader.accessibility.toggleParagraphHighlight': 'Basculer les paragraphes sélectionnés en surbrillance',
    'reader.accessibility.toggleRules': 'Basculer la règle d\'assistance',
    'reader.nextRelease.scheduled': 'Le prochain chapitre sera publié le {nextReleaseAt, date} à {nextReleaseAt, time}!',
    'reader.storyContinues': 'L\'histoire se poursuit...',
    'reader.storyOnHiatus': 'L\'auteur est actuellement en pause avec cette histoire et celle-ci est en pause pour le moment. Revenez dans un mois ou deux.',
    'reader.storyCancelled': 'Malheureusement, c\'est terminé. L\'histoire a été annulée, il est donc peu probable qu\'il y ait quelque chose de nouveau.',
    'reader.storyCancelled.heading': 'Annulé',
    'reader.nextChapterEstimation.verySoon': 'Based on the publication dates of the last {chaptersCount} chapters, the next chapter is expected to be released very soon.',
    'reader.nextChapterEstimation.days': 'Based on the publication dates of the last {chaptersCount} chapters, the next chapter should be available in approximately {daysLeft} days.',
    'reader.nextChapterEstimation.notEnoughChapters': 'Nous fournirons également une estimation de la date de publication du prochain chapitre une fois que cette histoire aura plus d\'un chapitre.'
};