export default {
    'sharing.title': 'Partager',
    'sharing.button': 'Bouton de partage',
    'sharing.share': 'Partager avec...',
    'sharing.feedback': 'Manque-t-il un endroit que vous aimeriez partager avec nous ? Faites-le nous savoir !',
    'sharing.copy': 'Copier',
    'sharing.email': 'Email',
    'sharing.sms': 'SMS',
    'sharing.messenger': 'Facebook Messenger',
    'sharing.whatsapp': 'WhatsApp',
    'sharing.twitter': 'X/Twitter',
    'sharing.linkedin': 'LinkedIn',
    'sharing.telegram': 'Telegram',
    'sharing.facebook': 'Facebook',
    'sharing.line': 'LINE',
    'sharing.mastodonSocial': 'Mastodon Social',
    'sharing.mastodonJapan': 'Mastodon Japon',
    'sharing.gab': 'Gab',
    'sharing.pinterest': 'Pinterest',
    'sharing.gettr': 'Gettr',
    'sharing.minds': 'Minds.com',
    'sharing.instagram': 'Instagram'
};