/**
 * @authors Jan Dvorak
 */
/* eslint-disable max-len */
export default {
    siteName: 'Literary Universe',
    twitterHandle: '@lituniapp',
    'site.description': 'Literary Universe è una piattaforma creativa per pubblicazioni di interi universi di storie.',
    'site.keywords': 'scrittura creativa, scifi, sci-fi, fantasia, scrittura, pubblicazione, storia, storie, universo, web novel, webnovel',
    'site.logoAlt': 'Literary Universe logo',
    mobileMenu: 'Menù telefono',
    'common.signin': 'Accedi',
    'common.signup': 'Registrati',
    'common.signout': 'Log out',
    'common.dashboard': 'Bacheca',
    'common.discovery': 'Scopri',
    'common.library': 'Raccolta',
    'common.library.own': 'La tua raccolta',
    'common.workshop': 'Laboratorio',
    'common.pm': 'Messaggi',
    'common.settings': 'Impostazioni',
    'common.options': 'Opzioni',
    'common.profile': 'Profilo',
    'common.blog': 'Blog',
    'common.blogs': 'Blog',
    'common.about': 'Chi siamo',
    'common.accessdenied': 'Accesso negato',
    'common.accessdenied.msg': 'Non hai il permesso di accedere. Se credi di avere l\'autorizzazione per accedere, contatta il titolare e chiedi di ricontrollare le impostazioni.',
    'common.loading': 'Caricamento...',
    'common.add': 'Aggiungi',
    'common.save': 'Salva',
    'common.email': 'E-mail',
    'common.soon': 'Prossimamente...',
    'common.search': 'Cerca',
    'common.search.do': 'Cerca',
    'common.searching': 'Ricerca...',
    'common.report': 'Segnala',
    'common.user': 'Utente',
    'common.users': 'Utenti',
    'common.showmore': 'Mostra di più',
    'common.futurefeature.title': 'Prossime funzionalità',
    'common.futurefeature.text': 'Siamo molto spiacenti, ma questa funzione non è disponibile in questo momento. Stiamo lavorando sodo per renderla disponibile il prima possibile.',
    'common.nothingfound': 'Nessun risultato',
    'common.explore': 'Esplora',
    'common.by': 'di ',
    // keep the space at the end as username follows TODO: needs fixing
    'common.scratchpad': 'Blocco appunti',
    'common.scratchpad.own': 'Il tuo blocco appunti',
    'common.news': 'Novità',
    'common.encyclopedia': 'Enciclopedia',
    'common.art': 'Arte',
    'common.story': 'Storia',
    'common.stories': 'Storie',
    'common.universe': 'Universo',
    'common.universes': 'Universi',
    'common.collaborator': 'Collaboratore',
    'common.collaborators': 'Collaboratori',
    'common.translator': 'Traduttore/trice',
    'common.translators': 'Traduttori',
    'common.betareader': 'Beta reader',
    'common.betareaders': 'Beta readers',
    'common.post': 'Post',
    'common.statistics': 'Statistiche',
    'common.lang.select': 'Seleziona lingua',
    'common.submit': 'Invia',
    'common.close': 'Chiudi',
    'common.comment': 'Commento',
    'common.comments': 'Commenti',
    404: 'Pagina non trovata',
    'search.users': 'Ricerca utenti',
    'search.user': 'Ricerca utente',
    'common.help': 'Aiuto',
    'common.or': 'o',
    'common.account.create': 'Crea un account',
    'signup.username': 'Nome utente',
    'signup.email': 'Indirizzo e-mail',
    'signup.password.label': 'Password',
    'signup.password.repeat': 'Ripeti password',
    'common.password': 'Password',
    'signin.password.forgot': 'Password dimenticata?',
    'dashboard.whatsnew': 'Novità',
    'dashboard.blog': 'Il tuo blog',
    'common.footer.tagline': 'Scrivere e leggere di universi complessi con facilità.',
    'common.footer.plans': 'Piani & Prezzi',
    'common.legal.tos': 'Termini di Servizio',
    'common.legal.community': 'Linee guida della community',
    'common.legal.privacy': 'Condizioni sulla Privacy',
    'common.legal.copyright': 'Accordo Copyright',
    'common.legal.newVersionAvailable': 'Una nuova versione ({newVersion}) di questo documento entrerà in vigore il {effectiveAt, date}.',
    'common.legal.disclaimer': '© {year} Tutti i diritti riservati, tutti i testi appartengono ai rispettivi autori.',
    'premium.only.title': 'Grado di iscrizione non sufficiente',
    'premium.only.msg': 'Ci scusiamo, il tuo grado di iscrizione non è abbastanza alto per accedere a questa funzionalità.',
    'premium.only.join': 'Offriamo diversi piani per permettere a tutti di avere il meglio da Literary Universe.',
    'premium.only.link': 'Guarda qui!',
    'universe.visit': 'Visita pagina universo',
    'common.fanmanager': 'Fan Manager',
    'common.fanarts': 'Fan Arts',
    'common.fanfiction': 'Fan Fiction',
    'common.fansettings': 'Fan Settings',
    'story.chapter': 'Capitolo',
    'story.chapters': 'Capitoli',
    'story.genre': 'Genere',
    'story.genres': 'Generi',
    'story.read': 'Letti',
    'story.lastUpdate': 'Ultimo aggiornamento in {date, date, medium} {date, time, short}.',
    'story.finishedAt': 'Terminato il {date, date, medium}.',
    'story.comments.for': 'Commenti per {story} {chapter}.',
    'story.cover.alt': 'Immagine di copertina per {story}.',
    'story.note.fanfiction': 'NOTA: Questa storia è una fan fiction sull\'universo {universe}.',
    copyrights: 'Diritti',
    'common.challenges': 'Sfide',
    // for beta only
    'beta.notice': 'Benvenuto/a su Literary Universe BETA. Questa è un\'anteprima pubblica, stiamo ancora lavorando sull\'applicazione. Potrebbero quindi esserci alcuni errori o funzionalità incomplete. Se trovi errori o qualcosa di non funzionante, ti chiediamo di comunicarcelo. Ti ringraziamo per la pazienza mentre sistemiamo l\'applicazione.',
    'beta.thanks': 'Grazie per il tuo supporto!',
    'scratchpad.about': 'I tuoi appunti e idee accessibili ovunque sul sito.',
    'common.feedback': 'Feedback',
    'common.createdOn': 'Creato il {date, date, long}',
    'common.createdOn.title': 'Creato su',
    // account types
    admin: 'Amministratore',
    goodbye: 'Grazie! Alla prossima!',
    'common.saved': 'Salvato!',
    'common.saving': 'Salvataggio...',
    'common.friends': 'Amici',
    'lang.orig': 'Lingua d\'origine',
    'lang.orig.plus': 'Lingua d\'origine - {language}',
    buy: 'Compra',
    confirm: 'Conferma',
    cancel: 'Annulla',
    processing: 'Elaborazione...',
    'common.noData': 'Nessun dato',
    'error.title': 'Si è verificato un errore. Ci scusiamo per il disagio.',
    'common.offlineStatus': 'Al momento sei offline.',
    male: 'Maschio',
    female: 'Femmina',
    'common.legal.effectiveAt': 'Operativo da {date, date, medium}',
    select: 'Seleziona',
    'common.statusFailed': 'Impossibile connettersi al server.',
    'common.statusConnecting': 'Tentativo di connettersi al server... ({count, number})',
    'slug.checking': 'Verifica in corso...',
    'slug.failed': 'Indirizzo già esistente.',
    'slug.success': 'Indirizzo disponibile!',
    'notVerified.msg': `Il tuo account {option, select,
    email {e-mail}
    wallet {portafoglio}
    other {e-mail}
    } non è verificato.`,
    'notVerified.verify': `Verifica il tuo {option, select,
    email {e-mail}
    wallet {portafoglio}
    other {e-mail}
    }.`,
    unknown: 'sconosciuto',
    'common.legal.guidelines': 'Linee guida della community',
    'errorLoading.title': 'Errore durante il caricamento della pagina',
    'errorLoading.explained': 'Si è verificato un errore durante il caricamento della pagina. Ci scusiamo per il disagio. Prova ad accedere nuovamente alla pagina. Se il problema persiste, sei pregato/a di comunicarcelo.',
    'errorLoading.retry': 'Riprova!',
    'errorLoading.takingLong': 'Ci sta mettendo molto...',
    'common.title': 'Titolo',
    'common.timelines': 'Linee temporali',
    'common.legal.gdpr': 'GDPR',
    'common.legal.gdpr.long': 'General Data Protection Regulation',
    'editor.placeholder.link': 'Inserisci URL...',
    'editor.placeholder.connection': 'Cerca voce enciclopedia...',
    'editor.saved.beta': 'Nuova revisione per i lettori Beta!',
    'editor.saved.public': 'Nuova versione pubblicata!',
    goodbyeForever: 'Ci dispiace vederti andare via! Abbiamo sbagliato qualcosa? Ti chiediamo di farcelo sapere. In ogni caso ti auguriamo il meglio per le tue future imprese e speriamo di incontrati di nuovo! Lunga vita a te!',
    'goodbyeForever.feedback': 'Facci sapere cosa possiamo migliorare',
    'common.edit': 'Modifica',
    'common.publish': 'Pubblica',
    'common.publishAt': 'Data e ora di pubblicazione',
    'a11y.user.menu': 'Menù utente',
    'a11y.navigation': 'Navigazione',
    'dashboard.profile': 'Profilo',
    'profile.website': 'Il mio sito',
    'story.notes.concept': 'Bozza',
    'story.notes.settings': 'Impostazioni storia',
    'story.notes.theme': 'Tema',
    'story.notes.impact': 'Impatto desiderato',
    'story.notes.outcome': 'Esito',
    'story.notes.audience': 'Pubblico di destinazione',
    'story.notes.pitch': 'Tono',
    'story.notes.notes': 'Note',
    'story.authorsNotes': 'Note di autore',
    'common.members': 'Membri',
    'common.language': 'Lingua',
    next: 'Avanti',
    'common.legal.tos.short': 'Termini',
    'common.legal.privacy.short': 'Privacy',
    'premium.increaseLimit': 'Considera l\'upgrade per avere un limite maggiore.',
    'common.sharing': 'Condivisione',
    'story.isbn': 'ISBN',
    'common.name': 'Nome',
    'common.remove': 'Elimina',
    'common.time.milliseconds': 'Millisecondi',
    'common.time.seconds': 'Secondi',
    'common.time.minutes': 'Minuti',
    'common.time.hours': 'Ore',
    'common.time.days': 'Giorni',
    'common.time.weeks': 'Settimane',
    'common.time.months': 'Mesi',
    'common.time.years': 'Anni',
    'common.monetization': 'Monetizzazione',
    'common.tab.monetizationOptions': 'Opzioni di monetizzazione',
    'common.pagination': 'Impaginazione',
    'common.forum': 'Forum',
    'common.2faCode': 'Codice 2FA',
    'common.2faCodeIntro': 'Inserisci il tuo codice unico generato dalla tua applicazione di autenticazione.',
    'common.2faCodeAria': 'Modulo di inserimento del codice 2FA',
    'common.flashnews': 'Flashnews',
    'common.defaultLanguage': 'Lingua predefinita',
    'signin.web3.signMessage': 'Confermare che si desidera entrare in Literary Universe con il proprio portafoglio come metodo di autenticazione. Codice: {code}',
    'common.web3.confirmationCode': 'Codice di conferma: {code}',
    'common.roadmap': 'Tabella di marcia dello sviluppo',
    'common.luStatsIFrameOptOut': 'Literary Universe: opt-out per le statistiche',
    'common.image': 'Immagine',
    'common.home': 'Home',
    'common.administration': 'Amministrazione',
    'common.truncateAppend': '...',
    // What should be the symbol used to denote that the text continues when it was truncated
    'common.groups': 'Gruppi',
    'common.upload': 'Carica',
    'common.backToDashboard': 'Torna alla dashboard',
    'common.accept': 'Accetta',
    'common.reject': 'Rifiuta',
    'common.events': 'Eventi',
    'common.event': 'Evento'
}    /* eslint-enable max-len */;