export default {
    'feedback.home': 'Centro assistenza',
    'feedback.bugs': 'Segnalazioni',
    'feedback.bugs.desc': 'Hai riscontrato errori o qualcos\'altro di sbagliato o fuori luogo? Faccelo sapere qui!',
    'feedback.features': 'Idee & Proposte',
    'feedback.features.desc': 'Hai idee per nuove funzionalità o su come migliorare il sito? Faccelo sapere!',
    'feedback.help': 'Aiuto & Tutorial',
    'feedback.help.desc': 'Come fai a _____? Vai qui per trovare le risposte.',
    'feedback.desc': 'Benvenuti nel nostro centro di aiuto e soluzione!',
    'feedback.faq': 'Domande frequenti',
    'feedback.faq.desc': 'Domande frequenti',
    'feedback.open': 'Apri',
    'feedback.closed': 'Chiudi',
    'feedback.accepted': 'Accettato',
    'feedback.inprogress': 'In corso',
    'feedback.completed': 'Completato',
    'feedback.fixed': 'Corretto',
    'feedback.new.bugs': 'Segnala un nuovo problema',
    'feedback.new.features': 'Suggerisci nuova funzione',
    'feedback.lang.nosupport': 'La tua lingua non è supportata per il feedback, per favore scrivi in inglese. Grazie!',
    'feedback.new.thanks': 'Grazie per la comunicazione! Ce ne occuperemo a breve.',
    'feedback.comment.title': 'Commento',
    'feedback.comment.desc': 'Inviaci il tuo feedback',
    'feedback.comment.legend': 'Il tuo feedback - per qualsiasi cosa, facci sapere',
    'feedback.comment.success': 'Grazie per il tuo feedback!',
    'feedback.comment.label': 'Il tuo commento',
    'feedback.copyrightReport.title': 'Violazione di copyright',
    'feedback.copyrightReport.desc': 'Segnala violazione del copyright',
    'feedback.report.noUser': 'Per inviare una segnalazione, devi effettuare l\'accesso.',
    'feedback.voting.totalVoters': 'Gli utenti hanno votato: {voted, number}',
    'feedback.voting.upvote': 'Voto positivo',
    'feedback.voting.downvote': 'Voto negativo',
    'feedback.voting.score': 'Punteggio totale',
    'feedback.report.title': 'Contenuto del rapporto',
    'feedback.report.typeSelect': 'Di che si tratta?',
    'feedback.reportType.law': 'Violazione della legge',
    'feedback.reportType.vulgar': 'Volgarità/oscenità',
    'feedback.reportType.copyright': 'Violazione di copyright',
    'feedback.reportType.storyRating': 'Classificazione dell\'età non corretta',
    'feedback.reportType.scam': 'Truffa',
    'feedback.report.submit': 'Segnala',
    'feedback.report.submitting': 'Sto segnalando...',
    'feedback.report.violationDesc': 'Dettagli',
    'feedback.report.reportSaved': 'Grazie per la segnalazione! Cercheremo di indagare e di intervenire, se necessario.',
    'feedback.report.copyrightReportSaved': 'Grazie per la segnalazione! Indagheremo e ti faremo sapere.',
    'feedback.report.copyrightOwnershipDesc': 'Dichiarazione di proprietà',
    'feedback.report.copyrightNotice': 'Si prega di notare che per utilizzare questo modulo è necessario essere il legittimo proprietario del lavoro. Se non lo sei, ti preghiamo di informare il proprietario o utilizzare l\'altra categoria per farcelo sapere. Prendiamo molto sul serio le violazioni di copyright e lo stesso vale per l\'uso improprio e abusivo di questo modulo.',
    'feedback.report.copyrightInternalProperty': 'Ho pubblicato questo lavoro su Literary Universe',
    'feedback.reportType.spam': 'Spam o truffa',
    'feedback.reportType.other': 'Altro',
    'feedback.report.copyrightType.propertySelectLabel': `Quale {type, select,
    universe {universo}
    story {storia}
    other {storia}
    } è stato/a violato/a?`,
    'faq.section.about': 'Chi siamo',
    'faq.section.settings': 'Impostazioni',
    'faq.section.discovery': 'Scopri',
    'faq.section.reader': 'Lettore',
    'faq.section.library': 'Raccolta',
    'faq.section.workshop': 'Laboratorio',
    'faq.section.writer': 'Scrittore',
    'faq.section.encyclopedia': 'Enciclopedia',
    'faq.section.groups': 'Gruppi',
    'faq.section.blogs': 'Blog',
    'faq.section.guilds': 'Gilde',
    // About us questions
    'faq.question.about.whatIsLU': 'Cos\'è Literary Universe?',
    'faq.answer.about.whatIsLU': 'Letteratura Universo è una piattaforma per scrittori e lettori per creare, condividere e scoprire storie e mondi.',
    'faq.question.about.difference': 'Qual è la differenza tra Letteratura Universo e altre piattaforme di lettura online?',
    'faq.answer.about.difference': 'Letteratura Universo è una piattaforma all-in-one, il che significa che include strumenti per scrivere, leggere, creare mondi e costruire una comunità. La differenza principale è l\'inclusione di tutti questi strumenti insieme in una piattaforma e la loro interconnessione.',
    'faq.question.about.dataLocation': 'Dove vengono memorizzati i dati di LU?',
    'faq.answer.about.dataLocation': 'I dati dell\'Universo Letterario sono memorizzati su server negli Stati Uniti d\'America, nello specifico nella regione AWS us-east-1.',
    'faq.question.about.incorporation': 'Dove siete incorporati?',
    'faq.answer.about.incorporation': 'L\'Universo Letterario è incorporato nella Repubblica Ceca. Puoi trovare ulteriori dettagli sulla nostra pagina <a href="/about">su di noi</a>.',
    'faq.question.about.roadmap': 'Quali sono i prossimi passi per l\'Universo Letterario?',
    'faq.answer.about.roadmap': 'Questo è in costante evoluzione. Dai un\'occhiata alla nostra <a href="/roadmap">roadmap</a> per ulteriori dettagli.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Come posso cambiare l\'aspetto dell\'Universo Letterario?',
    'faq.answer.settings.changeTheme': 'Gli utenti registrati possono cambiare il loro tema nelle impostazioni dell\'account <a href="/user/settings/account"></a> nella sezione "temi del sito". Abbiamo a disposizione un tema chiaro e un tema scuro. Se non sei registrato, cerchiamo di determinare quale tema servirti in base alle impostazioni del tuo browser e del tuo sistema operativo.',
    'faq.question.settings.changeAvatar': 'Come posso cambiare il mio avatar?',
    'faq.answer.settings.changeAvatar': 'Puoi cambiare il tuo avatar nelle impostazioni del profilo <a href="/user/settings/profile"></a>.',
    'faq.question.settings.changeLanguage': 'Come posso cambiare la lingua?',
    'faq.answer.settings.changeLanguage': 'Puoi cambiare la lingua dell\'Universo Letterario nelle impostazioni dell\'account <a href="/user/settings/account"></a>.',
    'faq.question.settings.translationMistake': 'Ho trovato un errore nel testo sul sito web, dove posso segnalarlo?',
    'faq.answer.settings.translationMistake': 'Tutti i nostri file di lingua sono disponibili su GitHub. Puoi <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">segnalare un problema lì</a> o nella sezione Bug del feedback, oppure, se lo desideri, puoi correggerlo direttamente tu stesso tramite <a href="https://crowdin.com/project/literary-universe" target="_blank">la nostra pagina Crowdin</a>.',
    // Discovery questions
    'faq.question.discovery.explain': 'Cos\'è la sezione Scoperta?',
    'faq.answer.discovery.explain': 'La sezione Scoperta è dove puoi trovare nuove storie, universi, blog, gruppi e altri contenuti. È un luogo per esplorare e trovare nuove cose da leggere e godere.',
    // Writer
    'faq.question.writer.howToCreateStory': 'Come posso creare una nuova storia in Letteratura Universo?',
    'faq.answer.writer.howToCreateStory': 'You can create a new story by going to the <a href="/workshop">workshop</a> and clicking on one of the create buttons or go to the main <a href="/workshop/create">create page</a> where you can select a <a href="/workshop/create/story">new standalone story</a> or <a href="/workshop/create/fanfiction">fan fiction</a>. To create a new story in a universe, go first to that universe and then select "stories" on the dashboard and on the next page click the big red button on the right side of the page title. You will be asked to fill in the details of your story and then you can start writing.',
    'faq.question.writer.schedule': 'Come posso pianificare la pubblicazione di un capitolo in Letteratura Universo?',
    'faq.answer.writer.schedule': 'Puoi pianificare la pubblicazione di un capitolo quando clicchi sul pulsante pubblica nell\'editor del capitolo. Verrà mostrato un modale in cui avrai l\'opzione di pianificare una pubblicazione o pubblicare immediatamente. Se scegli di pianificare una pubblicazione, ti verrà chiesto di selezionare la data e l\'ora in cui desideri che il capitolo venga pubblicato. Consigliamo di pianificare i capitoli almeno 24 ore in anticipo per dare ai lettori il tempo di prepararsi al nuovo capitolo e di pubblicare nello stesso giorno e alla stessa ora della settimana.',
    // Reader
    'faq.question.reader.creativeTypes': 'Qual è la differenza tra Universo, Storie e Fan Fiction?',
    'faq.answer.reader.creativeTypes': 'L\'universo è un luogo in cui puoi trovare tutte le storie e altri contenuti relativi a un mondo letterario specifico. Le storie possono essere storie singole o parte di un universo. La Fan Fiction è una storia basata su un altro universo letterario creato da qualcun altro.',
    // Workshop
    'faq.question.workshop.explain': 'Cos\'è il Workshop?',
    'faq.answer.workshop.explain': 'Il Workshop è dove puoi creare nuove storie, fan fiction, universi e altri contenuti. È un luogo per scrivere, modificare e gestire i tuoi contenuti creativi.',
    'faq.question.workshop.creativeTypes': 'Qual è la differenza tra Universo, Storie e Fan Fiction?',
    'faq.answer.workshop.creativeTypes': 'L\'Universo è un luogo centrale per il tuo universo letterario in cui crei storie che abitano lo stesso mondo letterario, gestisci un\'enciclopedia con tutte le sfumature del tuo mondo e fai qualsiasi altra cosa ad essa collegata. La Fan Fiction è una storia basata su un\'altra storia o universo creato da qualcun altro. Le storie singole sono storie che non sono collegate a nessun universo, utilizzale ad esempio per la poesia o opere letterarie ambientate nel mondo reale senza molti personaggi o dettagli immersivi che richiederebbero un\'enciclopedia o altri vantaggi di avere un universo.',
    'faq.question.workshop.continueStory': 'Come posso continuare una storia precedentemente creata?',
    'faq.answer.workshop.continueStory': 'Puoi continuare una storia precedentemente creata andando al <a href="/workshop">workshop</a> e selezionando la storia che desideri continuare o, se è una storia in un universo, devi prima andare all\'universo e selezionare la storia dalla lista delle storie. Nel cruscotto della storia puoi quindi fare clic sul capitolo in cui desideri continuare a scrivere o creare un nuovo capitolo.',
    'faq.question.workshop.whatIsALicense': 'Cos\'è una Licenza di Storia?',
    'faq.answer.workshop.whatIsALicense': 'Una licenza di storia è un documento legale che definisce come la tua storia/universo può essere utilizzato da altri. È un modo per proteggere i tuoi diritti e definire come gli altri possono utilizzare il tuo lavoro.',
    'faq.question.workshop.licenses': 'Quali licenze sono disponibili?',
    'faq.answer.workshop.licenses': 'Offriamo una varietà di licenze tra cui scegliere. Quando crei un nuovo lavoro nella sezione delle licenze ci sarà un pulsante che elencherà tutte le licenze disponibili con tutti i dettagli. In generale offriamo protezioni complete del copyright e licenze <a href="https://creativecommons.org/" target="_blank" rel="noreferrer noopener external">Creative Commons</a> .',
    'faq.question.workshop.guildOwnership': 'Cos\'è la proprietà di una Gilda?',
    'faq.answer.workshop.guildOwnership': 'La proprietà di una gilda indica un lavoro di proprietà di un\'organizzazione, che chiamiamo gilde. Questo potrebbe essere un editore o un\'altra tipologia di azienda o organizzazione non-profit. La proprietà del lavoro è di solito un po\' più complessa e l\'autore potrebbe non avere il pieno controllo sul lavoro, ma significa principalmente che il lavoro è gestito attraverso l\'organizzazione e non dall\'autore dal proprio account personale.',
    'faq.question.workshop.howToInviteCollaborators': 'Come posso invitare collaboratori per una storia/universo?',
    'faq.answer.workshop.howToInviteCollaborators': 'Puoi invitare collaboratori alla tua storia/universo andando alla bacheca della storia/universo e cliccando il pulsante "collaboratori". Lì puoi invitare altri utenti a collaborare sulla tua storia/universo inserendo il loro nome utente e selezionando il ruolo che vuoi assegnare loro.',
    'faq.question.workshop.howToTranslation': 'Come posso tradurre la mia storia o universo?',
    'faq.answer.workshop.howToTranslation': 'Puoi tradurre la tua storia o universo andando alla bacheca della storia/universo e cliccando il pulsante "Traduzioni". Lì puoi aggiungere nuove traduzioni per il tuo lavoro e se hai qualcuno che può fare la traduzione puoi invitarli a unirsi alla traduzione. Da lì puoi anche gestire le traduzioni tu stesso.',
    'faq.question.workshop.betaReaders': 'Cosa sono i Beta Readers e qual è il loro scopo nella mia storia?',
    'faq.answer.workshop.betaReaders': 'I Beta Readers sono persone che leggono la tua storia prima che venga pubblicata e ti danno un feedback. Possono aiutarti a trovare errori, darti idee per miglioramenti e aiutarti a rendere la tua storia migliore.',
    'faq.question.workshop.hiatus': 'Cos\'è una pausa nello stato della storia?',
    'faq.answer.workshop.hiatus': 'Una pausa è uno stato per la tua storia che indica che stai facendo una pausa dalla scrittura e dalla pubblicazione di nuovi capitoli. È un modo per far sapere ai tuoi lettori che al momento non stai lavorando attivamente sulla storia. Questo stato viene impostato automaticamente dopo 6 mesi senza nuovi capitoli. Dopo ulteriori 6 mesi di inattività, la storia verrà contrassegnata come cancellata.',
    'faq.question.workshop.finished': 'Come posso indicare che la mia storia è finita?',
    'faq.answer.workshop.finished': 'Puoi indicare che la tua storia è finita andando alla bacheca della storia e in fondo c\'è un pulsante verde che dice "Cambia stato della storia in Completato". Questo segnerà la storia come finita, aggiustando l\'ultima pagina per dire ai lettori che la storia è finita e di dare un\'occhiata alle tue altre opere. Verrà anche indicato così nella scoperta, rendendo la tua storia più visibile ai lettori che cercano storie finite.',
    'faq.question.workshop.seo': 'Qual è l\'utilizzo di SEO-Friendly-Address in varie impostazioni?',
    'faq.answer.workshop.seo': 'SEO-Friendly-Address è un modo per rendere la tua storia, universo, articolo del blog più visibile ai motori di ricerca e per rendere l\'URL più leggibile per gli esseri umani. È un modo per rendere il tuo lavoro più scopribile e per aiutare le persone a trovare il tuo lavoro quando cercano qualcosa di simile.'
};