export default {
    'feedback.home': 'Centro assistenza',
    'feedback.bugs': 'Segnalazioni',
    'feedback.bugs.desc': 'Hai riscontrato errori o qualcos\'altro di sbagliato o fuori luogo? Faccelo sapere qui!',
    'feedback.features': 'Idee & Proposte',
    'feedback.features.desc': 'Hai idee per nuove funzionalità o su come migliorare il sito? Faccelo sapere!',
    'feedback.help': 'Aiuto & Tutorial',
    'feedback.help.desc': 'Come fai a _____? Vai qui per trovare le risposte.',
    'feedback.desc': 'Benvenuti nel nostro centro di aiuto e soluzione!',
    'feedback.faq': 'Domande frequenti',
    'feedback.faq.desc': 'Domande frequenti',
    'feedback.open': 'Apri',
    'feedback.closed': 'Chiudi',
    'feedback.accepted': 'Accettato',
    'feedback.inprogress': 'In corso',
    'feedback.completed': 'Completato',
    'feedback.fixed': 'Corretto',
    'feedback.new.bugs': 'Segnala un nuovo problema',
    'feedback.new.features': 'Suggerisci nuova funzione',
    'feedback.lang.nosupport': 'La tua lingua non è supportata per il feedback, per favore scrivi in inglese. Grazie!',
    'feedback.new.thanks': 'Grazie per la comunicazione! Ce ne occuperemo a breve.',
    'feedback.comment.title': 'Commento',
    'feedback.comment.desc': 'Inviaci il tuo feedback',
    'feedback.comment.legend': 'Il tuo feedback - per qualsiasi cosa, facci sapere',
    'feedback.comment.success': 'Grazie per il tuo feedback!',
    'feedback.comment.label': 'Il tuo commento',
    'feedback.copyrightReport.title': 'Violazione di copyright',
    'feedback.copyrightReport.desc': 'Segnala violazione del copyright',
    'feedback.report.noUser': 'Per inviare una segnalazione, devi effettuare l\'accesso.',
    'feedback.voting.totalVoters': 'Gli utenti hanno votato: {voted, number}',
    'feedback.voting.upvote': 'Voto positivo',
    'feedback.voting.downvote': 'Voto negativo',
    'feedback.voting.score': 'Punteggio totale',
    'feedback.report.title': 'Contenuto del rapporto',
    'feedback.report.typeSelect': 'Di che si tratta?',
    'feedback.reportType.law': 'Violazione della legge',
    'feedback.reportType.vulgar': 'Volgarità/oscenità',
    'feedback.reportType.copyright': 'Violazione di copyright',
    'feedback.reportType.storyRating': 'Classificazione dell\'età non corretta',
    'feedback.reportType.scam': 'Truffa',
    'feedback.report.submit': 'Segnala',
    'feedback.report.submitting': 'Sto segnalando...',
    'feedback.report.violationDesc': 'Dettagli',
    'feedback.report.reportSaved': 'Grazie per la segnalazione! Cercheremo di indagare e di intervenire, se necessario.',
    'feedback.report.copyrightReportSaved': 'Grazie per la segnalazione! Indagheremo e ti faremo sapere.',
    'feedback.report.copyrightOwnershipDesc': 'Dichiarazione di proprietà',
    'feedback.report.copyrightNotice': 'Si prega di notare che per utilizzare questo modulo è necessario essere il legittimo proprietario del lavoro. Se non lo sei, ti preghiamo di informare il proprietario o utilizzare l\'altra categoria per farcelo sapere. Prendiamo molto sul serio le violazioni di copyright e lo stesso vale per l\'uso improprio e abusivo di questo modulo.',
    'feedback.report.copyrightInternalProperty': 'Ho pubblicato questo lavoro su Literary Universe',
    'feedback.reportType.spam': 'Spam o truffa',
    'feedback.reportType.other': 'Altro',
    'feedback.report.copyrightType.propertySelectLabel': `Quale {type, select,
    universe {universo}
    story {storia}
    other {storia}
    } è stato/a violato/a?`,
    'faq.section.about': 'Chi siamo',
    'faq.section.settings': 'Impostazioni',
    'faq.section.discovery': 'Scopri',
    'faq.section.reader': 'Lettore',
    'faq.section.library': 'Raccolta',
    'faq.section.workshop': 'Laboratorio',
    'faq.section.writer': 'Scrittore',
    'faq.section.encyclopedia': 'Enciclopedia',
    'faq.section.groups': 'Gruppi',
    'faq.section.blogs': 'Blog',
    // About us questions
    'faq.question.about.dataLocation': 'Dove vengono memorizzati i dati di LU?',
    'faq.answer.about.dataLocation': 'I dati dell\'Universo Letterario sono memorizzati su server negli Stati Uniti d\'America, nello specifico nella regione AWS us-east-1.',
    'faq.question.about.incorporation': 'Dove siete incorporati?',
    'faq.answer.about.incorporation': 'Literary Universe is incorporated in the Czech Republic. You can find more details on the <a href="/about">about us page</a>.',
    'faq.question.about.roadmap': 'What are the next steps for Literary Universe?',
    'faq.answer.about.roadmap': 'This is constantly evolving. Check out our <a href="/roadmap">roadmap</a> for more details.',
    // Settings questions
    'faq.question.settings.changeTheme': 'How do I change the look of Literary Universe?',
    'faq.answer.settings.changeTheme': 'Registered users can change their theme in the <a href="/user/settings/account">account settings</a> under "site theming" section. We have a light and a dark theme available. If you are not registered, then we try to determine which theme to serve you based on your browser and operating system settings.',
    'faq.question.settings.changeAvatar': 'How do I change my avatar?',
    'faq.answer.settings.changeAvatar': 'You can change your avatar in the <a href="/user/settings/profile">profile settings</a>.',
    'faq.question.settings.changeLanguage': 'How do I change the language?',
    'faq.answer.settings.changeLanguage': 'You can change the language of Literary Universe in the <a href="/user/settings/account">account settings</a>.',
    'faq.question.settings.translationMistake': 'I found a mistake in the text on the website, where can I report it?',
    'faq.answer.settings.translationMistake': 'All our language files are available on GitHub. You can <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">submit an issue there</a> or in the Bug section of the feedback, or if you are so inclined, you can fix it directly yourself via <a href="https://crowdin.com/project/literary-universe" target="_blank">our Crowdin page</a>.'
};