export default {
    'homepage.welcome': 'Benvenuto su',
    'homepage.start': 'Inizia il tuo viaggio!',
    'homepage.iAm': 'Sono un',
    'homepage.iAm.aria': 'Seleziona tra la visualizzazione delle funzionalità per lettori e scrittori',
    'homepage.reader': 'LETTORE',
    'homepage.writer': 'SCRITTORE',
    'homepage.reader.title': 'La lettura non è mai stata così interessante',
    'homepage.reader.registerCTA': 'Inizi a leggere ora!',
    'homepage.reader.readingTitle': 'Un\'esperienza di lettura unica',
    'homepage.reader.readingDesc': 'Approfondisci il tuo universo di finzione preferito in Literary Universe. Le storie in Literary Universe sono connesse nello stesso universo, offrendoti un accesso immediato all\'enciclopedia dell\'universo dalla lettura della storia.',
    'homepage.reader.favoriteTitle': 'Scopri di più sulle tue storie e autori preferiti',
    'homepage.reader.favoriteDesc': 'L\'enciclopedia dell\'universo e i blog degli autori sono solo alcune delle funzionalità che ti aiuteranno a scoprire tutto ciò che devi sapere sulle tue storie preferite, le loro ambientazioni e i loro creatori!',
    'homepage.reader.communityTitle': 'Unisciti alla community',
    'homepage.reader.communityDesc': 'Incontra persone provenienti da tutto il mondo su forum dedicati all\'universo e agli autori, blog e altre funzionalità della community dove i fan con interessi simili si riuniscono. Tutto in un unico posto.',
    'homepage.reader.readingFeatureTitle': 'Goditi un\'esperienza di lettura coinvolgente e pratica',
    'homepage.reader.readingFeatureDesc': 'Dalle storie all\'universo, beneficia di una lettura senza sforzo con accesso ai dettagli senza dover passare da una pagina all\'altra.',
    'homepage.reader.readingExploreTitle': 'Esplora tutti i dettagli nell\'universo',
    'homepage.reader.readingExploreDesc': 'L\'enciclopedia dell\'universo ti permette di conoscere tutti i dettagli sull\'universo e immergerti completamente nelle storie.',
    'homepage.reader.start': 'Inizia la lettura',
    'homepage.writer.title': 'Mostra il tuo universo e condividi le tue storie',
    'homepage.writer.writingTitle': 'Scrittura e creazione semplificate',
    'homepage.writer.writingDesc': 'Vivi la nuova modalità di scrittura con il Workshop degli Universi Letterari. Crea tutti i dettagli del tuo universo in un\'enciclopedia da condividere con i tuoi lettori e scrivi storie straordinarie su questa base.',
    'homepage.writer.collaborationTitle': 'Creazione collaborativa',
    'homepage.writer.collaborationDesc': 'Il processo creativo coinvolge spesso più persone. Non preoccuparti, siamo qui per te! Puoi facilmente aggiungere beta reader, co-autori e traduttori alle tue storie e universi.',
    'homepage.writer.communityTitle': 'Connettiti con i tuoi lettori',
    'homepage.writer.communityDesc': 'Vai oltre la scrittura e connettiti con i tuoi lettori tramite blog, forum e altre funzionalità della comunità collegate ai tuoi universi o a te come scrittore.',
    'homepage.writer.workshopFeatureTitle': 'Un unico luogo per tutte le tue esigenze creative',
    'homepage.writer.workshopFeatureDesc': 'Il nostro workshop in continua evoluzione è il luogo centrale per le tue esigenze creative. Da una semplice idea, crea universi straordinari, storie e tutto ciò che è necessario attorno ad essi.',
    'homepage.writer.monetizationFeatureTitle': 'Monetizzazione',
    'homepage.writer.monetizationDesc': 'Crediamo fortemente che le persone debbano essere pagate per il loro lavoro e cerchiamo costantemente nuove opportunità di monetizzazione per gli scrittori. La funzione di monetizzazione consente agli scrittori di essere apprezzati per ciò che fanno. Esplora tutte le diverse opzioni che permettono ai tuoi fan di mostrarti il loro apprezzamento.',
    'homepage.writer.start': 'Configura il tuo workshop!',
    'homepage.featureSelection': 'Scopri questi universi popolari!',
    'about.title': 'Informazioni su Literary Universe',
    'about.desc': 'Storia, segreti e umani dietro Literary Universe.',
    'about.text.1': 'Letteratura Universe è progettato sia per gli scrittori che per i lettori appassionati. Gli scrittori possono utilizzare la piattaforma per creare opere originali selezionando il pulsante "Workshop" nel menu della dashboard. Questo fornisce accesso all\'editor principale e alle funzioni dell\'enciclopedia, che si concentrano sull\'organizzazione di tutti gli aspetti del tuo universo narrativo personale in una singola pagina. Le funzionalità social permettono agli autori di condividere il loro lavoro, costruire un seguito e interagire in modo più diretto con i loro lettori se lo desiderano.',
    'about.text.2': 'I lettori possono utilizzare il sito principalmente per scoprire nuove opere e seguire i loro autori preferiti, ma possono anche aiutare a modificare storie pre-pubblicate se l\'autore concede il permesso. Essere un lettore su Literary Universe offre un\'esperienza di lettura completamente nuova: avere accesso a tutte le informazioni di sfondo nella stessa pagina della storia principale fornisce una visione della mente dell\'autore come mai prima d\'ora.',
    'about.text.3': 'Il futuro di Literary Universe include la creazione di un mercato in cui gli autori possono vendere le loro opere e l\'aggiunta di funzionalità comunitarie per migliorare la comunicazione tra autori e lettori attraverso blog e forum. Abbiamo in programma di introdurre nel tempo ulteriori strumenti per gli scrittori, con più di una dozzina attualmente in fase di sviluppo o pianificati. Il nostro obiettivo finale è arricchire l\'esperienza di scrittori e lettori sfruttando in modo innovativo il mezzo internet.',
    'about.text.4': 'Speriamo che tu ti unisca a noi mentre esploriamo cosa può fare il mezzo internet per la scrittura creativa!',
    'about.team': 'Il Team',
    'about.history': 'Cronologia',
    'about.company': 'L\'azienda',
    'about.companyCountry.czechia': 'Cechia',
    'about.companyCountry.japan': 'Giappone',
    'about.companyCity.prague': 'Praga',
    'about.companyCity.sendai': 'Sendai',
    'about.CEO': 'Amministratore Delegato',
    'about.CTO': 'Direttore Tecnico',
    'about.jan': 'Jan è il fondatore, il visionario e il genio tecnologico dietro a Literary Universe. Come scrittore di universi letterari vasti, Jan spesso ha faticato nello scrivere storie in modo equilibrato tra precisione tecnica e leggibilità, senza compromettere l\'esperienza del lettore. Questa sfida lo ha spinto a perseguire gli studi nello sviluppo web, con l\'obiettivo di creare un\'applicazione che semplifichi il processo di scrittura di storie all\'interno di grandi universi.',
    'about.history.text': 'Nel 2010, Jan ha iniziato i suoi studi presso il Rochester Institute of Technology per approfondire le sue conoscenze nello sviluppo web, con l\'obiettivo di costruire una piattaforma di scrittura creativa. Questa visione si è concretizzata nel 2013 quando la prima prova concettuale è stata presentata a Imagine RIT. Jan ha continuato i suoi studi e nel 2016 è stata creata una nuova versione dell\'app come suo progetto per la tesi magistrale. Il progetto è continuato a evolversi durante l\'autunno 2016, sviluppandosi infine nella piattaforma che vedi oggi.',
    'copyrights.desc': 'Informazioni sui diritti d\'autore su Universo Letterario.',
    'privacy.desc': 'Testo legale completo della Privacy Policy di Literary Universe.',
    'guidelines.desc': 'Linee guida della community di Literary Universe.',
    'tos.desc': 'Testo legale completo dei Termini di servizio di Literary Universe.',
    'homepage.intro': 'Lascia che la tua creatività si scateni nell\'Universo Letterario',
    // 'homepage.explanation':
    //   'Literary Universe is all-in-one creative writing and reading platform, focused on complex literary universe.  We aim to provide interconnected tools to write complex story universes and stories, and a great experience for fans and readers in exploring those universe.',
    'homepage.explanation': 'Hai mai sognato di sviluppare un mondo di finzione così dettagliato da perderci anche tu? Su Literary Universe, mettiamo a disposizione gli strumenti per rendere questa visione realtà. Ogni scrittore merita accesso a risorse e supporto di prima classe. Ecco perché abbiamo progettato uno spazio completo che colma il divario tra narrazione intricata e lettura appassionata. Per gli scrittori, è uno spazio di lavoro ideale; per i lettori, un\'odissea di esplorazione. Unisciti a noi mentre seguiamo la tana del coniglio letterario per scoprire quanto lontano ci porterà nel mondo dell\'immaginazione.',
    'gdpr.title': 'Conformità GDPR',
    'gdpr.desc': 'Literary Universe è conforme alle direttive del GDPR dell\'UE.',
    'gdpr.compliant': 'L\'Universo Letterario è conforme al GDPR',
    'gdpr.compliant.text': 'Literary Universe ha implementato vari aggiornamenti e modifiche alla sua codebase in preparazione all\'applicazione del GDPR il 25 maggio 2018.',
    'common.legal.dmca': 'DMCA',
    'common.legal.dmca.long': 'Digital Millennium Copyright Act',
    'common.legal.changelog': 'Modifiche in questa versione',
    'dmca.title': 'Politica sul Digital Millennium Copyright Act (DMCA)',
    'dmca.subtitle': 'Politica sulle controversie di copyright',
    'dmca.step1.title': 'Procedura per segnalare violazioni del copyright.',
    'dmca.step2.title': 'Una volta ricevuta una notifica di violazione adeguata e in buona fede da parte dell\'Agente designato.',
    'dmca.step3.title': 'Procedura per fornire una contro-notifica all\'Agente designato.',
    'dmca.desc': 'Prendiamo seriamente le violazioni del copyright.',
    'gdpr.access.title': 'Diritto di accesso e diritto alla portabilità dei dati',
    'gdpr.access.desc': 'Nelle impostazioni utente è possibile esportare tutti i propri dati. I dati saranno in formato JSON standard.',
    'gdpr.forget.title': 'Esportazione',
    'gdpr.forget.desc': 'Ogni account può essere cancellato tramite le impostazioni dell\'utente. Alcuni dati potrebbero essere conservati, soprattutto se sono stati oggetto di vendita e/o di controversie.',
    'gdpr.rectification.title': 'Diritto alla rettificazione',
    'gdpr.rectification.desc': ' ',
    'gdpr.processing.title': 'Diritto di limitazione del trattamento',
    'gdpr.processing.desc': 'Literary Universe rispetta pienamente le impostazioni del browser, come le richieste "Do not track" per la segnalazione al nostro server di statistiche Matomo.',
    'gdpr.object.title': 'Diritto all\'oggetto',
    'gdpr.object.desc': ' ',
    'dmca.step1.desc1': 'La segnalazione è divisa in due scenari. 1. Proprietà interna (violazione sul sito della proprietà esistente sul sito). 2. Proprietà esterna (violazione sul sito di una proprietà non esistente sul sito).',
    'dmca.step1.desc2': 'La segnalazione di una proprietà interna può essere fatta tramite il pulsante di segnalazione sulla proprietà. La segnalazione di una violazione di proprietà esterna può essere fatta tramite la schermata di feedback. In entrambi i casi ti verrà chiesto di fornire dati personali e dettagli aggiuntivi che ci permetteranno di verificare la tua proprietà.',
    'dmca.step1.desc3': 'Si prega di notare che fare false dichiarazioni comporterà la tua incapacità di presentare reclami in futuro.',
    'dmca.step2.desc1': 'Al ricevimento della tua segnalazione, verificheremo le tue credenziali e la tua richiesta di proprietà. Se tutto è corretto, procederemo a verificare il reclamo. Se determiniamo che il reclamo è vero, la proprietà che viola i diritti sarà resa inaccessibile fino alla determinazione del contronotifica o fino a quando saranno trascorsi 14 giorni, dopodiché sarà eliminata.',
    'dmca.step3.desc1': 'Una volta ricevuta una denuncia, il proprietario della proprietà designata avrà 14 giorni per presentare una contronotifica. L\'Agente Designato procederà quindi a investigare sulla controversia. Qualsiasi decisione presa dall\'Agente Designato in questa fase sarà definitiva.',
    // Team members - only translate if lang has specific spelling for foreign names or switches the order of family vs given name
    'team.name.jdvorak': 'Jan Dvořák',
    'about.attributions': 'Attribuzioni',
    'about.attributionsIntro': 'Literary Universe si basa su molti progetti Open Source e risorse gratuite. Qui sotto troverai il loro elenco.',
    'about.attributionsMatomo': 'Le nostre analisi utilizzano Matomo in hosting con i dati IP2Location LITE disponibili su https://lite.ip2location.com.',
    'team.name.pjakubec': 'Pavel Jakubec',
    'about.developer': 'Sviluppatore',
    'about.seniorDeveloper': 'Sviluppatore Senior',
    'about.juniorDeveloper': 'Sviluppatore Junior',
    'about.leadDesigner': 'Designer principale',
    'about.leadUX': 'Designer UX principale',
    'about.intern': 'Stagista',
    'about.advisor': 'Consulente',
    'about.headOfResearch': 'Responsabile della Ricerca',
    'about.CFO': 'Direttore Finanziario',
    'team.name.hsconovianus': 'Hendry Sconovianus',
    'about.hendry': 'Hendry è un designer con più di 15 anni di esperienza. Ha lavorato in un\'agenzia dal 2010, con clienti come PERTAMINA, VOA e il Ministero del Turismo dell\'Indonesia. Esperto di branding, layout e anche UI/UX, si sente sfidato nel progettare Literary Universe.',
    'about.pavel': 'Web3, il Metaverse, l\'IA e ogni tecnologia emergente: Pavel esplora tutto ciò per vedere come può migliorare Literary Universe. Come vero ricercatore multidisciplinare, Pavel ha conoscenze in molti campi e lavora per integrare nuove ed entusiasmanti funzionalità nella piattaforma.',
    'copyrights.about': 'Universo Letterario prende molto sul serio il Copyright. Tutti i contenuti pubblicati dagli utenti sono di loro proprietà e sono disponibili con la licenza specificata. Oltre alla serie completa di licenze Creative Commons, Literary Universe offre anche 2 licenze commerciali, esclusiva e non esclusiva.',
    'copyrights.nonExclusiveLicense': 'La Licenza Non Esclusiva di Literary Universe le permette di pubblicare su Literary Universe senza cedere nessuno dei suoi diritti di titolare del copyright. È libero di pubblicare altrove. Literary Universe si riserva il diritto di utilizzare la sua IP solo per scopi di marketing. Se decide di vendere la sua IP su Literary Universe, la piattaforma addebiterà una commissione del 30%.',
    'copyrights.exclusiveLicense': 'La Licenza esclusiva di Literary Universe le consente di pubblicare esclusivamente su Literary Universe. Ciò significa che non può pubblicare la sua IP su altre piattaforme online o altro al di fuori di Literary Universe. Se desidera pubblicare un supporto fisico come un libro, deve chiedere l\'autorizzazione a Literary Universe. Se Literary Universe non risponde entro 30 giorni, si tratta di un consenso automatico. In futuro speriamo di poterle offrire la pubblicazione fisica e altri servizi tramite i nostri partner. Non abbia paura di contattarci, ci auguriamo il suo successo e nella maggior parte dei casi stiamo solo cercando di evitare le aziende fraudolente. Tuttavia questo è restrittivo, quindi per ringraziarla, la commissione della piattaforma è solo del 10%.',
    'copyrights.licensesAreImportant': 'La scelta di una licenza è estremamente importante e influisce sulle modalità di accesso al suo lavoro in futuro. Per facilitare la scelta, può consultare il nostro selezionatore di licenze qui sotto.'
};