export default {
    'feedback.home': 'Yardım merkezi',
    'feedback.bugs': 'Sorunlar',
    'feedback.bugs.desc': 'Hata veya başka bir yanlışlıkla karşılaştınız mı? Bize buradan bildirin!',
    'feedback.features': 'Fikirler ve Öneriler',
    'feedback.features.desc': 'Yeni özellikler için fikirleriniz mi var veya siteyi nasıl daha iyi yapabiliriz? Bize bildirin!',
    'feedback.help': 'Yardım ve Öğreticiler',
    'feedback.help.desc': '_____nasıl yapılır? Cevapları burada bulabilirsiniz.',
    'feedback.desc': 'Yardım ve çözüm merkezimize hoş geldiniz!',
    'feedback.faq': 'SSS',
    'feedback.faq.desc': 'Sıkça Sorulan Sorular',
    'feedback.open': 'Açık',
    'feedback.closed': 'Kapalı',
    'feedback.accepted': 'Kabul edildi',
    'feedback.inprogress': 'Devam ediyor',
    'feedback.completed': 'Tamamlandı',
    'feedback.fixed': 'Düzeltildi',
    'feedback.new.bugs': 'Yeni sorun bildir',
    'feedback.new.features': 'Yeni bir özellik öner',
    'feedback.lang.nosupport': 'Mevcut diliniz geri bildirim için desteklenmiyor, lütfen İngilizce yazın. Teşekkür ederiz!',
    'feedback.new.thanks': 'Bildirim için teşekkür ederiz! En kısa sürede inceleyeceğiz.',
    'feedback.comment.title': 'Yorum',
    'feedback.comment.desc': 'Bize geri bildirim gönderin',
    'feedback.comment.legend': 'Geri bildiriminiz - herhangi bir şey hakkında bize bilgi verin',
    'feedback.comment.success': 'Geri bildiriminiz için teşekkür ederiz!',
    'feedback.comment.label': 'Yorumunuz',
    'feedback.copyrightReport.title': 'Telif hakkı ihlali',
    'feedback.copyrightReport.desc': 'Telif hakkı ihlali bildir',
    'feedback.report.noUser': 'Bir rapor göndermek için giriş yapmanız gerekmektedir.',
    'feedback.voting.totalVoters': 'Kullanıcılar oy kullandı: {voted, number}',
    'feedback.voting.upvote': 'Yukarı oy',
    'feedback.voting.downvote': 'Aşağı oy',
    'feedback.voting.score': 'Toplam puan',
    'feedback.report.title': 'İçeriği rapor et',
    'feedback.report.typeSelect': 'Burada sorun ne?',
    'feedback.reportType.law': 'Kanun ihlali',
    'feedback.reportType.vulgar': 'Kaba/edepsiz',
    'feedback.reportType.copyright': 'Telif hakkı ihlali',
    'feedback.reportType.storyRating': 'Yanlış yaş derecelendirmesi',
    'feedback.reportType.scam': 'Dolandırıcılık',
    'feedback.report.submit': 'Rapor',
    'feedback.report.submitting': 'Raporlanıyor...',
    'feedback.report.violationDesc': 'Detaylar',
    'feedback.report.reportSaved': 'Raporunuz için teşekkür ederiz! Gerekliyse araştırma yapacak ve gereken önlemleri alacağız.',
    'feedback.report.copyrightReportSaved': 'Raporunuz için teşekkür ederiz! Araştırma yapacak ve sizinle iletişime geçeceğiz.',
    'feedback.report.copyrightOwnershipDesc': 'Mülkiyet bildirimi',
    'feedback.report.copyrightNotice': 'Lütfen bu formu kullanmak için eserin hak sahibi olmanız gerektiğini unutmayın. Eğer sahip değilseniz, lütfen sahibi bilgilendirin veya bize bilgi vermek için diğer kategoriyi kullanın. Telif hakkı ihlallerini son derece ciddiye alıyoruz ve aynı şey bu formun yanlış ve kötüye kullanımı için de geçerlidir.',
    'feedback.report.copyrightInternalProperty': 'Bu eseri Literary Universe üzerinde yayımladım',
    'feedback.reportType.spam': 'Spam veya phishing',
    'feedback.reportType.other': 'Diğer',
    'feedback.report.copyrightType.propertySelectLabel': `Hangi {type, select,
    universe {evrenin}
    story {hikayesi}
    other {hikayesi}
  } ihlal ediliyor?`,
    'faq.section.about': 'Hakkımızda',
    'faq.section.settings': 'Ayarlar',
    'faq.section.discovery': 'Keşif',
    'faq.section.reader': 'Okuyucu',
    'faq.section.library': 'Kütüphane',
    'faq.section.workshop': 'Atölye',
    'faq.section.writer': 'Yazar',
    'faq.section.encyclopedia': 'Ansiklopedi',
    'faq.section.groups': 'Gruplar',
    'faq.section.blogs': 'Bloglar',
    // About us questions
    'faq.question.about.dataLocation': 'LU verileri nerede saklanır?',
    'faq.answer.about.dataLocation': 'Literary Universe verileri Amerika Birleşik Devletleri\'ndeki sunucularda saklanır, özellikle AWS us-east-1 bölgesinde.',
    'faq.question.about.incorporation': 'Nerede tescil edildiniz?',
    'faq.answer.about.incorporation': 'Literary Universe is incorporated in the Czech Republic. You can find more details on the <a href="/about">about us page</a>.',
    'faq.question.about.roadmap': 'What are the next steps for Literary Universe?',
    'faq.answer.about.roadmap': 'This is constantly evolving. Check out our <a href="/roadmap">roadmap</a> for more details.',
    // Settings questions
    'faq.question.settings.changeTheme': 'How do I change the look of Literary Universe?',
    'faq.answer.settings.changeTheme': 'Registered users can change their theme in the <a href="/user/settings/account">account settings</a> under "site theming" section. We have a light and a dark theme available. If you are not registered, then we try to determine which theme to serve you based on your browser and operating system settings.',
    'faq.question.settings.changeAvatar': 'How do I change my avatar?',
    'faq.answer.settings.changeAvatar': 'You can change your avatar in the <a href="/user/settings/profile">profile settings</a>.',
    'faq.question.settings.changeLanguage': 'How do I change the language?',
    'faq.answer.settings.changeLanguage': 'You can change the language of Literary Universe in the <a href="/user/settings/account">account settings</a>.',
    'faq.question.settings.translationMistake': 'I found a mistake in the text on the website, where can I report it?',
    'faq.answer.settings.translationMistake': 'All our language files are available on GitHub. You can <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">submit an issue there</a> or in the Bug section of the feedback, or if you are so inclined, you can fix it directly yourself via <a href="https://crowdin.com/project/literary-universe" target="_blank">our Crowdin page</a>.'
};