export default {
    'feedback.home': 'Yardım merkezi',
    'feedback.bugs': 'Sorunlar',
    'feedback.bugs.desc': 'Hata veya başka bir yanlışlıkla karşılaştınız mı? Bize buradan bildirin!',
    'feedback.features': 'Fikirler ve Öneriler',
    'feedback.features.desc': 'Yeni özellikler için fikirleriniz mi var veya siteyi nasıl daha iyi yapabiliriz? Bize bildirin!',
    'feedback.help': 'Yardım ve Öğreticiler',
    'feedback.help.desc': '_____nasıl yapılır? Cevapları burada bulabilirsiniz.',
    'feedback.desc': 'Yardım ve çözüm merkezimize hoş geldiniz!',
    'feedback.faq': 'SSS',
    'feedback.faq.desc': 'Sıkça Sorulan Sorular',
    'feedback.open': 'Açık',
    'feedback.closed': 'Kapalı',
    'feedback.accepted': 'Kabul edildi',
    'feedback.inprogress': 'Devam ediyor',
    'feedback.completed': 'Tamamlandı',
    'feedback.fixed': 'Düzeltildi',
    'feedback.new.bugs': 'Yeni sorun bildir',
    'feedback.new.features': 'Yeni bir özellik öner',
    'feedback.lang.nosupport': 'Mevcut diliniz geri bildirim için desteklenmiyor, lütfen İngilizce yazın. Teşekkür ederiz!',
    'feedback.new.thanks': 'Bildirim için teşekkür ederiz! En kısa sürede inceleyeceğiz.',
    'feedback.comment.title': 'Yorum',
    'feedback.comment.desc': 'Bize geri bildirim gönderin',
    'feedback.comment.legend': 'Geri bildiriminiz - herhangi bir şey hakkında bize bilgi verin',
    'feedback.comment.success': 'Geri bildiriminiz için teşekkür ederiz!',
    'feedback.comment.label': 'Yorumunuz',
    'feedback.copyrightReport.title': 'Telif hakkı ihlali',
    'feedback.copyrightReport.desc': 'Telif hakkı ihlali bildir',
    'feedback.report.noUser': 'Bir rapor göndermek için giriş yapmanız gerekmektedir.',
    'feedback.voting.totalVoters': 'Kullanıcılar oy kullandı: {voted, number}',
    'feedback.voting.upvote': 'Yukarı oy',
    'feedback.voting.downvote': 'Aşağı oy',
    'feedback.voting.score': 'Toplam puan',
    'feedback.report.title': 'İçeriği rapor et',
    'feedback.report.typeSelect': 'Burada sorun ne?',
    'feedback.reportType.law': 'Kanun ihlali',
    'feedback.reportType.vulgar': 'Kaba/edepsiz',
    'feedback.reportType.copyright': 'Telif hakkı ihlali',
    'feedback.reportType.storyRating': 'Yanlış yaş derecelendirmesi',
    'feedback.reportType.scam': 'Dolandırıcılık',
    'feedback.report.submit': 'Rapor',
    'feedback.report.submitting': 'Raporlanıyor...',
    'feedback.report.violationDesc': 'Detaylar',
    'feedback.report.reportSaved': 'Raporunuz için teşekkür ederiz! Gerekliyse araştırma yapacak ve gereken önlemleri alacağız.',
    'feedback.report.copyrightReportSaved': 'Raporunuz için teşekkür ederiz! Araştırma yapacak ve sizinle iletişime geçeceğiz.',
    'feedback.report.copyrightOwnershipDesc': 'Mülkiyet bildirimi',
    'feedback.report.copyrightNotice': 'Lütfen bu formu kullanmak için eserin hak sahibi olmanız gerektiğini unutmayın. Eğer sahip değilseniz, lütfen sahibi bilgilendirin veya bize bilgi vermek için diğer kategoriyi kullanın. Telif hakkı ihlallerini son derece ciddiye alıyoruz ve aynı şey bu formun yanlış ve kötüye kullanımı için de geçerlidir.',
    'feedback.report.copyrightInternalProperty': 'Bu eseri Literary Universe üzerinde yayımladım',
    'feedback.reportType.spam': 'Spam veya phishing',
    'feedback.reportType.other': 'Diğer',
    'feedback.report.copyrightType.propertySelectLabel': `Hangi {type, select,
    universe {evrenin}
    story {hikayesi}
    other {hikayesi}
  } ihlal ediliyor?`,
    'faq.section.about': 'Hakkımızda',
    'faq.section.settings': 'Ayarlar',
    'faq.section.discovery': 'Keşif',
    'faq.section.reader': 'Okuyucu',
    'faq.section.library': 'Kütüphane',
    'faq.section.workshop': 'Atölye',
    'faq.section.writer': 'Yazar',
    'faq.section.encyclopedia': 'Ansiklopedi',
    'faq.section.groups': 'Gruplar',
    'faq.section.blogs': 'Bloglar',
    'faq.section.guilds': 'Loncalar',
    // About us questions
    'faq.question.about.whatIsLU': 'Edebi Evren Nedir?',
    'faq.answer.about.whatIsLU': 'Edebiyat Evreni, yazarların ve okuyucuların hikayeler ve dünyalar oluşturabileceği, paylaşabileceği ve keşfedebileceği bir platformdur.',
    'faq.question.about.difference': 'Edebiyat Evreni diğer çevrimiçi okuma platformlarından ne farklıdır?',
    'faq.answer.about.difference': 'Edebiyat Evreni, yazma, okuma, evren oluşturma ve topluluk oluşturma araçlarını içeren tek bir platformdur. Temel fark, tüm bu araçların bir arada olması ve birbirleriyle bağlantılı olmasıdır.',
    'faq.question.about.dataLocation': 'LU verileri nerede saklanır?',
    'faq.answer.about.dataLocation': 'Literary Universe verileri Amerika Birleşik Devletleri\'ndeki sunucularda saklanır, özellikle AWS us-east-1 bölgesinde.',
    'faq.question.about.incorporation': 'Nerede tescil edildiniz?',
    'faq.answer.about.incorporation': 'Literary Universe, Çek Cumhuriyeti\'nde kurulmuştur. Bize dair daha fazla detayı <a href="/about">hakkımızda sayfasında</a>bulabilirsiniz.',
    'faq.question.about.roadmap': 'Literary Universe için sonraki adımlar nelerdir?',
    'faq.answer.about.roadmap': 'Bu sürekli olarak gelişmektedir. Daha fazla detay için <a href="/roadmap">yol haritasına</a> göz atabilirsiniz.',
    // Settings questions
    'faq.question.settings.changeTheme': 'Literary Universe\'ün görünümünü nasıl değiştirebilirim?',
    'faq.answer.settings.changeTheme': 'Kayıtlı kullanıcılar, "site temaları" bölümü altında <a href="/user/settings/account">hesap ayarları</a> içerisinde temalarını değiştirebilirler. Bir açık ve bir koyu tema seçeneğimiz bulunmaktadır. Kayıtlı değilseniz, tarayıcı ve işletim sistemi ayarlarınıza dayanarak size hangi temayı sunacağımızı belirlemeye çalışıyoruz.',
    'faq.question.settings.changeAvatar': 'Avatarımı nasıl değiştirebilirim?',
    'faq.answer.settings.changeAvatar': 'Avatarınızı <a href="/user/settings/profile">profil ayarları</a>içerisinde değiştirebilirsiniz.',
    'faq.question.settings.changeLanguage': 'Dili nasıl değiştirebilirim?',
    'faq.answer.settings.changeLanguage': 'Literary Universe\'ün dilini <a href="/user/settings/account">hesap ayarları</a>içerisinde değiştirebilirsiniz.',
    'faq.question.settings.translationMistake': 'Web sitesindeki metinde bir hata buldum, nereye bildirebilirim?',
    'faq.answer.settings.translationMistake': 'Tüm dil dosyalarımız GitHub üzerinde mevcuttur. Orada bir sorun <a target="_blank" href="https://github.com/LiteraryUniverse/intl-web/issues/new/choose">bildirebilirsiniz</a> ya da geri bildirimlerin Hata bölümünde veya isterseniz doğrudan <a href="https://crowdin.com/project/literary-universe" target="_blank">Crowdin sayfamız</a>üzerinden düzeltebilirsiniz.',
    // Discovery questions
    'faq.question.discovery.explain': 'Keşif bölümü nedir?',
    'faq.answer.discovery.explain': 'Keşif bölümü, yeni hikayeler, evrenler, bloglar, gruplar ve diğer içerikleri bulabileceğiniz bir yerdir. Okumak ve keyif almak için yeni şeyler keşfetmek için kullanılır.',
    // Writer
    'faq.question.writer.howToCreateStory': 'Edebiyat Evreni\'nde nasıl yeni bir hikaye oluşturabilirim?',
    'faq.answer.writer.howToCreateStory': 'You can create a new story by going to the <a href="/workshop">workshop</a> and clicking on one of the create buttons or go to the main <a href="/workshop/create">create page</a> where you can select a <a href="/workshop/create/story">new standalone story</a> or <a href="/workshop/create/fanfiction">fan fiction</a>. To create a new story in a universe, go first to that universe and then select "stories" on the dashboard and on the next page click the big red button on the right side of the page title. You will be asked to fill in the details of your story and then you can start writing.',
    'faq.question.writer.schedule': 'Edebiyat Evreni\'nde bir bölümün yayınlanma zamanını nasıl planlarım?',
    'faq.answer.writer.schedule': 'Bölüm düzenleyicide yayınlama düğmesine tıkladığınızda, bir bölümün yayınlanma zamanını planlamak için bir iletişim kutusu görüntülenir. Bir yayın zamanı planlamak veya hemen yayınlamak için seçenek sunulur. Yayın zamanını planlamayı seçerseniz, bölümün yayınlanmasını istediğiniz tarihi ve saati seçmeniz istenir. Yeni bir bölüm için okuyucuların hazırlanması ve haftanın aynı günü ve saatinde yayınlanması için bölümleri en az 24 saat önceden planlamanızı öneririz.',
    // Reader
    'faq.question.reader.creativeTypes': 'Evren, Hikayeler ve Hayran Kurgu arasındaki fark nedir?',
    'faq.answer.reader.creativeTypes': 'Evren, belirli bir edebi dünya ile ilgili tüm hikayeleri ve diğer içerikleri bulabileceğiniz bir yerdir. Hikayeler ya bağımsız hikayelerdir ya da başka birinin oluşturduğu bir edebi evrene aittir. Hayran Kurgu, başka bir edebi evrene dayanan bir hikayedir.',
    // Workshop
    'faq.question.workshop.explain': 'Atölye nedir?',
    'faq.answer.workshop.explain': 'Atölye, yeni hikayeler, hayran kurgu, evrenler ve diğer içerikleri oluşturabileceğiniz bir yerdir. Yaratıcı içeriğinizi yazmanızı, düzenlemenizi ve yönetmenizi sağlar.',
    'faq.question.workshop.creativeTypes': 'Evren, Hikayeler ve Hayran Kurgu arasındaki fark nedir?',
    'faq.answer.workshop.creativeTypes': 'Evren, aynı edebi dünyada yer alan hikayeleri oluşturduğunuz edebi evreniniz için merkezi bir yerdir, dünyanızın tüm ayrıntılarına sahip bir ansiklopedi yönetir ve bununla ilgili her şeyi yapar. Hayran Kurgu, başka bir hikaye veya evrene dayanan bir hikayedir. Bağımsız hikayeler, herhangi bir evrene bağlı olmayan hikayelerdir, bunu örneğin şiir veya gerçek dünyada geçen karakter veya etkileyici ayrıntıların ansiklopedi veya diğer evren avantajlarına ihtiyaç duymadan edebi çalışmalar için kullanabilirsiniz.',
    'faq.question.workshop.continueStory': 'Daha önce oluşturulmuş bir hikayeyi nasıl devam ettirebilirim?',
    'faq.answer.workshop.continueStory': 'You can continue a previously created story by going to the <a href="/workshop">workshop</a> and selecting the story you want to continue or if it is a story in a universe, you need to first go to the universe and select the story from the stories listing. On the story dashboard you can then click on the chapter you want to continue writing or create a new chapter.',
    'faq.question.workshop.whatIsALicense': 'Hikaye Lisansı nedir?',
    'faq.answer.workshop.whatIsALicense': 'Hikaye lisansı, hikayenizin/evreninizin başkaları tarafından nasıl kullanılabileceğini tanımlayan yasal bir belgedir. Bu, haklarınızı korumanın ve başkalarının çalışmanızı nasıl kullanabileceğini belirlemenin bir yoludur.',
    'faq.question.workshop.licenses': 'Hangi lisanslar mevcut?',
    'faq.answer.workshop.licenses': 'We offer a variety of licenses to choose from. When creating a new work in the licenses section will be a button which will list all available licenses with their full details. In general we offer full copyright protections and <a href="https://creativecommons.org/" target="_blank" rel="noreferrer noopener external">Creative Commons</a> licenses.',
    'faq.question.workshop.guildOwnership': 'Bir Lonca sahipliği nedir?',
    'faq.answer.workshop.guildOwnership': 'Kilise sahipliği, bir organizasyon tarafından sahip olunan bir çalışmayı ifade eder, onlara Loncalar diyoruz. Bu bir yayıncı veya başka tür bir şirket veya kar amacı gütmeyen bir organizasyon olabilir. Eserin sahipliği genellikle biraz daha karmaşıktır ve yazar eserin üzerinde tam kontrol sahibi olmayabilir, bu genellikle eserin organizasyon tarafından yönetildiği ve yazarın kişisel hesabından değil olduğu anlamına gelir.',
    'faq.question.workshop.howToInviteCollaborators': 'Bir hikaye/evren için işbirlikçileri nasıl davet edebilirim?',
    'faq.answer.workshop.howToInviteCollaborators': 'Hikaye/evren panosuna giderek ve "işbirlikçiler" düğmesine tıklayarak hikaye/evreninize işbirlikçi davet edebilirsiniz. Orada kullanıcı adını girerek ve onlara atamak istediğiniz rolü seçerek diğer kullanıcıları hikaye/evreninizde işbirliği yapmaya davet edebilirsiniz.',
    'faq.question.workshop.howToTranslation': 'Hikayemi veya evrenimi nasıl çevirebilirim?',
    'faq.answer.workshop.howToTranslation': 'Hikayenizi veya evreninizi çevirmek için hikaye/evren panosuna giderek ve "Çeviriler" düğmesine tıklayarak yeni bir çeviri ekleyebilirsiniz. Eğer çeviri yapacak biri varsa, onları çeviriye katılmaya davet edebilirsiniz. Oradan çevirileri kendiniz yönetebilirsiniz.',
    'faq.question.workshop.betaReaders': 'Beta Okuyucular nedir ve hikayeme ne gibi katkıları olur?',
    'faq.answer.workshop.betaReaders': 'Beta okuyucular, hikayenizi yayınlamadan önce okuyan ve geri bildirim veren kişilerdir. Hataları bulmanıza, geliştirmeler için fikirler sunmanıza ve hikayenizi daha iyi hale getirmenize yardımcı olabilirler.',
    'faq.question.workshop.hiatus': 'Hikaye durumunda bir ara ne anlama gelir?',
    'faq.answer.workshop.hiatus': 'Ara, hikayenizin yazma ve yeni bölümler yayınlama sürecinden bir süreliğine ara verdiğinizi gösteren bir durumdur. Bu, okuyucularınıza şu anda hikaye üzerinde aktif olarak çalışmadığınızı bildirmenin bir yoludur. Bu durum, yeni bölümler olmadan 6 ay sonra otomatik olarak ayarlanır. Ek 6 ay süreyle faaliyetsizlik durumunda hikaye iptal edilmiş olarak işaretlenir.',
    'faq.question.workshop.finished': 'Hikayemin bittiğini nasıl belirtebilirim?',
    'faq.answer.workshop.finished': 'Hikayenizin bittiğini belirtebilirsiniz. Bunun için hikaye panosuna gidin ve alt kısımda "Hikaye durumunu Tamamlandı olarak değiştir" yazan yeşil bir düğme bulunur. Bu, hikayeyi tamamlanmış olarak işaretleyerek son sayfayı okuyuculara hikayenin bittiğini ve diğer çalışmalarınıza göz atabileceklerini söyleyen şekilde ayarlar. Ayrıca keşifte de böyle gösterilir, böylece tamamlanmış hikayeler arayan okuyucular tarafından daha fazla fark edilir.',
    'faq.question.workshop.seo': 'Çeşitli ayarlarda SEO Dostu Adresin kullanımı nedir?',
    'faq.answer.workshop.seo': 'SEO-Dostu-Adres, hikayenizi, evreninizi, blog gönderinizi arama motorlarına daha görünür ve insanlar için daha okunabilir bir URL haline getirmenin bir yoludur. Çalışmanızı daha keşfedilebilir hale getirmek ve insanların benzer bir şey aradıklarında çalışmanızı bulmalarına yardımcı olmak için bir yöntemdir.'
};