// Notifications & flashnews
export default {
  'flashnews.create': 'Yeni bir flaş haber oluşturun',
  'flashnews.startsAt': 'Bu mesajı şuradan itibaren göstermeye başla',
  'flashnews.endsAt': 'Bu mesajı şuradan itibaren göstermeyi durdur',
  'flashnews.newLanguage': 'Eklenecek yeni dil seç',
  'flashnews.onlyDisplayOn': 'Haberler sadece aşağıda seçilen dillerde gösterilecek (eğer herhangi bir dil seçili ise), diğer dillerde varsayılan dilde bile haber gösterilmeyecek.',
  'notifications.menu.all': 'Tüm bildirimler',
  'notifications.menu.following': 'Takip ettiğim',
  'notifications.menu.workshop': 'Atölye',
  'notifications.menu.news': 'Haberler ve güncellemeler',
  'notifications.menu.markUnread': 'Okunmamış olarak işaretle',
  'notifications.menu.markRead': 'Okundu olarak işaretle',
  'notifications.menu.delete': 'Bildirimi sil',
  // Notification messages
  'notification.workshopStoryStatus.toHiatus': 'Hikayeniz {storyName} hareketsizlik nedeniyle otomatik olarak ara verildi.',
  'notification.workshopStoryStatus.toCancelled': 'Hikayeniz {storyName} bir yıllık hareketsizlikten sonra otomatik olarak iptal edildi.',
  'notification.followingStoryStatus.toHiatus': '{storyName} ara verdi.',
  'notification.followingStoryStatus.toCancelled': '{storyName} iptal edildi.',
  'notification.followingNewChapter.new': '{storyName} adlı hikayede yeni bir bölüm yayınlandı!',
  'notification.workshopStory.newComment': '{storyName}hakkında yorum yaptı.',
  // Before this text will be the username of the user
  'notification.friendRequest': 'size bir arkadaşlık isteği gönderdi.',
  // Before this text will be the username of the user
  // Story notification messages - In-app notifications
  'notification.story.newComment.subject': '"{storyTitle}" hakkında yeni yorum',
  'notification.story.newComment.body': '{commenterName} hikayenize yorum yaptı: "{commentText}"',
  'notification.story.betaComment.subject': '"{storyTitle}" hakkında yeni beta geri bildirimi',
  'notification.story.betaComment.body': '{commenterName} beta geri bildirimi sağladı: "{commentText}"',
  'notification.story.collaboratorAccepted.subject': 'Yeni {role} katıldı "{storyTitle}"',
  'notification.story.collaboratorAccepted.body': '{collaboratorName} {role}olmak için davetinizi kabul etti',
  'notification.story.statusChange.subject': '"{storyTitle}" için durum güncellemesi',
  'notification.story.statusChange.body': 'Hikaye durumu {oldStatus} \'dan {newStatus}olarak değiştirildi',
  'notification.story.completed.subject': '"{storyTitle}" tamamlandı!',
  'notification.story.completed.body': '{authorName} "{storyTitle}" adresini tamamladı. Okuduğunuz için teşekkürler!',
  'notification.story.milestone.subject': 'Kilometre taşına ulaşıldı: {milestone} "{storyTitle}" üzerinde!',
  'notification.story.milestone.body': '"{chapterTitle}" bölümünüz {count} {milestone}adresine ulaştı!',
  'notification.story.betaRevision.subject': 'Yeni beta revizyonu: "{chapterTitle}"',
  'notification.story.betaRevision.body': '{authorName} "{chapterTitle}"un yeni bir beta revizyonunu incelemeye sundu',
  'notification.story.authorReply.subject': '{authorName} geri bildiriminize yanıt verdi',
  'notification.story.authorReply.body': '{authorName} "{storyTitle}" hakkındaki beta geri bildiriminize yanıt verdi: "{commentText}"',
  'notification.story.newChapterForTranslators.subject': 'Çeviri için yeni içerik mevcut: "{chapterTitle}"',
  'notification.story.newBetaForTranslators.body': '"{chapterTitle}"\'un yeni beta revizyonu çeviriye hazır',
  'notification.story.newChapterForTranslators.body': 'Yeni bölüm "{chapterTitle}" çeviri için hazır',
  'notification.story.newChapter.subject': 'Yeni bölüm: "{chapterTitle}"',
  'notification.story.newChapter.body': '{authorName} "{storyTitle}" \'un yeni bir bölümünü yayınladı: "{chapterTitle}"',
  // Universe notifications
  'notification.universe.newStory.subject': 'Evrende yeni bir hikaye: "{storyTitle}"',
  'notification.universe.newStory.body': '{authorName} takip ettiğiniz evrene yeni bir hikaye ekledi "{storyTitle}"',
  'notification.universe.collaboratorChange.subject': 'Evren işbirliği güncellemesi',
  'notification.universe.collaboratorChange.body': 'Dahil olduğunuz bir evren için işbirliği ekibi değişti',
  'notification.universe.update.subject': 'Evren güncellendi',
  'notification.universe.update.body': 'Takip ettiğiniz bir evren güncellendi',
  'notification.universe.comment.subject': 'Evren hakkında yeni yorum',
  'notification.universe.comment.body': '{commenterName} Takip ettiğiniz bir evren hakkında yorum yaptınız: "{commentText}"',
  // Blog notifications
  'notification.blog.newPost.subject': 'Yeni blog yazısı: "{postTitle}"',
  'notification.blog.newPost.body': '{authorName} takip ettiğiniz bir blogda yeni bir blog yazısı "{postTitle}" yayınladı',
  'notification.blog.comment.subject': 'Blog gönderisine yeni yorum: "{postTitle}"',
  'notification.blog.comment.body': '{commenterName} "{postTitle}" blog yazısı hakkında yorum yaptı: "{commentText}"',
  'notification.blog.update.subject': 'Blog güncellendi',
  'notification.blog.update.body': 'Takip ettiğiniz bir blog güncellendi',
  // General comment notifications
  'notification.comment.general.subject': '"{contentTitle}" hakkında yeni yorum',
  'notification.comment.general.body': '{commenterName} "{contentTitle}": "{commentText}" hakkında yorum yaptı',
  'notification.comment.reply.subject': 'Yorumunuza cevap verin',
  'notification.comment.reply.body': '{replierName} "{contentTitle}" hakkındaki yorumunuza yanıt: "{replyText}"',
  'notification.comment.like.subject': 'Yorumunuz beğenildi',
  'notification.comment.like.body': '{likerName} yorumunuzu beğendim',
  // Content-specific comment notifications
  'notification.comment.fanArt.subject': 'Hayran sanatı hakkında yeni yorum: "{contentTitle}"',
  'notification.comment.fanArt.body': '{commenterName} "{contentTitle}" hayran sanatınız hakkında yorum yaptı: "{commentText}"',
  'notification.comment.event.subject': 'Etkinlik hakkında yeni yorum: "{contentTitle}"',
  'notification.comment.event.body': '{commenterName} "{contentTitle}" etkinliği hakkında yorum yaptı: "{commentText}"',
  'notification.comment.revision.subject': 'Revizyon hakkında yeni yorum',
  'notification.comment.revision.body': '{commenterName} revizyonunuz hakkında yorum yaptı: "{commentText}"',
  'notification.comment.feedback.subject': 'Geri bildirim hakkında yeni yorum',
  'notification.comment.feedback.body': '{commenterName} geri bildirim sorununuz hakkında yorum yaptı: "{commentText}"',
  // Welcome notification
  'notification.welcome.body': 'Aramıza katıldığınız için çok heyecanlıyız.',
  'notification.welcome.cta.reader': 'Okumaya başla!',
  'notification.welcome.cta.writer': 'Yazmaya başla!',
  // Strings for extra section
  'notificationExtra.workshopStoryStatus.goToStory': 'Hikayeye Git',
  // UI strings for enhanced notifications
  'notifications.menu.community': 'Topluluk',
  'notifications.menu.reading': 'Okuma ve Kütüphane',
  'notifications.menu.system': 'Sistem',
  'notifications.empty': 'Her şey hazır! Burada yeni bir şey yok.',
  'notifications.empty.category': 'Diğer kategorileri kontrol etmeyi veya bildirim tercihlerinizi ayarlamayı deneyin.',
  'notifications.error.loadFailed': 'Bildirimler yüklenemedi: {error}',
  'notifications.loadMore': 'Daha Fazla Yükle',
  // Action button labels
  'notifications.action.viewStory': 'Hikayeyi Görüntüle',
  'notifications.action.readChapter': 'Bölüm Oku',
  'notifications.action.goToWorkshop': 'Atölyeye Git',
  'notifications.action.viewUniverse': 'Evreni Görüntüle',
  'notifications.action.viewBlog': 'Blogu Görüntüle',
  'notifications.action.readPost': 'Yazıyı Oku',
  'notifications.action.viewComments': 'Yorumları Görüntüle',
  // Category descriptions
  'notifications.category.workshop.description': 'İçerik oluşturma ve yönetme faaliyetleriniz hakkında bildirimler',
  'notifications.category.community.description': 'Sosyal etkileşimler ve topluluk katılımı hakkında bildirimler',
  'notifications.category.reading.description': 'Yeni içerik ve okuma etkinlikleri hakkında bildirimler',
  'notifications.category.system.description': 'Sistem bildirimleri ve önemli güncellemeler'
};