export default {
    'settings.biography': 'Biyografi',
    'settings.biography.placeholder': 'Profilinizde gösterilecek kendiniz hakkında biraz bilgi.',
    'settings.avatar.title': 'Avatar',
    'settings.avatar.own': 'Avatarınız',
    'settings.avatar.upload': 'Resim seç',
    'settings.email': 'E-postalar',
    'settings.email.msg': 'Hesabınıza bağlı e-postalar',
    'settings.email.verified.false': 'Doğrulanmadı, doğrulama e-postasını yeniden göndermek için tıklayın.',
    'settings.email.verified.true': 'Doğrulanmış e-posta',
    'settings.email.add': 'E-posta ekle',
    'settings.languages.title': 'Dil ayarları',
    'settings.languages.notice': 'İngilizce ve Çekçe şu anda yalnızca resmi olarak desteklenen dillerdir. Diğer diller, harika gönüllüler ve yapay zeka çevirisi sayesinde mevcuttur, ancak hala eksik ve hatalı olabilirler.',
    'settings.languages.join': 'Bize yardımcı olmak isterseniz, Literary Universe\'yi de çevirebilirsiniz.',
    'settings.name.title': 'Gerçek ad',
    'settings.name.given': 'Verilen ad',
    'settings.name.family': 'Soyad',
    'settings.username.change': 'Kullanıcı adını değiştir',
    'settings.username.label': 'Kullanıcı adı',
    'settings.password.title': 'Şifre değiştir',
    'settings.password.current': 'Mevcut şifre',
    'settings.password.new': 'Yeni şifre',
    'settings.password.repeat': 'Yeni şifrenizi tekrarlayın',
    'settings.password.nomatch': 'Yeni şifre eşleşmiyor!',
    'settings.password.reset': 'Şifrenizi sıfırlayın',
    'settings.password.resetSend': 'Şifrenizi sıfırlamanız için talimatlar içeren bir e-posta gönderildi!',
    'settings.socialConnectTitle': 'Diğer hizmetlerden hesaplarınıza bağlanın',
    'settings.socialDisconnect': 'Bağlantıyı kes',
    'settings.socialConnect': 'Bağlan',
    'settings.loginWith': '{service}ile giriş yapın',
    'settings.connectTo': '{service}ile bağlanın',
    'settings.export.title': 'Verileri Dışa Aktar',
    'settings.export.explain': 'Bu, veritabanımızda depolanan tüm verilerinizi json formatında almanızı sağlar.',
    'settings.export.submit': 'Verileri dışa aktar',
    'settings.delete.title': 'Hesabı Sil',
    'settings.delete.warning': `UYARI: Hesabınızı sildiğinizde bu hesaba erişiminizi kaybedersiniz ve
    hesabınızı geri almanın hiçbir yolu yoktur. Bunun yayınlanmış çalışmalarınızı,
    yorumlarınızı vb. otomatik olarak silmeyebileceğini unutmayın. Ayrıntılar için lütfen Hizmet Şartları'na bakın.`,
    'settings.delete.confirm': 'Sadece emin olmak için. Hesabınızı silmek istediğinizden emin misiniz?',
    'settings.delete.cancel': 'Hesabımı silmek istemiyorum',
    'settings.delete.submit': 'Hesabımı sil',
    'settings.legal.title': 'Kullanıcı onay anlaşmaları',
    'settings.legal.explained': 'Burada çeşitli yasal belgelere olan onayınızı yönetebilirsiniz.',
    'settings.legal.analytics.title': 'Analitik ve izleme',
    'settings.legal.analytics.description': 'Literary Universe\'de kullanılan analiz ve izleme hizmetlerini kontrol edebilirsiniz. Bu bölüm, biz ekledikçe tüm hizmetleri listeleyecektir.',
    'settings.legal.analytics.ostrio': 'Ostrio Analytics izlemesini devre dışı bırakmak için devre dışı bırakma sayfasını ziyaret edin:',
    'settings.legal.analytics.ostrioOptOut': 'Ostrio Analytics devre dışı bırakmayı yönetme',
    'settings.legal.analytics.future': 'Google Analytics veya Seznam gibi ek sağlayıcıları, etkinleştirildiklerinde buraya ekleyeceğiz.',
    'settings.name.private': 'İsim gizli olacak',
    'settings.emailSubscriptions.title': 'E-posta bildirim ayarları',
    'settings.emailSubscriptions.explain': 'Bize hangi e-posta bildirimlerini almak istediğinizi seçin.',
    'settings.emailSubscriptions.newsletter': 'Arada bir bülten',
    'settings.profile': 'Profil ayarları',
    'settings.profile.basic': 'Temel Profil Bilgileri',
    'settings.profile.identity': 'Kimlik',
    'settings.profile.about': 'Senin Hakkında',
    'settings.profile.basic.description': 'Diğer kullanıcılar tarafından görülebilecek temel profil bilgilerinizi yönetin.',
    'settings.interests.title': 'İlgi Alanlarınız',
    'settings.account': 'Hesap ayarları',
    'settings.legal.export.download': 'Verilerinizi İndirin',
    'settings.legal.export.gathering': 'Verileriniz toplanıyor... Bu biraz zaman alabilir.',
    'settings.gender.title': 'Cinsiyetiniz',
    'settings.gender.usage': 'Bu bilgi gizli kalacaktır. Bu verileri platform analitiği ve yaratıcıların hikayelerini okuduğunuzda anonimleştirilmiş analitikler için kullanıyoruz.',
    'settings.age.title': 'Yaşınız',
    'settings.age.explicit': 'Show explicit content (age rating 21+)',
    'settings.age.birthday': 'Doğum tarihi',
    'settings.age.usage': 'Bu bilgi gizli kalacaktır. Yasal olarak yaşınızı sormakla yükümlüyüz. Bu verileri platform analitiği, derecelendirmelere dayalı içerik gösterimi ve yaratıcıların hikayelerini okuduğunuzda anonimleştirilmiş analitikler için kullanıyoruz.',
    'settings.country.title': 'Ülkeniz',
    'settings.country.usage': 'Hükümet soruşturmalarına yanıt vermek için yasal olarak ülkenizi sormakla yükümlüyüz. Bu verileri platform analitiği ve yaratıcıların hikayelerini okuduğunuzda anonimleştirilmiş analitikler için kullanıyoruz. İsterseniz bu bilgiyi profilinizde görüntüleyebilirsiniz.',
    'settings.country.public': 'Ülkenizi herkese açık olarak göster',
    'settings.country.select': 'Ülkenizi seçin',
    'settings.emailSubscriptions.newsletterTech': 'Geliştiricilerimizden gelen zaman zaman bülten',
    'settings.emailSubscriptions.newsletterFeatures': 'Yeni özellikler hakkında bilgi',
    'settings.emailNotifications.title': 'Bildirimler',
    'settings.emailNotifications.pm': 'Yeni mesajlar',
    'settings.emailNotifications.newChapters': 'Takip ettiğiniz hikayelerden yeni bölümler',
    'settings.emailNotifications.newStories': 'Evrenlerde veya takip ettiğiniz yazarlardan yeni hikayeler',
    'settings.emailNotifications.newUniverses': 'Takip ettiğiniz yazarlardan yeni evrenler',
    'settings.resetPasswordEmailSend': 'Şifrenizi sıfırlamanız için size e-posta ile talimatlar gönderdik.',
    'settings.theme.title': 'Site temaları',
    'settings.theme.label': 'Site teması',
    'settings.theme.light': 'Açık',
    'settings.theme.dark': 'Koyu',
    'settings.links.title': 'Diğer web sitelerinize bağlantı',
    'settings.links.description': 'Bu bağlantılar profil sayfanızda görüntülenecektir.',
    'settings.links.website': 'Kişisel web siteniz',
    'settings.links.social': 'Diğer web siteleri',
    'settings.links.select': 'Eklenecek web sitesini seçin',
    // 2FA
    'settings.2fa.title': 'İki faktörlü kimlik doğrulama',
    'settings.2fa.explained': 'İki faktörlü kimlik doğrulama, giriş sırasında ek bir kimlik doğrulama adımı ekleyerek hesabınız için ek bir güvenlik katmanı sağlar. Bu, ilk giriş adımınızın tehlikeye düşmesi durumunda kötü niyetli kişilerin hesabınıza erişmesini engeller.',
    'settings.2fa.otpTitle': 'OTP',
    'settings.2fa.otpExplained': 'OTP koduyla iki faktörlü kimlik doğrulama, kimlik doğrulayıcı uygulamalar (Authy, Google/Microsoft Authenticator vb.) aracılığıyla bir kez kullanılan şifre oluşturur ve bunu girişte kullanırsınız.',
    'settings.2fa.otpModalAria': '2FA OTP yöntemi',
    'settings.2fa.otpAdd': '2FA OTP ekle',
    'settings.2fa.confirmCode': 'Kimlik doğrulama uygulamasında görünen kod',
    'settings.2fa.svgAlt': 'Kimlik doğrulama uygulaması için QR kodu',
    'settings.2fa.codeHeading': 'QR kodunu tarayamıyorsanız, aşağıdaki kodu manuel olarak girebilirsiniz:',
    'settings.2fa.instructionsTitle': 'Talimatlar',
    'settings.2fa.instructions1': 'Seçtiğiniz kimlik doğrulayıcı uygulamasını (Authy, Google/Microsoft Authenticator, FreeOTP vb.) indirin ve açın.',
    'settings.2fa.instructions2': '"Hesap ekle" seçeneğini seçin (görünen bir "+" simgesi olabilir veya bir menüde gizlenebilir).',
    'settings.2fa.instructions3': 'Ekranınızda sunulan QR kodunu tarayın veya mümkün değilse aşağıdaki kodu girin.',
    'settings.2fa.instructions4': 'Ekranda görünen 6 rakamı buraya girerek işlemi tamamlayın.',
    'settings.2fa.saved': 'İki faktörlü kimlik doğrulama başarıyla oluşturuldu!',
    'settings.2fa.disableOTP': 'OTP iki faktörlü kimlik doğrulamayı devre dışı bırak',
    // API Keys
    'settings.apiKeys.title': 'API Anahtarları',
    'settings.apiKeys.description': 'API anahtarları, üçüncü taraf uygulamaların sizin adınıza Literary Universe verilerinize erişmesini sağlar. Bunlara parola gibi davranın ve asla paylaşmayın.',
    'settings.apiKeys.noKeys': 'Henüz herhangi bir API anahtarınız yok.',
    'settings.apiKeys.created': 'Created {date, date, medium} at {date, time, short}',
    'settings.apiKeys.lastUsed': 'Son kullanılan {time}',
    'settings.apiKeys.neverUsed': 'Hiç kullanılmadı',
    'settings.apiKeys.expires': 'Süresi doluyor {date, date, medium}',
    'settings.apiKeys.name': 'Anahtar İsim',
    'settings.apiKeys.name.placeholder': 'örneğin, Obsidian Eklentisi',
    'settings.apiKeys.permissions': 'İzinler',
    'settings.apiKeys.generate': 'API Anahtarı Oluştur',
    'settings.apiKeys.generated.title': 'API Anahtarı Oluşturuldu',
    'settings.apiKeys.generated.warning': 'Bu anahtarı hemen kaydedin! Bir daha göremeyeceksiniz.',
    'settings.apiKeys.copyToClipboard': 'Panoya Kopyala',
    'settings.apiKeys.expiration': 'Son kullanma tarihi',
    'settings.apiKeys.expiration.duration': `{months, plural,
    =1 {1 ay}
    =3 {3 ay}
    =6 {6 ay}
    =12 {1 yıl (önerilir)}
    =24 {2 yıl}
    other {{months} ay}
  }`,
    'settings.apiKeys.revoke.confirm': 'Bu API anahtarını iptal etmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'settings.apiKeys.delete.confirm': 'Bu API anahtarını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'settings.apiKeys.error.nameRequired': 'Lütfen API anahtarınız için bir ad girin',
    'settings.apiKeys.error.scopesRequired': 'Lütfen en az bir izin seçin',
    'settings.apiKeys.security.title': 'Güvenlik Bildirimi',
    'settings.apiKeys.security.1': 'API anahtarınızı asla kimseyle paylaşmayın',
    'settings.apiKeys.security.2': 'Şifre gibi davranın',
    'settings.apiKeys.security.3': 'İstediğiniz zaman erişimi iptal edebilirsiniz',
    'settings.apiKeys.security.4': 'Anahtar yalnızca bir kez gösterilecektir',
    'settings.apiKeys.scope.story.read': 'Hikayeleri okuyun',
    'settings.apiKeys.scope.story.read.desc': 'Hikaye başlıklarınıza, içeriğinize ve bölümlerinize erişin',
    'settings.apiKeys.scope.story.write': 'Hikaye oluşturma ve düzenleme',
    'settings.apiKeys.scope.story.write.desc': 'Yeni hikayeler oluşturun ve mevcut hikayeleri güncelleyin',
    'settings.apiKeys.scope.universe.read': 'Evrenleri okuyun',
    'settings.apiKeys.scope.universe.read.desc': 'Ansiklopedi girişlerinize ve dünya oluşturma verilerinize erişin',
    'settings.apiKeys.scope.universe.write': 'Evrenler oluşturma ve düzenleme',
    'settings.apiKeys.scope.universe.write.desc': 'Ansiklopedi girdileri oluşturma ve güncelleme',
    'settings.apiKeys.scope.scratchpad.read': 'Notları okuyun',
    'settings.apiKeys.scope.scratchpad.read.desc': 'Özel notlarınıza ve karalama defterinize erişin',
    'settings.apiKeys.scope.scratchpad.write': 'Not oluşturma ve düzenleme',
    'settings.apiKeys.scope.scratchpad.write.desc': 'Notlarınızı oluşturun ve güncelleyin',
    'settings.apiKeys.scope.blog.read': 'Blog yazılarını okuyun',
    'settings.apiKeys.scope.blog.read.desc': 'Blog yazılarınıza ve taslaklarınıza erişin',
    'settings.apiKeys.scope.blog.write': 'Blog gönderileri oluşturma ve düzenleme',
    'settings.apiKeys.scope.blog.write.desc': 'Blog gönderileri oluşturma ve güncelleme',
    'settings.apiKeys.scope.user.read': 'Profili okuyun',
    'settings.apiKeys.scope.user.read.desc': 'Kullanıcı adınıza, avatarınıza ve genel profilinize erişin',
    'settings.apiKeys.scope.library.read': 'Kütüphane okuyun',
    'settings.apiKeys.scope.library.read.desc': 'Okuma listelerinize ve kayıtlı hikayelerinize erişin',
    // Web3
    'settings.web3.legend': 'Web3 cüzdan bağlantısı',
    'settings.web3.explained': 'Web3 kripto cüzdanınızı Edebiyat Evreni hesabınıza bağlayabilirsiniz. Bağlandıktan sonra cüzdanınızla giriş yapabilir ve Web3 teklifimizi genişlettikçe gelecekte daha fazla şey yapabilirsiniz.',
    'settings.web3.connect': 'Cüzdanınızı bağlayın',
    'settings.web3.address': 'Bağlı adres: {address}',
    'settings.web3.verify': 'Adresinizi imzalayın',
    'settings.web3.verify.explained': 'Bu adresin size ait olduğunu doğrulamak için cüzdanınızın sahipliğini sağlamak için bir mesaj imzalamanızı isteyeceğiz.',
    'settings.web3.verified': 'Doğrulandı',
    'settings.web3.verificationMessage': 'Edebiyat Evreni için kullanıcı doğrulanıyor {username} . Kod: {code}',
    'settings.web3.unlink': 'Cüzdanı kaldır',
    'settings.web3.linkingMessage': 'Lütfen cüzdanınızı Edebiyat Evreni\'ne bağlamak istediğinizi onaylayın. Kod: {code}',
    'settings.web3.linkError': 'Bu adres zaten veritabanımızda listelenmiş ve atanamaz!',
    // Reader settings
    'settings.reader.title': 'Okuyucu ayarları',
    'settings.reader.darkMode': 'Her zaman karanlık modda göster',
    'settings.reader.asideView': 'Sihirli yan paneli göster',
    'settings.reader.textSize': 'Metni daha büyük yazı tipinde göster',
    'settings.reader.storyRecommendations': 'Hikaye Önerileri',
    'settings.reader.storyRecommendationsHelp': 'Kişiselleştirilmiş hikaye önerilerini etkinleştirin.',
    // AI settings
    'settings.ai.title': 'Yapay zeka ayarları',
    'settings.ai.explained': 'Literary Universe\'te yapay zeka özelliklerinin sizin için nasıl çalışacağını yapılandırın.',
    // Accessibility
    'settings.accessibility.title': 'Okuyucu erişilebilirliği',
    'settings.accessibility.openDyslexic': 'OpenDyslexic yazı tipi kullan',
    'settings.accessibility.paragraphStripes': 'Paragraf arka planında alternatif renk kullan',
    'settings.accessibility.paragraphHighlighting': 'Üzerine geldiğiniz geçerli paragrafı vurgula',
    'settings.accessibility.ruler': 'Fareye bir cetvel ekle',
    // Story Recommendations
    'settings.storyRecommendations.title': 'Hikaye önerileri',
    'settings.storyRecommendations.explained': 'Okuma tercihlerinize ve geçmişinize göre uygulama genelinde kişiselleştirilmiş hikaye önerilerini etkinleştirin.',
    'settings.tab.legal': 'Hukuki belgeler',
    'settings.tab.exportDelete': 'Verileri dışa aktar ve hesabı sil',
    'settings.languages.uiLanguage': 'Arayüz dili',
    'settings.languages.readingLanguage': 'Okuma dili',
    'settings.languages.readingLanguageExplained': 'Hikayelere bakarken, aksini belirtmediğiniz sürece size hikayeleri ve çevirilerini bu dilde sunacağız.',
    'settings.biography.help': 'Başkalarına kendinizden bahsedin',
    'settings.username.help': 'Platformdaki benzersiz kullanıcı adınız',
    'settings.interests.tags.custom.help': 'Virgülle ayrılmış etiket listesini girin',
    'settings.interests.tags.placeholder': 'Etiketler ekle',
    'settings.interests.avoidGenres.help': 'Önerilerde görmek istemediğiniz türleri seçin.',
    'settings.interests.avoidGenres': 'Kaçınılması gereken türler',
    'settings.notifications': 'Bildirimler & Haber Bültenleri'
};