export default {
    'workshop.title': 'Çalışmanız',
    'workshop.noneassigned': 'Henüz size atanmış bir çalışma yok.',
    'workshop.notavailable': 'Bu özellik henüz kullanılabilir değil.',
    'workshop.none': `Şu anda hiçbir {type, select,
      universe {evreniniz}
      story {hikayeniz}
      fanfiction {hayran kurgunuz}
      other {}
    }yok. Şimdi bir tane oluşturun!`,
    'workshop.collab': 'İşbirlikli çalışma',
    'workshop.betareadings': 'Beta okumaları',
    'workshop.translations': 'Çeviriler',
    'workshop.createnew': 'Yeni oluştur...',
    'workshop.story.standalone': 'Bağımsız hikaye',
    'workshop.story.standalone.desc': 'Bu bağımsız bir hikayedir.',
    'workshop.controlpanel': '{name} kontrol paneli',
    'workshop.universe.page': 'Evren sayfası',
    'workshop.fictionaltime': 'Kurgusal zaman',
    'workshop.dashboard.name': '{name} panosu',
    'workshop.stories.in': '{universe}hikayeleri',
    'workshop.universe.nostories': 'Bu evrende hiç hikaye yok.',
    'workshop.story.chapter.add': 'Yeni bölüm',
    'workshop.universe.new': 'Yeni bir evren oluştur',
    'workshop.universe.publish': 'Evreni yayınla',
    'workshop.universe.publishing.notice': 'Evreni yayınlamazsanız, evrene bağlı ilk hikaye yayınlandığında otomatik olarak yayınlanır.',
    'workshop.universe.settings': '{universe} evren ayarları',
    'workshop.universe.publishedOn': 'Bu evren {date, date, long} {date, time, short}üzerinde yayınlanmıştır.',
    'workshop.work.deletion.contactUs': 'Yardıma ihtiyacınız varsa, <contact>bizimle iletişime</contact> geçin.',
    'workshop.work.delete.restrictions': `Bu {type, select,
    universe {evrenini yalnızca yayınlanmış hikayesi yoksa ve}
    story {hikayesini yalnızca}
    other {çalışması yalnızca}} bir aydan daha kısa bir süre önce yayınlanmışsa silebilirsiniz. Bundan sonra yardıma mı ihtiyacınız var? <contact>Bize ulaşın</contact>.`,
    'workshop.work.delete.notAllowed': `Bu {type, select,
    universe {evren}
    story {hikaye}
    other {iş}
  } artık self servis aracılığıyla silinemez. Kaldırılması gerekiyorsa, <contact>bizimle iletişime</contact> geçin ve güvenli bir şekilde kaldırmak için sizinle birlikte çalışacağız.`,
    'workshop.work.delete.notAllowed.plain': `Bu {type, select,
    universe {universe}
    story {story}
    other {work}
  } artık self servis aracılığıyla silinemez. Kaldırılması gerekiyorsa, deletions@literaryuniverse.com adresinden bizimle iletişime geçin; güvenli bir şekilde kaldırmak için sizinle birlikte çalışacağız.`,
    'workshop.work.danger.delete.desc': `Bunu kalıcı olarak siler {type, select,
    universe {evren ve bağlantılı atölye verileri}
    story {tüm bölümleri, istatistikleri ve atölye ilişkilerini içeren hikaye}
    other {çalışma ve ilgili veriler}
  }.`,
    'workshop.work.makePrivate.impact': `Bunu {type, select,
    universe {universe}
    story {story}
    other {work}
  } yapmak, onu keşif ve aramadan kaldırır. Kütüphanelerinde zaten bulunan kişiler erişmeye devam eder. Yeni kullanıcılar artık kütüphanelerine ekleyemez{type, select,
    story { veya siz onlara hediye etmedikçe satın alamaz}
    other {}
  }.`,
    'workshop.work.private.notice': `Bu {type, select,
    universe {evren}
    story {hikaye}
    other {çalışma}
  } şu anda özeldir. Mevcut kütüphane sahiplerinin hala erişimi vardır. Yeni kullanıcılar bunu kütüphanelerine ekleyemez{type, select,
    story { veya satın alamaz}
    other {}
  }.`,
    'workshop.work.makePrivate.button': `Make {type, select,
    universe {Universe}
    story {Story}
    other {Work}
  } Private`,
    'workshop.work.makePrivate.modalAria': `Bir {type, select,
    universe {evren}
    story {hikaye}
    other {iş}
  } özel yapmak için onay modu`,
    'workshop.work.makePrivate.warning': `Bunu {type, select,
    universe {evren}
    story {hikaye}
    other {iş}
  } özel yapmak, onu genel keşif ve aramadan kaldıracaktır.`,
    'workshop.work.makePublic.button': `Make {type, select,
    universe {Universe}
    story {Story}
    other {Work}
  } Public`,
    'workshop.work.makePublic.modalAria': `Bir {type, select,
    universe {evren}
    story {hikaye}
    other {iş}
  } Kamu yapmak için onay modu`,
    'workshop.work.makePublic.warning': `Bu {type, select,
    universe {evreni}
    story {hikayeyi}
    other {çalışmayı}
  } herkese açık hale getirmek, onu yeniden keşfedilebilir kılacak ve yeni kullanıcıların kütüphanelerine{type, select,
    story { eklemelerine veya satın almalarına}
    other {}
  } olanak sağlayacaktır.`,
    'workshop.universe.dangerZone': 'Tehlikeli bölge',
    'workshop.universe.dangerZone.desc': 'Bu evreni yalnızca yayınlanmış hikayesi olmadığında ve bir aydan daha kısa bir süre önce yayınlandığında silebilirsiniz. Bu sınırlama süresinden sonra silmeniz gerekiyorsa, lütfen bizimle iletişime geçin.',
    'workshop.universe.delete.modalAria': 'Bir evreni silmek için onay modalı',
    'workshop.universe.delete.warning': '"{title}" adresini silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'workshop.universe.delete.button': 'Evreni Sil',
    'workshop.universe.description': 'Evren açıklaması',
    'workshop.settings.title': 'Başlık',
    'workshop.description': 'Açıklama',
    'workshop.language.primary': 'Birincil dil',
    'workshop.publication.options': 'Yayın seçenekleri',
    'workshop.rating': 'Genel derecelendirme',
    'workshop.universe.rating.desc': 'Bu derecelendirmeden yüksek hikayeler ve hayran kurguları, anonim kullanıcılardan ve uygun yaşta olmayan kullanıcılardan evren sayfası listesinde gizlenecektir.',
    'workshop.universe.license': 'Evren lisansı',
    'workshop.universe.genre.pick': 'Evren için tür seçin',
    'workshop.story.genre.pick': 'Hikaye için türler seçin',
    'workshop.cover': 'Kapak',
    'workshop.nothingtosee': 'Burada görülecek bir şey yok...',
    'workshop.story.cannon': 'Kanon hikaye',
    'workshop.story.cannon.desc': 'Bu hikaye {universe} evrende kanoniktir.',
    'workshop.story.cannon.desc.create': 'Bu hikaye, {universe} evrende bir kanon hikaye olarak oluşturulacak.',
    'workshop.story.fanfiction.search': 'Evrenin adını yazın (kütüphanenizde olması gerekiyor). Ardından öneriler arasından seçin.',
    'workshop.story.error.nogenres': 'En az bir tür seçmelisiniz.',
    'workshop.story.error.toomanygenres': 'Bir hikayede sadece iki tür izin verilir.',
    'workshop.story.error.fanfiction.selectuniverse': 'Hayran kurgusu için orijinal evren seçmelisiniz!',
    'workshop.story.error.tags.toomany': 'Bir hikayede en fazla 10 etiket olabilir.',
    'workshop.thema.primary': 'Tema Birincil Sınıflandırma',
    'workshop.thema.secondary': 'Thema İkincil Sınıflandırmalar',
    'workshop.thema.secondary.max': 'En fazla {max} ikincil sınıflandırma ekleyebilirsiniz.',
    'workshop.thema.selectedCode': 'Kod: {code}',
    'workshop.thema.searchPlaceholder': 'İsme göre arama, örneğin "Bilim kurgu"',
    'workshop.thema.quickRef': '📖 Thema Hızlı Referans',
    'workshop.story.new': 'Yeni bir hikaye oluştur',
    'workshop.story.publishing.notice': 'İlk bölümü yayınladığınızda hikaye otomatik olarak yayınlanacaktır.',
    'workshop.story.published.congratulations.title': 'Tebrikler! Hikayeniz yayınlandı',
    'workshop.story.published.congratulations.heading': 'Tebrikler! Hikayeniz yayınlandı',
    'workshop.story.published.congratulations.description': 'Yazma yolculuğunuz devam ediyor. Hikayeniz artık okuyucular tarafından keşfedilmeye ve keyifle okunmaya hazır.',
    'workshop.story.published.congratulations.publicStoryBtn': 'Hikaye sayfasına git',
    'workshop.story.published.congratulations.imageAlt': 'Yayınlanan hikaye için kutlama illüstrasyonu',
    'workshop.settings.edit': 'Ayarları düzenle',
    'workshop.story.publishedOn': 'Bu hikaye {date, date, long} {date, time, short}üzerinde yayınlandı.',
    'workshop.story.settings': 'Hikaye ayarları',
    'workshop.story.monetizationTitle': 'Hikayeden para kazanma',
    'workshop.settings.basic': 'Temel ayarlar',
    'workshop.settings.genres': 'Türler (en fazla 2)',
    'workshop.story.license': 'Hikaye lisansı',
    'workshop.story.settings.universe': 'Evren ayarları',
    'workshop.story.dangerZone': 'Tehlikeli bölge',
    'workshop.story.dangerZone.desc': 'Bu eylemler hikayenizin evrenler arasında nasıl düzenlendiğini etkiler. Dikkatli ilerleyin.',
    'workshop.story.universe.assign.missing': 'Devam etmek için lütfen bir evren seçin.',
    'workshop.story.universe.assignTitle': 'Evren oluşturma veya atama',
    'workshop.story.universe.assign.desc': 'Bu hikayeyi mevcut bir evrene ekleyin veya hikaye ayrıntılarını kullanarak yepyeni bir evren oluşturun.',
    'workshop.story.universe.assign.mode': 'Evren seçeneği',
    'workshop.story.universe.assign.existing': 'Mevcut bir evrene atama',
    'workshop.story.universe.assign.create': 'Bu hikayeden yeni bir evren yaratın',
    'workshop.story.universe.assign.loading': 'Evrenlerinizi yüklüyoruz...',
    'workshop.story.universe.assign.select': 'Evren seçin',
    'workshop.story.universe.assign.placeholder': 'Bir evren seçin',
    'workshop.story.universe.assign.none': 'Henüz herhangi bir evreniniz yok. Devam etmek için yeni bir tane oluşturun.',
    'workshop.story.universe.assign.publishNote': 'Bu hikaye zaten yayınlandı, dolayısıyla yeni evren de yayınlanacak.',
    'workshop.story.universe.assign.createBtn': 'Evren yaratın',
    'workshop.story.universe.assign.trigger': 'Evren oluşturma veya atama',
    'workshop.story.universe.standalone.title': 'Hikayeyi bağımsız hale getirin',
    'workshop.story.universe.standalone.heading': 'Bu hikayeyi kendi evreninin dışına mı taşıyalım?',
    'workshop.story.universe.standalone.desc': 'Bu hikâye evrenden çıkarılacak ve bağımsız bir hikâye olarak listelenecektir.',
    'workshop.story.universe.standalone.current': 'Şu anki evren: {title}',
    'workshop.story.universe.standalone.warning1': 'Evrende gezinen okuyucular artık bu hikayenin orada listelendiğini görmeyecekler.',
    'workshop.story.universe.standalone.warning2': 'Bu hikayenin evren versiyonuna işaret eden mevcut bağlantılar çalışmayabilir.',
    'workshop.story.universe.standalone.warning3': 'Hikayeyi daha sonra hikaye ayarlarından tekrar bir evrene ekleyebilirsiniz.',
    'workshop.story.universe.standalone.trigger': 'Hikayeyi bağımsız hale getirin',
    'workshop.settings.tags': 'Etiketler',
    'workshop.revision': 'Düzeltme',
    'workshop.revisions.title': '{story}: {chapter} Düzeltmeler',
    'workshop.revisions.current': 'Mevcut taslak',
    'workshop.revisions.new.beta': 'Taslaktan yeni bir düzeltme oluştur.',
    'workshop.revisions.new.public': 'Taslaktan yeni bir genel düzeltme oluştur.',
    'workshop.revisions.toeditor': 'Editöre git',
    'workshop.revisions.comments': 'Düzeltme yorumları',
    'workshop.revisions.comments.title': '{story}: {chapter} - Düzeltme {revision} - Yorumlar',
    'workshop.revisions.comments.list': `{revision}: {language}, {publication, select,
      beta {Beta okuyucular için}
      readers {Genel}
      other {}
    } {datetime, date, medium} {datetime, time, short}`,
    'workshop.revisions.comments.norevision': 'Önce bir düzeltme oluşturmanız gerekiyor.',
    'workshop.revisions.comments.select': 'Revizyon seçin',
    'workshop.collaborators.noresults': 'Sonuç bulunamadı',
    'workshop.collaborators.add.beta': 'Beta okuyucu ekle',
    'workshop.collaborators.add.collaborator': 'Ortak ekleyin',
    'workshop.collaborators.add.translator': 'Çevirmen ekleyin',
    'workshop.collaborators.language.add': 'Yeni bir çeviri oluşturun',
    'workshop.translations.stories': 'Çeviriler - hikayeler',
    'workshop.translations.universes': 'Çeviriler - evrenler',
    'workshop.revisions.beta.none': 'Şu anda revizyon yok.',
    'reader.asidetoggle': 'Yan bilgiyi aç/kapat',
    'workshop.translation.original': 'Orijinal:',
    'workshop.translation.original.title': 'Orijinal başlık:',
    'workshop.translation.original.description': 'Orijinal açıklama:',
    'workshop.translation.original.cover': 'Orijinal kapak',
    'workshop.translation.original.tags': 'Orijinal etiketler',
    'workshop.cover.alt': 'kapak resmi',
    'workshop.translation.updatedOrig': 'Orijinalin son güncellenme tarihi: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.updatedTrs': 'Çevirinin son güncellenme tarihi: {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionOrig': 'Orijinalin son revizyonu {revision, number}, {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.translation.revisionTrs': 'Çevirinin son revizyonu {revision, number}, {updatedAt, date, long} {updatedAt, time, medium}',
    'workshop.monetization.minPriceNotice': 'Fiyatlar kaydedilmeden veya senkronize edilmeden önce lisansa özgü minimum değerlere göre doğrulanır.',
    'workshop.monetization.storyPrices': 'Hikaye fiyatları',
    'workshop.monetization.minPrice': 'Minimum: {price}',
    'workshop.monetization.revenueSplit': 'Gelir dağılımı',
    'workshop.monetization.userId': 'Katılımcı kullanıcı kimliği',
    'workshop.monetization.splitTotal': 'Toplam katılımcı dağılımı: {total}%',
    'workshop.monetization.arcPricing': 'Ark fiyatlandırması',
    'workshop.monetization.arcRange': 'Bölümler {from}-{to}',
    'workshop.monetization.arcEnabled': 'Bu yay ayrı olarak satılır',
    'workshop.monetization.saved': 'Fiyatlandırma ayarları kaydedildi.',
    'workshop.monetization.synced': 'Stripe ürünleri ve fiyatları senkronize edildi.',
    'workshop.monetization.syncStripe': 'Stripe ile senkronize edin',
    'workshop.collaborators.premium': `Daha fazla {type, select,
    collaborator {işbirlikçi}
    beta {beta okuyucu}
    translator {çevirmen}
    other {}
  }eklemek için üyelik seviyenizi yükseltmelisiniz.`,
    'workshop.collaborators.requests.sent': 'Gönderilen istekler',
    'workshop.collaborators.requests.invite': `Aşağıdakiler için {role, select,
    beta {beta okuyucu}
    translator {çevirmen}
    collaborator {işbirlikçi}
    other {}
  } olmanız için davet edildiniz:`,
    'workshop.collaborators.requests.dashboard': `{count, plural,
    zero {eser yok}
    one {bir edebi eser}
    other {# edebi eser}
  }üzerinde işbirliği yapmaya davet edildiniz.`,
    'workshop.collaborators.language.added': 'Dil eklendi',
    'workshop.story.noChaptersFound': 'Bölüm bulunamadı.',
    'workshop.outliner.title': 'Hikaye Taslağı - {storyTitle}',
    'workshop.outliner.addScene': 'Yeni sahne sütun adı',
    'workshop.outliner.addSceneAction': 'Sahne ekle',
    'workshop.outliner.sceneName': 'Sahne adı…',
    'workshop.outliner.hideArchived': 'Arşivlenenleri gizle',
    'workshop.outliner.showArchived': 'Arşivlenenleri göster',
    'workshop.outliner.newStoryline': 'Yeni hikaye adı…',
    'workshop.outliner.noChapters': 'Hikaye yapınızı planlamak için "Bölüm planla "yı kullanın veya atölyede ilk bölümünüzü yazın.',
    'workshop.outliner.noScenes': 'Henüz sahne yok',
    'workshop.outliner.storyline': 'Hikaye',
    'workshop.outliner.dragHint': 'Tıpkı bir Trello panosunda olduğu gibi, kartları herhangi bir sahne sütunu ve hikaye çizgisi arasında sürükleyin.',
    'workshop.outliner.editCard': 'Outliner kartını düzenleme',
    'workshop.outliner.cardDetailsPlaceholder': 'Bu vuruşu, sahne hedefini, temel çatışmayı ve herhangi bir notu açıklayın…',
    'workshop.outliner.written': 'Yazıldığı gibi işaretleyin',
    'workshop.outliner.emptyCard': '(boş)',
    'workshop.outliner.planChapter': 'Plan bölümü',
    'workshop.outliner.addChapterHint': 'Bir planlama bölümü oluşturun. Hikayenizde gerçek bir bölüm olduğunda, otomatik olarak burada görünecek ve bu yer tutucu değiştirilecektir.',
    'workshop.outliner.chapterTitlePlaceholder': 'Bölüm başlığı…',
    'workshop.outliner.hypothetical': 'taslak',
    'workshop.outliner.deleteChapter': 'Planlanan bölümü silin',
    'workshop.fanfic.needUniverseInLibrary': 'Orada birçok evren var. Lütfen yazmak istediğiniz evrenleri önce kütüphanenize ekleyin, böylece onları bulabiliriz.',
    'workshop.fanfic.findUniverse': 'Harika bir evren bulun!',
    'workshop.encSettings': 'Ansiklopedi ayarları',
    'workshop.collaborators.removeUser': 'Kullanıcıyı kaldır',
    'workshop.collaborators.cancelInvite': 'Daveti iptal et',
    'workshop.universe.createFirstStory': 'İlk hikayeyi oluştur',
    'workshop.storylines': 'Hikaye çizgileri',
    'workshop.scenesManager': 'Sahne Yöneticisi',
    'workshop.collaborators.addRoleForLang': '{language}için {role} adresini ekleyin',
    'workshop.beta.revisionInfo': 'Bu, {createdAt, date, long}tarihinde oluşturulan {revision, number}revizyonudur.',
    'workshop.story.notes.title': '{storyTitle}için notlarınız',
    'workshop.story.notes.desc': 'Hikaye için genel notlar.',
    'workshop.story.notes.tile': 'Genel notlar',
    'workshop.story.alternateFormats.tile': 'Alternatif formatlar',
    'workshop.story.alternateFormats.title': '{storyTitle}: Alternatif formatlar',
    'workshop.story.alternateFormats.arcs.title': 'Yaylar',
    'workshop.story.alternateFormats.arcs.add': 'Yay ekleyin',
    'workshop.story.alternateFormats.arc.defaultTitle': 'Ark {index}',
    'workshop.story.alternateFormats.arc.name': 'Ark adı',
    'workshop.story.alternateFormats.arc.from': 'Bölümden',
    'workshop.story.alternateFormats.arc.to': 'Bölüme',
    'workshop.story.alternateFormats.arc.uploads': 'Dosyalar',
    'workshop.story.alternateFormats.arc.upload.epub': 'EPUB Yükle',
    'workshop.story.alternateFormats.arc.upload.pdf': 'PDF Yükle',
    'workshop.story.alternateFormats.epub.generate': 'EPUB oluşturun',
    'workshop.story.alternateFormats.epub.openGenerated': 'Açık oluşturulmuş EPUB',
    'workshop.story.alternateFormats.epub.generatedAt': 'Generated on {generatedAt, date, medium} at {generatedAt, time, short}',
    'workshop.story.alternateFormats.epub.generationFailed': 'EPUB oluşturma başarısız oldu.',
    'workshop.story.alternateFormats.epub.saveArcBeforeGeneration': 'EPUB oluşturmayı etkinleştirmek için önce bu yayı kaydedin.',
    'workshop.story.alternateFormats.fullStory.title': 'Tam hikaye dosyası',
    'workshop.story.alternateFormats.ongoingAccess.title': 'Devam eden erişim',
    'workshop.story.alternateFormats.ongoingAccess.allAvailable': 'Şu anda mevcut olan tüm bölümler',
    'workshop.story.alternateFormats.ongoingAccess.perChapter': 'Bölüm başına (bölümler yayınlandıkça)',
    'workshop.hideOrgs': 'İçeriği kuruluşlardan gizle',
    'workshop.translation.premium': 'Çeviri eklemek için en azından Keşifçi aboneliğine sahip olmanız gerekmektedir.',
    'workshop.story.finished': 'Hikaye tamamlandı',
    'workshop.story.publishing.externalSellingNotice': 'Edebi Evren dışında satış yapıyorsanız, hikayeyi şimdi yayınlayabilirsiniz. Mağaza listelemeleriniz hikayenin altında veya burada yayınladığınız mevcut hikayenin sonunda görünecektir.',
    'workshop.shoppingExternal.kobo': 'Rakuten Kobo',
    'workshop.shoppingExternal.koboStore': 'Rakuten Kobo mağazası',
    'workshop.shoppingExternal.koboStoreInternational': 'Uluslararası vitrin',
    'workshop.sharing.publicURL': 'Halka açık sürüm',
    'workshop.fictionalTime.title': '{universeName}için kurgusal zamanlar',
    'workshop.fictionalTime.none': 'Şu anda hiçbir hayali zamanınız ayarlanmamış.',
    'workshop.fictionalTime.createNow': 'Şimdi bir tane oluşturun!',
    'workshop.fictionalTime.createTitle': 'Yeni bir hayali zaman oluştur',
    'workshop.fictionalTime.editTitle': 'Düzenle {ftName}',
    'workshop.fictionalTime.formDescription': `Burada kendi kurgusal zamanınızı oluşturabilirsiniz. Şu anda bu araç sınırlıdır ve yalnızca
        simetrik zamanlar oluşturabilmektedir. Bu, Maya takvimini veya Gregoryen takvimini yeniden yaratamayacağınız anlamına gelir. Şu anda
        bu araç tüm zaman dilimlerinin her zaman aynı olmasını beklemektedir; örneğin aylar istisnasız her zaman 30 gündür ve bu şekilde
        devam eder. Bunu daha sonraki sürümlerde ele alacağız, ancak o zamana kadar bu araç öncelikle
        sci-fi tabanlı zaman sistemleri oluşturmak için daha uygundur.`,
    'workshop.fictionalTime.timeName': 'Zaman adı',
    'workshop.fictionalTime.basicInfo': 'Temel bilgiler',
    'workshop.fictionalTime.timeSetup': 'Zaman ayarı',
    'workshop.fictionalTime.linkedToET': 'Bu zaman Gregoryen takvimine (Dünya tarihi) göre mi başlıyor?',
    'workshop.fictionalTime.timeDeclaration': 'Zaman beyanı',
    'workshop.fictionalTime.declarationLocation': 'Zaman adı nerede bildirilmelidir?',
    'workshop.fictionalTime.declarationBefore': 'Birimlerden önce',
    'workshop.fictionalTime.declarationAfter': 'Birimlerden sonra',
    'workshop.fictionalTime.declarationNone': 'Hiçbiri',
    'workshop.fictionalTime.units': 'Birimler',
    'workshop.fictionalTime.ETStart': 'Bu zamanın başlangıç tarihi',
    'workshop.fictionalTime.unitsDescFirst': 'Bu birimde kaç birim var (milisaniyeden)?',
    'workshop.fictionalTime.unitsDesc': 'Bu birim bir öncekine göre kaç birimdir?',
    'workshop.fictionalTime.unitsName': 'Birim adı',
    'workshop.fictionalTime.unitsSeparator': 'Önceki birimden ayırıcı',
    'workshop.fictionalTime.unitAdd': 'Birim ekle',
    'workshop.fictionalTime.clocks': 'Saatler',
    'workshop.fictionalTime.unitTransfer': 'Birimleri transfer et',
    'fictionalTime.pageStartElapsedTime': 'Bu sayfanın açılmasından bu yana geçen süre',
    'fictionalTime.currentTime': 'Geçerli zaman',
    'workshop.shoppingExternal.options': 'Harici satın alma seçenekleri',
    'workshop.shoppingExternal.explainer': 'Hikayeniz başka bir yerde satılıyorsa burada bağlantıları ayarlayabilirsiniz. Bağlantılar, içeriğin yerine veya önizlemeyi seçtiğiniz içeriğin sonunda gösterilecektir.',
    'workshop.shoppingExternal.amazonStore': 'Amazon mağazası',
    'workshop.shoppingExternal.amazon': 'Amazon',
    'workshop.shoppingExternal.storeName': 'Mağaza adı',
    'workshop.shoppingExternal.itemUrl': 'Ürün URL\'si',
    'workshop.shoppingExternal.storesOther': 'Diğer mağazalar',
    'fictionalTime.units.milliseconds': '{units, number} milisaniye',
    'fictionalTime.countdownToStart': 'Başlangıç zamanına geri sayım',
    'fictionalTime.unitsToETList': `{units, number} {unitName} = 
    {days, plural,
      =0 {}
      one {1 gün }
      other {{days} günler }
    }{hours, plural,
      =0 {00:}
      other {{hours}:}
    }{minutes, plural,
      =0 {00:}
      other {{minutes}:}
    }{seconds, plural,
      =0 {00}
      other {{seconds}}
    }
  `,
    'fictionalTime.ETToUnitsList': `{units, number} {unitType, select,
    seconds {{units, plural,
      one {saniye}
      other {saniye}
    }}
    minutes {{units, plural,
      one {dakika}
      other {dakika}
    }}
    hours {{units, plural,
      one {saat}
      other {saat}
    }}
    days {{units, plural,
      one {gün}
      other {gün}
    }}
    years {{units, plural,
      one {yıl}
      other {yıl}
    }}
    other {}
  } = {targetResult, number} {targetType}`,
    'fictionalTime.inputFrom': 'Başlangıç',
    'fictionalTime.inputSelectTimeUnit': 'Zaman birimini seçin',
    'fictionalTime.inputSelectETUnit': 'Dünya zaman birimini seçin',
    'fictionalTime.ETDateToTimeDate': '{date, date, medium} = {timeDate}',
    'workshop.writerSidebar.title': 'Kenar Çubuğu Araç Kutusu',
    'workshop.writerSidebar.description': 'Hikayenize hoş geldiniz! Bu kenar çubuğu, hikayenizle ilgili tüm kaynaklara kolay erişim sağlar. En son yorumları, notlarınızı ve çok daha fazlasını görmek için yukarıdaki simgeleri kontrol edin!',
    'workshop.story.authorsNotesExplained': 'Bölümün başında okuyucuların okuması için notlarınız.',
    'workshop.story.chapterSortSwitch': 'Bölümün sırasını değiştir',
    'workshop.story.prolog': 'Prolog',
    'workshop.story.chapter': 'Bölüm {sequence, number}',
    'workshop.work.includesAds': 'Çalışmada herhangi bir reklam veya ürün yerleştirme var mı?',
    'workshop.universe.forumSettings': 'İç evren forumu ayarları',
    'workshop.ratingAdjusted': 'Şikayetler nedeniyle değerlendirmenizi uygun gördüğümüz bir değere ayarlamak zorunda kaldık. Bu nedenle değerlendirmeyi değiştirmek artık devre dışı bırakılmıştır.',
    'workshop.rating.disabled.sexualContent': 'İçerik uyarılarında Cinsel İçerik seçtiğiniz için derecelendirme Açık (21+) olarak kilitlendi.',
    'workshop.contentWarnings.title': 'İçerik Uyarıları',
    'workshop.contentWarnings.description': 'Okuyucuları hassas olabilecek içerikler hakkında bilgilendirmek için geçerli içerik uyarılarını seçin',
    'workshop.contentWarnings.graphicViolence': 'Grafik Şiddet',
    'workshop.contentWarnings.graphicViolence.description': 'Fiziksel zarar, kan dökme, sakatlama veya rahatsız edici veya aşırı grafik olarak kabul edilebilecek diğer açık şiddet tasvirleri dahil ancak bunlarla sınırlı olmamak üzere şiddet eylemlerinin ayrıntılı açıklamaları.',
    'workshop.contentWarnings.profanity': 'Küfür',
    'workshop.contentWarnings.profanity.description': 'Aşırı veya müstehcen küfür ve sövme.',
    'workshop.contentWarnings.sensitiveContent': 'Hassas İçerik',
    'workshop.contentWarnings.sensitiveContent.description': 'İşkence, kölelik, madde bağımlılığı, akıl hastalığı, bağımlılık, tecavüz, kendine zarar verme veya uyarı etiketlerinin kapsamına girmeyen travmatize edici veya olgun sayılabilecek diğer içeriklerin tanımları. Bu içerik yüceltilmemiştir.',
    'workshop.contentWarnings.sexualContent': 'Cinsel İçerik',
    'workshop.contentWarnings.sexualContent.description': 'Açık cinsel içerik (sadece metin), açıklayıcı seks sahneleri. Bu, derecelendirmeyi otomatik olarak Açık (21+) olarak ayarlayacaktır.',
    'workshop.selectCollaborator': 'Ortak seç',
    'workshop.chapters.scheduledOn': '{publishDate, date, short} | {publishDate, time}',
    'workshop.chapterStatus.draft': 'Taslak',
    'workshop.chapterStatus.scheduled': 'Planlanan',
    'workshop.chapterStatus.published': 'Yayınlanan',
    'workshop.story.continuedIn': 'Bu hikayeye hangi hikayeler devam ediyor?',
    'workshop.story.continuedPlaceholder': 'Bu evrendeki hikayelerden birini seç',
    'workshop.universe.isAIGenerated': 'Evrenin içeriği yapay zeka tarafından mı üretiliyor?',
    'workshop.universe.isAIGeneratedTooltip': 'Lütfen evrenin içeriğinin yapay zeka tarafından veya yapay zekanın yardımıyla üretilip üretilmediğini bize bildirin. Bu bilgiyi uygun etiketleme için kullanıyoruz ve yapay zeka programlarının nasıl üretildiğine bağlı olarak bazı sınırlamalar ve kısıtlamalar olabilir.',
    'workshop.story.isAIGenerated': 'Hikaye yapay zeka tarafından mı üretiliyor?',
    'workshop.story.isAIGeneratedTooltip': 'Lütfen hikayenin içeriğinin yapay zeka tarafından veya yapay zekanın yardımıyla üretilip üretilmediğini bize bildirin. Bu bilgiyi uygun etiketleme için kullanıyoruz ve yapay zeka programlarının nasıl üretildiğine bağlı olarak bazı sınırlamalar ve kısıtlamalar olabilir.',
    'workshop.publicationAgreement.aria': 'Eser için yayın sözleşmesi',
    'workshop.publicationAgreement.intro': 'Yaratıcı eserinizi bizimle yayınlamayı seçtiğiniz için mutluyuz. İlerlemeden önce, hukuki yönünden ne anlama geldiğini anlamanız için yayın sözleşmemizi gözden geçirmenizi rica ediyoruz.',
    'workshop.sortChapters': 'Sıralama düzeni:',
    'workshop.sortChapters.ascending': 'Baştan itibaren',
    'workshop.sortChapters.descending': 'En yeniden',
    'workshop.sortChapters.aria': 'Bölüm listesini nasıl sıralayacağınızı seçin',
    'workshop.hiatus.btn': 'Hikaye durumunu Beklemede olarak değiştir',
    'workshop.cancelled.btn': 'Hikaye durumunu İptal Edildi olarak değiştir',
    'workshop.complete.btn': 'Hikaye durumunu Tamamlandı olarak değiştir',
    'workshop.statusChange.modalTop': 'Durumu değiştirmek istediğinizden emin misiniz',
    'workshop.statusName.hiatus': 'Beklemede',
    'workshop.statusName.cancelled': 'İptal Edildi',
    'workshop.statusName.completed': 'Tamamlandı',
    'workshop.statusExplain.hiatus1': 'Beklemede, bir süreliğine hikaye üzerinde çalışmaktan uzaklaştığınızı belirtir. Okuyucularınıza önümüzdeki haftalarda veya hatta birkaç ay boyunca yeni güncellemeler beklememeleri gerektiğini söyleyecektir.',
    'workshop.statusExplain.hiatus2': 'Bekleme durumu, herhangi bir bölüm yayımlamanız durumunda otomatik olarak kaldırılacaktır. Ya da kendiniz değiştirebilirsiniz.',
    'workshop.statusExplain.hiatus3': 'Hikayenizi altı ay boyunca beklemeye alırsanız, bu hikayeyi otomatik olarak iptal edeceğiz.',
    'workshop.statusExplain.cancelled1': 'Hikaye üzerinde çalışmaya devam edememenize üzüldük. Öte yandan, okuyucularınıza bildirmek istediğiniz için mutluyuz.',
    'workshop.statusExplain.cancelled2': 'Hikayeyi iptal etmek, okuyucularınıza yeni güncellemeler beklememeleri gerektiğini bildirecektir.',
    'workshop.statusExplain.cancelled3': 'Her zaman bir bölüm yayımlayarak veya durumu değiştirerek bunu geri alabilirsiniz.',
    'workshop.statusExplain.finished1': 'Tebrikler! Tüm o zor çalışmanın ardından inanılmaz bir yolculuğun sonuna nihayet ulaştınız. Hikaye şimdi sona erse de, umarız gelecekte anlatılacak daha fazla hikaye olur, ama şimdilik dinlenin ve iyi kazanılmış dinlenmenin tadını çıkarın.',
    'workshop.statusExplain.finished2': 'Hikayeyi tamamlandı olarak işaretlemek, okuyuculara hikayenin bittiğini söyleyecektir. Yeni bölümler eklememelisiniz, ancak ekstra bölümler eklemek kötü bir fikir değildir, örneğin tüm karakterler için daha fazla epilog eklemek gibi.',
    'workshop.statusExplain.finished3': 'Bu durumu her zaman iptal edebilirsiniz, ancak bunu kesinlikle önermiyoruz. Hikaye devam edecekse, yeni bir hikaye başlatmak daha iyi olabilir.',
    'workshop.status.goActive': 'Hikayeyi tekrar etkin hale getir',
    'workshop.statusChangeEmail.storyIntro': 'Hikayeniz hakkında sizi bilgilendirmek istiyoruz:',
    'workshop.statusChangeEmail.hiatusTitle': 'Hikaye durumunuz otomatik olarak araya alındı',
    'workshop.statusChangeEmail.hiatusIntro': 'Hareketsizlik nedeniyle hikaye durumunuz otomatik olarak araya alındı.',
    'workshop.statusChangeEmail.hiatusWhy': '6 aydan fazla süredir yeni bir bölüm yayınlanmadığı için otomatik olarak araya alındı.',
    'workshop.statusChangeEmail.hiatusWhatFollows': 'Bu durum, yeni bir bölüm yayınlamanız halinde otomatik olarak kaldırılacaktır. Eğer önümüzdeki 6 ay içinde yeni bir bölüm yayınlamazsanız, hikayeyi otomatik olarak iptal edeceğiz.',
    'workshop.statusChangeEmail.cancellationIntro': 'Hikaye durumunuz otomatik olarak iptal edildi.',
    'workshop.statusChangeEmail.cancellationWhy': 'Bu, 6 ay önce ara verildiğinden beri hikayeye yeni bir bölüm göndermediğiniz için oldu. Bir yıllık hareketsizlikten sonra, okuyucuların hangi hikayelerin aktif olduğunu bilmeleri için hikayeleri otomatik olarak iptal edildi olarak ayarlıyoruz.',
    'workshop.statusChangeEmail.cancellationWhatFollows': 'Bu durum, yeni bir bölüm yayınlamanız halinde otomatik olarak kaldırılacaktır. Eğer bu hikaye üzerinde çalışmayı planlamıyorsanız, yapmanız gereken başka bir şey yoktur.',
    'workshop.startCreating': 'Oluşturmaya başlayın',
    'workshop.ownWork': 'Kendi çalışmam',
    'workshop.list.thumbs': 'Küçük resim listesi',
    'workshop.list.list': 'Kısa liste',
    'workshop.fanfiction.new': 'Yeni bir hayran kurgusu oluşturun',
    'workshop.videoTrailerLink': 'Video fragmanı bağlantısı',
    'workshop.videoTrailerPlayerTitle': 'Hikaye video fragmanı oynatıcı',
    'workshop.videoTrailer.supportedPlaftorms': 'Youtube, Vimeo ve Odysee\'yi destekliyoruz',
    'workshop.videoTrailer.rumble': 'Rumble\'u da destekliyoruz, ancak IFRAME URL\'sini kopyalamayı unutmayın.',
    'workshop.videoTrailer.suggestPlatforms': 'Video platformunuz eksik mi, bize <a>geri bildirim</a> yoluyla bildirin!',
    'workshop.cover.edit': 'Kapağı değiştirin',
    'workshop.collaborator.leave': 'Projeden ayrılın',
    'workshop.collaborator.leaveTitle': 'Lütfen {workName}adresinden ayrılmak istediğinizi onaylayın.',
    'workshop.collaborator.leaveExplained': 'Projeden ayrılmak, tüm erişim, ilişkilendirme ve ayrıcalıkları kaybedeceğiniz anlamına gelecektir. Tüm bunların ne anlama geldiğinden emin değilseniz, muhtemelen tıklamak istediğiniz şey bu değildir.',
    'workshop.collaborators.leftInfo': 'Sol açık {date, date}',
    'workshop.collaborators.removedInfo': 'Kaldırıldı {date, date}',
    'workshop.aiGeneratedAdjusted': 'Bu içeriğin AI oluşturma durumu, bir kullanıcı raporunun sonucu olarak bir yönetici tarafından ayarlanmıştır ve değiştirilemez.',
    'workshop.theWay.authorProgress': 'Yazar İlerleme',
    'workshop.universe.preventPublishing': 'Hikayelerin yayınlanmasını önleyin',
    'workshop.universe.preventPublishingTooltip': 'Etkinleştirildiğinde, bu evrendeki hiçbir hikaye yayınlanamaz. Bu, hala geliştirilmekte olan evrenler veya yalnızca özel kullanım amaçlı evrenler için kullanışlıdır.',
    'workshop.story.preventPublishing': 'Yayınlamayı önleyin',
    'workshop.story.preventPublishingTooltip': 'Etkinleştirildiğinde, bu hikaye yayınlanamaz. Bu, hala geliştirme aşamasında olan veya yalnızca özel kullanım amaçlı hikayeler için kullanışlıdır.',
    'workshop.story.preventPublishingTooltipUniverse': 'Evrende yayınlamayı engelle ayarı etkinleştirilmiş olduğundan yayınlama engellenir.',
    'workshop.story.showChapterNumbersInListing': 'Bölüm listesinde bölüm numaralarını göster',
    'workshop.story.showChapterNumbersInListingTooltip': 'Etkinleştirildiğinde, bölüm numaraları hikaye bölüm listelerinde okuyucular tarafından görülebilir.',
    'workshop.revisions.new.public.disabled': 'Öykü ayarlarında yayınlamayı engelle etkinleştirildiğinde yayınlanamıyor.',
    'workshop.publishing.restricted': 'İyi hal ihlali nedeniyle yayınlama yeteneğinizi devre dışı bıraktık.',
    'workshop.story.buyingSettings': 'Satış ayarları',
    'workshop.story.delete.modalAria': 'Bir hikayeyi silmek için onay modalı',
    'workshop.story.delete.warning': '"{title}" adresini silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'workshop.story.delete.button': 'Hikayeyi Sil',
    'workshop.story.private.universeExplain': 'Bu hikaye özeldir çünkü evreni özeldir.',
    'workshop.story.makePublicWithUniverse.button': 'Hikayeyi ve Evreni Herkese Açık Hale Getirin',
    'workshop.universe.makePublic.only.button': 'Evreni Yalnızca Herkese Açık Yapın',
    'workshop.universe.makePublic.only.modalAria': 'Bir evreni yalnızca herkese açık hale getirmek için onaylama modu',
    'workshop.universe.makePublic.only.warning': 'Bu sadece evreni kamuya açık hale getirir. Bu evrendeki hikayeler tek tek herkese açık hale getirilinceye kadar gizli kalır.',
    'workshop.universe.makePublic.withStories.button': 'Evreni ve Tüm Hikayeleri Herkese Açık Yapın',
    'workshop.universe.makePublic.withStories.modalAria': 'Bir evreni ve tüm hikayeleri herkese açık hale getirmek için onaylama modu',
    'workshop.universe.makePublic.withStories.warning': 'Bu, evreni ve bağlantılı tüm hikayeleri halka açık hale getirir.',
    // Chapter deletion
    'workshop.chapter.delete.modalAria': 'Bir bölümü silmek için onay modalı',
    'workshop.chapter.delete.warning': '"{title}" adresini silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'workshop.chapter.delete.button': 'Bölüm Silme',
    'workshop.chapter.delete.deleting': 'Siliniyor...',
    // AI Content Marking
    'workshop.chapter.aiGenerated': 'Yapay Zeka Tarafından Oluşturulan İçerik',
    'workshop.chapter.aiGenerated.tooltip': 'Bu bölümü yapay zeka tarafından oluşturulmuş içerik içeriyor olarak işaretleyin',
    'workshop.chapter.aiGenerated.description': 'Bu bölüm, yapay zeka yardımıyla oluşturulmuş içerik içermektedir.',
    'workshop.chapter.aiModel': 'Yapay Zeka Modeli',
    'workshop.chapter.aiModel.tooltip': 'İçerik oluşturmak için kullanılan yapay zeka modelini seçin',
    'workshop.chapter.aiModel.custom': 'Özel',
    'workshop.chapter.aiModel.custom.placeholder': 'Yapay zeka modelinin adını girin',
    'workshop.chapter.aiGenerated.locked': 'AI içerik işaretlemesi, moderasyon ekibi tarafından ayarlandığı için değiştirilemez.',
    'workshop.monetization.aiNotEligible': 'Yapay zeka tarafından oluşturulan içerik para kazanma için uygun değildir.',
    'workshop.timer.settings': 'Timer Settings',
    'workshop.timer': 'Timer',
    'workshop.timer.type': 'Type',
    'workshop.timer.timer': 'Timer',
    'workshop.timer.countdown': 'Countdown',
    'workshop.timer.pomodoro': 'Pomodoro',
    'workshop.timer.mode': 'Mode',
    'workshop.timer.regular': 'Regular',
    'workshop.timer.improved': 'Improved',
    'workshop.timer.duration': 'Duration (min)',
    'workshop.timer.workDuration': 'Work (min)',
    'workshop.timer.breakDuration': 'Break (min)',
    'workshop.timer.breakType': 'Break Type',
    'workshop.timer.softBreak': 'Soft Break',
    'workshop.timer.hardBreak': 'Hard Break',
    'workshop.timer.break': 'Break',
    'workshop.timer.breakTime': 'Break Time!',
    'workshop.timer.breakMessage': 'Take a moment to rest. Click anywhere to dismiss.',
    'workshop.timer.pause': 'Pause',
    'workshop.timer.resume': 'Resume',
    'workshop.timer.stop': 'Stop',
    'workshop.timer.start': 'Start',
    'workshop.timer.tabInactive': 'Timer paused - switch back to tab to continue',
    // Timer descriptions
    'workshop.timer.type.timer.desc': 'Simple stopwatch that starts at 0:00 and counts upward. Perfect for tracking total writing time in a session or seeing how long you\'ve been working continuously. Never ends automatically - you control when to stop.',
    'workshop.timer.type.countdown.desc': 'Countdown timer that starts from your set duration and counts down to zero. Great for time-boxed writing sessions, word sprints, or when you want to work for a specific amount of time before taking a break.',
    'workshop.timer.type.pomodoro.desc': 'Structured productivity technique: 25-minute focused work sessions alternating with 5-minute breaks. After 4 cycles, takes a longer 15-30 minute break. Scientifically proven to improve focus and prevent burnout.',
    'workshop.timer.mode.regular.desc': 'Timer runs continuously regardless of your activity. Best for disciplined writers who want to track time even when researching, editing, or taking short breaks. Timer keeps going when you switch tabs or stop typing.',
    'workshop.timer.mode.improved.desc': 'Smart timer that automatically pauses when you switch browser tabs. Perfect for focused writing sessions where you want accurate tracking of actual writing time, not total time spent on the page.',
    'workshop.timer.breakType.soft.desc': 'Gentle reminder approach: Shows a small notification when break time starts. You can choose to continue working if you\'re in \'the zone\' or take the break. Good for flexible writers who sometimes need to extend productive sessions.',
    'workshop.timer.breakType.hard.desc': 'Strict enforcement: Displays a full-screen modal that prevents further input until the break timer completes. Forces you to step away from the keyboard. Ideal for writers who struggle with self-discipline or workaholics who need enforced rest periods.',
    'workshop.timer.duration.timer.desc': 'How long you plan to write in this session. Start with 25-50 minutes for focused work, or set longer sessions (2-4 hours) for deep writing days.',
    'workshop.timer.duration.countdown.desc': 'Target writing time before the timer ends. Try 25 minutes for focused sprints, 45-60 minutes for substantial work sessions, or 90 minutes for creative deep dives.',
    'workshop.timer.workDuration.desc': 'Length of focused work sessions. Traditional Pomodoro uses 25 minutes. Try 15-20 minutes if you find it hard to concentrate for longer periods, or 45-50 minutes for experienced writers who can maintain deep focus.',
    'workshop.timer.breakDuration.desc': 'Rest period between work sessions. Standard is 5 minutes for short breaks. Use 10-15 minutes for longer breaks that allow you to step away from your desk, stretch, or get a drink. Every 4th break is automatically longer (2-3x duration).',
    'workshop.llmstxt': 'AI Access',
    'workshop.llmstxt.blocked': 'Blocked - LLMs cannot access your content',
    'workshop.llmstxt.limited': 'Sınırlı - LLM\'ler yalnızca meta verilere erişebilir',
    'workshop.llmstxt.free': 'Free - LLMs can access your content for free',
    'workshop.llmstxt.paid': 'Paid - LLMs can access your content for a fee (coming soon)',
    'workshop.ai.llmstxt.generate': 'Generate LLMs.txt',
    'workshop.ai.llmstxt.generating': 'Generating LLMs.txt...',
    'workshop.ai.llmstxt.download': 'Download LLMs.txt',
    'workshop.ai.llmstxt.title': 'Texts for AI services',
    'workshop.ai.agent.title': 'Assistant',
    'workshop.ai.llmstxt.story-info': 'Story Info LLMs.txt',
    'workshop.ai.llmstxt.full-content': 'Full Content LLMs.txt',
    'workshop.ai.llmstxt.info': 'Info LLMs.txt - Basic information for AI',
    'workshop.ai.llmstxt.infoShort': 'Basic information',
    'workshop.ai.llmstxt.full': 'Content LLMs.txt - Full content for AI',
    'workshop.ai.llmstxt.fullShort': 'Full content'
};