export default {
    'writer.menu.optionsAria': 'Düzenleyici seçenekleri menüsü',
    'writer.menu.saveOptionsAria': 'Kaydetme seçenekleri',
    'writer.undo': 'Geri al',
    'writer.redo': 'Yinele',
    'writer.ul': 'Sırasız liste',
    'writer.ol': 'Sıralı liste',
    'writer.blockquote': 'Alıntı',
    'writer.link': 'Bir bağlantı ekle',
    'writer.image': 'Bir resim ekle',
    'writer.bold': 'Seçimi kalın yap',
    'writer.underline': 'Seçimi altı çizili yap',
    'writer.italic': 'Seçimi vurgula',
    'writer.wordcount': '{characters, number} karakter, {words, number} kelime',
    'finder.details': 'detaylar',
    'finder.remove': 'bağlantıyı kaldır',
    'finder.connect': 'Seçimi ansiklopedi girişiyle bağla',
    'writer.aside.ariaLabel': 'Yardım seçenekleri menüsü',
    'writer.nothingToSave': 'Kaydedilecek bir şey yok',
    'writer.publish.publishAria': 'Yayın seçenekleri',
    'writer.publish.scheduleExplained': 'Hemen yayımlayabilir veya bölümü daha sonra kullanılmak üzere planlayabilirsiniz.',
    'writer.publish.schedule': 'Yayımlanma tarih saatini ayarla',
    'writer.publish.previousChapterPublished': 'Önceki bölüm {publishDate, date, short} tarihinde {publishDate, time}yayımlandı',
    'writer.publish.previousChapterScheduled': 'Önceki bölüm {publishDate, date, short} tarihinde {publishDate, time}yayımlanması planlandı',
    'writer.publish.alreadyPublished': 'Bu bölüm zaten {publishedAt, date, short}tarihinde yayımlandı. Yeni sürümler hemen yayımlanacak.',
    'writer.publish.betaReader': 'Beta',
    'writer.publish.public': 'Yayınla'
};